import type { ListeningFlowLessonContent } from "@/lib/listening/tactics-basic-flow-types";

/** Unit 4 — Listening 1 (Daily Routines / telling time). */
export const DAILY_ROUTINES_TIME_CONTENT: ListeningFlowLessonContent = {
  predictionOptions: [
    { key: "time", labelEn: "Asking what time it is", labelVi: "Hỏi mấy giờ rồi" },
    { key: "late", labelEn: "Being late for class or work", labelVi: "Đi học hoặc đi làm trễ" },
    { key: "dates", labelEn: "Birthdays and holidays", labelVi: "Sinh nhật và ngày lễ" },
    { key: "food", labelEn: "Ordering breakfast", labelVi: "Gọi món sáng" },
  ],
  gistOptions: [
    {
      key: "tell-time",
      labelEn: "People ask for the time and hear different clock times",
      labelVi: "Mọi người hỏi giờ và nghe các mốc thời gian khác nhau",
      correct: true,
    },
    {
      key: "schedules",
      labelEn: "Short exchanges about being late or on time",
      labelVi: "Trao đổi ngắn về trễ giờ hoặc đúng giờ",
      correct: true,
    },
    { key: "weather", labelEn: "Weather forecasts", labelVi: "Dự báo thời tiết" },
    { key: "travel", labelEn: "Flight departure times", labelVi: "Giờ bay của chuyến bay" },
  ],
  detailQuestions: [
    {
      key: "q1",
      conversationEn: "Conversation 1",
      conversationVi: "Hội thoại 1",
      questionEn: "What time is it?",
      questionVi: "Mấy giờ rồi?",
      answerEn: "10:15.",
      answerVi: "10 giờ 15.",
    },
    {
      key: "q2",
      conversationEn: "Conversation 2",
      conversationVi: "Hội thoại 2",
      questionEn: "What time is it?",
      questionVi: "Mấy giờ rồi?",
      answerEn: "10 after 2 (2:10).",
      answerVi: "10 phút qua 2 giờ (2:10).",
    },
    {
      key: "q3",
      conversationEn: "Conversation 3",
      conversationVi: "Hội thoại 3",
      questionEn: "What time is it?",
      questionVi: "Mấy giờ rồi?",
      answerEn: "Exactly 12 o'clock — midnight, Happy New Year.",
      answerVi: "Đúng 12 giờ — nửa đêm, Chúc mừng năm mới.",
    },
    {
      key: "q4",
      conversationEn: "Conversation 4",
      conversationVi: "Hội thoại 4",
      questionEn: "What time is it? Why is the speaker surprised?",
      questionVi: "Mấy giờ? Vì sao người nói ngạc nhiên?",
      answerEn: "11:30. He says “Wow, I'm late.”",
      answerVi: "11:30. Anh ấy nói “Wow, I'm late.” (Trời, mình trễ rồi.)",
    },
    {
      key: "q5",
      conversationEn: "Conversation 5",
      conversationVi: "Hội thoại 5",
      questionEn: "What time is it?",
      questionVi: "Mấy giờ rồi?",
      answerEn: "A quarter to four (3:45).",
      answerVi: "Kém 15 phút 4 giờ (3:45).",
    },
    {
      key: "q6",
      conversationEn: "Conversation 6",
      conversationVi: "Hội thoại 6",
      questionEn: "What time is it? When does class start?",
      questionVi: "Mấy giờ? Lớp bắt đầu lúc mấy giờ?",
      answerEn: "7:50. Class starts at 8 — only 10 minutes left.",
      answerVi: "7:50. Lớp bắt đầu lúc 8 — chỉ còn 10 phút.",
    },
  ],
  memoryPlaceholder: "…",
};

/** Unit 4 — Listening 2 (Times and Schedules / sleep habits). */
export const TIMES_AND_SCHEDULES_CONTENT: ListeningFlowLessonContent = {
  predictionOptions: [
    { key: "sleep", labelEn: "When people go to bed and get up", labelVi: "Giờ đi ngủ và thức dậy" },
    { key: "morning-night", labelEn: "Morning people vs night people", labelVi: "Người buổi sáng vs buổi tối" },
    { key: "work-shift", labelEn: "Night shift at work", labelVi: "Ca đêm ở công việc" },
    { key: "movies", labelEn: "Movie show times", labelVi: "Giờ chiếu phim" },
  ],
  gistOptions: [
    {
      key: "sleep-schedules",
      labelEn: "Different sleep and wake-up schedules",
      labelVi: "Các lịch ngủ và thức dậy khác nhau",
      correct: true,
    },
    {
      key: "early-late",
      labelEn: "Some go to bed early, others stay up late",
      labelVi: "Có người ngủ sớm, có người thức khuya",
      correct: true,
    },
    { key: "exercise", labelEn: "Exercise and gym schedules", labelVi: "Lịch tập thể dục và gym" },
    { key: "meals", labelEn: "Cooking and meal times", labelVi: "Nấu ăn và giờ ăn" },
  ],
  detailQuestions: [
    {
      key: "q1",
      conversationEn: "Conversation 1",
      conversationVi: "Hội thoại 1",
      questionEn: "What time does she go to bed? Why so early?",
      questionVi: "Cô ấy đi ngủ lúc mấy giờ? Vì sao sớm vậy?",
      answerEn: "8:30 — she gets up at 5 a.m. to study before school.",
      answerVi: "8:30 — cô ấy dậy lúc 5 giờ sáng để học trước khi đi học.",
    },
    {
      key: "q2",
      conversationEn: "Conversation 2",
      conversationVi: "Hội thoại 2",
      questionEn: "When does John go to bed and get up?",
      questionVi: "John đi ngủ và dậy lúc mấy giờ?",
      answerEn: "Bed around midnight; up at 6:15 for work.",
      answerVi: "Ngủ khoảng nửa đêm; dậy 6:15 đi làm.",
    },
    {
      key: "q3",
      conversationEn: "Conversation 3",
      conversationVi: "Hội thoại 3",
      questionEn: "What time does Sam get up? When does he stay up until?",
      questionVi: "Sam dậy lúc mấy giờ? Thức đến mấy giờ?",
      answerEn: "Gets up around 9:30; stays up until about 3 a.m.",
      answerVi: "Dậy khoảng 9:30; thức đến khoảng 3 giờ sáng.",
    },
    {
      key: "q4",
      conversationEn: "Conversation 4",
      conversationVi: "Hội thoại 4",
      questionEn: "Is Grace a morning or night person?",
      questionVi: "Grace là người buổi sáng hay buổi tối?",
      answerEn: "Night person — bed around 1 a.m., up at a quarter to 8.",
      answerVi: "Buổi tối — ngủ khoảng 1 giờ sáng, dậy kém 15 phút 8 giờ.",
    },
    {
      key: "q5",
      conversationEn: "Conversation 5",
      conversationVi: "Hội thoại 5",
      questionEn: "When does Mia go to bed? Why?",
      questionVi: "Mia đi ngủ lúc mấy giờ? Vì sao?",
      answerEn: "Around 10 — she gets up at 6 a.m. for work.",
      answerVi: "Khoảng 10 giờ — cô ấy dậy 6 giờ sáng đi làm.",
    },
    {
      key: "q6",
      conversationEn: "Conversation 6",
      conversationVi: "Hội thoại 6",
      questionEn: "When does James sleep (night shift)?",
      questionVi: "James ngủ lúc nào (ca đêm)?",
      answerEn: "Bed at 8 a.m., sleeps all day, up at 4 p.m.",
      answerVi: "Ngủ lúc 8 giờ sáng, ngủ cả ngày, dậy 4 giờ chiều.",
    },
  ],
  memoryPlaceholder: "…",
};

/** Unit 4 — Listening 3 (Activities and Habits / daily routines). */
export const ACTIVITIES_AND_HABITS_CONTENT: ListeningFlowLessonContent = {
  predictionOptions: [
    { key: "daily-routine", labelEn: "A typical day from morning to night", labelVi: "Một ngày điển hình từ sáng đến tối" },
    { key: "commute", labelEn: "Commuting to work or school", labelVi: "Đi làm hoặc đi học" },
    { key: "job-hunt", labelEn: "Looking for a job", labelVi: "Tìm việc làm" },
    { key: "vacation", labelEn: "Planning a vacation", labelVi: "Lên kế hoạch nghỉ phép" },
  ],
  gistOptions: [
    {
      key: "three-routines",
      labelEn: "Three people describe their daily routines",
      labelVi: "Ba người mô tả thói quen hàng ngày",
      correct: true,
    },
    {
      key: "work-study",
      labelEn: "Work, study, meals, and free time in order",
      labelVi: "Công việc, học, ăn và giờ rảnh theo thứ tự",
      correct: true,
    },
    { key: "sports-only", labelEn: "Only sports and exercise", labelVi: "Chỉ thể thao và tập luyện" },
    { key: "shopping", labelEn: "Shopping at the mall", labelVi: "Mua sắm ở trung tâm thương mại" },
  ],
  detailQuestions: [
    {
      key: "q1",
      conversationEn: "Conversation 1",
      conversationVi: "Hội thoại 1",
      questionEn: "What time does the first speaker get up? When does he get to work?",
      questionVi: "Người thứ nhất dậy lúc mấy giờ? Đến chỗ làm lúc mấy giờ?",
      answerEn: "Up at 5:15, running, then subway; at work by 7 a.m., works until 8 p.m.",
      answerVi: "Dậy 5:15, chạy bộ, rồi đi tàu điện ngầm; đến làm 7 giờ sáng, làm đến 8 giờ tối.",
    },
    {
      key: "q2",
      conversationEn: "Conversation 2",
      conversationVi: "Hội thoại 2",
      questionEn: "What does Amelia do on the bus? When are her classes?",
      questionVi: "Amelia làm gì trên xe buýt? Lớp học lúc mấy giờ?",
      answerEn: "Texts friends on the bus; classes 9 until 3.",
      answerVi: "Nhắn tin bạn trên xe buýt; học từ 9 đến 3 giờ.",
    },
    {
      key: "q3",
      conversationEn: "Conversation 3",
      conversationVi: "Hội thoại 3",
      questionEn: "Why doesn't Charlie have much routine? When does he get up?",
      questionVi: "Vì sao Charlie không có lịch cố định? Dậy lúc mấy giờ?",
      answerEn: "Looking for a job; usually gets up around 11.",
      answerVi: "Đang tìm việc; thường dậy khoảng 11 giờ.",
    },
  ],
  memoryPlaceholder: "…",
};

/** Unit 5 — Listening 1 (Days and Months / travel dates). */
export const DAYS_AND_MONTHS_CONTENT: ListeningFlowLessonContent = {
  predictionOptions: [
    { key: "arrive-leave", labelEn: "Arrival and departure dates", labelVi: "Ngày đến và ngày đi" },
    { key: "vacation-length", labelEn: "How long someone is staying", labelVi: "Ở lại bao lâu" },
    { key: "appointments", labelEn: "Doctor or dentist appointments", labelVi: "Lịch hẹn bác sĩ hoặc nha sĩ" },
    { key: "shopping", labelEn: "Store opening hours", labelVi: "Giờ mở cửa hàng" },
  ],
  gistOptions: [
    {
      key: "travel-dates",
      labelEn: "People say when they arrived and when they leave",
      labelVi: "Mọi người nói ngày đến và ngày rời đi",
      correct: true,
    },
    {
      key: "short-stays",
      labelEn: "Short vacation stays with specific dates",
      labelVi: "Kỳ nghỉ ngắn với ngày cụ thể",
      correct: true,
    },
    { key: "birthdays", labelEn: "Birthday parties only", labelVi: "Chỉ tiệc sinh nhật" },
    { key: "work", labelEn: "Work deadlines and projects", labelVi: "Deadline và dự án công việc" },
  ],
  detailQuestions: [
    {
      key: "q1",
      conversationEn: "Conversation 1",
      conversationVi: "Hội thoại 1",
      questionEn: "When did they arrive? When do they leave?",
      questionVi: "Họ đến khi nào? Rời đi khi nào?",
      answerEn: "Arrived on the 1st; leave on the 14th (two weeks).",
      answerVi: "Đến ngày 1; đi ngày 14 (hai tuần).",
    },
    {
      key: "q2",
      conversationEn: "Conversation 2",
      conversationVi: "Hội thoại 2",
      questionEn: "When did he arrive? When does he leave?",
      questionVi: "Anh ấy đến khi nào? Đi khi nào?",
      answerEn: "Arrived on the 4th; until the 13th.",
      answerVi: "Đến ngày 4; ở đến ngày 13.",
    },
    {
      key: "q3",
      conversationEn: "Conversation 3",
      conversationVi: "Hội thoại 3",
      questionEn: "When did she arrive? When does she leave?",
      questionVi: "Cô ấy đến khi nào? Đi khi nào?",
      answerEn: "July 2nd; leaves on the 10th.",
      answerVi: "2 tháng 7; đi ngày 10.",
    },
    {
      key: "q4",
      conversationEn: "Conversation 4",
      conversationVi: "Hội thoại 4",
      questionEn: "When did they arrive? How long are they staying?",
      questionVi: "Họ đến khi nào? Ở bao lâu?",
      answerEn: "Got in on the 5th; leaving on the 15th (10 days).",
      answerVi: "Đến ngày 5; đi ngày 15 (10 ngày).",
    },
    {
      key: "q5",
      conversationEn: "Conversation 5",
      conversationVi: "Hội thoại 5",
      questionEn: "When did they arrive? When do they leave?",
      questionVi: "Họ đến khi nào? Rời khi nào?",
      answerEn: "Got here on the 3rd; not leaving until the 31st.",
      answerVi: "Đến ngày 3; không đi cho đến ngày 31.",
    },
    {
      key: "q6",
      conversationEn: "Conversation 6",
      conversationVi: "Hội thoại 6",
      questionEn: "When did they arrive? When are they leaving?",
      questionVi: "Họ đến khi nào? Rời khi nào?",
      answerEn: "On the 6th; leaving on the 16th.",
      answerVi: "Ngày 6; đi ngày 16.",
    },
  ],
  memoryPlaceholder: "…",
};

/** Unit 5 — Listening 2 (Making Plans / phone messages). */
export const MAKING_PLANS_CONTENT: ListeningFlowLessonContent = {
  predictionOptions: [
    { key: "messages", labelEn: "Phone messages about dates and times", labelVi: "Tin nhắn điện thoại về ngày giờ" },
    { key: "appointments", labelEn: "Changing appointments", labelVi: "Đổi lịch hẹn" },
    { key: "parties", labelEn: "Birthday parties and social plans", labelVi: "Tiệc sinh nhật và kế hoạch gặp gỡ" },
    { key: "weather", labelEn: "Weather reports", labelVi: "Bản tin thời tiết" },
  ],
  gistOptions: [
    {
      key: "scheduled-events",
      labelEn: "Messages about appointments, parties, flights, and meetings",
      labelVi: "Tin nhắn về lịch hẹn, tiệc, chuyến bay và cuộc gặp",
      correct: true,
    },
    {
      key: "specific-dates",
      labelEn: "Specific dates and times for plans",
      labelVi: "Ngày giờ cụ thể cho kế hoạch",
      correct: true,
    },
    { key: "gossip", labelEn: "Celebrity gossip news", labelVi: "Tin đồn người nổi tiếng" },
    { key: "shopping", labelEn: "Online shopping deliveries", labelVi: "Giao hàng mua online" },
  ],
  detailQuestions: [
    {
      key: "q1",
      conversationEn: "Conversation 1",
      conversationVi: "Hội thoại 1",
      questionEn: "When is the new dental appointment?",
      questionVi: "Lịch nha khoa mới là khi nào?",
      answerEn: "August 3rd at 9:30 in the morning.",
      answerVi: "3 tháng 8 lúc 9:30 sáng.",
    },
    {
      key: "q2",
      conversationEn: "Conversation 2",
      conversationVi: "Hội thoại 2",
      questionEn: "When is Nicole's birthday party?",
      questionVi: "Tiệc sinh nhật Nicole là khi nào?",
      answerEn: "July 28th at 8 p.m.",
      answerVi: "28 tháng 7 lúc 8 giờ tối.",
    },
    {
      key: "q3",
      conversationEn: "Conversation 3",
      conversationVi: "Hội thoại 3",
      questionEn: "When does Aunt Betty arrive?",
      questionVi: "Dì Betty đến khi nào?",
      answerEn: "August 10th at 11:15 in the morning.",
      answerVi: "10 tháng 8 lúc 11:15 sáng.",
    },
    {
      key: "q4",
      conversationEn: "Conversation 4",
      conversationVi: "Hội thoại 4",
      questionEn: "When can they play tennis instead?",
      questionVi: "Khi nào có thể chơi tennis thay thế?",
      answerEn: "Sunday afternoon, July 26th around 3.",
      answerVi: "Chiều Chủ nhật, 26 tháng 7 khoảng 3 giờ.",
    },
    {
      key: "q5",
      conversationEn: "Conversation 5",
      conversationVi: "Hội thoại 5",
      questionEn: "When does Sam return? When do they plan to meet?",
      questionVi: "Sam về khi nào? Họ hẹn gặp lúc nào?",
      answerEn: "Back Tuesday, September 22nd; meet in his office around 6 p.m.",
      answerVi: "Về thứ Ba, 22 tháng 9; gặp ở văn phòng khoảng 6 giờ tối.",
    },
    {
      key: "q6",
      conversationEn: "Conversation 6",
      conversationVi: "Hội thoại 6",
      questionEn: "When is the flight to New Orleans?",
      questionVi: "Chuyến bay đi New Orleans là khi nào?",
      answerEn: "August 2nd, Flight 101 from Kennedy at 2 p.m.",
      answerVi: "2 tháng 8, chuyến 101 từ Kennedy lúc 2 giờ chiều.",
    },
  ],
  memoryPlaceholder: "…",
};

/** Unit 5 — Listening 3 (Special Dates / birthdays). */
export const SPECIAL_DATES_CONTENT: ListeningFlowLessonContent = {
  predictionOptions: [
    { key: "birthdays", labelEn: "Birthdays — past, present, and future", labelVi: "Sinh nhật — đã qua, sắp tới và tương lai" },
    { key: "parties", labelEn: "Birthday parties and celebrations", labelVi: "Tiệc sinh nhật và lễ kỷ niệm" },
    { key: "exams", labelEn: "School exams", labelVi: "Kỳ thi ở trường" },
    { key: "holidays", labelEn: "Public holidays only", labelVi: "Chỉ ngày lễ công cộng" },
  ],
  gistOptions: [
    {
      key: "when-birthday",
      labelEn: "Friends talk about when their birthdays are or were",
      labelVi: "Bạn bè nói sinh nhật của mình đã qua hay sắp tới",
      correct: true,
    },
    {
      key: "plans",
      labelEn: "Plans for celebrating or quiet birthdays",
      labelVi: "Kế hoạch ăn mừng hoặc sinh nhật đơn giản",
      correct: true,
    },
    { key: "gifts", labelEn: "Buying and wrapping gifts", labelVi: "Mua và gói quà" },
    { key: "travel", labelEn: "Booking flights", labelVi: "Đặt vé máy bay" },
  ],
  detailQuestions: [
    {
      key: "q1",
      conversationEn: "Conversation 1",
      conversationVi: "Hội thoại 1",
      questionEn: "When was Henry's birthday? What did he do?",
      questionVi: "Sinh nhật Henry khi nào? Anh ấy làm gì?",
      answerEn: "A month ago; had to study for school exams (no big party).",
      answerVi: "Một tháng trước; phải học vì kỳ thi (không tiệc lớn).",
    },
    {
      key: "q2",
      conversationEn: "Conversation 2",
      conversationVi: "Hội thoại 2",
      questionEn: "When is Eva's birthday? What is she planning?",
      questionVi: "Sinh nhật Eva khi nào? Cô ấy định làm gì?",
      answerEn: "In two months; going to New York with her parents.",
      answerVi: "Còn hai tháng nữa; đi New York với bố mẹ.",
    },
    {
      key: "q3",
      conversationEn: "Conversation 3",
      conversationVi: "Hội thoại 3",
      questionEn: "When is Julia's birthday? What is she planning?",
      questionVi: "Sinh nhật Julia khi nào? Cô ấy định làm gì?",
      answerEn: "Next month; planning a barbecue.",
      answerVi: "Tháng tới; định tổ chức tiệc nướng BBQ.",
    },
    {
      key: "q4",
      conversationEn: "Conversation 4",
      conversationVi: "Hội thoại 4",
      questionEn: "When was Luke's birthday? How was it?",
      questionVi: "Sinh nhật Luke khi nào? Thế nào?",
      answerEn: "A month ago; quiet family party at home.",
      answerVi: "Một tháng trước; tiệc gia đình nhỏ ở nhà.",
    },
  ],
  memoryPlaceholder: "…",
};

export const TACTICS_BASIC_FLOW_UNITS_4_5: Record<string, ListeningFlowLessonContent> = {
  "tactics-basic-u04-l01": DAILY_ROUTINES_TIME_CONTENT,
  "tactics-basic-u04-l02": TIMES_AND_SCHEDULES_CONTENT,
  "tactics-basic-u04-l03": ACTIVITIES_AND_HABITS_CONTENT,
  "tactics-basic-u05-l01": DAYS_AND_MONTHS_CONTENT,
  "tactics-basic-u05-l02": MAKING_PLANS_CONTENT,
  "tactics-basic-u05-l03": SPECIAL_DATES_CONTENT,
};
