import type { ListeningFlowLessonContent } from "@/lib/listening/tactics-basic-flow-types";

/** Unit 6 — Listening 1 (Jobs and Workplaces). */
export const JOBS_AND_WORKPLACES_CONTENT: ListeningFlowLessonContent = {
  predictionOptions: [
    { key: "jobs", labelEn: "Different jobs and workplaces", labelVi: "Nghề nghiệp và nơi làm việc khác nhau" },
    { key: "likes", labelEn: "Why people like their jobs", labelVi: "Vì sao mọi người thích công việc" },
    { key: "salary", labelEn: "Salaries and pay only", labelVi: "Chỉ lương và thu nhập" },
    { key: "school", labelEn: "School subjects and homework", labelVi: "Môn học và bài tập" },
  ],
  gistOptions: [
    {
      key: "six-jobs",
      labelEn: "Six people briefly describe their jobs",
      labelVi: "Sáu người mô tả ngắn về công việc",
      correct: true,
    },
    {
      key: "why-like",
      labelEn: "Why each job suits the speaker",
      labelVi: "Vì sao từng công việc phù hợp với người nói",
      correct: true,
    },
    { key: "unemployment", labelEn: "Looking for work", labelVi: "Tìm việc làm" },
    { key: "travel-only", labelEn: "Vacation travel only", labelVi: "Chỉ du lịch nghỉ phép" },
  ],
  detailQuestions: [
    {
      key: "q1",
      conversationEn: "Conversation 1",
      conversationVi: "Hội thoại 1",
      questionEn: "What job does speaker 1 have?",
      questionVi: "Người 1 làm nghề gì?",
      answerEn: "Salesperson — sells computers.",
      answerVi: "Nhân viên bán hàng — bán máy tính.",
    },
    {
      key: "q2",
      conversationEn: "Conversation 2",
      conversationVi: "Hội thoại 2",
      questionEn: "What does speaker 2 do? What does he hope to do?",
      questionVi: "Người 2 làm gì? Anh ấy hy vọng làm gì?",
      answerEn: "Acting; hopes to write a book about his work.",
      answerVi: "Diễn xuất; hy vọng viết sách về công việc.",
    },
    {
      key: "q3",
      conversationEn: "Conversation 3",
      conversationVi: "Hội thoại 3",
      questionEn: "What job does speaker 3 have? Why does she like it?",
      questionVi: "Người 3 làm nghề gì? Vì sao cô ấy thích?",
      answerEn: "Job with travel and flying; likes visiting countries and her uniform.",
      answerVi: "Công việc đi lại và bay; thích thăm nhiều nước và đồng phục.",
    },
    {
      key: "q4",
      conversationEn: "Conversation 4",
      conversationVi: "Hội thoại 4",
      questionEn: "What job does speaker 4 have?",
      questionVi: "Người 4 làm nghề gì?",
      answerEn: "Works with food / cooking at a restaurant; famous people visit.",
      answerVi: "Làm về ẩm thực / nấu ở nhà hàng; nhiều người nổi tiếng ghé.",
    },
    {
      key: "q5",
      conversationEn: "Conversation 5",
      conversationVi: "Hội thoại 5",
      questionEn: "What job does speaker 5 have?",
      questionVi: "Người 5 làm nghề gì?",
      answerEn: "Nursing — likes helping sick people.",
      answerVi: "Điều dưỡng — thích giúp người bệnh.",
    },
    {
      key: "q6",
      conversationEn: "Conversation 6",
      conversationVi: "Hội thoại 6",
      questionEn: "What job does speaker 6 have? Why is it good for him?",
      questionVi: "Người 6 làm nghề gì? Vì sao phù hợp?",
      answerEn: "Works outside; hard work but good pay and keeps him in shape.",
      answerVi: "Làm ngoài trời; vất vả nhưng lương tốt và giúp giữ dáng.",
    },
  ],
  memoryPlaceholder: "…",
};

/** Unit 6 — Listening 2 (What Do You Do?). */
export const WHAT_DO_YOU_DO_CONTENT: ListeningFlowLessonContent = {
  predictionOptions: [
    { key: "current-job", labelEn: "What people do for work now", labelVi: "Mọi người đang làm gì" },
    { key: "job-change", labelEn: "Changing jobs or careers", labelVi: "Đổi việc hoặc nghề" },
    { key: "school", labelEn: "Still in school or just graduated", labelVi: "Còn đi học hoặc vừa tốt nghiệp" },
    { key: "hobbies", labelEn: "Weekend hobbies only", labelVi: "Chỉ sở thích cuối tuần" },
  ],
  gistOptions: [
    {
      key: "job-talk",
      labelEn: "Short conversations about people's jobs",
      labelVi: "Hội thoại ngắn về công việc của mọi người",
      correct: true,
    },
    {
      key: "new-old",
      labelEn: "New jobs, old jobs, and job hunting",
      labelVi: "Việc mới, việc cũ và tìm việc",
      correct: true,
    },
    { key: "salaries", labelEn: "Negotiating salaries", labelVi: "Đàm phán lương" },
    { key: "interviews", labelEn: "Job interview questions", labelVi: "Câu hỏi phỏng vấn" },
  ],
  detailQuestions: [
    {
      key: "q1",
      conversationEn: "Conversation 1",
      conversationVi: "Hội thoại 1",
      questionEn: "Where does Ryan work?",
      questionVi: "Ryan làm ở đâu?",
      answerEn: "Still working in the bank.",
      answerVi: "Vẫn làm ở ngân hàng.",
    },
    {
      key: "q2",
      conversationEn: "Conversation 2",
      conversationVi: "Hội thoại 2",
      questionEn: "What is Bridget's new job?",
      questionVi: "Công việc mới của Bridget là gì?",
      answerEn: "Chef in an Italian restaurant.",
      answerVi: "Đầu bếp ở nhà hàng Ý.",
    },
    {
      key: "q3",
      conversationEn: "Conversation 3",
      conversationVi: "Hội thoại 3",
      questionEn: "What is Jake doing after college?",
      questionVi: "Jake làm gì sau khi tốt nghiệp đại học?",
      answerEn: "Taking a long vacation (graduated last month).",
      answerVi: "Nghỉ dài (tốt nghiệp tháng trước).",
    },
    {
      key: "q4",
      conversationEn: "Conversation 4",
      conversationVi: "Hội thoại 4",
      questionEn: "What does Marie do? How long?",
      questionVi: "Marie làm nghề gì? Bao lâu rồi?",
      answerEn: "Lawyer — for about five years.",
      answerVi: "Luật sư — khoảng năm năm.",
    },
    {
      key: "q5",
      conversationEn: "Conversation 7",
      conversationVi: "Hội thoại 7",
      questionEn: "What is Patrick's new job? How was his first class?",
      questionVi: "Công việc mới của Patrick là gì? Lớp đầu thế nào?",
      answerEn: "English teacher — first class was terrific.",
      answerVi: "Giáo viên tiếng Anh — lớp đầu rất tuyệt.",
    },
    {
      key: "q6",
      conversationEn: "Conversation 8",
      conversationVi: "Hội thoại 8",
      questionEn: "Where does Allison work? What doesn't she like?",
      questionVi: "Allison làm ở đâu? Cô ấy không thích gì?",
      answerEn: "Bookstore — has to stand all day and gets tired.",
      answerVi: "Hiệu sách — phải đứng cả ngày và rất mệt.",
    },
  ],
  memoryPlaceholder: "…",
};

/** Unit 6 — Listening 3 (Talking About Work). */
export const TALKING_ABOUT_WORK_CONTENT: ListeningFlowLessonContent = {
  predictionOptions: [
    { key: "like-dislike", labelEn: "Liking or disliking a job", labelVi: "Thích hoặc không thích công việc" },
    { key: "problems", labelEn: "Problems at work (boring, travel, hours)", labelVi: "Khó khăn ở công việc (nhàm, đi công tác, giờ làm)" },
    { key: "boss", labelEn: "Bosses and coworkers", labelVi: "Sếp và đồng nghiệp" },
    { key: "food", labelEn: "Restaurant menus", labelVi: "Thực đơn nhà hàng" },
  ],
  gistOptions: [
    {
      key: "job-feelings",
      labelEn: "People talk about what they like and dislike about work",
      labelVi: "Mọi người nói thích và không thích gì ở công việc",
      correct: true,
    },
    {
      key: "stay-or-leave",
      labelEn: "Reasons to stay in a job or want to change",
      labelVi: "Lý do ở lại hoặc muốn đổi việc",
      correct: true,
    },
    { key: "promotion", labelEn: "Getting promoted", labelVi: "Được thăng chức" },
    { key: "retirement", labelEn: "Retirement plans", labelVi: "Kế hoạch nghỉ hưu" },
  ],
  detailQuestions: [
    {
      key: "q1",
      conversationEn: "Conversation 1",
      conversationVi: "Hội thoại 1",
      questionEn: "Why doesn't Chris like his job now? Why doesn't he leave?",
      questionVi: "Vì sao Chris không thích việc nữa? Vì sao chưa nghỉ?",
      answerEn: "Boring, same thing every day — but he is well paid.",
      answerVi: "Nhàm, làm một việc mãi — nhưng lương cao.",
    },
    {
      key: "q2",
      conversationEn: "Conversation 2",
      conversationVi: "Hội thoại 2",
      questionEn: "What does Alexa dislike about her job?",
      questionVi: "Alexa không thích gì ở công việc?",
      answerEn: "Distance to school — an hour drive each way.",
      answerVi: "Khoảng cách đến trường — lái xe một giờ mỗi chiều.",
    },
    {
      key: "q3",
      conversationEn: "Conversation 3",
      conversationVi: "Hội thoại 3",
      questionEn: "What does Anna like best? What is the trouble?",
      questionVi: "Anna thích nhất điều gì? Khó khăn là gì?",
      answerEn: "The people she works with — but travels a lot (two weeks/month).",
      answerVi: "Đồng nghiệp — nhưng đi công tác nhiều (khoảng hai tuần/tháng).",
    },
    {
      key: "q4",
      conversationEn: "Conversation 4",
      conversationVi: "Hội thoại 4",
      questionEn: "What doesn't Rachel like? Why doesn't she quit?",
      questionVi: "Rachel không thích gì? Vì sao chưa nghỉ?",
      answerEn: "Long hours, always tired — but her boss is great.",
      answerVi: "Giờ làm dài, luôn mệt — nhưng sếp rất tốt.",
    },
    {
      key: "q5",
      conversationEn: "Conversation 5",
      conversationVi: "Hội thoại 5",
      questionEn: "Does Martin enjoy restaurant work? Why does he stay?",
      questionVi: "Martin có thích làm nhà hàng không? Vì sao ở lại?",
      answerEn: "No — hard and tiring, on feet all night — but tips are great.",
      answerVi: "Không — vất vả, đứng cả đêm — nhưng tiền tip rất tốt.",
    },
  ],
  memoryPlaceholder: "…",
};

/** Unit 7 — Listening 1 (Favorite Things). */
export const FAVORITE_THINGS_CONTENT: ListeningFlowLessonContent = {
  predictionOptions: [
    { key: "tv", labelEn: "TV shows and talent contests", labelVi: "Chương trình TV và cuộc thi tài năng" },
    { key: "music", labelEn: "Music and musicians", labelVi: "Âm nhạc và ca sĩ" },
    { key: "food", labelEn: "Favorite restaurants and pizza", labelVi: "Nhà hàng yêu thích và pizza" },
    { key: "games", labelEn: "Video games", labelVi: "Trò chơi điện tử" },
  ],
  gistOptions: [
    {
      key: "favorites",
      labelEn: "People talk about favorite TV, music, sports, games, food, and radio",
      labelVi: "Mọi người nói về TV, nhạc, thể thao, game, đồ ăn và radio yêu thích",
      correct: true,
    },
    {
      key: "entertainment",
      labelEn: "Entertainment and leisure preferences",
      labelVi: "Sở thích giải trí và thư giãn",
      correct: true,
    },
    { key: "work", labelEn: "Office work schedules", labelVi: "Lịch làm việc văn phòng" },
    { key: "shopping", labelEn: "Clothes shopping", labelVi: "Mua quần áo" },
  ],
  detailQuestions: [
    {
      key: "q1",
      conversationEn: "Conversation 1",
      conversationVi: "Hội thoại 1",
      questionEn: "What TV show is on tonight?",
      questionVi: "Tối nay có chương trình TV gì?",
      answerEn: "The World's Greatest Talent — finals tonight.",
      answerVi: "The World's Greatest Talent — chung kết tối nay.",
    },
    {
      key: "q2",
      conversationEn: "Conversation 2",
      conversationVi: "Hội thoại 2",
      questionEn: "What do they say about the singer?",
      questionVi: "Họ nói gì về ca sĩ?",
      answerEn: "Beautiful voice; writes great songs; very creative.",
      answerVi: "Giọng đẹp; viết hay; rất sáng tạo.",
    },
    {
      key: "q3",
      conversationEn: "Conversation 3",
      conversationVi: "Hội thoại 3",
      questionEn: "When did the athlete start playing? How many goals in her career?",
      questionVi: "Vận động viên bắt đầu chơi khi nào? Bao nhiêu bàn thắng?",
      answerEn: "Age 2; professionally at 16; about 100 goals.",
      answerVi: "2 tuổi; chuyên nghiệp lúc 16; khoảng 100 bàn.",
    },
    {
      key: "q4",
      conversationEn: "Conversation 5",
      conversationVi: "Hội thoại 5",
      questionEn: "Where do they want to go? Why?",
      questionVi: "Họ muốn đi đâu? Vì sao?",
      answerEn: "Giovanni's — best pizza in the world.",
      answerVi: "Giovanni's — pizza ngon nhất thế giới.",
    },
    {
      key: "q5",
      conversationEn: "Conversation 6",
      conversationVi: "Hội thoại 6",
      questionEn: "Which radio station does one person want? What does the other prefer?",
      questionVi: "Một người muốn đài nào? Người kia thích gì?",
      answerEn: "97.9 (top hits) vs sports talk show.",
      answerVi: "97.9 (nhạc hot) so với chương trình thể thao.",
    },
  ],
  memoryPlaceholder: "…",
};

/** Unit 7 — Listening 2 (Likes and Dislikes / websites). */
export const LIKES_AND_DISLIKES_CONTENT: ListeningFlowLessonContent = {
  predictionOptions: [
    { key: "websites", labelEn: "Favorite websites and why", labelVi: "Trang web yêu thích và lý do" },
    { key: "music-download", labelEn: "Downloading music", labelVi: "Tải nhạc" },
    { key: "social", labelEn: "Social media and staying in touch", labelVi: "Mạng xã hội và giữ liên lạc" },
    { key: "news", labelEn: "News and gossip", labelVi: "Tin tức và tin đồn" },
  ],
  gistOptions: [
    {
      key: "six-sites",
      labelEn: "Six people describe favorite websites",
      labelVi: "Sáu người mô tả trang web yêu thích",
      correct: true,
    },
    {
      key: "reasons",
      labelEn: "Reasons they like each site (music, friends, shopping, news…)",
      labelVi: "Lý do thích từng trang (nhạc, bạn bè, mua sắm, tin tức…)",
      correct: true,
    },
    { key: "games-only", labelEn: "Online games only", labelVi: "Chỉ game online" },
    { key: "email", labelEn: "Email at work", labelVi: "Email công việc" },
  ],
  detailQuestions: [
    {
      key: "q1",
      conversationEn: "Conversation 1",
      conversationVi: "Hội thoại 1",
      questionEn: "Why does speaker 1 like this website?",
      questionVi: "Vì sao người 1 thích trang này?",
      answerEn: "Great music selection (rock, rap, jazz…) and cheaper downloads.",
      answerVi: "Nhiều thể loại nhạc và tải rẻ hơn các trang khác.",
    },
    {
      key: "q2",
      conversationEn: "Conversation 2",
      conversationVi: "Hội thoại 2",
      questionEn: "Why does speaker 2 like this website? What's the problem?",
      questionVi: "Vì sao người 2 thích trang này? Vấn đề là gì?",
      answerEn: "Stays in touch with friends/family and makes new friends — spends too much time when should study.",
      answerVi: "Giữ liên lạc và kết bạn mới — dành quá nhiều thời gian thay vì học.",
    },
    {
      key: "q3",
      conversationEn: "Conversation 3",
      conversationVi: "Hội thoại 3",
      questionEn: "What kind of videos does speaker 3 find?",
      questionVi: "Người 3 tìm thấy video gì?",
      answerEn: "Really funny videos (hasn't posted own videos yet).",
      answerVi: "Video rất hài (chưa đăng video của mình).",
    },
    {
      key: "q4",
      conversationEn: "Conversation 5",
      conversationVi: "Hội thoại 5",
      questionEn: "Why does speaker 5 shop on this website?",
      questionVi: "Vì sao người 5 mua trên trang này?",
      answerEn: "Big selection, fast delivery, best prices, sometimes free shipping.",
      answerVi: "Nhiều lựa chọn, giao nhanh, giá tốt, đôi khi miễn phí ship.",
    },
    {
      key: "q5",
      conversationEn: "Conversation 6",
      conversationVi: "Hội thoại 6",
      questionEn: "When does speaker 6 check the news site? What gossip did she learn?",
      questionVi: "Người 6 xem tin khi nào? Tin đồn gì?",
      answerEn: "At breakfast; Jeb Hawkes and Alison Romano broke up last week.",
      answerVi: "Lúc ăn sáng; Jeb Hawkes và Alison Romano chia tay tuần trước.",
    },
  ],
  memoryPlaceholder: "…",
};

/** Unit 7 — Listening 3 (Free Time / news favorites). */
export const FREE_TIME_FAVORITES_CONTENT: ListeningFlowLessonContent = {
  predictionOptions: [
    { key: "popular", labelEn: "What's popular this week (movies, sports, TV)", labelVi: "Gì đang hot tuần này (phim, thể thao, TV)" },
    { key: "sales", labelEn: "Sales and discounts", labelVi: "Giảm giá và khuyến mãi" },
    { key: "restaurants", labelEn: "Favorite new restaurants", labelVi: "Nhà hàng mới được yêu thích" },
    { key: "homework", labelEn: "School homework", labelVi: "Bài tập ở trường" },
  ],
  gistOptions: [
    {
      key: "news-bites",
      labelEn: "Short news items about current favorites in town or country",
      labelVi: "Tin ngắn về sở thích/thứ hot trong thành phố hoặc cả nước",
      correct: true,
    },
    {
      key: "entertainment-trends",
      labelEn: "Movies, sports teams, bands, stores, and TV shows trending",
      labelVi: "Phim, đội thể thao, ban nhạc, cửa hàng và TV đang thịnh hành",
      correct: true,
    },
    { key: "politics", labelEn: "Political speeches", labelVi: "Diễn văn chính trị" },
    { key: "weather", labelEn: "Weather forecasts", labelVi: "Dự báo thời tiết" },
  ],
  detailQuestions: [
    {
      key: "q1",
      conversationEn: "Conversation 1",
      conversationVi: "Hội thoại 1",
      questionEn: "What was the most popular movie? How much did it make?",
      questionVi: "Phim phổ biến nhất là gì? Doanh thu bao nhiêu?",
      answerEn: "The Terror in August — $20 million.",
      answerVi: "The Terror in August — 20 triệu đô.",
    },
    {
      key: "q2",
      conversationEn: "Conversation 2",
      conversationVi: "Hội thoại 2",
      questionEn: "What are the Freeville Blue Jays giving away?",
      questionVi: "Freeville Blue Jays tặng gì?",
      answerEn: "Free baseballs for one night only at the first game.",
      answerVi: "Bóng chày miễn phí một đêm ở trận mở mùa.",
    },
    {
      key: "q3",
      conversationEn: "Conversation 3",
      conversationVi: "Hội thoại 3",
      questionEn: "Which store is having a sale? How much off?",
      questionVi: "Cửa hàng nào giảm giá? Giảm bao nhiêu?",
      answerEn: "Star Rocker Clothes — 50% off once a year.",
      answerVi: "Star Rocker Clothes — giảm 50% một lần/năm.",
    },
    {
      key: "q4",
      conversationEn: "Conversation 4",
      conversationVi: "Hội thoại 4",
      questionEn: "What happened with the Brady Brothers concerts?",
      questionVi: "Buổi hòa nhạc Brady Brothers thế nào?",
      answerEn: "Two Boston shows sold out in five minutes; two more added.",
      answerVi: "Hai show Boston bán hết trong 5 phút; thêm hai show nữa.",
    },
    {
      key: "q5",
      conversationEn: "Conversation 5",
      conversationVi: "Hội thoại 5",
      questionEn: "What is the new favorite restaurant? When does it open?",
      questionVi: "Nhà hàng hot mới là gì? Mở cửa lúc mấy giờ?",
      answerEn: "Superburger — opens at 11; get there early.",
      answerVi: "Superburger — mở 11 giờ; đến sớm.",
    },
    {
      key: "q6",
      conversationEn: "Conversation 6",
      conversationVi: "Hội thoại 6",
      questionEn: "What is the most popular TV show for the third week?",
      questionVi: "Chương trình TV phổ biến nhất tuần thứ ba là gì?",
      answerEn: "The Island — adventures of Captain Smith.",
      answerVi: "The Island — cuộc phiêu lưu của Captain Smith.",
    },
  ],
  memoryPlaceholder: "…",
};

/** Unit 8 — Listening 1 (Sports and Teams). */
export const SPORTS_AND_TEAMS_CONTENT: ListeningFlowLessonContent = {
  predictionOptions: [
    { key: "play-sports", labelEn: "Playing sports on weekends", labelVi: "Chơi thể thao cuối tuần" },
    { key: "exercise", labelEn: "Swimming, biking, and staying in shape", labelVi: "Bơi, đạp xe và giữ dáng" },
    { key: "watch-tv", labelEn: "Watching sports on TV", labelVi: "Xem thể thao trên TV" },
    { key: "cooking", labelEn: "Cooking and recipes", labelVi: "Nấu ăn và công thức" },
  ],
  gistOptions: [
    {
      key: "sports-habits",
      labelEn: "People talk about sports they play, watch, or avoid",
      labelVi: "Mọi người nói môn thể thao chơi, xem hoặc tránh",
      correct: true,
    },
    {
      key: "fitness",
      labelEn: "Different ways to get exercise (or not)",
      labelVi: "Cách khác nhau để vận động (hoặc không)",
      correct: true,
    },
    { key: "jobs", labelEn: "Jobs and offices", labelVi: "Công việc và văn phòng" },
    { key: "travel", labelEn: "Travel plans", labelVi: "Kế hoạch du lịch" },
  ],
  detailQuestions: [
    {
      key: "q1",
      conversationEn: "Conversation 1",
      conversationVi: "Hội thoại 1",
      questionEn: "Does Rita play sports on weekends?",
      questionVi: "Rita có chơi thể thao cuối tuần không?",
      answerEn: "No — she watches favorite TV programs.",
      answerVi: "Không — cô ấy xem chương trình TV yêu thích.",
    },
    {
      key: "q2",
      conversationEn: "Conversation 2",
      conversationVi: "Hội thoại 2",
      questionEn: "What is Curtis's favorite sport?",
      questionVi: "Môn yêu thích của Curtis là gì?",
      answerEn: "Tennis — plays every day after work.",
      answerVi: "Quần vợt — chơi mỗi ngày sau giờ làm.",
    },
    {
      key: "q3",
      conversationEn: "Conversation 3",
      conversationVi: "Hội thoại 3",
      questionEn: "How often does Robert swim? For how long?",
      questionVi: "Robert bơi bao lâu một lần? Mỗi lần bao lâu?",
      answerEn: "About three times a week for about two hours.",
      answerVi: "Khoảng ba lần/tuần, mỗi lần khoảng hai giờ.",
    },
    {
      key: "q4",
      conversationEn: "Conversation 4",
      conversationVi: "Hội thoại 4",
      questionEn: "How does John keep in shape?",
      questionVi: "John giữ dáng thế nào?",
      answerEn: "Rides his bike about 20 miles every weekend.",
      answerVi: "Đạp xe khoảng 20 dặm mỗi cuối tuần.",
    },
    {
      key: "q5",
      conversationEn: "Conversation 5",
      conversationVi: "Hội thoại 5",
      questionEn: "What happened to the speaker? How often does he ski?",
      questionVi: "Chuyện gì xảy ra? Anh ấy trượt tuyết thường xuyên không?",
      answerEn: "Went skiing — first time, got hurt.",
      answerVi: "Đi trượt tuyết — lần đầu, bị thương.",
    },
    {
      key: "q6",
      conversationEn: "Conversation 6",
      conversationVi: "Hội thoại 6",
      questionEn: "How does Joe get exercise?",
      questionVi: "Joe vận động thế nào?",
      answerEn: "Walks to McDonald's about four times a week.",
      answerVi: "Đi bộ đến McDonald's khoảng bốn lần/tuần.",
    },
  ],
  memoryPlaceholder: "…",
};

/** Unit 8 — Listening 2 (Exercise and Fitness). */
export const EXERCISE_AND_FITNESS_CONTENT: ListeningFlowLessonContent = {
  predictionOptions: [
    { key: "gym", labelEn: "Going to the gym", labelVi: "Đi phòng gym" },
    { key: "team-sports", labelEn: "Volleyball and tennis with friends", labelVi: "Bóng chuyền và quần vợt với bạn" },
    { key: "watch-only", labelEn: "Watching sports without exercising", labelVi: "Xem thể thao mà không tập" },
    { key: "walking", labelEn: "Walking for exercise", labelVi: "Đi bộ để tập luyện" },
  ],
  gistOptions: [
    {
      key: "exercise-habits",
      labelEn: "People describe how they exercise or stay in shape",
      labelVi: "Mọi người mô tả cách tập luyện hoặc giữ dáng",
      correct: true,
    },
    {
      key: "play-vs-watch",
      labelEn: "Some play sports, others only watch on TV",
      labelVi: "Có người chơi thể thao, có người chỉ xem TV",
      correct: true,
    },
    { key: "diet", labelEn: "Diet and nutrition plans", labelVi: "Chế độ ăn và dinh dưỡng" },
    { key: "sleep", labelEn: "Sleep schedules", labelVi: "Lịch ngủ" },
  ],
  detailQuestions: [
    {
      key: "q1",
      conversationEn: "Conversation 1",
      conversationVi: "Hội thoại 1",
      questionEn: "How often does David go to the gym?",
      questionVi: "David đi gym bao lâu một lần?",
      answerEn: "Every day after work and on Saturdays too.",
      answerVi: "Mỗi ngày sau giờ làm và cả thứ Bảy.",
    },
    {
      key: "q2",
      conversationEn: "Conversation 2",
      conversationVi: "Hội thoại 2",
      questionEn: "What sport does the speaker play during the week?",
      questionVi: "Người nói chơi môn gì trong tuần?",
      answerEn: "Volleyball — invites friend to play tonight.",
      answerVi: "Bóng chuyền — mời bạn chơi tối nay.",
    },
    {
      key: "q3",
      conversationEn: "Conversation 3",
      conversationVi: "Hội thoại 3",
      questionEn: "When does Zach play volleyball and tennis?",
      questionVi: "Zach chơi bóng chuyền và quần vợt khi nào?",
      answerEn: "Volleyball Thursdays; tennis Saturdays and Sundays.",
      answerVi: "Bóng chuyền thứ Năm; quần vợt thứ Bảy và Chủ nhật.",
    },
    {
      key: "q4",
      conversationEn: "Conversation 4",
      conversationVi: "Hội thoại 4",
      questionEn: "Does the speaker like exercising? What does he watch?",
      questionVi: "Người nói có thích tập không? Xem gì?",
      answerEn: "No — watches a lot of baseball on TV.",
      answerVi: "Không — xem nhiều bóng chày trên TV.",
    },
    {
      key: "q5",
      conversationEn: "Conversation 5",
      conversationVi: "Hội thoại 5",
      questionEn: "How often does the last speaker walk?",
      questionVi: "Người cuối đi bộ bao lâu một lần?",
      answerEn: "About once a week for an hour.",
      answerVi: "Khoảng một lần/tuần, một giờ.",
    },
  ],
  memoryPlaceholder: "…",
};

/** Unit 8 — Listening 3 (Playing and Watching Sports). */
export const PLAYING_AND_WATCHING_SPORTS_CONTENT: ListeningFlowLessonContent = {
  predictionOptions: [
    { key: "club", labelEn: "Sports club: tennis, gym, baseball", labelVi: "Câu lạc bộ thể thao: tennis, gym, bóng chày" },
    { key: "walk-swim", labelEn: "Walking and light swimming", labelVi: "Đi bộ và bơi nhẹ" },
    { key: "watch-only", labelEn: "Watching soccer and tennis on TV", labelVi: "Xem bóng đá và quần vợt trên TV" },
    { key: "intense", labelEn: "Early morning swimming and many sports", labelVi: "Bơi sáng sớm và nhiều môn thể thao" },
  ],
  gistOptions: [
    {
      key: "five-people",
      labelEn: "Five people compare playing sports vs watching them",
      labelVi: "Năm người so sánh tự chơi và xem thể thao",
      correct: true,
    },
    {
      key: "different-levels",
      labelEn: "From very active to prefer watching on the couch",
      labelVi: "Từ rất năng động đến thích xem trên sofa",
      correct: true,
    },
    { key: "jobs", labelEn: "Work and commuting", labelVi: "Công việc và đi làm" },
    { key: "food", labelEn: "Restaurant reviews", labelVi: "Review nhà hàng" },
  ],
  detailQuestions: [
    {
      key: "q1",
      conversationEn: "Conversation 1",
      conversationVi: "Hội thoại 1",
      questionEn: "What does speaker 1 do during the week and on weekends?",
      questionVi: "Người 1 làm gì trong tuần và cuối tuần?",
      answerEn: "Tennis before school; gym on weekends; baseball with friends.",
      answerVi: "Quần vợt trước giờ học; gym cuối tuần; bóng chày với bạn.",
    },
    {
      key: "q2",
      conversationEn: "Conversation 2",
      conversationVi: "Hội thoại 2",
      questionEn: "What does speaker 2 prefer? What on Sunday?",
      questionVi: "Người 2 thích gì? Chủ nhật làm gì?",
      answerEn: "Short daily walks in the park; swims about half an hour on Sunday.",
      answerVi: "Đi bộ ngắn hàng ngày trong công viên; Chủ nhật bơi khoảng nửa giờ.",
    },
    {
      key: "q3",
      conversationEn: "Conversation 3",
      conversationVi: "Hội thoại 3",
      questionEn: "Does speaker 3 play soccer? What else does he enjoy?",
      questionVi: "Người 3 có chơi bóng đá không? Còn thích gì?",
      answerEn: "Only watches soccer on TV; enjoys tennis (wants to learn); plays chess and video games.",
      answerVi: "Chỉ xem bóng đá trên TV; thích quần vợt (muốn học); chơi cờ và game.",
    },
    {
      key: "q4",
      conversationEn: "Conversation 4",
      conversationVi: "Hội thoại 4",
      questionEn: "When does speaker 4 swim? What other sports?",
      questionVi: "Người 4 bơi khi nào? Môn nào khác?",
      answerEn: "5 a.m. Mon–Fri for two hours; basketball Tuesdays; started golf; jogs to warm up.",
      answerVi: "5 giờ sáng T2–T6 hai giờ; bóng rổ thứ Ba; mới chơi golf; chạy bộ khởi động.",
    },
    {
      key: "q5",
      conversationEn: "Conversation 5",
      conversationVi: "Hội thoại 5",
      questionEn: "When does speaker 5 play tennis? How about baseball?",
      questionVi: "Người 5 chơi quần vợt khi nào? Còn bóng chày?",
      answerEn: "Tennis every Wednesday ~1 hour; bikes on weekends; watches baseball on couch with popcorn.",
      answerVi: "Quần vợt mỗi thứ Tư ~1 giờ; đạp xe cuối tuần; xem bóng chày trên sofa ăn bỏng.",
    },
  ],
  memoryPlaceholder: "…",
};

export const TACTICS_BASIC_FLOW_UNITS_6_8: Record<string, ListeningFlowLessonContent> = {
  "tactics-basic-u06-l01": JOBS_AND_WORKPLACES_CONTENT,
  "tactics-basic-u06-l02": WHAT_DO_YOU_DO_CONTENT,
  "tactics-basic-u06-l03": TALKING_ABOUT_WORK_CONTENT,
  "tactics-basic-u07-l01": FAVORITE_THINGS_CONTENT,
  "tactics-basic-u07-l02": LIKES_AND_DISLIKES_CONTENT,
  "tactics-basic-u07-l03": FREE_TIME_FAVORITES_CONTENT,
  "tactics-basic-u08-l01": SPORTS_AND_TEAMS_CONTENT,
  "tactics-basic-u08-l02": EXERCISE_AND_FITNESS_CONTENT,
  "tactics-basic-u08-l03": PLAYING_AND_WATCHING_SPORTS_CONTENT,
};
