import type { ListeningFlowLessonContent } from "@/lib/listening/tactics-basic-flow-types";

/** Unit 2 — Listening 2 (Talking About Friends). */
export const TALKING_ABOUT_FRIENDS_CONTENT: ListeningFlowLessonContent = {
  predictionOptions: [
    { key: "boyfriend", labelEn: "Describing a boyfriend or partner", labelVi: "Miêu tả bạn trai / người yêu" },
    { key: "classmate", labelEn: "A new student in class", labelVi: "Học sinh mới trong lớp" },
    { key: "relative", labelEn: "A cousin or family member", labelVi: "Anh/chị/em họ hoặc người thân" },
    { key: "shopping", labelEn: "Shopping for electronics", labelVi: "Mua đồ điện tử" },
  ],
  gistOptions: [
    {
      key: "describe-people-you-know",
      labelEn: "People describe friends, classmates, or relatives",
      labelVi: "Mọi người miêu tả bạn bè, bạn cùng lớp hoặc người thân",
      correct: true,
    },
    {
      key: "appearance-details",
      labelEn: "Talking about age, hair, height, and looks",
      labelVi: "Nói về tuổi, tóc, chiều cao và ngoại hình",
      correct: true,
    },
    { key: "jobs-only", labelEn: "Discussing salaries and office jobs", labelVi: "Thảo luận lương và công việc văn phòng" },
    { key: "directions", labelEn: "Asking for directions downtown", labelVi: "Hỏi đường ở trung tâm thành phố" },
  ],
  detailQuestions: [
    {
      key: "q1",
      conversationEn: "Conversation 2",
      conversationVi: "Hội thoại 2",
      questionEn: "What is Anne's boyfriend's name? How old is he?",
      questionVi: "Tên bạn trai của Anne là gì? Anh ấy bao nhiêu tuổi?",
      answerEn: "Daniel. He is 17.",
      answerVi: "Daniel. Anh ấy 17 tuổi.",
    },
    {
      key: "q2",
      conversationEn: "Conversation 2",
      conversationVi: "Hội thoại 2",
      questionEn: "What does Daniel look like?",
      questionVi: "Daniel trông như thế nào?",
      answerEn: "Curly blonde hair, about average height, really good looking.",
      answerVi: "Tóc vàng xoăn, chiều cao trung bình, khá đẹp trai.",
    },
    {
      key: "q3",
      conversationEn: "Conversation 3",
      conversationVi: "Hội thoại 3",
      questionEn: "How tall is the new girl? What is her name?",
      questionVi: "Cô gái mới cao bao nhiêu? Tên cô ấy là gì?",
      answerEn: "About 170 cm. Anne (Matt thinks).",
      answerVi: "Khoảng 170 cm. Anne (Matt nghĩ vậy).",
    },
    {
      key: "q4",
      conversationEn: "Conversation 4",
      conversationVi: "Hội thoại 4",
      questionEn: "What does Paul's cousin do? What color is her hair?",
      questionVi: "Em họ của Paul làm nghề gì? Tóc màu gì?",
      answerEn: "She is an actress. Dark brown hair.",
      answerVi: "Cô ấy là diễn viên. Tóc nâu đen.",
    },
  ],
  memoryPlaceholder: "…",
};

/** Unit 2 — Listening 3 (What People Look Like). */
export const WHAT_PEOPLE_LOOK_LIKE_CONTENT: ListeningFlowLessonContent = {
  predictionOptions: [
    { key: "lost-child", labelEn: "A lost child in a store", labelVi: "Trẻ bị lạc trong cửa hàng" },
    { key: "hair-color", labelEn: "Hair color and age", labelVi: "Màu tóc và tuổi" },
    { key: "store-help", labelEn: "Store staff helping parents", labelVi: "Nhân viên cửa hàng giúp phụ huynh" },
    { key: "restaurant", labelEn: "Ordering food at a restaurant", labelVi: "Gọi món ở nhà hàng" },
  ],
  gistOptions: [
    {
      key: "lost-kids",
      labelEn: "Parents ask for help finding lost children",
      labelVi: "Phụ huynh nhờ giúp tìm con bị lạc",
      correct: true,
    },
    {
      key: "describe-child",
      labelEn: "Describing a child's age and hair color",
      labelVi: "Miêu tả tuổi và màu tóc của trẻ",
      correct: true,
    },
    { key: "buy-clothes", labelEn: "Shopping for clothes and shoes", labelVi: "Mua quần áo và giày" },
    { key: "school", labelEn: "Teachers talking about homework", labelVi: "Giáo viên nói về bài tập" },
  ],
  detailQuestions: [
    {
      key: "q1",
      conversationEn: "Conversation 1",
      conversationVi: "Hội thoại 1",
      questionEn: "How old is the lost boy? What color is his hair?",
      questionVi: "Cậu bé bao nhiêu tuổi? Tóc màu gì?",
      answerEn: "9 years old. Dark brown hair.",
      answerVi: "9 tuổi. Tóc nâu đen.",
    },
    {
      key: "q2",
      conversationEn: "Conversation 2",
      conversationVi: "Hội thoại 2",
      questionEn: "How old is the lost son? What color is his hair?",
      questionVi: "Con trai bao nhiêu tuổi? Tóc màu gì?",
      answerEn: "11. Light brown hair.",
      answerVi: "11 tuổi. Tóc nâu nhạt.",
    },
    {
      key: "q3",
      conversationEn: "Conversation 3",
      conversationVi: "Hội thoại 3",
      questionEn: "How old is the daughter? Describe her hair.",
      questionVi: "Con gái bao nhiêu tuổi? Tóc như thế nào?",
      answerEn: "10. Blonde, kind of long and straight.",
      answerVi: "10 tuổi. Vàng, khá dài và thẳng.",
    },
    {
      key: "q4",
      conversationEn: "Conversation 4",
      conversationVi: "Hội thoại 4",
      questionEn: "How old is she? Where might she be?",
      questionVi: "Cô bé bao nhiêu tuổi? Có thể ở đâu?",
      answerEn: "12. Probably in the toy section; brown, very curly hair.",
      answerVi: "12 tuổi. Có thể ở khu đồ chơi; tóc nâu, rất xoăn.",
    },
    {
      key: "q5",
      conversationEn: "Conversation 5",
      conversationVi: "Hội thoại 5",
      questionEn: "How old is the boy? Where was he last seen?",
      questionVi: "Cậu bé bao nhiêu tuổi? Lần cuối thấy ở đâu?",
      answerEn: "10. Near the video equipment; blonde, pretty long hair.",
      answerVi: "10 tuổi. Gần khu thiết bị video; tóc vàng, khá dài.",
    },
    {
      key: "q6",
      conversationEn: "Conversation 6",
      conversationVi: "Hội thoại 6",
      questionEn: "How old is the daughter? Where is she found?",
      questionVi: "Con gái bao nhiêu tuổi? Tìm thấy ở đâu?",
      answerEn: "About 13, average height, red hair — in the shoe department.",
      answerVi: "Khoảng 13 tuổi, cao trung bình, tóc đỏ — ở khu giày.",
    },
  ],
  memoryPlaceholder: "…",
};

/** Unit 3 — Listening 1 (Shopping for Clothes). */
export const SHOPPING_FOR_CLOTHES_CONTENT: ListeningFlowLessonContent = {
  predictionOptions: [
    { key: "find-person", labelEn: "Finding someone at a party", labelVi: "Tìm ai đó ở buổi tiệc" },
    { key: "clothes", labelEn: "What people are wearing", labelVi: "Trang phục mọi người đang mặc" },
    { key: "glasses", labelEn: "Glasses, suits, and casual wear", labelVi: "Kính, vest và đồ thường ngày" },
    { key: "weather", labelEn: "Weather and outdoor plans", labelVi: "Thời tiết và kế hoạch ngoài trời" },
  ],
  gistOptions: [
    {
      key: "identify-by-clothes",
      labelEn: "People identify others by what they are wearing",
      labelVi: "Mọi người nhận ra người khác qua trang phục",
      correct: true,
    },
    {
      key: "party-event",
      labelEn: "Looking for friends at an event or party",
      labelVi: "Tìm bạn ở sự kiện hoặc buổi tiệc",
      correct: true,
    },
    { key: "buying", labelEn: "Buying clothes in a store", labelVi: "Mua quần áo trong cửa hàng" },
    { key: "jobs", labelEn: "Talking about jobs and offices", labelVi: "Nói về công việc và văn phòng" },
  ],
  detailQuestions: [
    {
      key: "q1",
      conversationEn: "Conversation 1",
      conversationVi: "Hội thoại 1",
      questionEn: "What is David wearing?",
      questionVi: "David đang mặc gì?",
      answerEn: "A jacket and tie; reddish blonde hair.",
      answerVi: "Áo khoác và cà vạt; tóc vàng hơi đỏ.",
    },
    {
      key: "q2",
      conversationEn: "Conversation 2",
      conversationVi: "Hội thoại 2",
      questionEn: "What is Monica wearing? Does she have long hair?",
      questionVi: "Monica mặc gì? Cô ấy có tóc dài không?",
      answerEn: "Long dress and glasses; hair not really long.",
      answerVi: "Váy dài và đeo kính; tóc không thật sự dài.",
    },
    {
      key: "q3",
      conversationEn: "Conversation 3",
      conversationVi: "Hội thoại 3",
      questionEn: "What is Nick wearing?",
      questionVi: "Nick mặc gì?",
      answerEn: "Dark suit, tie, and sneakers.",
      answerVi: "Bộ vest tối màu, cà vạt và giày thể thao.",
    },
    {
      key: "q4",
      conversationEn: "Conversation 4",
      conversationVi: "Hội thoại 4",
      questionEn: "What is Emma wearing?",
      questionVi: "Emma mặc gì?",
      answerEn: "White pants, red blouse, and a scarf.",
      answerVi: "Quần trắng, áo blouse đỏ và khăn quàng.",
    },
    {
      key: "q5",
      conversationEn: "Conversation 5",
      conversationVi: "Hội thoại 5",
      questionEn: "What is Andrew wearing?",
      questionVi: "Andrew mặc gì?",
      answerEn: "Shorts, t-shirt, and short blonde hair.",
      answerVi: "Quần short, áo phông và tóc vàng ngắn.",
    },
    {
      key: "q6",
      conversationEn: "Conversation 8",
      conversationVi: "Hội thoại 8",
      questionEn: "What is Ben wearing?",
      questionVi: "Ben mặc gì?",
      answerEn: "Sneakers, shorts, and a tight shirt (he likes to show off his muscles).",
      answerVi: "Giày thể thao, quần short và áo bó ( thích khoe cơ bắp).",
    },
  ],
  memoryPlaceholder: "…",
};

/** Unit 3 — Listening 2 (What Are You Wearing?). */
export const WHAT_ARE_YOU_WEARING_CONTENT: ListeningFlowLessonContent = {
  predictionOptions: [
    { key: "fit", labelEn: "Whether clothes fit (too big/small/short)", labelVi: "Quần áo có vừa không (quá to/nhỏ/ngắn)" },
    { key: "colors", labelEn: "Colors and styles only", labelVi: "Chỉ màu sắc và phong cách" },
    { key: "store", labelEn: "Shopping in a clothing store", labelVi: "Mua sắm ở cửa hàng quần áo" },
    { key: "party", labelEn: "Getting dressed for a party", labelVi: "Chọn đồ đi tiệc" },
  ],
  gistOptions: [
    {
      key: "wrong-size",
      labelEn: "Customers say clothes are too big, small, short, or tight",
      labelVi: "Khách nói đồ quá to, nhỏ, ngắn hoặc chật",
      correct: true,
    },
    {
      key: "try-another",
      labelEn: "Asking for a different size or pair",
      labelVi: "Xin size hoặc đôi khác",
      correct: true,
    },
    { key: "prices", labelEn: "Comparing prices and discounts", labelVi: "So sánh giá và giảm giá" },
    { key: "returns", labelEn: "Returning items from last week", labelVi: "Trả hàng tuần trước" },
  ],
  detailQuestions: [
    {
      key: "q1",
      conversationEn: "Conversation 1",
      conversationVi: "Hội thoại 1",
      questionEn: "What's wrong with the pants?",
      questionVi: "Quần có vấn đề gì?",
      answerEn: "They are too short; he wants a longer pair.",
      answerVi: "Quá ngắn; anh ấy muốn đôi dài hơn.",
    },
    {
      key: "q2",
      conversationEn: "Conversation 2",
      conversationVi: "Hội thoại 2",
      questionEn: "What's wrong with the blouse?",
      questionVi: "Áo blouse có vấn đề gì?",
      answerEn: "It is a little too big; she needs a smaller one.",
      answerVi: "Hơi quá rộng; cô ấy cần size nhỏ hơn.",
    },
    {
      key: "q3",
      conversationEn: "Conversation 3",
      conversationVi: "Hội thoại 3",
      questionEn: "What's wrong with the sneakers?",
      questionVi: "Giày thể thao có vấn đề gì?",
      answerEn: "They are a little small; he needs a bigger pair.",
      answerVi: "Hơi nhỏ; anh ấy cần đôi lớn hơn.",
    },
    {
      key: "q4",
      conversationEn: "Conversation 4",
      conversationVi: "Hội thoại 4",
      questionEn: "What's wrong with the jeans?",
      questionVi: "Quần jean có vấn đề gì?",
      answerEn: "They are too big; they need a smaller pair.",
      answerVi: "Quá rộng; cần size nhỏ hơn.",
    },
    {
      key: "q5",
      conversationEn: "Conversation 5",
      conversationVi: "Hội thoại 5",
      questionEn: "Is the t-shirt too tight?",
      questionVi: "Áo phông có quá chật không?",
      answerEn: "Yes; he asks for a looser one.",
      answerVi: "Có; anh ấy xin áo rộng hơn.",
    },
    {
      key: "q6",
      conversationEn: "Conversation 6",
      conversationVi: "Hội thoại 6",
      questionEn: "What's wrong with the sandals?",
      questionVi: "Dép xăng đan có vấn đề gì?",
      answerEn: "Too big; she needs a smaller size.",
      answerVi: "Quá lớn; cô ấy cần size nhỏ hơn.",
    },
  ],
  memoryPlaceholder: "…",
};

/** Unit 3 — Listening 3 (At the Clothing Store). */
export const AT_THE_CLOTHING_STORE_CONTENT: ListeningFlowLessonContent = {
  predictionOptions: [
    { key: "outfits", labelEn: "Describing what people wore", labelVi: "Miêu tả trang phục mọi người mặc" },
    { key: "accessories", labelEn: "Shoes, bags, and jewelry", labelVi: "Giày, túi và trang sức" },
    { key: "prices", labelEn: "Prices and payment", labelVi: "Giá cả và thanh toán" },
    { key: "food", labelEn: "Ordering lunch", labelVi: "Gọi món trưa" },
  ],
  gistOptions: [
    {
      key: "detailed-outfits",
      labelEn: "Detailed descriptions of people's clothes and accessories",
      labelVi: "Mô tả chi tiết quần áo và phụ kiện",
      correct: true,
    },
    {
      key: "formal-casual",
      labelEn: "Mix of formal and casual outfits",
      labelVi: "Kết hợp trang phục trang trọng và thường ngày",
      correct: true,
    },
    { key: "uniforms", labelEn: "School or work uniforms only", labelVi: "Chỉ đồng phục trường hoặc công sở" },
    { key: "sports", labelEn: "Sports clothes and gym wear", labelVi: "Đồ thể thao và tập gym" },
  ],
  detailQuestions: [
    {
      key: "q1",
      conversationEn: "Conversation 1",
      conversationVi: "Hội thoại 1",
      questionEn: "What was Sonia wearing? What shoes did she have?",
      questionVi: "Sonia mặc gì? Giày thế nào?",
      answerEn: "Jacket, long dark blue skirt, yellow blouse, gold earrings; black high heels.",
      answerVi: "Áo khoác, váy xanh đen dài, blouse vàng, bông tai vàng; giày cao gót đen.",
    },
    {
      key: "q2",
      conversationEn: "Conversation 2",
      conversationVi: "Hội thoại 2",
      questionEn: "How was Matt dressed?",
      questionVi: "Matt mặc thế nào?",
      answerEn: "Old jeans with holes, wide leather belt, blue button shirt, high brown boots, glasses.",
      answerVi: "Jean cũ rách, thắt lưng da rộng, áo cài nút xanh, bốt nâu cao, đeo kính.",
    },
    {
      key: "q3",
      conversationEn: "Conversation 3",
      conversationVi: "Hội thoại 3",
      questionEn: "What was Kevin wearing?",
      questionVi: "Kevin mặc gì?",
      answerEn: "Yellow shirt, green tie, brown pants, sneakers with long white socks, leather bag.",
      answerVi: "Áo vàng, cà vạt xanh lá, quần nâu, giày thể thao tất trắng dài, túi da.",
    },
    {
      key: "q4",
      conversationEn: "Conversation 4",
      conversationVi: "Hội thoại 4",
      questionEn: "What did Amy wear?",
      questionVi: "Amy mặc gì?",
      answerEn: "Long skirt, black jacket, expensive glasses, collared shirt, sandals (no bag).",
      answerVi: "Váy dài, áo khoác đen, kính đắt, áo có cổ, sandal (không mang túi).",
    },
  ],
  memoryPlaceholder: "…",
};

export const TACTICS_BASIC_FLOW_UNITS_2_3: Record<string, ListeningFlowLessonContent> = {
  "tactics-basic-u02-l02": TALKING_ABOUT_FRIENDS_CONTENT,
  "tactics-basic-u02-l03": WHAT_PEOPLE_LOOK_LIKE_CONTENT,
  "tactics-basic-u03-l01": SHOPPING_FOR_CLOTHES_CONTENT,
  "tactics-basic-u03-l02": WHAT_ARE_YOU_WEARING_CONTENT,
  "tactics-basic-u03-l03": AT_THE_CLOTHING_STORE_CONTENT,
};
