/**
 * Fetch IPA for curated vocabulary lemmas via Free Dictionary API and write
 * `lib/vocabulary/ipa/vocabulary-ipa-data.ts`.
 *
 * Usage:
 *   npx tsx scripts/enrich-vocabulary-ipa.mts
 *   npx tsx scripts/enrich-vocabulary-ipa.mts --level=A1
 *   npx tsx scripts/enrich-vocabulary-ipa.mts --retry-failed
 */
import { writeFileSync, readFileSync, existsSync } from "node:fs";
import { resolve } from "node:path";
import { listEviuElementaryUnits } from "../lib/vocabulary/units/eviu-elementary-all-units";
import { listEviuPreIntermediateUnits } from "../lib/vocabulary/units/eviu-pre-intermediate-all-units";
import { listEviuUpperIntermediateUnits } from "../lib/vocabulary/units/eviu-upper-intermediate-all-units";
import { listEviuAdvancedUnits } from "../lib/vocabulary/units/eviu-advanced-all-units";
import type { VocabularyUnitLevel } from "../lib/vocabulary/vocabulary-catalog-types";
import { normalizeVocabularyIpaKey } from "../lib/vocabulary/ipa/vocabulary-ipa-lookup";
import { normalizeIpaForDisplay } from "../lib/reading/lookup-dictionary-utils";
import type { VocabularyUnit } from "../lib/vocabulary/vocabulary-unit-types";

const OUT = resolve(process.cwd(), "lib/vocabulary/ipa/vocabulary-ipa-data.ts");
const CACHE = resolve(process.cwd(), "lib/vocabulary/ipa/.ipa-fetch-cache.json");

type Cache = Record<string, string | null>;

function parseArgs() {
  const levelArg = process.argv.find((a) => a.startsWith("--level="))?.slice("--level=".length) as
    | VocabularyUnitLevel
    | undefined;
  const limitArg = process.argv.find((a) => a.startsWith("--limit="))?.slice("--limit=".length);
  const limit = limitArg ? Number(limitArg) : undefined;
  const retryFailed = process.argv.includes("--retry-failed");
  const phrases = process.argv.includes("--phrases");
  return { level: levelArg, limit, retryFailed, phrases };
}

function allUnits(): VocabularyUnit[] {
  return [
    ...listEviuElementaryUnits(),
    ...listEviuPreIntermediateUnits(),
    ...listEviuUpperIntermediateUnits(),
    ...listEviuAdvancedUnits(),
  ];
}

function loadCache(): Cache {
  if (!existsSync(CACHE)) return {};
  try {
    return JSON.parse(readFileSync(CACHE, "utf8")) as Cache;
  } catch {
    return {};
  }
}

function saveCache(cache: Cache) {
  writeFileSync(CACHE, JSON.stringify(cache, null, 2) + "\n", "utf8");
}

function loadExistingData(): Record<string, string> {
  if (!existsSync(OUT)) return {};
  const text = readFileSync(OUT, "utf8");
  const match = text.match(/export const VOCABULARY_IPA_BY_KEY[^=]*=\s*(\{[\s\S]*\})\s*;?\s*$/m);
  if (!match) return {};
  try {
    return Function(`"use strict"; return (${match[1]})`)() as Record<string, string>;
  } catch {
    return {};
  }
}

function writeData(data: Record<string, string>) {
  const keys = Object.keys(data).sort((a, b) => a.localeCompare(b));
  const body = keys.map((k) => `  ${JSON.stringify(k)}: ${JSON.stringify(data[k])},`).join("\n");
  const file = `/**
 * IPA lookup tập trung cho curated vocabulary.
 * Key = normalizeVocabularyIpaKey(term); value = IPA (không bắt buộc /.../).
 * Generated by scripts/enrich-vocabulary-ipa.mts — ${new Date().toISOString().slice(0, 10)}.
 */
export const VOCABULARY_IPA_BY_KEY: Record<string, string> = {
${body}
};
`;
  writeFileSync(OUT, file, "utf8");
}

type DictPhonetic = { text?: string; audio?: string };

function isFetchableLemma(key: string): boolean {
  if (!key) return false;
  if (/\s/.test(key)) return false;
  if (key.includes("...") || key.includes("…")) return false;
  if (/^\d/.test(key)) return false;
  // allow hyphenated / apostrophe words
  return /^[a-z][a-z'-]*$/i.test(key);
}

async function fetchIpa(lemma: string): Promise<string | null> {
  const url = `https://api.dictionaryapi.dev/api/v2/entries/en/${encodeURIComponent(lemma)}`;
  const res = await fetch(url);
  if (res.status === 404) return null;
  if (res.status === 429) {
    const err = new Error("RATE_LIMIT");
    throw err;
  }
  if (!res.ok) throw new Error(`HTTP ${res.status}`);
  const json = (await res.json()) as Array<{ phonetics?: DictPhonetic[]; phonetic?: string }>;
  const entry = json[0];
  if (!entry) return null;

  const candidates: string[] = [];
  if (entry.phonetic?.trim()) candidates.push(entry.phonetic.trim());
  for (const p of entry.phonetics ?? []) {
    if (p.text?.trim()) candidates.push(p.text.trim());
  }

  const scored = candidates
    .map((text) => {
      let score = 0;
      if (/^\/.*\/$/.test(text)) score += 8;
      if (text.length <= 28) score += 4;
      if (text.includes("\u0279")) score -= 6;
      return { text, score };
    })
    .sort((a, b) => b.score - a.score);

  const best = scored[0]?.text;
  if (!best) return null;
  return normalizeIpaForDisplay(best).replace(/^\/+|\/+$/g, "");
}

function sleep(ms: number) {
  return new Promise((r) => setTimeout(r, ms));
}

async function main() {
  const { level, limit, retryFailed, phrases } = parseArgs();
  const units = allUnits().filter((u) => !level || u.level === level);

  const keys = new Set<string>();
  for (const unit of units) {
    for (const word of unit.words) {
      const key = normalizeVocabularyIpaKey(word.term);
      if (!key) continue;
      if (!phrases && !isFetchableLemma(key)) continue;
      keys.add(key);
      const noArticle = key.replace(/^(a|an|the)\s+/, "");
      if (noArticle !== key && isFetchableLemma(noArticle)) keys.add(noArticle);
    }
  }

  const cache = loadCache();
  const data = loadExistingData();

  let pending = [...keys].filter((k) => {
    if (k in data) return false;
    if (retryFailed) return true;
    if (k in cache) return false;
    return true;
  });
  pending.sort((a, b) => a.localeCompare(b));
  if (limit && limit > 0) pending = pending.slice(0, limit);

  console.log(
    `level=${level ?? "ALL"} fetchable=${keys.size} pending=${pending.length} data=${Object.keys(data).length}`,
  );

  let ok = 0;
  let miss = 0;
  let fail = 0;
  let delay = 250;

  for (let i = 0; i < pending.length; i += 1) {
    const key = pending[i]!;
    try {
      const ipa = await fetchIpa(key);
      cache[key] = ipa;
      if (ipa) {
        data[key] = ipa;
        ok += 1;
        delay = Math.max(200, delay - 20);
      } else {
        miss += 1;
      }
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      if (msg === "RATE_LIMIT") {
        delay = Math.min(5000, delay * 2);
        console.warn(`rate-limit on "${key}", backing off ${delay}ms — will retry later`);
        // do not cache; leave for retry
        await sleep(delay);
        i -= 1; // retry same key
        continue;
      }
      fail += 1;
      console.warn(`fail ${key}: ${msg}`);
      await sleep(delay);
      continue;
    }

    if ((i + 1) % 20 === 0 || i + 1 === pending.length) {
      saveCache(cache);
      writeData(data);
      console.log(`progress ${i + 1}/${pending.length} ok=${ok} miss=${miss} fail=${fail} delay=${delay}`);
    }
    await sleep(delay);
  }

  saveCache(cache);
  writeData(data);
  console.log(`done ok=${ok} miss=${miss} fail=${fail} totalInData=${Object.keys(data).length}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
