#!/usr/bin/env python3
"""Fetch YouTube CC/transcripts for accent video lessons into a TS module."""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "lib" / "listening" / "accent-video-transcript-text.ts"

LESSONS = [
    ("vowels", "vj7o0AAfM1U", ["en-GB", "en"]),
    ("consonants", "r0RfrCkcwM0", ["en", "en-US"]),
    ("word-stress", "71HZyrjx_jI", ["en", "en-US"]),
]


def ensure_deps() -> None:
    try:
        import youtube_transcript_api  # noqa: F401
    except ImportError:
        subprocess.check_call([sys.executable, "-m", "pip", "install", "youtube-transcript-api", "-q"])


def format_transcript(snippets) -> str:
    """Plain text with paragraph breaks aligned to caption lines and pauses."""
    entries: list[tuple[object, str]] = []
    for snippet in snippets:
        text = snippet.text.strip().replace("\n", " ")
        if text:
            entries.append((snippet, text))

    if not entries:
        return ""

    paragraphs: list[str] = []
    chunk: list[str] = []

    for index, (snippet, line) in enumerate(entries):
        chunk.append(line)
        ends_sentence = line[-1] in ".!?"
        long_pause = False
        if index + 1 < len(entries):
            next_snippet = entries[index + 1][0]
            gap = next_snippet.start - (snippet.start + snippet.duration)
            long_pause = gap >= 1.4

        if (len(chunk) >= 2 and ends_sentence) or long_pause or len(chunk) >= 4:
            paragraphs.append(" ".join(chunk))
            chunk = []

    if chunk:
        paragraphs.append(" ".join(chunk))

    return "\n\n".join(paragraphs)


def fetch_transcript(video_id: str, languages: list[str]) -> tuple[str, str]:
    from youtube_transcript_api import YouTubeTranscriptApi

    api = YouTubeTranscriptApi()
    last_error: Exception | None = None
    for lang in languages:
        try:
            transcript = api.fetch(video_id, languages=[lang])
            return lang, format_transcript(list(transcript.snippets))
        except Exception as exc:  # noqa: BLE001
            last_error = exc
    raise RuntimeError(f"No transcript for {video_id}: {last_error}")


def ts_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def main() -> None:
    ensure_deps()
    entries: list[str] = []
    meta: dict[str, str] = {}

    for lesson_id, video_id, langs in LESSONS:
        lang, text = fetch_transcript(video_id, langs)
        meta[lesson_id] = lang
        entries.append(f'  "{lesson_id}": {ts_string(text)},')
        print(f"fetched {lesson_id} ({lang}, {len(text)} chars)")

    content = (
        "/** Auto-generated by scripts/fetch-accent-video-transcripts.py — do not edit by hand. */\n\n"
        f"export const ACCENT_VIDEO_TRANSCRIPT_LANG: Record<string, string> = {json.dumps(meta, indent=2)};\n\n"
        "export const ACCENT_VIDEO_TRANSCRIPTS: Record<string, string> = {\n"
        + "\n".join(entries)
        + "\n};\n"
    )
    OUT.write_text(content, encoding="utf-8")
    print(f"done → {OUT}")


if __name__ == "__main__":
    main()
