#!/usr/bin/env python3
"""Translate accent video transcript paragraphs to Vietnamese."""

from __future__ import annotations

import json
import re
import subprocess
import sys
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "lib" / "listening" / "accent-video-transcript-text.ts"
OUT = ROOT / "lib" / "listening" / "accent-video-transcript-vi.ts"

LESSON_IDS = ("vowels", "consonants", "word-stress")
MAX_CHUNK_CHARS = 4500


def ensure_deps() -> None:
    try:
        import deep_translator  # noqa: F401
    except ImportError:
        subprocess.check_call([sys.executable, "-m", "pip", "install", "deep-translator", "-q"])


def load_en_transcripts() -> dict[str, str]:
    text = SRC.read_text(encoding="utf-8")
    block_match = re.search(
        r"export const ACCENT_VIDEO_TRANSCRIPTS: Record<string, string> = \{(.*)\};\s*$",
        text,
        re.DOTALL,
    )
    if not block_match:
        raise RuntimeError("Missing ACCENT_VIDEO_TRANSCRIPTS block")
    block = block_match.group(1)
    transcripts: dict[str, str] = {}
    for lesson_id in LESSON_IDS:
        match = re.search(rf'"{re.escape(lesson_id)}":\s*("(?:\\.|[^"\\])*")', block, re.DOTALL)
        if not match:
            raise RuntimeError(f"Missing EN transcript for {lesson_id}")
        transcripts[lesson_id] = json.loads(match.group(1))
    return transcripts


def split_for_translation(paragraph: str) -> list[str]:
    if len(paragraph) <= MAX_CHUNK_CHARS:
        return [paragraph]
    sentences = re.split(r"(?<=[.!?])\s+", paragraph)
    chunks: list[str] = []
    current: list[str] = []
    current_len = 0
    for sentence in sentences:
        if not sentence:
            continue
        extra = len(sentence) + (1 if current else 0)
        if current and current_len + extra > MAX_CHUNK_CHARS:
            chunks.append(" ".join(current))
            current = [sentence]
            current_len = len(sentence)
        else:
            current.append(sentence)
            current_len += extra
    if current:
        chunks.append(" ".join(current))
    return chunks


def translate_text(text: str) -> str:
    from deep_translator import GoogleTranslator

    translator = GoogleTranslator(source="en", target="vi")
    chunks = split_for_translation(text)
    translated: list[str] = []
    for chunk in chunks:
        translated.append(translator.translate(chunk))
        time.sleep(0.35)
    return " ".join(translated)


def translate_lesson(en_text: str) -> str:
    paragraphs = [part.strip() for part in en_text.split("\n\n") if part.strip()]
    vi_paragraphs: list[str] = []
    for index, paragraph in enumerate(paragraphs, start=1):
        print(f"  paragraph {index}/{len(paragraphs)} ({len(paragraph)} chars)")
        vi_paragraphs.append(translate_text(paragraph))
    return "\n\n".join(vi_paragraphs)


def ts_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def main() -> None:
    ensure_deps()
    en_transcripts = load_en_transcripts()
    entries: list[str] = []

    for lesson_id in LESSON_IDS:
        en_text = en_transcripts[lesson_id]
        print(f"translating {lesson_id}…")
        vi_text = translate_lesson(en_text)
        entries.append(f'  "{lesson_id}": {ts_string(vi_text)},')
        print(f"done {lesson_id} ({len(vi_text)} chars)")

    content = (
        "/** Auto-generated by scripts/translate-accent-video-transcripts.py — do not edit by hand. */\n\n"
        "export const ACCENT_VIDEO_TRANSCRIPTS_VI: Record<string, string> = {\n"
        + "\n".join(entries)
        + "\n};\n"
    )
    OUT.write_text(content, encoding="utf-8")
    print(f"done → {OUT}")


if __name__ == "__main__":
    main()
