import type { QuickCheckQuiz } from "@/lib/reading/passage-quiz";

export const CAMBRIDGE_18_19_QUIZ: Record<string, QuickCheckQuiz> = {
  "cam19-test4-p1": {
    questionEn: "According to the passage, what do butterflies need outdoor conditions to be?",
    optionsEn: ["Too hot", "Just right — neither too hot nor too cold", "Very wet", "Completely dark"],
    questionVi: "Theo bài, điều kiện ngoài trời bướm cần là gì?",
    optionsVi: ["Quá nóng", "Vừa phải — không quá nóng cũng không quá lạnh", "Rất ẩm", "Tối hoàn toàn"],
    correctIndex: 1,
  },
  "cam19-test4-p2": {
    questionEn: "What did Professor Mat Upton discover in a deep-sea sponge microbe?",
    optionsEn: [
      "It produced rare metals for mining",
      "It was killing pathogenic bugs in his laboratory",
      "It could only live in shallow water",
      "It had no medical potential",
    ],
    questionVi: "Giáo sư Mat Upton phát hiện gì từ vi sinh vật trong bọt biển sâu?",
    optionsVi: [
      "Nó tạo kim loại quý để khai thác",
      "Nó tiêu diệt vi khuẩn gây bệnh trong phòng thí nghiệm",
      "Nó chỉ sống được ở vùng nước nông",
      "Nó không có tiềm năng y học",
    ],
    correctIndex: 1,
  },
  "cam19-test4-p3": {
    questionEn: "Which book is closely associated with the view that humans are essentially selfish?",
    optionsEn: [
      "Great Minds and How to Grow Them",
      "The Selfish Gene by Richard Dawkins",
      "Peak: Secrets from the New Science of Expertise",
      "The Hitchhiker's Guide to the Galaxy",
    ],
    questionVi: "Cuốn sách nào gắn với quan điểm con người vốn ích kỷ?",
    optionsVi: [
      "Great Minds and How to Grow Them",
      "The Selfish Gene của Richard Dawkins",
      "Peak: Secrets from the New Science of Expertise",
      "The Hitchhiker's Guide to the Galaxy",
    ],
    correctIndex: 1,
  },
  "cam19-test3-p1": {
    questionEn: "Where did Dr Ceri Shipton's team find prehistoric stone tools in 2019?",
    optionsEn: ["Mainland Australia", "The Indonesian island of Obi", "New Guinea highlands", "Southern Japan"],
    questionVi: "Năm 2019, nhóm Ceri Shipton tìm thấy đá công cụ tiền sử ở đâu?",
    optionsVi: ["Đại lục Australia", "Đảo Obi (Indonesia)", "Cao nguyên New Guinea", "Nam Nhật Bản"],
    correctIndex: 1,
  },
  "cam19-test3-p2": {
    questionEn: "According to the passage, what proportion of the world's wetlands has disappeared since 1990?",
    optionsEn: ["One quarter", "Half", "Three quarters", "Almost all"],
    questionVi: "Theo bài, bao nhiêu phần đất ngập nước thế giới đã biến mất từ 1990?",
    optionsVi: ["Một phần tư", "Một nửa", "Ba phần tư", "Gần như toàn bộ"],
    correctIndex: 1,
  },
  "cam19-test3-p3": {
    questionEn: "What does Alex Waibel identify as one of the major challenges for artificial speech translation?",
    optionsEn: ["Noise", "Lack of internet", "Too many languages", "Keyboard size"],
    questionVi: "Alex Waibel cho rằng thách thức lớn của dịch giọng nói nhân tạo là gì?",
    optionsVi: ["Tiếng ồn", "Thiếu internet", "Quá nhiều ngôn ngữ", "Kích thước bàn phím"],
    correctIndex: 0,
  },
  "cam19-test2-p1": {
    questionEn: "Where did the Industrial Revolution begin?",
    optionsEn: ["France", "Britain", "Germany", "The United States"],
    questionVi: "Cách mạng Công nghiệp bắt đầu ở đâu?",
    optionsVi: ["Pháp", "Anh", "Đức", "Hoa Kỳ"],
    correctIndex: 1,
  },
  "cam19-test2-p2": {
    questionEn: "What is a positive stress response called in the passage?",
    optionsEn: ["A threat state", "A challenge state", "A panic state", "A recovery state"],
    questionVi: "Phản ứng stress tích cực trong bài được gọi là gì?",
    optionsVi: ["Trạng thái đe dọa", "Trạng thái thử thách", "Trạng thái hoảng loạn", "Trạng thái phục hồi"],
    correctIndex: 1,
  },
  "cam19-test2-p3": {
    questionEn: "Who was the only woman to win a Fields Medal, mentioned at the start of the passage?",
    optionsEn: ["Deborah Eyre", "Maryam Mirzakhani", "Benjamin Bloom", "Albert Einstein"],
    questionVi: "Ai là người phụ nữ duy nhất được nhắc đến với Huy chương Fields?",
    optionsVi: ["Deborah Eyre", "Maryam Mirzakhani", "Benjamin Bloom", "Albert Einstein"],
    correctIndex: 1,
  },
  "cam19-test1-p1": {
    questionEn: "What change did Andy Murray make to his racket strings in 2012?",
    optionsEn: [
      "He switched to synthetic string for the mains",
      "He removed all strings",
      "He used only natural gut for both mains and crosses",
      "He stopped using a hybrid setup",
    ],
    questionVi: "Andy Murray đã thay đổi gì với dây vợt năm 2012?",
    optionsVi: [
      "Chuyển sang dây tổng hợp cho dọc (mains)",
      "Tháo hết dây",
      "Chỉ dùng ruột tự nhiên cho cả dọc và ngang",
      "Bỏ hẳn kiểu lai dây",
    ],
    correctIndex: 0,
  },
  "cam19-test1-p2": {
    questionEn: "When did Rome take concerted action against Mediterranean piracy according to the passage?",
    optionsEn: ["67 BC", "1390 BC", "1811 AD", "2016 AD"],
    questionVi: "Theo bài, Rome hành động quyết liệt chống cướp biển Địa Trung Hải vào năm nào?",
    optionsVi: ["67 TCN", "1390 TCN", "1811 SCN", "2016 SCN"],
    correctIndex: 0,
  },
  "cam19-test1-p3": {
    questionEn: "What is the main worry about misinformation mentioned in the passage?",
    optionsEn: [
      "It may unduly influence attitudes and behaviour",
      "It always disappears quickly",
      "It only affects print media",
      "It cannot spread on social media",
    ],
    questionVi: "Lo ngại chính về misinformation trong bài là gì?",
    optionsVi: [
      "Có thể ảnh hưởng không đáng kể đến thái độ và hành vi",
      "Luôn biến mất nhanh",
      "Chỉ ảnh hưởng báo in",
      "Không thể lan trên mạng xã hội",
    ],
    correctIndex: 0,
  },
  "cam18-test1-p1": {
    questionEn: "What soil-free growing method is used on the Paris rooftop farm?",
    optionsEn: ["Hydroponics only", "Aeroponic growing towers", "Traditional soil beds", "Open-field irrigation"],
    questionVi: "Nông trại mái nhà Paris dùng phương pháp không đất nào?",
    optionsVi: ["Chỉ thủy canh", "Tháp trồng aeroponic", "Luống đất truyền thống", "Tưới ruộng mở"],
    correctIndex: 1,
  },
  "cam18-test1-p2": {
    questionEn: "What is a Timber Stand Improvement (TSI) Cut mainly used for?",
    optionsEn: [
      "Removing poor-quality material to improve the stand",
      "Planting new urban crops",
      "Mining peat for fuel",
      "Launching satellites",
    ],
    questionVi: "TSI Cut chủ yếu dùng để làm gì?",
    optionsVi: [
      "Loại vật liệu kém chất lượng để cải thiện rừng",
      "Trồng cây đô thị mới",
      "Khai thác peat làm nhiên liệu",
      "Phóng vệ tinh",
    ],
    correctIndex: 0,
  },
  "cam18-test1-p3": {
    questionEn: "What serious event happened ten years ago involving satellites?",
    optionsEn: [
      "A US Iridium satellite collided with an inactive Russian satellite",
      "All satellites were removed from orbit",
      "The International Space Station was abandoned",
      "GPS stopped working worldwide",
    ],
    questionVi: "Sự kiện nghiêm trọng liên quan vệ tinh cách đây mười năm là gì?",
    optionsVi: [
      "Vệ tinh Iridium Mỹ va vào vệ tinh Nga không hoạt động",
      "Mọi vệ tinh bị gỡ khỏi quỹ đạo",
      "Trạm ISS bị bỏ hoang",
      "GPS ngừng hoạt động toàn cầu",
    ],
    correctIndex: 0,
  },
  "cam18-test2-p1": {
    questionEn: "Where did Stonehenge's bluestones originally come from?",
    optionsEn: [
      "The Preseli Hills in Wales",
      "Salisbury Plain itself",
      "The Scottish Highlands",
      "Northern France",
    ],
    questionVi: "Đá bluestone của Stonehenge ban đầu đến từ đâu?",
    optionsVi: [
      "Đồi Preseli ở Wales",
      "Chính Salisbury Plain",
      "Cao nguyên Scotland",
      "Bắc Pháp",
    ],
    correctIndex: 0,
  },
  "cam18-test2-p2": {
    questionEn: "Which folklore character illustrates the danger of asking for the wrong thing from powerful AI?",
    optionsEn: ["King Midas", "King Arthur", "Odysseus", "Robin Hood"],
    questionVi: "Nhân vật nào trong truyện dân gian minh họa nguy cơ yêu cầu sai từ AI mạnh?",
    optionsVi: ["Vua Midas", "Vua Arthur", "Odysseus", "Robin Hood"],
    correctIndex: 0,
  },
  "cam18-test2-p3": {
    questionEn: "Along which river did Leonardo plan his ideal city?",
    optionsEn: ["The Ticino River", "The Thames", "The Seine", "The Rhine"],
    questionVi: "Leonardo lên kế hoạch thành phố lý tưởng bên sông nào?",
    optionsVi: ["Sông Ticino", "Sông Thames", "Sông Seine", "Sông Rhine"],
    correctIndex: 0,
  },
  "cam18-test3-p1": {
    questionEn: "What is described as the second most used substance in the global economy?",
    optionsEn: ["Concrete", "Steel", "Timber", "Plastic"],
    questionVi: "Chất liệu nào được mô tả là thứ hai được dùng nhiều nhất trong nền kinh tế toàn cầu?",
    optionsVi: ["Bê tông", "Thép", "Gỗ", "Nhựa"],
    correctIndex: 0,
  },
  "cam18-test3-p2": {
    questionEn: "How quickly could the Doble Model B accelerate from zero to sixty miles per hour?",
    optionsEn: ["Fifteen seconds", "Thirty seconds", "One minute", "Twenty minutes"],
    questionVi: "Doble Model B tăng tốc từ 0 lên 60 dặm/giờ trong bao lâu?",
    optionsVi: ["Mười lăm giây", "Ba mươi giây", "Một phút", "Hai mươi phút"],
    correctIndex: 0,
  },
  "cam18-test3-p3": {
    questionEn: "According to John Hattie, what is the effect of streaming on learning outcomes?",
    optionsEn: [
      "Minimal effects on learning outcomes",
      "Large improvements for all students",
      "Only benefits the lowest sets",
      "Eliminates the achievement gap",
    ],
    questionVi: "Theo John Hattie, streaming ảnh hưởng thế nào đến kết quả học tập?",
    optionsVi: [
      "Ảnh hưởng tối thiểu đến kết quả học tập",
      "Cải thiện lớn cho mọi học sinh",
      "Chỉ có lợi cho nhóm thấp nhất",
      "Xóa bỏ khoảng cách thành tích",
    ],
    correctIndex: 0,
  },
  "cam18-test4-p1": {
    questionEn: "Which UK city is highlighted for forward-thinking green roof policies?",
    optionsEn: ["London", "Manchester", "Edinburgh", "Bristol"],
    questionVi: "Thành phố UK nào được nhấn mạnh vì chính sách mái xanh tiên phong?",
    optionsVi: ["London", "Manchester", "Edinburgh", "Bristol"],
    correctIndex: 0,
  },
  "cam18-test4-p2": {
    questionEn: "Whose research in the 1990s is the growth mindset theory based on?",
    optionsEn: ["Carol Dweck", "John Dewey", "Alfred Binet", "Andrew Gelman"],
    questionVi: "Lý thuyết growth mindset dựa trên nghiên cứu của ai trong thập niên 1990?",
    optionsVi: ["Carol Dweck", "John Dewey", "Alfred Binet", "Andrew Gelman"],
    correctIndex: 0,
  },
  "cam18-test4-p3": {
    questionEn: "What was Alfred Wegener's profession when he proposed continental drift in 1912?",
    optionsEn: [
      "Lecturer in physics and astronomy",
      "Professional geologist",
      "Ship captain",
      "University historian",
    ],
    questionVi: "Wegener làm nghề gì khi đề xuất trôi dạt lục địa năm 1912?",
    optionsVi: [
      "Giảng viên vật lý và thiên văn",
      "Địa chất học chuyên nghiệp",
      "Thuyền trưởng",
      "Sử gia đại học",
    ],
    correctIndex: 0,
  },
};
