import type { QuickCheckQuiz } from "@/lib/reading/passage-quiz";

export const CAMBRIDGE_12_QUIZ: Record<string, QuickCheckQuiz> = {
  "cam12-test1-p1": {
    questionEn: "How long does it take from planting a cork sapling to the first harvest?",
    optionsEn: [
      "25 years",
      "15 years",
      "10 years",
      "200 years",
    ],
    questionVi: "Từ khi trồng cây bồn bồn non đến lần thu hoạch đầu tiên mất bao lâu?",
    optionsVi: [
      "25 năm",
      "15 năm",
      "10 năm",
      "200 năm",
    ],
    correctIndex: 0,
    explanationEn: "The passage states that from the planting of a cork sapling to the first harvest takes 25 years, with approximately a decade between subsequent harvests.",
    explanationVi: "Bài nêu từ lúc trồng cây bồn bồn non đến lần thu hoạch đầu tiên mất 25 năm, và khoảng một thập kỷ giữa các lần thu hoạch sau đó.",
  },
  "cam12-test1-p2": {
    questionEn: "According to the passage, what feeling can buying cheap and selling dear give collectors?",
    optionsEn: [
      "A sense of triumph",
      "A feeling of aimlessness",
      "A need for control",
      "Educational satisfaction",
    ],
    questionVi: "Theo bài, cảm giác nào mà việc mua rẻ bán đắt có thể mang lại cho người sưu tập?",
    optionsVi: [
      "Cảm giác chiến thắng",
      "Cảm giác vô mục đích",
      "Nhu cầu kiểm soát",
      "Sự thỏa mãn kiến thức",
    ],
    correctIndex: 0,
    explanationEn: "The passage says that for collectors who want to make money, buying cheap and selling dear can give the collector a sense of triumph.",
    explanationVi: "Bài nói với người sưu tập để kiếm tiền, mua rẻ bán đắt có thể mang lại cảm giác chiến thắng.",
  },
  "cam12-test1-p3": {
    questionEn: "According to the writer, if someone uses marketing principles unethically, what are they doing?",
    optionsEn: [
      "Fraud, not marketing",
      "Firefighting, not arson",
      "Medicine, not poisoning",
      "Professional marketing with poor results",
    ],
    questionVi: "Theo tác giả, nếu ai đó dùng nguyên tắc marketing không đạo đức thì họ đang làm gì?",
    optionsVi: [
      "Gian lận, không phải marketing",
      "Chữa cháy, không phải phóng hỏa",
      "Hành nghề y, không phải đầu độc",
      "Marketing chuyên nghiệp nhưng kém hiệu quả",
    ],
    correctIndex: 0,
    explanationEn: "The writer argues that unethical use of marketing principles is not marketing at all — we have another term for it: fraud, just as arson is distinct from firefighting.",
    explanationVi: "Tác giả cho rằng dùng nguyên tắc marketing không đạo đức không phải marketing — ta gọi đó là gian lận, tương tự phóng hỏa khác chữa cháy.",
  },
  "cam12-test2-p1": {
    questionEn: "What did Rokeya Kabir report about beneficiaries of agricultural subsidies?",
    optionsEn: [
      "Sixty percent are not poor but rich landowners and non-farmer traders",
      "Most subsidies reach the smallest farms in developing countries",
      "Cash transfers always strengthen food production",
      "Subsidies have fully compensated for private traders' control",
    ],
    questionVi: "Rokeya Kabir báo cáo gì về người hưởng trợ cấp nông nghiệp?",
    optionsVi: [
      "60% không nghèo mà là địa chủ giàu và thương nhân không nông dân",
      "Phần lớn trợ cấp đến các trang trại nhỏ nhất ở nước đang phát triển",
      "Chuyển tiền mặt luôn củng cố sản xuất lương thực",
      "Trợ cấp đã bù đắp hoàn toàn sự kiểm soát của thương nhân tư",
    ],
    correctIndex: 0,
    explanationEn: "Kabir commented that studies show sixty percent of subsidy beneficiaries are not poor, but rich landowners and non-farmer traders.",
    explanationVi: "Kabir cho biết nghiên cứu cho thấy 60% người hưởng trợ cấp không nghèo mà là địa chủ giàu và thương nhân không nông dân.",
  },
  "cam12-test2-p2": {
    questionEn: "Why was Bingham able to travel down the Urubamba valley along a route most previous travellers had avoided?",
    optionsEn: [
      "A track had recently been blasted through the canyon for rubber transport",
      "Local farmers had built a new road to Machu Picchu",
      "The Spanish had cleared a path centuries earlier",
      "National Geographic had funded an expedition road",
    ],
    questionVi: "Tại sao Bingham có thể đi xuống thung lũng Urubamba theo tuyến mà hầu hết lữ khách trước đó tránh?",
    optionsVi: [
      "Một con đường mới được đặt mìn xuyên hẻm núi để vận chuyển cao su",
      "Nông dân địa phương đã xây đường mới đến Machu Picchu",
      "Người Tây Ban Nha đã mở lối đi từ nhiều thế kỷ trước",
      "National Geographic tài trợ xây đường thám hiểm",
    ],
    correctIndex: 0,
    explanationEn: "Bingham's team had an advantage because a track had recently been blasted down the valley canyon to bring rubber up by mules from the jungle.",
    explanationVi: "Nhóm Bingham có lợi thế vì một con đường mới được đặt mìn xuyên hẻm núi để đưa cao su lên bằng lạc đà từ rừng.",
  },
  "cam12-test2-p3": {
    questionEn: "What is 'language co-activation' as described in the passage?",
    optionsEn: [
      "Hearing a word activates corresponding words in both languages a bilingual knows",
      "Bilingual people can only use one language at a time",
      "Eye movements stop when bilinguals hear their second language",
      "Bilinguals guess words more accurately than monolinguals",
    ],
    questionVi: "'Kích hoạt đồng thời ngôn ngữ' trong bài được mô tả như thế nào?",
    optionsVi: [
      "Nghe một từ kích hoạt các từ tương ứng ở cả hai ngôn ngữ mà người song ngữ biết",
      "Người song ngữ chỉ dùng được một ngôn ngữ tại một thời điểm",
      "Chuyển động mắt dừng khi người song ngữ nghe ngôn ngữ thứ hai",
      "Người song ngữ đoán từ chính xác hơn người đơn ngữ",
    ],
    correctIndex: 0,
    explanationEn: "Language co-activation occurs because auditory input activates corresponding words regardless of which language they belong to, as shown in eye-movement studies.",
    explanationVi: "Kích hoạt đồng thời ngôn ngữ xảy ra vì âm thanh nghe được kích hoạt các từ tương ứng bất kể thuộc ngôn ngữ nào, như các nghiên cứu chuyển động mắt cho thấy.",
  },
  "cam12-test3-p1": {
    questionEn: "At what minimum age and weight can captive-bred tortoises be reintroduced into the wild?",
    optionsEn: [
      "Five years old and at least 4.5 kilograms",
      "Three years old and at least 2 kilograms",
      "Ten years old and at least 10 kilograms",
      "One year old once their shells begin to harden",
    ],
    questionVi: "Rùa nuôi nhân tạo được thả lại tự nhiên khi nào theo tiêu chuẩn tối thiểu về tuổi và cân nặng?",
    optionsVi: [
      "5 tuổi và ít nhất 4,5 kg",
      "3 tuổi và ít nhất 2 kg",
      "10 tuổi và ít nhất 10 kg",
      "1 tuổi khi mai bắt đầu cứng",
    ],
    correctIndex: 0,
    explanationEn: "Captive-bred tortoises cannot be reintroduced until they are at least five years old and weigh at least 4.5 kilograms, when their hardened shells can protect them.",
    explanationVi: "Rùa nuôi nhân tạo chỉ được thả lại khi ít nhất 5 tuổi và nặng ít nhất 4,5 kg, lúc mai cứng đủ bảo vệ chúng.",
  },
  "cam12-test3-p2": {
    questionEn: "How does the passage define health geography?",
    optionsEn: [
      "The combination of geographical knowledge and the study of health, diseases and healthcare",
      "The mapping of hospitals in developing countries only",
      "Research into how doctors choose where to practise medicine",
      "The study of how climate change eliminates all disease",
    ],
    questionVi: "Bài định nghĩa địa lý y tế như thế nào?",
    optionsVi: [
      "Sự kết hợp kiến thức địa lý với nghiên cứu sức khỏe, bệnh tật và chăm sóc y tế",
      "Lập bản đồ bệnh viện chỉ ở nước đang phát triển",
      "Nghiên cứu cách bác sĩ chọn nơi hành nghề",
      "Nghiên cứu cách biến đổi khí hậu loại bỏ mọi bệnh",
    ],
    correctIndex: 0,
    explanationEn: "Health geography combines knowledge of geography and methods to analyse geographical information with the study of health, diseases and healthcare practices worldwide.",
    explanationVi: "Địa lý y tế kết hợp kiến thức địa lý, phương pháp phân tích thông tin địa lý với nghiên cứu sức khỏe, bệnh tật và thực hành chăm sóc y tế trên thế giới.",
  },
  "cam12-test3-p3": {
    questionEn: "When were dopamine neurons in the caudate most active in the Montreal study?",
    optionsEn: [
      "About 15 seconds before participants' favourite moments in the music",
      "Only during the loudest acoustic climax of each song",
      "After the favourite part had already finished",
      "When participants heard music they disliked",
    ],
    questionVi: "Trong nghiên cứu Montreal, neuron dopamine ở vùng caudate hoạt động mạnh nhất khi nào?",
    optionsVi: [
      "Khoảng 15 giây trước khoảnh khắc yêu thích trong bài nhạc",
      "Chỉ ở đỉnh điểm âm thanh lớn nhất của mỗi bài",
      "Sau khi đoạn yêu thích đã kết thúc",
      "Khi người tham gia nghe nhạc họ không thích",
    ],
    correctIndex: 0,
    explanationEn: "Dopamine neurons in the caudate were most active around 15 seconds before participants' favourite moments, in what researchers call the 'anticipatory phase'.",
    explanationVi: "Neuron dopamine ở caudate hoạt động mạnh nhất khoảng 15 giây trước khoảnh khắc yêu thích, trong giai đoạn được gọi là 'dự đoán'.",
  },
  "cam12-test4-p1": {
    questionEn: "When were the first hollow glass containers made?",
    optionsEn: [
      "Around 1500 BC",
      "Around 4000 BC",
      "In the first century BC",
      "In 1632 AD",
    ],
    questionVi: "Lần đầu tiên làm được bình thủy tinh rỗng là khi nào?",
    optionsVi: [
      "Khoảng 1500 TCN",
      "Khoảng 4000 TCN",
      "Thế kỷ I TCN",
      "Năm 1632 SCN",
    ],
    correctIndex: 0,
    explanationEn: "It was not until 1500 BC that the first hollow glass container was made by covering a sand core with a layer of molten glass.",
    explanationVi: "Mãi đến khoảng 1500 TCN mới có bình thủy tinh rỗng đầu tiên, bằng cách phủ lõi cát bằng lớp thủy tinh nóng chảy.",
  },
  "cam12-test4-p2": {
    questionEn: "What did the 2006 animal bone discovery suggest about the lynx in Britain?",
    optionsEn: [
      "It survived there longer than previously believed",
      "It died out at least 6,000 years before farming began",
      "It was identical to the animal called the aurochs",
      "It was never depicted in British art or poetry",
    ],
    questionVi: "Phát hiện xương động vật năm 2006 gợi ý gì về linh miêu ở Anh?",
    optionsVi: [
      "Nó tồn tại lâu hơn so với niềm tin trước đây",
      "Nó tuyệt chủng ít nhất 6.000 năm trước khi có nông nghiệp",
      "Nó giống hệt loài gọi là aurochs",
      "Nó chưa từng được miêu tả trong nghệ thuật hay thơ Anh",
    ],
    correctIndex: 0,
    explanationEn: "The 2006 bone find is evidence that the lynx survived in Britain longer than previously thought, bringing forward its estimated extinction date by roughly 5,000 years.",
    explanationVi: "Xương tìm được năm 2006 cho thấy linh miêu sống ở Anh lâu hơn tưởng, đẩy thời điểm tuyệt chủng ước tính sớm hơn khoảng 5.000 năm.",
  },
  "cam12-test4-p3": {
    questionEn: "Why were part-time non-executive directors unable to anticipate the 2008 banking crash?",
    optionsEn: [
      "Executives had access to information that the directors lacked",
      "They spent too much time on remuneration committees",
      "They were legally forbidden from reading audit reports",
      "Board meetings had been reduced to fewer than eight per year",
    ],
    questionVi: "Tại sao giám đốc không điều hành bán thời gian không thể đoán trước khủng hoảng ngân hàng 2008?",
    optionsVi: [
      "Ban lãnh đạo điều hành có thông tin mà giám đốc không điều hành thiếu",
      "Họ dành quá nhiều thời gian cho ủy ban thù lao",
      "Họ bị luật cấm đọc báo cáo kiểm toán",
      "Cuộc họp hội đồng giảm xuống dưới 8 lần mỗi năm",
    ],
    correctIndex: 0,
    explanationEn: "The passage says bank executives had access to information that part-time non-executive directors lacked, leaving the latter unable to comprehend or anticipate the 2008 crash.",
    explanationVi: "Bài nêu ban điều hành ngân hàng có thông tin mà giám đốc không điều hành bán thời gian thiếu, khiến họ không thể hiểu hay đoán trước khủng hoảng 2008.",
  },
};
