import type { PassageVocabItem } from "@/lib/reading/passage-vocabulary";

export const CAMBRIDGE_18_19_VOCABULARY: Record<string, PassageVocabItem[]> = {
  "cam19-test4-p1": [
    { term: "phenology", definitionVi: "sinh học thời gian (chu kỳ sinh trưởng theo mùa)", level: "B1-B2" },
    { term: "conservationist", definitionVi: "nhà bảo tồn", level: "B1-B2" },
    { term: "lifecycles", definitionVi: "vòng đời", level: "B1-B2" },
    { term: "reproductive", definitionVi: "sinh sản", level: "B1-B2" },
    { term: "flexible", definitionVi: "linh hoạt", level: "B1-B2" },
  ],
  "cam19-test4-p2": [
    { term: "pathogenic", definitionVi: "gây bệnh", level: "B1-B2" },
    { term: "hydrothermal", definitionVi: "thủy nhiệt", level: "B1-B2" },
    { term: "ramifications", definitionVi: "hệ quả / tác động dây chuyền", level: "B1-B2" },
    { term: "bioactive", definitionVi: "sinh hoạt (có tác dụng sinh học)", level: "B1-B2" },
    { term: "seabed", definitionVi: "đáy biển", level: "B1-B2" },
  ],
  "cam19-test4-p3": [
    { term: "altruism", definitionVi: "vị tha", level: "B1-B2" },
    { term: "egalitarianism", definitionVi: "bình đẳng xã hội", level: "C1" },
    { term: "hunter-gatherer", definitionVi: "săn bắt – hái lượm", level: "B1-B2" },
    { term: "innate", definitionVi: "bẩm sinh", level: "B1-B2" },
    { term: "selfish", definitionVi: "ích kỷ", level: "B1-B2" },
  ],
  "cam19-test3-p1": [
    { term: "archaeologist", definitionVi: "nhà khảo cổ", level: "B1-B2" },
    { term: "obsidian", definitionVi: "đá vỏ chai (obsidian)", level: "B1-B2" },
    { term: "excavation", definitionVi: "khai quật", level: "B1-B2" },
    { term: "dispersal", definitionVi: "phân tán / lan rộng", level: "B1-B2" },
    { term: "prehistoric", definitionVi: "tiền sử", level: "B1-B2" },
  ],
  "cam19-test3-p2": [
    { term: "wetland", definitionVi: "đất ngập nước", level: "B1-B2" },
    { term: "peat", definitionVi: "than bùn / đất đen", level: "B1-B2" },
    { term: "subsidence", definitionVi: "sụt lún", level: "B1-B2" },
    { term: "mitigating", definitionVi: "giảm thiểu", level: "B1-B2" },
    { term: "biodiversity", definitionVi: "đa dạng sinh học", level: "B1-B2" },
  ],
  "cam19-test3-p3": [
    { term: "translation", definitionVi: "dịch thuật", level: "B1-B2" },
    { term: "earpiece", definitionVi: "tai nghe (nhét tai)", level: "B1-B2" },
    { term: "morphing", definitionVi: "biến đổi hình/thanh", level: "B1-B2" },
    { term: "novelty", definitionVi: "cái mới lạ", level: "B1-B2" },
    { term: "bilingual", definitionVi: "song ngữ", level: "B1-B2" },
  ],
  "cam19-test2-p1": [
    { term: "industrialisation", definitionVi: "công nghiệp hóa", level: "B1-B2" },
    { term: "mechanised", definitionVi: "cơ giới hóa", level: "B1-B2" },
    { term: "urbanisation", definitionVi: "đô thị hóa", level: "B1-B2" },
    { term: "smelting", definitionVi: "luyện kim", level: "B1-B2" },
    { term: "Luddites", definitionVi: "người phá máy (phong trào Luddite)", level: "C1" },
  ],
  "cam19-test2-p2": [
    { term: "adrenaline", definitionVi: "adrenaline / adrenaline", level: "B1-B2" },
    { term: "cortisol", definitionVi: "cortisol (hormone stress)", level: "B1-B2" },
    { term: "anxiety", definitionVi: "lo âu", level: "B1-B2" },
    { term: "unavoidable", definitionVi: "không thể tránh", level: "B1-B2" },
    { term: "psychological", definitionVi: "tâm lý", level: "B1-B2" },
  ],
  "cam19-test2-p3": [
    { term: "gifted", definitionVi: "có năng khiếu / thiên tài", level: "B1-B2" },
    { term: "deliberate", definitionVi: "cố ý / có chủ đích", level: "B1-B2" },
    { term: "resolute", definitionVi: "kiên quyết", level: "B1-B2" },
    { term: "setbacks", definitionVi: "trở ngại / thất bại tạm thời", level: "B1-B2" },
    { term: "expertise", definitionVi: "chuyên môn", level: "B1-B2" },
  ],
  "cam19-test1-p1": [
    { term: "hybrid", definitionVi: "lai / kết hợp", level: "B1-B2" },
    { term: "polyester", definitionVi: "polyester", level: "B1-B2" },
    { term: "topspin", definitionVi: "xoáy trên (tennis)", level: "B1-B2" },
    { term: "customisation", definitionVi: "tùy chỉnh", level: "B1-B2" },
    { term: "synthetic", definitionVi: "tổng hợp / nhân tạo", level: "B1-B2" },
  ],
  "cam19-test1-p2": [
    { term: "piracy", definitionVi: "cướp biển", level: "B1-B2" },
    { term: "Mediterranean", definitionVi: "Địa Trung Hải", level: "B1-B2" },
    { term: "merchant", definitionVi: "thương gia", level: "B1-B2" },
    { term: "republic", definitionVi: "cộng hòa", level: "B1-B2" },
    { term: "prowled", definitionVi: "rình rập / lang thang", level: "B1-B2" },
  ],
  "cam19-test1-p3": [
    { term: "misinformation", definitionVi: "thông tin sai lệch", level: "B1-B2" },
    { term: "rhetorically", definitionVi: "về mặt hùng biện", level: "C1" },
    { term: "unduly", definitionVi: "quá mức / không đáng", level: "B1-B2" },
    { term: "preemptively", definitionVi: "chủ động ngăn chặn", level: "C1" },
    { term: "encounter", definitionVi: "tiếp xúc / gặp phải", level: "B1-B2" },
  ],
  "cam18-test1-p1": [
    { term: "aeroponic", definitionVi: "aeroponic (trồng không đất, phun sương)", level: "B1-B2" },
    { term: "hydroponics", definitionVi: "thủy canh", level: "B1-B2" },
    { term: "vegetarian", definitionVi: "thuần thực vật", level: "B1-B2" },
    { term: "showcase", definitionVi: "trưng bày / minh họa", level: "B1-B2" },
    { term: "intensive", definitionVi: "quy mô / cường độ cao", level: "B1-B2" },
  ],
  "cam18-test1-p2": [
    { term: "timber", definitionVi: "gỗ xẻ / gỗ thương phẩm", level: "B1-B2" },
    { term: "bioenergy", definitionVi: "năng lượng sinh khối", level: "B1-B2" },
    { term: "salvage", definitionVi: "thu hồi / cứu vớt", level: "B1-B2" },
    { term: "thinning", definitionVi: "tỉa cây / thưa rừng", level: "B1-B2" },
    { term: "accessibility", definitionVi: "khả năng tiếp cận", level: "B1-B2" },
  ],
  "cam18-test1-p3": [
    { term: "debris", definitionVi: "mảnh vỡ / rác vũ trụ", level: "B1-B2" },
    { term: "orbit", definitionVi: "quỹ đạo", level: "B1-B2" },
    { term: "collision", definitionVi: "va chạm", level: "B1-B2" },
    { term: "catalogue", definitionVi: "danh mục", level: "B1-B2" },
    { term: "Kessler", definitionVi: "hiệu ứng Kessler (chuỗi va chạm)", level: "C1" },
  ],
};
