import type { PassageVocabItem } from "@/lib/reading/passage-vocabulary";

export const CAMBRIDGE_14_15_VOCABULARY: Record<string, PassageVocabItem[]> = {
  "cam14-test1-p1": [
    { term: "creativity", definitionVi: "khả năng sáng tạo", level: "B1-B2" },
    { term: "self-control", definitionVi: "khả năng tự kiểm soát", level: "B1-B2" },
    { term: "pretence", definitionVi: "sự giả vờ, đóng vai", level: "B1-B2" },
    { term: "spontaneous", definitionVi: "tự nhiên, không có kế hoạch trước", level: "B1-B2" },
    { term: "neurodevelopmental", definitionVi: "thuộc phát triển thần kinh", level: "C1" },
  ],
  "cam14-test1-p2": [
    { term: "activist", definitionVi: "nhà hoạt động (xã hội)", level: "B1-B2" },
    { term: "consumerism", definitionVi: "chủ nghĩa tiêu dùng", level: "B1-B2" },
    { term: "deposit", definitionVi: "tiền đặt cọc", level: "B1-B2" },
    { term: "vandalism", definitionVi: "hành vi phá hoại", level: "B1-B2" },
    { term: "municipality", definitionVi: "chính quyền thành phố", level: "C1" },
  ],
  "cam14-test1-p3": [
    { term: "turnover", definitionVi: "tỷ lệ thay đổi nhân viên", level: "B1-B2" },
    { term: "morale", definitionVi: "tinh thần làm việc", level: "B1-B2" },
    { term: "compensation", definitionVi: "khoản đền bù / lương thưởng", level: "B1-B2" },
    { term: "retention", definitionVi: "sự giữ chân (nhân viên)", level: "B1-B2" },
    { term: "dichotomy", definitionVi: "sự phân chia đối lập", level: "C1" },
  ],
  "cam14-test2-p1": [
    { term: "emigrate", definitionVi: "di cư (ra nước ngoài)", level: "B1-B2" },
    { term: "portraiture", definitionVi: "nghệ thuật chụp/vẽ chân dung", level: "B1-B2" },
    { term: "souvenir", definitionVi: "quà lưu niệm", level: "B1-B2" },
    { term: "commission", definitionVi: "hợp đồng đặt làm (tác phẩm)", level: "B1-B2" },
    { term: "apprenticeship", definitionVi: "thời gian học nghề", level: "C1" },
  ],
  "cam14-test2-p2": [
    { term: "ventilation", definitionVi: "thông gió", level: "B1-B2" },
    { term: "pathogens", definitionVi: "vi khuẩn/vi sinh vật gây bệnh", level: "B1-B2" },
    { term: "sealed", definitionVi: "được đóng kín", level: "B1-B2" },
    { term: "emissions", definitionVi: "khí thải", level: "B1-B2" },
    { term: "miasma", definitionVi: "khí độc bị coi là gây bệnh (thuyết cổ)", level: "C1" },
  ],
  "cam14-test2-p3": [
    { term: "hierarchy", definitionVi: "hệ thống cấp bậc", level: "B1-B2" },
    { term: "efficiency", definitionVi: "hiệu suất", level: "B1-B2" },
    { term: "obsession", definitionVi: "sự ám ảnh", level: "B1-B2" },
    { term: "innovate", definitionVi: "đổi mới, sáng tạo", level: "B1-B2" },
    { term: "boundaryless", definitionVi: "không giới hạn / không rào cản", level: "C1" },
  ],
  "cam14-test3-p1": [
    { term: "implicit", definitionVi: "ngầm, ẩn (không nói ra)", level: "B1-B2" },
    { term: "statesman", definitionVi: "nhà chính trị / chính khách", level: "B1-B2" },
    { term: "elite", definitionVi: "tầng lớp ưu tú", level: "B1-B2" },
    { term: "presupposition", definitionVi: "giả định ngầm", level: "B1-B2" },
    { term: "intersubstitutable", definitionVi: "có thể thay thế lẫn nhau", level: "C1" },
  ],
  "cam14-test3-p2": [
    { term: "antimicrobial", definitionVi: "kháng khuẩn", level: "B1-B2" },
    { term: "bioprospecting", definitionVi: "tìm kiếm hợp chất tự nhiên có ích", level: "B1-B2" },
    { term: "venom", definitionVi: "nọc độc", level: "B1-B2" },
    { term: "larvae", definitionVi: "ấu trùng", level: "B1-B2" },
    { term: "pathogenic", definitionVi: "gây bệnh", level: "C1" },
  ],
  "cam14-test3-p3": [
    { term: "intrinsic", definitionVi: "nội tại, tự thân", level: "B1-B2" },
    { term: "extrinsic", definitionVi: "bên ngoài, ngoại tại", level: "B1-B2" },
    { term: "repertoire", definitionVi: "vốn kỹ năng / danh mục", level: "B1-B2" },
    { term: "autonomy", definitionVi: "quyền tự chủ", level: "B1-B2" },
    { term: "continuum", definitionVi: "dải liên tục (không có ranh giới rõ)", level: "C1" },
  ],
  "cam14-test4-p1": [
    { term: "deteriorate", definitionVi: "suy giảm, xấu đi", level: "B1-B2" },
    { term: "mandibles", definitionVi: "hàm (côn trùng)", level: "B1-B2" },
    { term: "pupae", definitionVi: "nhộng (côn trùng)", level: "B1-B2" },
    { term: "aggressively", definitionVi: "một cách hung hăng", level: "B1-B2" },
    { term: "senescence", definitionVi: "sự lão hóa", level: "C1" },
  ],
  "cam14-test4-p2": [
    { term: "captivity", definitionVi: "tình trạng bị nuôi nhốt", level: "B1-B2" },
    { term: "predator", definitionVi: "động vật ăn thịt", level: "B1-B2" },
    { term: "reintroduction", definitionVi: "sự tái thả về tự nhiên", level: "B1-B2" },
    { term: "conservation", definitionVi: "bảo tồn", level: "B1-B2" },
    { term: "oestrus cycle", definitionVi: "chu kỳ động dục", level: "C1" },
  ],
  "cam14-test4-p3": [
    { term: "ingest", definitionVi: "ăn / nuốt vào", level: "B1-B2" },
    { term: "entangled", definitionVi: "bị vướng, mắc kẹt", level: "B1-B2" },
    { term: "microplastic", definitionVi: "vi nhựa (hạt nhựa siêu nhỏ)", level: "B1-B2" },
    { term: "debris", definitionVi: "rác thải, mảnh vỡ", level: "B1-B2" },
    { term: "strandings", definitionVi: "hiện tượng động vật dạt bờ (mắc cạn)", level: "C1" },
  ],
  "cam15-test1-p1": [
    { term: "husk", definitionVi: "vỏ ngoài (quả)", level: "B1-B2" },
    { term: "aril", definitionVi: "màng bọc hạt (tạo ra mace)", level: "B1-B2" },
    { term: "plantation", definitionVi: "đồn điền", level: "B1-B2" },
    { term: "monopoly", definitionVi: "sự độc quyền", level: "B1-B2" },
    { term: "commodity", definitionVi: "mặt hàng (giao dịch)", level: "C1" },
  ],
  "cam15-test1-p2": [
    { term: "automation", definitionVi: "tự động hóa", level: "B1-B2" },
    { term: "autonomy", definitionVi: "quyền tự chủ", level: "B1-B2" },
    { term: "mobility", definitionVi: "khả năng di chuyển", level: "B1-B2" },
    { term: "collision", definitionVi: "va chạm", level: "B1-B2" },
    { term: "liability", definitionVi: "trách nhiệm pháp lý", level: "C1" },
  ],
  "cam15-test1-p3": [
    { term: "explorer", definitionVi: "nhà thám hiểm", level: "B1-B2" },
    { term: "expedition", definitionVi: "chuyến thám hiểm", level: "B1-B2" },
    { term: "indigenous", definitionVi: "bản địa", level: "B1-B2" },
    { term: "isolated", definitionVi: "bị cô lập, hẻo lánh", level: "B1-B2" },
    { term: "unmechanised", definitionVi: "không dùng máy móc / thủ công", level: "C1" },
  ],
  "cam15-test2-p1": [
    { term: "choreographer", definitionVi: "biên đạo múa", level: "B1-B2" },
    { term: "pedestrian", definitionVi: "người đi bộ", level: "B1-B2" },
    { term: "sustainable", definitionVi: "bền vững", level: "B1-B2" },
    { term: "improvise", definitionVi: "ứng biến, làm ngay không chuẩn bị", level: "B1-B2" },
    { term: "counter-intuitive", definitionVi: "phản trực giác", level: "C1" },
  ],
  "cam15-test2-p2": [
    { term: "extinction", definitionVi: "sự tuyệt chủng", level: "B1-B2" },
    { term: "cloning", definitionVi: "nhân bản (vô tính)", level: "B1-B2" },
    { term: "hybrid", definitionVi: "lai, kết hợp hai loài", level: "B1-B2" },
    { term: "tundra", definitionVi: "vùng lãnh nguyên (đài nguyên)", level: "B1-B2" },
    { term: "genomics", definitionVi: "hệ gen học", level: "C1" },
  ],
  "cam15-test2-p3": [
    { term: "laughter", definitionVi: "tiếng cười", level: "B1-B2" },
    { term: "dominant", definitionVi: "áp đảo, chiếm ưu thế", level: "B1-B2" },
    { term: "submissive", definitionVi: "phục tùng, nhượng bộ", level: "B1-B2" },
    { term: "hierarchy", definitionVi: "hệ thống cấp bậc xã hội", level: "B1-B2" },
    { term: "replenishment", definitionVi: "sự bổ sung, phục hồi lại", level: "C1" },
  ],
  "cam15-test3-p1": [
    { term: "sculptor", definitionVi: "nhà điêu khắc", level: "B1-B2" },
    { term: "abstract", definitionVi: "trừu tượng", level: "B1-B2" },
    { term: "carving", definitionVi: "việc chạm khắc", level: "B1-B2" },
    { term: "commission", definitionVi: "đơn đặt làm tác phẩm", level: "B1-B2" },
    { term: "reclining", definitionVi: "ở thế nằm nghiêng/ngả", level: "C1" },
  ],
  "cam15-test3-p2": [
    { term: "desalination", definitionVi: "sự khử muối (nước biển)", level: "B1-B2" },
    { term: "distilled", definitionVi: "được chưng cất", level: "B1-B2" },
    { term: "purify", definitionVi: "làm sạch, tinh khiết hóa", level: "B1-B2" },
    { term: "borehole", definitionVi: "lỗ khoan (giếng)", level: "B1-B2" },
    { term: "scarcity", definitionVi: "sự khan hiếm", level: "C1" },
  ],
  "cam15-test3-p3": [
    { term: "folklore", definitionVi: "văn hóa dân gian", level: "B1-B2" },
    { term: "cautionary", definitionVi: "mang tính cảnh báo", level: "B1-B2" },
    { term: "gruesome", definitionVi: "ghê rợn, kinh khủng", level: "B1-B2" },
    { term: "variant", definitionVi: "phiên bản khác", level: "B1-B2" },
    { term: "phylogenetic", definitionVi: "thuộc phát sinh chủng loại (di truyền)", level: "C1" },
  ],
  "cam15-test4-p1": [
    { term: "arid", definitionVi: "khô hạn", level: "B1-B2" },
    { term: "erosion", definitionVi: "sự xói mòn", level: "B1-B2" },
    { term: "drought", definitionVi: "hạn hán", level: "B1-B2" },
    { term: "sustainable", definitionVi: "bền vững", level: "B1-B2" },
    { term: "ethnobotanist", definitionVi: "nhà dân tộc thực vật học", level: "C1" },
  ],
  "cam15-test4-p2": [
    { term: "whistle", definitionVi: "tiếng huýt sáo", level: "B1-B2" },
    { term: "frequency", definitionVi: "tần số", level: "B1-B2" },
    { term: "ambiguity", definitionVi: "sự mơ hồ, không rõ nghĩa", level: "B1-B2" },
    { term: "isolated", definitionVi: "hẻo lánh, cô lập", level: "B1-B2" },
    { term: "neuroimaging", definitionVi: "chụp ảnh thần kinh (não)", level: "C1" },
  ],
  "cam15-test4-p3": [
    { term: "shareholder", definitionVi: "cổ đông", level: "B1-B2" },
    { term: "sue", definitionVi: "kiện (ai đó)", level: "B1-B2" },
    { term: "regulation", definitionVi: "quy định, luật lệ", level: "B1-B2" },
    { term: "sustainable", definitionVi: "bền vững", level: "B1-B2" },
    { term: "fiduciary responsibility", definitionVi: "trách nhiệm ủy thác (pháp lý)", level: "C1" },
  ],
};
