import type { QuickCheckQuiz } from "@/lib/reading/passage-quiz";

export const CAMBRIDGE_14_15_QUIZ: Record<string, QuickCheckQuiz> = {
  "cam14-test1-p1": {
    questionEn: "According to Dr Sara Baker, what is a strong possibility about the role of play?",
    optionsEn: [
      "Play supports the early development of children's self-control",
      "Play is only useful for physical fitness",
      "Play has no measurable effect on learning",
      "Play should always be adult-directed",
    ],
    questionVi: "Theo Dr Sara Baker, khả năng lớn về vai trò của việc chơi là gì?",
    optionsVi: [
      "Chơi hỗ trợ sự phát triển sớm khả năng tự kiểm soát của trẻ",
      "Chơi chỉ có ích cho thể chất",
      "Chơi không ảnh hưởng gì đến việc học",
      "Chơi luôn cần người lớn chỉ đạo",
    ],
    correctIndex: 0,
    explanationEn: "Baker explains: 'A strong possibility is that play supports the early development of children's self-control.'",
    explanationVi: "Baker nói khả năng lớn là play hỗ trợ sự phát triển sớm self-control của trẻ.",
  },
  "cam14-test1-p2": {
    questionEn: "What happened to the white bikes shortly after Provo distributed them around Amsterdam in 1965?",
    optionsEn: [
      "They were sold to tourists",
      "The police removed them almost immediately",
      "They were donated to the city council",
      "They were painted different colours",
    ],
    questionVi: "Điều gì xảy ra với những chiếc xe đạp trắng ngay sau khi Provo phân phát ở Amsterdam năm 1965?",
    optionsVi: [
      "Chúng được bán cho khách du lịch",
      "Cảnh sát dẹp chúng đi gần như ngay lập tức",
      "Chúng được tặng cho hội đồng thành phố",
      "Chúng được sơn lại màu khác",
    ],
    correctIndex: 1,
    explanationEn: "The passage states police were opposed to Provo's initiatives and removed the bikes almost as soon as they were distributed.",
    explanationVi: "Bài nêu cảnh sát phản đối và dẹp xe gần như ngay khi Provo phân phát.",
  },
  "cam14-test1-p3": {
    questionEn: "According to Herzberg (1966), what do extrinsic motivation factors relate to?",
    optionsEn: [
      "Personal achievement and recognition",
      "The context in which work is performed, such as working conditions",
      "Salary increases only",
      "Employees' family life outside work",
    ],
    questionVi: "Theo Herzberg (1966), yếu tố động lực bên ngoài (extrinsic) liên quan đến điều gì?",
    optionsVi: [
      "Thành tích và sự công nhận cá nhân",
      "Bối cảnh công việc được thực hiện, như điều kiện làm việc",
      "Chỉ việc tăng lương",
      "Cuộc sống gia đình ngoài công việc",
    ],
    correctIndex: 1,
    explanationEn: "The passage says extrinsic factors relate to the context in which work is performed, including working conditions and job security.",
    explanationVi: "Bài nêu yếu tố extrinsic liên quan bối cảnh công việc, gồm điều kiện làm việc và độ an toàn công việc.",
  },
  "cam14-test2-p1": {
    questionEn: "Why did people buy Henderson's photographs, according to the passage?",
    optionsEn: [
      "As investments that would increase in value",
      "As souvenirs of a trip or as gifts, since amateur photography was rare",
      "Because he sold them cheaper than other photographers",
      "For use in newspapers",
    ],
    questionVi: "Theo bài, tại sao người ta mua ảnh của Henderson?",
    optionsVi: [
      "Như một khoản đầu tư sẽ tăng giá",
      "Làm quà lưu niệm hoặc tặng, vì chụp ảnh nghiệp dư còn hiếm",
      "Vì ông bán rẻ hơn các nhà chụp ảnh khác",
      "Để dùng trên báo",
    ],
    correctIndex: 1,
    explanationEn: "The passage explains people wanted photos as souvenirs or gifts, since amateur photography was rare before the late 1880s.",
    explanationVi: "Bài giải thích người ta muốn ảnh làm lưu niệm/tặng vì nhiếp ảnh nghiệp dư còn hiếm trước cuối thập niên 1880.",
  },
  "cam14-test2-p2": {
    questionEn: "What does Professor Alan Short argue skyscrapers should rely on instead of air conditioning?",
    optionsEn: [
      "Solar panels only",
      "Natural ventilation and cooling based on 19th-century design principles",
      "Smaller windows",
      "Underground construction",
    ],
    questionVi: "Giáo sư Alan Short cho rằng các nhà chọc trời nên dựa vào điều gì thay vì điều hòa?",
    optionsVi: [
      "Chỉ pin năng lượng mặt trời",
      "Thông gió và làm mát tự nhiên theo nguyên tắc thiết kế thế kỷ 19",
      "Cửa sổ nhỏ hơn",
      "Xây dựng dưới lòng đất",
    ],
    correctIndex: 1,
    explanationEn: "Short calls for a return to natural ventilation and cooling principles from 19th- and early-20th-century architecture.",
    explanationVi: "Short kêu gọi trở lại nguyên tắc thông gió và làm mát tự nhiên từ kiến trúc thế kỷ 19 - đầu 20.",
  },
  "cam14-test2-p3": {
    questionEn: "According to recent studies mentioned in the passage, what happens to order beyond a certain point?",
    optionsEn: [
      "It continues to increase productivity indefinitely",
      "It has diminishing returns and can eventually reduce productivity",
      "It has no effect on productivity at all",
      "It always leads to business failure",
    ],
    questionVi: "Theo các nghiên cứu gần đây trong bài, điều gì xảy ra với 'sự có trật tự' (order) sau một mức nào đó?",
    optionsVi: [
      "Tiếp tục tăng năng suất vô hạn",
      "Có lợi ích giảm dần và cuối cùng có thể làm giảm năng suất",
      "Không ảnh hưởng gì đến năng suất",
      "Luôn dẫn đến thất bại kinh doanh",
    ],
    correctIndex: 1,
    explanationEn: "The passage states order increases productivity up to a point, then further order actually reduces productivity.",
    explanationVi: "Bài nêu order tăng năng suất đến một điểm, sau đó thêm order lại làm giảm năng suất.",
  },
  "cam14-test3-p1": {
    questionEn: "What are 'implicit theories', as described at the start of the passage?",
    optionsEn: [
      "Scientific theories published in academic journals",
      "People's unconscious notions of what intelligence is",
      "Government policies about education",
      "Formal IQ test results",
    ],
    questionVi: "'Implicit theories' được mô tả ở đầu bài là gì?",
    optionsVi: [
      "Lý thuyết khoa học đăng trên tạp chí học thuật",
      "Những quan niệm vô thức của con người về trí tuệ là gì",
      "Chính sách giáo dục của chính phủ",
      "Kết quả bài kiểm tra IQ chính thức",
    ],
    correctIndex: 1,
    explanationEn: "The passage says people have unconscious notions — known as 'implicit theories' — of intelligence.",
    explanationVi: "Bài nêu con người có những quan niệm vô thức — gọi là 'implicit theories' — về trí tuệ.",
  },
  "cam14-test3-p2": {
    questionEn: "What is alloferon, as mentioned in the passage?",
    optionsEn: [
      "A synthetic chemical designed entirely in a laboratory",
      "An antimicrobial compound from blow fly larvae used as an antiviral/antitumor agent",
      "A type of insect commonly found in Europe",
      "A vaccine used against malaria",
    ],
    questionVi: "Alloferon được nhắc trong bài là gì?",
    optionsVi: [
      "Hóa chất tổng hợp hoàn toàn trong phòng thí nghiệm",
      "Hợp chất kháng khuẩn từ ấu trùng ruồi nhặng, dùng làm thuốc kháng virus/kháng u",
      "Một loại côn trùng phổ biến ở châu Âu",
      "Vắc-xin chống sốt rét",
    ],
    correctIndex: 1,
    explanationEn: "The passage states alloferon is an antimicrobial compound produced by blow fly larvae, used as an antiviral and antitumor agent in South Korea and Russia.",
    explanationVi: "Bài nêu alloferon là hợp chất kháng khuẩn từ ấu trùng ruồi nhặng, dùng làm thuốc kháng virus và kháng u ở Hàn Quốc và Nga.",
  },
  "cam14-test3-p3": {
    questionEn: "How does Stuart Brown define play, according to the passage?",
    optionsEn: [
      "An activity always assigned by teachers",
      "Anything spontaneously done for its own sake, appearing purposeless but producing pleasure",
      "A structured task with a clear extrinsic goal",
      "An activity only children under five engage in",
    ],
    questionVi: "Stuart Brown định nghĩa 'play' như thế nào?",
    optionsVi: [
      "Hoạt động luôn do giáo viên giao",
      "Bất cứ điều gì làm một cách tự nhiên vì chính nó, có vẻ vô mục đích nhưng tạo niềm vui",
      "Nhiệm vụ có cấu trúc với mục tiêu bên ngoài rõ ràng",
      "Hoạt động chỉ trẻ dưới 5 tuổi tham gia",
    ],
    correctIndex: 1,
    explanationEn: "Brown describes play as 'anything that spontaneously is done for its own sake' that 'appears purposeless, produces pleasure and joy'.",
    explanationVi: "Brown mô tả play là điều làm tự nhiên vì chính nó, có vẻ vô mục đích nhưng tạo niềm vui, hạnh phúc.",
  },
  "cam14-test4-p1": {
    questionEn: "What did Ysabel Giraldo find when comparing old and young Pheidole dentata worker ants?",
    optionsEn: [
      "Old ants performed much worse on every task",
      "Old ants performed just as well as young ants, showing little sign of decline",
      "Old ants could no longer respond to light",
      "Old ants stopped caring for the colony's young entirely",
    ],
    questionVi: "Ysabel Giraldo phát hiện gì khi so sánh kiến thợ Pheidole dentata già và trẻ?",
    optionsVi: [
      "Kiến già làm mọi việc kém hơn hẳn",
      "Kiến già làm tốt như kiến trẻ, hầu như không suy giảm",
      "Kiến già không còn phản ứng với ánh sáng",
      "Kiến già ngừng hẳn việc chăm sóc con non trong đàn",
    ],
    correctIndex: 1,
    explanationEn: "The passage says old worker ants can do everything just as well as youngsters and their brains appear just as sharp.",
    explanationVi: "Bài nêu kiến thợ già làm mọi việc tốt như kiến trẻ và não vẫn nhạy bén như vậy.",
  },
  "cam14-test4-p2": {
    questionEn: "According to David Hone, why might animals in good zoos have a quality of life as high as in the wild?",
    optionsEn: [
      "They are trained to perform for visitors",
      "They get a good diet, treatment for illness, and safety from predators and parasites",
      "They can roam freely without any restriction",
      "They no longer need any conservation programmes",
    ],
    questionVi: "Theo David Hone, tại sao động vật trong sở thú tốt có thể có chất lượng sống cao như trong tự nhiên?",
    optionsVi: [
      "Chúng được huấn luyện để trình diễn cho khách",
      "Chúng có chế độ ăn tốt, được điều trị bệnh, an toàn trước kẻ săn mồi và ký sinh trùng",
      "Chúng được tự do di chuyển không hạn chế",
      "Chúng không còn cần chương trình bảo tồn nào nữa",
    ],
    correctIndex: 1,
    explanationEn: "The passage lists a varied high-quality diet, treated illnesses, safety from predators/parasites, and no starvation as reasons.",
    explanationVi: "Bài nêu chế độ ăn tốt, được điều trị bệnh, an toàn trước kẻ săn mồi/ký sinh trùng, không chết vì đói khát là lý do.",
  },
  "cam14-test4-p3": {
    questionEn: "In Rochman's analysis, in what proportion of the studies examined were the perceived dangers of ocean trash proven true?",
    optionsEn: ["25 percent", "50 percent", "83 percent", "100 percent"],
    questionVi: "Trong phân tích của Rochman, bao nhiêu phần trăm nghiên cứu được xem xét chứng minh mối nguy của rác đại dương là thật?",
    optionsVi: ["25%", "50%", "83%", "100%"],
    correctIndex: 2,
    explanationEn: "The passage states: 'In 83 percent of cases, the perceived dangers of ocean trash were proven true.'",
    explanationVi: "Bài nêu: trong 83% trường hợp, mối nguy hại được cho là do rác đại dương đã được chứng minh là thật.",
  },
  "cam15-test1-p1": {
    questionEn: "What did the British receive from the Dutch in exchange for giving up the island of Run?",
    optionsEn: ["A large sum of gold", "The island of Manhattan", "Control of the Banda Islands", "A share of the VOC company"],
    questionVi: "Người Anh nhận được gì từ người Hà Lan để đổi lấy đảo Run?",
    optionsVi: ["Một khoản vàng lớn", "Đảo Manhattan", "Quyền kiểm soát quần đảo Banda", "Cổ phần trong công ty VOC"],
    correctIndex: 1,
    explanationEn: "The passage explains the Dutch traded a distant island — Manhattan — for Run, which is how New Amsterdam became New York.",
    explanationVi: "Bài nêu Hà Lan đổi đảo Manhattan xa xôi để lấy đảo Run, dẫn đến New Amsterdam trở thành New York.",
  },
  "cam15-test1-p2": {
    questionEn: "According to research at the UK's Transport Research Laboratory, what is the primary cause of most road collisions?",
    optionsEn: ["Poor road design", "Bad weather conditions", "Human error", "Vehicle mechanical failure"],
    questionVi: "Theo nghiên cứu của Transport Research Laboratory (Anh), nguyên nhân chính của hầu hết va chạm giao thông là gì?",
    optionsVi: ["Thiết kế đường kém", "Thời tiết xấu", "Lỗi con người", "Hỏng hóc cơ khí xe"],
    correctIndex: 2,
    explanationEn: "The passage states more than 90 percent of road collisions involve human error, which is the primary cause in the vast majority.",
    explanationVi: "Bài nêu hơn 90% va chạm giao thông có yếu tố lỗi con người, và đây là nguyên nhân chính trong đa số trường hợp.",
  },
  "cam15-test1-p3": {
    questionEn: "How does Ran Fiennes define an explorer, according to the passage?",
    optionsEn: [
      "Someone who simply enjoys travelling to new places",
      "Someone who has done something no human has done before, and also something scientifically useful",
      "Someone who writes books about far-off places",
      "Someone who studies exploration history at university",
    ],
    questionVi: "Ran Fiennes định nghĩa 'explorer' (nhà thám hiểm) như thế nào?",
    optionsVi: [
      "Người chỉ thích du lịch đến nơi mới",
      "Người đã làm điều chưa ai từng làm, và cũng làm điều có ích cho khoa học",
      "Người viết sách về những nơi xa xôi",
      "Người học lịch sử thám hiểm ở đại học",
    ],
    correctIndex: 1,
    explanationEn: "Fiennes says: 'An explorer is someone who has done something that no human has done before – and also done something scientifically useful.'",
    explanationVi: "Fiennes nói nhà thám hiểm là người làm điều chưa ai từng làm, và cũng làm điều có ích cho khoa học.",
  },
  "cam15-test2-p1": {
    questionEn: "What does the writer suggest urban engineers could learn from choreographers?",
    optionsEn: [
      "How to design faster road networks",
      "Techniques for 'thinking with the body' to imagine how movement will feel",
      "How to reduce construction costs",
      "How to build taller buildings",
    ],
    questionVi: "Người viết gợi ý kỹ sư đô thị có thể học được gì từ các biên đạo múa?",
    optionsVi: [
      "Cách thiết kế mạng lưới đường nhanh hơn",
      "Kỹ thuật 'suy nghĩ bằng cơ thể' để tưởng tượng cảm giác của sự di chuyển",
      "Cách giảm chi phí xây dựng",
      "Cách xây nhà cao hơn",
    ],
    correctIndex: 1,
    explanationEn: "The passage describes choreographers 'thinking with the body' to simulate outcomes engineers could use to design for emotional and physical effects.",
    explanationVi: "Bài mô tả biên đạo múa 'suy nghĩ bằng cơ thể' để mô phỏng kết quả, kỹ sư có thể dùng cách này để thiết kế hiệu ứng cảm xúc và vật lý.",
  },
  "cam15-test2-p2": {
    questionEn: "According to Ben Novak, what is the ultimate goal of the passenger pigeon de-extinction project?",
    optionsEn: [
      "To create a zoo attraction",
      "To replace the extinct species with a suitable ecological replacement that restores forest disturbance",
      "To sell pigeons to collectors",
      "To study pigeon DNA for medical research only",
    ],
    questionVi: "Theo Ben Novak, mục tiêu cuối cùng của dự án phục sinh chim bồ câu di cư (passenger pigeon) là gì?",
    optionsVi: [
      "Tạo điểm tham quan cho sở thú",
      "Thay thế loài đã tuyệt chủng bằng một loài thay thế sinh thái phù hợp, khôi phục sự xáo trộn rừng",
      "Bán chim bồ câu cho người sưu tầm",
      "Chỉ nghiên cứu DNA chim để phục vụ y học",
    ],
    correctIndex: 1,
    explanationEn: "Novak explains the goal is a suitable replacement that could re-establish the forest disturbance passenger pigeons once caused.",
    explanationVi: "Novak giải thích mục tiêu là loài thay thế phù hợp có thể khôi phục sự xáo trộn rừng mà chim bồ câu di cư từng tạo ra.",
  },
  "cam15-test2-p3": {
    questionEn: "According to the San Diego study, how was dominant laughter characterised?",
    optionsEn: [
      "Quiet and low in pitch",
      "Higher in pitch, louder, and more variable in tone than submissive laughter",
      "Identical to submissive laughter",
      "Only produced by low-status individuals",
    ],
    questionVi: "Theo nghiên cứu ở San Diego, tiếng cười 'dominant' (áp đảo) có đặc điểm gì?",
    optionsVi: [
      "Nhẹ và trầm",
      "Cao hơn, to hơn, và biến đổi âm điệu nhiều hơn tiếng cười 'submissive'",
      "Giống hoàn toàn tiếng cười submissive",
      "Chỉ do người có địa vị thấp tạo ra",
    ],
    correctIndex: 1,
    explanationEn: "The passage states dominant laughter was higher in pitch, louder, and more variable in tone than submissive laughter.",
    explanationVi: "Bài nêu tiếng cười dominant cao hơn, to hơn, và biến đổi âm điệu nhiều hơn tiếng cười submissive.",
  },
  "cam15-test3-p1": {
    questionEn: "What especially fascinated Henry Moore during his 1925 visit to the Trocadero Museum in Paris?",
    optionsEn: [
      "A collection of modern British paintings",
      "A cast of a Mayan sculpture of the rain spirit",
      "An exhibition of Egyptian mummies",
      "A display of Picasso's early sketches",
    ],
    questionVi: "Điều gì đặc biệt cuốn hút Henry Moore khi ông thăm bảo tàng Trocadero ở Paris năm 1925?",
    optionsVi: [
      "Bộ sưu tập tranh Anh hiện đại",
      "Bản đúc tượng thần mưa của người Maya",
      "Triển lãm xác ướp Ai Cập",
      "Bộ ký họa đầu tay của Picasso",
    ],
    correctIndex: 1,
    explanationEn: "The passage says Moore was impressed by a cast of a Mayan sculpture of the rain spirit and became fascinated with it.",
    explanationVi: "Bài nêu Moore bị cuốn hút bởi bản đúc tượng thần mưa của người Maya.",
  },
  "cam15-test3-p2": {
    questionEn: "What is the Desolenator's main selling point compared with standard desalination techniques?",
    optionsEn: [
      "It uses a diesel generator for extra power",
      "It doesn't require a generated power supply — just sunlight",
      "It can produce unlimited amounts of water",
      "It works only with seawater",
    ],
    questionVi: "Điểm bán hàng chính của Desolenator so với kỹ thuật khử muối thông thường là gì?",
    optionsVi: [
      "Dùng máy phát diesel để có thêm điện",
      "Không cần nguồn điện tạo ra — chỉ cần ánh nắng",
      "Có thể sản xuất nước không giới hạn",
      "Chỉ hoạt động với nước biển",
    ],
    correctIndex: 1,
    explanationEn: "The passage states its main selling point is that, unlike standard desalination, it doesn't require a generated power supply — just sunlight.",
    explanationVi: "Bài nêu điểm bán hàng chính là không cần nguồn điện tạo ra, chỉ cần ánh nắng, khác với khử muối thông thường.",
  },
  "cam15-test3-p3": {
    questionEn: "What did Tehrani find was the best-preserved element across variants of Little Red Riding Hood?",
    optionsEn: [
      "The cautionary, survival-relevant messages",
      "The gruesome, fearful details, such as the wolf eating the grandmother",
      "The exact identity of the characters",
      "The setting of the story",
    ],
    questionVi: "Tehrani phát hiện yếu tố nào được bảo tồn tốt nhất qua các phiên bản Cô bé quàng khăn đỏ?",
    optionsVi: [
      "Thông điệp cảnh báo, liên quan sinh tồn",
      "Chi tiết ghê rợn, đáng sợ, như chó sói ăn bà",
      "Danh tính chính xác của nhân vật",
      "Bối cảnh câu chuyện",
    ],
    correctIndex: 1,
    explanationEn: "The passage says fear — the blood-thirsty and gruesome aspects — turned out to be the best preserved of all, not the cautionary messages.",
    explanationVi: "Bài nêu nỗi sợ — các yếu tố ghê rợn — được bảo tồn tốt nhất, không phải thông điệp cảnh báo.",
  },
  "cam15-test4-p1": {
    questionEn: "Why is the huarango tree so well suited to the arid valleys of southern Peru?",
    optionsEn: [
      "It needs very little water to survive",
      "It has the longest roots of any tree in the world, reaching deep water sources",
      "It grows quickly and needs no maintenance",
      "It only grows in sandy soil",
    ],
    questionVi: "Tại sao cây huarango lại thích hợp với các thung lũng khô hạn ở nam Peru?",
    optionsVi: [
      "Cần rất ít nước để sống",
      "Có rễ dài nhất trong các loài cây, chạm được nguồn nước sâu",
      "Mọc nhanh và không cần chăm sóc",
      "Chỉ mọc trên đất cát",
    ],
    correctIndex: 1,
    explanationEn: "The passage says the huarango has the longest roots of any tree in the world, stretching 50-80 metres down to water.",
    explanationVi: "Bài nêu huarango có rễ dài nhất trong các loài cây, sâu 50-80 mét để chạm nguồn nước.",
  },
  "cam15-test4-p2": {
    questionEn: "What did the brain-imaging study find about silbadores listening to Silbo?",
    optionsEn: [
      "No brain regions were activated at all",
      "The left temporal lobe, usually linked to spoken language, was engaged",
      "Only the visual cortex responded",
      "Their brain activity was identical to non-whistlers",
    ],
    questionVi: "Nghiên cứu hình ảnh não phát hiện gì khi silbadores nghe Silbo?",
    optionsVi: [
      "Không vùng não nào được kích hoạt",
      "Thùy thái dương trái, thường liên quan ngôn ngữ nói, được kích hoạt",
      "Chỉ vùng vỏ não thị giác phản ứng",
      "Hoạt động não giống hoàn toàn người không biết huýt sáo",
    ],
    correctIndex: 1,
    explanationEn: "The passage states the left temporal lobe, usually associated with spoken language, was engaged during processing of Silbo.",
    explanationVi: "Bài nêu thùy thái dương trái, thường liên quan ngôn ngữ nói, được kích hoạt khi xử lý Silbo.",
  },
  "cam15-test4-p3": {
    questionEn: "According to the writer, who has the ultimate responsibility for changing environmentally damaging business practices?",
    optionsEn: [
      "Company shareholders alone",
      "The public, directly or through their politicians",
      "International courts",
      "Business directors' personal morals",
    ],
    questionVi: "Theo tác giả, ai chịu trách nhiệm cuối cùng trong việc thay đổi các thực hành kinh doanh gây hại môi trường?",
    optionsVi: [
      "Chỉ các cổ đông công ty",
      "Công chúng, trực tiếp hoặc qua các chính trị gia của họ",
      "Tòa án quốc tế",
      "Đạo đức cá nhân của giám đốc doanh nghiệp",
    ],
    correctIndex: 1,
    explanationEn: "The writer argues it is the public, directly or through politicians, that has the power to make destructive policies unprofitable and illegal.",
    explanationVi: "Tác giả cho rằng công chúng, trực tiếp hoặc qua chính trị gia, có quyền lực khiến chính sách gây hại trở nên bất hợp pháp và không sinh lời.",
  },
};
