import type { QuickCheckQuiz } from "@/lib/reading/passage-quiz";

export const CAMBRIDGE_13_QUIZ: Record<string, QuickCheckQuiz> = {
  "cam13-test1-p1": {
    questionEn: "According to research cited in the passage, what proportion of visitor satisfaction is driven by activities?",
    optionsEn: [
      "74%",
      "26%",
      "50%",
      "9%",
    ],
    questionVi: "Theo nghiên cứu được trích dẫn trong bài, bao nhiêu phần trăm sự hài lòng của du khách đến từ các hoạt động?",
    optionsVi: [
      "74%",
      "26%",
      "50%",
      "9%",
    ],
    correctIndex: 0,
    explanationEn: "The passage states that activities are the key driver of visitor satisfaction, contributing 74%, while transport and accommodation account for the remaining 26%.",
    explanationVi: "Bài nêu hoạt động là yếu tố chính tạo sự hài lòng (74%), còn giao thông và chỗ ở chiếm 26% còn lại.",
  },
  "cam13-test1-p2": {
    questionEn: "What did Sandi Mann find about people who had been made to feel bored?",
    optionsEn: [
      "They came up with more creative ideas than a control group",
      "They became permanently depressed",
      "They were unable to focus on any task at all",
      "They preferred distraction through social media",
    ],
    questionVi: "Sandi Mann phát hiện điều gì về những người bị tạo cảm giác chán nản?",
    optionsVi: [
      "Họ đưa ra nhiều ý tưởng sáng tạo hơn nhóm đối chứng",
      "Họ rơi vào trầm cảm lâu dài",
      "Họ hoàn toàn không thể tập trung vào bất kỳ việc gì",
      "Họ thích giải trí bằng mạng xã hội",
    ],
    correctIndex: 0,
    explanationEn: "Mann's experiments found that people bored by copying numbers from a phone book produced more creative ideas about using a polystyrene cup than a control group.",
    explanationVi: "Thí nghiệm của Mann cho thấy người chán nản vì chép số điện thoại đưa ra nhiều ý tưởng sáng tạo hơn nhóm đối chứng.",
  },
  "cam13-test1-p3": {
    questionEn: "What is a key difference between Aaron and the Painting Fool?",
    optionsEn: [
      "Aaron uses more expensive materials",
      "The Painting Fool has sold more artworks",
      "The Painting Fool can find its own subject matter online",
      "Aaron has been exhibited in more prestigious galleries",
    ],
    questionVi: "Điểm khác biệt chính giữa Aaron và Painting Fool là gì?",
    optionsVi: [
      "Aaron dùng nguyên liệu đắt hơn",
      "Painting Fool bán được nhiều tác phẩm hơn",
      "Painting Fool có thể tự tìm chủ đề trên internet",
      "Aaron được trưng bày ở nhiều phòng tranh danh tiếng hơn",
    ],
    correctIndex: 2,
    explanationEn: "Unlike Aaron, the Painting Fool needs minimal direction and can come up with its own concepts by searching online and trawling social media.",
    explanationVi: "Khác Aaron, Painting Fool chỉ cần hướng dẫn tối thiểu và tự tìm ý tưởng bằng cách lướt web và mạng xã hội.",
  },
  "cam13-test2-p1": {
    questionEn: "How did Arab merchants transport cinnamon from India to the Mediterranean?",
    optionsEn: [
      "On camels via an overland route",
      "By ship directly across the Indian Ocean",
      "Through Portuguese-controlled sea routes",
      "By train to Alexandria",
    ],
    questionVi: "Thương nhân Ả Rập vận chuyển quế từ Ấn Độ đến Địa Trung Hải bằng cách nào?",
    optionsVi: [
      "Lạc đà đi đường bộ",
      "Tàu thẳng qua Ấn Độ Dương",
      "Tuyến biển do Bồ Đào Nha kiểm soát",
      "Tàu hỏa đến Alexandria",
    ],
    correctIndex: 0,
    explanationEn: "Arab merchants took cinnamon from India on camels via an overland route to the Mediterranean, ending in Alexandria.",
    explanationVi: "Thương nhân Ả Rập đưa quế từ Ấn Độ bằng lạc đà qua đường bộ đến Địa Trung Hải, kết thúc tại Alexandria.",
  },
  "cam13-test2-p2": {
    questionEn: "What did Markus Heinrichs' 2005 experiment find about participants who sniffed oxytocin?",
    optionsEn: [
      "They invested more money than those given a placebo",
      "They became less trusting in all situations",
      "They showed more envy when others won a game",
      "They cooperated less with complete strangers",
    ],
    questionVi: "Thí nghiệm năm 2005 của Markus Heinrichs phát hiện gì về người hít oxytocin?",
    optionsVi: [
      "Họ đầu tư nhiều tiền hơn nhóm dùng thuốc giả",
      "Họ kém tin tưởng trong mọi tình huống",
      "Họ ghen tị hơn khi người khác thắng",
      "Họ hợp tác kém hơn với người lạ",
    ],
    correctIndex: 0,
    explanationEn: "Heinrichs found that participants who sniffed oxytocin via a nasal spray invested more money than those who received a placebo.",
    explanationVi: "Heinrichs thấy người hít oxytocin qua xịt mũi đầu tư nhiều tiền hơn nhóm dùng thuốc giả.",
  },
  "cam13-test2-p3": {
    questionEn: "Why did Coach avoid cutting prices across its range during the 2008 economic downturn?",
    optionsEn: [
      "Research showed customers wanted only lower-priced brands",
      "Competitors had already reduced all their prices",
      "It wanted to protect its image as a luxury brand",
      "The Poppy range could not be produced cheaply enough",
    ],
    questionVi: "Tại sao Coach không giảm giá toàn bộ sản phẩm trong suy thoái kinh tế 2008?",
    optionsVi: [
      "Nghiên cứu cho thấy khách chỉ muốn thương hiệu rẻ",
      "Đối thủ đã hạ giá toàn bộ",
      "Họ muốn bảo vệ hình ảnh thương hiệu xa xỉ",
      "Dòng Poppy không thể sản xuất đủ rẻ",
    ],
    correctIndex: 2,
    explanationEn: "Coach had been a symbol of opulence for nearly 70 years, and lowering prices would have risked cheapening the brand's image.",
    explanationVi: "Coach là biểu tượng xa xỉ gần 70 năm; hạ giá toàn diện sẽ làm loãng hình ảnh thương hiệu.",
  },
  "cam13-test3-p1": {
    questionEn: "Besides being a drink, what does coconut water provide for other plants?",
    optionsEn: [
      "Hormones that encourage faster growth and higher yields",
      "Salt that helps seeds tolerate sea water",
      "Charcoal used in various industries",
      "Fibre for manufacturing ropes",
    ],
    questionVi: "Ngoài làm đồ uống, nước dừa còn cung cấp gì cho các loài thực vật khác?",
    optionsVi: [
      "Hormone kích thích sinh trưởng nhanh và năng suất cao hơn",
      "Muối giúp hạt chịu nước biển",
      "Than củi dùng trong công nghiệp",
      "Sợi xơ để làm dây thừng",
    ],
    correctIndex: 0,
    explanationEn: "The passage says coconut water provides hormones which encourage other plants to grow more rapidly and produce higher yields.",
    explanationVi: "Bài nêu nước dừa cung cấp hormone giúp cây khác phát triển nhanh hơn và cho năng suất cao hơn.",
  },
  "cam13-test3-p2": {
    questionEn: "What did Nairán Ramirez-Esparza's study find about one-on-one baby talk?",
    optionsEn: [
      "It had no effect on vocabulary at age two",
      "More one-on-one baby talk led to more babbling and later produced more words",
      "It only helped children from higher socioeconomic backgrounds",
      "It was less effective than fathers' normal speech",
    ],
    questionVi: "Nghiên cứu của Nairán Ramirez-Esparza phát hiện gì về baby talk một-một?",
    optionsVi: [
      "Không ảnh hưởng vốn từ lúc 2 tuổi",
      "Nhiều baby talk một-một giúp bé bập bẹ hơn và sau này nói nhiều từ hơn",
      "Chỉ có ích với trẻ từ gia đình khá giả",
      "Kém hiệu quả hơn giọng nói bình thường của cha",
    ],
    correctIndex: 1,
    explanationEn: "Ramirez-Esparza found that the more parents used baby talk one-on-one, the more babies babbled, and the more words they produced later in life.",
    explanationVi: "Ramirez-Esparza thấy càng nhiều baby talk một-một thì bé càng bập bẹ nhiều và sau này có vốn từ lớn hơn.",
  },
  "cam13-test3-p3": {
    questionEn: "What did Dixit and Hodell's research provide regarding north-western India?",
    optionsEn: [
      "The first definitive evidence of climate change affecting the region",
      "Proof that invasion alone caused the Harappan decline",
      "Evidence that all Harappan cities shared identical drainage systems",
      "Confirmation that glacier-fed rivers never changed course",
    ],
    questionVi: "Nghiên cứu của Dixit và Hodell cung cấp gì về tây bắc Ấn Độ?",
    optionsVi: [
      "Bằng chứng xác định đầu tiên về biến đổi khí hậu tác động vùng này",
      "Chứng minh chỉ xâm lược gây suy tàn Harappa",
      "Bằng chứng mọi thành phố Harappa có hệ thoát nước giống nhau",
      "Xác nhận sông từ sông băng không bao giờ đổi hướng",
    ],
    correctIndex: 0,
    explanationEn: "Their research provided the first definitive evidence for climate change affecting the plains of north-western India, showing a drought when evaporation exceeded rainfall.",
    explanationVi: "Nghiên cứu của họ đưa bằng chứng xác định đầu tiên về biến đổi khí hậu ở đồng bằng tây bắc Ấn Độ, với hạn hán khi bốc hơi vượt lượng mưa.",
  },
  "cam13-test4-p1": {
    questionEn: "Why was the Suez Canal of little use to sailing ships such as Cutty Sark?",
    optionsEn: [
      "They needed strong ocean winds and had to sail a much greater distance",
      "The canal was too shallow for cargo ships",
      "Steam ships blocked their access to the canal",
      "The canal had not opened until after Cutty Sark was scrapped",
    ],
    questionVi: "Tại sao kênh Suez ít hữu ích với tàu buồm như Cutty Sark?",
    optionsVi: [
      "Chúng cần gió biển mạnh và phải đi quãng đường dài hơn nhiều",
      "Kênh quá nông cho tàu chở hàng",
      "Tàu hơi nước chặn quyền vào kênh",
      "Kênh mở sau khi Cutty Sark bị tháo dỡ",
    ],
    correctIndex: 0,
    explanationEn: "The passage explains that while steam ships could use the canal's direct route, sailing ships needed stronger ocean winds and so had to sail a far greater distance.",
    explanationVi: "Bài giải thích tàu hơi nước dùng tuyến kênh trực tiếp, còn tàu buồm cần gió đại dương mạnh nên phải đi xa hơn nhiều.",
  },
  "cam13-test4-p2": {
    questionEn: "According to the passage, what proportion of our food is grown in soil?",
    optionsEn: [
      "95%",
      "60%",
      "35%",
      "100%",
    ],
    questionVi: "Theo bài, bao nhiêu phần trăm thực phẩm của chúng ta được trồng từ đất?",
    optionsVi: [
      "95%",
      "60%",
      "35%",
      "100%",
    ],
    correctIndex: 0,
    explanationEn: "The passage states that soil grows 95% of our food.",
    explanationVi: "Bài nêu đất trồng 95% lượng thực phẩm của chúng ta.",
  },
  "cam13-test4-p3": {
    questionEn: "What is the reviewer's attitude toward advocates of positive psychology?",
    optionsEn: [
      "They reject Bentham too strongly",
      "They are over-influenced by studying Bentham's theories",
      "They offer a genuinely new approach to happiness",
      "They are ignorant about important ideas they should consider",
    ],
    questionVi: "Thái độ của người viết review đối với những người ủng hộ tâm lý học tích cực là gì?",
    optionsVi: [
      "Họ phản đối Bentham quá mạnh",
      "Họ bị ảnh hưởng quá nhiều bởi lý thuyết Bentham",
      "Họ có cách tiếp cận mới thực sự về hạnh phúc",
      "Họ thiếu hiểu biết về các tư tưởng quan trọng cần xem xét",
    ],
    correctIndex: 3,
    explanationEn: "The reviewer says advocates write as if nothing important had been thought about happiness before them, and are 'illiterate in the history of ideas'.",
    explanationVi: "Người review cho rằng họ viết như thể chưa ai nghiên cứu hạnh phúc trước đó, và 'mù lịch sử tư tưởng'.",
  },
};
