import type { QuickCheckQuiz } from "@/lib/reading/passage-quiz";

export const CAMBRIDGE_16_21_QUIZ: Record<string, QuickCheckQuiz> = {
  "cam16-test1-p1": {
    questionEn: "Why is the loss of sea ice especially dangerous for polar bears?",
    optionsEn: [
      "They use sea ice as a platform to hunt seals",
      "They need ice to build dens in cities",
      "Sea ice is their only source of drinking water",
      "They migrate south only when ice expands",
    ],
    questionVi: "Vì sao mất băng biển đặc biệt nguy hiểm với gấu Bắc Cực?",
    optionsVi: [
      "Chúng dùng băng biển làm nền để săn hải cẩu",
      "Chúng cần băng để làm hang trong thành phố",
      "Băng biển là nguồn nước uống duy nhất",
      "Chúng chỉ di cư về phía nam khi băng mở rộng",
    ],
    correctIndex: 0,
    explanationEn: "Polar bears rely on sea ice to reach and hunt seals; shrinking ice reduces hunting opportunities.",
    explanationVi: "Gấu Bắc Cực dựa vào băng biển để tiếp cận và săn hải cẩu; băng thu hẹp làm giảm cơ hội săn mồi.",
  },
  "cam16-test1-p2": {
    questionEn: "Who is traditionally credited with designing the Step Pyramid of Djoser?",
    optionsEn: ["Imhotep", "Cleopatra", "Tutankhamun", "Ramses II"],
    questionVi: "Ai thường được cho là thiết kế Kim tự tháp bậc thang của Djoser?",
    optionsVi: ["Imhotep", "Cleopatra", "Tutankhamun", "Ramses II"],
    correctIndex: 0,
    explanationEn: "The Step Pyramid at Saqqara is linked to the architect-priest Imhotep under Pharaoh Djoser.",
    explanationVi: "Kim tự tháp bậc thang ở Saqqara gắn với kiến trúc sư–tu sĩ Imhotep dưới thời pharaông Djoser.",
  },
  "cam16-test1-p3": {
    questionEn: "Which trend is commonly discussed when predicting the future of work?",
    optionsEn: [
      "Greater automation and changing skill needs",
      "The permanent end of all office jobs tomorrow",
      "A return to only agricultural labour",
      "Banning remote work worldwide",
    ],
    questionVi: "Xu hướng nào thường được bàn khi dự đoán tương lai việc làm?",
    optionsVi: [
      "Tự động hóa nhiều hơn và nhu cầu kỹ năng thay đổi",
      "Chấm dứt vĩnh viễn mọi việc văn phòng vào ngày mai",
      "Quay lại chỉ làm nông nghiệp",
      "Cấm làm việc từ xa trên toàn thế giới",
    ],
    correctIndex: 0,
    explanationEn: "Discussions of future work focus on automation, new skills, and flexible or remote patterns of employment.",
    explanationVi: "Bàn về tương lai việc làm tập trung vào tự động hóa, kỹ năng mới và hình thức làm việc linh hoạt/từ xa.",
  },
  "cam16-test2-p1": {
    questionEn: "What is the White Horse of Uffington?",
    optionsEn: [
      "A prehistoric chalk hill figure in England",
      "A Roman marble statue in Rome",
      "A modern theme-park ride",
      "A Viking longship carving in Norway",
    ],
    questionVi: "White Horse of Uffington là gì?",
    optionsVi: [
      "Hình ngựa khắc phấn tiền sử trên đồi ở Anh",
      "Tượng đá cẩm thạch La Mã ở Rome",
      "Trò chơi công viên giải trí hiện đại",
      "Hình khắc tàu Viking ở Na Uy",
    ],
    correctIndex: 0,
    explanationEn: "It is a famous prehistoric chalk figure cut into a hillside in Oxfordshire, England.",
    explanationVi: "Đây là hình khắc phấn tiền sử nổi tiếng trên sườn đồi ở Oxfordshire, Anh.",
  },
  "cam16-test2-p2": {
    questionEn: "What is the central subject of Ed Yong's book I Contain Multitudes?",
    optionsEn: [
      "How microbes shape animal and human life",
      "How to build pyramids in Egypt",
      "The history of railway travel",
      "Rules for competitive chess",
    ],
    questionVi: "Chủ đề trung tâm của sách I Contain Multitudes của Ed Yong là gì?",
    optionsVi: [
      "Cách vi sinh vật định hình đời sống động vật và con người",
      "Cách xây kim tự tháp ở Ai Cập",
      "Lịch sử đường sắt",
      "Luật cờ vua thi đấu",
    ],
    correctIndex: 0,
    explanationEn: "The book explores the microbiome — the vast world of microbes living in and on animals, including humans.",
    explanationVi: "Sách khám phá microbiome — thế giới vi sinh vật sống trong và trên động vật, gồm cả con người.",
  },
  "cam16-test2-p3": {
    questionEn: "According to research on wise decisions, what often helps people choose better?",
    optionsEn: [
      "Combining careful thinking with awareness of bias",
      "Always guessing immediately without information",
      "Ignoring every expert opinion",
      "Making choices only when angry",
    ],
    questionVi: "Theo nghiên cứu về quyết định khôn ngoan, điều gì thường giúp chọn tốt hơn?",
    optionsVi: [
      "Kết hợp suy nghĩ kỹ với nhận thức về thiên kiến",
      "Luôn đoán ngay mà không cần thông tin",
      "Bỏ qua mọi ý kiến chuyên gia",
      "Chỉ quyết định khi đang giận",
    ],
    correctIndex: 0,
    explanationEn: "Wise decision-making draws on deliberation and recognising cognitive biases, not pure impulse.",
    explanationVi: "Quyết định khôn ngoan dựa trên cân nhắc và nhận ra thiên kiến nhận thức, không chỉ theo xung động.",
  },
  "cam16-test3-p1": {
    questionEn: "What was a key purpose of Roman shipbuilding and navigation?",
    optionsEn: [
      "Moving people, troops and trade goods across the Mediterranean",
      "Exploring Antarctica exclusively",
      "Building underwater cities",
      "Racing cars on Roman roads",
    ],
    questionVi: "Mục đích chính của đóng tàu và hàng hải La Mã là gì?",
    optionsVi: [
      "Vận chuyển người, quân và hàng hóa quanh Địa Trung Hải",
      "Chỉ thám hiểm Nam Cực",
      "Xây thành phố dưới nước",
      "Đua xe trên đường La Mã",
    ],
    correctIndex: 0,
    explanationEn: "Roman fleets and merchant ships supported military movement and Mediterranean trade.",
    explanationVi: "Hạm đội và tàu buôn La Mã phục vụ di chuyển quân sự và thương mại Địa Trung Hải.",
  },
  "cam16-test3-p2": {
    questionEn: "How is climate change linked to finds in Norway's glaciers?",
    optionsEn: [
      "Melting ice reveals previously buried ancient artefacts",
      "Glaciers grow and hide all archaeology forever",
      "Warming creates brand-new Roman cities overnight",
      "Ice melt only produces modern plastic waste",
    ],
    questionVi: "Biến đổi khí hậu liên quan thế nào đến hiện vật ở sông băng Na Uy?",
    optionsVi: [
      "Băng tan lộ ra hiện vật cổ trước đây bị chôn vùi",
      "Sông băng lớn lên và che khảo cổ mãi mãi",
      "Nóng lên tạo thành phố La Mã mới trong một đêm",
      "Tan băng chỉ tạo rác nhựa hiện đại",
    ],
    correctIndex: 0,
    explanationEn: "As glaciers and ice patches shrink, organic and other artefacts once preserved in ice become exposed.",
    explanationVi: "Khi sông băng và khối băng thu hẹp, hiện vật (kể cả hữu cơ) từng được bảo quản trong băng lộ ra.",
  },
  "cam16-test3-p3": {
    questionEn: "What does a 'plant thermometer' idea refer to in springtime growth research?",
    optionsEn: [
      "Plants timing growth in response to temperature cues",
      "A metal tool farmers use to cook seeds",
      "A device that only measures ocean depth",
      "A pesticide that freezes insects",
    ],
    questionVi: "Ý tưởng 'nhiệt kế thực vật' trong nghiên cứu sinh trưởng mùa xuân ám chỉ gì?",
    optionsVi: [
      "Cây định thời gian sinh trưởng theo tín hiệu nhiệt độ",
      "Dụng cụ kim loại nông dân dùng để nấu hạt",
      "Thiết bị chỉ đo độ sâu đại dương",
      "Thuốc trừ sâu làm đóng băng côn trùng",
    ],
    correctIndex: 0,
    explanationEn: "Researchers describe how plants sense temperature and other cues to time budding and flowering.",
    explanationVi: "Nhà nghiên cứu mô tả cách thực vật cảm nhận nhiệt độ và tín hiệu khác để định thời nảy chồi và ra hoa.",
  },
  "cam16-test4-p1": {
    questionEn: "What were many Roman tunnels primarily built to do?",
    optionsEn: [
      "Carry water or provide underground passage for infrastructure",
      "Store modern electric cars",
      "Host Olympic swimming races",
      "Grow tropical forests indoors",
    ],
    questionVi: "Nhiều đường hầm La Mã chủ yếu được xây để làm gì?",
    optionsVi: [
      "Dẫn nước hoặc tạo lối ngầm cho hạ tầng",
      "Chứa xe điện hiện đại",
      "Tổ chức đua bơi Olympic",
      "Trồng rừng nhiệt đới trong nhà",
    ],
    correctIndex: 0,
    explanationEn: "Roman tunnelling often served aqueducts, drainage and other engineering needs underground.",
    explanationVi: "Đào hầm La Mã thường phục vụ dẫn nước, thoát nước và nhu cầu kỹ thuật dưới lòng đất.",
  },
  "cam16-test4-p2": {
    questionEn: "What change in reading habits is widely associated with the digital age?",
    optionsEn: [
      "More screen-based reading and different attention patterns",
      "People completely stopped reading anything",
      "Books became illegal in every country",
      "Only children were allowed to use print",
    ],
    questionVi: "Thay đổi thói quen đọc nào thường gắn với thời đại số?",
    optionsVi: [
      "Đọc trên màn hình nhiều hơn và kiểu chú ý khác",
      "Người ta hoàn toàn ngừng đọc mọi thứ",
      "Sách bị cấm ở mọi quốc gia",
      "Chỉ trẻ em được dùng ấn phẩm in",
    ],
    correctIndex: 0,
    explanationEn: "Digital media shifted reading toward screens, skimming and new patterns of attention.",
    explanationVi: "Truyền thông số chuyển việc đọc sang màn hình, đọc lướt và kiểu chú ý mới.",
  },
  "cam16-test4-p3": {
    questionEn: "What do surveys about attitudes towards AI often reveal?",
    optionsEn: [
      "A mix of optimism about benefits and concern about risks",
      "Universal agreement that AI has no impact",
      "That nobody has ever heard of computers",
      "That AI only exists in ancient myths",
    ],
    questionVi: "Khảo sát về thái độ với AI thường cho thấy gì?",
    optionsVi: [
      "Vừa lạc quan về lợi ích vừa lo về rủi ro",
      "Đồng thuận tuyệt đối rằng AI không có tác động",
      "Chưa ai từng nghe về máy tính",
      "AI chỉ tồn tại trong thần thoại cổ",
    ],
    correctIndex: 0,
    explanationEn: "Public attitudes toward AI typically combine hopes for usefulness with worries about ethics, jobs and trust.",
    explanationVi: "Thái độ công chúng với AI thường kết hợp kỳ vọng hữu ích và lo ngại về đạo đức, việc làm và niềm tin.",
  },
  "cam21-test1-p1": {
    questionEn: "Who were the Davies Sisters best known as?",
    optionsEn: [
      "Welsh art collectors and patrons",
      "Roman tunnel engineers",
      "Arctic polar-bear biologists",
      "Inventors of the first smartphone",
    ],
    questionVi: "Các chị em Davies nổi tiếng nhất với vai trò gì?",
    optionsVi: [
      "Nhà sưu tập và bảo trợ nghệ thuật người Wales",
      "Kỹ sư đường hầm La Mã",
      "Nhà sinh học gấu Bắc Cực",
      "Người phát minh smartphone đầu tiên",
    ],
    correctIndex: 0,
    explanationEn: "Gwendoline and Margaret Davies assembled a major art collection and supported cultural life in Wales.",
    explanationVi: "Gwendoline và Margaret Davies xây dựng bộ sưu tập nghệ thuật lớn và hỗ trợ đời sống văn hóa ở Wales.",
  },
  "cam21-test1-p2": {
    questionEn: "Why do writers argue that we need silence?",
    optionsEn: [
      "Quiet supports concentration, rest and mental wellbeing",
      "Silence makes all machines run faster",
      "Noise has no effect on human health",
      "People sleep better only in stadiums",
    ],
    questionVi: "Vì sao người viết cho rằng chúng ta cần sự im lặng?",
    optionsVi: [
      "Yên tĩnh hỗ trợ tập trung, nghỉ ngơi và sức khỏe tinh thần",
      "Im lặng làm mọi máy chạy nhanh hơn",
      "Tiếng ồn không ảnh hưởng sức khỏe con người",
      "Người ta chỉ ngủ ngon hơn trong sân vận động",
    ],
    correctIndex: 0,
    explanationEn: "Arguments for silence stress recovery from noise pollution and better focus and wellbeing.",
    explanationVi: "Lập luận về im lặng nhấn mạnh phục hồi khỏi ô nhiễm tiếng ồn và tập trung cũng như an lạc tốt hơn.",
  },
  "cam21-test1-p3": {
    questionEn: "What is Ulbe Bosma's The World of Sugar mainly about?",
    optionsEn: [
      "The global history of sugar as a traded commodity",
      "A cookbook of only salty recipes",
      "How to grow polar bears on farms",
      "The biography of a football manager",
    ],
    questionVi: "Sách The World of Sugar của Ulbe Bosma chủ yếu nói về gì?",
    optionsVi: [
      "Lịch sử toàn cầu của đường như một hàng hóa thương mại",
      "Sách nấu ăn chỉ toàn món mặn",
      "Cách nuôi gấu Bắc Cực trên nông trại",
      "Tiểu sử một huấn luyện viên bóng đá",
    ],
    correctIndex: 0,
    explanationEn: "The book reviews how sugar shaped economies, labour and colonial trade across centuries.",
    explanationVi: "Sách xem xét cách đường định hình kinh tế, lao động và thương mại thuộc địa qua nhiều thế kỷ.",
  },
  "cam21-test2-p1": {
    questionEn: "What do scientists study when asking whether animals dream?",
    optionsEn: [
      "Sleep stages such as REM and related brain activity",
      "Only the colour of their fur",
      "How fast they can type",
      "Whether they pay taxes",
    ],
    questionVi: "Khi hỏi động vật có mơ không, nhà khoa học nghiên cứu gì?",
    optionsVi: [
      "Các giai đoạn ngủ như REM và hoạt động não liên quan",
      "Chỉ màu lông của chúng",
      "Chúng gõ phím nhanh thế nào",
      "Chúng có nộp thuế hay không",
    ],
    correctIndex: 0,
    explanationEn: "Evidence about animal dreaming comes from sleep research, especially REM-like brain patterns.",
    explanationVi: "Bằng chứng về giấc mơ ở động vật đến từ nghiên cứu giấc ngủ, đặc biệt mẫu hoạt động não giống REM.",
  },
  "cam21-test2-p2": {
    questionEn: "What is Mapungubwe famous for?",
    optionsEn: [
      "An early southern African kingdom with rich archaeological finds",
      "The capital of ancient Rome",
      "A modern space station",
      "The deepest ocean trench",
    ],
    questionVi: "Mapungubwe nổi tiếng vì điều gì?",
    optionsVi: [
      "Vương quốc sớm ở miền nam châu Phi với nhiều hiện vật khảo cổ",
      "Thủ đô của La Mã cổ",
      "Trạm vũ trụ hiện đại",
      "Rãnh đại dương sâu nhất",
    ],
    correctIndex: 0,
    explanationEn: "Mapungubwe was a powerful early kingdom in southern Africa, known for gold artefacts including a gold rhino.",
    explanationVi: "Mapungubwe là vương quốc sớm hùng mạnh ở miền nam châu Phi, nổi tiếng với hiện vật vàng gồm tê giác vàng.",
  },
  "cam21-test2-p3": {
    questionEn: "What is a common theme in discussions of artificial intelligence?",
    optionsEn: [
      "Powerful pattern-learning tools that also raise ethical questions",
      "That AI only works without any data",
      "That AI replaced fire in prehistoric times",
      "That AI cannot process text or images",
    ],
    questionVi: "Chủ đề nào thường gặp khi bàn về trí tuệ nhân tạo?",
    optionsVi: [
      "Công cụ học mẫu mạnh mẽ nhưng cũng đặt ra câu hỏi đạo đức",
      "AI chỉ hoạt động khi không có dữ liệu",
      "AI đã thay thế lửa thời tiền sử",
      "AI không xử lý được chữ hay hình",
    ],
    correctIndex: 0,
    explanationEn: "AI systems learn from data and automate tasks, while prompting debate about bias, control and society.",
    explanationVi: "Hệ thống AI học từ dữ liệu và tự động hóa tác vụ, đồng thời gây tranh luận về thiên kiến, kiểm soát và xã hội.",
  },
  "cam21-test3-p1": {
    questionEn: "What is the saiga?",
    optionsEn: [
      "A distinctive Central Asian antelope under conservation pressure",
      "A type of Roman warship",
      "A Welsh art gallery",
      "A Kenyan mountain railway",
    ],
    questionVi: "Saiga là gì?",
    optionsVi: [
      "Một loài linh dương Trung Á đặc trưng đang chịu áp lực bảo tồn",
      "Một loại tàu chiến La Mã",
      "Một gallery nghệ thuật ở Wales",
      "Một đường sắt núi ở Kenya",
    ],
    correctIndex: 0,
    explanationEn: "The saiga antelope of the Eurasian steppes has faced disease outbreaks, hunting and habitat threats.",
    explanationVi: "Linh dương saiga ở thảo nguyên Á–Âu từng đối mặt dịch bệnh, săn bắt và đe dọa môi trường sống.",
  },
  "cam21-test3-p2": {
    questionEn: "What is a major everyday problem of getting around Dar es Salaam?",
    optionsEn: [
      "Heavy traffic congestion and strained urban transport",
      "Too many underground metro lines with no passengers",
      "A complete ban on all buses and taxis",
      "Ice roads that never melt",
    ],
    questionVi: "Vấn đề đi lại hàng ngày lớn ở Dar es Salaam là gì?",
    optionsVi: [
      "Ùn tắc nặng và giao thông đô thị quá tải",
      "Quá nhiều tuyến metro ngầm nhưng không có khách",
      "Cấm hoàn toàn mọi xe buýt và taxi",
      "Đường băng không bao giờ tan",
    ],
    correctIndex: 0,
    explanationEn: "Rapid growth in Dar es Salaam has brought severe congestion and difficult daily commuting.",
    explanationVi: "Tăng trưởng nhanh ở Dar es Salaam gây ùn tắc nghiêm trọng và đi lại hàng ngày khó khăn.",
  },
  "cam21-test3-p3": {
    questionEn: "What does 'rethinking the past' usually involve in history or archaeology?",
    optionsEn: [
      "Revisiting old assumptions when new evidence appears",
      "Deleting all museums permanently",
      "Refusing to study any artefacts",
      "Claiming the future never changes",
    ],
    questionVi: "'Rethinking the past' thường nghĩa là gì trong lịch sử hay khảo cổ?",
    optionsVi: [
      "Xem lại giả định cũ khi có bằng chứng mới",
      "Xóa vĩnh viễn mọi bảo tàng",
      "Từ chối nghiên cứu mọi hiện vật",
      "Khẳng định tương lai không bao giờ đổi",
    ],
    correctIndex: 0,
    explanationEn: "Scholars reinterpret earlier narratives as methods improve and fresh finds challenge old stories.",
    explanationVi: "Học giả diễn giải lại tường thuật cũ khi phương pháp tiến bộ và phát hiện mới thách thức câu chuyện cũ.",
  },
  "cam21-test4-p1": {
    questionEn: "Why is water hyacinth a problem in places such as Kenya?",
    optionsEn: [
      "It is an invasive plant that can choke lakes and waterways",
      "It only grows inside refrigerators",
      "It is a rare animal that eats concrete",
      "It produces diamonds that block roads",
    ],
    questionVi: "Vì sao lục bình (water hyacinth) là vấn đề ở những nơi như Kenya?",
    optionsVi: [
      "Là loài thực vật xâm lấn có thể nghẽn hồ và đường thủy",
      "Chỉ mọc trong tủ lạnh",
      "Là động vật quý hiếm ăn bê tông",
      "Tạo kim cương chặn đường",
    ],
    correctIndex: 0,
    explanationEn: "Water hyacinth spreads rapidly on water surfaces, harming fishing, transport and ecosystems — though some reuse projects exist.",
    explanationVi: "Lục bình lan nhanh trên mặt nước, hại nghề cá, giao thông và hệ sinh thái — dù có dự án tái sử dụng.",
  },
  "cam21-test4-p2": {
    questionEn: "What issue is central to discussions of multilingualism among Indian schoolchildren?",
    optionsEn: [
      "How multiple languages are used and taught in education",
      "Whether children should never speak at school",
      "Banning all Indian languages from classrooms",
      "Teaching only through silence",
    ],
    questionVi: "Vấn đề trung tâm khi bàn về đa ngữ ở học sinh Ấn Độ là gì?",
    optionsVi: [
      "Cách nhiều ngôn ngữ được dùng và dạy trong giáo dục",
      "Liệu trẻ có nên không bao giờ nói ở trường",
      "Cấm mọi ngôn ngữ Ấn Độ khỏi lớp học",
      "Chỉ dạy bằng sự im lặng",
    ],
    correctIndex: 0,
    explanationEn: "India's linguistic diversity raises questions about mother-tongue schooling, English and classroom multilingual practice.",
    explanationVi: "Sự đa dạng ngôn ngữ Ấn Độ đặt câu hỏi về dạy bằng tiếng mẹ đẻ, tiếng Anh và thực hành đa ngữ trong lớp.",
  },
  "cam21-test4-p3": {
    questionEn: "What do 'globemakers' primarily create?",
    optionsEn: [
      "Handcrafted geographical globes",
      "Industrial steel bridges only",
      "Digital passwords for banks",
      "Space rockets for tourism",
    ],
    questionVi: "'Globemakers' chủ yếu tạo ra gì?",
    optionsVi: [
      "Quả địa cầu địa lý làm thủ công",
      "Chỉ cầu thép công nghiệp",
      "Mật khẩu số cho ngân hàng",
      "Tên lửa vũ trụ du lịch",
    ],
    correctIndex: 0,
    explanationEn: "Globemakers are craftspeople who design and build detailed world globes by hand.",
    explanationVi: "Globemakers là nghệ nhân thiết kế và làm quả địa cầu chi tiết bằng tay.",
  },
};
