import type { PassageVocabItem } from "@/lib/reading/passage-vocabulary";

export const CAMBRIDGE_16_21_VOCABULARY: Record<string, PassageVocabItem[]> = {
  "cam16-test1-p1": [
    { term: "habitat", definitionVi: "môi trường sống", level: "B1-B2" },
    { term: "sea ice", definitionVi: "băng biển", level: "B1-B2" },
    { term: "endangered", definitionVi: "bị đe dọa (tuyệt chủng)", level: "B1-B2" },
    { term: "apex predator", definitionVi: "động vật săn mồi đỉnh chuỗi thức ăn", level: "C1" },
    { term: "conservation", definitionVi: "bảo tồn", level: "B1-B2" },
  ],
  "cam16-test1-p2": [
    { term: "pyramid", definitionVi: "kim tự tháp", level: "B1-B2" },
    { term: "pharaoh", definitionVi: "pharaông (vua Ai Cập cổ)", level: "B1-B2" },
    { term: "tomb", definitionVi: "lăng mộ", level: "B1-B2" },
    { term: "limestone", definitionVi: "đá vôi", level: "B1-B2" },
    { term: "monumental", definitionVi: "hoành tráng / mang tính đài kỷ niệm", level: "C1" },
  ],
  "cam16-test1-p3": [
    { term: "automation", definitionVi: "tự động hóa", level: "B1-B2" },
    { term: "workforce", definitionVi: "lực lượng lao động", level: "B1-B2" },
    { term: "remote working", definitionVi: "làm việc từ xa", level: "B1-B2" },
    { term: "gig economy", definitionVi: "kinh tế việc làm linh hoạt / theo dự án", level: "C1" },
    { term: "upskilling", definitionVi: "nâng cao kỹ năng", level: "B1-B2" },
  ],
  "cam16-test2-p1": [
    { term: "chalk", definitionVi: "đá phấn / phấn trắng", level: "B1-B2" },
    { term: "hill figure", definitionVi: "hình khắc trên sườn đồi", level: "C1" },
    { term: "prehistoric", definitionVi: "tiền sử", level: "B1-B2" },
    { term: "excavation", definitionVi: "khai quật", level: "B1-B2" },
    { term: "ritual", definitionVi: "nghi lễ", level: "B1-B2" },
  ],
  "cam16-test2-p2": [
    { term: "microbe", definitionVi: "vi sinh vật", level: "B1-B2" },
    { term: "microbiome", definitionVi: "hệ vi sinh vật (trong cơ thể)", level: "C1" },
    { term: "bacteria", definitionVi: "vi khuẩn", level: "B1-B2" },
    { term: "symbiosis", definitionVi: "cộng sinh", level: "C1" },
    { term: "immune system", definitionVi: "hệ miễn dịch", level: "B1-B2" },
  ],
  "cam16-test2-p3": [
    { term: "intuition", definitionVi: "trực giác", level: "B1-B2" },
    { term: "deliberation", definitionVi: "suy xét kỹ / cân nhắc", level: "C1" },
    { term: "bias", definitionVi: "thiên kiến / thành kiến", level: "B1-B2" },
    { term: "judgment", definitionVi: "phán đoán", level: "B1-B2" },
    { term: "rational", definitionVi: "hợp lý / dựa trên lý trí", level: "B1-B2" },
  ],
  "cam16-test3-p1": [
    { term: "navigation", definitionVi: "hàng hải / định hướng trên biển", level: "B1-B2" },
    { term: "galley", definitionVi: "tàu chiến cổ (chèo)", level: "C1" },
    { term: "harbour", definitionVi: "cảng", level: "B1-B2" },
    { term: "cargo", definitionVi: "hàng hóa vận chuyển", level: "B1-B2" },
    { term: "shipwright", definitionVi: "thợ đóng tàu", level: "C1" },
  ],
  "cam16-test3-p2": [
    { term: "glacier", definitionVi: "sông băng", level: "B1-B2" },
    { term: "artefact", definitionVi: "hiện vật khảo cổ", level: "B1-B2" },
    { term: "ice melt", definitionVi: "tan băng", level: "B1-B2" },
    { term: "archaeology", definitionVi: "khảo cổ học", level: "B1-B2" },
    { term: "preservation", definitionVi: "sự bảo tồn / giữ gìn", level: "B1-B2" },
  ],
  "cam16-test3-p3": [
    { term: "phenology", definitionVi: "sinh học thời gian (chu kỳ theo mùa)", level: "C1" },
    { term: "budburst", definitionVi: "nảy chồi / ra chồi", level: "C1" },
    { term: "temperature", definitionVi: "nhiệt độ", level: "B1-B2" },
    { term: "flowering", definitionVi: "sự ra hoa", level: "B1-B2" },
    { term: "climate cue", definitionVi: "tín hiệu khí hậu (kích thích sinh trưởng)", level: "C1" },
  ],
  "cam16-test4-p1": [
    { term: "tunnel", definitionVi: "đường hầm", level: "B1-B2" },
    { term: "aqueduct", definitionVi: "cống dẫn nước / cầu máng", level: "B1-B2" },
    { term: "underground", definitionVi: "dưới lòng đất", level: "B1-B2" },
    { term: "engineering", definitionVi: "kỹ thuật / công trình kỹ thuật", level: "B1-B2" },
    { term: "shaft", definitionVi: "giếng / hố đứng (hầm)", level: "C1" },
  ],
  "cam16-test4-p2": [
    { term: "literacy", definitionVi: "khả năng đọc viết", level: "B1-B2" },
    { term: "digital reading", definitionVi: "đọc trên thiết bị số", level: "B1-B2" },
    { term: "print media", definitionVi: "báo chí / ấn phẩm in", level: "B1-B2" },
    { term: "attention span", definitionVi: "khả năng tập trung / duy trì chú ý", level: "C1" },
    { term: "skim", definitionVi: "đọc lướt", level: "B1-B2" },
  ],
  "cam16-test4-p3": [
    { term: "artificial intelligence", definitionVi: "trí tuệ nhân tạo", level: "B1-B2" },
    { term: "attitude", definitionVi: "thái độ", level: "B1-B2" },
    { term: "trust", definitionVi: "niềm tin / sự tin tưởng", level: "B1-B2" },
    { term: "ethics", definitionVi: "đạo đức / đạo đức học", level: "B1-B2" },
    { term: "automation anxiety", definitionVi: "lo ngại về tự động hóa", level: "C1" },
  ],
  "cam21-test1-p1": [
    { term: "patron", definitionVi: "nhà bảo trợ (nghệ thuật)", level: "B1-B2" },
    { term: "collection", definitionVi: "bộ sưu tập", level: "B1-B2" },
    { term: "Impressionist", definitionVi: "thuộc trường phái Ấn tượng", level: "B1-B2" },
    { term: "gallery", definitionVi: "phòng trưng bày / gallery", level: "B1-B2" },
    { term: "philanthropy", definitionVi: "hoạt động từ thiện / hảo tâm", level: "C1" },
  ],
  "cam21-test1-p2": [
    { term: "silence", definitionVi: "sự im lặng", level: "B1-B2" },
    { term: "noise pollution", definitionVi: "ô nhiễm tiếng ồn", level: "B1-B2" },
    { term: "wellbeing", definitionVi: "sức khỏe / sự an lạc", level: "B1-B2" },
    { term: "distraction", definitionVi: "sự phân tâm", level: "B1-B2" },
    { term: "solitude", definitionVi: "sự cô tịch / ở một mình", level: "C1" },
  ],
  "cam21-test1-p3": [
    { term: "commodity", definitionVi: "hàng hóa / mặt hàng thương mại", level: "B1-B2" },
    { term: "plantation", definitionVi: "đồn điền", level: "B1-B2" },
    { term: "colonialism", definitionVi: "chủ nghĩa thực dân", level: "C1" },
    { term: "trade route", definitionVi: "tuyến thương mại", level: "B1-B2" },
    { term: "refined sugar", definitionVi: "đường tinh luyện", level: "B1-B2" },
  ],
  "cam21-test2-p1": [
    { term: "REM sleep", definitionVi: "giấc ngủ REM (chuyển động mắt nhanh)", level: "C1" },
    { term: "dream", definitionVi: "giấc mơ", level: "B1-B2" },
    { term: "neuroscience", definitionVi: "khoa học thần kinh", level: "C1" },
    { term: "cognition", definitionVi: "nhận thức", level: "B1-B2" },
    { term: "brain activity", definitionVi: "hoạt động não", level: "B1-B2" },
  ],
  "cam21-test2-p2": [
    { term: "kingdom", definitionVi: "vương quốc", level: "B1-B2" },
    { term: "gold rhino", definitionVi: "tê giác vàng (hiện vật Mapungubwe)", level: "C1" },
    { term: "trade network", definitionVi: "mạng lưới thương mại", level: "B1-B2" },
    { term: "excavation", definitionVi: "khai quật", level: "B1-B2" },
    { term: "heritage", definitionVi: "di sản", level: "B1-B2" },
  ],
  "cam21-test2-p3": [
    { term: "algorithm", definitionVi: "thuật toán", level: "B1-B2" },
    { term: "machine learning", definitionVi: "học máy", level: "B1-B2" },
    { term: "dataset", definitionVi: "bộ dữ liệu", level: "B1-B2" },
    { term: "bias", definitionVi: "thiên kiến (trong dữ liệu/AI)", level: "B1-B2" },
    { term: "autonomy", definitionVi: "quyền tự chủ / tính tự trị", level: "C1" },
  ],
  "cam21-test3-p1": [
    { term: "saiga", definitionVi: "linh dương saiga", level: "C1" },
    { term: "antelope", definitionVi: "linh dương", level: "B1-B2" },
    { term: "poaching", definitionVi: "săn trộm", level: "B1-B2" },
    { term: "outbreak", definitionVi: "đợt bùng phát (dịch)", level: "B1-B2" },
    { term: "endangered species", definitionVi: "loài bị đe dọa", level: "B1-B2" },
  ],
  "cam21-test3-p2": [
    { term: "congestion", definitionVi: "ùn tắc giao thông", level: "B1-B2" },
    { term: "commuter", definitionVi: "người đi làm hàng ngày", level: "B1-B2" },
    { term: "public transport", definitionVi: "giao thông công cộng", level: "B1-B2" },
    { term: "infrastructure", definitionVi: "cơ sở hạ tầng", level: "B1-B2" },
    { term: "informal sector", definitionVi: "khu vực kinh tế phi chính thức", level: "C1" },
  ],
  "cam21-test3-p3": [
    { term: "reinterpret", definitionVi: "diễn giải lại", level: "B1-B2" },
    { term: "historical narrative", definitionVi: "diễn ngôn / câu chuyện lịch sử", level: "C1" },
    { term: "evidence", definitionVi: "bằng chứng", level: "B1-B2" },
    { term: "assumption", definitionVi: "giả định", level: "B1-B2" },
    { term: "revisionist", definitionVi: "theo hướng xét lại lịch sử", level: "C1" },
  ],
  "cam21-test4-p1": [
    { term: "water hyacinth", definitionVi: "bèo tây / lục bình", level: "C1" },
    { term: "invasive species", definitionVi: "loài xâm lấn", level: "B1-B2" },
    { term: "waterway", definitionVi: "đường thủy", level: "B1-B2" },
    { term: "biofuel", definitionVi: "nhiên liệu sinh học", level: "B1-B2" },
    { term: "infestation", definitionVi: "sự xâm chiếm / lan tràn (của loài)", level: "C1" },
  ],
  "cam21-test4-p2": [
    { term: "multilingualism", definitionVi: "đa ngữ / biết nhiều ngôn ngữ", level: "C1" },
    { term: "mother tongue", definitionVi: "tiếng mẹ đẻ", level: "B1-B2" },
    { term: "medium of instruction", definitionVi: "ngôn ngữ giảng dạy", level: "C1" },
    { term: "bilingual", definitionVi: "song ngữ", level: "B1-B2" },
    { term: "literacy", definitionVi: "khả năng đọc viết", level: "B1-B2" },
  ],
  "cam21-test4-p3": [
    { term: "globe", definitionVi: "quả địa cầu", level: "B1-B2" },
    { term: "craftsmanship", definitionVi: "tay nghề thủ công", level: "B1-B2" },
    { term: "cartography", definitionVi: "bản đồ học", level: "C1" },
    { term: "handmade", definitionVi: "làm thủ công", level: "B1-B2" },
    { term: "workshop", definitionVi: "xưởng / workshop", level: "B1-B2" },
  ],
};
