import type { EnViWiktionaryIndex } from "@/lib/reading/wiktionary-vi-types";
import { pickViGlossFromIndex } from "@/lib/reading/wiktionary-vi-store";

/** Từ cơ bản / hay gặp khi đọc — bổ sung khi Wiktionary import chưa có. */
export const CORE_EN_VI_GLOSSARY: EnViWiktionaryIndex = {
  necessary: { adjective: ["cần thiết", "cần"] },
  essential: { adjective: ["thiết yếu", "cần thiết"] },
  required: { adjective: ["bắt buộc", "cần thiết"] },
  inevitable: { adjective: ["không thể tránh", "tất yếu"] },
  unavoidable: { adjective: ["không thể tránh"] },
  possible: { adjective: ["có thể", "khả thi"] },
  available: { adjective: ["có sẵn", "sẵn có"] },
  different: { adjective: ["khác", "khác biệt"] },
  similar: { adjective: ["tương tự", "giống"] },
  common: { adjective: ["phổ biến", "thông thường"] },
  specific: { adjective: ["cụ thể", "đặc thù"] },
  general: { adjective: ["chung", "tổng quát"] },
  basic: { adjective: ["cơ bản"] },
  simple: { adjective: ["đơn giản"] },
  complex: { adjective: ["phức tạp"] },
  difficult: { adjective: ["khó", "khó khăn"] },
  easy: { adjective: ["dễ", "dễ dàng"] },
  clear: { adjective: ["rõ ràng", "rõ"] },
  obvious: { adjective: ["hiển nhiên", "rõ ràng"] },
  likely: { adjective: ["có khả năng", "có thể"] },
  recent: { adjective: ["gần đây", "mới"] },
  modern: { adjective: ["hiện đại"] },
  natural: { adjective: ["tự nhiên"] },
  physical: { adjective: ["thể chất", "vật lý"] },
  mental: { adjective: ["tinh thần", "trí tuệ"] },
  personal: { adjective: ["cá nhân"] },
  public: { adjective: ["công cộng", "công khai"] },
  private: { adjective: ["riêng tư", "cá nhân"] },
  national: { adjective: ["quốc gia", "toàn quốc"] },
  international: { adjective: ["quốc tế"] },
  traditional: { adjective: ["truyền thống"] },
  practical: { adjective: ["thực tế", "thực dụng"] },
  actual: { adjective: ["thực tế", "thật sự"] },
  current: { adjective: ["hiện tại", "đương thời"] },
  previous: { adjective: ["trước đó", "trước"] },
  entire: { adjective: ["toàn bộ", "cả"] },
  complete: { adjective: ["hoàn chỉnh", "đầy đủ"] },
  sufficient: { adjective: ["đủ", "đáp ứng"] },
  effective: { adjective: ["hiệu quả"] },
  efficient: { adjective: ["hiệu quả", "năng suất"] },
  successful: { adjective: ["thành công"] },
  analysis: { noun: ["phân tích"] },
  avoid: { verb: ["tránh", "né tránh"] },
  achieve: { verb: ["đạt được", "đạt"] },
  improve: { verb: ["cải thiện", "nâng cao"] },
  consider: { verb: ["cân nhắc", "xem xét"] },
  involve: { verb: ["liên quan", "bao gồm"] },
  occur: { verb: ["xảy ra", "diễn ra"] },
  appear: { verb: ["xuất hiện", "có vẻ"] },
  become: { verb: ["trở nên"] },
  create: { verb: ["tạo ra", "sáng tạo"] },
  exist: { verb: ["tồn tại"] },
  influence: { noun: ["ảnh hưởng"], verb: ["ảnh hưởng"] },
  benefit: { noun: ["lợi ích"], verb: ["có lợi", "hưởng lợi"] },
  advantage: { noun: ["lợi thế", "ưu điểm"] },
  disadvantage: { noun: ["bất lợi", "nhược điểm"] },
  impact: { noun: ["tác động", "ảnh hưởng"] },
  result: { noun: ["kết quả"], verb: ["dẫn đến"] },
  reason: { noun: ["lý do", "nguyên nhân"] },
  purpose: { noun: ["mục đích"] },
  method: { noun: ["phương pháp", "cách"] },
  process: { noun: ["quy trình", "tiến trình"] },
  system: { noun: ["hệ thống"] },
  condition: { noun: ["điều kiện", "tình trạng"] },
  situation: { noun: ["tình huống", "hoàn cảnh"] },
  problem: { noun: ["vấn đề"] },
  solution: { noun: ["giải pháp"] },
  issue: { noun: ["vấn đề", "chủ đề"] },
  factor: { noun: ["yếu tố", "nhân tố"] },
  evidence: { noun: ["bằng chứng", "chứng cứ"] },
  information: { noun: ["thông tin"] },
  knowledge: { noun: ["kiến thức"] },
  experience: { noun: ["kinh nghiệm", "trải nghiệm"] },
  behavior: { noun: ["hành vi"] },
  activity: { noun: ["hoạt động"] },
  change: { noun: ["sự thay đổi"], verb: ["thay đổi"] },
  build: { verb: ["xây dựng", "xây", "làm"], adjective: ["được xây"] },
  breach: { verb: ["vi phạm", "phá vỡ", "xâm phạm"], noun: ["sự vi phạm", "lỗ hổng", "vi phạm"] },
  growth: { noun: ["sự tăng trưởng", "phát triển"] },
  however: { adverb: ["tuy nhiên", "nhưng"] },
  therefore: { adverb: ["do đó", "vì vậy"] },
  although: { adverb: ["mặc dù", "dù"] },
  usually: { adverb: ["thường", "thông thường"] },
  often: { adverb: ["thường", "hay"] },
  always: { adverb: ["luôn luôn", "luôn"] },
  never: { adverb: ["không bao giờ", "không"] },
};

export function coreEnViGloss(lemma: string, primaryPos: string, headword?: string): string | null {
  return pickViGlossFromIndex(CORE_EN_VI_GLOSSARY, lemma, primaryPos, headword);
}
