import type { QuickCheckQuiz } from "@/lib/reading/passage-quiz";

/** Kiểm tra nhanh Compass — câu đọc hiểu theo nội dung bài (không dùng template placeholder). */
export const READING_CHALLENGE_1_QUIZ: Record<string, QuickCheckQuiz> = {
  "reading-challenge-1-p1": {
    questionEn: "What is the main idea of this reading?",
    questionVi: "Ý chính của bài đọc là gì?",
    optionsEn: [
      "How the Ice Hotel is built step by step",
      "What makes the Ice Hotel special and unusual",
      "Why ice is dangerous in winter",
      "The history of hotels in Quebec",
    ],
    optionsVi: [
      "Cách xây Ice Hotel từng bước",
      "Điều gì khiến Ice Hotel đặc biệt và lạ",
      "Vì sao băng nguy hiểm vào mùa đông",
      "Lịch sử khách sạn ở Quebec",
    ],
    correctIndex: 1,
    explanationEn: "The passage focuses on what makes the ice hotel unique — built of ice/snow, open in winter, popular for its atmosphere.",
    explanationVi: "Bài tập trung vào điều khiến khách sạn băng độc đáo — làm từ băng/tuyết, chỉ mở mùa đông, nổi tiếng nhờ không khí đặc biệt.",
  },
  "reading-challenge-1-p2": {
    questionEn: "According to the passage, where did hamburgers probably come from?",
    questionVi: "Theo bài, hamburger có lẽ xuất phát từ đâu?",
    optionsEn: ["England", "India", "Hamburg, Germany", "Persia (Iran)"],
    optionsVi: ["Anh", "Ấn Độ", "Hamburg, Đức", "Ba Tư (Iran)"],
    correctIndex: 2,
    explanationEn: "The text says hamburgers likely came from Hamburg, Germany, before sailors brought them to America.",
    explanationVi: "Bài cho rằng hamburger có thể đến từ Hamburg (Đức) trước khi thủy thủ đưa sang Mỹ.",
  },
  "reading-challenge-1-p3": {
    questionEn: "Why do tropical cyclones have names?",
    questionVi: "Vì sao bão nhiệt đới được đặt tên?",
    optionsEn: [
      "To honor famous meteorologists",
      "Because only male names are allowed",
      "To make it easier to track a storm and its dangers",
      "To confuse people about wind direction",
    ],
    optionsVi: [
      "Để vinh danh nhà khí tượng nổi tiếng",
      "Vì chỉ được dùng tên nam",
      "Để dễ theo dõi cơn bão và nguy hiểm của nó",
      "Để làm người ta nhầm hướng gió",
    ],
    correctIndex: 2,
    explanationEn: "The WMO names storms so people can follow information about a hurricane and possible dangers.",
    explanationVi: "WMO đặt tên để mọi người theo dõi thông tin về bão và nguy cơ dễ hơn.",
  },
  "reading-challenge-1-p4": {
    questionEn: "What causes the feeling of “butterflies in the stomach”?",
    questionVi: "Điều gì gây cảm giác “bướm bay trong bụng”?",
    optionsEn: [
      "Eating too much before a performance",
      "Chemicals the body produces under stress, such as cortisol",
      "Lack of sleep the night before",
      "Cold temperature on stage",
    ],
    optionsVi: [
      "Ăn quá no trước khi biểu diễn",
      "Hóa chất cơ thể tiết ra khi căng thẳng, như cortisol",
      "Thiếu ngủ đêm trước",
      "Lạnh trên sân khấu",
    ],
    correctIndex: 1,
    explanationEn: "The passage explains butterflies come from stress chemicals like cortisol affecting the stomach.",
    explanationVi: "Bài giải thích cảm giác bướm bay đến từ hóa chất căng thẳng như cortisol ảnh hưởng dạ dày.",
  },
  "reading-challenge-1-p5": {
    questionEn: "What have scientists recently observed about fruit flies?",
    questionVi: "Các nhà khoa học gần đây quan sát thấy gì ở ruồi giấm?",
    optionsEn: [
      "They never rest at night",
      "They dream like humans",
      "They show behaviors similar to sleep",
      "They do not have brains",
    ],
    optionsVi: [
      "Chúng không bao giờ nghỉ ban đêm",
      "Chúng mơ như con người",
      "Chúng có hành vi giống khi ngủ",
      "Chúng không có não",
    ],
    correctIndex: 2,
    explanationEn: "Fruit flies become still for hours, change posture, and respond less to quiet noises — like sleep.",
    explanationVi: "Ruồi giấm bất động hàng giờ, đổi tư thế và ít phản ứng với tiếng nhỏ — giống khi ngủ.",
  },
  "reading-challenge-1-p6": {
    questionEn: "What is this reading mainly about?",
    questionVi: "Bài đọc chủ yếu nói về điều gì?",
    optionsEn: [
      "Rules of professional golf",
      "Tiger Woods’ life, career, and foundation",
      "How to build a golf course",
      "Winter sports in the United States",
    ],
    optionsVi: [
      "Luật golf chuyên nghiệp",
      "Cuộc đời, sự nghiệp và quỹ của Tiger Woods",
      "Cách xây sân golf",
      "Thể thao mùa đông ở Mỹ",
    ],
    correctIndex: 1,
    explanationEn: "The passage tells Tiger Woods’ story from childhood golf to fame and helping others play golf.",
    explanationVi: "Bài kể câu chuyện Tiger Woods từ golf thuở nhỏ đến nổi tiếng và giúp người khác chơi golf.",
  },
  "reading-challenge-1-p7": {
    questionEn: "What is HappyNews trying to do?",
    questionVi: "HappyNews đang cố làm gì?",
    optionsEn: [
      "Stop all newspapers from reporting bad news",
      "Balance negative news with more positive stories",
      "Replace television news completely",
      "Hide serious social problems from readers",
    ],
    optionsVi: [
      "Ngăn mọi báo đưa tin xấu",
      "Cân bằng tin tiêu cực bằng tin tích cực hơn",
      "Thay hoàn toàn tin truyền hình",
      "Che giấu vấn đề xã hội nghiêm trọng",
    ],
    correctIndex: 1,
    explanationEn: "Byron Reese created HappyNews to balance the media’s focus on bad news with good news.",
    explanationVi: "Byron Reese tạo HappyNews để cân bằng trọng tâm tin xấu của truyền thông bằng tin vui.",
  },
  "reading-challenge-1-p8": {
    questionEn: "What did the Wright brothers achieve on December 17, 1903?",
    questionVi: "Anh em Wright đạt được gì ngày 17/12/1903?",
    optionsEn: [
      "They opened a bicycle shop",
      "They graduated from high school",
      "They made a successful powered flight",
      "They moved to Kitty Hawk permanently",
    ],
    optionsVi: [
      "Họ mở cửa hàng xe đạp",
      "Họ tốt nghiệp trung học",
      "Họ bay thành công bằng máy có động cơ",
      "Họ chuyển vĩnh viễn tới Kitty Hawk",
    ],
    correctIndex: 2,
    explanationEn: "On that date they flew the Wright Flyer over Kitty Hawk — a historic first flight.",
    explanationVi: "Ngày đó họ lái Wright Flyer bay qua Kitty Hawk — chuyến bay có động cơ mang tính lịch sử.",
  },
  "reading-challenge-1-p9": {
    questionEn: "According to Kevin Mitnick, what is the biggest security danger today?",
    questionVi: "Theo Kevin Mitnick, mối đe dọa an ninh lớn nhất hiện nay là gì?",
    optionsEn: [
      "Weak firewall software",
      "Hackers with advanced technology only",
      "People who are too trusting with their information",
      "Old computers in government offices",
    ],
    optionsVi: [
      "Phần mềm firewall yếu",
      "Chỉ hacker có công nghệ cao",
      "Con người quá dễ tin và đưa thông tin",
      "Máy tính cũ ở cơ quan nhà nước",
    ],
    correctIndex: 2,
    explanationEn: "Mitnick says attackers can get in if one trusting person gives information — people are the weak link.",
    explanationVi: "Mitnick nói kẻ tấn công lọt vào nếu một người tin tưởng đưa thông tin — con người là điểm yếu.",
  },
  "reading-challenge-1-p10": {
    questionEn: "What is unusual about the company Mirai Seiko?",
    questionVi: "Điều gì đặc biệt về công ty Mirai Seiko?",
    optionsEn: [
      "It sells beetles through vending machines",
      "It only sells soft drinks",
      "It bans children from collecting insects",
      "It builds houses for beetles in the wild",
    ],
    optionsVi: [
      "Bán bọ cánh cứng qua máy bán hàng tự động",
      "Chỉ bán nước ngọt",
      "Cấm trẻ em sưu tầm côn trùng",
      "Xây nhà cho bọ ngoài tự nhiên",
    ],
    correctIndex: 0,
    explanationEn: "The company sells large live beetles in vending machines, which conservationists criticize.",
    explanationVi: "Công ty bán bọ sống lớn qua máy bán hàng, bị nhà bảo tồn chỉ trích.",
  },
  "reading-challenge-1-p11": {
    questionEn: "What is the main idea of this reading?",
    questionVi: "Ý chính của bài đọc là gì?",
    optionsEn: [
      "How da Vinci painted landscapes",
      "The making of a great mystery novel",
      "Fashion trends among Italian women",
      "The identity of the woman in the Mona Lisa",
    ],
    optionsVi: [
      "Cách da Vinci vẽ phong cảnh",
      "Việc viết tiểu thuyết bí ẩn",
      "Xu hướng thời trang phụ nữ Ý",
      "Danh tính người phụ nữ trong Mona Lisa",
    ],
    correctIndex: 3,
    explanationEn: "The passage discusses theories and the discovery that the subject was Lisa del Giocondo.",
    explanationVi: "Bài bàn các giả thuyết và phát hiện người trong tranh là Lisa del Giocondo.",
  },
  "reading-challenge-1-p12": {
    questionEn: "What is the main idea of this reading?",
    questionVi: "Ý chính của bài đọc là gì?",
    optionsEn: [
      "English has no borrowed words",
      "Only Indian words entered English",
      "Many common English words come from other languages",
      "Sauna is the only Finnish word in English",
    ],
    optionsVi: [
      "Tiếng Anh không có từ mượn",
      "Chỉ từ Ấn Độ vào tiếng Anh",
      "Nhiều từ tiếng Anh thông dụng đến từ ngôn ngữ khác",
      "Sauna là từ Phần Lan duy nhất trong tiếng Anh",
    ],
    correctIndex: 2,
    explanationEn: "Shampoo, ketchup, and sauna are examples of words English borrowed from other languages.",
    explanationVi: "Shampoo, ketchup, sauna là ví dụ từ tiếng Anh mượn từ ngôn ngữ khác.",
  },
  "reading-challenge-1-p13": {
    questionEn: "What is the main idea of this reading?",
    questionVi: "Ý chính của bài đọc là gì?",
    optionsEn: [
      "A list of all deserts on Earth",
      "How tourists enjoy deserts",
      "Why deserts are growing and how to slow it",
      "Why cows should not walk on soil",
    ],
    optionsVi: [
      "Danh sách mọi sa mạc trên Trái Đất",
      "Du khách thích sa mạc thế nào",
      "Vì sao sa mạc mở rộng và cách hạn chế",
      "Vì sao bò không nên đi trên đất",
    ],
    correctIndex: 2,
    explanationEn: "The text explains desertification from nature and human activity and the need to treat land better.",
    explanationVi: "Bài giải thích sa mạc hóa do thiên nhiên và con người, cần đối xử tốt hơn với đất.",
  },
  "reading-challenge-1-p14": {
    questionEn: "What could be another title for this reading?",
    questionVi: "Tiêu đề nào khác phù hợp với bài?",
    optionsEn: [
      "Drink Water, Not Soft Drinks",
      "Drink During Every Meal",
      "Never Drink Before Breakfast",
      "Drink Enough Water",
    ],
    optionsVi: [
      "Uống nước, không uống nước ngọt",
      "Uống nước trong mọi bữa ăn",
      "Không bao giờ uống trước bữa sáng",
      "Uống đủ nước",
    ],
    correctIndex: 3,
    explanationEn: "The passage advises drinking enough water daily and checking urine color for hydration.",
    explanationVi: "Bài khuyên uống đủ nước mỗi ngày và xem màu nước tiểu để biết đã đủ nước chưa.",
  },
  "reading-challenge-1-p15": {
    questionEn: "What is the main idea of this reading?",
    questionVi: "Ý chính của bài đọc là gì?",
    optionsEn: [
      "How to train dogs after earthquakes",
      "A history of earthquakes in Japan only",
      "How natural events may change animals’ behavior",
      "Why folklore should be ignored",
    ],
    optionsVi: [
      "Cách huấn luyện chó sau động đất",
      "Chỉ lịch sử động đất ở Nhật",
      "Thiên tai có thể làm đổi hành vi động vật",
      "Vì sao nên bỏ qua truyện dân gian",
    ],
    correctIndex: 2,
    explanationEn: "Scientists revisit stories and data suggesting animals act differently before earthquakes and storms.",
    explanationVi: "Nhà khoa học xem lại truyện và dữ liệu cho thấy động vật hành xử khác trước động đất/bão.",
  },
  "reading-challenge-1-p16": {
    questionEn: "What is the main idea of this reading?",
    questionVi: "Ý chính của bài đọc là gì?",
    optionsEn: [
      "Only children watch Totoro",
      "Miyazaki’s school years in detail",
      "The highest-grossing film in world history",
      "The life and films of Hayao Miyazaki",
    ],
    optionsVi: [
      "Chỉ trẻ em xem Totoro",
      "Chi tiết thời đi học của Miyazaki",
      "Phim doanh thu cao nhất thế giới",
      "Cuộc đời và phim của Hayao Miyazaki",
    ],
    correctIndex: 3,
    explanationEn: "The passage covers Miyazaki’s career, Studio Ghibli, famous films, and themes about nature.",
    explanationVi: "Bài nói về sự nghiệp Miyazaki, Studio Ghibli, phim nổi tiếng và chủ đề thiên nhiên.",
  },
  "reading-challenge-1-p17": {
    questionEn: "What is the main idea of this reading?",
    questionVi: "Ý chính của bài đọc là gì?",
    optionsEn: [
      "Colors are not important in daily life",
      "Managers must always wear black",
      "Colors can affect how people feel",
      "People cannot see colors clearly",
    ],
    optionsVi: [
      "Màu sắc không quan trọng trong đời sống",
      "Quản lý phải luôn mặc đen",
      "Màu sắc có thể ảnh hưởng cảm xúc",
      "Con người không nhìn rõ màu",
    ],
    correctIndex: 2,
    explanationEn: "Red, yellow, blue, and clothing colors are linked to excitement, hunger, calm, or confidence.",
    explanationVi: "Đỏ, vàng, xanh và màu quần áo gắn với hứng khởi, đói, bình tĩnh hoặc tự tin.",
  },
  "reading-challenge-1-p18": {
    questionEn: "What does a philatelist enjoy?",
    questionVi: "Philatelist thích làm gì?",
    optionsEn: [
      "Collecting stamps",
      "Selling expensive art",
      "Writing letters to doctors",
      "Calling the police",
    ],
    optionsVi: [
      "Sưu tầm tem",
      "Bán tranh đắt tiền",
      "Viết thư cho bác sĩ",
      "Gọi cảnh sát",
    ],
    correctIndex: 0,
    explanationEn: "A philatelist is a person who collects stamps — a popular hobby for over 150 years.",
    explanationVi: "Philatelist là người sưu tầm tem — sở thích phổ biến hơn 150 năm.",
  },
  "reading-challenge-1-p19": {
    questionEn: "What is the main idea of this reading?",
    questionVi: "Ý chính của bài đọc là gì?",
    optionsEn: [
      "How to download pirated movies easily",
      "A new advertising approach to piracy online",
      "Why all piracy is good for artists",
      "How to shut down the entire Internet",
    ],
    optionsVi: [
      "Cách tải phim lậu dễ dàng",
      "Cách tiếp cận quảng cáo mới với nội dung lậu trên mạng",
      "Vì sao vi phạm bản quyền tốt cho nghệ sĩ",
      "Cách đóng toàn bộ Internet",
    ],
    correctIndex: 1,
    explanationEn: "New software adds ads to pirated clips so companies can earn from copies instead of only blocking them.",
    explanationVi: "Phần mềm mới chèn quảng cáo vào clip lậu để công ty kiếm tiền thay vì chỉ chặn.",
  },
  "reading-challenge-1-p20": {
    questionEn: "What could be another title for this reading?",
    questionVi: "Tiêu đề nào khác phù hợp với bài?",
    optionsEn: [
      "Taking Care of Your Dog",
      "Homeless Dogs on the Street",
      "Dog Millionaires",
      "Training Dogs to Act in Movies",
    ],
    optionsVi: [
      "Chăm sóc chó cưng",
      "Chó không nhà trên phố",
      "Triệu phú là chó",
      "Huấn luyện chó đóng phim",
    ],
    correctIndex: 2,
    explanationEn: "Wealthy owners leave fortunes to dogs like Toby, Flossie, and Gunther IV.",
    explanationVi: "Chủ giàu để lại gia tài cho chó như Toby, Flossie và Gunther IV.",
  },
};
