import type { PassageVocabItem } from "@/lib/reading/passage-vocabulary";

/** Từ vựng curated theo unit — idioms từ .txt + từ khóa bài đọc (không tên riêng). */
export const READING_CHALLENGE_3_VOCABULARY: Record<string, PassageVocabItem[]> = {
  "reading-challenge-3-p1": [
    { term: "more often than not", definitionVi: "thường là; trong đa số trường hợp", level: "C1" },
    { term: "measure up to", definitionVi: "sánh được với; đạt kỳ vọng như", level: "C1" },
    { term: "it is a good bet", definitionVi: "rất có thể; gần như chắc chắn", level: "C1" },
    { term: "adaptation", definitionVi: "bản chuyển thể (sách → phim)", level: "B1-B2" },
    { term: "blockbuster", definitionVi: "phim ăn khách, bom tấn", level: "B1-B2" },
  ],
  "reading-challenge-3-p2": [
    { term: "woe be it", definitionVi: "thật không may cho (ai/cái gì)", level: "C1" },
    { term: "old wives' tales", definitionVi: "mê tín dân gian", level: "C1" },
    { term: "feed on", definitionVi: "ăn; sống nhờ (con mồi)", level: "C1" },
    { term: "superstition", definitionVi: "mê tín", level: "B1-B2" },
    { term: "omen", definitionVi: "điềm báo", level: "B1-B2" },
  ],
  "reading-challenge-3-p3": [
    { term: "wipe out", definitionVi: "xóa sổ; tiêu diệt hoàn toàn", level: "C1" },
    { term: "turn up", definitionVi: "xuất hiện; lộ ra", level: "C1" },
    { term: "turn of the century", definitionVi: "đầu thế kỷ", level: "C1" },
    { term: "permafrost", definitionVi: "băng vĩnh cửa (lớp đất luôn đóng băng)", level: "C1" },
    { term: "glacier", definitionVi: "sông băng", level: "B1-B2" },
  ],
  "reading-challenge-3-p4": [
    { term: "bear in mind", definitionVi: "nhớ; ghi nhớ", level: "C1" },
    { term: "stick to", definitionVi: "giữ nguyên; kiên trì với", level: "C1" },
    { term: "in a row", definitionVi: "liên tiếp", level: "C1" },
    { term: "cardiovascular", definitionVi: "tim mạch", level: "C1" },
    { term: "intensity", definitionVi: "cường độ (tập luyện)", level: "B1-B2" },
  ],
  "reading-challenge-3-p5": [
    { term: "hit the books", definitionVi: "học chăm chỉ", level: "C1" },
    { term: "be traced back to", definitionVi: "bắt nguồn từ; liên quan đến", level: "C1" },
    { term: "beef up", definitionVi: "củng cố; tăng cường", level: "C1" },
    { term: "aerobic", definitionVi: "có oxy (tập thể dục nhịp tim)", level: "B1-B2" },
    { term: "cognitive", definitionVi: "nhận thức", level: "C1" },
  ],
  "reading-challenge-3-p6": [
    { term: "set up (something)", definitionVi: "thiết lập; thành lập", level: "C1" },
    { term: "take (something) away", definitionVi: "mang đi; di dời", level: "C1" },
    { term: "tear down", definitionVi: "phá dỡ (công trình)", level: "C1" },
    { term: "relic", definitionVi: "di vật, cổ vật", level: "B1-B2" },
    { term: "folk art", definitionVi: "nghệ thuật dân gian", level: "B1-B2" },
  ],
  "reading-challenge-3-p7": [
    { term: "rely on", definitionVi: "phụ thuộc vào; cần đến", level: "C1" },
    { term: "be fitted with", definitionVi: "được trang bị", level: "C1" },
    { term: "lend (someone) a hand", definitionVi: "giúp ai một tay", level: "C1" },
    { term: "pedestrian", definitionVi: "người đi bộ", level: "B1-B2" },
    { term: "navigate", definitionVi: "điều hướng; tìm đường", level: "B1-B2" },
  ],
  "reading-challenge-3-p8": [
    { term: "launch", definitionVi: "ra mắt; khởi động", level: "B1-B2" },
    { term: "skyrocket", definitionVi: "tăng vọt", level: "B1-B2" },
    { term: "spring up", definitionVi: "mọc lên nhanh; xuất hiện ồ ạt", level: "C1" },
    { term: "inline skating", definitionVi: "trượt patin một hàng bánh", level: "B1-B2" },
    { term: "recreational", definitionVi: "mang tính giải trí", level: "B1-B2" },
  ],
  "reading-challenge-3-p9": [
    { term: "by its very nature", definitionVi: "vì bản chất của nó", level: "C1" },
    { term: "wave of the future", definitionVi: "xu hướng tương lai", level: "C1" },
    { term: "as far as", definitionVi: "ở mức độ; về phương diện", level: "C1" },
    { term: "versatile", definitionVi: "đa năng, linh hoạt", level: "B1-B2" },
    { term: "module", definitionVi: "mô-đun; khối lắp ghép", level: "B1-B2" },
  ],
  "reading-challenge-3-p10": [
    { term: "divide up (into)", definitionVi: "chia thành nhiều phần", level: "C1" },
    { term: "break into", definitionVi: "đột nhập trái phép", level: "C1" },
    { term: "take the credit (for)", definitionVi: "được coi là nguyên nhân (của thành công)", level: "C1" },
    { term: "vandalism", definitionVi: "phá hoại tài sản công", level: "B1-B2" },
    { term: "florist", definitionVi: "người bán hoa; tiệm hoa", level: "B1-B2" },
  ],
  "reading-challenge-3-p11": [
    { term: "touch up", definitionVi: "sửa, tô lại cho đẹp hơn", level: "C1" },
    { term: "case in point", definitionVi: "ví dụ điển hình", level: "C1" },
    { term: "no longer", definitionVi: "không còn", level: "C1" },
    { term: "restoration", definitionVi: "phục hồi, trùng tu", level: "B1-B2" },
    { term: "masterpiece", definitionVi: "kiệt tác", level: "B1-B2" },
  ],
  "reading-challenge-3-p12": [
    { term: "set about", definitionVi: "bắt đầu làm", level: "C1" },
    { term: "at some point", definitionVi: "ở thời điểm nào đó", level: "C1" },
    { term: "pass down", definitionVi: "truyền lại cho thế hệ sau", level: "C1" },
    { term: "legend", definitionVi: "truyền thuyết", level: "B1-B2" },
    { term: "repopulate", definitionVi: "tái sinh sản; làm đầy dân số trở lại", level: "C1" },
  ],
  "reading-challenge-3-p13": [
    { term: "face up to", definitionVi: "đối mặt; thừa nhận sự thật", level: "C1" },
    { term: "come up with", definitionVi: "nghĩ ra; đưa ra ý tưởng", level: "C1" },
    { term: "in the long run", definitionVi: "về lâu dài", level: "C1" },
    { term: "earthship", definitionVi: "nhà xanh làm từ vật liệu tái chế", level: "C1" },
    { term: "energy-efficient", definitionVi: "tiết kiệm năng lượng", level: "B1-B2" },
  ],
  "reading-challenge-3-p14": [
    { term: "take in", definitionVi: "hấp thụ; ăn/uống vào cơ thể", level: "C1" },
    { term: "stock up on", definitionVi: "tích trữ nhiều", level: "C1" },
    { term: "even better", definitionVi: "càng tốt hơn nữa", level: "C1" },
    { term: "antioxidant", definitionVi: "chất chống oxy hóa", level: "B1-B2" },
    { term: "free radical", definitionVi: "gốc tự do (gây lão hóa tế bào)", level: "C1" },
  ],
  "reading-challenge-3-p15": [
    { term: "be thought of", definitionVi: "được coi là", level: "B1-B2" },
    { term: "tend to", definitionVi: "có xu hướng", level: "B1-B2" },
    { term: "come to mind", definitionVi: "chợt nghĩ đến; nảy ra trong đầu", level: "B1-B2" },
    { term: "daydreaming", definitionVi: "mơ mộng ban ngày", level: "B1-B2" },
    { term: "wander", definitionVi: "lang thang (tâm trí)", level: "B1-B2" },
  ],
  "reading-challenge-3-p16": [
    { term: "climb to the top", definitionVi: "leo lên đỉnh cao; thành công", level: "C1" },
    { term: "(not) mince (one's) words", definitionVi: "nói thẳng, không vòng vo", level: "C1" },
    { term: "make a statement", definitionVi: "tỏ thái độ mạnh mẽ", level: "C1" },
    { term: "piracy", definitionVi: "vi phạm bản quyền; tải lậu", level: "B1-B2" },
    { term: "file-sharing", definitionVi: "chia sẻ tệp trực tuyến", level: "B1-B2" },
  ],
  "reading-challenge-3-p17": [
    { term: "in good working order", definitionVi: "hoạt động tốt", level: "C1" },
    { term: "at all costs", definitionVi: "bằng mọi giá", level: "C1" },
    { term: "draw on", definitionVi: "vận dụng; dựa vào (ký ức, kiến thức)", level: "C1" },
    { term: "prospective memory", definitionVi: "trí nhớ việc cần làm trong tương lai", level: "C1" },
    { term: "cortisol", definitionVi: "hormone stress (cortisol)", level: "C1" },
  ],
  "reading-challenge-3-p18": [
    { term: "under lock and key", definitionVi: "được cất giữ an toàn, khóa kỹ", level: "C1" },
    { term: "none the worse for wear", definitionVi: "vẫn nguyên vẹn, không hư hại", level: "C1" },
    { term: "rest assured", definitionVi: "yên tâm; chắc chắn rằng", level: "C1" },
    { term: "replica", definitionVi: "bản sao", level: "B1-B2" },
    { term: "outright", definitionVi: "hoàn toàn; vĩnh viễn (giành quyền sở hữu)", level: "C1" },
  ],
  "reading-challenge-3-p19": [
    { term: "con (someone) into (doing)", definitionVi: "lừa ai làm gì", level: "C1" },
    { term: "track down", definitionVi: "lần theo để tìm ra", level: "C1" },
    { term: "right away", definitionVi: "ngay lập tức", level: "C1" },
    { term: "phisher", definitionVi: "kẻ lừa đảo qua email/web giả", level: "B1-B2" },
    { term: "scam", definitionVi: "vụ lừa đảo", level: "B1-B2" },
  ],
  "reading-challenge-3-p20": [
    { term: "complete with", definitionVi: "kèm theo; có đủ cả", level: "C1" },
    { term: "make (somewhere) (someone's) home", definitionVi: "coi nơi nào là nhà; sinh sống tại đó", level: "C1" },
    { term: "haunted", definitionVi: "bị ám; có ma", level: "B1-B2" },
    { term: "rustle", definitionVi: "sột soạt (áo, lá)", level: "B1-B2" },
    { term: "paranormal", definitionVi: "siêu nhiên", level: "C1" },
  ],
};
