import type { QuickCheckQuiz } from "@/lib/reading/passage-quiz";

/** Kiểm tra nhanh Compass — câu đọc hiểu theo nội dung bài (không dùng template placeholder). */
export const READING_CHALLENGE_2_QUIZ: Record<string, QuickCheckQuiz> = {
  "reading-challenge-2-p1": {
    questionEn: "What dangerous substance did some Renaissance women put on their faces?",
    questionVi: "Chất nguy hiểm nào một số phụ nữ thời Phục hưng bôi lên mặt?",
    optionsEn: [
      "Henna from India",
      "White powder made of lead",
      "Black kohl from Egypt",
      "Belladonna rubbed on the skin",
    ],
    optionsVi: [
      "Henna từ Ấn Độ",
      "Bột trắng làm từ chì",
      "Phấn kohl đen từ Ai Cập",
      "Belladonna bôi lên da",
    ],
    correctIndex: 1,
    explanationEn: "During the Italian Renaissance, women wore white lead powder on their faces, which doctors now know is poisonous.",
    explanationVi: "Thời Phục hưng ở Ý, phụ nữ dùng bột chì trắng trên mặt — ngày nay bác sĩ biết chì độc với cơ thể.",
  },
  "reading-challenge-2-p2": {
    questionEn: "According to Korean tradition, what should a child do with a lost baby tooth?",
    questionVi: "Theo truyền thống Hàn Quốc, trẻ nên làm gì với răng sữa rụng?",
    optionsEn: [
      "Hide it under a pillow for the Tooth Fairy",
      "Throw it onto the roof of a house",
      "Feed it to a dog in meat fat",
      "Bury it in the garden",
    ],
    optionsVi: [
      "Giấu dưới gối cho Tiên răng",
      "Ném lên mái nhà",
      "Cho chó ăn trong mỡ thịt",
      "Chôn trong vườn",
    ],
    correctIndex: 1,
    explanationEn: "In Korea, children throw lost teeth onto the roof so a magpie can take them and later bring a new tooth.",
    explanationVi: "Ở Hàn Quốc, trẻ ném răng lên mái để chim sáo mang đi và sau đó mang răng mới về.",
  },
  "reading-challenge-2-p3": {
    questionEn: "Why do scientists study the Ring of Fire?",
    questionVi: "Vì sao các nhà khoa học nghiên cứu Vành đai lửa?",
    optionsEn: [
      "It has the world’s only volcanoes",
      "They can observe plate tectonics there",
      "It is the coldest region on Earth",
      "Wegener proved continents never move",
    ],
    optionsVi: [
      "Nơi duy nhất có núi lửa",
      "Có thể quan sát kiến tạo mảng",
      "Vùng lạnh nhất Trái Đất",
      "Wegener chứng minh lục địa không di chuyển",
    ],
    correctIndex: 1,
    explanationEn: "More than 75% of the world’s volcanoes lie in the Ring of Fire, where plate tectonics can be seen at work.",
    explanationVi: "Hơn 75% núi lửa thế giới nằm ở Vành đai lửa, nơi có thể thấy kiến tạo mảng hoạt động.",
  },
  "reading-challenge-2-p4": {
    questionEn: "What does the passage say about popping pimples?",
    questionVi: "Bài nói gì về việc nặn mụn?",
    optionsEn: [
      "It is the best way to cure acne",
      "It pushes germs deeper and can cause more harm",
      "Doctors recommend it for teenagers",
      "It works better than washing your face",
    ],
    optionsVi: [
      "Cách tốt nhất chữa mụn",
      "Đẩy vi khuẩn sâu hơn và gây hại thêm",
      "Bác sĩ khuyên thanh thiếu niên nặn",
      "Hiệu quả hơn rửa mặt",
    ],
    correctIndex: 1,
    explanationEn: "Popping pushes germs under the skin, causing more redness, pain, or even infection.",
    explanationVi: "Nặn mụn đẩy vi khuẩn dưới da, gây đỏ, đau hoặc nhiễm trùng.",
  },
  "reading-challenge-2-p5": {
    questionEn: "What is the main message of this reading about passing gas?",
    questionVi: "Thông điệp chính của bài về việc đánh rắm là gì?",
    optionsEn: [
      "Only nervous people produce gas",
      "Holding gas in is always poisonous",
      "It is normal, and there is no need to be embarrassed",
      "Beans are the only food that causes gas",
    ],
    optionsVi: [
      "Chỉ người lo lắng mới có khí",
      "Nhịn khí luôn gây ngộc",
      "Bình thường, không cần xấu hổ",
      "Chỉ đậu gây khí",
    ],
    correctIndex: 2,
    explanationEn: "The passage says everyone does it, and after you face up to that fact you can learn interesting facts without shame.",
    explanationVi: "Bài cho rằng ai cũng vậy; khi chấp nhận sự thật đó, bạn có thể học thêm mà không cần xấu hổ.",
  },
  "reading-challenge-2-p6": {
    questionEn: "How did Satoru Iwata help change Nintendo’s fortunes?",
    questionVi: "Satoru Iwata đã giúp đổi vận Nintendo như thế nào?",
    optionsEn: [
      "By making consoles only for dedicated gamers",
      "By copying competitors’ most powerful machines",
      "By creating easier, more accessible systems like the DS and Wii",
      "By stopping production of new game types",
    ],
    optionsVi: [
      "Chỉ làm máy cho game thủ cứng",
      "Sao chép máy mạnh nhất của đối thủ",
      "Tạo hệ thống dễ tiếp cận như DS và Wii",
      "Ngừng làm loại game mới",
    ],
    correctIndex: 2,
    explanationEn: "Iwata shifted strategy toward touch screens, motion controls, and games for new kinds of players.",
    explanationVi: "Iwata đổi chiến lược sang màn hình cảm ứng, điều khiển cử động và game cho nhiều đối tượng mới.",
  },
  "reading-challenge-2-p7": {
    questionEn: "Who do many researchers believe is the main cause of too much aggression in children’s sports?",
    questionVi: "Nhiều nhà nghiên cứu cho ai là nguyên nhân chính của sự hung hăng quá mức trong thể thao trẻ em?",
    optionsEn: [
      "Other children on the team",
      "Television cameras only",
      "Adults, especially parents and coaches",
      "Sports equipment manufacturers",
    ],
    optionsVi: [
      "Trẻ khác trong đội",
      "Chỉ máy quay truyền hình",
      "Người lớn, nhất là phụ huynh và HLV",
      "Nhà sản xuất dụng cụ",
    ],
    correctIndex: 2,
    explanationEn: "Researchers say children copy aggressive adult behavior reinforced by parents and coaches.",
    explanationVi: "Họ cho trẻ bắt chước hành vi hung hăng của người lớn, được phụ huynh và HLV củng cố.",
  },
  "reading-challenge-2-p8": {
    questionEn: "What mainly determines how much money an autograph is worth?",
    questionVi: "Điều gì chủ yếu quyết định giá trị tiền của một chữ ký?",
    optionsEn: [
      "Whether the signer is still alive",
      "How rare the autograph is",
      "The color of ink used",
      "Whether it was signed at a restaurant",
    ],
    optionsVi: [
      "Người ký còn sống hay không",
      "Chữ ký hiếm đến mức nào",
      "Màu mực",
      "Ký tại nhà hàng hay không",
    ],
    correctIndex: 1,
    explanationEn: "The price depends on rarity — for example, Madonna and Nicole Kidman rarely sign, so their autographs cost more.",
    explanationVi: "Giá phụ thuộc độ hiếm — ví dụ Madonna và Nicole Kidman hiếm khi ký nên chữ ký đắt hơn.",
  },
  "reading-challenge-2-p9": {
    questionEn: "Why are the Martin jetpack and Jetlev-Flyer unlikely to sell widely?",
    questionVi: "Vì sao Martin jetpack và Jetlev-Flyer khó bán rộng rãi?",
    optionsEn: [
      "They cannot fly at all",
      "They are banned by law everywhere",
      "They cost over $100,000 each",
      "They only work in comic books",
    ],
    optionsVi: [
      "Chúng không bay được",
      "Bị cấm ở mọi nơi",
      "Mỗi chiếc hơn 100.000 đô la",
      "Chỉ hoạt động trong truyện tranh",
    ],
    correctIndex: 2,
    explanationEn: "Both jetpacks work but are too expensive for the average person, costing more than $100,000.",
    explanationVi: "Cả hai đều bay được nhưng quá đắt với người bình thường — hơn 100.000 đô la mỗi chiếc.",
  },
  "reading-challenge-2-p10": {
    questionEn: "What solution did Wycliffe Oluoch create for Garissa’s library problem?",
    questionVi: "Wycliffe Oluoch nghĩ ra giải pháp gì cho thư viện Garissa?",
    optionsEn: [
      "Closing the library to save money",
      "Replacing books with the Internet only",
      "A Mobile Camel Library that brings books to villages",
      "Paying children to read at the main building",
    ],
    optionsVi: [
      "Đóng thư viện để tiết kiệm",
      "Chỉ dùng Internet thay sách",
      "Thư viện lạch đà mang sách tới làng",
      "Trả tiền cho trẻ đọc tại trụ sở",
    ],
    correctIndex: 2,
    explanationEn: "When people would not walk to the library, Oluoch strapped books onto camels and took the library to them.",
    explanationVi: "Vì người dân không chịu đi bộ tới thư viện, Oluoch buộc sách lên lạch đà và mang thư viện đến họ.",
  },
  "reading-challenge-2-p11": {
    questionEn: "What happened to the original Globe Theatre in 1613?",
    questionVi: "Nhà hát Globe gốc đã xảy ra chuyện gì năm 1613?",
    optionsEn: [
      "It was closed by Shakespeare",
      "A cannon on stage started a fire that destroyed it",
      "It moved to a new city",
      "It was never rebuilt",
    ],
    optionsVi: [
      "Shakespeare đóng cửa",
      "Đại bác trên sân khấu gây cháy phá hủy",
      "Chuyển sang thành phố khác",
      "Không bao giờ được xây lại",
    ],
    correctIndex: 1,
    explanationEn: "During Henry VIII, a stage cannon set off a fire that completely destroyed the theater.",
    explanationVi: "Trong vở Henry VIII, đại bác sân khấu gây cháy và thiêu rụi nhà hát.",
  },
  "reading-challenge-2-p12": {
    questionEn: "In Italy, how are children traditionally named?",
    questionVi: "Ở Ý, trẻ em truyền thống được đặt tên như thế nào?",
    optionsEn: [
      "Only by fortune-tellers",
      "After the day of the week they were born",
      "After their grandparents",
      "Using random names from a book",
    ],
    optionsVi: [
      "Chỉ do thầy bói",
      "Theo ngày sinh trong tuần",
      "Theo tên ông bà",
      "Tên ngẫu nhiên trong sách",
    ],
    correctIndex: 2,
    explanationEn: "Italian children are traditionally named after grandparents, usually the father’s parents first.",
    explanationVi: "Trẻ Ý truyền thống mang tên ông bà, thường ưu tiên ông bà nội trước.",
  },
  "reading-challenge-2-p13": {
    questionEn: "Approximately what share of the Earth’s surface do rainforests cover?",
    questionVi: "Rừng mưa chiếm khoảng bao nhiêu phần bề mặt Trái Đất?",
    optionsEn: ["About six percent", "About fifty percent", "About ninety percent", "All tropical land"],
    optionsVi: ["Khoảng 6%", "Khoảng 50%", "Khoảng 90%", "Toàn bộ đất nhiệt đới"],
    correctIndex: 0,
    explanationEn: "Rainforests make up only a small part of the Earth’s surface, about six percent.",
    explanationVi: "Rừng mưa chỉ chiếm phần nhỏ bề mặt Trái Đất, khoảng 6%.",
  },
  "reading-challenge-2-p14": {
    questionEn: "According to Red Bull’s makers, what is the drink NOT meant to be?",
    questionVi: "Theo hãng Red Bull, đồ uống KHÔNG nhằm mục đích gì?",
    optionsEn: [
      "A way to revitalize tired consumers",
      "A thirst quencher or athlete fluid replacement drink",
      "A beverage with caffeine and sugar",
      "A product sold in interviews",
    ],
    optionsVi: [
      "Hồi phục người mệt",
      "Giải khát hoặc thay nước cho vận động viên",
      "Đồ uống có caffeine và đường",
      "Sản phẩm quảng bá qua phỏng vấn",
    ],
    correctIndex: 1,
    explanationEn: "The company says Red Bull is not a thirst quencher nor a fluid replacement drink for athletes.",
    explanationVi: "Hãng nói Red Bull không phải đồ giải khát cũng không thay nước cho vận động viên.",
  },
  "reading-challenge-2-p15": {
    questionEn: "Why did the U.S. government legally call tomatoes a vegetable?",
    questionVi: "Vì sao chính phủ Mỹ gọi cà chua là rau theo luật?",
    optionsEn: [
      "Tomatoes have no seeds",
      "Scientists could not tell fruits from vegetables",
      "To tax imported tomatoes, since fruit had no import tax",
      "Farmers wanted to stop eating tomatoes",
    ],
    optionsVi: [
      "Cà chua không có hạt",
      "Khoa học không phân biệt được",
      "Để đánh thuế cà chua nhập khẩu (trái cây không chịu thuế)",
      "Nông dân muốn cấm ăn cà chua",
    ],
    correctIndex: 2,
    explanationEn: "In the 1800s fruit had no import tax but vegetables did, so tomatoes were classified as vegetables to tax imports.",
    explanationVi: "Thế kỷ 19, trái cây nhập khẩu không thuế nhưng rau có; cà chua bị xếp là rau để đánh thuế hàng nhập.",
  },
  "reading-challenge-2-p16": {
    questionEn: "Who was named Sportsman of the 20th Century by the BBC, Sports Illustrated, and the World Sports Award?",
    questionVi: "Ai được BBC, Sports Illustrated và World Sports Award bầu là Vận động viên thế kỷ?",
    optionsEn: ["Jack Nicklaus", "Pelé", "Muhammad Ali", "A golf team from Brazil"],
    optionsVi: ["Jack Nicklaus", "Pelé", "Muhammad Ali", "Đội golf Brazil"],
    correctIndex: 2,
    explanationEn: "Although Nicklaus and Pelé ranked highly, Muhammad Ali was named Sportsman of the Century by all three groups.",
    explanationVi: "Dù Nicklaus và Pelé xếp cao, Muhammad Ali được cả ba tổ chức bầu là Vận động viên thế kỷ.",
  },
  "reading-challenge-2-p17": {
    questionEn: "How do left-handed people’s brains differ from right-handed people’s, according to the passage?",
    questionVi: "Theo bài, não người thuận tay trái khác người thuận tay phải thế nào?",
    optionsEn: [
      "They use only the right hemisphere",
      "They cannot use language well",
      "They use both sides almost equally, with a larger connecting part",
      "They have no connection between the two halves",
    ],
    optionsVi: [
      "Chỉ dùng bán cầu phải",
      "Không dùng ngôn ngữ tốt",
      "Dùng gần như cả hai bên, phần nối lớn hơn",
      "Không có dây nối hai bán cầu",
    ],
    correctIndex: 2,
    explanationEn: "Left-handers use both brain sides almost equally, and the connecting corpus callosum is usually larger.",
    explanationVi: "Người thuận trái dùng gần như cả hai bán cầu; phần nối hai nửa não thường lớn hơn.",
  },
  "reading-challenge-2-p18": {
    questionEn: "What is unusual about Ski Dubai’s location and climate?",
    questionVi: "Điều gì đặc biệt về vị trí và khí hậu của Ski Dubai?",
    optionsEn: [
      "It is in the Swiss Alps",
      "It has natural hills and heavy winter snow outdoors",
      "It was built in a desert where it never snows naturally",
      "Outdoor summer temperatures stay below freezing",
    ],
    optionsVi: [
      "Ở dãy Alps Thụy Sĩ",
      "Có đồi tự nhiên và tuyết dày ngoài trời",
      "Xây ở sa mạc, không bao giờ có tuyết tự nhiên",
      "Hè ngoài trời luôn dưới 0°C",
    ],
    correctIndex: 2,
    explanationEn: "Ski Dubai operates indoors in a desert city where there are no natural hills and it never snows outside.",
    explanationVi: "Ski Dubai trong nhà ở thành phố sa mạc — không có đồi tự nhiên và không tuyết ngoài trời.",
  },
  "reading-challenge-2-p19": {
    questionEn: "Which type of hacker does the passage describe as more dangerous?",
    questionVi: "Loại hacker nào bài mô tả là nguy hiểm hơn?",
    optionsEn: [
      "Passive hackers who only enter systems",
      "Active hackers who damage or steal data",
      "Hackers who only guess weak passwords",
      "People who design password-plus cards",
    ],
    optionsVi: [
      "Hack thụ động chỉ xâm nhập",
      "Hack chủ động phá hoại hoặc trộm dữ liệu",
      "Chỉ đoán mật khẩu yếu",
      "Người thiết kế thẻ password-plus",
    ],
    correctIndex: 1,
    explanationEn: "Active hackers release viruses or alter, delete, or take information and are called the more dangerous type.",
    explanationVi: "Hack chủ động phát virus hoặc sửa, xóa, lấy thông tin — bài gọi đây là loại nguy hiểm hơn.",
  },
  "reading-challenge-2-p20": {
    questionEn: "What was one of Arthur Pedrick’s bizarre plans for Australia?",
    questionVi: "Một kế hoạch kỳ quặc của Arthur Pedrick cho Australia là gì?",
    optionsEn: [
      "Building a radio-controlled golf ball factory only",
      "Tubes carrying ice balls from Antarctica to melt for irrigation",
      "Selling underwear for dogs in Antarctica",
      "Banning all inventions that break physics",
    ],
    optionsVi: [
      "Chỉ xưởng bóng golf điều khiển từ xa",
      "Ống chở cục băng từ Nam Cực tan ra để tưới tiêu",
      "Bán quần lót cho chó ở Nam Cực",
      "Cấm mọi phát minh trái vật lý",
    ],
    correctIndex: 1,
    explanationEn: "He imagined 10,000 km tubes bringing Antarctic ice to melt in the Australian desert for irrigation.",
    explanationVi: "Ông tưởng tượng ống dài 10.000 km chở băng Nam Cực tan ở sa mạc Australia để tưới.",
  },
};
