import type { PassageVocabItem } from "@/lib/reading/passage-vocabulary";

/** Từ vựng curated theo unit — PDF extract idioms bị lặp unit 1 trên mọi bài. */
export const READING_CHALLENGE_2_VOCABULARY: Record<string, PassageVocabItem[]> = {
  "reading-challenge-2-p1": [
    { term: "cosmetics", definitionVi: "mỹ phẩm", level: "B1-B2" },
    { term: "sunscreen", definitionVi: "kem chống nắng", level: "B1-B2" },
    { term: "kohl", definitionVi: "phấn kắt mắt đen (Ai Cập cổ)", level: "C1" },
    { term: "belladonna", definitionVi: "cây thuốc độc (nhỏ mắt thời Phục hưng)", level: "C1" },
    { term: "in the name of", definitionVi: "vì, để (làm đẹp)", level: "B1-B2" },
  ],
  "reading-challenge-2-p2": [
    { term: "tradition", definitionVi: "truyền thống", level: "B1-B2" },
    { term: "magpie", definitionVi: "chim sáo", level: "B1-B2" },
    { term: "guardian angel", definitionVi: "thiên thần hộ mệnh", level: "B1-B2" },
    { term: "count on", definitionVi: "trông chờ, tin cậy", level: "B1-B2" },
    { term: "the wee hours", definitionVi: "rạng sáng (nửa đêm–4–5 giờ)", level: "C1" },
  ],
  "reading-challenge-2-p3": [
    { term: "Ring of Fire", definitionVi: "Vành đai lửa Thái Bình Dương", level: "B1-B2" },
    { term: "plate tectonics", definitionVi: "kiến tạo mảng", level: "C1" },
    { term: "magma", definitionVi: "magma (đá nóng chảy)", level: "B1-B2" },
    { term: "subduction", definitionVi: "sự hút chìm mảng kiến tạo", level: "C1" },
    { term: "right on the mark", definitionVi: "hoàn toàn đúng", level: "B1-B2" },
  ],
  "reading-challenge-2-p4": [
    { term: "acne", definitionVi: "mụn trứng cá", level: "B1-B2" },
    { term: "puberty", definitionVi: "tuổi dậy thì", level: "B1-B2" },
    { term: "popping pimples", definitionVi: "nặn mụn", level: "B1-B2" },
    { term: "myth", definitionVi: "điều sai lầm, huyền thoại", level: "B1-B2" },
    { term: "infection", definitionVi: "nhiễm trùng", level: "B1-B2" },
  ],
  "reading-challenge-2-p5": [
    { term: "intestines", definitionVi: "ruột", level: "B1-B2" },
    { term: "sulfur", definitionVi: "lưu huỳnh", level: "B1-B2" },
    { term: "face up to", definitionVi: "đối mặt, thừa nhận", level: "B1-B2" },
    { term: "cut the cheese", definitionVi: "đánh rắm (tiếng lóng)", level: "B1-B2" },
    { term: "digestive", definitionVi: "tiêu hóa", level: "B1-B2" },
  ],
  "reading-challenge-2-p6": [
    { term: "innovative", definitionVi: "đổi mới, sáng tạo", level: "B1-B2" },
    { term: "CEO", definitionVi: "giám đốc điều hành", level: "B1-B2" },
    { term: "touch screen", definitionVi: "màn hình cảm ứng", level: "B1-B2" },
    { term: "motion-based", definitionVi: "dựa trên cử động cơ thể", level: "B1-B2" },
    { term: "groundbreaking", definitionVi: "đột phá", level: "C1" },
  ],
  "reading-challenge-2-p7": [
    { term: "self-esteem", definitionVi: "lòng tự trọng", level: "B1-B2" },
    { term: "aggressive behavior", definitionVi: "hành vi hung hăng", level: "B1-B2" },
    { term: "reinforced", definitionVi: "được củng cố, tăng cường", level: "B1-B2" },
    { term: "coaches", definitionVi: "huấn luyện viên", level: "B1-B2" },
    { term: "face up to", definitionVi: "đối mặt (vấn đề)", level: "B1-B2" },
  ],
  "reading-challenge-2-p8": [
    { term: "autograph", definitionVi: "chữ ký (người nổi tiếng)", level: "B1-B2" },
    { term: "autograph hound", definitionVi: "người săn chữ ký để bán", level: "C1" },
    { term: "rare", definitionVi: "hiếm", level: "B1-B2" },
    { term: "admiration", definitionVi: "sự ngưỡng mộ", level: "B1-B2" },
    { term: "signature", definitionVi: "chữ ký", level: "B1-B2" },
  ],
  "reading-challenge-2-p9": [
    { term: "jetpack", definitionVi: "balo phản lực cá nhân", level: "B1-B2" },
    { term: "propel", definitionVi: "đẩy, phóng", level: "C1" },
    { term: "experimental", definitionVi: "thử nghiệm", level: "B1-B2" },
    { term: "vision of the future", definitionVi: "tầm nhìn tương lai", level: "B1-B2" },
    { term: "on the market", definitionVi: "đang bán trên thị trường", level: "B1-B2" },
  ],
  "reading-challenge-2-p10": [
    { term: "mobile library", definitionVi: "thư viện lưu động", level: "B1-B2" },
    { term: "entice", definitionVi: "lôi cuốn, thu hút", level: "C1" },
    { term: "herdsman", definitionVi: "người chăn lạc đà", level: "B1-B2" },
    { term: "rack one's brain", definitionVi: "vắt óc suy nghĩ", level: "B1-B2" },
    { term: "hit upon an idea", definitionVi: "bất ngờ nghĩ ra ý hay", level: "B1-B2" },
  ],
  "reading-challenge-2-p11": [
    { term: "playwright", definitionVi: "nhà viết kịch", level: "B1-B2" },
    { term: "open-air theater", definitionVi: "nhà hát ngoài trời", level: "B1-B2" },
    { term: "Puritans", definitionVi: "người Thanh giáo (Anh)", level: "C1" },
    { term: "props", definitionVi: "đạo cụ sân khấu", level: "B1-B2" },
    { term: "tourist attraction", definitionVi: "điểm du lịch", level: "B1-B2" },
  ],
  "reading-challenge-2-p12": [
    { term: "ancestors", definitionVi: "tổ tiên", level: "B1-B2" },
    { term: "fortune-teller", definitionVi: "thầy bói", level: "B1-B2" },
    { term: "character", definitionVi: "tính cách", level: "B1-B2" },
    { term: "in some cases", definitionVi: "trong một số trường hợp", level: "B1-B2" },
    { term: "treasured", definitionVi: "được trân trọng", level: "B1-B2" },
  ],
  "reading-challenge-2-p13": [
    { term: "humid", definitionVi: "ẩm ướt", level: "B1-B2" },
    { term: "lungs of the planet", definitionVi: "lá phổi của hành tinh", level: "B1-B2" },
    { term: "species", definitionVi: "loài", level: "B1-B2" },
    { term: "cut down", definitionVi: "chặt (cây)", level: "B1-B2" },
    { term: "be made of", definitionVi: "được làm từ", level: "B1-B2" },
  ],
  "reading-challenge-2-p14": [
    { term: "energy drink", definitionVi: "nước tăng lực", level: "B1-B2" },
    { term: "caffeine", definitionVi: "caffeine", level: "B1-B2" },
    { term: "revitalize", definitionVi: "hồi phục sức sống", level: "C1" },
    { term: "thirst quencher", definitionVi: "đồ uống giải khát", level: "B1-B2" },
    { term: "pick-me-up", definitionVi: "thứ giúp tỉnh táo, tiếp thêm năng lượng", level: "B1-B2" },
  ],
  "reading-challenge-2-p15": [
    { term: "controversy", definitionVi: "tranh cãi", level: "B1-B2" },
    { term: "nightshade", definitionVi: "cây thuốc độc (họ cà)", level: "C1" },
    { term: "werewolf", definitionVi: "người sói", level: "B1-B2" },
    { term: "import tax", definitionVi: "thuế nhập khẩu", level: "B1-B2" },
    { term: "be due for", definitionVi: "sắp đến lúc (có chuyện gì)", level: "B1-B2" },
  ],
  "reading-challenge-2-p16": [
    { term: "Sportsman of the Century", definitionVi: "Vận động viên thế kỷ", level: "B1-B2" },
    { term: "civil liberties", definitionVi: "quyền tự do dân sự", level: "C1" },
    { term: "charity work", definitionVi: "công việc từ thiện", level: "B1-B2" },
    { term: "legend", definitionVi: "huyền thoại", level: "B1-B2" },
    { term: "speak out against", definitionVi: "lên tiếng phản đối", level: "B1-B2" },
  ],
  "reading-challenge-2-p17": [
    { term: "southpaw", definitionVi: "người thuận tay trái", level: "C1" },
    { term: "sinister", definitionVi: "đáng sợ; (tiếng Latin) trái", level: "C1" },
    { term: "hemisphere", definitionVi: "bán cầu não", level: "B1-B2" },
    { term: "prejudice", definitionVi: "định kiến", level: "B1-B2" },
    { term: "stereotyped", definitionVi: "bị gán khuôn mẫu", level: "C1" },
  ],
  "reading-challenge-2-p18": [
    { term: "indoor ski", definitionVi: "trượt tuyết trong nhà", level: "B1-B2" },
    { term: "exotic", definitionVi: "kỳ lạ, xa lạ", level: "B1-B2" },
    { term: "manmade snow", definitionVi: "tuyết nhân tạo", level: "B1-B2" },
    { term: "black diamond", definitionVi: "đường trượt khó (cấp độ cao)", level: "C1" },
    { term: "year round", definitionVi: "quanh năm", level: "B1-B2" },
  ],
  "reading-challenge-2-p19": [
    { term: "unauthorized", definitionVi: "trái phép", level: "B1-B2" },
    { term: "protocols", definitionVi: "giao thức (mạng máy tính)", level: "C1" },
    { term: "passive hacking", definitionVi: "hack thụ động (chỉ xâm nhập)", level: "C1" },
    { term: "password-plus", definitionVi: "mật khẩu kèm mã thứ hai", level: "B1-B2" },
    { term: "by far", definitionVi: "vượt trội, rõ ràng nhất", level: "B1-B2" },
  ],
  "reading-challenge-2-p20": [
    { term: "inventor", definitionVi: "nhà phát minh", level: "B1-B2" },
    { term: "bizarre", definitionVi: "kỳ quặc", level: "B1-B2" },
    { term: "irrigation", definitionVi: "tưới tiêu", level: "B1-B2" },
    { term: "theft-prevention", definitionVi: "chống trộm", level: "B1-B2" },
    { term: "out in left field", definitionVi: "kỳ quặc, lạ đời (ý tưởng)", level: "C1" },
  ],
};
