import type { PassageVocabItem } from "@/lib/reading/passage-vocabulary";

/** Từ vựng curated theo unit — PDF extract idioms bị lặp unit 1 trên mọi bài. */
export const READING_CHALLENGE_1_VOCABULARY: Record<string, PassageVocabItem[]> = {
  "reading-challenge-1-p1": [
    { term: "check in", definitionVi: "nhận phòng (khách sạn)", level: "B1-B2" },
    { term: "made of", definitionVi: "được làm từ", level: "B1-B2" },
    { term: "unusual", definitionVi: "bất thường, đặc biệt", level: "B1-B2" },
    { term: "atmosphere", definitionVi: "không khí, bầu không khí", level: "B1-B2" },
    { term: "cozy", definitionVi: "ấm áp, thoải mái", level: "B1-B2" },
  ],
  "reading-challenge-1-p2": [
    { term: "curry", definitionVi: "món cà ri", level: "B1-B2" },
    { term: "spices", definitionVi: "gia vị", level: "B1-B2" },
    { term: "catch on", definitionVi: "trở nên phổ biến", level: "B1-B2" },
    { term: "according to", definitionVi: "theo như", level: "B1-B2" },
    { term: "delicious", definitionVi: "ngon", level: "B1-B2" },
  ],
  "reading-challenge-1-p3": [
    { term: "cyclone", definitionVi: "bão nhiệt đới", level: "B1-B2" },
    { term: "hurricane", definitionVi: "bão (cơn bão lớn)", level: "B1-B2" },
    { term: "meteorologist", definitionVi: "nhà khí tượng", level: "C1" },
    { term: "detect", definitionVi: "phát hiện", level: "B1-B2" },
    { term: "danger", definitionVi: "nguy hiểm", level: "B1-B2" },
  ],
  "reading-challenge-1-p4": [
    { term: "butterflies in one's stomach", definitionVi: "hồi hộp, bồn chồn", level: "B1-B2" },
    { term: "stressful", definitionVi: "gây căng thẳng", level: "B1-B2" },
    { term: "cortisol", definitionVi: "cortisol (hormone căng thẳng)", level: "C1" },
    { term: "relax", definitionVi: "thư giãn", level: "B1-B2" },
    { term: "whisper", definitionVi: "thì thầm", level: "B1-B2" },
  ],
  "reading-challenge-1-p5": [
    { term: "mammal", definitionVi: "động vật có vú", level: "B1-B2" },
    { term: "reptile", definitionVi: "bò sát", level: "B1-B2" },
    { term: "insect", definitionVi: "côn trùng", level: "B1-B2" },
    { term: "stimulant", definitionVi: "chất kích thích", level: "C1" },
    { term: "behavior", definitionVi: "hành vi", level: "B1-B2" },
  ],
  "reading-challenge-1-p6": [
    { term: "professional", definitionVi: "chuyên nghiệp", level: "B1-B2" },
    { term: "championship", definitionVi: "giải vô địch", level: "B1-B2" },
    { term: "role model", definitionVi: "hình mẫu", level: "B1-B2" },
    { term: "diversity", definitionVi: "đa dạng", level: "B1-B2" },
    { term: "foundation", definitionVi: "quỹ (tổ chức phi lợi nhuận)", level: "B1-B2" },
  ],
  "reading-challenge-1-p7": [
    { term: "distorted", definitionVi: "bị bóp méo, sai lệch", level: "C1" },
    { term: "exaggerate", definitionVi: "phóng đại", level: "B1-B2" },
    { term: "misery", definitionVi: "đau khổ", level: "B1-B2" },
    { term: "informed", definitionVi: "có thông tin, sáng suốt", level: "B1-B2" },
    { term: "balanced", definitionVi: "cân bằng", level: "B1-B2" },
  ],
  "reading-challenge-1-p8": [
    { term: "inventor", definitionVi: "nhà phát minh", level: "B1-B2" },
    { term: "glider", definitionVi: "tàu lượn (máy bay không động cơ)", level: "B1-B2" },
    { term: "propeller", definitionVi: "cánh quạt", level: "B1-B2" },
    { term: "engine", definitionVi: "động cơ", level: "B1-B2" },
    { term: "make history", definitionVi: "ghi dấu lịch sử", level: "B1-B2" },
  ],
  "reading-challenge-1-p9": [
    { term: "firewall", definitionVi: "tường lửa (bảo mật mạng)", level: "B1-B2" },
    { term: "hacker", definitionVi: "hacker, tin tặc", level: "B1-B2" },
    { term: "security", definitionVi: "an ninh, bảo mật", level: "B1-B2" },
    { term: "trusting", definitionVi: "dễ tin, hay tin người", level: "B1-B2" },
    { term: "pose as", definitionVi: "giả danh là", level: "C1" },
  ],
  "reading-challenge-1-p10": [
    { term: "beetle", definitionVi: "bọ cánh cứng", level: "B1-B2" },
    { term: "vending machine", definitionVi: "máy bán hàng tự động", level: "B1-B2" },
    { term: "conservationist", definitionVi: "nhà bảo tồn thiên nhiên", level: "C1" },
    { term: "in the wild", definitionVi: "trong tự nhiên", level: "B1-B2" },
    { term: "harmful", definitionVi: "có hại", level: "B1-B2" },
  ],
  "reading-challenge-1-p11": [
    { term: "portrait", definitionVi: "chân dung", level: "B1-B2" },
    { term: "mystery", definitionVi: "bí ẩn", level: "B1-B2" },
    { term: "identity", definitionVi: "danh tính", level: "B1-B2" },
    { term: "unearthly", definitionVi: "siêu thực, khác thường", level: "C1" },
    { term: "historian", definitionVi: "nhà sử học", level: "B1-B2" },
  ],
  "reading-challenge-1-p12": [
    { term: "originally", definitionVi: "ban đầu, gốc là", level: "B1-B2" },
    { term: "borrowed", definitionVi: "mượn (từ ngôn ngữ khác)", level: "B1-B2" },
    { term: "massage", definitionVi: "mát-xa", level: "B1-B2" },
    { term: "sailor", definitionVi: "thủy thủ", level: "B1-B2" },
    { term: "sauna", definitionVi: "phòng xông hơi (Phần Lan)", level: "B1-B2" },
  ],
  "reading-challenge-1-p13": [
    { term: "rainfall", definitionVi: "lượng mưa", level: "B1-B2" },
    { term: "desertification", definitionVi: "sa mạc hóa", level: "C1" },
    { term: "pollution", definitionVi: "ô nhiễm", level: "B1-B2" },
    { term: "farmland", definitionVi: "đất canh tác", level: "B1-B2" },
    { term: "ruin", definitionVi: "làm hỏng, tàn phá", level: "B1-B2" },
  ],
  "reading-challenge-1-p14": [
    { term: "digestion", definitionVi: "tiêu hóa", level: "B1-B2" },
    { term: "kidney", definitionVi: "thận", level: "B1-B2" },
    { term: "intestine", definitionVi: "ruột", level: "B1-B2" },
    { term: "nutrient", definitionVi: "chất dinh dưỡng", level: "B1-B2" },
    { term: "dilute", definitionVi: "pha loãng", level: "C1" },
  ],
  "reading-challenge-1-p15": [
    { term: "natural disaster", definitionVi: "thiên tai", level: "B1-B2" },
    { term: "earthquake", definitionVi: "động đất", level: "B1-B2" },
    { term: "observe", definitionVi: "quan sát", level: "B1-B2" },
    { term: "aggressive", definitionVi: "hung hăng", level: "B1-B2" },
    { term: "predict", definitionVi: "dự đoán", level: "B1-B2" },
  ],
  "reading-challenge-1-p16": [
    { term: "animation", definitionVi: "hoạt hình", level: "B1-B2" },
    { term: "supernatural", definitionVi: "siêu nhiên", level: "B1-B2" },
    { term: "warm-hearted", definitionVi: "ấm áp, nhân hậu", level: "B1-B2" },
    { term: "fantasy", definitionVi: "giả tưởng", level: "B1-B2" },
    { term: "natural world", definitionVi: "thế giới tự nhiên", level: "B1-B2" },
  ],
  "reading-challenge-1-p17": [
    { term: "excited", definitionVi: "hứng khởi", level: "B1-B2" },
    { term: "concentrate", definitionVi: "tập trung", level: "B1-B2" },
    { term: "confidence", definitionVi: "sự tự tin", level: "B1-B2" },
    { term: "appearance", definitionVi: "vẻ ngoài", level: "B1-B2" },
    { term: "energetic", definitionVi: "năng động", level: "B1-B2" },
  ],
  "reading-challenge-1-p18": [
    { term: "philatelist", definitionVi: "người sưu tầm tem", level: "C1" },
    { term: "postage stamp", definitionVi: "tem bưu chính", level: "B1-B2" },
    { term: "hobby", definitionVi: "sở thích", level: "B1-B2" },
    { term: "condition", definitionVi: "tình trạng (tem)", level: "B1-B2" },
    { term: "print run", definitionVi: "số lượng in", level: "C1" },
  ],
  "reading-challenge-1-p19": [
    { term: "piracy", definitionVi: "vi phạm bản quyền", level: "B1-B2" },
    { term: "culprit", definitionVi: "thủ phạm", level: "C1" },
    { term: "pirated", definitionVi: "bị sao chép trái phép", level: "B1-B2" },
    { term: "greedy", definitionVi: "tham lam", level: "B1-B2" },
    { term: "analyze", definitionVi: "phân tích", level: "B1-B2" },
  ],
  "reading-challenge-1-p20": [
    { term: "pass away", definitionVi: "qua đời", level: "B1-B2" },
    { term: "leave behind", definitionVi: "để lại (tài sản)", level: "B1-B2" },
    { term: "heir", definitionVi: "người thừa kế", level: "B1-B2" },
    { term: "fortune", definitionVi: "gia tài lớn", level: "B1-B2" },
    { term: "inherit", definitionVi: "thừa kế", level: "B1-B2" },
  ],
};
