import type { QuickCheckQuiz } from "@/lib/reading/passage-quiz";

/** Kiểm tra nhanh Compass — câu đọc hiểu theo nội dung bài (MCQ Q1 từ sách). */
export const READING_CHALLENGE_3_QUIZ: Record<string, QuickCheckQuiz> = {
  "reading-challenge-3-p1": {
    questionEn: "What is the main focus of this reading?",
    questionVi: "Trọng tâm của bài đọc là gì?",
    optionsEn: [
      "Books that make more money than movies",
      "Books written about movies",
      "Movie made from books",
      "Movie stars who have written books",
    ],
    optionsVi: [
      "Sách kiếm nhiều tiền hơn phim",
      "Sách viết về phim",
      "Phim làm từ sách",
      "Ngôi sao phim viết sách",
    ],
    correctIndex: 2,
    explanationEn: "The passage states: The movie industry seems to believe that if the story made a great book, it should make a great movie as well.",
    explanationVi: "Bài nêu: The movie industry seems to believe that if the story made a great book, it should make a great movie as well.",
  },
  "reading-challenge-3-p2": {
    questionEn: "What is the main idea of this reading?",
    questionVi: "Ý chính của bài đọc là gì?",
    optionsEn: [
      "Birds bring bad luck.",
      "Don't look a crow in the eye.",
      "There are many superstitions surrounding birds.",
      "Birds are important to English people.",
    ],
    optionsVi: [
      "Chim mang vận xui",
      "Không nhìn quạ trong mắt",
      "Có nhiều mê tín về chim",
      "Chim quan trọng với người Anh",
    ],
    correctIndex: 2,
    explanationEn: "The passage states: Though many people think these superstitions are old wives' tales, there is actually some evidence to support them.",
    explanationVi: "Bài nêu: Though many people think these superstitions are old wives' tales, there is actually some evidence to support them.",
  },
  "reading-challenge-3-p3": {
    questionEn: "What is the main idea of this reading?",
    questionVi: "Ý chính của bài đọc là gì?",
    optionsEn: [
      "Alaskan trees are dying.",
      "Warmer temperatures are affecting Alaska.",
      "Alaska has beautiful glaciers.",
      "Alaskan villages must relocate.",
    ],
    optionsVi: [
      "Cây Alaska đang chết",
      "Nhiệt độ ấm hơn ảnh hưởng Alaska",
      "Alaska có sông băng đẹp",
      "Làng Alaska phải di dời",
    ],
    correctIndex: 1,
    explanationEn: "The passage states: The melting permafrost and increasing temperatures are both affecting the forests of Alaska.",
    explanationVi: "Bài nêu: The melting permafrost and increasing temperatures are both affecting the forests of Alaska.",
  },
  "reading-challenge-3-p4": {
    questionEn: "What is the main idea of this reading?",
    questionVi: "Ý chính của bài đọc là gì?",
    optionsEn: [
      "Daily exercise can often be bad for your health.",
      "Working out properly is the only way to gain effective hea lth results.",
      "Most people know how to work out efficiently and effective ly.",
      "Adding a variety of workouts to your routine is not import ant.",
    ],
    optionsVi: [
      "Tập hàng ngày thường gây hại sức khỏe",
      "Tập đúng cách là cách duy nhất có kết quả sức khỏe hiệu quả",
      "Đa số biết tập hiệu quả",
      "Thêm đa dạng bài tập không quan trọng",
    ],
    correctIndex: 1,
    explanationEn: "The passage states: Instead of concentrating on how to get the best results efficiently and effectively, people usually rush through their workouts, or they make the same common workout mistakes.",
    explanationVi: "Bài nêu: Instead of concentrating on how to get the best results efficiently and effectively, people usually rush through their workouts, or they make the same common workout mistakes.",
  },
  "reading-challenge-3-p5": {
    questionEn: "What is the main idea of this reading?",
    questionVi: "Ý chính của bài đọc là gì?",
    optionsEn: [
      "How to exercise",
      "How exercise helps the brain",
      "How to get good scores on a test",
      "How the brain can ch ange",
    ],
    optionsVi: [
      "Cách tập luyện",
      "Tập luyện giúp não",
      "Cách đạt điểm cao trong bài thi",
      "Não có thể thay đổi",
    ],
    correctIndex: 1,
    explanationEn: "The passage states: According to her research, it seems that exercise can make blood vessels, including those in the brain, stronger and more fully developed.",
    explanationVi: "Bài nêu: According to her research, it seems that exercise can make blood vessels, including those in the brain, stronger and more fully developed.",
  },
  "reading-challenge-3-p6": {
    questionEn: "What is another possible title for this reading?",
    questionVi: "Tiêu đề khác có thể cho bài đọc này là gì?",
    optionsEn: [
      "“ A Man and His Museum”",
      "“Beijing's Best Museum Designer”",
      "“Changes in Chinese Architecture”",
      "“The Largest Museum in China”",
    ],
    optionsVi: [
      "“Một người và bảo tàng của ông”",
      "“Nhà thiết kế bảo tàng xuất sắc Bắc Kinh”",
      "“Thay đổi kiến trúc Trung Quốc”",
      "“Bảo tàng lớn nhất Trung Quốc”",
    ],
    correctIndex: 0,
    explanationEn: "The passage states: The museum displays some of the best examples of Chinese folk art he has collected over his lifetime.",
    explanationVi: "Bài nêu: The museum displays some of the best examples of Chinese folk art he has collected over his lifetime.",
  },
  "reading-challenge-3-p7": {
    questionEn: "What is this reading about?",
    questionVi: "Bài đọc nói về gì?",
    optionsEn: [
      "A place to buy robots",
      "A new kind of toy",
      "An experiment",
      "An interesting idea for the future",
    ],
    optionsVi: [
      "Nơi mua robot",
      "Loại đồ chơi mới",
      "Một thí nghiệm",
      "Ý tưởng thú vị cho tương lai",
    ],
    correctIndex: 2,
    explanationEn: "The passage states: Aresearcher intereste din studying how helpful people really are uses such robots in her experiments t hat take place on the streets of New York.",
    explanationVi: "Bài nêu: Aresearcher intereste din studying how helpful people really are uses such robots in her experiments t hat take place on the streets of New York.",
  },
  "reading-challenge-3-p8": {
    questionEn: "What is the main idea of this reading?",
    questionVi: "Ý chính của bài đọc là gì?",
    optionsEn: [
      "Why inline skating is popular",
      "The history of inline sk ating competitions",
      "How inline skating developed",
      "The story of Scott and B rennan Olson",
    ],
    optionsVi: [
      "Vì sao trượt patin inline phổ biến",
      "Lịch sử giải trượt inline",
      "Inline skating phát triển ra sao",
      "Câu chuyện Scott và Brennan Olson",
    ],
    correctIndex: 2,
    explanationEn: "The passage states: Such wa s the case for Americans Scott and Brennan Olson, who used an old idea to launch a hot new trend in sports: inline roller skating.",
    explanationVi: "Bài nêu: Such wa s the case for Americans Scott and Brennan Olson, who used an old idea to launch a hot new trend in sports: inline roller skating.",
  },
  "reading-challenge-3-p9": {
    questionEn: "What is the focus of this reading?",
    questionVi: "Trọng tâm của bài đọc là gì?",
    optionsEn: [
      "How snakebots were invented",
      "Similarities between snakes and robots",
      "The mission of the first working snakebot",
      "What a snakebot looks like and can do",
    ],
    optionsVi: [
      "Snakebot được phát minh như thế nào",
      "Điểm giống giữa rắn và robot",
      "Nhiệm vụ của snakebot đầu tiên",
      "Snakebot trông thế nào và làm gì",
    ],
    correctIndex: 3,
    explanationEn: "The passage states: These new robots move like snakes, so they have been given the name “snakebots.” The way a snake is shaped lets it get into very small spaces, like cracks in rocks.",
    explanationVi: "Bài nêu: These new robots move like snakes, so they have been given the name “snakebots.” The way a snake is shaped lets it get into very small spaces, like cracks in rocks.",
  },
  "reading-challenge-3-p10": {
    questionEn: "What question does this reading answer?",
    questionVi: "Bài đọc trả lời câu hỏi nào?",
    optionsEn: [
      "How did flowers curb crime?",
      "What kinds of flowers are popular there?",
      "Who were the thieves in Suginami?",
      "Why was the crime ra te in the city so high?",
    ],
    optionsVi: [
      "Hoa đã hạn chế tội phạm ra sao?",
      "Loại hoa nào phổ biến ở đó?",
      "Ai là kẻ trộm ở Suginami?",
      "Vì sao tỷ lệ tội phạm cao?",
    ],
    correctIndex: 0,
    explanationEn: "The passage states: The police and officials in Suginami knew that something had to be done to curb all of the crime in their area.",
    explanationVi: "Bài nêu: The police and officials in Suginami knew that something had to be done to curb all of the crime in their area.",
  },
  "reading-challenge-3-p11": {
    questionEn: "What is the main idea of the reading?",
    questionVi: "Ý chính của bài đọc là gì?",
    optionsEn: [
      "People sometimes disagree about restoring historical treasu res.",
      "The statue of David is a famous masterpiece.",
      "Restoring works of art is expensive.",
      "The Taj Mahal needs to be repaired.",
    ],
    optionsVi: [
      "Đôi khi người ta bất đồng về phục hồi di sản",
      "Tượng David là kiệt tác nổi tiếng",
      "Phục hồi tác phẩm nghệ thuật tốn kém",
      "Taj Mahal cần sửa chữa",
    ],
    correctIndex: 0,
    explanationEn: "The passage states: In some cases, there is a pressing need for something to be done in order to save a historical treasure.",
    explanationVi: "Bài nêu: In some cases, there is a pressing need for something to be done in order to save a historical treasure.",
  },
  "reading-challenge-3-p12": {
    questionEn: "What is the main idea of the reading?",
    questionVi: "Ý chính của bài đọc là gì?",
    optionsEn: [
      "Many cultures have stories about a flood.",
      "A flood killed many people.",
      "The legend of the flood is not true.",
      "Floods can be very dangerous.",
    ],
    optionsVi: [
      "Nhiều nền văn hóa có truyện lũ lụt",
      "Một trận lũ giết nhiều người",
      "Truyền thuyết lũ lụt không đúng",
      "Lũ lụt rất nguy hiểm",
    ],
    correctIndex: 0,
    explanationEn: "The passage states: Actually, many cultures have similar stories about a great flood that wiped out almost everyone on Earth.",
    explanationVi: "Bài nêu: Actually, many cultures have similar stories about a great flood that wiped out almost everyone on Earth.",
  },
  "reading-challenge-3-p13": {
    questionEn: "What is the main idea of this reading?",
    questionVi: "Ý chính của bài đọc là gì?",
    optionsEn: [
      "Environmentalists are concerned about energy.",
      "Earthships are in many different countries.",
      "Earthships look like typical houses.",
      "Earthships are environmentally friendly homes.",
    ],
    optionsVi: [
      "Nhà môi trường lo về năng lượng",
      "Earthship có ở nhiều nước",
      "Earthship trông như nhà thường",
      "Earthship là nhà thân thiện môi trường",
    ],
    correctIndex: 3,
    explanationEn: "The passage states: All of these features make earthships very environmentally friendly.",
    explanationVi: "Bài nêu: All of these features make earthships very environmentally friendly.",
  },
  "reading-challenge-3-p14": {
    questionEn: "What is the main idea of the reading?",
    questionVi: "Ý chính của bài đọc là gì?",
    optionsEn: [
      "Our bodies are aging.",
      "Carrots are good for us.",
      "Food affects aging.",
      "We should use facial cream.",
    ],
    optionsVi: [
      "Cơ thể ta đang lão hóa",
      "Cà rốt tốt cho ta",
      "Thức ăn ảnh hưởng lão hóa",
      "Nên dùng kem dưỡng mặt",
    ],
    correctIndex: 2,
    explanationEn: "The passage states: However, as we get older, these repair mechanisms start to break down, resulting in signs of aging, such as wrinkles.",
    explanationVi: "Bài nêu: However, as we get older, these repair mechanisms start to break down, resulting in signs of aging, such as wrinkles.",
  },
  "reading-challenge-3-p15": {
    questionEn: "What question is the main focus of this reading?",
    questionVi: "Bài đọc tập trung vào câu hỏi nào?",
    optionsEn: [
      "Can daydreams reduce the hours we sleep?",
      "How is daydreaming different from sleeping?",
      "Who daydreams more, men or women?",
      "Why is daydreaming good for people?",
    ],
    optionsVi: [
      "Mơ mộng ban ngày có làm giảm giờ ngủ không?",
      "Mơ mộng ban ngày khác giấc ngủ ở điểm nào?",
      "Ai mơ mộng ban ngày nhiều hơn, nam hay nữ?",
      "Vì sao mơ mộng ban ngày có lợi cho con người?",
    ],
    correctIndex: 3,
    explanationEn:
      "The passage states that daydreaming is far from a waste of time — many scientists believe it is a healthy and useful activity for the brain.",
    explanationVi:
      "Bài nêu rằng mơ mộng ban ngày không phải lãng phí thời gian — nhiều nhà khoa học cho rằng đó là hoạt động lành mạnh và hữu ích cho não bộ.",
  },
  "reading-challenge-3-p16": {
    questionEn: "Which question does this passage focus on answering?",
    questionVi: "Bài tập trung trả lời câu hỏi nào?",
    optionsEn: [
      "How does Madonna control the distribution of her music?",
      "What are Madonna's most popular songs?",
      "How did Madonna deal with the problem of music piracy?",
      "Why does Madonna give away her music?",
    ],
    optionsVi: [
      "Madonna kiểm soát phân phối nhạc ra sao?",
      "Bài hát nổi tiếng nhất của Madonna?",
      "Madonna xử lý đánh cắp nhạc ra sao?",
      "Vì sao Madonna cho nhạc miễn phí?",
    ],
    correctIndex: 2,
    explanationEn: "The passage states: Madonna has continued to work hard for her success, redefining herself and her music with every album.",
    explanationVi: "Bài nêu: Madonna has continued to work hard for her success, redefining herself and her music with every album.",
  },
  "reading-challenge-3-p17": {
    questionEn: "What is the main focus of this reading?",
    questionVi: "Trọng tâm của bài đọc là gì?",
    optionsEn: [
      "Types of human memory",
      "Functions of brain chemicals",
      "Tricks for remembering things",
      "How to stay active",
    ],
    optionsVi: [
      "Các loại trí nhớ con người",
      "Chức năng hóa chất trong não",
      "Mẹo ghi nhớ",
      "Cách giữ năng động",
    ],
    correctIndex: 0,
    explanationEn: "The passage states: But did you know that we have differe nt kinds of memory?",
    explanationVi: "Bài nêu: But did you know that we have differe nt kinds of memory?",
  },
  "reading-challenge-3-p18": {
    questionEn: "What is the reading mainly about?",
    questionVi: "Bài chủ yếu nói về gì?",
    optionsEn: [
      "The World Cup tournament",
      "Thieves",
      "The World Cup trophy",
      "World Cup stars",
    ],
    optionsVi: [
      "Giải World Cup",
      "Kẻ trộm",
      "Cúp World Cup",
      "Ngôi sao World Cup",
    ],
    correctIndex: 2,
    explanationEn: "The passage states: Every four years, teams from all over the globe compete to take home the FIFA World Cup Trophy, yet nobody ever does.",
    explanationVi: "Bài nêu: Every four years, teams from all over the globe compete to take home the FIFA World Cup Trophy, yet nobody ever does.",
  },
  "reading-challenge-3-p19": {
    questionEn: "What is the main purpose of the reading?",
    questionVi: "Mục đích chính của bài là gì?",
    optionsEn: [
      "To contrast phishers and hackers",
      "To explain what phishing is",
      "To outline three ways to recognize phishing scams",
      "To report a surprising phishing scam",
    ],
    optionsVi: [
      "So sánh phisher và hacker",
      "Giải thích phishing là gì",
      "Ba cách nhận biết lừa đảo phishing",
      "Báo một vụ phishing bất ngờ",
    ],
    correctIndex: 1,
    explanationEn: "The passage states: Recently, police tracked down members of an organized phishing group in Eastern Europe, who had stolen hundreds of thousands of dollars from people online.",
    explanationVi: "Bài nêu: Recently, police tracked down members of an organized phishing group in Eastern Europe, who had stolen hundreds of thousands of dollars from people online.",
  },
  "reading-challenge-3-p20": {
    questionEn: "What is the main idea of this reading?",
    questionVi: "Ý chính của bài đọc là gì?",
    optionsEn: [
      "Castles usually have ghosts.",
      "Chillingham Castle has a long history.",
      "Many ghosts live in England.",
      "Chillingham Castle is an interesting place.",
    ],
    optionsVi: [
      "Lâu đài thường có ma",
      "Chillingham Castle có lịch sử lâu",
      "Nhiều ma ở Anh",
      "Chillingham Castle là nơi thú vị",
    ],
    correctIndex: 3,
    explanationEn: "The passage states: If you were in Chillingham Castle in Northumber land, England, it may have been!",
    explanationVi: "Bài nêu: If you were in Chillingham Castle in Northumber land, England, it may have been!",
  },
};
