export const CURATED_EXERCISE_PROMPT_VI_46_60: Readonly<Record<string, string>> = {
  "ex-46-1-2": "Ghép: Chúng ta đến ga → ?",
  "ex-46-1-3": "Ghép: Chương trình hài sắp chiếu → ?",
  "ex-46-1-4": "Ghép: Xe buýt đã đến → ?",
  "ex-46-1-5": "Ghép: Tôi đang cố làm việc → ?",
  "ex-46-1-6": "Ghép: Tôi không nghe được tin tức → ?",
  "ex-46-1-7": "Ghép: Hôm nay trời mưa → ?",
  "ex-46-1-8": "Ghép: Tôi không muốn nhận việc đó → ?",
  "ex-46-2-1": "Trời tối quá. Bật ___ đèn lên.",
  "ex-46-2-2": "Máy bay cất cánh ___ lúc 6 giờ 25.",
  "ex-46-2-3": "Đến bãi biển, anh ấy mặc ___ quần bơi.",
  "ex-46-2-4": "Các em cởi ___ đồng phục khi về nhà.",
  "ex-46-2-5": "Đến giờ tắt ___ TV và đi ngủ.",
  "ex-46-2-7": "Học sinh tiếp tục ___ làm việc đến khuya.",
  "ex-46-3-2": "Điều gì đang xảy ra? (giày)",
  "ex-46-3-3": "Điều gì đang xảy ra? (máy bay)",
  "ex-46-3-4": "Điều gì đang xảy ra? (lò nướng)",
  "ex-46-4-2": "Tôi cởi mũ và áo khoác. → Tôi ___ mũ và áo khoác.",
  "ex-46-4-3": "Cô ấy tiếp tục viết tiểu thuyết. → Cô ấy ___ viết tiểu thuyết.",
  "ex-46-4-4": "Michael bỏ đi không nói tạm biệt. → Michael ___ không nói tạm biệt.",
  "ex-46-4-5": "Tôi từ chối lời mời cưới Maya. → Tôi ___ lời mời.",
  "ex-47-1-2": "Cô ấy ___ quần áo mỗi thứ Bảy.",
  "ex-47-1-3": "Anh ấy ___ nhà mỗi cuối tuần.",
  "ex-47-1-4": "Anh ấy ___ TV mỗi tối.",
  "ex-47-1-5": "Cô ấy ___ đi dạo mỗi Chủ nhật.",
  "ex-47-2-2": "Bạn đi dạo bao lâu một lần?",
  "ex-47-2-3": "Bạn đi làm bằng gì?",
  "ex-47-2-4": "Bạn ăn tối lúc nào?",
  "ex-47-3-1": "Tôi thường thức dậy lúc ___.",
  "ex-47-3-2": "Tôi vào phòng tắm và ___.",
  "ex-47-3-3": "Tôi thường ăn trà và bánh mì nướng cho ___.",
  "ex-47-3-4": "Tôi đi làm bằng ___.",
  "ex-47-3-6": "Tôi thường về nhà khoảng ___.",
  "ex-47-3-7": "Tôi thường nấu bữa tối lúc ___ giờ.",
  "ex-47-3-8": "Buổi tối tôi thường xem TV hoặc đi ___.",
  "ex-47-3-10": "Tôi thường đi ___ lúc 11 giờ.",
  "ex-47-w1": "Anh ấy nghe ___ mỗi sáng.",
  "ex-48-1-2": "Cô ấy ___ tôi rằng cô ấy sẽ đi.",
  "ex-48-1-3": "Anh ấy ___ rằng anh ấy sẽ đi.",
  "ex-48-1-4": "Bạn có thể ___ tôi mấy giờ không?",
  "ex-48-1-5": "Cô ấy ___ rằng cô ấy sẽ đi.",
  "ex-48-1-6": "Anh ấy ___ tôi rằng anh ấy sẽ đi.",
  "ex-48-2-2": "Làm sao ___ 'tree' bằng tiếng Đức?",
  "ex-48-2-3": "Xin lỗi, bạn có thể ___ tôi mấy giờ không?",
  "ex-48-2-4": "Tôi chỉ muốn ___ tạm biệt (với bạn).",
  "ex-48-2-5": "Bạn có thể ___ tôi khi nào thi không?",
  "ex-48-3": "Ghép động từ bên trái với cụm từ bên phải",
  "ex-48-4-2": "Cho chúng tôi ___, làm ơn.",
  "ex-48-4-3": "___ New Year!",
  "ex-48-4-4": "___ tôi nghe một câu chuyện trước khi ngủ. Làm ơn!",
  "ex-49-1-2": "Mọi người ___ tại bữa tiệc tối qua.",
  "ex-49-1-3": "Anh ấy ___ rất nhanh.",
  "ex-49-1-4": "Cô ấy ___ ở biển mỗi ngày.",
  "ex-49-1-5": "Chúng tôi đi ___ trên núi.",
  "ex-49-1-6": "Con mèo ___ lên tường.",
  "ex-49-1-7": "Anh ấy ___ rồi bơi về bờ.",
  "ex-49-1-8": "Tôi ___ đi làm mỗi ngày.",
  "ex-49-2-2": "Anh ấy ___ đi làm mỗi ngày.",
  "ex-49-2-3": "Cô ấy ___ xe buýt đi học.",
  "ex-49-2-4": "Tôi ___ xe đạp đến công viên.",
  "ex-49-3-2": "Hôm qua Maria ___ bà đến thành phố.",
  "ex-49-3-3": "Hôm qua Charlie ___ Madrid.",
  "ex-49-3-4": "Hôm qua tôi ___ taxi về nhà từ ga.",
  "ex-49-3-5": "Hôm qua Bella ___ khi đạp xe.",
  "ex-49-3-6": "Hôm qua Adrian ___ xe buýt 7 giờ 30 đến trường.",
  "ex-49-3-8": "Hôm qua Madeline ___ rất giỏi.",
  "ex-50-1-2": "Annabelle đồng ý cưới Aarav ___ họ quyết định kinh doanh chung.",
  "ex-50-1-3": "Annabelle đồng ý cưới Aarav ___ cô ấy yêu anh ấy.",
  "ex-50-1-4": "Annabelle đồng ý cưới Aarav ___ anh ấy chuyển London.",
  "ex-50-1-5": "Annabelle sẽ cưới Aarav ___ anh ấy chuyển London.",
  "ex-50-1-6": "Annabelle đồng ý cưới Aarav ___ anh ấy chuyển London.",
  "ex-50-1-7": "Annabelle sẽ cưới Aarav ___ cô ấy sẽ không cưới ai khác.",
  "ex-50-1-8": "Annabelle đồng ý cưới Aarav ___ anh ấy chuyển London.",
  "ex-50-2-2": "Tôi thích nghe nhạc và cũng thích đọc ___.",
  "ex-50-2-3": "Chị tôi chơi piano giỏi hơn ___ tôi.",
  "ex-50-2-4": "Anh trai tôi bơi ___ cá.",
  "ex-50-2-5": "Tôi ___ chơi tennis vào mùa hè.",
  "ex-50-3-1": "Tôi học tiếng Anh ___ tôi thích nó.",
  "ex-50-3-2": "Tôi sẽ học thêm tiếng Anh ___ tôi làm hết bài tập trong sách.",
  "ex-50-3-3": "Tôi bắt đầu học tiếng Anh ___ tôi 10 tuổi.",
  "ex-50-3-4": "Tôi nói được chút tiếng Anh, ___ đi nghỉ ở Anh cũng ổn.",
  "ex-51-1-2": "100 năm = một ___.",
  "ex-51-1-3": "2 tuần = một ___.",
  "ex-51-1-4": "60 phút = một ___.",
  "ex-51-1-5": "7 ngày = một ___.",
  "ex-51-2-2": "Tháng sau tháng Bảy là ___.",
  "ex-51-2-3": "Tháng trước tháng Hai là ___.",
  "ex-51-2-4": "Tháng sau tháng Tám là ___.",
  "ex-51-2-5": "Tháng trước tháng Năm là ___.",
  "ex-51-2-6": "Ngày sau thứ Hai là ___.",
  "ex-51-2-7": "Ngày trước Chủ nhật là ___.",
  "ex-51-2-8": "Ngày sau thứ Tư là ___.",
  "ex-51-2-9": "Tháng trước tháng Ba là ___.",
  "ex-51-2-10": "Tháng trước tháng Mười hai là ___.",
  "ex-51-3-1": "Sinh nhật Valentina vào ___.",
  "ex-51-3-2": "Cô ấy muốn tổ chức tiệc vào ___.",
  "ex-51-3-3": "___ là tháng tốt để sinh nhật vì thời tiết.",
  "ex-51-4-1": "Hai tuần có bao nhiêu ngày? ___",
  "ex-51-4-3": "Năm giờ có bao nhiêu phút? ___",
  "ex-51-4-4": "Tháng nào đến sau tháng Sáu? ___",
  "ex-52-1-2": "Tôi sống ở đây ___ mười năm.",
  "ex-52-1-3": "Cửa hàng mở ___ 9 ___ 5.",
  "ex-52-1-4": "Chúng tôi đi Tây Ban Nha ___ hai tuần.",
  "ex-52-1-5": "___ thời điểm này tôi rất bận.",
  "ex-52-1-6": "Tôi không gặp cô ấy ___ ages.",
  "ex-52-2-2": "Thế kỷ 22 thuộc ___.",
  "ex-52-2-3": "Thế kỷ 18 thuộc ___.",
  "ex-52-2-4": "Thế kỷ 21 là ___.",
  "ex-52-3-2": "Tôi ___ đi học bằng xe buýt.",
  "ex-52-3-3": "Tôi ___ xem TV.",
  "ex-52-3-4": "Tôi ___ uống sữa.",
  "ex-52-3-5": "Tôi ___ đội mũ.",
  "ex-52-3-7": "Tôi ___ đi ngủ lúc 10 giờ.",
  "ex-52-4-2": "Lần cuối gặp cô ấy? Có lẽ một ___ trước.",
  "ex-52-4-3": "Xe buýt sẽ đến sau vài ___.",
  "ex-52-5-1": "John chơi tennis hai lần một ___.",
  "ex-52-5-2": "Anh ấy họp công việc ở Đức một lần một ___.",
  "ex-53-1-2": "Lại ___ đây. Tôi muốn cho bạn xem cái gì đó.",
  "ex-53-1-3": "Nhìn sang ___. Bạn thấy sông không?",
  "ex-53-1-4": "Người ta nói tiếng Anh ___.",
  "ex-53-1-5": "Tôi sống Rome một năm nhưng giờ tôi ___ London.",
  "ex-53-2-2": "Cô ấy làm việc ___ bệnh viện.",
  "ex-53-2-3": "Có một bức tranh ___ tường.",
  "ex-53-2-4": "Tôi gặp bạn ___ ga.",
  "ex-53-2-5": "Cô ấy sống ___ tầng ba.",
  "ex-53-2-6": "Có con nhện ___ bồn tắm và một con ___ phòng tắm.",
  "ex-53-3": "Ghép vị trí bên trái với nơi chốn bên phải",
  "ex-53-4-2": "Anh ấy đi ___ khỏi phòng.",
  "ex-53-4-3": "Cô ấy đi ___ vài ngày.",
  "ex-53-4-4": "Họ đi ___ nghỉ.",
  "ex-53-5-2": "Đáp án ở ___ cuốn sách này.",
  "ex-53-5-4": "Lúc này tôi cầm bút ở tay ___.",
  "ex-53-5-5": "Unit 3 ở ___ cuốn sách.",
  "ex-53-5-6": "Unit 36 ở ___ cuốn sách.",
  "ex-54-1-2": "Anh ấy hát ___.",
  "ex-54-1-3": "Cô ấy nói ___.",
  "ex-54-1-4": "Anh ấy lái xe rất ___.",
  "ex-54-1-5": "Làm ơn nói ___.",
  "ex-54-1-6": "Cô ấy hát rất ___.",
  "ex-54-2-2": "Chó tôi già và rất ___.",
  "ex-54-2-3": "Anh trai tôi nói tiếng Đức ___.",
  "ex-54-2-4": "Từ nào KHÔNG phải trạng từ?",
  "ex-54-2-5": "Tôi thích làm mọi việc theo cách ___.",
  "ex-54-3-2": "Tôi thường ăn quá ___.",
  "ex-54-3-3": "Mẹ tôi luôn cư xử theo cách thân thiện ___.",
  "ex-54-3-4": "Chó tôi già và rất ___.",
  "ex-54-3-5": "Giọng tôi ___.",
  "ex-54-3-6": "Tôi thích hát ___.",
  "ex-55-1-2": "Từ nào không đếm được?",
  "ex-55-1-3": "Từ nào không đếm được?",
  "ex-55-1-4": "Từ nào không đếm được?",
  "ex-55-1-5": "Từ nào không đếm được?",
  "ex-55-1-6": "Từ nào không đếm được?",
  "ex-55-2": "Ghép cụm đo lường bên trái với danh từ bên phải",
  "ex-55-3-2": "Tôi lấy ___ về đất nước bạn ở đâu?",
  "ex-55-3-3": "Để tôi cho bạn một chút ___.",
  "ex-55-3-5": "Cho tôi một ít ___, làm ơn.",
  "ex-55-3-6": "Chúng ta cần mua ___ mới.",
  "ex-55-3-8": "Tôi phải tìm ___ mới sớm.",
  "ex-55-4-2": "Phía đông có thời tiết tốt hơn phía tây.",
  "ex-56-1-2": "Đồ ăn rất tệ / khủng khiếp / ___.",
  "ex-56-1-4": "Khách sạn xuất sắc / tuyệt / ___.",
  "ex-56-2-2": "Ôi, ___ quá!",
  "ex-56-2-3": "Ý tưởng hay! / Vâng, ___!",
  "ex-56-2-4": "Có nhà hàng Ritz. Đó là nhà hàng ___.",
  "ex-56-3": "Ghép tính từ bên trái với danh từ đi kèm bên phải",
  "ex-56-4-1": "Across: rất hay — b _ _ _ _ _ _ _ t",
  "ex-56-4-2": "Down: rất tệ — d _ _ _ _ _ _ _ l",
  "ex-56-4-3": "Across: tuyệt vời — m _ _ _ _ _ _ _ s",
  "ex-56-4-4": "Down: khó chịu — n _ _ _ _",
  "ex-56-4-5": "Across: ổn/đẹp — f _ _ _",
  "ex-56-5-1": "một ý tưởng / nhà khoa học ___",
  "ex-56-5-2": "một tin xấu / mùi ___",
  "ex-56-5-3": "thời tiết / đồ ăn ___",
  "ex-57-1-2": "Xe đạp này thuộc ___ khách sạn.",
  "ex-57-1-3": "Các em cảm ơn dì ___ số tiền.",
  "ex-57-1-4": "Molly đang nghe ___ nhạc trên điện thoại.",
  "ex-57-1-5": "Anh ấy xin lỗi ___ lỗi của mình.",
  "ex-57-1-6": "Để tôi trả tiền ___ vé của chúng ta.",
  "ex-57-1-7": "Javier đang nghĩ ___ kỳ nghỉ.",
  "ex-57-2-2": "Tôi mong ___ tiệc sinh nhật.",
  "ex-57-2-3": "Cảm ơn ___ họ.",
  "ex-57-2-5": "Cô ấy la ___ tôi.",
  "ex-57-2-6": "Tôi đang tìm ___ việc mới.",
  "ex-57-3-2": "Hiroshi không quen ăn ___ Anh.",
  "ex-57-3-4": "Anh ấy quen ___ giao thông.",
  "ex-57-4-1": "Tôi giỏi ___ ngoại ngữ và dở thể dục.",
  "ex-57-4-3": "Tôi tự hào ___ gia đình.",
  "ex-57-4-4": "Tôi sợ ___ nha sĩ.",
  "ex-57-4-6": "Tôi mong ___ kỳ nghỉ.",
  "ex-57-4-7": "Tôi là thành viên ___ câu lạc bộ tennis.",
  "ex-58-1-2": "Làm ơn ___ bài luận. (viết lại)",
  "ex-58-1-3": "Đây là từ ___ — không dùng trong văn viết trang trọng.",
  "ex-58-1-4": "Cô ấy rất ___ sau tin đó.",
  "ex-58-1-5": "Hôm nay mọi thứ trong shop ___ .",
  "ex-58-1-6": "___ khi đi một mình ban đêm ở đây.",
  "ex-58-2-2": "Tôi không còn gặp ___-boyfriend nữa.",
  "ex-58-2-3": "Bài này chưa tốt. Làm ơn ___ nó.",
  "ex-58-2-4": "___ đọc chữ viết tay của anh ấy.",
  "ex-58-2-5": "Trẻ ___-school học qua chơi.",
  "ex-58-3-2": "Chiếc ghế này rất ___.",
  "ex-58-3-3": "Anh ấy ___ khi không nói cảm ơn.",
  "ex-58-3-4": "Mùi trong phòng ___.",
  "ex-58-3-5": "Anh ấy thấy bức tranh ___.",
  "ex-58-4-1": "Phòng con gái tôi luôn rất ___.",
  "ex-58-4-2": "Tuần sau chúng tôi sẽ ___sơn lại phòng.",
  "ex-59-1-2": "Người dạy trượt tuyết là ski ___.",
  "ex-59-1-3": "Tom là ___ giỏi.",
  "ex-59-1-4": "Họ sống ___ mãi mãi.",
  "ex-59-1-5": "Dùng ___ cho phép tính khó.",
  "ex-59-1-6": "Từ điển này rất ___.",
  "ex-59-2-2": "một ___ nhanh / xe / người bơi",
  "ex-59-2-3": "một bãi biển / thời tiết / nụ cười ___",
  "ex-59-2-4": "một bãi biển ___",
  "ex-59-2-5": "thời tiết / nụ cười ___",
  "ex-59-2-6": "một ___ chăm chỉ",
  "ex-59-3-2": "Cô ấy hát ___.",
  "ex-59-3-3": "Cảm ơn vì bạn rất ___.",
  "ex-59-3-4": "Cảm ơn vì ___ của bạn.",
  "ex-59-3-5": "Bạn ___ khi để cửa mở.",
  "ex-59-3-6": "Hôm qua trời rất ___.",
  "ex-59-3-7": "Cô ấy thi ___ .",
  "ex-59-3-8": "Bố tôi là ___.",
  "ex-59-4": "Ghép từ bên trái với định nghĩa bên phải",
  "ex-60-1-2": "Cẩn thận kẻo bạn ___ chìa khóa.",
  "ex-60-1-3": "Hôm qua tôi ___ mệt.",
  "ex-60-1-4": "Tuần trước chúng tôi mua ___ mới.",
  "ex-60-1-5": "Cô ấy ___ khỏi xe đạp.",
  "ex-60-1-6": "Việc này ___ khó.",
  "ex-60-1-7": "Quần này ___ quá.",
  "ex-60-1-8": "Tôi không ___ giỏi lắm.",
  "ex-60-2-2": "Nắp chai ___ . (không chặt)",
  "ex-60-2-3": "Đúng ___ rồi.",
  "ex-60-2-4": "Làm ơn ___ đi.",
  "ex-60-3-2": "Tôi có thể ___ máy ảnh của bạn không?",
  "ex-60-3-3": "Bạn có thể ___ tôi £1 không?",
  "ex-60-3-4": "Chúc ___ .",
  "ex-60-3-5": "Họ chờ ___ xe buýt.",
  "ex-60-3-6": "Làm ơn ___ đi.",
  "ex-60-4-1": "Tôi đang ___ anh trai lúc 5 giờ 30.",
  "ex-60-4-2": "Tôi hy vọng đi nghỉ Tây Ban Nha. (= Tôi thực sự ___ đi)",
  "ex-60-4-3": "Đôi khi tôi ___ sách và DVD.",
};
