import { assertExerciseCount, cloze, match, mcq } from "./eviu-elementary-curated-helpers";
import type { VocabularyExercise } from "@/lib/vocabulary/vocabulary-unit-types";

const UNIT_31: VocabularyExercise[] = [
  cloze("ex-31-1-2", "31.1 · Hoàn thành câu", "A ___ has a very long neck.", "giraffe", ["Giraffe"]),
  cloze("ex-31-1-3", "31.1 · Hoàn thành câu", "___ and hens are birds.", "Parrots", ["parrots"]),
  cloze("ex-31-1-4", "31.1 · Hoàn thành câu", "Tigers and ___ are large cats.", "lions", ["Lions"]),
  cloze("ex-31-1-5", "31.1 · Hoàn thành câu", "You can ride a horse and an ___.", "elephant", ["Elephant"]),
  cloze("ex-31-1-6", "31.1 · Hoàn thành câu", "Fish swim and birds ___.", "fly", ["Fly"]),
  cloze("ex-31-1-7", "31.1 · Hoàn thành câu", "___ are farm birds.", "Chickens", ["Chickens", "hens", "Hens"]),
  cloze("ex-31-1-8", "31.1 · Hoàn thành câu", "___ are very good at hopping and jumping.", "Rabbits", ["rabbits"]),
  cloze("ex-31-1-9", "31.1 · Hoàn thành câu", "Don't forget to ___ the cat and give it some water.", "feed", ["Feed"]),
  cloze("ex-31-1-10", "31.1 · Hoàn thành câu", "I ___ my dog for a walk every day before school.", "take", ["Take"]),
  match("ex-31-2", "31.2 · Ghép con vật — thịt — con non", [
    { left: "sheep", right: "lamb (meat and baby)" },
    { left: "cow", right: "beef / calf" },
    { left: "hen", right: "chicken / chick" },
    { left: "pig", right: "pork / piglet" },
  ]),
  cloze("ex-31-4-1", "31.4 · Ô chữ", "Down 1: colourful bird that can talk — ___", "parrot", ["Parrot"]),
  cloze("ex-31-4-2", "31.4 · Ô chữ", "Down 2: animal that climbs trees — ___", "monkey", ["Monkey"]),
  cloze("ex-31-4-3", "31.4 · Ô chữ", "Across 3: pet that catches mice — ___", "cats", ["Cats"]),
  cloze("ex-31-4-4", "31.4 · Ô chữ", "Down 4: farm animal with wool — ___", "sheep", ["Sheep"]),
  cloze("ex-31-4-5", "31.4 · Ô chữ", "Down 5: big cat with stripes — ___", "tiger", ["Tiger"]),
  cloze("ex-31-4-6", "31.4 · Ô chữ", "Across 6: king of the jungle — ___", "lion", ["Lion"]),
  cloze("ex-31-4-7", "31.4 · Ô chữ", "Across 7: animal you can ride — ___", "horse", ["Horse"]),
  cloze("ex-31-4-8", "31.4 · Ô chữ", "Across 8: very big animal with a trunk — ___", "elephant", ["Elephant"]),
  cloze("ex-31-4-9", "31.4 · Ô chữ", "Across 9: farm bird that lays eggs — ___", "hen", ["Hen"]),
];

const UNIT_32: VocabularyExercise[] = [
  mcq(
    "ex-32-1-2",
    "32.1 · Ghép từ",
    "Match: direct → ?",
    "d",
    [
      { key: "a", label: "a place to eat on a train" },
      { key: "b", label: "bags and suitcases" },
      { key: "c", label: "it says when trains depart and arrive" },
      { key: "d", label: "you do not have to change plane / train / bus" },
    ],
  ),
  mcq(
    "ex-32-1-3",
    "32.1 · Ghép từ",
    "Match: restaurant car → ?",
    "a",
    [
      { key: "a", label: "a place to eat on a train" },
      { key: "b", label: "bags and suitcases" },
      { key: "c", label: "it says when trains depart and arrive" },
      { key: "d", label: "planes do this at airports" },
    ],
  ),
  mcq(
    "ex-32-1-4",
    "32.1 · Ghép từ",
    "Match: ship → ?",
    "a",
    [
      { key: "a", label: "it travels on water, e.g. the Titanic" },
      { key: "b", label: "bags and suitcases" },
      { key: "c", label: "it says when trains depart and arrive" },
      { key: "d", label: "a place to eat on a train" },
    ],
  ),
  mcq(
    "ex-32-1-5",
    "32.1 · Ghép từ",
    "Match: timetable → ?",
    "c",
    [
      { key: "a", label: "a place to eat on a train" },
      { key: "b", label: "bags and suitcases" },
      { key: "c", label: "it says when trains depart and arrive" },
      { key: "d", label: "you do not have to change plane / train / bus" },
    ],
  ),
  mcq(
    "ex-32-1-6",
    "32.1 · Ghép từ",
    "Match: platform → ?",
    "a",
    [
      { key: "a", label: "where you stand when waiting for a train" },
      { key: "b", label: "bags and suitcases" },
      { key: "c", label: "it says when trains depart and arrive" },
      { key: "d", label: "planes do this at airports" },
    ],
  ),
  mcq(
    "ex-32-1-7",
    "32.1 · Ghép từ",
    "Match: luggage → ?",
    "b",
    [
      { key: "a", label: "a place to eat on a train" },
      { key: "b", label: "bags and suitcases" },
      { key: "c", label: "it says when trains depart and arrive" },
      { key: "d", label: "where you stand when waiting for a train" },
    ],
  ),
  mcq(
    "ex-32-2-3",
    "32.2 · Đúng hay sai?",
    "Planes land at the beginning of a journey.",
    "b",
    [
      { key: "a", label: "Đúng" },
      { key: "b", label: "Sai — planes take off at the start and land at the end" },
      { key: "c", label: "Đúng — land means depart" },
      { key: "d", label: "Sai — only trains land" },
    ],
  ),
  mcq(
    "ex-32-2-4",
    "32.2 · Đúng hay sai?",
    "You need a boarding card to get off a plane.",
    "b",
    [
      { key: "a", label: "Đúng" },
      { key: "b", label: "Sai — you need it to get on a plane" },
      { key: "c", label: "Đúng — for customs" },
      { key: "d", label: "Sai — you need a passport to get off" },
    ],
  ),
  mcq(
    "ex-32-2-5",
    "32.2 · Đúng hay sai?",
    "Hiring a car is the same as buying a car.",
    "b",
    [
      { key: "a", label: "Đúng" },
      { key: "b", label: "Sai — hiring means renting for a short time" },
      { key: "c", label: "Đúng — both mean owning a car" },
      { key: "d", label: "Sai — hiring is only for taxis" },
    ],
  ),
  mcq(
    "ex-32-2-6",
    "32.2 · Đúng hay sai?",
    "If you give someone a lift they travel in your car.",
    "a",
    [
      { key: "a", label: "Đúng" },
      { key: "b", label: "Sai — a lift is an elevator" },
      { key: "c", label: "Sai — they travel by bus" },
      { key: "d", label: "Đúng — but only on a train" },
    ],
  ),
  cloze("ex-32-4-1", "32.4 · Ô chữ", "Down 1: shows train times — ___", "timetable", ["Timetable"]),
  cloze("ex-32-4-2", "32.4 · Ô chữ", "Down 2: car you pay to take you somewhere — ___", "taxi", ["Taxi"]),
  cloze("ex-32-4-3", "32.4 · Ô chữ", "Across 3: helps you find your way — ___", "map", ["Map"]),
  cloze("ex-32-4-4", "32.4 · Ô chữ", "Down 4: where you wait for a train — ___", "platform", ["Platform"]),
  cloze("ex-32-4-5", "32.4 · Ô chữ", "Down 5: travels on rails — ___", "train", ["Train"]),
  cloze("ex-32-4-6", "32.4 · Ô chữ", "Across 6: flies but is not a plane — ___", "helicopter", ["Helicopter"]),
  cloze("ex-32-4-7", "32.4 · Ô chữ", "Across 7: public road vehicle — ___", "bus", ["Bus"]),
  cloze("ex-32-4-8", "32.4 · Ô chữ", "Across 8: fuel for cars — ___", "petrol", ["Petrol"]),
  cloze("ex-32-4-9", "32.4 · Ô chữ", "Down 3: two-wheeled motor vehicle — ___", "motorcycle", ["Motorcycle"]),
];

const UNIT_33: VocabularyExercise[] = [
  mcq("ex-33-1-2", "33.1 · Lễ hội", "Picture 2 shows which festival?", "a", [
    { key: "a", label: "Christmas" },
    { key: "b", label: "Easter" },
    { key: "c", label: "Bonfire Night" },
    { key: "d", label: "Valentine's Day" },
  ]),
  mcq("ex-33-1-3", "33.1 · Lễ hội", "Picture 3 shows which festival?", "c", [
    { key: "a", label: "Christmas" },
    { key: "b", label: "Easter" },
    { key: "c", label: "Bonfire Night" },
    { key: "d", label: "New Year's Eve" },
  ]),
  mcq("ex-33-1-4", "33.1 · Lễ hội", "Picture 4 shows which festival?", "b", [
    { key: "a", label: "Christmas" },
    { key: "b", label: "Easter" },
    { key: "c", label: "Bonfire Night" },
    { key: "d", label: "Halloween" },
  ]),
  mcq("ex-33-1-5", "33.1 · Lễ hội", "Picture 5 shows which festival?", "d", [
    { key: "a", label: "Christmas" },
    { key: "b", label: "Easter" },
    { key: "c", label: "Bonfire Night" },
    { key: "d", label: "Valentine's Day" },
  ]),
  mcq("ex-33-1-6", "33.1 · Lễ hội", "Picture 6 shows which festival?", "a", [
    { key: "a", label: "New Year's Eve / Hogmanay" },
    { key: "b", label: "Easter" },
    { key: "c", label: "Bonfire Night" },
    { key: "d", label: "Valentine's Day" },
  ]),
  cloze("ex-33-3-2", "33.3 · Ẩm thực Anh", "Where does chicken tikka masala come from?", "India", ["India"]),
  cloze("ex-33-3-3", "33.3 · Ẩm thực Anh", "Chicken tikka masala is a kind of ___.", "curry", ["Curry"]),
  mcq("ex-33-3-4", "33.3 · Ẩm thực Anh", "Do British people eat Yorkshire pudding after their main course?", "b", [
    { key: "a", label: "Yes — as dessert" },
    { key: "b", label: "No — they eat it with roast beef" },
    { key: "c", label: "Yes — before soup" },
    { key: "d", label: "No — they never eat it" },
  ]),
  cloze("ex-33-3-5", "33.3 · Ẩm thực Anh", "You make roast beef and roast potatoes in the ___.", "oven", ["Oven"]),
  mcq("ex-33-4-1", "33.4 · Trường học", "Lily is seven. Her parents pay for school. She goes to a ___", "a", [
    { key: "a", label: "private primary school" },
    { key: "b", label: "state secondary school" },
    { key: "c", label: "nursery school" },
    { key: "d", label: "university" },
  ]),
  mcq("ex-33-4-2", "33.4 · Trường học", "Gabriel is 14. His school is free. He goes to a ___", "b", [
    { key: "a", label: "private primary school" },
    { key: "b", label: "state secondary school" },
    { key: "c", label: "nursery school" },
    { key: "d", label: "private secondary school" },
  ]),
  mcq("ex-33-4-3", "33.4 · Trường học", "James and Ellie are three. They go to a ___", "c", [
    { key: "a", label: "primary school" },
    { key: "b", label: "secondary school" },
    { key: "c", label: "nursery school" },
    { key: "d", label: "university" },
  ]),
  mcq("ex-33-4-4", "33.4 · Trường học", "Mehmet is ten. His school is free. He goes to a ___", "d", [
    { key: "a", label: "private secondary school" },
    { key: "b", label: "nursery school" },
    { key: "c", label: "state secondary school" },
    { key: "d", label: "state primary school" },
  ]),
  mcq("ex-33-4-5", "33.4 · Trường học", "Nick is 16. His parents pay. He goes to a ___", "a", [
    { key: "a", label: "private secondary school" },
    { key: "b", label: "state primary school" },
    { key: "c", label: "nursery school" },
    { key: "d", label: "state secondary school" },
  ]),
  cloze("ex-33-5-1", "33.5 · Văn hóa Anh", "Who was Prime Minister of the UK in 2016? ___", "Theresa May", ["Theresa May"]),
  cloze("ex-33-5-2", "33.5 · Văn hóa Anh", "Where do MPs meet? The ___", "Houses of Parliament", ["Houses of Parliament"]),
  cloze("ex-33-5-3", "33.5 · Văn hóa Anh", "Who was the British monarch in 2016? Queen ___ II", "Elizabeth", ["Elizabeth"]),
];

const UNIT_34: VocabularyExercise[] = [
  cloze("ex-34-1-2", "34.1 · Tội phạm", "What do we call someone who kills someone? A ___", "murderer", ["Murderer"]),
  cloze("ex-34-1-3", "34.1 · Tội phạm", "What do we call someone who steals from shops? A ___", "shoplifter", ["Shoplifter", "robber", "Robber"]),
  cloze("ex-34-1-4", "34.1 · Tội phạm", "What do we call someone who robs people's houses? A ___", "burglar", ["Burglar"]),
  cloze("ex-34-1-5", "34.1 · Tội phạm", "What do we call someone who attacks people in the street for money? A ___", "mugger", ["Mugger"]),
  cloze("ex-34-1-6", "34.1 · Tội phạm", "What do we call someone who sells illegal drugs? A ___", "drug dealer", ["Drug dealer"]),
  cloze("ex-34-2-2", "34.2 · Hoàn thành câu", "The police officer ___ her for shoplifting.", "arrested", ["Arrested"]),
  cloze("ex-34-2-3", "34.2 · Hoàn thành câu", "Some ___ destroyed all the flowers in the park.", "vandals", ["Vandals"]),
  cloze("ex-34-2-4", "34.2 · Hoàn thành câu", "He had to pay a ___ of £50 for parking in the wrong place.", "fine", ["Fine"]),
  cloze("ex-34-2-5", "34.2 · Hoàn thành câu", "There are a lot of ___ in this part of the city.", "burglaries", ["Burglaries", "burglars", "Burglars"]),
  cloze("ex-34-2-6", "34.2 · Hoàn thành câu", "The police made a mistake; she was ___. She did not steal the money.", "innocent", ["Innocent"]),
  cloze("ex-34-2-7", "34.2 · Hoàn thành câu", "A group of ___ have attacked the airport.", "terrorists", ["Terrorists"]),
  cloze("ex-34-2-8", "34.2 · Hoàn thành câu", "He murdered his wife. He was in ___ for 20 years.", "prison", ["Prison"]),
  mcq("ex-34-3-2", "34.3 · Đúng hay sai?", "Vandals take people's money.", "b", [
    { key: "a", label: "Đúng" },
    { key: "b", label: "Sai — vandals destroy things" },
    { key: "c", label: "Đúng — vandals rob banks" },
    { key: "d", label: "Sai — vandals are police officers" },
  ]),
  mcq("ex-34-3-4", "34.3 · Đúng hay sai?", "A car thief is someone who drives very badly.", "b", [
    { key: "a", label: "Đúng" },
    { key: "b", label: "Sai — a car thief steals cars" },
    { key: "c", label: "Đúng — they give parking tickets" },
    { key: "d", label: "Sai — they repair cars" },
  ]),
  cloze("ex-34-4-2", "34.4 · Rob / steal", "Someone ___ my bike last night.", "stole", ["Stole"]),
  cloze("ex-34-4-3", "34.4 · Rob / steal", "My brother was ___ yesterday.", "robbed", ["Robbed"]),
  cloze("ex-34-4-4", "34.4 · Rob / steal", "My local bank has been ___.", "robbed", ["Robbed"]),
  cloze("ex-34-4-5", "34.4 · Rob / steal", "They have ___ all the money from the shop.", "stolen", ["Stolen"]),
];

const UNIT_35: VocabularyExercise[] = [
  cloze("ex-35-1-2", "35.1 · Truyền thông", "The news on channel 3 ___ at 9 o'clock every night.", "is", ["Is"]),
  cloze("ex-35-1-3", "35.1 · Truyền thông", "There was a ___ about traffic problems in cities on TV last night.", "documentary", ["Documentary"]),
  cloze("ex-35-1-4", "35.1 · Truyền thông", "I saw a ___ programme about birds in Antarctica.", "nature", ["Nature"]),
  cloze("ex-35-1-5", "35.1 · Truyền thông", "My sister reads a ___ magazine every week.", "teenage", ["Teenage"]),
  cloze("ex-35-1-6", "35.1 · Truyền thông", "With my mobile I can read the sports news ___.", "online", ["Online"]),
  cloze("ex-35-1-7", "35.1 · Truyền thông", "Is it OK if I ___ the channel?", "change", ["Change"]),
  cloze("ex-35-1-8", "35.1 · Truyền thông", "Did you see the ___ with the Prime Minister last night?", "interview", ["Interview"]),
  mcq("ex-35-2-2", "35.2 · Loại chương trình", "Film of elephants in Africa is a ___", "d", [
    { key: "a", label: "International news" },
    { key: "b", label: "Sports programme" },
    { key: "c", label: "Reality TV programme" },
    { key: "d", label: "Nature programme" },
  ]),
  mcq("ex-35-2-3", "35.2 · Loại chương trình", "Football cup final is a ___", "b", [
    { key: "a", label: "Talk show" },
    { key: "b", label: "Sports programme" },
    { key: "c", label: "Soap (opera)" },
    { key: "d", label: "Nature programme" },
  ]),
  mcq("ex-35-2-4", "35.2 · Loại chương trình", "Reports from all over the world is ___", "a", [
    { key: "a", label: "International news" },
    { key: "b", label: "Sports programme" },
    { key: "c", label: "Reality TV programme" },
    { key: "d", label: "Nature programme" },
  ]),
  mcq("ex-35-2-5", "35.2 · Loại chương trình", "Maria decides not to marry Philip is a ___", "d", [
    { key: "a", label: "International news" },
    { key: "b", label: "Sports programme" },
    { key: "c", label: "Reality TV programme" },
    { key: "d", label: "Soap (opera)" },
  ]),
  mcq("ex-35-2-6", "35.2 · Loại chương trình", "Ten people in a house who cannot leave is ___", "c", [
    { key: "a", label: "Talk show" },
    { key: "b", label: "Nature programme" },
    { key: "c", label: "Reality TV programme" },
    { key: "d", label: "International news" },
  ]),
  cloze("ex-35-3-2", "35.3 · Từ vựng", "A person who writes articles in newspapers is a ___.", "journalist", ["Journalist"]),
  cloze("ex-35-3-3", "35.3 · Từ vựng", "A newspaper you buy after about 5 pm is an ___", "evening paper", ["Evening paper", "evening newspaper", "Evening newspaper"]),
  cloze("ex-35-3-4", "35.3 · Từ vựng", "A programme made from lots of pictures is a ___.", "cartoon", ["Cartoon"]),
  cloze("ex-35-3-6", "35.3 · Từ vựng", "Something that tries to sell something on TV is an ___.", "advert", ["Advert", "advertisement", "Advertisement"]),
  cloze("ex-35-3-7", "35.3 · Từ vựng", "CNN or Sky Sports is a TV ___.", "channel", ["Channel"]),
];

const UNIT_36: VocabularyExercise[] = [
  cloze("ex-36-1-2", "36.1 · Vấn đề", "The computer has ___.", "crashed", ["Crashed"]),
  cloze("ex-36-1-3", "36.1 · Vấn đề", "The cup is ___.", "broken", ["Broken"]),
  cloze("ex-36-1-4", "36.1 · Vấn đề", "The coffee machine ___ working.", "isn't", ["Isn't", "is not", "Is not"]),
  cloze("ex-36-1-5", "36.1 · Vấn đề", "She has too much ___.", "work", ["Work"]),
  cloze("ex-36-1-6", "36.1 · Vấn đề", "He's cut his ___.", "hand", ["Hand", "finger", "Finger"]),
  cloze("ex-36-1-7", "36.1 · Vấn đề", "The room is ___.", "untidy", ["Untidy"]),
  cloze("ex-36-1-8", "36.1 · Vấn đề", "She is ___ for work.", "late", ["Late"]),
  match("ex-36-4", "36.4 · Ghép vấn đề — giải pháp", [
    { left: "too much work", right: "get an assistant" },
    { left: "a colleague in a bad mood", right: "pay no attention" },
    { left: "a crashed computer", right: "get a technician" },
    { left: "a coffee machine that isn't working", right: "drink water" },
  ]),
  cloze("ex-36-w1", "36 · Từ vựng", "I ___ my knee when I fell.", "cut", ["Cut"]),
  cloze("ex-36-w2", "36 · Từ vựng", "My brother ___ his credit card.", "lost", ["Lost"]),
  cloze("ex-36-w3", "36 · Từ vựng", "My cousin ___ a glass.", "broke", ["Broke"]),
  cloze("ex-36-w4", "36 · Từ vựng", "My DVD player didn't ___.", "work", ["Work"]),
];

const UNIT_37: VocabularyExercise[] = [
  cloze("ex-37-1-2", "37.1 · Vấn đề toàn cầu", "Picture 2: ___", "car crash", ["Car crash"]),
  cloze("ex-37-1-3", "37.1 · Vấn đề toàn cầu", "Picture 3: ___", "flood", ["Flood"]),
  cloze("ex-37-1-4", "37.1 · Vấn đề toàn cầu", "Picture 4: ___", "war", ["War"]),
  cloze("ex-37-1-5", "37.1 · Vấn đề toàn cầu", "Picture 5: ___", "earthquake", ["Earthquake"]),
  cloze("ex-37-1-6", "37.1 · Vấn đề toàn cầu", "Picture 6: ___", "forest fire", ["Forest fire"]),
  cloze("ex-37-1-7", "37.1 · Vấn đề toàn cầu", "Picture 7: ___", "hurricane", ["Hurricane"]),
  cloze("ex-37-1-8", "37.1 · Vấn đề toàn cầu", "Picture 8: ___", "traffic jam", ["Traffic jam"]),
  cloze("ex-37-1-9", "37.1 · Vấn đề toàn cầu", "Picture 9: ___", "snowstorm", ["Snowstorm"]),
  match("ex-37-2", "37.2 · Ghép cụm từ", [
    { left: "air", right: "pollution" },
    { left: "traffic", right: "jam" },
    { left: "rush", right: "hour" },
    { left: "forest", right: "fire" },
    { left: "crowded", right: "cities" },
    { left: "homeless", right: "people" },
    { left: "car", right: "crash" },
    { left: "earth", right: "quake" },
  ]),
  cloze("ex-37-3-2", "37.3 · Định nghĩa", "So many cars that they can't move easily: a ___", "traffic jam", ["Traffic jam"]),
  cloze("ex-37-3-3", "37.3 · Định nghĩa", "A street with a large number of people: ___", "crowded", ["Crowded"]),
  cloze("ex-37-3-4", "37.3 · Định nghĩa", "When two cars hit one another: a ___", "car crash", ["Car crash"]),
  cloze("ex-37-3-5", "37.3 · Định nghĩa", "Without work: ___", "unemployed", ["Unemployed"]),
  cloze("ex-37-5-2", "37.5 · Hoàn thành câu", "Their wages were low so the workers went on ___.", "strike", ["Strike"]),
  cloze("ex-37-5-3", "37.5 · Hoàn thành câu", "My great-grandfather died in the First World ___.", "War", ["War"]),
  cloze("ex-37-5-5", "37.5 · Hoàn thành câu", "Earthquakes and ___ can destroy towns.", "snowstorms", ["Snowstorms", "hurricanes", "Hurricanes"]),
  cloze("ex-37-5-6", "37.5 · Hoàn thành câu", "Poor, hungry and ___ people need help.", "homeless", ["Homeless"]),
];

const UNIT_38: VocabularyExercise[] = [
  cloze("ex-38-1-2", "38.1 · Have", "I have a tennis ___ every Saturday morning.", "lesson", ["Lesson"]),
  cloze("ex-38-1-4", "38.1 · Have", "Evelyn's having a ___ on Saturday.", "party", ["Party"]),
  cloze("ex-38-1-5", "38.1 · Have", "Do you want to have a ___?", "shower", ["Shower", "bath", "Bath"]),
  cloze("ex-38-1-6", "38.1 · Have", "I have an ___ tomorrow, so I have to study tonight.", "exam", ["Exam"]),
  cloze("ex-38-1-7", "38.1 · Have", "We must have a ___ to talk about these problems.", "meeting", ["Meeting"]),
  cloze("ex-38-1-9", "38.1 · Have", "The hotel has a pool, so we can have a ___ every day.", "swim", ["Swim"]),
  cloze("ex-38-2-2", "38.2 · Sửa lỗi", "Scarlett has gone to the hairdresser's to have ___ hair cut.", "her", ["Her"]),
  cloze("ex-38-2-3", "38.2 · Sửa lỗi", "That game looks great. Can I have a ___?", "go", ["Go"]),
  cloze("ex-38-2-4", "38.2 · Sửa lỗi", "I want to have a ___ with my teacher after the lesson.", "word", ["Word"]),
  cloze("ex-38-2-5", "38.2 · Sửa lỗi", "Mum didn't have the ___ to go to the shop today.", "time", ["Time"]),
  cloze("ex-38-2-6", "38.2 · Sửa lỗi", "They ___ got any cake in the café today.", "haven't", ["Haven't", "have not", "Have not"]),
  cloze("ex-38-4-2", "38.4 · Nói gì?", "Your friend is leaving on a trip. You say: ___", "Have a good journey", ["Have a good journey!", "Have a good time"]),
  mcq("ex-38-4-3", "38.4 · Nói gì?", "Someone is sneezing. You ask:", "b", [
    { key: "a", label: "Have a good journey!" },
    { key: "b", label: "Have you got a cold?" },
    { key: "c", label: "Have a party!" },
    { key: "d", label: "Have a word!" },
  ]),
  cloze("ex-38-4-4", "38.4 · Nói gì?", "You want to see something. You say: Can I have a ___?", "look", ["Look"]),
];

const UNIT_39: VocabularyExercise[] = [
  cloze("ex-39-1-2", "39.1 · Đi đâu?", "The Sharps are going to the ___.", "beach", ["Beach"]),
  cloze("ex-39-1-3", "39.1 · Đi đâu?", "Zoe and Penelope are going ___.", "shopping", ["Shopping"]),
  cloze("ex-39-1-4", "39.1 · Đi đâu?", "Asad is going to ___.", "Cairo", ["Cairo"]),
  cloze("ex-39-1-5", "39.1 · Đi đâu?", "Lars is going ___.", "fishing", ["Fishing"]),
  cloze("ex-39-2-2", "39.2 · Kế hoạch năm mới", "This year Victoria is going to ___ her driving test.", "pass", ["Pass"]),
  cloze("ex-39-2-3", "39.2 · Kế hoạch năm mới", "This year Victoria is going to learn ___.", "Spanish", ["Spanish"]),
  cloze("ex-39-2-4", "39.2 · Kế hoạch năm mới", "This year Victoria is going to watch ___ TV.", "less", ["Less"]),
  cloze("ex-39-2-5", "39.2 · Kế hoạch năm mới", "This year Victoria is going to keep her room ___.", "tidy", ["Tidy"]),
  mcq("ex-39-3-1", "39.3 · Hoạt động", "I sometimes go ___ on holiday.", "a", [
    { key: "a", label: "swimming" },
    { key: "b", label: "skiing" },
    { key: "c", label: "fishing" },
    { key: "d", label: "sightseeing" },
  ]),
  mcq("ex-39-3-2", "39.3 · Hoạt động", "I never go ___ on holiday.", "b", [
    { key: "a", label: "swimming" },
    { key: "b", label: "skiing" },
    { key: "c", label: "dancing" },
    { key: "d", label: "sightseeing" },
  ]),
  mcq("ex-39-3-3", "39.3 · Hoạt động", "I always go ___ when I visit a new city.", "d", [
    { key: "a", label: "fishing" },
    { key: "b", label: "skiing" },
    { key: "c", label: "shopping" },
    { key: "d", label: "sightseeing" },
  ]),
  mcq("ex-39-5-2", "39.5 · Sửa lỗi", "Mum is going for shopping this afternoon. Correct sentence:", "a", [
    { key: "a", label: "Mum is going shopping this afternoon." },
    { key: "b", label: "Mum is going for the shopping this afternoon." },
    { key: "c", label: "Mum goes to shopping this afternoon." },
    { key: "d", label: "Mum is going shop this afternoon." },
  ]),
  mcq("ex-39-5-5", "39.5 · Sửa lỗi", "Alexei is going to home at 4 o'clock. Correct sentence:", "b", [
    { key: "a", label: "Alexei is going to the home at 4 o'clock." },
    { key: "b", label: "Alexei is going home at 4 o'clock." },
    { key: "c", label: "Alexei goes at home at 4 o'clock." },
    { key: "d", label: "Alexei is going for home at 4 o'clock." },
  ]),
  cloze("ex-39-5-8", "39.5 · Sửa lỗi", "I go to swimming → I go ___ every Sunday morning.", "swimming", ["Swimming"]),
  cloze("ex-39-5-9", "39.5 · Sửa lỗi", "We're going ___ today. → going sightseeing", "sightsee", ["Sightseeing"]),
];

const UNIT_40: VocabularyExercise[] = [
  mcq("ex-40-1-2", "40.1 · Đang làm gì?", "What are the girls doing? They're ___", "a", [
    { key: "a", label: "playing tennis" },
    { key: "b", label: "sleeping" },
    { key: "c", label: "reading a book" },
    { key: "d", label: "gardening" },
  ]),
  mcq("ex-40-1-3", "40.1 · Đang làm gì?", "What is the dog doing? It's ___", "b", [
    { key: "a", label: "eating an ice cream" },
    { key: "b", label: "sleeping" },
    { key: "c", label: "playing tennis" },
    { key: "d", label: "washing up" },
  ]),
  mcq("ex-40-1-4", "40.1 · Đang làm gì?", "What is the man in the house doing? He's ___", "c", [
    { key: "a", label: "gardening" },
    { key: "b", label: "reading" },
    { key: "c", label: "washing up" },
    { key: "d", label: "sleeping" },
  ]),
  mcq("ex-40-1-5", "40.1 · Đang làm gì?", "What is the woman doing? She's ___", "d", [
    { key: "a", label: "gardening" },
    { key: "b", label: "sleeping" },
    { key: "c", label: "washing up" },
    { key: "d", label: "reading a book" },
  ]),
  mcq("ex-40-1-6", "40.1 · Đang làm gì?", "What is the man in the garden doing? He's ___", "a", [
    { key: "a", label: "gardening" },
    { key: "b", label: "reading" },
    { key: "c", label: "sleeping" },
    { key: "d", label: "washing up" },
  ]),
  cloze("ex-40-2-2", "40.2 · Nghề nghiệp", "What does Lee Atkins do? He's a ___.", "teacher", ["Teacher"]),
  cloze("ex-40-2-3", "40.2 · Nghề nghiệp", "What does Sophie Hicks do? She's a ___.", "doctor", ["Doctor"]),
  cloze("ex-40-2-4", "40.2 · Nghề nghiệp", "What do Cooper and Hailey do? They're ___.", "students", ["Students"]),
  cloze("ex-40-3-2", "40.3 · Sáng nay", "What did Lara Brown do? She went to a ___.", "meeting", ["Meeting"]),
  cloze("ex-40-3-3", "40.3 · Sáng nay", "What did Sophie Hicks do? She talked to five ___.", "patients", ["Patients"]),
  cloze("ex-40-3-4", "40.3 · Sáng nay", "What did Cooper and Hailey do? They wrote an ___.", "essay", ["Essay"]),
  cloze("ex-40-w1", "40 · Do", "I hate doing the ___.", "housework", ["Housework"]),
  cloze("ex-40-w2", "40 · Do", "My son has to do his ___ every day.", "homework", ["Homework"]),
  cloze("ex-40-w3", "40 · Do", "I love doing the ___.", "gardening", ["Gardening"]),
  cloze("ex-40-5-2", "40.5 · Sửa hội thoại", "No, we don't go to Wales → No, we ___ go to Wales", "didn't", ["Didn't"]),
  cloze("ex-40-5-3", "40.5 · Sửa hội thoại", "Do your grandmother lives → Does your grandmother ___", "live", ["Live"]),
];

const UNIT_41: VocabularyExercise[] = [
  cloze("ex-41-1-2", "41.1 · Make", "Our neighbours ___ a lot of noise last night.", "made", ["Made"]),
  cloze("ex-41-1-3", "41.1 · Make", "I am ___ dinner for my parents this evening.", "making", ["Making"]),
  cloze("ex-41-1-4", "41.1 · Make", "We must ___ our choice today.", "make", ["Make"]),
  cloze("ex-41-1-5", "41.1 · Make", "I ___ an appointment with the doctor for you.", "made", ["Made", "have made", "Have made"]),
  cloze("ex-41-1-6", "41.1 · Make", "Craig is ___ a cup of tea.", "making", ["Making"]),
  cloze("ex-41-2-2", "41.2 · Make + cảm giác", "Long lessons always make me (feel) ___.", "tired", ["Tired"]),
  cloze("ex-41-2-3", "41.2 · Make + cảm giác", "She was horrible to me; it made me (feel) ___.", "angry", ["Angry"]),
  cloze("ex-41-2-4", "41.2 · Make + cảm giác", "It's a lovely song. It makes me (feel) ___.", "happy", ["Happy"]),
  cloze("ex-41-2-5", "41.2 · Make + cảm giác", "That meal was horrible. It made me (feel) ___.", "sick", ["Sick"]),
  cloze("ex-41-3-2", "41.3 · Đang làm gì?", "She's ___ tea.", "making", ["Making"]),
  cloze("ex-41-3-3", "41.3 · Đang làm gì?", "The little boys are ___ a noise.", "making", ["Making"]),
  cloze("ex-41-3-5", "41.3 · Đang làm gì?", "The children are ___ a mess.", "making", ["Making"]),
  cloze("ex-41-3-6", "41.3 · Đang làm gì?", "She is ___ her bed.", "making", ["Making"]),
  cloze("ex-41-4-2", "41.4 · Sửa lỗi", "Can I make a photo → Can I ___ a photo of you?", "take", ["Take"]),
  cloze("ex-41-4-4", "41.4 · Sửa lỗi", "Are you making an exam → Are you ___ / taking an exam?", "doing", ["Doing"]),
  cloze("ex-41-4-5", "41.4 · Sửa lỗi", "Have you made your homework → Have you ___ your homework?", "done", ["Done"]),
];

const UNIT_42: VocabularyExercise[] = [
  cloze("ex-42-1-2", "42.1 · Come", "A: I'm going to Thailand. B: When are you coming ___?", "back", ["Back"]),
  cloze("ex-42-1-3", "42.1 · Come", "The teacher came ___ the classroom.", "into", ["Into"]),
  cloze("ex-42-1-4", "42.1 · Come", "A: Where do you come ___? B: I'm Spanish.", "from", ["From"]),
  cloze("ex-42-1-5", "42.1 · Come", "Come and ___ me at 5 o'clock.", "see", ["See"]),
  cloze("ex-42-1-6", "42.1 · Come", "The children come ___ school at 4 o'clock.", "out of", ["Out of", "home from", "Home from"]),
  cloze("ex-42-2-2", "42.2 · Hội thoại", "Someone at the door says: ___!", "Come in", ["Come in"]),
  cloze("ex-42-2-3", "42.2 · Hội thoại", "We're going to a party. Do you want to ___?", "come along", ["Come along"]),
  cloze("ex-42-2-4", "42.2 · Hội thoại", "I come ___ France.", "from", ["From"]),
  cloze("ex-42-3-2", "42.3 · Dạng đúng", "She ___ back yesterday.", "came", ["Came"]),
  cloze("ex-42-3-3", "42.3 · Dạng đúng", "He ___ here every Tuesday.", "comes", ["Comes"]),
  cloze("ex-42-3-4", "42.3 · Dạng đúng", "___ you coming to the party tonight?", "Are", ["Are"]),
  cloze("ex-42-3-5", "42.3 · Dạng đúng", "Pierre ___ from a small town in Luxembourg.", "comes", ["Comes"]),
  cloze("ex-42-4-1", "42.4 · Thói quen", "I usually come ___ at five-thirty.", "home", ["Home"]),
];

const UNIT_43: VocabularyExercise[] = [
  cloze("ex-43-1-1", "43.1 · It takes", "It ___ me 10 minutes to get to university.", "takes", ["Takes"]),
  cloze("ex-43-1-2", "43.1 · It takes", "It takes me 30 minutes to go to the nearest railway ___.", "station", ["Station"]),
  cloze("ex-43-1-3", "43.1 · It takes", "It ___ me an hour to do one unit of this book.", "takes", ["Takes"]),
  cloze("ex-43-2-2", "43.2 · Take + cụm", "You can fly to Paris or you can ___", "take the train", ["Take the train"]),
  cloze("ex-43-2-3", "43.2 · Take + cụm", "You want to learn Russian? Why don't you ___?", "take a course", ["Take a course"]),
  cloze("ex-43-2-4", "43.2 · Take + cụm", "If you go out on a hot day, you need to ___", "take some water", ["Take some water"]),
  cloze("ex-43-3-2", "43.3 · Phương tiện", "How can I get to the airport? You can ___", "take a taxi", ["Take a taxi"]),
  cloze("ex-43-3-3", "43.3 · Phương tiện", "How does Christopher go to school? He ___", "takes the bus", ["Takes the bus"]),
  cloze("ex-43-3-4", "43.3 · Phương tiện", "How do Santiago and Lucia get home? They ___", "take the underground", ["Take the underground"]),
  cloze("ex-43-4-2", "43.4 · Mang theo", "When it's raining I take my ___.", "umbrella", ["Umbrella"]),
  cloze("ex-43-4-3", "43.4 · Mang theo", "When you go to another country you take your ___.", "passport", ["Passport"]),
  cloze("ex-43-4-4", "43.4 · Mang theo", "When I go to English lessons I take my ___ and pen.", "notebook", ["Notebook"]),
  cloze("ex-43-4-5", "43.4 · Mang theo", "When I need to text someone I take my ___", "mobile", ["Mobile", "mobile phone", "Mobile phone"]),
];

const UNIT_44: VocabularyExercise[] = [
  cloze("ex-44-1-2", "44.1 · Bring / take", "Don't forget to ___ your books tomorrow!", "bring", ["Bring"]),
  cloze("ex-44-1-3", "44.1 · Bring / take", "Can you ___ me some water?", "bring", ["Bring"]),
  cloze("ex-44-1-4", "44.1 · Bring / take", "___ your camera with you when you go to Thailand.", "Take", ["Take"]),
  cloze("ex-44-1-5", "44.1 · Bring / take", "Can you ___ these papers, please?", "take", ["Take"]),
  cloze("ex-44-1-6", "44.1 · Bring / take", "I'll ___ you a present from New York.", "bring", ["Bring"]),
  match("ex-44-2", "44.2 · Ghép câu", [
    { left: "Go to the post office and take", right: "these letters, please" },
    { left: "Come to my house and bring", right: "your guitar" },
    { left: "Everybody is going to bring", right: "food to the party" },
    { left: "You must take", right: "your passport when you travel" },
  ]),
  cloze("ex-44-3-1", "44.3 · Dạng đúng", "She always ___ me presents.", "brings", ["Brings"]),
  cloze("ex-44-3-2", "44.3 · Dạng đúng", "Yesterday she ___ me some chocolates.", "brought", ["Brought"]),
  cloze("ex-44-3-3", "44.3 · Dạng đúng", "Can you ___ this present when you go and see Sonia?", "take", ["Take"]),
  cloze("ex-44-3-4", "44.3 · Dạng đúng", "She is going to ___ my book and ___ it back tomorrow.", "take", ["Take"]),
  cloze("ex-44-4-1", "44.4 · Bring back", "Can I ___ this magazine? I'll ___ it tomorrow.", "take", ["Take"]),
  cloze("ex-44-4-2", "44.4 · Bring back", "When she went to Belgium, she ___ me some chocolates.", "brought", ["Brought"]),
];

const UNIT_45: VocabularyExercise[] = [
  mcq("ex-45-1-2", "45.1 · Get + tính từ", "I ate too much and I got ___", "c", [
    { key: "a", label: "hot" },
    { key: "b", label: "tired" },
    { key: "c", label: "sick" },
    { key: "d", label: "dark" },
  ]),
  mcq("ex-45-1-3", "45.1 · Get + tính từ", "I sat in the sun too much and I got ___", "a", [
    { key: "a", label: "hot" },
    { key: "b", label: "tired" },
    { key: "c", label: "sick" },
    { key: "d", label: "wet" },
  ]),
  mcq("ex-45-1-4", "45.1 · Get + tính từ", "In winter in the north it gets ___ very early.", "b", [
    { key: "a", label: "tired" },
    { key: "b", label: "dark" },
    { key: "c", label: "wet" },
    { key: "d", label: "sick" },
  ]),
  mcq("ex-45-1-5", "45.1 · Get + tính từ", "Vincent got very ___ in the rain.", "c", [
    { key: "a", label: "dark" },
    { key: "b", label: "better" },
    { key: "c", label: "wet" },
    { key: "d", label: "hot" },
  ]),
  cloze("ex-45-2-2", "45.2 · Get + tính từ", "When the sun comes up it gets ___.", "light", ["Light"]),
  cloze("ex-45-2-3", "45.2 · Get + tính từ", "She's in hospital but she's getting ___.", "better", ["Better"]),
  cloze("ex-45-2-4", "45.2 · Get + tính từ", "It's raining! I'm getting ___!", "wet", ["Wet"]),
  cloze("ex-45-2-5", "45.2 · Get + tính từ", "Please close the window. I'm getting ___.", "cold", ["Cold"]),
  cloze("ex-45-3-2", "45.3 · Get + danh từ", "Somebody is ill! Please get a ___.", "doctor", ["Doctor"]),
  cloze("ex-45-3-3", "45.3 · Get + danh từ", "Do you want a drink? I can get some ___.", "coffee", ["Coffee", "drink", "Drink"]),
  cloze("ex-45-3-4", "45.3 · Get + danh từ", "Where can I get a ___?", "taxi", ["Taxi"]),
  cloze("ex-45-3-5", "45.3 · Get + danh từ", "I've finished my studies. Now I want to get a ___.", "job", ["Job"]),
  cloze("ex-45-4-2", "45.4 · Get to / home", "The bus from the university ___ my house in 25 minutes.", "gets to", ["Gets to"]),
  cloze("ex-45-4-4", "45.4 · Get to / home", "José usually leaves work at 6 and ___ home at 6.30.", "gets", ["Gets"]),
  cloze("ex-45-4-5", "45.4 · Get to / home", "Mike is in New York. He won't ___ till the 14th July.", "get back", ["Get back", "get home", "Get home"]),
  mcq("ex-45-w1", "45 · Get", "Maria and David are ___ married in April.", "a", [
    { key: "a", label: "getting" },
    { key: "b", label: "going" },
    { key: "c", label: "making" },
    { key: "d", label: "having" },
  ]),
];

export const CURATED_UNITS_31_45: Readonly<Partial<Record<number, readonly VocabularyExercise[]>>> = {
  31: UNIT_31,
  32: UNIT_32,
  33: UNIT_33,
  34: UNIT_34,
  35: UNIT_35,
  36: UNIT_36,
  37: UNIT_37,
  38: UNIT_38,
  39: UNIT_39,
  40: UNIT_40,
  41: UNIT_41,
  42: UNIT_42,
  43: UNIT_43,
  44: UNIT_44,
  45: UNIT_45,
};

for (const [unitNumber, exercises] of Object.entries(CURATED_UNITS_31_45)) {
  if (exercises) {
    assertExerciseCount(Number(unitNumber), exercises);
  }
}
