export const CURATED_PRE_PROMPT_VI_61_75: Readonly<Record<string, string>> = {
  "ex-pre-61-1": "Ghép mỗi từ với nghĩa tiếng Việt.",
  "ex-pre-61-2": "Hãy thêm một ___ (số không) vào con số.",
  "ex-pre-61-3": "Sáng nay tôi mua một ___ (tá) trứng.",
  "ex-pre-61-4": "Viết đáp án dưới dạng ___ (số thập phân).",
  "ex-pre-61-5": "Tôi cần con số ___ (chính xác), không phải phỏng đoán.",
  "ex-pre-61-6": "Bảy là một số ___ (lẻ).",
  "ex-pre-61-7": "Bạn nên ___ (làm tròn lên) 4.6 thành 5.",
  "ex-pre-61-8": "Bạn có thể ___ (tính) tổng nhanh không?",
  "ex-pre-61-9": "Từ nào có nghĩa 'một tỷ'?",
  "ex-pre-61-10": "Từ nào chỉ một phần nhỏ của tổng thể?",
  "ex-pre-61-11": "Từ nào có nghĩa 'khoảng chừng, không chính xác'?",
  "ex-pre-61-12": "\"To ___\" nghĩa là ước lượng một con số mà không tính chính xác.",
  "ex-pre-61-13": "Từ nào có nghĩa 'tỷ lệ phần trăm'?",
  "ex-pre-61-14": "Chúng ta ___ 7.2 xuống 7.",
  "ex-pre-62-1": "Ghép mỗi từ với nghĩa tiếng Việt.",
  "ex-pre-62-2": "Chúng tôi đo ___ (chiều dài) của bàn.",
  "ex-pre-62-3": "___ (chiều cao) của bạn tính bằng centimet là bao nhiêu?",
  "ex-pre-62-4": "___ (độ sâu) của hồ bơi là hai mét.",
  "ex-pre-62-5": "___ (bán kính) bằng một nửa đường kính.",
  "ex-pre-62-6": "Chúng tôi tính ___ (diện tích) của căn phòng.",
  "ex-pre-62-7": "Kiện hàng ___ (nặng) ba kilogram.",
  "ex-pre-62-8": "Kim loại có thể ___ (giãn nở) khi trời nóng.",
  "ex-pre-62-9": "Từ nào có nghĩa 'trọng lượng'?",
  "ex-pre-62-10": "Từ nào có nghĩa 'rất nhỏ'?",
  "ex-pre-62-11": "Quần áo len có thể ___ trong nước nóng.",
  "ex-pre-62-12": "Chiếc pizza có ___ 30 cm.",
  "ex-pre-62-13": "Kiểm tra kỹ từng ___ trước khi cắt.",
  "ex-pre-62-14": "Chiếc hộp đó quá ___ để nhấc lên.",
  "ex-pre-63-1": "Ghép mỗi từ với nghĩa tiếng Việt.",
  "ex-pre-63-2": "Hãy di chuyển ___ (vật) nặng đó cẩn thận.",
  "ex-pre-63-3": "Chiếc áo khoác này làm bằng ___ (chất liệu) gì?",
  "ex-pre-63-4": "___ (vải) này mềm mại và thoáng khí.",
  "ex-pre-63-5": "Chúng tôi mua một chiếc ghế ___ (bằng gỗ).",
  "ex-pre-63-6": "Bề mặt ___ (mịn) khi chạm vào.",
  "ex-pre-63-7": "Vẽ một ___ (hình tròn) ở giữa.",
  "ex-pre-63-8": "Chiếc gương có hình ___ (chữ nhật).",
  "ex-pre-63-9": "Từ nào có nghĩa 'thô ráp, gồ ghề'?",
  "ex-pre-63-10": "Từ nào có nghĩa 'nhựa'?",
  "ex-pre-63-11": "Một ___ có ba cạnh.",
  "ex-pre-63-12": "Tôi thích ___ xanh đậm hơn này.",
  "ex-pre-63-13": "Từ nào có nghĩa 'trang thiết bị, dụng cụ'?",
  "ex-pre-63-14": "Khu chợ đầy quần áo ___.",
  "ex-pre-64-1": "Ghép mỗi từ với nghĩa tiếng Việt.",
  "ex-pre-64-2": "Cô ấy đổ đầy nước vào một ___ (chai).",
  "ex-pre-64-3": "Có mật ong trong ___ (lọ) đó.",
  "ex-pre-64-4": "Cho tôi một ___ (lát) bánh mì được không?",
  "ex-pre-64-5": "Thêm một ___ (giọt) nước cốt chanh.",
  "ex-pre-64-6": "Anh ấy mua một ___ (nải) chuối.",
  "ex-pre-64-7": "Hãy ___ (đổ rỗng) thùng rác trước khi rời đi.",
  "ex-pre-64-8": "Bạn có thể ___ (đổ đầy) chai này giúp tôi không?",
  "ex-pre-64-9": "Từ nào có nghĩa 'hộp giấy cứng, hộp đựng sữa'?",
  "ex-pre-64-10": "Lấy một ___ đường.",
  "ex-pre-64-11": "Mua ___ giúp tiết kiệm tiền.",
  "ex-pre-64-12": "Cho tôi một ___ sô cô la.",
  "ex-pre-64-13": "Chiếc xe tải chở một ___ đầy.",
  "ex-pre-64-14": "Cô ấy bóp kem đánh răng từ ___.",
  "ex-pre-65-1": "Ghép mỗi từ với nghĩa tiếng Việt.",
  "ex-pre-65-2": "Tôi ___ (xin lỗi) vì đã đến muộn.",
  "ex-pre-65-3": "Anh ấy đưa ra một ___ (lời xin lỗi) chân thành.",
  "ex-pre-65-4": "Đó là ___ (lỗi) của tôi, không phải của bạn.",
  "ex-pre-65-5": "Hãy ___ (tha thứ) cho lỗi của tôi.",
  "ex-pre-65-6": "Tôi thực sự ___ (trân trọng) lời khuyên của bạn.",
  "ex-pre-65-7": "Tôi sẽ ___ (bù đắp) cho bạn.",
  "ex-pre-65-8": "___ (tôi xin lỗi) vì sự nhầm lẫn.",
  "ex-pre-65-9": "Cụm nào có nghĩa 'xin phép / xin lỗi khi làm phiền'?",
  "ex-pre-65-10": "Từ nào có nghĩa 'hối tiếc'?",
  "ex-pre-65-11": "Lời giải thích của bạn ___.",
  "ex-pre-65-12": "Tôi ___ bạn một lời xin lỗi.",
  "ex-pre-65-13": "Từ nào có nghĩa 'biết ơn'?",
  "ex-pre-65-14": "Trễ mười phút là điều ___.",
  "ex-pre-66-1": "Ghép mỗi từ với nghĩa tiếng Việt.",
  "ex-pre-66-2": "Tôi gửi một ___ (yêu cầu) để biết thêm chi tiết.",
  "ex-pre-66-3": "Bạn có thể ___ (yêu cầu) hoàn tiền tại quầy.",
  "ex-pre-66-4": "Họ không ___ (cho phép) dùng điện thoại trong lớp.",
  "ex-pre-66-5": "Hãy ___ (để) tôi giải thích.",
  "ex-pre-66-6": "Tôi ___ (giới thiệu) cuốn từ điển này.",
  "ex-pre-66-7": "Tôi vui vẻ ___ (chấp nhận) lời mời của bạn.",
  "ex-pre-66-8": "___ (còn) gặp nhau lúc bảy giờ thì sao?",
  "ex-pre-66-9": "Cụm nào là cách lịch sự để nhờ ai đó làm việc gì?",
  "ex-pre-66-10": "Cụm nào có nghĩa 'được phép làm gì'?",
  "ex-pre-66-11": "Cô ấy ___ ký vào biểu mẫu.",
  "ex-pre-66-12": "Cụm nào có nghĩa 'sao chúng ta không...'?",
  "ex-pre-66-13": "Cảm ơn vì ___ hữu ích.",
  "ex-pre-66-14": "Bạn có thể ___ yêu cầu này hôm nay không?",
  "ex-pre-67-1": "Ghép mỗi từ với nghĩa tiếng Việt.",
  "ex-pre-67-2": "Mỗi người có một ___ (ý kiến) khác nhau.",
  "ex-pre-67-3": "Hãy thử nhìn từ ___ (góc nhìn) của cô ấy.",
  "ex-pre-67-4": "___ (theo tôi), kế hoạch này thực tế.",
  "ex-pre-67-5": "Tôi ___ (đồng ý) với đề xuất của bạn.",
  "ex-pre-67-6": "Tôi ___ (hoàn toàn) đồng ý với bạn.",
  "ex-pre-67-7": "Bạn có thể ___ (thuyết phục) họ tham gia không?",
  "ex-pre-67-8": "Chúng ta cần ___ (bằng chứng) để hỗ trợ luận điểm này.",
  "ex-pre-67-9": "Cụm nào có nghĩa 'thành thật mà nói'?",
  "ex-pre-67-10": "Từ nào có nghĩa 'một phần'?",
  "ex-pre-67-11": "Đó là một ___, cảm ơn.",
  "ex-pre-67-12": "Cô ấy đưa ra một ___ mạnh mẽ.",
  "ex-pre-67-13": "Cụm nào có nghĩa 'không hẳn vậy'?",
  "ex-pre-67-14": "___, các quy tắc rõ ràng giúp ích.",
  "ex-pre-68-1": "Ghép mỗi từ với nghĩa tiếng Việt.",
  "ex-pre-68-2": "Tôi ___ (thích) thiết kế mới này.",
  "ex-pre-68-3": "Tôi ___ (thích hơn) trà so với cà phê.",
  "ex-pre-68-4": "Xanh dương là màu ___ (yêu thích) của tôi.",
  "ex-pre-68-5": "Chúng tôi ___ (thích) đi bộ sau bữa tối.",
  "ex-pre-68-6": "Tôi ___ (hứng thú với) thiết kế đồ họa.",
  "ex-pre-68-7": "Tôi ___ (không chịu nổi) tiếng ồn lớn.",
  "ex-pre-68-8": "Tôi thà đi bộ ___ (hơn là) lái xe.",
  "ex-pre-68-9": "Cụm nào có nghĩa 'rất mê, cực kỳ thích'?",
  "ex-pre-68-10": "Nhiều người dùng ___ biểu mẫu dài.",
  "ex-pre-68-11": "Chúng tôi có ___ tương tự về phim ảnh.",
  "ex-pre-68-12": "Tối nay tôi ___ ở nhà.",
  "ex-pre-68-13": "Bà tôi ___ nhạc cổ điển.",
  "ex-pre-68-14": "Bạn có một ___ giữa hai lựa chọn.",
  "ex-pre-69-1": "Ghép mỗi từ với nghĩa tiếng Việt.",
  "ex-pre-69-2": "Hãy ___ (chào đón) khách ở cửa.",
  "ex-pre-69-3": "___ (chào mừng) đến văn phòng của chúng tôi.",
  "ex-pre-69-4": "Để tôi ___ (giới thiệu) đồng nghiệp của mình.",
  "ex-pre-69-5": "___ (rất vui được gặp bạn) sau bao lâu.",
  "ex-pre-69-6": "___ (hẹn gặp) ngày mai ở lớp.",
  "ex-pre-69-7": "___ (giữ gìn nhé) trên đường về nhà.",
  "ex-pre-69-8": "___ (chúc một ngày tốt lành) ở chỗ làm.",
  "ex-pre-69-9": "Lời chào nào là thân mật, không trang trọng?",
  "ex-pre-69-10": "Cụm nào có nghĩa 'chúc chuyến đi an toàn'?",
  "ex-pre-69-11": "Họ tổ chức một bữa tiệc ___.",
  "ex-pre-69-12": "___ hôm nay?",
  "ex-pre-69-13": "Cụm nào có nghĩa 'gặp lại sau nhé'?",
  "ex-pre-69-14": "Một ___ ấm áp khiến mọi người thoải mái.",
  "ex-pre-70-1": "Ghép mỗi từ với nghĩa tiếng Việt.",
  "ex-pre-70-2": "Nguyên nhân vẫn còn ___ (chưa rõ).",
  "ex-pre-70-3": "Tôi đã ___ (hiểu nhầm) tin nhắn của bạn.",
  "ex-pre-70-4": "Hãy ___ (viết lại) đoạn văn này.",
  "ex-pre-70-5": "Hãy ___ (kiểm tra lại) các con số cuối cùng.",
  "ex-pre-70-6": "Đừng ___ (nấu quá chín) rau.",
  "ex-pre-70-7": "Tôi ___ (ngủ quên) và lỡ xe buýt.",
  "ex-pre-70-8": "Đừng ___ (đánh giá thấp) nhiệm vụ này.",
  "ex-pre-70-9": "Từ nào có tiền tố mang nghĩa 'không' hoặc 'trái ngược'?",
  "ex-pre-70-10": "Từ nào có nghĩa 'trả trước'?",
  "ex-pre-70-11": "Chúng tôi xem một ___ của bộ phim.",
  "ex-pre-70-12": "Các phong cách khác nhau có thể ___.",
  "ex-pre-70-13": "Cuốn sách giáo khoa này có một ___.",
  "ex-pre-70-14": "Anh ấy trở nên ___ trong nhóm đông người.",
  "ex-pre-71-1": "Ghép mỗi từ với nghĩa tiếng Việt.",
  "ex-pre-71-2": "___ (lòng tốt) của cô ấy khiến mọi người xúc động.",
  "ex-pre-71-3": "Căn phòng chìm trong ___ (bóng tối) hoàn toàn.",
  "ex-pre-71-4": "___ (tình bạn) của họ bắt đầu từ thời đại học.",
  "ex-pre-71-5": "___ (phí thành viên) phòng gym được trả hằng tháng.",
  "ex-pre-71-6": "___ (tài xế) xe buýt rất kiên nhẫn.",
  "ex-pre-71-7": "___ (học viên tập sự) đặt nhiều câu hỏi thông minh.",
  "ex-pre-71-8": "Tôi kiểm tra ___ (bản dịch) hai lần.",
  "ex-pre-71-9": "Từ nào có nghĩa 'khách tham quan'?",
  "ex-pre-71-10": "Đó là một ___ khó khăn.",
  "ex-pre-71-11": "___ tốt xây dựng lòng tin.",
  "ex-pre-71-12": "___ ngoài trời cải thiện tâm trạng.",
  "ex-pre-71-13": "Không có ___ nào về kết quả.",
  "ex-pre-71-14": "Mỗi ___ phải đeo thẻ nhân viên.",
  "ex-pre-72-1": "Ghép mỗi từ với nghĩa tiếng Việt.",
  "ex-pre-72-2": "Ứng dụng này rất ___ (hữu ích) cho học sinh.",
  "ex-pre-72-3": "Hãy ___ (cẩn thận) với con dao đó.",
  "ex-pre-72-4": "Hướng dẫn viên rất ___ (nhiệt tình giúp đỡ).",
  "ex-pre-72-5": "Đà Nẵng ___ (nổi tiếng) với các bãi biển.",
  "ex-pre-72-6": "Tôi cảm thấy ___ (lo lắng) trước buổi phỏng vấn.",
  "ex-pre-72-7": "Ngày mai trời sẽ ___ (nắng).",
  "ex-pre-72-8": "Đôi giày này ___ (thoải mái).",
  "ex-pre-72-9": "Từ nào có nghĩa 'nguy hiểm'?",
  "ex-pre-72-10": "Bầu trời ___ sáng nay.",
  "ex-pre-72-11": "Con phố này ___ vào ban đêm.",
  "ex-pre-72-12": "Hôm nay là một ngày lễ ___.",
  "ex-pre-72-13": "Món súp đó thực sự ___.",
  "ex-pre-72-14": "Trời quá ___ để đi thuyền.",
  "ex-pre-73-1": "Ghép mỗi từ với nghĩa tiếng Việt.",
  "ex-pre-73-2": "Tôi bỏ ___ (bàn chải đánh răng) vào một túi nhỏ.",
  "ex-pre-73-3": "Mua một tuýp ___ (kem đánh răng) mới.",
  "ex-pre-73-4": "___ (phòng ngủ) của chúng tôi nhìn ra khu vườn.",
  "ex-pre-73-5": "Tôi ghi ý tưởng vào ___ (sổ tay).",
  "ex-pre-73-6": "Cô ấy đeo ___ (kính râm) ở bãi biển.",
  "ex-pre-73-7": "___ (bàn phím) của tôi không dây.",
  "ex-pre-73-8": "Gặp tôi ở ___ (trạm xe buýt).",
  "ex-pre-73-9": "Danh từ ghép nào có nghĩa 'quán cà phê'?",
  "ex-pre-73-10": "Phòng khách sạn có kèm một ___.",
  "ex-pre-73-11": "Chúng tôi về thăm bố mẹ vào ___ này.",
  "ex-pre-73-12": "Giờ đây hầu như ai cũng có một ___.",
  "ex-pre-73-13": "___ trên dòng sông thật đẹp.",
  "ex-pre-73-14": "Bạn có chấp nhận thanh toán bằng ___ không?",
  "ex-pre-74-1": "Ghép mỗi từ với nghĩa tiếng Việt.",
  "ex-pre-74-2": "Hôm nay chúng ta cần ___ (đưa ra quyết định).",
  "ex-pre-74-3": "Hãy ___ (nghỉ giải lao) sau phần này.",
  "ex-pre-74-4": "Bạn ___ (xem qua) tệp này được không?",
  "ex-pre-74-5": "Tôi thường ___ (làm bài tập) sau bữa tối.",
  "ex-pre-74-6": "Chúng ta phải ___ (bắt xe buýt) lúc 6:30.",
  "ex-pre-74-7": "Hãy ___ (chú ý) đến hướng dẫn.",
  "ex-pre-74-8": "Hãy cố ___ (giữ bình tĩnh) trong khi thi.",
  "ex-pre-74-9": "Cụm kết hợp nào có nghĩa 'tiết kiệm thời gian'?",
  "ex-pre-74-10": "Bạn nên ___.",
  "ex-pre-74-11": "Anh ấy không bao giờ ___.",
  "ex-pre-74-12": "Đặt một ___ lúc 5 giờ sáng.",
  "ex-pre-74-13": "Người lãnh đạo nên ___.",
  "ex-pre-74-14": "Chúng ta đã ___ sữa.",
  "ex-pre-75-1": "Ghép mỗi từ với nghĩa tiếng Việt.",
  "ex-pre-75-2": "Vui lòng trả lời ___ (càng sớm càng tốt).",
  "ex-pre-75-3": "___ (nhân tiện), kiện hàng của bạn đã đến.",
  "ex-pre-75-4": "___ (thực ra), chúng tôi hoàn thành sớm hơn dự kiến.",
  "ex-pre-75-5": "Mang theo ___ (ít nhất) hai bản sao.",
  "ex-pre-75-6": "___ (lúc đầu), tôi không hiểu nhiệm vụ.",
  "ex-pre-75-7": "Tàu đến ___ (đúng giờ).",
  "ex-pre-75-8": "Chúng tôi đến ga ___ (kịp giờ).",
  "ex-pre-75-9": "Cụm nào có nghĩa 'thỉnh thoảng'?",
  "ex-pre-75-10": "___, chúng tôi chọn phương án B.",
  "ex-pre-75-11": "Cụm nào có nghĩa 'nói cách khác'?",
  "ex-pre-75-12": "Cô ấy không xóa tệp ___.",
  "ex-pre-75-13": "Anh ấy đến sớm ___.",
  "ex-pre-75-14": "Cụm nào có nghĩa 'thành thật mà nói'?",
};
