import type { VocabularyUnit } from "@/lib/vocabulary/vocabulary-unit-types";
import {
  bold,
  ex,
  fillBlank,
  mcq,
  purple,
} from "@/lib/vocabulary/units/eviu-unit-builder";
import { upperUnit, wordList } from "@/lib/vocabulary/units/eviu-upper-unit-helpers";

const U5_WORDS = wordList([
  ["the Netherlands", "Hà Lan", "Amsterdam is the capital of the Netherlands."],
  ["Briton", "người Anh", "Many Britons travel abroad in summer."],
  ["bilingual", "nói được hai ngôn ngữ", "Growing up bilingual helped her at work.", "ADJECTIVE"],
  ["multilingual", "nói được nhiều ngôn ngữ", "The tour guide is multilingual.", "ADJECTIVE"],
  ["monolingual", "chỉ nói một ngôn ngữ", "Some schools still teach in a monolingual setting.", "ADJECTIVE"],
  ["mother tongue", "tiếng mẹ đẻ", "Vietnamese is her mother tongue."],
  ["dialect", "phương ngữ", "He speaks a northern dialect of Italian."],
  ["Far East", "vùng Viễn Đông", "She has lived in the Far East for years."],
  ["Middle East", "Trung Đông", "Oil prices often depend on events in the Middle East."],
  ["Latin American", "thuộc Mỹ Latinh", "They love Latin American music.", "ADJECTIVE"],
  ["ethnic group", "nhóm dân tộc", "The city is home to many ethnic groups."],
  ["African-Caribbean", "người gốc Phi–Caribbean", "African-Caribbean culture is vibrant in London.", "ADJECTIVE"],
  ["Catalan", "tiếng hoặc người Catalan", "Catalan is widely spoken in Barcelona."],
  ["Flemish", "tiếng Flanders (Bỉ)", "Flemish and French are both used in Belgium."],
  ["Cypriot", "người Síp", "A Cypriot friend invited us to Nicosia.", "ADJECTIVE"],
  ["native speaker", "người bản ngữ", "The course is taught by a native speaker."],
  ["official language", "ngôn ngữ chính thức", "English is an official language in India."],
  ["nationality", "quốc tịch", "What is your nationality?"],
  ["the UAE", "Các Tiểu vương quốc Ả Rập Thống nhất", "Dubai is in the UAE."],
  ["the Philippines", "Philippines", "Manila is the capital of the Philippines."],
  ["Spaniard", "người Tây Ban Nha", "A Spaniard sat next to me on the train."],
  ["Scandinavia", "Bán đảo Scandinavia", "She toured Scandinavia last summer."],
  ["the Mediterranean", "vùng Địa Trung Hải", "They sailed around the Mediterranean."],
  ["the Caribbean", "vùng Caribe", "We spent a week in the Caribbean."],
  ["Slavonic", "thuộc nhóm ngôn ngữ Slav", "Russian is a Slavonic language.", "ADJECTIVE"],
]);

const U6_WORDS = wordList([
  ["misty", "có sương mù nhẹ", "It was a misty morning in the hills.", "ADJECTIVE"],
  ["damp", "ẩm ướt", "The clothes still feel damp.", "ADJECTIVE"],
  ["frost", "sương giá", "There was frost on the grass at dawn."],
  ["thaw", "tan băng, hết giá", "The snow began to thaw in the afternoon.", "VERB"],
  ["melt", "tan chảy", "The ice cream will melt in this heat.", "VERB"],
  ["stifling", "nóng bức đến ngộp thở", "The subway was stifling during rush hour.", "ADJECTIVE"],
  ["muggy", "nồm ẩm, oi bức", "August evenings here are muggy.", "ADJECTIVE"],
  ["humid", "ẩm cao", "Tropical climates are often humid.", "ADJECTIVE"],
  ["heatwave", "đợt nắng nóng kéo dài", "The heatwave lasted for two weeks."],
  ["shower", "cơn mưa rào ngắn", "We got caught in a sudden shower."],
  ["downpour", "mưa xối xả", "A heavy downpour flooded the streets."],
  ["torrential rain", "mưa như trút", "Torrential rain delayed the match.", "PHRASE"],
  ["overcast", "u ám, mây phủ kín", "The sky stayed overcast all day.", "ADJECTIVE"],
  ["drought", "hạn hán", "The drought damaged the harvest."],
  ["gale", "gió mạnh", "A gale blew tiles off the roof."],
  ["hurricane", "bão lớn vùng Đại Tây Dương", "The hurricane forced people to evacuate."],
  ["freeze", "đóng băng hoặc giá buốt", "Temperatures may freeze overnight.", "VERB"],
  ["scorching", "nóng cháy da", "It was a scorching afternoon by the beach.", "ADJECTIVE"],
  ["daytime temperature", "nhiệt độ ban ngày", "Daytime temperatures stayed mild.", "PHRASE"],
  ["late autumn", "cuối mùa thu", "Frost often appears in late autumn.", "PHRASE"],
  ["severe weather", "thời tiết khắc nghiệt", "Flights were cancelled due to severe weather.", "PHRASE"],
  ["boiling", "nóng như thiêu đốt", "It was boiling outside at noon.", "ADJECTIVE"],
  ["pour down", "mưa như trút", "It poured down all afternoon.", "VERB"],
  ["gentle breeze", "gió nhẹ dễ chịu", "A gentle breeze cooled the beach.", "PHRASE"],
  ["high wind", "gió mạnh", "A high wind knocked over the chairs.", "PHRASE"],
  ["tropical climate", "khí hậu nhiệt đới", "Singapore has a tropical climate.", "PHRASE"],
  ["icy roads", "đường đóng băng", "Drive carefully on icy roads.", "PHRASE"],
  ["keep warm", "giữ ấm", "Wear layers to keep warm.", "PHRASE"],
]);

const U7_WORDS = wordList([
  ["complexion", "nước da", "She has a clear complexion."],
  ["crew-cut", "kiểu tóc cắt rất ngắn", "He got a crew-cut before training camp."],
  ["freckles", "tàn nhang", "Her freckles show more in summer."],
  ["chubby", "bụ bẫm, hơi mũm mĩm", "The toddler has chubby cheeks.", "ADJECTIVE"],
  ["receding hair", "tóc hói dần ở trán", "He jokes about his receding hair.", "PHRASE"],
  ["wrinkles", "nếp nhăn", "Laugh lines left wrinkles around her eyes."],
  ["auburn", "nâu đỏ (tóc)", "She has long auburn hair.", "ADJECTIVE"],
  ["plump", "đầy đặn, múp míp", "The baby looks healthy and plump.", "ADJECTIVE"],
  ["stout", "đậm người, chắc nịch", "A stout man held the door open.", "ADJECTIVE"],
  ["stocky", "thấp đậm, chắc chắn", "The rugby player has a stocky build.", "ADJECTIVE"],
  ["muscular", "cơ bắp", "Years of training made him muscular.", "ADJECTIVE"],
  ["obese", "béo phì", "Obese patients need medical support.", "ADJECTIVE"],
  ["slim", "thon thả", "She stayed slim through swimming.", "ADJECTIVE"],
  ["skinny", "gầy tong teo", "He looked skinny after the illness.", "ADJECTIVE"],
  ["stunning", "đẹp đến ngỡ ngàng", "She looked stunning in that dress.", "ADJECTIVE"],
  ["scruffy", "bề bộn, xuề xòa", "He arrived looking scruffy after the hike.", "ADJECTIVE"],
  ["elegant", "thanh lịch", "Her elegant coat suited the occasion.", "ADJECTIVE"],
  ["well-built", "vạm vỡ, dáng chắc", "The security guard was tall and well-built.", "ADJECTIVE"],
  ["thin-faced", "mặt thon", "She is thin-faced with sharp cheekbones.", "ADJECTIVE"],
  ["round-faced", "mặt tròn", "The baby is round-faced and cheerful.", "ADJECTIVE"],
  ["ginger-haired", "tóc đỏ hung", "A ginger-haired boy waved at us.", "ADJECTIVE"],
  ["first impressions", "ấn tượng đầu tiên", "First impressions matter in interviews.", "PHRASE"],
  ["best feature", "điểm đẹp nhất trên khuôn mặt", "Her eyes are her best feature.", "PHRASE"],
  ["get a tan", "rám nắng", "She likes to get a tan in summer.", "PHRASE"],
  ["sunburnt", "bị cháy nắng", "He got sunburnt at the beach.", "ADJECTIVE"],
]);

const U8_WORDS = wordList([
  ["shrewd", "tinh khôn, sắc sảo", "She made a shrewd business decision.", "ADJECTIVE"],
  ["gifted", "có năng khiếu", "He is a gifted pianist.", "ADJECTIVE"],
  ["cunning", "láu cá, mánh khóe", "The fox is often described as cunning.", "ADJECTIVE"],
  ["crafty", "khéo tính toán, xảo quyệt", "That was a crafty way to avoid the question.", "ADJECTIVE"],
  ["pessimistic", "bi quan", "Don't be so pessimistic about the exam.", "ADJECTIVE"],
  ["optimistic", "lạc quan", "She stays optimistic even under pressure.", "ADJECTIVE"],
  ["extroverted", "hướng ngoại", "Extroverted students enjoy group work.", "ADJECTIVE"],
  ["introverted", "hướng nội", "He is quiet and rather introverted.", "ADJECTIVE"],
  ["sensible", "khôn ngoan, thực tế", "Wearing a coat was a sensible choice.", "ADJECTIVE"],
  ["sensitive", "nhạy cảm", "Be careful — she is very sensitive.", "ADJECTIVE"],
  ["gregarious", "thích giao du, hòa đồng", "Gregarious people love busy parties.", "ADJECTIVE"],
  ["quarrelsome", "hay cãi vã", "His quarrelsome attitude caused tension.", "ADJECTIVE"],
  ["easy-going", "dễ tính, thoải mái", "Our new manager is friendly and easy-going.", "ADJECTIVE"],
  ["trustworthy", "đáng tin cậy", "She needs a trustworthy assistant.", "ADJECTIVE"],
  ["thrifty", "chi tiêu tiết kiệm", "Thrifty shoppers wait for sales.", "ADJECTIVE"],
  ["stingy", "keo kiệt", "Don't be stingy with the tip.", "ADJECTIVE"],
  ["obstinate", "bướng bỉnh, cứng đầu", "The obstinate child refused to apologise.", "ADJECTIVE"],
  ["inquisitive", "tò mò, hay hỏi", "Inquisitive learners ask better questions.", "ADJECTIVE"],
  ["assertive", "quả quyết, biết bày tỏ", "Be assertive, but stay polite.", "ADJECTIVE"],
  ["naive", "ngây thơ, cả tin", "It was naive to trust that email.", "ADJECTIVE"],
]);

const U9_WORDS = wordList([
  ["heart of gold", "rất tốt bụng", "Despite his tough look, he has a heart of gold.", "IDIOM"],
  ["as hard as nails", "cứng rắn, không dễ lung lay", "The coach is as hard as nails in training.", "IDIOM"],
  ["as good as gold", "ngoan / dễ bảo", "The kids were as good as gold all afternoon.", "IDIOM"],
  ["heart's in the right place", "ý tốt, tấm lòng đúng chỗ", "He can be clumsy, but his heart's in the right place.", "IDIOM"],
  ["pain in the neck", "đồ phiền phức", "This paperwork is a real pain in the neck.", "IDIOM"],
  ["get on everyone's nerves", "làm ai cũng khó chịu", "His constant humming gets on everyone's nerves.", "IDIOM"],
  ["head screwed on", "biết suy nghĩ chín chắn", "She's young but has her head screwed on.", "IDIOM"],
  ["head like a sieve", "hay quên", "I have a head like a sieve with names.", "IDIOM"],
  ["head in the clouds", "mơ mộng, không thực tế", "Stop walking with your head in the clouds.", "IDIOM"],
  ["bury your head in the sand", "tránh đối mặt vấn đề", "You can't bury your head in the sand forever.", "IDIOM"],
  ["keep your head", "giữ bình tĩnh", "Keep your head in an emergency.", "IDIOM"],
  ["odd-ball", "người lập dị", "He's a bit of an odd-ball, but harmless."],
  ["over the top", "quá lố, thái quá", "The decoration was a bit over the top.", "IDIOM"],
  ["teacher's pet", "học trò được thầy cô cưng", "Nobody wants to be called the teacher's pet."],
  ["know-all", "kẻ hay khoe là biết hết", "Don't act like a know-all in meetings."],
  ["lazy-bones", "đồ lười biếng", "Get up, lazy-bones — breakfast is ready."],
  ["down to earth", "thực tế, chân chất", "I like managers who are down to earth.", "IDIOM"],
  ["two-faced", "hai mặt, giả tạo", "She felt betrayed by her two-faced colleague.", "ADJECTIVE"],
]);

const U10_WORDS = wordList([
  ["casual acquaintance", "người quen sơ sơ", "He's only a casual acquaintance from the gym.", "PHRASE"],
  ["housemate", "bạn cùng nhà", "My housemate cooks dinner twice a week."],
  ["steady relationship", "mối quan hệ nghiêm túc, ổn định", "They have been in a steady relationship for years.", "PHRASE"],
  ["partner", "bạn đời", "I'd like you to meet my partner."],
  ["parents-in-law", "bố mẹ chồng hoặc bố mẹ vợ", "We visit my parents-in-law every Sunday."],
  ["colleague", "đồng nghiệp", "A colleague covered my shift yesterday."],
  ["unfriend", "hủy kết bạn (mạng xã hội)", "I decided to unfriend him after the argument.", "VERB"],
  ["idolise", "thần tượng hóa", "Teenagers often idolise pop stars.", "VERB"],
  ["can't stand", "không chịu nổi", "I can't stand people who talk through films.", "PHRASE"],
  ["loathe", "ghét cay ghét đắng", "She loathes waking up before dawn.", "VERB"],
  ["look up to", "ngưỡng mộ, noi gương", "I look up to my older sister.", "VERB"],
  ["look down on", "coi thường", "Don't look down on people with less money.", "VERB"],
  ["fancy", "thích (ai đó) theo kiểu tình cảm", "Do you think he fancies her?", "VERB"],
  ["get on well", "hợp nhau, chơi thân", "We get on well despite our differences.", "PHRASE"],
  ["see eye to eye", "đồng quan điểm", "They rarely see eye to eye on politics.", "IDIOM"],
  ["fall out with", "cãi nhau đến lạnh nhạt", "She fell out with her best friend last year.", "VERB"],
  ["make it up", "làm lành sau cãi vã", "They argued, then made it up the next day.", "PHRASE"],
  ["have an affair", "ngoại tình", "Rumours said he had an affair.", "PHRASE"],
  ["get together", "tụ họp hoặc bắt đầu hẹn hò", "Shall we get together this weekend?", "VERB"],
]);

const U11_WORDS = wordList([
  ["bungalow", "nhà một tầng", "They retired to a quiet bungalow by the sea."],
  ["cottage", "nhà nhỏ kiểu thôn quê", "We rented a stone cottage for the weekend."],
  ["studio flat", "căn hộ studio (một không gian mở)", "A studio flat is cheaper in the city centre."],
  ["villa", "biệt thự", "The family spent August in a villa in Italy."],
  ["self-contained flat", "căn hộ khép kín (có bếp, WC riêng)", "Students prefer a self-contained flat.", "PHRASE"],
  ["terraced house", "nhà liền kề trong dãy", "They bought a terraced house near the station."],
  ["semi-detached", "nhà đôi (dính một bên tường)", "Semi-detached homes are common in suburbs.", "ADJECTIVE"],
  ["utility room", "phòng để máy giặt / đồ tiện ích", "The washing machine is in the utility room."],
  ["attic", "gác mái", "Old photos were stored in the attic."],
  ["loft", "gác xép, tầng áp mái", "They converted the loft into a bedroom."],
  ["cellar", "hầm dưới đất", "Wine is kept cool in the cellar."],
  ["basement", "tầng hầm", "The gym is in the basement."],
  ["landing", "khoảng sàn trước cầu thang", "Leave the boxes on the landing."],
  ["porch", "hiên trước nhà", "She waited for the taxi on the porch."],
  ["patio", "sân nhỏ lát gạch ngoài trời", "We had breakfast on the patio."],
  ["drive", "lối xe vào nhà", "Park on the drive, not on the pavement."],
  ["remote control", "điều khiển từ xa", "Where did you put the remote control?"],
  ["corkscrew", "dụng cụ mở nút rượu", "I can't open this bottle without a corkscrew."],
]);

const U12_WORDS = wordList([
  ["leak", "chỗ rò rỉ", "There's a leak under the kitchen sink."],
  ["smash", "đập vỡ tan", "He smashed a glass by accident.", "VERB"],
  ["crack", "vết nứt", "There's a crack in the windscreen."],
  ["chip", "mẻ (cốc, bát, men sứ)", "This mug has a chip on the rim."],
  ["power cut", "mất điện", "A power cut stopped the meeting.", "PHRASE"],
  ["break down", "hỏng hoặc chết máy", "Our car broke down on the motorway.", "VERB"],
  ["crash", "sập máy (máy tính)", "My laptop crashed before I saved the file.", "VERB"],
  ["twist", "bong gân", "She twisted her ankle on the stairs.", "VERB"],
  ["bruise", "vết bầm", "He got a bruise on his knee."],
  ["graze", "xước da nhẹ", "The child grazed her elbow on the pavement.", "VERB"],
  ["trip", "vấp ngã", "Don't trip over the cable.", "VERB"],
  ["mislay", "để thất lạc (tạm thời)", "I've mislaid my glasses again.", "VERB"],
  ["spill", "làm đổ (chất lỏng)", "Careful — don't spill the coffee.", "VERB"],
  ["stain", "vết bẩn khó tẩy", "Red wine left a stain on the carpet."],
  ["blocked", "bị tắc", "The drain is blocked again.", "ADJECTIVE"],
  ["dent", "vết lõm (xe, đồ kim loại)", "There's a dent in the car door."],
  ["lock oneself out", "tự khóa trái ngoài nhà", "I locked myself out without my keys.", "PHRASE"],
  ["flat battery", "pin hoặc ắc quy hết điện", "The remote won't work — flat battery.", "PHRASE"],
  ["run out", "hết (pin, vật liệu)", "The batteries have run out.", "VERB"],
  ["dead batteries", "pin hết điện", "These are dead batteries.", "PHRASE"],
  ["leave a stain", "để lại vết bẩn", "Coffee may leave a stain.", "PHRASE"],
  ["software problem", "lỗi phần mềm", "It could be a software problem.", "PHRASE"],
  ["nothing serious", "không có gì nghiêm trọng", "I hope it's nothing serious.", "PHRASE"],
]);

const U13_WORDS = wordList([
  ["earthquake", "động đất", "The earthquake shook buildings across the city."],
  ["drought", "hạn hán", "Crops failed because of the drought."],
  ["famine", "nạn đói", "Aid agencies rushed food during the famine."],
  ["landslide", "sạt lở đất", "Heavy rain triggered a landslide."],
  ["epidemic", "dịch bệnh lan rộng", "An epidemic of flu hit the region."],
  ["erupt", "phun trào (núi lửa)", "The volcano could erupt without much warning.", "VERB"],
  ["casualty", "thương vong", "There were dozens of casualties after the crash."],
  ["survivor", "người sống sót", "Survivors were airlifted to hospital."],
  ["refugee", "người tị nạn", "Refugees crossed the border seeking safety."],
  ["migrant", "người di cư", "Migrant workers send money home."],
  ["wounded", "bị thương", "Medics treated the wounded at the scene.", "ADJECTIVE"],
  ["natural disaster", "thiên tai", "Insurance rarely covers every natural disaster.", "PHRASE"],
  ["civil war", "nội chiến", "The civil war lasted for years."],
  ["malaria", "sốt rét", "Mosquito nets help prevent malaria."],
  ["cholera", "bệnh tả", "Dirty water can spread cholera."],
  ["injure", "làm bị thương (người)", "Falling debris injured three people.", "VERB"],
  ["outbreak", "đợt bùng phát dịch", "Officials feared a new outbreak."],
  ["evacuate", "sơ tán", "Residents were told to evacuate immediately.", "VERB"],
  ["tornado", "lốc xoáy", "A tornado damaged several homes."],
  ["typhoon", "bão nhiệt đới vùng Tây Thái Bình Dương", "The typhoon closed the airport."],
  ["volcano", "núi lửa", "Ash covered villages near the volcano."],
  ["aid agency", "tổ chức cứu trợ", "Aid agencies delivered food overnight.", "PHRASE"],
  ["contaminated", "bị nhiễm bẩn", "Avoid contaminated water.", "ADJECTIVE"],
  ["tropical storm", "bão nhiệt đới", "A tropical storm hit the coast.", "PHRASE"],
]);

const U14_WORDS = wordList([
  ["crèche", "nhà trẻ cho trẻ rất nhỏ", "The company offers a workplace crèche."],
  ["nursery school", "trường mẫu giáo", "She started nursery school at three."],
  ["comprehensive school", "trường phổ thông công lập không tuyển chọn (Anh)", "Most local children attend a comprehensive school."],
  ["grammar school", "trường trung học tuyển chọn (Anh)", "He passed the exam for a grammar school."],
  ["public school", "trường tư danh tiếng kiểu Anh", "In the UK, a public school is actually private."],
  ["sixth-form college", "trường dự bị A-level (sau THPT)", "She moved to a sixth-form college at 16."],
  ["compulsory", "bắt buộc", "Maths is compulsory until sixteen.", "ADJECTIVE"],
  ["resit", "thi lại", "He has to resit the chemistry exam.", "VERB"],
  ["skip classes", "trốn học", "Students who skip classes fall behind.", "PHRASE"],
  ["blended learning", "học kết hợp online và offline", "Blended learning became common after the pandemic.", "PHRASE"],
  ["distance learning", "học từ xa", "Distance learning suits people who work full-time.", "PHRASE"],
  ["module", "học phần", "This course has eight modules."],
  ["submit", "nộp (bài, hồ sơ)", "Please submit your essay by Friday.", "VERB"],
  ["school-leaving age", "tuổi được nghỉ học chính thức", "The school-leaving age is sixteen in many places.", "PHRASE"],
  ["curriculum", "chương trình giảng dạy", "They updated the national curriculum."],
  ["vocational", "hướng nghề nghiệp", "She chose a vocational training course.", "ADJECTIVE"],
  ["truancy", "việc trốn học thường xuyên", "The school is cracking down on truancy."],
  ["continuous assessment", "đánh giá liên tục trong khóa", "Grades include continuous assessment, not only exams.", "PHRASE"],
]);

const U15_WORDS = wordList([
  ["undergraduate", "sinh viên đại học chưa tốt nghiệp", "Undergraduates live mostly on campus."],
  ["bachelor's degree", "bằng cử nhân", "She earned a bachelor's degree in economics."],
  ["postgraduate", "sau đại học", "He started a postgraduate course in law.", "ADJECTIVE"],
  ["master's degree", "bằng thạc sĩ", "A master's degree can improve job prospects."],
  ["PhD", "tiến sĩ", "She is doing a PhD in climate science."],
  ["credit", "tín chỉ", "You need 120 credits to graduate."],
  ["dissertation", "luận văn tốt nghiệp", "Writing the dissertation took all summer."],
  ["thesis", "luận án", "His thesis focuses on renewable energy."],
  ["lecture theatre", "giảng đường lớn", "The lecture theatre was packed."],
  ["seminar", "buổi thảo luận nhóm nhỏ", "We prepare readings before each seminar."],
  ["tutorial", "buổi hướng dẫn với giảng viên", "Her tutor explained the feedback in a tutorial."],
  ["halls of residence", "ký túc xá sinh viên", "First-years often live in halls of residence.", "PHRASE"],
  ["tuition fees", "học phí", "Tuition fees rose again this year.", "PHRASE"],
  ["student loan", "khoản vay sinh viên", "Many graduates still repay a student loan."],
  ["scholarship", "học bổng", "She won a scholarship for academic excellence."],
  ["admissions", "tuyển sinh", "Admissions open in October."],
  ["entry requirements", "điều kiện đầu vào", "Check the entry requirements before you apply.", "PHRASE"],
  ["campus", "khuôn viên trường", "The campus has a new library."],
  ["specialise", "chuyên sâu về một lĩnh vực", "He specialised in marine biology.", "VERB"],
  ["academic staff", "đội ngũ giảng viên", "Academic staff hold weekly office hours.", "PHRASE"],
  ["tutor", "giảng viên hướng dẫn nhóm nhỏ", "My tutor marked the essay carefully."],
  ["student union", "hội sinh viên", "Join a club through the student union.", "PHRASE"],
  ["funding", "nguồn tài trợ học tập", "Funding is limited this year."],
  ["lecturer", "giảng viên đại học", "The lecturer paused for questions."],
  ["halls", "ký túc xá (cách gọi tắt)", "Most first-years live in halls."],
]);

const U16_WORDS = wordList([
  ["executive", "nhân sự cấp điều hành", "Senior executives met to discuss strategy."],
  ["skilled worker", "lao động có tay nghề", "The factory needs more skilled workers.", "PHRASE"],
  ["unskilled worker", "lao động phổ thông, ít tay nghề", "Unskilled workers often earn lower wages.", "PHRASE"],
  ["supervisor", "người giám sát", "Report any safety issues to your supervisor."],
  ["make a living", "kiếm sống", "It's hard to make a living as an artist.", "PHRASE"],
  ["shiftwork", "làm việc theo ca", "Shiftwork can disrupt your sleep."],
  ["flexi-time", "giờ làm linh hoạt", "Flexi-time helps parents manage childcare."],
  ["nine-to-five", "làm giờ hành chính cố định", "She's tired of a rigid nine-to-five job.", "PHRASE"],
  ["get the sack", "bị sa thải", "He got the sack for repeated lateness.", "IDIOM"],
  ["made redundant", "bị cắt giảm nhân sự", "Hundreds were made redundant after the merger.", "PHRASE"],
  ["maternity leave", "nghỉ thai sản", "She starts maternity leave next month.", "PHRASE"],
  ["sick leave", "nghỉ ốm", "He took sick leave for a week.", "PHRASE"],
  ["workaholic", "người nghiện làm việc", "Being a workaholic can harm your health."],
  ["be promoted", "được thăng chức", "She was promoted to team leader.", "VERB"],
  ["apply for a job", "ứng tuyển một công việc", "I applied for a job in marketing.", "PHRASE"],
  ["overtime", "làm thêm giờ", "Staff get paid for overtime on weekends."],
  ["resign", "xin thôi việc", "He resigned to start his own company.", "VERB"],
  ["job security", "sự ổn định công việc", "Public sector jobs often offer better job security.", "PHRASE"],
]);

const U17_WORDS = wordList([
  ["business plan", "kế hoạch kinh doanh", "Investors asked to see a clear business plan."],
  ["custom-built", "làm theo yêu cầu riêng", "They ordered a custom-built kitchen.", "ADJECTIVE"],
  ["launch", "ra mắt (sản phẩm)", "The company will launch the app in May.", "VERB"],
  ["roll out", "triển khai rộng", "They plan to roll out the service nationwide.", "VERB"],
  ["manufacture", "sản xuất (hàng hóa)", "The firm manufactures electric bikes.", "VERB"],
  ["customer care", "chăm sóc khách hàng", "Good customer care builds loyalty.", "PHRASE"],
  ["market research", "nghiên cứu thị trường", "Market research showed strong demand.", "PHRASE"],
  ["recession", "suy thoái kinh tế", "Hiring slowed during the recession."],
  ["potential customer", "khách hàng tiềm năng", "Sales staff called potential customers.", "PHRASE"],
  ["order books", "sổ đơn hàng đang chờ xử lý", "Full order books suggest a busy quarter.", "PHRASE"],
  ["stiff competition", "cạnh tranh gay gắt", "There is stiff competition in online retail.", "PHRASE"],
  ["feedback", "phản hồi", "We use customer feedback to improve the product."],
  ["CEO", "giám đốc điều hành", "The CEO announced record profits."],
  ["corporation", "tập đoàn lớn", "Multinational corporations operate worldwide."],
  ["make a profit", "có lãi", "The café finally made a profit last year.", "PHRASE"],
  ["access new markets", "tiếp cận thị trường mới", "Exports help firms access new markets.", "PHRASE"],
  ["turnover", "doanh thu", "Annual turnover rose by 12 percent."],
  ["negotiate", "thương lượng", "We negotiated a better price with the supplier.", "VERB"],
]);

const U18_WORDS = wordList([
  ["hang-gliding", "môn dù lượn", "Hang-gliding looks thrilling from the cliff."],
  ["fencing", "môn đấu kiếm", "She took up fencing at university."],
  ["archery", "môn bắn cung", "Archery requires a steady hand."],
  ["snooker", "bi-a snooker", "They watched a snooker final on TV."],
  ["scuba diving", "lặn bình khí", "Scuba diving lets you explore coral reefs.", "PHRASE"],
  ["racket", "vợt (tennis, badminton...)", "I need to restring my tennis racket."],
  ["cue", "gậy bi-a", "He chalked the cue before the shot."],
  ["javelin", "môn / cây lao", "She threw the javelin over fifty metres."],
  ["pole vault", "nhảy sào", "He broke the school record in the pole vault."],
  ["sprinter", "vận động viên chạy nước rút", "The sprinter won the 100 metres."],
  ["qualify", "giành vé vào vòng tiếp", "They need one more win to qualify.", "VERB"],
  ["knock out", "loại (đối thủ) khỏi giải", "The underdogs knocked out the champions.", "VERB"],
  ["semi-final", "bán kết", "The semi-final will be played on Saturday."],
  ["trophy", "cúp / giải thưởng", "The team lifted the trophy after extra time."],
  ["spectator", "khán giả tại sân", "Spectators cheered when the goal went in."],
  ["breaststroke", "kiểu bơi ếch", "Breaststroke is her strongest stroke."],
  ["umpire", "trọng tài (tennis, cricket...)", "The umpire called a fault."],
  ["personal best", "thành tích cá nhân tốt nhất", "She ran a personal best in the marathon.", "PHRASE"],
]);

const U19_WORDS = wordList([
  ["the arts", "các môn nghệ thuật nói chung", "Funding for the arts has been cut.", "PHRASE"],
  ["fine art", "mỹ thuật (hội họa, điêu khắc...)", "She studied fine art at college.", "PHRASE"],
  ["sculpture", "tác phẩm điêu khắc", "A bronze sculpture stands in the square."],
  ["ceramics", "đồ gốm sứ nghệ thuật", "The gallery has a ceramics exhibition."],
  ["work of art", "tác phẩm nghệ thuật", "That mural is a true work of art.", "PHRASE"],
  ["abstract painting", "tranh trừu tượng", "I prefer abstract painting to realism.", "PHRASE"],
  ["portrait", "chân dung", "He commissioned a portrait of his mother."],
  ["landscape", "tranh phong cảnh", "Turner is famous for dramatic landscapes."],
  ["still life", "tĩnh vật", "Students practised drawing a still life.", "PHRASE"],
  ["novelist", "nhà văn tiểu thuyết", "The novelist signed books after the talk."],
  ["bestseller", "sách bán chạy", "Her debut novel became a bestseller."],
  ["plot", "cốt truyện", "The plot twists in the final chapter."],
  ["character", "nhân vật", "The main character is complex and flawed."],
  ["critic", "nhà phê bình", "Critics praised the director's latest film."],
  ["literary", "thuộc văn học", "She won a literary prize last year.", "ADJECTIVE"],
  ["publication", "ấn phẩm / việc xuất bản", "The publication of his memoirs caused debate."],
  ["extract", "đoạn trích", "We read an extract from chapter three."],
  ["arts and crafts", "thủ công mỹ nghệ", "The market sells local arts and crafts.", "PHRASE"],
]);

export const EVIU_UPPER_UNITS_05_19: VocabularyUnit[] = [
  upperUnit(5, {
    introVi:
      "Unit 5 giúp bạn nói về quốc gia, quốc tịch và ngôn ngữ ở mức B2: không chỉ tên nước mà còn vùng miền, nhóm dân tộc và tình trạng song ngữ. Bạn sẽ phân biệt được các cách gọi người và ngôn ngữ tự nhiên hơn trong giao tiếp quốc tế.",
    structureSections: [
      { label: "Countries and nationalities", wordCount: 6 },
      { label: "Languages and dialects", wordCount: 6 },
      { label: "Regions and ethnic identity", wordCount: 6 },
    ],
    collocationHtml: `${purple("mother tongue")}, ${purple("ethnic group")} và ${purple("bilingual speaker")} là các cụm then chốt khi nói về bản sắc ngôn ngữ.`,
    mistakeHtml: `Đừng nhầm ${bold("the Netherlands")} (tên nước) với ${bold("Dutch")} (quốc tịch/ngôn ngữ). Cũng phân biệt ${bold("dialect")} (phương ngữ) và ${bold("language")} (ngôn ngữ).`,
    principles: [
      {
        title: "Gọi người và nước đúng dạng",
        body: `Học theo cặp: tên nước ↔ người/quốc tịch, ví dụ ${purple("the Netherlands")} → ${purple("Dutch")}, ${purple("Cyprus")} → ${purple("Cypriot")}.`,
        examples: [
          ex("She is a Briton living in the Netherlands.", "Cô ấy là người Anh đang sống ở Hà Lan."),
          ex("He is Cypriot, but his family is Greek-speaking.", "Anh ấy là người Síp, nhưng gia đình nói tiếng Hy Lạp."),
        ],
      },
      {
        title: "Mô tả năng lực ngôn ngữ chính xác",
        body: `${purple("monolingual")}, ${purple("bilingual")} và ${purple("multilingual")} mô tả số ngôn ngữ; ${purple("mother tongue")} và ${purple("dialect")} mô tả nền tảng dùng ngôn ngữ.`,
        examples: [
          ex("She is bilingual in Catalan and Spanish.", "Cô ấy nói được cả tiếng Catalan và tiếng Tây Ban Nha."),
          ex("Flemish is closely related to Dutch.", "Tiếng Flemish có quan hệ gần với tiếng Hà Lan."),
        ],
      },
      {
        title: "Nói về vùng và bản sắc dân tộc",
        body: `Dùng ${purple("Far East")}, ${purple("Middle East")}, ${purple("Latin American")} và ${purple("ethnic group")} khi cần khung địa lý hoặc bản sắc, không gắn nhãn thô.`,
        examples: [
          ex("Many Latin American countries share cultural ties.", "Nhiều nước Mỹ Latinh có mối liên hệ văn hóa chung."),
          ex("African-Caribbean communities have a rich cultural heritage.", "Các cộng đồng Phi-Caribbean có di sản văn hóa phong phú."),
        ],
      },
    ],
    words: U5_WORDS,
    exercises: [
      mcq(
        5,
        1,
        "Từ nào chỉ ngôn ngữ mẹ đẻ của một người?",
        [
          { key: "a", label: "dialect" },
          { key: "b", label: "mother tongue" },
          { key: "c", label: "official language" },
          { key: "d", label: "accent" },
        ],
        "b",
      ),
      fillBlank(
        5,
        2,
        "Someone who speaks two languages fluently is ____.",
        "bilingual",
        [
          { key: "a", label: "monolingual" },
          { key: "b", label: "bilingual" },
          { key: "c", label: "ethnic" },
          { key: "d", label: "regional" },
        ],
        "b",
      ),
      mcq(
        5,
        3,
        "Người từ Hà Lan thường được gọi là gì?",
        [
          { key: "a", label: "Dutch" },
          { key: "b", label: "Danish" },
          { key: "c", label: "Deutsch" },
          { key: "d", label: "Flemish" },
        ],
        "a",
      ),
      fillBlank(
        5,
        4,
        "A local form of a language is called a ____.",
        "dialect",
        [
          { key: "a", label: "dialect" },
          { key: "b", label: "nationality" },
          { key: "c", label: "passport" },
          { key: "d", label: "border" },
        ],
        "a",
      ),
      mcq(
        5,
        5,
        "Cụm nào chỉ nhóm người có chung nguồn gốc văn hóa hoặc dân tộc?",
        [
          { key: "a", label: "Far East" },
          { key: "b", label: "ethnic group" },
          { key: "c", label: "mother tongue" },
          { key: "d", label: "official language" },
        ],
        "b",
      ),
      fillBlank(
        5,
        6,
        "She speaks Catalan, Spanish and English, so she is ____.",
        "multilingual",
        [
          { key: "a", label: "monolingual" },
          { key: "b", label: "multilingual" },
          { key: "c", label: "silent" },
          { key: "d", label: "native only" },
        ],
        "b",
      ),
      mcq(
        5,
        7,
        "\"Briton\" dùng để chỉ người đến từ đâu?",
        [
          { key: "a", label: "Britain" },
          { key: "b", label: "Brittany" },
          { key: "c", label: "Brazil" },
          { key: "d", label: "Belgium" },
        ],
        "a",
      ),
    ],
  }),

  upperUnit(6, {
    introVi:
      "Unit 6 nâng cấp vốn từ thời tiết vượt mức sunny/rainy: bạn mô tả được nóng bức ngột ngạt, mưa xối xả, sương giá tan và bão mạnh. Đây là bộ từ rất hay gặp trong tin tức và hội thoại đời thường.",
    structureSections: [
      { label: "Heat and humidity", wordCount: 6 },
      { label: "Rain and storms", wordCount: 6 },
      { label: "Cold, ice and extremes", wordCount: 6 },
    ],
    collocationHtml: `${purple("torrential rain")}, ${purple("heatwave")} và ${purple("overcast sky")} giúp mô tả thời tiết sống động hơn nhiều so với từ cơ bản.`,
    mistakeHtml: `Phân biệt ${bold("damp")} (ẩm nhẹ) và ${bold("humid")} (ẩm nóng khó chịu); ${bold("shower")} (mưa rào ngắn) khác ${bold("downpour")} / ${bold("torrential rain")} (mưa rất to).`,
    principles: [
      {
        title: "Chọn từ theo mức độ, không chỉ loại thời tiết",
        body: `${purple("muggy")} và ${purple("stifling")} đều nóng ẩm, nhưng stifling nhấn mạnh cảm giác ngộp thở hơn.`,
        examples: [
          ex("The air was stifling in the crowded train.", "Không khí trong tàu đông nghịt ngộp đến nghẹt thở."),
          ex("It feels muggy before the storm.", "Trời oi bức khó chịu trước khi bão tới."),
        ],
      },
      {
        title: "Mưa và gió cần collocation đúng",
        body: `Học theo cụm: ${purple("torrential rain")}, ${purple("heavy shower")}, ${purple("strong gale")} thay vì dịch từng từ.`,
        examples: [
          ex("Torrential rain flooded the streets.", "Mưa xối xả làm ngập đường phố."),
          ex("A gale damaged several roofs overnight.", "Một trận gió mạnh làm hỏng vài mái nhà trong đêm."),
        ],
      },
      {
        title: "Nói về lạnh và biến đổi trạng thái",
        body: `${purple("frost")}, ${purple("freeze")}, ${purple("thaw")} và ${purple("melt")} thường đi cùng khi mô tả chu kỳ lạnh–ấm.`,
        examples: [
          ex("The frost will thaw by midday.", "Sương giá sẽ tan vào giữa trưa."),
          ex("The snow began to melt in the sun.", "Tuyết bắt đầu tan dưới nắng."),
        ],
      },
    ],
    words: U6_WORDS,
    exercises: [
      mcq(
        6,
        1,
        "Từ nào mô tả thời tiết nóng ẩm đến mức khó thở?",
        [
          { key: "a", label: "misty" },
          { key: "b", label: "stifling" },
          { key: "c", label: "frosty" },
          { key: "d", label: "overcast" },
        ],
        "b",
      ),
      fillBlank(
        6,
        2,
        "We stayed indoors during the ____; the rain was extremely heavy.",
        "downpour",
        [
          { key: "a", label: "drought" },
          { key: "b", label: "downpour" },
          { key: "c", label: "heatwave" },
          { key: "d", label: "thaw" },
        ],
        "b",
      ),
      mcq(
        6,
        3,
        "\"Heatwave\" nghĩa là gì?",
        [
          { key: "a", label: "Một đợt lạnh bất thường" },
          { key: "b", label: "Một đợt nắng nóng kéo dài" },
          { key: "c", label: "Một trận mưa ngắn" },
          { key: "d", label: "Một cơn bão tuyết" },
        ],
        "b",
      ),
      fillBlank(
        6,
        4,
        "The sky was completely ____, so we knew it might rain.",
        "overcast",
        [
          { key: "a", label: "overcast" },
          { key: "b", label: "frozen" },
          { key: "c", label: "gale" },
          { key: "d", label: "melted" },
        ],
        "a",
      ),
      mcq(
        6,
        5,
        "Tình trạng thiếu mưa kéo dài gây khô hạn gọi là gì?",
        [
          { key: "a", label: "drought" },
          { key: "b", label: "shower" },
          { key: "c", label: "thaw" },
          { key: "d", label: "mist" },
        ],
        "a",
      ),
      fillBlank(
        6,
        6,
        "After the cold night, there was white ____ on the grass.",
        "frost",
        [
          { key: "a", label: "gale" },
          { key: "b", label: "frost" },
          { key: "c", label: "humidity" },
          { key: "d", label: "heatwave" },
        ],
        "b",
      ),
      mcq(
        6,
        7,
        "Cơn mưa rất mạnh, xối xả thường được gọi là gì?",
        [
          { key: "a", label: "light shower" },
          { key: "b", label: "torrential rain" },
          { key: "c", label: "gentle drizzle" },
          { key: "d", label: "sea breeze" },
        ],
        "b",
      ),
      fillBlank(
        6,
        8,
        "The ice will ____ when the temperature rises.",
        "melt",
        [
          { key: "a", label: "freeze" },
          { key: "b", label: "melt" },
          { key: "c", label: "blow" },
          { key: "d", label: "pour" },
        ],
        "b",
      ),
    ],
  }),

  upperUnit(7, {
    introVi:
      "Unit 7 tập trung mô tả ngoại hình ở mức tinh tế hơn: nước da, kiểu tóc, vóc dáng và ấn tượng tổng thể. Bạn học cách dùng từ chính xác mà vẫn lịch sự khi nói về người khác.",
    structureSections: [
      { label: "Face, skin and hair", wordCount: 6 },
      { label: "Build and body shape", wordCount: 7 },
      { label: "Overall look and style", wordCount: 5 },
    ],
    collocationHtml: `${purple("receding hair")}, ${purple("well-built")} và ${purple("scruffy appearance")} là các cụm mô tả rất hay dùng ở trình độ này.`,
    mistakeHtml: `Phân biệt ${bold("slim")} (thon gọn, thường trung tính/tích cực) và ${bold("skinny")} (gầy quá, dễ mang sắc thái tiêu cực); ${bold("sensible")} thuộc tính cách, không dùng cho ngoại hình.`,
    principles: [
      {
        title: "Đi từ chi tiết khuôn mặt đến tổng thể",
        body: `Bắt đầu với ${purple("complexion")}, ${purple("freckles")}, tóc rồi mới đến vóc dáng như ${purple("stocky")} hay ${purple("muscular")}.`,
        examples: [
          ex("She has a fair complexion and freckles.", "Cô ấy da sáng và có tàn nhang."),
          ex("He has a crew-cut and a strong jawline.", "Anh ấy để tóc cắt ngắn kiểu lính và quai hàm rõ."),
        ],
      },
      {
        title: "Chọn từ vóc dáng có sắc thái phù hợp",
        body: `${purple("plump")}, ${purple("stout")}, ${purple("chubby")} và ${purple("obese")} khác nhau về mức độ và mức độ lịch sự; ưu tiên từ trung tính trong giao tiếp.`,
        examples: [
          ex("The baby has chubby cheeks.", "Em bé có đôi má bầu bĩnh."),
          ex("He looks stocky rather than tall and slim.", "Anh ấy trông chắc nịch chứ không cao gầy."),
        ],
      },
      {
        title: "Mô tả phong cách ăn mặc và ấn tượng",
        body: `${purple("elegant")}, ${purple("stunning")} và ${purple("scruffy")} giúp truyền tải ấn tượng tổng thể nhanh chóng.`,
        examples: [
          ex("She looked stunning in that dress.", "Cô ấy trông thật lộng lẫy trong chiếc váy đó."),
          ex("He arrived looking rather scruffy.", "Anh ấy đến trông hơi lôi thôi."),
        ],
      },
    ],
    words: U7_WORDS,
    exercises: [
      mcq(
        7,
        1,
        "\"Complexion\" chủ yếu nói về điều gì?",
        [
          { key: "a", label: "Nước da / làn da" },
          { key: "b", label: "Chiều cao" },
          { key: "c", label: "Giọng nói" },
          { key: "d", label: "Tính cách" },
        ],
        "a",
      ),
      fillBlank(
        7,
        2,
        "He has ____ hairline; you can see more of his forehead now.",
        "a receding",
        [
          { key: "a", label: "an auburn" },
          { key: "b", label: "a receding" },
          { key: "c", label: "a freckled" },
          { key: "d", label: "a stunning" },
        ],
        "b",
        ["receding", "a receding hairline"],
      ),
      mcq(
        7,
        3,
        "Từ nào thường mang sắc thái \"gầy quá\" hơn là khen?",
        [
          { key: "a", label: "slim" },
          { key: "b", label: "skinny" },
          { key: "c", label: "elegant" },
          { key: "d", label: "well-built" },
        ],
        "b",
      ),
      fillBlank(
        7,
        4,
        "After years in the sun, she has small ____ around her eyes.",
        "wrinkles",
        [
          { key: "a", label: "freckles" },
          { key: "b", label: "wrinkles" },
          { key: "c", label: "crew-cuts" },
          { key: "d", label: "porches" },
        ],
        "b",
      ),
      mcq(
        7,
        5,
        "Ai đó \"well-built\" thường được hiểu là gì?",
        [
          { key: "a", label: "Thân hình chắc chắn, vạm vỡ" },
          { key: "b", label: "Rất gầy" },
          { key: "c", label: "Mặc đồ đắt tiền" },
          { key: "d", label: "Có nhiều tàn nhang" },
        ],
        "a",
      ),
      fillBlank(
        7,
        6,
        "Her hair is a rich ____ colour, almost red-brown.",
        "auburn",
        [
          { key: "a", label: "auburn" },
          { key: "b", label: "scruffy" },
          { key: "c", label: "stocky" },
          { key: "d", label: "plump" },
        ],
        "a",
      ),
      mcq(
        7,
        7,
        "Từ nào mô tả vẻ ngoài lịch sự, thanh lịch?",
        [
          { key: "a", label: "scruffy" },
          { key: "b", label: "elegant" },
          { key: "c", label: "chubby" },
          { key: "d", label: "obese" },
        ],
        "b",
      ),
    ],
  }),

  upperUnit(8, {
    introVi:
      "Unit 8 mở rộng vốn từ tính cách ở mức B2: từ thông minh sắc sảo đến hướng ngoại/hướng nội, tiết kiệm hay keo kiệt. Bạn sẽ nhận xét người khác chính xác hơn mà vẫn giữ sắc thái phù hợp.",
    structureSections: [
      { label: "Mind and ability", wordCount: 6 },
      { label: "Social personality", wordCount: 7 },
      { label: "Attitude and habits", wordCount: 5 },
    ],
    collocationHtml: `${purple("shrewd decision")}, ${purple("gregarious person")} và ${purple("assertive communication")} là các kết hợp hay gặp trong học thuật và công sở.`,
    mistakeHtml: `Đừng nhầm ${bold("sensible")} (biết điều, thực tế) với ${bold("sensitive")} (nhạy cảm); ${bold("thrifty")} (tiết kiệm khôn ngoan) khác ${bold("stingy")} (keo kiệt).`,
    principles: [
      {
        title: "Phân biệt các cặp từ dễ nhầm",
        body: `${purple("sensible")} ≠ ${purple("sensitive")}; ${purple("cunning")}/${purple("crafty")} mang sắc thái \"khéo léo theo hướng mánh khóe\" hơn ${purple("shrewd")}.`,
        examples: [
          ex("It was a sensible choice to leave early.", "Rời đi sớm là quyết định hợp lý."),
          ex("She's sensitive to criticism.", "Cô ấy khá nhạy cảm với lời phê bình."),
        ],
      },
      {
        title: "Mô tả phong cách giao tiếp xã hội",
        body: `${purple("extroverted")}, ${purple("introverted")}, ${purple("gregarious")} và ${purple("quarrelsome")} giúp nói rõ cách một người tương tác với người khác.`,
        examples: [
          ex("He's gregarious and makes friends easily.", "Anh ấy hòa đồng và dễ kết bạn."),
          ex("She can be quarrelsome when stressed.", "Khi căng thẳng, cô ấy dễ cãi vã."),
        ],
      },
      {
        title: "Nói về thái độ với tiền và quan điểm",
        body: `${purple("thrifty")} thường tích cực; ${purple("stingy")} tiêu cực. ${purple("optimistic")}/${purple("pessimistic")} mô tả góc nhìn cuộc sống.`,
        examples: [
          ex("My grandmother is thrifty but never stingy with gifts.", "Bà tôi tiết kiệm nhưng không keo khi tặng quà."),
          ex("Try to stay optimistic about the interview.", "Hãy cố giữ thái độ lạc quan về buổi phỏng vấn."),
        ],
      },
    ],
    words: U8_WORDS,
    exercises: [
      mcq(
        8,
        1,
        "\"Sensible\" gần nghĩa nhất với đâu?",
        [
          { key: "a", label: "Biết điều, thực tế" },
          { key: "b", label: "Dễ xúc động" },
          { key: "c", label: "Hướng ngoại" },
          { key: "d", label: "Keo kiệt" },
        ],
        "a",
      ),
      fillBlank(
        8,
        2,
        "Don't be ____ with tipping; the service was excellent.",
        "stingy",
        [
          { key: "a", label: "gifted" },
          { key: "b", label: "stingy" },
          { key: "c", label: "gregarious" },
          { key: "d", label: "naive" },
        ],
        "b",
      ),
      mcq(
        8,
        3,
        "Người thích ở một mình, ít tìm kiếm kích thích xã hội thường được mô tả là gì?",
        [
          { key: "a", label: "extroverted" },
          { key: "b", label: "introverted" },
          { key: "c", label: "quarrelsome" },
          { key: "d", label: "assertive" },
        ],
        "b",
      ),
      fillBlank(
        8,
        4,
        "A ____ investor spots opportunities before others do.",
        "shrewd",
        [
          { key: "a", label: "naive" },
          { key: "b", label: "shrewd" },
          { key: "c", label: "lazy" },
          { key: "d", label: "sensitive" },
        ],
        "b",
      ),
      mcq(
        8,
        5,
        "\"Trustworthy\" nghĩa là gì?",
        [
          { key: "a", label: "Đáng tin cậy" },
          { key: "b", label: "Tò mò thái quá" },
          { key: "c", label: "Cứng đầu" },
          { key: "d", label: "Lạc quan" },
        ],
        "a",
      ),
      fillBlank(
        8,
        6,
        "He is too ____; he believes every email scam.",
        "naive",
        [
          { key: "a", label: "cunning" },
          { key: "b", label: "naive" },
          { key: "c", label: "obstinate" },
          { key: "d", label: "thrifty" },
        ],
        "b",
      ),
      mcq(
        8,
        7,
        "Từ nào mô tả người cứng đầu, khó thuyết phục?",
        [
          { key: "a", label: "easy-going" },
          { key: "b", label: "obstinate" },
          { key: "c", label: "gifted" },
          { key: "d", label: "optimistic" },
        ],
        "b",
      ),
      fillBlank(
        8,
        8,
        "Be ____ in meetings: state your view clearly without being rude.",
        "assertive",
        [
          { key: "a", label: "assertive" },
          { key: "b", label: "quarrelsome" },
          { key: "c", label: "stingy" },
          { key: "d", label: "crafty" },
        ],
        "a",
      ),
    ],
  }),

  upperUnit(9, {
    introVi:
      "Unit 9 đưa bạn vào thành ngữ mô tả tính cách và hành vi: từ trái tim vàng đến cái đầu đãng trí. Học idiom theo hình ảnh sẽ giúp bạn nhớ lâu và dùng tự nhiên trong hội thoại.",
    structureSections: [
      { label: "Heart idioms", wordCount: 5 },
      { label: "Head idioms", wordCount: 7 },
      { label: "People types and behaviour", wordCount: 6 },
    ],
    collocationHtml: `${purple("heart of gold")}, ${purple("keep your head")} và ${purple("get on everyone's nerves")} là các idiom tần suất cao trong tiếng Anh đời thường.`,
    mistakeHtml: `Đừng dịch word-by-word: ${bold("head in the clouds")} không phải \"đầu trên mây\" theo nghĩa đen; ${bold("as hard as nails")} nói về tính cách cứng rắn, không phải móng tay.`,
    principles: [
      {
        title: "Nhóm idiom theo hình ảnh trái tim",
        body: `${purple("heart of gold")} và ${purple("heart's in the right place")} nhấn mạnh lòng tốt; ${purple("as hard as nails")} thì ngược lại.`,
        examples: [
          ex("She has a heart of gold and helps everyone.", "Cô ấy có trái tim vàng và sẵn sàng giúp mọi người."),
          ex("His heart's in the right place, even if he messes up.", "Anh ấy bản chất tốt, dù đôi khi làm hỏng việc."),
        ],
      },
      {
        title: "Nhóm idiom theo hình ảnh cái đầu",
        body: `${purple("head screwed on")} = thực tế; ${purple("head like a sieve")} = đãng trí; ${purple("bury your head in the sand")} = trốn tránh vấn đề.`,
        examples: [
          ex("She's got her head screwed on when it comes to money.", "Cô ấy rất thực tế trong chuyện tiền bạc."),
          ex("Don't bury your head in the sand about the deadline.", "Đừng có mà chui đầu vào cát trước deadline."),
        ],
      },
      {
        title: "Dùng idiom mô tả kiểu người",
        body: `${purple("pain in the neck")}, ${purple("know-all")}, ${purple("teacher's pet")} và ${purple("lazy-bones")} mang sắc thái mạnh — dùng thận trọng.`,
        examples: [
          ex("Filling endless forms is a pain in the neck.", "Điền đơn từ dài dòng thật là chuyện khó chịu."),
          ex("Nobody likes a know-all in group work.", "Chẳng ai thích kiểu người tự cho là biết hết trong làm việc nhóm."),
        ],
      },
    ],
    words: U9_WORDS,
    exercises: [
      mcq(
        9,
        1,
        "\"Heart of gold\" mô tả người như thế nào?",
        [
          { key: "a", label: "Rất tốt bụng" },
          { key: "b", label: "Rất giàu có" },
          { key: "c", label: "Rất đãng trí" },
          { key: "d", label: "Rất cứng đầu" },
        ],
        "a",
      ),
      fillBlank(
        9,
        2,
        "Stay calm and ____ in an emergency.",
        "keep your head",
        [
          { key: "a", label: "bury your head in the sand" },
          { key: "b", label: "keep your head" },
          { key: "c", label: "get on everyone's nerves" },
          { key: "d", label: "go over the top" },
        ],
        "b",
      ),
      mcq(
        9,
        3,
        "Ai đó \"has a head like a sieve\" thường thế nào?",
        [
          { key: "a", label: "Đãng trí, hay quên" },
          { key: "b", label: "Rất thực tế" },
          { key: "c", label: "Rất nghiêm khắc" },
          { key: "d", label: "Rất lười biếng" },
        ],
        "a",
      ),
      fillBlank(
        9,
        4,
        "Stop humming; you're starting to ____.",
        "get on everyone's nerves",
        [
          { key: "a", label: "get on everyone's nerves" },
          { key: "b", label: "keep your head" },
          { key: "c", label: "have a heart of gold" },
          { key: "d", label: "be as good as gold" },
        ],
        "a",
      ),
      mcq(
        9,
        5,
        "\"Teacher's pet\" chỉ kiểu người nào?",
        [
          { key: "a", label: "Học sinh được giáo viên ưu ái" },
          { key: "b", label: "Giáo viên yêu động vật" },
          { key: "c", label: "Người rất cứng rắn" },
          { key: "d", label: "Người đãng trí" },
        ],
        "a",
      ),
      fillBlank(
        9,
        6,
        "His reaction was completely ____; nobody expected such drama.",
        "over the top",
        [
          { key: "a", label: "as good as gold" },
          { key: "b", label: "over the top" },
          { key: "c", label: "as hard as nails" },
          { key: "d", label: "heart of gold" },
        ],
        "b",
      ),
      mcq(
        9,
        7,
        "\"Bury your head in the sand\" nghĩa là gì?",
        [
          { key: "a", label: "Trốn tránh sự thật / vấn đề" },
          { key: "b", label: "Học thuộc lòng" },
          { key: "c", label: "Giữ bình tĩnh" },
          { key: "d", label: "Làm việc chăm chỉ" },
        ],
        "a",
      ),
    ],
  }),

  upperUnit(10, {
    introVi:
      "Unit 10 nói về các kiểu quan hệ và động từ miêu tả cảm xúc giữa người với người: từ người quen sơ đến đối tác, từ ngưỡng mộ đến không ưa. Bạn sẽ diễn đạt trạng thái quan hệ tự nhiên hơn ở mức B2.",
    structureSections: [
      { label: "Types of relationships", wordCount: 6 },
      { label: "Feelings and attitudes", wordCount: 6 },
      { label: "Getting on and falling out", wordCount: 6 },
    ],
    collocationHtml: `${purple("casual acquaintance")}, ${purple("see eye to eye")} và ${purple("fall out with")} là các cụm then chốt khi kể chuyện quan hệ.`,
    mistakeHtml: `Phân biệt ${bold("partner")} (bạn đời/đối tác) và ${bold("colleague")} (đồng nghiệp); ${bold("can't stand")} mạnh hơn ${bold("dislike")}. Động từ ${bold("unfriend")} mang ngữ cảnh mạng xã hội.`,
    principles: [
      {
        title: "Gọi đúng mức độ quan hệ",
        body: `${purple("casual acquaintance")} khác ${purple("housemate")} và ${purple("steady relationship")}; ${purple("parents-in-law")} là bố mẹ chồng/vợ.`,
        examples: [
          ex("He's only a casual acquaintance from the gym.", "Anh ấy chỉ là người quen sơ từ phòng gym."),
          ex("We're in a steady relationship now.", "Bọn mình đang trong một mối quan hệ nghiêm túc."),
        ],
      },
      {
        title: "Thái độ tích cực và tiêu cực",
        body: `${purple("look up to")} / ${purple("idolise")} trái ngược ${purple("look down on")} / ${purple("loathe")} / ${purple("can't stand")}.`,
        examples: [
          ex("I look up to my older sister.", "Tôi rất ngưỡng mộ chị gái."),
          ex("She can't stand people who interrupt constantly.", "Cô ấy không chịu nổi những người cứ ngắt lời."),
        ],
      },
      {
        title: "Kể chu kỳ xung đột và hòa giải",
        body: `Dùng chuỗi ${purple("fall out with")} → ${purple("make it up")}; hoặc ${purple("get on well")} / ${purple("see eye to eye")} khi hòa thuận.`,
        examples: [
          ex("They fell out over money, but made it up later.", "Họ cãi nhau vì tiền, nhưng sau đó đã làm lành."),
          ex("We don't always see eye to eye, but we get on well.", "Chúng tôi không phải lúc nào cũng đồng quan điểm, nhưng vẫn hợp nhau."),
        ],
      },
    ],
    words: U10_WORDS,
    exercises: [
      mcq(
        10,
        1,
        "\"Casual acquaintance\" là kiểu quan hệ nào?",
        [
          { key: "a", label: "Người quen sơ" },
          { key: "b", label: "Bạn đời lâu năm" },
          { key: "c", label: "Bố mẹ chồng/vợ" },
          { key: "d", label: "Sếp trực tiếp" },
        ],
        "a",
      ),
      fillBlank(
        10,
        2,
        "I ____ my old manager; she taught me so much.",
        "look up to",
        [
          { key: "a", label: "look down on" },
          { key: "b", label: "look up to" },
          { key: "c", label: "fall out with" },
          { key: "d", label: "unfriend" },
        ],
        "b",
      ),
      mcq(
        10,
        3,
        "\"See eye to eye\" nghĩa là gì?",
        [
          { key: "a", label: "Đồng quan điểm" },
          { key: "b", label: "Nhìn chằm chằm" },
          { key: "c", label: "Chia tay" },
          { key: "d", label: "Ghen tị" },
        ],
        "a",
      ),
      fillBlank(
        10,
        4,
        "They ____ last month, but they made it up yesterday.",
        "fell out",
        [
          { key: "a", label: "got together" },
          { key: "b", label: "fell out" },
          { key: "c", label: "idolised" },
          { key: "d", label: "fancied" },
        ],
        "b",
        ["fell out with each other", "fell out"],
      ),
      mcq(
        10,
        5,
        "Động từ nào mang nghĩa ghét/không chịu nổi rất mạnh?",
        [
          { key: "a", label: "fancy" },
          { key: "b", label: "loathe" },
          { key: "c", label: "get on well" },
          { key: "d", label: "make it up" },
        ],
        "b",
      ),
      fillBlank(
        10,
        6,
        "My ____ are coming for dinner — my partner's parents.",
        "parents-in-law",
        [
          { key: "a", label: "colleagues" },
          { key: "b", label: "parents-in-law" },
          { key: "c", label: "housemates" },
          { key: "d", label: "acquaintances" },
        ],
        "b",
      ),
      mcq(
        10,
        7,
        "\"Have an affair\" trong ngữ cảnh quan hệ thường nghĩa là gì?",
        [
          { key: "a", label: "Ngoại tình / có quan hệ ngoài luồng" },
          { key: "b", label: "Tổ chức tiệc" },
          { key: "c", label: "Xin việc" },
          { key: "d", label: "Kết bạn mới" },
        ],
        "a",
      ),
    ],
  }),

  upperUnit(11, {
    introVi:
      "Unit 11 cung cấp từ vựng về loại nhà và không gian trong nhà ở mức B2: từ studio flat, terraced house đến attic, patio, landing. Bạn sẽ mô tả chỗ ở chi tiết hơn khi kể chuyện hoặc viết mô tả.",
    structureSections: [
      { label: "Types of home", wordCount: 7 },
      { label: "Parts of the house", wordCount: 7 },
      { label: "Outdoor spaces and gadgets", wordCount: 4 },
    ],
    collocationHtml: `${purple("self-contained flat")}, ${purple("semi-detached house")} và ${purple("utility room")} là các cụm rất thực dụng khi nói về chỗ ở.`,
    mistakeHtml: `Phân biệt ${bold("attic")}/${bold("loft")} (gác mái) với ${bold("basement")}/${bold("cellar")} (tầng hầm); ${bold("bungalow")} là nhà một tầng, không phải biệt thự ${bold("villa")}.`,
    principles: [
      {
        title: "Gọi đúng loại nhà",
        body: `${purple("terraced house")}, ${purple("semi-detached")}, ${purple("cottage")}, ${purple("studio flat")} và ${purple("villa")} mang hình ảnh chỗ ở rất khác nhau.`,
        examples: [
          ex("They bought a terraced house near the station.", "Họ mua một căn nhà liền kề gần ga."),
          ex("A studio flat is enough for one person.", "Căn studio là đủ cho một người."),
        ],
      },
      {
        title: "Mô tả các khu vực trong nhà",
        body: `Học theo vị trí: ${purple("landing")}, ${purple("porch")}, ${purple("attic")}, ${purple("basement")} để chỉ đường trong nhà rõ ràng.`,
        examples: [
          ex("Leave your shoes in the porch.", "Để giày ở mái hiên/sảnh trước nhà."),
          ex("We store old boxes in the loft.", "Chúng tôi để hộp cũ trên gác mái."),
        ],
      },
      {
        title: "Không gian ngoài trời và đồ dùng",
        body: `${purple("patio")}, ${purple("drive")} và đồ như ${purple("remote control")}, ${purple("corkscrew")} hay xuất hiện khi kể sinh hoạt tại nhà.`,
        examples: [
          ex("We had breakfast on the patio.", "Chúng tôi ăn sáng ngoài sân trong."),
          ex("I can't find the remote control again.", "Lại chẳng thấy cái điều khiển đâu cả."),
        ],
      },
    ],
    words: U11_WORDS,
    exercises: [
      mcq(
        11,
        1,
        "\"Bungalow\" là loại nhà nào?",
        [
          { key: "a", label: "Nhà một tầng" },
          { key: "b", label: "Căn hộ studio" },
          { key: "c", label: "Tầng hầm" },
          { key: "d", label: "Nhà liền kề dài" },
        ],
        "a",
      ),
      fillBlank(
        11,
        2,
        "A ____ shares one wall with the neighbouring house.",
        "semi-detached house",
        [
          { key: "a", label: "villa" },
          { key: "b", label: "semi-detached house" },
          { key: "c", label: "cellar" },
          { key: "d", label: "patio" },
        ],
        "b",
        ["semi-detached", "semi-detached house"],
      ),
      mcq(
        11,
        3,
        "Phòng giặt/để máy móc tiện ích thường gọi là gì?",
        [
          { key: "a", label: "utility room" },
          { key: "b", label: "landing" },
          { key: "c", label: "porch" },
          { key: "d", label: "drive" },
        ],
        "a",
      ),
      fillBlank(
        11,
        4,
        "We keep wine in the cool ____ under the house.",
        "cellar",
        [
          { key: "a", label: "attic" },
          { key: "b", label: "cellar" },
          { key: "c", label: "patio" },
          { key: "d", label: "porch" },
        ],
        "b",
      ),
      mcq(
        11,
        5,
        "\"Self-contained flat\" nghĩa là căn hộ như thế nào?",
        [
          { key: "a", label: "Có đủ tiện nghi riêng, độc lập" },
          { key: "b", label: "Phải dùng chung bếp với chủ nhà" },
          { key: "c", label: "Chỉ có một tầng hầm" },
          { key: "d", label: "Là nhà tranh quê" },
        ],
        "a",
      ),
      fillBlank(
        11,
        6,
        "Park on the ____ in front of the garage.",
        "drive",
        [
          { key: "a", label: "landing" },
          { key: "b", label: "drive" },
          { key: "c", label: "attic" },
          { key: "d", label: "loft" },
        ],
        "b",
        ["driveway", "drive"],
      ),
      mcq(
        11,
        7,
        "Khu vực cầu thang giữa các tầng thường gọi là gì?",
        [
          { key: "a", label: "landing" },
          { key: "b", label: "patio" },
          { key: "c", label: "villa" },
          { key: "d", label: "cottage" },
        ],
        "a",
      ),
    ],
  }),

  upperUnit(12, {
    introVi:
      "Unit 12 tập trung những rắc rối nhỏ đời thường: đồ vỡ, mất điện, máy hỏng, bị thương nhẹ hay tự khóa ngoài cửa. Bộ từ này cực kỳ hữu ích khi kể chuyện và xin giúp đỡ.",
    structureSections: [
      { label: "Things going wrong", wordCount: 7 },
      { label: "Injuries and accidents", wordCount: 6 },
      { label: "Everyday mishaps", wordCount: 5 },
    ],
    collocationHtml: `${purple("power cut")}, ${purple("flat battery")} và ${purple("lock yourself out")} là các cụm \"đời thực\" nên học nguyên cụm.`,
    mistakeHtml: `Phân biệt ${bold("bruise")} (bầm), ${bold("graze")} (trầy) và ${bold("twist")} (trật/vặn); máy tính ${bold("crash")} khác xe ${bold("break down")}.`,
    principles: [
      {
        title: "Mô tả hư hỏng đồ vật bằng động từ đúng",
        body: `${purple("leak")}, ${purple("smash")}, ${purple("crack")}, ${purple("chip")}, ${bold("dent")} và ${purple("blocked")} giúp kể sự cố nhà cửa rõ ràng.`,
        examples: [
          ex("The pipe is leaking under the sink.", "Ống nước đang rò dưới bồn rửa."),
          ex("I chipped a plate while washing up.", "Tôi làm sứt một cái đĩa lúc rửa chén."),
        ],
      },
      {
        title: "Nói về chấn thương nhẹ",
        body: `Dùng ${purple("twist your ankle")}, ${purple("bruise")}, ${purple("graze")} và ${purple("trip")} khi kể tai nạn nhỏ.`,
        examples: [
          ex("I twisted my ankle on the stairs.", "Tôi bị trật mắt cá khi xuống cầu thang."),
          ex("She fell and grazed her knee.", "Cô ấy ngã và trầy đầu gối."),
        ],
      },
      {
        title: "Sự cố tiện ích và đồ điện tử",
        body: `${purple("power cut")}, ${purple("break down")}, máy ${purple("crash")}, ${purple("flat battery")} và ${purple("lock oneself out")} rất hay gặp trong hội thoại.`,
        examples: [
          ex("There was a power cut during the storm.", "Bị mất điện trong trận bão."),
          ex("I've locked myself out again.", "Lại tự khóa mình ngoài cửa mất rồi."),
        ],
      },
    ],
    words: U12_WORDS,
    exercises: [
      mcq(
        12,
        1,
        "\"Power cut\" nghĩa là gì?",
        [
          { key: "a", label: "Mất điện" },
          { key: "b", label: "Cắt giấy" },
          { key: "c", label: "Hết pin điện thoại" },
          { key: "d", label: "Vỡ kính" },
        ],
        "a",
      ),
      fillBlank(
        12,
        2,
        "Be careful — don't ____ your coffee on the laptop.",
        "spill",
        [
          { key: "a", label: "bruise" },
          { key: "b", label: "spill" },
          { key: "c", label: "dent" },
          { key: "d", label: "crash" },
        ],
        "b",
      ),
      mcq(
        12,
        3,
        "Khi mắt cá bị vặn/trật, ta thường nói gì?",
        [
          { key: "a", label: "twist your ankle" },
          { key: "b", label: "chip your ankle" },
          { key: "c", label: "mislay your ankle" },
          { key: "d", label: "stain your ankle" },
        ],
        "a",
      ),
      fillBlank(
        12,
        4,
        "The washing machine has ____ again; we need a repairman.",
        "broken down",
        [
          { key: "a", label: "broken down" },
          { key: "b", label: "grazed" },
          { key: "c", label: "thawed" },
          { key: "d", label: "melted" },
        ],
        "a",
        ["broken down", "broke down"],
      ),
      mcq(
        12,
        5,
        "\"Mislay\" gần nghĩa với đâu?",
        [
          { key: "a", label: "Để thất lạc / quên để đâu" },
          { key: "b", label: "Làm vỡ tan" },
          { key: "c", label: "Bị bầm tím" },
          { key: "d", label: "Bị tắc nghẽn" },
        ],
        "a",
      ),
      fillBlank(
        12,
        6,
        "My phone won't start — I think it has a ____.",
        "flat battery",
        [
          { key: "a", label: "flat battery" },
          { key: "b", label: "power cut" },
          { key: "c", label: "blocked sink" },
          { key: "d", label: "small bruise" },
        ],
        "a",
      ),
      mcq(
        12,
        7,
        "Vết bầm trên da thường gọi là gì?",
        [
          { key: "a", label: "bruise" },
          { key: "b", label: "leak" },
          { key: "c", label: "dent" },
          { key: "d", label: "stain" },
        ],
        "a",
      ),
      fillBlank(
        12,
        8,
        "The sink is ____; water won't go down.",
        "blocked",
        [
          { key: "a", label: "blocked" },
          { key: "b", label: "scruffy" },
          { key: "c", label: "muggy" },
          { key: "d", label: "stunning" },
        ],
        "a",
      ),
    ],
  }),

  upperUnit(13, {
    introVi:
      "Unit 13 trang bị từ vựng về vấn đề toàn cầu: thiên tai, dịch bệnh, xung đột và người phải di dời. Đây là nền tảng để đọc tin tức và thảo luận xã hội ở mức upper-intermediate.",
    structureSections: [
      { label: "Natural disasters", wordCount: 7 },
      { label: "Conflict and people affected", wordCount: 6 },
      { label: "Disease and crisis language", wordCount: 5 },
    ],
    collocationHtml: `${purple("natural disaster")}, ${purple("civil war")} và ${purple("aid for refugees")} là các cụm xuất hiện dày đặc trên báo chí.`,
    mistakeHtml: `Dùng ${bold("injure")} với người (${bold("injure people")}), không nói \"damage people\". Phân biệt ${bold("refugee")} (người tị nạn) và ${bold("migrant")} (người di cư).`,
    principles: [
      {
        title: "Gọi đúng loại thiên tai",
        body: `${purple("earthquake")}, ${purple("drought")}, ${purple("famine")}, ${purple("landslide")} và núi lửa ${purple("erupt")} là khung từ khóa tin tức.`,
        examples: [
          ex("The earthquake left thousands homeless.", "Trận động đất khiến hàng nghìn người mất nhà."),
          ex("The volcano could erupt again this year.", "Ngọn núi lửa có thể phun trào trở lại năm nay."),
        ],
      },
      {
        title: "Nói về người chịu ảnh hưởng",
        body: `${purple("casualty")}, ${purple("survivor")}, ${purple("wounded")}, ${purple("refugee")} và ${purple("migrant")} cần dùng đúng ngữ cảnh nhân đạo.`,
        examples: [
          ex("Rescue teams searched for survivors.", "Đội cứu hộ tìm kiếm người sống sót."),
          ex("Many refugees crossed the border overnight.", "Nhiều người tị nạn vượt biên trong đêm."),
        ],
      },
      {
        title: "Dịch bệnh và xung đột",
        body: `${purple("epidemic")}, ${purple("malaria")}, ${purple("cholera")} và ${purple("civil war")} thường đi cùng ngôn ngữ hỗ trợ/khủng hoảng.`,
        examples: [
          ex("The epidemic spread quickly in crowded camps.", "Dịch bệnh lây nhanh trong các trại đông đúc."),
          ex("Civilians were wounded during the civil war.", "Dân thường bị thương trong nội chiến."),
        ],
      },
    ],
    words: U13_WORDS,
    exercises: [
      mcq(
        13,
        1,
        "Người sống sót sau thảm họa gọi là gì?",
        [
          { key: "a", label: "survivor" },
          { key: "b", label: "casualty list only" },
          { key: "c", label: "spectator" },
          { key: "d", label: "critic" },
        ],
        "a",
      ),
      fillBlank(
        13,
        2,
        "A long period without rain can lead to ____ and crop failure.",
        "drought",
        [
          { key: "a", label: "drought" },
          { key: "b", label: "lecture" },
          { key: "c", label: "seminar" },
          { key: "d", label: "patio" },
        ],
        "a",
      ),
      mcq(
        13,
        3,
        "\"Refugee\" khác \"migrant\" ở điểm nào nổi bật nhất?",
        [
          { key: "a", label: "Refugee thường buộc phải rời đi vì nguy hiểm/xung đột" },
          { key: "b", label: "Refugee chỉ đi du lịch ngắn ngày" },
          { key: "c", label: "Migrant luôn là nạn nhân động đất" },
          { key: "d", label: "Hai từ hoàn toàn giống nhau" },
        ],
        "a",
      ),
      fillBlank(
        13,
        4,
        "The volcano may ____ if pressure keeps building.",
        "erupt",
        [
          { key: "a", label: "erupt" },
          { key: "b", label: "apply" },
          { key: "c", label: "qualify" },
          { key: "d", label: "launch" },
        ],
        "a",
      ),
      mcq(
        13,
        5,
        "Câu nào đúng hơn?",
        [
          { key: "a", label: "The blast injured several people." },
          { key: "b", label: "The blast damaged several people." },
          { key: "c", label: "The blast graduated several people." },
          { key: "d", label: "The blast promoted several people." },
        ],
        "a",
      ),
      fillBlank(
        13,
        6,
        "An ____ of cholera was reported after the floods.",
        "epidemic",
        [
          { key: "a", label: "epidemic" },
          { key: "b", label: "acquaintance" },
          { key: "c", label: "dissertation" },
          { key: "d", label: "trophy" },
        ],
        "a",
      ),
      mcq(
        13,
        7,
        "\"Famine\" nghĩa là gì?",
        [
          { key: "a", label: "Nạn đói quy mô lớn" },
          { key: "b", label: "Một trận mưa ngắn" },
          { key: "c", label: "Buổi hội thảo" },
          { key: "d", label: "Kỳ nghỉ phép" },
        ],
        "a",
      ),
    ],
  }),

  upperUnit(14, {
    introVi:
      "Unit 14 đi qua hệ thống giáo dục phổ thông và các hành động học tập: loại trường, độ tuổi bắt buộc đến trường, học kết hợp và nộp bài. Từ vựng nghiêng về ngữ cảnh Anh và học tập hiện đại.",
    structureSections: [
      { label: "Types of school", wordCount: 7 },
      { label: "Study actions and courses", wordCount: 6 },
      { label: "Rules and attendance", wordCount: 5 },
    ],
    collocationHtml: `${purple("compulsory education")}, ${purple("blended learning")} và ${purple("school-leaving age")} là các cụm quan trọng khi nói về hệ thống giáo dục.`,
    mistakeHtml: `Ở Anh, ${bold("public school")} thường là trường tư danh tiếng — không phải \"trường công\" theo nghĩa Việt. Phân biệt ${bold("nursery school")} và ${bold("crèche")}.`,
    principles: [
      {
        title: "Phân biệt các loại trường",
        body: `${purple("comprehensive school")}, ${purple("grammar school")}, ${purple("public school")} (UK) và ${purple("sixth-form college")} thuộc các lộ trình khác nhau.`,
        examples: [
          ex("Most children attend a comprehensive school.", "Hầu hết trẻ học trường phổ thông không tuyển chọn."),
          ex("She moved to a sixth-form college at 16.", "Cô ấy chuyển sang trường sixth-form khi 16 tuổi."),
        ],
      },
      {
        title: "Nói về hình thức và hành động học",
        body: `${purple("blended learning")}, ${purple("distance learning")}, ${purple("module")}, ${purple("submit")} và ${purple("resit")} rất hay dùng ở môi trường học hiện đại.`,
        examples: [
          ex("We follow a blended learning model.", "Chúng tôi theo mô hình học kết hợp."),
          ex("I have to resit the chemistry exam.", "Tôi phải thi lại môn hóa."),
        ],
      },
      {
        title: "Quy định và chuyên cần",
        body: `${purple("compulsory")}, ${purple("school-leaving age")} và ${purple("skip classes")} giúp nói về nghĩa vụ đi học và việc trốn học.`,
        examples: [
          ex("Education is compulsory until the school-leaving age.", "Giáo dục là bắt buộc cho đến độ tuổi được nghỉ học."),
          ex("He skipped classes and fell behind.", "Cậu ấy trốn học và bị tụt lại."),
        ],
      },
    ],
    words: U14_WORDS,
    exercises: [
      mcq(
        14,
        1,
        "Trong tiếng Anh Anh, \"public school\" thường là gì?",
        [
          { key: "a", label: "Trường tư danh tiếng (không phải \"trường công\" theo nghĩa Việt)" },
          { key: "b", label: "Trường miễn phí của nhà nước" },
          { key: "c", label: "Nhà trẻ" },
          { key: "d", label: "Khóa học online" },
        ],
        "a",
      ),
      fillBlank(
        14,
        2,
        "Maths is ____ until the age of 16 in many countries.",
        "compulsory",
        [
          { key: "a", label: "optional" },
          { key: "b", label: "compulsory" },
          { key: "c", label: "redundant" },
          { key: "d", label: "literary" },
        ],
        "b",
      ),
      mcq(
        14,
        3,
        "\"Skip classes\" nghĩa là gì?",
        [
          { key: "a", label: "Trốn/bỏ học" },
          { key: "b", label: "Học thêm buổi tối" },
          { key: "c", label: "Nộp bài sớm" },
          { key: "d", label: "Thi lại" },
        ],
        "a",
      ),
      fillBlank(
        14,
        4,
        "Please ____ your essay before Friday.",
        "submit",
        [
          { key: "a", label: "submit" },
          { key: "b", label: "erupt" },
          { key: "c", label: "thaw" },
          { key: "d", label: "launch" },
        ],
        "a",
      ),
      mcq(
        14,
        5,
        "Học kết hợp trực tiếp và trực tuyến gọi là gì?",
        [
          { key: "a", label: "blended learning" },
          { key: "b", label: "grammar school only" },
          { key: "c", label: "power cut" },
          { key: "d", label: "heatwave" },
        ],
        "a",
      ),
      fillBlank(
        14,
        6,
        "If you fail, you may have to ____ the exam next term.",
        "resit",
        [
          { key: "a", label: "resit" },
          { key: "b", label: "idolise" },
          { key: "c", label: "qualify" },
          { key: "d", label: "manufacture" },
        ],
        "a",
      ),
      mcq(
        14,
        7,
        "\"Module\" trong khóa học thường là gì?",
        [
          { key: "a", label: "Một học phần / đơn vị học" },
          { key: "b", label: "Một loại thiên tai" },
          { key: "c", label: "Một môn thể thao" },
          { key: "d", label: "Một kiểu nhà" },
        ],
        "a",
      ),
    ],
  }),

  upperUnit(15, {
    introVi:
      "Unit 15 tập trung giáo dục đại học: bậc học, hình thức giảng dạy, chỗ ở sinh viên và học phí. Bạn sẽ nói chuyện về đại học tự nhiên hơn khi đọc brochure hoặc kể lộ trình học.",
    structureSections: [
      { label: "Degrees and students", wordCount: 7 },
      { label: "Teaching and study formats", wordCount: 6 },
      { label: "Fees, funding and admissions", wordCount: 5 },
    ],
    collocationHtml: `${purple("tuition fees")}, ${purple("student loan")} và ${purple("entry requirements")} là các cụm bắt buộc khi bàn về đại học.`,
    mistakeHtml: `Phân biệt ${bold("dissertation")} / ${bold("thesis")} (luận văn) với bài luận ngắn; ${bold("undergraduate")} chưa tốt nghiệp đại học, khác ${bold("postgraduate")}.`,
    principles: [
      {
        title: "Gọi đúng bậc học",
        body: `${purple("undergraduate")}, ${purple("bachelor's degree")}, ${purple("master's degree")}, ${purple("PhD")} và ${purple("postgraduate")} tạo thành lộ trình học thuật.`,
        examples: [
          ex("She's an undergraduate in economics.", "Cô ấy đang là sinh viên đại học ngành kinh tế."),
          ex("He completed his master's degree last year.", "Anh ấy hoàn thành bằng thạc sĩ năm ngoái."),
        ],
      },
      {
        title: "Hình thức học trên giảng đường",
        body: `${purple("lecture theatre")}, ${purple("seminar")}, ${purple("tutorial")} và ${purple("credit")} mô tả cách học và tín chỉ.`,
        examples: [
          ex("The lecture theatre was packed.", "Giảng đường chật kín người."),
          ex("We discussed the article in a seminar.", "Chúng tôi thảo luận bài báo trong seminar."),
        ],
      },
      {
        title: "Tiền học và tuyển sinh",
        body: `${purple("tuition fees")}, ${purple("scholarship")}, ${purple("student loan")}, ${purple("halls of residence")} và ${purple("admissions")} là ngôn ngữ thực tế của đời sinh viên.`,
        examples: [
          ex("She won a scholarship that covers tuition fees.", "Cô ấy giành được học bổng trang trải học phí."),
          ex("Check the entry requirements before you apply.", "Hãy xem yêu cầu đầu vào trước khi nộp hồ sơ."),
        ],
      },
    ],
    words: U15_WORDS,
    exercises: [
      mcq(
        15,
        1,
        "Sinh viên chưa lấy bằng đại học thường gọi là gì?",
        [
          { key: "a", label: "undergraduate" },
          { key: "b", label: "supervisor" },
          { key: "c", label: "spectator" },
          { key: "d", label: "critic" },
        ],
        "a",
      ),
      fillBlank(
        15,
        2,
        "Many students take out a ____ to pay for university.",
        "student loan",
        [
          { key: "a", label: "student loan" },
          { key: "b", label: "power cut" },
          { key: "c", label: "heatwave" },
          { key: "d", label: "civil war" },
        ],
        "a",
      ),
      mcq(
        15,
        3,
        "\"Halls of residence\" là gì?",
        [
          { key: "a", label: "Ký túc xá sinh viên" },
          { key: "b", label: "Phòng thi" },
          { key: "c", label: "Thư viện luật" },
          { key: "d", label: "Sân vận động" },
        ],
        "a",
      ),
      fillBlank(
        15,
        4,
        "She is writing her ____ in the final year.",
        "dissertation",
        [
          { key: "a", label: "dissertation" },
          { key: "b", label: "bungalow" },
          { key: "c", label: "bruise" },
          { key: "d", label: "dialect" },
        ],
        "a",
      ),
      mcq(
        15,
        5,
        "Buổi học nhóm nhỏ với giảng viên thường gọi là gì?",
        [
          { key: "a", label: "tutorial" },
          { key: "b", label: "drought" },
          { key: "c", label: "patio" },
          { key: "d", label: "gale" },
        ],
        "a",
      ),
      fillBlank(
        15,
        6,
        "____ fees have risen again this year.",
        "Tuition",
        [
          { key: "a", label: "Tuition" },
          { key: "b", label: "Torrential" },
          { key: "c", label: "Stifling" },
          { key: "d", label: "Scruffy" },
        ],
        "a",
        ["Tuition", "tuition"],
      ),
      mcq(
        15,
        7,
        "\"Entry requirements\" là gì?",
        [
          { key: "a", label: "Điều kiện đầu vào" },
          { key: "b", label: "Lịch thi đấu" },
          { key: "c", label: "Hóa đơn điện" },
          { key: "d", label: "Bản dịch sách" },
        ],
        "a",
      ),
      fillBlank(
        15,
        8,
        "After her bachelor's degree, she started a ____ course.",
        "postgraduate",
        [
          { key: "a", label: "postgraduate" },
          { key: "b", label: "nursery" },
          { key: "c", label: "terraced" },
          { key: "d", label: "muggy" },
        ],
        "a",
      ),
    ],
  }),

  upperUnit(16, {
    introVi:
      "Unit 16 bàn về công việc ở mức B2: loại lao động, ca làm, nghỉ phép và mất việc. Bạn sẽ mô tả đời làm việc thực tế hơn thay vì chỉ nói \"I have a job\".",
    structureSections: [
      { label: "Jobs and workers", wordCount: 6 },
      { label: "Working patterns", wordCount: 6 },
      { label: "Leaving, leave and progress", wordCount: 6 },
    ],
    collocationHtml: `${purple("make a living")}, ${purple("get the sack")} và ${purple("maternity leave")} là các cụm đời công sở rất đáng học nguyên cụm.`,
    mistakeHtml: `Phân biệt ${bold("get the sack")} (bị sa thải vì lỗi/hiệu suất) và ${bold("made redundant")} (cắt giảm nhân sự). ${bold("Flexi-time")} khác ${bold("nine-to-five")}.`,
    principles: [
      {
        title: "Gọi đúng vai trò và kỹ năng",
        body: `${purple("executive")}, ${purple("supervisor")}, ${purple("skilled worker")} và ${purple("unskilled worker")} giúp định vị vị trí trong tổ chức.`,
        examples: [
          ex("She's a senior executive in marketing.", "Cô ấy là giám đốc điều hành cấp cao bên marketing."),
          ex("The supervisor checks quality on the line.", "Giám sát viên kiểm tra chất lượng trên chuyền."),
        ],
      },
      {
        title: "Mô tả nhịp làm việc",
        body: `${purple("shiftwork")}, ${purple("flexi-time")}, ${purple("nine-to-five")} và ${purple("workaholic")} nói về lịch làm và thói quen làm việc.`,
        examples: [
          ex("Nurses often do shiftwork.", "Y tá thường phải làm việc theo ca."),
          ex("Our company offers flexi-time.", "Công ty chúng tôi cho phép giờ làm linh hoạt."),
        ],
      },
      {
        title: "Nghỉ phép, mất việc và thăng tiến",
        body: `Học ${purple("sick leave")}, ${purple("maternity leave")}, ${purple("get the sack")}, ${purple("made redundant")}, ${purple("be promoted")} và ${purple("apply for a job")}.`,
        examples: [
          ex("He was made redundant when the factory closed.", "Anh ấy bị cắt giảm khi nhà máy đóng cửa."),
          ex("She was promoted to team leader.", "Cô ấy được thăng chức làm trưởng nhóm."),
        ],
      },
    ],
    words: U16_WORDS,
    exercises: [
      mcq(
        16,
        1,
        "\"Made redundant\" thường nghĩa là gì?",
        [
          { key: "a", label: "Bị cắt giảm nhân sự / mất việc vì tổ chức tinh giản" },
          { key: "b", label: "Được tăng lương" },
          { key: "c", label: "Được nghỉ thai sản" },
          { key: "d", label: "Làm thêm giờ" },
        ],
        "a",
      ),
      fillBlank(
        16,
        2,
        "It's hard to ____ as an artist in a small town.",
        "make a living",
        [
          { key: "a", label: "make a living" },
          { key: "b", label: "get on everyone's nerves" },
          { key: "c", label: "keep your head" },
          { key: "d", label: "see eye to eye" },
        ],
        "a",
      ),
      mcq(
        16,
        3,
        "Người làm việc quá mức, gần như nghiện việc gọi là gì?",
        [
          { key: "a", label: "workaholic" },
          { key: "b", label: "lazy-bones" },
          { key: "c", label: "odd-ball" },
          { key: "d", label: "know-all" },
        ],
        "a",
      ),
      fillBlank(
        16,
        4,
        "She is on ____ after the birth of her baby.",
        "maternity leave",
        [
          { key: "a", label: "maternity leave" },
          { key: "b", label: "sick leave only forever" },
          { key: "c", label: "shiftwork" },
          { key: "d", label: "stiff competition" },
        ],
        "a",
      ),
      mcq(
        16,
        5,
        "\"Get the sack\" nghĩa là gì?",
        [
          { key: "a", label: "Bị sa thải" },
          { key: "b", label: "Nhận quà" },
          { key: "c", label: "Được thăng chức" },
          { key: "d", label: "Xin việc" },
        ],
        "a",
      ),
      fillBlank(
        16,
        6,
        "I want to ____ a job in digital marketing.",
        "apply for",
        [
          { key: "a", label: "apply for" },
          { key: "b", label: "fall out with" },
          { key: "c", label: "look down on" },
          { key: "d", label: "lock myself out of" },
        ],
        "a",
      ),
      mcq(
        16,
        7,
        "Lịch làm linh hoạt thường gọi là gì?",
        [
          { key: "a", label: "flexi-time" },
          { key: "b", label: "nine-to-five only" },
          { key: "c", label: "civil war" },
          { key: "d", label: "torrential rain" },
        ],
        "a",
      ),
    ],
  }),

  upperUnit(17, {
    introVi:
      "Unit 17 mở vốn từ kinh doanh: kế hoạch, nghiên cứu thị trường, cạnh tranh và lợi nhuận. Đây là ngôn ngữ hữu ích cho tin tức kinh tế, phỏng vấn và thảo luận khởi nghiệp ở mức B2.",
    structureSections: [
      { label: "Starting and producing", wordCount: 6 },
      { label: "Customers and markets", wordCount: 7 },
      { label: "Performance and competition", wordCount: 5 },
    ],
    collocationHtml: `${purple("market research")}, ${purple("stiff competition")} và ${purple("make a profit")} là các cụm xương sống của chủ đề business.`,
    mistakeHtml: `Phân biệt ${bold("launch")} / ${bold("roll out")} (đưa sản phẩm ra thị trường) với chỉ \"bắt đầu làm việc\". ${bold("Custom-built")} nghĩa là làm theo yêu cầu, không phải \"phong tục\".`,
    principles: [
      {
        title: "Nói về sản phẩm và sản xuất",
        body: `${purple("business plan")}, ${purple("manufacture")}, ${purple("custom-built")}, ${purple("launch")} và ${purple("roll out")} tạo chuỗi từ ý tưởng đến ra mắt.`,
        examples: [
          ex("They launched the app in May.", "Họ ra mắt ứng dụng vào tháng Năm."),
          ex("The furniture is custom-built for each client.", "Nội thất được làm riêng theo từng khách."),
        ],
      },
      {
        title: "Khách hàng và thị trường",
        body: `${purple("potential customer")}, ${purple("customer care")}, ${purple("market research")}, ${purple("feedback")} và ${purple("access new markets")} là ngôn ngữ tăng trưởng.`,
        examples: [
          ex("We ran market research before the launch.", "Chúng tôi làm nghiên cứu thị trường trước khi ra mắt."),
          ex("Good customer care builds loyalty.", "Chăm sóc khách hàng tốt tạo lòng trung thành."),
        ],
      },
      {
        title: "Kết quả kinh doanh và cạnh tranh",
        body: `${purple("recession")}, ${purple("order books")}, ${purple("stiff competition")}, ${purple("make a profit")}, ${purple("CEO")} và ${purple("corporation")} thường đi cùng tin tài chính.`,
        examples: [
          ex("Sales fell during the recession.", "Doanh số giảm trong suy thoái."),
          ex("They face stiff competition from abroad.", "Họ phải đối mặt cạnh tranh gay gắt từ nước ngoài."),
        ],
      },
    ],
    words: U17_WORDS,
    exercises: [
      mcq(
        17,
        1,
        "\"Stiff competition\" nghĩa là gì?",
        [
          { key: "a", label: "Cạnh tranh gay gắt" },
          { key: "b", label: "Cuộc thi thể thao cứng nhắc" },
          { key: "c", label: "Khách hàng tiềm năng" },
          { key: "d", label: "Nghỉ ốm" },
        ],
        "a",
      ),
      fillBlank(
        17,
        2,
        "The company hopes to ____ a profit this quarter.",
        "make",
        [
          { key: "a", label: "make" },
          { key: "b", label: "skip" },
          { key: "c", label: "bruise" },
          { key: "d", label: "thaw" },
        ],
        "a",
        ["make", "make a profit"],
      ),
      mcq(
        17,
        3,
        "\"Market research\" là gì?",
        [
          { key: "a", label: "Nghiên cứu thị trường" },
          { key: "b", label: "Xây biệt thự" },
          { key: "c", label: "Thi lại môn" },
          { key: "d", label: "Mất điện" },
        ],
        "a",
      ),
      fillBlank(
        17,
        4,
        "They will ____ the new model next spring.",
        "launch",
        [
          { key: "a", label: "launch" },
          { key: "b", label: "graze" },
          { key: "c", label: "idolise" },
          { key: "d", label: "resit" },
        ],
        "a",
      ),
      mcq(
        17,
        5,
        "CEO viết tắt thường chỉ ai?",
        [
          { key: "a", label: "Giám đốc điều hành" },
          { key: "b", label: "Nhân viên part-time" },
          { key: "c", label: "Khách hàng tiềm năng" },
          { key: "d", label: "Người tị nạn" },
        ],
        "a",
      ),
      fillBlank(
        17,
        6,
        "A period of economic decline is called a ____.",
        "recession",
        [
          { key: "a", label: "recession" },
          { key: "b", label: "scholarship" },
          { key: "c", label: "dissertation" },
          { key: "d", label: "heatwave" },
        ],
        "a",
      ),
      mcq(
        17,
        7,
        "\"Custom-built\" mô tả sản phẩm như thế nào?",
        [
          { key: "a", label: "Làm theo yêu cầu riêng" },
          { key: "b", label: "Làm hàng loạt giá rẻ" },
          { key: "c", label: "Chỉ bán online" },
          { key: "d", label: "Đã lỗi thời" },
        ],
        "a",
      ),
      fillBlank(
        17,
        8,
        "We need ____ from users before the next update.",
        "feedback",
        [
          { key: "a", label: "feedback" },
          { key: "b", label: "frost" },
          { key: "c", label: "freckles" },
          { key: "d", label: "fencing" },
        ],
        "a",
      ),
    ],
  }),

  upperUnit(18, {
    introVi:
      "Unit 18 mở rộng từ vựng thể thao: môn ít phổ biến hơn, dụng cụ, vòng đấu và người xem. Bạn sẽ miêu tả sự kiện thể thao và kết quả thi đấu rõ ràng hơn trên báo hoặc trong hội thoại.",
    structureSections: [
      { label: "Sports and equipment", wordCount: 8 },
      { label: "Competition stages", wordCount: 5 },
      { label: "Athletes and spectators", wordCount: 5 },
    ],
    collocationHtml: `${purple("qualify for the final")}, ${purple("knock out")} và ${purple("win the trophy")} là các cụm thi đấu rất hay gặp.`,
    mistakeHtml: `Phân biệt ${bold("racket")} (vợt) và ${bold("cue")} (gậy bi-a); ${bold("spectator")} là người xem, không phải vận động viên. ${bold("Breaststroke")} là kiểu bơi ếch.`,
    principles: [
      {
        title: "Học môn thể thao kèm dụng cụ",
        body: `${purple("fencing")}, ${purple("archery")}, ${purple("snooker")}, ${purple("scuba diving")} và ${purple("hang-gliding")} đi với dụng cụ như ${purple("racket")}, ${purple("cue")}, ${purple("javelin")}.`,
        examples: [
          ex("He bought a new tennis racket.", "Anh ấy mua một cây vợt tennis mới."),
          ex("Archery requires a steady hand.", "Bắn cung cần bàn tay vững."),
        ],
      },
      {
        title: "Nói về vòng đấu và kết quả",
        body: `${purple("qualify")}, ${purple("knock out")}, ${purple("semi-final")} và ${purple("trophy")} giúp kể diễn biến giải đấu.`,
        examples: [
          ex("They qualified for the semi-final.", "Họ giành quyền vào bán kết."),
          ex("The champion lifted the trophy.", "Nhà vô địch nâng cao chiếc cúp."),
        ],
      },
      {
        title: "Phân biệt người chơi và người xem",
        body: `${purple("sprinter")}, vận động viên các môn khác và ${purple("spectator")} / khán giả đóng vai trò khác trong sự kiện.`,
        examples: [
          ex("The sprinter broke the record.", "VĐV chạy ngắn phá kỷ lục."),
          ex("Spectators cheered loudly.", "Khán giả reo hò ầm ĩ."),
        ],
      },
    ],
    words: U18_WORDS,
    exercises: [
      mcq(
        18,
        1,
        "\"Spectator\" là ai?",
        [
          { key: "a", label: "Người xem / khán giả" },
          { key: "b", label: "Trọng tài" },
          { key: "c", label: "Huấn luyện viên" },
          { key: "d", label: "Người viết phê bình nghệ thuật" },
        ],
        "a",
      ),
      fillBlank(
        18,
        2,
        "Our team was ____ in the quarter-final.",
        "knocked out",
        [
          { key: "a", label: "knocked out" },
          { key: "b", label: "made redundant" },
          { key: "c", label: "locked out" },
          { key: "d", label: "rolled out" },
        ],
        "a",
      ),
      mcq(
        18,
        3,
        "Dụng cụ dùng trong snooker thường là gì?",
        [
          { key: "a", label: "cue" },
          { key: "b", label: "javelin" },
          { key: "c", label: "racket" },
          { key: "d", label: "remote control" },
        ],
        "a",
      ),
      fillBlank(
        18,
        4,
        "She hopes to ____ for the Olympics next year.",
        "qualify",
        [
          { key: "a", label: "qualify" },
          { key: "b", label: "mislay" },
          { key: "c", label: "unfriend" },
          { key: "d", label: "thaw" },
        ],
        "a",
      ),
      mcq(
        18,
        5,
        "\"Breaststroke\" là kiểu bơi nào?",
        [
          { key: "a", label: "Bơi ếch" },
          { key: "b", label: "Bơi sải" },
          { key: "c", label: "Bơi bướm" },
          { key: "d", label: "Lặn biển có bình khí" },
        ],
        "a",
      ),
      fillBlank(
        18,
        6,
        "The winner raised the ____ above her head.",
        "trophy",
        [
          { key: "a", label: "trophy" },
          { key: "b", label: "thesis" },
          { key: "c", label: "dialect" },
          { key: "d", label: "porch" },
        ],
        "a",
      ),
      mcq(
        18,
        7,
        "\"Pole vault\" là môn gì?",
        [
          { key: "a", label: "Nhảy sào" },
          { key: "b", label: "Bắn cung" },
          { key: "c", label: "Đấu kiếm" },
          { key: "d", label: "Bi-a" },
        ],
        "a",
      ),
      fillBlank(
        18,
        8,
        "They reached the ____ but lost in the final.",
        "semi-final",
        [
          { key: "a", label: "semi-final" },
          { key: "b", label: "utility room" },
          { key: "c", label: "mother tongue" },
          { key: "d", label: "heatwave" },
        ],
        "a",
      ),
    ],
  }),

  upperUnit(19, {
    introVi:
      "Unit 19 đưa bạn vào ngôn ngữ nghệ thuật và văn học: mỹ thuật, thể loại tranh, tiểu thuyết và phê bình. Bạn sẽ nói về tác phẩm và trải nghiệm thẩm mỹ tự nhiên hơn ở mức B2.",
    structureSections: [
      { label: "Visual arts", wordCount: 8 },
      { label: "Literature and books", wordCount: 6 },
      { label: "Criticism and crafts", wordCount: 4 },
    ],
    collocationHtml: `${purple("work of art")}, ${purple("abstract painting")} và ${purple("literary critic")} là các cụm then chốt khi bàn về nghệ thuật và sách.`,
    mistakeHtml: `Phân biệt ${bold("the arts")} (các ngành nghệ thuật nói chung) và ${bold("fine art")} (mỹ thuật); ${bold("plot")} là cốt truyện, không phải \"âm mưu\" trong mọi ngữ cảnh văn học.`,
    principles: [
      {
        title: "Phân loại hình thức nghệ thuật thị giác",
        body: `${purple("sculpture")}, ${purple("ceramics")}, ${purple("portrait")}, ${purple("landscape")}, ${purple("still life")} và ${purple("abstract painting")} giúp mô tả tác phẩm chính xác.`,
        examples: [
          ex("The gallery has a striking abstract painting.", "Phòng trưng bày có một bức tranh trừu tượng rất ấn tượng."),
          ex("She specializes in portrait photography.", "Cô ấy chuyên về nhiếp ảnh chân dung."),
        ],
      },
      {
        title: "Nói về sách và nhà văn",
        body: `${purple("novelist")}, ${purple("bestseller")}, ${purple("plot")}, ${purple("character")}, ${purple("publication")} và ${purple("extract")} là ngôn ngữ văn học phổ biến.`,
        examples: [
          ex("The novelist builds suspense through the plot.", "Nhà tiểu thuyết tạo hồi hộp qua cốt truyện."),
          ex("Read this extract before the seminar.", "Hãy đọc đoạn trích này trước buổi seminar."),
        ],
      },
      {
        title: "Phê bình và thủ công mỹ nghệ",
        body: `${purple("critic")}, ${purple("literary")} và ${purple("arts and crafts")} mở rộng cách bàn luận ngoài tranh/sách đơn thuần.`,
        examples: [
          ex("The critic praised the new exhibition.", "Nhà phê bình khen ngợi triển lãm mới."),
          ex("The market sells local arts and crafts.", "Chợ bán đồ thủ công mỹ nghệ địa phương."),
        ],
      },
    ],
    words: U19_WORDS,
    exercises: [
      mcq(
        19,
        1,
        "\"Still life\" trong hội họa thường là gì?",
        [
          { key: "a", label: "Tranh tĩnh vật" },
          { key: "b", label: "Tiểu thuyết trinh thám" },
          { key: "c", label: "Nhạc sống" },
          { key: "d", label: "Phim tài liệu" },
        ],
        "a",
      ),
      fillBlank(
        19,
        2,
        "That sculpture is a true ____.",
        "work of art",
        [
          { key: "a", label: "work of art" },
          { key: "b", label: "power cut" },
          { key: "c", label: "flat battery" },
          { key: "d", label: "sick leave" },
        ],
        "a",
      ),
      mcq(
        19,
        3,
        "Người viết tiểu thuyết gọi là gì?",
        [
          { key: "a", label: "novelist" },
          { key: "b", label: "sprinter" },
          { key: "c", label: "supervisor" },
          { key: "d", label: "migrant" },
        ],
        "a",
      ),
      fillBlank(
        19,
        4,
        "The book's ____ is full of unexpected twists.",
        "plot",
        [
          { key: "a", label: "plot" },
          { key: "b", label: "patio" },
          { key: "c", label: "porch" },
          { key: "d", label: "cue" },
        ],
        "a",
      ),
      mcq(
        19,
        5,
        "\"Fine art\" gần nghĩa nhất với đâu?",
        [
          { key: "a", label: "Mỹ thuật (hội họa, điêu khắc…)" },
          { key: "b", label: "Nghệ thuật nấu ăn nhanh" },
          { key: "c", label: "Phần mềm văn phòng" },
          { key: "d", label: "Luật giao thông" },
        ],
        "a",
      ),
      fillBlank(
        19,
        6,
        "Her first novel became a ____ within months.",
        "bestseller",
        [
          { key: "a", label: "bestseller" },
          { key: "b", label: "bungalow" },
          { key: "c", label: "bruise" },
          { key: "d", label: "drought" },
        ],
        "a",
      ),
      mcq(
        19,
        7,
        "Đoạn trích từ sách/bài viết thường gọi là gì?",
        [
          { key: "a", label: "extract" },
          { key: "b", label: "epidemic" },
          { key: "c", label: "executive" },
          { key: "d", label: "eruption" },
        ],
        "a",
      ),
      fillBlank(
        19,
        8,
        "Clay pots and bowls are examples of ____.",
        "ceramics",
        [
          { key: "a", label: "ceramics" },
          { key: "b", label: "casual acquaintances" },
          { key: "c", label: "civil wars" },
          { key: "d", label: "credit modules" },
        ],
        "a",
      ),
    ],
  }),
];
