export const CURATED_PRE_PROMPT_VI_46_60: Readonly<Record<string, string>> = {
  "ex-pre-46-1": "Ghép mỗi từ với nghĩa tiếng Việt.",
  "ex-pre-46-2": "___ (lịch trình) của chúng tôi gồm Hà Nội, Huế và Hội An.",
  "ex-pre-46-3": "Tôi cần ___ (đặt trước) hai vé tàu.",
  "ex-pre-46-4": "Hãy giữ ___ (mã đặt chỗ) cẩn thận.",
  "ex-pre-46-5": "Đọc ___ (chính sách hủy) trước khi thanh toán.",
  "ex-pre-46-6": "Vé này ___ (không hoàn tiền).",
  "ex-pre-46-7": "Một ___ (chuyến bay thẳng) tiết kiệm nhiều thời gian.",
  "ex-pre-46-8": "___ (hạn mức hành lý) của tôi là 20 kg.",
  "ex-pre-46-9": "Từ nào chỉ công ty dịch vụ tư vấn và đặt chuyến đi?",
  "ex-pre-46-10": "Chúng tôi có một ___ kéo dài sáu tiếng ở Doha.",
  "ex-pre-46-11": "Từ nào chỉ email xác nhận sau khi đặt thành công?",
  "ex-pre-46-12": "Gói du lịch gồm nhiều dịch vụ trọn bộ gọi là ___",
  "ex-pre-46-13": "Việc chọn chỗ ngồi trước chuyến đi gọi là ___",
  "ex-pre-46-14": "Nền tảng trực tuyến để đặt dịch vụ du lịch là ___",
  "ex-pre-47-1": "Ghép mỗi từ với nghĩa tiếng Việt.",
  "ex-pre-47-2": "Xuất trình ___ (thẻ lên máy bay) tại cửa.",
  "ex-pre-47-3": "Chất lỏng được kiểm tra tại ___ (khu kiểm tra an ninh).",
  "ex-pre-47-4": "Tôi luôn thấy lo lắng trong lúc ___ (cất cánh).",
  "ex-pre-47-5": "Phi công cảnh báo chúng tôi về ___ (nhiễu động không khí).",
  "ex-pre-47-6": "Đặt túi của bạn vào ___ (ngăn để đồ phía trên).",
  "ex-pre-47-7": "Máy bay di chuyển chậm ra ___ (đường băng).",
  "ex-pre-47-8": "Tôi bị ___ (lệch múi giờ) nặng sau chuyến đi.",
  "ex-pre-47-9": "Từ nào chỉ số cổng ra máy bay?",
  "ex-pre-47-10": "Chuyến bay bị hoãn gọi là ___",
  "ex-pre-47-11": "Lỡ chuyến nối tiếp gọi là ___",
  "ex-pre-47-12": "Nhân viên kiểm tra hành lý tại hải quan là ___",
  "ex-pre-47-13": "Hàng chờ làm thủ tục nhập cảnh gọi là ___",
  "ex-pre-47-14": "Hành lý xách tay mang lên cabin gọi là ___",
  "ex-pre-48-1": "Ghép mỗi từ với nghĩa tiếng Việt.",
  "ex-pre-48-2": "Vui lòng để lại chìa khóa ở ___ (quầy lễ tân).",
  "ex-pre-48-3": "Xin lỗi, tối nay chúng tôi không còn ___ (phòng trống).",
  "ex-pre-48-4": "Khách sạn ___ (kín phòng) vào cuối tuần này.",
  "ex-pre-48-5": "Chúng tôi gọi bánh sandwich qua ___ (dịch vụ phòng).",
  "ex-pre-48-6": "___ (bộ phận dọn phòng) dọn phòng vào buổi trưa.",
  "ex-pre-48-7": "Cho chúng tôi xin ___ (hóa đơn) được không?",
  "ex-pre-48-8": "___ (giờ trả phòng) là 11 giờ sáng.",
  "ex-pre-48-9": "Phòng dành cho một người gọi là ___",
  "ex-pre-48-10": "Cuộc gọi báo thức từ khách sạn gọi là ___",
  "ex-pre-48-11": "Thực đơn chọn sẵn theo suất gọi là ___",
  "ex-pre-48-12": "Món ăn kèm gọi là ___",
  "ex-pre-48-13": "Tiền boa cho nhân viên phục vụ gọi là ___",
  "ex-pre-48-14": "Được tặng miễn phí kèm dịch vụ gọi là ___",
  "ex-pre-49-1": "Ghép mỗi từ với nghĩa tiếng Việt.",
  "ex-pre-49-2": "Anh ấy uống một ___ (espresso) mỗi sáng.",
  "ex-pre-49-3": "Tôi thường gọi một ___ (latte) đá.",
  "ex-pre-49-4": "Cô ấy thích ___ (cappuccino) với quế.",
  "ex-pre-49-5": "___ (nhân viên pha chế) gợi ý một loại pha trộn mới.",
  "ex-pre-49-6": "Cho tôi đựng cái này trong ___ (ly mang đi) được không?",
  "ex-pre-49-7": "Hôm nay chúng tôi quyết định ___ (dùng tại chỗ).",
  "ex-pre-49-8": "Buổi tối tôi uống ___ (cà phê tách caffeine).",
  "ex-pre-49-9": "Cà phê espresso pha thêm nước nóng gọi là ___",
  "ex-pre-49-10": "Sữa đậu nành thay sữa bò gọi là ___",
  "ex-pre-49-11": "Độ mịn của bột cà phê sau khi xay gọi là ___",
  "ex-pre-49-12": "Việc rót thêm đồ uống gọi là ___",
  "ex-pre-49-13": "Góc ngồi ấm cúng, dễ chịu trong quán gọi là ___",
  "ex-pre-49-14": "Dịch vụ wifi miễn phí cho khách gọi là ___",
  "ex-pre-50-1": "Ghép mỗi từ với nghĩa tiếng Việt.",
  "ex-pre-50-2": "Nhà hát opera là ___ (địa danh biểu tượng) của thành phố.",
  "ex-pre-50-3": "Chúng tôi tham gia một ___ (tour có hướng dẫn) ở phố cổ.",
  "ex-pre-50-4": "Lấy một ___ (bản đồ thành phố) ở sảnh khách sạn.",
  "ex-pre-50-5": "Bảo tàng có ___ (thuyết minh tự động) bằng tiếng Anh.",
  "ex-pre-50-6": "Hoàng hôn nhìn từ ___ (điểm ngắm cảnh) này rất đẹp.",
  "ex-pre-50-7": "Chúng tôi đi dạo quanh ___ (khu phố cổ) suốt buổi sáng.",
  "ex-pre-50-8": "Du khách ___ (xếp hàng) trước khi cổng mở.",
  "ex-pre-50-9": "Vé gộp vào nhiều bảo tàng gọi là ___",
  "ex-pre-50-10": "Hướng dẫn viên bản địa am hiểu vùng gọi là ___",
  "ex-pre-50-11": "Chuyến khám phá đi bộ theo tuyến gọi là ___",
  "ex-pre-50-12": "Chuyến đi về trong ngày gọi là ___",
  "ex-pre-50-13": "Khung giờ mở cửa tham quan gọi là ___",
  "ex-pre-50-14": "Điểm chụp hình đẹp phổ biến gọi là ___",
  "ex-pre-51-1": "Ghép mỗi từ với nghĩa tiếng Việt.",
  "ex-pre-51-2": "Họ ở tại một ___ (khu nghỉ dưỡng ven biển) yên tĩnh.",
  "ex-pre-51-3": "___ (bờ biển) ở đây rất nhiều đá.",
  "ex-pre-51-4": "Trẻ em chơi trên ___ (bãi biển cát).",
  "ex-pre-51-5": "Bôi ___ (kem chống nắng) mỗi hai tiếng.",
  "ex-pre-51-6": "___ (nhân viên cứu hộ) thổi còi.",
  "ex-pre-51-7": "___ (thủy triều) dâng cao chiều nay.",
  "ex-pre-51-8": "Chúng tôi thử ___ (lặn ống thở) gần rạn san hô.",
  "ex-pre-51-9": "Việc nằm tắm nắng trên bãi biển gọi là ___",
  "ex-pre-51-10": "Khăn lớn dùng tại bãi biển gọi là ___",
  "ex-pre-51-11": "Cầu tàu nhô ra mặt nước gọi là ___",
  "ex-pre-51-12": "Gió biển mát thổi từ mặt nước gọi là ___",
  "ex-pre-51-13": "Thuê ô che nắng ở bãi biển gọi là ___",
  "ex-pre-51-14": "Chuyến đi biển bằng thuyền gọi là ___",
  "ex-pre-52-1": "Ghép mỗi từ với nghĩa tiếng Việt.",
  "ex-pre-52-2": "___ (tiêu đề) khiến nhiều độc giả sốc.",
  "ex-pre-52-3": "Bài phỏng vấn của cô ấy xuất hiện trên ___ (trang nhất).",
  "ex-pre-52-4": "Kênh chuyển sang ___ (tin nóng).",
  "ex-pre-52-5": "___ (người dẫn thời sự) vẫn bình tĩnh trong lúc cập nhật.",
  "ex-pre-52-6": "Chúng tôi xem một ___ (phim tài liệu) về sinh vật biển.",
  "ex-pre-52-7": "Tôi xem ___ (bản tin thời tiết) mỗi sáng.",
  "ex-pre-52-8": "Cuộc tranh luận sẽ ___ (phát sóng trực tiếp) tối nay.",
  "ex-pre-52-9": "Người viết chuyên mục định kỳ gọi là ___",
  "ex-pre-52-10": "Bài xã luận thể hiện quan điểm tòa soạn gọi là ___",
  "ex-pre-52-11": "Báo khổ nhỏ thiên về tin giật gân gọi là ___",
  "ex-pre-52-12": "Báo chính luận khổ lớn, nội dung nghiêm túc gọi là ___",
  "ex-pre-52-13": "Bản tin ngắn cập nhật theo khung giờ gọi là ___",
  "ex-pre-52-14": "Thiết bị điều khiển tivi từ xa gọi là ___",
  "ex-pre-53-1": "Ghép mỗi từ với nghĩa tiếng Việt.",
  "ex-pre-53-2": "Hãy ___ (bấm số) lại lần nữa.",
  "ex-pre-53-3": "Tôi để lại lời nhắn trong ___ (hộp thư thoại) của bạn.",
  "ex-pre-53-4": "Tôi không có ___ (sóng) trong tầng hầm này.",
  "ex-pre-53-5": "Sáng nay tôi thấy ___ (cuộc gọi nhỡ) của bạn.",
  "ex-pre-53-6": "Tôi sẽ ___ (gọi lại) sau mười phút.",
  "ex-pre-53-7": "Nhắn cho tôi một ___ (tin nhắn) khi bạn đến.",
  "ex-pre-53-8": "Anh ấy gửi một ___ (tin nhắn thoại) thay vì gõ chữ.",
  "ex-pre-53-9": "Cuộc gọi nhóm với nhiều người gọi là ___",
  "ex-pre-53-10": "Biểu tượng cảm xúc dùng khi nhắn tin gọi là ___",
  "ex-pre-53-11": "Tính năng tự sửa từ khi gõ gọi là ___",
  "ex-pre-53-12": "Đoạn trò chuyện có nhiều thành viên gọi là ___",
  "ex-pre-53-13": "Dấu hiệu cho biết tin nhắn đã được đọc gọi là ___",
  "ex-pre-53-14": "Trạng thái pin yếu gần hết gọi là ___",
  "ex-pre-54-1": "Ghép mỗi từ với nghĩa tiếng Việt.",
  "ex-pre-54-2": "Văn phòng vẫn dùng máy tính ___ (để bàn).",
  "ex-pre-54-3": "Tôi mang ___ (máy tính xách tay) đến lớp mỗi ngày.",
  "ex-pre-54-4": "___ (bàn phím) này êm và mượt.",
  "ex-pre-54-5": "Một ___ (màn hình) thứ hai giúp tăng năng suất.",
  "ex-pre-54-6": "Sao lưu ảnh vào ___ (ổ cứng) ngoài.",
  "ex-pre-54-7": "Hãy thử ___ (khởi động lại) máy tính trước.",
  "ex-pre-54-8": "Luôn tạo một ___ (tệp sao lưu) trước khi chỉnh sửa lớn.",
  "ex-pre-54-9": "Chuột điều khiển con trỏ trên màn hình gọi là ___",
  "ex-pre-54-10": "Cổng cắm USB để kết nối thiết bị gọi là ___",
  "ex-pre-54-11": "Tắt máy hoàn toàn gọi là ___",
  "ex-pre-54-12": "Sao chép và dán dữ liệu gọi là ___",
  "ex-pre-54-13": "Độ phân giải hiển thị của màn hình gọi là ___",
  "ex-pre-54-14": "Thư mục chứa tệp tin gọi là ___",
  "ex-pre-55-1": "Ghép mỗi từ với nghĩa tiếng Việt.",
  "ex-pre-55-2": "___ (hộp thư đến) của tôi đầy email chưa đọc.",
  "ex-pre-55-3": "Kiểm tra ___ (thư mục spam) để tìm thư bị thiếu.",
  "ex-pre-55-4": "Tôi quên đính kèm ___ (tệp đính kèm).",
  "ex-pre-55-5": "Viết một ___ (dòng tiêu đề) rõ ràng.",
  "ex-pre-55-6": "Hãy ___ (gửi kèm CC) cho trưởng nhóm của bạn.",
  "ex-pre-55-7": "___ (liên kết) dẫn đến trang chủ của chúng tôi.",
  "ex-pre-55-8": "Tôi mở quá nhiều ___ (thẻ trình duyệt).",
  "ex-pre-55-9": "Gửi bản sao ẩn danh sách người nhận gọi là ___",
  "ex-pre-55-10": "Hủy đăng ký nhận tin gọi là ___",
  "ex-pre-55-11": "Công cụ tìm kiếm thông tin trực tuyến gọi là ___",
  "ex-pre-55-12": "Tải dữ liệu từ internet về thiết bị gọi là ___",
  "ex-pre-55-13": "Thao tác đặt lại mật khẩu gọi là ___",
  "ex-pre-55-14": "Tùy chọn kiểm soát quyền riêng tư gọi là ___",
  "ex-pre-56-1": "Ghép mỗi từ với nghĩa tiếng Việt.",
  "ex-pre-56-2": "___ (trộm cắp) đã gia tăng ở khu vực này.",
  "ex-pre-56-3": "___ (vụ cướp) xảy ra vào ban đêm.",
  "ex-pre-56-4": "Cảnh sát điều tra một ___ (vụ đột nhập trộm) gần đó.",
  "ex-pre-56-5": "___ (nghi phạm) bị ghi hình bởi camera.",
  "ex-pre-56-6": "Một ___ (nhân chứng) đưa ra lời khai chi tiết.",
  "ex-pre-56-7": "___ (chứng cứ) ADN làm thay đổi vụ án.",
  "ex-pre-56-8": "Cảnh sát quyết định ___ (bắt giữ) nghi phạm.",
  "ex-pre-56-9": "Dấu vân tay nhận dạng cá nhân gọi là ___",
  "ex-pre-56-10": "Thám tử hoặc điều tra viên hình sự gọi là ___",
  "ex-pre-56-11": "Án phạt tù do tòa tuyên gọi là ___",
  "ex-pre-56-12": "Vô tội, không phạm hành vi bị cáo buộc gọi là ___",
  "ex-pre-56-13": "Hành vi lừa đảo để chiếm đoạt tài sản gọi là ___",
  "ex-pre-56-14": "Ăn cắp hàng hóa trong cửa hàng gọi là ___",
  "ex-pre-57-1": "Ghép mỗi từ với nghĩa tiếng Việt.",
  "ex-pre-57-2": "___ (cuộc bầu cử) toàn quốc diễn ra vào tháng sau.",
  "ex-pre-57-3": "___ (chiến dịch tranh cử) của cô ấy tập trung vào cải cách giáo dục.",
  "ex-pre-57-4": "Mỗi ___ (ứng cử viên) có một bài phát biểu ngắn.",
  "ex-pre-57-5": "___ (cử tri) trẻ quan tâm đến chính sách khí hậu.",
  "ex-pre-57-6": "Bỏ ___ (phiếu bầu) của bạn vào hòm.",
  "ex-pre-57-7": "Đạo luật được tranh luận trong ___ (nghị viện).",
  "ex-pre-57-8": "___ (thủ tướng) phát biểu trước toàn dân.",
  "ex-pre-57-9": "Cuộc tranh luận chính thức về vấn đề công gọi là ___",
  "ex-pre-57-10": "Cải cách hệ thống thuế gọi là ___",
  "ex-pre-57-11": "Đảng đối lập với chính quyền đương nhiệm gọi là ___",
  "ex-pre-57-12": "Liên minh giữa nhiều đảng để cầm quyền gọi là ___",
  "ex-pre-57-13": "Cuộc tuần hành biểu tình ôn hòa gọi là ___",
  "ex-pre-57-14": "Khảo sát ý kiến dư luận gọi là ___",
  "ex-pre-58-1": "Ghép mỗi từ với nghĩa tiếng Việt.",
  "ex-pre-58-2": "___ (nóng lên toàn cầu) ảnh hưởng đến thời tiết trên toàn thế giới.",
  "ex-pre-58-3": "CO2 là một ___ (khí nhà kính) chủ yếu.",
  "ex-pre-58-4": "Đi tàu giúp giảm ___ (dấu chân carbon) của bạn.",
  "ex-pre-58-5": "___ (năng lượng tái tạo) đang phát triển nhanh.",
  "ex-pre-58-6": "Chúng tôi lắp ___ (tấm pin mặt trời) trên mái nhà.",
  "ex-pre-58-7": "___ (nạn phá rừng) đe dọa đa dạng sinh học.",
  "ex-pre-58-8": "___ (băng tan) làm dâng mực nước biển.",
  "ex-pre-58-9": "Mực nước biển dâng cao theo thời gian gọi là ___",
  "ex-pre-58-10": "Thời tiết cực đoan khó dự đoán gọi là ___",
  "ex-pre-58-11": "Hạn hán kéo dài thiếu nước nghiêm trọng gọi là ___",
  "ex-pre-58-12": "Phương tiện chạy điện thay nhiên liệu hóa thạch gọi là ___",
  "ex-pre-58-13": "Mục tiêu phát thải ròng bằng không gọi là ___",
  "ex-pre-58-14": "Thuế áp lên lượng phát thải carbon gọi là ___",
  "ex-pre-59-1": "Ghép mỗi từ với nghĩa tiếng Việt.",
  "ex-pre-59-2": "___ (cuộc xung đột) đã kéo dài nhiều năm.",
  "ex-pre-59-3": "Cả hai bên đồng ý một ___ (thỏa thuận ngừng bắn).",
  "ex-pre-59-4": "Trại này che chở nhiều ___ (người tị nạn).",
  "ex-pre-59-5": "Quân đội ___ (sơ tán) dân làng trong đêm.",
  "ex-pre-59-6": "Các đội y tế làm việc gần ___ (tiền tuyến).",
  "ex-pre-59-7": "___ (cuộc không kích) làm hư hại nhiều tòa nhà.",
  "ex-pre-59-8": "___ (đàm phán hòa bình) được nối lại trong tuần này.",
  "ex-pre-59-9": "Người thương vong trong xung đột gọi là ___",
  "ex-pre-59-10": "Vũ khí dùng để tấn công hoặc phòng vệ gọi là ___",
  "ex-pre-59-11": "Nhóm có trang bị vũ trang gọi là ___",
  "ex-pre-59-12": "Con tin bị bắt để gây áp lực gọi là ___",
  "ex-pre-59-13": "Tội ác chiến tranh vi phạm luật quốc tế gọi là ___",
  "ex-pre-59-14": "Sang chấn tâm lý sau biến cố nghiêm trọng gọi là ___",
  "ex-pre-60-1": "Ghép mỗi từ với nghĩa tiếng Việt.",
  "ex-pre-60-2": "Cô ấy luôn ___ (đúng giờ) trong các cuộc họp.",
  "ex-pre-60-3": "Chúng ta phải đáp ứng ___ (hạn chót) của dự án.",
  "ex-pre-60-4": "___ (lịch trình) của tôi kín mít tuần này.",
  "ex-pre-60-5": "Kiểm tra ___ (thời gian biểu) xe buýt trước khi đi.",
  "ex-pre-60-6": "Tàu đến ___ (đúng giờ).",
  "ex-pre-60-7": "Vui lòng đặt ___ (trước) cho cuối tuần.",
  "ex-pre-60-8": "Kẹt xe nặng gây ra một ___ (sự trì hoãn) dài.",
  "ex-pre-60-9": "Hoãn lại sang thời điểm khác gọi là ___",
  "ex-pre-60-10": "Trong lúc đó, ở thời điểm song song gọi là ___",
  "ex-pre-60-11": "Cuối cùng sau nhiều chờ đợi gọi là ___",
  "ex-pre-60-12": "Hiện tại, vào lúc này gọi là ___",
  "ex-pre-60-13": "Thời gian rảnh ngoài việc chính gọi là ___",
  "ex-pre-60-14": "Chế độ chỉnh đồng hồ theo mùa để tận dụng ánh sáng gọi là ___",
};
