export const CURATED_PRE_PROMPT_VI_16_30: Readonly<Record<string, string>> = {
  "ex-pre-16-1": "Ghép mỗi từ với nghĩa tiếng Việt.",
  "ex-pre-16-2": "Tôi thường ___ (thức dậy) trước lúc mặt trời mọc.",
  "ex-pre-16-3": "Nhân viên phải ___ (chấm công vào ca) trước 8:30.",
  "ex-pre-16-4": "Tôi ___ (nghỉ giải lao) sau hai giờ học.",
  "ex-pre-16-5": "Tôi ___ (làm việc lặt vặt) sau bữa trưa thứ Bảy.",
  "ex-pre-16-6": "___ (chuẩn bị sẵn đồ ăn) giúp tiết kiệm thời gian ngày bận.",
  "ex-pre-16-7": "Tôi đọc sách để ___ (thư giãn) vào buổi tối.",
  "ex-pre-16-8": "Tôi ___ (ngủ quá giờ) và lỡ chuyến xe buýt đầu.",
  "ex-pre-16-9": "Từ nào mô tả tình trạng bận rộn và gấp gáp?",
  "ex-pre-16-10": "Từ nào nghĩa là hoãn chuông báo thức thêm vài phút?",
  "ex-pre-16-11": "Cụm nào nghĩa là làm việc nhà thường ngày?",
  "ex-pre-16-12": "\"To ___\" nghĩa là ngừng ngủ và thức dậy.",
  "ex-pre-16-13": "Từ nào chỉ ca làm việc?",
  "ex-pre-16-14": "Người luôn đến đúng giờ thì ___",
  "ex-pre-17-1": "Ghép mỗi từ với nghĩa tiếng Việt.",
  "ex-pre-17-2": "Tôi làm việc ở ___ (trung tâm) nhưng sống ngoài thành phố.",
  "ex-pre-17-3": "Họ mua một ___ (nhà riêng tách biệt) năm ngoái.",
  "ex-pre-17-4": "___ (hóa đơn điện nước) cao hơn vào mùa đông.",
  "ex-pre-17-5": "Chúng tôi mất một tháng để ___ (ổn định ở nơi mới).",
  "ex-pre-17-6": "Hàng xóm mới sẽ ___ (dọn vào ở) tuần sau.",
  "ex-pre-17-7": "Giờ tôi đã ___ (thấy thoải mái như ở nhà) tại thành phố này.",
  "ex-pre-17-8": "___ (tiền thuê nhà) ở khu này đã tăng nhiều.",
  "ex-pre-17-9": "Từ nào chỉ người thuê nhà?",
  "ex-pre-17-10": "Từ nào chỉ chủ nhà cho thuê?",
  "ex-pre-17-11": "Tính từ nào nghĩa là thuận tiện?",
  "ex-pre-17-12": "Tính từ nào nghĩa là ồn ào?",
  "ex-pre-17-13": "Cụm nào chỉ tòa chung cư?",
  "ex-pre-17-14": "Cụm nào chỉ tiện ích địa phương như công viên, trường học?",
  "ex-pre-18-1": "Ghép mỗi từ với nghĩa tiếng Việt.",
  "ex-pre-18-2": "Chìa khóa của cô ấy ở ___ (ngăn kéo) trên cùng.",
  "ex-pre-18-3": "Tôi để sách lại lên ___ (kệ).",
  "ex-pre-18-4": "Hãy ___ (dọn gọn) phòng khách trước khi khách đến.",
  "ex-pre-18-5": "Tôi ___ (lau bề mặt) bàn bếp mỗi tối.",
  "ex-pre-18-6": "Chúng tôi phát hiện chỗ ___ (rò rỉ) dưới bồn rửa.",
  "ex-pre-18-7": "Dùng ___ (dây điện nối dài) cho quạt.",
  "ex-pre-18-8": "Tủ lạnh là một ___ (thiết bị gia dụng) thiết yếu.",
  "ex-pre-18-9": "Từ nào chỉ ổ cắm điện trên tường?",
  "ex-pre-18-10": "Từ nào nghĩa là sạch bong không tì vết?",
  "ex-pre-18-11": "Từ nào chỉ sự bừa bộn?",
  "ex-pre-18-12": "Từ nào chỉ cây lau nhà?",
  "ex-pre-18-13": "Cụm nào chỉ giỏ đựng quần áo bẩn?",
  "ex-pre-18-14": "Từ nào chỉ máy rửa chén?",
  "ex-pre-19-1": "Ghép mỗi từ với nghĩa tiếng Việt.",
  "ex-pre-19-2": "Tôi đặt một ___ (ngân sách) hằng tuần cho thực phẩm.",
  "ex-pre-19-3": "Đi lại là ___ (khoản chi) lớn nhất hằng tháng của tôi.",
  "ex-pre-19-4": "Anh ấy đang cố trả hết ___ (khoản nợ).",
  "ex-pre-19-5": "Tôi cần ___ (cắt giảm) việc ăn ngoài.",
  "ex-pre-19-6": "Tôi ___ (chuyển tiền) cho bố mẹ mỗi tháng.",
  "ex-pre-19-7": "Một ___ (quỹ dự phòng khẩn cấp) giúp bạn an tâm.",
  "ex-pre-19-8": "Chiếc áo khoác này là một ___ (món mua hời) thực sự.",
  "ex-pre-19-9": "Từ nào chỉ khoản tiền vào bạn nhận được?",
  "ex-pre-19-10": "Cụm nào chỉ quỹ dự phòng khi có việc khẩn cấp?",
  "ex-pre-19-11": "Động từ nào nghĩa là có khả năng chi trả?",
  "ex-pre-19-12": "Tính từ nào nghĩa là bị bán quá đắt?",
  "ex-pre-19-13": "Cụm nào chỉ chi phí sinh hoạt?",
  "ex-pre-19-14": "Từ nào chỉ khoản trả góp theo kỳ?",
  "ex-pre-20-1": "Ghép mỗi từ với nghĩa tiếng Việt.",
  "ex-pre-20-2": "Tôi ở nhà vì bị ___ (đau họng).",
  "ex-pre-20-3": "___ (chảy nước mũi) thường gặp khi trời lạnh.",
  "ex-pre-20-4": "Cô ấy mất một tuần để ___ (hồi phục) hoàn toàn.",
  "ex-pre-20-5": "Bạn nên ___ (nghỉ ngơi hồi sức) vào cuối tuần này.",
  "ex-pre-20-6": "Nhớ ___ (uống thuốc) sau bữa ăn.",
  "ex-pre-20-7": "Một ___ (chế độ ăn cân bằng) hỗ trợ sức khỏe tổng thể.",
  "ex-pre-20-8": "Tôi đi ___ (khám định kỳ) hai lần một năm.",
  "ex-pre-20-9": "Từ nào là đơn thuốc bác sĩ đưa cho bệnh nhân?",
  "ex-pre-20-10": "Từ nào mang nghĩa mất nước?",
  "ex-pre-20-11": "Động từ nào nghĩa là kê đơn thuốc?",
  "ex-pre-20-12": "Tính từ nào nghĩa là mãn tính, kéo dài?",
  "ex-pre-20-13": "Cụm nào chỉ huyết áp?",
  "ex-pre-20-14": "Cụm nào chỉ sức khỏe tinh thần?",
  "ex-pre-21-1": "Ghép mỗi từ với nghĩa tiếng Việt.",
  "ex-pre-21-2": "___ (ống tay áo) quá dài với tôi.",
  "ex-pre-21-3": "___ (chất liệu vải) này mềm và thoáng.",
  "ex-pre-21-4": "Tôi thích ___ (vải cotton) khi trời nóng.",
  "ex-pre-21-5": "Chiếc áo ___ (len) này rất ấm.",
  "ex-pre-21-6": "Tôi có thể ___ (thử) chiếc áo khoác này không?",
  "ex-pre-21-7": "Bạn nên ___ (mặc nhiều lớp) quần áo vào mùa đông.",
  "ex-pre-21-8": "___ (trang phục trang trọng) là bắt buộc cho sự kiện.",
  "ex-pre-21-9": "Từ nào chỉ phần cổ của áo?",
  "ex-pre-21-10": "Tính từ nào nghĩa là rộng, không ôm sát?",
  "ex-pre-21-11": "Tính từ nào nghĩa là ôm sát người?",
  "ex-pre-21-12": "Tính từ nào nghĩa là trơn, không họa tiết?",
  "ex-pre-21-13": "Tính từ nào nghĩa là có họa tiết?",
  "ex-pre-21-14": "Cụm nào chỉ trang phục thường ngày?",
  "ex-pre-22-1": "Ghép mỗi từ với nghĩa tiếng Việt.",
  "ex-pre-22-2": "Cỡ này vẫn ___ (còn hàng).",
  "ex-pre-22-3": "Xin lỗi, màu đen đã ___ (hết hàng).",
  "ex-pre-22-4": "Tôi dùng một ___ (mã giảm giá) khi thanh toán.",
  "ex-pre-22-5": "Chúng tôi mua áo khoác trong ___ (đợt giảm giá theo mùa).",
  "ex-pre-22-6": "Kiểm tra ___ (bảng kích cỡ) trước khi đặt hàng online.",
  "ex-pre-22-7": "Tôi có thể ___ (thanh toán bằng thẻ) ở đây không?",
  "ex-pre-22-8": "___ (giữ lại hóa đơn) phòng khi bạn cần hoàn tiền.",
  "ex-pre-22-9": "Cụm nào nghĩa là đã hết hàng?",
  "ex-pre-22-10": "Từ nào mô tả món mua không nằm trong kế hoạch?",
  "ex-pre-22-11": "Tính từ nào nghĩa là đúng xu hướng?",
  "ex-pre-22-12": "Tính từ nào nghĩa là không lỗi mốt?",
  "ex-pre-22-13": "Tính từ nào nghĩa là giá phải chăng?",
  "ex-pre-22-14": "Động từ nào nghĩa là đổi hàng?",
  "ex-pre-23-1": "Ghép mỗi từ với nghĩa tiếng Việt.",
  "ex-pre-23-2": "Tôi chỉ cần một ___ (giỏ xách) cho vài món.",
  "ex-pre-23-3": "Lấy một ___ (xe đẩy) nếu bạn mua nhiều.",
  "ex-pre-23-4": "Chúng tôi ___ (xem hàng) nửa tiếng.",
  "ex-pre-23-5": "Người mua thông minh ___ (so sánh giá) trước.",
  "ex-pre-23-6": "Tôi liên hệ ___ (bộ phận chăm sóc khách hàng) vì sản phẩm bị hỏng.",
  "ex-pre-23-7": "Nhiều người ___ (mua sắm trực tuyến) sau giờ làm.",
  "ex-pre-23-8": "Tôi đặt một ___ (khung giờ giao hàng) buổi tối.",
  "ex-pre-23-9": "Từ nào chỉ xe đẩy lớn trong siêu thị?",
  "ex-pre-23-10": "Cụm nào nghĩa là bán hết hàng?",
  "ex-pre-23-11": "Cụm nào chỉ ưu đãi đặc biệt?",
  "ex-pre-23-12": "Cụm nào chỉ sản phẩm bị lỗi?",
  "ex-pre-23-13": "Cụm nào nghĩa là trả lại hàng?",
  "ex-pre-23-14": "Động từ nào nghĩa là xếp hàng?",
  "ex-pre-24-1": "Ghép mỗi từ với nghĩa tiếng Việt.",
  "ex-pre-24-2": "Trứng giàu ___ (chất đạm).",
  "ex-pre-24-3": "Rau cung cấp nhiều ___ (chất xơ).",
  "ex-pre-24-4": "Hãy hạn chế lượng ___ (thực phẩm chế biến sẵn).",
  "ex-pre-24-5": "Hãy kiểm soát ___ (kích cỡ khẩu phần) nếu muốn tránh ăn quá nhiều.",
  "ex-pre-24-6": "Chúng tôi giữ ___ (đồ ăn thừa) cho bữa trưa.",
  "ex-pre-24-7": "Tôi thường ăn trái cây làm ___ (bữa phụ).",
  "ex-pre-24-8": "Cô ấy bị ___ (dị ứng thực phẩm) với đậu phộng.",
  "ex-pre-24-9": "Cụm nào chỉ đồ ăn chế biến sẵn?",
  "ex-pre-24-10": "Từ nào mang nghĩa nhạt, thiếu vị?",
  "ex-pre-24-11": "Tính từ nào nghĩa là giàu dinh dưỡng?",
  "ex-pre-24-12": "Tính từ nào nghĩa là nhiều dầu mỡ?",
  "ex-pre-24-13": "Tính từ nào chỉ người ăn thuần chay (tránh cả sữa, trứng)?",
  "ex-pre-24-14": "Từ nào chỉ ngũ cốc nguyên cám?",
  "ex-pre-25-1": "Ghép mỗi từ với nghĩa tiếng Việt.",
  "ex-pre-25-2": "___ (băm nhỏ) hành thật nhuyễn.",
  "ex-pre-25-3": "___ (thái lát) cà chua thật mỏng.",
  "ex-pre-25-4": "Chúng tôi ___ (hấp) rau để giữ dưỡng chất.",
  "ex-pre-25-5": "Để món súp ___ (đun liu riu) trong 20 phút.",
  "ex-pre-25-6": "Hãy ___ (nêm nếm) món súp trước khi dọn ra.",
  "ex-pre-25-7": "___ (ướp gia vị) thịt bò qua đêm.",
  "ex-pre-25-8": "___ (nguyên liệu) tươi tạo khác biệt lớn.",
  "ex-pre-25-9": "Động từ nào nghĩa là đun liu riu?",
  "ex-pre-25-10": "Từ nào mô tả món ăn chưa chín kỹ?",
  "ex-pre-25-11": "Từ nào mô tả món ăn chín quá, bị khô?",
  "ex-pre-25-12": "Động từ nào nghĩa là bào nhỏ?",
  "ex-pre-25-13": "Động từ nào nghĩa là nướng lò?",
  "ex-pre-25-14": "Cụm nào chỉ chảo rán?",
  "ex-pre-26-1": "Ghép mỗi từ với nghĩa tiếng Việt.",
  "ex-pre-26-2": "___ (đường chân trời) trông tuyệt đẹp lúc hoàng hôn.",
  "ex-pre-26-3": "Chúng tôi bị kẹt trong một ___ (vụ kẹt xe).",
  "ex-pre-26-4": "Thành phố có ___ (hoạt động về đêm) sôi động.",
  "ex-pre-26-5": "Xe không được phép vào ___ (khu đi bộ) này.",
  "ex-pre-26-6": "___ (ô nhiễm) không khí tệ hơn vào mùa đông.",
  "ex-pre-26-7": "Xin đừng đi vào ___ (làn xe đạp).",
  "ex-pre-26-8": "Hầu hết văn phòng ở ___ (trung tâm thành phố).",
  "ex-pre-26-9": "Cụm nào chỉ tình trạng kẹt xe?",
  "ex-pre-26-10": "Tính từ nào nghĩa là sôi động, đầy sức sống?",
  "ex-pre-26-11": "Tính từ nào nghĩa là đông đúc?",
  "ex-pre-26-12": "Cụm nào chỉ giao thông công cộng?",
  "ex-pre-26-13": "Từ nào chỉ tòa nhà cao tầng?",
  "ex-pre-26-14": "Cụm nào chỉ giờ cao điểm?",
  "ex-pre-27-1": "Ghép mỗi từ với nghĩa tiếng Việt.",
  "ex-pre-27-2": "Dụng cụ được cất trong ___ (nhà kho).",
  "ex-pre-27-3": "Gia đình anh ấy sở hữu một ___ (vườn cây) xoài.",
  "ex-pre-27-4": "Bò gặm cỏ trên ___ (đồng cỏ chăn thả).",
  "ex-pre-27-5": "Nông dân bận rộn nhất trong ___ (mùa thu hoạch).",
  "ex-pre-27-6": "Chúng tôi mua ___ (nông sản tươi) từ nông trại địa phương.",
  "ex-pre-27-7": "Tôi dậy sớm để ngắm ___ (bình minh).",
  "ex-pre-27-8": "Anh ấy chuyển về ___ (vùng nông thôn).",
  "ex-pre-27-9": "Từ nào chỉ vườn cây ăn quả?",
  "ex-pre-27-10": "Tính từ nào nghĩa là xa xôi, hẻo lánh?",
  "ex-pre-27-11": "Tính từ nào nghĩa là yên bình?",
  "ex-pre-27-12": "Tính từ nào nghĩa là gắn kết chặt chẽ?",
  "ex-pre-27-13": "Cụm nào chỉ hội chợ làng?",
  "ex-pre-27-14": "Cụm nào chỉ nông sản tươi?",
  "ex-pre-28-1": "Ghép mỗi từ với nghĩa tiếng Việt.",
  "ex-pre-28-2": "Kiểm tra ___ (bảng giờ tàu) trước khi rời nhà.",
  "ex-pre-28-3": "Tàu của chúng tôi rời ___ (sân ga) số 2 trong mười phút.",
  "ex-pre-28-4": "Có một ___ (sự chậm trễ) 20 phút do mưa.",
  "ex-pre-28-5": "Tôi mua một ___ (vé một chiều) đi Huế.",
  "ex-pre-28-6": "Một ___ (vé khứ hồi) thường rẻ hơn.",
  "ex-pre-28-7": "Hành khách nên ___ (lên tàu) nhanh chóng.",
  "ex-pre-28-8": "Tôi lỡ ___ (chuyến nối) vì bị chậm.",
  "ex-pre-28-9": "Cụm nào chỉ vé khứ hồi?",
  "ex-pre-28-10": "Động từ nào nghĩa là xuống tàu/xe?",
  "ex-pre-28-11": "Cụm nào chỉ vé tháng đi lại thường xuyên?",
  "ex-pre-28-12": "Từ nào chỉ toa tàu?",
  "ex-pre-28-13": "Cụm nào chỉ khung giờ cao điểm?",
  "ex-pre-28-14": "Cụm nào chỉ đặt trước chỗ ngồi?",
  "ex-pre-29-1": "Ghép mỗi từ với nghĩa tiếng Việt.",
  "ex-pre-29-2": "Đi thẳng qua ___ (vòng xuyến).",
  "ex-pre-29-3": "Bạn không được vượt ___ (giới hạn tốc độ) trên đường này.",
  "ex-pre-29-4": "Dừng lại ở ___ (vạch sang đường cho người đi bộ).",
  "ex-pre-29-5": "Chúng tôi phải dừng vì một ___ (lốp xe xẹp).",
  "ex-pre-29-6": "Nhớ ___ (bật xi nhan) trước khi rẽ.",
  "ex-pre-29-7": "Đi theo các biển ___ (đường vòng) một cách cẩn thận.",
  "ex-pre-29-8": "Mọi người phải thắt ___ (dây an toàn).",
  "ex-pre-29-9": "Từ nào chỉ vòng xuyến?",
  "ex-pre-29-10": "Cụm nào nghĩa là đỗ xe sai quy định?",
  "ex-pre-29-11": "Động từ nào nghĩa là vượt xe?",
  "ex-pre-29-12": "Từ nào chỉ công trình sửa đường?",
  "ex-pre-29-13": "Cụm nào chỉ tiền phạt giao thông?",
  "ex-pre-29-14": "Cụm nào chỉ trạm xăng?",
  "ex-pre-30-1": "Ghép mỗi từ với nghĩa tiếng Việt.",
  "ex-pre-30-2": "Hãy dùng ___ (lối thoát hiểm) khi có cháy.",
  "ex-pre-30-3": "Cẩn thận: ___ (sàn trơn trượt) sau khi lau.",
  "ex-pre-30-4": "Đừng chạm vào tường, ___ (sơn còn ướt).",
  "ex-pre-30-5": "___ (chuông báo cháy) reo lúc nửa đêm.",
  "ex-pre-30-6": "Thang máy đang ___ (hỏng, không hoạt động).",
  "ex-pre-30-7": "Cây cầu đang ___ (thi công).",
  "ex-pre-30-8": "___ (đẩy) để mở cửa.",
  "ex-pre-30-9": "Biển nào nghĩa là cấm vào?",
  "ex-pre-30-10": "Cụm nào cảnh báo đồ dễ vỡ khi vận chuyển?",
  "ex-pre-30-11": "Tính từ nào nghĩa là dễ vỡ?",
  "ex-pre-30-12": "Biển nào nghĩa là cấm hút thuốc?",
  "ex-pre-30-13": "Động từ nào nghĩa là kéo (cửa)?",
  "ex-pre-30-14": "Cụm nào cảnh báo coi chừng chó?",
};
