export const CURATED_EXERCISE_PROMPT_VI_31_45: Readonly<Record<string, string>> = {
  "ex-31-1-2": "___ có cổ rất dài.",
  "ex-31-1-3": "___ và gà mái là chim.",
  "ex-31-1-4": "Hổ và ___ là loài mèo lớn.",
  "ex-31-1-5": "Bạn có thể cưỡi ngựa và ___.",
  "ex-31-1-6": "Cá bơi và chim ___.",
  "ex-31-1-7": "___ là chim nuôi ở trang trại.",
  "ex-31-1-8": "___ nhảy rất giỏi.",
  "ex-31-1-9": "Đừng quên ___ mèo và cho nó nước uống.",
  "ex-31-1-10": "Tôi ___ chó đi dạo mỗi ngày trước giờ học.",
  "ex-31-2": "Ghép con vật bên trái với thịt và con non bên phải",
  "ex-31-4-1": "Down 1: chim nhiều màu có thể bắt chước nói — ___",
  "ex-31-4-2": "Down 2: động vật leo cây — ___",
  "ex-31-4-3": "Across 3: thú cưng bắt chuột — ___",
  "ex-31-4-4": "Down 4: vật nuôi trang trại có lông cừu — ___",
  "ex-31-4-5": "Down 5: mèo lớn có sọc — ___",
  "ex-31-4-6": "Across 6: vua rừng xanh — ___",
  "ex-31-4-7": "Across 7: động vật có thể cưỡi — ___",
  "ex-31-4-8": "Across 8: động vật rất to có vòi — ___",
  "ex-31-4-9": "Across 9: chim trang trại đẻ trứng — ___",
  "ex-32-1-2": "Ghép: direct → ?",
  "ex-32-1-3": "Ghép: restaurant car → ?",
  "ex-32-1-4": "Ghép: ship → ?",
  "ex-32-1-5": "Ghép: timetable → ?",
  "ex-32-1-6": "Ghép: platform → ?",
  "ex-32-1-7": "Ghép: luggage → ?",
  "ex-32-2-3": "Máy bay hạ cánh ở đầu hành trình.",
  "ex-32-2-4": "Bạn cần thẻ lên máy bay để xuống máy bay.",
  "ex-32-2-5": "Thuê xe giống như mua xe.",
  "ex-32-2-6": "Nếu bạn cho ai đi nhờ, họ đi trong xe của bạn.",
  "ex-32-4-1": "Down 1: cho biết giờ tàu — ___",
  "ex-32-4-2": "Down 2: xe trả tiền chở bạn đi — ___",
  "ex-32-4-3": "Across 3: giúp bạn tìm đường — ___",
  "ex-32-4-4": "Down 4: nơi chờ tàu — ___",
  "ex-32-4-5": "Down 5: chạy trên đường ray — ___",
  "ex-32-4-6": "Across 6: bay nhưng không phải máy bay — ___",
  "ex-32-4-7": "Across 7: phương tiện công cộng trên đường — ___",
  "ex-32-4-8": "Across 8: nhiên liệu cho ô tô — ___",
  "ex-32-4-9": "Down 3: xe máy hai bánh — ___",
  "ex-33-1-2": "Hình 2 thể hiện lễ hội nào?",
  "ex-33-1-3": "Hình 3 thể hiện lễ hội nào?",
  "ex-33-1-4": "Hình 4 thể hiện lễ hội nào?",
  "ex-33-1-5": "Hình 5 thể hiện lễ hội nào?",
  "ex-33-1-6": "Hình 6 thể hiện lễ hội nào?",
  "ex-33-3-2": "Chicken tikka masala đến từ đâu?",
  "ex-33-3-3": "Chicken tikka masala là một loại ___.",
  "ex-33-3-4": "Người Anh có ăn Yorkshire pudding sau món chính không?",
  "ex-33-3-5": "Bạn làm thịt nướng và khoai nướng trong ___.",
  "ex-33-4-1": "Lily 7 tuổi, bố mẹ trả học phí. Cô bé học ở ___",
  "ex-33-4-2": "Gabriel 14 tuổi, trường miễn phí. Cậu học ở ___",
  "ex-33-4-3": "James và Ellie 3 tuổi. Các em học ở ___",
  "ex-33-4-4": "Mehmet 10 tuổi, trường miễn phí. Cậu học ở ___",
  "ex-33-4-5": "Nick 16 tuổi, bố mẹ trả học phí. Cậu học ở ___",
  "ex-33-5-1": "Ai là Thủ tướng Anh năm 2016? ___",
  "ex-33-5-2": "Nghị sĩ họp ở đâu? ___",
  "ex-33-5-3": "Ai là quốc vương Anh năm 2016? Nữ hoàng ___ II",
  "ex-34-1-2": "Người giết người gọi là ___",
  "ex-34-1-3": "Người ăn trộm ở cửa hàng gọi là ___",
  "ex-34-1-4": "Người đột nhập nhà để trộm gọi là ___",
  "ex-34-1-5": "Người cướp trên phố gọi là ___",
  "ex-34-1-6": "Người bán ma túy trái phép gọi là ___",
  "ex-34-2-2": "Cảnh sát đã ___ cô ấy vì ăn trộm.",
  "ex-34-2-3": "Một số ___ đã phá hết hoa trong công viên.",
  "ex-34-2-4": "Anh ấy phải nộp ___ 50 bảng vì đỗ xe sai chỗ.",
  "ex-34-2-5": "Khu này có rất nhiều ___.",
  "ex-34-2-6": "Cảnh sát nhầm; cô ấy ___ — cô không lấy tiền.",
  "ex-34-2-7": "Một nhóm ___ đã tấn công sân bay.",
  "ex-34-2-8": "Anh ấy giết vợ và ở ___ 20 năm.",
  "ex-34-3-2": "Kẻ phá hoại lấy tiền của người khác.",
  "ex-34-3-4": "Kẻ trộm xe là người lái xe rất tệ.",
  "ex-34-4-2": "Ai đó đã ___ xe đạp của tôi tối qua.",
  "ex-34-4-3": "Anh trai tôi bị ___ hôm qua.",
  "ex-34-4-4": "Ngân hàng địa phương đã bị ___.",
  "ex-34-4-5": "Họ đã ___ hết tiền trong cửa hàng.",
  "ex-35-1-2": "Tin tức kênh 3 ___ lúc 9 giờ tối mỗi ngày.",
  "ex-35-1-3": "Tối qua có một ___ về tắc đường ở thành phố trên TV.",
  "ex-35-1-4": "Tôi xem chương trình ___ về chim ở Nam Cực.",
  "ex-35-1-5": "Em gái tôi đọc tạp chí ___ mỗi tuần.",
  "ex-35-1-6": "Tôi đọc tin thể thao ___ trên điện thoại.",
  "ex-35-1-7": "Tôi ___ kênh được không?",
  "ex-35-1-8": "Bạn có xem ___ với Thủ tướng tối qua không?",
  "ex-35-2-2": "Phim voi ở châu Phi là ___",
  "ex-35-2-3": "Chung kết cúp bóng đá là ___",
  "ex-35-2-4": "Tin từ khắp thế giới là ___",
  "ex-35-2-5": "Maria quyết định không cưới Philip là ___",
  "ex-35-2-6": "Mười người trong nhà không được ra ngoài là ___",
  "ex-35-3-2": "Người viết bài báo gọi là ___.",
  "ex-35-3-3": "Báo mua sau khoảng 5 giờ chiều là ___",
  "ex-35-3-4": "Chương trình làm từ nhiều hình vẽ gọi là ___.",
  "ex-35-3-6": "Thứ trên TV cố bán hàng gọi là ___.",
  "ex-35-3-7": "CNN hoặc Sky Sports là ___ TV.",
  "ex-36-1-2": "Máy tính đã ___.",
  "ex-36-1-3": "Cái cốc bị ___.",
  "ex-36-1-4": "Máy pha cà phê ___ hoạt động.",
  "ex-36-1-5": "Cô ấy có quá nhiều ___.",
  "ex-36-1-6": "Anh ấy bị cắt ___.",
  "ex-36-1-7": "Căn phòng ___.",
  "ex-36-1-8": "Cô ấy ___ đi làm.",
  "ex-36-4": "Ghép vấn đề bên trái với giải pháp bên phải",
  "ex-36-w1": "Tôi ___ đầu gối khi ngã.",
  "ex-36-w2": "Anh trai tôi ___ thẻ tín dụng.",
  "ex-36-w3": "Anh họ tôi ___ một cái ly.",
  "ex-36-w4": "Đầu DVD của tôi không ___.",
  "ex-37-1-2": "Hình 2: ___",
  "ex-37-1-3": "Hình 3: ___",
  "ex-37-1-4": "Hình 4: ___",
  "ex-37-1-5": "Hình 5: ___",
  "ex-37-1-6": "Hình 6: ___",
  "ex-37-1-7": "Hình 7: ___",
  "ex-37-1-8": "Hình 8: ___",
  "ex-37-1-9": "Hình 9: ___",
  "ex-37-2": "Ghép từ bên trái với từ bên phải thành cụm",
  "ex-37-3-2": "Quá nhiều xe không di chuyển được: ___",
  "ex-37-3-3": "Con phố có rất đông người: ___",
  "ex-37-3-4": "Hai xe va vào nhau: ___",
  "ex-37-3-5": "Không có việc làm: ___",
  "ex-37-5-2": "Lương thấp nên công nhân đã ___.",
  "ex-37-5-3": "Cố của tôi mất trong Thế chiến thứ nhất ___.",
  "ex-37-5-5": "Động đất và ___ có thể phá hủy thị trấn.",
  "ex-37-5-6": "Người nghèo, đói và ___ cần được giúp đỡ.",
  "ex-38-1-2": "Tôi có buổi ___ quần vợt mỗi sáng thứ Bảy.",
  "ex-38-1-4": "Evelyn sẽ tổ chức ___ vào thứ Bảy.",
  "ex-38-1-5": "Bạn có muốn ___ không?",
  "ex-38-1-6": "Ngày mai tôi có ___, nên tối nay phải học.",
  "ex-38-1-7": "Chúng ta phải có ___ để bàn các vấn đề này.",
  "ex-38-1-9": "Khách sạn có bể bơi, nên mỗi ngày chúng ta có thể ___.",
  "ex-38-2-2": "Scarlett đi tiệm làm tóc để cắt tóc ___.",
  "ex-38-2-3": "Trò chơi hay quá. Tôi thử ___ được không?",
  "ex-38-2-4": "Tôi muốn ___ với giáo viên sau buổi học.",
  "ex-38-2-5": "Mẹ không có ___ đi cửa hàng hôm nay.",
  "ex-38-2-6": "Hôm nay quán cà phê ___ bánh nào.",
  "ex-38-4-2": "Bạn đi du lịch. Bạn nói: ___",
  "ex-38-4-3": "Ai đó hắt hơi. Bạn hỏi:",
  "ex-38-4-4": "Bạn muốn xem. Bạn nói: Can I have a ___?",
  "ex-39-1-2": "Gia đình Sharp sẽ đến ___.",
  "ex-39-1-3": "Zoe và Penelope sẽ đi ___.",
  "ex-39-1-4": "Asad sẽ đến ___.",
  "ex-39-1-5": "Lars sẽ đi ___.",
  "ex-39-2-2": "Năm nay Victoria sẽ ___ bài thi lái xe.",
  "ex-39-2-3": "Năm nay Victoria sẽ học ___.",
  "ex-39-2-4": "Năm nay Victoria sẽ xem ___ TV.",
  "ex-39-2-5": "Năm nay Victoria sẽ giữ phòng ___.",
  "ex-39-3-1": "Khi đi nghỉ tôi đôi khi đi ___.",
  "ex-39-3-2": "Khi đi nghỉ tôi không bao giờ đi ___.",
  "ex-39-3-3": "Khi đến thành phố mới tôi luôn đi ___.",
  "ex-39-5-2": "Mum is going for shopping this afternoon. Câu đúng:",
  "ex-39-5-5": "Alexei is going to home at 4 o'clock. Câu đúng:",
  "ex-39-5-8": "I go to swimming → I go ___ mỗi sáng Chủ nhật.",
  "ex-39-5-9": "We're going sightsee → We're going ___ today.",
  "ex-40-1-2": "Các cô gái đang làm gì? Họ đang ___",
  "ex-40-1-3": "Con chó đang làm gì? Nó đang ___",
  "ex-40-1-4": "Người đàn ông trong nhà đang làm gì? Anh ấy đang ___",
  "ex-40-1-5": "Người phụ nữ đang làm gì? Cô ấy đang ___",
  "ex-40-1-6": "Người đàn ông trong vườn đang làm gì? Anh ấy đang ___",
  "ex-40-2-2": "Lee Atkins làm nghề gì? Anh ấy là ___.",
  "ex-40-2-3": "Sophie Hicks làm nghề gì? Cô ấy là ___.",
  "ex-40-2-4": "Cooper và Hailey làm nghề gì? Họ là ___.",
  "ex-40-3-2": "Lara Brown sáng nay đã làm gì? Cô ấy đi ___",
  "ex-40-3-3": "Sophie Hicks sáng nay đã làm gì? Cô ấy nói chuyện với năm ___.",
  "ex-40-3-4": "Cooper và Hailey sáng nay đã làm gì? Họ viết một ___.",
  "ex-40-w1": "Tôi ghét làm ___.",
  "ex-40-w2": "Con trai tôi phải làm ___ mỗi ngày.",
  "ex-40-w3": "Tôi thích làm ___.",
  "ex-40-5-2": "No, we don't go to Wales → No, we ___ go to Wales",
  "ex-40-5-3": "Do your grandmother lives → Does your grandmother ___",
  "ex-41-1-2": "Hàng xóm ___ rất nhiều tiếng ồn tối qua.",
  "ex-41-1-3": "Tối nay tôi đang ___ bữa tối cho bố mẹ.",
  "ex-41-1-4": "Hôm nay chúng ta phải ___ lựa chọn.",
  "ex-41-1-5": "Tôi đã ___ lịch hẹn bác sĩ cho bạn.",
  "ex-41-1-6": "Craig đang ___ một tách trà.",
  "ex-41-2-2": "Buổi học dài luôn khiến tôi (cảm thấy) ___.",
  "ex-41-2-3": "Cô ấy đối xử tệ với tôi; điều đó khiến tôi (cảm thấy) ___.",
  "ex-41-2-4": "Bài hát hay quá. Nó khiến tôi (cảm thấy) ___.",
  "ex-41-2-5": "Bữa ăn dở quá. Nó khiến tôi (cảm thấy) ___.",
  "ex-41-3-2": "Cô ấy đang ___ trà.",
  "ex-41-3-3": "Mấy cậu bé đang ___ ồn ào.",
  "ex-41-3-5": "Lũ trẻ đang ___ bừa bộn.",
  "ex-41-3-6": "Cô ấy đang ___ giường.",
  "ex-41-4-2": "Can I make a photo → Can I ___ a photo of you?",
  "ex-41-4-4": "Are you making an exam → Are you ___ / taking an exam?",
  "ex-41-4-5": "Have you made your homework → Have you ___ your homework?",
  "ex-42-1-2": "A: Tôi đi Thái Lan. B: Khi nào bạn về ___?",
  "ex-42-1-3": "Giáo viên bước ___ lớp học.",
  "ex-42-1-4": "A: Bạn đến từ ___? B: Tôi là người Tây Ban Nha.",
  "ex-42-1-5": "Hãy ___ tôi lúc 5 giờ.",
  "ex-42-1-6": "Trẻ em ra ___ trường lúc 4 giờ.",
  "ex-42-2-2": "Ai đó ở cửa nói: ___!",
  "ex-42-2-3": "Chúng tôi đi dự tiệc. Bạn có muốn ___ không?",
  "ex-42-2-4": "Tôi đến ___ Pháp.",
  "ex-42-3-2": "Cô ấy ___ về hôm qua.",
  "ex-42-3-3": "Anh ấy ___ đây mỗi thứ Ba.",
  "ex-42-3-4": "___ bạn có đến tiệc tối nay không?",
  "ex-42-3-5": "Pierre ___ từ thị trấn nhỏ ở Luxembourg.",
  "ex-42-4-1": "Tôi thường về ___ lúc năm rưỡi.",
  "ex-43-1-1": "Tôi mất 10 phút để đến trường đại học — It ___ me 10 minutes.",
  "ex-43-1-2": "Tôi mất 30 phút đến ga xe lửa gần nhất.",
  "ex-43-1-3": "Làm một unit sách này ___ tôi một giờ.",
  "ex-43-2-2": "Bạn có thể bay đến Paris hoặc ___",
  "ex-43-2-3": "Muốn học tiếng Nga? Sao không ___?",
  "ex-43-2-4": "Trời nóng khi ra ngoài, bạn cần ___",
  "ex-43-3-2": "Làm sao đến sân bay? Bạn có thể ___",
  "ex-43-3-3": "Christopher đi học bằng gì? Anh ấy ___",
  "ex-43-3-4": "Santiago và Lucia về nhà bằng gì? Họ ___",
  "ex-43-4-2": "Trời mưa tôi mang theo ___.",
  "ex-43-4-3": "Khi sang nước khác bạn mang theo ___.",
  "ex-43-4-4": "Khi đi học tiếng Anh tôi mang ___ và bút.",
  "ex-43-4-5": "Khi cần nhắn tin tôi mang theo ___.",
  "ex-44-1-2": "Đừng quên ___ sách ngày mai!",
  "ex-44-1-3": "Bạn ___ cho tôi chút nước được không?",
  "ex-44-1-4": "___ máy ảnh khi đi Thái Lan.",
  "ex-44-1-5": "Bạn ___ giúp mấy tờ giấy này được không?",
  "ex-44-1-6": "Tôi sẽ ___ bạn quà từ New York.",
  "ex-44-2": "Ghép nửa câu bên trái với nửa câu bên phải",
  "ex-44-3-1": "Cô ấy luôn ___ quà cho tôi.",
  "ex-44-3-2": "Hôm qua cô ấy ___ cho tôi sô-cô-la.",
  "ex-44-3-3": "Bạn ___ món quà này khi đến thăm Sonia được không?",
  "ex-44-3-4": "Cô ấy sẽ ___ sách của tôi và trả lại ngày mai.",
  "ex-44-4-1": "Tôi ___ tạp chí này được không? Ngày mai tôi sẽ trả lại.",
  "ex-44-4-2": "Khi sang Bỉ, cô ấy ___ cho tôi sô-cô-la.",
  "ex-45-1-2": "Tôi ăn quá nhiều và bị ___",
  "ex-45-1-3": "Tôi ngồi nắng quá và bị ___",
  "ex-45-1-4": "Mùa đông ở phía bắc trời ___ rất sớm.",
  "ex-45-1-5": "Vincent bị ___ vì mưa.",
  "ex-45-2-2": "Khi mặt trời mọc trời ___.",
  "ex-45-2-3": "Cô ấy đang nằm viện nhưng đang ___.",
  "ex-45-2-4": "Trời mưa! Tôi đang bị ___!",
  "ex-45-2-5": "Đóng cửa sổ đi. Tôi đang bị ___.",
  "ex-45-3-2": "Có người ốm! Hãy gọi ___.",
  "ex-45-3-3": "Bạn muốn uống gì? Tôi có thể lấy ___.",
  "ex-45-3-4": "Tôi có thể gọi ___ ở đâu?",
  "ex-45-3-5": "Tôi học xong rồi. Giờ tôi muốn có ___.",
  "ex-45-4-2": "Xe buýt từ trường đại học ___ nhà tôi trong 25 phút.",
  "ex-45-4-4": "José thường tan làm lúc 6 và ___ nhà lúc 6 rưỡi.",
  "ex-45-4-5": "Mike ở New York. Anh ấy sẽ không ___ đến 14 tháng 7.",
  "ex-45-w1": "Maria và David sẽ ___ vào tháng Tư.",
};
