import type { VocabularyUnit } from "../vocabulary-unit-types";
import { bold, ex, fillBlank, mcq, purple } from "./eviu-unit-builder";
import { preUnit, wordList } from "./eviu-pre-unit-helpers";

const U16_WORDS = wordList([
  ["alarm clock", "đồng hồ báo thức", "My alarm clock rings at 6 a.m."],
  ["snooze", "hoãn chuông báo thức thêm vài phút", "I pressed snooze twice this morning.", "VERB"],
  ["wake up", "thức dậy", "I usually wake up before sunrise.", "VERB"],
  ["get dressed", "mặc quần áo", "She gets dressed quickly for work.", "VERB"],
  ["commute", "đi lại hằng ngày giữa nhà và nơi làm/học", "My commute takes about forty minutes.", "NOUN"],
  ["rush hour", "giờ cao điểm giao thông", "Buses are packed during rush hour."],
  ["clock in", "chấm công vào ca làm", "Staff must clock in before 8:30.", "VERB"],
  ["shift", "ca làm việc", "He works the evening shift at the café."],
  ["take a break", "nghỉ giải lao", "I take a break after two hours of study.", "VERB"],
  ["run errands", "đi làm các việc lặt vặt", "I run errands after lunch on Saturdays.", "VERB"],
  ["household task", "việc nhà thường ngày", "Washing dishes is my least favorite household task."],
  ["do chores", "làm việc nhà", "Teenagers should do chores regularly.", "VERB"],
  ["meal prep", "chuẩn bị sẵn đồ ăn cho nhiều bữa", "Meal prep saves time on busy weekdays."],
  ["wind down", "thư giãn, giảm nhịp sau ngày dài", "I read a book to wind down at night.", "VERB"],
  ["bedtime", "giờ đi ngủ", "Keeping a fixed bedtime helps me sleep better."],
  ["oversleep", "ngủ quá giờ", "I overslept and missed the first bus.", "VERB"],
  ["punctual", "đúng giờ", "She is always punctual for meetings.", "ADJECTIVE"],
  ["hectic", "bận rộn và gấp gáp", "Monday mornings are usually hectic.", "ADJECTIVE"],
]);

const U17_WORDS = wordList([
  ["neighbourhood", "khu dân cư nơi mình sống", "My neighbourhood is quiet after 10 p.m."],
  ["suburb", "vùng ngoại ô", "Many young families move to the suburb."],
  ["downtown", "khu trung tâm thành phố", "I work downtown but live outside the city."],
  ["apartment block", "tòa chung cư", "There is a small gym in our apartment block."],
  ["detached house", "nhà riêng tách biệt", "They bought a detached house last year."],
  ["landlord", "chủ nhà cho thuê", "Our landlord fixed the broken window quickly."],
  ["tenant", "người thuê nhà", "The tenant signed a one-year contract."],
  ["rent", "tiền thuê nhà", "Rent in this area has increased a lot."],
  ["mortgage", "khoản vay mua nhà", "They are paying off their mortgage monthly."],
  ["utility bill", "hóa đơn điện, nước, internet...", "Utility bills are higher in winter."],
  ["local amenity", "tiện ích địa phương như công viên, trường học", "Good local amenities make life easier."],
  ["green space", "không gian xanh trong khu dân cư", "This district has little green space."],
  ["residential area", "khu vực chủ yếu để ở", "It is a peaceful residential area."],
  ["convenient", "thuận tiện", "The flat is convenient for public transport.", "ADJECTIVE"],
  ["noisy", "ồn ào", "The street gets noisy at night.", "ADJECTIVE"],
  ["settle in", "ổn định cuộc sống ở nơi mới", "It took us a month to settle in.", "VERB"],
  ["move in", "dọn vào ở", "Our new neighbors will move in next week.", "VERB"],
  ["feel at home", "cảm thấy thoải mái như ở nhà", "I feel at home in this city now.", "VERB"],
]);

const U18_WORDS = wordList([
  ["hallway", "hành lang trong nhà", "Please leave your shoes in the hallway."],
  ["storage cupboard", "tủ để đồ", "We keep cleaning products in the storage cupboard."],
  ["shelf", "kệ", "I put the books back on the shelf."],
  ["drawer", "ngăn kéo", "Her keys are in the top drawer."],
  ["plug socket", "ổ cắm điện", "There is no plug socket near the desk."],
  ["extension lead", "dây điện nối dài", "Use an extension lead for the fan."],
  ["vacuum cleaner", "máy hút bụi", "The vacuum cleaner is in the laundry room."],
  ["mop", "cây lau nhà", "I bought a new mop yesterday."],
  ["laundry basket", "giỏ đựng quần áo bẩn", "Put dirty clothes in the laundry basket."],
  ["ironing board", "cầu là", "The ironing board is behind the door."],
  ["dishwasher", "máy rửa chén", "Our dishwasher saves a lot of time."],
  ["home appliance", "thiết bị gia dụng", "A fridge is an essential home appliance."],
  ["tidy up", "dọn gọn lại", "Please tidy up the living room before guests arrive.", "VERB"],
  ["wipe down", "lau bề mặt", "I wipe down the kitchen counter every night.", "VERB"],
  ["clutter", "sự bừa bộn", "Too much clutter makes the room feel smaller."],
  ["spotless", "sạch bong, không tì vết", "The bathroom was spotless after cleaning.", "ADJECTIVE"],
  ["leak", "chỗ rò rỉ nước/khí", "We found a leak under the sink."],
  ["spare key", "chìa khóa dự phòng", "I gave my sister a spare key."],
]);

const U19_WORDS = wordList([
  ["budget", "ngân sách chi tiêu", "I set a weekly budget for groceries."],
  ["income", "thu nhập", "Her income increased after promotion."],
  ["expense", "khoản chi", "Transport is my biggest monthly expense."],
  ["savings account", "tài khoản tiết kiệm", "I opened a savings account at the bank."],
  ["interest rate", "lãi suất", "The interest rate is quite low this year."],
  ["debt", "khoản nợ", "He is trying to pay off his debt."],
  ["afford", "có khả năng chi trả", "We cannot afford a bigger apartment now.", "VERB"],
  ["cut back", "cắt giảm chi tiêu", "I need to cut back on eating out.", "VERB"],
  ["cost of living", "chi phí sinh hoạt", "The cost of living is rising quickly."],
  ["bargain", "món mua hời", "This jacket was a real bargain."],
  ["overpriced", "bị bán quá đắt", "That restaurant is overpriced.", "ADJECTIVE"],
  ["refund", "hoàn tiền", "I asked for a refund after returning the product."],
  ["receipt", "hóa đơn mua hàng", "Keep the receipt in case you need an exchange."],
  ["transfer money", "chuyển tiền", "I transfer money to my parents every month.", "VERB"],
  ["instalment", "khoản trả góp theo kỳ", "She pays for her laptop in instalments."],
  ["cash withdrawal", "rút tiền mặt", "There is a fee for cash withdrawal abroad."],
  ["financial goal", "mục tiêu tài chính", "Buying a home is my long-term financial goal."],
  ["emergency fund", "quỹ dự phòng khẩn cấp", "An emergency fund gives you peace of mind."],
]);

const U20_WORDS = wordList([
  ["symptom", "triệu chứng bệnh", "A persistent cough can be a symptom of flu."],
  ["sore throat", "đau họng", "I stayed home because of a sore throat."],
  ["runny nose", "chảy nước mũi", "A runny nose is common in cold weather."],
  ["temperature", "sốt, thân nhiệt cao bất thường", "His temperature was over 38 degrees."],
  ["prescribe", "kê đơn thuốc", "The doctor prescribed antibiotics.", "VERB"],
  ["prescription", "đơn thuốc", "You need a prescription for this medicine."],
  ["recover", "hồi phục", "It took her a week to recover fully.", "VERB"],
  ["dehydrated", "mất nước", "You may feel dizzy when dehydrated.", "ADJECTIVE"],
  ["balanced diet", "chế độ ăn cân bằng", "A balanced diet supports overall health."],
  ["immune system", "hệ miễn dịch", "Sleep helps strengthen your immune system."],
  ["check-up", "buổi khám sức khỏe định kỳ", "I go for a check-up twice a year."],
  ["blood pressure", "huyết áp", "The nurse checked my blood pressure."],
  ["muscle strain", "căng cơ", "He stopped running due to a muscle strain."],
  ["rest up", "nghỉ ngơi để hồi sức", "You should rest up this weekend.", "VERB"],
  ["take medicine", "uống thuốc", "Remember to take medicine after meals.", "VERB"],
  ["side effect", "tác dụng phụ", "This medicine may cause mild side effects."],
  ["chronic", "mãn tính, kéo dài", "She is receiving treatment for chronic pain.", "ADJECTIVE"],
  ["mental wellbeing", "sức khỏe tinh thần", "Exercise can improve mental wellbeing."],
]);

const U21_WORDS = wordList([
  ["sleeve", "ống tay áo", "The sleeves are too long for me."],
  ["collar", "cổ áo", "His shirt collar is neatly pressed."],
  ["fabric", "chất liệu vải", "This fabric feels soft and breathable."],
  ["cotton", "vải cotton", "I prefer cotton in hot weather."],
  ["wool", "len", "This wool sweater is very warm."],
  ["fit", "độ vừa vặn của quần áo", "The fit of these jeans is perfect."],
  ["loose-fitting", "rộng, không ôm sát", "I like loose-fitting trousers in summer.", "ADJECTIVE"],
  ["tight-fitting", "ôm sát người", "This top is too tight-fitting for me.", "ADJECTIVE"],
  ["plain", "trơn, không họa tiết", "He chose a plain white T-shirt.", "ADJECTIVE"],
  ["patterned", "có họa tiết", "She bought a patterned skirt.", "ADJECTIVE"],
  ["try on", "thử đồ", "Can I try on this jacket?", "VERB"],
  ["match", "phối hợp hài hòa", "These shoes match your dress.", "VERB"],
  ["layer", "mặc nhiều lớp", "You should layer your clothes in winter.", "VERB"],
  ["formal wear", "trang phục trang trọng", "Formal wear is required for the event."],
  ["casual wear", "trang phục thường ngày", "I usually buy casual wear for work."],
  ["outfit", "bộ trang phục hoàn chỉnh", "Her outfit looks simple but elegant."],
  ["wrinkle", "nếp nhăn trên vải", "This shirt has too many wrinkles."],
  ["comfortable", "thoải mái khi mặc", "These sneakers are really comfortable.", "ADJECTIVE"],
]);

const U22_WORDS = wordList([
  ["changing room", "phòng thử đồ", "The changing room is at the back of the shop."],
  ["in stock", "còn hàng", "This size is still in stock.", "ADJECTIVE"],
  ["out of stock", "hết hàng", "Sorry, black is out of stock.", "ADJECTIVE"],
  ["refund policy", "chính sách hoàn tiền", "Please read the refund policy carefully."],
  ["exchange", "đổi hàng", "You can exchange it within seven days.", "VERB"],
  ["size chart", "bảng kích cỡ", "Check the size chart before ordering online."],
  ["discount code", "mã giảm giá", "I used a discount code at checkout."],
  ["seasonal sale", "đợt giảm giá theo mùa", "We bought coats during the seasonal sale."],
  ["impulse buy", "mua bốc đồng", "That expensive bag was an impulse buy."],
  ["on trend", "đúng xu hướng", "Wide-leg jeans are on trend this year.", "ADJECTIVE"],
  ["timeless", "không lỗi mốt", "A black blazer is a timeless item.", "ADJECTIVE"],
  ["brand-conscious", "quan tâm nhiều đến thương hiệu", "Some teenagers are very brand-conscious.", "ADJECTIVE"],
  ["affordable", "giá phải chăng", "This store sells affordable basics.", "ADJECTIVE"],
  ["quality", "chất lượng", "The quality of this coat is excellent."],
  ["shop assistant", "nhân viên bán hàng", "A shop assistant helped me pick a size."],
  ["pay by card", "thanh toán bằng thẻ", "Can I pay by card here?", "VERB"],
  ["keep the receipt", "giữ lại hóa đơn", "Keep the receipt in case you need a refund.", "VERB"],
  ["queue for fitting", "xếp hàng chờ thử đồ", "We had to queue for fitting on Saturday.", "VERB"],
]);

const U23_WORDS = wordList([
  ["shopping mall", "trung tâm mua sắm", "The new shopping mall opened downtown."],
  ["department store", "cửa hàng bách hóa tổng hợp", "You can buy cosmetics at the department store."],
  ["convenience store", "cửa hàng tiện lợi", "I bought milk at a convenience store."],
  ["aisle", "lối giữa các kệ hàng", "Please stand clear of the aisle."],
  ["checkout counter", "quầy thanh toán", "There was a long line at the checkout counter."],
  ["basket", "giỏ xách mua hàng", "I only need a basket for a few items."],
  ["trolley", "xe đẩy mua hàng", "Take a trolley if you buy in bulk."],
  ["browse", "xem hàng mà chưa chắc mua", "We browsed for half an hour.", "VERB"],
  ["compare prices", "so sánh giá", "Smart shoppers compare prices first.", "VERB"],
  ["special offer", "ưu đãi đặc biệt", "This coffee is on special offer today."],
  ["loyalty card", "thẻ khách hàng thân thiết", "Use your loyalty card to get points."],
  ["delivery slot", "khung giờ giao hàng", "I booked an evening delivery slot."],
  ["customer service", "bộ phận chăm sóc khách hàng", "Customer service solved my issue quickly."],
  ["faulty item", "sản phẩm bị lỗi", "The charger was a faulty item."],
  ["return an item", "trả lại hàng", "You can return an item within 14 days.", "VERB"],
  ["queue", "xếp hàng", "People queue near the cashier at peak time.", "VERB"],
  ["shop online", "mua sắm trực tuyến", "Many people shop online after work.", "VERB"],
  ["sold out", "đã bán hết", "The best-selling model is sold out.", "ADJECTIVE"],
]);

const U24_WORDS = wordList([
  ["carbohydrate", "chất bột đường", "Rice is a major source of carbohydrate."],
  ["protein", "chất đạm", "Eggs are rich in protein."],
  ["fibre", "chất xơ", "Vegetables provide plenty of fibre."],
  ["dairy product", "sản phẩm từ sữa", "Yogurt is a healthy dairy product."],
  ["wholegrain", "ngũ cốc nguyên cám", "Wholegrain bread keeps you full longer."],
  ["processed food", "thực phẩm chế biến sẵn", "Try to limit processed food intake."],
  ["portion size", "kích cỡ khẩu phần", "Portion size affects your daily calories."],
  ["appetite", "cảm giác thèm ăn", "Stress can reduce your appetite."],
  ["nutritious", "giàu dinh dưỡng", "This soup is light but nutritious.", "ADJECTIVE"],
  ["greasy", "nhiều dầu mỡ", "That street food is tasty but greasy.", "ADJECTIVE"],
  ["spicy", "cay", "I like spicy noodles.", "ADJECTIVE"],
  ["bland", "nhạt, thiếu vị", "The sauce is a bit bland.", "ADJECTIVE"],
  ["food allergy", "dị ứng thực phẩm", "She has a food allergy to peanuts."],
  ["vegetarian", "người ăn chay/thuộc đồ ăn chay", "My sister is vegetarian.", "ADJECTIVE"],
  ["vegan", "thuần chay", "This café offers vegan desserts.", "ADJECTIVE"],
  ["leftovers", "đồ ăn thừa", "We kept the leftovers for lunch."],
  ["snack", "bữa phụ, món ăn nhẹ", "I usually have fruit as a snack."],
  ["meal prep", "chuẩn bị trước bữa ăn", "Meal prep helps me eat healthier."],
]);

const U25_WORDS = wordList([
  ["chop", "băm/chặt nhỏ", "Chop the onions finely.", "VERB"],
  ["slice", "thái lát", "Slice the tomatoes thinly.", "VERB"],
  ["grate", "bào nhỏ", "Grate some cheese over the pasta.", "VERB"],
  ["boil", "luộc/đun sôi", "Boil the eggs for seven minutes.", "VERB"],
  ["steam", "hấp", "We steam vegetables to keep nutrients.", "VERB"],
  ["fry", "chiên/rán", "Do not fry it on high heat.", "VERB"],
  ["roast", "nướng lò", "They roast chicken every Sunday.", "VERB"],
  ["simmer", "đun liu riu", "Let the soup simmer for 20 minutes.", "VERB"],
  ["stir", "khuấy", "Stir the sauce continuously.", "VERB"],
  ["season", "nêm nếm gia vị", "Season the fish with salt and pepper.", "VERB"],
  ["marinate", "ướp gia vị trước khi nấu", "Marinate the beef overnight.", "VERB"],
  ["recipe", "công thức nấu ăn", "I found this recipe online."],
  ["ingredient", "nguyên liệu", "Fresh ingredients make a big difference."],
  ["saucepan", "nồi có tay cầm", "Heat the milk in a saucepan."],
  ["frying pan", "chảo rán", "Use a non-stick frying pan."],
  ["oven", "lò nướng", "Preheat the oven to 180 degrees."],
  ["undercooked", "chưa chín kỹ", "The chicken is still undercooked.", "ADJECTIVE"],
  ["overcooked", "chín quá, bị khô", "The steak became overcooked.", "ADJECTIVE"],
]);

const U26_WORDS = wordList([
  ["skyline", "đường chân trời với các tòa nhà cao", "The skyline looks amazing at sunset."],
  ["traffic jam", "kẹt xe", "We got stuck in a traffic jam."],
  ["public transport", "giao thông công cộng", "Public transport is convenient in this city."],
  ["rush hour", "giờ cao điểm", "Trains are crowded at rush hour."],
  ["nightlife", "hoạt động giải trí về đêm", "The city has a vibrant nightlife."],
  ["apartment block", "tòa chung cư", "He lives in an old apartment block."],
  ["high-rise", "tòa nhà cao tầng", "New high-rises are being built rapidly."],
  ["pedestrian zone", "khu vực dành cho người đi bộ", "Cars are not allowed in this pedestrian zone."],
  ["pollution", "ô nhiễm", "Air pollution gets worse in winter."],
  ["commute", "hành trình đi làm mỗi ngày", "Her daily commute takes over an hour."],
  ["vibrant", "sôi động, đầy sức sống", "It is a vibrant neighborhood.", "ADJECTIVE"],
  ["crowded", "đông đúc", "The metro is crowded every morning.", "ADJECTIVE"],
  ["expensive", "đắt đỏ", "City-center apartments are expensive.", "ADJECTIVE"],
  ["cycle lane", "làn đường cho xe đạp", "Please stay out of the cycle lane."],
  ["public square", "quảng trường công cộng", "People gather in the public square on weekends."],
  ["security camera", "camera an ninh", "Security cameras are installed in many streets."],
  ["city centre", "trung tâm thành phố", "Most offices are in the city centre."],
  ["convenience", "sự tiện lợi", "City life offers a lot of convenience."],
]);

const U27_WORDS = wordList([
  ["farmhouse", "nhà ở tại nông trại", "They renovated an old farmhouse."],
  ["barn", "nhà kho/chuồng lớn trong nông trại", "The tools are kept in the barn."],
  ["orchard", "vườn cây ăn quả", "His family owns a mango orchard."],
  ["pasture", "đồng cỏ chăn thả", "Cows grazed in the pasture."],
  ["dirt track", "đường đất nhỏ", "We cycled along a dirt track."],
  ["livestock", "gia súc nuôi", "Farmers protect livestock from heavy rain."],
  ["harvest season", "mùa thu hoạch", "Everyone is busy during harvest season."],
  ["village fair", "hội chợ làng", "The village fair attracts many visitors."],
  ["close-knit", "gắn kết chặt chẽ", "It is a close-knit rural community.", "ADJECTIVE"],
  ["peaceful", "yên bình", "The countryside feels peaceful at night.", "ADJECTIVE"],
  ["remote", "xa xôi, hẻo lánh", "They live in a remote mountain village.", "ADJECTIVE"],
  ["fresh produce", "nông sản tươi", "We buy fresh produce from local farms."],
  ["well water", "nước giếng", "They still use well water for gardening."],
  ["sunrise", "bình minh", "I wake up early to watch the sunrise."],
  ["tractor", "máy kéo nông nghiệp", "A tractor passed slowly on the road."],
  ["countryside", "vùng nông thôn", "He moved back to the countryside."],
  ["isolated", "cô lập, cách biệt", "Some villages feel isolated in winter.", "ADJECTIVE"],
  ["rural chore", "việc nhà nông hằng ngày", "Feeding chickens is a common rural chore."],
]);

const U28_WORDS = wordList([
  ["timetable", "bảng giờ xe/tàu", "Check the timetable before leaving home."],
  ["platform", "sân ga", "Our train departs from platform 4."],
  ["carriage", "toa tàu", "This carriage is quieter than the others."],
  ["transfer", "chuyển tuyến/chặng", "You need one transfer to reach the airport.", "NOUN"],
  ["direct train", "tàu đi thẳng không đổi chuyến", "The direct train is faster."],
  ["delay", "sự chậm trễ", "There was a 20-minute delay due to rain."],
  ["cancel service", "hủy chuyến", "They cancelled service on this route.", "VERB"],
  ["season ticket", "vé tháng/quý đi lại thường xuyên", "A season ticket saves commuters money."],
  ["fare", "giá vé", "Bus fare has gone up this year."],
  ["one-way ticket", "vé một chiều", "I bought a one-way ticket to Hue."],
  ["return ticket", "vé khứ hồi", "A return ticket is often cheaper."],
  ["board", "lên tàu/xe", "Passengers should board quickly.", "VERB"],
  ["alight", "xuống tàu/xe", "Please alight at the next station.", "VERB"],
  ["seat reservation", "đặt trước chỗ ngồi", "Seat reservation is required on this train."],
  ["luggage rack", "kệ để hành lý", "Put your backpack on the luggage rack."],
  ["peak hours", "khung giờ cao điểm", "Trains are packed during peak hours."],
  ["route", "tuyến đường", "This route passes through three towns."],
  ["connection", "chuyến nối", "I missed my connection because of delay."],
]);

const U29_WORDS = wordList([
  ["junction", "nút giao/điểm giao nhau của đường", "Take the second exit at the junction."],
  ["roundabout", "vòng xuyến", "Go straight through the roundabout."],
  ["speed limit", "giới hạn tốc độ", "Drivers must obey the speed limit."],
  ["lane", "làn đường", "Stay in the left lane if you turn left."],
  ["overtake", "vượt xe", "Do not overtake on this narrow road.", "VERB"],
  ["pedestrian crossing", "vạch sang đường cho người đi bộ", "Stop at the pedestrian crossing."],
  ["traffic light", "đèn giao thông", "Turn right at the second traffic light."],
  ["roadworks", "công trình sửa đường", "Roadworks caused heavy congestion."],
  ["detour", "đường vòng tạm thời", "Follow the detour signs carefully."],
  ["petrol station", "trạm xăng", "There is a petrol station ahead."],
  ["flat tyre", "lốp xe bị xẹp", "We had to stop because of a flat tyre."],
  ["engine", "động cơ", "The engine makes a strange noise."],
  ["brake", "phanh xe", "Press the brake gently on wet roads.", "VERB"],
  ["seat belt", "dây an toàn", "Everyone must wear a seat belt."],
  ["indicate", "bật xi nhan báo hướng rẽ", "Remember to indicate before turning.", "VERB"],
  ["park illegally", "đỗ xe sai quy định", "Do not park illegally near schools.", "VERB"],
  ["traffic fine", "tiền phạt giao thông", "He got a traffic fine for speeding."],
  ["driving licence", "giấy phép lái xe", "Always carry your driving licence."],
]);

const U30_WORDS = wordList([
  ["mind the gap", "chú ý khoảng trống giữa tàu và sân ga", "The sign says: mind the gap."],
  ["no entry", "cấm vào", "This door is marked no entry."],
  ["slippery floor", "sàn trơn trượt", "Be careful: slippery floor after cleaning."],
  ["wet paint", "sơn còn ướt", "Do not touch the wall, wet paint."],
  ["keep out", "cấm vào, không phận sự miễn vào", "The gate says keep out."],
  ["staff only", "chỉ dành cho nhân viên", "This area is staff only."],
  ["emergency exit", "lối thoát hiểm", "Locate the emergency exit when you arrive."],
  ["fire alarm", "chuông/cảnh báo cháy", "The fire alarm went off at midnight."],
  ["fragile", "dễ vỡ", "This package is marked fragile.", "ADJECTIVE"],
  ["handle with care", "xin nhẹ tay khi vận chuyển", "The box says handle with care."],
  ["no smoking", "cấm hút thuốc", "No smoking in this building."],
  ["beware of dog", "coi chừng chó", "A sign on the gate says beware of dog."],
  ["high voltage", "điện áp cao, nguy hiểm điện giật", "Do not touch the panel: high voltage."],
  ["under construction", "đang thi công", "The bridge is under construction."],
  ["out of order", "hỏng, không hoạt động", "The elevator is out of order."],
  ["push", "đẩy", "Push to open the door.", "VERB"],
  ["pull", "kéo", "Pull the handle gently.", "VERB"],
  ["queue here", "xếp hàng tại đây", "Please queue here for tickets."],
]);

export const EVIU_PRE_UNITS_16_30: VocabularyUnit[] = [
  preUnit(16, {
    introVi: "Unit 16 mở rộng từ vựng về thói quen hằng ngày ở nhà, khi đi làm và quản lý thời gian. Mục tiêu là diễn đạt được nhịp sinh hoạt tự nhiên bằng cụm từ quen dùng.",
    structureSections: [
      { label: "Morning and work rhythm", wordCount: 6 },
      { label: "Daily tasks", wordCount: 6 },
      { label: "Evening routine", wordCount: 6 },
    ],
    collocationHtml: `${purple("wake up early")}, ${purple("clock in on time")}, ${purple("run errands")}, ${purple("wind down before bedtime")} là các cụm quan trọng.`,
    mistakeHtml: `Tránh dịch máy kiểu ${bold("I do my routine")}; tự nhiên hơn là ${bold("I stick to my routine")} hoặc ${bold("I follow a routine")}.`,
    principles: [
      {
        title: "Gộp từ theo chuỗi thời gian trong ngày",
        body: `Học theo trình tự sáng - trưa - tối giúp nhớ bền hơn, ví dụ từ ${purple("alarm clock")} đến ${purple("bedtime")}.`,
        examples: [ex("I wake up, commute, then clock in.", "Tôi thức dậy, đi làm rồi chấm công.")],
      },
      {
        title: "Ưu tiên cụm động từ thay vì từ đơn",
        body: `Các cụm như ${purple("take a break")}, ${purple("run errands")} và ${purple("wind down")} nghe tự nhiên hơn trong hội thoại.`,
        examples: [ex("I run errands after work.", "Tôi làm việc lặt vặt sau giờ làm.")],
      },
      {
        title: "Dùng tính từ mô tả nhịp sống",
        body: `Kết hợp ${purple("punctual")} và ${purple("hectic")} để nói về mức độ bận rộn và tính kỷ luật.`,
        examples: [ex("Monday is hectic but I stay punctual.", "Thứ Hai bận rộn nhưng tôi vẫn đúng giờ.")],
      },
    ],
    words: U16_WORDS,
    exercises: [
      mcq(
        16,
        1,
        "Cụm nào nghĩa là đi làm các việc lặt vặt như ngân hàng, siêu thị?",
        [
          { key: "a", label: "run errands" },
          { key: "b", label: "clock in" },
          { key: "c", label: "oversleep" },
          { key: "d", label: "wind down" },
        ],
        "a",
      ),
      fillBlank(
        16,
        2,
        "I always ____ at 8:00 to record my attendance.",
        "clock in",
        [
          { key: "a", label: "take a break" },
          { key: "b", label: "clock in" },
          { key: "c", label: "snooze" },
          { key: "d", label: "do chores" },
        ],
        "b",
      ),
      mcq(
        16,
        3,
        "Từ nào mô tả tình trạng bận rộn và gấp gáp?",
        [
          { key: "a", label: "punctual" },
          { key: "b", label: "hectic" },
          { key: "c", label: "household" },
          { key: "d", label: "spare" },
        ],
        "b",
      ),
    ],
  }),
  preUnit(17, {
    introVi: "Unit 17 giúp bạn mô tả nơi ở, loại nhà và điều kiện sống trong khu dân cư. Bạn sẽ nói rõ hơn về thuê nhà, chi phí và cảm nhận khi chuyển đến nơi mới.",
    structureSections: [
      { label: "Types of places", wordCount: 6 },
      { label: "Housing and costs", wordCount: 6 },
      { label: "Living experience", wordCount: 6 },
    ],
    collocationHtml: `${purple("apartment block")}, ${purple("utility bill")}, ${purple("local amenities")} và ${purple("settle in")} xuất hiện rất thường xuyên.`,
    mistakeHtml: `Đừng nhầm ${bold("rent")} (tiền thuê) với ${bold("mortgage")} (trả góp mua nhà).`,
    principles: [
      {
        title: "Phân biệt rõ vị trí sống",
        body: `Dùng ${purple("downtown")} cho trung tâm và ${purple("suburb")} cho ngoại ô để tránh diễn đạt mơ hồ.`,
        examples: [ex("I work downtown but live in the suburb.", "Tôi làm ở trung tâm nhưng sống ở ngoại ô.")],
      },
      {
        title: "Dùng từ đúng vai trò nhà ở",
        body: `${purple("landlord")} là chủ cho thuê, còn ${purple("tenant")} là người thuê.`,
        examples: [ex("Our landlord is helpful.", "Chủ nhà của chúng tôi rất hỗ trợ.")],
      },
      {
        title: "Nói về chất lượng sống bằng cụm thực tế",
        body: `Kết hợp ${purple("green space")}, ${purple("convenient")} và ${purple("feel at home")} để mô tả trải nghiệm sống.`,
        examples: [ex("There is enough green space for children.", "Có đủ không gian xanh cho trẻ em.")],
      },
    ],
    words: U17_WORDS,
    exercises: [
      mcq(
        17,
        1,
        "Từ nào chỉ người thuê nhà?",
        [
          { key: "a", label: "landlord" },
          { key: "b", label: "tenant" },
          { key: "c", label: "resident" },
          { key: "d", label: "owner" },
        ],
        "b",
      ),
      fillBlank(
        17,
        2,
        "We need to pay the ____ every month, including water and electricity.",
        "utility bill",
        [
          { key: "a", label: "utility bill" },
          { key: "b", label: "green space" },
          { key: "c", label: "mortgage rate" },
          { key: "d", label: "apartment block" },
        ],
        "a",
      ),
      mcq(
        17,
        3,
        "Cụm nào nghĩa là ổn định cuộc sống ở nơi mới?",
        [
          { key: "a", label: "move out" },
          { key: "b", label: "settle in" },
          { key: "c", label: "sign off" },
          { key: "d", label: "pay rent" },
        ],
        "b",
      ),
    ],
  }),
  preUnit(18, {
    introVi: "Unit 18 tập trung vào từ vựng đồ đạc và việc dọn dẹp quanh nhà. Bạn sẽ mô tả chính xác vị trí đồ dùng, thiết bị và các việc bảo trì cơ bản.",
    structureSections: [
      { label: "Rooms and furniture details", wordCount: 6 },
      { label: "Cleaning tools and tasks", wordCount: 6 },
      { label: "Maintenance and condition", wordCount: 6 },
    ],
    collocationHtml: `${purple("storage cupboard")}, ${purple("plug socket")}, ${purple("wipe down surfaces")} và ${purple("home appliance")} là nhóm từ cốt lõi.`,
    mistakeHtml: `Tránh dùng chung một động từ ${bold("clean")} cho mọi việc; nên phân biệt ${bold("vacuum")}, ${bold("mop")} và ${bold("wipe down")}.`,
    principles: [
      {
        title: "Gắn từ vựng với vị trí thật trong nhà",
        body: "Khi học, hãy chỉ trực tiếp vào đồ vật thật để ghi nhớ nhanh hơn và tránh nhầm lẫn.",
        examples: [ex("The spare key is in the top drawer.", "Chìa khóa dự phòng ở ngăn kéo trên cùng.")],
      },
      {
        title: "Phân loại công cụ và hành động dọn dẹp",
        body: `${purple("vacuum cleaner")}, ${purple("mop")} là dụng cụ; ${purple("tidy up")}, ${purple("wipe down")} là hành động.`,
        examples: [ex("I tidy up first, then mop the floor.", "Tôi dọn gọn trước rồi mới lau sàn.")],
      },
      {
        title: "Mô tả tình trạng nhà rõ ràng",
        body: `Dùng ${purple("clutter")}, ${purple("spotless")} và ${purple("leak")} để nói vấn đề hoặc trạng thái sau khi dọn.`,
        examples: [ex("The kitchen is spotless now.", "Bếp bây giờ sạch bong.")],
      },
    ],
    words: U18_WORDS,
    exercises: [
      mcq(
        18,
        1,
        "Từ nào chỉ ổ cắm điện trên tường?",
        [
          { key: "a", label: "plug socket" },
          { key: "b", label: "drawer" },
          { key: "c", label: "shelf" },
          { key: "d", label: "hallway" },
        ],
        "a",
      ),
      fillBlank(
        18,
        2,
        "Please ____ the kitchen counter after cooking.",
        "wipe down",
        [
          { key: "a", label: "tidy up" },
          { key: "b", label: "wipe down" },
          { key: "c", label: "store up" },
          { key: "d", label: "wind down" },
        ],
        "b",
      ),
      mcq(
        18,
        3,
        "Từ nào nghĩa là sạch bong không tì vết?",
        [
          { key: "a", label: "cluttered" },
          { key: "b", label: "spotless" },
          { key: "c", label: "dusty" },
          { key: "d", label: "tight" },
        ],
        "b",
      ),
    ],
  }),
  preUnit(19, {
    introVi: "Unit 19 xây nền từ vựng về tiền bạc, thu chi và kế hoạch tài chính cá nhân. Mục tiêu là dùng được ngôn ngữ thực tế khi mua sắm, tiết kiệm và quản lý nợ.",
    structureSections: [
      { label: "Income and spending", wordCount: 6 },
      { label: "Banking and payments", wordCount: 6 },
      { label: "Money planning", wordCount: 6 },
    ],
    collocationHtml: `${purple("set a budget")}, ${purple("cut back on spending")}, ${purple("transfer money")} và ${purple("emergency fund")} là các cụm nên học theo cặp.`,
    mistakeHtml: `Không nói ${bold("I have many debtses")}; ${bold("debt")} thường là danh từ không đếm được trong ngữ cảnh chung.`,
    principles: [
      {
        title: "Ưu tiên từ mô tả dòng tiền",
        body: `Phân biệt ${purple("income")} và ${purple("expense")} trước khi học sâu về ngân hàng.`,
        examples: [ex("My expenses are higher than my income this month.", "Chi tiêu tháng này cao hơn thu nhập.")],
      },
      {
        title: "Học cụm tài chính gắn với hành động",
        body: `Dùng các cụm như ${purple("pay in instalments")} hoặc ${purple("cash withdrawal")} trong tình huống đời thực.`,
        examples: [ex("We paid in instalments for the sofa.", "Chúng tôi trả góp chiếc sofa.")],
      },
      {
        title: "Xây tư duy kế hoạch dài hạn",
        body: `Kết hợp ${purple("financial goal")} với ${purple("emergency fund")} để diễn đạt mục tiêu tài chính rõ ràng.`,
        examples: [ex("My financial goal is to build a six-month emergency fund.", "Mục tiêu tài chính của tôi là lập quỹ dự phòng sáu tháng.")],
      },
    ],
    words: U19_WORDS,
    exercises: [
      mcq(
        19,
        1,
        "Từ nào chỉ khoản tiền vào bạn nhận được?",
        [
          { key: "a", label: "expense" },
          { key: "b", label: "income" },
          { key: "c", label: "debt" },
          { key: "d", label: "refund" },
        ],
        "b",
      ),
      fillBlank(
        19,
        2,
        "I am trying to ____ on coffee and take-away meals.",
        "cut back",
        [
          { key: "a", label: "cut back" },
          { key: "b", label: "transfer money" },
          { key: "c", label: "pay debt" },
          { key: "d", label: "withdraw budget" },
        ],
        "a",
      ),
      mcq(
        19,
        3,
        "Cụm nào chỉ quỹ dự phòng khi có việc khẩn cấp?",
        [
          { key: "a", label: "savings account" },
          { key: "b", label: "emergency fund" },
          { key: "c", label: "cash withdrawal" },
          { key: "d", label: "financial debt" },
        ],
        "b",
      ),
    ],
  }),
  preUnit(20, {
    introVi: "Unit 20 mở rộng vốn từ về triệu chứng, điều trị và thói quen giữ sức khỏe. Bạn sẽ giao tiếp rõ hơn khi đi khám và khi nói về lối sống lành mạnh.",
    structureSections: [
      { label: "Symptoms and diagnosis", wordCount: 6 },
      { label: "Treatment and recovery", wordCount: 6 },
      { label: "Healthy lifestyle", wordCount: 6 },
    ],
    collocationHtml: `${purple("sore throat")}, ${purple("medical prescription")}, ${purple("rest up properly")} và ${purple("balanced diet")} là các cụm trọng tâm.`,
    mistakeHtml: `Tránh dùng ${bold("I am sickness")}; đúng là ${bold("I am sick")} hoặc ${bold("I have a symptom")}.`,
    principles: [
      {
        title: "Mô tả triệu chứng cụ thể thay vì chung chung",
        body: `Nói rõ ${purple("runny nose")}, ${purple("temperature")} hay ${purple("muscle strain")} để người nghe hiểu đúng vấn đề.`,
        examples: [ex("I have a sore throat and a mild temperature.", "Tôi đau họng và sốt nhẹ.")],
      },
      {
        title: "Phân biệt đơn thuốc và hành động điều trị",
        body: `${purple("prescription")} là danh từ, còn ${purple("prescribe")} là động từ bác sĩ thực hiện.`,
        examples: [ex("The doctor prescribed medicine.", "Bác sĩ đã kê thuốc.")],
      },
      {
        title: "Mở rộng từ vựng về sức khỏe dài hạn",
        body: `Kết hợp ${purple("immune system")} và ${purple("mental wellbeing")} để nói sức khỏe toàn diện.`,
        examples: [ex("Regular sleep supports your immune system.", "Ngủ đều đặn hỗ trợ hệ miễn dịch.")],
      },
    ],
    words: U20_WORDS,
    exercises: [
      mcq(
        20,
        1,
        "Từ nào là đơn thuốc bác sĩ đưa cho bệnh nhân?",
        [
          { key: "a", label: "symptom" },
          { key: "b", label: "prescription" },
          { key: "c", label: "check-up" },
          { key: "d", label: "diet" },
        ],
        "b",
      ),
      fillBlank(
        20,
        2,
        "You should ____ and drink more water after getting the flu.",
        "rest up",
        [
          { key: "a", label: "rest up" },
          { key: "b", label: "clock in" },
          { key: "c", label: "cut back" },
          { key: "d", label: "warm up" },
        ],
        "a",
      ),
      mcq(
        20,
        3,
        "Từ nào mang nghĩa mất nước?",
        [
          { key: "a", label: "chronic" },
          { key: "b", label: "dehydrated" },
          { key: "c", label: "balanced" },
          { key: "d", label: "immune" },
        ],
        "b",
      ),
    ],
  }),
  preUnit(21, {
    introVi: "Unit 21 tập trung vào các thành phần trang phục và cách mô tả quần áo phù hợp ngữ cảnh. Bạn sẽ phối hợp được từ về kiểu dáng, chất liệu và mức độ thoải mái.",
    structureSections: [
      { label: "Parts and materials", wordCount: 6 },
      { label: "Style and fit", wordCount: 6 },
      { label: "Usage and occasions", wordCount: 6 },
    ],
    collocationHtml: `${purple("tight-fitting jeans")}, ${purple("formal wear")}, ${purple("try on clothes")} và ${purple("match an outfit")} là các cụm nên luyện kỹ.`,
    mistakeHtml: `Đừng dùng ${bold("very fit")} để nói quần áo; dùng ${bold("it fits well")} khi muốn nói đồ mặc vừa.`,
    principles: [
      {
        title: "Bắt đầu từ phần cấu tạo quần áo",
        body: `Nắm chắc các danh từ như ${purple("sleeve")}, ${purple("collar")} và ${purple("fabric")} để mô tả chính xác.`,
        examples: [ex("The collar is too tight.", "Phần cổ áo hơi chật.")],
      },
      {
        title: "Phân biệt kiểu dáng và chất liệu",
        body: `Dùng ${purple("loose-fitting")} / ${purple("tight-fitting")} cho form, còn ${purple("cotton")} / ${purple("wool")} cho chất liệu.`,
        examples: [ex("I prefer loose-fitting cotton shirts.", "Tôi thích áo cotton rộng.")],
      },
      {
        title: "Diễn đạt phù hợp theo bối cảnh",
        body: `Khi đi sự kiện dùng ${purple("formal wear")}, ngày thường dùng ${purple("casual wear")}.`,
        examples: [ex("The invitation says formal wear only.", "Thiệp mời ghi chỉ mặc trang phục trang trọng.")],
      },
    ],
    words: U21_WORDS,
    exercises: [
      mcq(
        21,
        1,
        "Từ nào chỉ phần cổ của áo?",
        [
          { key: "a", label: "sleeve" },
          { key: "b", label: "collar" },
          { key: "c", label: "fabric" },
          { key: "d", label: "outfit" },
        ],
        "b",
      ),
      fillBlank(
        21,
        2,
        "These trousers are too ____; I need a looser pair.",
        "tight-fitting",
        [
          { key: "a", label: "plain" },
          { key: "b", label: "tight-fitting" },
          { key: "c", label: "casual" },
          { key: "d", label: "comfortable" },
        ],
        "b",
      ),
      mcq(
        21,
        3,
        "Cụm nào nghĩa là thử đồ trước khi mua?",
        [
          { key: "a", label: "match up" },
          { key: "b", label: "try on" },
          { key: "c", label: "wear out" },
          { key: "d", label: "fit in" },
        ],
        "b",
      ),
    ],
  }),
  preUnit(22, {
    introVi: "Unit 22 mở rộng ngôn ngữ mua quần áo và nói về xu hướng thời trang. Bạn sẽ tự tin hơn khi hỏi size, kiểm tra chính sách đổi trả và đánh giá phong cách.",
    structureSections: [
      { label: "In-store process", wordCount: 6 },
      { label: "Buying decisions", wordCount: 6 },
      { label: "Style and value", wordCount: 6 },
    ],
    collocationHtml: `${purple("changing room queue")}, ${purple("size chart")}, ${purple("seasonal sale")} và ${purple("refund policy")} cần dùng rất thường xuyên khi mua đồ.`,
    mistakeHtml: `Không nên nói ${bold("this is very fashion")}; dùng ${bold("this is fashionable")} hoặc ${bold("this is on trend")}.`,
    principles: [
      {
        title: "Hỏi thông tin mua hàng rõ ràng",
        body: `Dùng câu có từ khóa ${purple("in stock")}, ${purple("out of stock")} và ${purple("exchange")} để tránh hiểu nhầm.`,
        examples: [ex("Is this jacket in stock in size M?", "Áo khoác này còn size M không?")],
      },
      {
        title: "Tránh mua bốc đồng bằng ngôn ngữ đánh giá",
        body: `Nhận diện ${purple("impulse buy")} và cân nhắc ${purple("quality")} so với giá.`,
        examples: [ex("I avoided an impulse buy this time.", "Lần này tôi tránh được việc mua bốc đồng.")],
      },
      {
        title: "Phân biệt phong cách theo thời gian",
        body: `${purple("on trend")} dùng cho xu hướng hiện tại, còn ${purple("timeless")} cho món đồ lâu bền.`,
        examples: [ex("A white shirt is timeless.", "Áo sơ mi trắng là món không lỗi mốt.")],
      },
    ],
    words: U22_WORDS,
    exercises: [
      mcq(
        22,
        1,
        "Cụm nào nghĩa là đã hết hàng?",
        [
          { key: "a", label: "in stock" },
          { key: "b", label: "out of stock" },
          { key: "c", label: "on trend" },
          { key: "d", label: "in queue" },
        ],
        "b",
      ),
      fillBlank(
        22,
        2,
        "I checked the ____ before buying shoes online.",
        "size chart",
        [
          { key: "a", label: "refund policy" },
          { key: "b", label: "size chart" },
          { key: "c", label: "quality tag" },
          { key: "d", label: "seasonal sale" },
        ],
        "b",
      ),
      mcq(
        22,
        3,
        "Từ nào mô tả món mua không nằm trong kế hoạch?",
        [
          { key: "a", label: "seasonal sale" },
          { key: "b", label: "impulse buy" },
          { key: "c", label: "affordable" },
          { key: "d", label: "timeless" },
        ],
        "b",
      ),
    ],
  }),
  preUnit(23, {
    introVi: "Unit 23 bao quát từ vựng mua sắm nói chung ở cửa hàng và online. Bạn sẽ xử lý tốt hơn các tình huống so sánh giá, thanh toán và đổi trả.",
    structureSections: [
      { label: "Store types and layout", wordCount: 6 },
      { label: "Buying actions", wordCount: 6 },
      { label: "After-sales and service", wordCount: 6 },
    ],
    collocationHtml: `${purple("compare prices")}, ${purple("special offer")}, ${purple("customer service")} và ${purple("return an item")} là bộ cụm thực tế nhất của chủ đề.`,
    mistakeHtml: `Tránh nói ${bold("I buy in internet")}; cách tự nhiên là ${bold("I shop online")}.`,
    principles: [
      {
        title: "Dùng từ đúng theo bối cảnh cửa hàng",
        body: `Phân biệt ${purple("basket")} và ${purple("trolley")} theo số lượng đồ mua.`,
        examples: [ex("I used a trolley because I bought many items.", "Tôi dùng xe đẩy vì mua nhiều đồ.")],
      },
      {
        title: "Xây cụm động từ khi mua hàng",
        body: `Luyện các cụm ${purple("browse")}, ${purple("compare prices")} và ${purple("shop online")} để nói tự nhiên.`,
        examples: [ex("We compared prices across two stores.", "Chúng tôi so sánh giá giữa hai cửa hàng.")],
      },
      {
        title: "Nắm ngôn ngữ xử lý lỗi sản phẩm",
        body: `Các từ như ${purple("faulty item")} và ${purple("customer service")} rất quan trọng khi cần hỗ trợ.`,
        examples: [ex("Customer service replaced the faulty item.", "Bộ phận chăm sóc khách hàng đã đổi sản phẩm lỗi.")],
      },
    ],
    words: U23_WORDS,
    exercises: [
      mcq(
        23,
        1,
        "Từ nào chỉ xe đẩy lớn trong siêu thị?",
        [
          { key: "a", label: "basket" },
          { key: "b", label: "trolley" },
          { key: "c", label: "aisle" },
          { key: "d", label: "counter" },
        ],
        "b",
      ),
      fillBlank(
        23,
        2,
        "I contacted ____ because the product was broken.",
        "customer service",
        [
          { key: "a", label: "special offer" },
          { key: "b", label: "customer service" },
          { key: "c", label: "checkout counter" },
          { key: "d", label: "delivery slot" },
        ],
        "b",
      ),
      mcq(
        23,
        3,
        "Cụm nào nghĩa là bán hết hàng?",
        [
          { key: "a", label: "sold out" },
          { key: "b", label: "queue up" },
          { key: "c", label: "shop now" },
          { key: "d", label: "special offer" },
        ],
        "a",
      ),
    ],
  }),
  preUnit(24, {
    introVi: "Unit 24 phát triển vốn từ về dinh dưỡng và thói quen ăn uống hằng ngày. Bạn sẽ mô tả được thực phẩm theo thành phần, khẩu phần và cảm nhận vị.",
    structureSections: [
      { label: "Nutrition basics", wordCount: 6 },
      { label: "Food quality and taste", wordCount: 6 },
      { label: "Eating habits", wordCount: 6 },
    ],
    collocationHtml: `${purple("balanced diet")}, ${purple("processed food")}, ${purple("portion size")} và ${purple("food allergy")} là các cụm cần nắm vững.`,
    mistakeHtml: `Đừng nhầm ${bold("hungry")} với ${bold("appetite")}: hungry là cảm giác hiện tại, appetite là khả năng/thói quen thèm ăn.`,
    principles: [
      {
        title: "Nhóm từ theo thành phần dinh dưỡng",
        body: `Học theo cụm ${purple("protein")}, ${purple("fibre")}, ${purple("carbohydrate")} để đọc nhãn thực phẩm tốt hơn.`,
        examples: [ex("This meal has protein and fibre.", "Bữa này có đạm và chất xơ.")],
      },
      {
        title: "Mô tả vị và chất lượng món ăn rõ nghĩa",
        body: `Dùng ${purple("greasy")}, ${purple("spicy")} hoặc ${purple("bland")} để nói đúng trải nghiệm vị giác.`,
        examples: [ex("The soup is nutritious but bland.", "Món súp bổ dưỡng nhưng hơi nhạt.")],
      },
      {
        title: "Nói về lựa chọn ăn uống hiện đại",
        body: `Phân biệt ${purple("vegetarian")} và ${purple("vegan")} khi gọi món hoặc đọc menu.`,
        examples: [ex("She is vegan, so she avoids dairy products.", "Cô ấy ăn thuần chay nên tránh sản phẩm từ sữa.")],
      },
    ],
    words: U24_WORDS,
    exercises: [
      mcq(
        24,
        1,
        "Từ nào chỉ đồ ăn chế biến sẵn?",
        [
          { key: "a", label: "processed food" },
          { key: "b", label: "wholegrain" },
          { key: "c", label: "leftovers" },
          { key: "d", label: "protein" },
        ],
        "a",
      ),
      fillBlank(
        24,
        2,
        "Try to control your ____ if you want to avoid overeating.",
        "portion size",
        [
          { key: "a", label: "appetite" },
          { key: "b", label: "portion size" },
          { key: "c", label: "snack time" },
          { key: "d", label: "diet food" },
        ],
        "b",
      ),
      mcq(
        24,
        3,
        "Từ nào mang nghĩa nhạt, thiếu vị?",
        [
          { key: "a", label: "spicy" },
          { key: "b", label: "greasy" },
          { key: "c", label: "bland" },
          { key: "d", label: "nutritious" },
        ],
        "c",
      ),
    ],
  }),
  preUnit(25, {
    introVi: "Unit 25 cung cấp động từ nấu ăn cốt lõi từ chuẩn bị đến hoàn thành món. Bạn sẽ mô tả quy trình bếp chính xác hơn, tránh nói chung chung kiểu cook everything.",
    structureSections: [
      { label: "Preparation actions", wordCount: 6 },
      { label: "Cooking techniques", wordCount: 6 },
      { label: "Tools and outcomes", wordCount: 6 },
    ],
    collocationHtml: `${purple("chop and slice")}, ${purple("boil then simmer")}, ${purple("season to taste")} và ${purple("marinate overnight")} là các cụm cực kỳ thông dụng.`,
    mistakeHtml: `Đừng dùng ${bold("cook with big fire")} trong tiếng Anh tự nhiên; nên nói ${bold("cook on high heat")} hoặc ${bold("simmer on low heat")}.`,
    principles: [
      {
        title: "Chọn động từ theo kỹ thuật cụ thể",
        body: `Ví dụ ${purple("boil")} khác ${purple("steam")}, và ${purple("fry")} khác ${purple("roast")}.`,
        examples: [ex("Steam the fish, don't fry it.", "Hấp cá, đừng chiên.")],
      },
      {
        title: "Nêu rõ thứ tự thao tác trong công thức",
        body: `Kết hợp động từ nối bước như ${purple("chop")}, ${purple("marinate")} rồi ${purple("roast")} để câu mạch lạc.`,
        examples: [ex("Chop, marinate, then roast the chicken.", "Băm/cắt, ướp rồi nướng gà.")],
      },
      {
        title: "Mô tả kết quả món ăn chính xác",
        body: `Dùng ${purple("undercooked")} hoặc ${purple("overcooked")} để nói chất lượng món sau khi nấu.`,
        examples: [ex("The steak is overcooked.", "Miếng bít tết bị chín quá.")],
      },
    ],
    words: U25_WORDS,
    exercises: [
      mcq(
        25,
        1,
        "Động từ nào nghĩa là đun liu riu?",
        [
          { key: "a", label: "fry" },
          { key: "b", label: "simmer" },
          { key: "c", label: "grate" },
          { key: "d", label: "slice" },
        ],
        "b",
      ),
      fillBlank(
        25,
        2,
        "Please ____ the soup before serving so it has enough flavor.",
        "season",
        [
          { key: "a", label: "stir" },
          { key: "b", label: "season" },
          { key: "c", label: "boil" },
          { key: "d", label: "steam" },
        ],
        "b",
      ),
      mcq(
        25,
        3,
        "Từ nào mô tả món ăn chưa chín kỹ?",
        [
          { key: "a", label: "overcooked" },
          { key: "b", label: "undercooked" },
          { key: "c", label: "roasted" },
          { key: "d", label: "seasoned" },
        ],
        "b",
      ),
    ],
  }),
  preUnit(26, {
    introVi: "Unit 26 giúp bạn nói về cuộc sống thành phố từ giao thông đến nhịp sống xã hội. Bạn sẽ có đủ từ để nêu cả điểm mạnh lẫn áp lực của môi trường đô thị.",
    structureSections: [
      { label: "Urban landscape", wordCount: 6 },
      { label: "Mobility and infrastructure", wordCount: 6 },
      { label: "City lifestyle", wordCount: 6 },
    ],
    collocationHtml: `${purple("city skyline")}, ${purple("public transport system")}, ${purple("traffic jam at rush hour")} và ${purple("vibrant nightlife")} là các cụm chủ lực.`,
    mistakeHtml: `Không dùng ${bold("very many traffic")} mà nên nói ${bold("heavy traffic")} hoặc ${bold("a traffic jam")}.`,
    principles: [
      {
        title: "Mô tả thành phố theo ba lớp",
        body: "Bắt đầu với cảnh quan, rồi giao thông, cuối cùng là nhịp sống để câu trả lời có cấu trúc.",
        examples: [ex("The skyline is modern but traffic is heavy.", "Đường chân trời hiện đại nhưng giao thông nặng.")],
      },
      {
        title: "Dùng từ chỉ hạ tầng giao thông cụ thể",
        body: `Các từ như ${purple("cycle lane")}, ${purple("pedestrian zone")} và ${purple("public square")} làm mô tả chính xác hơn.`,
        examples: [ex("The new pedestrian zone is safer for families.", "Khu đi bộ mới an toàn hơn cho gia đình.")],
      },
      {
        title: "Cân bằng giữa lợi ích và thách thức",
        body: `Ghép từ tích cực như ${purple("convenience")} với từ trung tính như ${purple("pollution")} hoặc ${purple("crowded")}.`,
        examples: [ex("City life is convenient but expensive.", "Sống ở thành phố tiện nhưng đắt.")],
      },
    ],
    words: U26_WORDS,
    exercises: [
      mcq(
        26,
        1,
        "Từ nào chỉ tình trạng kẹt xe?",
        [
          { key: "a", label: "rush hour" },
          { key: "b", label: "traffic jam" },
          { key: "c", label: "nightlife" },
          { key: "d", label: "pollution" },
        ],
        "b",
      ),
      fillBlank(
        26,
        2,
        "Cars are not allowed inside this ____.",
        "pedestrian zone",
        [
          { key: "a", label: "public square" },
          { key: "b", label: "pedestrian zone" },
          { key: "c", label: "cycle lane" },
          { key: "d", label: "city centre" },
        ],
        "b",
      ),
      mcq(
        26,
        3,
        "Tính từ nào nghĩa là sôi động, đầy sức sống?",
        [
          { key: "a", label: "crowded" },
          { key: "b", label: "vibrant" },
          { key: "c", label: "isolated" },
          { key: "d", label: "remote" },
        ],
        "b",
      ),
    ],
  }),
  preUnit(27, {
    introVi: "Unit 27 tập trung vào đời sống nông thôn với từ vựng về nông trại, mùa vụ và cộng đồng làng xã. Bạn sẽ diễn đạt rõ sự khác biệt giữa nhịp sống quê và thành thị.",
    structureSections: [
      { label: "Rural places and farming", wordCount: 6 },
      { label: "Community and seasons", wordCount: 6 },
      { label: "Lifestyle descriptions", wordCount: 6 },
    ],
    collocationHtml: `${purple("harvest season")}, ${purple("fresh produce")}, ${purple("close-knit community")} và ${purple("remote village")} là các cụm quan trọng.`,
    mistakeHtml: `Tránh nói ${bold("the life is very peace")}; cách đúng là ${bold("life is peaceful")} hoặc ${bold("it is a peaceful life")}.`,
    principles: [
      {
        title: "Dùng từ cụ thể khi tả bối cảnh nông thôn",
        body: `Các danh từ như ${purple("orchard")}, ${purple("pasture")} và ${purple("farmhouse")} giúp bức tranh rõ ràng hơn.`,
        examples: [ex("They live near an orange orchard.", "Họ sống gần vườn cam.")],
      },
      {
        title: "Kết hợp yếu tố mùa vụ và cộng đồng",
        body: `${purple("harvest season")} và ${purple("village fair")} thường đi cùng trong mô tả nông thôn.`,
        examples: [ex("The village fair starts after harvest season.", "Hội làng bắt đầu sau mùa thu hoạch.")],
      },
      {
        title: "Mô tả cảm nhận sống ở quê bằng tính từ phù hợp",
        body: `Dùng ${purple("peaceful")}, ${purple("remote")} hoặc ${purple("isolated")} tùy sắc thái tích cực/trung tính.`,
        examples: [ex("It is peaceful but a bit remote.", "Nơi này yên bình nhưng hơi xa xôi.")],
      },
    ],
    words: U27_WORDS,
    exercises: [
      mcq(
        27,
        1,
        "Từ nào chỉ vườn cây ăn quả?",
        [
          { key: "a", label: "pasture" },
          { key: "b", label: "orchard" },
          { key: "c", label: "barn" },
          { key: "d", label: "farmhouse" },
        ],
        "b",
      ),
      fillBlank(
        27,
        2,
        "Local farmers are busiest during ____.",
        "harvest season",
        [
          { key: "a", label: "village fair" },
          { key: "b", label: "sunrise" },
          { key: "c", label: "harvest season" },
          { key: "d", label: "well water" },
        ],
        "c",
      ),
      mcq(
        27,
        3,
        "Tính từ nào nghĩa là xa xôi, hẻo lánh?",
        [
          { key: "a", label: "close-knit" },
          { key: "b", label: "fresh" },
          { key: "c", label: "remote" },
          { key: "d", label: "crowded" },
        ],
        "c",
      ),
    ],
  }),
  preUnit(28, {
    introVi: "Unit 28 phát triển ngôn ngữ đi lại bằng phương tiện công cộng: tàu, xe và các chuyến nối. Bạn sẽ xử lý tốt hơn tình huống mua vé, đổi tuyến và chậm chuyến.",
    structureSections: [
      { label: "Stations and tickets", wordCount: 6 },
      { label: "Travel actions", wordCount: 6 },
      { label: "Scheduling and routes", wordCount: 6 },
    ],
    collocationHtml: `${purple("check the timetable")}, ${purple("board the train")}, ${purple("miss a connection")} và ${purple("peak hours fare")} là các cụm rất phổ biến.`,
    mistakeHtml: `Tránh nói ${bold("I go down the train")} trong ngữ cảnh trang trọng; dùng ${bold("I alight at...")} hoặc ${bold("I get off at...")}.`,
    principles: [
      {
        title: "Làm rõ các loại vé và chi phí",
        body: `Phân biệt ${purple("one-way ticket")}, ${purple("return ticket")} và ${purple("season ticket")} theo nhu cầu di chuyển.`,
        examples: [ex("A season ticket is best for daily commuters.", "Vé tháng hợp nhất cho người đi lại hằng ngày.")],
      },
      {
        title: "Dùng động từ đúng ngữ cảnh giao thông",
        body: `${purple("board")} là lên phương tiện, còn ${purple("alight")} là xuống.`,
        examples: [ex("Please board quickly and alight in order.", "Hãy lên xe nhanh và xuống xe theo thứ tự.")],
      },
      {
        title: "Nói về sự cố đi lại chính xác",
        body: `Các từ ${purple("delay")}, ${purple("cancel service")} và ${purple("connection")} rất hữu ích khi hỏi thông tin.`,
        examples: [ex("Our connection was delayed by heavy rain.", "Chuyến nối của chúng tôi bị chậm do mưa lớn.")],
      },
    ],
    words: U28_WORDS,
    exercises: [
      mcq(
        28,
        1,
        "Từ nào chỉ vé khứ hồi?",
        [
          { key: "a", label: "season ticket" },
          { key: "b", label: "return ticket" },
          { key: "c", label: "platform pass" },
          { key: "d", label: "one-way route" },
        ],
        "b",
      ),
      fillBlank(
        28,
        2,
        "Our train leaves from ____ 2 in ten minutes.",
        "platform",
        [
          { key: "a", label: "carriage" },
          { key: "b", label: "platform" },
          { key: "c", label: "route" },
          { key: "d", label: "timetable" },
        ],
        "b",
      ),
      mcq(
        28,
        3,
        "Động từ nào nghĩa là xuống tàu/xe?",
        [
          { key: "a", label: "board" },
          { key: "b", label: "transfer" },
          { key: "c", label: "alight" },
          { key: "d", label: "reserve" },
        ],
        "c",
      ),
    ],
  }),
  preUnit(29, {
    introVi: "Unit 29 tập trung vào tình huống đi đường và lái xe an toàn. Bạn sẽ nắm được biển báo cơ bản, lỗi giao thông phổ biến và từ vựng xử lý sự cố xe.",
    structureSections: [
      { label: "Road layout", wordCount: 6 },
      { label: "Driving actions and safety", wordCount: 6 },
      { label: "Problems and penalties", wordCount: 6 },
    ],
    collocationHtml: `${purple("speed limit sign")}, ${purple("pedestrian crossing")}, ${purple("wear a seat belt")} và ${purple("get a traffic fine")} là các cụm cốt lõi.`,
    mistakeHtml: `Không nói ${bold("open the light")} khi lái xe; nên nói ${bold("turn on the indicator")} hoặc ${bold("indicate before turning")}.`,
    principles: [
      {
        title: "Nhận diện cấu trúc đường và điểm giao",
        body: `Phân biệt ${purple("junction")} và ${purple("roundabout")} để hiểu chỉ dẫn chính xác.`,
        examples: [ex("Take the first exit at the roundabout.", "Đi lối ra đầu tiên ở vòng xuyến.")],
      },
      {
        title: "Ưu tiên từ vựng an toàn khi lái",
        body: `Các hành động như ${purple("indicate")}, ${purple("brake")} và ${purple("wear a seat belt")} cần dùng đúng ngữ cảnh.`,
        examples: [ex("Always indicate before changing lanes.", "Luôn bật xi nhan trước khi chuyển làn.")],
      },
      {
        title: "Biết diễn đạt sự cố trên đường",
        body: `Nắm từ ${purple("flat tyre")}, ${purple("detour")} và ${purple("roadworks")} để xử lý tình huống thực tế.`,
        examples: [ex("We took a detour because of roadworks.", "Chúng tôi đi đường vòng vì công trình sửa đường.")],
      },
    ],
    words: U29_WORDS,
    exercises: [
      mcq(
        29,
        1,
        "Từ nào chỉ vòng xuyến?",
        [
          { key: "a", label: "lane" },
          { key: "b", label: "junction" },
          { key: "c", label: "roundabout" },
          { key: "d", label: "detour" },
        ],
        "c",
      ),
      fillBlank(
        29,
        2,
        "You must not exceed the ____ on this road.",
        "speed limit",
        [
          { key: "a", label: "traffic light" },
          { key: "b", label: "speed limit" },
          { key: "c", label: "roadworks" },
          { key: "d", label: "seat belt" },
        ],
        "b",
      ),
      mcq(
        29,
        3,
        "Cụm nào nghĩa là đỗ xe sai quy định?",
        [
          { key: "a", label: "park illegally" },
          { key: "b", label: "overtake carefully" },
          { key: "c", label: "take a lane" },
          { key: "d", label: "stop by station" },
        ],
        "a",
      ),
    ],
  }),
  preUnit(30, {
    introVi: "Unit 30 cung cấp từ vựng trên biển báo, nhãn hướng dẫn và cảnh báo an toàn thường gặp. Bạn sẽ hiểu nhanh các thông điệp ngắn nhưng quan trọng trong nơi công cộng.",
    structureSections: [
      { label: "Prohibition and access signs", wordCount: 6 },
      { label: "Safety warnings", wordCount: 6 },
      { label: "Instruction labels", wordCount: 6 },
    ],
    collocationHtml: `${purple("no entry sign")}, ${purple("emergency exit")}, ${purple("high voltage warning")} và ${purple("handle with care")} là các cụm bắt buộc nên thuộc.`,
    mistakeHtml: `Đừng bỏ qua biển báo ngắn như ${bold("out of order")} hoặc ${bold("wet paint")}; dù ít từ nhưng thông tin rất quan trọng cho an toàn.`,
    principles: [
      {
        title: "Nhận diện nhóm biển cấm và giới hạn",
        body: `Các cụm ${purple("no entry")}, ${purple("keep out")}, ${purple("staff only")} thường liên quan quyền truy cập khu vực.`,
        examples: [ex("That corridor is staff only.", "Hành lang đó chỉ dành cho nhân viên.")],
      },
      {
        title: "Ưu tiên hiểu biển cảnh báo nguy hiểm",
        body: `Nhóm từ như ${purple("slippery floor")}, ${purple("high voltage")} hoặc ${purple("fire alarm")} cần phản xạ nhanh.`,
        examples: [ex("The sign warns of high voltage.", "Biển báo cảnh báo điện áp cao.")],
      },
      {
        title: "Đọc kỹ nhãn hướng dẫn ngắn",
        body: `Các từ một bước như ${purple("push")} và ${purple("pull")} thường quyết định thao tác đúng ngay lập tức.`,
        examples: [ex("Push this door to open it.", "Đẩy cửa này để mở.")],
      },
    ],
    words: U30_WORDS,
    exercises: [
      mcq(
        30,
        1,
        "Biển nào nghĩa là cấm vào?",
        [
          { key: "a", label: "queue here" },
          { key: "b", label: "no entry" },
          { key: "c", label: "push" },
          { key: "d", label: "pull" },
        ],
        "b",
      ),
      fillBlank(
        30,
        2,
        "Please use the ____ in case of fire.",
        "emergency exit",
        [
          { key: "a", label: "staff only" },
          { key: "b", label: "no smoking" },
          { key: "c", label: "emergency exit" },
          { key: "d", label: "handle with care" },
        ],
        "c",
      ),
      mcq(
        30,
        3,
        "Cụm nào cảnh báo đồ dễ vỡ khi vận chuyển?",
        [
          { key: "a", label: "high voltage" },
          { key: "b", label: "wet paint" },
          { key: "c", label: "mind the gap" },
          { key: "d", label: "handle with care" },
        ],
        "d",
      ),
    ],
  }),
];
