import type { VocabularyUnit } from "@/lib/vocabulary/vocabulary-unit-types";
import {
  bold,
  ex,
  fillBlank,
  mcq,
  purple,
} from "@/lib/vocabulary/units/eviu-unit-builder";
import { advancedUnit, wordList } from "@/lib/vocabulary/units/eviu-advanced-unit-helpers";

const U76_WORDS = wordList([
  ["promise the earth", "hứa hẹn quá mức, không thực tế", "Politicians often promise the earth before elections.", "PHRASE"],
  ["anticipate", "dự đoán trước khi xảy ra", "We anticipate that the afternoon will be interesting.", "VERB"],
  ["promising", "đầy triển vọng (người/tài năng)", "She is a promising artist although her style is still immature.", "ADJECTIVE"],
  ["oath", "lời thề trang trọng", "Witnesses are put under oath in court.", "NOUN"],
  ["swear by", "tin tưởng tuyệt đối vào (sản phẩm, phương pháp)", "My mother swears by these vitamin pills.", "VERB"],
  ["swear words", "từ chửi thề, ngôn ngữ cấm kỵ", "Tom often uses swear words when he is angry.", "PHRASE"],
  ["pledge", "cam kết (thường tiền hoặc tình bạn)", "The mayor pledged millions to improve the city centre.", "VERB"],
  ["vow", "thề, quyết tâm mạnh mẽ", "He vowed to discover who had killed his father.", "VERB"],
  ["turn over a new leaf", "bắt đầu lại, thay đổi hành vi tốt hơn", "New Year's resolutions help people turn over a new leaf.", "IDIOM"],
  ["go back on your word", "nuốt lời, không giữ lời hứa", "If you go back on your word, people will stop trusting you.", "PHRASE"],
  ["gambling", "cờ bạc, đặt cược tiền", "People lose a lot of money gambling on football.", "NOUN"],
  ["stake", "số tiền đặt cược; mức rủi ro", "She put a stake of £10 on the horse.", "NOUN"],
  ["at stake", "đang bị đe dọa, có thể mất", "Many lives will be at stake if the flood barrier is not built.", "PHRASE"],
  ["wager", "đặt cược (trang trọng hơn bet)", "I would wager that he will come to a bad end.", "VERB"],
  ["best bet", "lựa chọn tốt nhất", "Your best bet would be to look for a part-time job.", "PHRASE"],
  ["don't bet on it", "đừng trông chờ, khó xảy ra", "You think Stuart will win? Don't bet on it!", "PHRASE"],
  ["have a flutter", "đặt cược nhỏ (informal)", "My granny enjoys having a flutter on the horses.", "PHRASE"],
  ["bet my life on", "chắc chắn tuyệt đối", "I'd bet my life on James getting the job.", "PHRASE"],
  ["you bet", "chắc chắn rồi! (informal)", "Do you feel like coming to the beach? You bet!", "PHRASE"],
  ["hedge your bets", "phòng ngừa rủi ro bằng nhiều lựa chọn", "You can hedge your bets by investing in several companies.", "PHRASE"],
  ["the odds", "tỷ lệ cược; khả năng xảy ra", "The odds are against her getting that promotion.", "PHRASE"],
]);

const U77_WORDS = wordList([
  ["out of touch", "mất liên lạc, không biết tin mới", "I've been a bit out of touch since I moved away.", "PHRASE"],
  ["what became of", "điều gì đã xảy ra với", "I wonder what became of that maths teacher.", "PHRASE"],
  ["think back", "hồi tưởng, nghĩ về quá khứ", "When I think back, I realise how difficult things were.", "VERB"],
  ["lost touch", "mất liên lạc với ai", "I've lost touch with Sanjay too.", "PHRASE"],
  ["takes me back to", "khiến tôi nhớ lại", "That song takes me back to our school days.", "PHRASE"],
  ["vague memory", "ký ức mơ hồ", "I have a vague memory of that day.", "PHRASE"],
  ["coming back to me", "dần nhớ lại rõ hơn", "It's all coming back to me now.", "PHRASE"],
  ["stands out in my mind", "nổi bật trong trí nhớ", "What stands out in my mind is the freedom we had.", "PHRASE"],
  ["reminisce about", "hồi tưởng về điều vui trong quá khứ", "I often find myself reminiscing about my teenage years.", "VERB"],
  ["rose-tinted spectacles", "nhìn quá khứ chỉ thấy điều tốt", "We all tend to look at the past through rose-tinted spectacles.", "PHRASE"],
  ["nostalgia", "nỗi nhớ hoài niệm vui buồn lẫn lộn", "A bit of nostalgia does nobody any harm.", "NOUN"],
  ["regret", "hối tiếc", "I regret not spending more time with my aunt.", "VERB"],
  ["remorse", "hối hận sâu sắc về việc đã làm", "He showed no sign of remorse for what he had done.", "NOUN"],
  ["pangs of guilt", "cơn đau tội lỗi bất ngờ", "I felt great pangs of guilt thinking of what happened.", "PHRASE"],
  ["rue the day", "hối hận sâu sắc (trang trọng)", "I rue the day we ever met.", "PHRASE"],
  ["lament", "than thở, tiếc nuối (văn chương)", "I lament the passing of time.", "VERB"],
  ["mourn lost opportunities", "buồn vì bỏ lỡ cơ hội", "I mourn my lost opportunities.", "PHRASE"],
  ["hear anything of", "nghe tin gì về ai", "Do you ever hear anything of James?", "PHRASE"],
  ["recall", "nhớ lại (nếu nhớ đúng)", "If I recall, his name was Mr Sanderson.", "VERB"],
  ["shame", "xấu hổ và tội lỗi về việc xấu", "She felt great shame for what had happened.", "NOUN"],
]);

const U78_WORDS = wordList([
  ["tally with", "khớp, phù hợp với", "Her complaints tally with comments from other people.", "VERB"],
  ["concur with", "đồng ý với ý kiến", "His opinion concurs with the general opinion of experts.", "VERB"],
  ["in full accord with", "hoàn toàn đồng ý với", "The President was in full accord with the opposition.", "PHRASE"],
  ["coincide with", "trùng khớp với", "Your views coincide with mine on crime and punishment.", "VERB"],
  ["conform to", "phù hợp với (kỳ vọng, quy tắc)", "His behaviour does not conform to the school's expectations.", "VERB"],
  ["approve of", "tán thành, cho là đúng", "My parents approve of my choice of profession.", "VERB"],
  ["meet with approval", "được ai đó tán thành", "The plan met with the board's approval.", "PHRASE"],
  ["agree to differ", "đồng ý bất đồng, không tranh nữa", "We couldn't reach consensus, so we agreed to differ.", "PHRASE"],
  ["dissent", "bất đồng với quan điểm chính thức", "There is dissent in the party on the issue.", "NOUN"],
  ["discord", "bất hòa, thiếu đồng thuận", "The general discord between members hurt the club.", "NOUN"],
  ["rift", "vết nứt, bất đồng sâu (nhóm chính trị)", "The growing rift in the party is now public.", "NOUN"],
  ["split", "chia tách vì bất đồng", "A major split resulted in ministers forming a new party.", "NOUN"],
  ["division", "chia rẽ (trang trọng, trừu tượng)", "There is major division in the party over economic policy.", "NOUN"],
  ["controversy", "tranh cãi lớn ảnh hưởng nhiều người", "Plans for a new airport are bound to cause controversy.", "NOUN"],
  ["compromise", "thỏa hiệp", "The two sides reached a compromise over the new road.", "NOUN"],
  ["concessions", "nhượng bộ (một phần yêu cầu)", "The government made several concessions to the protesters.", "NOUN"],
  ["settlement", "thỏa thuận giải quyết tranh chấp", "Management and the union reached a settlement.", "NOUN"],
  ["exercise discretion", "dùng phán đoán nhạy cảm", "We should exercise discretion and avoid more conflict.", "PHRASE"],
  ["consensus", "sự đồng thuận chung", "We couldn't reach a consensus at the meeting.", "NOUN"],
  ["absolutely", "hoàn toàn đồng ý (phản hồi nhanh)", "A: It would be risky. B: Absolutely!", "ADVERB"],
]);

const U79_WORDS = wordList([
  ["advocate", "ủng hộ, bênh vực (trong luận văn)", "He advocated capital punishment in his essay.", "VERB"],
  ["deduce", "suy luận từ sự kiện đã biết", "Can you deduce how the imperfect tense is used?", "VERB"],
  ["infer", "suy ra gián tiếp", "From contemporary accounts we can infer that results were slower.", "VERB"],
  ["complements", "bổ sung, làm tăng hiệu quả lẫn nhau", "Elswick's research complements that of Johnson.", "VERB"],
  ["overlaps with", "trùng lặp một phần với", "Her work overlaps with earlier studies on the topic.", "PHRASE"],
  ["empirical", "dựa trên quan sát thực tế, không chỉ lý thuyết", "The study presents empirical evidence from fieldwork.", "ADJECTIVE"],
  ["ambiguous", "mơ hồ, có thể hiểu nhiều cách", "The conclusion is ambiguous and open to debate.", "ADJECTIVE"],
  ["coherent", "mạch lạc, logic rõ ràng", "The argument is coherent from start to finish.", "ADJECTIVE"],
  ["comprehensive", "toàn diện, bao quát đủ", "She wrote a comprehensive review of the literature.", "ADJECTIVE"],
  ["authoritative", "uy tín, chuyên sâu", "It is the most authoritative account of the period.", "ADJECTIVE"],
  ["arbitrary", "tùy ý, không dựa trên hệ thống rõ", "The figures seem arbitrary rather than data-driven.", "ADJECTIVE"],
  ["deviate from the norm", "lệch khỏi mức trung bình", "Results that deviate from the norm need explanation.", "PHRASE"],
  ["distort the picture", "bóp méo, tạo ấn tượng sai", "Small samples can distort the picture.", "PHRASE"],
  ["incidence", "tần suất xảy ra (bệnh, hiện tượng)", "We measured the incidence of brown eyes in the sample.", "NOUN"],
  ["predominant", "chiếm ưu thế về số lượng", "English was the predominant language in the dataset.", "ADJECTIVE"],
  ["in sequence", "theo thứ tự nhất định", "The stages happen in sequence.", "PHRASE"],
  ["widespread", "lan rộng khắp nơi", "There were widespread outbreaks of the illness.", "ADJECTIVE"],
  ["denote", "biểu thị, đại diện cho", "The symbol denotes a change in direction.", "VERB"],
  ["negate", "phủ nhận hiệu lực, làm vô hiệu", "One error can negate the whole argument.", "VERB"],
  ["thereby", "bằng cách đó, do đó", "She revised the draft, thereby improving clarity.", "ADVERB"],
  ["whereby", "theo cách mà", "A system whereby data is shared openly.", "ADVERB"],
  ["notwithstanding", "bất chấp, mặc dù vậy", "Notwithstanding these limits, the study is useful.", "ADVERB"],
]);

const U80_WORDS = wordList([
  ["reiterate", "nhắc lại (nhấn mạnh)", "The Prime Minister reiterated her concern.", "VERB"],
  ["summarise", "tóm tắt ý chính", "She summarised the new policy as progressive.", "VERB"],
  ["epitomise", "là hình mẫu tiêu biểu của", "His comments epitomise the attitude of many parents.", "VERB"],
  ["expound", "trình bày chi tiết (lý thuyết)", "It was a philosophy first expounded by Ruskin.", "VERB"],
  ["underscore", "nhấn mạnh tầm quan trọng", "Recent events underscore the need for better understanding.", "VERB"],
  ["posit", "đề xuất như giả thuyết cơ bản", "Several scientists have posited a link with migration.", "VERB"],
  ["account for", "giải thích nguyên nhân", "Analysts tried to account for the lack of interest.", "PHRASE"],
  ["comprised of", "gồm có, cấu thành từ", "The course is comprised of two elements.", "PHRASE"],
  ["subsumed under", "gộp chung dưới một mục", "These approaches can be subsumed under one heading.", "PHRASE"],
  ["embraces", "bao gồm, đề cập nhiều vấn đề", "The book embraces issues from economic to religious.", "VERB"],
  ["categorise", "phân loại vào nhóm", "Her philosophy is difficult to categorise.", "VERB"],
  ["preface", "mở đầu bài luận bằng phần giới thiệu", "I should like to preface my argument with a story.", "VERB"],
  ["address the question", "đi vào trực tiếp vấn đề", "I should now like to address the question of the arms race.", "PHRASE"],
  ["ascending order", "theo thứ tự tăng dần (quan trọng)", "Arguments are presented in ascending order of importance.", "PHRASE"],
  ["cited", "trích dẫn (tác giả)", "Several writers will be cited in support.", "VERB"],
  ["alludes to", "ám chỉ, nhắc gián tiếp", "The text alludes to themes needing closer examination.", "VERB"],
  ["touch upon", "đề cập sơ qua", "There is only space to touch upon political responsibility.", "PHRASE"],
  ["beyond the scope", "vượt phạm vi bài viết", "Discussion of the roots is beyond the scope of this essay.", "PHRASE"],
  ["asserting", "khẳng định mạnh mẽ", "Parents are asserting that schools are to blame.", "VERB"],
  ["consist of", "gồm có (cấu trúc chính thức)", "The country consists of five major regions.", "VERB"],
]);

const U81_WORDS = wordList([
  ["scribble", "viết vội, cẩu thả", "If you're in a hurry, you can scribble a note.", "VERB"],
  ["chatty", "thân mật, như trò chuyện (văn phong)", "A note is likely to be in a more chatty style.", "ADJECTIVE"],
  ["jot down", "ghi nhanh để nhớ", "I'll jot down your phone number before I forget.", "VERB"],
  ["doodle", "vẽ/viết linh tinh khi chán", "She spent the meeting doodling on her notepad.", "VERB"],
  ["copy out", "chép lại bằng tay", "I'll copy out the hotel information for you.", "VERB"],
  ["drafting", "viết bản nháp đầu tiên", "I'm just drafting an application letter.", "VERB"],
  ["write up", "viết bản hoàn chỉnh từ nháp", "She's writing up her dissertation at the moment.", "VERB"],
  ["manuscript", "bản thảo gốc của tác giả", "She bought the manuscript of a famous poem.", "NOUN"],
  ["touch-type", "đánh máy không nhìn phím", "Learning to touch-type was very useful.", "VERB"],
  ["typescript", "bản đánh máy chưa xuất bản", "I'll email the typescript to the publisher.", "NOUN"],
  ["run off a copy", "in ra một bản", "I'll run you off a copy at the same time.", "PHRASE"],
  ["format", "định dạng trang trước khi in", "I want to format it properly before printing.", "VERB"],
  ["cut and paste", "cắt dán văn bản trên máy", "I cut and paste bits from my notes into the essay.", "PHRASE"],
  ["characters", "ký tự trên bàn phím", "A password often needs at least eight characters.", "NOUN"],
  ["italicised", "in nghiêng", "These words are italicised in the printed book.", "ADJECTIVE"],
  ["indented", "thụt lề so với lề chuẩn", "This sentence is indented from the margin.", "ADJECTIVE"],
  ["bullet point", "dấu chấm đầu dòng", "This sentence has a bullet point in front of it.", "NOUN"],
  ["superscript", "chữ số viết cao hơn dòng", "The page numbers on the extract are in superscript.", "ADJECTIVE"],
  ["block capitals", "viết hoa toàn bộ chữ cái", "She wrote her name in block capitals.", "PHRASE"],
  ["chapter heading", "tiêu đề chương", "Look at the chapter heading on the first page.", "NOUN"],
  ["sub-heading", "tiêu đề phụ trong chương", "Section 1.1 is a sub-heading within the chapter.", "NOUN"],
]);

const U82_WORDS = wordList([
  ["make a big thing of it", "làm ầm ĩ quá mức", "Don't make such a big thing of it!", "PHRASE"],
  ["the thing is", "vấn đề là (giới thiệu lý do)", "The thing is, I have to take my car for a service.", "PHRASE"],
  ["as things are", "theo tình hình hiện tại", "As things are at present, we cannot afford it.", "PHRASE"],
  ["get things sorted", "sắp xếp để giải quyết vấn đề", "Jill will get things sorted out today.", "PHRASE"],
  ["whatchamacallit", "cái gì đó (quên tên)", "Have you seen the whatchamacallit we use for the door?", "NOUN"],
  ["whatsit", "cái gì đó (vật, informal)", "Pass me that whatsit on the shelf.", "NOUN"],
  ["whatsisname", "ông kia (quên tên, informal)", "Did you see whatsisname today?", "NOUN"],
  ["bags of", "rất nhiều (thời gian, informal)", "I can help you — I've got bags of time.", "PHRASE"],
  ["loads of", "rất nhiều (informal)", "They've got loads of money for holidays.", "PHRASE"],
  ["umpteen", "vô số lần (informal)", "I've tried phoning her umpteen times.", "ADJECTIVE"],
  ["a scrap of", "một chút xíu (thường phủ định)", "You haven't done a scrap of work all day.", "PHRASE"],
  ["not the most practical", "cách nói gián tiếp chỉ trích", "It's not the most practical idea you've ever had.", "PHRASE"],
  ["no offence intended", "không có ý xúc phạm", "No offence intended, but I think you've misunderstood.", "PHRASE"],
  ["if you don't mind me saying", "xin phép nói thẳng (lịch sự)", "If you don't mind me saying so, you could have handled that better.", "PHRASE"],
  ["I gather", "tôi nghe được rằng", "I gather you feel upset by the recent changes.", "PHRASE"],
  ["incidentally", "nhân tiện (chuyển chủ đề gián tiếp)", "Incidentally, have you paid for the club outing?", "ADVERB"],
  ["present company excepted", "trừ những người có mặt ở đây", "What a load of idiots — present company excepted.", "PHRASE"],
  ["myself included", "kể cả bản thân tôi", "The staff here, myself included, haven't worked hard enough.", "PHRASE"],
  ["for one thing", "trước hết là (liệt kê lý do)", "For one thing, I haven't got time.", "PHRASE"],
  ["get it together", "tự tổ chức, hành động quyết đoán", "She never got it together to travel the world.", "PHRASE"],
]);

const U83_WORDS = wordList([
  ["in excess of", "hơn, vượt quá (trang trọng)", "He left a sum in excess of $1 million.", "PHRASE"],
  ["in the region of", "khoảng, xấp xỉ", "It'll cost in the region of £900 a month.", "PHRASE"],
  ["give or take", "cộng trừ một chút", "It'll take five hours, give or take half an hour.", "PHRASE"],
  ["approximately", "xấp xỉ (trang trọng)", "The second meeting is approximately two and a half months later.", "ADVERB"],
  ["a week or so", "khoảng một tuần (informal)", "It'll take a week or so to repair the computer.", "PHRASE"],
  ["quite a few", "khá nhiều (bất ngờ hoặc không mong muốn)", "Quite a few students hadn't registered.", "PHRASE"],
  ["smattering", "một ít, tỷ lệ nhỏ", "There was only a smattering of women authors among winners.", "NOUN"],
  ["smidgen", "một chút rất nhỏ", "Would you like a smidgen of chilli sauce?", "NOUN"],
  ["dollop", "một muỗng/một cục (thường nhỏ)", "I'd like a dollop of ice cream with my fruit.", "NOUN"],
  ["stacks of", "rất nhiều (informal)", "I used to have stacks of CDs on memory sticks.", "PHRASE"],
  ["more or less", "gần như, tương đối", "I think we've more or less solved the problem.", "PHRASE"],
  ["a bit of a", "hơi, khá (làm dịu nghĩa)", "We were in a bit of a panic at the airport.", "PHRASE"],
  ["or whatever", "hoặc thứ tương tự", "Spend Sunday at museums or galleries or whatever.", "PHRASE"],
  ["or something", "hoặc thứ gì khác tương tự", "Have a lemonade or something if you don't want tea.", "PHRASE"],
  ["things like that", "những thứ kiểu vậy", "We played board games and things like that.", "PHRASE"],
  ["along those lines", "kiểu như vậy, tương tự", "A dustbin or something along those lines would do.", "PHRASE"],
  ["words to that effect", "nội dung tương tự", "He said he was fed up, or words to that effect.", "PHRASE"],
  ["that kind of thing", "loại hoạt động tương tự", "In the evenings we played games and that kind of thing.", "PHRASE"],
  ["dash of", "một chút (gia vị)", "Add a dash of chilli sauce to the kebab.", "PHRASE"],
  ["around", "khoảng (số lượng, informal)", "He's about 35 — use around, not more or less with age.", "ADVERB"],
]);

const U84_WORDS = wordList([
  ["mumble", "lẩm bẩm khó nghe (tiêu cực)", "Stop mumbling! I can't hear what you're saying.", "VERB"],
  ["mutter", "lẩm bẩm phàn nàn", "He was muttering something under his breath.", "VERB"],
  ["murmur", "thì thầm (có thể tích cực)", "They murmured their approval when he told them the plan.", "VERB"],
  ["without a murmur", "im lặng chấp nhận, không phản đối", "They accepted it all without a murmur.", "PHRASE"],
  ["raise your voice", "nói to hơn", "You'll have to raise your voice; she's hard of hearing.", "PHRASE"],
  ["shriek", "la hét cao vút", "Oh, wow! That's fantastic! she shrieked.", "VERB"],
  ["roar", "gầm thét rất to (âm trầm)", "The crowd roared as he kicked the ball into the net.", "VERB"],
  ["nagging", "cằn nhằn chỉ trích liên tục", "Tom and Lily are always nagging at each other.", "VERB"],
  ["bickering", "cãi vã nhỏ nhặt", "Stop bickering over who sits by the window!", "VERB"],
  ["squabble", "cãi nhau vụn vặt", "Children often squabble over trivial things.", "VERB"],
  ["slagging off", "chê bai insulting (rất informal)", "They spent the evening slagging off their colleagues.", "PHRASE"],
  ["whingeing", "than phiền khó chịu (informal)", "Jessie is always whining and whingeing.", "VERB"],
  ["chatting away", "nói chuyện phiềm không ngừng", "He's been chatting away on the phone all morning.", "PHRASE"],
  ["gossip", "buôn chuyện, đồn đại", "We always gossip about work when we go out.", "VERB"],
  ["winding up", "trêu chọc, dụ dỗ", "It took him a long time to realise they were winding him up.", "PHRASE"],
  ["buttering up", "nịnh bợ để xin điều gì", "I realised she was buttering me up.", "PHRASE"],
  ["exaggerate", "phóng đại", "Rick tends to exaggerate his problems.", "VERB"],
  ["generalise", "khái quát hóa quá mức", "Meg is inclined to generalise on limited experience.", "VERB"],
  ["lisp", "nói lẫn âm s/th", "She speaks with a lisp.", "NOUN"],
  ["stammer", "nói lắp, ngắt quãng", "He's got a really bad stammer.", "NOUN"],
  ["stutter", "nói lặp âm đầu từ", "I want to t-t-tell you something, she stuttered.", "VERB"],
  ["slur your words", "nói lè nhè (say rượu)", "He was slurring his words after drinking too much.", "PHRASE"],
  ["tongue-tied", " cứng lưỡi vì ngại", "I get tongue-tied when I want to tell her I love her.", "ADJECTIVE"],
]);

const U85_WORDS = wordList([
  ["e.g.", "ví dụ (exempli gratia)", "Bring essentials, e.g. a toothbrush and towel.", "ABBREVIATION"],
  ["i.e.", "tức là (id est)", "The first month, i.e. January, was cold.", "ABBREVIATION"],
  ["AD", "sau Công Nguyên (Anno Domini)", "The temple was built in AD 120.", "ABBREVIATION"],
  ["BC", "trước Công Nguyên", "The wall dates from 200 BC.", "ABBREVIATION"],
  ["CE", "Công Nguyên (Common Era, thay AD)", "The manuscript is dated 450 CE.", "ABBREVIATION"],
  ["BCE", "trước Công Nguyên (Before Common Era)", "The pottery is from 300 BCE.", "ABBREVIATION"],
  ["NB", "chú ý (nota bene)", "NB: the exam starts at 9 a.m. sharp.", "ABBREVIATION"],
  ["PTO", "vui lòng lật trang (please turn over)", "More details on the next page — PTO.", "ABBREVIATION"],
  ["RSVP", "xin hồi đáp (thư mời)", "Please RSVP by Friday if you can attend.", "ABBREVIATION"],
  ["ASAP", "càng sớm càng tốt", "Send the report ASAP.", "ABBREVIATION"],
  ["FAQ", "câu hỏi thường gặp", "Check the FAQ section on the website.", "ABBREVIATION"],
  ["VIP", "nhân vật quan trọng", "VIP guests use a separate entrance.", "ABBREVIATION"],
  ["UFO", "vật thể bay không xác định", "Tabloids love stories about UFO sightings.", "ABBREVIATION"],
  ["IQ", "chỉ số thông minh", "IQ tests measure one kind of ability only.", "ABBREVIATION"],
  ["USB", "cổng kết nối thiết bị với máy tính", "Copy the files onto a USB stick.", "ABBREVIATION"],
  ["EU", "Liên minh châu Âu", "Trade rules differ across the EU.", "ABBREVIATION"],
  ["bedsit", "phòng vừa ngủ vừa sinh hoạt", "She rented a tiny bedsit near the station.", "NOUN"],
  ["sitcom", "phim hài tình huống", "That sitcom has run for ten seasons.", "NOUN"],
  ["sci-fi", "khoa học viễn tưởng", "He prefers sci-fi to romance novels.", "NOUN"],
  ["biopic", "phim tiểu sử người thật", "The biopic of the singer won several awards.", "NOUN"],
  ["biodata", "sơ lược tiểu sử / lý lịch ngắn", "Attach your biodata with the application.", "NOUN"],
  ["wi-fi", "kết nối không dây", "The café offers free wi-fi.", "NOUN"],
  ["AIDS", "hội chứng suy giảm miễn dịch", "Research into AIDS has saved many lives.", "NOUN"],
  ["NATO", "Tổ chức Hiệp ước Bắc Đại Tây Dương", "NATO members meet annually.", "NOUN"],
  ["PIN", "mã nhận dạng cá nhân (thẻ)", "Never share your PIN with anyone.", "NOUN"],
  ["VAT", "thuế giá trị gia tăng", "Prices shown exclude VAT.", "NOUN"],
  ["et al.", "và các tác giả khác (bibliography)", "O'Keeffe et al. (2010) discuss this problem.", "ABBREVIATION"],
  ["cf.", "so sánh với (compare)", "Carter (1997) investigated core vocabulary (cf. Lee 1987).", "ABBREVIATION"],
  ["fig.", "hình / sơ đồ trong sách (figure)", "See fig. 2 for the full diagram.", "ABBREVIATION"],
  ["eds.", "các biên tập viên (editors)", "Smith and Lee (eds.) published the collection.", "ABBREVIATION"],
  ["pp.", "các trang (pages)", "See pp. 58–61 for the discussion.", "ABBREVIATION"],
]);

const U86_WORDS = wordList([
  ["inappropriate", "không phù hợp (tiền tố in-)", "That comment was completely inappropriate.", "ADJECTIVE"],
  ["misuse", "dùng sai mục đích (mis-)", "Misuse of data can invalidate results.", "VERB"],
  ["outnumber", "nhiều hơn về số lượng (out-)", "Women outnumber men in the department.", "VERB"],
  ["outweigh", "quan trọng/lớn hơn (out-)", "The benefits outweigh the risks.", "VERB"],
  ["reconsider", "xem xét lại (re-)", "Please reconsider your decision.", "VERB"],
  ["e-commerce", "thương mại điện tử (e-)", "E-commerce grew rapidly during the pandemic.", "NOUN"],
  ["eco-friendly", "thân thiện môi trường (eco-)", "We use eco-friendly cleaning products.", "ADJECTIVE"],
  ["eco-warrior", "người chiến đấu bảo vệ môi trường", "She calls herself an eco-warrior.", "NOUN"],
  ["overrated", "bị đánh giá quá cao (over-)", "That film was overrated in my view.", "ADJECTIVE"],
  ["overpriced", "đắt quá mức (over-)", "It was a bad restaurant with an overpriced menu.", "ADJECTIVE"],
  ["overhang", "nhô ra phía trên (over-)", "Neighbour's trees overhang our garden.", "VERB"],
  ["overshadowed", "bị lu mờ, che khuất (over-)", "She always felt overshadowed by her older sister.", "ADJECTIVE"],
  ["overstepped the mark", "vượt giới hạn chấp nhận được", "He overstepped the mark when he said that.", "PHRASE"],
  ["overnight", "qua đêm (over-)", "Will you be staying overnight?", "ADVERB"],
  ["underestimate", "đánh giá thấp hơn thực tế (under-)", "Don't underestimate the time it will take.", "VERB"],
  ["understaffed", "thiếu nhân sự (under-)", "The company is seriously understaffed.", "ADJECTIVE"],
  ["underfoot", "dưới chân, trên mặt đất (under-)", "It's quite wet underfoot after the rain.", "ADVERB"],
  ["underlying", "nằm sâu bên dưới (under-)", "The underlying question is very difficult.", "ADJECTIVE"],
  ["undermine", "phá hoại, làm yếu đi (under-)", "I wish you would not undermine everything I do.", "VERB"],
  ["underhand", "lén lút, không minh bạch (under-)", "He did it in a very underhand way.", "ADJECTIVE"],
  ["upgrade", "nâng cấp lên hạng tốt hơn (up-)", "The airline upgraded me to business class.", "VERB"],
  ["upturn", "cải thiện, đảo chiều tích cực (up-)", "There has been an upturn in the economy.", "NOUN"],
]);

const U87_WORDS = wordList([
  ["washable", "có thể giặt được (-able)", "It's a washable jacket.", "ADJECTIVE"],
  ["disposable", "dùng một lần rồi bỏ (-able)", "Disposable nappies create waste.", "ADJECTIVE"],
  ["predictable", "dễ đoán trước (-able)", "The results were predictable.", "ADJECTIVE"],
  ["health-conscious", "quan tâm sức khỏe (-conscious)", "She is a health-conscious person.", "ADJECTIVE"],
  ["stress-free", "không căng thẳng (-free)", "They want a stress-free life.", "ADJECTIVE"],
  ["tax-free", "miễn thuế (-free)", "Duty-free shops sell tax-free goods.", "ADJECTIVE"],
  ["fibre-rich", "giàu chất xơ (-rich)", "A fibre-rich diet aids digestion.", "ADJECTIVE"],
  ["community-led", "do cộng đồng dẫn dắt (-led)", "It was a community-led initiative.", "ADJECTIVE"],
  ["like-minded", "cùng chí hướng (-minded)", "She found like-minded friends online.", "ADJECTIVE"],
  ["waterproof", "chống nước (-proof)", "Wear a waterproof jacket in the rain.", "ADJECTIVE"],
  ["soundproof", "cách âm (-proof)", "They built a soundproof room.", "ADJECTIVE"],
  ["stress-related", "liên quan đến căng thẳng (-related)", "She took stress-related absence from work.", "ADJECTIVE"],
  ["crime-ridden", "nhiều tội phạm (-ridden)", "It was a crime-ridden city.", "ADJECTIVE"],
  ["bedridden", "nằm liệt giường (-ridden)", "He has been bedridden for weeks.", "ADJECTIVE"],
  ["newsworthy", "đáng đưa tin (-worthy)", "It was a newsworthy incident.", "ADJECTIVE"],
  ["praiseworthy", "đáng khen (-worthy)", "Her effort was praiseworthy.", "ADJECTIVE"],
  ["lively", "sôi nổi (-ly tạo tính từ)", "The lively children ran around the garden.", "ADJECTIVE"],
  ["costly", "tốn kém (-ly tạo tính từ)", "It was a costly holiday.", "ADJECTIVE"],
  ["applicant", "người nộp đơn (-ant tạo danh từ)", "There were fifty applicants for the job.", "NOUN"],
  ["moisten", "làm ẩm (-en tạo động từ)", "Moisten your lips before speaking.", "VERB"],
  ["worsens", "trở nên tệ hơn (-en)", "The situation worsens every day.", "VERB"],
  ["coining", "tạo từ mới (coin a word)", "You might try coining some words of your own.", "VERB"],
]);

const U88_WORDS = wordList([
  ["autonomous", "tự trị (auto- = self)", "It is an autonomous region.", "ADJECTIVE"],
  ["biodegradable", "phân hủy sinh học (bio- = life)", "Use biodegradable packaging.", "ADJECTIVE"],
  ["cybercafé", "quán net (cyber-)", "We met at a cybercafé downtown.", "NOUN"],
  ["demotivate", "làm mất hứng thú (de- = opposite)", "Poor feedback can demotivate staff.", "VERB"],
  ["monograph", "luận văn ngắn một chủ đề (-graph-)", "She published a monograph on the poet.", "NOUN"],
  ["congress", "hội nghị (-gress- = come together)", "The medical congress meets every two years.", "NOUN"],
  ["obstetrics", "khoa sản khoa (-ics = field)", "She specialises in obstetrics.", "NOUN"],
  ["phonetics", "ngữ âm học (-phon- = sound)", "Phonetics helps with pronunciation.", "NOUN"],
  ["criminology", "tội phạm học (-ology = study)", "He studied criminology at university.", "NOUN"],
  ["prepaid", "trả trước (pre- = before)", "Buy prepaid tickets online.", "ADJECTIVE"],
  ["retroactive", "có hiệu lực ngược thời gian (retro-)", "The law was retroactive to January.", "ADJECTIVE"],
  ["technophobia", "sợ công nghệ (techno-)", "Technophobia keeps some people offline.", "NOUN"],
  ["telepathic", "cảm nhận từ xa (tele-)", "She described a telepathic experience.", "ADJECTIVE"],
  ["brunch", "bữa sáng trưa (breakfast + lunch)", "Let's meet for brunch on Sunday.", "NOUN"],
  ["heliport", "bến trực thăng (helicopter + airport)", "The hotel has its own heliport.", "NOUN"],
  ["smog", "sương khói ô nhiễm (smoke + fog)", "Smog hangs over the city in summer.", "NOUN"],
  ["motel", "khách sạn ven đường (motor + hotel)", "We stayed at a motel off the motorway.", "NOUN"],
  ["webinar", "hội thảo trực tuyến (web + seminar)", "Register for the free webinar.", "NOUN"],
  ["guesstimate", "ước lượng sơ bộ (guess + estimate)", "It's only a guesstimate, not exact data.", "NOUN"],
  ["docudrama", "phim tài liệu kịch hóa (documentary + drama)", "The docudrama recreated the trial.", "NOUN"],
  ["breathalyser", "máy đo nồng độ cồn (breath + analyse)", "Police used a breathalyser at the checkpoint.", "NOUN"],
]);

const U89_WORDS = wordList([
  ["lexicon", "từ vựng của một ngôn ngữ", "Some languages resist foreign words in their lexicon.", "NOUN"],
  ["loanwords", "từ mượn từ ngôn ngữ khác", "English has loanwords from at least 120 languages.", "NOUN"],
  ["Anglo-Saxon", "tiếng Anh cổ (gốc Germanic)", "English started with a basic Anglo-Saxon word stock.", "ADJECTIVE"],
  ["Norse", "ngôn ngữ Bắc Âu (gốc Viking)", "Viking invaders brought Norse words.", "ADJECTIVE"],
  ["Norman", "người/văn hóa Normandy (Pháp)", "Norman invaders spoke a form of French.", "ADJECTIVE"],
  ["Renaissance", "thời kỳ Phục hưng (15–17th c.)", "Scholars introduced classical words in the Renaissance.", "NOUN"],
  ["classical origin", "gốc Latin hoặc Hy Lạp cổ", "Many academic words are of classical origin.", "PHRASE"],
  ["linguistic consequences", "hậu quả đối với ngôn ngữ", "Contact with the world had linguistic consequences.", "PHRASE"],
  ["amber", "hổ phách (từ Arabic)", "She wore an amber necklace.", "NOUN"],
  ["roster", "danh sách ca/lượt (từ Dutch)", "Check the cooking roster for this week.", "NOUN"],
  ["tabby", "mèo vằn xám nâu (từ Farsi)", "Our old tabby sleeps on the sofa.", "NOUN"],
  ["gimmick", "chiêu trò thu hút (từ German)", "The ad used a clever gimmick.", "NOUN"],
  ["tonic", "thuốc bổ (từ Greek)", "Take a tonic if you feel weak.", "NOUN"],
  ["karaoke", "hát theo nhạc nền (từ Japanese)", "They bought a karaoke machine.", "NOUN"],
  ["palaver", "ồn ào, rắc rối không cần thiết (Portuguese)", "What a palaver over a simple mistake!", "NOUN"],
  ["intelligentsia", "tầng lớp trí thức (từ Russian)", "The 19th-century intelligentsia debated reform.", "NOUN"],
  ["hammock", "võng (từ Spanish)", "We slept in a hammock on the beach.", "NOUN"],
  ["turban", "khăn xếp đội đầu (từ Turkish)", "He wore a white turban.", "NOUN"],
  ["false friends", "từ trông giống nhưng nghĩa khác", "Gift in German means poison — a false friend.", "PHRASE"],
  ["sympathetic", "thông cảm nỗi đau người khác (hẹp hơn 'nice')", "In English sympathetic means understanding suffering.", "ADJECTIVE"],
  ["borrowings", "từ được mượn vào tiếng Anh", "These borrowings enrich the language.", "NOUN"],
]);

const U90_WORDS = wordList([
  ["intervene", "can thiệp (trung lập)", "The UN should intervene to stop the war.", "VERB"],
  ["interfere", "can thiệp (tiêu cực, xen vào)", "She shouldn't interfere in things that don't concern her.", "VERB"],
  ["continually", "liên tục, rất thường xuyên", "The phone's been ringing continually.", "ADVERB"],
  ["continuously", "không ngừng, không gián đoạn", "Stir the mixture continuously until it boils.", "ADVERB"],
  ["series", "loạt chương trình liên quan", "There's a new series on TV about space.", "NOUN"],
  ["serial", "phim/bài nối tiếp từng tập", "Oliver Twist is a serial — miss one and you lose track.", "NOUN"],
  ["shade", "bóng râm dễ chịu", "We sat in the shade of a big oak tree.", "NOUN"],
  ["shadow", "bóng tối (thường tiêu cực)", "They lived in the shadow of a chemical factory.", "NOUN"],
  ["compliment", "khen ngợi", "She complimented me on my performance.", "VERB"],
  ["complement", "bổ sung cho nhau", "Programming complements my other IT skills.", "VERB"],
  ["moist", "ẩm vừa phải (công thức nấu)", "The cake mixture should be moist but not sticky.", "ADJECTIVE"],
  ["damp", "ẩm ướt khó chịu", "The climate in the north is damp and cold.", "ADJECTIVE"],
  ["theme", "chủ đề tổng thể sự kiện", "The theme of the festival was culture.", "NOUN"],
  ["topic", "chủ đề cuộc trò chuyện", "The topic of conversation soon changed.", "NOUN"],
  ["security officer", "nhân viên an ninh tài sản", "The security officer noticed a broken window.", "PHRASE"],
  ["safety officer", "nhân viên an toàn lao động", "The safety officer said he must wear a helmet.", "PHRASE"],
  ["avoid", "tránh, không đi qua", "We took a smaller road to avoid the roadworks.", "VERB"],
  ["evade", "trốn tránh (trang trọng hơn)", "The prisoner evaded capture for three months.", "VERB"],
  ["breakout", "vượt ngục (danh từ từ break out)", "There was a breakout at the prison.", "NOUN"],
  ["outbreak", "bùng phát (dịch bệnh)", "There has been an outbreak of the disease.", "NOUN"],
  ["outlook", "triển vọng (từ look out)", "The economic outlook is not good.", "NOUN"],
  ["lookout", "người canh gác (từ look out)", "He was the lookout while others robbed the bank.", "NOUN"],
  ["end up", "kết thúc ở trạng thái nào (khác upend)", "We ended up staying until midnight.", "PHRASE"],
  ["set up", "tổ chức, thiết lập (khác upset)", "The club decided to set up a committee.", "PHRASE"],
]);

export const EVIU_ADVANCED_UNITS_76_90: readonly VocabularyUnit[] = [
  advancedUnit(76, {
    introVi:
      "Unit 76 phân biệt lời hứa trang trọng và cá cược trong tiếng Anh: từ pledge, vow đến stake và the odds. Bạn sẽ dùng collocations tự nhiên khi nói về cam kết và rủi ro.",
    structureSections: [
      { label: "Promises and formal commitment", wordCount: 10 },
      { label: "Breaking and keeping promises", wordCount: 4 },
      { label: "Bets and gambling language", wordCount: 8 },
    ],
    collocationHtml: `${purple("swear by")}, ${purple("turn over a new leaf")}, ${purple("at stake")} và ${purple("hedge your bets")} là cụm then chốt khi bàn về lời hứa và cá cược.`,
    mistakeHtml: `${bold("Swear")} vừa có thể là thề (trang trọng) vừa là chửi thề. ${bold("Anticipate")} = dự đoán trước; khác ${bold("promise")} mang hàm ý cam kết.`,
    principles: [
      {
        title: "Lời hứa trang trọng và thân mật",
        body: `${purple("pledge")} và ${purple("vow")} thường gặp trong văn viết; ${purple("oath")} dùng ở tòa. ${purple("promise the earth")} gợi hứa quá mức; ${purple("promising")} mô tả triển vọng tích cực.`,
        examples: [
          ex("The child shows great promise as a violinist.", "Đứa trẻ thể hiện triển vọng lớn với violin."),
          ex("The couple exchanged vows at the ceremony.", "Hai người trao lời thề trong lễ cưới."),
        ],
      },
      {
        title: "Giữ lời và nuốt lời",
        body: `Resolutions có thể được made, kept hoặc broken. ${purple("turn over a new leaf")} = thay đổi hành vi; ${purple("go back on your word")} = phá vỡ lời hứa.`,
        examples: [
          ex("New Year's resolutions help people turn over a new leaf.", "Lời hứa năm mới giúp mọi người bắt đầu lại."),
          ex("Never go back on your word if you want trust.", "Đừng nuốt lời nếu muốn được tin tưởng."),
        ],
      },
      {
        title: "Ngôn ngữ cá cược",
        body: `${purple("stake")} là tiền cược; ${purple("at stake")} = đang bị đe dọa. ${purple("best bet")} = lựa chọn tốt nhất; ${purple("don't bet on it")} = khó xảy ra. ${purple("the odds")} mô tả khả năng thắng/thua.`,
        examples: [
          ex("Your best bet would be a part-time job.", "Lựa chọn tốt nhất là tìm việc bán thời gian."),
          ex("The odds are against her getting promotion.", "Khả năng cô ấy thăng chức là thấp."),
        ],
      },
    ],
    words: U76_WORDS,
    exercises: [
      fillBlank(
        76,
        1,
        "If you ____ on your word, people will stop trusting you.",
        "go back on your word",
        [
          { key: "a", label: "go back on your word" },
          { key: "b", label: "swear by" },
          { key: "c", label: "hedge your bets" },
          { key: "d", label: "have a flutter" },
        ],
        "a",
      ),
      mcq(
        76,
        2,
        "\"Swear by\" nghĩa là gì?",
        [
          { key: "a", label: "Tin tưởng tuyệt đối vào (sản phẩm/phương pháp)" },
          { key: "b", label: "Chửi thề" },
          { key: "c", label: "Thề trong tòa" },
          { key: "d", label: "Nuốt lời hứa" },
        ],
        "a",
      ),
      fillBlank(
        76,
        3,
        "Many lives will be ____ if the flood barrier is not built.",
        "at stake",
        [
          { key: "a", label: "at stake" },
          { key: "b", label: "you bet" },
          { key: "c", label: "the odds" },
          { key: "d", label: "gambling" },
        ],
        "a",
      ),
      fillBlank(
        76,
        4,
        "She is a ____ artist although her style is still immature.",
        "promising",
        [
          { key: "a", label: "promising" },
          { key: "b", label: "gambling" },
          { key: "c", label: "wager" },
          { key: "d", label: "oath" },
        ],
        "a",
      ),
      mcq(
        76,
        5,
        "Cách nói \"chắc chắn rồi!\" (informal):",
        [
          { key: "a", label: "You bet!" },
          { key: "b", label: "Don't bet on it!" },
          { key: "c", label: "At stake" },
          { key: "d", label: "Best bet" },
        ],
        "a",
      ),
      fillBlank(
        76,
        6,
        "You can ____ by investing in several companies.",
        "hedge your bets",
        [
          { key: "a", label: "hedge your bets" },
          { key: "b", label: "turn over a new leaf" },
          { key: "c", label: "promise the earth" },
          { key: "d", label: "bet my life on" },
        ],
        "a",
      ),
    ],
  }),

  advancedUnit(77, {
    introVi:
      "Unit 77 giúp bạn hồi tưởng quá khứ và diễn đạt hối tiếc: từ out of touch đến rose-tinted spectacles và pangs of guilt. Bạn sẽ phân biệt remind và remember đúng ngữ cảnh.",
    structureSections: [
      { label: "Sharing memories", wordCount: 12 },
      { label: "Expressing regret", wordCount: 6 },
      { label: "Formal literary regret", wordCount: 3 },
    ],
    collocationHtml: `${purple("out of touch")}, ${purple("takes me back to")}, ${purple("rose-tinted spectacles")} và ${purple("pangs of guilt")} xuất hiện khi nhớ lại và hối hận.`,
    mistakeHtml: `Dùng ${bold("remind")} + of: the photo reminded me of schooldays (NOT remembered me). ${bold("Nostalgia")} thường tích cực; ${bold("remorse")} nặng nề hơn ${bold("regret")}.`,
    principles: [
      {
        title: "Hồi tưởng và mất liên lạc",
        body: `${purple("out of touch")} và ${purple("lost touch")} mô tả mất liên hệ. ${purple("what became of")} hỏi ai đó giờ ra sao; ${purple("takes me back to")} gợi ký ức mạnh.`,
        examples: [
          ex("I wonder what became of our maths teacher.", "Tôi tự hỏi thầy toán giờ ra sao."),
          ex("That song takes me back to our school days.", "Bài hát ấy khiến tôi nhớ ngày học."),
        ],
      },
      {
        title: "Ký ức mơ hồ và nổi bật",
        body: `${purple("vague memory")} và ${purple("coming back to me")} mô tả độ rõ của nhớ. ${purple("stands out in my mind")} = điều nhớ nhất; ${purple("reminisce about")} = hồi tưởng vui.`,
        examples: [
          ex("What stands out in my mind is the freedom we had.", "Điều nổi bật nhất là sự tự do chúng tôi có."),
          ex("We all look at the past through rose-tinted spectacles.", "Ta thường nhìn quá khứ quá đẹp."),
        ],
      },
      {
        title: "Hối tiếc và tội lỗi",
        body: `${purple("regret")} + V-ing; ${purple("remorse")} và ${purple("shame")} nặng hơn. ${purple("rue the day")}, ${purple("lament")} và ${purple("mourn lost opportunities")} mang sắc thái văn chương.`,
        examples: [
          ex("I regret not spending more time with my aunt.", "Tôi hối tiếc không dành thêm thời gian cho dì."),
          ex("I felt pangs of guilt thinking of what happened.", "Tôi cảm thấy cơn tội lỗi khi nghĩ về chuyện đã xảy ra."),
        ],
      },
    ],
    words: U77_WORDS,
    exercises: [
      fillBlank(
        77,
        1,
        "I've been a bit ____ since I moved away from London.",
        "out of touch",
        [
          { key: "a", label: "out of touch" },
          { key: "b", label: "lost touch" },
          { key: "c", label: "think back" },
          { key: "d", label: "recall" },
        ],
        "a",
      ),
      mcq(
        77,
        2,
        "\"Rose-tinted spectacles\" nghĩa là gì?",
        [
          { key: "a", label: "Nhìn quá khứ chỉ thấy điều tốt" },
          { key: "b", label: "Ký ức hoàn toàn mơ hồ" },
          { key: "c", label: "Mất liên lạc với bạn cũ" },
          { key: "d", label: "Hối hận sâu sắc" },
        ],
        "a",
      ),
      fillBlank(
        77,
        3,
        "I ____ not spending more time with my aunt when she was ill.",
        "regret",
        [
          { key: "a", label: "regret" },
          { key: "b", label: "reminisce" },
          { key: "c", label: "recall" },
          { key: "d", label: "lament" },
        ],
        "a",
      ),
      fillBlank(
        77,
        4,
        "That photo ____ me back to the day the inspector visited.",
        "takes",
        [
          { key: "a", label: "takes" },
          { key: "b", label: "stands" },
          { key: "c", label: "hears" },
          { key: "d", label: "mourn" },
        ],
        "a",
      ),
      {
        type: "match",
        id: "ex-77-match-5",
        instruction: "Ghép cụm hồi tưởng với nghĩa tiếng Việt",
        pairs: [
          { left: "what became of", right: "điều gì đã xảy ra với" },
          { left: "coming back to me", right: "dần nhớ lại rõ hơn" },
          { left: "nostalgia", right: "nỗi nhớ hoài niệm" },
          { left: "remorse", right: "hối hận sâu sắc" },
          { left: "pangs of guilt", right: "cơn đau tội lỗi" },
        ],
      },
      mcq(
        77,
        6,
        "Cách diễn đạt hối hận văn chương/trang trọng:",
        [
          { key: "a", label: "I rue the day we ever met." },
          { key: "b", label: "You bet!" },
          { key: "c", label: "Don't bet on it!" },
          { key: "d", label: "Present company excepted." },
        ],
        "a",
      ),
    ],
  }),

  advancedUnit(78, {
    introVi:
      "Unit 78 trang bị từ vựng đồng ý, bất đồng và thỏa hiệp — từ tally with đến controversy và exercise discretion. Bạn sẽ thảo luận chính trị và xã hội có chiều sâu hơn.",
    structureSections: [
      { label: "Agreement and shared views", wordCount: 9 },
      { label: "Political disagreement", wordCount: 6 },
      { label: "Compromise and settlement", wordCount: 5 },
    ],
    collocationHtml: `${purple("tally with")}, ${purple("in full accord with")}, ${purple("agree to differ")} và ${purple("reach a compromise")} là collocations thảo luận then chốt.`,
    mistakeHtml: `${bold("Concur with")} và ${bold("coincide with")} đều là đồng ý/trùng khớp nhưng ${bold("concur")} nhấn ý kiến. ${bold("Dissent")} ≠ ${bold("descent")}.`,
    principles: [
      {
        title: "Đồng ý và trùng quan điểm",
        body: `${purple("tally with")}, ${purple("concur with")}, ${purple("coincide with")} và ${purple("conform to")} mô tả sự phù hợp. ${purple("approve of")} + V-ing; kế hoạch có thể ${purple("meet with approval")}.`,
        examples: [
          ex("Your views coincide with mine on this issue.", "Quan điểm của bạn trùng với tôi về vấn đề này."),
          ex("We agreed to differ and ended the argument.", "Chúng tôi đồng ý bất đồng và chấm dứt tranh cãi."),
        ],
      },
      {
        title: "Bất đồng chính trị",
        body: `${purple("dissent")} = phản đối quan điểm chính thức; ${purple("discord")} và ${purple("rift")} gợi mâu thuẫn sâu. ${purple("split")} / ${purple("division")} khi nhóm chia đôi; ${purple("controversy")} ảnh hưởng nhiều người.`,
        examples: [
          ex("There is dissent in the party on defence policy.", "Đảng bất đồng về chính sách quốc phòng."),
          ex("The airport plan is bound to cause controversy.", "Kế hoạch sân bay chắc chắn gây tranh cãi."),
        ],
      },
      {
        title: "Thỏa hiệp",
        body: `Hai bên ${purple("reach a compromise")}; chính phủ có thể ${purple("concessions")}. ${purple("settlement")} kết thúc đình công; đôi khi cần ${purple("exercise discretion")} để tránh leo thang.`,
        examples: [
          ex("The union and management reached a settlement.", "Công đoàn và quản lý đạt thỏa thuận."),
          ex("We should exercise discretion and say nothing inflammatory.", "Ta nên dùng phán đoán và tránh lời kích động."),
        ],
      },
    ],
    words: U78_WORDS,
    exercises: [
      fillBlank(
        78,
        1,
        "Her complaints ____ with comments from other customers.",
        "tally",
        [
          { key: "a", label: "tally" },
          { key: "b", label: "dissent" },
          { key: "c", label: "split" },
          { key: "d", label: "compromise" },
        ],
        "a",
      ),
      mcq(
        78,
        2,
        "Khi hai bên giữ ý kiến khác nhưng không tranh nữa:",
        [
          { key: "a", label: "agree to differ" },
          { key: "b", label: "in full accord with" },
          { key: "c", label: "meet with approval" },
          { key: "d", label: "reach consensus" },
        ],
        "a",
      ),
      fillBlank(
        78,
        3,
        "A growing ____ in the party over defence is now public.",
        "rift",
        [
          { key: "a", label: "rift" },
          { key: "b", label: "approval" },
          { key: "c", label: "settlement" },
          { key: "d", label: "consensus" },
        ],
        "a",
      ),
      fillBlank(
        78,
        4,
        "The government made several ____ to the protesters.",
        "concessions",
        [
          { key: "a", label: "concessions" },
          { key: "b", label: "dissents" },
          { key: "c", label: "divisions" },
          { key: "d", label: "controversies" },
        ],
        "a",
      ),
      mcq(
        78,
        5,
        "Phản hồi nhanh thể hiện đồng ý hoàn toàn:",
        [
          { key: "a", label: "Absolutely!" },
          { key: "b", label: "Dissent!" },
          { key: "c", label: "Controversy!" },
          { key: "d", label: "Division!" },
        ],
        "a",
      ),
      fillBlank(
        78,
        6,
        "His behaviour doesn't ____ to the school's expectations.",
        "conform",
        [
          { key: "a", label: "conform" },
          { key: "b", label: "coincide" },
          { key: "c", label: "concur" },
          { key: "d", label: "approve" },
        ],
        "a",
      ),
    ],
  }),

  advancedUnit(79, {
    introVi:
      "Unit 79 tập trung từ vựng học thuật khi lập luận: advocate, deduce, infer và các tính từ mô tả nghiên cứu. Bạn sẽ chọn động từ trang trọng thay cho show, think, use.",
    structureSections: [
      { label: "Presenting arguments", wordCount: 10 },
      { label: "Figures and processes", wordCount: 6 },
      { label: "Academic register", wordCount: 6 },
    ],
    collocationHtml: `${purple("advocate")}, ${purple("deduce")}, ${purple("deviate from the norm")} và ${purple("distort the picture")} là ngôn ngữ phân tích học thuật.`,
    mistakeHtml: `${bold("Deduce")} từ sự kiện đã biết; ${bold("infer")} gián tiếp hơn. ${bold("Complements")} (bổ sung) khác ${bold("compliments")} (khen).`,
    principles: [
      {
        title: "Lập luận và bình luận nghiên cứu",
        body: `${purple("advocate")} ủng hộ; ${purple("deduce")} suy luận từ bằng chứng; ${purple("infer")} suy ra gián tiếp. Công trình A ${purple("complements")} công trình B hoặc ${purple("overlaps with")} nó.`,
        examples: [
          ex("From the data we can infer that progress was slower.", "Từ dữ liệu ta suy ra tiến độ chậm hơn."),
          ex("Her review is comprehensive and authoritative.", "Bài review của cô toàn diện và uy tín."),
        ],
      },
      {
        title: "Số liệu và quy trình",
        body: `Số ${purple("arbitrary")} thiếu cơ sở; kết quả ${purple("deviate from the norm")} cần giải thích. ${purple("incidence")} = tần suất; ${purple("predominant")} = chiếm ưu thế; ${purple("widespread")} = lan rộng.`,
        examples: [
          ex("Small samples can distort the picture.", "Mẫu nhỏ có thể bóp méo bức tranh."),
          ex("The stages occur in sequence.", "Các giai đoạn xảy ra theo thứ tự."),
        ],
      },
      {
        title: "Đăng ký học thuật",
        body: `Dùng ${purple("denote")}, ${purple("negate")}, ${purple("thereby")}, ${purple("whereby")}, ${purple("notwithstanding")} thay cho everyday verbs. ${purple("Empirical")} vs lý thuyết; ${purple("coherent")} vs ${purple("ambiguous")}.`,
        examples: [
          ex("The symbol denotes a change in direction.", "Ký hiệu biểu thị sự thay đổi hướng."),
          ex("Notwithstanding these limits, the study is useful.", "Bất chấp hạn chế, nghiên cứu vẫn hữu ích."),
        ],
      },
    ],
    words: U79_WORDS,
    exercises: [
      fillBlank(
        79,
        1,
        "From contemporary accounts we can ____ that results were slower than expected.",
        "infer",
        [
          { key: "a", label: "infer" },
          { key: "b", label: "advocate" },
          { key: "c", label: "negate" },
          { key: "d", label: "denote" },
        ],
        "a",
      ),
      mcq(
        79,
        2,
        "Nghiên cứu dựa trên quan sát thực tế gọi là:",
        [
          { key: "a", label: "empirical" },
          { key: "b", label: "ambiguous" },
          { key: "c", label: "arbitrary" },
          { key: "d", label: "predominant" },
        ],
        "a",
      ),
      fillBlank(
        79,
        3,
        "Elswick's research ____ that of Johnson (2012).",
        "complements",
        [
          { key: "a", label: "complements" },
          { key: "b", label: "distorts" },
          { key: "c", label: "negates" },
          { key: "d", label: "advocates" },
        ],
        "a",
      ),
      fillBlank(
        79,
        4,
        "Figures that ____ from the norm need explanation.",
        "deviate",
        [
          { key: "a", label: "deviate" },
          { key: "b", label: "denote" },
          { key: "c", label: "overlap" },
          { key: "d", label: "reside" },
        ],
        "a",
      ),
      mcq(
        79,
        5,
        "\"Notwithstanding\" nghĩa là gì?",
        [
          { key: "a", label: "Bất chấp, mặc dù vậy" },
          { key: "b", label: "Do đó, bằng cách đó" },
          { key: "c", label: "Theo cách mà" },
          { key: "d", label: "Là dấu hiệu của" },
        ],
        "a",
      ),
      fillBlank(
        79,
        6,
        "There were ____ outbreaks of the illness across the region.",
        "widespread",
        [
          { key: "a", label: "widespread" },
          { key: "b", label: "coherent" },
          { key: "c", label: "comprehensive" },
          { key: "d", label: "authoritative" },
        ],
        "a",
      ),
    ],
  }),

  advancedUnit(80, {
    introVi:
      "Unit 80 dạy từ nối và động từ cấu trúc bài luận: preface, underscore, touch upon và beyond the scope. Bạn sẽ tổ chức văn bản học thuật mạch lạc hơn.",
    structureSections: [
      { label: "Explaining and reinforcing", wordCount: 9 },
      { label: "Categorising and including", wordCount: 5 },
      { label: "Structuring the text", wordCount: 7 },
    ],
    collocationHtml: `${purple("reiterate")}, ${purple("underscore")}, ${purple("account for")} và ${purple("beyond the scope")} giúp dẫn dắt độc giả qua bài viết.`,
    mistakeHtml: `${bold("Consist of")} + các thành phần (NOT consists on/in). ${bold("Comprised of")} cũng phổ biến; ${bold("composed of")} trang trọng hơn.`,
    principles: [
      {
        title: "Giải thích và nhấn mạnh",
        body: `${purple("reiterate")} nhắc lại; ${purple("summarise")} tóm tắt; ${purple("epitomise")} là hình mẫu tiêu biểu. ${purple("underscore")} / ${purple("posit")} nhấn hoặc đề xuất; ${purple("account for")} giải thích nguyên nhân.`,
        examples: [
          ex("Recent events underscore the need for reform.", "Sự kiện gần đây nhấn mạnh nhu cầu cải cách."),
          ex("Analysts tried to account for low turnout.", "Nhà phân tích cố giải thích tỷ lệ tham dự thấp."),
        ],
      },
      {
        title: "Phân loại và bao gồm",
        body: `${purple("comprised of")} / ${purple("consist of")} mô tả cấu phần. ${purple("subsumed under")} gộp chung; ${purple("embraces")} bao quát nhiều chủ đề; ${purple("categorise")} gán vào loại.`,
        examples: [
          ex("The course is comprised of two elements.", "Khóa học gồm hai thành phần."),
          ex("Her philosophy is difficult to categorise.", "Triết lý của cô khó phân loại."),
        ],
      },
      {
        title: "Cấu trúc bài luận",
        body: `${purple("preface")} mở đầu; ${purple("address the question")} đi vào vấn đề; trích dẫn ${purple("cited")}, ${purple("alludes to")}. ${purple("touch upon")} đề cập sơ; ${purple("beyond the scope")} ngoài phạm vi.`,
        examples: [
          ex("I shall preface my argument with a true story.", "Tôi sẽ mở đầu luận điểm bằng một câu chuyện thật."),
          ex("That topic is beyond the scope of this essay.", "Chủ đề đó vượt phạm vi bài luận này."),
        ],
      },
    ],
    words: U80_WORDS,
    exercises: [
      fillBlank(
        80,
        1,
        "Recent events ____ the need for a better understanding of biotechnology.",
        "underscore",
        [
          { key: "a", label: "underscore" },
          { key: "b", label: "preface" },
          { key: "c", label: "touch upon" },
          { key: "d", label: "categorise" },
        ],
        "a",
      ),
      mcq(
        80,
        2,
        "Đề cập sơ qua một chủ đề lớn:",
        [
          { key: "a", label: "touch upon" },
          { key: "b", label: "expound" },
          { key: "c", label: "reiterate" },
          { key: "d", label: "account for" },
        ],
        "a",
      ),
      fillBlank(
        80,
        3,
        "The country ____ of five major regions.",
        "consists",
        [
          { key: "a", label: "consists" },
          { key: "b", label: "embraces" },
          { key: "c", label: "asserts" },
          { key: "d", label: "posits" },
        ],
        "a",
      ),
      fillBlank(
        80,
        4,
        "Several writers will be ____ in support of the argument.",
        "cited",
        [
          { key: "a", label: "cited" },
          { key: "b", label: "summarised" },
          { key: "c", label: "subsumed" },
          { key: "d", label: "epitomised" },
        ],
        "a",
      ),
      mcq(
        80,
        5,
        "\"Beyond the scope of this essay\" nghĩa là gì?",
        [
          { key: "a", label: "Vượt phạm vi bài viết" },
          { key: "b", label: "Là phần mở đầu bài luận" },
          { key: "c", label: "Là ví dụ tiêu biểu" },
          { key: "d", label: "Là kết luận bắt buộc" },
        ],
        "a",
      ),
      fillBlank(
        80,
        6,
        "These two approaches can be ____ under one heading.",
        "subsumed",
        [
          { key: "a", label: "subsumed" },
          { key: "b", label: "reiterated" },
          { key: "c", label: "expounded" },
          { key: "d", label: "asserted" },
        ],
        "a",
      ),
    ],
  }),

  advancedUnit(81, {
    introVi:
      "Unit 81 bao quát quy trình viết và định dạng văn bản: từ jot down và drafting đến bullet point và superscript. Bạn sẽ mô tả chính xác các bước soạn thảo.",
    structureSections: [
      { label: "Writing process", wordCount: 10 },
      { label: "Typing and printing", wordCount: 6 },
      { label: "Format and layout", wordCount: 6 },
    ],
    collocationHtml: `${purple("jot down")}, ${purple("write up")}, ${purple("cut and paste")} và ${purple("run off a copy")} là collocations quy trình viết.`,
    mistakeHtml: `${bold("Draft")} (noun/verb) = bản nháp; ${bold("draught")} = gió/lốc (UK). ${bold("Italicised")} = nghiêng; ${bold("bold")} = đậm.`,
    principles: [
      {
        title: "Quy trình viết",
        body: `${purple("scribble")} viết vội; ${purple("jot down")} ghi nhanh; ${purple("drafting")} viết nháp; ${purple("write up")} hoàn thiện từ nháp. ${purple("manuscript")} là bản gốc của tác giả.`,
        examples: [
          ex("I'm drafting an application letter for that job.", "Tôi đang viết nháp thư xin việc."),
          ex("She's writing up her dissertation.", "Cô ấy đang hoàn thiện luận văn."),
        ],
      },
      {
        title: "Đánh máy và in",
        body: `${purple("touch-type")} gõ không nhìn phím; ${purple("typescript")} bản đánh máy gửi nhà xuất bản. ${purple("format")} trước khi in; ${purple("run off a copy")} in nhanh một bản.`,
        examples: [
          ex("Learning to touch-type saved me hours.", "Học gõ mù tiết kiệm hàng giờ."),
          ex("I'll format the page before printing.", "Tôi sẽ định dạng trang trước khi in."),
        ],
      },
      {
        title: "Định dạng và bố cục",
        body: `${purple("bold")}, ${purple("italicised")}, ${purple("indented")}, ${purple("bullet point")}, ${purple("superscript")}. ${purple("chapter heading")} và ${purple("sub-heading")} cấu trúc sách học thuật; ${purple("block capitals")} viết hoa toàn bộ.`,
        examples: [
          ex("Key terms are in bold in the textbook.", "Thuật ngữ chính in đậm trong sách."),
          ex("Section 1.1 is a sub-heading within the chapter.", "Mục 1.1 là tiêu đề phụ trong chương."),
        ],
      },
    ],
    words: U81_WORDS,
    exercises: [
      fillBlank(
        81,
        1,
        "I'll ____ your phone number before I forget it.",
        "jot down",
        [
          { key: "a", label: "jot down" },
          { key: "b", label: "write up" },
          { key: "c", label: "run off" },
          { key: "d", label: "format" },
        ],
        "a",
      ),
      mcq(
        81,
        2,
        "Viết bản hoàn chỉnh từ các bản nháp gọi là:",
        [
          { key: "a", label: "write up" },
          { key: "b", label: "scribble" },
          { key: "c", label: "doodle" },
          { key: "d", label: "copy out" },
        ],
        "a",
      ),
      fillBlank(
        81,
        3,
        "She bought the ____ of a famous poem at the sale.",
        "manuscript",
        [
          { key: "a", label: "manuscript" },
          { key: "b", label: "typescript" },
          { key: "c", label: "bullet point" },
          { key: "d", label: "sub-heading" },
        ],
        "a",
      ),
      fillBlank(
        81,
        4,
        "I usually ____ bits from my notes when writing an essay.",
        "cut and paste",
        [
          { key: "a", label: "cut and paste" },
          { key: "b", label: "touch-type" },
          { key: "c", label: "block capitals" },
          { key: "d", label: "superscript" },
        ],
        "a",
      ),
      mcq(
        81,
        5,
        "Chữ viết cao hơn dòng thường gọi là:",
        [
          { key: "a", label: "superscript" },
          { key: "b", label: "indented" },
          { key: "c", label: "italicised" },
          { key: "d", label: "chatty" },
        ],
        "a",
      ),
      fillBlank(
        81,
        6,
        "Learning to ____ was one of the most useful skills I acquired.",
        "touch-type",
        [
          { key: "a", label: "touch-type" },
          { key: "b", label: "doodle" },
          { key: "c", label: "scribble" },
          { key: "d", label: "draft" },
        ],
        "a",
      ),
    ],
  }),

  advancedUnit(82, {
    introVi:
      "Unit 82 dạy cách nói gián tiếp và dùng từ mơ hồ trong hội thoại: thing, whatchamacallit, loads of và present company excepted. Bạn sẽ làm lời nói bớt thẳng thừng mà vẫn tự nhiên.",
    structureSections: [
      { label: "Vague words: thing and get", wordCount: 7 },
      { label: "Placeholder words", wordCount: 4 },
      { label: "Indirect and softening expressions", wordCount: 9 },
    ],
    collocationHtml: `${purple("the thing is")}, ${purple("whatchamacallit")}, ${purple("bags of")} và ${purple("no offence intended")} là cụm informal then chốt.`,
    mistakeHtml: `${bold("Thing")} có nhiều nghĩa — đọc ngữ cảnh. ${bold("Get")} + sorted = giải quyết; khác ${bold("get")} + understand.`,
    principles: [
      {
        title: "Thing và get đa nghĩa",
        body: `${purple("the thing is")} giới thiệu vấn đề; ${purple("make a big thing of it")} = làm ầm ĩ. ${purple("get things sorted")} = giải quyết; ${purple("get it together")} = tự tổ chức.`,
        examples: [
          ex("The thing is, I have to take my car for a service.", "Vấn đề là tôi phải đưa xe đi bảo dưỡng."),
          ex("Jill will get things sorted out today.", "Jill sẽ sắp xếp giải quyết hôm nay."),
        ],
      },
      {
        title: "Từ thay khi quên tên",
        body: `${purple("whatchamacallit")}, ${purple("whatsit")}, ${purple("whatsisname")} thay tên vật/người khi quên. Có thể viết nhiều cách; mang sắc thái rất informal.`,
        examples: [
          ex("Have you seen the whatchamacallit for the door?", "Bạn thấy cái kẹp cửa chưa?"),
          ex("I was talking to whatsisname about that yesterday.", "Hôm qua tôi nói chuyện với ông kia về việc đó."),
        ],
      },
      {
        title: "Nói gián tiếp, bớt xúc phạm",
        body: `${purple("not the most practical")} = chỉ trích nhẹ. ${purple("no offence intended")}, ${purple("if you don't mind me saying")} làm mềm lời. ${purple("present company excepted")} / ${purple("myself included")} loại trừ người nghe.`,
        examples: [
          ex("No offence intended, but I think you've misunderstood.", "Không có ý xúc phạm, nhưng tôi nghĩ bạn hiểu sai."),
          ex("What idiots — present company excepted, of course.", "Toàn kẻ ngốc — trừ mọi người ở đây."),
        ],
      },
    ],
    words: U82_WORDS,
    exercises: [
      fillBlank(
        82,
        1,
        "____, I have to take my car for a service tomorrow.",
        "The thing is",
        [
          { key: "a", label: "The thing is" },
          { key: "b", label: "For one thing" },
          { key: "c", label: "Incidentally" },
          { key: "d", label: "I gather" },
        ],
        "a",
      ),
      mcq(
        82,
        2,
        "Cụm chỉ \"rất nhiều\" (informal):",
        [
          { key: "a", label: "loads of" },
          { key: "b", label: "a scrap of" },
          { key: "c", label: "for one thing" },
          { key: "d", label: "as things are" },
        ],
        "a",
      ),
      fillBlank(
        82,
        3,
        "Have you seen the ____ we use to keep the door open?",
        "whatchamacallit",
        [
          { key: "a", label: "whatchamacallit" },
          { key: "b", label: "incidentally" },
          { key: "c", label: "umpteen" },
          { key: "d", label: "myself included" },
        ],
        "a",
      ),
      fillBlank(
        82,
        4,
        "____, but I think you could have handled that better.",
        "If you don't mind me saying so",
        [
          { key: "a", label: "If you don't mind me saying so" },
          { key: "b", label: "You bet" },
          { key: "c", label: "Don't bet on it" },
          { key: "d", label: "Give or take" },
        ],
        "a",
      ),
      mcq(
        82,
        5,
        "\"Present company excepted\" nghĩa là gì?",
        [
          { key: "a", label: "Trừ những người có mặt ở đây" },
          { key: "b", label: "Kể cả bản thân tôi" },
          { key: "c", label: "Nhân tiện chuyển chủ đề" },
          { key: "d", label: "Không có ý xúc phạm" },
        ],
        "a",
      ),
      fillBlank(
        82,
        6,
        "Don't make such a ____ of it!",
        "big thing",
        [
          { key: "a", label: "big thing" },
          { key: "b", label: "scrap" },
          { key: "c", label: "flutter" },
          { key: "d", label: "stake" },
        ],
        "a",
      ),
    ],
  }),

  advancedUnit(83, {
    introVi:
      "Unit 83 mở rộng cách nói mơ hồ về số lượng và thời gian: give or take, quite a few và or whatever. Bạn sẽ ước lượng tự nhiên trong hội thoại informal.",
    structureSections: [
      { label: "Vague numbers and quantities", wordCount: 11 },
      { label: "Softening with more or less", wordCount: 3 },
      { label: "Vague references to things", wordCount: 6 },
    ],
    collocationHtml: `${purple("in the region of")}, ${purple("give or take")}, ${purple("quite a few")} và ${purple("or whatever")} giúp nói không chính xác một cách tự nhiên.`,
    mistakeHtml: `Không dùng ${bold("more or less")} với tuổi: He's about 35 (NOT more or less 35). ${bold("In excess of")} trang trọng; ${bold("give or take")} informal.`,
    principles: [
      {
        title: "Số lượng mơ hồ",
        body: `${purple("in excess of")} = hơn (formal); ${purple("in the region of")} = khoảng. ${purple("give or take")} cộng trừ một chút; ${purple("a week or so")} = hơn một tuần.`,
        examples: [
          ex("It'll take five hours, give or take half an hour.", "Mất năm giờ, cộng trừ nửa tiếng."),
          ex("He left a sum in excess of $1 million.", "Ông để lại hơn một triệu đô."),
        ],
      },
      {
        title: "Lượng nhỏ và lớn informal",
        body: `${purple("quite a few")} = khá nhiều (đôi khi bất ngờ). ${purple("smattering")} = một ít; ${purple("smidgen")} / ${purple("dash of")} = chút xíu; ${purple("stacks of")} = rất nhiều.`,
        examples: [
          ex("Quite a few students hadn't registered.", "Khá nhiều sinh viên chưa đăng ký."),
          ex("Add a dash of chilli sauce.", "Cho thêm chút tương ớt."),
        ],
      },
      {
        title: "Or whatever / or something",
        body: `${purple("or whatever")}, ${purple("or something")}, ${purple("things like that")} tham chiếu mơ hồ. ${purple("along those lines")} = kiểu tương tự; ${purple("words to that effect")} = nội dung tương tự.`,
        examples: [
          ex("Visit museums or galleries or whatever.", "Đi bảo tàng hay triển lãm hay gì tương tự."),
          ex("He was fed up, or words to that effect.", "Anh ấy chán ngấy, hay lời tương tự."),
        ],
      },
    ],
    words: U83_WORDS,
    exercises: [
      fillBlank(
        83,
        1,
        "It'll cost you somewhere ____ £900 a month.",
        "in the region of",
        [
          { key: "a", label: "in the region of" },
          { key: "b", label: "in excess of" },
          { key: "c", label: "give or take" },
          { key: "d", label: "more or less" },
        ],
        "a",
      ),
      mcq(
        83,
        2,
        "\"Give or take\" dùng để:",
        [
          { key: "a", label: "Cộng trừ một khoảng nhỏ so với ước lượng" },
          { key: "b", label: "Nói chính xác tuyệt đối" },
          { key: "c", label: "Thay thế tuổi tác" },
          { key: "d", label: "Chỉ số lượng rất lớn" },
        ],
        "a",
      ),
      fillBlank(
        83,
        3,
        "____ students hadn't registered — more than we expected.",
        "Quite a few",
        [
          { key: "a", label: "Quite a few" },
          { key: "b", label: "A smattering of" },
          { key: "c", label: "A scrap of" },
          { key: "d", label: "In excess of" },
        ],
        "a",
      ),
      fillBlank(
        83,
        4,
        "I used to have ____ of CDs before I moved everything to one stick.",
        "stacks",
        [
          { key: "a", label: "stacks" },
          { key: "b", label: "smatterings" },
          { key: "c", label: "smidgens" },
          { key: "d", label: "dollops" },
        ],
        "a",
      ),
      {
        type: "match",
        id: "ex-83-match-5",
        instruction: "Ghép cụm ước lượng với nghĩa",
        pairs: [
          { left: "in excess of", right: "hơn, vượt quá (trang trọng)" },
          { left: "a week or so", right: "khoảng một tuần" },
          { left: "more or less", right: "gần như, tương đối" },
          { left: "or something", right: "hoặc thứ tương tự" },
          { left: "along those lines", right: "kiểu như vậy" },
        ],
      },
      mcq(
        83,
        6,
        "Cụm KHÔNG nên dùng với tuổi:",
        [
          { key: "a", label: "more or less" },
          { key: "b", label: "about" },
          { key: "c", label: "around" },
          { key: "d", label: "approximately" },
        ],
        "a",
      ),
    ],
  }),

  advancedUnit(84, {
    introVi:
      "Unit 84 mô tả cách nói từ thì thầm đến gầm thét và các kiểu hội thoại tiêu cực: nagging, slagging off, winding up. Bạn sẽ chọn động từ âm lượng và phong cách đúng ngữ cảnh.",
    structureSections: [
      { label: "Volume: quiet to loud", wordCount: 8 },
      { label: "Styles of conversation", wordCount: 9 },
      { label: "Speech problems", wordCount: 6 },
    ],
    collocationHtml: `${purple("without a murmur")}, ${purple("raise your voice")}, ${purple("slagging off")} và ${purple("buttering up")} thể hiện sắc thái giọng nói.`,
    mistakeHtml: `${bold("Shout")}, ${bold("yell")}, ${bold("scream")}, ${bold("roar")}, ${bold("shriek")} đều + at. ${bold("Mumble")} và ${bold("mutter")} thường tiêu cực; ${bold("murmur")} có thể tích cực.`,
    principles: [
      {
        title: "Âm lượng từ nhỏ đến lớn",
        body: `${purple("mumble")} / ${purple("mutter")} khó nghe; ${purple("murmur")} thì thầm (có thể đồng ý). ${purple("raise your voice")} nói to hơn; ${purple("roar")} / ${purple("shriek")} rất to — thường + at.`,
        examples: [
          ex("Stop mumbling! I can't hear you.", "Đừng lẩm bẩm! Tôi không nghe được."),
          ex("They accepted it all without a murmur.", "Họ im lặng chấp nhận tất cả."),
        ],
      },
      {
        title: "Kiểu hội thoại",
        body: `${purple("nagging")} cằn nhằn; ${purple("bickering")} / ${purple("squabble")} cãi vụn vặt. ${purple("slagging off")} chê insulting; ${purple("winding up")} trêu; ${purple("buttering up")} nịnh.`,
        examples: [
          ex("They spent the evening slagging off colleagues.", "Họ cả tối chê bai đồng nghiệp."),
          ex("It took him ages to realise they were winding him up.", "Anh ấy lâu mới biết bị trêu."),
        ],
      },
      {
        title: "Vấn đề phát âm",
        body: `${purple("lisp")}, ${purple("stammer")}, ${purple("stutter")} là rối loạn vật lý. ${purple("slur your words")} do say; ${purple("tongue-tied")} do ngại, không nói được.`,
        examples: [
          ex("He slurred his words after drinking too much.", "Anh ấy nói lè nhè sau khi uống quá nhiều."),
          ex("I get tongue-tied when I want to confess.", "Tôi cứng lưỡi khi muốn tỏ tình."),
        ],
      },
    ],
    words: U84_WORDS,
    exercises: [
      fillBlank(
        84,
        1,
        "Stop ____! I can't hear what you're saying.",
        "mumbling",
        [
          { key: "a", label: "mumbling" },
          { key: "b", label: "murmuring" },
          { key: "c", label: "roaring" },
          { key: "d", label: "gossiping" },
        ],
        "a",
      ),
      mcq(
        84,
        2,
        "Chấp nhận im lặng, không phản đối:",
        [
          { key: "a", label: "without a murmur" },
          { key: "b", label: "raise your voice" },
          { key: "c", label: "slagging off" },
          { key: "d", label: "bickering" },
        ],
        "a",
      ),
      fillBlank(
        84,
        3,
        "They spent all evening ____ their colleagues.",
        "slagging off",
        [
          { key: "a", label: "slagging off" },
          { key: "b", label: "buttering up" },
          { key: "c", label: "chatting away" },
          { key: "d", label: "generalising" },
        ],
        "a",
      ),
      fillBlank(
        84,
        4,
        "It took him a long time to realise they were ____ him up.",
        "winding",
        [
          { key: "a", label: "winding" },
          { key: "b", label: "buttering" },
          { key: "c", label: "nagging" },
          { key: "d", label: "whingeing" },
        ],
        "a",
      ),
      mcq(
        84,
        5,
        "\"Tongue-tied\" mô tả:",
        [
          { key: "a", label: "Không nói được vì ngại/xúc động" },
          { key: "b", label: "Nói lắp do rối loạn vật lý" },
          { key: "c", label: "Nói lè nhè vì say rượu" },
          { key: "d", label: "La hét cao vút" },
        ],
        "a",
      ),
      fillBlank(
        84,
        6,
        "Tom and Lily are always ____ at each other about small things.",
        "nagging",
        [
          { key: "a", label: "nagging" },
          { key: "b", label: "roaring" },
          { key: "c", label: "stuttering" },
          { key: "d", label: "lisps" },
        ],
        "a",
      ),
    ],
  }),

  advancedUnit(85, {
    introVi:
      "Unit 85 liệt kê viết tắt, từ rút gọn và acronym thường gặp — từ e.g. và i.e. đến NATO và et al. Bạn sẽ đọc và viết đúng trong email, thư mời và bibliography.",
    structureSections: [
      { label: "Letter abbreviations", wordCount: 10 },
      { label: "Shortened and blended words", wordCount: 6 },
      { label: "Acronyms and academic refs", wordCount: 6 },
    ],
    collocationHtml: `${purple("e.g.")}, ${purple("i.e.")}, ${purple("RSVP")} và ${purple("et al.")} xuất hiện hàng ngày trong văn bản và học thuật.`,
    mistakeHtml: `${bold("e.g.")} = ví dụ; ${bold("i.e.")} = tức là — không thay thế lẫn nhau. ${bold("PIN")} đọc như từ; ${bold("VAT")} có thể /væt/ hoặc đọc từng chữ.`,
    principles: [
      {
        title: "Viết tắt đọc từng chữ",
        body: `${purple("e.g.")} (ví dụ), ${purple("i.e.")} (tức là), ${purple("NB")} (chú ý), ${purple("PTO")} (lật trang). ${purple("AD")} / ${purple("BC")} đếm năm; ${purple("RSVP")} trên thư mời.`,
        examples: [
          ex("Bring essentials, e.g. a toothbrush.", "Mang đồ cần thiết, ví dụ bàn chải."),
          ex("Please RSVP by Friday.", "Vui lòng hồi đáp trước thứ Sáu."),
        ],
      },
      {
        title: "Từ rút gọn và blend",
        body: `${purple("bedsit")}, ${purple("sitcom")}, ${purple("sci-fi")}, ${purple("biopic")}, ${purple("wi-fi")} là clipped forms. Một số đọc như từ hoàn chỉnh.`,
        examples: [
          ex("She rented a tiny bedsit near the station.", "Cô thuê phòng bedsit nhỏ gần ga."),
          ex("The café offers free wi-fi.", "Quán có wi-fi miễn phí."),
        ],
      },
      {
        title: "Acronym và trích dẫn",
        body: `${purple("NATO")}, ${purple("AIDS")}, ${purple("PIN")}, ${purple("VAT")} đọc như từ. Trong bibliography: ${purple("et al.")}, ${purple("cf.")}, pp. cho trang.`,
        examples: [
          ex("O'Keeffe et al. (2010) discuss this problem.", "O'Keeffe và c.s. (2010) bàn vấn đề này."),
          ex("Compare Carter (1997) with Lee (1987) — cf. Lee 1987.", "So sánh Carter (1997) với Lee (1987)."),
        ],
      },
    ],
    words: U85_WORDS,
    exercises: [
      fillBlank(
        85,
        1,
        "The first month, ____ January, was unusually cold.",
        "i.e.",
        [
          { key: "a", label: "i.e." },
          { key: "b", label: "e.g." },
          { key: "c", label: "cf." },
          { key: "d", label: "et al." },
        ],
        "a",
      ),
      mcq(
        85,
        2,
        "Viết tắt mời hồi đáp trên thư mời:",
        [
          { key: "a", label: "RSVP" },
          { key: "b", label: "PTO" },
          { key: "c", label: "ASAP" },
          { key: "d", label: "FAQ" },
        ],
        "a",
      ),
      fillBlank(
        85,
        3,
        "Never share your ____ with anyone at the ATM.",
        "PIN",
        [
          { key: "a", label: "PIN" },
          { key: "b", label: "VIP" },
          { key: "c", label: "UFO" },
          { key: "d", label: "IQ" },
        ],
        "a",
      ),
      fillBlank(
        85,
        4,
        "O'Keeffe ____ (2010) discuss this problem in detail.",
        "et al.",
        [
          { key: "a", label: "et al." },
          { key: "b", label: "e.g." },
          { key: "c", label: "NB" },
          { key: "d", label: "PTO" },
        ],
        "a",
      ),
      mcq(
        85,
        5,
        "Phim tiểu sử người thật (biographical picture):",
        [
          { key: "a", label: "biopic" },
          { key: "b", label: "sitcom" },
          { key: "c", label: "bedsit" },
          { key: "d", label: "sci-fi" },
        ],
        "a",
      ),
      fillBlank(
        85,
        6,
        "Bring snacks, ____ crisps and fruit.",
        "e.g.",
        [
          { key: "a", label: "e.g." },
          { key: "b", label: "i.e." },
          { key: "c", label: "AD" },
          { key: "d", label: "BC" },
        ],
        "a",
      ),
    ],
  }),

  advancedUnit(86, {
    introVi:
      "Unit 86 hệ thống tiền tố tạo nghĩa mới: in-, mis-, over-, under-, up- và eco-. Bạn sẽ đoán nghĩa từ mới và tránh nhầm over- (quá mức) với under- (thiếu).",
    structureSections: [
      { label: "Common prefixes", wordCount: 8 },
      { label: "Over- and under-", wordCount: 10 },
      { label: "Up- and other prefixes", wordCount: 4 },
    ],
    collocationHtml: `${purple("overrated")}, ${purple("underestimate")}, ${purple("overstepped the mark")} và ${purple("eco-friendly")} minh họa tiền tố over-, under-, eco-.`,
    mistakeHtml: `${bold("Over-")} = quá mức hoặc phía trên; ${bold("under-")} = thiếu hoặc bên dưới. ${bold("Re-")} = làm lại; ${bold("Mis-")} = sai cách.`,
    principles: [
      {
        title: "Tiền tố phổ biến",
        body: `${purple("in-")} / im- / il- / ir- phủ định: inappropriate. ${purple("mis-")} = sai: misuse. ${purple("re-")} = lại: reconsider. ${purple("e-")} = điện tử; ${purple("eco-")} = môi trường.`,
        examples: [
          ex("Don't misuse data in your report.", "Đừng dùng sai dữ liệu trong báo cáo."),
          ex("We use eco-friendly cleaning products.", "Chúng tôi dùng sản phẩm thân thiện môi trường."),
        ],
      },
      {
        title: "Over- và under-",
        body: `${purple("overrated")}, ${purple("overpriced")}, ${purple("overhang")}, ${purple("overshadowed")}. ${purple("underestimate")}, ${purple("understaffed")}, ${purple("undermine")}, ${purple("underhand")}. ${purple("overstepped the mark")} = vượt giới hạn.`,
        examples: [
          ex("Don't underestimate the time it will take.", "Đừng đánh giá thấp thời gian cần."),
          ex("He overstepped the mark with that remark.", "Anh ấy vượt giới hạn với lời nói đó."),
        ],
      },
      {
        title: "Up- và out-",
        body: `${purple("upgrade")} và ${purple("upturn")} gợi cải thiện. ${purple("outnumber")} / ${purple("outweigh")} = nhiều/quan trọng hơn. ${purple("overnight")} = qua đêm.`,
        examples: [
          ex("The airline upgraded me to business class.", "Hãng nâng tôi lên hạng thương gia."),
          ex("Women outnumber men in this department.", "Nữ nhiều hơn nam ở khoa này."),
        ],
      },
    ],
    words: U86_WORDS,
    exercises: [
      fillBlank(
        86,
        1,
        "That film was ____ in my view — not as good as critics said.",
        "overrated",
        [
          { key: "a", label: "overrated" },
          { key: "b", label: "underrated" },
          { key: "c", label: "upgraded" },
          { key: "d", label: "underhand" },
        ],
        "a",
      ),
      mcq(
        86,
        2,
        "Tiền tố \"mis-\" thường nghĩa là:",
        [
          { key: "a", label: "Sai cách hoặc sai mục đích" },
          { key: "b", label: "Làm lại" },
          { key: "c", label: "Quá mức" },
          { key: "d", label: "Thiếu hụt" },
        ],
        "a",
      ),
      fillBlank(
        86,
        3,
        "I wish you would not ____ everything I do.",
        "undermine",
        [
          { key: "a", label: "undermine" },
          { key: "b", label: "outnumber" },
          { key: "c", label: "upgrade" },
          { key: "d", label: "reconsider" },
        ],
        "a",
      ),
      fillBlank(
        86,
        4,
        "The company is seriously ____ and needs more staff.",
        "understaffed",
        [
          { key: "a", label: "understaffed" },
          { key: "b", label: "overpriced" },
          { key: "c", label: "eco-friendly" },
          { key: "d", label: "inappropriate" },
        ],
        "a",
      ),
      mcq(
        86,
        5,
        "\"Overstepped the mark\" nghĩa là gì?",
        [
          { key: "a", label: "Vượt giới hạn chấp nhận được" },
          { key: "b", label: "Ở lại qua đêm" },
          { key: "c", label: "Nhiều hơn về số lượng" },
          { key: "d", label: "Cải thiện kinh tế" },
        ],
        "a",
      ),
      fillBlank(
        86,
        6,
        "There has been an ____ in the economy recently.",
        "upturn",
        [
          { key: "a", label: "upturn" },
          { key: "b", label: "overnight" },
          { key: "c", label: "overhang" },
          { key: "d", label: "misuse" },
        ],
        "a",
      ),
    ],
  }),

  advancedUnit(87, {
    introVi:
      "Unit 87 trình bày hậu tố productive: -able, -free, -proof, -worthy và cách chúng tạo tính từ/danh từ mới. Bạn sẽ đọc hiểu và có thể coin từ theo mẫu sách.",
    structureSections: [
      { label: "Productive adjective suffixes", wordCount: 14 },
      { label: "-ly, -ant, -en in other classes", wordCount: 5 },
      { label: "Coining new words", wordCount: 3 },
    ],
    collocationHtml: `${purple("washable")}, ${purple("stress-free")}, ${purple("waterproof")} và ${purple("newsworthy")} minh họa hậu tố -able, -free, -proof, -worthy.`,
    mistakeHtml: `Phần trước hậu tố thường là danh từ số ít: ${bold("crime-related")} (NOT crimes-related). ${bold("-able")} productive; ${bold("-ible")} ít tạo từ mới.`,
    principles: [
      {
        title: "Hậu tố tính từ productive",
        body: `${purple("-able")} = có thể: washable, predictable. ${purple("-conscious")}, ${purple("-minded")} mô tả người. ${purple("-free")} không có điều không mong muốn; ${purple("-rich")} giàu chất.`,
        examples: [
          ex("She wants a stress-free life.", "Cô ấy muốn cuộc sống không căng thẳng."),
          ex("Wear a waterproof jacket in the rain.", "Mặc áo chống nước khi mưa."),
        ],
      },
      {
        title: "-led, -related, -ridden, -worthy",
        body: `${purple("community-led")} do cộng đồng dẫn dắt. ${purple("stress-related")} liên quan căng thẳng. ${purple("crime-ridden")} / ${purple("bedridden")} full of / stuck. ${purple("newsworthy")} đáng đưa tin.`,
        examples: [
          ex("It was a community-led initiative.", "Đó là sáng kiến do cộng đồng dẫn dắt."),
          ex("Her effort was praiseworthy.", "Nỗ lực của cô đáng khen."),
        ],
      },
      {
        title: "Hậu tố đa từ loại",
        body: `${purple("-ly")} không chỉ trạng từ: lively, costly. ${purple("-ant")} tạo danh từ chỉ người: applicant. ${purple("-en")} tạo động từ: moisten, worsen.`,
        examples: [
          ex("There were fifty applicants for the job.", "Có năm mươi ứng viên cho vị trí."),
          ex("Moisten your lips before you speak.", "Làm ẩm môi trước khi nói."),
        ],
      },
    ],
    words: U87_WORDS,
    exercises: [
      fillBlank(
        87,
        1,
        "Wear a ____ jacket — it's going to rain.",
        "waterproof",
        [
          { key: "a", label: "waterproof" },
          { key: "b", label: "washable" },
          { key: "c", label: "disposable" },
          { key: "d", label: "predictable" },
        ],
        "a",
      ),
      mcq(
        87,
        2,
        "Người phải nằm liệt giường vì bệnh:",
        [
          { key: "a", label: "bedridden" },
          { key: "b", label: "crime-ridden" },
          { key: "c", label: "like-minded" },
          { key: "d", label: "tax-free" },
        ],
        "a",
      ),
      fillBlank(
        87,
        3,
        "She is a ____ person who cares about diet and exercise.",
        "health-conscious",
        [
          { key: "a", label: "health-conscious" },
          { key: "b", label: "stress-related" },
          { key: "c", label: "newsworthy" },
          { key: "d", label: "fibre-rich" },
        ],
        "a",
      ),
      fillBlank(
        87,
        4,
        "It was a ____ incident that every newspaper reported.",
        "newsworthy",
        [
          { key: "a", label: "newsworthy" },
          { key: "b", label: "praiseworthy" },
          { key: "c", label: "soundproof" },
          { key: "d", label: "community-led" },
        ],
        "a",
      ),
      {
        type: "match",
        id: "ex-87-match-5",
        instruction: "Ghép hậu tố với ví dụ",
        pairs: [
          { left: "-free", right: "stress-free life" },
          { left: "-rich", right: "fibre-rich diet" },
          { left: "-proof", right: "soundproof room" },
          { left: "-worthy", right: "praiseworthy action" },
          { left: "-led", right: "community-led initiative" },
        ],
      },
      mcq(
        87,
        6,
        "Động từ \"moisten\" được tạo từ tính từ \"moist\" bằng hậu tố:",
        [
          { key: "a", label: "-en" },
          { key: "b", label: "-ant" },
          { key: "c", label: "-ly" },
          { key: "d", label: "-able" },
        ],
        "a",
      ),
    ],
  }),

  advancedUnit(88, {
    introVi:
      "Unit 88 kết hợp word parts Latin/Greek và blends như smog và webinar. Bạn sẽ đoán nghĩa từ gốc và nhận biết cách English tạo từ mới.",
    structureSections: [
      { label: "Latin and Greek word parts", wordCount: 12 },
      { label: "Well-established blends", wordCount: 9 },
    ],
    collocationHtml: `${purple("biodegradable")}, ${purple("monograph")}, ${purple("criminology")} và ${purple("webinar")} cho thấy gốc từ và cách blend.`,
    mistakeHtml: `Gốc Latin/Greek giúp hiểu từ có sẵn — không tự do ghép như tiền tố Unit 86. ${bold("Smog")} = smoke + fog; ${bold("motel")} = motor + hotel.`,
    principles: [
      {
        title: "Word parts học thuật",
        body: `${purple("auto-")} = self; ${purple("bio-")} = life; ${purple("cyber-")} = computers. ${purple("-ology")} = study: criminology. ${purple("pre-")} / ${purple("retro-")} = before / back in time.`,
        examples: [
          ex("Use biodegradable packaging.", "Dùng bao bì phân hủy sinh học."),
          ex("She published a monograph on the poet.", "Cô xuất bản luận văn ngắn về nhà thơ."),
        ],
      },
      {
        title: "Blends phổ biến",
        body: `${purple("brunch")}, ${purple("smog")}, ${purple("motel")}, ${purple("webinar")}, ${purple("guesstimate")}, ${purple("docudrama")}, ${purple("breathalyser")} — ghép hai từ thành một.`,
        examples: [
          ex("Let's meet for brunch on Sunday.", "Chủ nhật gặp ăn brunch nhé."),
          ex("Register for the free webinar.", "Đăng ký webinar miễn phí."),
        ],
      },
      {
        title: "Techno- và tele-",
        body: `${purple("technophobia")} sợ công nghệ; ${purple("telepathic")} cảm nhận từ xa. ${purple("heliport")} = helicopter + airport.`,
        examples: [
          ex("Technophobia keeps some people offline.", "Sợ công nghệ khiến vài người không dùng mạng."),
          ex("The hotel has its own heliport.", "Khách sạn có bến trực thăng riêng."),
        ],
      },
    ],
    words: U88_WORDS,
    exercises: [
      fillBlank(
        88,
        1,
        "Polluted fog in cities is often called ____.",
        "smog",
        [
          { key: "a", label: "smog" },
          { key: "b", label: "motel" },
          { key: "c", label: "brunch" },
          { key: "d", label: "monograph" },
        ],
        "a",
      ),
      mcq(
        88,
        2,
        "Hội thảo trực tuyến (web + seminar):",
        [
          { key: "a", label: "webinar" },
          { key: "b", label: "cybercafé" },
          { key: "c", label: "heliport" },
          { key: "d", label: "docudrama" },
        ],
        "a",
      ),
      fillBlank(
        88,
        3,
        "She specialises in ____, the study of crime.",
        "criminology",
        [
          { key: "a", label: "criminology" },
          { key: "b", label: "obstetrics" },
          { key: "c", label: "phonetics" },
          { key: "d", label: "technophobia" },
        ],
        "a",
      ),
      fillBlank(
        88,
        4,
        "It's only a ____, not an exact calculation.",
        "guesstimate",
        [
          { key: "a", label: "guesstimate" },
          { key: "b", label: "monograph" },
          { key: "c", label: "congress" },
          { key: "d", label: "breathalyser" },
        ],
        "a",
      ),
      mcq(
        88,
        5,
        "Tiền tố \"bio-\" thường liên quan đến:",
        [
          { key: "a", label: "Sự sống, sinh học" },
          { key: "b", label: "Máy tính" },
          { key: "c", label: "Âm thanh" },
          { key: "d", label: "Tự trị" },
        ],
        "a",
      ),
      fillBlank(
        88,
        6,
        "Use ____ packaging that can decay naturally.",
        "biodegradable",
        [
          { key: "a", label: "biodegradable" },
          { key: "b", label: "autonomous" },
          { key: "c", label: "retroactive" },
          { key: "d", label: "telepathic" },
        ],
        "a",
      ),
    ],
  }),

  advancedUnit(89, {
    introVi:
      "Unit 89 khám phá tiếng Anh như ngôn ngữ toàn cầu: nguồn gốc từ vựng, loanwords và false friends. Bạn sẽ hiểu vì sao English có nhiều từ cho cùng một khái niệm.",
    structureSections: [
      { label: "Origins and history", wordCount: 8 },
      { label: "Loanwords by language", wordCount: 10 },
      { label: "False friends", wordCount: 3 },
    ],
    collocationHtml: `${purple("loanwords")}, ${purple("Anglo-Saxon")}, ${purple("classical origin")} và ${purple("false friends")} giải thích sự đa dạng từ vựng English.`,
    mistakeHtml: `${bold("Sympathetic")} trong English = thông cảm nỗi đau, không chỉ \"nice\". ${bold("Gift")} trong German = poison — classic false friend.`,
    principles: [
      {
        title: "Nguồn gốc từ vựng",
        body: `English bắt đầu với ${purple("Anglo-Saxon")}; Viking ${purple("Norse")} và ${purple("Norman")} French bổ sung hàng loạt từ. ${purple("Renaissance")} mang ${purple("classical origin")} Latin/Greek.`,
        examples: [
          ex("English welcomes words from many languages.", "Tiếng Anh chào đón từ nhiều ngôn ngữ."),
          ex("Scholars introduced classical words in the Renaissance.", "Học giả đưa từ cổ điển vào thời Phục hưng."),
        ],
      },
      {
        title: "Loanwords theo ngôn ngữ",
        body: `${purple("amber")} (Arabic), ${purple("roster")} (Dutch), ${purple("karaoke")} (Japanese), ${purple("hammock")} (Spanish), ${purple("turban")} (Turkish)... English gọi là ${purple("loanwords")} / ${purple("borrowings")}.`,
        examples: [
          ex("She wore an amber necklace.", "Cô đeo vòng cổ hổ phách."),
          ex("What a palaver over a simple mistake!", "Ồn ào quá vì một lỗi nhỏ!"),
        ],
      },
      {
        title: "False friends",
        body: `${purple("false friends")} trông giống từ ngôn ngữ bạn nhưng nghĩa khác. ${purple("sympathetic")} hẹp hơn \"dễ thương\" ở nhiều ngôn ngữ Châu Âu.`,
        examples: [
          ex("Gift in German means poison — a false friend.", "Gift trong tiếng Đức nghĩa là độc — false friend."),
          ex("Sympathetic means understanding others' suffering.", "Sympathetic nghĩa là thông cảm nỗi đau người khác."),
        ],
      },
    ],
    words: U89_WORDS,
    exercises: [
      fillBlank(
        89,
        1,
        "English has always welcomed ____ from other languages.",
        "loanwords",
        [
          { key: "a", label: "loanwords" },
          { key: "b", label: "false friends" },
          { key: "c", label: "prefixes" },
          { key: "d", label: "suffixes" },
        ],
        "a",
      ),
      mcq(
        89,
        2,
        "Từ \"karaoke\" mượn từ ngôn ngữ nào?",
        [
          { key: "a", label: "Japanese" },
          { key: "b", label: "Arabic" },
          { key: "c", label: "Russian" },
          { key: "d", label: "Portuguese" },
        ],
        "a",
      ),
      fillBlank(
        89,
        3,
        "Gift in German means poison — a classic ____.",
        "false friend",
        [
          { key: "a", label: "false friend" },
          { key: "b", label: "loanword" },
          { key: "c", label: "Anglo-Saxon word" },
          { key: "d", label: "blend" },
        ],
        "a",
      ),
      fillBlank(
        89,
        4,
        "Check the cooking ____ to see when it's your turn.",
        "roster",
        [
          { key: "a", label: "roster" },
          { key: "b", label: "hammock" },
          { key: "c", label: "turban" },
          { key: "d", label: "tonic" },
        ],
        "a",
      ),
      mcq(
        89,
        5,
        "\"Sympathetic\" trong English thường nghĩa là:",
        [
          { key: "a", label: "Thông cảm nỗi đau người khác" },
          { key: "b", label: "Dễ thương, nice" },
          { key: "c", label: "Thông minh" },
          { key: "d", label: "Trung thực" },
        ],
        "a",
      ),
      fillBlank(
        89,
        6,
        "The 19th-century ____ debated social reform.",
        "intelligentsia",
        [
          { key: "a", label: "intelligentsia" },
          { key: "b", label: "lexicon" },
          { key: "c", label: "gimmick" },
          { key: "d", label: "tabby" },
        ],
        "a",
      ),
    ],
  }),

  advancedUnit(90, {
    introVi:
      "Unit 90 tập trung cặp từ dễ nhầm: intervene/interfere, continually/continuously, compliment/complement và phrasal noun pairs. Bạn sẽ chọn từ đúng sắc thái và ngữ pháp.",
    structureSections: [
      { label: "Similar form, different shade", wordCount: 10 },
      { label: "Theme, topic, security, safety", wordCount: 6 },
      { label: "Phrasal verb noun pairs", wordCount: 8 },
    ],
    collocationHtml: `${purple("intervene")} vs ${purple("interfere")}, ${purple("compliment")} vs ${purple("complement")} và ${purple("breakout")} vs ${purple("outbreak")} là cặp then chốt.`,
    mistakeHtml: `${bold("Continually")} = liên tục/lặp lại (often negative); ${bold("continuously")} = không ngắt. ${bold("Series")} = bộ nhiều phần; ${bold("serial")} = câu chuyện nối tiếp.`,
    principles: [
      {
        title: "Cùng dạng, khác sắc thái",
        body: `${purple("intervene")} trung lập/can thiệp; ${purple("interfere")} xen vào (tiêu cực). ${purple("continually")} rất thường xuyên; ${purple("continuously")} không dừng. ${purple("shade")} dễ chịu; ${purple("shadow")} thường tiêu cực.`,
        examples: [
          ex("The UN should intervene to stop the war.", "LHQ nên can thiệp để chấm dứt chiến tranh."),
          ex("Stir continuously until it boils.", "Khuấy liên tục không ngừng đến khi sôi."),
        ],
      },
      {
        title: "Compliment vs complement",
        body: `${purple("compliment")} khen; ${purple("complement")} bổ sung cho nhau. ${purple("moist")} (công thức) vs ${purple("damp")} (khó chịu). ${purple("theme")} chủ đề tổng; ${purple("topic")} chủ đề cuộc nói.`,
        examples: [
          ex("She complimented me on my performance.", "Cô khen phần trình diễn của tôi."),
          ex("Programming complements my other IT skills.", "Lập trình bổ sung kỹ năng IT khác."),
        ],
      },
      {
        title: "Phrasal noun pairs",
        body: `break out → ${purple("breakout")} (vượt ngục) / ${purple("outbreak")} (dịch). look out → ${purple("outlook")} (triển vọng) / ${purple("lookout")} (canh gác). ${purple("end up")} ≠ upend; ${purple("set up")} ≠ upset.`,
        examples: [
          ex("There was a breakout at the prison.", "Có vụ vượt ngục ở nhà tù."),
          ex("There has been an outbreak of the disease.", "Dịch bệnh bùng phát."),
        ],
      },
    ],
    words: U90_WORDS,
    exercises: [
      fillBlank(
        90,
        1,
        "She shouldn't ____ in things that don't concern her.",
        "interfere",
        [
          { key: "a", label: "interfere" },
          { key: "b", label: "intervene" },
          { key: "c", label: "complement" },
          { key: "d", label: "compliment" },
        ],
        "a",
      ),
      mcq(
        90,
        2,
        "Khuấy liên tục không ngừng (công thức nấu):",
        [
          { key: "a", label: "continuously" },
          { key: "b", label: "continually" },
          { key: "c", label: "intermittently" },
          { key: "d", label: "vaguely" },
        ],
        "a",
      ),
      fillBlank(
        90,
        3,
        "Programming ____ my other IT skills.",
        "complements",
        [
          { key: "a", label: "complements" },
          { key: "b", label: "compliments" },
          { key: "c", label: "intervenes" },
          { key: "d", label: "interferes" },
        ],
        "a",
      ),
      fillBlank(
        90,
        4,
        "There has been an ____ of the disease in several villages.",
        "outbreak",
        [
          { key: "a", label: "outbreak" },
          { key: "b", label: "breakout" },
          { key: "c", label: "outlook" },
          { key: "d", label: "lookout" },
        ],
        "a",
      ),
      {
        type: "match",
        id: "ex-90-match-5",
        instruction: "Ghép cặp từ dễ nhầm với nghĩa phân biệt",
        pairs: [
          { left: "intervene", right: "can thiệp (trung lập)" },
          { left: "interfere", right: "xen vào (tiêu cực)" },
          { left: "moist", right: "ẩm vừa (công thức)" },
          { left: "damp", right: "ẩm ướt khó chịu" },
          { left: "theme", right: "chủ đề tổng thể sự kiện" },
        ],
      },
      mcq(
        90,
        6,
        "Phim/bài nối tiếp từng tập — miss one và mất mạch:",
        [
          { key: "a", label: "serial" },
          { key: "b", label: "series" },
          { key: "c", label: "shade" },
          { key: "d", label: "shadow" },
        ],
        "a",
      ),
    ],
  }),
];
