import { assertExerciseCount, cloze, match, mcq } from "./eviu-elementary-curated-helpers";
import type { VocabularyExercise } from "@/lib/vocabulary/vocabulary-unit-types";

const UNIT_16: VocabularyExercise[] = [
  cloze("ex-16-2-1", "16.2 · Giao tiếp", "You put letters through the slot in a ___ on the street.", "letter box", [
    "Letter box",
  ]),
  cloze(
    "ex-16-2-2",
    "16.2 · Giao tiếp",
    "A ___ is a small box in the street where you can make phone calls.",
    "phone box",
    ["Phone box"],
  ),
  cloze("ex-16-2-3", "16.2 · Giao tiếp", "A ___ phone is a phone you can carry with you.", "mobile", ["Mobile"]),
  cloze("ex-16-2-4", "16.2 · Giao tiếp", "You put a ___ on an envelope before you post it.", "stamp", ["Stamp"]),
  cloze("ex-16-2-5", "16.2 · Giao tiếp", "Write your name and ___ on the envelope.", "address", ["Address"]),
  cloze("ex-16-2-6", "16.2 · Giao tiếp", "Put the letter inside an ___ before you post it.", "envelope", ["Envelope"]),
  cloze("ex-16-2-7", "16.2 · Giao tiếp", "A computer ___ shows pictures and words.", "screen", ["Screen"]),
  cloze("ex-16-2-8", "16.2 · Giao tiếp", "A ___ is a small computer you can carry.", "laptop", ["Laptop"]),
  cloze("ex-16-2-9", "16.2 · Giao tiếp", "A ___ stick stores computer files.", "memory", ["Memory"]),
  cloze("ex-16-2-10", "16.2 · Giao tiếp", "You use a ___ to move the cursor on a computer.", "mouse", ["Mouse"]),
  cloze("ex-16-2-11", "16.2 · Giao tiếp", "Pick up the ___ and dial a number.", "phone", ["Phone"]),
  cloze("ex-16-3-1", "16.3 · Hội thoại", "MEENA: Hello. ___ Meena here. Can I speak to Amal, please?", "It's", ["It's"]),
  cloze("ex-16-3-2", "16.3 · Hội thoại", "MEENA: Can I ___ to Amal, please?", "speak", ["Speak"]),
  cloze("ex-16-3-3", "16.3 · Hội thoại", "AMELIA: I'm ___, he's at work at the moment.", "sorry", ["Sorry"]),
  cloze("ex-16-3-4", "16.3 · Hội thoại", "AMELIA: He's at work ___ the moment.", "at", ["At"]),
  cloze("ex-16-3-5", "16.3 · Hội thoại", "AMELIA: Can I ___ a message?", "take", ["Take"]),
  cloze("ex-16-3-6", "16.3 · Hội thoại", "MEENA: I'll ___ back later.", "call", ["Call", "phone", "Phone", "ring", "Ring"]),
];

const UNIT_17: VocabularyExercise[] = [
  match("ex-17-1", "17.1 · Ghép bộ phận điện thoại", [
    { left: "camera", right: "takes photos" },
    { left: "SIM card", right: "stores the information you need to use your phone" },
    { left: "screen", right: "shows pictures and words" },
    { left: "phone case", right: "covers the phone" },
    { left: "power button", right: "starts the phone" },
  ]),
  mcq(
    "ex-17-2-1",
    "17.2 · Chọn từ",
    "Tanya has a new ___ for texting on the Internet.",
    "a",
    [
      { key: "a", label: "app" },
      { key: "b", label: "battery" },
      { key: "c", label: "charger" },
      { key: "d", label: "screen" },
    ],
  ),
  mcq(
    "ex-17-2-2",
    "17.2 · Chọn từ",
    "When your phone's battery is low, you need a ___.",
    "a",
    [
      { key: "a", label: "charger" },
      { key: "b", label: "camera" },
      { key: "c", label: "app" },
      { key: "d", label: "phone case" },
    ],
  ),
  mcq(
    "ex-17-2-3",
    "17.2 · Chọn từ",
    "You can use my phone to ___ Megan.",
    "b",
    [
      { key: "a", label: "voicemail" },
      { key: "b", label: "call" },
      { key: "c", label: "download" },
      { key: "d", label: "swipe" },
    ],
  ),
  mcq(
    "ex-17-2-4",
    "17.2 · Chọn từ",
    "Danny's new phone has a great ___. It takes amazing photos.",
    "b",
    [
      { key: "a", label: "screen" },
      { key: "b", label: "camera" },
      { key: "c", label: "battery" },
      { key: "d", label: "SIM card" },
    ],
  ),
  mcq(
    "ex-17-2-5",
    "17.2 · Chọn từ",
    "I bought a new ___ in France, so that it was cheaper to call and use the Internet.",
    "b",
    [
      { key: "a", label: "battery" },
      { key: "b", label: "SIM card" },
      { key: "c", label: "phone case" },
      { key: "d", label: "app" },
    ],
  ),
  mcq(
    "ex-17-2-6",
    "17.2 · Chọn từ",
    "I want to buy a new ___. This one is old and dirty.",
    "c",
    [
      { key: "a", label: "battery" },
      { key: "b", label: "app" },
      { key: "c", label: "phone case" },
      { key: "d", label: "charger" },
    ],
  ),
  cloze("ex-17-3-1", "17.3 · Hoàn thành câu", "Maria ___ me last night, but I didn't see her message until this morning.", "texted", [
    "Texted",
  ]),
  cloze("ex-17-3-2", "17.3 · Hoàn thành câu", "Carlos ___ a lot of photos of his new dog and puts them on Facebook.", "takes", [
    "Takes",
  ]),
  cloze("ex-17-3-3", "17.3 · Hoàn thành câu", "What was the last app that you ___?", "downloaded", ["Downloaded"]),
  cloze("ex-17-3-4", "17.3 · Hoàn thành câu", "Lucy ___ her sister. They talked about their holiday at the beach.", "called", ["Called"]),
  cloze("ex-17-3-5", "17.3 · Hoàn thành câu", "Victor ___ me a voicemail. He asked me to call him back.", "left", ["Left"]),
  cloze("ex-17-4-1", "17.4 · Hội thoại", "IREENA: Let me just put in the PIN to ___ it.", "unlock", ["Unlock"]),
  cloze("ex-17-4-2", "17.4 · Hội thoại", "DEEPA: Do I ___ right to see the next photo?", "swipe", ["Swipe"]),
  cloze("ex-17-4-3", "17.4 · Hội thoại", "IREENA: I ___ them in a different folder.", "saved", ["Saved"]),
];

const UNIT_18: VocabularyExercise[] = [
  cloze("ex-18-1-1", "18.1 · Kỳ nghỉ", "A: Are you working on Monday? B: No, I'm ___ holiday.", "on", ["On"]),
  cloze("ex-18-1-2", "18.1 · Kỳ nghỉ", "A: Are you on holiday this year? B: Yes, I'm ___ camping.", "going", ["Going"]),
  cloze("ex-18-1-3", "18.1 · Kỳ nghỉ", "A: Did you have a good ___ in Greece? B: Yes, it was wonderful.", "time", ["Time", "holiday", "Holiday"]),
  cloze("ex-18-1-4", "18.1 · Kỳ nghỉ", "A: Are you flying to Italy? B: No, I'm going ___ train.", "by", ["By"]),
  cloze("ex-18-1-5", "18.1 · Kỳ nghỉ", "A: I'm going to New York next week. B: Great! Please ___ me a postcard.", "send", ["Send"]),
  mcq(
    "ex-18-2-1",
    "18.2 · Loại kỳ nghỉ",
    "It was fun but the tent was very small. This is a ___ holiday.",
    "d",
    [
      { key: "a", label: "package holiday" },
      { key: "b", label: "coach tour" },
      { key: "c", label: "walking holiday" },
      { key: "d", label: "camping holiday" },
    ],
  ),
  mcq(
    "ex-18-2-2",
    "18.2 · Loại kỳ nghỉ",
    "Everything was included — hotels and flights.",
    "a",
    [
      { key: "a", label: "a package holiday" },
      { key: "b", label: "a walking holiday" },
      { key: "c", label: "a winter holiday" },
      { key: "d", label: "camping" },
    ],
  ),
  mcq(
    "ex-18-2-3",
    "18.2 · Loại kỳ nghỉ",
    "We were on the coach for seven days. I was very tired.",
    "b",
    [
      { key: "a", label: "a package holiday" },
      { key: "b", label: "a coach tour" },
      { key: "c", label: "camping" },
      { key: "d", label: "a walking holiday" },
    ],
  ),
  mcq(
    "ex-18-2-4",
    "18.2 · Loại kỳ nghỉ",
    "We walked about 20 kilometres every day.",
    "c",
    [
      { key: "a", label: "a coach tour" },
      { key: "b", label: "camping" },
      { key: "c", label: "a walking holiday" },
      { key: "d", label: "a package holiday" },
    ],
  ),
  mcq(
    "ex-18-2-5",
    "18.2 · Loại kỳ nghỉ",
    "We went to Switzerland in December. There was a lot of snow.",
    "d",
    [
      { key: "a", label: "camping" },
      { key: "b", label: "a coach tour" },
      { key: "c", label: "a walking holiday" },
      { key: "d", label: "a winter holiday" },
    ],
  ),
  cloze("ex-18-4-1", "18.4 · Đồ mang theo", "Don't forget your ___ when you go to another country.", "passport", ["Passport"]),
  cloze("ex-18-4-2", "18.4 · Đồ mang theo", "Take a ___ to take photos on holiday.", "camera", ["Camera"]),
  cloze("ex-18-4-3", "18.4 · Đồ mang theo", "You need your ___ for the plane or train.", "tickets", ["Tickets"]),
  cloze("ex-18-5-1", "18.5 · Đồ mang theo", "You may need a ___ — a special stamp in your passport.", "visa", ["Visa"]),
  cloze("ex-18-5-2", "18.5 · Đồ mang theo", "We flew there in a ___.", "plane", ["Plane"]),
  cloze("ex-18-5-3", "18.5 · Đồ mang theo", "A ___ is a bag you carry on your back.", "rucksack", ["Rucksack"]),
  cloze("ex-18-6-1", "18.6 · Email", "I'm having a great ___ here in Spain.", "time", ["Time"]),
  cloze("ex-18-6-2", "18.6 · Email", "The ___ is great — the clubs are open all night.", "nightlife", ["Nightlife"]),
  cloze("ex-18-6-3", "18.6 · Email", "The ___ food is very good — lots of fish and salads.", "local", ["Local"]),
  cloze("ex-18-6-4", "18.6 · Email", "Please send me a ___ from your holiday in Italy.", "postcard", ["Postcard"]),
];

const UNIT_19: VocabularyExercise[] = [
  match("ex-19-1", "19.1 · Ghép cửa hàng", [
    { left: "sausages", right: "butcher" },
    { left: "beach ball", right: "toy shop" },
    { left: "bread", right: "baker" },
    { left: "greeting cards", right: "newsagent" },
    { left: "souvenir T-shirt", right: "gift shop" },
  ]),
  cloze("ex-19-2-1", "19.2 · Mua sắm", "I want to get a newspaper. I need to go to the ___.", "newsagent", ["Newsagent", "newsagent's"]),
  cloze("ex-19-2-2", "19.2 · Mua sắm", "I'd like to buy food for a week. I'll go to the ___.", "supermarket", ["Supermarket"]),
  cloze("ex-19-2-3", "19.2 · Mua sắm", "I need some stamps. I'll go to the ___.", "post office", ["Post office"]),
  cloze("ex-19-2-4", "19.2 · Mua sắm", "We must get Michael a present. Let's go to a ___.", "gift shop", ["Gift shop"]),
  cloze("ex-19-2-5", "19.2 · Mua sắm", "I'd like to buy a book. I'll go to the ___.", "bookshop", ["Bookshop"]),
  cloze("ex-19-3-1", "19.3 · Tầng cửa hàng", "Lipstick is on the ___ floor (Beauty).", "ground", ["Ground"]),
  cloze("ex-19-3-2", "19.3 · Tầng cửa hàng", "An armchair is on the ___ floor (Furniture).", "third", ["Third"]),
  cloze("ex-19-3-3", "19.3 · Tầng cửa hàng", "A skirt is on the ___ floor (Women's Wear).", "first", ["First"]),
  cloze("ex-19-3-4", "19.3 · Tầng cửa hàng", "A TV is in the ___ (Electricals).", "basement", ["Basement"]),
  mcq(
    "ex-19-4-1",
    "19.4 · Định nghĩa",
    "Money (not a cheque or credit/debit card) is called ___",
    "a",
    [
      { key: "a", label: "cash" },
      { key: "b", label: "change" },
      { key: "c", label: "receipt" },
      { key: "d", label: "note" },
    ],
  ),
  mcq(
    "ex-19-4-2",
    "19.4 · Định nghĩa",
    "A piece of paper that is worth £20 is a ___",
    "d",
    [
      { key: "a", label: "coin" },
      { key: "b", label: "cash" },
      { key: "c", label: "receipt" },
      { key: "d", label: "note" },
    ],
  ),
  mcq(
    "ex-19-4-3",
    "19.4 · Định nghĩa",
    "'Plastic money' means a ___",
    "b",
    [
      { key: "a", label: "£20 note" },
      { key: "b", label: "credit or debit card" },
      { key: "c", label: "carrier bag" },
      { key: "d", label: "receipt" },
    ],
  ),
  mcq(
    "ex-19-4-4",
    "19.4 · Định nghĩa",
    "Coins or smaller notes are called ___",
    "c",
    [
      { key: "a", label: "cash" },
      { key: "b", label: "credit" },
      { key: "c", label: "change" },
      { key: "d", label: "receipt" },
    ],
  ),
  mcq(
    "ex-19-5-1",
    "19.5 · Biển báo",
    "Which sign tells you that you can't go into the shop?",
    "a",
    [
      { key: "a", label: "Closed" },
      { key: "b", label: "Open" },
      { key: "c", label: "Push" },
      { key: "d", label: "Pull" },
    ],
  ),
  mcq(
    "ex-19-5-2",
    "19.5 · Biển báo",
    "Which sign tells you that the door will open towards you?",
    "c",
    [
      { key: "a", label: "Closed" },
      { key: "b", label: "Open" },
      { key: "c", label: "Pull" },
      { key: "d", label: "Push" },
    ],
  ),
  mcq(
    "ex-19-5-3",
    "19.5 · Biển báo",
    "Which sign tells you that the door will open away from you?",
    "d",
    [
      { key: "a", label: "Closed" },
      { key: "b", label: "Open" },
      { key: "c", label: "Pull" },
      { key: "d", label: "Push" },
    ],
  ),
  cloze("ex-19-6-1", "19.6 · Hội thoại", "CUSTOMER: How much does this jacket ___?", "cost", ["Cost"]),
  cloze("ex-19-6-2", "19.6 · Hội thoại", "CUSTOMER: Can I ___ by credit card?", "pay", ["Pay"]),
  cloze("ex-19-6-3", "19.6 · Hội thoại", "SHOP ASSISTANT: Would you like a (carrier) ___?", "bag", ["Bag"]),
];

const UNIT_20: VocabularyExercise[] = [
  match("ex-20-1", "20.1 · Ghép thuật ngữ", [
    { left: "size", right: "small" },
    { left: "price", right: "£12.89" },
    { left: "delivery address", right: "7 Park Lane, Bristol" },
    { left: "post code", right: "MR12 6QA" },
    { left: "credit card", right: "MasterCard" },
    { left: "order number", right: "8167990012" },
  ]),
  mcq(
    "ex-20-2-1",
    "20.2 · Chọn từ",
    "When you shop online, you can ___ for the best price.",
    "a",
    [
      { key: "a", label: "search" },
      { key: "b", label: "collect" },
      { key: "c", label: "deliver" },
      { key: "d", label: "delete" },
    ],
  ),
  mcq(
    "ex-20-2-2",
    "20.2 · Chọn từ",
    "You can read ___ from other people who bought the same thing.",
    "b",
    [
      { key: "a", label: "sizes" },
      { key: "b", label: "reviews" },
      { key: "c", label: "orders" },
      { key: "d", label: "receipts" },
    ],
  ),
  mcq(
    "ex-20-2-3",
    "20.2 · Chọn từ",
    "If you want to buy something, ___ it to your basket.",
    "a",
    [
      { key: "a", label: "add" },
      { key: "b", label: "deliver" },
      { key: "c", label: "delete" },
      { key: "d", label: "order" },
    ],
  ),
  mcq(
    "ex-20-2-4",
    "20.2 · Chọn từ",
    "If you don't want to buy something in your basket, you can ___ it.",
    "c",
    [
      { key: "a", label: "add" },
      { key: "b", label: "deliver" },
      { key: "c", label: "delete" },
      { key: "d", label: "search" },
    ],
  ),
  mcq(
    "ex-20-2-5",
    "20.2 · Chọn từ",
    "Don't forget to check how much you will pay for ___.",
    "a",
    [
      { key: "a", label: "delivery" },
      { key: "b", label: "order number" },
      { key: "c", label: "post code" },
      { key: "d", label: "size" },
    ],
  ),
  mcq(
    "ex-20-2-6",
    "20.2 · Chọn từ",
    "You can use your ___ to pay for your shopping.",
    "b",
    [
      { key: "a", label: "post code" },
      { key: "b", label: "credit card" },
      { key: "c", label: "delivery address" },
      { key: "d", label: "review" },
    ],
  ),
  cloze("ex-20-3-1", "20.3 · Hội thoại", "TOM: I'm waiting for a ___ of a pair of shoes.", "delivery", ["Delivery"]),
  cloze("ex-20-3-2", "20.3 · Hội thoại", "CUSTOMER CARE: What's your ___?", "order number", ["Order number"]),
  cloze("ex-20-3-3", "20.3 · Hội thoại", "TOM: 31 Mill Road, WC2 5SN. What's your address and ___?", "post code", [
    "Post code",
  ]),
  cloze("ex-20-3-4", "20.3 · Hội thoại", "I paid £5 for ___ delivery.", "next day", ["Next day"]),
  mcq(
    "ex-20-4-1",
    "20.4 · Thứ tự mua hàng",
    "What is the FIRST step when buying a computer online?",
    "c",
    [
      { key: "a", label: "Pay with a credit card" },
      { key: "b", label: "Add the computer to your basket" },
      { key: "c", label: "Search for a website which sells the computer" },
      { key: "d", label: "Wait at home for the delivery" },
    ],
  ),
  mcq(
    "ex-20-4-2",
    "20.4 · Thứ tự mua hàng",
    "After you find a website, what do you do next?",
    "d",
    [
      { key: "a", label: "Choose next day delivery" },
      { key: "b", label: "Pay with a credit card" },
      { key: "c", label: "Wait at home for the delivery" },
      { key: "d", label: "Read online reviews and choose which computer to buy" },
    ],
  ),
  mcq(
    "ex-20-4-3",
    "20.4 · Thứ tự mua hàng",
    "What do you do AFTER you choose the computer?",
    "a",
    [
      { key: "a", label: "Add the computer to your basket" },
      { key: "b", label: "Search for a website" },
      { key: "c", label: "Read online reviews" },
      { key: "d", label: "Wait at home for the delivery" },
    ],
  ),
  mcq(
    "ex-20-4-4",
    "20.4 · Thứ tự mua hàng",
    "What is the LAST step?",
    "b",
    [
      { key: "a", label: "Add the computer to your basket" },
      { key: "b", label: "Wait at home for the delivery" },
      { key: "c", label: "Search for a website" },
      { key: "d", label: "Read online reviews" },
    ],
  ),
];

const UNIT_21: VocabularyExercise[] = [
  cloze("ex-21-1-1", "21.1 · Khách sạn", "RECEPTIONIST: Would you like a ___ room with a bathroom?", "double", ["Double"]),
  cloze("ex-21-1-2", "21.1 · Khách sạn", "CUSTOMER: Yes, please. And with a view of the ___, please.", "sea", ["Sea", "garden", "Garden"]),
  cloze("ex-21-1-3", "21.1 · Khách sạn", "RECEPTIONIST: All our rooms have a TV, a ___ and a shower.", "phone", ["Phone"]),
  cloze("ex-21-1-4", "21.1 · Khách sạn", "RECEPTIONIST: Here is your ___.", "key", ["Key"]),
  cloze("ex-21-1-5", "21.1 · Khách sạn", "RECEPTIONIST: The ___ is over there.", "lift", ["Lift"]),
  match("ex-21-2", "21.2 · Ghép nhu cầu", [
    { left: "have a drink in your room", right: "a mini-bar" },
    { left: "go to the top floor", right: "the lift" },
    { left: "open your door", right: "a key" },
    { left: "get up at 6 am", right: "a wake-up call" },
    { left: "phone your country", right: "an outside line" },
    { left: "watch the news", right: "a TV" },
    { left: "wash your hair", right: "a shower" },
    { left: "dry your hair", right: "a hairdryer" },
  ]),
  cloze("ex-21-3-1", "21.3 · Sửa lỗi", "At ___ you can order room service.", "reception", ["Reception"]),
  cloze("ex-21-3-2", "21.3 · Sửa lỗi", "We'd like a ___ room with a view of the garden, please.", "double", ["Double"]),
  cloze("ex-21-3-3", "21.3 · Sửa lỗi", "The ___ is over there. Take it to the second floor.", "lift", ["Lift"]),
  cloze("ex-21-3-4", "21.3 · Sửa lỗi", "Please ___ in this form.", "fill", ["Fill"]),
  cloze("ex-21-3-5", "21.3 · Sửa lỗi", "I'd like a ___ call at 7.30, please.", "wake-up", ["Wake-up"]),
  cloze("ex-21-3-6", "21.3 · Sửa lỗi", "I have a ___ for a single room with a bathroom.", "reservation", ["Reservation"]),
  cloze("ex-21-4-1", "21.4 · Can I...?", "Can I have a ___ call, please?", "wake-up", ["Wake-up"]),
  cloze("ex-21-4-2", "21.4 · Can I...?", "Can I have breakfast in my ___, please?", "room", ["Room"]),
  cloze("ex-21-4-3", "21.4 · Can I...?", "Can I have the ___, please?", "bill", ["Bill"]),
  cloze("ex-21-4-4", "21.4 · Can I...?", "Can I have a ___ room for tonight, please?", "double", ["Double", "single", "Single"]),
];

const UNIT_22: VocabularyExercise[] = [
  mcq(
    "ex-22-1-1",
    "22.1 · Ăn uống",
    "Where would you go to buy a meal and take it home to eat?",
    "c",
    [
      { key: "a", label: "restaurant" },
      { key: "b", label: "café" },
      { key: "c", label: "take-away" },
      { key: "d", label: "bar" },
    ],
  ),
  mcq(
    "ex-22-1-2",
    "22.1 · Ăn uống",
    "Where would you go to have a romantic dinner for two?",
    "a",
    [
      { key: "a", label: "restaurant" },
      { key: "b", label: "fast food restaurant" },
      { key: "c", label: "take-away" },
      { key: "d", label: "café" },
    ],
  ),
  mcq(
    "ex-22-1-3",
    "22.1 · Ăn uống",
    "Where would you go to eat a quick lunch?",
    "b",
    [
      { key: "a", label: "restaurant" },
      { key: "b", label: "fast food restaurant" },
      { key: "c", label: "bar" },
      { key: "d", label: "take-away" },
    ],
  ),
  mcq(
    "ex-22-1-4",
    "22.1 · Ăn uống",
    "Where would you go to have a cake and a cup of coffee?",
    "d",
    [
      { key: "a", label: "restaurant" },
      { key: "b", label: "take-away" },
      { key: "c", label: "bar" },
      { key: "d", label: "café" },
    ],
  ),
  mcq(
    "ex-22-1-5",
    "22.1 · Ăn uống",
    "Where would you go to drink a glass of wine with friends?",
    "c",
    [
      { key: "a", label: "café" },
      { key: "b", label: "take-away" },
      { key: "c", label: "bar / pub" },
      { key: "d", label: "fast food restaurant" },
    ],
  ),
  cloze("ex-22-3-1", "22.3 · Collocation", "You can have tomato / vegetable / chicken ___ as a starter.", "soup", ["Soup"]),
  cloze("ex-22-3-2", "22.3 · Collocation", "I'd like the beef / chicken / vegetable ___ as a main course.", "curry", ["Curry"]),
  cloze("ex-22-3-3", "22.3 · Collocation", "I'll have the mixed / tomato / fruit ___.", "salad", ["Salad"]),
  cloze("ex-22-3-4", "22.3 · Collocation", "Can I have the apple / chicken ___, please?", "pie", ["Pie"]),
  cloze("ex-22-3-5", "22.3 · Collocation", "Do you like your ___ well-done, medium or rare?", "steak", ["Steak"]),
  cloze("ex-22-4-1", "22.4 · Sửa hội thoại", "WAITER: Are you ready to ___?", "order", ["Order"]),
  cloze("ex-22-4-2", "22.4 · Sửa hội thoại", "CUSTOMER: Yes, I'd ___ vegetable soup and steak, please.", "like", ["Like"]),
  cloze("ex-22-4-3", "22.4 · Sửa hội thoại", "WAITER: How would you like your steak? Rare, medium or well-___?", "done", ["Done"]),
  cloze("ex-22-4-4", "22.4 · Sửa hội thoại", "WAITER: What would you ___ to drink?", "like", ["Like"]),
  cloze("ex-22-4-5", "22.4 · Sửa hội thoại", "CUSTOMER: ___ orange juice, please.", "An", ["An", "A"]),
  cloze("ex-22-4-6", "22.4 · Sửa hội thoại", "CUSTOMER: A ___ juice, please.", "orange", ["Orange"]),
];

const UNIT_23: VocabularyExercise[] = [
  mcq(
    "ex-23-1-1",
    "23.1 · Môn thể thao",
    "People kick a ball into a goal in this sport.",
    "a",
    [
      { key: "a", label: "football" },
      { key: "b", label: "swimming" },
      { key: "c", label: "sailing" },
      { key: "d", label: "motor racing" },
    ],
  ),
  mcq(
    "ex-23-1-2",
    "23.1 · Môn thể thao",
    "People swim in water for this sport.",
    "b",
    [
      { key: "a", label: "volleyball" },
      { key: "b", label: "swimming" },
      { key: "c", label: "judo" },
      { key: "d", label: "baseball" },
    ],
  ),
  mcq(
    "ex-23-1-3",
    "23.1 · Môn thể thao",
    "People fight using judo or karate.",
    "c",
    [
      { key: "a", label: "sailing" },
      { key: "b", label: "swimming" },
      { key: "c", label: "judo / karate" },
      { key: "d", label: "volleyball" },
    ],
  ),
  mcq(
    "ex-23-1-4",
    "23.1 · Môn thể thao",
    "People race cars very fast in this sport.",
    "d",
    [
      { key: "a", label: "sailing" },
      { key: "b", label: "swimming" },
      { key: "c", label: "volleyball" },
      { key: "d", label: "motor racing" },
    ],
  ),
  mcq(
    "ex-23-1-5",
    "23.1 · Môn thể thao",
    "People hit a ball over a net on a beach or court.",
    "a",
    [
      { key: "a", label: "volleyball" },
      { key: "b", label: "skiing" },
      { key: "c", label: "motor racing" },
      { key: "d", label: "judo" },
    ],
  ),
  mcq(
    "ex-23-1-6",
    "23.1 · Môn thể thao",
    "People use a boat and the wind on the water.",
    "b",
    [
      { key: "a", label: "swimming" },
      { key: "b", label: "sailing" },
      { key: "c", label: "baseball" },
      { key: "d", label: "motor racing" },
    ],
  ),
  cloze("ex-23-2-1", "23.2 · Dụng cụ", "You need a racket and shuttlecock for ___.", "badminton", ["Badminton"]),
  cloze("ex-23-2-2", "23.2 · Dụng cụ", "You play ___ on a table with small bats.", "table tennis", ["Table tennis"]),
  cloze("ex-23-2-3", "23.2 · Dụng cụ", "You need skis for ___.", "skiing", ["Skiing"]),
  cloze("ex-23-2-4", "23.2 · Dụng cụ", "You throw and catch a ball with a glove in ___.", "baseball", ["Baseball"]),
  cloze("ex-23-2-5", "23.2 · Dụng cụ", "You shoot the ball into a hoop in ___.", "basketball", ["Basketball"]),
  cloze("ex-23-2-6", "23.2 · Dụng cụ", "You ride on snow with one board in ___.", "snowboarding", ["Snowboarding"]),
  cloze("ex-23-3-1", "23.3 · Câu hỏi", "___ you play football?", "Do", ["Do"]),
  cloze("ex-23-3-2", "23.3 · Câu hỏi", "___ you do any sports?", "Do", ["Do"]),
  cloze("ex-23-3-3", "23.3 · Câu hỏi", "___ you go swimming?", "Do", ["Do"]),
  cloze("ex-23-3-4", "23.3 · Câu hỏi", "___ is your favourite sport?", "What", ["What"]),
  cloze("ex-23-3-5", "23.3 · Câu hỏi", "Where ___ people play rugby?", "do", ["Do"]),
];

const UNIT_24: VocabularyExercise[] = [
  mcq(
    "ex-24-1-2",
    "24.1 · Thể loại phim",
    "A flying saucer lands from Mars.",
    "b",
    [
      { key: "a", label: "western" },
      { key: "b", label: "science fiction" },
      { key: "c", label: "comedy" },
      { key: "d", label: "musical" },
    ],
  ),
  mcq(
    "ex-24-1-3",
    "24.1 · Thể loại phim",
    "A dead person comes back to life.",
    "c",
    [
      { key: "a", label: "cartoon" },
      { key: "b", label: "romantic comedy" },
      { key: "c", label: "horror" },
      { key: "d", label: "musical" },
    ],
  ),
  mcq(
    "ex-24-1-4",
    "24.1 · Thể loại phim",
    "James Bond saves the world.",
    "d",
    [
      { key: "a", label: "comedy" },
      { key: "b", label: "western" },
      { key: "c", label: "horror" },
      { key: "d", label: "action" },
    ],
  ),
  mcq(
    "ex-24-1-5",
    "24.1 · Thể loại phim",
    "Mickey Mouse goes on a picnic.",
    "a",
    [
      { key: "a", label: "cartoon" },
      { key: "b", label: "thriller" },
      { key: "c", label: "action" },
      { key: "d", label: "western" },
    ],
  ),
  mcq(
    "ex-24-1-6",
    "24.1 · Thể loại phim",
    "A man falls in love with his teacher.",
    "b",
    [
      { key: "a", label: "horror" },
      { key: "b", label: "romantic comedy" },
      { key: "c", label: "science fiction" },
      { key: "d", label: "action" },
    ],
  ),
  mcq(
    "ex-24-1-7",
    "24.1 · Thể loại phim",
    "A dead body is found in the river.",
    "c",
    [
      { key: "a", label: "comedy" },
      { key: "b", label: "cartoon" },
      { key: "c", label: "thriller" },
      { key: "d", label: "musical" },
    ],
  ),
  mcq(
    "ex-24-1-8",
    "24.1 · Thể loại phim",
    "There are lots of songs and dancing.",
    "d",
    [
      { key: "a", label: "thriller" },
      { key: "b", label: "action" },
      { key: "c", label: "western" },
      { key: "d", label: "musical" },
    ],
  ),
  cloze("ex-24-3-1", "24.3 · Ô chữ", "A film that makes you feel afraid is a ___.", "thriller", ["Thriller", "horror", "Horror"]),
  cloze("ex-24-3-2", "24.3 · Ô chữ", "A film that makes you laugh is a ___.", "comedy", ["Comedy"]),
  cloze("ex-24-3-3", "24.3 · Ô chữ", "A film with lots of fighting and car chases is an ___ film.", "action", ["Action"]),
  cloze("ex-24-3-4", "24.3 · Ô chữ", "A film about the future and space is ___ fiction.", "science", ["Science"]),
  cloze("ex-24-3-5", "24.3 · Ô chữ", "A film with singing and dancing is a ___.", "musical", ["Musical"]),
  cloze("ex-24-3-6", "24.3 · Ô chữ", "An animated film for children is a ___.", "cartoon", ["Cartoon"]),
  cloze("ex-24-4-1", "24.4 · Hoàn thành câu", "We ___ a DVD last night.", "watched", ["Watched", "saw", "Saw"]),
  cloze("ex-24-4-2", "24.4 · Hoàn thành câu", "Daniel Radcliffe ___ Harry Potter in the Harry Potter films.", "played", ["Played"]),
  cloze("ex-24-4-3", "24.4 · Hoàn thành câu", "Monica Bellucci is a film ___.", "star", ["Star", "stars", "Stars"]),
  cloze("ex-24-4-4", "24.4 · Hoàn thành câu", "Steven Spielberg is a famous American film ___.", "director", ["Director"]),
  cloze("ex-24-4-5", "24.4 · Hoàn thành câu", "Was Rachel Weisz ___ The Constant Gardener?", "in", ["In"]),
];

const UNIT_25: VocabularyExercise[] = [
  // 25.1 in the book is picture-based ("What are these people doing?").
  // Scene hints replace pictures; blank keeps the activity phrase off the prompt.
  mcq(
    "ex-25-1-1",
    "25.1 · Hoạt động",
    "She's on the sofa with the remote control. She's ___.",
    "a",
    [
      { key: "a", label: "watching TV" },
      { key: "b", label: "reading a newspaper" },
      { key: "c", label: "cooking" },
      { key: "d", label: "gardening" },
    ],
  ),
  mcq(
    "ex-25-1-2",
    "25.1 · Hoạt động",
    "He's looking at today's paper. He's ___.",
    "b",
    [
      { key: "a", label: "listening to music" },
      { key: "b", label: "reading a newspaper" },
      { key: "c", label: "using the Internet" },
      { key: "d", label: "cooking" },
    ],
  ),
  mcq(
    "ex-25-1-3",
    "25.1 · Hoạt động",
    "He's in the kitchen with pans and food. He's ___.",
    "c",
    [
      { key: "a", label: "gardening" },
      { key: "b", label: "watching TV" },
      { key: "c", label: "cooking" },
      { key: "d", label: "chatting online" },
    ],
  ),
  mcq(
    "ex-25-1-4",
    "25.1 · Hoạt động",
    "She's at a laptop, browsing websites. She's ___.",
    "d",
    [
      { key: "a", label: "reading a novel" },
      { key: "b", label: "doing nothing" },
      { key: "c", label: "gardening" },
      { key: "d", label: "using the Internet" },
    ],
  ),
  mcq(
    "ex-25-1-5",
    "25.1 · Hoạt động",
    "She's wearing headphones. She's ___.",
    "a",
    [
      { key: "a", label: "listening to music" },
      { key: "b", label: "watching a DVD" },
      { key: "c", label: "cooking" },
      { key: "d", label: "reading a magazine" },
    ],
  ),
  mcq(
    "ex-25-1-6",
    "25.1 · Hoạt động",
    "He's outside with plants and flowers. He's ___.",
    "b",
    [
      { key: "a", label: "using the computer" },
      { key: "b", label: "gardening" },
      { key: "c", label: "listening to music" },
      { key: "d", label: "reading a newspaper" },
    ],
  ),
  cloze("ex-25-2-1", "25.2 · Động từ", "I usually ___ to music on my laptop at home.", "listen", ["Listen"]),
  cloze("ex-25-2-2", "25.2 · Động từ", "I like to ___ magazines more than newspapers.", "read", ["Read"]),
  cloze("ex-25-2-3", "25.2 · Động từ", "I ___ to my sister on the phone every Sunday.", "talk", ["Talk"]),
  cloze("ex-25-2-4", "25.2 · Động từ", "A lot of people like to ___ a sleep after lunch.", "have", ["Have"]),
  cloze("ex-25-2-5", "25.2 · Động từ", "Do you ever ___ friends to dinner?", "invite", ["Invite", "have", "Have"]),
  cloze("ex-25-2-6", "25.2 · Động từ", "The children ___ video games every evening.", "play", ["Play"]),
  cloze("ex-25-2-7", "25.2 · Động từ", "I want to ___ some music from the Internet this evening.", "download", ["Download"]),
  cloze("ex-25-2-8", "25.2 · Động từ", "Did you ___ the programme about Namibia yesterday?", "watch", ["Watch"]),
  cloze("ex-25-2-9", "25.2 · Động từ", "My dad ___ vegetables in his garden.", "grows", ["Grows"]),
  cloze("ex-25-2-10", "25.2 · Động từ", "Shall we ___ a DVD tonight?", "watch", ["Watch"]),
];

const UNIT_26: VocabularyExercise[] = [
  mcq(
    "ex-26-1-1",
    "26.1 · music / musical / musician",
    "What are your favourite types of ___?",
    "d",
    [
      { key: "a", label: "musician" },
      { key: "b", label: "musical" },
      { key: "c", label: "musicians" },
      { key: "d", label: "music" },
    ],
  ),
  mcq(
    "ex-26-1-2",
    "26.1 · music / musical / musician",
    "My brother thinks he's a good ___, but he's very bad!",
    "a",
    [
      { key: "a", label: "musician" },
      { key: "b", label: "music" },
      { key: "c", label: "musical" },
      { key: "d", label: "musicians" },
    ],
  ),
  mcq(
    "ex-26-1-3",
    "26.1 · music / musical / musician",
    "Can you play a ___ instrument?",
    "b",
    [
      { key: "a", label: "music" },
      { key: "b", label: "musical" },
      { key: "c", label: "musician" },
      { key: "d", label: "musics" },
    ],
  ),
  mcq(
    "ex-26-1-4",
    "26.1 · music / musical / musician",
    "I love different types of ___, for example, jazz, rock and classical.",
    "c",
    [
      { key: "a", label: "musical" },
      { key: "b", label: "musician" },
      { key: "c", label: "music" },
      { key: "d", label: "musicals" },
    ],
  ),
  mcq(
    "ex-26-1-5",
    "26.1 · music / musical / musician",
    "Are there any ___ in your family?",
    "d",
    [
      { key: "a", label: "music" },
      { key: "b", label: "musical" },
      { key: "c", label: "musics" },
      { key: "d", label: "musicians" },
    ],
  ),
  mcq(
    "ex-26-1-6",
    "26.1 · music / musical / musician",
    "The band played fantastic ___ for more than two hours.",
    "a",
    [
      { key: "a", label: "music" },
      { key: "b", label: "musics" },
      { key: "c", label: "musical" },
      { key: "d", label: "musician" },
    ],
  ),
  cloze("ex-26-2-1", "26.2 · Nhạc cụ", "Madison plays the ___ in an orchestra.", "cello", ["Cello"]),
  cloze("ex-26-2-2", "26.2 · Nhạc cụ", "Noah loves playing the ___.", "drums", ["Drums"]),
  cloze("ex-26-2-3", "26.2 · Nhạc cụ", "Emily is having a ___ lesson.", "piano", ["Piano"]),
  cloze("ex-26-2-4", "26.2 · Nhạc cụ", "Mason is a very good ___-player.", "trumpet", ["Trumpet"]),
  cloze("ex-26-2-5", "26.2 · Nhạc cụ", "Ella plays the ___ every evening.", "clarinet", ["Clarinet"]),
  cloze("ex-26-2-6", "26.2 · Nhạc cụ", "William plays the ___.", "guitar", ["Guitar"]),
  cloze("ex-26-2-7", "26.2 · Nhạc cụ", "Emma is learning the ___.", "flute", ["Flute"]),
  cloze("ex-26-2-8", "26.2 · Nhạc cụ", "Lucas is an excellent ___.", "violinist", ["Violinist"]),
  mcq(
    "ex-26-3-1",
    "26.3 · Loại nhạc",
    "I love ___ music. Beethoven is my favourite.",
    "b",
    [
      { key: "a", label: "classic" },
      { key: "b", label: "classical" },
      { key: "c", label: "classist" },
      { key: "d", label: "classics" },
    ],
  ),
  mcq(
    "ex-26-3-2",
    "26.3 · Loại nhạc",
    "My brother ___ folk music but I love it.",
    "a",
    [
      { key: "a", label: "can't stand" },
      { key: "b", label: "can stand" },
      { key: "c", label: "can't stay" },
      { key: "d", label: "can stand up" },
    ],
  ),
  mcq(
    "ex-26-3-3",
    "26.3 · Loại nhạc",
    "I have some tickets for a ___ at the Town Hall. Would you like one?",
    "c",
    [
      { key: "a", label: "concert music" },
      { key: "b", label: "music concert" },
      { key: "c", label: "concert" },
      { key: "d", label: "musical concert" },
    ],
  ),
  mcq(
    "ex-26-3-4",
    "26.3 · Loại nhạc",
    "Harper prefers ___ music.",
    "d",
    [
      { key: "a", label: "classical" },
      { key: "b", label: "opera" },
      { key: "c", label: "folk" },
      { key: "d", label: "pop" },
    ],
  ),
];

const UNIT_27: VocabularyExercise[] = [
  cloze("ex-27-1-1", "27.1 · Anagram", "H I N A C → ___", "China", ["China"]),
  cloze("ex-27-1-2", "27.1 · Anagram", "Z I R A L B → ___", "Brazil", ["Brazil"]),
  cloze("ex-27-1-3", "27.1 · Anagram", "P I N S A → ___", "Spain", ["Spain"]),
  cloze("ex-27-1-4", "27.1 · Anagram", "O C R M O O C → ___", "Morocco", ["Morocco"]),
  cloze("ex-27-1-5", "27.1 · Anagram", "A N J A P → ___", "Japan", ["Japan"]),
  cloze("ex-27-2-1", "27.2 · Thủ đô", "Rome is the capital of ___.", "Italy", ["Italy"]),
  cloze("ex-27-2-2", "27.2 · Thủ đô", "Canberra is the capital of ___.", "Australia", ["Australia"]),
  cloze("ex-27-2-3", "27.2 · Thủ đô", "Bogotá is the capital of ___.", "Colombia", ["Colombia"]),
  cloze("ex-27-2-4", "27.2 · Thủ đô", "Cairo is the capital of ___.", "Egypt", ["Egypt"]),
  cloze("ex-27-2-5", "27.2 · Thủ đô", "London is the capital of the ___.", "UK", ["UK"]),
  cloze("ex-27-2-6", "27.2 · Thủ đô", "Berlin is the capital of ___.", "Germany", ["Germany"]),
  mcq(
    "ex-27-3-1",
    "27.3 · Ngôn ngữ",
    "In Mexico, Spain and Chile they speak Spanish but in Brazil they speak ___.",
    "b",
    [
      { key: "a", label: "Spanish" },
      { key: "b", label: "Portuguese" },
      { key: "c", label: "English" },
      { key: "d", label: "French" },
    ],
  ),
  mcq(
    "ex-27-3-2",
    "27.3 · Ngôn ngữ",
    "In Austria, Germany and Switzerland they speak German but in Italy they speak ___.",
    "c",
    [
      { key: "a", label: "German" },
      { key: "b", label: "French" },
      { key: "c", label: "Italian" },
      { key: "d", label: "Spanish" },
    ],
  ),
  mcq(
    "ex-27-3-3",
    "27.3 · Ngôn ngữ",
    "In Morocco, Egypt and Saudi Arabia they speak Arabic but in China they speak ___.",
    "d",
    [
      { key: "a", label: "Arabic" },
      { key: "b", label: "French" },
      { key: "c", label: "Thai" },
      { key: "d", label: "Chinese" },
    ],
  ),
  mcq(
    "ex-27-3-4",
    "27.3 · Ngôn ngữ",
    "In Switzerland, Canada and France they speak French but in Scotland they speak ___.",
    "a",
    [
      { key: "a", label: "English" },
      { key: "b", label: "French" },
      { key: "c", label: "German" },
      { key: "d", label: "Scottish" },
    ],
  ),
  cloze("ex-27-4-1", "27.4 · Quốc tịch", "Someone from Thailand is ___.", "Thai", ["Thai"]),
  cloze("ex-27-4-2", "27.4 · Quốc tịch", "Someone from Germany is ___.", "German", ["German"]),
  cloze("ex-27-4-3", "27.4 · Quốc tịch", "Someone from Egypt is ___.", "Egyptian", ["Egyptian"]),
  cloze("ex-27-4-4", "27.4 · Quốc tịch", "Someone from Argentina is ___.", "Argentinian", ["Argentinian"]),
  cloze("ex-27-4-5", "27.4 · Quốc tịch", "Someone from Spain is ___.", "Spanish", ["Spanish"]),
];

const UNIT_28: VocabularyExercise[] = [
  match("ex-28-1", "28.1 · Ghép biểu tượng thời tiết", [
    { left: "snow", right: "white flakes from the sky" },
    { left: "sun", right: "bright and hot" },
    { left: "rain", right: "water falling from clouds" },
    { left: "fog", right: "cloud near the ground; hard to see" },
    { left: "lightning", right: "flash in the sky during a storm" },
    { left: "wind", right: "air moving fast" },
    { left: "cloud", right: "grey or white mass in the sky" },
  ]),
  cloze("ex-28-2-1", "28.2 · Thời tiết", "It is ___ in La Paz.", "windy", ["Windy"]),
  cloze("ex-28-2-2", "28.2 · Thời tiết", "It is ___ in Paris.", "cloudy", ["Cloudy"]),
  cloze("ex-28-2-3", "28.2 · Thời tiết", "It is ___ in Tashkent.", "foggy", ["Foggy"]),
  cloze("ex-28-2-4", "28.2 · Thời tiết", "It is ___ in Seoul.", "sunny", ["Sunny"]),
  cloze("ex-28-2-5", "28.2 · Thời tiết", "It is ___ in Washington.", "snowing", ["Snowing", "snowy", "Snowy"]),
  cloze("ex-28-3-1", "28.3 · Hoàn thành câu", "When it ___, I take my umbrella.", "rains", ["Rains"]),
  cloze("ex-28-3-2", "28.3 · Hoàn thành câu", "What's the ___ like in your country in January?", "weather", ["Weather"]),
  cloze("ex-28-3-3", "28.3 · Hoàn thành câu", "When it ___, we can go skiing.", "snows", ["Snows"]),
  cloze("ex-28-3-4", "28.3 · Hoàn thành câu", "It is 24 ___ here today.", "degrees", ["Degrees"]),
  cloze("ex-28-3-5", "28.3 · Hoàn thành câu", "It is dangerous to be in a small boat at sea in a ___.", "storm", ["Storm"]),
  cloze("ex-28-3-6", "28.3 · Hoàn thành câu", "You see ___ before you hear thunder.", "lightning", ["Lightning"]),
  cloze("ex-28-3-7", "28.3 · Hoàn thành câu", "It is very ___ in Siberia in winter.", "cold", ["Cold"]),
];

const UNIT_29: VocabularyExercise[] = [
  cloze("ex-29-1-1", "29.1 · Trong thị trấn", "Where can I get information about hotels? At the tourist information ___.", "office", [
    "Office",
  ]),
  cloze("ex-29-1-2", "29.1 · Trong thị trấn", "Where can I change money? At the ___.", "bank", ["Bank"]),
  cloze("ex-29-1-3", "29.1 · Trong thị trấn", "Where can I park my car? At the car ___.", "park", ["Park"]),
  cloze("ex-29-1-4", "29.1 · Trong thị trấn", "Where can I see old and interesting things? At the ___.", "museum", ["Museum"]),
  cloze("ex-29-1-5", "29.1 · Trong thị trấn", "Where can I get a train? At the train / railway ___.", "station", ["Station"]),
  cloze("ex-29-1-6", "29.1 · Trong thị trấn", "Where can I post a parcel? At the post ___.", "office", ["Office"]),
  mcq(
    "ex-29-2-1",
    "29.2 · Biển báo",
    "You want to leave the shopping centre. Which sign helps you?",
    "a",
    [
      { key: "a", label: "Exit" },
      { key: "b", label: "Entrance" },
      { key: "c", label: "No smoking" },
      { key: "d", label: "Out of order" },
    ],
  ),
  mcq(
    "ex-29-2-2",
    "29.2 · Biển báo",
    "You want to sit where there are no cigarettes.",
    "c",
    [
      { key: "a", label: "Exit" },
      { key: "b", label: "Entrance" },
      { key: "c", label: "No smoking" },
      { key: "d", label: "Please do not walk on the grass" },
    ],
  ),
  mcq(
    "ex-29-2-3",
    "29.2 · Biển báo",
    "You want to know if people can go on the grass.",
    "d",
    [
      { key: "a", label: "Exit" },
      { key: "b", label: "Entrance" },
      { key: "c", label: "No smoking" },
      { key: "d", label: "Please do not walk on the grass" },
    ],
  ),
  mcq(
    "ex-29-2-4",
    "29.2 · Biển báo",
    "You want to go into the museum.",
    "b",
    [
      { key: "a", label: "Exit" },
      { key: "b", label: "Entrance" },
      { key: "c", label: "No smoking" },
      { key: "d", label: "Out of order" },
    ],
  ),
  cloze("ex-29-3-1", "29.3 · Chỉ đường", "Turn right at the ___ of the road.", "end", ["End"]),
  cloze("ex-29-3-2", "29.3 · Chỉ đường", "The bus stop is over there on the ___.", "left", ["Left"]),
  cloze("ex-29-3-3", "29.3 · Chỉ đường", "For the Town Hall take the number 14 ___.", "bus", ["Bus"]),
  cloze("ex-29-3-4", "29.3 · Chỉ đường", "There is a post office on the other ___ of the road.", "side", ["Side"]),
  cloze("ex-29-3-5", "29.3 · Chỉ đường", "You can find a cash machine at the bank in High ___.", "Street", ["Street"]),
  cloze("ex-29-3-6", "29.3 · Chỉ đường", "Can you tell me the way to the railway ___, please?", "station", ["Station"]),
  cloze("ex-29-4-1", "29.4 · Anagram", "sumuem → ___", "museum", ["Museum"]),
  cloze("ex-29-4-2", "29.4 · Anagram", "nowt hlal → ___", "town hall", ["Town hall"]),
  cloze("ex-29-4-3", "29.4 · Anagram", "brilyra → ___", "library", ["Library"]),
  cloze("ex-29-4-4", "29.4 · Anagram", "rac prak → ___", "car park", ["Car park"]),
];

const UNIT_30: VocabularyExercise[] = [
  cloze("ex-30-1-1", "30.1 · Phong cảnh", "Tall rocky land that rises high is called ___.", "mountains", ["Mountains"]),
  cloze("ex-30-1-2", "30.1 · Phong cảnh", "A large area covered with trees is a ___.", "forest", ["Forest"]),
  cloze("ex-30-1-3", "30.1 · Phong cảnh", "Small raised areas of land are ___.", "hills", ["Hills"]),
  cloze("ex-30-1-4", "30.1 · Phong cảnh", "A small group of houses in the countryside is a ___.", "village", ["Village"]),
  cloze("ex-30-1-5", "30.1 · Phong cảnh", "Land used for growing crops is called ___.", "fields", ["Fields"]),
  cloze("ex-30-1-6", "30.1 · Phong cảnh", "A small area of water surrounded by land is a ___.", "lake", ["Lake"]),
  cloze("ex-30-1-7", "30.1 · Phong cảnh", "A narrow way for walking in the countryside is a ___.", "path", ["Path"]),
  cloze("ex-30-1-8", "30.1 · Phong cảnh", "Water flowing to the sea is a ___.", "river", ["River"]),
  cloze("ex-30-2-1", "30.2 · Nơi ở", "My brother is a farmer. He lives on a ___.", "farm", ["Farm"]),
  cloze("ex-30-2-2", "30.2 · Nơi ở", "It's not a big house; it's just a ___.", "cottage", ["Cottage"]),
  cloze("ex-30-2-3", "30.2 · Nơi ở", "The farm is near a ___ which has 800 people.", "village", ["Village"]),
  cloze("ex-30-2-4", "30.2 · Nơi ở", "Twenty kilometres from the village there is a small ___. It has 9,000 people.", "town", [
    "Town",
  ]),
  match("ex-30-3", "30.3 · Ghép hoạt động", [
    { left: "We went swimming", right: "in the lake" },
    { left: "We went walking", right: "along a five-kilometre path" },
    { left: "We went skiing", right: "down the mountain" },
    { left: "We saw some wonderful wildlife", right: "in the national park" },
    { left: "We had a picnic", right: "sitting by the river" },
  ]),
  mcq(
    "ex-30-4-1",
    "30.4 · the / không the",
    "Choose the correct sentence:",
    "b",
    [
      { key: "a", label: "My parents live in countryside." },
      { key: "b", label: "My parents live in the countryside." },
      { key: "c", label: "My parents live in the country side." },
      { key: "d", label: "My parents live at countryside." },
    ],
  ),
  mcq(
    "ex-30-4-2",
    "30.4 · the / không the",
    "Choose the correct sentence:",
    "a",
    [
      { key: "a", label: "He loves nature." },
      { key: "b", label: "He loves the nature." },
      { key: "c", label: "He loves a nature." },
      { key: "d", label: "He loves natures." },
    ],
  ),
  mcq(
    "ex-30-4-3",
    "30.4 · the / không the",
    "Choose the correct sentence:",
    "c",
    [
      { key: "a", label: "She wants to live in country." },
      { key: "b", label: "She wants to live in a country." },
      { key: "c", label: "She wants to live in the country." },
      { key: "d", label: "She wants to live at the country." },
    ],
  ),
  mcq(
    "ex-30-4-4",
    "30.4 · the / không the",
    "Choose the correct sentence:",
    "d",
    [
      { key: "a", label: "They are interested in the wildlife." },
      { key: "b", label: "They are interested in a wildlife." },
      { key: "c", label: "They are interested in wild life." },
      { key: "d", label: "They are interested in wildlife." },
    ],
  ),
];

export const CURATED_UNITS_16_30: Readonly<Partial<Record<number, readonly VocabularyExercise[]>>> = {
  16: UNIT_16,
  17: UNIT_17,
  18: UNIT_18,
  19: UNIT_19,
  20: UNIT_20,
  21: UNIT_21,
  22: UNIT_22,
  23: UNIT_23,
  24: UNIT_24,
  25: UNIT_25,
  26: UNIT_26,
  27: UNIT_27,
  28: UNIT_28,
  29: UNIT_29,
  30: UNIT_30,
};

for (const [unitNumber, exercises] of Object.entries(CURATED_UNITS_16_30)) {
  if (exercises) {
    assertExerciseCount(Number(unitNumber), exercises);
  }
}
