import type { VocabularyUnit } from "../vocabulary-unit-types";
import { ex, fillBlank, mcq, purple } from "./eviu-unit-builder";
import { preUnit, wordList } from "./eviu-pre-unit-helpers";

const U91_WORDS = wordList([
  ["carefully", "một cách cẩn thận, chú ý chi tiết", "Please read the instructions carefully.", "ADVERB"],
  ["efficiently", "một cách hiệu quả, ít tốn thời gian/công sức", "She manages her tasks efficiently.", "ADVERB"],
  ["clearly", "một cách rõ ràng, dễ hiểu", "Could you explain that clearly?", "ADVERB"],
  ["politely", "một cách lịch sự, nhã nhặn", "He politely asked for more time.", "ADVERB"],
  ["roughly", "một cách ước chừng, không chính xác hoàn toàn", "The meeting lasted roughly an hour.", "ADVERB"],
  ["barely", "hầu như không, chỉ vừa đủ", "I barely slept last night.", "ADVERB"],
  ["hardly ever", "hầu như không bao giờ", "We hardly ever eat fast food.", "ADVERB"],
  ["frequently", "thường xuyên, với tần suất cao", "This error occurs frequently.", "ADVERB"],
  ["occasionally", "thỉnh thoảng, không đều đặn", "I occasionally work from a cafe.", "ADVERB"],
  ["constantly", "liên tục, không ngừng", "The baby was constantly crying.", "ADVERB"],
  ["recently", "gần đây, trong thời gian vừa qua", "I recently changed my phone plan.", "ADVERB"],
  ["currently", "hiện tại, vào lúc này", "We are currently reviewing your application.", "ADVERB"],
  ["eventually", "cuối cùng sau một quá trình", "They eventually reached an agreement.", "ADVERB"],
  ["previously", "trước đó, vào thời điểm đã qua", "She had previously worked in marketing.", "ADVERB"],
  ["absolutely", "hoàn toàn, tuyệt đối", "I absolutely agree with your point.", "ADVERB"],
  ["fairly", "khá, tương đối", "The test was fairly difficult.", "ADVERB"],
  ["extremely", "cực kỳ, ở mức rất cao", "The room was extremely quiet.", "ADVERB"],
  ["almost", "gần như, suýt nữa", "I almost missed the last bus.", "ADVERB"],
]);

const U92_WORDS = wordList([
  ["first of all", "trước hết, điều đầu tiên cần nói", "First of all, let's define the problem."],
  ["subsequently", "sau đó, ở bước tiếp theo", "The data was cleaned and subsequently analyzed.", "ADVERB"],
  ["meanwhile", "trong khi đó, cùng lúc ở diễn biến khác", "I prepared dinner; meanwhile, he set the table.", "ADVERB"],
  ["simultaneously", "đồng thời, xảy ra cùng lúc", "Both systems were updated simultaneously.", "ADVERB"],
  ["afterwards", "sau đó, sau sự kiện vừa nêu", "We had coffee afterwards.", "ADVERB"],
  ["eventually", "cuối cùng sau nhiều bước/chờ đợi", "The team eventually solved the issue.", "ADVERB"],
  ["in the meantime", "trong lúc chờ đợi, tạm thời trước khi việc khác xảy ra", "The report will be ready tomorrow; in the meantime, review the draft."],
  ["at first", "ban đầu, lúc mới bắt đầu", "At first, I found the software confusing."],
  ["to begin with", "để bắt đầu, xét trước tiên", "To begin with, we need more evidence."],
  ["next", "tiếp theo trong trình tự", "Next, click the save button.", "ADVERB"],
  ["then", "sau đó theo thứ tự", "Finish step one, then continue.", "ADVERB"],
  ["finally", "cuối cùng ở bước kết", "Finally, submit your answer.", "ADVERB"],
  ["earlier", "sớm hơn, trước thời điểm nói đến", "I emailed you earlier today.", "ADVERB"],
  ["later on", "về sau, ở thời điểm muộn hơn", "We can discuss the details later on."],
  ["initially", "lúc đầu, ở giai đoạn đầu", "Initially, the project had a small budget.", "ADVERB"],
  ["ultimately", "rốt cuộc, xét đến cùng", "Ultimately, customer trust matters most.", "ADVERB"],
  ["beforehand", "trước đó, chuẩn bị từ sớm", "Please read the document beforehand.", "ADVERB"],
  ["from then on", "từ thời điểm đó trở đi", "From then on, we met every Friday."],
]);

const U93_WORDS = wordList([
  ["moreover", "hơn nữa, bổ sung ý theo hướng tăng cường", "The course is practical; moreover, it is affordable."],
  ["furthermore", "thêm vào đó, ngoài ra", "Furthermore, we should consider long-term costs."],
  ["in addition", "ngoài ra, bổ sung thêm thông tin", "In addition, the app supports offline mode."],
  ["besides", "hơn nữa, còn thêm một lý do/ý nữa", "Besides, we do not have enough time."],
  ["as well as", "cũng như, đồng thời với", "She speaks French as well as English."],
  ["not only ... but also", "không chỉ ... mà còn ...", "The update is not only faster but also more secure."],
  ["however", "tuy nhiên, chuyển sang ý đối lập", "The design looks good; however, it is hard to maintain."],
  ["nevertheless", "dù vậy, mặc dù thế", "The task was difficult; nevertheless, we finished it."],
  ["on the other hand", "mặt khác, xét ở khía cạnh đối lập", "Working remotely is flexible; on the other hand, it can feel isolating."],
  ["in contrast", "trái lại, đối chiếu khác biệt", "In contrast, the second method is simpler."],
  ["whereas", "trong khi đó, dùng để nêu hai ý trái nhau", "My sister likes cities, whereas I prefer small towns."],
  ["although", "mặc dù, dù cho", "Although it was raining, we went out."],
  ["even though", "mặc dù (nhấn mạnh hơn although)", "Even though he was tired, he kept working."],
  ["despite", "mặc cho, bất chấp", "Despite the delay, we arrived on time."],
  ["in spite of", "mặc dù, bất chấp", "In spite of the noise, she could focus."],
  ["instead", "thay vào đó, chọn phương án khác", "Let's email them instead.", "ADVERB"],
  ["alternatively", "hoặc là, như một lựa chọn khác", "Alternatively, we can split the task.", "ADVERB"],
  ["by contrast", "ngược lại, khi so sánh", "The old model was heavy; by contrast, this one is light."],
]);

const U94_WORDS = wordList([
  ["because of", "bởi vì, do nguyên nhân nào đó", "The match was canceled because of heavy rain."],
  ["due to", "do, vì (thường dùng văn viết trang trọng hơn)", "The delay was due to technical issues."],
  ["since", "vì, bởi vì", "Since traffic was bad, we left early."],
  ["therefore", "vì vậy, do đó", "The system was overloaded; therefore, response time increased."],
  ["as a result", "kết quả là", "Sales improved; as a result, we hired more staff."],
  ["consequently", "vì thế, hệ quả là", "He forgot the deadline; consequently, the report was late."],
  ["thus", "do đó, bởi vậy (trang trọng)", "The sample size was small, thus the conclusion is limited."],
  ["so that", "để mà, nhằm mục đích", "We left early so that we could avoid traffic."],
  ["in order to", "để, nhằm mục đích", "She took notes in order to remember key points."],
  ["for the purpose of", "với mục đích", "The data was collected for the purpose of training.", "NOUN"],
  ["if", "nếu, trong trường hợp", "If you need help, call me."],
  ["unless", "trừ khi, nếu không thì", "You won't pass unless you practice."],
  ["provided that", "với điều kiện là", "You can borrow the car provided that you drive carefully."],
  ["as long as", "miễn là", "You may stay as long as you are quiet."],
  ["in case", "phòng khi, để đề phòng", "Take an umbrella in case it rains."],
  ["otherwise", "nếu không thì, bằng không", "Submit today; otherwise, your request may be rejected.", "ADVERB"],
  ["so ... that", "quá ... đến mức mà", "The movie was so moving that she cried."],
  ["such ... that", "thật ... đến nỗi mà", "It was such a good idea that everyone agreed."],
]);

const U95_WORDS = wordList([
  ["formal register", "văn phong trang trọng dùng trong bối cảnh nghiêm túc", "Formal register is expected in job applications."],
  ["informal register", "văn phong thân mật trong giao tiếp gần gũi", "Informal register works better with close friends."],
  ["contraction", "dạng rút gọn như I'm, don't", "Avoid too many contractions in formal emails."],
  ["phrasal verb", "cụm động từ gồm động từ + tiểu từ/giới từ", "Phrasal verbs are common in spoken English."],
  ["slang", "từ lóng, cách nói không chuẩn mực", "That slang term is popular among teenagers."],
  ["colloquial", "mang tính khẩu ngữ đời thường", "The phrase sounds too colloquial for a report.", "ADJECTIVE"],
  ["neutral tone", "giọng điệu trung tính, không quá trang trọng hay suồng sã", "Use a neutral tone when writing to a new client."],
  ["polite expression", "cách diễn đạt lịch sự", "Please and thank you are basic polite expressions."],
  ["courtesy title", "danh xưng lịch sự như Mr, Ms, Dr", "Use the correct courtesy title in formal letters."],
  ["greeting line", "dòng chào mở đầu thư/email", "Choose an appropriate greeting line for the situation."],
  ["closing line", "dòng kết thư trước chữ ký", "The closing line should match the tone of your message."],
  ["appropriateness", "mức độ phù hợp với bối cảnh giao tiếp", "Appropriateness matters more than complexity.", "NOUN"],
  ["professional wording", "cách dùng từ chuyên nghiệp trong công việc", "Professional wording can build trust quickly."],
  ["casual wording", "cách diễn đạt tự nhiên, thoải mái", "Casual wording is fine in a family chat."],
  ["overly direct", "quá trực diện, dễ gây cảm giác thiếu lịch sự", "The sentence sounds overly direct.", "ADJECTIVE"],
  ["soften a request", "làm mềm lời yêu cầu để lịch sự hơn", "Could you possibly... can soften a request.", "VERB"],
  ["hedging language", "ngôn ngữ giảm mức khẳng định tuyệt đối", "Hedging language is useful in academic discussion."],
  ["tone mismatch", "lệch tông văn phong so với người nhận/bối cảnh", "A tone mismatch can create misunderstanding."],
]);

const U96_WORDS = wordList([
  ["application form", "mẫu đơn đăng ký thông tin", "Please complete the application form in block capitals."],
  ["personal details", "thông tin cá nhân cơ bản", "Enter your personal details accurately."],
  ["date of birth", "ngày tháng năm sinh", "Write your date of birth in the correct format."],
  ["nationality", "quốc tịch", "Nationality is required on this form."],
  ["contact number", "số điện thoại liên hệ", "Include a daytime contact number."],
  ["postal address", "địa chỉ bưu chính để nhận thư", "Your postal address must include the postcode."],
  ["postcode", "mã bưu chính khu vực", "Don't forget to add the postcode."],
  ["emergency contact", "người liên hệ khẩn cấp", "List one emergency contact on page two."],
  ["educational background", "quá trình học tập và bằng cấp", "Summarize your educational background clearly."],
  ["work experience", "kinh nghiệm làm việc", "Highlight relevant work experience first."],
  ["qualification", "trình độ/chứng chỉ đạt được", "This role requires a technical qualification."],
  ["reference", "người tham chiếu xác nhận năng lực", "Provide two references if possible."],
  ["referee", "người được nêu để xác nhận thông tin ứng viên", "Your referee should know your work well."],
  ["skills summary", "phần tóm tắt kỹ năng nổi bật", "Keep the skills summary concise and specific."],
  ["employment history", "lịch sử các công việc đã làm", "List your employment history in reverse order."],
  ["cover letter", "thư xin việc gửi kèm CV", "Attach a cover letter tailored to the role."],
  ["curriculum vitae", "sơ yếu lý lịch nghề nghiệp (CV)", "Your curriculum vitae should be easy to scan."],
  ["declare", "khai báo, xác nhận thông tin là đúng", "You must declare that all details are correct.", "VERB"],
]);

const U97_WORDS = wordList([
  ["essay question", "đề bài luận cần trả lời", "Read the essay question carefully before writing."],
  ["thesis statement", "câu nêu luận điểm chính của bài", "Your thesis statement should be specific."],
  ["introduction paragraph", "đoạn mở bài giới thiệu chủ đề và hướng triển khai", "Write the introduction paragraph after planning."],
  ["body paragraph", "đoạn thân bài phát triển một ý chính", "Each body paragraph needs one clear focus."],
  ["concluding paragraph", "đoạn kết luận tổng hợp ý chính", "The concluding paragraph should not add new ideas."],
  ["topic sentence", "câu chủ đề mở đầu đoạn văn", "Start each paragraph with a strong topic sentence."],
  ["supporting idea", "ý hỗ trợ để làm rõ luận điểm", "Add one supporting idea with evidence."],
  ["evidence", "dẫn chứng minh họa cho lập luận", "Use evidence from reliable sources."],
  ["argument", "lập luận thể hiện quan điểm có lý lẽ", "Your argument must stay focused."],
  ["counterargument", "lập luận phản biện với ý kiến đối lập", "Include a brief counterargument for balance."],
  ["coherence", "tính mạch lạc xuyên suốt bài viết", "Coherence improves when ideas are logically ordered."],
  ["cohesion", "sự liên kết giữa các câu/đoạn", "Linking words help cohesion.", "NOUN"],
  ["transition", "cụm chuyển ý giữa các phần", "Use transition phrases to guide readers."],
  ["outline", "dàn ý trước khi viết bài đầy đủ", "Create an outline before drafting.", "NOUN"],
  ["draft", "bản nháp ban đầu", "Finish your first draft quickly, then revise.", "NOUN"],
  ["revise", "chỉnh sửa lại nội dung và cấu trúc", "Revise your essay for clarity.", "VERB"],
  ["word limit", "giới hạn số lượng từ được phép", "Stay within the word limit."],
  ["academic tone", "văn phong học thuật, khách quan và chuẩn mực", "Avoid slang in an academic tone paragraph."],
]);

const U98_WORDS = wordList([
  ["Dear Sir or Madam", "cụm chào trang trọng khi chưa biết tên người nhận", "Begin with Dear Sir or Madam when no name is given."],
  ["To whom it may concern", "cách mở đầu trang trọng cho người nhận không cụ thể", "Use To whom it may concern in official references."],
  ["I am writing to", "cụm mở đầu nêu mục đích viết thư/email", "I am writing to inquire about your services."],
  ["with reference to", "liên quan đến, theo nội dung đã đề cập trước đó", "With reference to your email dated 5 May, ..."],
  ["I would appreciate", "tôi sẽ rất cảm kích nếu...", "I would appreciate your prompt response."],
  ["could you please", "xin vui lòng có thể ...", "Could you please confirm the appointment time?"],
  ["please find attached", "xin gửi kèm theo", "Please find attached the signed contract."],
  ["further information", "thông tin bổ sung thêm", "Let me know if you need further information."],
  ["at your earliest convenience", "khi thuận tiện sớm nhất có thể", "Please reply at your earliest convenience."],
  ["I look forward to", "tôi mong nhận được/được...", "I look forward to hearing from you."],
  ["Yours faithfully", "kết thư trang trọng khi không biết tên người nhận", "Use Yours faithfully after Dear Sir or Madam."],
  ["Yours sincerely", "kết thư trang trọng khi biết tên người nhận", "Use Yours sincerely when addressing a named person."],
  ["formal complaint", "thư khiếu nại theo phong cách trang trọng", "A formal complaint should stay factual."],
  ["official request", "đề nghị chính thức gửi cơ quan/tổ chức", "Submit an official request in writing."],
  ["enquiry", "thư hỏi thông tin (Anh-Anh)", "Send an enquiry before placing a large order."],
  ["acknowledgement", "thư/xác nhận đã nhận thông tin", "We sent an acknowledgement of receipt."],
  ["recipient", "người nhận thư/email", "Double-check the recipient before sending."],
  ["subject heading", "dòng tiêu đề chủ đề thư", "Use a clear subject heading for urgent matters."],
]);

const U99_WORDS = wordList([
  ["Hey", "chào thân mật mở đầu tin nhắn", "Hey, are you free this evening?"],
  ["How's it going?", "dạo này thế nào rồi?", "How's it going? I haven't seen you in weeks."],
  ["Just wanted to", "mở câu thân mật: chỉ muốn ...", "Just wanted to check if you're okay."],
  ["by the way", "nhân tiện, tiện thể nói thêm", "By the way, I found your book."],
  ["no worries", "không sao đâu, đừng lo", "No worries, we can reschedule."],
  ["sounds good", "nghe ổn đó, đồng ý", "Friday at 7 sounds good."],
  ["catch up", "gặp lại để cập nhật chuyện gần đây", "Let's catch up over coffee this weekend.", "VERB"],
  ["hang out", "đi chơi, dành thời gian cùng nhau", "Do you want to hang out after class?", "VERB"],
  ["talk soon", "nói chuyện lại sớm nhé", "I'm in a meeting now, talk soon."],
  ["take care", "giữ gìn nhé, chúc bình an", "Take care and get home safely."],
  ["cheers", "cảm ơn/bye thân mật (Anh-Anh)", "Cheers for helping me yesterday."],
  ["BTW", "viết tắt của by the way", "BTW, I sent you the file."],
  ["FYI", "viết tắt của for your information", "FYI, the class starts at 8:30."],
  ["ASAP", "viết tắt của as soon as possible", "Can you reply ASAP?"],
  ["emoji", "biểu tượng cảm xúc trong tin nhắn", "A smile emoji can soften the tone."],
  ["voice note", "tin nhắn thoại ghi âm ngắn", "I'll send a voice note later."],
  ["typing mistake", "lỗi gõ nhầm khi nhắn nhanh", "Sorry for the typing mistake."],
  ["autocorrect", "tính năng tự sửa chữ khi gõ", "Autocorrect changed the word again."],
]);

const U100_WORDS = wordList([
  ["abbreviation", "từ/cụm từ viết tắt", "Abbreviation is common in business writing."],
  ["acronym", "từ viết tắt đọc thành một từ hoàn chỉnh", "NATO is an acronym.", "NOUN"],
  ["initialism", "dạng viết tắt đọc từng chữ cái", "BBC is an initialism.", "NOUN"],
  ["etc.", "viết tắt của et cetera, nghĩa là v.v.", "Bring pens, paper, etc. to class."],
  ["e.g.", "viết tắt của for example, nghĩa là ví dụ", "Use renewable energy, e.g., wind and solar."],
  ["i.e.", "viết tắt của that is, nghĩa là tức là", "He is bilingual, i.e., he speaks two languages."],
  ["vs.", "viết tắt của versus, nghĩa là đối với/so với", "Today's topic is online learning vs. classroom learning."],
  ["approx.", "viết tắt của approximately, nghĩa là xấp xỉ", "The trip takes approx. 45 minutes."],
  ["dept.", "viết tắt của department, nghĩa là phòng/ban", "Please contact the HR dept. for details."],
  ["min.", "viết tắt của minute, nghĩa là phút", "Wait 10 min. before restarting."],
  ["hr", "viết tắt của hour, nghĩa là giờ", "The meeting lasted 1 hr."],
  ["kg", "viết tắt của kilogram", "The package weighs 2 kg."],
  ["cm", "viết tắt của centimeter", "The screen is 30 cm wide."],
  ["DOB", "viết tắt của date of birth", "Write your DOB clearly on the form."],
  ["ETA", "viết tắt của estimated time of arrival", "What's your ETA to the station?"],
  ["FAQ", "viết tắt của frequently asked questions", "Check the FAQ before contacting support."],
  ["ID", "viết tắt của identification", "Bring your ID to the exam room."],
  ["N/A", "viết tắt của not applicable / not available", "Write N/A if a field does not apply."],
]);

export const EVIU_PRE_UNITS_91_100: VocabularyUnit[] = [
  preUnit(91, {
    introVi: "Unit 91 tập trung vào trạng từ: cách thức, tần suất, mức độ và thời điểm. Bạn sẽ dùng trạng từ chính xác hơn để câu tiếng Anh tự nhiên, rõ nghĩa.",
    structureSections: [
      { label: "Adverbs of manner", wordCount: 6 },
      { label: "Frequency and time", wordCount: 6 },
      { label: "Degree and emphasis", wordCount: 6 },
    ],
    collocationHtml: `${purple("hardly ever")}, ${purple("currently")} và ${purple("extremely")} là các trạng từ rất hữu dụng trong giao tiếp và viết.`,
    mistakeHtml: "Đừng nhầm hardly với hard: hardly nghĩa là hầu như không, còn hard là chăm chỉ/khó khăn tùy ngữ cảnh.",
    principles: [
      {
        title: "Chọn đúng loại trạng từ theo ý muốn diễn đạt",
        body: `${purple("carefully")} thường chỉ cách thức, còn ${purple("frequently")} chỉ tần suất.`,
        examples: [ex("She drives carefully but checks her mirrors frequently.", "Cô ấy lái xe cẩn thận nhưng kiểm tra gương thường xuyên.")],
      },
      {
        title: "Dùng trạng từ mức độ để tăng giảm sắc thái",
        body: `${purple("fairly")} tạo mức vừa phải, ${purple("extremely")} nhấn mạnh mức rất cao.`,
        examples: [ex("The task was fairly easy, not extremely difficult.", "Nhiệm vụ khá dễ, không quá khó.")],
      },
      {
        title: "Ưu tiên trạng từ thời điểm để rõ mạch thời gian",
        body: `Các từ như ${purple("recently")}, ${purple("currently")} và ${purple("previously")} giúp người nghe theo dõi tiến trình.`,
        examples: [ex("I previously worked in sales and currently lead a small team.", "Trước đây tôi làm bán hàng và hiện đang dẫn dắt một nhóm nhỏ.")],
      },
    ],
    words: U91_WORDS,
    exercises: [
      mcq(
        91,
        1,
        "Từ nào có nghĩa là 'hầu như không bao giờ'?",
        [
          { key: "a", label: "constantly" },
          { key: "b", label: "hardly ever" },
          { key: "c", label: "efficiently" },
          { key: "d", label: "absolutely" },
        ],
        "b",
      ),
      fillBlank(
        91,
        2,
        "Please read the safety instructions ____ before using the machine.",
        "carefully",
        [
          { key: "a", label: "carefully" },
          { key: "b", label: "almost" },
          { key: "c", label: "roughly" },
          { key: "d", label: "occasionally" },
        ],
        "a",
      ),
    ],
  }),
  preUnit(92, {
    introVi: "Unit 92 mở rộng từ nối chỉ thời gian và trình tự. Mục tiêu là giúp bạn kể quy trình, mô tả diễn biến và viết bài có thứ tự rõ ràng.",
    structureSections: [
      { label: "Starting and sequencing", wordCount: 6 },
      { label: "Parallel and interval time", wordCount: 6 },
      { label: "Ending and timeline markers", wordCount: 6 },
    ],
    collocationHtml: `${purple("first of all")}, ${purple("in the meantime")} và ${purple("from then on")} giúp kết nối các bước mạch lạc.`,
    mistakeHtml: "Phân biệt eventually và finally: eventually nhấn mạnh quá trình lâu mới đạt kết quả, còn finally thường là bước cuối trong danh sách.",
    principles: [
      {
        title: "Mở đầu chuỗi hành động rõ ràng",
        body: `Bắt đầu bằng ${purple("first of all")} hoặc ${purple("to begin with")} để định hướng người nghe.`,
        examples: [ex("First of all, back up your files.", "Trước hết, hãy sao lưu tệp của bạn.")],
      },
      {
        title: "Dùng từ chỉ diễn biến đồng thời đúng ngữ cảnh",
        body: `${purple("meanwhile")} và ${purple("simultaneously")} đều nói về cùng lúc, nhưng simultaneously nhấn tính đồng thời chính xác hơn.`,
        examples: [ex("The two experiments were run simultaneously.", "Hai thí nghiệm được chạy đồng thời.")],
      },
      {
        title: "Chốt tiến trình bằng mốc thời gian kết thúc",
        body: `${purple("afterwards")}, ${purple("ultimately")} và ${purple("from then on")} giúp kết đoạn hoặc chuyển giai đoạn.`,
        examples: [ex("We had a short discussion afterwards.", "Sau đó chúng tôi có một cuộc thảo luận ngắn.")],
      },
    ],
    words: U92_WORDS,
    exercises: [
      mcq(
        92,
        1,
        "Cụm nào phù hợp nhất để mở đầu một quy trình?",
        [
          { key: "a", label: "first of all" },
          { key: "b", label: "from then on" },
          { key: "c", label: "afterwards" },
          { key: "d", label: "ultimately" },
        ],
        "a",
      ),
      fillBlank(
        92,
        2,
        "The report will be ready tomorrow. ____, please review the draft.",
        "In the meantime",
        [
          { key: "a", label: "In the meantime" },
          { key: "b", label: "From then on" },
          { key: "c", label: "At first" },
          { key: "d", label: "Beforehand" },
        ],
        "a",
      ),
    ],
  }),
  preUnit(93, {
    introVi: "Unit 93 tập trung từ nối bổ sung và tương phản. Bạn sẽ diễn đạt quan hệ ý tưởng rõ ràng hơn khi tranh luận, viết luận hoặc thuyết trình.",
    structureSections: [
      { label: "Adding information", wordCount: 6 },
      { label: "Contrasting ideas", wordCount: 6 },
      { label: "Alternatives and comparison", wordCount: 6 },
    ],
    collocationHtml: `${purple("in addition")}, ${purple("on the other hand")} và ${purple("by contrast")} là bộ từ nối quan trọng khi lập luận.`,
    mistakeHtml: "Despite và although không dùng cùng cấu trúc: despite + noun/gerund, còn although + mệnh đề.",
    principles: [
      {
        title: "Dùng từ nối bổ sung để mở rộng luận điểm",
        body: `${purple("moreover")}, ${purple("furthermore")} và ${purple("in addition")} đều thêm ý, nhưng moreover/furthermore thường trang trọng hơn.`,
        examples: [ex("The plan is low-cost; moreover, it is easy to deploy.", "Kế hoạch này chi phí thấp; hơn nữa, nó dễ triển khai.")],
      },
      {
        title: "Chọn liên từ tương phản theo mức độ đối lập",
        body: `${purple("however")} trung tính; ${purple("nevertheless")} nhấn mạnh việc vẫn xảy ra dù có trở ngại.`,
        examples: [ex("The weather was bad; nevertheless, the event continued.", "Thời tiết xấu; dù vậy, sự kiện vẫn tiếp tục.")],
      },
      {
        title: "Giữ cấu trúc ngữ pháp nhất quán khi nối câu",
        body: `${purple("whereas")} thường nối hai mệnh đề song song để đối chiếu rõ hơn.`,
        examples: [ex("My brother prefers tea, whereas I drink coffee.", "Anh tôi thích trà, trong khi tôi uống cà phê.")],
      },
    ],
    words: U93_WORDS,
    exercises: [
      mcq(
        93,
        1,
        "Từ nào phù hợp nhất để chuyển sang ý đối lập?",
        [
          { key: "a", label: "furthermore" },
          { key: "b", label: "as well as" },
          { key: "c", label: "however" },
          { key: "d", label: "moreover" },
        ],
        "c",
      ),
      fillBlank(
        93,
        2,
        "The apartment is small; ____, it is very comfortable.",
        "however",
        [
          { key: "a", label: "however" },
          { key: "b", label: "besides" },
          { key: "c", label: "not only ... but also" },
          { key: "d", label: "as well as" },
        ],
        "a",
      ),
    ],
  }),
  preUnit(94, {
    introVi: "Unit 94 phát triển nhóm từ nối cho lý do, mục đích, kết quả và điều kiện. Đây là nền tảng để viết câu phức và lập luận nguyên nhân-kết quả chính xác.",
    structureSections: [
      { label: "Reason and cause", wordCount: 5 },
      { label: "Purpose and result", wordCount: 7 },
      { label: "Condition patterns", wordCount: 6 },
    ],
    collocationHtml: `${purple("due to")}, ${purple("as a result")} và ${purple("provided that")} là các cụm dùng nhiều trong văn viết học thuật lẫn công việc.`,
    mistakeHtml: "Do not confuse because of (đi với danh từ/cụm danh từ) và because (đi với mệnh đề đầy đủ).",
    principles: [
      {
        title: "Phân biệt nguyên nhân và hệ quả",
        body: `${purple("because of")}/${purple("due to")} nêu nguyên nhân, còn ${purple("therefore")}/${purple("consequently")} nêu kết quả.`,
        examples: [ex("The road was flooded; therefore, the bus was delayed.", "Đường bị ngập; vì vậy xe buýt bị chậm.")],
      },
      {
        title: "Dùng cấu trúc mục đích tự nhiên",
        body: `${purple("so that")} và ${purple("in order to")} giúp làm rõ mục tiêu hành động.`,
        examples: [ex("She set an alarm so that she wouldn't oversleep.", "Cô ấy đặt báo thức để không ngủ quên.")],
      },
      {
        title: "Nêu điều kiện bằng mẫu câu phù hợp",
        body: `${purple("unless")}, ${purple("as long as")} và ${purple("provided that")} cần đi với ngữ cảnh điều kiện rõ ràng.`,
        examples: [ex("You can join us as long as you finish your work.", "Bạn có thể tham gia miễn là hoàn thành công việc.")],
      },
    ],
    words: U94_WORDS,
    exercises: [
      mcq(
        94,
        1,
        "Từ nào diễn đạt kết quả theo phong cách trang trọng?",
        [
          { key: "a", label: "if" },
          { key: "b", label: "therefore" },
          { key: "c", label: "in case" },
          { key: "d", label: "unless" },
        ],
        "b",
      ),
      fillBlank(
        94,
        2,
        "Take your charger ____ your phone battery runs out.",
        "in case",
        [
          { key: "a", label: "due to" },
          { key: "b", label: "in case" },
          { key: "c", label: "thus" },
          { key: "d", label: "provided that" },
        ],
        "b",
      ),
    ],
  }),
  preUnit(95, {
    introVi: "Unit 95 giúp bạn phân biệt tiếng Anh trang trọng và thân mật theo ngữ cảnh. Bạn sẽ điều chỉnh giọng điệu phù hợp khi viết email, báo cáo và trò chuyện.",
    structureSections: [
      { label: "Register and tone", wordCount: 6 },
      { label: "Politeness strategies", wordCount: 6 },
      { label: "Style mismatch awareness", wordCount: 6 },
    ],
    collocationHtml: `${purple("formal register")}, ${purple("professional wording")} và ${purple("tone mismatch")} là ba khái niệm trọng tâm của unit này.`,
    mistakeHtml: "Không phải câu càng dài càng trang trọng; điều quan trọng là từ chọn phù hợp bối cảnh và người nhận.",
    principles: [
      {
        title: "Bắt đầu bằng xác định bối cảnh giao tiếp",
        body: `Email công việc nên ưu tiên ${purple("formal register")} hoặc ${purple("neutral tone")}; chat bạn bè dùng ${purple("informal register")} hợp hơn.`,
        examples: [ex("A neutral tone is safer when writing to new clients.", "Giọng điệu trung tính an toàn hơn khi viết cho khách hàng mới.")],
      },
      {
        title: "Làm mềm yêu cầu để tăng tính hợp tác",
        body: `Các chiến lược như ${purple("soften a request")} hoặc dùng ${purple("polite expression")} giúp tránh cảm giác ra lệnh.`,
        examples: [ex("Could you please review this draft by Friday?", "Bạn có thể vui lòng xem bản nháp này trước thứ Sáu không?")],
      },
      {
        title: "Tránh lệch phong cách trong cùng một văn bản",
        body: `Kết hợp ${purple("slang")} với ${purple("courtesy title")} thường gây ${purple("tone mismatch")}.`,
        examples: [ex("Using 'Hey bro' in a formal complaint is inappropriate.", "Dùng 'Hey bro' trong thư khiếu nại trang trọng là không phù hợp.")],
      },
    ],
    words: U95_WORDS,
    exercises: [
      mcq(
        95,
        1,
        "Khái niệm nào chỉ sự phù hợp văn phong theo bối cảnh?",
        [
          { key: "a", label: "appropriateness" },
          { key: "b", label: "slang" },
          { key: "c", label: "contraction" },
          { key: "d", label: "phrasal verb" },
        ],
        "a",
      ),
      fillBlank(
        95,
        2,
        "In a message to your manager, avoid language that is too ____.",
        "colloquial",
        [
          { key: "a", label: "polite" },
          { key: "b", label: "professional" },
          { key: "c", label: "colloquial" },
          { key: "d", label: "neutral" },
        ],
        "c",
      ),
    ],
  }),
  preUnit(96, {
    introVi: "Unit 96 tập trung từ vựng điền biểu mẫu và viết CV. Bạn sẽ biết cách cung cấp thông tin chuẩn xác, rõ ràng và chuyên nghiệp khi ứng tuyển hoặc đăng ký.",
    structureSections: [
      { label: "Form fields", wordCount: 6 },
      { label: "CV sections", wordCount: 6 },
      { label: "Application documents", wordCount: 6 },
    ],
    collocationHtml: `${purple("personal details")}, ${purple("employment history")} và ${purple("cover letter")} là các phần gần như bắt buộc trong hồ sơ.`,
    mistakeHtml: "Referee là người xác nhận thông tin, còn reference thường là phần thông tin tham chiếu hoặc thư giới thiệu.",
    principles: [
      {
        title: "Điền form với định dạng nhất quán",
        body: `Các trường như ${purple("date of birth")}, ${purple("postcode")} và ${purple("contact number")} cần đúng chuẩn biểu mẫu.`,
        examples: [ex("Please enter your date of birth as DD/MM/YYYY.", "Vui lòng nhập ngày sinh theo định dạng DD/MM/YYYY.")],
      },
      {
        title: "Sắp xếp CV theo mức độ liên quan",
        body: `Đặt ${purple("skills summary")} và ${purple("work experience")} nổi bật ở đầu giúp nhà tuyển dụng đọc nhanh.`,
        examples: [ex("Her skills summary highlighted customer support and data analysis.", "Phần tóm tắt kỹ năng của cô ấy nhấn mạnh hỗ trợ khách hàng và phân tích dữ liệu.")],
      },
      {
        title: "Bảo đảm tính trung thực của thông tin",
        body: `Khi ký đơn bạn đang ${purple("declare")} rằng các mục trong ${purple("application form")} là chính xác.`,
        examples: [ex("Applicants must declare that the information is true.", "Ứng viên phải xác nhận thông tin là đúng sự thật.")],
      },
    ],
    words: U96_WORDS,
    exercises: [
      mcq(
        96,
        1,
        "Từ nào chỉ người xác nhận thông tin nghề nghiệp của bạn?",
        [
          { key: "a", label: "postcode" },
          { key: "b", label: "referee" },
          { key: "c", label: "cover letter" },
          { key: "d", label: "application form" },
        ],
        "b",
      ),
      fillBlank(
        96,
        2,
        "Always include your most relevant ____ at the top of your CV.",
        "work experience",
        [
          { key: "a", label: "date of birth" },
          { key: "b", label: "work experience" },
          { key: "c", label: "postcode" },
          { key: "d", label: "emergency contact" },
        ],
        "b",
      ),
    ],
  }),
  preUnit(97, {
    introVi: "Unit 97 xây nền tảng viết bài luận: lập dàn ý, phát triển luận điểm và chỉnh sửa bản nháp. Bạn sẽ viết có cấu trúc, mạch lạc và thuyết phục hơn.",
    structureSections: [
      { label: "Essay structure", wordCount: 6 },
      { label: "Argument development", wordCount: 6 },
      { label: "Editing and quality", wordCount: 6 },
    ],
    collocationHtml: `${purple("thesis statement")}, ${purple("body paragraph")} và ${purple("concluding paragraph")} là khung xương sống của một bài luận tốt.`,
    mistakeHtml: "Đừng biến kết luận thành đoạn lặp lại nguyên văn; hãy tổng hợp ý chính và chốt quan điểm một cách tự nhiên.",
    principles: [
      {
        title: "Lên kế hoạch trước khi viết đầy đủ",
        body: `Dùng ${purple("outline")} để xác định ${purple("topic sentence")} cho từng đoạn giúp tiết kiệm thời gian sửa.`,
        examples: [ex("I wrote a quick outline before drafting the essay.", "Tôi lập dàn ý nhanh trước khi viết nháp bài luận.")],
      },
      {
        title: "Mỗi đoạn thân bài cần một ý chính rõ",
        body: `Một ${purple("body paragraph")} hiệu quả thường có luận điểm, ${purple("supporting idea")} và ${purple("evidence")}.`,
        examples: [ex("Each body paragraph includes one claim and one piece of evidence.", "Mỗi đoạn thân bài gồm một luận điểm và một dẫn chứng.")],
      },
      {
        title: "Dành thời gian cho bước chỉnh sửa",
        body: `Sau khi hoàn thành ${purple("draft")}, hãy ${purple("revise")} để tăng ${purple("coherence")} và độ chính xác.`,
        examples: [ex("Revising improved the coherence of my essay.", "Việc chỉnh sửa giúp bài luận của tôi mạch lạc hơn.")],
      },
    ],
    words: U97_WORDS,
    exercises: [
      mcq(
        97,
        1,
        "Thành phần nào nêu rõ luận điểm trung tâm của bài luận?",
        [
          { key: "a", label: "topic sentence" },
          { key: "b", label: "thesis statement" },
          { key: "c", label: "word limit" },
          { key: "d", label: "transition" },
        ],
        "b",
      ),
      fillBlank(
        97,
        2,
        "Before writing full paragraphs, create an ____ to organize your ideas.",
        "outline",
        [
          { key: "a", label: "argument" },
          { key: "b", label: "draft" },
          { key: "c", label: "outline" },
          { key: "d", label: "counterargument" },
        ],
        "c",
      ),
    ],
  }),
  preUnit(98, {
    introVi: "Unit 98 tập trung thư và email trang trọng cho công việc/học tập. Bạn sẽ học cách mở thư, nêu mục đích, yêu cầu lịch sự và kết thư đúng chuẩn.",
    structureSections: [
      { label: "Formal openings", wordCount: 6 },
      { label: "Request and attachment language", wordCount: 6 },
      { label: "Closings and etiquette", wordCount: 6 },
    ],
    collocationHtml: `${purple("I am writing to")}, ${purple("please find attached")} và ${purple("Yours sincerely")} là bộ khung phổ biến của email trang trọng.`,
    mistakeHtml: "Yours faithfully dùng khi không biết tên người nhận; nếu biết tên, ưu tiên Yours sincerely.",
    principles: [
      {
        title: "Mở thư theo mức độ thông tin về người nhận",
        body: `Dùng ${purple("Dear Sir or Madam")} khi chưa có tên cụ thể, hoặc cụm ${purple("To whom it may concern")} cho văn bản chung.`,
        examples: [ex("To whom it may concern, I am writing to request a reference letter.", "Kính gửi bộ phận liên quan, tôi viết thư để xin thư giới thiệu.")],
      },
      {
        title: "Nêu mục đích và yêu cầu ngắn gọn, lịch sự",
        body: `${purple("with reference to")}, ${purple("I would appreciate")} và ${purple("could you please")} giúp giọng văn chuyên nghiệp.`,
        examples: [ex("Could you please confirm receipt of my documents?", "Anh/chị có thể vui lòng xác nhận đã nhận tài liệu của tôi không?")],
      },
      {
        title: "Kết thư đúng quy ước",
        body: `Kết bằng ${purple("I look forward to")} và chọn ${purple("Yours sincerely")} hoặc ${purple("Yours faithfully")} đúng tình huống.`,
        examples: [ex("I look forward to hearing from you. Yours sincerely,", "Tôi mong nhận được phản hồi từ anh/chị. Trân trọng,")],
      },
    ],
    words: U98_WORDS,
    exercises: [
      mcq(
        98,
        1,
        "Cụm nào dùng khi gửi kèm tài liệu trong email trang trọng?",
        [
          { key: "a", label: "by the way" },
          { key: "b", label: "please find attached" },
          { key: "c", label: "talk soon" },
          { key: "d", label: "no worries" },
        ],
        "b",
      ),
      fillBlank(
        98,
        2,
        "If you know the recipient's name, end the letter with ____.",
        "Yours sincerely",
        [
          { key: "a", label: "Yours sincerely" },
          { key: "b", label: "Yours faithfully" },
          { key: "c", label: "Cheers" },
          { key: "d", label: "Take care" },
        ],
        "a",
      ),
    ],
  }),
  preUnit(99, {
    introVi: "Unit 99 mở rộng ngôn ngữ email/tin nhắn thân mật. Bạn sẽ giao tiếp tự nhiên hơn với bạn bè, đồng nghiệp thân quen mà vẫn giữ rõ ràng và lịch sự.",
    structureSections: [
      { label: "Friendly openings", wordCount: 6 },
      { label: "Conversation flow", wordCount: 6 },
      { label: "Digital message habits", wordCount: 6 },
    ],
    collocationHtml: `${purple("How's it going?")}, ${purple("catch up")} và ${purple("talk soon")} là các cụm rất phổ biến trong tin nhắn đời thường.`,
    mistakeHtml: "Viết tắt như ASAP, FYI, BTW phù hợp chat thân mật; với bối cảnh trang trọng cần cân nhắc hoặc viết đầy đủ.",
    principles: [
      {
        title: "Mở đầu thân mật nhưng đúng đối tượng",
        body: `${purple("Hey")} hoặc ${purple("How's it going?")} phù hợp bạn bè; nên tránh khi gửi người lạ hoặc đối tác mới.`,
        examples: [ex("Hey, just wanted to ask about tomorrow's plan.", "Này, mình chỉ muốn hỏi về kế hoạch ngày mai.")],
      },
      {
        title: "Giữ hội thoại tự nhiên bằng cụm nối ngắn",
        body: `Các cụm như ${purple("by the way")}, ${purple("sounds good")} và ${purple("no worries")} giúp nhịp nhắn tin linh hoạt.`,
        examples: [ex("Sounds good. By the way, I'll be 10 minutes late.", "Nghe ổn đó. Nhân tiện, mình sẽ trễ 10 phút.")],
      },
      {
        title: "Tận dụng công cụ số nhưng kiểm soát sắc thái",
        body: `${purple("emoji")}, ${purple("voice note")} và ${purple("autocorrect")} tiện lợi, nhưng cần đọc lại để tránh ${purple("typing mistake")}.`,
        examples: [ex("Autocorrect caused a typing mistake, so I sent a quick correction.", "Tự sửa chữ gây lỗi gõ nên tôi gửi đính chính ngay.")],
      },
    ],
    words: U99_WORDS,
    exercises: [
      mcq(
        99,
        1,
        "Từ viết tắt nào nghĩa là 'for your information'?",
        [
          { key: "a", label: "ASAP" },
          { key: "b", label: "FYI" },
          { key: "c", label: "BTW" },
          { key: "d", label: "ID" },
        ],
        "b",
      ),
      fillBlank(
        99,
        2,
        "Let's ____ this weekend and talk about your new job.",
        "catch up",
        [
          { key: "a", label: "take care" },
          { key: "b", label: "catch up" },
          { key: "c", label: "talk soon" },
          { key: "d", label: "no worries" },
        ],
        "b",
      ),
    ],
  }),
  preUnit(100, {
    introVi: "Unit 100 tổng hợp từ viết tắt thường gặp trong học tập, công việc và giao tiếp số. Bạn sẽ hiểu cách đọc, cách dùng và tránh nhầm lẫn giữa các loại viết tắt.",
    structureSections: [
      { label: "Types of abbreviations", wordCount: 6 },
      { label: "Common written shortcuts", wordCount: 6 },
      { label: "Practical forms and labels", wordCount: 6 },
    ],
    collocationHtml: `${purple("abbreviation")}, ${purple("acronym")} và ${purple("initialism")} là ba khái niệm nền tảng cần phân biệt rõ.`,
    mistakeHtml: "Không phải viết tắt nào cũng dùng trong văn bản trang trọng; hãy ưu tiên dạng đầy đủ nếu bối cảnh yêu cầu rõ ràng tuyệt đối.",
    principles: [
      {
        title: "Phân biệt loại viết tắt theo cách đọc",
        body: `${purple("acronym")} thường đọc như một từ, còn ${purple("initialism")} đọc từng chữ cái.`,
        examples: [ex("BBC is an initialism, while NATO is an acronym.", "BBC là dạng đọc từng chữ cái, còn NATO là dạng đọc thành từ.")],
      },
      {
        title: "Dùng ký hiệu viết tắt đúng chức năng",
        body: `Các dạng như ${purple("e.g.")}, ${purple("i.e.")} và ${purple("etc.")} cần đặt đúng vị trí để tránh hiểu sai.`,
        examples: [ex("Use e.g. to give examples, i.e. to clarify meaning.", "Dùng e.g. để nêu ví dụ, i.e. để diễn giải rõ nghĩa.")],
      },
      {
        title: "Ưu tiên tính rõ ràng trong biểu mẫu và giao tiếp",
        body: `${purple("DOB")}, ${purple("ETA")} hay ${purple("N/A")} rất tiện, nhưng nên chắc người đọc hiểu cùng quy ước.`,
        examples: [ex("Write N/A if a section does not apply to you.", "Hãy ghi N/A nếu mục đó không áp dụng với bạn.")],
      },
    ],
    words: U100_WORDS,
    exercises: [
      mcq(
        100,
        1,
        "Khái niệm nào chỉ dạng viết tắt đọc từng chữ cái (ví dụ BBC)?",
        [
          { key: "a", label: "acronym" },
          { key: "b", label: "initialism" },
          { key: "c", label: "abbreviation" },
          { key: "d", label: "contraction" },
        ],
        "b",
      ),
      fillBlank(
        100,
        2,
        "If a field does not apply, write ____ on the form.",
        "N/A",
        [
          { key: "a", label: "DOB" },
          { key: "b", label: "ETA" },
          { key: "c", label: "N/A" },
          { key: "d", label: "FAQ" },
        ],
        "c",
      ),
    ],
  }),
];
