import { assertExerciseCount, cloze, match, mcq } from "./eviu-elementary-curated-helpers";
import type { VocabularyExercise } from "@/lib/vocabulary/vocabulary-unit-types";

const UNIT_61: VocabularyExercise[] = [
  match("ex-pre-61-1", "61 · Ghép từ với nghĩa", [
    { left: "dozen", right: "một tá, gồm mười hai đơn vị" },
    { left: "million", right: "một triệu" },
    { left: "percentage", right: "tỷ lệ phần trăm" },
    { left: "fraction", right: "phân số, phần nhỏ của tổng thể" },
    { left: "approximate", right: "xấp xỉ, gần đúng" },
    { left: "round down", right: "làm tròn xuống" },
  ]),
  cloze("ex-pre-61-2", "61 · Điền từ", "Please add one ___ to the amount.", "zero", ["Zero"]),
  cloze("ex-pre-61-3", "61 · Điền từ", "I bought a ___ of eggs this morning.", "dozen", ["Dozen"]),
  cloze("ex-pre-61-4", "61 · Điền từ", "Write the answer as a ___.", "decimal", ["Decimal"]),
  cloze("ex-pre-61-5", "61 · Điền từ", "I need the ___ number, not a guess.", "exact", ["Exact"]),
  cloze("ex-pre-61-6", "61 · Điền từ", "Seven is an ___ number.", "odd", ["Odd"]),
  cloze("ex-pre-61-7", "61 · Điền cụm", "You should ___ 4.6 to 5.", "round up", ["Round up"]),
  cloze("ex-pre-61-8", "61 · Điền từ", "Can you ___ the total quickly?", "calculate", ["Calculate"]),
  mcq("ex-pre-61-9", "61 · Chọn đáp án", "Which word means 'one billion'?", "c", [
    { key: "a", label: "million" },
    { key: "b", label: "thousand" },
    { key: "c", label: "billion" },
    { key: "d", label: "dozen" },
  ]),
  mcq("ex-pre-61-10", "61 · Chọn đáp án", "Which word means a small part of a whole?", "a", [
    { key: "a", label: "fraction" },
    { key: "b", label: "decimal" },
    { key: "c", label: "figure" },
    { key: "d", label: "zero" },
  ]),
  mcq("ex-pre-61-11", "61 · Chọn đáp án", "Which word means 'roughly, not exact'?", "d", [
    { key: "a", label: "exact" },
    { key: "b", label: "calculate" },
    { key: "c", label: "decimal" },
    { key: "d", label: "approximate" },
  ]),
  mcq("ex-pre-61-12", "61 · Chọn đáp án", "To ___ means to guess a number without calculating exactly.", "a", [
    { key: "a", label: "estimate" },
    { key: "b", label: "calculate" },
    { key: "c", label: "round up" },
    { key: "d", label: "figure" },
  ]),
  mcq("ex-pre-61-13", "61 · Chọn đáp án", "Which word means 'tỷ lệ phần trăm'?", "b", [
    { key: "a", label: "figure" },
    { key: "b", label: "percentage" },
    { key: "c", label: "fraction" },
    { key: "d", label: "decimal" },
  ]),
  mcq("ex-pre-61-14", "61 · Chọn đáp án", "We ___ 7.2 to 7.", "c", [
    { key: "a", label: "round up" },
    { key: "b", label: "calculate" },
    { key: "c", label: "round down" },
    { key: "d", label: "estimate" },
  ]),
];

const UNIT_62: VocabularyExercise[] = [
  match("ex-pre-62-1", "62 · Ghép từ với nghĩa", [
    { left: "distance", right: "khoảng cách giữa hai điểm" },
    { left: "width", right: "chiều rộng" },
    { left: "depth", right: "độ sâu" },
    { left: "diameter", right: "đường kính của hình tròn" },
    { left: "volume", right: "thể tích" },
    { left: "lightweight", right: "nhẹ cân, trọng lượng nhẹ" },
  ]),
  cloze("ex-pre-62-2", "62 · Điền từ", "We measured the table ___.", "length", ["Length"]),
  cloze("ex-pre-62-3", "62 · Điền từ", "What is your ___ in centimeters?", "height", ["Height"]),
  cloze("ex-pre-62-4", "62 · Điền từ", "The ___ of the pool is two meters.", "depth", ["Depth"]),
  cloze("ex-pre-62-5", "62 · Điền từ", "The ___ is half the diameter.", "radius", ["Radius"]),
  cloze("ex-pre-62-6", "62 · Điền từ", "We calculated the ___ of the room.", "area", ["Area"]),
  cloze("ex-pre-62-7", "62 · Điền từ", "The package ___ three kilos.", "weighs", ["Weighs", "weigh", "Weigh"]),
  cloze("ex-pre-62-8", "62 · Điền từ", "Metal can ___ in hot weather.", "expand", ["Expand"]),
  mcq("ex-pre-62-9", "62 · Chọn đáp án", "Which word means 'trọng lượng'?", "b", [
    { key: "a", label: "volume" },
    { key: "b", label: "weight" },
    { key: "c", label: "distance" },
    { key: "d", label: "area" },
  ]),
  mcq("ex-pre-62-10", "62 · Chọn đáp án", "Which word means 'rất nhỏ'?", "d", [
    { key: "a", label: "huge" },
    { key: "b", label: "heavy" },
    { key: "c", label: "lightweight" },
    { key: "d", label: "tiny" },
  ]),
  mcq("ex-pre-62-11", "62 · Chọn đáp án", "Wool clothes may ___ in hot water.", "a", [
    { key: "a", label: "shrink" },
    { key: "b", label: "expand" },
    { key: "c", label: "weigh" },
    { key: "d", label: "measure" },
  ]),
  mcq("ex-pre-62-12", "62 · Chọn đáp án", "The pizza has a ___ of 30 cm.", "c", [
    { key: "a", label: "radius" },
    { key: "b", label: "depth" },
    { key: "c", label: "diameter" },
    { key: "d", label: "width" },
  ]),
  mcq("ex-pre-62-13", "62 · Chọn đáp án", "Double-check each ___ before cutting.", "b", [
    { key: "a", label: "distance" },
    { key: "b", label: "measurement" },
    { key: "c", label: "volume" },
    { key: "d", label: "height" },
  ]),
  mcq("ex-pre-62-14", "62 · Chọn đáp án", "That box is too ___ to lift.", "a", [
    { key: "a", label: "heavy" },
    { key: "b", label: "lightweight" },
    { key: "c", label: "tiny" },
    { key: "d", label: "huge" },
  ]),
];

const UNIT_63: VocabularyExercise[] = [
  match("ex-pre-63-1", "63 · Ghép từ với nghĩa", [
    { left: "device", right: "thiết bị" },
    { left: "fabric", right: "vải, chất liệu dệt" },
    { left: "wooden", right: "làm bằng gỗ" },
    { left: "smooth", right: "mịn, trơn láng" },
    { left: "triangle", right: "hình tam giác" },
    { left: "curved", right: "cong, uốn cong" },
  ]),
  cloze("ex-pre-63-2", "63 · Điền từ", "Please move that heavy ___ carefully.", "object", ["Object"]),
  cloze("ex-pre-63-3", "63 · Điền từ", "What ___ is this jacket made of?", "material", ["Material"]),
  cloze("ex-pre-63-4", "63 · Điền từ", "The ___ feels soft and breathable.", "fabric", ["Fabric"]),
  cloze("ex-pre-63-5", "63 · Điền từ", "We bought a ___ chair.", "wooden", ["Wooden"]),
  cloze("ex-pre-63-6", "63 · Điền từ", "The surface is ___ to the touch.", "smooth", ["Smooth"]),
  cloze("ex-pre-63-7", "63 · Điền từ", "Draw a ___ in the center.", "circle", ["Circle"]),
  cloze("ex-pre-63-8", "63 · Điền từ", "The mirror is ___.", "rectangular", ["Rectangular"]),
  mcq("ex-pre-63-9", "63 · Chọn đáp án", "Which word means 'thô ráp, gồ ghề'?", "a", [
    { key: "a", label: "rough" },
    { key: "b", label: "smooth" },
    { key: "c", label: "metallic" },
    { key: "d", label: "curved" },
  ]),
  mcq("ex-pre-63-10", "63 · Chọn đáp án", "Which word means 'nhựa'?", "c", [
    { key: "a", label: "glass" },
    { key: "b", label: "fabric" },
    { key: "c", label: "plastic" },
    { key: "d", label: "wooden" },
  ]),
  mcq("ex-pre-63-11", "63 · Chọn đáp án", "A ___ has three sides.", "b", [
    { key: "a", label: "square" },
    { key: "b", label: "triangle" },
    { key: "c", label: "circle" },
    { key: "d", label: "object" },
  ]),
  mcq("ex-pre-63-12", "63 · Chọn đáp án", "I like this darker ___ of blue.", "d", [
    { key: "a", label: "material" },
    { key: "b", label: "fabric" },
    { key: "c", label: "equipment" },
    { key: "d", label: "shade" },
  ]),
  mcq("ex-pre-63-13", "63 · Chọn đáp án", "Which word means 'trang thiết bị, dụng cụ'?", "a", [
    { key: "a", label: "equipment" },
    { key: "b", label: "device" },
    { key: "c", label: "object" },
    { key: "d", label: "material" },
  ]),
  mcq("ex-pre-63-14", "63 · Chọn đáp án", "The market is full of ___ clothes.", "b", [
    { key: "a", label: "metallic" },
    { key: "b", label: "colourful" },
    { key: "c", label: "rough" },
    { key: "d", label: "rectangular" },
  ]),
];

const UNIT_64: VocabularyExercise[] = [
  match("ex-pre-64-1", "64 · Ghép từ với nghĩa", [
    { left: "container", right: "đồ chứa, vật đựng" },
    { left: "jar", right: "lọ, hũ" },
    { left: "packet", right: "gói nhỏ đóng sẵn" },
    { left: "spoonful", right: "một thìa đầy" },
    { left: "handful", right: "một nắm tay" },
    { left: "bulk", right: "khối lượng lớn" },
  ]),
  cloze("ex-pre-64-2", "64 · Điền từ", "She filled a ___ with water.", "bottle", ["Bottle"]),
  cloze("ex-pre-64-3", "64 · Điền từ", "There is honey in that ___.", "jar", ["Jar"]),
  cloze("ex-pre-64-4", "64 · Điền từ", "Can I have a ___ of bread?", "slice", ["Slice"]),
  cloze("ex-pre-64-5", "64 · Điền từ", "Add a ___ of lemon juice.", "drop", ["Drop"]),
  cloze("ex-pre-64-6", "64 · Điền từ", "He bought a ___ of bananas.", "bunch", ["Bunch"]),
  cloze("ex-pre-64-7", "64 · Điền từ", "Please ___ the bin before leaving.", "empty", ["Empty"]),
  cloze("ex-pre-64-8", "64 · Điền từ", "Could you ___ this bottle for me?", "fill", ["Fill"]),
  mcq("ex-pre-64-9", "64 · Chọn đáp án", "Which word means 'hộp giấy cứng, hộp đựng sữa'?", "c", [
    { key: "a", label: "box" },
    { key: "b", label: "can" },
    { key: "c", label: "carton" },
    { key: "d", label: "tube" },
  ]),
  mcq("ex-pre-64-10", "64 · Chọn đáp án", "Take a ___ of sugar.", "b", [
    { key: "a", label: "drop" },
    { key: "b", label: "spoonful" },
    { key: "c", label: "slice" },
    { key: "d", label: "piece" },
  ]),
  mcq("ex-pre-64-11", "64 · Chọn đáp án", "Buying in ___ saves money.", "d", [
    { key: "a", label: "load" },
    { key: "b", label: "bunch" },
    { key: "c", label: "packet" },
    { key: "d", label: "bulk" },
  ]),
  mcq("ex-pre-64-12", "64 · Chọn đáp án", "Give me one ___ of chocolate.", "a", [
    { key: "a", label: "piece" },
    { key: "b", label: "drop" },
    { key: "c", label: "tube" },
    { key: "d", label: "can" },
  ]),
  mcq("ex-pre-64-13", "64 · Chọn đáp án", "The truck carried a full ___.", "b", [
    { key: "a", label: "packet" },
    { key: "b", label: "load" },
    { key: "c", label: "slice" },
    { key: "d", label: "container" },
  ]),
  mcq("ex-pre-64-14", "64 · Chọn đáp án", "She squeezed toothpaste from the ___.", "c", [
    { key: "a", label: "carton" },
    { key: "b", label: "jar" },
    { key: "c", label: "tube" },
    { key: "d", label: "box" },
  ]),
];

const UNIT_65: VocabularyExercise[] = [
  match("ex-pre-65-1", "65 · Ghép từ với nghĩa", [
    { left: "apologize", right: "xin lỗi" },
    { left: "forgive", right: "tha thứ" },
    { left: "fault", right: "lỗi, trách nhiệm sai sót" },
    { left: "grateful", right: "cảm kích" },
    { left: "appreciate", right: "đánh giá cao, trân trọng" },
    { left: "no problem", right: "không sao đâu" },
  ]),
  cloze("ex-pre-65-2", "65 · Điền từ", "I ___ for arriving late.", "apologize", ["Apologize"]),
  cloze("ex-pre-65-3", "65 · Điền từ", "He offered a sincere ___.", "apology", ["Apology"]),
  cloze("ex-pre-65-4", "65 · Điền từ", "It was my ___, not yours.", "fault", ["Fault"]),
  cloze("ex-pre-65-5", "65 · Điền từ", "Please ___ my mistake.", "forgive", ["Forgive"]),
  cloze("ex-pre-65-6", "65 · Điền từ", "I really ___ your advice.", "appreciate", ["Appreciate"]),
  cloze("ex-pre-65-7", "65 · Điền cụm", "I will ___ to you.", "make it up to", ["Make it up to"]),
  cloze("ex-pre-65-8", "65 · Điền cụm", "___ for the confusion.", "I'm sorry", ["I'm sorry"]),
  mcq("ex-pre-65-9", "65 · Chọn đáp án", "Which phrase means 'xin phép / xin lỗi khi làm phiền'?", "b", [
    { key: "a", label: "I'm sorry" },
    { key: "b", label: "excuse me" },
    { key: "c", label: "no problem" },
    { key: "d", label: "thanks a lot" },
  ]),
  mcq("ex-pre-65-10", "65 · Chọn đáp án", "Which word means 'hối tiếc'?", "c", [
    { key: "a", label: "blame" },
    { key: "b", label: "forgive" },
    { key: "c", label: "regret" },
    { key: "d", label: "owe" },
  ]),
  mcq("ex-pre-65-11", "65 · Chọn đáp án", "Your explanation is ___.", "a", [
    { key: "a", label: "reasonable" },
    { key: "b", label: "fault" },
    { key: "c", label: "excuse" },
    { key: "d", label: "blame" },
  ]),
  mcq("ex-pre-65-12", "65 · Chọn đáp án", "I ___ you an apology.", "d", [
    { key: "a", label: "blame" },
    { key: "b", label: "regret" },
    { key: "c", label: "forgive" },
    { key: "d", label: "owe" },
  ]),
  mcq("ex-pre-65-13", "65 · Chọn đáp án", "Which word means 'biết ơn'?", "b", [
    { key: "a", label: "grateful" },
    { key: "b", label: "thankful" },
    { key: "c", label: "acceptable" },
    { key: "d", label: "reasonable" },
  ]),
  mcq("ex-pre-65-14", "65 · Chọn đáp án", "A ten-minute delay is ___.", "c", [
    { key: "a", label: "reasonable" },
    { key: "b", label: "grateful" },
    { key: "c", label: "acceptable" },
    { key: "d", label: "fault" },
  ]),
];

const UNIT_66: VocabularyExercise[] = [
  match("ex-pre-66-1", "66 · Ghép từ với nghĩa", [
    { left: "request", right: "đề nghị, yêu cầu lịch sự" },
    { left: "permission", right: "sự cho phép" },
    { left: "suggest", right: "đề xuất" },
    { left: "recommend", right: "khuyên dùng, đề nghị" },
    { left: "refuse", right: "từ chối" },
    { left: "how about", right: "thế còn... thì sao" },
  ]),
  cloze("ex-pre-66-2", "66 · Điền từ", "I sent a ___ for more details.", "request", ["Request"]),
  cloze("ex-pre-66-3", "66 · Điền cụm", "You can ___ a refund at the desk.", "ask for", ["Ask for"]),
  cloze("ex-pre-66-4", "66 · Điền từ", "They don't ___ phones in class.", "allow", ["Allow"]),
  cloze("ex-pre-66-5", "66 · Điền từ", "Please ___ me explain.", "let", ["Let"]),
  cloze("ex-pre-66-6", "66 · Điền từ", "I ___ this dictionary.", "recommend", ["Recommend"]),
  cloze("ex-pre-66-7", "66 · Điền từ", "I gladly ___ your invitation.", "accept", ["Accept"]),
  cloze("ex-pre-66-8", "66 · Điền cụm", "___ meeting at seven?", "How about", ["how about"]),
  mcq("ex-pre-66-9", "66 · Chọn đáp án", "Which phrase is a polite way to ask someone to do something?", "b", [
    { key: "a", label: "ask for" },
    { key: "b", label: "could you" },
    { key: "c", label: "refuse" },
    { key: "d", label: "deal" },
  ]),
  mcq("ex-pre-66-10", "66 · Chọn đáp án", "Which phrase means 'được phép làm gì'?", "c", [
    { key: "a", label: "ask for" },
    { key: "b", label: "would you mind" },
    { key: "c", label: "be allowed to" },
    { key: "d", label: "refuse" },
  ]),
  mcq("ex-pre-66-11", "66 · Chọn đáp án", "She ___ to sign the form.", "a", [
    { key: "a", label: "refused" },
    { key: "b", label: "accepted" },
    { key: "c", label: "offered" },
    { key: "d", label: "recommended" },
  ]),
  mcq("ex-pre-66-12", "66 · Chọn đáp án", "Which phrase means 'sao chúng ta không...'?", "d", [
    { key: "a", label: "how about" },
    { key: "b", label: "could you" },
    { key: "c", label: "it's a good idea" },
    { key: "d", label: "why don't we" },
  ]),
  mcq("ex-pre-66-13", "66 · Chọn đáp án", "Thanks for the useful ___.", "b", [
    { key: "a", label: "request" },
    { key: "b", label: "advice" },
    { key: "c", label: "permission" },
    { key: "d", label: "offer" },
  ]),
  mcq("ex-pre-66-14", "66 · Chọn đáp án", "Can you ___ with this request today?", "c", [
    { key: "a", label: "suggest" },
    { key: "b", label: "recommend" },
    { key: "c", label: "deal" },
    { key: "d", label: "refuse" },
  ]),
];

const UNIT_67: VocabularyExercise[] = [
  match("ex-pre-67-1", "67 · Ghép từ với nghĩa", [
    { left: "opinion", right: "ý kiến cá nhân" },
    { left: "agree", right: "đồng ý" },
    { left: "disagree", right: "không đồng ý" },
    { left: "evidence", right: "bằng chứng" },
    { left: "valid", right: "hợp lệ, có cơ sở" },
    { left: "on the other hand", right: "mặt khác" },
  ]),
  cloze("ex-pre-67-2", "67 · Điền từ", "Everyone has a different ___.", "opinion", ["Opinion"]),
  cloze("ex-pre-67-3", "67 · Điền cụm", "Try to see it from her ___.", "point of view", ["Point of view"]),
  cloze("ex-pre-67-4", "67 · Điền cụm", "___, this plan is practical.", "In my view", ["in my view"]),
  cloze("ex-pre-67-5", "67 · Điền từ", "I ___ with your suggestion.", "agree", ["Agree"]),
  cloze("ex-pre-67-6", "67 · Điền từ", "I ___ agree with you.", "completely", ["Completely"]),
  cloze("ex-pre-67-7", "67 · Điền từ", "Can you ___ them to join?", "convince", ["Convince"]),
  cloze("ex-pre-67-8", "67 · Điền từ", "We need ___ to support this claim.", "evidence", ["Evidence"]),
  mcq("ex-pre-67-9", "67 · Chọn đáp án", "Which phrase means 'thành thật mà nói'?", "a", [
    { key: "a", label: "to be honest" },
    { key: "b", label: "exactly" },
    { key: "c", label: "personally" },
    { key: "d", label: "fair point" },
  ]),
  mcq("ex-pre-67-10", "67 · Chọn đáp án", "Which word means 'một phần'?", "c", [
    { key: "a", label: "completely" },
    { key: "b", label: "exactly" },
    { key: "c", label: "partly" },
    { key: "d", label: "personally" },
  ]),
  mcq("ex-pre-67-11", "67 · Chọn đáp án", "That's a ___, thanks.", "d", [
    { key: "a", label: "argument" },
    { key: "b", label: "opinion" },
    { key: "c", label: "evidence" },
    { key: "d", label: "fair point" },
  ]),
  mcq("ex-pre-67-12", "67 · Chọn đáp án", "She presented a strong ___.", "b", [
    { key: "a", label: "opinion" },
    { key: "b", label: "argument" },
    { key: "c", label: "evidence" },
    { key: "d", label: "fair point" },
  ]),
  mcq("ex-pre-67-13", "67 · Chọn đáp án", "Which phrase means 'không hẳn vậy'?", "a", [
    { key: "a", label: "not really" },
    { key: "b", label: "exactly" },
    { key: "c", label: "completely" },
    { key: "d", label: "in my view" },
  ]),
  mcq("ex-pre-67-14", "67 · Chọn đáp án", "___, clear rules help.", "c", [
    { key: "a", label: "On the other hand" },
    { key: "b", label: "To be honest" },
    { key: "c", label: "From my experience" },
    { key: "d", label: "Not really" },
  ]),
];

const UNIT_68: VocabularyExercise[] = [
  match("ex-pre-68-1", "68 · Ghép từ với nghĩa", [
    { left: "prefer", right: "thích hơn, ưu tiên hơn" },
    { left: "favorite", right: "yêu thích nhất" },
    { left: "keen on", right: "rất thích, hứng thú với" },
    { left: "can't stand", right: "không thể chịu nổi" },
    { left: "don't mind", right: "không ngại" },
    { left: "would rather", right: "muốn ... hơn" },
  ]),
  cloze("ex-pre-68-2", "68 · Điền từ", "I ___ this new design.", "like", ["Like"]),
  cloze("ex-pre-68-3", "68 · Điền từ", "I ___ tea to coffee.", "prefer", ["Prefer"]),
  cloze("ex-pre-68-4", "68 · Điền từ", "Blue is my ___ color.", "favorite", ["Favorite"]),
  cloze("ex-pre-68-5", "68 · Điền từ", "We ___ walking after dinner.", "enjoy", ["Enjoy"]),
  cloze("ex-pre-68-6", "68 · Điền cụm", "I'm ___ graphic design.", "interested in", ["Interested in"]),
  cloze("ex-pre-68-7", "68 · Điền cụm", "I ___ loud noise.", "can't stand", ["Can't stand"]),
  cloze("ex-pre-68-8", "68 · Điền cụm", "I'd walk ___ drive.", "rather than", ["Rather than"]),
  mcq("ex-pre-68-9", "68 · Chọn đáp án", "Which phrase means 'rất mê, cực kỳ thích'?", "d", [
    { key: "a", label: "don't mind" },
    { key: "b", label: "fond of" },
    { key: "c", label: "prefer" },
    { key: "d", label: "be crazy about" },
  ]),
  mcq("ex-pre-68-10", "68 · Chọn đáp án", "Many users ___ long forms.", "b", [
    { key: "a", label: "love" },
    { key: "b", label: "dislike" },
    { key: "c", label: "enjoy" },
    { key: "d", label: "prefer" },
  ]),
  mcq("ex-pre-68-11", "68 · Chọn đáp án", "We have similar ___ in films.", "c", [
    { key: "a", label: "choice" },
    { key: "b", label: "preference" },
    { key: "c", label: "taste" },
    { key: "d", label: "favorite" },
  ]),
  mcq("ex-pre-68-12", "68 · Chọn đáp án", "I ___ stay home tonight.", "a", [
    { key: "a", label: "would rather" },
    { key: "b", label: "rather than" },
    { key: "c", label: "prefer" },
    { key: "d", label: "don't mind" },
  ]),
  mcq("ex-pre-68-13", "68 · Chọn đáp án", "My grandmother is ___ classical music.", "b", [
    { key: "a", label: "keen on" },
    { key: "b", label: "fond of" },
    { key: "c", label: "interested in" },
    { key: "d", label: "crazy about" },
  ]),
  mcq("ex-pre-68-14", "68 · Chọn đáp án", "You have a ___ between two options.", "a", [
    { key: "a", label: "choice" },
    { key: "b", label: "taste" },
    { key: "c", label: "preference" },
    { key: "d", label: "favorite" },
  ]),
];

const UNIT_69: VocabularyExercise[] = [
  match("ex-pre-69-1", "69 · Ghép từ với nghĩa", [
    { left: "greeting", right: "lời chào" },
    { left: "good morning", right: "chào buổi sáng" },
    { left: "nice to meet you", right: "rất vui được gặp bạn" },
    { left: "introduce", right: "giới thiệu" },
    { left: "take care", right: "giữ gìn nhé" },
    { left: "farewell", right: "lời chia tay trang trọng" },
  ]),
  cloze("ex-pre-69-2", "69 · Điền từ", "Please ___ the guests at the door.", "greet", ["Greet"]),
  cloze("ex-pre-69-3", "69 · Điền từ", "___ to our office.", "Welcome", ["welcome"]),
  cloze("ex-pre-69-4", "69 · Điền từ", "Let me ___ my colleague.", "introduce", ["Introduce"]),
  cloze("ex-pre-69-5", "69 · Điền cụm", "___ at last.", "Nice to meet you", ["Nice to meet you"]),
  cloze("ex-pre-69-6", "69 · Điền cụm", "___ tomorrow at class.", "See you", ["See you"]),
  cloze("ex-pre-69-7", "69 · Điền cụm", "___ on your way home.", "Take care", ["Take care"]),
  cloze("ex-pre-69-8", "69 · Điền cụm", "___ at work.", "Have a nice day", ["Have a nice day"]),
  mcq("ex-pre-69-9", "69 · Chọn đáp án", "Which greeting is informal?", "b", [
    { key: "a", label: "good morning" },
    { key: "b", label: "hi" },
    { key: "c", label: "good evening" },
    { key: "d", label: "farewell" },
  ]),
  mcq("ex-pre-69-10", "69 · Chọn đáp án", "Which phrase means 'chúc chuyến đi an toàn'?", "c", [
    { key: "a", label: "take care" },
    { key: "b", label: "see you later" },
    { key: "c", label: "safe trip" },
    { key: "d", label: "goodbye" },
  ]),
  mcq("ex-pre-69-11", "69 · Chọn đáp án", "They organized a ___ party.", "d", [
    { key: "a", label: "greeting" },
    { key: "b", label: "welcome" },
    { key: "c", label: "hello" },
    { key: "d", label: "farewell" },
  ]),
  mcq("ex-pre-69-12", "69 · Chọn đáp án", "___ today?", "a", [
    { key: "a", label: "How are you" },
    { key: "b", label: "See you" },
    { key: "c", label: "Take care" },
    { key: "d", label: "Goodbye" },
  ]),
  mcq("ex-pre-69-13", "69 · Chọn đáp án", "Which phrase means 'gặp lại sau nhé'?", "b", [
    { key: "a", label: "see you" },
    { key: "b", label: "see you later" },
    { key: "c", label: "hello" },
    { key: "d", label: "good morning" },
  ]),
  mcq("ex-pre-69-14", "69 · Chọn đáp án", "A warm ___ makes people comfortable.", "a", [
    { key: "a", label: "greeting" },
    { key: "b", label: "farewell" },
    { key: "c", label: "bye" },
    { key: "d", label: "introduce" },
  ]),
];

const UNIT_70: VocabularyExercise[] = [
  match("ex-pre-70-1", "70 · Ghép từ với nghĩa", [
    { left: "unhappy", right: "không vui" },
    { left: "misunderstand", right: "hiểu nhầm" },
    { left: "rewrite", right: "viết lại" },
    { left: "overcook", right: "nấu quá chín" },
    { left: "underpaid", right: "bị trả lương thấp" },
    { left: "co-worker", right: "đồng nghiệp" },
  ]),
  cloze("ex-pre-70-2", "70 · Điền từ", "The cause is still ___.", "unknown", ["Unknown"]),
  cloze("ex-pre-70-3", "70 · Điền từ", "I ___ your message.", "misunderstood", ["Misunderstood", "misunderstand", "Misunderstand"]),
  cloze("ex-pre-70-4", "70 · Điền từ", "Please ___ this paragraph.", "rewrite", ["Rewrite"]),
  cloze("ex-pre-70-5", "70 · Điền từ", "Let's ___ the final numbers.", "recheck", ["Recheck"]),
  cloze("ex-pre-70-6", "70 · Điền từ", "Don't ___ the vegetables.", "overcook", ["Overcook"]),
  cloze("ex-pre-70-7", "70 · Điền từ", "I ___ and missed the bus.", "overslept", ["Overslept", "oversleep", "Oversleep"]),
  cloze("ex-pre-70-8", "70 · Điền từ", "Don't ___ this task.", "underestimate", ["Underestimate"]),
  mcq("ex-pre-70-9", "70 · Chọn đáp án", "Which word has the prefix meaning 'not' or 'opposite'?", "a", [
    { key: "a", label: "disagree" },
    { key: "b", label: "rewrite" },
    { key: "c", label: "preview" },
    { key: "d", label: "coexist" },
  ]),
  mcq("ex-pre-70-10", "70 · Chọn đáp án", "Which word means 'trả trước'?", "c", [
    { key: "a", label: "underpaid" },
    { key: "b", label: "unknown" },
    { key: "c", label: "prepaid" },
    { key: "d", label: "overcook" },
  ]),
  mcq("ex-pre-70-11", "70 · Chọn đáp án", "We watched a ___ of the film.", "b", [
    { key: "a", label: "misprint" },
    { key: "b", label: "preview" },
    { key: "c", label: "rewrite" },
    { key: "d", label: "recheck" },
  ]),
  mcq("ex-pre-70-12", "70 · Chọn đáp án", "Different styles can ___.", "d", [
    { key: "a", label: "misunderstand" },
    { key: "b", label: "oversleep" },
    { key: "c", label: "dislike" },
    { key: "d", label: "coexist" },
  ]),
  mcq("ex-pre-70-13", "70 · Chọn đáp án", "This textbook has a ___.", "a", [
    { key: "a", label: "misprint" },
    { key: "b", label: "preview" },
    { key: "c", label: "subway" },
    { key: "d", label: "co-worker" },
  ]),
  mcq("ex-pre-70-14", "70 · Chọn đáp án", "He becomes ___ in large groups.", "c", [
    { key: "a", label: "unhappy" },
    { key: "b", label: "unknown" },
    { key: "c", label: "anti-social" },
    { key: "d", label: "underpaid" },
  ]),
];

const UNIT_71: VocabularyExercise[] = [
  match("ex-pre-71-1", "71 · Ghép từ với nghĩa", [
    { left: "happiness", right: "sự hạnh phúc" },
    { left: "friendship", right: "tình bạn" },
    { left: "leadership", right: "khả năng lãnh đạo" },
    { left: "teacher", right: "giáo viên" },
    { left: "decision", right: "quyết định" },
    { left: "ability", right: "khả năng" },
  ]),
  cloze("ex-pre-71-2", "71 · Điền từ", "Her ___ touched everyone.", "kindness", ["Kindness"]),
  cloze("ex-pre-71-3", "71 · Điền từ", "The room was in complete ___.", "darkness", ["Darkness"]),
  cloze("ex-pre-71-4", "71 · Điền từ", "Their ___ started in college.", "friendship", ["Friendship"]),
  cloze("ex-pre-71-5", "71 · Điền từ", "Gym ___ is paid monthly.", "membership", ["Membership"]),
  cloze("ex-pre-71-6", "71 · Điền từ", "The bus ___ was very patient.", "driver", ["Driver"]),
  cloze("ex-pre-71-7", "71 · Điền từ", "The ___ asked many smart questions.", "trainee", ["Trainee"]),
  cloze("ex-pre-71-8", "71 · Điền từ", "I checked the ___ twice.", "translation", ["Translation"]),
  mcq("ex-pre-71-9", "71 · Chọn đáp án", "Which word means 'khách tham quan'?", "c", [
    { key: "a", label: "employee" },
    { key: "b", label: "actor" },
    { key: "c", label: "visitor" },
    { key: "d", label: "trainee" },
  ]),
  mcq("ex-pre-71-10", "71 · Chọn đáp án", "That was a difficult ___.", "b", [
    { key: "a", label: "discussion" },
    { key: "b", label: "decision" },
    { key: "c", label: "activity" },
    { key: "d", label: "translation" },
  ]),
  mcq("ex-pre-71-11", "71 · Chọn đáp án", "Good ___ builds trust.", "a", [
    { key: "a", label: "leadership" },
    { key: "b", label: "friendship" },
    { key: "c", label: "membership" },
    { key: "d", label: "ability" },
  ]),
  mcq("ex-pre-71-12", "71 · Chọn đáp án", "Outdoor ___ improves mood.", "d", [
    { key: "a", label: "discussion" },
    { key: "b", label: "decision" },
    { key: "c", label: "translation" },
    { key: "d", label: "activity" },
  ]),
  mcq("ex-pre-71-13", "71 · Chọn đáp án", "There is no ___ about the result.", "b", [
    { key: "a", label: "ability" },
    { key: "b", label: "certainty" },
    { key: "c", label: "happiness" },
    { key: "d", label: "darkness" },
  ]),
  mcq("ex-pre-71-14", "71 · Chọn đáp án", "Every ___ must wear an ID card.", "a", [
    { key: "a", label: "employee" },
    { key: "b", label: "visitor" },
    { key: "c", label: "actor" },
    { key: "d", label: "driver" },
  ]),
];

const UNIT_72: VocabularyExercise[] = [
  match("ex-pre-72-1", "72 · Ghép từ với nghĩa", [
    { left: "useful", right: "hữu ích" },
    { left: "dangerous", right: "nguy hiểm" },
    { left: "natural", right: "tự nhiên" },
    { left: "rainy", right: "mưa nhiều, có mưa" },
    { left: "friendly", right: "thân thiện" },
    { left: "affordable", right: "có giá phải chăng" },
  ]),
  cloze("ex-pre-72-2", "72 · Điền từ", "This app is very ___ for students.", "useful", ["Useful"]),
  cloze("ex-pre-72-3", "72 · Điền từ", "Be ___ with that knife.", "careful", ["Careful"]),
  cloze("ex-pre-72-4", "72 · Điền từ", "The guide was ___.", "helpful", ["Helpful"]),
  cloze("ex-pre-72-5", "72 · Điền từ", "Da Nang is ___ for its beaches.", "famous", ["Famous"]),
  cloze("ex-pre-72-6", "72 · Điền từ", "I felt ___ before the interview.", "nervous", ["Nervous"]),
  cloze("ex-pre-72-7", "72 · Điền từ", "Tomorrow will be ___.", "sunny", ["Sunny"]),
  cloze("ex-pre-72-8", "72 · Điền từ", "These shoes are ___.", "comfortable", ["Comfortable"]),
  mcq("ex-pre-72-9", "72 · Chọn đáp án", "Which word means 'nguy hiểm'?", "b", [
    { key: "a", label: "natural" },
    { key: "b", label: "dangerous" },
    { key: "c", label: "friendly" },
    { key: "d", label: "useful" },
  ]),
  mcq("ex-pre-72-10", "72 · Chọn đáp án", "The sky is ___ this morning.", "d", [
    { key: "a", label: "rainy" },
    { key: "b", label: "sunny" },
    { key: "c", label: "windy" },
    { key: "d", label: "cloudy" },
  ]),
  mcq("ex-pre-72-11", "72 · Chọn đáp án", "This street is ___ at night.", "c", [
    { key: "a", label: "friendly" },
    { key: "b", label: "tasty" },
    { key: "c", label: "noisy" },
    { key: "d", label: "personal" },
  ]),
  mcq("ex-pre-72-12", "72 · Chọn đáp án", "Today is a ___ holiday.", "a", [
    { key: "a", label: "national" },
    { key: "b", label: "natural" },
    { key: "c", label: "personal" },
    { key: "d", label: "rainy" },
  ]),
  mcq("ex-pre-72-13", "72 · Chọn đáp án", "That soup is really ___.", "b", [
    { key: "a", label: "comfortable" },
    { key: "b", label: "tasty" },
    { key: "c", label: "windy" },
    { key: "d", label: "nervous" },
  ]),
  mcq("ex-pre-72-14", "72 · Chọn đáp án", "It's too ___ for a boat trip.", "c", [
    { key: "a", label: "cloudy" },
    { key: "b", label: "rainy" },
    { key: "c", label: "windy" },
    { key: "d", label: "sunny" },
  ]),
];

const UNIT_73: VocabularyExercise[] = [
  match("ex-pre-73-1", "73 · Ghép từ với nghĩa", [
    { left: "toothbrush", right: "bàn chải đánh răng" },
    { left: "hairdryer", right: "máy sấy tóc" },
    { left: "raincoat", right: "áo mưa" },
    { left: "headphones", right: "tai nghe chụp đầu" },
    { left: "sunrise", right: "bình minh" },
    { left: "credit card", right: "thẻ tín dụng" },
  ]),
  cloze("ex-pre-73-2", "73 · Điền từ", "I packed my ___ in a small bag.", "toothbrush", ["Toothbrush"]),
  cloze("ex-pre-73-3", "73 · Điền từ", "Buy a new tube of ___.", "toothpaste", ["Toothpaste"]),
  cloze("ex-pre-73-4", "73 · Điền từ", "Our ___ faces the garden.", "bedroom", ["Bedroom"]),
  cloze("ex-pre-73-5", "73 · Điền từ", "I wrote the idea in my ___.", "notebook", ["Notebook"]),
  cloze("ex-pre-73-6", "73 · Điền từ", "She wore ___ at the beach.", "sunglasses", ["Sunglasses"]),
  cloze("ex-pre-73-7", "73 · Điền từ", "My ___ is wireless.", "keyboard", ["Keyboard"]),
  cloze("ex-pre-73-8", "73 · Điền cụm", "Meet me at the ___.", "bus stop", ["Bus stop"]),
  mcq("ex-pre-73-9", "73 · Chọn đáp án", "Which compound noun means 'quán cà phê'?", "d", [
    { key: "a", label: "bookshop" },
    { key: "b", label: "bedroom" },
    { key: "c", label: "bus stop" },
    { key: "d", label: "coffee shop" },
  ]),
  mcq("ex-pre-73-10", "73 · Chọn đáp án", "The hotel room includes a ___.", "b", [
    { key: "a", label: "raincoat" },
    { key: "b", label: "hairdryer" },
    { key: "c", label: "sunrise" },
    { key: "d", label: "notebook" },
  ]),
  mcq("ex-pre-73-11", "73 · Chọn đáp án", "We're visiting my parents this ___.", "c", [
    { key: "a", label: "sunset" },
    { key: "b", label: "sunrise" },
    { key: "c", label: "weekend" },
    { key: "d", label: "bookshop" },
  ]),
  mcq("ex-pre-73-12", "73 · Chọn đáp án", "Almost everyone has a ___ now.", "a", [
    { key: "a", label: "smartphone" },
    { key: "b", label: "keyboard" },
    { key: "c", label: "toothbrush" },
    { key: "d", label: "raincoat" },
  ]),
  mcq("ex-pre-73-13", "73 · Chọn đáp án", "___ over the river was beautiful.", "b", [
    { key: "a", label: "Sunrise" },
    { key: "b", label: "Sunset" },
    { key: "c", label: "Weekend" },
    { key: "d", label: "Bathroom" },
  ]),
  mcq("ex-pre-73-14", "73 · Chọn đáp án", "Do you accept ___ payments?", "d", [
    { key: "a", label: "headphones" },
    { key: "b", label: "smartphone" },
    { key: "c", label: "notebook" },
    { key: "d", label: "credit card" },
  ]),
];

const UNIT_74: VocabularyExercise[] = [
  match("ex-pre-74-1", "74 · Ghép từ với nghĩa", [
    { left: "make a decision", right: "đưa ra quyết định" },
    { left: "take a break", right: "nghỉ giải lao" },
    { left: "pay attention", right: "chú ý" },
    { left: "keep calm", right: "giữ bình tĩnh" },
    { left: "keep in touch", right: "giữ liên lạc" },
    { left: "run out of", right: "hết, cạn kiệt" },
  ]),
  cloze("ex-pre-74-2", "74 · Điền cụm", "We need to ___ today.", "make a decision", ["Make a decision"]),
  cloze("ex-pre-74-3", "74 · Điền cụm", "Let's ___ after this section.", "take a break", ["Take a break"]),
  cloze("ex-pre-74-4", "74 · Điền cụm", "Could you ___ at this file?", "have a look", ["Have a look"]),
  cloze("ex-pre-74-5", "74 · Điền cụm", "I usually ___ after dinner.", "do homework", ["Do homework"]),
  cloze("ex-pre-74-6", "74 · Điền cụm", "We must ___ at 6:30.", "catch a bus", ["Catch a bus"]),
  cloze("ex-pre-74-7", "74 · Điền cụm", "Please ___ to the instructions.", "pay attention", ["Pay attention"]),
  cloze("ex-pre-74-8", "74 · Điền cụm", "Try to ___ during the exam.", "keep calm", ["Keep calm"]),
  mcq("ex-pre-74-9", "74 · Chọn đáp án", "Which collocation means 'tiết kiệm thời gian'?", "b", [
    { key: "a", label: "waste money" },
    { key: "b", label: "save time" },
    { key: "c", label: "take a break" },
    { key: "d", label: "miss a chance" },
  ]),
  mcq("ex-pre-74-10", "74 · Chọn đáp án", "You should ___.", "c", [
    { key: "a", label: "break a promise" },
    { key: "b", label: "waste money" },
    { key: "c", label: "tell the truth" },
    { key: "d", label: "run out of" },
  ]),
  mcq("ex-pre-74-11", "74 · Chọn đáp án", "He never ___.", "a", [
    { key: "a", label: "breaks a promise" },
    { key: "b", label: "takes a break" },
    { key: "c", label: "pays attention" },
    { key: "d", label: "catches a bus" },
  ]),
  mcq("ex-pre-74-12", "74 · Chọn đáp án", "Set an ___ for 5 a.m.", "b", [
    { key: "a", label: "goal" },
    { key: "b", label: "alarm" },
    { key: "c", label: "break" },
    { key: "d", label: "chance" },
  ]),
  mcq("ex-pre-74-13", "74 · Chọn đáp án", "Leaders should ___.", "d", [
    { key: "a", label: "miss a chance" },
    { key: "b", label: "waste money" },
    { key: "c", label: "run out of" },
    { key: "d", label: "take responsibility" },
  ]),
  mcq("ex-pre-74-14", "74 · Chọn đáp án", "We've ___ milk.", "c", [
    { key: "a", label: "saved time" },
    { key: "b", label: "kept calm" },
    { key: "c", label: "run out of" },
    { key: "d", label: "kept in touch" },
  ]),
];

const UNIT_75: VocabularyExercise[] = [
  match("ex-pre-75-1", "75 · Ghép từ với nghĩa", [
    { left: "as soon as possible", right: "càng sớm càng tốt" },
    { left: "by the way", right: "nhân tiện, tiện thể" },
    { left: "at least", right: "ít nhất" },
    { left: "on time", right: "đúng giờ" },
    { left: "in the end", right: "cuối cùng (kết quả sau cùng)" },
    { left: "all of a sudden", right: "đột nhiên" },
  ]),
  cloze("ex-pre-75-2", "75 · Điền cụm", "Please reply ___.", "as soon as possible", ["As soon as possible"]),
  cloze("ex-pre-75-3", "75 · Điền cụm", "___, your package arrived.", "By the way", ["by the way"]),
  cloze("ex-pre-75-4", "75 · Điền cụm", "___, we finished earlier than planned.", "In fact", ["In fact", "in fact"]),
  cloze("ex-pre-75-5", "75 · Điền cụm", "Bring ___ two copies.", "at least", ["At least"]),
  cloze("ex-pre-75-6", "75 · Điền cụm", "___, I didn't understand the task.", "At first", ["At first", "at first"]),
  cloze("ex-pre-75-7", "75 · Điền cụm", "The train arrived ___.", "on time", ["On time"]),
  cloze("ex-pre-75-8", "75 · Điền cụm", "We reached the station ___.", "in time", ["In time"]),
  mcq("ex-pre-75-9", "75 · Chọn đáp án", "Which phrase means 'thỉnh thoảng'?", "a", [
    { key: "a", label: "from time to time" },
    { key: "b", label: "at the moment" },
    { key: "c", label: "in the end" },
    { key: "d", label: "as usual" },
  ]),
  mcq("ex-pre-75-10", "75 · Chọn đáp án", "___, we chose option B.", "c", [
    { key: "a", label: "At first" },
    { key: "b", label: "For now" },
    { key: "c", label: "In the end" },
    { key: "d", label: "By the way" },
  ]),
  mcq("ex-pre-75-11", "75 · Chọn đáp án", "Which phrase means 'nói cách khác'?", "d", [
    { key: "a", label: "in fact" },
    { key: "b", label: "for example" },
    { key: "c", label: "by the way" },
    { key: "d", label: "in other words" },
  ]),
  mcq("ex-pre-75-12", "75 · Chọn đáp án", "She didn't delete the file ___.", "a", [
    { key: "a", label: "on purpose" },
    { key: "b", label: "on time" },
    { key: "c", label: "in time" },
    { key: "d", label: "as usual" },
  ]),
  mcq("ex-pre-75-13", "75 · Chọn đáp án", "He arrived early ___.", "d", [
    { key: "a", label: "in fact" },
    { key: "b", label: "for now" },
    { key: "c", label: "at first" },
    { key: "d", label: "as usual" },
  ]),
  mcq("ex-pre-75-14", "75 · Chọn đáp án", "Which phrase means 'thành thật mà nói'?", "b", [
    { key: "a", label: "by the way" },
    { key: "b", label: "to be honest" },
    { key: "c", label: "for example" },
    { key: "d", label: "at least" },
  ]),
];

export const CURATED_PRE_UNITS_61_75: Readonly<Partial<Record<number, readonly VocabularyExercise[]>>> = {
  61: UNIT_61,
  62: UNIT_62,
  63: UNIT_63,
  64: UNIT_64,
  65: UNIT_65,
  66: UNIT_66,
  67: UNIT_67,
  68: UNIT_68,
  69: UNIT_69,
  70: UNIT_70,
  71: UNIT_71,
  72: UNIT_72,
  73: UNIT_73,
  74: UNIT_74,
  75: UNIT_75,
};

for (const [unitNumber, exercises] of Object.entries(CURATED_PRE_UNITS_61_75)) {
  if (exercises) {
    assertExerciseCount(Number(unitNumber), exercises);
  }
}
