import type { VocabularyUnit } from "@/lib/vocabulary/vocabulary-unit-types";
import {
  bold,
  ex,
  fillBlank,
  mcq,
  purple,
} from "@/lib/vocabulary/units/eviu-unit-builder";
import { advancedUnit, wordList } from "@/lib/vocabulary/units/eviu-advanced-unit-helpers";

const U1_WORDS = wordList([
  ["composition", "bài viết ngắn (thường bài tập trường)", "The teacher asked for a 200-word composition.", "NOUN"],
  ["assignment", "bài luận dài, thường là một phần khóa học", "She spent weeks on her final assignment.", "NOUN"],
  ["project", "đề tài tự chọn, nhấn mạnh ý tưởng của sinh viên", "His project combined field research with interviews.", "NOUN"],
  ["portfolio", "tập hợp các bài làm cá nhân", "Art students submit a portfolio of drawings and essays.", "NOUN"],
  ["mind map", "sơ đồ tư duy liên kết các ý chính", "Start your essay with a mind map on paper.", "NOUN"],
  ["first draft", "bản nháp đầu tiên", "Never submit your first draft without revising it.", "NOUN"],
  ["plagiarism", "đạo văn, dùng bài người khác như của mình", "The university treats plagiarism as a serious offence.", "NOUN"],
  ["cram", "nhồi nhét kiến thức trong thời gian ngắn", "Some students cram the night before finals.", "VERB"],
  ["revision", "ôn tập trước kỳ thi", "Revision is easier if you spread it over several weeks.", "NOUN"],
  ["past papers", "đề thi các năm trước", "Past papers show how exam questions are phrased.", "PHRASE"],
  ["by heart", "thuộc lòng", "She learnt the poem by heart for the recital.", "PHRASE"],
  ["rote-learning", "học vẹt, học thuộc lòng không hiểu", "Rote-learning alone is not enough for essay subjects.", "NOUN"],
  ["mnemonics", "mẹo ghi nhớ", "The rhyme is a useful mnemonic for spelling rules.", "NOUN"],
  ["inside out", "nắm rất kỹ, thuộc từng chi tiết", "He knows the subject inside out after months of study.", "PHRASE"],
  ["academic journal", "tạp chí học thuật", "Researchers publish findings in academic journals.", "NOUN"],
  ["inter-library loan", "mượn sách giữa các thư viện", "I ordered the book through inter-library loan.", "NOUN"],
  ["open educational resources", "tài liệu giáo dục mở, dùng tự do", "Open educational resources save students money.", "PHRASE"],
  ["drop out", "bỏ học giữa chừng", "Stress caused several classmates to drop out.", "VERB"],
  ["finals", "kỳ thi cuối khóa đại học", "She revised hard for her finals in June.", "NOUN"],
  ["well-qualified", "có trình độ chuyên môn tốt", "Graduates should leave university well-qualified.", "ADJECTIVE"],
  ["acknowledge", "ghi nhận nguồn tham khảo", "You must acknowledge every source you use.", "VERB"],
  ["intensively", "một cách tập trung cao độ", "She studied intensively for two weeks.", "ADVERB"],
]);

const U2_WORDS = wordList([
  ["equality of opportunity", "cơ hội bình đẳng trong giáo dục", "Debate often centres on equality of opportunity.", "PHRASE"],
  ["selective schooling", "hệ thống trường tuyển chọn học sinh", "Selective schooling favours high academic scores.", "PHRASE"],
  ["comprehensive schooling", "hệ thống trường không tuyển chọn", "Comprehensive schooling aims to serve every child.", "PHRASE"],
  ["elitism", "chủ nghĩa tinh hoa, ưu tiên nhóm đặc quyền", "Critics say elitism is built into the system.", "NOUN"],
  ["league tables", "bảng xếp hạng trường theo điểm thi", "League tables rank schools from best to worst.", "PHRASE"],
  ["two-tier system", "hệ thống hai tầng (tốt và kém)", "League tables can create a two-tier system.", "PHRASE"],
  ["well-endowed", "được tài trợ dồi dào", "Well-endowed schools attract more resources.", "ADJECTIVE"],
  ["bursary", "học bổng theo hoàn cảnh kinh tế", "A bursary helped her afford tertiary education.", "NOUN"],
  ["tertiary education", "giáo dục đại học, cao đẳng", "Tertiary education should not depend on wealth.", "PHRASE"],
  ["literacy", "khả năng đọc viết", "Literacy programmes target early learners.", "NOUN"],
  ["numeracy", "khả năng tính toán cơ bản", "Numeracy skills matter in everyday life.", "NOUN"],
  ["curriculum reform", "cải cách chương trình giảng dạy", "Curriculum reform is often driven by politics.", "PHRASE"],
  ["lifelong education", "học tập suốt đời", "Lifelong education keeps workers adaptable.", "PHRASE"],
  ["mature student", "sinh viên lớn tuổi hơn trung bình", "Mature students bring real-world experience to class.", "NOUN"],
  ["special needs education", "giáo dục cho học sinh có nhu cầu đặc biệt", "Special needs education requires smaller classes.", "PHRASE"],
  ["one-to-one", "một giáo viên một học sinh", "Some pupils need one-to-one support.", "ADJECTIVE"],
  ["bullying", "bắt nạt ở trường", "Schools must take bullying seriously.", "NOUN"],
  ["guidelines", "hướng dẫn chính thức (thường từ cơ quan)", "New government guidelines distract headteachers.", "NOUN"],
  ["distraction", "sự làm xao nhãng khỏi việc chính", "Paperwork is a distraction from teaching.", "NOUN"],
  ["perpetuate", "duy trì, khiến (bất công) tiếp diễn", "League tables may perpetuate inequality.", "VERB"],
  ["excel", "đạt thành tích xuất sắc", "Pushy parents want children to excel.", "VERB"],
  ["better-off", "khá giả hơn", "Better-off families can afford extra tutoring.", "ADJECTIVE"],
  ["less well-off", "kém khả năng tài chính hơn", "Fees hit less well-off students hardest.", "ADJECTIVE"],
]);

const U3_WORDS = wordList([
  ["stand out", "nổi bật hơn các ứng viên khác", "A clear cover letter helps you stand out.", "VERB"],
  ["cover letter", "thư xin việc kèm CV", "Attach a tailored cover letter to your CV.", "NOUN"],
  ["fast-paced", "nhịp độ nhanh, áp lực cao", "She thrives in a fast-paced working environment.", "ADJECTIVE"],
  ["openings", "vị trí tuyển dụng còn trống", "The bank has several new openings this month.", "NOUN"],
  ["reporting to", "báo cáo trực tiếp cho (cấp trên)", "You will be reporting to the service manager.", "PHRASE"],
  ["career prospects", "triển vọng thăng tiến nghề nghiệp", "The post offers excellent career prospects.", "PHRASE"],
  ["leadership qualities", "phẩm chất lãnh đạo", "Candidates should demonstrate leadership qualities.", "PHRASE"],
  ["competitive salary", "mức lương cạnh tranh so với thị trường", "They advertise a competitive salary and benefits.", "PHRASE"],
  ["benefits package", "gói phúc lợi ngoài lương", "The benefits package includes healthcare and pension.", "PHRASE"],
  ["subsidised", "được công ty trợ cấp một phần", "Staff meals are subsidised in the canteen.", "ADJECTIVE"],
  ["hands-on", "thực hành trực tiếp, không chỉ lý thuyết", "She wanted hands-on experience in banking.", "ADJECTIVE"],
  ["field", "lĩnh vực, ngành nghề", "He hopes to build a career in this field.", "NOUN"],
  ["customer-facing", "tiếp xúc trực tiếp với khách hàng", "Retail work gave her customer-facing experience.", "ADJECTIVE"],
  ["team player", "người hợp tác tốt trong nhóm", "Employers value applicants who are team players.", "NOUN"],
  ["managerial experience", "kinh nghiệm quản lý", "She gained managerial experience leading a small team.", "PHRASE"],
  ["Yours faithfully", "kết thư trang trọng khi không biết tên người nhận", "End the letter with Yours faithfully.", "PHRASE"],
  ["challenging role", "vị trí đòi hỏi cao, hấp dẫn", "The ad describes a challenging role in fintech.", "PHRASE"],
  ["full training", "đào tạo đầy đủ tại chỗ", "No experience is needed; full training will be given.", "PHRASE"],
  ["previous experience", "kinh nghiệm làm việc trước đó", "Mention any previous experience that is relevant.", "PHRASE"],
  ["passion for", "đam mê mạnh mẽ với điều gì", "Do you have a genuine passion for customer service?", "PHRASE"],
  ["Dear Sir or Madam", "lời mở đầu thư khi không biết tên người nhận", "Dear Sir or Madam is formal but acceptable.", "PHRASE"],
  ["relevant", "liên quan, phù hợp với vị trí", "Highlight studies that are relevant to the role.", "ADJECTIVE"],
]);

const U4_WORDS = wordList([
  ["recruiting", "tuyển dụng nhân sự mới", "The firm is recruiting engineers this quarter.", "VERB"],
  ["criteria", "tiêu chí đánh giá ứng viên", "Candidates must meet strict selection criteria.", "NOUN"],
  ["shortlisted", "lọt vào vòng phỏng vấn", "She was shortlisted after a strong application.", "ADJECTIVE"],
  ["do your homework", "tìm hiểu kỹ trước phỏng vấn", "Do your homework on the company before the interview.", "PHRASE"],
  ["trial run", "buổi thử phỏng vấn giả", "A trial run with a friend boosted her confidence.", "PHRASE"],
  ["line manager", "người quản lý trực tiếp", "Your line manager will set weekly targets.", "NOUN"],
  ["body language", "ngôn ngữ cơ thể", "Confident body language matters at interviews.", "PHRASE"],
  ["speak up", "nói to và rõ ràng", "Speak up so the panel can hear you.", "VERB"],
  ["first impression", "ấn tượng ban đầu", "A firm handshake creates a good first impression.", "PHRASE"],
  ["ideal fit", "rất phù hợp với vị trí", "Your skills seem an ideal fit for the role.", "PHRASE"],
  ["paid leave", "nghỉ phép có lương", "The offer includes generous paid leave.", "PHRASE"],
  ["reporting structure", "cơ cấu báo cáo trong công ty", "The contract outlines the reporting structure.", "PHRASE"],
  ["talk us through", "trình bày chi tiết từng phần", "Can you talk us through your CV?", "PHRASE"],
  ["trainee", "người mới học nghề tại công ty", "He joined as a trainee programmer.", "NOUN"],
  ["in-house", "nội bộ công ty", "We run an in-house training programme.", "ADJECTIVE"],
  ["new recruits", "nhân viên mới tuyển", "New recruits attend orientation on Monday.", "PHRASE"],
  ["take on responsibility", "nhận thêm trách nhiệm", "She is keen to take on more responsibility.", "PHRASE"],
  ["notice period", "thời gian báo trước khi nghỉ", "My notice period is only two weeks.", "PHRASE"],
  ["professional development", "phát triển nghề nghiệp", "Ask about opportunities for professional development.", "PHRASE"],
  ["panel", "hội đồng phỏng vấn", "The interview was conducted by a panel of four.", "NOUN"],
  ["supervisor", "người giám sát trực tiếp", "How would your supervisor describe you?", "NOUN"],
]);

const U5_WORDS = wordList([
  ["opposite number", "người cùng chức vụ ở chi nhánh khác", "Philip is my opposite number in New York.", "NOUN"],
  ["working relationship", "mối quan hệ làm việc", "We have a good working relationship.", "PHRASE"],
  ["collaboration", "hợp tác để đạt mục tiêu chung", "Day-to-day collaboration keeps projects moving.", "NOUN"],
  ["counterpart", "đối tác cùng vai trò (trang trọng hơn opposite number)", "Meet your counterpart in the London office.", "NOUN"],
  ["rapport", "mối quan hệ thân thiện, tin cậy", "The new boss quickly built rapport with the team.", "NOUN"],
  ["take the initiative", "chủ động làm việc không cần chỉ đạo", "She likes staff who take the initiative.", "PHRASE"],
  ["hierarchical", "theo thứ bậc rõ ràng", "The company culture is quite hierarchical.", "ADJECTIVE"],
  ["pecking order", "thứ tự ưu tiên quyền lợi trong tổ chức", "There is a pecking order for promotions.", "PHRASE"],
  ["job-share", "chia sẻ một vị trí cho hai người", "She does a job-share to manage childcare.", "NOUN"],
  ["hot-desking", "ngồi bàn linh hoạt, không cố định chỗ", "Hot-desking means a different desk each day.", "NOUN"],
  ["workmates", "đồng nghiệp thân (không trang trọng)", "I socialise with workmates after hours.", "NOUN"],
  ["talk shop", "nói chuyện công việc (ngoài giờ)", "We try not to talk shop at dinner.", "PHRASE"],
  ["mundane", "tẻ nhạt, đơn điệu", "Most days involve fairly mundane tasks.", "ADJECTIVE"],
  ["volunteer", "tình nguyện nhận việc", "Someone had to volunteer for the late shift.", "VERB"],
  ["rewarding", "mang lại cảm giác thành quả", "Teaching can be deeply rewarding.", "ADJECTIVE"],
  ["stimulating", "kích thích tư duy", "Research work is more stimulating than data entry.", "ADJECTIVE"],
  ["heavy workload", "khối lượng công việc lớn", "A heavy workload made her rethink priorities.", "PHRASE"],
  ["knocking off", "tan ca, kết thúc giờ làm", "He counts the minutes until knocking off time.", "PHRASE"],
  ["stuck in a rut", "mắc kẹt trong công việc nhàm chán", "After ten years she felt stuck in a rut.", "PHRASE"],
  ["dead-end job", "công việc không triển vọng thăng tiến", "He left a dead-end job to retrain.", "PHRASE"],
  ["start-up", "công ty khởi nghiệp mới", "They formed a software start-up in 2009.", "NOUN"],
  ["self-employed", "tự kinh doanh, làm chủ", "Being self-employed means handling your own tax.", "ADJECTIVE"],
  ["freelance", "làm tự do theo hợp đồng", "She works freelance for several agencies.", "ADJECTIVE"],
  ["mind-numbing", "nhàm chán đến mất hết hứng thú", "Long-haul flights can feel mind-numbing.", "ADJECTIVE"],
]);

const U6_WORDS = wordList([
  ["job satisfaction", "sự hài lòng với công việc", "Job satisfaction matters more than perks alone.", "PHRASE"],
  ["run-of-the-mill", "bình thường, không có gì đặc biệt", "It is just a run-of-the-mill office job.", "ADJECTIVE"],
  ["staff morale", "tinh thần, động lực của nhân viên", "Pay freezes damaged staff morale.", "PHRASE"],
  ["freeze on pay rises", "đóng băng tăng lương", "A freeze on pay rises upset the team.", "PHRASE"],
  ["teamwork", "làm việc nhóm hướng tới mục tiêu chung", "Good teamwork helped us solve the problem.", "NOUN"],
  ["job stability", "sự ổn định công việc lâu dài", "Some people prefer job stability to risk.", "PHRASE"],
  ["work-life balance", "cân bằng giữa công việc và đời sống cá nhân", "She wanted a better work-life balance.", "PHRASE"],
  ["fast-moving", "biến động nhanh (ngành, công ty)", "Fashion is a fast-moving industry.", "ADJECTIVE"],
  ["dynamic", "năng động, không ngừng phát triển", "He joined a dynamic new company.", "ADJECTIVE"],
  ["demotivated", "mất hứng thú, giảm động lực làm việc", "Recent cuts left her demotivated.", "ADJECTIVE"],
  ["maternity leave", "nghỉ thai sản", "She starts maternity leave next month.", "PHRASE"],
  ["paternity leave", "nghỉ khi vợ sinh con", "Fathers can take paternity leave too.", "PHRASE"],
  ["adoption leave", "nghỉ để chăm con nhận nuôi", "Adoption leave policies vary by employer.", "PHRASE"],
  ["perks", "phúc lợi phụ (không trang trọng)", "What perks come with the job?", "NOUN"],
  ["holiday entitlement", "số ngày nghỉ phép được hưởng", "Check your holiday entitlement in the contract.", "PHRASE"],
  ["salary increment", "mức tăng lương định kỳ", "Staff expect an annual salary increment.", "PHRASE"],
  ["performance-related pay", "lương thưởng gắn với hiệu suất", "Bonuses are performance-related pay.", "PHRASE"],
  ["annual bonus", "thưởng cuối năm", "The firm paid an annual bonus after strong sales.", "PHRASE"],
  ["overworked and underpaid", "làm quá nhiều mà lương thấp (cụm hài hước)", "Nurses often joke they are overworked and underpaid.", "PHRASE"],
  ["voluntary redundancy", "tự nguyện nghỉ để nhận trợ cấp", "Several staff accepted voluntary redundancy.", "PHRASE"],
  ["compulsory redundancy", "sa thải bắt buộc do cắt giảm", "The plant announced compulsory redundancies.", "PHRASE"],
  ["skeleton staff", "số nhân viên tối thiểu vẫn vận hành", "The airport ran on a skeleton staff during the strike.", "PHRASE"],
  ["seeking a career in", "đang tìm hướng nghề nghiệp mới", "She is seeking a career in marketing.", "PHRASE"],
]);

const U7_WORDS = wordList([
  ["telesales", "bán hàng qua điện thoại", "He started in telesales after school.", "NOUN"],
  ["cold calling", "gọi điện bán hàng cho người lạ", "Most people hate cold calling.", "PHRASE"],
  ["hard sell", "cách bán ép buộc, thuyết phục mạnh", "A hard sell puts many customers off.", "PHRASE"],
  ["shopping channel", "kênh truyền hình bán hàng", "She sold sportswear on a shopping channel.", "NOUN"],
  ["merchandise", "hàng hóa được mua bán", "The store stocks branded merchandise.", "NOUN"],
  ["purchasing power", "sức mua của người tiêu dùng", "Inflation erodes purchasing power.", "PHRASE"],
  ["shop around", "so sánh giá nhiều nơi trước khi mua", "Shop around before you sign a contract.", "VERB"],
  ["brand loyalty", "sự trung thành với một thương hiệu", "Discounts can weaken brand loyalty.", "PHRASE"],
  ["loss leader", "sản phẩm bán lỗ để thu hút khách", "Milk is often used as a loss leader.", "PHRASE"],
  ["niche market", "phân khúc thị trường chuyên biệt", "They found a niche market in vegan snacks.", "PHRASE"],
  ["under the hammer", "được bán tại phiên đấu giá", "The painting went under the hammer last week.", "PHRASE"],
  ["lucrative", "sinh lời cao", "Software proved a lucrative business.", "ADJECTIVE"],
  ["red tape", "thủ tục hành chính rườm rà", "Start-ups struggle with red tape.", "NOUN"],
  ["takeover", "một công ty mua quyền kiểm soát công ty khác", "The takeover was announced in May.", "NOUN"],
  ["compromise", "thỏa hiệp, ai cũng nhượng bộ", "Both sides reached a compromise on price.", "NOUN"],
  ["hammer out a deal", "đàm phán đến khi có thỏa thuận", "Lawyers hammered out a deal overnight.", "PHRASE"],
  ["swallowed up", "bị công ty lớn hơn thôn tính", "Her firm was swallowed up by a multinational.", "PHRASE"],
  ["capital assets", "tài sản cố định của doanh nghiệp", "She sold capital assets to fund a new venture.", "PHRASE"],
  ["letting agency", "công ty cho thuê nhà, căn hộ", "They run an online holiday letting agency.", "PHRASE"],
  ["trade up", "đổi sang hàng/nhà giá trị cao hơn", "Many families trade up when they have children.", "VERB"],
  ["trade down", "đổi sang hàng/nhà rẻ hơn", "Retirees sometimes trade down to a smaller home.", "VERB"],
  ["hasn't looked back", "thành công liên tục kể từ đó", "Since the launch, the brand hasn't looked back.", "PHRASE"],
]);

const U8_WORDS = wordList([
  ["opportunistic", "hay lợi dụng hoàn cảnh vì lợi ích riêng", "Opportunistic traders buy cheap and resell fast.", "ADJECTIVE"],
  ["methodical", "làm việc có hệ thống, cẩn thận", "She is methodical about checking every detail.", "ADJECTIVE"],
  ["chauvinistic", "bảo thủ, coi thường nhóm khác", "His chauvinistic remarks offended colleagues.", "ADJECTIVE"],
  ["get carried away", "say mê quá mức, mất kiểm soát", "Don't get carried away by early success.", "PHRASE"],
  ["obliging", "sẵn lòng giúp đỡ", "An obliging neighbour watered the plants.", "ADJECTIVE"],
  ["perfectionist", "người đòi hỏi hoàn hảo tuyệt đối", "Perfectionists struggle to delegate tasks.", "NOUN"],
  ["tactless", "thiếu tế nhị, dễ làm tổn thương người khác", "That was a tactless comment at the meeting.", "ADJECTIVE"],
  ["intuitive", "hiểu bản chất mà không cần giải thích dài", "She has an intuitive grasp of design.", "ADJECTIVE"],
  ["diligent", "chăm chỉ, siêng năng", "Diligent students revise little and often.", "ADJECTIVE"],
  ["placid", "điềm đạm, khó nổi giận", "He remained placid under pressure.", "ADJECTIVE"],
  ["magnetic personality", "tính cách cuốn hút mọi người", "Leaders often have a magnetic personality.", "PHRASE"],
  ["distrustful", "hay nghi ngờ, khó tin người", "Years of betrayal made him distrustful.", "ADJECTIVE"],
  ["industrious", "cần cù, chuyên cần", "Industrious workers arrive early and stay focused.", "ADJECTIVE"],
  ["shrewd", "sắc sảo, tinh ranh trong quyết định", "A shrewd investor reads the market carefully.", "ADJECTIVE"],
  ["extravagant", "hoang phí, chi tiêu quá mức", "Extravagant spending drained his savings.", "ADJECTIVE"],
  ["altruistic", "vị tha, quan tâm người khác hơn bản thân", "Her altruistic work supports refugees.", "ADJECTIVE"],
  ["morose", "u sầu, hay cau có", "He grew morose after the setback.", "ADJECTIVE"],
  ["sharp-tongued", "lời lẽ sắc nhọn, hay chê bai", "A sharp-tongued critic can hurt morale.", "ADJECTIVE"],
  ["naive", "ngây thơ, dễ tin", "It was naive to trust that offer.", "ADJECTIVE"],
  ["materialistic", "coi trọng vật chất", "Materialistic values clash with her ideals.", "ADJECTIVE"],
  ["astute", "nhạy bén, sắc sảo (tích cực)", "An astute negotiator spots weak points.", "ADJECTIVE"],
  ["sullen", "cau có, im lặng bực bội", "Teenagers can turn sullen without warning.", "ADJECTIVE"],
  ["unscrupulous", "vô đạo đức, sẵn sàng lừa gạt", "Unscrupulous sellers hide defects.", "ADJECTIVE"],
  ["garrulous", "lắm lời, nói lan man", "A garrulous guest dominated the dinner.", "ADJECTIVE"],
]);

export const EVIU_ADVANCED_UNITS_01_08: readonly VocabularyUnit[] = [
  advancedUnit(1, {
    introVi:
      "Unit 1 đưa bạn vào ngôn ngữ học thuật ở mức C1: từ bài luận ngắn đến luận văn dài, cách ôn thi và văn hóa trích dẫn nguồn. Bạn sẽ phân biệt các loại bài viết và nói tự nhiên về quy trình nghiên cứu.",
    structureSections: [
      { label: "Academic writing types", wordCount: 7 },
      { label: "Study, exams and revision", wordCount: 8 },
      { label: "Higher academic study", wordCount: 7 },
    ],
    collocationHtml: `${purple("first draft")}, ${purple("by heart")}, ${purple("inside out")} và ${purple("inter-library loan")} là các cụm then chốt khi bàn về học và nghiên cứu.`,
    mistakeHtml: `Phân biệt ${bold("composition")} (ngắn) với ${bold("assignment")} / ${bold("project")} (dài hơn). ${bold("Plagiarism")} là danh từ; động từ là ${bold("acknowledge")} nguồn.`,
    principles: [
      {
        title: "Các dạng bài viết học thuật",
        body: `${purple("composition")} ngắn; ${purple("assignment")} và ${purple("project")} dài hơn; ${purple("portfolio")} là tập hợp nhiều sản phẩm. Luôn viết ${purple("first draft")} trước bản chính thức.`,
        examples: [
          ex("Always write a first draft before the final version.", "Luôn viết bản nháp trước bản hoàn chỉnh."),
          ex("Her portfolio included essays and creative work.", "Portfolio của cô ấy gồm bài luận và sản phẩm sáng tạo."),
        ],
      },
      {
        title: "Ôn thi và ghi nhớ",
        body: `${purple("cram")} là học dồn sát kỳ thi; ${purple("revision")} và ${purple("past papers")} bền vững hơn. ${purple("rote-learning")} khác ${purple("mnemonics")} — mẹo ghi nhớ có chủ đích.`,
        examples: [
          ex("He crammed for two nights but still felt unprepared.", "Anh ấy nhồi hai đêm nhưng vẫn thấy chưa sẵn sàng."),
          ex("'i before e except after c' is a classic mnemonic.", "'i before e except after c' là mẹo ghi nhớ kinh điển."),
        ],
      },
      {
        title: "Nghiên cứu và tài nguyên",
        body: `Đọc ${purple("academic journal")}; mượn sách qua ${purple("inter-library loan")}; dùng ${purple("open educational resources")}. ${purple("drop out")} nghĩa bỏ học; ${purple("finals")} là kỳ thi cuối khóa.`,
        examples: [
          ex("The article appeared in a leading academic journal.", "Bài báo xuất hiện trên một tạp chí học thuật hàng đầu."),
          ex("Several students dropped out during the first year.", "Vài sinh viên bỏ học ngay năm đầu."),
        ],
      },
    ],
    words: U1_WORDS,
    exercises: [
      fillBlank(
        1,
        1,
        "Copying someone else's essay without credit is called ____.",
        "plagiarism",
        [
          { key: "a", label: "plagiarism" },
          { key: "b", label: "portfolio" },
          { key: "c", label: "revision" },
          { key: "d", label: "finals" },
        ],
        "a",
      ),
      fillBlank(
        1,
        2,
        "Before the exam she decided to ____ for three days straight.",
        "cram",
        [
          { key: "a", label: "cram" },
          { key: "b", label: "acknowledge" },
          { key: "c", label: "drop out" },
          { key: "d", label: "excel" },
        ],
        "a",
      ),
      mcq(
        1,
        3,
        "Tập hợp nhiều bài làm cá nhân (bài viết, hình vẽ...) gọi là gì?",
        [
          { key: "a", label: "portfolio" },
          { key: "b", label: "composition" },
          { key: "c", label: "mind map" },
          { key: "d", label: "first draft" },
        ],
        "a",
      ),
      fillBlank(
        1,
        4,
        "If the library lacks a book, you can request an ____.",
        "inter-library loan",
        [
          { key: "a", label: "inter-library loan" },
          { key: "b", label: "open educational resources" },
          { key: "c", label: "past papers" },
          { key: "d", label: "heavy workload" },
        ],
        "a",
      ),
      mcq(
        1,
        5,
        "\"Inside out\" nghĩa là gì?",
        [
          { key: "a", label: "Nắm rất kỹ chủ đề" },
          { key: "b", label: "Học vẹt không hiểu" },
          { key: "c", label: "Bỏ học giữa chừng" },
          { key: "d", label: "Nộp bài trễ deadline" },
        ],
        "a",
      ),
      fillBlank(
        1,
        6,
        "Learning purely by repetition is known as ____.",
        "rote-learning",
        [
          { key: "a", label: "rote-learning" },
          { key: "b", label: "mnemonics" },
          { key: "c", label: "collaboration" },
          { key: "d", label: "guidelines" },
        ],
        "a",
      ),
    ],
  }),

  advancedUnit(2, {
    introVi:
      "Unit 2 xoay quanh các cuộc tranh luận giáo dục: cơ hội bình đẳng, trường tuyển chọn và bảng xếp hạng. Bạn sẽ dùng từ vựng chính sách và xã hội để bàn luận có chiều sâu về hệ thống học.",
    structureSections: [
      { label: "Opportunity and equality", wordCount: 8 },
      { label: "League tables and inequality", wordCount: 8 },
      { label: "Other debates and issues", wordCount: 7 },
    ],
    collocationHtml: `${purple("equality of opportunity")}, ${purple("league tables")}, ${purple("two-tier system")} và ${purple("tertiary education")} xuất hiện liên tục trong tranh luận giáo dục.`,
    mistakeHtml: `${bold("Selective")} và ${bold("comprehensive")} mô tả hệ thống trường, không phải một trường đơn lẻ. ${bold("Bursary")} theo hoàn cảnh; ${bold("scholarship")} thường theo thành tích.`,
    principles: [
      {
        title: "Cơ hội và bình đẳng",
        body: `${purple("equality of opportunity")} là thước đo then chốt. Tranh luận ${purple("selective schooling")} đối ${purple("comprehensive schooling")} thường gắn với ${purple("elitism")}.`,
        examples: [
          ex("Systems may be judged by equality of opportunity.", "Hệ thống có thể được đánh giá qua cơ hội bình đẳng."),
          ex("Elitism can be inherent in selective entry.", "Chủ nghĩa tinh hoa có thể nằm sẵn trong tuyển chọn."),
        ],
      },
      {
        title: "Bảng xếp hạng và bất bình đẳng",
        body: `${purple("league tables")} có thể ${purple("perpetuate")} bất công. ${purple("well-endowed")} trường và gia đình ${purple("better-off")} dễ đẩy con vào top; ${purple("less well-off")} khó ${purple("excel")}.`,
        examples: [
          ex("League tables divide schools into success and failure.", "Bảng xếp hạng chia trường thành thành công và thất bại."),
          ex("Tables may unintentionally create a two-tier system.", "Bảng xếp hạng có thể vô tình tạo hệ thống hai tầng."),
        ],
      },
      {
        title: "Các vấn đề giáo dục khác",
        body: `${purple("literacy")} và ${purple("numeracy")} là nền tảng; ${purple("curriculum reform")} và ${purple("lifelong education")} là chính sách. Chú ý ${purple("special needs education")}, ${purple("bullying")} và ${purple("guidelines")} gây ${purple("distraction")}.`,
        examples: [
          ex("Mature students need flexible entry routes.", "Sinh viên trưởng thành cần lộ trình vào học linh hoạt."),
          ex("One-to-one support is costly but essential.", "Hỗ trợ một-một tốn kém nhưng cần thiết."),
        ],
      },
    ],
    words: U2_WORDS,
    exercises: [
      fillBlank(
        2,
        1,
        "Schools ranked by exam results appear in national ____.",
        "league tables",
        [
          { key: "a", label: "league tables" },
          { key: "b", label: "past papers" },
          { key: "c", label: "mind maps" },
          { key: "d", label: "portfolios" },
        ],
        "a",
      ),
      mcq(
        2,
        2,
        "Học bổng chủ yếu theo hoàn cảnh kinh tế gọi là gì?",
        [
          { key: "a", label: "bursary" },
          { key: "b", label: "merit badge" },
          { key: "c", label: "notice period" },
          { key: "d", label: "loss leader" },
        ],
        "a",
      ),
      fillBlank(
        2,
        3,
        "Everyone enters without exams in a ____ system.",
        "comprehensive schooling",
        [
          { key: "a", label: "comprehensive schooling" },
          { key: "b", label: "cold calling" },
          { key: "c", label: "hot-desking" },
          { key: "d", label: "hard sell" },
        ],
        "a",
      ),
      mcq(
        2,
        4,
        "\"Two-tier system\" mô tả điều gì?",
        [
          { key: "a", label: "Hệ thống chia tầng tốt và kém" },
          { key: "b", label: "Lớp một giáo viên một học sinh" },
          { key: "c", label: "Học tập suốt đời" },
          { key: "d", label: "Bán hàng qua điện thoại" },
        ],
        "a",
      ),
      fillBlank(
        2,
        5,
        "Reading and writing skills together are called ____.",
        "literacy",
        [
          { key: "a", label: "literacy" },
          { key: "b", label: "numeracy" },
          { key: "c", label: "elitism" },
          { key: "d", label: "rapport" },
        ],
        "a",
      ),
      {
        type: "match",
        id: "ex-2-match-6",
        instruction: "Ghép thuật ngữ giáo dục với nghĩa tiếng Việt",
        pairs: [
          { left: "tertiary education", right: "giáo dục đại học, cao đẳng" },
          { left: "mature student", right: "sinh viên lớn tuổi hơn trung bình" },
          { left: "curriculum reform", right: "cải cách chương trình giảng dạy" },
          { left: "bullying", right: "bắt nạt ở trường" },
          { left: "one-to-one", right: "một giáo viên một học sinh" },
        ],
      },
    ],
  }),

  advancedUnit(3, {
    introVi:
      "Unit 3 tập trung vào ứng tuyển việc làm: đọc tin tuyển dụng, viết cover letter và dùng collocations chuyên nghiệp. Bạn sẽ trình bày kinh nghiệm và động lực một cách thuyết phục.",
    structureSections: [
      { label: "Job ads and openings", wordCount: 8 },
      { label: "Cover letter language", wordCount: 8 },
      { label: "Experience and fit", wordCount: 6 },
    ],
    collocationHtml: `${purple("stand out")}, ${purple("cover letter")}, ${purple("career prospects")} và ${purple("benefits package")} là collocations bắt buộc khi ứng tuyển.`,
    mistakeHtml: `Dùng ${bold("Dear Sir or Madam")} + ${bold("Yours faithfully")} khi không biết tên người nhận. ${bold("Hands-on")} = thực hành; khác ${bold("customer-facing")} = tiếp xúc khách.`,
    principles: [
      {
        title: "Đọc tin tuyển dụng",
        body: `Tin thường nhấn ${purple("fast-paced")} environment, ${purple("openings")}, ${purple("reporting to")} ai, ${purple("competitive salary")} và ${purple("subsidised")} perks.`,
        examples: [
          ex("The bank has several new openings.", "Ngân hàng có vài vị trí tuyển mới."),
          ex("Meals are subsidised in the staff canteen.", "Bữa ăn nhân viên được trợ cấp một phần."),
        ],
      },
      {
        title: "Viết cover letter hiệu quả",
        body: `Mở bằng ${purple("Dear Sir or Madam")} nếu cần; nêu vị trí rõ ràng; nhấn ${purple("passion for")} lĩnh vực; kết bằng ${purple("Yours faithfully")}.`,
        examples: [
          ex("I am keen to gain hands-on experience in banking.", "Tôi muốn có kinh nghiệm thực hành trong ngành ngân hàng."),
          ex("Thank you for considering this application.", "Cảm ơn quý công ty đã xem xét hồ sơ."),
        ],
      },
      {
        title: "Chứng minh phù hợp",
        body: `Nêu ${purple("relevant")} modules, ${purple("customer-facing")} role, ${purple("team player")} và ${purple("managerial experience")} nếu có. Mục tiêu là ${purple("stand out")}.`,
        examples: [
          ex("Retail work gave me valuable customer-facing experience.", "Bán lẻ cho tôi kinh nghiệm tiếp xúc khách hàng."),
          ex("I led a team of four in my previous role.", "Tôi dẫn dắt nhóm bốn người ở vị trí trước."),
        ],
      },
    ],
    words: U3_WORDS,
    exercises: [
      fillBlank(
        3,
        1,
        "A clear, well-written ____ helps your application stand out.",
        "cover letter",
        [
          { key: "a", label: "cover letter" },
          { key: "b", label: "loss leader" },
          { key: "c", label: "pecking order" },
          { key: "d", label: "skeleton staff" },
        ],
        "a",
      ),
      fillBlank(
        3,
        2,
        "She wanted ____ experience, not just theory from her degree.",
        "hands-on",
        [
          { key: "a", label: "hands-on" },
          { key: "b", label: "subsidised" },
          { key: "c", label: "hierarchical" },
          { key: "d", label: "morose" },
        ],
        "a",
      ),
      mcq(
        3,
        3,
        "\"Reporting to the manager\" nghĩa là gì?",
        [
          { key: "a", label: "Làm việc dưới quyền quản lý đó" },
          { key: "b", label: "Viết báo cáo cho khách hàng" },
          { key: "c", label: "Thay manager đi công tác" },
          { key: "d", label: "Quản lý toàn bộ chi nhánh" },
        ],
        "a",
      ),
      fillBlank(
        3,
        4,
        "The post offers excellent ____ for ambitious candidates.",
        "career prospects",
        [
          { key: "a", label: "career prospects" },
          { key: "b", label: "past papers" },
          { key: "c", label: "holiday entitlement" },
          { key: "d", label: "two-tier system" },
        ],
        "a",
      ),
      mcq(
        3,
        5,
        "Kết thư trang trọng khi không biết tên người nhận:",
        [
          { key: "a", label: "Yours faithfully" },
          { key: "b", label: "Best wishes" },
          { key: "c", label: "See you soon" },
          { key: "d", label: "Cheers" },
        ],
        "a",
      ),
      fillBlank(
        3,
        6,
        "Employers want someone who is a good ____ and communicates clearly.",
        "team player",
        [
          { key: "a", label: "team player" },
          { key: "b", label: "loss leader" },
          { key: "c", label: "cold calling" },
          { key: "d", label: "first draft" },
        ],
        "a",
      ),
    ],
  }),

  advancedUnit(4, {
    introVi:
      "Unit 4 bao quát phỏng vấn xin việc từ chuẩn bị đến nhận offer: tiêu chí tuyển chọn, ngôn ngữ cơ thể và các câu hỏi–trả lời điển hình. Bạn sẽ tự tin hơn trong phòng phỏng vấn tiếng Anh.",
    structureSections: [
      { label: "Preparing for interviews", wordCount: 8 },
      { label: "During the interview", wordCount: 7 },
      { label: "Job offer language", wordCount: 6 },
    ],
    collocationHtml: `${purple("do your homework")}, ${purple("trial run")}, ${purple("first impression")} và ${purple("notice period")} là cụm thực tế trong quy trình phỏng vấn.`,
    mistakeHtml: `${bold("Shortlisted")} = vào vòng phỏng vấn, chưa phải được nhận. ${bold("Line manager")} quản lý trực tiếp; ${bold("panel")} là cả hội đồng phỏng vấn.`,
    principles: [
      {
        title: "Chuẩn bị trước phỏng vấn",
        body: `Công ty ${purple("recruiting")} dùng ${purple("criteria")} lọc ứng viên. Nếu ${purple("shortlisted")}, hãy ${purple("do your homework")} và thử ${purple("trial run")} với bạn bè.`,
        examples: [
          ex("Find out as much as you can about the company.", "Tìm hiểu càng nhiều về công ty càng tốt."),
          ex("A trial run boosted her confidence.", "Buổi thử giúp cô ấy tự tin hơn."),
        ],
      },
      {
        title: "Trong phòng phỏng vấn",
        body: `${purple("body language")} và ${purple("speak up")} tạo ${purple("first impression")} tốt. Hội đồng có thể hỏi bạn ${purple("talk us through")} CV hoặc mô tả ${purple("supervisor")}.`,
        examples: [
          ex("Can you talk us through your CV?", "Anh/chị trình bày CV chi tiết được không?"),
          ex("I'm keen to take on more responsibility.", "Tôi muốn nhận thêm trách nhiệm."),
        ],
      },
      {
        title: "Thư mời và điều khoản",
        body: `Offer letter nêu ${purple("ideal fit")}, ${purple("paid leave")}, ${purple("reporting structure")}. Hỏi về ${purple("professional development")} và ${purple("notice period")} hiện tại.`,
        examples: [
          ex("Your qualifications seem an ideal fit for the job.", "Trình độ của bạn rất phù hợp vị trí."),
          ex("My notice period is just two weeks.", "Thời gian báo trước của tôi chỉ hai tuần."),
        ],
      },
    ],
    words: U4_WORDS,
    exercises: [
      fillBlank(
        4,
        1,
        "Before the interview, ____ on the company and its products.",
        "do your homework",
        [
          { key: "a", label: "do your homework" },
          { key: "b", label: "talk shop" },
          { key: "c", label: "trade down" },
          { key: "d", label: "get carried away" },
        ],
        "a",
      ),
      mcq(
        4,
        2,
        "Ứng viên được chọn từ danh sách dài để phỏng vấn gọi là:",
        [
          { key: "a", label: "shortlisted" },
          { key: "b", label: "self-employed" },
          { key: "c", label: "subsidised" },
          { key: "d", label: "well-endowed" },
        ],
        "a",
      ),
      fillBlank(
        4,
        3,
        "Give a firm handshake and ____ so the panel can hear you.",
        "speak up",
        [
          { key: "a", label: "speak up" },
          { key: "b", label: "drop out" },
          { key: "c", label: "knock off" },
          { key: "d", label: "shop around" },
        ],
        "a",
      ),
      fillBlank(
        4,
        4,
        "Can you ____ your CV and explain each role?",
        "talk us through",
        [
          { key: "a", label: "talk us through" },
          { key: "b", label: "hammer out a deal" },
          { key: "c", label: "stand out" },
          { key: "d", label: "perpetuate" },
        ],
        "a",
      ),
      mcq(
        4,
        5,
        "\"Notice period\" là gì?",
        [
          { key: "a", label: "Thời gian báo trước khi nghỉ việc" },
          { key: "b", label: "Buổi thử phỏng vấn giả" },
          { key: "c", label: "Kỳ thi cuối khóa" },
          { key: "d", label: "Học bổng theo hoàn cảnh" },
        ],
        "a",
      ),
      fillBlank(
        4,
        6,
        "The firm runs an ____ training programme for new recruits.",
        "in-house",
        [
          { key: "a", label: "in-house" },
          { key: "b", label: "customer-facing" },
          { key: "c", label: "fast-paced" },
          { key: "d", label: "run-of-the-mill" },
        ],
        "a",
      ),
    ],
  }),

  advancedUnit(5, {
    introVi:
      "Unit 5 mô tả đồng nghiệp, văn hóa công sở và nhịp làm việc đa dạng — từ văn phòng chia sẻ bàn đến ca đêm và khởi nghiệp. Bạn sẽ nói tự nhiên về quan hệ và thói quen hàng ngày.",
    structureSections: [
      { label: "Colleagues and office culture", wordCount: 10 },
      { label: "Daily routines and workload", wordCount: 7 },
      { label: "Career patterns", wordCount: 7 },
    ],
    collocationHtml: `${purple("opposite number")}, ${purple("take the initiative")}, ${purple("job-share")} và ${purple("talk shop")} giúp mô tả đời sống công sở sống động.`,
    mistakeHtml: `${bold("Counterpart")} trang trọng hơn ${bold("opposite number")}. ${bold("Knocking off")} = tan ca (informal); ${bold("dead-end job")} không phải công việc nguy hiểm.`,
    principles: [
      {
        title: "Quan hệ đồng nghiệp",
        body: `${purple("working relationship")} tốt cần ${purple("collaboration")}. ${purple("rapport")} với sếp mới quan trọng; văn hóa ${purple("hierarchical")} có ${purple("pecking order")}.`,
        examples: [
          ex("Philip is my opposite number in New York.", "Philip là người cùng vai trò với tôi ở New York."),
          ex("She likes staff to take the initiative.", "Cô ấy thích nhân viên chủ động."),
        ],
      },
      {
        title: "Nhịp làm và khối lượng công việc",
        body: `Công việc có thể ${purple("mundane")} hoặc ${purple("stimulating")}; đôi khi ${purple("heavy workload")}, đôi khi nhẹ. ${purple("volunteer")} cho việc khó có thể ${purple("rewarding")}.`,
        examples: [
          ex("Occasionally I have to meet a tight deadline.", "Thỉnh thoảng tôi phải hoàn thành đúng deadline."),
          ex("Factory work can feel monotonous.", "Công việc nhà máy có thể đơn điệu."),
        ],
      },
      {
        title: "Lộ trình nghề nghiệp linh hoạt",
        body: `${purple("job-share")} và ${purple("hot-desking")} phản ánh mô hình mới. ${purple("freelance")} / ${purple("self-employed")} khác nhân viên công ty; ${purple("start-up")} là công ty mới thành lập.`,
        examples: [
          ex("They formed a start-up in 2009.", "Họ thành lập start-up năm 2009."),
          ex("I try not to talk shop at dinner.", "Tôi cố không bàn chuyện công ty khi ăn tối."),
        ],
      },
    ],
    words: U5_WORDS,
    exercises: [
      fillBlank(
        5,
        1,
        "She does a ____ with Rose because they both have childcare duties.",
        "job-share",
        [
          { key: "a", label: "job-share" },
          { key: "b", label: "cold call" },
          { key: "c", label: "first draft" },
          { key: "d", label: "bursary" },
        ],
        "a",
      ),
      mcq(
        5,
        2,
        "\"Pecking order\" trong công ty nghĩa là gì?",
        [
          { key: "a", label: "Thứ tự ưu tiên quyền lợi/thăng tiến" },
          { key: "b", label: "Lịch ca làm ban đêm" },
          { key: "c", label: "Hợp đồng thử việc" },
          { key: "d", label: "Bảng xếp hạng trường học" },
        ],
        "a",
      ),
      fillBlank(
        5,
        3,
        "After ten years in the same role, he felt ____.",
        "stuck in a rut",
        [
          { key: "a", label: "stuck in a rut" },
          { key: "b", label: "under the hammer" },
          { key: "c", label: "by heart" },
          { key: "d", label: "shortlisted" },
        ],
        "a",
      ),
      fillBlank(
        5,
        4,
        "The office uses ____ so nobody has a fixed desk.",
        "hot-desking",
        [
          { key: "a", label: "hot-desking" },
          { key: "b", label: "rote-learning" },
          { key: "c", label: "literacy" },
          { key: "d", label: "takeover" },
        ],
        "a",
      ),
      mcq(
        5,
        5,
        "\"Talk shop\" nghĩa là gì?",
        [
          { key: "a", label: "Nói chuyện công việc (thường ngoài giờ)" },
          { key: "b", label: "Đi mua sắm cùng đồng nghiệp" },
          { key: "c", label: "Bán hàng trong cửa hàng" },
          { key: "d", label: "Viết thư xin việc" },
        ],
        "a",
      ),
      fillBlank(
        5,
        6,
        "Research feels more ____ than entering data all day.",
        "stimulating",
        [
          { key: "a", label: "stimulating" },
          { key: "b", label: "subsidised" },
          { key: "c", label: "selective" },
          { key: "d", label: "tertiary" },
        ],
        "a",
      ),
    ],
  }),

  advancedUnit(6, {
    introVi:
      "Unit 6 bàn về sự hài lòng với công việc: động lực, cân bằng cuộc sống, phúc lợi và sa thải. Bạn sẽ diễn đạt cảm xúc và kỳ vọng nghề nghiệp một cách tinh tế hơn.",
    structureSections: [
      { label: "Job satisfaction drivers", wordCount: 8 },
      { label: "Leave and benefits", wordCount: 8 },
      { label: "Pay, morale and redundancies", wordCount: 7 },
    ],
    collocationHtml: `${purple("work-life balance")}, ${purple("staff morale")}, ${purple("performance-related pay")} và ${purple("skeleton staff")} là ngôn ngữ HR thực tế.`,
    mistakeHtml: `${bold("Perks")} informal; ${bold("benefits")} formal — cùng nghĩa phúc lợi. ${bold("Demotivated")} = mất hứng thú; khác ${bold("dynamic")} (năng động).`,
    principles: [
      {
        title: "Điều gì tạo job satisfaction",
        body: `Không chỉ ${purple("workplace")} dễ chịu: ${purple("teamwork")}, ${purple("job stability")} và ${purple("work-life balance")} đều quan trọng. Ngành ${purple("fast-moving")} hoặc ${purple("dynamic")} có thể hấp dẫn nhưng căng.`,
        examples: [
          ex("Can a run-of-the-mill job still be satisfying?", "Công việc bình thường có thể hài lòng không?"),
          ex("She felt demotivated after the restructuring.", "Cô ấy mất động lực sau tái cơ cấu."),
        ],
      },
      {
        title: "Nghỉ phép và phúc lợi",
        body: `${purple("maternity leave")}, ${purple("paternity leave")}, ${purple("adoption leave")}. Hỏi về ${purple("holiday entitlement")}, ${purple("annual bonus")} và ${purple("perks")}.`,
        examples: [
          ex("What's your holiday entitlement?", "Bạn được bao nhiêu ngày phép?"),
          ex("Bonuses are often performance-related.", "Thưởng thường gắn với hiệu suất."),
        ],
      },
      {
        title: "Lương, tinh thần và cắt giảm",
        body: `${purple("freeze on pay rises")} làm tụt ${purple("staff morale")}. ${purple("voluntary redundancy")} tự nguyện; ${purple("compulsory redundancy")} bắt buộc. ${purple("skeleton staff")} giữ vận hành tối thiểu.`,
        examples: [
          ex("Many nurses say they are overworked and underpaid.", "Nhiều y tá nói họ làm quá nhiều, lương thấp."),
          ex("The airport ran on a skeleton staff during the strike.", "Sân bay vận hành tối thiểu trong đình công."),
        ],
      },
    ],
    words: U6_WORDS,
    exercises: [
      fillBlank(
        6,
        1,
        "She left fashion to find a better ____.",
        "work-life balance",
        [
          { key: "a", label: "work-life balance" },
          { key: "b", label: "pecking order" },
          { key: "c", label: "mind map" },
          { key: "d", label: "cold calling" },
        ],
        "a",
      ),
      mcq(
        6,
        2,
        "\"Staff morale\" đề cập đến điều gì?",
        [
          { key: "a", label: "Tinh thần và động lực của nhân viên" },
          { key: "b", label: "Số ngày nghỉ phép" },
          { key: "c", label: "Hợp đồng thử việc" },
          { key: "d", label: "Bảng xếp hạng trường" },
        ],
        "a",
      ),
      fillBlank(
        6,
        3,
        "A pay freeze can seriously damage ____.",
        "staff morale",
        [
          { key: "a", label: "staff morale" },
          { key: "b", label: "brand loyalty" },
          { key: "c", label: "first impression" },
          { key: "d", label: "literacy" },
        ],
        "a",
      ),
      fillBlank(
        6,
        4,
        "Fathers may take ____ when a baby is born.",
        "paternity leave",
        [
          { key: "a", label: "paternity leave" },
          { key: "b", label: "adoption leave" },
          { key: "c", label: "notice period" },
          { key: "d", label: "finals" },
        ],
        "a",
      ),
      mcq(
        6,
        5,
        "Cụm hài hước chỉ làm nhiều mà lương thấp:",
        [
          { key: "a", label: "overworked and underpaid" },
          { key: "b", label: "hands-on experience" },
          { key: "c", label: "career prospects" },
          { key: "d", label: "magnetic personality" },
        ],
        "a",
      ),
      fillBlank(
        6,
        6,
        "During the strike only a ____ kept the site open.",
        "skeleton staff",
        [
          { key: "a", label: "skeleton staff" },
          { key: "b", label: "shopping channel" },
          { key: "c", label: "league tables" },
          { key: "d", label: "workmates" },
        ],
        "a",
      ),
    ],
  }),

  advancedUnit(7, {
    introVi:
      "Unit 7 kết hợp từ vựng bán hàng, mua sắm và sự nghiệp kinh doanh: từ telesales đến takeover và start-up mới. Bạn sẽ hiểu collocations thương mại và ngôn ngữ M&A cơ bản.",
    structureSections: [
      { label: "Sales and telemarketing", wordCount: 7 },
      { label: "Buying and selling", wordCount: 8 },
      { label: "Business careers", wordCount: 7 },
    ],
    collocationHtml: `${purple("cold calling")}, ${purple("loss leader")}, ${purple("niche market")} và ${purple("hammer out a deal")} là collocations thương mại đáng học nguyên cụm.`,
    mistakeHtml: `${bold("Trade up")} = mua đồ đắt hơn; ${bold("trade down")} ngược lại. ${bold("Under the hammer")} = đấu giá, không phải \"dưới búa\" theo nghĩa đen.`,
    principles: [
      {
        title: "Nghề bán hàng",
        body: `${purple("telesales")} và ${purple("cold calling")} khó chịu với khách; ${purple("hard sell")} ép mua. ${purple("shopping channel")} bán ${purple("merchandise")}; thành công có thể khiến bạn ${purple("hasn't looked back")}.`,
        examples: [
          ex("Most people hate cold calling.", "Đa số ghét gọi bán hàng cho người lạ."),
          ex("He specialised in selling leisure merchandise.", "Anh ấy chuyên bán hàng tiêu dùng giải trí."),
        ],
      },
      {
        title: "Hành vi mua sắm",
        body: `${purple("purchasing power")} phản ánh khả năng chi. ${purple("shop around")}, giữ ${purple("brand loyalty")}, hoặc mua ${purple("loss leader")}. ${purple("niche market")} phục vụ nhóm khách chuyên biệt.`,
        examples: [
          ex("Inflation reduces consumers' purchasing power.", "Lạm phát làm giảm sức mua."),
          ex("The vase went under the hammer at auction.", "Chiếc bình được bán đấu giá."),
        ],
      },
      {
        title: "Sự nghiệp kinh doanh",
        body: `Doanh nghiệp ${purple("lucrative")} vẫn vướng ${purple("red tape")}. ${purple("takeover")} / bị ${purple("swallowed up")}; đàm phán ${purple("compromise")} và ${purple("hammer out a deal")}.`,
        examples: [
          ex("She sold capital assets to fund a start-up.", "Cô ấy bán tài sản cố định để góp vốn start-up."),
          ex("They reached a compromise on the sale price.", "Hai bên thỏa hiệp về giá bán."),
        ],
      },
    ],
    words: U7_WORDS,
    exercises: [
      fillBlank(
        7,
        1,
        "Phoning strangers to sell products is called ____.",
        "cold calling",
        [
          { key: "a", label: "cold calling" },
          { key: "b", label: "hot-desking" },
          { key: "c", label: "job-share" },
          { key: "d", label: "one-to-one" },
        ],
        "a",
      ),
      mcq(
        7,
        2,
        "Sản phẩm bán lỗ để kéo khách vào cửa hàng gọi là:",
        [
          { key: "a", label: "loss leader" },
          { key: "b", label: "capital assets" },
          { key: "c", label: "cover letter" },
          { key: "d", label: "first draft" },
        ],
        "a",
      ),
      fillBlank(
        7,
        3,
        "Before signing, it's wise to ____ and compare prices.",
        "shop around",
        [
          { key: "a", label: "shop around" },
          { key: "b", label: "drop out" },
          { key: "c", label: "speak up" },
          { key: "d", label: "excel" },
        ],
        "a",
      ),
      fillBlank(
        7,
        4,
        "Excessive bureaucracy is often called ____.",
        "red tape",
        [
          { key: "a", label: "red tape" },
          { key: "b", label: "staff morale" },
          { key: "c", label: "body language" },
          { key: "d", label: "numeracy" },
        ],
        "a",
      ),
      mcq(
        7,
        5,
        "\"Swallowed up\" trong kinh doanh nghĩa là gì?",
        [
          { key: "a", label: "Bị công ty lớn mua/thôn tính" },
          { key: "b", label: "Tăng lương đột biến" },
          { key: "c", label: "Nghỉ phép có lương" },
          { key: "d", label: "Học vẹt trước thi" },
        ],
        "a",
      ),
      fillBlank(
        7,
        6,
        "Lawyers worked overnight to ____ on the takeover.",
        "hammer out a deal",
        [
          { key: "a", label: "hammer out a deal" },
          { key: "b", label: "talk shop" },
          { key: "c", label: "get carried away" },
          { key: "d", label: "stand out" },
        ],
        "a",
      ),
    ],
  }),

  advancedUnit(8, {
    introVi:
      "Unit 8 trình bày tính cách tích cực và tiêu cực qua bảng tử vi Trung Hoa và các cặp từ đồng nghĩa có sắc thái khác nhau. Bạn sẽ chọn tính từ đúng ngữ cảnh và nhận biết hàm ý +/-.",
    structureSections: [
      { label: "Zodiac traits", wordCount: 10 },
      { label: "Positive qualities", wordCount: 7 },
      { label: "Negative nuances and pairs", wordCount: 7 },
    ],
    collocationHtml: `${purple("magnetic personality")}, ${purple("get carried away")}, ${purple("sharp-tongued")} và các cặp như ${purple("shrewd")} / ${purple("cunning")} thể hiện sắc thái tinh tế.`,
    mistakeHtml: `${bold("Shrewd")} và ${bold("astute")} tích cực; ${bold("cunning")} / ${bold("sly")} tiêu cực — cùng ý \"khôn\" nhưng khác hàm ý. ${bold("Stingy")} tiêu cực; ${bold("frugal")} tích cực.`,
    principles: [
      {
        title: "Tính từ mô tả phẩm chất",
        body: `Sách dùng 12 con giáp minh họa: ${purple("diligent")}, ${purple("obliging")}, ${purple("tactless")}, ${purple("extravagant")}... Mỗi từ mang hàm ý riêng, không thay thế tuỳ ý.`,
        examples: [
          ex("A perfectionist may seem tactless when criticising details.", "Người cầu hảo hảo có thể thiếu tế nhị khi chỉ trích."),
          ex("She has a magnetic personality in meetings.", "Cô ấy có sức cuốn hút trong họp."),
        ],
      },
      {
        title: "Phẩm chất tích cực",
        body: `${purple("methodical")}, ${purple("intuitive")}, ${purple("altruistic")}, ${purple("down-to-earth")} (trong sách: Dog) — mô tả người đáng tin và dễ gần.`,
        examples: [
          ex("An astute investor reads subtle market signals.", "Nhà đầu tư sắc sảo đọc tín hiệu thị trường tinh tế."),
          ex("He remained placid despite harsh criticism.", "Anh ấy vẫn điềm đạm dù bị chỉ trích gay gắt."),
        ],
      },
      {
        title: "Sắc thái tiêu cực và cặp từ",
        body: `${purple("opportunistic")}, ${purple("distrustful")}, ${purple("unscrupulous")}, ${purple("garrulous")} mang hàm ý trừ. Học theo cặp: generous/unstinting vs extravagant/immoderate.`,
        examples: [
          ex("Don't get carried away by early praise.", "Đừng say sưa vì vài lời khen ban đầu."),
          ex("Unscrupulous sellers hide product defects.", "Người bán vô đạo đức che khuyết điểm sản phẩm."),
        ],
      },
    ],
    words: U8_WORDS,
    exercises: [
      fillBlank(
        8,
        1,
        "A ____ person works carefully and follows a clear system.",
        "methodical",
        [
          { key: "a", label: "methodical" },
          { key: "b", label: "garrulous" },
          { key: "c", label: "tactless" },
          { key: "d", label: "opportunistic" },
        ],
        "a",
      ),
      mcq(
        8,
        2,
        "Tính từ nào mang hàm ý tiêu cực (khôn nhưng mánh khóe)?",
        [
          { key: "a", label: "cunning" },
          { key: "b", label: "shrewd" },
          { key: "c", label: "astute" },
          { key: "d", label: "intuitive" },
        ],
        "a",
      ),
      fillBlank(
        8,
        3,
        "He tends to ____ and spend more than he planned.",
        "get carried away",
        [
          { key: "a", label: "get carried away" },
          { key: "b", label: "hammer out a deal" },
          { key: "c", label: "do your homework" },
          { key: "d", label: "shop around" },
        ],
        "a",
      ),
      fillBlank(
        8,
        4,
        "She is ____ and ready to help without being asked.",
        "obliging",
        [
          { key: "a", label: "obliging" },
          { key: "b", label: "morose" },
          { key: "c", label: "distrustful" },
          { key: "d", label: "materialistic" },
        ],
        "a",
      ),
      {
        type: "match",
        id: "ex-8-match-5",
        instruction: "Ghép tính từ với sắc thái nghĩa",
        pairs: [
          { left: "altruistic", right: "vị tha, quan tâm người khác" },
          { left: "extravagant", right: "hoang phí, chi tiêu quá mức" },
          { left: "placid", right: "điềm đạm, khó nổi giận" },
          { left: "sharp-tongued", right: "lời lẽ sắc nhọn, hay chê" },
          { left: "naive", right: "ngây thơ, dễ tin" },
        ],
      },
      mcq(
        8,
        6,
        "\"Garrulous\" mô tả người như thế nào?",
        [
          { key: "a", label: "Nói nhiều, lan man" },
          { key: "b", label: "Im lặng, khép kín" },
          { key: "c", label: "Chăm chỉ, ít nói" },
          { key: "d", label: "Hay giúp đỡ" },
        ],
        "a",
      ),
    ],
  }),
];
