export const CURATED_PRE_PROMPT_VI_76_90: Readonly<Record<string, string>> = {
  "ex-pre-76-1": "Ghép mỗi từ với nghĩa tiếng Việt.",
  "ex-pre-76-2": "Tiện thể, bạn đã gửi email ___ (chưa) chưa?",
  "ex-pre-76-3": "___ (Như tôi đang nói), ngày mai chúng ta nên đi sớm hơn.",
  "ex-pre-76-4": "Thành thật mà nói, tôi không ___ (thích) bộ phim đó.",
  "ex-pre-76-5": "Thực tế là, doanh số đã tăng tháng trước ___ (thực tế).",
  "ex-pre-76-6": "Dù sao thì, hãy quay lại ___ (chủ đề chính) của chúng ta.",
  "ex-pre-76-7": "Nghĩ kỹ lại thì, tôi đã gặp cô ấy ___ (trước đây).",
  "ex-pre-76-8": "Nói ngắn gọn, chúng tôi lỡ tàu và đi ___ (xe buýt).",
  "ex-pre-76-9": "Cụm nào có nghĩa 'theo những gì tôi biết'?",
  "ex-pre-76-10": "Cụm nào thường dùng để đưa ra ý kiến cá nhân?",
  "ex-pre-76-11": "\"That reminds me\" dùng khi nào?",
  "ex-pre-76-12": "\"Mind you\" dùng để ___",
  "ex-pre-76-13": "Cụm nào có nghĩa 'bạn hiểu ý tôi chứ'?",
  "ex-pre-76-14": "\"At least\" thường dùng để ___",

  "ex-pre-77-1": "Ghép mỗi từ với nghĩa tiếng Việt.",
  "ex-pre-77-2": "Kết quả phụ thuộc vào việc bạn ___ (luyện tập) bao nhiêu.",
  "ex-pre-77-3": "Chiếc túi này thuộc ___ (về) chị gái tôi.",
  "ex-pre-77-4": "Anh ấy chịu đựng ___ (từ/mắc phải) đau lưng.",
  "ex-pre-77-5": "Tôi dự định nộp đơn ___ (xin) học bổng.",
  "ex-pre-77-6": "Hãy tập trung ___ (vào) các điểm chính.",
  "ex-pre-77-7": "Chúng ta cần xử lý ___ (với) vấn đề này ngay.",
  "ex-pre-77-8": "Tôi quan tâm ___ (đến) khoa học môi trường.",
  "ex-pre-77-9": "Cụm đúng là gì?",
  "ex-pre-77-10": "\"Be responsible for\" nghĩa là ___",
  "ex-pre-77-11": "Cụm nào có nghĩa 'rất thích, say mê'?",
  "ex-pre-77-12": "\"Be good at\" đi với giới từ nào?",
  "ex-pre-77-13": "\"Recover from\" nghĩa là ___",
  "ex-pre-77-14": "\"Be satisfied with\" nghĩa là ___",

  "ex-pre-78-1": "Ghép mỗi từ với nghĩa tiếng Việt.",
  "ex-pre-78-2": "Tôi không thể nói chuyện lúc ___ (này/hiện tại).",
  "ex-pre-78-3": "Vui lòng cho tôi biết ___ (trước).",
  "ex-pre-78-4": "Lan phụ trách ___ (về) hỗ trợ khách hàng.",
  "ex-pre-78-5": "Chúng tôi có nhiều điểm ___ (chung).",
  "ex-pre-78-6": "Tôi không làm vậy ___ (cố ý).",
  "ex-pre-78-7": "Tôi tình cờ tìm thấy quán cà phê này ___ (vô tình).",
  "ex-pre-78-8": "Nhìn chung, dự án diễn ra ___ (tốt).",
  "ex-pre-78-9": "Cụm nào có nghĩa 'vô tình'?",
  "ex-pre-78-10": "\"For the time being\" nghĩa là ___",
  "ex-pre-78-11": "Cụm nào có nghĩa 'có nguy cơ'?",
  "ex-pre-78-12": "\"In public\" nghĩa là ___",
  "ex-pre-78-13": "Cụm nào có nghĩa 'chẳng hạn như'?",
  "ex-pre-78-14": "\"Under pressure\" nghĩa là ___",

  "ex-pre-79-1": "Ghép mỗi từ với nghĩa tiếng Việt.",
  "ex-pre-79-2": "Hãy bật ___ (lên) máy điều hòa.",
  "ex-pre-79-3": "Đừng quên tắt ___ (đi) đèn.",
  "ex-pre-79-4": "Cô ấy chăm sóc ___ (cho) em trai sau giờ học.",
  "ex-pre-79-5": "Chúng ta cần tìm ___ (ra) lý do doanh số giảm.",
  "ex-pre-79-6": "Đừng từ bỏ ___ (quá) sớm.",
  "ex-pre-79-7": "Chúng tôi hết ___ (cạn) giấy in.",
  "ex-pre-79-8": "Xe tôi hỏng ___ (hỏng) trên cao tốc.",
  "ex-pre-79-9": "Cụm nào có nghĩa là 'chăm sóc'?",
  "ex-pre-79-10": "\"Come across\" nghĩa là ___",
  "ex-pre-79-11": "\"Take off\" trong \"The plane took off on time\" nghĩa là ___",
  "ex-pre-79-12": "\"Work out\" trong \"We will work out a better plan\" nghĩa là ___",
  "ex-pre-79-13": "\"Bring up\" nghĩa là ___",
  "ex-pre-79-14": "\"Get over\" nghĩa là ___",

  "ex-pre-80-1": "Ghép mỗi từ với nghĩa tiếng Việt.",
  "ex-pre-80-2": "Bạn vặn nhỏ ___ (xuống) nhạc được không?",
  "ex-pre-80-3": "Hãy điền ___ (vào) ngày sinh của bạn.",
  "ex-pre-80-4": "Sinh viên phải nộp ___ (bài) báo cáo trước thứ Sáu.",
  "ex-pre-80-5": "Họ hoãn ___ (lại) cuộc họp đến tuần sau.",
  "ex-pre-80-6": "Tôi đang cố cắt giảm ___ (lượng) đường.",
  "ex-pre-80-7": "Dùng email để đăng nhập ___ (vào).",
  "ex-pre-80-8": "Tôi đã đăng ký ___ (tham gia) một workshop cuối tuần.",
  "ex-pre-80-9": "Cụm nào nghĩa là 'hoãn lại'?",
  "ex-pre-80-10": "\"Call off\" nghĩa là ___",
  "ex-pre-80-11": "\"Fill out\" khác \"fill in\" ở chỗ ___",
  "ex-pre-80-12": "\"Take back\" nghĩa là ___",
  "ex-pre-80-13": "\"Calm down\" nghĩa là ___",
  "ex-pre-80-14": "\"Point out\" nghĩa là ___",

  "ex-pre-81-1": "Ghép mỗi từ với nghĩa tiếng Việt.",
  "ex-pre-81-2": "Chúng ta cần đưa ra ___ (quyết định) hôm nay.",
  "ex-pre-81-3": "Bạn đang tiến bộ ___ (tốt) tháng này.",
  "ex-pre-81-4": "Các em làm ___ (bài tập về nhà) sau bữa tối.",
  "ex-pre-81-5": "Bạn giúp tôi một ___ (việc) và in cái này được không?",
  "ex-pre-81-6": "Hãy nghỉ ___ (giải lao) một chút.",
  "ex-pre-81-7": "Anh ấy chịu ___ (trách nhiệm) về lỗi đó.",
  "ex-pre-81-8": "Lời giải thích của bạn ___ (hợp lý) với tôi.",
  "ex-pre-81-9": "Cụm đúng là gì?",
  "ex-pre-81-10": "\"Take part\" nghĩa là ___",
  "ex-pre-81-11": "\"Take place\" nghĩa là ___",
  "ex-pre-81-12": "\"Do well\" nghĩa là ___",
  "ex-pre-81-13": "\"Make an effort\" nghĩa là ___",
  "ex-pre-81-14": "\"Take your time\" nghĩa là ___",

  "ex-pre-82-1": "Ghép mỗi từ với nghĩa tiếng Việt.",
  "ex-pre-82-2": "Mentor của tôi đã cho tôi ___ (lời khuyên) hữu ích.",
  "ex-pre-82-3": "Anh ấy không ___ (bỏ cuộc) dù thất bại hai lần.",
  "ex-pre-82-4": "Cô ấy luôn giữ ___ (lời hứa) của mình.",
  "ex-pre-82-5": "Chúng tôi vẫn giữ liên lạc ___ (liên lạc) sau khi tốt nghiệp.",
  "ex-pre-82-6": "Đừng bỏ lỡ ___ (cơ hội) luyện nói.",
  "ex-pre-82-7": "Tôi không muốn bỏ lỡ ___ (cơ hội nhận) ưu đãi này.",
  "ex-pre-82-8": "Giữ ___ (bình tĩnh) và làm theo hướng dẫn.",
  "ex-pre-82-9": "Cụm nào nghĩa là 'giữ liên lạc'?",
  "ex-pre-82-10": "\"Miss the point\" nghĩa là ___",
  "ex-pre-82-11": "\"Give someone a hand\" nghĩa là ___",
  "ex-pre-82-12": "\"Keep an eye on\" nghĩa là ___",
  "ex-pre-82-13": "\"Miss a deadline\" nghĩa là ___",
  "ex-pre-82-14": "\"Keep in mind\" nghĩa là ___",

  "ex-pre-83-1": "Ghép mỗi từ với nghĩa tiếng Việt.",
  "ex-pre-83-2": "Phát âm của tôi đang trở nên ___ (tốt hơn).",
  "ex-pre-83-3": "Chuẩn bị ___ (sẵn sàng). Lớp bắt đầu sau năm phút.",
  "ex-pre-83-4": "Bạn sẽ quen ___ (với) lịch mới sớm thôi.",
  "ex-pre-83-5": "Chúng ta cần loại bỏ ___ (các) tệp lỗi thời.",
  "ex-pre-83-6": "Cô ấy hòa hợp ___ (với) mọi đồng nghiệp.",
  "ex-pre-83-7": "Cuối cùng tôi đã nắm được cách dùng ___ (phần mềm) này.",
  "ex-pre-83-8": "Hãy liên lạc ___ (liên lạc) nếu bạn cần hỗ trợ.",
  "ex-pre-83-9": "Cụm nào có nghĩa là 'loại bỏ'?",
  "ex-pre-83-10": "\"Get by\" nghĩa là ___",
  "ex-pre-83-11": "\"Get into trouble\" nghĩa là ___",
  "ex-pre-83-12": "\"Get worse\" nghĩa là ___",
  "ex-pre-83-13": "\"Get together\" nghĩa là ___",
  "ex-pre-83-14": "\"Get permission\" nghĩa là ___",

  "ex-pre-84-1": "Ghép mỗi từ với nghĩa tiếng Việt.",
  "ex-pre-84-2": "Cứ ___ (tiếp tục) và đặt câu hỏi của bạn.",
  "ex-pre-84-3": "Tôi cần quay ___ (lại) và kiểm tra các con số.",
  "ex-pre-84-4": "Giá thực phẩm đã tăng ___ (lên) gần đây.",
  "ex-pre-84-5": "Nhiệt độ giảm ___ (xuống) vào ban đêm.",
  "ex-pre-84-6": "Có gì đó xảy ra ___ (sai) với thanh toán.",
  "ex-pre-84-7": "Hãy xem lại ___ (bài) từ vựng chính một lần nữa.",
  "ex-pre-84-8": "Thời gian trôi ___ (qua) thật nhanh những ngày này.",
  "ex-pre-84-9": "Cụm nào thường dùng để cho phép người khác tiếp tục?",
  "ex-pre-84-10": "\"Go through\" nghĩa là ___",
  "ex-pre-84-11": "\"Go for\" nghĩa là ___",
  "ex-pre-84-12": "\"Go off\" trong \"My alarm went off at 5:30\" nghĩa là ___",
  "ex-pre-84-13": "\"Go with\" nghĩa là ___",
  "ex-pre-84-14": "\"Go without\" nghĩa là ___",

  "ex-pre-85-1": "Ghép mỗi từ với nghĩa tiếng Việt.",
  "ex-pre-85-2": "Tôi liếc nhanh ___ (vào) đồng hồ trong cuộc họp.",
  "ex-pre-85-3": "Nhìn chằm chằm ___ (vào) người khác là thiếu lịch sự.",
  "ex-pre-85-4": "Tôi ___ (vô tình nghe được) họ nói về dự án.",
  "ex-pre-85-5": "Tên anh ấy nghe quen quen ___ (gợi nhớ), nhưng tôi không chắc tại sao.",
  "ex-pre-85-6": "Nhà bếp có mùi ___ (của) bánh mì tươi.",
  "ex-pre-85-7": "Những bông hoa này rất ___ (thơm).",
  "ex-pre-85-8": "Bức ảnh ___ (mờ) vì tôi cử động.",
  "ex-pre-85-9": "Từ nào có nghĩa là 'vô tình nghe được'?",
  "ex-pre-85-10": "\"Gaze at\" khác \"glance at\" ở chỗ ___",
  "ex-pre-85-11": "Từ nào mô tả vị 'đắng'?",
  "ex-pre-85-12": "\"Crunchy\" mô tả cảm giác ___",
  "ex-pre-85-13": "\"Faint\" mô tả âm thanh ___",
  "ex-pre-85-14": "\"Sound familiar\" nghĩa là ___",

  "ex-pre-86-1": "Ghép mỗi từ với nghĩa tiếng Việt.",
  "ex-pre-86-2": "Cô ấy đã cho tôi ___ (lời khuyên) hữu ích.",
  "ex-pre-86-3": "Tôi cần thêm ___ (thông tin) về khóa học.",
  "ex-pre-86-4": "Chúng tôi mua ___ (đồ nội thất) mới cho phòng khách.",
  "ex-pre-86-5": "___ (Trang thiết bị) phòng lab rất đắt.",
  "ex-pre-86-6": "Để tôi cho bạn một ___ (lời khuyên).",
  "ex-pre-86-7": "Bạn đang tiến bộ ___ (đều đặn).",
  "ex-pre-86-8": "Tối nay tôi có quá nhiều ___ (bài tập về nhà).",
  "ex-pre-86-9": "Cách dùng nào đúng?",
  "ex-pre-86-10": "Danh từ nào KHÔNG đếm được?",
  "ex-pre-86-11": "Cách lượng hóa \"information\" đúng là ___",
  "ex-pre-86-12": "\"Research\" trong ngữ cảnh chung đi với động từ ___",
  "ex-pre-86-13": "\"Scenery\" nghĩa là ___",
  "ex-pre-86-14": "\"Cash\" là danh từ ___",

  "ex-pre-87-1": "Ghép mỗi từ với nghĩa tiếng Việt.",
  "ex-pre-87-2": "Tôi thích ___ (đọc sách) trước khi ngủ.",
  "ex-pre-87-3": "Hãy tránh ___ (kiểm tra) điện thoại khi học.",
  "ex-pre-87-4": "Tôi quyết định ___ (sẽ) học tiếng Tây Ban Nha năm nay.",
  "ex-pre-87-5": "Cô ấy xoay xở ___ (để) hoàn thành đúng hạn.",
  "ex-pre-87-6": "Anh ấy không chịu nổi việc ___ (chờ đợi) trong hàng dài.",
  "ex-pre-87-7": "Cô ấy dành nhiều thời gian ___ (luyện) đàn piano.",
  "ex-pre-87-8": "Xin lỗi, tôi đang bận ___ (chuẩn bị) bài ngày mai.",
  "ex-pre-87-9": "Câu nào đúng ngữ pháp?",
  "ex-pre-87-10": "\"Suggest doing\" đi theo dạng ___",
  "ex-pre-87-11": "\"Refuse to do\" nghĩa là ___",
  "ex-pre-87-12": "\"Consider doing\" nghĩa là ___",
  "ex-pre-87-13": "\"Would like to do\" là cách nói ___ hơn \"want to do\"",
  "ex-pre-87-14": "\"Need to do\" đi theo dạng ___",

  "ex-pre-88-1": "Ghép mỗi từ với nghĩa tiếng Việt.",
  "ex-pre-88-2": "Giáo viên bắt chúng tôi ___ (viết lại) đoạn văn.",
  "ex-pre-88-3": "Bố mẹ cho tôi ___ (chọn) chuyên ngành.",
  "ex-pre-88-4": "Tôi nhờ anh ấy ___ (gửi) tệp tin.",
  "ex-pre-88-5": "Anh ấy đã ngừng ___ (hút thuốc) năm ngoái.",
  "ex-pre-88-6": "Chúng tôi dừng lại ___ (để) mua nước.",
  "ex-pre-88-7": "Tôi nhớ đã ___ (khóa) cửa.",
  "ex-pre-88-8": "Nhớ ___ (sạc) điện thoại tối nay.",
  "ex-pre-88-9": "Câu nào mang nghĩa 'dừng lại để làm việc khác'?",
  "ex-pre-88-10": "\"Remember doing\" nghĩa là ___",
  "ex-pre-88-11": "\"Try doing\" khác \"try to do\" ở chỗ ___",
  "ex-pre-88-12": "\"Warn someone not to do\" nghĩa là ___",
  "ex-pre-88-13": "\"Prefer doing to doing\" diễn tả ___",
  "ex-pre-88-14": "\"Used to do\" diễn tả ___",

  "ex-pre-89-1": "Ghép mỗi từ với nghĩa tiếng Việt.",
  "ex-pre-89-2": "Cảnh từ tầng thượng thật ___ (tuyệt vời).",
  "ex-pre-89-3": "Tôi ___ (kinh ngạc) vì tiến bộ nhanh của cô ấy.",
  "ex-pre-89-4": "Bài giảng dài và ___ (gây chán).",
  "ex-pre-89-5": "Tôi cảm thấy ___ (chán) trong lúc chờ.",
  "ex-pre-89-6": "Cô ấy là đồng đội ___ (đáng tin cậy).",
  "ex-pre-89-7": "Khu này có căn hộ ___ (vừa túi tiền).",
  "ex-pre-89-8": "Thanh toán trực tuyến rất ___ (thuận tiện).",
  "ex-pre-89-9": "Chọn câu đúng:",
  "ex-pre-89-10": "Tính từ -ing thường mô tả ___",
  "ex-pre-89-11": "\"Confusing\" và \"confused\" khác nhau ở chỗ ___",
  "ex-pre-89-12": "\"Spacious\" nghĩa là ___",
  "ex-pre-89-13": "\"Rude\" nghĩa là ___",
  "ex-pre-89-14": "\"Challenging\" nghĩa là ___",

  "ex-pre-90-1": "Ghép mỗi từ với nghĩa tiếng Việt.",
  "ex-pre-90-2": "Chúng tôi đi bộ ___ (băng qua) cây cầu.",
  "ex-pre-90-3": "Tàu đi ___ (xuyên qua) một đường hầm dài.",
  "ex-pre-90-4": "Họ đạp xe ___ (dọc theo) bờ sông.",
  "ex-pre-90-5": "Đi ___ (ngang qua) ngân hàng rồi rẽ trái.",
  "ex-pre-90-6": "Quán cà phê nằm ___ (giữa) hiệu sách và nhà thuốc.",
  "ex-pre-90-7": "Văn phòng chúng tôi ___ (đối diện) bưu điện.",
  "ex-pre-90-8": "Có trạm xe buýt ở phía trước ___ (nhà) tôi.",
  "ex-pre-90-9": "Giới từ nào nghĩa là 'xuyên qua'?",
  "ex-pre-90-10": "\"Among\" dùng khi ___",
  "ex-pre-90-11": "\"Across\" khác \"through\" ở chỗ ___",
  "ex-pre-90-12": "\"Towards\" nghĩa là ___",
  "ex-pre-90-13": "\"Away from\" nghĩa là ___",
  "ex-pre-90-14": "\"Up to\" nghĩa là ___",
};
