export const CURATED_PRE_PROMPT_VI_91_100: Readonly<Record<string, string>> = {
  "ex-pre-91-1": "Ghép mỗi từ với nghĩa tiếng Việt.",
  "ex-pre-91-2": "Hãy đọc hướng dẫn ___ (một cách cẩn thận).",
  "ex-pre-91-3": "Cô ấy quản lý công việc ___ (một cách hiệu quả).",
  "ex-pre-91-4": "Bạn có thể giải thích điều đó ___ (một cách rõ ràng) không?",
  "ex-pre-91-5": "Chúng tôi ___ (hầu như không bao giờ) ăn đồ ăn nhanh.",
  "ex-pre-91-6": "Lỗi này xảy ra ___ (thường xuyên).",
  "ex-pre-91-7": "Chúng tôi ___ (hiện tại) đang xem xét đơn của bạn.",
  "ex-pre-91-8": "Họ ___ (cuối cùng) đã đạt được thỏa thuận.",
  "ex-pre-91-9": "Từ nào có nghĩa là 'hầu như không bao giờ'?",
  "ex-pre-91-10": "Từ nào chỉ tần suất thấp, không đều đặn?",
  "ex-pre-91-11": "Từ nào nhấn mạnh mức độ rất cao?",
  "ex-pre-91-12": "Từ nào có nghĩa 'gần như, suýt nữa'?",
  "ex-pre-91-13": "Từ nào chỉ thời điểm trước đó?",
  "ex-pre-91-14": "Từ nào có nghĩa 'một cách ước chừng'?",
  "ex-pre-92-1": "Ghép mỗi từ với nghĩa tiếng Việt.",
  "ex-pre-92-2": "___, hãy xác định vấn đề (trước hết).",
  "ex-pre-92-3": "Dữ liệu đã được làm sạch và ___ (sau đó) được phân tích.",
  "ex-pre-92-4": "Tôi chuẩn bị bữa tối; ___, anh ấy dọn bàn (trong khi đó).",
  "ex-pre-92-5": "Cả hai hệ thống được cập nhật ___ (đồng thời).",
  "ex-pre-92-6": "Báo cáo sẽ sẵn sàng ngày mai; ___, hãy xem bản nháp (trong lúc chờ).",
  "ex-pre-92-7": "___, tôi thấy phần mềm khó hiểu (ban đầu).",
  "ex-pre-92-8": "___, nộp câu trả lời của bạn (cuối cùng).",
  "ex-pre-92-9": "Cụm nào phù hợp nhất để mở đầu một quy trình?",
  "ex-pre-92-10": "Từ nào chỉ bước tiếp theo trong trình tự?",
  "ex-pre-92-11": "Từ nào nhấn mạnh kết quả sau quá trình dài?",
  "ex-pre-92-12": "Từ nào có nghĩa 'trước đó, chuẩn bị từ sớm'?",
  "ex-pre-92-13": "Từ nào chỉ thời điểm sớm hơn?",
  "ex-pre-92-14": "Từ nào chỉ giai đoạn đầu tiên?",
  "ex-pre-93-1": "Ghép mỗi từ với nghĩa tiếng Việt.",
  "ex-pre-93-2": "Khóa học rất thực tế; ___, nó còn phải chăng (hơn nữa).",
  "ex-pre-93-3": "___, ứng dụng hỗ trợ chế độ offline (ngoài ra).",
  "ex-pre-93-4": "Thiết kế trông đẹp; ___, khó bảo trì (tuy nhiên).",
  "ex-pre-93-5": "Nhiệm vụ khó; ___, chúng tôi vẫn hoàn thành (dù vậy).",
  "ex-pre-93-6": "Chị tôi thích thành phố, ___ tôi thích thị trấn nhỏ (trong khi).",
  "ex-pre-93-7": "___ sự chậm trễ, chúng tôi vẫn đến đúng giờ (mặc cho).",
  "ex-pre-93-8": "Hãy gửi email cho họ ___ (thay vào đó).",
  "ex-pre-93-9": "Từ nào phù hợp nhất để chuyển sang ý đối lập?",
  "ex-pre-93-10": "Cụm nào bổ sung thông tin theo hướng tăng cường?",
  "ex-pre-93-11": "Cụm nào nhấn mạnh hơn 'although'?",
  "ex-pre-93-12": "Cụm nào đối chiếu hai phương pháp khác nhau?",
  "ex-pre-93-13": "Cấu trúc nào diễn đạt 'không chỉ ... mà còn ...'?",
  "ex-pre-93-14": "Cụm nào có nghĩa 'mặt khác, xét ở khía cạnh đối lập'?",
  "ex-pre-94-1": "Ghép mỗi từ với nghĩa tiếng Việt.",
  "ex-pre-94-2": "Trận đấu bị hủy ___ mưa lớn (bởi vì).",
  "ex-pre-94-3": "Sự chậm trễ là ___ sự cố kỹ thuật (do).",
  "ex-pre-94-4": "Hệ thống quá tải; ___, thời gian phản hồi tăng (vì vậy).",
  "ex-pre-94-5": "Doanh số cải thiện; ___, chúng tôi tuyển thêm nhân viên (kết quả là).",
  "ex-pre-94-6": "Cô ấy ghi chú ___ nhớ các điểm chính (để).",
  "ex-pre-94-7": "Mang theo ô ___ trời mưa (phòng khi).",
  "ex-pre-94-8": "Nộp hôm nay; ___, yêu cầu của bạn có thể bị từ chối (nếu không thì).",
  "ex-pre-94-9": "Từ nào diễn đạt kết quả theo phong cách trang trọng?",
  "ex-pre-94-10": "Cụm nào có nghĩa 'với điều kiện là'?",
  "ex-pre-94-11": "Cụm nào có nghĩa 'miễn là'?",
  "ex-pre-94-12": "Từ nào diễn đạt hệ quả trang trọng tương đương 'therefore'?",
  "ex-pre-94-13": "Cụm nào diễn đạt mục đích bằng mệnh đề?",
  "ex-pre-94-14": "Từ nào có nghĩa 'trừ khi, nếu không thì'?",
  "ex-pre-95-1": "Ghép mỗi từ với nghĩa tiếng Việt.",
  "ex-pre-95-2": "___ được yêu cầu trong đơn xin việc (văn phong trang trọng).",
  "ex-pre-95-3": "Tránh quá nhiều ___ trong email trang trọng (dạng rút gọn).",
  "ex-pre-95-4": "___ rất phổ biến trong tiếng Anh nói (cụm động từ).",
  "ex-pre-95-5": "Cụm từ nghe quá ___ cho một báo cáo (khẩu ngữ).",
  "ex-pre-95-6": "Dùng ___ khi viết cho khách hàng mới (giọng trung tính).",
  "ex-pre-95-7": "Please và thank you là các ___ cơ bản (cách diễn đạt lịch sự).",
  "ex-pre-95-8": "___ có thể xây dựng niềm tin nhanh chóng (cách dùng từ chuyên nghiệp).",
  "ex-pre-95-9": "Khái niệm nào chỉ sự phù hợp văn phong theo bối cảnh?",
  "ex-pre-95-10": "Cụm nào chỉ danh xưng lịch sự như Mr, Ms, Dr?",
  "ex-pre-95-11": "Cụm nào chỉ lệch tông văn phong so với bối cảnh?",
  "ex-pre-95-12": "Cụm nào chỉ cách làm mềm lời yêu cầu?",
  "ex-pre-95-13": "Cụm nào chỉ ngôn ngữ giảm mức khẳng định tuyệt đối?",
  "ex-pre-95-14": "Cụm nào chỉ cách diễn đạt tự nhiên, thoải mái?",
  "ex-pre-96-1": "Ghép mỗi từ với nghĩa tiếng Việt.",
  "ex-pre-96-2": "Vui lòng điền ___ bằng chữ in hoa (mẫu đơn đăng ký).",
  "ex-pre-96-3": "Nhập ___ của bạn chính xác (thông tin cá nhân).",
  "ex-pre-96-4": "Ghi ___ theo đúng định dạng (ngày sinh).",
  "ex-pre-96-5": "Ghi ___ ban ngày (số điện thoại liên hệ).",
  "ex-pre-96-6": "Đừng quên thêm ___ (mã bưu chính).",
  "ex-pre-96-7": "Nêu bật ___ liên quan trước tiên (kinh nghiệm làm việc).",
  "ex-pre-96-8": "Đính kèm ___ phù hợp với vị trí (thư xin việc).",
  "ex-pre-96-9": "Từ nào chỉ người xác nhận thông tin nghề nghiệp của bạn?",
  "ex-pre-96-10": "Cụm nào chỉ sơ yếu lý lịch nghề nghiệp?",
  "ex-pre-96-11": "Cụm nào chỉ quá trình học tập và bằng cấp?",
  "ex-pre-96-12": "Động từ nào nghĩa là 'khai báo, xác nhận thông tin là đúng'?",
  "ex-pre-96-13": "Cụm nào chỉ phần tóm tắt kỹ năng nổi bật?",
  "ex-pre-96-14": "Cụm nào chỉ lịch sử các công việc đã làm?",
  "ex-pre-97-1": "Ghép mỗi từ với nghĩa tiếng Việt.",
  "ex-pre-97-2": "Đọc ___ kỹ trước khi viết (đề bài luận).",
  "ex-pre-97-3": "___ của bạn nên cụ thể (câu luận điểm chính).",
  "ex-pre-97-4": "Bắt đầu mỗi đoạn bằng ___ mạnh (câu chủ đề).",
  "ex-pre-97-5": "Dùng ___ từ nguồn đáng tin cậy (dẫn chứng).",
  "ex-pre-97-6": "Lập ___ trước khi viết nháp (dàn ý).",
  "ex-pre-97-7": "Hoàn thành ___ đầu tiên nhanh, rồi chỉnh sửa (bản nháp).",
  "ex-pre-97-8": "Giữ trong ___ (giới hạn số từ).",
  "ex-pre-97-9": "Thành phần nào nêu rõ luận điểm trung tâm của bài luận?",
  "ex-pre-97-10": "Cụm nào chỉ lập luận phản biện với ý kiến đối lập?",
  "ex-pre-97-11": "Từ nào chỉ sự liên kết giữa các câu và đoạn?",
  "ex-pre-97-12": "Động từ nào nghĩa là 'chỉnh sửa lại nội dung và cấu trúc'?",
  "ex-pre-97-13": "Cụm nào chỉ đoạn kết luận tổng hợp ý chính?",
  "ex-pre-97-14": "Cụm nào chỉ văn phong học thuật, khách quan?",
  "ex-pre-98-1": "Ghép mỗi từ với nghĩa tiếng Việt.",
  "ex-pre-98-2": "Bắt đầu bằng ___ khi chưa có tên (cụm chào trang trọng).",
  "ex-pre-98-3": "___ hỏi về dịch vụ của bạn (tôi viết thư để).",
  "ex-pre-98-4": "___ email ngày 5 tháng 5 của bạn, ... (liên quan đến).",
  "ex-pre-98-5": "___ hợp đồng đã ký (xin gửi kèm theo).",
  "ex-pre-98-6": "___ nhận được phản hồi từ bạn (tôi mong).",
  "ex-pre-98-7": "Dùng ___ sau Dear Sir or Madam (kết thư trang trọng).",
  "ex-pre-98-8": "Dùng ___ rõ ràng cho việc khẩn cấp (dòng tiêu đề).",
  "ex-pre-98-9": "Cụm nào dùng khi gửi kèm tài liệu trong email trang trọng?",
  "ex-pre-98-10": "Cụm nào dùng khi biết tên người nhận?",
  "ex-pre-98-11": "Cụm nào có nghĩa 'khi thuận tiện sớm nhất có thể'?",
  "ex-pre-98-12": "Cụm nào dùng cho thư mở đầu trang trọng khi người nhận không cụ thể?",
  "ex-pre-98-13": "Cụm nào chỉ thư khiếu nại theo phong cách trang trọng?",
  "ex-pre-98-14": "Cụm nào có nghĩa 'tôi sẽ rất cảm kích nếu...'?",
  "ex-pre-99-1": "Ghép mỗi từ với nghĩa tiếng Việt.",
  "ex-pre-99-2": "___, tối nay bạn rảnh không? (chào thân mật).",
  "ex-pre-99-3": "___? Mình không gặp bạn vài tuần rồi (dạo này thế nào?).",
  "ex-pre-99-4": "___ hỏi xem bạn ổn không (chỉ muốn).",
  "ex-pre-99-5": "___, mình tìm thấy sách của bạn (nhân tiện).",
  "ex-pre-99-6": "Cuối tuần này mình ___ uống cà phê nhé (gặp lại cập nhật chuyện).",
  "ex-pre-99-7": "Thứ Sáu lúc 7 giờ ___ (nghe ổn đó).",
  "ex-pre-99-8": "Mình đang họp, ___ (nói chuyện lại sớm nhé).",
  "ex-pre-99-9": "Từ viết tắt nào nghĩa là 'for your information'?",
  "ex-pre-99-10": "Từ viết tắt nào nghĩa là 'as soon as possible'?",
  "ex-pre-99-11": "Cụm nào có nghĩa 'đi chơi, dành thời gian cùng nhau'?",
  "ex-pre-99-12": "Từ viết tắt nào là viết tắt của 'by the way'?",
  "ex-pre-99-13": "Cụm nào có nghĩa 'cảm ơn/bye thân mật (Anh-Anh)'?",
  "ex-pre-99-14": "Từ nào chỉ lỗi gõ nhầm khi nhắn nhanh?",
  "ex-pre-100-1": "Ghép mỗi từ với nghĩa tiếng Việt.",
  "ex-pre-100-2": "___ rất phổ biến trong văn viết công việc (từ viết tắt).",
  "ex-pre-100-3": "NATO là một ___ (từ viết tắt đọc thành từ).",
  "ex-pre-100-4": "BBC là một ___ (viết tắt đọc từng chữ cái).",
  "ex-pre-100-5": "Mang bút, giấy, ___ đến lớp (v.v.).",
  "ex-pre-100-6": "Dùng năng lượng tái tạo, ___, gió và mặt trời (ví dụ).",
  "ex-pre-100-7": "Anh ấy song ngữ, ___, anh ấy nói hai thứ tiếng (tức là).",
  "ex-pre-100-8": "Ghi ___ nếu mục đó không áp dụng (không có/không áp dụng).",
  "ex-pre-100-9": "Khái niệm nào chỉ dạng viết tắt đọc từng chữ cái (ví dụ BBC)?",
  "ex-pre-100-10": "Viết tắt nào nghĩa là 'xấp xỉ'?",
  "ex-pre-100-11": "Viết tắt nào nghĩa là 'date of birth'?",
  "ex-pre-100-12": "Viết tắt nào nghĩa là 'estimated time of arrival'?",
  "ex-pre-100-13": "Viết tắt nào nghĩa là 'frequently asked questions'?",
  "ex-pre-100-14": "Viết tắt nào nghĩa là 'versus, đối với/so với'?",
};
