export const CURATED_EXERCISE_PROMPT_VI: Readonly<Record<string, string>> = {
  "ex-1-1-1": "Kavita là ___ của Ravi.",
  "ex-1-1-2": "Ravi là ___ của Kavita.",
  "ex-1-1-3": "Anne là ___ của Kavita.",
  "ex-1-1-4": "Ivan là ___ của Ravi.",
  "ex-1-1-5": "Diana là ___ của Ravi.",
  "ex-1-1-6": "Henry là ___ của Kavita.",
  "ex-1-1-7": "Ravi là ___ của Ivan.",
  "ex-1-1-8": "Kavita là ___ của Ivan.",
  "ex-1-1-9": "Meena là ___ của Kavita.",
  "ex-1-1-10": "Meena là ___ của George.",
  "ex-1-1-11": "Karen là ___ của Ravi.",
  "ex-1-2-1": "Sanjay là ___ của Kavita và Ravi.",
  "ex-1-2-2": "Vợ của Sanjay là ___ của họ.",
  "ex-1-2-3": "Prem là một ___.",
  "ex-1-2-4": "Alexander là ___ của Henry.",
  "ex-1-2-5": "Leila là ___ của Henry.",
  "ex-1-2-6": "Alexander và Leila có ba ___ — Amelia, Ivan và George.",
  "ex-1-2-7": "Ivan và George cùng các ___, Anne và Meena, của họ rất yêu ông bà.",
  "ex-1-2-8": "Họ yêu ___ của mình và thăm họ thường xuyên nhất có thể.",
  "ex-1-2-9": "Họ cũng thăm ___ của mình (parents cũng đúng).",
  "ex-2-2-2": "Tên gọi người đàn ông trong ngày cưới là ___",
  "ex-2-2-3": "Bạn là gì nếu chưa có người yêu:",
  "ex-2-2-4": "Nặng 57 kilôgam nghĩa là ___",
  "ex-2-2-5": "Bạn là gì nếu hôn nhân đã kết thúc hợp pháp:",
  "ex-2-2-6": "Lễ tôn giáo cho người đã mất:",
  "ex-2-2-7": "Kỳ nghỉ sau đám cưới:",
  "ex-2-2-8": "Bạn là gì nếu chồng hoặc vợ đã mất:",
  "ex-2-3-1": "Năm 2003 Anne kết hôn ___ Daniel Smith.",
  "ex-2-3-2": "Lydia Smith qua đời ___ tuổi già ngay sau đám cưới.",
  "ex-2-3-3": "Daniel và Anne đang ___ tuần trăng mật khi bà mất.",
  "ex-2-3-4": "Con gái sơ sinh của Anne được sinh ra ___ hai năm sau.",
  "ex-2-3-5": "Họ đặt tên em bé là Lydia, ___ bà ngoại của Daniel.",
  "ex-2-4-2": "Christopher Columbus sinh năm 1451 và ___ năm 1506.",
  "ex-2-4-3": "Leonardo da Vinci sinh năm 1452 và ___ năm 1519.",
  "ex-2-4-4": "Công nương Diana sinh năm 1961 và ___ năm 1997.",
  "ex-2-5-1": "Ông ngoại của Kelly ___ năm ngoái.",
  "ex-2-5-2": "Cái ___ của ông khiến cô rất buồn.",
  "ex-2-5-3": "Bà ngoại của cô đã ___ được năm năm rồi.",
  "ex-2-5-4": "Bà ___ vì đau tim.",
  "ex-2-5-5": "Giờ tất cả ông bà của Kelly đều đã ___.",
  "ex-4-2": "Ghép từ quần áo bên trái với bộ phận cơ thể bên phải",
  "ex-4-3-1": "Quần jean của Tim ___ màu xanh và áo phông ___ màu đỏ.",
  "ex-4-3-2": "Hôm nay Julia ___ quần jean và áo phông.",
  "ex-4-3-3": "Meena ___ mặc áo khoác đỏ và cô ấy ___ một số bông hoa.",
  "ex-4-3-4": "Váy của Sarah ___ cũ nhưng giày ___ mới.",
  "ex-4-3-5": "Năm ngoái quần của Harry ___ màu trắng. Giờ chúng ___ màu xám.",
  "ex-4-3-6": "___ đây có phải một cặp quần jean mới không?",
  "ex-4-3-7": "Bộ đồ ngủ yêu thích của tôi ___ màu xanh đậm.",
  "ex-4-3-8": "Kim ___ một cặp quần short mới.",
  "ex-4-4-2": "Trời lạnh — tôi cần ___ của mình.",
  "ex-4-4-3": "Mang theo ___ — trời có thể mưa.",
  "ex-4-4-4": "Cô ấy mặc ___ màu xanh đến bữa tiệc.",
  "ex-4-4-5": "Anh ấy đóng gói ___ cho chuyến đi.",
  "ex-4-4-6": "Xem giờ trên ___ của bạn.",
  "ex-4-4-7": "Anh ấy mặc ___ màu trắng đi làm.",
  "ex-4-4-8": "Mặc ___ vào — trời lạnh buốt.",
  "ex-4-4-9": "Cô ấy mua ___ mùa đông mới.",
  "ex-4-6-1": "Joe đang mặc ___ chỉnh tề, áo sơ mi trắng và cà vạt.",
  "ex-5-1-1": "Anh ấy chỉ cao 1 mét 52. Anh ấy khá ___.",
  "ex-5-1-2": "Người rất ___ thường chơi bóng rổ giỏi.",
  "ex-5-1-3": "Người mẫu thường ___.",
  "ex-5-1-4": "Cô ấy có da sẫm không? Không, da ___ mà.",
  "ex-5-1-5": "Cô bé mới bảy tuổi. Cô bé rất ___.",
  "ex-5-1-6": "Nếu tôi ăn quá nhiều tôi sẽ ___.",
  "ex-5-1-7": "Bà ngoại tôi ở bệnh viện này dành cho người ___.",
  "ex-5-2-1": "___ tóc của Elena vàng / sáng màu không?",
  "ex-5-2-2": "___ tóc của Mike dài không?",
  "ex-5-2-3": "___ bố mẹ bạn có già không?",
  "ex-5-2-4": "___ em gái anh ấy xinh / đẹp không?",
  "ex-5-2-5": "Tại sao Sara lại ___ gầy thế?",
  "ex-5-3-1": "Felicity có tóc vàng và da ___.",
  "ex-5-3-2": "Jeff có tóc vàng ngắn và một ___.",
  "ex-5-4-1": "Anh trai bạn cao bao ___?",
  "ex-5-4-2": "Giáo viên của bạn trông ___ như thế nào?",
  "ex-5-4-3": "Bạn nặng bao ___?",
  "ex-5-4-4": "Mẹ bạn bao ___ tuổi?",
  "ex-5-4-5": "___ của bạn cao bao nhiêu?",
  "ex-6-1-1": "A: Hôm nay bạn thế nào? B: ___, cảm ơn.",
  "ex-6-1-2": "A: Bạn ổn không? B: Không, tôi cảm thấy ___.",
  "ex-6-1-3": "A: Tôi cảm thấy ___. B: Tôi sẽ gọi bác sĩ.",
  "ex-6-1-4": "A: Tôi bị ___. B: Đây là số điện thoại nha sĩ.",
  "ex-6-1-5": "A: Mũi bạn đỏ. Bạn bị ___ không? B: Có.",
  "ex-6-2": "Ghép loại bệnh bên trái với cách xử trí bên phải",
  "ex-6-3-2": "Nước uống ô nhiễm có thể gây ___.",
  "ex-6-3-3": "Ô nhiễm và khói xe liên quan đến ___.",
  "ex-6-3-4": "Cỏ và hoa mùa hè có thể gây ___.",
  "ex-6-3-5": "Hút thuốc và chế độ ăn không lành mạnh liên quan đến ___.",
  "ex-6-w1": "Tôi bị ___. Tôi cần đến nha sĩ.",
  "ex-6-w2": "Tôi lên giường với đồ uống nóng. Tôi bị ___.",
  "ex-6-w3": "Bố tôi bị ___ và đi bệnh viện.",
  "ex-6-w4": "Mỗi mùa hè tôi bắt đầu hắt hơi — tôi bị ___.",
  "ex-6-w5": "Bơi lội và đạp xe là ___ tốt cho bạn.",
  "ex-6-w6": "Tôi cảm thấy ___ khi có quá nhiều việc.",
  "ex-6-w7": "Muỗi có thể truyền ___ cho người.",
  "ex-6-w8": "Ăn nhiều trái cây và rau để có chế độ ăn ___.",
  "ex-7-4-2": "Nicholas trông khát nước. Anh ấy cảm thấy thế nào?",
  "ex-7-4-3": "Max đang mặc áo khoác và run. Anh ấy cảm thấy thế nào?",
  "ex-7-4-4": "Sunita đang ngáp. Cô ấy cảm thấy thế nào?",
  "ex-7-4-5": "Mắt Fiona mở to. Cô ấy cảm thấy thế nào?",
  "ex-7-4-6": "Các em đổ mồ hôi dưới nắng. Các em cảm thấy thế nào?",
  "ex-7-5-1": "Sửa lỗi vị trí trạng từ: I very like basketball. → I like basketball ___.",
  "ex-7-5-2": "Sửa giới từ: I am happy for my sister's good news. → I am happy ___ my sister's good news.",
  "ex-7-5-3": "Sửa mệnh đề: The teacher wants that we learn these words. → The teacher wants ___ to learn these words.",
  "ex-7-5-4": "Sửa vị trí really: I like really spiders. → I ___ like spiders.",
  "ex-7-5-5": "Sửa giới từ: I'm very happy about him. → I'm very happy ___ him.",
  "ex-7-5-6": "Sửa mệnh đề: My parents want that I go to university. → My parents want ___ to go to university.",
  "ex-7-5-7": "Sửa câu hỏi: How for you? → How ___ you?",
  "ex-7-5-8": "Sửa thiếu từ: Priya is bit tired. → Priya is ___ tired this morning.",
  "ex-7-p1": "Bạn thích cái nào hơn — trà hay cà phê? Câu trả lời hay nhất:",
  "ex-7-p2": "Tôi ___ phim kinh dị. (không thích)",
  "ex-7-p3": "Tôi ___ kỳ thi của tôi diễn ra tốt đẹp.",
  "ex-7-p4": "Tôi ___ cà phê hơn trà.",
  "ex-7-p5": "Nhện à? Tôi ___ chúng!",
  "ex-8-1-1": "A hắt xì hơi. B nói:",
  "ex-8-1-2": "A: Hôm nay tôi thi bằng lái xe. B:",
  "ex-8-1-3": "A: Tôi đã đỗ bằng lái xe! B:",
  "ex-8-1-4": "A: Tạm biệt. B:",
  "ex-8-1-5": "A: Hôm nay là sinh nhật tôi. B:",
  "ex-8-1-6": "A: Bạn khỏe không? B:",
  "ex-8-3-1": "Bạn muốn đi qua cửa. Mọi người đang chặn. Bạn nói:",
  "ex-8-3-2": "Bạn bè mua đồ uống cho bạn. Bạn nói:",
  "ex-8-3-3": "Một đứa trẻ nói 'Chúc ngủ ngon' với bạn. Bạn đáp:",
  "ex-8-3-4": "Bạn nghe điện thoại ở công ty lúc 10 giờ 30 sáng. Bạn nói:",
  "ex-8-3-5": "Bạn nghe điện thoại ở công ty lúc 3 giờ chiều. Bạn nói:",
  "ex-8-3-6": "Lúc 2 giờ sáng ngày 1 tháng 1. Bạn gặp bạn. Bạn nói:",
  "ex-8-3-7": "Trên xe buýt đông người bạn giẫm chân ai đó. Bạn nói:",
  "ex-8-3-8": "Ngày 24 tháng 12. Bạn gặp bạn trên xe buýt. Bạn nói:",
  "ex-8-2-1": "Ai đó muốn thu hút sự chú ý của bạn một cách nhẹ nhàng. Họ nói:",
  "ex-8-2-2": "Ai đó sắp rời đi. Họ nói:",
  "ex-8-2-3": "Ai đó đạt được điều gì đặc biệt. Bạn nói:",
  "ex-8-2-4": "Bạn gặp ai đó vào buổi sáng. Bạn nói:",
  "ex-8-4-1": "Ann: Chào buổi tối. Bạn đáp:",
  "ex-8-4-2": "Ann: Hôm nay là sinh nhật tôi. Bạn nói:",
  "ex-9-1-1": "Ở đây chán quá. Mình đi đâu đó ___ đi.",
  "ex-9-1-2": "Có ___ 20 người tại buổi thuyết trình.",
  "ex-9-1-3": "Đây là một bức ảnh ___ đẹp!",
  "ex-9-1-4": "Bạn có muốn gì ___ không?",
  "ex-9-1-5": "Anh ấy nói là bác sĩ nhưng thực ra chỉ là sinh viên y khoa ___.",
  "ex-9-1-6": "Chuyến đi mất ___ hai giờ.",
  "ex-9-2-1": "Tôi không thích trượt tuyết và ___ tôi cũng không rảnh cuối tuần đó.",
  "ex-9-2-2": "Tôi không ___ chúng ta làm gì. Với tôi đều như nhau.",
  "ex-9-2-3": "___ mời Rachel ăn tối tối nay nhé?",
  "ex-9-2-4": "___ ở London. Ở đó giao thông rất đông.",
  "ex-9-2-5": "Tôi không có thời gian đi xem phim và ___ tôi đã xem phim đó rồi.",
  "ex-9-3-1": "Ôi trời! Tôi không được nhận việc đó.",
  "ex-9-3-2": "Bạn có muốn đi dự tiệc hay không?",
  "ex-9-3-3": "Tôi đã đỗ kỳ thi!",
  "ex-9-3-4": "Taxi đã đến — chúng ta phải đi ngay!",
  "ex-9-4-1": "Sửa lỗi: Well made! → Well ___!",
  "ex-9-4-2": "Sửa lỗi: How about go out → How about ___ out",
  "ex-9-4-3": "Sửa lỗi: Let go to → Let's ___ to",
  "ex-9-4-4": "Sửa lỗi: it isn't matter → it doesn't ___",
  "ex-9-4-5": "Sửa lỗi: Why don't we going → Why don't we ___",
  "ex-11-1-1": "Bạn dùng chảo rán để uống nước.",
  "ex-11-1-2": "Tủ lạnh lạnh hơn ngăn đông.",
  "ex-11-1-3": "Khăn lau bàn dùng để pha trà.",
  "ex-11-2-1": "Cà phê ở đâu? → Nó ở trong ___.",
  "ex-11-2-2": "Nồi nấu ở đâu? → Nó ở trên ___.",
  "ex-11-3-1": "Để pha cà phê tôi cần máy pha cà phê, cốc và ___.",
  "ex-11-3-2": "Để pha trà tôi cần ấm trà và ___.",
  "ex-11-3-3": "Để chiên món gì đó tôi cần ___ và bếp nấu.",
  "ex-11-3-4": "Để ăn tôi cần đĩa, dao và ___.",
  "ex-11-3-5": "Để uống nước tôi cần ___ hoặc cốc.",
  "ex-11-3-6": "Để nấu bữa tối trong hai phút tôi cần ___.",
  "ex-11-3-7": "Để rửa bát tôi cần nước rửa chén, bồn rửa và ___.",
  "ex-11-3-8": "Để giặt quần áo tôi cần máy giặt ___.",
  "ex-11-w1": "Cho sữa vào ___ — bên trong lạnh.",
  "ex-11-w2": "Bật ___ để lấy nước.",
  "ex-11-w3": "Rửa bát trong ___.",
  "ex-11-w4": "Vứt rác vào ___.",
  "ex-11-w5": "Nấu cơm trong ___.",
  "ex-11-w4b": "Lau bát bằng khăn ___.",
  "ex-12-1-2": "Mục 2 trong hình phòng ngủ: ___",
  "ex-12-1-3": "Mục 3: ___",
  "ex-12-1-4": "Mục 4: ___",
  "ex-12-1-5": "Mục 5: ___",
  "ex-12-1-6": "Mục 6: ___",
  "ex-12-1-7": "Mục 7: tủ đầu giường ___",
  "ex-12-1-8": "Mục 8: tủ đầu giường ___",
  "ex-12-1-9": "Mục 9: đồng hồ báo thức ___",
  "ex-12-1-10": "Mục 10: tủ ngăn kéo ___",
  "ex-12-3-1": "Anne đang lau ___.",
  "ex-12-3-2": "Selim và Umit đang rửa ___.",
  "ex-12-3-3": "Bà Park đang ___ giường.",
  "ex-12-3-4": "Ông Park đang ___ tắm.",
  "ex-12-3-5": "Jaime đang ___ quần áo.",
  "ex-12-3-6": "Lee đang tắt ___.",
  "ex-12-6-1": "Tôi thường ___ giường lúc 10 giờ 30.",
  "ex-12-6-2": "Tôi ___ và lên giường.",
  "ex-12-6-3": "Tôi tắt ___ đèn và chìm vào giấc ngủ.",
  "ex-12-6-4": "Tôi ___ dậy khi đồng hồ báo thức reo.",
  "ex-12-6-5": "Tôi ___ răng và mặc quần áo.",
  "ex-13-1-2": "Chỗ hai hoặc ba người có thể ngồi: một ___",
  "ex-13-1-3": "Chỗ bạn có thể đặt cốc xuống: bàn ___",
  "ex-13-1-4": "Thứ bạn có thể nhìn trên tường: một ___",
  "ex-13-1-5": "Thứ dùng để bật hoặc tắt đèn: công tắc ___",
  "ex-13-1-6": "Thứ dùng để nghe nhạc: một ___",
  "ex-13-1-7": "Thứ dưới chân bạn: thảm hoặc ___",
  "ex-13-1-8": "Thứ dùng đổi kênh TV: điều khiển ___",
  "ex-13-2": "Ghép hai phần cụm từ thành câu hoàn chỉnh",
  "ex-13-3-1": "Sửa lỗi: Let's just relax us at home. → Let's just relax ___ home.",
  "ex-13-3-2": "Sửa lỗi: I don't often listen the radio. → I don't often listen ___ the radio.",
  "ex-13-3-3": "Sửa lỗi: We need some more bookshelfs. → We need some more ___.",
  "ex-13-3-4": "Sửa lỗi: I watched at television. → I watched ___ yesterday.",
  "ex-13-3-5": "Sửa lỗi: Please make the curtains. → Please ___ the curtains.",
  "ex-13-3-6": "Sửa lỗi: Nice furnitures in his house. → Nice ___ in his house.",
  "ex-13-w1": "Bạn đóng ___ được không? Trời sắp tối rồi.",
  "ex-13-w2": "Đưa điều khiển ___ — tôi muốn bật TV.",
  "ex-13-w3": "Đặt sách lên ___.",
  "ex-13-w4": "Tôi thích ___ trên ghế bành sau giờ làm.",
  "ex-13-w5": "Bật ___ đèn lên, làm ơn.",
  "ex-14-1-1": "Giáo viên làm việc ở trường / cao đẳng / ___.",
  "ex-14-1-2": "Bác sĩ làm việc ở bệnh viện hoặc ___.",
  "ex-14-1-3": "Bồi bàn làm việc ở nhà hàng hoặc ___.",
  "ex-14-1-4": "Thư ký làm việc ở ___.",
  "ex-14-1-5": "Nhân viên bán hàng làm việc ở ___.",
  "ex-14-1-6": "Thợ làm tóc làm việc ở tiệm làm đẹp ___",
  "ex-14-4-2": "Cô ấy muốn trở thành ___.",
  "ex-14-4-3": "Anh ấy làm ___ lái xe.",
  "ex-14-4-4": "Dì tôi là ___ ở bệnh viện.",
  "ex-14-4-5": "___ đã sửa xe cho tôi.",
  "ex-14-4-6": "Cô ấy là ___ ở một công ty lớn.",
  "ex-14-x-1": "Người làm việc trên xe buýt là ___",
  "ex-14-x-2": "Người viết sách là ___",
  "ex-14-x-3": "Người làm việc ở trường là ___",
  "ex-14-x-4": "___ làm việc cùng bác sĩ ở bệnh viện.",
  "ex-14-w1": "___ điều khiển giao thông và phạt đỗ xe.",
  "ex-14-w2": "___ làm việc ở thư viện.",
  "ex-14-w3": "___ ngân hàng làm việc sau quầy.",
  "ex-14-w4": "___ bảo vệ an toàn cho người dân trong thị trấn.",
  "ex-15-1": "Ghép đồ dùng học tập bên trái với nghĩa tiếng Việt bên phải",
  "ex-15-4-1": "Cô ấy ___ tốt trong tất cả kỳ thi.",
  "ex-15-4-2": "Anh ấy ___ kỳ thi tuần trước.",
  "ex-15-4-3": "Tôi cần ___ / làm bài tập về nhà.",
  "ex-15-4-4": "Nếu bạn ___ tất cả kỳ thi, bạn có thể ăn mừng.",
  "ex-15-4-5": "Tôi ___ đại học năm sau.",
  "ex-15-4-6": "Anh ấy ___ bài kiểm tra toán — được 30%.",
  "ex-15-4-7": "Chúng tôi ___ tiếng Anh mỗi ngày.",
  "ex-15-4-8": "Bạn ___ môn gì ở trường?",
  "ex-15-4-9": "Tôi hy vọng ___ điểm tốt.",
  "ex-15-w1": "Viết câu trả lời vào ___ của bạn.",
  "ex-15-w2": "Giáo viên viết lên ___.",
  "ex-15-w3": "Ghim thông báo bằng ___ vẽ.",
  "ex-15-w4": "Đo đường thẳng bằng ___.",
  "ex-15-w5": "Gọt bút chì bằng ___ gọt bút chì.",
  "ex-15-w6": "Dùng ___ để xóa lỗi sai.",
  "ex-15-w7": "Đọc chương 3 trong ___ của bạn.",
  "ex-15-w8": "Viết bằng ___ hoặc bút mực.",
  "ex-15-w9": "___ dùng để viết bằng mực.",
  "ex-15-w10": "Một tờ ___ để viết lên.",
};

/** Unit mẫu body-a1 + food-a1 */
export const SAMPLE_UNITS_PROMPT_VI: Readonly<Record<string, string>> = {
  "ex-3-1-1": "Sắp xếp các chữ cái: eken → ___",
  "ex-3-1-2": "Sắp xếp các chữ cái: osen → ___",
  "ex-3-1-3": "Sắp xếp các chữ cái: rathe → ___",
  "ex-3-1-4": "Sắp xếp các chữ cái: hamcost → ___",
  "ex-3-1-5": "Sắp xếp các chữ cái: olderush → ___",
  "ex-3-1-8": "Sắp xếp các chữ cái: buhtm → ___",
  "ex-3-2-1": "Một bàn chân có năm ___.",
  "ex-3-2-2": "Người trưởng thành có 32 ___.",
  "ex-3-2-3": "Bạn ngửi bằng ___.",
  "ex-3-2-4": "___ là biểu tượng của tình yêu.",
  "ex-3-2-7": "Nhóm ___ của bạn có thể là A, B, AB hoặc O.",
  "ex-3-2-8": "Bạn suy nghĩ bằng ___.",
  "ex-3-3-1": "Sửa lỗi số nhiều: That woman has got very big foots. → That woman has got very big ___.",
  "ex-3-3-2": "Thêm tính từ sở hữu: My grandfather has a pain in ___ shoulder.",
  "ex-3-3-3": "Sửa lỗi số nhiều: The baby has already got two tooths. → two ___.",
  "ex-3-3-5": "Hair không đếm được: My hairs are dirty. → My ___ is dirty.",
  "ex-3-4-1": "Ghép từ chỉ bộ phận cơ thể: ___ball (môn thể thao)",
  "ex-3-4-3": "Ghép danh từ: ___brush (lược chải tóc)",
  "ex-3-4-5": "Ghép danh từ: ___bag (túi xách)",
  "ex-3-5-1": "Ghép từ tiếng Anh bên trái với nghĩa tiếng Việt bên phải",
  "ex-10-1-1": "___ rất phổ biến ở Nhật Bản.",
  "ex-10-1-2": "___ và ___ rất phổ biến ở Ý.",
  "ex-10-1-3": "Khoai tây chiên được làm từ ___.",
  "ex-10-1-4": "Nhiều người Anh ăn ___.",
  "ex-10-1-5": "Hamburger được làm từ ___.",
  "ex-10-1-6": "___ là xúc xích kẹp trong một miếng bánh mì.",
  "ex-10-5-1": "Người ăn chay (vegetarian) không ăn gì?",
  "ex-10-5-2": "Tỏi (garlic) là loại gì?",
  "ex-10-5-3": "Bạn cho ___ vào cà phê.",
  "ex-10-5-4": "Cách viết nào đúng? (dứa / pineapple)",
  "ex-10-5-5": "Âm đầu của onion giống âm đầu từ nào?",
  "ex-10-5-6": "Quả lê (pear) là gì?",
};
