import { assertExerciseCount, cloze, match, mcq } from "./eviu-elementary-curated-helpers";
import type { VocabularyExercise } from "@/lib/vocabulary/vocabulary-unit-types";

const UNIT_31: VocabularyExercise[] = [
  match("ex-pre-31-1", "31 · Ghép từ với nghĩa", [
    { left: "handout", right: "tài liệu phát tay trong giờ học" },
    { left: "whiteboard", right: "bảng trắng dùng trong lớp học" },
    { left: "attendance", right: "sĩ số hoặc điểm danh" },
    { left: "timetable", right: "thời khóa biểu theo tiết học" },
    { left: "pair work", right: "hoạt động làm việc theo cặp" },
    { left: "group discussion", right: "thảo luận nhóm trong lớp" },
  ]),
  cloze("ex-pre-31-2", "31 · Điền từ", "Please keep the ___ for next lesson.", "handout", ["Handout"]),
  cloze("ex-pre-31-3", "31 · Điền từ", "Write your answers on the ___.", "whiteboard", ["Whiteboard"]),
  cloze("ex-pre-31-4", "31 · Điền từ", "___ is taken at the start of class.", "Attendance", ["attendance"]),
  cloze("ex-pre-31-5", "31 · Điền từ", "Check your ___ before Monday.", "timetable", ["Timetable"]),
  cloze("ex-pre-31-6", "31 · Điền cụm", "We will do ___ for ten minutes.", "pair work", ["Pair work"]),
  cloze("ex-pre-31-7", "31 · Điền từ", "Please ___ your homework by Friday.", "submit", ["Submit"]),
  cloze("ex-pre-31-8", "31 · Điền từ", "I ___ vocabulary every evening.", "revise", ["Revise"]),
  mcq("ex-pre-31-9", "31 · Chọn đáp án", "Which phrase means 'giơ tay xin phát biểu'?", "b", [
    { key: "a", label: "take notes" },
    { key: "b", label: "raise your hand" },
    { key: "c", label: "submit" },
    { key: "d", label: "pair work" },
  ]),
  mcq("ex-pre-31-10", "31 · Chọn đáp án", "A ___ is a phiếu bài tập trên lớp.", "c", [
    { key: "a", label: "handout" },
    { key: "b", label: "instruction" },
    { key: "c", label: "worksheet" },
    { key: "d", label: "deadline" },
  ]),
  mcq("ex-pre-31-11", "31 · Chọn đáp án", "To ___ means to ghi chép ý chính khi học.", "a", [
    { key: "a", label: "take notes" },
    { key: "b", label: "clarify" },
    { key: "c", label: "participate" },
    { key: "d", label: "revise" },
  ]),
  cloze("ex-pre-31-12", "31 · Điền cụm", "We did a ___ in class.", "pronunciation drill", ["Pronunciation drill"]),
  cloze("ex-pre-31-13", "31 · Điền từ", "The project ___ is next Tuesday.", "deadline", ["Deadline"]),
  mcq("ex-pre-31-14", "31 · Chọn đáp án", "To ___ means to làm rõ điều chưa hiểu.", "d", [
    { key: "a", label: "submit" },
    { key: "b", label: "participate" },
    { key: "c", label: "revise" },
    { key: "d", label: "clarify" },
  ]),
];

const UNIT_32: VocabularyExercise[] = [
  match("ex-pre-32-1", "32 · Ghép từ với nghĩa", [
    { left: "curriculum", right: "chương trình học chính thức" },
    { left: "semester", right: "học kỳ trong năm học" },
    { left: "compulsory subject", right: "môn học bắt buộc" },
    { left: "optional subject", right: "môn học tự chọn" },
    { left: "report card", right: "phiếu kết quả học tập" },
    { left: "school uniform", right: "đồng phục học sinh" },
  ]),
  cloze("ex-pre-32-2", "32 · Điền từ", "The ___ includes science and arts.", "curriculum", ["Curriculum"]),
  cloze("ex-pre-32-3", "32 · Điền từ", "This ___ ends in December.", "semester", ["Semester"]),
  cloze("ex-pre-32-4", "32 · Điền cụm", "Maths is a ___.", "compulsory subject", ["Compulsory subject"]),
  cloze("ex-pre-32-5", "32 · Điền cụm", "Music is an ___.", "optional subject", ["Optional subject"]),
  cloze("ex-pre-32-6", "32 · Điền cụm", "I showed my ___ to my parents.", "report card", ["Report card"]),
  cloze("ex-pre-32-7", "32 · Điền cụm", "Our ___ is blue and white.", "school uniform", ["School uniform"]),
  cloze("ex-pre-32-8", "32 · Điền từ", "There is an ___ every Monday morning.", "assembly", ["Assembly"]),
  mcq("ex-pre-32-9", "32 · Chọn đáp án", "A ___ is a điểm số hoặc mức đánh giá.", "b", [
    { key: "a", label: "term" },
    { key: "b", label: "grade" },
    { key: "c", label: "detention" },
    { key: "d", label: "discipline" },
  ]),
  mcq("ex-pre-32-10", "32 · Chọn đáp án", "The ___ welcomed new students.", "a", [
    { key: "a", label: "principal" },
    { key: "b", label: "headteacher" },
    { key: "c", label: "candidate" },
    { key: "d", label: "mentor" },
  ]),
  mcq("ex-pre-32-11", "32 · Chọn đáp án", "Students meet in the ___ at break.", "c", [
    { key: "a", label: "canteen" },
    { key: "b", label: "assembly" },
    { key: "c", label: "playground" },
    { key: "d", label: "detention" },
  ]),
  cloze("ex-pre-32-12", "32 · Điền cụm", "The ___ was very educational.", "school trip", ["School trip"]),
  cloze("ex-pre-32-13", "32 · Điền từ", "Good ___ creates a better learning space.", "discipline", ["Discipline"]),
  mcq("ex-pre-32-14", "32 · Chọn đáp án", "The ___ increased this year.", "d", [
    { key: "a", label: "report card" },
    { key: "b", label: "curriculum" },
    { key: "c", label: "semester" },
    { key: "d", label: "tuition fee" },
  ]),
];

const UNIT_33: VocabularyExercise[] = [
  match("ex-pre-33-1", "33 · Ghép từ với nghĩa", [
    { left: "mock exam", right: "kỳ thi thử trước kỳ thi chính" },
    { left: "invigilator", right: "giám thị coi thi" },
    { left: "candidate", right: "thí sinh tham gia kỳ thi" },
    { left: "marking scheme", right: "thang điểm và tiêu chí chấm" },
    { left: "time management", right: "kỹ năng phân bổ thời gian làm bài" },
    { left: "band score", right: "mức điểm theo thang bậc" },
  ]),
  cloze("ex-pre-33-2", "33 · Điền cụm", "We take a ___ every month.", "mock exam", ["Mock exam"]),
  cloze("ex-pre-33-3", "33 · Điền cụm", "Do not write on the ___ first.", "exam paper", ["Exam paper"]),
  cloze("ex-pre-33-4", "33 · Điền từ", "The ___ checked our IDs.", "invigilator", ["Invigilator"]),
  cloze("ex-pre-33-5", "33 · Điền từ", "Each ___ has a number.", "candidate", ["Candidate"]),
  cloze("ex-pre-33-6", "33 · Điền cụm", "Read the ___ after practice.", "marking scheme", ["Marking scheme"]),
  cloze("ex-pre-33-7", "33 · Điền cụm", "___ is crucial in reading tests.", "Time management", ["time management"]),
  cloze("ex-pre-33-8", "33 · Điền cụm", "My target ___ is 6.5.", "band score", ["Band score"]),
  mcq("ex-pre-33-9", "33 · Chọn đáp án", "To ___ means to nghe lấy ý chính.", "a", [
    { key: "a", label: "listen for gist" },
    { key: "b", label: "scan for details" },
    { key: "c", label: "proofread" },
    { key: "d", label: "retake" },
  ]),
  mcq("ex-pre-33-10", "33 · Chọn đáp án", "To ___ means to quét nhanh để tìm chi tiết.", "b", [
    { key: "a", label: "listen for gist" },
    { key: "b", label: "scan for details" },
    { key: "c", label: "proofread" },
    { key: "d", label: "retake" },
  ]),
  mcq("ex-pre-33-11", "33 · Chọn đáp án", "A ___ is an đáp án nhiễu trong bài trắc nghiệm.", "c", [
    { key: "a", label: "pass mark" },
    { key: "b", label: "sample answer" },
    { key: "c", label: "distractor" },
    { key: "d", label: "revision plan" },
  ]),
  cloze("ex-pre-33-12", "33 · Điền từ", "Always ___ your writing task.", "proofread", ["Proofread"]),
  cloze("ex-pre-33-13", "33 · Điền cụm", "Make a weekly ___.", "revision plan", ["Revision plan"]),
  mcq("ex-pre-33-14", "33 · Chọn đáp án", "The ___ is 50 percent.", "d", [
    { key: "a", label: "band score" },
    { key: "b", label: "word stress" },
    { key: "c", label: "grammar accuracy" },
    { key: "d", label: "pass mark" },
  ]),
];

const UNIT_34: VocabularyExercise[] = [
  match("ex-pre-34-1", "34 · Ghép từ với nghĩa", [
    { left: "undergraduate", right: "sinh viên bậc cử nhân" },
    { left: "postgraduate", right: "học viên sau đại học" },
    { left: "campus", right: "khuôn viên trường đại học" },
    { left: "lecture hall", right: "giảng đường lớn của đại học" },
    { left: "seminar", right: "buổi học thảo luận chuyên sâu" },
    { left: "tutorial", right: "buổi hướng dẫn nhóm nhỏ" },
  ]),
  cloze("ex-pre-34-2", "34 · Điền từ", "She is an ___ in economics.", "undergraduate", ["Undergraduate"]),
  cloze("ex-pre-34-3", "34 · Điền từ", "He is a ___ student.", "postgraduate", ["Postgraduate"]),
  cloze("ex-pre-34-4", "34 · Điền từ", "The ___ is near the city center.", "campus", ["Campus"]),
  cloze("ex-pre-34-5", "34 · Điền cụm", "Our class is in ___ B.", "lecture hall", ["Lecture hall"]),
  cloze("ex-pre-34-6", "34 · Điền từ", "We had a ___ on media ethics.", "seminar", ["Seminar"]),
  cloze("ex-pre-34-7", "34 · Điền từ", "The ___ is every Thursday afternoon.", "tutorial", ["Tutorial"]),
  cloze("ex-pre-34-8", "34 · Điền từ", "This module is worth three ___.", "credits", ["Credits", "credit", "Credit"]),
  mcq("ex-pre-34-9", "34 · Chọn đáp án", "A ___ is a chuyên ngành chính của sinh viên.", "b", [
    { key: "a", label: "minor" },
    { key: "b", label: "major" },
    { key: "c", label: "module" },
    { key: "d", label: "credit" },
  ]),
  mcq("ex-pre-34-10", "34 · Chọn đáp án", "He is writing his ___ now.", "a", [
    { key: "a", label: "thesis" },
    { key: "b", label: "tutorial" },
    { key: "c", label: "seminar" },
    { key: "d", label: "module" },
  ]),
  mcq("ex-pre-34-11", "34 · Chọn đáp án", "She received a full ___.", "c", [
    { key: "a", label: "tuition waiver" },
    { key: "b", label: "dormitory" },
    { key: "c", label: "scholarship" },
    { key: "d", label: "credit" },
  ]),
  cloze("ex-pre-34-12", "34 · Điền cụm", "Talk to your ___ first.", "academic advisor", ["Academic advisor"]),
  cloze("ex-pre-34-13", "34 · Điền từ", "You must ___ before the deadline.", "enrol", ["Enrol", "enroll", "Enroll"]),
  mcq("ex-pre-34-14", "34 · Chọn đáp án", "He will ___ next summer.", "b", [
    { key: "a", label: "defer" },
    { key: "b", label: "graduate" },
    { key: "c", label: "enrol" },
    { key: "d", label: "enroll" },
  ]),
];

const UNIT_35: VocabularyExercise[] = [
  match("ex-pre-35-1", "35 · Ghép từ với nghĩa", [
    { left: "occupation", right: "nghề nghiệp của một người" },
    { left: "profession", right: "nghề chuyên môn cần đào tạo" },
    { left: "full-time", right: "làm việc toàn thời gian" },
    { left: "part-time", right: "làm việc bán thời gian" },
    { left: "job vacancy", right: "vị trí tuyển dụng còn trống" },
    { left: "qualification", right: "bằng cấp hoặc chứng chỉ" },
  ]),
  cloze("ex-pre-35-2", "35 · Điền từ", "What is your ___?", "occupation", ["Occupation"]),
  cloze("ex-pre-35-3", "35 · Điền từ", "Teaching is a respected ___.", "profession", ["Profession"]),
  cloze("ex-pre-35-4", "35 · Điền cụm", "I have a ___ position.", "full-time", ["Full-time"]),
  cloze("ex-pre-35-5", "35 · Điền cụm", "Many students have ___ jobs.", "part-time", ["Part-time"]),
  cloze("ex-pre-35-6", "35 · Điền cụm", "I saw a ___ online.", "job vacancy", ["Job vacancy"]),
  cloze("ex-pre-35-7", "35 · Điền từ", "You need the right ___.", "qualification", ["Qualification"]),
  cloze("ex-pre-35-8", "35 · Điền từ", "She has five years of ___.", "experience", ["Experience"]),
  mcq("ex-pre-35-9", "35 · Chọn đáp án", "A ___ is a kỳ thực tập nghề nghiệp.", "b", [
    { key: "a", label: "shift" },
    { key: "b", label: "internship" },
    { key: "c", label: "trade" },
    { key: "d", label: "promotion" },
  ]),
  mcq("ex-pre-35-10", "35 · Chọn đáp án", "Factory workers earn hourly ___.", "c", [
    { key: "a", label: "salary" },
    { key: "b", label: "promotion" },
    { key: "c", label: "wages" },
    { key: "d", label: "qualification" },
  ]),
  mcq("ex-pre-35-11", "35 · Chọn đáp án", "To ___ means to xin nghỉ việc tự nguyện.", "b", [
    { key: "a", label: "recruit" },
    { key: "b", label: "resign" },
    { key: "c", label: "promote" },
    { key: "d", label: "apply" },
  ]),
  cloze("ex-pre-35-12", "35 · Điền từ", "My ___ starts at 7 a.m.", "shift", ["Shift"]),
  cloze("ex-pre-35-13", "35 · Điền từ", "The ___ is paid on the last day.", "salary", ["Salary"]),
  mcq("ex-pre-35-14", "35 · Chọn đáp án", "She got a ___ after two years.", "d", [
    { key: "a", label: "internship" },
    { key: "b", label: "job vacancy" },
    { key: "c", label: "shift" },
    { key: "d", label: "promotion" },
  ]),
];

const UNIT_36: VocabularyExercise[] = [
  match("ex-pre-36-1", "36 · Ghép từ với nghĩa", [
    { left: "workload", right: "khối lượng công việc phải xử lý" },
    { left: "responsibility", right: "trách nhiệm trong vai trò làm việc" },
    { left: "colleague", right: "đồng nghiệp cùng cơ quan" },
    { left: "supervisor", right: "người giám sát trực tiếp" },
    { left: "remote work", right: "làm việc từ xa không đến văn phòng" },
    { left: "work-life balance", right: "cân bằng giữa việc và cuộc sống" },
  ]),
  cloze("ex-pre-36-2", "36 · Điền từ", "My ___ is heavy this week.", "workload", ["Workload"]),
  cloze("ex-pre-36-3", "36 · Điền cụm", "___ affects sleep.", "Deadline pressure", ["deadline pressure"]),
  cloze("ex-pre-36-4", "36 · Điền từ", "My main ___ is client support.", "responsibility", ["Responsibility"]),
  cloze("ex-pre-36-5", "36 · Điền cụm", "I update my ___ every morning.", "task list", ["Task list"]),
  cloze("ex-pre-36-6", "36 · Điền từ", "You should ___ urgent tasks.", "prioritise", ["Prioritise", "prioritize", "Prioritize"]),
  cloze("ex-pre-36-7", "36 · Điền từ", "I can ___ in a busy office.", "multitask", ["Multitask"]),
  cloze("ex-pre-36-8", "36 · Điền từ", "I ___ with the sales team.", "coordinate", ["Coordinate"]),
  mcq("ex-pre-36-9", "36 · Chọn đáp án", "A ___ runs weekly check-ins.", "c", [
    { key: "a", label: "supervisor" },
    { key: "b", label: "colleague" },
    { key: "c", label: "team lead" },
    { key: "d", label: "intern" },
  ]),
  mcq("ex-pre-36-10", "36 · Chọn đáp án", "We follow a ___ schedule.", "b", [
    { key: "a", label: "remote work" },
    { key: "b", label: "hybrid schedule" },
    { key: "c", label: "overtime" },
    { key: "d", label: "task list" },
  ]),
  mcq("ex-pre-36-11", "36 · Chọn đáp án", "To ___ means to báo cáo trực tiếp cho ai.", "a", [
    { key: "a", label: "report to" },
    { key: "b", label: "commute" },
    { key: "c", label: "multitask" },
    { key: "d", label: "prioritise" },
  ]),
  cloze("ex-pre-36-12", "36 · Điền từ", "I had to do ___ yesterday.", "overtime", ["Overtime"]),
  cloze("ex-pre-36-13", "36 · Điền cụm", "My ___ is next week.", "performance review", ["Performance review"]),
  mcq("ex-pre-36-14", "36 · Chọn đáp án", "Good ___ prevents burnout.", "b", [
    { key: "a", label: "deadline pressure" },
    { key: "b", label: "work-life balance" },
    { key: "c", label: "overtime" },
    { key: "d", label: "workload" },
  ]),
];

const UNIT_37: VocabularyExercise[] = [
  match("ex-pre-37-1", "37 · Ghép từ với nghĩa", [
    { left: "career path", right: "lộ trình phát triển nghề nghiệp" },
    { left: "career goal", right: "mục tiêu nghề nghiệp dài hạn" },
    { left: "skill set", right: "bộ kỹ năng phục vụ công việc" },
    { left: "mentor", right: "người cố vấn nghề nghiệp" },
    { left: "networking", right: "xây dựng quan hệ nghề nghiệp" },
    { left: "leadership", right: "năng lực dẫn dắt đội nhóm" },
  ]),
  cloze("ex-pre-37-2", "37 · Điền cụm", "He has a clear ___.", "career path", ["Career path"]),
  cloze("ex-pre-37-3", "37 · Điền cụm", "Set a realistic ___.", "career goal", ["Career goal"]),
  cloze("ex-pre-37-4", "37 · Điền cụm", "Your ___ is strong.", "skill set", ["Skill set"]),
  cloze("ex-pre-37-5", "37 · Điền từ", "I need to ___ in data analysis.", "upskill", ["Upskill"]),
  cloze("ex-pre-37-6", "37 · Điền từ", "Many workers ___ after automation.", "reskill", ["Reskill"]),
  cloze("ex-pre-37-7", "37 · Điền từ", "___ helped her find new opportunities.", "Networking", ["networking"]),
  cloze("ex-pre-37-8", "37 · Điền từ", "A ___ can guide your decisions.", "mentor", ["Mentor"]),
  mcq("ex-pre-37-9", "37 · Chọn đáp án", "The company offers a ___ program.", "b", [
    { key: "a", label: "networking" },
    { key: "b", label: "mentorship" },
    { key: "c", label: "certification" },
    { key: "d", label: "portfolio" },
  ]),
  mcq("ex-pre-37-10", "37 · Chọn đáp án", "___ can worry employers.", "c", [
    { key: "a", label: "career break" },
    { key: "b", label: "mentorship" },
    { key: "c", label: "job hopping" },
    { key: "d", label: "networking" },
  ]),
  mcq("ex-pre-37-11", "37 · Chọn đáp án", "Show your ___ at interviews.", "d", [
    { key: "a", label: "career ladder" },
    { key: "b", label: "skill set" },
    { key: "c", label: "certification" },
    { key: "d", label: "portfolio" },
  ]),
  cloze("ex-pre-37-12", "37 · Điền cụm", "Training supports ___.", "professional development", ["Professional development"]),
  cloze("ex-pre-37-13", "37 · Điền cụm", "She moved up the ___ quickly.", "career ladder", ["Career ladder"]),
  mcq("ex-pre-37-14", "37 · Chọn đáp án", "This achievement helps you ___.", "a", [
    { key: "a", label: "stand out" },
    { key: "b", label: "reskill" },
    { key: "c", label: "upskill" },
    { key: "d", label: "network" },
  ]),
];

const UNIT_38: VocabularyExercise[] = [
  match("ex-pre-38-1", "38 · Ghép từ với nghĩa", [
    { left: "workstation", right: "bàn làm việc kèm thiết bị" },
    { left: "meeting room", right: "phòng họp cho nhóm làm việc" },
    { left: "agenda", right: "chương trình nội dung cuộc họp" },
    { left: "attachment", right: "tệp đính kèm trong email" },
    { left: "inbox", right: "hộp thư nhận email" },
    { left: "office etiquette", right: "quy tắc ứng xử nơi công sở" },
  ]),
  cloze("ex-pre-38-2", "38 · Điền từ", "Each employee has a ___.", "workstation", ["Workstation"]),
  cloze("ex-pre-38-3", "38 · Điền cụm", "___ are kept in that cabinet.", "Office supplies", ["office supplies"]),
  cloze("ex-pre-38-4", "38 · Điền từ", "We need more ___ this month.", "stationery", ["Stationery"]),
  cloze("ex-pre-38-5", "38 · Điền cụm", "The ___ is very long.", "printer queue", ["Printer queue"]),
  cloze("ex-pre-38-6", "38 · Điền từ", "The ___ is out of paper.", "photocopier", ["Photocopier"]),
  cloze("ex-pre-38-7", "38 · Điền cụm", "Book the ___ in advance.", "meeting room", ["Meeting room"]),
  cloze("ex-pre-38-8", "38 · Điền cụm", "We have a ___ at 3 p.m.", "conference call", ["Conference call"]),
  mcq("ex-pre-38-9", "38 · Chọn đáp án", "___ is part of my role.", "b", [
    { key: "a", label: "office etiquette" },
    { key: "b", label: "minute-taking" },
    { key: "c", label: "hot desk" },
    { key: "d", label: "stationery" },
  ]),
  mcq("ex-pre-38-10", "38 · Chọn đáp án", "Please send the ___ beforehand.", "a", [
    { key: "a", label: "agenda" },
    { key: "b", label: "attachment" },
    { key: "c", label: "outbox" },
    { key: "d", label: "inbox" },
  ]),
  mcq("ex-pre-38-11", "38 · Chọn đáp án", "To ___ means to đặt trước phòng họp.", "b", [
    { key: "a", label: "file a document" },
    { key: "b", label: "book a room" },
    { key: "c", label: "schedule a meeting" },
    { key: "d", label: "take minutes" },
  ]),
  cloze("ex-pre-38-12", "38 · Điền cụm", "I wrote a ___ to clients.", "follow-up email", ["Follow-up email"]),
  cloze("ex-pre-38-13", "38 · Điền từ", "My ___ is full today.", "inbox", ["Inbox"]),
  mcq("ex-pre-38-14", "38 · Chọn đáp án", "Our team uses a ___ system.", "d", [
    { key: "a", label: "printer queue" },
    { key: "b", label: "conference call" },
    { key: "c", label: "workstation" },
    { key: "d", label: "hot desk" },
  ]),
];

const UNIT_39: VocabularyExercise[] = [
  match("ex-pre-39-1", "39 · Ghép từ với nghĩa", [
    { left: "startup", right: "công ty khởi nghiệp giai đoạn đầu" },
    { left: "founder", right: "người sáng lập công ty" },
    { left: "shareholder", right: "cổ đông sở hữu cổ phần doanh nghiệp" },
    { left: "board of directors", right: "hội đồng quản trị công ty" },
    { left: "business model", right: "mô hình tạo giá trị và lợi nhuận" },
    { left: "cash flow", right: "dòng tiền vào ra của công ty" },
  ]),
  cloze("ex-pre-39-2", "39 · Điền từ", "He launched a ___ in fintech.", "startup", ["Startup"]),
  cloze("ex-pre-39-3", "39 · Điền từ", "The ___ pitched to investors.", "founder", ["Founder"]),
  cloze("ex-pre-39-4", "39 · Điền từ", "She is the ___ of the app.", "co-founder", ["Co-founder", "cofounder", "Cofounder"]),
  cloze("ex-pre-39-5", "39 · Điền từ", "___ voted on the proposal.", "Shareholders", ["shareholders", "Shareholder", "shareholder"]),
  cloze("ex-pre-39-6", "39 · Điền cụm", "The ___ approved the budget.", "board of directors", ["Board of directors"]),
  cloze("ex-pre-39-7", "39 · Điền từ", "I work in the marketing ___.", "department", ["Department"]),
  cloze("ex-pre-39-8", "39 · Điền cụm", "___ handles recruitment.", "Human resources", ["human resources"]),
  mcq("ex-pre-39-9", "39 · Chọn đáp án", "Subscription is our main ___.", "d", [
    { key: "a", label: "overhead cost" },
    { key: "b", label: "business model" },
    { key: "c", label: "cash flow" },
    { key: "d", label: "revenue stream" },
  ]),
  mcq("ex-pre-39-10", "39 · Chọn đáp án", "Their ___ is scalable.", "b", [
    { key: "a", label: "merger" },
    { key: "b", label: "business model" },
    { key: "c", label: "stakeholder" },
    { key: "d", label: "operations" },
  ]),
  mcq("ex-pre-39-11", "39 · Chọn đáp án", "Managers should ___ effectively.", "c", [
    { key: "a", label: "outsource" },
    { key: "b", label: "expand" },
    { key: "c", label: "delegate" },
    { key: "d", label: "set up" },
  ]),
  cloze("ex-pre-39-12", "39 · Điền từ", "Rent is a major ___ cost.", "overhead", ["Overhead"]),
  cloze("ex-pre-39-13", "39 · Điền cụm", "Healthy ___ keeps business stable.", "cash flow", ["Cash flow"]),
  mcq("ex-pre-39-14", "39 · Chọn đáp án", "The ___ created a larger group.", "a", [
    { key: "a", label: "merger" },
    { key: "b", label: "startup" },
    { key: "c", label: "founder" },
    { key: "d", label: "department" },
  ]),
];

const UNIT_40: VocabularyExercise[] = [
  match("ex-pre-40-1", "40 · Ghép từ với nghĩa", [
    { left: "turnover", right: "doanh thu trong một giai đoạn" },
    { left: "profit margin", right: "biên lợi nhuận sau chi phí" },
    { left: "net profit", right: "lợi nhuận ròng sau tất cả chi phí" },
    { left: "budget", right: "ngân sách phân bổ cho hoạt động" },
    { left: "invoice", right: "hóa đơn yêu cầu thanh toán" },
    { left: "asset", right: "tài sản có giá trị kinh tế" },
  ]),
  cloze("ex-pre-40-2", "40 · Điền từ", "The company doubled its ___.", "turnover", ["Turnover"]),
  cloze("ex-pre-40-3", "40 · Điền cụm", "Low ___ worries investors.", "profit margin", ["Profit margin"]),
  cloze("ex-pre-40-4", "40 · Điền cụm", "___ increased this quarter.", "Net profit", ["net profit"]),
  cloze("ex-pre-40-5", "40 · Điền từ", "The firm reported a small ___.", "loss", ["Loss"]),
  cloze("ex-pre-40-6", "40 · Điền từ", "We need a realistic ___.", "budget", ["Budget"]),
  cloze("ex-pre-40-7", "40 · Điền từ", "The sales ___ is optimistic.", "forecast", ["Forecast"]),
  cloze("ex-pre-40-8", "40 · Điền từ", "Please send the ___ today.", "invoice", ["Invoice"]),
  mcq("ex-pre-40-9", "40 · Chọn đáp án", "Keep the ___ for reimbursement.", "b", [
    { key: "a", label: "invoice" },
    { key: "b", label: "receipt" },
    { key: "c", label: "budget" },
    { key: "d", label: "forecast" },
  ]),
  mcq("ex-pre-40-10", "40 · Chọn đáp án", "They took a ___ to buy equipment.", "c", [
    { key: "a", label: "debt" },
    { key: "b", label: "investment" },
    { key: "c", label: "loan" },
    { key: "d", label: "asset" },
  ]),
  mcq("ex-pre-40-11", "40 · Chọn đáp án", "Short-term ___ are too high.", "d", [
    { key: "a", label: "assets" },
    { key: "b", label: "investments" },
    { key: "c", label: "receipts" },
    { key: "d", label: "liabilities" },
  ]),
  cloze("ex-pre-40-12", "40 · Điền cụm", "We hope to ___ this year.", "break even", ["Break even"]),
  cloze("ex-pre-40-13", "40 · Điền cụm", "She ___ her student loan.", "paid off", ["Paid off", "pay off", "Pay off"]),
  mcq("ex-pre-40-14", "40 · Chọn đáp án", "The auditor reviewed the ___.", "d", [
    { key: "a", label: "invoice" },
    { key: "b", label: "receipt" },
    { key: "c", label: "forecast" },
    { key: "d", label: "financial statement" },
  ]),
];

const UNIT_41: VocabularyExercise[] = [
  match("ex-pre-41-1", "41 · Ghép từ với nghĩa", [
    { left: "leisure activity", right: "hoạt động giải trí lúc rảnh" },
    { left: "workout", right: "buổi tập luyện thể chất" },
    { left: "hiking", right: "hoạt động đi bộ đường dài" },
    { left: "pastime", right: "thú tiêu khiển thường ngày" },
    { left: "board game", right: "trò chơi bàn cờ tại nhà" },
    { left: "spectator sport", right: "môn thể thao hấp dẫn người xem" },
  ]),
  cloze("ex-pre-41-2", "41 · Điền cụm", "Reading is my favourite ___.", "leisure activity", ["Leisure activity"]),
  cloze("ex-pre-41-3", "41 · Điền từ", "I do a ___ after work.", "workout", ["Workout"]),
  cloze("ex-pre-41-4", "41 · Điền cụm", "She joined a ___.", "fitness class", ["Fitness class"]),
  cloze("ex-pre-41-5", "41 · Điền từ", "We go ___ at weekends.", "hiking", ["Hiking"]),
  cloze("ex-pre-41-6", "41 · Điền từ", "___ helps me relax.", "Cycling", ["cycling"]),
  cloze("ex-pre-41-7", "41 · Điền từ", "___ is good for your back.", "Swimming", ["swimming"]),
  cloze("ex-pre-41-8", "41 · Điền từ", "___ improves flexibility.", "Yoga", ["yoga"]),
  mcq("ex-pre-41-9", "41 · Chọn đáp án", "To ___ means to bắt đầu theo đuổi sở thích mới.", "a", [
    { key: "a", label: "take up" },
    { key: "b", label: "wind down" },
    { key: "c", label: "stay active" },
    { key: "d", label: "recharge" },
  ]),
  mcq("ex-pre-41-10", "41 · Chọn đáp án", "Music helps me ___.", "b", [
    { key: "a", label: "take up" },
    { key: "b", label: "wind down" },
    { key: "c", label: "stay active" },
    { key: "d", label: "recharge" },
  ]),
  mcq("ex-pre-41-11", "41 · Chọn đáp án", "Photography is his main ___.", "c", [
    { key: "a", label: "workout" },
    { key: "b", label: "craft" },
    { key: "c", label: "pastime" },
    { key: "d", label: "hiking" },
  ]),
  cloze("ex-pre-41-12", "41 · Điền cụm", "Try to ___ every day.", "stay active", ["Stay active"]),
  cloze("ex-pre-41-13", "41 · Điền từ", "Weekends help me ___.", "recharge", ["Recharge"]),
  mcq("ex-pre-41-14", "41 · Chọn đáp án", "Football is a top ___.", "d", [
    { key: "a", label: "outdoor pursuit" },
    { key: "b", label: "fitness class" },
    { key: "c", label: "board game" },
    { key: "d", label: "spectator sport" },
  ]),
];

const UNIT_42: VocabularyExercise[] = [
  match("ex-pre-42-1", "42 · Ghép từ với nghĩa", [
    { left: "tournament", right: "giải đấu gồm nhiều vòng tranh tài" },
    { left: "championship", right: "giải vô địch cấp cao" },
    { left: "final", right: "trận đấu cuối cùng quyết định" },
    { left: "referee", right: "trọng tài điều hành trận đấu" },
    { left: "coach", right: "huấn luyện viên của đội" },
    { left: "stamina", right: "sức bền trong thi đấu" },
  ]),
  cloze("ex-pre-42-2", "42 · Điền từ", "Our team entered a ___.", "tournament", ["Tournament"]),
  cloze("ex-pre-42-3", "42 · Điền từ", "She won the national ___.", "championship", ["Championship"]),
  cloze("ex-pre-42-4", "42 · Điền từ", "They reached the ___.", "final", ["Final"]),
  cloze("ex-pre-42-5", "42 · Điền cụm", "The ___ is on Saturday.", "semi-final", ["Semi-final", "semifinal", "Semifinal"]),
  cloze("ex-pre-42-6", "42 · Điền từ", "This match is a ___.", "qualifier", ["Qualifier"]),
  cloze("ex-pre-42-7", "42 · Điền từ", "Check the ___ for next week.", "fixture", ["Fixture"]),
  cloze("ex-pre-42-8", "42 · Điền từ", "The ___ gave a red card.", "referee", ["Referee"]),
  mcq("ex-pre-42-9", "42 · Chọn đáp án", "The ___ changed the tactics.", "b", [
    { key: "a", label: "referee" },
    { key: "b", label: "coach" },
    { key: "c", label: "captain" },
    { key: "d", label: "substitute" },
  ]),
  mcq("ex-pre-42-10", "42 · Chọn đáp án", "The game ended in a ___.", "c", [
    { key: "a", label: "defeat" },
    { key: "b", label: "penalty" },
    { key: "c", label: "draw" },
    { key: "d", label: "final" },
  ]),
  mcq("ex-pre-42-11", "42 · Chọn đáp án", "Long runs build ___.", "a", [
    { key: "a", label: "stamina" },
    { key: "b", label: "penalty" },
    { key: "c", label: "fixture" },
    { key: "d", label: "qualifier" },
  ]),
  cloze("ex-pre-42-12", "42 · Điền cụm", "They scored in ___.", "injury time", ["Injury time"]),
  cloze("ex-pre-42-13", "42 · Điền từ", "She ___ in the second half.", "equalised", ["equalised", "equalized", "Equalised", "Equalized"]),
  mcq("ex-pre-42-14", "42 · Chọn đáp án", "He ___ in the 200m race.", "d", [
    { key: "a", label: "knocked out" },
    { key: "b", label: "equalised" },
    { key: "c", label: "captained" },
    { key: "d", label: "set a record" },
  ]),
];

const UNIT_43: VocabularyExercise[] = [
  match("ex-pre-43-1", "43 · Ghép từ với nghĩa", [
    { left: "novel", right: "tiểu thuyết có cốt truyện dài" },
    { left: "biography", right: "sách tiểu sử về một người thật" },
    { left: "plot", right: "mạch truyện và diễn biến chính" },
    { left: "genre", right: "thể loại tác phẩm" },
    { left: "sequel", right: "phần tiếp theo của phim hoặc sách" },
    { left: "bestseller", right: "sách bán chạy số lượng lớn" },
  ]),
  cloze("ex-pre-43-2", "43 · Điền từ", "I am reading a historical ___.", "novel", ["Novel"]),
  cloze("ex-pre-43-3", "43 · Điền từ", "This ___ is very inspiring.", "biography", ["Biography"]),
  cloze("ex-pre-43-4", "43 · Điền từ", "Her ___ became a bestseller.", "memoir", ["Memoir"]),
  cloze("ex-pre-43-5", "43 · Điền từ", "The ___ is full of surprises.", "plot", ["Plot"]),
  cloze("ex-pre-43-6", "43 · Điền cụm", "The hero has a strong ___.", "character arc", ["Character arc"]),
  cloze("ex-pre-43-7", "43 · Điền từ", "The ___ is a small seaside town.", "setting", ["Setting"]),
  cloze("ex-pre-43-8", "43 · Điền từ", "My favourite ___ is sci-fi.", "genre", ["Genre"]),
  mcq("ex-pre-43-9", "43 · Chọn đáp án", "The film is an ___ of a novel.", "b", [
    { key: "a", label: "subtitle" },
    { key: "b", label: "adaptation" },
    { key: "c", label: "sequel" },
    { key: "d", label: "review" },
  ]),
  mcq("ex-pre-43-10", "43 · Chọn đáp án", "Please do not post ___.", "a", [
    { key: "a", label: "spoilers" },
    { key: "b", label: "soundtracks" },
    { key: "c", label: "settings" },
    { key: "d", label: "genres" },
  ]),
  mcq("ex-pre-43-11", "43 · Chọn đáp án", "That thriller is a real ___.", "c", [
    { key: "a", label: "memoir" },
    { key: "b", label: "biography" },
    { key: "c", label: "page-turner" },
    { key: "d", label: "review" },
  ]),
  cloze("ex-pre-43-12", "43 · Điền từ", "The story was ___ from start to end.", "captivating", ["Captivating"]),
  cloze("ex-pre-43-13", "43 · Điền từ", "It is a ___ documentary.", "thought-provoking", ["Thought-provoking"]),
  mcq("ex-pre-43-14", "43 · Chọn đáp án", "Fans are waiting for the ___.", "b", [
    { key: "a", label: "adaptation" },
    { key: "b", label: "sequel" },
    { key: "c", label: "subtitle" },
    { key: "d", label: "spoiler" },
  ]),
];

const UNIT_44: VocabularyExercise[] = [
  match("ex-pre-44-1", "44 · Ghép từ với nghĩa", [
    { left: "melody", right: "giai điệu chính dễ nhận ra" },
    { left: "rhythm", right: "nhịp điệu lặp lại của âm nhạc" },
    { left: "lyrics", right: "lời bài hát" },
    { left: "chorus", right: "điệp khúc lặp lại trong bài hát" },
    { left: "tempo", right: "tốc độ nhanh chậm của bản nhạc" },
    { left: "playlist", right: "danh sách bài hát phát liên tục" },
  ]),
  cloze("ex-pre-44-2", "44 · Điền từ", "The ___ stayed in my head all day.", "melody", ["Melody"]),
  cloze("ex-pre-44-3", "44 · Điền từ", "This song has a strong ___.", "rhythm", ["Rhythm"]),
  cloze("ex-pre-44-4", "44 · Điền từ", "I love the ___ of this track.", "lyrics", ["Lyrics"]),
  cloze("ex-pre-44-5", "44 · Điền từ", "Everyone sang the ___ together.", "chorus", ["Chorus"]),
  cloze("ex-pre-44-6", "44 · Điền từ", "The second ___ tells the story.", "verse", ["Verse"]),
  cloze("ex-pre-44-7", "44 · Điền từ", "Their vocal ___ is excellent.", "harmony", ["Harmony"]),
  cloze("ex-pre-44-8", "44 · Điền từ", "The ___ becomes faster near the end.", "tempo", ["Tempo"]),
  mcq("ex-pre-44-9", "44 · Chọn đáp án", "I made a study ___.", "b", [
    { key: "a", label: "single" },
    { key: "b", label: "playlist" },
    { key: "c", label: "album" },
    { key: "d", label: "gig" },
  ]),
  mcq("ex-pre-44-10", "44 · Chọn đáp án", "We went to a jazz ___ last night.", "d", [
    { key: "a", label: "concert hall" },
    { key: "b", label: "album" },
    { key: "c", label: "single" },
    { key: "d", label: "gig" },
  ]),
  mcq("ex-pre-44-11", "44 · Chọn đáp án", "The crowd asked for an ___.", "c", [
    { key: "a", label: "verse" },
    { key: "b", label: "tempo" },
    { key: "c", label: "encore" },
    { key: "d", label: "harmony" },
  ]),
  cloze("ex-pre-44-12", "44 · Điền cụm", "She will ___ this weekend.", "perform live", ["Perform live"]),
  cloze("ex-pre-44-13", "44 · Điền từ", "He ___ music for films.", "composes", ["composes", "compose", "Compose"]),
  mcq("ex-pre-44-14", "44 · Chọn đáp án", "Jazz musicians often ___.", "d", [
    { key: "a", label: "tune" },
    { key: "b", label: "compose" },
    { key: "c", label: "perform live" },
    { key: "d", label: "improvise" },
  ]),
];

const UNIT_45: VocabularyExercise[] = [
  match("ex-pre-45-1", "45 · Ghép từ với nghĩa", [
    { left: "anniversary", right: "ngày kỷ niệm theo mốc thời gian" },
    { left: "ceremony", right: "buổi lễ trang trọng theo nghi thức" },
    { left: "celebration", right: "hoạt động ăn mừng một dịp đặc biệt" },
    { left: "festival", right: "lễ hội văn hóa theo mùa hoặc truyền thống" },
    { left: "guest list", right: "danh sách khách mời tham dự" },
    { left: "venue", right: "địa điểm tổ chức sự kiện" },
  ]),
  cloze("ex-pre-45-2", "45 · Điền từ", "Today is our wedding ___.", "anniversary", ["Anniversary"]),
  cloze("ex-pre-45-3", "45 · Điền cụm", "Graduation is a ___ event.", "milestone event", ["Milestone event"]),
  cloze("ex-pre-45-4", "45 · Điền từ", "The opening ___ starts at 8.", "ceremony", ["Ceremony"]),
  cloze("ex-pre-45-5", "45 · Điền từ", "The whole town joined the ___.", "celebration", ["Celebration"]),
  cloze("ex-pre-45-6", "45 · Điền từ", "The lantern ___ attracts many visitors.", "festival", ["Festival"]),
  cloze("ex-pre-45-7", "45 · Điền từ", "A ___ moved through downtown.", "parade", ["Parade"]),
  cloze("ex-pre-45-8", "45 · Điền từ", "We watched ___ at midnight.", "fireworks", ["Fireworks", "firework", "Firework"]),
  mcq("ex-pre-45-9", "45 · Chọn đáp án", "Please finalise the ___ today.", "a", [
    { key: "a", label: "guest list" },
    { key: "b", label: "dress code" },
    { key: "c", label: "venue" },
    { key: "d", label: "banquet" },
  ]),
  mcq("ex-pre-45-10", "45 · Chọn đáp án", "The ___ is formal.", "b", [
    { key: "a", label: "invitation" },
    { key: "b", label: "dress code" },
    { key: "c", label: "ceremony" },
    { key: "d", label: "parade" },
  ]),
  mcq("ex-pre-45-11", "45 · Chọn đáp án", "Rain may ___ the outdoor event.", "c", [
    { key: "a", label: "attend" },
    { key: "b", label: "commemorate" },
    { key: "c", label: "postpone" },
    { key: "d", label: "host" },
  ]),
  cloze("ex-pre-45-12", "45 · Điền từ", "Many alumni ___ the reunion.", "attended", ["attended", "attend", "Attend"]),
  cloze("ex-pre-45-13", "45 · Điền từ", "The event ___ local heroes.", "commemorates", ["commemorates", "commemorate", "Commemorate"]),
  mcq("ex-pre-45-14", "45 · Chọn đáp án", "It was a ___ evening.", "b", [
    { key: "a", label: "formal" },
    { key: "b", label: "memorable" },
    { key: "c", label: "ordinary" },
    { key: "d", label: "annual" },
  ]),
];

export const CURATED_PRE_UNITS_31_45: Readonly<Partial<Record<number, readonly VocabularyExercise[]>>> = {
  31: UNIT_31,
  32: UNIT_32,
  33: UNIT_33,
  34: UNIT_34,
  35: UNIT_35,
  36: UNIT_36,
  37: UNIT_37,
  38: UNIT_38,
  39: UNIT_39,
  40: UNIT_40,
  41: UNIT_41,
  42: UNIT_42,
  43: UNIT_43,
  44: UNIT_44,
  45: UNIT_45,
};

for (const [unitNumber, exercises] of Object.entries(CURATED_PRE_UNITS_31_45)) {
  if (exercises) {
    assertExerciseCount(Number(unitNumber), exercises);
  }
}
