import { EVIU_ELEMENTARY_CATALOG, type VocabularyUnitCatalogEntry } from "../eviu-elementary-catalog";
import type { VocabularyUnit } from "../vocabulary-unit-types";
import {
  bold,
  buildEviuUnit,
  ex,
  fillBlank,
  mcq,
  purple,
  type PrincipleInput,
  type UnitContentInput,
  type WordInput,
} from "./eviu-unit-builder";

type ExerciseSeed = {
  sentence: string;
  answer: string;
  distractors: [string, string, string];
};

type UnitDraft = {
  unitNumber: number;
  introVi: string;
  structureSections: { label: string; wordCount: number }[];
  collocationHtml: string;
  mistakeHtml: string;
  principles: PrincipleInput[];
  words: WordInput[];
  seeds: ExerciseSeed[];
};

function getCatalogEntryByUnitNumber(unitNumber: number): VocabularyUnitCatalogEntry {
  const entry = EVIU_ELEMENTARY_CATALOG.find((item) => item.unitNumber === unitNumber);
  if (!entry) {
    throw new Error(`Cannot find EVIU catalog entry for unit ${unitNumber}`);
  }
  return entry;
}

function toOptions(seed: ExerciseSeed): { key: string; label: string }[] {
  return [
    { key: "a", label: seed.answer },
    { key: "b", label: seed.distractors[0] },
    { key: "c", label: seed.distractors[1] },
    { key: "d", label: seed.distractors[2] },
  ];
}

function buildExercises(unitNumber: number, seeds: ExerciseSeed[]) {
  return seeds.flatMap((seed, index) => {
    const itemIndex = index * 2 + 1;
    const options = toOptions(seed);
    return [
      fillBlank(
        unitNumber,
        itemIndex,
        seed.sentence,
        seed.answer,
        options,
        "a",
        [seed.answer.toLowerCase()],
      ),
      mcq(
        unitNumber,
        itemIndex + 1,
        `Choose the best word to complete: ${seed.sentence}`,
        options,
        "a",
        "Chọn đáp án đúng",
      ),
    ];
  });
}

function buildUnitContent(draft: UnitDraft): UnitContentInput {
  return {
    introVi: draft.introVi,
    structureSections: draft.structureSections,
    collocationHtml: draft.collocationHtml,
    mistakeHtml: draft.mistakeHtml,
    principles: draft.principles,
    words: draft.words,
    exercises: buildExercises(draft.unitNumber, draft.seeds),
  };
}

const UNIT_DRAFTS: UnitDraft[] = [
  {
    unitNumber: 16,
    introVi: "Từ vựng giao tiếp qua thư, email và thông báo trong học tập, công việc.",
    structureSections: [
      { label: "Messages and channels", wordCount: 5 },
      { label: "Email writing", wordCount: 5 },
      { label: "Response and follow-up", wordCount: 5 },
      { label: "Public communication", wordCount: 5 },
      { label: "Useful adjectives", wordCount: 5 },
    ],
    collocationHtml: `Học theo cụm sẽ tự nhiên hơn: ${purple("send a message")}, ${purple("reply to all")}, ${purple("write a subject line")}, ${purple("share an update")}.`,
    mistakeHtml: `${bold("I wait your email")} ${bold("[SAI]")} → dùng ${purple("I am waiting for your email")}.<br>${bold("I will discuss about it")} ${bold("[SAI]")} → dùng ${purple("I will discuss it")}.`,
    principles: [
      {
        title: "GỬI TIN NHẮN",
        body: `Với trao đổi nhanh, ưu tiên ${purple("message")} và ${purple("chat")}; khi cần rõ ý thì chuyển sang ${purple("email")}.`,
        examples: [
          ex("I sent a quick chat message to my classmate.", "Tôi đã gửi một tin nhắn chat nhanh cho bạn cùng lớp."),
          ex("Please email the full report tonight.", "Vui lòng gửi email bản báo cáo đầy đủ tối nay."),
        ],
      },
      {
        title: "VIẾT EMAIL",
        body: `Email nên có ${purple("subject line")} rõ ràng, chia ${purple("paragraph")} ngắn và kết bằng ${purple("closing")} lịch sự.`,
        examples: [
          ex("Subject line: Meeting time for Friday.", "Tiêu đề email: Thời gian họp cho thứ Sáu."),
          ex(
            "I ended the email with Thank you for your support.",
            "Tôi kết thúc email bằng câu \"Cảm ơn bạn đã hỗ trợ.\"",
          ),
        ],
      },
      {
        title: "PHẢN HỒI",
        body: `Khi ${purple("reply")}, thêm bước tiếp theo, hạn chót hoặc file đính kèm để người nhận xử lý ngay.`,
        examples: [
          ex("I replied with the draft and a deadline.", "Tôi đã phản hồi kèm bản nháp và hạn chót."),
          ex("She followed up with an updated document.", "Cô ấy đã gửi thư nhắc lại kèm tài liệu đã cập nhật."),
        ],
      },
    ],
    words: [
      { term: "message", definition: "tin nhắn; thông điệp", example: "I left a message for the manager." },
      { term: "email", definition: "thư điện tử", example: "I sent an email to the support team." },
      { term: "inbox", definition: "hộp thư đến", example: "My inbox is full after the event." },
      { term: "attachment", definition: "tệp đính kèm", example: "The attachment includes the final schedule." },
      { term: "subject line", definition: "dòng tiêu đề email", example: "Use a clear subject line in business emails." },
      { term: "reply", definition: "trả lời", example: "Please reply before 6 p.m." },
      { term: "forward", definition: "chuyển tiếp", example: "Can you forward this message to Anna?" },
      { term: "draft", definition: "bản nháp", example: "I saved a draft before lunch." },
      { term: "signature", definition: "chữ ký", example: "My signature has my phone number." },
      { term: "greeting", definition: "lời chào", example: "Start the email with a friendly greeting." },
      { term: "announcement", definition: "thông báo", example: "The announcement was posted at noon." },
      { term: "notice", definition: "thông cáo; thông báo ngắn", example: "I read the notice on the door." },
      { term: "headline", definition: "tiêu đề chính", example: "The headline catches the reader's attention." },
      { term: "audience", definition: "đối tượng người nghe/đọc", example: "Think about your audience before writing." },
      { term: "tone", definition: "giọng điệu", example: "Keep a polite tone in formal emails." },
      { term: "urgent", definition: "khẩn cấp", partOfSpeech: "ADJECTIVE", example: "This is an urgent request." },
      { term: "formal", definition: "trang trọng", partOfSpeech: "ADJECTIVE", example: "Use formal language in job applications." },
      { term: "informal", definition: "thân mật", partOfSpeech: "ADJECTIVE", example: "An informal message is fine for friends." },
      { term: "clarify", definition: "làm rõ", partOfSpeech: "VERB", example: "Could you clarify the final date?" },
      { term: "confirm", definition: "xác nhận", partOfSpeech: "VERB", example: "Please confirm your attendance today." },
      { term: "follow-up", definition: "thư/tin nhắn nhắc lại", example: "I sent a follow-up after the meeting." },
      { term: "communication", definition: "sự giao tiếp", example: "Good communication saves time." },
      { term: "update", definition: "cập nhật", example: "She shared an update with the whole class." },
      { term: "feedback", definition: "phản hồi", example: "I asked for feedback on my report." },
      { term: "contact", definition: "liên hệ; người liên lạc", example: "He is my main contact at the company." },
    ],
    seeds: [
      { sentence: "Please check the ___ before the meeting starts.", answer: "inbox", distractors: ["headline", "draft", "audience"] },
      { sentence: "I added the photo as an ___ in the email.", answer: "attachment", distractors: ["greeting", "notice", "tone"] },
      { sentence: "Could you ___ your travel dates by tonight?", answer: "confirm", distractors: ["forward", "clarify", "contact"] },
      { sentence: "A polite ___ makes your message sound friendly.", answer: "greeting", distractors: ["signature", "update", "reply"] },
      { sentence: "After no answer, I sent a short ___.", answer: "follow-up", distractors: ["subject line", "announcement", "communication"] },
    ],
  },
  {
    unitNumber: 17,
    introVi: "Từ vựng điện thoại thông minh, cuộc gọi, tin nhắn và ứng dụng thường ngày.",
    structureSections: [
      { label: "Phone hardware", wordCount: 5 },
      { label: "Calls and messages", wordCount: 5 },
      { label: "Apps and settings", wordCount: 5 },
      { label: "Problems and fixes", wordCount: 5 },
      { label: "Phone habits", wordCount: 5 },
    ],
    collocationHtml: `Học theo cụm sẽ tự nhiên hơn: ${purple("miss a call")}, ${purple("turn on airplane mode")}, ${purple("charge the battery")}, ${purple("unlock the screen")}.`,
    mistakeHtml: `${bold("My battery is empty")} ${bold("[SAI]")} → dùng ${purple("My battery is dead")}.<br>${bold("Open bluetooth")} ${bold("[SAI]")} → dùng ${purple("Turn on Bluetooth")}.`,
    principles: [
      {
        title: "THAO TÁC ĐIỆN THOẠI",
        body: `Mô tả đúng hành động bằng ${purple("ring")}, ${purple("vibrate")}, ${purple("connect")}, ${purple("update")}.`,
        examples: [
          ex("My phone vibrates in silent mode.", "Điện thoại của tôi rung ở chế độ im lặng."),
          ex("The app updates automatically at night.", "Ứng dụng tự động cập nhật vào ban đêm."),
        ],
      },
      {
        title: "THIẾT BỊ VÀ ỨNG DỤNG",
        body: `Tách lỗi phần cứng và phần mềm: ${purple("my phone is slow")} khác với ${purple("the app crashed")}.`,
        examples: [
          ex("My phone is slow when storage is full.", "Điện thoại của tôi chậm khi bộ nhớ đầy."),
          ex("The map app crashed twice today.", "Ứng dụng bản đồ bị sập hai lần hôm nay."),
        ],
      },
      {
        title: "CÀI ĐẶT CƠ BẢN",
        body: `Dùng đúng thuật ngữ cài đặt như ${purple("airplane mode")}, ${purple("Wi-Fi")}, ${purple("notifications")}.`,
        examples: [
          ex("Turn on airplane mode during the flight.", "Hãy bật chế độ máy bay trong suốt chuyến bay."),
          ex("I disabled notifications for this app.", "Tôi đã tắt thông báo cho ứng dụng này."),
        ],
      },
    ],
    words: [
      { term: "smartphone", definition: "điện thoại thông minh", example: "My smartphone has a great camera." },
      { term: "screen", definition: "màn hình", example: "The screen is too bright at night." },
      { term: "battery", definition: "pin", example: "The battery is at ten percent." },
      { term: "charger", definition: "bộ sạc", example: "I forgot my charger at home." },
      { term: "headphones", definition: "tai nghe", example: "I use headphones on the bus." },
      { term: "call", definition: "cuộc gọi; gọi điện", example: "I made a quick call to my mother." },
      { term: "voicemail", definition: "thư thoại", example: "He left a voicemail after class." },
      { term: "ringtone", definition: "nhạc chuông", example: "Her ringtone is very loud." },
      { term: "text message", definition: "tin nhắn văn bản", example: "Send me a text message when you arrive." },
      { term: "contact list", definition: "danh bạ", example: "I saved your number in my contact list." },
      { term: "app", definition: "ứng dụng", example: "This app helps me learn vocabulary." },
      { term: "notification", definition: "thông báo", example: "I got a notification from the bank." },
      { term: "update", definition: "bản cập nhật", example: "The update improved camera quality." },
      { term: "password", definition: "mật khẩu", example: "Use a strong password for your phone." },
      { term: "fingerprint", definition: "dấu vân tay", example: "I unlock the phone with my fingerprint." },
      { term: "airplane mode", definition: "chế độ máy bay", example: "Please switch to airplane mode now." },
      { term: "Bluetooth", definition: "kết nối Bluetooth", example: "Bluetooth is connected to my speaker." },
      { term: "Wi-Fi", definition: "mạng Wi-Fi", example: "The Wi-Fi is faster in the office." },
      { term: "signal", definition: "sóng điện thoại", example: "There is no signal in this tunnel." },
      { term: "storage", definition: "bộ nhớ lưu trữ", example: "My storage is almost full." },
      { term: "download", definition: "tải xuống", partOfSpeech: "VERB", example: "I need to download the document." },
      { term: "upload", definition: "tải lên", partOfSpeech: "VERB", example: "She uploaded the video yesterday." },
      { term: "mute", definition: "tắt tiếng", partOfSpeech: "VERB", example: "Please mute your phone in class." },
      { term: "unlock", definition: "mở khóa", partOfSpeech: "VERB", example: "I unlock my phone with a code." },
      { term: "scroll", definition: "cuộn màn hình", partOfSpeech: "VERB", example: "He scrolls social media before bed." },
    ],
    seeds: [
      { sentence: "I cannot hear you; my ___ is too low.", answer: "signal", distractors: ["storage", "ringer", "screen"] },
      { sentence: "Please put your phone on ___ during the lecture.", answer: "mute", distractors: ["scroll", "upload", "download"] },
      { sentence: "My ___ is dead, so I need a power bank.", answer: "battery", distractors: ["ringer", "password", "contact list"] },
      { sentence: "I forgot my ___, so I cannot charge the phone.", answer: "charger", distractors: ["fingerprint", "notification", "voicemail"] },
      { sentence: "Turn on ___ to connect your phone to the speaker.", answer: "Bluetooth", distractors: ["airplane mode", "signal", "unlock"] },
    ],
  },
  {
    unitNumber: 18,
    introVi: "Từ vựng cho kỳ nghỉ: lên kế hoạch, đặt dịch vụ và tận hưởng chuyến đi.",
    structureSections: [
      { label: "Planning a trip", wordCount: 5 },
      { label: "Transport and documents", wordCount: 5 },
      { label: "Staying and activities", wordCount: 5 },
      { label: "Beach and sightseeing", wordCount: 5 },
      { label: "Travel feelings", wordCount: 5 },
    ],
    collocationHtml: `Học theo cụm sẽ tự nhiên hơn: ${purple("book a package tour")}, ${purple("go sightseeing")}, ${purple("catch a flight")}, ${purple("travel light")}.`,
    mistakeHtml: `${bold("I made many photos")} ${bold("[SAI]")} → dùng ${purple("I took many photos")}.<br>${bold("We were on holiday in the mountain")} ${bold("[SAI]")} → dùng ${purple("in the mountains")}.`,
    principles: [
      {
        title: "LÊN KẾ HOẠCH CHUYẾN ĐI",
        body: `Chuẩn bị ${purple("itinerary")} và thông tin ${purple("booking")} từ sớm để tránh thiếu sót khi khởi hành.`,
        examples: [
          ex("Our itinerary includes two museums and one beach day.", "Lịch trình của chúng tôi gồm hai bảo tàng và một ngày đi biển."),
          ex("I checked every booking before departure.", "Tôi đã kiểm tra mọi đặt chỗ trước khi khởi hành."),
        ],
      },
      {
        title: "HOẠT ĐỘNG KỲ NGHỈ",
        body: `Miêu tả hoạt động bằng động từ rõ nghĩa như ${purple("explore")}, ${purple("relax")}, ${purple("sunbathe")}, ${purple("hike")}.`,
        examples: [
          ex("We explored the old town by bike.", "Chúng tôi khám phá phố cổ bằng xe đạp."),
          ex("They relaxed by the pool all afternoon.", "Họ thư giãn bên hồ bơi suốt cả buổi chiều."),
        ],
      },
      {
        title: "CẢM NHẬN CHUYẾN ĐI",
        body: `Dùng tính từ phù hợp như ${purple("crowded")}, ${purple("peaceful")}, ${purple("memorable")} để nói trải nghiệm.`,
        examples: [
          ex("The beach was crowded at noon.", "Bãi biển đông đúc vào buổi trưa."),
          ex("It was a memorable weekend trip.", "Đó là một chuyến đi cuối tuần đáng nhớ."),
        ],
      },
    ],
    words: [
      { term: "holiday", definition: "kỳ nghỉ", example: "We are on holiday next week." },
      { term: "itinerary", definition: "lịch trình", example: "Our itinerary starts with a city tour." },
      { term: "booking", definition: "việc đặt chỗ", example: "I confirmed the hotel booking yesterday." },
      { term: "package tour", definition: "tour trọn gói", example: "A package tour can be cheaper for families." },
      { term: "destination", definition: "điểm đến", example: "Da Nang is our final destination." },
      { term: "passport", definition: "hộ chiếu", example: "Keep your passport in a safe place." },
      { term: "boarding pass", definition: "thẻ lên máy bay", example: "Show your boarding pass at the gate." },
      { term: "luggage", definition: "hành lý", example: "Our luggage arrived late." },
      { term: "souvenir", definition: "quà lưu niệm", example: "I bought a small souvenir for my sister." },
      { term: "travel insurance", definition: "bảo hiểm du lịch", example: "Travel insurance is useful on long trips." },
      { term: "resort", definition: "khu nghỉ dưỡng", example: "The resort has a private beach." },
      { term: "hostel", definition: "nhà nghỉ tập thể", example: "We stayed in a clean hostel downtown." },
      { term: "sightseeing", definition: "tham quan", example: "We did sightseeing in the old quarter." },
      { term: "guidebook", definition: "sách hướng dẫn du lịch", example: "The guidebook recommends local food." },
      { term: "landmark", definition: "địa danh nổi tiếng", example: "This bridge is a famous landmark." },
      { term: "sunbathe", definition: "tắm nắng", partOfSpeech: "VERB", example: "People sunbathe near the hotel pool." },
      { term: "explore", definition: "khám phá", partOfSpeech: "VERB", example: "We want to explore the island tomorrow." },
      { term: "relax", definition: "thư giãn", partOfSpeech: "VERB", example: "I just want to relax this weekend." },
      { term: "hike", definition: "đi bộ đường dài", partOfSpeech: "VERB", example: "They hike in the mountains every summer." },
      { term: "cancel", definition: "hủy", partOfSpeech: "VERB", example: "We had to cancel the boat trip." },
      { term: "crowded", definition: "đông đúc", partOfSpeech: "ADJECTIVE", example: "The market was crowded in the evening." },
      { term: "peaceful", definition: "yên bình", partOfSpeech: "ADJECTIVE", example: "The village feels peaceful at dawn." },
      { term: "memorable", definition: "đáng nhớ", partOfSpeech: "ADJECTIVE", example: "It was a memorable holiday." },
      { term: "adventure", definition: "cuộc phiêu lưu", example: "The hike was a real adventure." },
      { term: "postcard", definition: "bưu thiếp", example: "I sent a postcard to my grandparents." },
    ],
    seeds: [
      { sentence: "Our ___ says we visit the museum at 9 a.m.", answer: "itinerary", distractors: ["boarding pass", "landmark", "souvenir"] },
      { sentence: "You need your ___ to fly abroad.", answer: "passport", distractors: ["postcard", "guidebook", "hostel"] },
      { sentence: "We did ___ around the old city after lunch.", answer: "sightseeing", distractors: ["sunbathe", "cancel", "booking"] },
      { sentence: "The beach was too ___, so we left early.", answer: "crowded", distractors: ["peaceful", "memorable", "adventure"] },
      { sentence: "I bought a small ___ for my teacher.", answer: "souvenir", distractors: ["resort", "luggage", "passport"] },
    ],
  },
  {
    unitNumber: 19,
    introVi: "Từ vựng khi đi mua sắm tại cửa hàng, siêu thị và trung tâm thương mại.",
    structureSections: [
      { label: "Types of shops", wordCount: 5 },
      { label: "Products and price", wordCount: 5 },
      { label: "Payment", wordCount: 5 },
      { label: "Customer service", wordCount: 5 },
      { label: "Shopping habits", wordCount: 5 },
    ],
    collocationHtml: `Học theo cụm sẽ tự nhiên hơn: ${purple("go window shopping")}, ${purple("try on clothes")}, ${purple("pay in cash")}, ${purple("ask for a receipt")}.`,
    mistakeHtml: `${bold("I buyed this yesterday")} ${bold("[SAI]")} → dùng ${purple("I bought this yesterday")}.<br>${bold("This shirt is very suit me")} ${bold("[SAI]")} → dùng ${purple("This shirt suits me")}.`,
    principles: [
      {
        title: "HỎI TRONG CỬA HÀNG",
        body: `Ưu tiên mẫu lịch sự khi mua sắm, đặc biệt với ${purple("try on")} và hỏi thêm ${purple("size")}.`,
        examples: [
          ex("Could I try this jacket on?", "Tôi có thể thử chiếc áo khoác này không?"),
          ex("Do you have this in medium?", "Bạn có cỡ M mẫu này không?"),
        ],
      },
      {
        title: "NÓI VỀ GIÁ",
        body: `Phân biệt nhóm từ về giá: ${purple("discount")} là giảm giá, còn ${purple("expensive")}/${purple("cheap")} là mức giá.`,
        examples: [
          ex("This store gives a student discount.", "Cửa hàng này có giảm giá cho sinh viên."),
          ex("That bag is too expensive for me.", "Chiếc túi đó quá đắt với tôi."),
        ],
      },
      {
        title: "THANH TOÁN",
        body: `Trước khi rời quầy, xác nhận ${purple("total")}, cách trả tiền và lấy ${purple("receipt")}.`,
        examples: [
          ex("The total is forty dollars.", "Tổng cộng là bốn mươi đô la."),
          ex("Can I have the receipt, please?", "Cho tôi xin hóa đơn được không?"),
        ],
      },
    ],
    words: [
      { term: "shop", definition: "cửa hàng", example: "There is a new shop near my house." },
      { term: "supermarket", definition: "siêu thị", example: "We buy fruit at the supermarket." },
      { term: "bakery", definition: "tiệm bánh", example: "The bakery opens at six o'clock." },
      { term: "pharmacy", definition: "nhà thuốc", example: "You can buy vitamins at the pharmacy." },
      { term: "market stall", definition: "sạp chợ", example: "This market stall sells fresh fish." },
      { term: "product", definition: "sản phẩm", example: "This product is made in Vietnam." },
      { term: "brand", definition: "thương hiệu", example: "She likes this sports brand." },
      { term: "price tag", definition: "tem giá", example: "Check the price tag before paying." },
      { term: "discount", definition: "giảm giá", example: "I got a ten percent discount." },
      { term: "bargain", definition: "món hời", example: "This coat was a real bargain." },
      { term: "cash", definition: "tiền mặt", example: "I usually pay in cash at the market." },
      { term: "card", definition: "thẻ thanh toán", example: "Can I pay by card here?" },
      { term: "receipt", definition: "hóa đơn", example: "Keep the receipt for returns." },
      { term: "checkout", definition: "quầy thanh toán", example: "The checkout is crowded now." },
      { term: "change", definition: "tiền thừa", example: "Here is your change, sir." },
      { term: "customer", definition: "khách hàng", example: "The customer asked many questions." },
      { term: "assistant", definition: "nhân viên bán hàng", example: "A shop assistant helped me choose shoes." },
      { term: "size", definition: "kích cỡ", example: "Do you have this in size 40?" },
      { term: "fit", definition: "vừa vặn", partOfSpeech: "VERB", example: "These jeans fit me well." },
      { term: "refund", definition: "hoàn tiền", partOfSpeech: "NOUN", example: "I requested a refund for the broken item." },
      { term: "exchange", definition: "đổi hàng", partOfSpeech: "VERB", example: "Can I exchange this shirt?" },
      { term: "queue", definition: "xếp hàng", partOfSpeech: "VERB", example: "People queue outside the store." },
      { term: "affordable", definition: "vừa túi tiền", partOfSpeech: "ADJECTIVE", example: "This phone is affordable for students." },
      { term: "expensive", definition: "đắt", partOfSpeech: "ADJECTIVE", example: "That watch looks expensive." },
      { term: "cheap", definition: "rẻ", partOfSpeech: "ADJECTIVE", example: "These socks are cheap but good." },
    ],
    seeds: [
      { sentence: "Could I get a ___ after payment, please?", answer: "receipt", distractors: ["brand", "market stall", "product"] },
      { sentence: "This jacket does not ___ me very well.", answer: "fit", distractors: ["queue", "refund", "checkout"] },
      { sentence: "I paid in ___ because my card was not working.", answer: "cash", distractors: ["size", "discount", "assistant"] },
      { sentence: "Can I ___ this shirt for a larger one?", answer: "exchange", distractors: ["affordable", "cheap", "queue"] },
      { sentence: "That laptop is too ___ for my budget.", answer: "expensive", distractors: ["affordable", "cheap", "bargain"] },
    ],
  },
  {
    unitNumber: 20,
    introVi: "Từ vựng mua sắm online: chọn hàng, thanh toán và theo dõi đơn.",
    structureSections: [
      { label: "Online stores", wordCount: 5 },
      { label: "Ordering", wordCount: 5 },
      { label: "Payment and delivery", wordCount: 5 },
      { label: "Reviews and returns", wordCount: 5 },
      { label: "Shopping safety", wordCount: 5 },
    ],
    collocationHtml: `Học theo cụm sẽ tự nhiên hơn: ${purple("add to cart")}, ${purple("place an order")}, ${purple("track a parcel")}, ${purple("leave a review")}.`,
    mistakeHtml: `${bold("I buy on internet")} ${bold("[SAI]")} → dùng ${purple("I buy online")}.<br>${bold("The package delayed")} ${bold("[SAI]")} → dùng ${purple("The package was delayed")}.`,
    principles: [
      {
        title: "XEM KỸ SẢN PHẨM",
        body: `Trước khi thanh toán, đọc ${purple("product description")}, kiểm tra size chart và ${purple("return policy")}.`,
        examples: [
          ex("The product description says this bag is waterproof.", "Mô tả sản phẩm ghi rằng chiếc túi này chống nước."),
          ex("I always check the size chart first.", "Tôi luôn kiểm tra bảng kích cỡ trước."),
        ],
      },
      {
        title: "THEO DÕI ĐƠN HÀNG",
        body: `Nắm trạng thái ${purple("processing")}, ${purple("shipped")}, ${purple("delivered")} để biết đơn đang ở đâu.`,
        examples: [
          ex("My order is still processing.", "Đơn hàng của tôi vẫn đang được xử lý."),
          ex("The parcel was delivered this morning.", "Bưu kiện đã được giao sáng nay."),
        ],
      },
      {
        title: "MUA SẮM AN TOÀN",
        body: `Ưu tiên thanh toán bảo mật, tránh link lạ và xem ${purple("reviews")} trước khi đặt mua.`,
        examples: [
          ex("I read ten reviews before ordering.", "Tôi đã đọc mười đánh giá trước khi đặt hàng."),
          ex("Never enter your card on unknown websites.", "Đừng bao giờ nhập thông tin thẻ trên các trang web lạ."),
        ],
      },
    ],
    words: [
      { term: "online store", definition: "cửa hàng trực tuyến", example: "This online store sells handmade bags." },
      { term: "homepage", definition: "trang chủ", example: "The discount code is on the homepage." },
      { term: "search bar", definition: "thanh tìm kiếm", example: "Type the product name in the search bar." },
      { term: "filter", definition: "bộ lọc", example: "Use a filter to find your size quickly." },
      { term: "wishlist", definition: "danh sách yêu thích", example: "I saved the jacket in my wishlist." },
      { term: "cart", definition: "giỏ hàng", example: "My cart has three books." },
      { term: "checkout", definition: "bước thanh toán", example: "The checkout page is simple and fast." },
      { term: "order", definition: "đơn hàng", example: "I placed an order last night." },
      { term: "voucher", definition: "mã giảm giá", example: "Use this voucher for free shipping." },
      { term: "payment gateway", definition: "cổng thanh toán", example: "The payment gateway supports many banks." },
      { term: "shipping fee", definition: "phí vận chuyển", example: "The shipping fee is cheap today." },
      { term: "delivery", definition: "giao hàng", example: "Delivery takes two business days." },
      { term: "tracking number", definition: "mã theo dõi đơn", example: "I received a tracking number by email." },
      { term: "parcel", definition: "bưu kiện", example: "The parcel arrived in good condition." },
      { term: "courier", definition: "người/đơn vị giao hàng", example: "The courier called before delivery." },
      { term: "review", definition: "đánh giá", example: "Please leave a review after using it." },
      { term: "rating", definition: "xếp hạng sao", example: "This product has a 4.9 rating." },
      { term: "return policy", definition: "chính sách đổi trả", example: "Read the return policy before buying." },
      { term: "refund", definition: "hoàn tiền", example: "I got a full refund within three days." },
      { term: "seller", definition: "người bán", example: "The seller answered my question quickly." },
      { term: "secure", definition: "an toàn, bảo mật", partOfSpeech: "ADJECTIVE", example: "Use a secure website for payments." },
      { term: "verified", definition: "đã xác thực", partOfSpeech: "ADJECTIVE", example: "Buy from verified sellers only." },
      { term: "scam", definition: "lừa đảo", example: "That link looks like a scam." },
      { term: "subscribe", definition: "đăng ký nhận tin", partOfSpeech: "VERB", example: "I subscribe for weekly deals." },
      { term: "confirm", definition: "xác nhận", partOfSpeech: "VERB", example: "Please confirm your delivery address." },
    ],
    seeds: [
      { sentence: "I clicked ___ and paid with my card.", answer: "checkout", distractors: ["wishlist", "filter", "homepage"] },
      { sentence: "The ___ helps me see where my package is.", answer: "tracking number", distractors: ["voucher", "rating", "cart"] },
      { sentence: "I only buy from ___ sellers on this platform.", answer: "verified", distractors: ["secure", "scam", "delivery"] },
      { sentence: "Read the ___ if you may send items back.", answer: "return policy", distractors: ["shipping fee", "search bar", "courier"] },
      { sentence: "The ___ delivered my parcel at 8 a.m.", answer: "courier", distractors: ["seller", "gateway", "homepage"] },
    ],
  },
  {
    unitNumber: 21,
    introVi: "Từ vựng dùng tại khách sạn: đặt phòng, nhận phòng, dịch vụ và trả phòng.",
    structureSections: [
      { label: "Booking and arrival", wordCount: 5 },
      { label: "Room facilities", wordCount: 5 },
      { label: "Hotel services", wordCount: 5 },
      { label: "Requests and problems", wordCount: 5 },
      { label: "Departure", wordCount: 5 },
    ],
    collocationHtml: `Học theo cụm sẽ tự nhiên hơn: ${purple("make a reservation")}, ${purple("check in at the desk")}, ${purple("ask for room service")}, ${purple("check out early")}.`,
    mistakeHtml: `${bold("I want reserve a room")} ${bold("[SAI]")} → dùng ${purple("I want to reserve a room")}.<br>${bold("The room has not hot water")} ${bold("[SAI]")} → dùng ${purple("The room doesn't have hot water")}.`,
    principles: [
      {
        title: "ĐẶT PHÒNG",
        body: `Khi đặt phòng, nêu rõ ${purple("dates")}, số khách, loại giường và yêu cầu về phòng.`,
        examples: [
          ex("I'd like a double room for two nights.", "Tôi muốn đặt một phòng đôi trong hai đêm."),
          ex("We arrive on Friday evening.", "Chúng tôi đến vào tối thứ Sáu."),
        ],
      },
      {
        title: "YÊU CẦU DỊCH VỤ",
        body: `Dùng ${purple("Could I")} hoặc ${purple("Can I")} để nhờ thêm ${purple("towel")}, ${purple("wake-up call")} hoặc đồ dùng trong phòng.`,
        examples: [
          ex("Could I have two extra towels?", "Tôi có thể xin thêm hai khăn tắm không?"),
          ex("Can I request a wake-up call at six?", "Tôi có thể yêu cầu cuộc gọi báo thức lúc sáu giờ không?"),
        ],
      },
      {
        title: "TRẢ PHÒNG",
        body: `Trước khi ${purple("check out")}, kiểm tra hóa đơn — đặc biệt ${purple("minibar")}, ${purple("laundry")} và các phí phát sinh.`,
        examples: [
          ex("Please check this minibar charge.", "Vui lòng kiểm tra khoản phí minibar này."),
          ex("I paid the final bill at checkout.", "Tôi đã thanh toán hóa đơn cuối khi trả phòng."),
        ],
      },
    ],
    words: [
      { term: "reservation", definition: "đặt phòng", example: "I made a reservation online." },
      { term: "reception", definition: "quầy lễ tân", example: "Please ask reception for a city map." },
      { term: "lobby", definition: "sảnh", example: "Let's meet in the lobby at seven." },
      { term: "check-in", definition: "thủ tục nhận phòng", example: "Check-in starts at 2 p.m." },
      { term: "check-out", definition: "thủ tục trả phòng", example: "Our check-out is tomorrow morning." },
      { term: "single room", definition: "phòng đơn", example: "A single room is enough for me." },
      { term: "double room", definition: "phòng đôi", example: "They booked a double room." },
      { term: "suite", definition: "phòng hạng sang", example: "The suite has a sea view." },
      { term: "key card", definition: "thẻ khóa phòng", example: "I lost my key card yesterday." },
      { term: "balcony", definition: "ban công", example: "Our room has a small balcony." },
      { term: "room service", definition: "dịch vụ phòng", example: "We ordered room service at night." },
      { term: "housekeeping", definition: "dịch vụ dọn phòng", example: "Housekeeping cleaned the room at noon." },
      { term: "laundry", definition: "dịch vụ giặt ủi", example: "The hotel laundry is expensive." },
      { term: "breakfast buffet", definition: "tiệc buffet sáng", example: "Breakfast buffet starts at 6:30." },
      { term: "wake-up call", definition: "cuộc gọi báo thức", example: "Please arrange a wake-up call at five." },
      { term: "air conditioning", definition: "điều hòa", example: "The air conditioning is not working." },
      { term: "towel", definition: "khăn tắm", example: "Could I get an extra towel?" },
      { term: "blanket", definition: "chăn", example: "The blanket is warm and soft." },
      { term: "minibar", definition: "tủ lạnh minibar", example: "Drinks in the minibar are not free." },
      { term: "bill", definition: "hóa đơn", example: "Please print my final bill." },
      { term: "complaint", definition: "lời phàn nàn", example: "She made a complaint about noise." },
      { term: "available", definition: "còn trống", partOfSpeech: "ADJECTIVE", example: "No rooms are available tonight." },
      { term: "book", definition: "đặt chỗ", partOfSpeech: "VERB", example: "I book hotels on my phone." },
      { term: "extend", definition: "gia hạn", partOfSpeech: "VERB", example: "Can we extend our stay by one night?" },
      { term: "vacancy", definition: "phòng trống", example: "Do you have any vacancy this weekend?" },
    ],
    seeds: [
      { sentence: "I made a ___ for two nights online.", answer: "reservation", distractors: ["vacancy", "towel", "suite"] },
      { sentence: "Please meet me in the ___ near reception.", answer: "lobby", distractors: ["balcony", "minibar", "laundry"] },
      { sentence: "Could you send one more ___ to room 305?", answer: "towel", distractors: ["bill", "check-out", "key card"] },
      { sentence: "I need a ___ at 5:30 because of my flight.", answer: "wake-up call", distractors: ["breakfast buffet", "complaint", "vacancy"] },
      { sentence: "We paid the final ___ before leaving.", answer: "bill", distractors: ["reservation", "suite", "air conditioning"] },
    ],
  },
  {
    unitNumber: 22,
    introVi: "Từ vựng ăn ngoài: gọi món, yêu cầu tại bàn và thanh toán.",
    structureSections: [
      { label: "Restaurant places", wordCount: 5 },
      { label: "Menu and dishes", wordCount: 5 },
      { label: "Ordering language", wordCount: 5 },
      { label: "Taste and quality", wordCount: 5 },
      { label: "Bill and payment", wordCount: 5 },
    ],
    collocationHtml: `Học theo cụm sẽ tự nhiên hơn: ${purple("book a table")}, ${purple("take an order")}, ${purple("split the bill")}, ${purple("leave a tip")}.`,
    mistakeHtml: `${bold("I very like this dish")} ${bold("[SAI]")} → dùng ${purple("I really like this dish")}.<br>${bold("Can I have a water?")} ${bold("[SAI]")} → dùng ${purple("Can I have some water?")}.`,
    principles: [
      {
        title: "GỌI MÓN LỊCH SỰ",
        body: `Khi gọi món, dùng mẫu ${purple("I'd like")} hoặc ${purple("Could we have")} để câu nói tự nhiên hơn.`,
        examples: [
          ex("I'd like the grilled chicken, please.", "Tôi muốn gọi món gà nướng, làm ơn."),
          ex("Could we have two lemon teas?", "Cho chúng tôi hai trà chanh được không?"),
        ],
      },
      {
        title: "MÔ TẢ MÓN ĂN",
        body: `Dùng từ vựng vị giác và kết cấu như ${purple("crispy")}, ${purple("spicy")}, ${purple("sweet")}, ${purple("bland")}.`,
        examples: [
          ex("The fries are crispy and hot.", "Khoai tây chiên giòn và nóng."),
          ex("This soup is too bland for me.", "Món súp này quá nhạt với tôi."),
        ],
      },
      {
        title: "THANH TOÁN HÓA ĐƠN",
        body: `Khi trả tiền, dùng cụm rõ nghĩa như ${purple("get the bill")} và ${purple("pay separately")}.`,
        examples: [
          ex("Could we get the bill, please?", "Cho chúng tôi xin hóa đơn được không?"),
          ex("We decided to split the bill.", "Chúng tôi quyết định chia hóa đơn."),
        ],
      },
    ],
    words: [
      { term: "restaurant", definition: "nhà hàng", example: "This restaurant serves local food." },
      { term: "cafe", definition: "quán cà phê", example: "We met at a small cafe." },
      { term: "table", definition: "bàn ăn", example: "Our table is near the window." },
      { term: "waiter", definition: "nhân viên phục vụ nam", example: "The waiter brought us the menu." },
      { term: "waitress", definition: "nhân viên phục vụ nữ", example: "The waitress recommended a noodle dish." },
      { term: "menu", definition: "thực đơn", example: "The menu has many vegetarian options." },
      { term: "starter", definition: "món khai vị", example: "We ordered salad as a starter." },
      { term: "main course", definition: "món chính", example: "Fish was my main course." },
      { term: "dessert", definition: "món tráng miệng", example: "I shared a dessert with my friend." },
      { term: "beverage", definition: "đồ uống", example: "Tea is my favorite beverage." },
      { term: "order", definition: "gọi món; đơn gọi", example: "Are you ready to order now?" },
      { term: "ingredient", definition: "nguyên liệu", example: "This dish has fresh ingredients." },
      { term: "allergy", definition: "dị ứng", example: "I have a peanut allergy." },
      { term: "vegetarian", definition: "ăn chay; người ăn chay", example: "She asked for a vegetarian meal." },
      { term: "portion", definition: "khẩu phần", example: "The portion is larger than I expected." },
      { term: "spicy", definition: "cay", partOfSpeech: "ADJECTIVE", example: "This curry is very spicy." },
      { term: "crispy", definition: "giòn", partOfSpeech: "ADJECTIVE", example: "The chicken skin is crispy." },
      { term: "bland", definition: "nhạt nhẽo", partOfSpeech: "ADJECTIVE", example: "The soup tastes bland." },
      { term: "juicy", definition: "mọng nước", partOfSpeech: "ADJECTIVE", example: "The steak is juicy and tender." },
      { term: "delicious", definition: "ngon", partOfSpeech: "ADJECTIVE", example: "Everything here is delicious." },
      { term: "bill", definition: "hóa đơn", example: "Can we have the bill, please?" },
      { term: "tip", definition: "tiền bo", example: "We left a small tip." },
      { term: "split", definition: "chia", partOfSpeech: "VERB", example: "Let's split the bill equally." },
      { term: "book", definition: "đặt bàn", partOfSpeech: "VERB", example: "I booked a table for tonight." },
      { term: "serve", definition: "phục vụ", partOfSpeech: "VERB", example: "They serve breakfast all day." },
    ],
    seeds: [
      { sentence: "Could we see the ___ before ordering?", answer: "menu", distractors: ["portion", "allergy", "ingredient"] },
      { sentence: "I have a seafood ___, so I cannot eat shrimp.", answer: "allergy", distractors: ["starter", "tip", "bill"] },
      { sentence: "The fried chicken is very ___ and tasty.", answer: "crispy", distractors: ["bland", "juicy", "split"] },
      { sentence: "Can we ___ the bill between four people?", answer: "split", distractors: ["serve", "book", "order"] },
      { sentence: "Please bring the ___ when you have time.", answer: "bill", distractors: ["beverage", "portion", "tip"] },
    ],
  },
  {
    unitNumber: 23,
    introVi: "Từ vựng thể thao, luyện tập, thi đấu và thói quen vận động.",
    structureSections: [
      { label: "Sports and games", wordCount: 5 },
      { label: "People in sports", wordCount: 5 },
      { label: "Training", wordCount: 5 },
      { label: "Competition", wordCount: 5 },
      { label: "Health and fitness", wordCount: 5 },
    ],
    collocationHtml: `Học theo cụm sẽ tự nhiên hơn: ${purple("do warm-up exercises")}, ${purple("score a goal")}, ${purple("win a match")}, ${purple("keep fit")}.`,
    mistakeHtml: `${bold("I play gym every day")} ${bold("[SAI]")} → dùng ${purple("I go to the gym every day")}.<br>${bold("He is very health")} ${bold("[SAI]")} → dùng ${purple("He is very healthy")}.`,
    principles: [
      {
        title: "ĐỘNG TỪ THỂ THAO",
        body: `Chọn đúng động từ theo môn: ${purple("play")} cho môn đối kháng, ${purple("go")} với bơi/chạy, ${purple("do")} với bài tập.`,
        examples: [
          ex("They play basketball after class.", "Họ chơi bóng rổ sau giờ học."),
          ex("I go swimming every Sunday.", "Tôi đi bơi mỗi Chủ nhật."),
        ],
      },
      {
        title: "THÓI QUEN TẬP LUYỆN",
        body: `Mô tả buổi tập bằng các từ ${purple("warm-up")}, ${purple("stretch")}, ${purple("practice")} để rõ quy trình.`,
        examples: [
          ex("We did a warm-up before running.", "Chúng tôi khởi động trước khi chạy."),
          ex("She stretches for ten minutes daily.", "Cô ấy giãn cơ mười phút mỗi ngày."),
        ],
      },
      {
        title: "KẾT QUẢ THI ĐẤU",
        body: `Nói kết quả bằng cụm ${purple("win")}, ${purple("lose")}, ${purple("draw")}, ${purple("score")}.`,
        examples: [
          ex("Our team won 2-1.", "Đội của chúng tôi thắng 2-1."),
          ex("He scored in the final minute.", "Anh ấy ghi bàn ở phút cuối."),
        ],
      },
    ],
    words: [
      { term: "football", definition: "bóng đá", example: "My brother plays football every weekend." },
      { term: "basketball", definition: "bóng rổ", example: "We have basketball practice on Tuesday." },
      { term: "tennis", definition: "quần vợt", example: "She plays tennis with her dad." },
      { term: "swimming", definition: "bơi lội", example: "Swimming is good for your back." },
      { term: "yoga", definition: "yoga", example: "Yoga helps me relax after work." },
      { term: "athlete", definition: "vận động viên", example: "The athlete trains twice a day." },
      { term: "coach", definition: "huấn luyện viên", example: "Our coach plans the training schedule." },
      { term: "captain", definition: "đội trưởng", example: "The captain motivated the whole team." },
      { term: "referee", definition: "trọng tài", example: "The referee blew the whistle." },
      { term: "opponent", definition: "đối thủ", example: "Our opponent is very strong this season." },
      { term: "practice", definition: "luyện tập", example: "Practice starts at five o'clock." },
      { term: "warm-up", definition: "khởi động", example: "Do a warm-up before running." },
      { term: "stretch", definition: "kéo giãn cơ", partOfSpeech: "VERB", example: "Stretch your legs after exercise." },
      { term: "equipment", definition: "dụng cụ", example: "The gym has modern equipment." },
      { term: "uniform", definition: "đồng phục", example: "The team wore a new uniform." },
      { term: "match", definition: "trận đấu", example: "The match starts at 7 p.m." },
      { term: "tournament", definition: "giải đấu", example: "Our school hosts a tennis tournament." },
      { term: "score", definition: "ghi điểm; tỉ số", partOfSpeech: "VERB", example: "She scored the winning goal." },
      { term: "win", definition: "thắng", partOfSpeech: "VERB", example: "We want to win this game." },
      { term: "lose", definition: "thua", partOfSpeech: "VERB", example: "They rarely lose at home." },
      { term: "fitness", definition: "thể lực", example: "Regular exercise improves your fitness." },
      { term: "healthy", definition: "khỏe mạnh", partOfSpeech: "ADJECTIVE", example: "He looks healthy and energetic." },
      { term: "injury", definition: "chấn thương", example: "She is recovering from a knee injury." },
      { term: "recover", definition: "hồi phục", partOfSpeech: "VERB", example: "It took him weeks to recover." },
      { term: "champion", definition: "nhà vô địch", example: "The champion received a gold medal." },
    ],
    seeds: [
      { sentence: "Our ___ gave us a new training plan.", answer: "coach", distractors: ["captain", "referee", "opponent"] },
      { sentence: "Always do a ___ before heavy exercise.", answer: "warm-up", distractors: ["tournament", "uniform", "match"] },
      { sentence: "She can ___ quickly from minor injuries.", answer: "recover", distractors: ["score", "lose", "stretch"] },
      { sentence: "We hope to ___ the final on Saturday.", answer: "win", distractors: ["lose", "practice", "injury"] },
      { sentence: "Daily exercise improves your ___.", answer: "fitness", distractors: ["equipment", "champion", "referee"] },
    ],
  },
  {
    unitNumber: 24,
    introVi: "Từ vựng về điện ảnh, rạp chiếu và cách nói về trải nghiệm xem phim.",
    structureSections: [
      { label: "Places and tickets", wordCount: 5 },
      { label: "Kinds of films", wordCount: 5 },
      { label: "People in cinema", wordCount: 5 },
      { label: "Watching experience", wordCount: 5 },
      { label: "Reviews and opinions", wordCount: 5 },
    ],
    collocationHtml: `Học theo cụm sẽ tự nhiên hơn: ${purple("book tickets online")}, ${purple("watch the trailer")}, ${purple("sit in the front row")}, ${purple("give a review")}.`,
    mistakeHtml: `${bold("The film was very bored")} ${bold("[SAI]")} → dùng ${purple("The film was very boring")}.<br>${bold("I am very exciting")} ${bold("[SAI]")} → dùng ${purple("I am very excited")}.`,
    principles: [
      {
        title: "THỂ LOẠI PHIM",
        body: `Khi nói sở thích xem phim, dùng đúng nhóm ${purple("comedy")}, ${purple("thriller")}, ${purple("documentary")}, ${purple("animation")}.`,
        examples: [
          ex("I usually watch comedy films.", "Tôi thường xem phim hài."),
          ex("My sister loves documentaries about nature.", "Chị gái tôi rất thích phim tài liệu về thiên nhiên."),
        ],
      },
      {
        title: "TRẢI NGHIỆM XEM PHIM",
        body: `Mô tả chỗ ngồi và chất lượng xem bằng ${purple("row")}, ${purple("soundtrack")}, ${purple("subtitle")}.`,
        examples: [
          ex("We sat in the back row for a better view.", "Chúng tôi ngồi ở hàng ghế sau để nhìn rõ hơn."),
          ex("The subtitles were clear and helpful.", "Phụ đề rõ ràng và hữu ích."),
        ],
      },
      {
        title: "NÊU NHẬN XÉT",
        body: `Khi review, ưu tiên tính từ ngắn gọn như ${purple("interesting")}, ${purple("predictable")}, ${purple("moving")}, ${purple("funny")}.`,
        examples: [
          ex("The ending was predictable.", "Cái kết khá dễ đoán."),
          ex("It was a moving story about family.", "Đó là một câu chuyện cảm động về gia đình."),
        ],
      },
    ],
    words: [
      { term: "cinema", definition: "rạp chiếu phim", example: "The new cinema opened last month." },
      { term: "ticket", definition: "vé", example: "I bought two tickets for tonight." },
      { term: "box office", definition: "quầy vé", example: "The box office closes at ten." },
      { term: "screen", definition: "màn chiếu", example: "Screen 3 is on the second floor." },
      { term: "row", definition: "hàng ghế", example: "We are in row F." },
      { term: "comedy", definition: "phim hài", example: "This comedy made everyone laugh." },
      { term: "drama", definition: "phim chính kịch", example: "She prefers drama to action films." },
      { term: "thriller", definition: "phim giật gân", example: "That thriller was intense." },
      { term: "animation", definition: "phim hoạt hình", example: "The animation is great for kids." },
      { term: "documentary", definition: "phim tài liệu", example: "We watched a documentary about oceans." },
      { term: "actor", definition: "nam diễn viên", example: "The actor won an award." },
      { term: "actress", definition: "nữ diễn viên", example: "The actress gave an excellent performance." },
      { term: "director", definition: "đạo diễn", example: "The director answered questions after the film." },
      { term: "script", definition: "kịch bản", example: "The script is clever and emotional." },
      { term: "scene", definition: "cảnh phim", example: "My favorite scene is at the end." },
      { term: "trailer", definition: "đoạn giới thiệu phim", example: "The trailer looked exciting." },
      { term: "subtitle", definition: "phụ đề", example: "I need subtitles for this movie." },
      { term: "soundtrack", definition: "nhạc phim", example: "The soundtrack is beautiful." },
      { term: "ending", definition: "đoạn kết", example: "The ending surprised everyone." },
      { term: "review", definition: "bài đánh giá", example: "I read a review before watching." },
      { term: "boring", definition: "chán", partOfSpeech: "ADJECTIVE", example: "The second half was boring." },
      { term: "exciting", definition: "hào hứng", partOfSpeech: "ADJECTIVE", example: "It was an exciting film." },
      { term: "moving", definition: "cảm động", partOfSpeech: "ADJECTIVE", example: "The final scene was moving." },
      { term: "predictable", definition: "dễ đoán", partOfSpeech: "ADJECTIVE", example: "The story was a bit predictable." },
      { term: "recommend", definition: "giới thiệu", partOfSpeech: "VERB", example: "I recommend this movie to friends." },
    ],
    seeds: [
      { sentence: "We bought our ___ online to avoid the queue.", answer: "ticket", distractors: ["row", "scene", "review"] },
      { sentence: "I watched the ___ before deciding to see the film.", answer: "trailer", distractors: ["script", "ending", "director"] },
      { sentence: "The film was emotional and very ___.", answer: "moving", distractors: ["boring", "predictable", "subtitle"] },
      { sentence: "Please turn on ___ because the accents are hard.", answer: "subtitle", distractors: ["scene", "soundtrack", "box office"] },
      { sentence: "Can you ___ a good comedy for tonight?", answer: "recommend", distractors: ["ending", "ticket", "director"] },
    ],
  },
  {
    unitNumber: 25,
    introVi: "Từ vựng về hoạt động giải trí tại nhà: đọc, xem, nấu và thư giãn.",
    structureSections: [
      { label: "Home activities", wordCount: 5 },
      { label: "Media and devices", wordCount: 5 },
      { label: "Creative hobbies", wordCount: 5 },
      { label: "Household relaxation", wordCount: 5 },
      { label: "Daily routines", wordCount: 5 },
    ],
    collocationHtml: `Học theo cụm sẽ tự nhiên hơn: ${purple("watch a series")}, ${purple("do a puzzle")}, ${purple("bake cookies")}, ${purple("tidy up the room")}.`,
    mistakeHtml: `${bold("I stay at home and boring")} ${bold("[SAI]")} → dùng ${purple("I stay at home and feel bored")}.<br>${bold("I listen music")} ${bold("[SAI]")} → dùng ${purple("I listen to music")}.`,
    principles: [
      {
        title: "SỞ THÍCH Ở NHÀ",
        body: `Dùng động từ đúng theo hoạt động như ${purple("read")}, ${purple("knit")}, ${purple("paint")}, ${purple("stream")}.`,
        examples: [
          ex("I read before bed every night.", "Tôi đọc sách trước khi ngủ mỗi tối."),
          ex("She paints landscapes on weekends.", "Cô ấy vẽ phong cảnh vào cuối tuần."),
        ],
      },
      {
        title: "GIẢI TRÍ VÀ VIỆC NHÀ",
        body: `Kết hợp thời gian thư giãn với việc nhỏ như ${purple("water plants")} hoặc ${purple("tidy up")} để giữ nếp sinh hoạt.`,
        examples: [
          ex("I tidy up after watching TV.", "Tôi dọn dẹp sau khi xem TV."),
          ex("He waters the plants every evening.", "Anh ấy tưới cây mỗi tối."),
        ],
      },
      {
        title: "KHÔNG KHÍ TRONG NHÀ",
        body: `Mô tả cảm giác ở nhà bằng ${purple("cozy")}, ${purple("peaceful")}, ${purple("lazy")}.`,
        examples: [
          ex("Sunday feels cozy at home.", "Chủ nhật ở nhà thật ấm cúng."),
          ex("We had a peaceful evening together.", "Chúng tôi đã có một buổi tối yên bình bên nhau."),
        ],
      },
    ],
    words: [
      { term: "novel", definition: "tiểu thuyết", example: "I finished a novel last weekend." },
      { term: "magazine", definition: "tạp chí", example: "My dad reads a travel magazine." },
      { term: "board game", definition: "trò chơi bàn cờ", example: "We played a board game after dinner." },
      { term: "puzzle", definition: "trò xếp hình", example: "This puzzle has one thousand pieces." },
      { term: "recipe", definition: "công thức nấu ăn", example: "I found a new soup recipe online." },
      { term: "streaming service", definition: "dịch vụ xem trực tuyến", example: "Our streaming service has many documentaries." },
      { term: "remote control", definition: "điều khiển từ xa", example: "Where is the remote control?" },
      { term: "speaker", definition: "loa", example: "The speaker sounds clear in this room." },
      { term: "podcast", definition: "podcast", example: "I listen to a language podcast daily." },
      { term: "playlist", definition: "danh sách nhạc", example: "This playlist helps me focus." },
      { term: "knitting", definition: "đan len", example: "My grandmother enjoys knitting." },
      { term: "painting", definition: "vẽ tranh", example: "Painting helps me relax." },
      { term: "craft", definition: "đồ thủ công", example: "The children made craft flowers." },
      { term: "journal", definition: "nhật ký", example: "I write in my journal every night." },
      { term: "baking", definition: "làm bánh", example: "Baking cookies is my weekend hobby." },
      { term: "candle", definition: "nến", example: "We lit a candle during the storm." },
      { term: "blanket", definition: "chăn", example: "I sat on the sofa with a blanket." },
      { term: "cozy", definition: "ấm cúng", partOfSpeech: "ADJECTIVE", example: "The living room feels cozy tonight." },
      { term: "peaceful", definition: "yên bình", partOfSpeech: "ADJECTIVE", example: "The house is peaceful in the morning." },
      { term: "lazy", definition: "lười biếng; thư thả", partOfSpeech: "ADJECTIVE", example: "We had a lazy Sunday afternoon." },
      { term: "tidy up", definition: "dọn dẹp gọn gàng", partOfSpeech: "VERB", example: "I tidy up before guests come." },
      { term: "water plants", definition: "tưới cây", partOfSpeech: "VERB", example: "Please water plants while I am away." },
      { term: "relax", definition: "thư giãn", partOfSpeech: "VERB", example: "I relax by reading short stories." },
      { term: "screen time", definition: "thời gian dùng màn hình", example: "I reduced my screen time this month." },
      { term: "routine", definition: "thói quen hằng ngày", example: "This routine keeps me calm." },
    ],
    seeds: [
      { sentence: "I solved half of the ___ before dinner.", answer: "puzzle", distractors: ["recipe", "routine", "playlist"] },
      { sentence: "Our living room feels very ___ tonight.", answer: "cozy", distractors: ["lazy", "peaceful", "blanket"] },
      { sentence: "Please ___ before our guests arrive.", answer: "tidy up", distractors: ["water plants", "relax", "streaming service"] },
      { sentence: "I wrote three pages in my ___ yesterday.", answer: "journal", distractors: ["novel", "magazine", "craft"] },
      { sentence: "Too much ___ can make your eyes tired.", answer: "screen time", distractors: ["board game", "podcast", "candle"] },
    ],
  },
  {
    unitNumber: 26,
    introVi: "Từ vựng về âm nhạc, nhạc cụ, biểu diễn và cảm nhận khi nghe nhạc.",
    structureSections: [
      { label: "Music types", wordCount: 5 },
      { label: "Instruments", wordCount: 5 },
      { label: "Performance", wordCount: 5 },
      { label: "Song structure", wordCount: 5 },
      { label: "Opinions and habits", wordCount: 5 },
    ],
    collocationHtml: `Học theo cụm sẽ tự nhiên hơn: ${purple("play an instrument")}, ${purple("write a song")}, ${purple("perform live")}, ${purple("listen on repeat")}.`,
    mistakeHtml: `${bold("I very like this melody")} ${bold("[SAI]")} → dùng ${purple("I really like this melody")}.<br>${bold("He sings very good")} ${bold("[SAI]")} → dùng ${purple("He sings very well")}.`,
    principles: [
      {
        title: "THỂ LOẠI ÂM NHẠC",
        body: `Nói gu nghe nhạc bằng các nhãn ${purple("pop")}, ${purple("rock")}, ${purple("jazz")}, ${purple("classical")}.`,
        examples: [
          ex("She listens to jazz while studying.", "Cô ấy nghe nhạc jazz khi học."),
          ex("My father enjoys classical music.", "Bố tôi thích nhạc cổ điển."),
        ],
      },
      {
        title: "BIỂU DIỄN TRÊN SÂN KHẤU",
        body: `Khi nói về buổi diễn, dùng các từ ${purple("concert")}, ${purple("stage")}, ${purple("audience")}, ${purple("encore")}.`,
        examples: [
          ex("The audience cheered loudly.", "Khán giả reo hò rất lớn."),
          ex("The singer came back for an encore.", "Ca sĩ quay lại biểu diễn thêm một bài."),
        ],
      },
      {
        title: "CẤU TRÚC BÀI HÁT",
        body: `Nắm từ khóa của bài hát như ${purple("verse")}, ${purple("chorus")}, ${purple("lyrics")} để nghe hiệu quả hơn.`,
        examples: [
          ex("The chorus is easy to remember.", "Điệp khúc rất dễ nhớ."),
          ex("I love the lyrics of this song.", "Tôi thích lời bài hát này."),
        ],
      },
    ],
    words: [
      { term: "pop", definition: "nhạc pop", example: "Pop songs are popular with teenagers." },
      { term: "rock", definition: "nhạc rock", example: "My brother plays in a rock band." },
      { term: "jazz", definition: "nhạc jazz", example: "We heard jazz at a local cafe." },
      { term: "classical", definition: "nhạc cổ điển", example: "She studies classical piano." },
      { term: "folk", definition: "nhạc dân gian", example: "Folk music tells traditional stories." },
      { term: "guitar", definition: "đàn guitar", example: "He practices guitar every evening." },
      { term: "piano", definition: "đàn piano", example: "The piano in the hall is old." },
      { term: "drums", definition: "trống", example: "My cousin plays drums in a band." },
      { term: "violin", definition: "đàn violin", example: "She carries her violin to class." },
      { term: "keyboard", definition: "đàn phím điện tử", example: "I learned keyboard from videos." },
      { term: "concert", definition: "buổi hòa nhạc", example: "We went to a concert on Friday." },
      { term: "stage", definition: "sân khấu", example: "The singer walked onto the stage." },
      { term: "audience", definition: "khán giả", example: "The audience clapped for five minutes." },
      { term: "microphone", definition: "micro", example: "Please test the microphone first." },
      { term: "band", definition: "ban nhạc", example: "The band released a new single." },
      { term: "melody", definition: "giai điệu", example: "The melody stays in my head." },
      { term: "rhythm", definition: "nhịp điệu", example: "This song has a strong rhythm." },
      { term: "lyrics", definition: "lời bài hát", example: "I memorized the lyrics quickly." },
      { term: "chorus", definition: "điệp khúc", example: "Everyone sang the chorus together." },
      { term: "verse", definition: "khổ nhạc", example: "The first verse is very emotional." },
      { term: "compose", definition: "sáng tác", partOfSpeech: "VERB", example: "She wants to compose film music." },
      { term: "perform", definition: "biểu diễn", partOfSpeech: "VERB", example: "They perform live every weekend." },
      { term: "rehearse", definition: "tập dượt", partOfSpeech: "VERB", example: "The choir rehearses on Thursdays." },
      { term: "talented", definition: "có tài", partOfSpeech: "ADJECTIVE", example: "He is a talented young pianist." },
      { term: "out of tune", definition: "lệch tông", partOfSpeech: "ADJECTIVE", example: "That guitar sounds out of tune." },
    ],
    seeds: [
      { sentence: "I can play the ___, but not the violin.", answer: "guitar", distractors: ["chorus", "band", "verse"] },
      { sentence: "The ___ sang along during the final song.", answer: "audience", distractors: ["stage", "lyrics", "melody"] },
      { sentence: "I love the ___ because the words are meaningful.", answer: "lyrics", distractors: ["rhythm", "keyboard", "concert"] },
      { sentence: "Our group will ___ on stage next month.", answer: "perform", distractors: ["compose", "rehearse", "out of tune"] },
      { sentence: "Please tune your guitar; it is ___.", answer: "out of tune", distractors: ["talented", "classical", "folk"] },
    ],
  },
  {
    unitNumber: 27,
    introVi: "Từ vựng quốc gia, quốc tịch và cách nói về vị trí địa lý, văn hóa.",
    structureSections: [
      { label: "Countries and regions", wordCount: 5 },
      { label: "Nationalities", wordCount: 5 },
      { label: "Geography basics", wordCount: 5 },
      { label: "Travel and culture", wordCount: 5 },
      { label: "Global communication", wordCount: 5 },
    ],
    collocationHtml: `Học theo cụm sẽ tự nhiên hơn: ${purple("come from a country")}, ${purple("speak a language")}, ${purple("cross the border")}, ${purple("respect local customs")}.`,
    mistakeHtml: `${bold("I am come from Vietnam")} ${bold("[SAI]")} → dùng ${purple("I come from Vietnam")}.<br>${bold("He is England")} ${bold("[SAI]")} → dùng ${purple("He is English / He is from England")}.`,
    principles: [
      {
        title: "QUỐC GIA VÀ QUỐC TỊCH",
        body: `Phân biệt rõ ${purple("country")}, ${purple("nationality")}, ${purple("language")} để tránh nhầm khi giới thiệu bản thân.`,
        examples: [
          ex("She is from Brazil.", "Cô ấy đến từ Brazil."),
          ex("She is Brazilian and speaks Portuguese.", "Cô ấy là người Brazil và nói tiếng Bồ Đào Nha."),
        ],
      },
      {
        title: "THUẬT NGỮ ĐỊA LÝ",
        body: `Khi mô tả vị trí, dùng đúng ${purple("border")}, ${purple("continent")}, ${purple("capital city")}.`,
        examples: [
          ex("Hanoi is the capital city of Vietnam.", "Hà Nội là thủ đô của Việt Nam."),
          ex("France shares a border with Spain.", "Pháp có chung biên giới với Tây Ban Nha."),
        ],
      },
      {
        title: "TÔN TRỌNG VĂN HÓA",
        body: `Khi nói về quốc gia khác, ưu tiên từ trung tính và nhắc ${purple("customs")} một cách tôn trọng.`,
        examples: [
          ex("Different countries have different customs.", "Các quốc gia khác nhau có những phong tục khác nhau."),
          ex("We learned local customs before traveling.", "Chúng tôi tìm hiểu phong tục địa phương trước khi đi du lịch."),
        ],
      },
    ],
    words: [
      { term: "country", definition: "quốc gia", example: "Vietnam is a beautiful country." },
      { term: "nation", definition: "dân tộc; quốc gia", example: "Every nation has unique traditions." },
      { term: "region", definition: "khu vực", example: "This region is famous for coffee." },
      { term: "continent", definition: "châu lục", example: "Asia is the largest continent." },
      { term: "border", definition: "biên giới", example: "We crossed the border by bus." },
      { term: "capital city", definition: "thủ đô", example: "Tokyo is the capital city of Japan." },
      { term: "nationality", definition: "quốc tịch", example: "What is your nationality?" },
      { term: "citizen", definition: "công dân", example: "She became a citizen last year." },
      { term: "passport", definition: "hộ chiếu", example: "Always check your passport expiry date." },
      { term: "visa", definition: "thị thực", example: "We applied for a tourist visa." },
      { term: "language", definition: "ngôn ngữ", example: "English is a global language." },
      { term: "accent", definition: "giọng vùng miền/quốc gia", example: "Her accent is easy to understand." },
      { term: "custom", definition: "phong tục", example: "It is a local custom to remove shoes." },
      { term: "tradition", definition: "truyền thống", example: "Tet is an important tradition in Vietnam." },
      { term: "festival", definition: "lễ hội", example: "The city hosts a food festival every summer." },
      { term: "foreign", definition: "nước ngoài", partOfSpeech: "ADJECTIVE", example: "He studies a foreign language." },
      { term: "international", definition: "quốc tế", partOfSpeech: "ADJECTIVE", example: "This is an international school." },
      { term: "local", definition: "địa phương", partOfSpeech: "ADJECTIVE", example: "We tried local dishes." },
      { term: "abroad", definition: "ở nước ngoài", partOfSpeech: "ADVERB", example: "My sister lives abroad now." },
      { term: "immigrate", definition: "nhập cư", partOfSpeech: "VERB", example: "Many families immigrate for work." },
      { term: "emigrate", definition: "di cư ra nước ngoài", partOfSpeech: "VERB", example: "His grandparents emigrated in 1980." },
      { term: "travel document", definition: "giấy tờ đi lại", example: "Please keep all travel documents safe." },
      { term: "currency", definition: "tiền tệ", example: "The local currency is different from ours." },
      { term: "map", definition: "bản đồ", example: "Use a map to find nearby countries." },
      { term: "population", definition: "dân số", example: "The population of the city is growing." },
    ],
    seeds: [
      { sentence: "You need a ___ to enter some countries.", answer: "visa", distractors: ["accent", "border", "currency"] },
      { sentence: "Canada is a ___ in North America.", answer: "country", distractors: ["citizen", "tradition", "passport"] },
      { sentence: "Hanoi is the ___ of Vietnam.", answer: "capital city", distractors: ["region", "continent", "festival"] },
      { sentence: "Please respect local ___ when you travel.", answer: "custom", distractors: ["population", "map", "language"] },
      { sentence: "My brother moved ___ for his master's degree.", answer: "abroad", distractors: ["local", "foreign", "nationality"] },
    ],
  },
  {
    unitNumber: 28,
    introVi: "Từ vựng thời tiết: mô tả khí hậu, dự báo và cách chuẩn bị theo thời tiết.",
    structureSections: [
      { label: "Basic weather words", wordCount: 5 },
      { label: "Temperature and sky", wordCount: 5 },
      { label: "Wind and rain", wordCount: 5 },
      { label: "Forecast and warnings", wordCount: 5 },
      { label: "Weather actions", wordCount: 5 },
    ],
    collocationHtml: `Học theo cụm sẽ tự nhiên hơn: ${purple("check the forecast")}, ${purple("heavy rain")}, ${purple("strong wind")}, ${purple("drop in temperature")}.`,
    mistakeHtml: `${bold("It is sun today")} ${bold("[SAI]")} → dùng ${purple("It is sunny today")}.<br>${bold("The weather is very hotly")} ${bold("[SAI]")} → dùng ${purple("The weather is very hot")}.`,
    principles: [
      {
        title: "TÍNH TỪ THỜI TIẾT",
        body: `Sau chủ ngữ ${purple("It is")}, dùng tính từ như ${purple("cloudy")}, ${purple("sunny")}, ${purple("windy")}.`,
        examples: [
          ex("It is cloudy this morning.", "Sáng nay trời nhiều mây."),
          ex("It is windy near the coast.", "Gần bờ biển trời có nhiều gió."),
        ],
      },
      {
        title: "MÔ TẢ SỰ THAY ĐỔI",
        body: `Diễn tả biến động bằng ${purple("rise")}, ${purple("drop")}, ${purple("clear up")}, ${purple("freeze")}.`,
        examples: [
          ex("The temperature will drop tonight.", "Nhiệt độ sẽ giảm vào tối nay."),
          ex("The sky cleared up in the afternoon.", "Trời đã quang vào buổi chiều."),
        ],
      },
      {
        title: "THỜI TIẾT VÀ KẾ HOẠCH",
        body: `Liên kết từ vựng thời tiết với kế hoạch đi lại, trang phục và hoạt động ngoài trời qua ${purple("forecast")} hoặc ${purple("warning")}.`,
        examples: [
          ex("Take an umbrella because showers are expected.", "Hãy mang theo ô vì dự báo sẽ có mưa rào."),
          ex("We canceled the picnic due to storms.", "Chúng tôi đã hủy buổi dã ngoại vì giông bão."),
        ],
      },
    ],
    words: [
      { term: "weather", definition: "thời tiết", example: "The weather is pleasant today." },
      { term: "forecast", definition: "dự báo thời tiết", example: "The forecast says rain at night." },
      { term: "climate", definition: "khí hậu", example: "The climate here is dry." },
      { term: "temperature", definition: "nhiệt độ", example: "The temperature reached 35 degrees." },
      { term: "season", definition: "mùa", example: "Spring is my favorite season." },
      { term: "sunny", definition: "có nắng", partOfSpeech: "ADJECTIVE", example: "It is sunny and warm outside." },
      { term: "cloudy", definition: "nhiều mây", partOfSpeech: "ADJECTIVE", example: "The sky is cloudy this afternoon." },
      { term: "rainy", definition: "mưa", partOfSpeech: "ADJECTIVE", example: "Today is rainy and cool." },
      { term: "windy", definition: "nhiều gió", partOfSpeech: "ADJECTIVE", example: "It gets windy near the sea." },
      { term: "stormy", definition: "giông bão", partOfSpeech: "ADJECTIVE", example: "It was stormy all night." },
      { term: "humidity", definition: "độ ẩm", example: "High humidity makes me tired." },
      { term: "shower", definition: "mưa rào", example: "A light shower started at noon." },
      { term: "thunder", definition: "sấm", example: "We heard thunder in the distance." },
      { term: "lightning", definition: "tia chớp", example: "Lightning lit up the sky." },
      { term: "fog", definition: "sương mù", example: "Thick fog slowed traffic." },
      { term: "freeze", definition: "đóng băng", partOfSpeech: "VERB", example: "Roads freeze in winter nights." },
      { term: "melt", definition: "tan chảy", partOfSpeech: "VERB", example: "Snow melts quickly in the sun." },
      { term: "rise", definition: "tăng lên", partOfSpeech: "VERB", example: "Temperatures rise in late morning." },
      { term: "drop", definition: "giảm xuống", partOfSpeech: "VERB", example: "The temperature may drop tonight." },
      { term: "clear up", definition: "quang đãng trở lại", partOfSpeech: "VERB", example: "The weather cleared up after lunch." },
      { term: "heatwave", definition: "đợt nắng nóng", example: "The city had a long heatwave." },
      { term: "warning", definition: "cảnh báo", example: "There is a storm warning on TV." },
      { term: "umbrella", definition: "ô dù", example: "Take your umbrella with you." },
      { term: "raincoat", definition: "áo mưa", example: "A raincoat is better than an umbrella on windy days." },
      { term: "forecast app", definition: "ứng dụng dự báo thời tiết", example: "I check a forecast app every morning." },
    ],
    seeds: [
      { sentence: "Please check the ___ before our trip.", answer: "forecast", distractors: ["climate", "season", "humidity"] },
      { sentence: "It is very ___, so wear a jacket.", answer: "windy", distractors: ["sunny", "rainy", "clear up"] },
      { sentence: "The roads can ___ at night in winter.", answer: "freeze", distractors: ["melt", "rise", "drop"] },
      { sentence: "Bring an ___ because showers are expected.", answer: "umbrella", distractors: ["raincoat", "warning", "forecast app"] },
      { sentence: "The temperature may ___ after sunset.", answer: "drop", distractors: ["rise", "clear up", "stormy"] },
    ],
  },
  {
    unitNumber: 29,
    introVi: "Từ vựng về thành phố: địa điểm công cộng, giao thông và chỉ đường.",
    structureSections: [
      { label: "Town places", wordCount: 5 },
      { label: "Transport and roads", wordCount: 5 },
      { label: "Public services", wordCount: 5 },
      { label: "Directions", wordCount: 5 },
      { label: "City life words", wordCount: 5 },
    ],
    collocationHtml: `Học theo cụm sẽ tự nhiên hơn: ${purple("take the bus")}, ${purple("cross the street")}, ${purple("turn left at the corner")}, ${purple("go straight ahead")}.`,
    mistakeHtml: `${bold("Go to straight")} ${bold("[SAI]")} → dùng ${purple("Go straight")}.<br>${bold("The traffic is very crowd")} ${bold("[SAI]")} → dùng ${purple("The traffic is very crowded")}.`,
    principles: [
      {
        title: "CỤM CHỈ ĐỊA ĐIỂM",
        body: `Ghép địa điểm với hành động để nói tự nhiên hơn, ví dụ ${purple("go to the post office")}, ${purple("wait at the bus stop")}.`,
        examples: [
          ex("I went to the post office after work.", "Tôi đã đến bưu điện sau giờ làm."),
          ex("We waited at the bus stop for ten minutes.", "Chúng tôi đợi ở trạm xe buýt mười phút."),
        ],
      },
      {
        title: "CHỈ ĐƯỜNG",
        body: `Khi hướng dẫn đường, ưu tiên cụm ngắn và rõ như ${purple("turn left")}, ${purple("turn right")}, ${purple("next to")}, ${purple("opposite")}.`,
        examples: [
          ex("Turn right at the traffic lights.", "Hãy rẽ phải ở đèn giao thông."),
          ex("The bank is opposite the museum.", "Ngân hàng nằm đối diện bảo tàng."),
        ],
      },
      {
        title: "MÔ TẢ THÀNH PHỐ",
        body: `Dùng tính từ phù hợp bối cảnh đô thị như ${purple("busy")}, ${purple("crowded")}, ${purple("convenient")}, ${purple("noisy")}.`,
        examples: [
          ex("The city center is crowded at rush hour.", "Trung tâm thành phố đông đúc vào giờ cao điểm."),
          ex("Public transport is convenient here.", "Giao thông công cộng ở đây rất thuận tiện."),
        ],
      },
    ],
    words: [
      { term: "town center", definition: "trung tâm thị trấn/thành phố", example: "The town center is busy at night." },
      { term: "square", definition: "quảng trường", example: "People gather in the square on weekends." },
      { term: "museum", definition: "bảo tàng", example: "The museum is free on Sundays." },
      { term: "library", definition: "thư viện", example: "I study at the library every evening." },
      { term: "post office", definition: "bưu điện", example: "The post office closes at five." },
      { term: "bus stop", definition: "trạm xe buýt", example: "Meet me at the bus stop." },
      { term: "station", definition: "nhà ga", example: "The station is ten minutes away." },
      { term: "crossroad", definition: "ngã tư", example: "Turn left at the crossroad." },
      { term: "traffic lights", definition: "đèn giao thông", example: "Wait at the traffic lights." },
      { term: "sidewalk", definition: "vỉa hè", example: "Please walk on the sidewalk." },
      { term: "police station", definition: "đồn cảnh sát", example: "Ask at the police station for help." },
      { term: "hospital", definition: "bệnh viện", example: "The hospital is near the bridge." },
      { term: "city hall", definition: "tòa thị chính", example: "City hall is open on weekdays." },
      { term: "bank", definition: "ngân hàng", example: "I need to go to the bank." },
      { term: "pharmacy", definition: "nhà thuốc", example: "There is a pharmacy next to the cafe." },
      { term: "turn left", definition: "rẽ trái", partOfSpeech: "VERB", example: "Turn left after the bridge." },
      { term: "turn right", definition: "rẽ phải", partOfSpeech: "VERB", example: "Turn right at the corner." },
      { term: "go straight", definition: "đi thẳng", partOfSpeech: "VERB", example: "Go straight for two blocks." },
      { term: "next to", definition: "bên cạnh", partOfSpeech: "PREPOSITION", example: "The bakery is next to the bank." },
      { term: "opposite", definition: "đối diện", partOfSpeech: "PREPOSITION", example: "The school is opposite the park." },
      { term: "busy", definition: "nhộn nhịp", partOfSpeech: "ADJECTIVE", example: "The main street is always busy." },
      { term: "crowded", definition: "đông đúc", partOfSpeech: "ADJECTIVE", example: "The bus is crowded in the morning." },
      { term: "convenient", definition: "thuận tiện", partOfSpeech: "ADJECTIVE", example: "This location is convenient for work." },
      { term: "noisy", definition: "ồn ào", partOfSpeech: "ADJECTIVE", example: "The market area is noisy." },
      { term: "pedestrian", definition: "người đi bộ", example: "Drivers must stop for pedestrians." },
    ],
    seeds: [
      { sentence: "Meet me at the ___ near our office.", answer: "bus stop", distractors: ["station", "hospital", "bank"] },
      { sentence: "The museum is ___ the city hall.", answer: "opposite", distractors: ["busy", "crowded", "turn right"] },
      { sentence: "Please ___ at the corner and walk two blocks.", answer: "turn left", distractors: ["go straight", "turn right", "next to"] },
      { sentence: "The old market gets very ___ at rush hour.", answer: "crowded", distractors: ["convenient", "busy", "noisy"] },
      { sentence: "Use the ___ when crossing this road.", answer: "sidewalk", distractors: ["crossroad", "traffic lights", "pedestrian"] },
    ],
  },
  {
    unitNumber: 30,
    introVi: "Từ vựng về nông thôn: cảnh quan, nông trại và nhịp sống ngoài thành phố.",
    structureSections: [
      { label: "Landscape", wordCount: 5 },
      { label: "Farm life", wordCount: 5 },
      { label: "Animals and crops", wordCount: 5 },
      { label: "Rural homes and roads", wordCount: 5 },
      { label: "Lifestyle and feelings", wordCount: 5 },
    ],
    collocationHtml: `Học theo cụm sẽ tự nhiên hơn: ${purple("work on a farm")}, ${purple("feed the animals")}, ${purple("walk along a dirt road")}, ${purple("enjoy fresh air")}.`,
    mistakeHtml: `${bold("Countryside is very peace")} ${bold("[SAI]")} → dùng ${purple("The countryside is very peaceful")}.<br>${bold("There have many trees")} ${bold("[SAI]")} → dùng ${purple("There are many trees")}.`,
    principles: [
      {
        title: "CẢNH QUAN NÔNG THÔN",
        body: `Khi tả cảnh, dùng danh từ cụ thể như ${purple("field")}, ${purple("hill")}, ${purple("river")}, ${purple("forest")}.`,
        examples: [
          ex("A river runs behind the village.", "Một con sông chảy phía sau ngôi làng."),
          ex("We walked across a wide field.", "Chúng tôi đi bộ qua một cánh đồng rộng."),
        ],
      },
      {
        title: "CÔNG VIỆC NÔNG TRẠI",
        body: `Diễn tả sinh hoạt nông trại bằng ${purple("plant")}, ${purple("harvest")}, ${purple("feed")}, ${purple("raise")}.`,
        examples: [
          ex("They harvest rice in early autumn.", "Họ thu hoạch lúa vào đầu mùa thu."),
          ex("He feeds the chickens every morning.", "Anh ấy cho gà ăn mỗi sáng."),
        ],
      },
      {
        title: "SO SÁNH LỐI SỐNG",
        body: `Khi so sánh với thành phố, dùng ${purple("quiet")}, ${purple("peaceful")}, ${purple("spacious")} để nêu cảm nhận.`,
        examples: [
          ex("The countryside is quieter than the city.", "Nông thôn yên tĩnh hơn thành phố."),
          ex("Their new house is spacious and bright.", "Ngôi nhà mới của họ rộng rãi và sáng sủa."),
        ],
      },
    ],
    words: [
      { term: "countryside", definition: "vùng nông thôn", example: "My grandparents live in the countryside." },
      { term: "village", definition: "làng", example: "The village is surrounded by rice fields." },
      { term: "field", definition: "cánh đồng", example: "Farmers are working in the field." },
      { term: "hill", definition: "đồi", example: "We climbed a small hill at sunset." },
      { term: "river", definition: "sông", example: "Children were fishing by the river." },
      { term: "farm", definition: "nông trại", example: "They run a small vegetable farm." },
      { term: "barn", definition: "chuồng/kho nông trại", example: "The tools are stored in the barn." },
      { term: "tractor", definition: "máy kéo", example: "A tractor moved slowly across the field." },
      { term: "fence", definition: "hàng rào", example: "The cows stood near the fence." },
      { term: "well", definition: "giếng", example: "The old well still has clean water." },
      { term: "crop", definition: "mùa vụ; cây trồng", example: "This year's rice crop is strong." },
      { term: "harvest", definition: "thu hoạch", partOfSpeech: "VERB", example: "They harvest corn in September." },
      { term: "plant", definition: "trồng", partOfSpeech: "VERB", example: "We plant flowers near the gate." },
      { term: "feed", definition: "cho ăn", partOfSpeech: "VERB", example: "Please feed the chickens at five." },
      { term: "raise", definition: "nuôi (gia súc)", partOfSpeech: "VERB", example: "My uncle raises goats." },
      { term: "chicken", definition: "gà", example: "The chicken ran across the yard." },
      { term: "cow", definition: "bò", example: "A cow was drinking from the stream." },
      { term: "goat", definition: "dê", example: "Goats can climb steep hills." },
      { term: "rice field", definition: "ruộng lúa", example: "The rice field looks bright green." },
      { term: "vegetable garden", definition: "vườn rau", example: "Her vegetable garden grows quickly in spring." },
      { term: "dirt road", definition: "đường đất", example: "We cycled along a dirt road." },
      { term: "quiet", definition: "yên tĩnh", partOfSpeech: "ADJECTIVE", example: "The village is very quiet at night." },
      { term: "peaceful", definition: "thanh bình", partOfSpeech: "ADJECTIVE", example: "It is a peaceful place to live." },
      { term: "fresh air", definition: "không khí trong lành", example: "I love the fresh air in the morning." },
      { term: "spacious", definition: "rộng rãi", partOfSpeech: "ADJECTIVE", example: "Their farmhouse is spacious and comfortable." },
    ],
    seeds: [
      { sentence: "My aunt works on a small ___ outside town.", answer: "farm", distractors: ["hill", "river", "village"] },
      { sentence: "We walked along a ___ after the rain.", answer: "dirt road", distractors: ["fence", "barn", "well"] },
      { sentence: "Farmers usually ___ rice in late autumn.", answer: "harvest", distractors: ["plant", "feed", "raise"] },
      { sentence: "The countryside air feels very ___.", answer: "fresh air", distractors: ["quiet", "peaceful", "spacious"] },
      { sentence: "The town is noisy, but the village is ___.", answer: "quiet", distractors: ["spacious", "farm", "tractor"] },
    ],
  },
];

export const EVIU_UNITS_16_30: VocabularyUnit[] = UNIT_DRAFTS.map((draft) =>
  buildEviuUnit(getCatalogEntryByUnitNumber(draft.unitNumber), buildUnitContent(draft)),
);
