import { assertExerciseCount, cloze, match, mcq } from "./eviu-elementary-curated-helpers";
import type { VocabularyExercise } from "@/lib/vocabulary/vocabulary-unit-types";

const UNIT_16: VocabularyExercise[] = [
  match("ex-pre-16-1", "16 · Ghép từ với nghĩa", [
    { left: "alarm clock", right: "đồng hồ báo thức" },
    { left: "commute", right: "đi lại hằng ngày giữa nhà và nơi làm" },
    { left: "rush hour", right: "giờ cao điểm giao thông" },
    { left: "shift", right: "ca làm việc" },
    { left: "bedtime", right: "giờ đi ngủ" },
    { left: "punctual", right: "đúng giờ" },
  ]),
  cloze("ex-pre-16-2", "16 · Điền cụm", "I usually ___ before sunrise.", "wake up", ["Wake up"]),
  cloze("ex-pre-16-3", "16 · Điền cụm", "Staff must ___ before 8:30.", "clock in", ["Clock in"]),
  cloze("ex-pre-16-4", "16 · Điền cụm", "I ___ after two hours of study.", "take a break", ["Take a break"]),
  cloze("ex-pre-16-5", "16 · Điền cụm", "I ___ after lunch on Saturdays.", "run errands", ["Run errands"]),
  cloze("ex-pre-16-6", "16 · Điền cụm", "___ saves time on busy weekdays.", "Meal prep", ["meal prep"]),
  cloze("ex-pre-16-7", "16 · Điền cụm", "I read a book to ___ at night.", "wind down", ["Wind down"]),
  cloze("ex-pre-16-8", "16 · Điền từ", "I ___ and missed the first bus.", "overslept", ["Overslept", "oversleep", "Oversleep"]),
  mcq("ex-pre-16-9", "16 · Chọn đáp án", "Từ nào mô tả tình trạng bận rộn và gấp gáp?", "b", [
    { key: "a", label: "punctual" },
    { key: "b", label: "hectic" },
    { key: "c", label: "spare" },
    { key: "d", label: "household" },
  ]),
  mcq("ex-pre-16-10", "16 · Chọn đáp án", "Từ nào nghĩa là hoãn chuông báo thức thêm vài phút?", "c", [
    { key: "a", label: "wind down" },
    { key: "b", label: "clock in" },
    { key: "c", label: "snooze" },
    { key: "d", label: "commute" },
  ]),
  mcq("ex-pre-16-11", "16 · Chọn đáp án", "Cụm nào nghĩa là làm việc nhà thường ngày?", "a", [
    { key: "a", label: "do chores" },
    { key: "b", label: "take a break" },
    { key: "c", label: "run errands" },
    { key: "d", label: "get dressed" },
  ]),
  mcq("ex-pre-16-12", "16 · Chọn đáp án", "\"To ___\" means to stop sleeping and get up.", "d", [
    { key: "a", label: "snooze" },
    { key: "b", label: "commute" },
    { key: "c", label: "oversleep" },
    { key: "d", label: "wake up" },
  ]),
  mcq("ex-pre-16-13", "16 · Chọn đáp án", "Từ nào chỉ ca làm việc?", "b", [
    { key: "a", label: "commute" },
    { key: "b", label: "shift" },
    { key: "c", label: "bedtime" },
    { key: "d", label: "errand" },
  ]),
  mcq("ex-pre-16-14", "16 · Chọn đáp án", "Người luôn đến đúng giờ thì ___", "c", [
    { key: "a", label: "hectic" },
    { key: "b", label: "household" },
    { key: "c", label: "punctual" },
    { key: "d", label: "dressed" },
  ]),
];

const UNIT_17: VocabularyExercise[] = [
  match("ex-pre-17-1", "17 · Ghép từ với nghĩa", [
    { left: "neighbourhood", right: "khu dân cư nơi mình sống" },
    { left: "suburb", right: "vùng ngoại ô" },
    { left: "landlord", right: "chủ nhà cho thuê" },
    { left: "tenant", right: "người thuê nhà" },
    { left: "mortgage", right: "khoản vay mua nhà" },
    { left: "green space", right: "không gian xanh trong khu dân cư" },
  ]),
  cloze("ex-pre-17-2", "17 · Điền từ", "I work ___ but live outside the city.", "downtown", ["Downtown"]),
  cloze("ex-pre-17-3", "17 · Điền cụm", "They bought a ___ last year.", "detached house", ["Detached house"]),
  cloze("ex-pre-17-4", "17 · Điền cụm", "___ are higher in winter.", "Utility bills", ["utility bills", "Utility bill", "utility bill"]),
  cloze("ex-pre-17-5", "17 · Điền cụm", "It took us a month to ___.", "settle in", ["Settle in"]),
  cloze("ex-pre-17-6", "17 · Điền cụm", "Our new neighbors will ___ next week.", "move in", ["Move in"]),
  cloze("ex-pre-17-7", "17 · Điền cụm", "I ___ in this city now.", "feel at home", ["Feel at home"]),
  cloze("ex-pre-17-8", "17 · Điền từ", "___ in this area has increased a lot.", "Rent", ["rent"]),
  mcq("ex-pre-17-9", "17 · Chọn đáp án", "Từ nào chỉ người thuê nhà?", "b", [
    { key: "a", label: "landlord" },
    { key: "b", label: "tenant" },
    { key: "c", label: "resident" },
    { key: "d", label: "owner" },
  ]),
  mcq("ex-pre-17-10", "17 · Chọn đáp án", "Từ nào chỉ chủ nhà cho thuê?", "a", [
    { key: "a", label: "landlord" },
    { key: "b", label: "tenant" },
    { key: "c", label: "neighbour" },
    { key: "d", label: "guest" },
  ]),
  mcq("ex-pre-17-11", "17 · Chọn đáp án", "Tính từ nào nghĩa là thuận tiện?", "c", [
    { key: "a", label: "noisy" },
    { key: "b", label: "remote" },
    { key: "c", label: "convenient" },
    { key: "d", label: "empty" },
  ]),
  mcq("ex-pre-17-12", "17 · Chọn đáp án", "Tính từ nào nghĩa là ồn ào?", "b", [
    { key: "a", label: "quiet" },
    { key: "b", label: "noisy" },
    { key: "c", label: "calm" },
    { key: "d", label: "convenient" },
  ]),
  mcq("ex-pre-17-13", "17 · Chọn đáp án", "Cụm nào chỉ tòa chung cư?", "a", [
    { key: "a", label: "apartment block" },
    { key: "b", label: "detached house" },
    { key: "c", label: "green space" },
    { key: "d", label: "suburb" },
  ]),
  mcq("ex-pre-17-14", "17 · Chọn đáp án", "Cụm nào chỉ tiện ích địa phương như công viên, trường học?", "d", [
    { key: "a", label: "green space" },
    { key: "b", label: "residential area" },
    { key: "c", label: "utility bill" },
    { key: "d", label: "local amenity" },
  ]),
];

const UNIT_18: VocabularyExercise[] = [
  match("ex-pre-18-1", "18 · Ghép từ với nghĩa", [
    { left: "hallway", right: "hành lang trong nhà" },
    { left: "shelf", right: "kệ" },
    { left: "drawer", right: "ngăn kéo" },
    { left: "plug socket", right: "ổ cắm điện" },
    { left: "vacuum cleaner", right: "máy hút bụi" },
    { left: "spare key", right: "chìa khóa dự phòng" },
  ]),
  cloze("ex-pre-18-2", "18 · Điền từ", "Her keys are in the top ___.", "drawer", ["Drawer"]),
  cloze("ex-pre-18-3", "18 · Điền từ", "I put the books back on the ___.", "shelf", ["Shelf"]),
  cloze("ex-pre-18-4", "18 · Điền cụm", "Please ___ the living room before guests arrive.", "tidy up", ["Tidy up"]),
  cloze("ex-pre-18-5", "18 · Điền cụm", "I ___ the kitchen counter every night.", "wipe down", ["Wipe down"]),
  cloze("ex-pre-18-6", "18 · Điền từ", "We found a ___ under the sink.", "leak", ["Leak"]),
  cloze("ex-pre-18-7", "18 · Điền cụm", "Use an ___ for the fan.", "extension lead", ["Extension lead"]),
  cloze("ex-pre-18-8", "18 · Điền cụm", "A fridge is an essential ___.", "home appliance", ["Home appliance"]),
  mcq("ex-pre-18-9", "18 · Chọn đáp án", "Từ nào chỉ ổ cắm điện trên tường?", "a", [
    { key: "a", label: "plug socket" },
    { key: "b", label: "drawer" },
    { key: "c", label: "shelf" },
    { key: "d", label: "hallway" },
  ]),
  mcq("ex-pre-18-10", "18 · Chọn đáp án", "Từ nào nghĩa là sạch bong không tì vết?", "b", [
    { key: "a", label: "cluttered" },
    { key: "b", label: "spotless" },
    { key: "c", label: "dusty" },
    { key: "d", label: "tidy" },
  ]),
  mcq("ex-pre-18-11", "18 · Chọn đáp án", "Từ nào chỉ sự bừa bộn?", "c", [
    { key: "a", label: "leak" },
    { key: "b", label: "shelf" },
    { key: "c", label: "clutter" },
    { key: "d", label: "mop" },
  ]),
  mcq("ex-pre-18-12", "18 · Chọn đáp án", "Từ nào chỉ cây lau nhà?", "a", [
    { key: "a", label: "mop" },
    { key: "b", label: "drawer" },
    { key: "c", label: "shelf" },
    { key: "d", label: "socket" },
  ]),
  mcq("ex-pre-18-13", "18 · Chọn đáp án", "Cụm nào chỉ giỏ đựng quần áo bẩn?", "d", [
    { key: "a", label: "dishwasher" },
    { key: "b", label: "ironing board" },
    { key: "c", label: "storage cupboard" },
    { key: "d", label: "laundry basket" },
  ]),
  mcq("ex-pre-18-14", "18 · Chọn đáp án", "Từ nào chỉ máy rửa chén?", "b", [
    { key: "a", label: "vacuum cleaner" },
    { key: "b", label: "dishwasher" },
    { key: "c", label: "mop" },
    { key: "d", label: "appliance" },
  ]),
];

const UNIT_19: VocabularyExercise[] = [
  match("ex-pre-19-1", "19 · Ghép từ với nghĩa", [
    { left: "budget", right: "ngân sách chi tiêu" },
    { left: "income", right: "thu nhập" },
    { left: "expense", right: "khoản chi" },
    { left: "debt", right: "khoản nợ" },
    { left: "receipt", right: "hóa đơn mua hàng" },
    { left: "interest rate", right: "lãi suất" },
  ]),
  cloze("ex-pre-19-2", "19 · Điền từ", "I set a weekly ___ for groceries.", "budget", ["Budget"]),
  cloze("ex-pre-19-3", "19 · Điền từ", "Transport is my biggest monthly ___.", "expense", ["Expense"]),
  cloze("ex-pre-19-4", "19 · Điền từ", "He is trying to pay off his ___.", "debt", ["Debt"]),
  cloze("ex-pre-19-5", "19 · Điền cụm", "I need to ___ on eating out.", "cut back", ["Cut back"]),
  cloze("ex-pre-19-6", "19 · Điền cụm", "I ___ to my parents every month.", "transfer money", ["Transfer money"]),
  cloze("ex-pre-19-7", "19 · Điền cụm", "An ___ gives you peace of mind.", "emergency fund", ["Emergency fund"]),
  cloze("ex-pre-19-8", "19 · Điền từ", "This jacket was a real ___.", "bargain", ["Bargain"]),
  mcq("ex-pre-19-9", "19 · Chọn đáp án", "Từ nào chỉ khoản tiền vào bạn nhận được?", "b", [
    { key: "a", label: "expense" },
    { key: "b", label: "income" },
    { key: "c", label: "debt" },
    { key: "d", label: "refund" },
  ]),
  mcq("ex-pre-19-10", "19 · Chọn đáp án", "Cụm nào chỉ quỹ dự phòng khi có việc khẩn cấp?", "b", [
    { key: "a", label: "savings account" },
    { key: "b", label: "emergency fund" },
    { key: "c", label: "cash withdrawal" },
    { key: "d", label: "cost of living" },
  ]),
  mcq("ex-pre-19-11", "19 · Chọn đáp án", "Động từ nào nghĩa là có khả năng chi trả?", "a", [
    { key: "a", label: "afford" },
    { key: "b", label: "refund" },
    { key: "c", label: "budget" },
    { key: "d", label: "owe" },
  ]),
  mcq("ex-pre-19-12", "19 · Chọn đáp án", "Tính từ nào nghĩa là bị bán quá đắt?", "c", [
    { key: "a", label: "affordable" },
    { key: "b", label: "cheap" },
    { key: "c", label: "overpriced" },
    { key: "d", label: "fair" },
  ]),
  mcq("ex-pre-19-13", "19 · Chọn đáp án", "Cụm nào chỉ chi phí sinh hoạt?", "d", [
    { key: "a", label: "interest rate" },
    { key: "b", label: "savings account" },
    { key: "c", label: "financial goal" },
    { key: "d", label: "cost of living" },
  ]),
  mcq("ex-pre-19-14", "19 · Chọn đáp án", "Từ nào chỉ khoản trả góp theo kỳ?", "a", [
    { key: "a", label: "instalment" },
    { key: "b", label: "refund" },
    { key: "c", label: "bargain" },
    { key: "d", label: "receipt" },
  ]),
];

const UNIT_20: VocabularyExercise[] = [
  match("ex-pre-20-1", "20 · Ghép từ với nghĩa", [
    { left: "symptom", right: "triệu chứng bệnh" },
    { left: "sore throat", right: "đau họng" },
    { left: "prescription", right: "đơn thuốc" },
    { left: "recover", right: "hồi phục" },
    { left: "immune system", right: "hệ miễn dịch" },
    { left: "side effect", right: "tác dụng phụ" },
  ]),
  cloze("ex-pre-20-2", "20 · Điền cụm", "I stayed home because of a ___.", "sore throat", ["Sore throat"]),
  cloze("ex-pre-20-3", "20 · Điền cụm", "A ___ is common in cold weather.", "runny nose", ["Runny nose"]),
  cloze("ex-pre-20-4", "20 · Điền từ", "It took her a week to ___ fully.", "recover", ["Recover"]),
  cloze("ex-pre-20-5", "20 · Điền cụm", "You should ___ this weekend.", "rest up", ["Rest up"]),
  cloze("ex-pre-20-6", "20 · Điền cụm", "Remember to ___ after meals.", "take medicine", ["Take medicine"]),
  cloze("ex-pre-20-7", "20 · Điền cụm", "A ___ supports overall health.", "balanced diet", ["Balanced diet"]),
  cloze("ex-pre-20-8", "20 · Điền từ", "I go for a ___ twice a year.", "check-up", ["Check-up"]),
  mcq("ex-pre-20-9", "20 · Chọn đáp án", "Từ nào là đơn thuốc bác sĩ đưa cho bệnh nhân?", "b", [
    { key: "a", label: "symptom" },
    { key: "b", label: "prescription" },
    { key: "c", label: "check-up" },
    { key: "d", label: "diet" },
  ]),
  mcq("ex-pre-20-10", "20 · Chọn đáp án", "Từ nào mang nghĩa mất nước?", "b", [
    { key: "a", label: "chronic" },
    { key: "b", label: "dehydrated" },
    { key: "c", label: "balanced" },
    { key: "d", label: "immune" },
  ]),
  mcq("ex-pre-20-11", "20 · Chọn đáp án", "Động từ nào nghĩa là kê đơn thuốc?", "a", [
    { key: "a", label: "prescribe" },
    { key: "b", label: "recover" },
    { key: "c", label: "examine" },
    { key: "d", label: "prevent" },
  ]),
  mcq("ex-pre-20-12", "20 · Chọn đáp án", "Tính từ nào nghĩa là mãn tính, kéo dài?", "c", [
    { key: "a", label: "acute" },
    { key: "b", label: "mild" },
    { key: "c", label: "chronic" },
    { key: "d", label: "severe" },
  ]),
  mcq("ex-pre-20-13", "20 · Chọn đáp án", "Cụm nào chỉ huyết áp?", "d", [
    { key: "a", label: "immune system" },
    { key: "b", label: "muscle strain" },
    { key: "c", label: "side effect" },
    { key: "d", label: "blood pressure" },
  ]),
  mcq("ex-pre-20-14", "20 · Chọn đáp án", "Cụm nào chỉ sức khỏe tinh thần?", "b", [
    { key: "a", label: "blood pressure" },
    { key: "b", label: "mental wellbeing" },
    { key: "c", label: "balanced diet" },
    { key: "d", label: "check-up" },
  ]),
];

const UNIT_21: VocabularyExercise[] = [
  match("ex-pre-21-1", "21 · Ghép từ với nghĩa", [
    { left: "sleeve", right: "ống tay áo" },
    { left: "collar", right: "cổ áo" },
    { left: "fabric", right: "chất liệu vải" },
    { left: "cotton", right: "vải cotton" },
    { left: "wool", right: "len" },
    { left: "outfit", right: "bộ trang phục hoàn chỉnh" },
  ]),
  cloze("ex-pre-21-2", "21 · Điền từ", "The ___ are too long for me.", "sleeves", ["Sleeves", "sleeve", "Sleeve"]),
  cloze("ex-pre-21-3", "21 · Điền từ", "This ___ feels soft and breathable.", "fabric", ["Fabric"]),
  cloze("ex-pre-21-4", "21 · Điền từ", "I prefer ___ in hot weather.", "cotton", ["Cotton"]),
  cloze("ex-pre-21-5", "21 · Điền từ", "This ___ sweater is very warm.", "wool", ["Wool"]),
  cloze("ex-pre-21-6", "21 · Điền cụm", "Can I ___ this jacket?", "try on", ["Try on"]),
  cloze("ex-pre-21-7", "21 · Điền từ", "You should ___ your clothes in winter.", "layer", ["Layer"]),
  cloze("ex-pre-21-8", "21 · Điền cụm", "___ is required for the event.", "Formal wear", ["formal wear"]),
  mcq("ex-pre-21-9", "21 · Chọn đáp án", "Từ nào chỉ phần cổ của áo?", "b", [
    { key: "a", label: "sleeve" },
    { key: "b", label: "collar" },
    { key: "c", label: "fabric" },
    { key: "d", label: "outfit" },
  ]),
  mcq("ex-pre-21-10", "21 · Chọn đáp án", "Tính từ nào nghĩa là rộng, không ôm sát?", "a", [
    { key: "a", label: "loose-fitting" },
    { key: "b", label: "tight-fitting" },
    { key: "c", label: "plain" },
    { key: "d", label: "patterned" },
  ]),
  mcq("ex-pre-21-11", "21 · Chọn đáp án", "Tính từ nào nghĩa là ôm sát người?", "b", [
    { key: "a", label: "loose-fitting" },
    { key: "b", label: "tight-fitting" },
    { key: "c", label: "comfortable" },
    { key: "d", label: "plain" },
  ]),
  mcq("ex-pre-21-12", "21 · Chọn đáp án", "Tính từ nào nghĩa là trơn, không họa tiết?", "c", [
    { key: "a", label: "patterned" },
    { key: "b", label: "woolly" },
    { key: "c", label: "plain" },
    { key: "d", label: "formal" },
  ]),
  mcq("ex-pre-21-13", "21 · Chọn đáp án", "Tính từ nào nghĩa là có họa tiết?", "a", [
    { key: "a", label: "patterned" },
    { key: "b", label: "plain" },
    { key: "c", label: "loose" },
    { key: "d", label: "casual" },
  ]),
  mcq("ex-pre-21-14", "21 · Chọn đáp án", "Cụm nào chỉ trang phục thường ngày?", "d", [
    { key: "a", label: "formal wear" },
    { key: "b", label: "outfit" },
    { key: "c", label: "fabric" },
    { key: "d", label: "casual wear" },
  ]),
];

const UNIT_22: VocabularyExercise[] = [
  match("ex-pre-22-1", "22 · Ghép từ với nghĩa", [
    { left: "changing room", right: "phòng thử đồ" },
    { left: "refund policy", right: "chính sách hoàn tiền" },
    { left: "size chart", right: "bảng kích cỡ" },
    { left: "discount code", right: "mã giảm giá" },
    { left: "shop assistant", right: "nhân viên bán hàng" },
    { left: "quality", right: "chất lượng" },
  ]),
  cloze("ex-pre-22-2", "22 · Điền cụm", "This size is still ___.", "in stock", ["In stock"]),
  cloze("ex-pre-22-3", "22 · Điền cụm", "Sorry, black is ___.", "out of stock", ["Out of stock"]),
  cloze("ex-pre-22-4", "22 · Điền cụm", "I used a ___ at checkout.", "discount code", ["Discount code"]),
  cloze("ex-pre-22-5", "22 · Điền cụm", "We bought coats during the ___.", "seasonal sale", ["Seasonal sale"]),
  cloze("ex-pre-22-6", "22 · Điền cụm", "Check the ___ before ordering online.", "size chart", ["Size chart"]),
  cloze("ex-pre-22-7", "22 · Điền cụm", "Can I ___ here?", "pay by card", ["Pay by card"]),
  cloze("ex-pre-22-8", "22 · Điền cụm", "___ in case you need a refund.", "Keep the receipt", ["keep the receipt"]),
  mcq("ex-pre-22-9", "22 · Chọn đáp án", "Cụm nào nghĩa là đã hết hàng?", "b", [
    { key: "a", label: "in stock" },
    { key: "b", label: "out of stock" },
    { key: "c", label: "on trend" },
    { key: "d", label: "in queue" },
  ]),
  mcq("ex-pre-22-10", "22 · Chọn đáp án", "Từ nào mô tả món mua không nằm trong kế hoạch?", "b", [
    { key: "a", label: "seasonal sale" },
    { key: "b", label: "impulse buy" },
    { key: "c", label: "affordable" },
    { key: "d", label: "timeless" },
  ]),
  mcq("ex-pre-22-11", "22 · Chọn đáp án", "Tính từ nào nghĩa là đúng xu hướng?", "a", [
    { key: "a", label: "on trend" },
    { key: "b", label: "timeless" },
    { key: "c", label: "affordable" },
    { key: "d", label: "faulty" },
  ]),
  mcq("ex-pre-22-12", "22 · Chọn đáp án", "Tính từ nào nghĩa là không lỗi mốt?", "c", [
    { key: "a", label: "on trend" },
    { key: "b", label: "brand-conscious" },
    { key: "c", label: "timeless" },
    { key: "d", label: "cheap" },
  ]),
  mcq("ex-pre-22-13", "22 · Chọn đáp án", "Tính từ nào nghĩa là giá phải chăng?", "d", [
    { key: "a", label: "overpriced" },
    { key: "b", label: "timeless" },
    { key: "c", label: "on trend" },
    { key: "d", label: "affordable" },
  ]),
  mcq("ex-pre-22-14", "22 · Chọn đáp án", "Động từ nào nghĩa là đổi hàng?", "b", [
    { key: "a", label: "refund" },
    { key: "b", label: "exchange" },
    { key: "c", label: "queue" },
    { key: "d", label: "browse" },
  ]),
];

const UNIT_23: VocabularyExercise[] = [
  match("ex-pre-23-1", "23 · Ghép từ với nghĩa", [
    { left: "shopping mall", right: "trung tâm mua sắm" },
    { left: "department store", right: "cửa hàng bách hóa tổng hợp" },
    { left: "convenience store", right: "cửa hàng tiện lợi" },
    { left: "aisle", right: "lối giữa các kệ hàng" },
    { left: "checkout counter", right: "quầy thanh toán" },
    { left: "loyalty card", right: "thẻ khách hàng thân thiết" },
  ]),
  cloze("ex-pre-23-2", "23 · Điền từ", "I only need a ___ for a few items.", "basket", ["Basket"]),
  cloze("ex-pre-23-3", "23 · Điền từ", "Take a ___ if you buy in bulk.", "trolley", ["Trolley"]),
  cloze("ex-pre-23-4", "23 · Điền từ", "We ___ for half an hour.", "browsed", ["Browsed", "browse", "Browse"]),
  cloze("ex-pre-23-5", "23 · Điền cụm", "Smart shoppers ___ first.", "compare prices", ["Compare prices"]),
  cloze("ex-pre-23-6", "23 · Điền cụm", "I contacted ___ because the product was broken.", "customer service", ["Customer service"]),
  cloze("ex-pre-23-7", "23 · Điền cụm", "Many people ___ after work.", "shop online", ["Shop online"]),
  cloze("ex-pre-23-8", "23 · Điền cụm", "I booked an evening ___.", "delivery slot", ["Delivery slot"]),
  mcq("ex-pre-23-9", "23 · Chọn đáp án", "Từ nào chỉ xe đẩy lớn trong siêu thị?", "b", [
    { key: "a", label: "basket" },
    { key: "b", label: "trolley" },
    { key: "c", label: "aisle" },
    { key: "d", label: "counter" },
  ]),
  mcq("ex-pre-23-10", "23 · Chọn đáp án", "Cụm nào nghĩa là bán hết hàng?", "a", [
    { key: "a", label: "sold out" },
    { key: "b", label: "queue up" },
    { key: "c", label: "shop now" },
    { key: "d", label: "special offer" },
  ]),
  mcq("ex-pre-23-11", "23 · Chọn đáp án", "Cụm nào chỉ ưu đãi đặc biệt?", "c", [
    { key: "a", label: "loyalty card" },
    { key: "b", label: "faulty item" },
    { key: "c", label: "special offer" },
    { key: "d", label: "delivery slot" },
  ]),
  mcq("ex-pre-23-12", "23 · Chọn đáp án", "Cụm nào chỉ sản phẩm bị lỗi?", "b", [
    { key: "a", label: "special offer" },
    { key: "b", label: "faulty item" },
    { key: "c", label: "loyalty card" },
    { key: "d", label: "basket" },
  ]),
  mcq("ex-pre-23-13", "23 · Chọn đáp án", "Cụm nào nghĩa là trả lại hàng?", "d", [
    { key: "a", label: "shop online" },
    { key: "b", label: "compare prices" },
    { key: "c", label: "sold out" },
    { key: "d", label: "return an item" },
  ]),
  mcq("ex-pre-23-14", "23 · Chọn đáp án", "Động từ nào nghĩa là xếp hàng?", "a", [
    { key: "a", label: "queue" },
    { key: "b", label: "browse" },
    { key: "c", label: "board" },
    { key: "d", label: "refund" },
  ]),
];

const UNIT_24: VocabularyExercise[] = [
  match("ex-pre-24-1", "24 · Ghép từ với nghĩa", [
    { left: "carbohydrate", right: "chất bột đường" },
    { left: "protein", right: "chất đạm" },
    { left: "fibre", right: "chất xơ" },
    { left: "dairy product", right: "sản phẩm từ sữa" },
    { left: "appetite", right: "cảm giác thèm ăn" },
    { left: "leftovers", right: "đồ ăn thừa" },
  ]),
  cloze("ex-pre-24-2", "24 · Điền từ", "Eggs are rich in ___.", "protein", ["Protein"]),
  cloze("ex-pre-24-3", "24 · Điền từ", "Vegetables provide plenty of ___.", "fibre", ["Fibre"]),
  cloze("ex-pre-24-4", "24 · Điền cụm", "Try to limit ___ intake.", "processed food", ["Processed food"]),
  cloze("ex-pre-24-5", "24 · Điền cụm", "Try to control your ___ if you want to avoid overeating.", "portion size", ["Portion size"]),
  cloze("ex-pre-24-6", "24 · Điền từ", "We kept the ___ for lunch.", "leftovers", ["Leftovers"]),
  cloze("ex-pre-24-7", "24 · Điền từ", "I usually have fruit as a ___.", "snack", ["Snack"]),
  cloze("ex-pre-24-8", "24 · Điền cụm", "She has a ___ to peanuts.", "food allergy", ["Food allergy"]),
  mcq("ex-pre-24-9", "24 · Chọn đáp án", "Cụm nào chỉ đồ ăn chế biến sẵn?", "a", [
    { key: "a", label: "processed food" },
    { key: "b", label: "wholegrain" },
    { key: "c", label: "leftovers" },
    { key: "d", label: "protein" },
  ]),
  mcq("ex-pre-24-10", "24 · Chọn đáp án", "Từ nào mang nghĩa nhạt, thiếu vị?", "c", [
    { key: "a", label: "spicy" },
    { key: "b", label: "greasy" },
    { key: "c", label: "bland" },
    { key: "d", label: "nutritious" },
  ]),
  mcq("ex-pre-24-11", "24 · Chọn đáp án", "Tính từ nào nghĩa là giàu dinh dưỡng?", "b", [
    { key: "a", label: "greasy" },
    { key: "b", label: "nutritious" },
    { key: "c", label: "bland" },
    { key: "d", label: "processed" },
  ]),
  mcq("ex-pre-24-12", "24 · Chọn đáp án", "Tính từ nào nghĩa là nhiều dầu mỡ?", "a", [
    { key: "a", label: "greasy" },
    { key: "b", label: "spicy" },
    { key: "c", label: "bland" },
    { key: "d", label: "nutritious" },
  ]),
  mcq("ex-pre-24-13", "24 · Chọn đáp án", "Tính từ nào chỉ người ăn thuần chay (tránh cả sữa, trứng)?", "d", [
    { key: "a", label: "vegetarian" },
    { key: "b", label: "nutritious" },
    { key: "c", label: "greasy" },
    { key: "d", label: "vegan" },
  ]),
  mcq("ex-pre-24-14", "24 · Chọn đáp án", "Từ nào chỉ ngũ cốc nguyên cám?", "b", [
    { key: "a", label: "dairy product" },
    { key: "b", label: "wholegrain" },
    { key: "c", label: "snack" },
    { key: "d", label: "fibre" },
  ]),
];

const UNIT_25: VocabularyExercise[] = [
  match("ex-pre-25-1", "25 · Ghép từ với nghĩa", [
    { left: "chop", right: "băm/chặt nhỏ" },
    { left: "slice", right: "thái lát" },
    { left: "boil", right: "luộc/đun sôi" },
    { left: "recipe", right: "công thức nấu ăn" },
    { left: "ingredient", right: "nguyên liệu" },
    { left: "oven", right: "lò nướng" },
  ]),
  cloze("ex-pre-25-2", "25 · Điền từ", "___ the onions finely.", "Chop", ["chop"]),
  cloze("ex-pre-25-3", "25 · Điền từ", "___ the tomatoes thinly.", "Slice", ["slice"]),
  cloze("ex-pre-25-4", "25 · Điền từ", "We ___ vegetables to keep nutrients.", "steam", ["Steam"]),
  cloze("ex-pre-25-5", "25 · Điền từ", "Let the soup ___ for 20 minutes.", "simmer", ["Simmer"]),
  cloze("ex-pre-25-6", "25 · Điền từ", "Please ___ the soup before serving.", "season", ["Season"]),
  cloze("ex-pre-25-7", "25 · Điền từ", "___ the beef overnight.", "Marinate", ["marinate"]),
  cloze("ex-pre-25-8", "25 · Điền từ", "Fresh ___ make a big difference.", "ingredients", ["Ingredients", "ingredient", "Ingredient"]),
  mcq("ex-pre-25-9", "25 · Chọn đáp án", "Động từ nào nghĩa là đun liu riu?", "b", [
    { key: "a", label: "fry" },
    { key: "b", label: "simmer" },
    { key: "c", label: "grate" },
    { key: "d", label: "slice" },
  ]),
  mcq("ex-pre-25-10", "25 · Chọn đáp án", "Từ nào mô tả món ăn chưa chín kỹ?", "b", [
    { key: "a", label: "overcooked" },
    { key: "b", label: "undercooked" },
    { key: "c", label: "roasted" },
    { key: "d", label: "seasoned" },
  ]),
  mcq("ex-pre-25-11", "25 · Chọn đáp án", "Từ nào mô tả món ăn chín quá, bị khô?", "a", [
    { key: "a", label: "overcooked" },
    { key: "b", label: "undercooked" },
    { key: "c", label: "raw" },
    { key: "d", label: "fresh" },
  ]),
  mcq("ex-pre-25-12", "25 · Chọn đáp án", "Động từ nào nghĩa là bào nhỏ?", "c", [
    { key: "a", label: "stir" },
    { key: "b", label: "boil" },
    { key: "c", label: "grate" },
    { key: "d", label: "roast" },
  ]),
  mcq("ex-pre-25-13", "25 · Chọn đáp án", "Động từ nào nghĩa là nướng lò?", "d", [
    { key: "a", label: "fry" },
    { key: "b", label: "steam" },
    { key: "c", label: "boil" },
    { key: "d", label: "roast" },
  ]),
  mcq("ex-pre-25-14", "25 · Chọn đáp án", "Cụm nào chỉ chảo rán?", "b", [
    { key: "a", label: "saucepan" },
    { key: "b", label: "frying pan" },
    { key: "c", label: "oven" },
    { key: "d", label: "recipe" },
  ]),
];

const UNIT_26: VocabularyExercise[] = [
  match("ex-pre-26-1", "26 · Ghép từ với nghĩa", [
    { left: "skyline", right: "đường chân trời với các tòa nhà cao" },
    { left: "traffic jam", right: "kẹt xe" },
    { left: "public transport", right: "giao thông công cộng" },
    { left: "nightlife", right: "hoạt động giải trí về đêm" },
    { left: "high-rise", right: "tòa nhà cao tầng" },
    { left: "cycle lane", right: "làn đường cho xe đạp" },
  ]),
  cloze("ex-pre-26-2", "26 · Điền từ", "The ___ looks amazing at sunset.", "skyline", ["Skyline"]),
  cloze("ex-pre-26-3", "26 · Điền cụm", "We got stuck in a ___.", "traffic jam", ["Traffic jam"]),
  cloze("ex-pre-26-4", "26 · Điền từ", "The city has a vibrant ___.", "nightlife", ["Nightlife"]),
  cloze("ex-pre-26-5", "26 · Điền cụm", "Cars are not allowed in this ___.", "pedestrian zone", ["Pedestrian zone"]),
  cloze("ex-pre-26-6", "26 · Điền từ", "Air ___ gets worse in winter.", "pollution", ["Pollution"]),
  cloze("ex-pre-26-7", "26 · Điền cụm", "Please stay out of the ___.", "cycle lane", ["Cycle lane"]),
  cloze("ex-pre-26-8", "26 · Điền cụm", "Most offices are in the ___.", "city centre", ["City centre"]),
  mcq("ex-pre-26-9", "26 · Chọn đáp án", "Cụm nào chỉ tình trạng kẹt xe?", "b", [
    { key: "a", label: "rush hour" },
    { key: "b", label: "traffic jam" },
    { key: "c", label: "nightlife" },
    { key: "d", label: "pollution" },
  ]),
  mcq("ex-pre-26-10", "26 · Chọn đáp án", "Tính từ nào nghĩa là sôi động, đầy sức sống?", "b", [
    { key: "a", label: "crowded" },
    { key: "b", label: "vibrant" },
    { key: "c", label: "isolated" },
    { key: "d", label: "remote" },
  ]),
  mcq("ex-pre-26-11", "26 · Chọn đáp án", "Tính từ nào nghĩa là đông đúc?", "a", [
    { key: "a", label: "crowded" },
    { key: "b", label: "vibrant" },
    { key: "c", label: "expensive" },
    { key: "d", label: "convenient" },
  ]),
  mcq("ex-pre-26-12", "26 · Chọn đáp án", "Cụm nào chỉ giao thông công cộng?", "c", [
    { key: "a", label: "cycle lane" },
    { key: "b", label: "public square" },
    { key: "c", label: "public transport" },
    { key: "d", label: "high-rise" },
  ]),
  mcq("ex-pre-26-13", "26 · Chọn đáp án", "Từ nào chỉ tòa nhà cao tầng?", "d", [
    { key: "a", label: "apartment block" },
    { key: "b", label: "pedestrian zone" },
    { key: "c", label: "skyline" },
    { key: "d", label: "high-rise" },
  ]),
  mcq("ex-pre-26-14", "26 · Chọn đáp án", "Cụm nào chỉ giờ cao điểm?", "a", [
    { key: "a", label: "rush hour" },
    { key: "b", label: "nightlife" },
    { key: "c", label: "city centre" },
    { key: "d", label: "cycle lane" },
  ]),
];

const UNIT_27: VocabularyExercise[] = [
  match("ex-pre-27-1", "27 · Ghép từ với nghĩa", [
    { left: "farmhouse", right: "nhà ở tại nông trại" },
    { left: "barn", right: "nhà kho/chuồng lớn trong nông trại" },
    { left: "orchard", right: "vườn cây ăn quả" },
    { left: "pasture", right: "đồng cỏ chăn thả" },
    { left: "livestock", right: "gia súc nuôi" },
    { left: "tractor", right: "máy kéo nông nghiệp" },
  ]),
  cloze("ex-pre-27-2", "27 · Điền từ", "The tools are kept in the ___.", "barn", ["Barn"]),
  cloze("ex-pre-27-3", "27 · Điền từ", "His family owns a mango ___.", "orchard", ["Orchard"]),
  cloze("ex-pre-27-4", "27 · Điền từ", "Cows grazed in the ___.", "pasture", ["Pasture"]),
  cloze("ex-pre-27-5", "27 · Điền cụm", "Local farmers are busiest during ___.", "harvest season", ["Harvest season"]),
  cloze("ex-pre-27-6", "27 · Điền cụm", "We buy ___ from local farms.", "fresh produce", ["Fresh produce"]),
  cloze("ex-pre-27-7", "27 · Điền từ", "I wake up early to watch the ___.", "sunrise", ["Sunrise"]),
  cloze("ex-pre-27-8", "27 · Điền từ", "He moved back to the ___.", "countryside", ["Countryside"]),
  mcq("ex-pre-27-9", "27 · Chọn đáp án", "Từ nào chỉ vườn cây ăn quả?", "b", [
    { key: "a", label: "pasture" },
    { key: "b", label: "orchard" },
    { key: "c", label: "barn" },
    { key: "d", label: "farmhouse" },
  ]),
  mcq("ex-pre-27-10", "27 · Chọn đáp án", "Tính từ nào nghĩa là xa xôi, hẻo lánh?", "c", [
    { key: "a", label: "close-knit" },
    { key: "b", label: "fresh" },
    { key: "c", label: "remote" },
    { key: "d", label: "crowded" },
  ]),
  mcq("ex-pre-27-11", "27 · Chọn đáp án", "Tính từ nào nghĩa là yên bình?", "a", [
    { key: "a", label: "peaceful" },
    { key: "b", label: "hectic" },
    { key: "c", label: "isolated" },
    { key: "d", label: "vibrant" },
  ]),
  mcq("ex-pre-27-12", "27 · Chọn đáp án", "Tính từ nào nghĩa là gắn kết chặt chẽ?", "b", [
    { key: "a", label: "remote" },
    { key: "b", label: "close-knit" },
    { key: "c", label: "isolated" },
    { key: "d", label: "peaceful" },
  ]),
  mcq("ex-pre-27-13", "27 · Chọn đáp án", "Cụm nào chỉ hội chợ làng?", "d", [
    { key: "a", label: "fresh produce" },
    { key: "b", label: "harvest season" },
    { key: "c", label: "well water" },
    { key: "d", label: "village fair" },
  ]),
  mcq("ex-pre-27-14", "27 · Chọn đáp án", "Cụm nào chỉ nông sản tươi?", "a", [
    { key: "a", label: "fresh produce" },
    { key: "b", label: "rural chore" },
    { key: "c", label: "well water" },
    { key: "d", label: "dirt track" },
  ]),
];

const UNIT_28: VocabularyExercise[] = [
  match("ex-pre-28-1", "28 · Ghép từ với nghĩa", [
    { left: "timetable", right: "bảng giờ xe/tàu" },
    { left: "platform", right: "sân ga" },
    { left: "carriage", right: "toa tàu" },
    { left: "fare", right: "giá vé" },
    { left: "route", right: "tuyến đường" },
    { left: "connection", right: "chuyến nối" },
  ]),
  cloze("ex-pre-28-2", "28 · Điền từ", "Check the ___ before leaving home.", "timetable", ["Timetable"]),
  cloze("ex-pre-28-3", "28 · Điền từ", "Our train leaves from ___ 2 in ten minutes.", "platform", ["Platform"]),
  cloze("ex-pre-28-4", "28 · Điền từ", "There was a 20-minute ___ due to rain.", "delay", ["Delay"]),
  cloze("ex-pre-28-5", "28 · Điền cụm", "I bought a ___ to Hue.", "one-way ticket", ["One-way ticket"]),
  cloze("ex-pre-28-6", "28 · Điền cụm", "A ___ is often cheaper.", "return ticket", ["Return ticket"]),
  cloze("ex-pre-28-7", "28 · Điền từ", "Passengers should ___ quickly.", "board", ["Board"]),
  cloze("ex-pre-28-8", "28 · Điền từ", "I missed my ___ because of delay.", "connection", ["Connection"]),
  mcq("ex-pre-28-9", "28 · Chọn đáp án", "Cụm nào chỉ vé khứ hồi?", "b", [
    { key: "a", label: "season ticket" },
    { key: "b", label: "return ticket" },
    { key: "c", label: "one-way ticket" },
    { key: "d", label: "fare" },
  ]),
  mcq("ex-pre-28-10", "28 · Chọn đáp án", "Động từ nào nghĩa là xuống tàu/xe?", "c", [
    { key: "a", label: "board" },
    { key: "b", label: "transfer" },
    { key: "c", label: "alight" },
    { key: "d", label: "reserve" },
  ]),
  mcq("ex-pre-28-11", "28 · Chọn đáp án", "Cụm nào chỉ vé tháng đi lại thường xuyên?", "a", [
    { key: "a", label: "season ticket" },
    { key: "b", label: "return ticket" },
    { key: "c", label: "fare" },
    { key: "d", label: "route" },
  ]),
  mcq("ex-pre-28-12", "28 · Chọn đáp án", "Từ nào chỉ toa tàu?", "b", [
    { key: "a", label: "platform" },
    { key: "b", label: "carriage" },
    { key: "c", label: "route" },
    { key: "d", label: "fare" },
  ]),
  mcq("ex-pre-28-13", "28 · Chọn đáp án", "Cụm nào chỉ khung giờ cao điểm?", "d", [
    { key: "a", label: "seat reservation" },
    { key: "b", label: "luggage rack" },
    { key: "c", label: "direct train" },
    { key: "d", label: "peak hours" },
  ]),
  mcq("ex-pre-28-14", "28 · Chọn đáp án", "Cụm nào chỉ đặt trước chỗ ngồi?", "a", [
    { key: "a", label: "seat reservation" },
    { key: "b", label: "luggage rack" },
    { key: "c", label: "season ticket" },
    { key: "d", label: "return ticket" },
  ]),
];

const UNIT_29: VocabularyExercise[] = [
  match("ex-pre-29-1", "29 · Ghép từ với nghĩa", [
    { left: "junction", right: "nút giao/điểm giao nhau của đường" },
    { left: "roundabout", right: "vòng xuyến" },
    { left: "lane", right: "làn đường" },
    { left: "traffic light", right: "đèn giao thông" },
    { left: "engine", right: "động cơ" },
    { left: "driving licence", right: "giấy phép lái xe" },
  ]),
  cloze("ex-pre-29-2", "29 · Điền từ", "Go straight through the ___.", "roundabout", ["Roundabout"]),
  cloze("ex-pre-29-3", "29 · Điền cụm", "You must not exceed the ___ on this road.", "speed limit", ["Speed limit"]),
  cloze("ex-pre-29-4", "29 · Điền cụm", "Stop at the ___.", "pedestrian crossing", ["Pedestrian crossing"]),
  cloze("ex-pre-29-5", "29 · Điền cụm", "We had to stop because of a ___.", "flat tyre", ["Flat tyre"]),
  cloze("ex-pre-29-6", "29 · Điền từ", "Remember to ___ before turning.", "indicate", ["Indicate"]),
  cloze("ex-pre-29-7", "29 · Điền từ", "Follow the ___ signs carefully.", "detour", ["Detour"]),
  cloze("ex-pre-29-8", "29 · Điền cụm", "Everyone must wear a ___.", "seat belt", ["Seat belt"]),
  mcq("ex-pre-29-9", "29 · Chọn đáp án", "Từ nào chỉ vòng xuyến?", "c", [
    { key: "a", label: "lane" },
    { key: "b", label: "junction" },
    { key: "c", label: "roundabout" },
    { key: "d", label: "detour" },
  ]),
  mcq("ex-pre-29-10", "29 · Chọn đáp án", "Cụm nào nghĩa là đỗ xe sai quy định?", "a", [
    { key: "a", label: "park illegally" },
    { key: "b", label: "overtake carefully" },
    { key: "c", label: "take a lane" },
    { key: "d", label: "stop by station" },
  ]),
  mcq("ex-pre-29-11", "29 · Chọn đáp án", "Động từ nào nghĩa là vượt xe?", "b", [
    { key: "a", label: "brake" },
    { key: "b", label: "overtake" },
    { key: "c", label: "indicate" },
    { key: "d", label: "board" },
  ]),
  mcq("ex-pre-29-12", "29 · Chọn đáp án", "Từ nào chỉ công trình sửa đường?", "c", [
    { key: "a", label: "detour" },
    { key: "b", label: "speed limit" },
    { key: "c", label: "roadworks" },
    { key: "d", label: "junction" },
  ]),
  mcq("ex-pre-29-13", "29 · Chọn đáp án", "Cụm nào chỉ tiền phạt giao thông?", "d", [
    { key: "a", label: "driving licence" },
    { key: "b", label: "petrol station" },
    { key: "c", label: "seat belt" },
    { key: "d", label: "traffic fine" },
  ]),
  mcq("ex-pre-29-14", "29 · Chọn đáp án", "Cụm nào chỉ trạm xăng?", "a", [
    { key: "a", label: "petrol station" },
    { key: "b", label: "traffic light" },
    { key: "c", label: "roundabout" },
    { key: "d", label: "engine" },
  ]),
];

const UNIT_30: VocabularyExercise[] = [
  match("ex-pre-30-1", "30 · Ghép từ với nghĩa", [
    { left: "no entry", right: "cấm vào" },
    { left: "staff only", right: "chỉ dành cho nhân viên" },
    { left: "emergency exit", right: "lối thoát hiểm" },
    { left: "fire alarm", right: "chuông/cảnh báo cháy" },
    { left: "high voltage", right: "điện áp cao, nguy hiểm điện giật" },
    { left: "out of order", right: "hỏng, không hoạt động" },
  ]),
  cloze("ex-pre-30-2", "30 · Điền cụm", "Please use the ___ in case of fire.", "emergency exit", ["Emergency exit"]),
  cloze("ex-pre-30-3", "30 · Điền cụm", "Be careful: ___ after cleaning.", "slippery floor", ["Slippery floor"]),
  cloze("ex-pre-30-4", "30 · Điền cụm", "Do not touch the wall, ___.", "wet paint", ["Wet paint"]),
  cloze("ex-pre-30-5", "30 · Điền cụm", "The ___ went off at midnight.", "fire alarm", ["Fire alarm"]),
  cloze("ex-pre-30-6", "30 · Điền cụm", "The elevator is ___.", "out of order", ["Out of order"]),
  cloze("ex-pre-30-7", "30 · Điền cụm", "The bridge is ___.", "under construction", ["Under construction"]),
  cloze("ex-pre-30-8", "30 · Điền từ", "___ to open the door.", "Push", ["push"]),
  mcq("ex-pre-30-9", "30 · Chọn đáp án", "Biển nào nghĩa là cấm vào?", "b", [
    { key: "a", label: "queue here" },
    { key: "b", label: "no entry" },
    { key: "c", label: "push" },
    { key: "d", label: "pull" },
  ]),
  mcq("ex-pre-30-10", "30 · Chọn đáp án", "Cụm nào cảnh báo đồ dễ vỡ khi vận chuyển?", "d", [
    { key: "a", label: "high voltage" },
    { key: "b", label: "wet paint" },
    { key: "c", label: "mind the gap" },
    { key: "d", label: "handle with care" },
  ]),
  mcq("ex-pre-30-11", "30 · Chọn đáp án", "Tính từ nào nghĩa là dễ vỡ?", "a", [
    { key: "a", label: "fragile" },
    { key: "b", label: "slippery" },
    { key: "c", label: "spotless" },
    { key: "d", label: "chronic" },
  ]),
  mcq("ex-pre-30-12", "30 · Chọn đáp án", "Biển nào nghĩa là cấm hút thuốc?", "c", [
    { key: "a", label: "keep out" },
    { key: "b", label: "staff only" },
    { key: "c", label: "no smoking" },
    { key: "d", label: "no entry" },
  ]),
  mcq("ex-pre-30-13", "30 · Chọn đáp án", "Động từ nào nghĩa là kéo (cửa)?", "b", [
    { key: "a", label: "push" },
    { key: "b", label: "pull" },
    { key: "c", label: "board" },
    { key: "d", label: "queue" },
  ]),
  mcq("ex-pre-30-14", "30 · Chọn đáp án", "Cụm nào cảnh báo coi chừng chó?", "d", [
    { key: "a", label: "mind the gap" },
    { key: "b", label: "keep out" },
    { key: "c", label: "staff only" },
    { key: "d", label: "beware of dog" },
  ]),
];

export const CURATED_PRE_UNITS_16_30: Readonly<Partial<Record<number, readonly VocabularyExercise[]>>> = {
  16: UNIT_16,
  17: UNIT_17,
  18: UNIT_18,
  19: UNIT_19,
  20: UNIT_20,
  21: UNIT_21,
  22: UNIT_22,
  23: UNIT_23,
  24: UNIT_24,
  25: UNIT_25,
  26: UNIT_26,
  27: UNIT_27,
  28: UNIT_28,
  29: UNIT_29,
  30: UNIT_30,
};

for (const [unitNumber, exercises] of Object.entries(CURATED_PRE_UNITS_16_30)) {
  if (exercises) {
    assertExerciseCount(Number(unitNumber), exercises);
  }
}
