import { assertExerciseCount, cloze, match, mcq } from "./eviu-elementary-curated-helpers";
import type { VocabularyExercise } from "@/lib/vocabulary/vocabulary-unit-types";

const UNIT_76: VocabularyExercise[] = [
  match("ex-pre-76-1", "76 · Ghép từ với nghĩa", [
    { left: "by the way", right: "tiện thể nói thêm, chuyển nhẹ sang ý liên quan" },
    { left: "to be honest", right: "thành thật mà nói" },
    { left: "anyway", right: "dù sao đi nữa, quay lại mạch chính" },
    { left: "actually", right: "thực ra, trên thực tế" },
    { left: "after all", right: "suy cho cùng" },
    { left: "speaking of", right: "nhân nói về" },
  ]),
  cloze("ex-pre-76-2", "76 · Điền cụm", "By the way, have you sent the email ___?", "yet", ["Yet"]),
  cloze("ex-pre-76-3", "76 · Điền cụm", "___ , we should leave earlier tomorrow.", "As I was saying", ["as I was saying"]),
  cloze("ex-pre-76-4", "76 · Điền cụm", "To be honest, I did not ___ that movie.", "enjoy", ["Enjoy"]),
  cloze("ex-pre-76-5", "76 · Điền cụm", "In ___, sales increased last month.", "fact", ["Fact"]),
  cloze("ex-pre-76-6", "76 · Điền cụm", "Anyway, let's get back to our main ___.", "topic", ["Topic"]),
  cloze("ex-pre-76-7", "76 · Điền cụm", "Come to think of it, I have met her ___.", "before", ["Before"]),
  cloze("ex-pre-76-8", "76 · Điền cụm", "Long story short, we missed the train and took a ___.", "bus", ["Bus"]),
  mcq("ex-pre-76-9", "76 · Chọn đáp án", "Cụm nào có nghĩa 'theo những gì tôi biết'?", "c", [
    { key: "a", label: "if you ask me" },
    { key: "b", label: "let's see" },
    { key: "c", label: "as far as I know" },
    { key: "d", label: "mind you" },
  ]),
  mcq("ex-pre-76-10", "76 · Chọn đáp án", "Cụm nào thường dùng để đưa ra ý kiến cá nhân?", "a", [
    { key: "a", label: "if you ask me" },
    { key: "b", label: "in fact" },
    { key: "c", label: "at least" },
    { key: "d", label: "long story short" },
  ]),
  mcq("ex-pre-76-11", "76 · Chọn đáp án", "\"That reminds me\" dùng khi nào?", "b", [
    { key: "a", label: "chuyển sang chủ đề hoàn toàn mới" },
    { key: "b", label: "một điều vừa nói gợi nhớ điều khác liên quan" },
    { key: "c", label: "kết thúc cuộc trò chuyện" },
    { key: "d", label: "phủ nhận thông tin vừa nêu" },
  ]),
  mcq("ex-pre-76-12", "76 · Chọn đáp án", "\"Mind you\" dùng để ___", "d", [
    { key: "a", label: "bắt đầu câu chuyện mới" },
    { key: "b", label: "xác nhận thông tin chắc chắn" },
    { key: "c", label: "hỏi ý kiến người nghe" },
    { key: "d", label: "bổ sung lưu ý điều chỉnh ý vừa nêu" },
  ]),
  mcq("ex-pre-76-13", "76 · Chọn đáp án", "Cụm nào có nghĩa 'bạn hiểu ý tôi chứ'?", "b", [
    { key: "a", label: "I suppose" },
    { key: "b", label: "you know what I mean" },
    { key: "c", label: "let's see" },
    { key: "d", label: "after all" },
  ]),
  mcq("ex-pre-76-14", "76 · Chọn đáp án", "\"At least\" thường dùng để ___", "a", [
    { key: "a", label: "nêu điểm tích cực trong tình huống không tốt" },
    { key: "b", label: "chuyển sang chủ đề mới" },
    { key: "c", label: "sửa thông tin sai" },
    { key: "d", label: "kết thúc câu chuyện" },
  ]),
];

const UNIT_77: VocabularyExercise[] = [
  match("ex-pre-77-1", "77 · Ghép từ với nghĩa", [
    { left: "depend on", right: "phụ thuộc vào" },
    { left: "apply for", right: "nộp đơn xin" },
    { left: "focus on", right: "tập trung vào" },
    { left: "be interested in", right: "quan tâm, hứng thú với" },
    { left: "be proud of", right: "tự hào về" },
    { left: "be used to", right: "quen với" },
  ]),
  cloze("ex-pre-77-2", "77 · Điền cụm", "The result depends on how much you ___.", "practice", ["Practice"]),
  cloze("ex-pre-77-3", "77 · Điền cụm", "This bag belongs ___ my sister.", "to", ["To"]),
  cloze("ex-pre-77-4", "77 · Điền cụm", "He suffers ___ back pain.", "from", ["From"]),
  cloze("ex-pre-77-5", "77 · Điền cụm", "I plan to apply ___ a scholarship.", "for", ["For"]),
  cloze("ex-pre-77-6", "77 · Điền cụm", "Please focus ___ the key points.", "on", ["On"]),
  cloze("ex-pre-77-7", "77 · Điền cụm", "We need to deal ___ this issue now.", "with", ["With"]),
  cloze("ex-pre-77-8", "77 · Điền cụm", "I am interested ___ environmental science.", "in", ["In"]),
  mcq("ex-pre-77-9", "77 · Chọn đáp án", "Cụm đúng là gì?", "c", [
    { key: "a", label: "depend in" },
    { key: "b", label: "depend at" },
    { key: "c", label: "depend on" },
    { key: "d", label: "depend for" },
  ]),
  mcq("ex-pre-77-10", "77 · Chọn đáp án", "\"Be responsible for\" nghĩa là ___", "b", [
    { key: "a", label: "sợ" },
    { key: "b", label: "chịu trách nhiệm về" },
    { key: "c", label: "giỏi về" },
    { key: "d", label: "tương tự với" },
  ]),
  mcq("ex-pre-77-11", "77 · Chọn đáp án", "Cụm nào có nghĩa 'rất thích, say mê'?", "d", [
    { key: "a", label: "be afraid of" },
    { key: "b", label: "be similar to" },
    { key: "c", label: "be aware of" },
    { key: "d", label: "be keen on" },
  ]),
  mcq("ex-pre-77-12", "77 · Chọn đáp án", "\"Be good at\" đi với giới từ nào?", "a", [
    { key: "a", label: "at" },
    { key: "b", label: "in" },
    { key: "c", label: "on" },
    { key: "d", label: "of" },
  ]),
  mcq("ex-pre-77-13", "77 · Chọn đáp án", "\"Recover from\" nghĩa là ___", "c", [
    { key: "a", label: "nộp đơn xin" },
    { key: "b", label: "xin lỗi vì" },
    { key: "c", label: "hồi phục sau" },
    { key: "d", label: "tập trung vào" },
  ]),
  mcq("ex-pre-77-14", "77 · Chọn đáp án", "\"Be satisfied with\" nghĩa là ___", "b", [
    { key: "a", label: "nhận thức rõ về" },
    { key: "b", label: "hài lòng với" },
    { key: "c", label: "quen với" },
    { key: "d", label: "tự hào về" },
  ]),
];

const UNIT_78: VocabularyExercise[] = [
  match("ex-pre-78-1", "78 · Ghép từ với nghĩa", [
    { left: "at the moment", right: "ngay lúc này, hiện tại" },
    { left: "in advance", right: "trước một khoảng thời gian" },
    { left: "on purpose", right: "cố ý, có chủ đích" },
    { left: "by accident", right: "tình cờ, vô tình" },
    { left: "on the whole", right: "nhìn chung" },
    { left: "out of date", right: "lỗi thời, không còn cập nhật" },
  ]),
  cloze("ex-pre-78-2", "78 · Điền cụm", "I cannot talk at the ___.", "moment", ["Moment"]),
  cloze("ex-pre-78-3", "78 · Điền cụm", "Please let me know in ___.", "advance", ["Advance"]),
  cloze("ex-pre-78-4", "78 · Điền cụm", "Lan is in charge ___ customer support.", "of", ["Of"]),
  cloze("ex-pre-78-5", "78 · Điền cụm", "We have a lot in ___.", "common", ["Common"]),
  cloze("ex-pre-78-6", "78 · Điền cụm", "I did not do it on ___.", "purpose", ["Purpose"]),
  cloze("ex-pre-78-7", "78 · Điền cụm", "I found this cafe by ___.", "accident", ["Accident"]),
  cloze("ex-pre-78-8", "78 · Điền cụm", "On the whole, the project went ___.", "well", ["Well"]),
  mcq("ex-pre-78-9", "78 · Chọn đáp án", "Cụm nào có nghĩa 'vô tình'?", "b", [
    { key: "a", label: "on purpose" },
    { key: "b", label: "by accident" },
    { key: "c", label: "in charge of" },
    { key: "d", label: "at risk" },
  ]),
  mcq("ex-pre-78-10", "78 · Chọn đáp án", "\"For the time being\" nghĩa là ___", "c", [
    { key: "a", label: "trước một khoảng thời gian" },
    { key: "b", label: "tính trung bình" },
    { key: "c", label: "tạm thời trong lúc này" },
    { key: "d", label: "đúng giờ" },
  ]),
  mcq("ex-pre-78-11", "78 · Chọn đáp án", "Cụm nào có nghĩa 'có nguy cơ'?", "d", [
    { key: "a", label: "in common" },
    { key: "b", label: "on average" },
    { key: "c", label: "in detail" },
    { key: "d", label: "at risk" },
  ]),
  mcq("ex-pre-78-12", "78 · Chọn đáp án", "\"In public\" nghĩa là ___", "a", [
    { key: "a", label: "ở nơi công cộng" },
    { key: "b", label: "trong áp lực" },
    { key: "c", label: "ngẫu nhiên" },
    { key: "d", label: "lỗi thời" },
  ]),
  mcq("ex-pre-78-13", "78 · Chọn đáp án", "Cụm nào có nghĩa 'chẳng hạn như'?", "b", [
    { key: "a", label: "by chance" },
    { key: "b", label: "for instance" },
    { key: "c", label: "on time" },
    { key: "d", label: "in touch with" },
  ]),
  mcq("ex-pre-78-14", "78 · Chọn đáp án", "\"Under pressure\" nghĩa là ___", "c", [
    { key: "a", label: "phụ trách" },
    { key: "b", label: "giữ liên lạc với" },
    { key: "c", label: "trong áp lực" },
    { key: "d", label: "một cách chi tiết" },
  ]),
];

const UNIT_79: VocabularyExercise[] = [
  match("ex-pre-79-1", "79 · Ghép từ với nghĩa", [
    { left: "turn on", right: "bật thiết bị" },
    { left: "look after", right: "chăm sóc" },
    { left: "find out", right: "tìm ra thông tin" },
    { left: "give up", right: "từ bỏ" },
    { left: "run out of", right: "hết, cạn" },
    { left: "break down", right: "hỏng hóc / suy sụp" },
  ]),
  cloze("ex-pre-79-2", "79 · Điền cụm", "Please turn ___ the air conditioner.", "on", ["On"]),
  cloze("ex-pre-79-3", "79 · Điền cụm", "Do not forget to turn ___ the lights.", "off", ["Off"]),
  cloze("ex-pre-79-4", "79 · Điền cụm", "She looks ___ her younger brother after school.", "after", ["After"]),
  cloze("ex-pre-79-5", "79 · Điền cụm", "We need to find ___ why sales dropped.", "out", ["Out"]),
  cloze("ex-pre-79-6", "79 · Điền cụm", "Do not give ___ too soon.", "up", ["Up"]),
  cloze("ex-pre-79-7", "79 · Điền cụm", "We ran out ___ printer paper.", "of", ["Of"]),
  cloze("ex-pre-79-8", "79 · Điền cụm", "My car broke ___ on the highway.", "down", ["Down"]),
  mcq("ex-pre-79-9", "79 · Chọn đáp án", "Cụm nào có nghĩa là 'chăm sóc'?", "a", [
    { key: "a", label: "look after" },
    { key: "b", label: "look for" },
    { key: "c", label: "pick up" },
    { key: "d", label: "put down" },
  ]),
  mcq("ex-pre-79-10", "79 · Chọn đáp án", "\"Come across\" nghĩa là ___", "b", [
    { key: "a", label: "đề cập một chủ đề" },
    { key: "b", label: "tình cờ gặp / thấy" },
    { key: "c", label: "tiếp tục" },
    { key: "d", label: "vượt qua" },
  ]),
  mcq("ex-pre-79-11", "79 · Chọn đáp án", "\"Take off\" trong \"The plane took off on time\" nghĩa là ___", "c", [
    { key: "a", label: "cởi ra" },
    { key: "b", label: "mặc vào" },
    { key: "c", label: "cất cánh" },
    { key: "d", label: "đặt xuống" },
  ]),
  mcq("ex-pre-79-12", "79 · Chọn đáp án", "\"Work out\" trong \"We will work out a better plan\" nghĩa là ___", "a", [
    { key: "a", label: "giải quyết được" },
    { key: "b", label: "tập luyện" },
    { key: "c", label: "từ bỏ" },
    { key: "d", label: "thiết lập" },
  ]),
  mcq("ex-pre-79-13", "79 · Chọn đáp án", "\"Bring up\" nghĩa là ___", "d", [
    { key: "a", label: "nhặt lên" },
    { key: "b", label: "tìm kiếm" },
    { key: "c", label: "chăm sóc" },
    { key: "d", label: "đề cập một chủ đề" },
  ]),
  mcq("ex-pre-79-14", "79 · Chọn đáp án", "\"Get over\" nghĩa là ___", "b", [
    { key: "a", label: "hết, cạn" },
    { key: "b", label: "vượt qua" },
    { key: "c", label: "hỏng hóc" },
    { key: "d", label: "tìm ra thông tin" },
  ]),
];

const UNIT_80: VocabularyExercise[] = [
  match("ex-pre-80-1", "80 · Ghép từ với nghĩa", [
    { left: "put off", right: "hoãn lại" },
    { left: "call off", right: "hủy bỏ" },
    { left: "hand in", right: "nộp (bài, tài liệu)" },
    { left: "cut down on", right: "cắt giảm" },
    { left: "log in", right: "đăng nhập" },
    { left: "sign up", right: "đăng ký tham gia" },
  ]),
  cloze("ex-pre-80-2", "80 · Điền cụm", "Could you turn ___ the music, please?", "down", ["Down"]),
  cloze("ex-pre-80-3", "80 · Điền cụm", "Please fill ___ your date of birth.", "in", ["In"]),
  cloze("ex-pre-80-4", "80 · Điền cụm", "Students must hand ___ the report by Friday.", "in", ["In"]),
  cloze("ex-pre-80-5", "80 · Điền cụm", "They put ___ the meeting until next week.", "off", ["Off"]),
  cloze("ex-pre-80-6", "80 · Điền cụm", "I am trying to cut down ___ sugar.", "on", ["On"]),
  cloze("ex-pre-80-7", "80 · Điền cụm", "Use your email to log ___.", "in", ["In"]),
  cloze("ex-pre-80-8", "80 · Điền cụm", "I signed ___ for a weekend workshop.", "up", ["Up"]),
  mcq("ex-pre-80-9", "80 · Chọn đáp án", "Cụm nào nghĩa là 'hoãn lại'?", "a", [
    { key: "a", label: "put off" },
    { key: "b", label: "hand in" },
    { key: "c", label: "check in" },
    { key: "d", label: "back up" },
  ]),
  mcq("ex-pre-80-10", "80 · Chọn đáp án", "\"Call off\" nghĩa là ___", "c", [
    { key: "a", label: "sao lưu" },
    { key: "b", label: "hoãn lại" },
    { key: "c", label: "hủy bỏ" },
    { key: "d", label: "chỉ ra" },
  ]),
  mcq("ex-pre-80-11", "80 · Chọn đáp án", "\"Fill out\" khác \"fill in\" ở chỗ ___", "b", [
    { key: "a", label: "fill out dùng cho số" },
    { key: "b", label: "fill out thường dùng cho biểu mẫu đầy đủ" },
    { key: "c", label: "fill in chỉ dùng cho tên" },
    { key: "d", label: "hai cụm không khác nhau" },
  ]),
  mcq("ex-pre-80-12", "80 · Chọn đáp án", "\"Take back\" nghĩa là ___", "a", [
    { key: "a", label: "rút lại lời nói / mang trả lại" },
    { key: "b", label: "vứt bỏ" },
    { key: "c", label: "sắp xếp / giải quyết" },
    { key: "d", label: "khởi động" },
  ]),
  mcq("ex-pre-80-13", "80 · Chọn đáp án", "\"Calm down\" nghĩa là ___", "d", [
    { key: "a", label: "đăng nhập" },
    { key: "b", label: "sao lưu" },
    { key: "c", label: "khởi động" },
    { key: "d", label: "bình tĩnh lại" },
  ]),
  mcq("ex-pre-80-14", "80 · Chọn đáp án", "\"Point out\" nghĩa là ___", "b", [
    { key: "a", label: "cắt giảm" },
    { key: "b", label: "chỉ ra" },
    { key: "c", label: "vứt bỏ" },
    { key: "d", label: "trả phòng" },
  ]),
];

const UNIT_81: VocabularyExercise[] = [
  match("ex-pre-81-1", "81 · Ghép từ với nghĩa", [
    { left: "make a decision", right: "đưa ra quyết định" },
    { left: "make progress", right: "tiến bộ" },
    { left: "do homework", right: "làm bài tập về nhà" },
    { left: "do someone a favor", right: "giúp ai một việc" },
    { left: "take a break", right: "nghỉ giải lao" },
    { left: "take responsibility", right: "chịu trách nhiệm" },
  ]),
  cloze("ex-pre-81-2", "81 · Điền cụm", "We need to make a ___ today.", "decision", ["Decision"]),
  cloze("ex-pre-81-3", "81 · Điền cụm", "You are making good ___ this month.", "progress", ["Progress"]),
  cloze("ex-pre-81-4", "81 · Điền cụm", "The kids do ___ after dinner.", "homework", ["Homework"]),
  cloze("ex-pre-81-5", "81 · Điền cụm", "Could you do me a ___ and print this?", "favor", ["Favor"]),
  cloze("ex-pre-81-6", "81 · Điền cụm", "Let's take a short ___.", "break", ["Break"]),
  cloze("ex-pre-81-7", "81 · Điền cụm", "He took ___ for the error.", "responsibility", ["Responsibility"]),
  cloze("ex-pre-81-8", "81 · Điền cụm", "Your explanation makes ___ to me.", "sense", ["Sense"]),
  mcq("ex-pre-81-9", "81 · Chọn đáp án", "Cụm đúng là gì?", "c", [
    { key: "a", label: "do a decision" },
    { key: "b", label: "take a decision" },
    { key: "c", label: "make a decision" },
    { key: "d", label: "make a homework" },
  ]),
  mcq("ex-pre-81-10", "81 · Chọn đáp án", "\"Take part\" nghĩa là ___", "b", [
    { key: "a", label: "nghỉ giải lao" },
    { key: "b", label: "tham gia" },
    { key: "c", label: "ghi chú" },
    { key: "d", label: "chịu trách nhiệm" },
  ]),
  mcq("ex-pre-81-11", "81 · Chọn đáp án", "\"Take place\" nghĩa là ___", "a", [
    { key: "a", label: "diễn ra" },
    { key: "b", label: "tham gia" },
    { key: "c", label: "nghỉ giải lao" },
    { key: "d", label: "làm tốt" },
  ]),
  mcq("ex-pre-81-12", "81 · Chọn đáp án", "\"Do well\" nghĩa là ___", "c", [
    { key: "a", label: "làm không tốt" },
    { key: "b", label: "rửa bát" },
    { key: "c", label: "làm tốt" },
    { key: "d", label: "làm ăn, kinh doanh" },
  ]),
  mcq("ex-pre-81-13", "81 · Chọn đáp án", "\"Make an effort\" nghĩa là ___", "d", [
    { key: "a", label: "mắc lỗi" },
    { key: "b", label: "lập kế hoạch" },
    { key: "c", label: "tiến bộ" },
    { key: "d", label: "nỗ lực" },
  ]),
  mcq("ex-pre-81-14", "81 · Chọn đáp án", "\"Take your time\" nghĩa là ___", "a", [
    { key: "a", label: "cứ từ từ, không cần vội" },
    { key: "b", label: "nghỉ giải lao" },
    { key: "c", label: "ghi chú" },
    { key: "d", label: "chịu trách nhiệm" },
  ]),
];

const UNIT_82: VocabularyExercise[] = [
  match("ex-pre-82-1", "82 · Ghép từ với nghĩa", [
    { left: "give advice", right: "đưa lời khuyên" },
    { left: "give up", right: "từ bỏ" },
    { left: "keep a promise", right: "giữ lời hứa" },
    { left: "keep in touch", right: "giữ liên lạc" },
    { left: "miss a chance", right: "bỏ lỡ cơ hội" },
    { left: "miss out on", right: "bỏ lỡ cơ hội trải nghiệm/nhận được" },
  ]),
  cloze("ex-pre-82-2", "82 · Điền cụm", "My mentor gave me useful ___.", "advice", ["Advice"]),
  cloze("ex-pre-82-3", "82 · Điền cụm", "He did not give ___ even after failing twice.", "up", ["Up"]),
  cloze("ex-pre-82-4", "82 · Điền cụm", "She always keeps her ___.", "promises", ["Promises"]),
  cloze("ex-pre-82-5", "82 · Điền cụm", "We still keep in ___ after graduation.", "touch", ["Touch"]),
  cloze("ex-pre-82-6", "82 · Điền cụm", "Do not miss the ___ to practice speaking.", "chance", ["Chance"]),
  cloze("ex-pre-82-7", "82 · Điền cụm", "I do not want to miss out ___ this offer.", "on", ["On"]),
  cloze("ex-pre-82-8", "82 · Điền cụm", "Keep ___ and follow the instructions.", "calm", ["Calm"]),
  mcq("ex-pre-82-9", "82 · Chọn đáp án", "Cụm nào nghĩa là 'giữ liên lạc'?", "a", [
    { key: "a", label: "keep in touch" },
    { key: "b", label: "give back" },
    { key: "c", label: "miss the point" },
    { key: "d", label: "give up" },
  ]),
  mcq("ex-pre-82-10", "82 · Chọn đáp án", "\"Miss the point\" nghĩa là ___", "c", [
    { key: "a", label: "bỏ lỡ cơ hội" },
    { key: "b", label: "lỡ hạn nộp" },
    { key: "c", label: "không hiểu ý chính" },
    { key: "d", label: "nhớ ai" },
  ]),
  mcq("ex-pre-82-11", "82 · Chọn đáp án", "\"Give someone a hand\" nghĩa là ___", "b", [
    { key: "a", label: "đưa lời khuyên" },
    { key: "b", label: "giúp ai một tay" },
    { key: "c", label: "phát biểu" },
    { key: "d", label: "trả lại" },
  ]),
  mcq("ex-pre-82-12", "82 · Chọn đáp án", "\"Keep an eye on\" nghĩa là ___", "d", [
    { key: "a", label: "giữ lời hứa" },
    { key: "b", label: "giữ liên lạc" },
    { key: "c", label: "tiếp tục cố gắng" },
    { key: "d", label: "để mắt đến, trông chừng" },
  ]),
  mcq("ex-pre-82-13", "82 · Chọn đáp án", "\"Miss a deadline\" nghĩa là ___", "a", [
    { key: "a", label: "lỡ hạn nộp" },
    { key: "b", label: "bỏ lỡ cơ hội" },
    { key: "c", label: "lỡ chuyến xe buýt" },
    { key: "d", label: "nhớ ai" },
  ]),
  mcq("ex-pre-82-14", "82 · Chọn đáp án", "\"Keep in mind\" nghĩa là ___", "c", [
    { key: "a", label: "giữ bình tĩnh" },
    { key: "b", label: "giữ liên lạc" },
    { key: "c", label: "ghi nhớ" },
    { key: "d", label: "để mắt đến" },
  ]),
];

const UNIT_83: VocabularyExercise[] = [
  match("ex-pre-83-1", "83 · Ghép từ với nghĩa", [
    { left: "get better", right: "trở nên tốt hơn / khỏi bệnh" },
    { left: "get ready", right: "chuẩn bị sẵn sàng" },
    { left: "get used to", right: "quen với" },
    { left: "get rid of", right: "loại bỏ" },
    { left: "get along with", right: "hòa hợp với" },
    { left: "get the hang of", right: "nắm được cách làm" },
  ]),
  cloze("ex-pre-83-2", "83 · Điền cụm", "My pronunciation is getting ___.", "better", ["Better"]),
  cloze("ex-pre-83-3", "83 · Điền cụm", "Get ___. The class starts in five minutes.", "ready", ["Ready"]),
  cloze("ex-pre-83-4", "83 · Điền cụm", "You will get used ___ the new schedule soon.", "to", ["To"]),
  cloze("ex-pre-83-5", "83 · Điền cụm", "We need to get rid ___ outdated files.", "of", ["Of"]),
  cloze("ex-pre-83-6", "83 · Điền cụm", "She gets along ___ all her coworkers.", "with", ["With"]),
  cloze("ex-pre-83-7", "83 · Điền cụm", "I finally got the hang ___ this software.", "of", ["Of"]),
  cloze("ex-pre-83-8", "83 · Điền cụm", "Please get in ___ if you need support.", "touch", ["Touch"]),
  mcq("ex-pre-83-9", "83 · Chọn đáp án", "Cụm nào có nghĩa là 'loại bỏ'?", "b", [
    { key: "a", label: "get through" },
    { key: "b", label: "get rid of" },
    { key: "c", label: "get by" },
    { key: "d", label: "get back" },
  ]),
  mcq("ex-pre-83-10", "83 · Chọn đáp án", "\"Get by\" nghĩa là ___", "c", [
    { key: "a", label: "kết hôn" },
    { key: "b", label: "bị lạc" },
    { key: "c", label: "xoay xở sống qua" },
    { key: "d", label: "tụ họp" },
  ]),
  mcq("ex-pre-83-11", "83 · Chọn đáp án", "\"Get into trouble\" nghĩa là ___", "a", [
    { key: "a", label: "gặp rắc rối" },
    { key: "b", label: "kiếm được việc" },
    { key: "c", label: "liên lạc" },
    { key: "d", label: "vượt qua" },
  ]),
  mcq("ex-pre-83-12", "83 · Chọn đáp án", "\"Get worse\" nghĩa là ___", "d", [
    { key: "a", label: "trở nên tốt hơn" },
    { key: "b", label: "quen với" },
    { key: "c", label: "chuẩn bị sẵn sàng" },
    { key: "d", label: "trở nên tệ hơn" },
  ]),
  mcq("ex-pre-83-13", "83 · Chọn đáp án", "\"Get together\" nghĩa là ___", "b", [
    { key: "a", label: "liên lạc" },
    { key: "b", label: "tụ họp" },
    { key: "c", label: "trở về" },
    { key: "d", label: "vượt qua" },
  ]),
  mcq("ex-pre-83-14", "83 · Chọn đáp án", "\"Get permission\" nghĩa là ___", "c", [
    { key: "a", label: "kiếm được việc" },
    { key: "b", label: "bị lạc" },
    { key: "c", label: "xin được sự cho phép" },
    { key: "d", label: "nắm được cách làm" },
  ]),
];

const UNIT_84: VocabularyExercise[] = [
  match("ex-pre-84-1", "84 · Ghép từ với nghĩa", [
    { left: "go ahead", right: "cứ làm đi, cứ tiếp tục" },
    { left: "go well", right: "diễn ra suôn sẻ" },
    { left: "go wrong", right: "xảy ra sai sót" },
    { left: "go up", right: "tăng lên" },
    { left: "go down", right: "giảm xuống" },
    { left: "go missing", right: "biến mất" },
  ]),
  cloze("ex-pre-84-2", "84 · Điền cụm", "Go ___ and ask your question.", "ahead", ["Ahead"]),
  cloze("ex-pre-84-3", "84 · Điền cụm", "I need to go ___ and check the figures.", "back", ["Back"]),
  cloze("ex-pre-84-4", "84 · Điền cụm", "Food prices have gone ___ recently.", "up", ["Up"]),
  cloze("ex-pre-84-5", "84 · Điền cụm", "The temperature went ___ at night.", "down", ["Down"]),
  cloze("ex-pre-84-6", "84 · Điền cụm", "Something went ___ with the payment.", "wrong", ["Wrong"]),
  cloze("ex-pre-84-7", "84 · Điền cụm", "Let's go ___ the key vocabulary again.", "over", ["Over"]),
  cloze("ex-pre-84-8", "84 · Điền cụm", "Time goes ___ so quickly these days.", "by", ["By"]),
  mcq("ex-pre-84-9", "84 · Chọn đáp án", "Cụm nào thường dùng để cho phép người khác tiếp tục?", "b", [
    { key: "a", label: "go by" },
    { key: "b", label: "go ahead" },
    { key: "c", label: "go bankrupt" },
    { key: "d", label: "go missing" },
  ]),
  mcq("ex-pre-84-10", "84 · Chọn đáp án", "\"Go through\" nghĩa là ___", "a", [
    { key: "a", label: "trải qua / xem xét kỹ" },
    { key: "b", label: "tăng lên" },
    { key: "c", label: "ra ngoài" },
    { key: "d", label: "phá sản" },
  ]),
  mcq("ex-pre-84-11", "84 · Chọn đáp án", "\"Go for\" nghĩa là ___", "c", [
    { key: "a", label: "hợp với" },
    { key: "b", label: "xoay xở mà không có" },
    { key: "c", label: "chọn / nhắm đến" },
    { key: "d", label: "tiếp diễn" },
  ]),
  mcq("ex-pre-84-12", "84 · Chọn đáp án", "\"Go off\" trong \"My alarm went off at 5:30\" nghĩa là ___", "d", [
    { key: "a", label: "hỏng" },
    { key: "b", label: "ra ngoài" },
    { key: "c", label: "giảm xuống" },
    { key: "d", label: "đổ chuông" },
  ]),
  mcq("ex-pre-84-13", "84 · Chọn đáp án", "\"Go with\" nghĩa là ___", "a", [
    { key: "a", label: "hợp với / đi cùng" },
    { key: "b", label: "chọn / nhắm đến" },
    { key: "c", label: "phá sản" },
    { key: "d", label: "biến mất" },
  ]),
  mcq("ex-pre-84-14", "84 · Chọn đáp án", "\"Go without\" nghĩa là ___", "b", [
    { key: "a", label: "diễn ra suôn sẻ" },
    { key: "b", label: "xoay xở mà không có" },
    { key: "c", label: "xảy ra sai sót" },
    { key: "d", label: "tăng lên" },
  ]),
];

const UNIT_85: VocabularyExercise[] = [
  match("ex-pre-85-1", "85 · Ghép từ với nghĩa", [
    { left: "glance at", right: "liếc nhanh qua" },
    { left: "stare at", right: "nhìn chằm chằm" },
    { left: "overhear", right: "vô tình nghe được" },
    { left: "ring a bell", right: "nghe quen quen, gợi nhớ" },
    { left: "fragrant", right: "thơm dễ chịu" },
    { left: "blurry", right: "mờ, không rõ nét" },
  ]),
  cloze("ex-pre-85-2", "85 · Điền cụm", "I glanced ___ the clock during the meeting.", "at", ["At"]),
  cloze("ex-pre-85-3", "85 · Điền cụm", "It is impolite to stare ___ people.", "at", ["At"]),
  cloze("ex-pre-85-4", "85 · Điền từ", "I ___ them talking about the project.", "overheard", ["Overheard"]),
  cloze("ex-pre-85-5", "85 · Điền cụm", "His name rings a ___, but I am not sure why.", "bell", ["Bell"]),
  cloze("ex-pre-85-6", "85 · Điền cụm", "The kitchen smells ___ fresh bread.", "of", ["Of"]),
  cloze("ex-pre-85-7", "85 · Điền từ", "These flowers are very ___.", "fragrant", ["Fragrant"]),
  cloze("ex-pre-85-8", "85 · Điền từ", "The photo is ___ because I moved.", "blurry", ["Blurry"]),
  mcq("ex-pre-85-9", "85 · Chọn đáp án", "Từ nào có nghĩa là 'vô tình nghe được'?", "b", [
    { key: "a", label: "spot" },
    { key: "b", label: "overhear" },
    { key: "c", label: "stare at" },
    { key: "d", label: "gaze at" },
  ]),
  mcq("ex-pre-85-10", "85 · Chọn đáp án", "\"Gaze at\" khác \"glance at\" ở chỗ ___", "c", [
    { key: "a", label: "gaze at là nhìn nhanh" },
    { key: "b", label: "hai cụm không khác nhau" },
    { key: "c", label: "gaze at là nhìn chăm chú lâu hơn" },
    { key: "d", label: "glance at là nhìn chằm chằm" },
  ]),
  mcq("ex-pre-85-11", "85 · Chọn đáp án", "Từ nào mô tả vị 'đắng'?", "a", [
    { key: "a", label: "bitter" },
    { key: "b", label: "sour" },
    { key: "c", label: "fragrant" },
    { key: "d", label: "crunchy" },
  ]),
  mcq("ex-pre-85-12", "85 · Chọn đáp án", "\"Crunchy\" mô tả cảm giác ___", "d", [
    { key: "a", label: "mịn như lụa" },
    { key: "b", label: "thô ráp" },
    { key: "c", label: "mờ, không rõ nét" },
    { key: "d", label: "giòn rụm khi cắn" },
  ]),
  mcq("ex-pre-85-13", "85 · Chọn đáp án", "\"Faint\" mô tả âm thanh ___", "b", [
    { key: "a", label: "rất to" },
    { key: "b", label: "mờ/nhẹ, khó nhận biết" },
    { key: "c", label: "thơm dễ chịu" },
    { key: "d", label: "bốc mùi khó chịu" },
  ]),
  mcq("ex-pre-85-14", "85 · Chọn đáp án", "\"Sound familiar\" nghĩa là ___", "c", [
    { key: "a", label: "nghe lạ" },
    { key: "b", label: "nghe to" },
    { key: "c", label: "nghe quen" },
    { key: "d", label: "vô tình nghe được" },
  ]),
];

const UNIT_86: VocabularyExercise[] = [
  match("ex-pre-86-1", "86 · Ghép từ với nghĩa", [
    { left: "advice", right: "lời khuyên (không đếm được)" },
    { left: "information", right: "thông tin (không đếm được)" },
    { left: "furniture", right: "đồ nội thất (không đếm được)" },
    { left: "equipment", right: "trang thiết bị (không đếm được)" },
    { left: "a piece of advice", right: "một lời khuyên" },
    { left: "progress", right: "sự tiến bộ (không đếm được)" },
  ]),
  cloze("ex-pre-86-2", "86 · Điền từ", "She gave me helpful ___.", "advice", ["Advice"]),
  cloze("ex-pre-86-3", "86 · Điền từ", "I need more ___ about the course.", "information", ["Information"]),
  cloze("ex-pre-86-4", "86 · Điền từ", "We bought new ___ for the living room.", "furniture", ["Furniture"]),
  cloze("ex-pre-86-5", "86 · Điền từ", "The lab ___ is expensive.", "equipment", ["Equipment"]),
  cloze("ex-pre-86-6", "86 · Điền cụm", "Let me give you a piece of ___.", "advice", ["Advice"]),
  cloze("ex-pre-86-7", "86 · Điền từ", "You are making steady ___.", "progress", ["Progress"]),
  cloze("ex-pre-86-8", "86 · Điền từ", "I have too much ___ tonight.", "homework", ["Homework"]),
  mcq("ex-pre-86-9", "86 · Chọn đáp án", "Cách dùng nào đúng?", "c", [
    { key: "a", label: "an advice" },
    { key: "b", label: "two informations" },
    { key: "c", label: "a piece of advice" },
    { key: "d", label: "many furniture" },
  ]),
  mcq("ex-pre-86-10", "86 · Chọn đáp án", "Danh từ nào KHÔNG đếm được?", "b", [
    { key: "a", label: "a piece of advice" },
    { key: "b", label: "luggage" },
    { key: "c", label: "a bit of information" },
    { key: "d", label: "none — all are countable" },
  ]),
  mcq("ex-pre-86-11", "86 · Chọn đáp án", "Cách lượng hóa \"information\" đúng là ___", "a", [
    { key: "a", label: "a bit of information" },
    { key: "b", label: "an information" },
    { key: "c", label: "many informations" },
    { key: "d", label: "few informations" },
  ]),
  mcq("ex-pre-86-12", "86 · Chọn đáp án", "\"Research\" trong ngữ cảnh chung đi với động từ ___", "c", [
    { key: "a", label: "are" },
    { key: "b", label: "were" },
    { key: "c", label: "is" },
    { key: "d", label: "have" },
  ]),
  mcq("ex-pre-86-13", "86 · Chọn đáp án", "\"Scenery\" nghĩa là ___", "d", [
    { key: "a", label: "hành vi" },
    { key: "b", label: "chỗ ở" },
    { key: "c", label: "bằng chứng" },
    { key: "d", label: "phong cảnh" },
  ]),
  mcq("ex-pre-86-14", "86 · Chọn đáp án", "\"Cash\" là danh từ ___", "b", [
    { key: "a", label: "đếm được số nhiều" },
    { key: "b", label: "không đếm được" },
    { key: "c", label: "chỉ dùng số nhiều" },
    { key: "d", label: "luôn có a/an" },
  ]),
];

const UNIT_87: VocabularyExercise[] = [
  match("ex-pre-87-1", "87 · Ghép từ với nghĩa", [
    { left: "enjoy doing", right: "thích làm gì" },
    { left: "avoid doing", right: "tránh làm gì" },
    { left: "decide to do", right: "quyết định làm gì" },
    { left: "manage to do", right: "xoay xở để làm được" },
    { left: "can't stand doing", right: "không chịu nổi việc làm gì" },
    { left: "spend time doing", right: "dành thời gian làm gì" },
  ]),
  cloze("ex-pre-87-2", "87 · Điền cụm", "I enjoy ___ before bed.", "reading", ["Reading"]),
  cloze("ex-pre-87-3", "87 · Điền cụm", "Try to avoid ___ your phone while studying.", "checking", ["Checking"]),
  cloze("ex-pre-87-4", "87 · Điền cụm", "I decided ___ learn Spanish this year.", "to", ["To"]),
  cloze("ex-pre-87-5", "87 · Điền cụm", "She managed ___ finish on time.", "to", ["To"]),
  cloze("ex-pre-87-6", "87 · Điền cụm", "He can't stand ___ in long queues.", "waiting", ["Waiting"]),
  cloze("ex-pre-87-7", "87 · Điền cụm", "She spends a lot of time ___ piano.", "practicing", ["Practicing"]),
  cloze("ex-pre-87-8", "87 · Điền cụm", "Sorry, I am busy ___ tomorrow's lesson.", "preparing", ["Preparing"]),
  mcq("ex-pre-87-9", "87 · Chọn đáp án", "Câu nào đúng ngữ pháp?", "b", [
    { key: "a", label: "I enjoy to read at night." },
    { key: "b", label: "I enjoy reading at night." },
    { key: "c", label: "I enjoy read at night." },
    { key: "d", label: "I enjoy to reading at night." },
  ]),
  mcq("ex-pre-87-10", "87 · Chọn đáp án", "\"Suggest doing\" đi theo dạng ___", "a", [
    { key: "a", label: "verb + -ing" },
    { key: "b", label: "verb + to do" },
    { key: "c", label: "verb + bare infinitive" },
    { key: "d", label: "verb + past tense" },
  ]),
  mcq("ex-pre-87-11", "87 · Chọn đáp án", "\"Refuse to do\" nghĩa là ___", "c", [
    { key: "a", label: "hy vọng làm gì" },
    { key: "b", label: "hứa sẽ làm gì" },
    { key: "c", label: "từ chối làm gì" },
    { key: "d", label: "cân nhắc làm gì" },
  ]),
  mcq("ex-pre-87-12", "87 · Chọn đáp án", "\"Consider doing\" nghĩa là ___", "b", [
    { key: "a", label: "hoàn thành việc làm gì" },
    { key: "b", label: "cân nhắc làm gì" },
    { key: "c", label: "tránh làm gì" },
    { key: "d", label: "gợi ý làm gì" },
  ]),
  mcq("ex-pre-87-13", "87 · Chọn đáp án", "\"Would like to do\" là cách nói ___ hơn \"want to do\"", "d", [
    { key: "a", label: "mạnh mẽ" },
    { key: "b", label: "thân mật" },
    { key: "c", label: "trang trọng nhất" },
    { key: "d", label: "lịch sự" },
  ]),
  mcq("ex-pre-87-14", "87 · Chọn đáp án", "\"Need to do\" đi theo dạng ___", "b", [
    { key: "a", label: "verb + -ing" },
    { key: "b", label: "verb + to do" },
    { key: "c", label: "verb + bare infinitive only" },
    { key: "d", label: "verb + past participle" },
  ]),
];

const UNIT_88: VocabularyExercise[] = [
  match("ex-pre-88-1", "88 · Ghép từ với nghĩa", [
    { left: "make someone do", right: "bắt/khiến ai làm gì" },
    { left: "let someone do", right: "để cho ai làm gì" },
    { left: "ask someone to do", right: "nhờ/yêu cầu ai làm gì" },
    { left: "stop doing", right: "dừng hẳn một hoạt động" },
    { left: "stop to do", right: "dừng lại để làm việc khác" },
    { left: "used to do", right: "đã từng làm (thói quen quá khứ)" },
  ]),
  cloze("ex-pre-88-2", "88 · Điền cụm", "The teacher made us ___ the paragraph.", "rewrite", ["Rewrite"]),
  cloze("ex-pre-88-3", "88 · Điền cụm", "My parents let me ___ my major.", "choose", ["Choose"]),
  cloze("ex-pre-88-4", "88 · Điền cụm", "I asked him ___ send the file.", "to", ["To"]),
  cloze("ex-pre-88-5", "88 · Điền cụm", "He stopped ___ last year.", "smoking", ["Smoking"]),
  cloze("ex-pre-88-6", "88 · Điền cụm", "We stopped ___ buy some water.", "to", ["To"]),
  cloze("ex-pre-88-7", "88 · Điền cụm", "I remember ___ the door.", "locking", ["Locking"]),
  cloze("ex-pre-88-8", "88 · Điền cụm", "Remember ___ charge your phone tonight.", "to", ["To"]),
  mcq("ex-pre-88-9", "88 · Chọn đáp án", "Câu nào mang nghĩa 'dừng lại để làm việc khác'?", "b", [
    { key: "a", label: "We stopped talking." },
    { key: "b", label: "We stopped to talk." },
    { key: "c", label: "We stop talked." },
    { key: "d", label: "We stopping to talk." },
  ]),
  mcq("ex-pre-88-10", "88 · Chọn đáp án", "\"Remember doing\" nghĩa là ___", "a", [
    { key: "a", label: "nhớ đã làm gì rồi" },
    { key: "b", label: "nhớ phải làm gì" },
    { key: "c", label: "dừng hẳn một hoạt động" },
    { key: "d", label: "cố gắng làm" },
  ]),
  mcq("ex-pre-88-11", "88 · Chọn đáp án", "\"Try doing\" khác \"try to do\" ở chỗ ___", "c", [
    { key: "a", label: "try doing nghĩa là cố gắng làm" },
    { key: "b", label: "hai cụm không khác nhau" },
    { key: "c", label: "try doing nghĩa là thử làm để xem hiệu quả" },
    { key: "d", label: "try to do nghĩa là thử nghiệm" },
  ]),
  mcq("ex-pre-88-12", "88 · Chọn đáp án", "\"Warn someone not to do\" nghĩa là ___", "d", [
    { key: "a", label: "mời ai làm gì" },
    { key: "b", label: "khuyến khích ai làm gì" },
    { key: "c", label: "nhắc ai làm gì" },
    { key: "d", label: "cảnh báo ai đừng làm gì" },
  ]),
  mcq("ex-pre-88-13", "88 · Chọn đáp án", "\"Prefer doing to doing\" diễn tả ___", "b", [
    { key: "a", label: "thói quen quá khứ" },
    { key: "b", label: "thích làm A hơn làm B" },
    { key: "c", label: "dừng hẳn hoạt động" },
    { key: "d", label: "bắt ai làm gì" },
  ]),
  mcq("ex-pre-88-14", "88 · Chọn đáp án", "\"Used to do\" diễn tả ___", "a", [
    { key: "a", label: "thói quen trước đây không còn đúng ở hiện tại" },
    { key: "b", label: "quen với điều gì" },
    { key: "c", label: "nhớ phải làm gì" },
    { key: "d", label: "cố gắng làm" },
  ]),
];

const UNIT_89: VocabularyExercise[] = [
  match("ex-pre-89-1", "89 · Ghép từ với nghĩa", [
    { left: "amazing", right: "rất tuyệt, gây ấn tượng mạnh" },
    { left: "amazed", right: "kinh ngạc" },
    { left: "boring", right: "gây chán" },
    { left: "bored", right: "cảm thấy chán" },
    { left: "reliable", right: "đáng tin cậy" },
    { left: "affordable", right: "vừa túi tiền, giá phải chăng" },
  ]),
  cloze("ex-pre-89-2", "89 · Điền từ", "The view from the top floor is ___.", "amazing", ["Amazing"]),
  cloze("ex-pre-89-3", "89 · Điền từ", "I was ___ by her quick progress.", "amazed", ["Amazed"]),
  cloze("ex-pre-89-4", "89 · Điền từ", "The lecture was long and ___.", "boring", ["Boring"]),
  cloze("ex-pre-89-5", "89 · Điền từ", "I felt ___ during the delay.", "bored", ["Bored"]),
  cloze("ex-pre-89-6", "89 · Điền từ", "She is a ___ teammate.", "reliable", ["Reliable"]),
  cloze("ex-pre-89-7", "89 · Điền từ", "This neighborhood has ___ apartments.", "affordable", ["Affordable"]),
  cloze("ex-pre-89-8", "89 · Điền từ", "Online payment is very ___.", "convenient", ["Convenient"]),
  mcq("ex-pre-89-9", "89 · Chọn đáp án", "Chọn câu đúng:", "b", [
    { key: "a", label: "I am amazing by this result." },
    { key: "b", label: "I am amazed by this result." },
    { key: "c", label: "This result is amazed." },
    { key: "d", label: "This result amazement." },
  ]),
  mcq("ex-pre-89-10", "89 · Chọn đáp án", "Tính từ -ing thường mô tả ___", "c", [
    { key: "a", label: "người cảm thấy cảm xúc" },
    { key: "b", label: "hành vi của người" },
    { key: "c", label: "thứ gây ra cảm xúc" },
    { key: "d", label: "thời gian" },
  ]),
  mcq("ex-pre-89-11", "89 · Chọn đáp án", "\"Confusing\" và \"confused\" khác nhau ở chỗ ___", "a", [
    { key: "a", label: "confusing mô tả sự vật gây rối; confused mô tả người bối rối" },
    { key: "b", label: "hai từ không khác nhau" },
    { key: "c", label: "confused mô tả sự vật gây rối" },
    { key: "d", label: "confusing mô tả người bối rối" },
  ]),
  mcq("ex-pre-89-12", "89 · Chọn đáp án", "\"Spacious\" nghĩa là ___", "d", [
    { key: "a", label: "đông đúc" },
    { key: "b", label: "hiệu quả" },
    { key: "c", label: "lịch sự" },
    { key: "d", label: "rộng rãi" },
  ]),
  mcq("ex-pre-89-13", "89 · Chọn đáp án", "\"Rude\" nghĩa là ___", "b", [
    { key: "a", label: "lịch sự" },
    { key: "b", label: "thô lỗ, bất lịch sự" },
    { key: "c", label: "kiên nhẫn" },
    { key: "d", label: "trung thực" },
  ]),
  mcq("ex-pre-89-14", "89 · Chọn đáp án", "\"Challenging\" nghĩa là ___", "c", [
    { key: "a", label: "gây chán" },
    { key: "b", label: "vừa túi tiền" },
    { key: "c", label: "đầy thử thách" },
    { key: "d", label: "linh hoạt" },
  ]),
];

const UNIT_90: VocabularyExercise[] = [
  match("ex-pre-90-1", "90 · Ghép từ với nghĩa", [
    { left: "across", right: "băng ngang qua" },
    { left: "through", right: "xuyên qua" },
    { left: "along", right: "dọc theo" },
    { left: "between", right: "ở giữa hai vật/người" },
    { left: "opposite", right: "đối diện" },
    { left: "in front of", right: "ở phía trước" },
  ]),
  cloze("ex-pre-90-2", "90 · Điền từ", "We walked ___ the bridge.", "across", ["Across"]),
  cloze("ex-pre-90-3", "90 · Điền từ", "The train passed ___ a long tunnel.", "through", ["Through"]),
  cloze("ex-pre-90-4", "90 · Điền từ", "They cycled ___ the river.", "along", ["Along"]),
  cloze("ex-pre-90-5", "90 · Điền từ", "Go ___ the bank and turn left.", "past", ["Past"]),
  cloze("ex-pre-90-6", "90 · Điền từ", "The cafe is ___ the bookstore and the pharmacy.", "between", ["Between"]),
  cloze("ex-pre-90-7", "90 · Điền từ", "Our office is ___ the post office.", "opposite", ["Opposite"]),
  cloze("ex-pre-90-8", "90 · Điền cụm", "There is a bus stop in front ___ my house.", "of", ["Of"]),
  mcq("ex-pre-90-9", "90 · Chọn đáp án", "Giới từ nào nghĩa là 'xuyên qua'?", "b", [
    { key: "a", label: "across" },
    { key: "b", label: "through" },
    { key: "c", label: "beside" },
    { key: "d", label: "among" },
  ]),
  mcq("ex-pre-90-10", "90 · Chọn đáp án", "\"Among\" dùng khi ___", "c", [
    { key: "a", label: "chỉ vị trí giữa hai vật" },
    { key: "b", label: "chỉ hướng di chuyển" },
    { key: "c", label: "ở giữa nhiều vật/người" },
    { key: "d", label: "ở phía sau" },
  ]),
  mcq("ex-pre-90-11", "90 · Chọn đáp án", "\"Across\" khác \"through\" ở chỗ ___", "a", [
    { key: "a", label: "across là băng ngang bề mặt; through là xuyên qua không gian" },
    { key: "b", label: "hai giới từ không khác nhau" },
    { key: "c", label: "through là băng ngang bề mặt" },
    { key: "d", label: "across chỉ dùng cho thời gian" },
  ]),
  mcq("ex-pre-90-12", "90 · Chọn đáp án", "\"Towards\" nghĩa là ___", "d", [
    { key: "a", label: "ra xa khỏi" },
    { key: "b", label: "ở bên trong" },
    { key: "c", label: "ở bên ngoài" },
    { key: "d", label: "hướng về phía" },
  ]),
  mcq("ex-pre-90-13", "90 · Chọn đáp án", "\"Away from\" nghĩa là ___", "b", [
    { key: "a", label: "hướng về phía" },
    { key: "b", label: "ra xa khỏi" },
    { key: "c", label: "dọc theo" },
    { key: "d", label: "đối diện" },
  ]),
  mcq("ex-pre-90-14", "90 · Chọn đáp án", "\"Up to\" nghĩa là ___", "c", [
    { key: "a", label: "ở bên dưới" },
    { key: "b", label: "ở giữa hai vật" },
    { key: "c", label: "cho đến tận, lên tới" },
    { key: "d", label: "băng ngang qua" },
  ]),
];

export const CURATED_PRE_UNITS_76_90: Readonly<Partial<Record<number, readonly VocabularyExercise[]>>> = {
  76: UNIT_76,
  77: UNIT_77,
  78: UNIT_78,
  79: UNIT_79,
  80: UNIT_80,
  81: UNIT_81,
  82: UNIT_82,
  83: UNIT_83,
  84: UNIT_84,
  85: UNIT_85,
  86: UNIT_86,
  87: UNIT_87,
  88: UNIT_88,
  89: UNIT_89,
  90: UNIT_90,
};

for (const [unitNumber, exercises] of Object.entries(CURATED_PRE_UNITS_76_90)) {
  if (exercises) {
    assertExerciseCount(Number(unitNumber), exercises);
  }
}
