export const CURATED_PRE_PROMPT_VI_31_45: Readonly<Record<string, string>> = {
  "ex-pre-31-1": "Ghép mỗi từ với nghĩa tiếng Việt.",
  "ex-pre-31-2": "Hãy giữ ___ (tài liệu phát tay) cho buổi học sau.",
  "ex-pre-31-3": "Viết câu trả lời của bạn lên ___ (bảng trắng).",
  "ex-pre-31-4": "___ (điểm danh) được thực hiện vào đầu giờ học.",
  "ex-pre-31-5": "Kiểm tra ___ (thời khóa biểu) trước thứ Hai.",
  "ex-pre-31-6": "Chúng ta sẽ làm ___ (hoạt động theo cặp) trong mười phút.",
  "ex-pre-31-7": "Hãy ___ (nộp) bài tập trước thứ Sáu.",
  "ex-pre-31-8": "Tôi ___ (ôn tập) từ vựng mỗi tối.",
  "ex-pre-31-9": "Cụm nào có nghĩa 'giơ tay xin phát biểu'?",
  "ex-pre-31-10": "Một ___ là phiếu bài tập trên lớp.",
  "ex-pre-31-11": "\"To ___\" nghĩa là ghi chép ý chính khi học.",
  "ex-pre-31-12": "Chúng tôi làm một ___ (bài luyện phát âm) trong lớp.",
  "ex-pre-31-13": "___ (hạn chót) của dự án là thứ Ba tới.",
  "ex-pre-31-14": "\"To ___\" nghĩa là làm rõ điều chưa hiểu.",
  "ex-pre-32-1": "Ghép mỗi từ với nghĩa tiếng Việt.",
  "ex-pre-32-2": "___ (chương trình học) gồm khoa học và nghệ thuật.",
  "ex-pre-32-3": "___ (học kỳ) này kết thúc vào tháng Mười Hai.",
  "ex-pre-32-4": "Toán là một ___ (môn học bắt buộc).",
  "ex-pre-32-5": "Âm nhạc là một ___ (môn học tự chọn).",
  "ex-pre-32-6": "Tôi cho bố mẹ xem ___ (phiếu kết quả học tập).",
  "ex-pre-32-7": "___ (đồng phục học sinh) của chúng tôi màu xanh và trắng.",
  "ex-pre-32-8": "Có một ___ (buổi tập trung toàn trường) vào mỗi sáng thứ Hai.",
  "ex-pre-32-9": "Một ___ là điểm số hoặc mức đánh giá.",
  "ex-pre-32-10": "___ chào đón các học sinh mới.",
  "ex-pre-32-11": "Học sinh gặp nhau ở ___ vào giờ ra chơi.",
  "ex-pre-32-12": "___ (chuyến đi học tập) rất bổ ích.",
  "ex-pre-32-13": "___ (kỷ luật) tốt tạo ra không gian học tập tốt hơn.",
  "ex-pre-32-14": "___ tăng trong năm nay.",
  "ex-pre-33-1": "Ghép mỗi từ với nghĩa tiếng Việt.",
  "ex-pre-33-2": "Chúng tôi làm một ___ (kỳ thi thử) mỗi tháng.",
  "ex-pre-33-3": "Đừng viết lên ___ (đề thi) trước.",
  "ex-pre-33-4": "___ (giám thị) kiểm tra thẻ của chúng tôi.",
  "ex-pre-33-5": "Mỗi ___ (thí sinh) có một số báo danh.",
  "ex-pre-33-6": "Đọc ___ (thang điểm chấm) sau khi luyện tập.",
  "ex-pre-33-7": "___ (quản lý thời gian) rất quan trọng trong bài đọc.",
  "ex-pre-33-8": "___ (điểm band) mục tiêu của tôi là 6.5.",
  "ex-pre-33-9": "\"To ___\" nghĩa là nghe lấy ý chính.",
  "ex-pre-33-10": "\"To ___\" nghĩa là quét nhanh để tìm chi tiết.",
  "ex-pre-33-11": "Một ___ là đáp án nhiễu trong bài trắc nghiệm.",
  "ex-pre-33-12": "Luôn ___ (soát lỗi) bài viết của bạn.",
  "ex-pre-33-13": "Lập một ___ (kế hoạch ôn tập) hằng tuần.",
  "ex-pre-33-14": "___ là 50 phần trăm.",
  "ex-pre-34-1": "Ghép mỗi từ với nghĩa tiếng Việt.",
  "ex-pre-34-2": "Cô ấy là một ___ (sinh viên cử nhân) ngành kinh tế.",
  "ex-pre-34-3": "Anh ấy là một sinh viên ___ (sau đại học).",
  "ex-pre-34-4": "___ (khuôn viên trường) nằm gần trung tâm thành phố.",
  "ex-pre-34-5": "Lớp chúng tôi ở ___ (giảng đường) B.",
  "ex-pre-34-6": "Chúng tôi có một ___ (buổi hội thảo) về đạo đức truyền thông.",
  "ex-pre-34-7": "___ (buổi hướng dẫn nhóm nhỏ) diễn ra chiều thứ Năm hằng tuần.",
  "ex-pre-34-8": "Học phần này trị giá ba ___ (tín chỉ).",
  "ex-pre-34-9": "Một ___ là chuyên ngành chính của sinh viên.",
  "ex-pre-34-10": "Bây giờ anh ấy đang viết ___ của mình.",
  "ex-pre-34-11": "Cô ấy nhận được một ___ toàn phần.",
  "ex-pre-34-12": "Hãy nói chuyện với ___ (cố vấn học tập) của bạn trước.",
  "ex-pre-34-13": "Bạn phải ___ (đăng ký nhập học) trước hạn chót.",
  "ex-pre-34-14": "Anh ấy sẽ ___ vào mùa hè tới.",
  "ex-pre-35-1": "Ghép mỗi từ với nghĩa tiếng Việt.",
  "ex-pre-35-2": "___ (nghề nghiệp) của bạn là gì?",
  "ex-pre-35-3": "Dạy học là một ___ (nghề chuyên môn) được kính trọng.",
  "ex-pre-35-4": "Tôi có một vị trí ___ (toàn thời gian).",
  "ex-pre-35-5": "Nhiều sinh viên làm công việc ___ (bán thời gian).",
  "ex-pre-35-6": "Tôi thấy một ___ (vị trí tuyển dụng) trên mạng.",
  "ex-pre-35-7": "Bạn cần ___ (bằng cấp) phù hợp.",
  "ex-pre-35-8": "Cô ấy có năm năm ___ (kinh nghiệm).",
  "ex-pre-35-9": "Một ___ là kỳ thực tập nghề nghiệp.",
  "ex-pre-35-10": "Công nhân nhà máy nhận ___ theo giờ.",
  "ex-pre-35-11": "\"To ___\" nghĩa là xin nghỉ việc tự nguyện.",
  "ex-pre-35-12": "___ (ca làm) của tôi bắt đầu lúc 7 giờ sáng.",
  "ex-pre-35-13": "___ (lương) được trả vào ngày cuối cùng.",
  "ex-pre-35-14": "Cô ấy được ___ sau hai năm.",
  "ex-pre-36-1": "Ghép mỗi từ với nghĩa tiếng Việt.",
  "ex-pre-36-2": "___ (khối lượng công việc) của tôi rất nặng tuần này.",
  "ex-pre-36-3": "___ (áp lực hạn chót) ảnh hưởng đến giấc ngủ.",
  "ex-pre-36-4": "___ (trách nhiệm) chính của tôi là hỗ trợ khách hàng.",
  "ex-pre-36-5": "Tôi cập nhật ___ (danh sách công việc) mỗi sáng.",
  "ex-pre-36-6": "Bạn nên ___ (ưu tiên) các việc gấp.",
  "ex-pre-36-7": "Tôi có thể ___ (làm nhiều việc cùng lúc) trong văn phòng bận rộn.",
  "ex-pre-36-8": "Tôi ___ (phối hợp) với nhóm kinh doanh.",
  "ex-pre-36-9": "Một ___ tổ chức các buổi họp hằng tuần.",
  "ex-pre-36-10": "Chúng tôi theo một lịch ___.",
  "ex-pre-36-11": "\"To ___\" nghĩa là báo cáo trực tiếp cho ai.",
  "ex-pre-36-12": "Hôm qua tôi phải làm ___ (thêm giờ).",
  "ex-pre-36-13": "___ (buổi đánh giá hiệu suất) của tôi vào tuần tới.",
  "ex-pre-36-14": "___ tốt giúp tránh kiệt sức.",
  "ex-pre-37-1": "Ghép mỗi từ với nghĩa tiếng Việt.",
  "ex-pre-37-2": "Anh ấy có một ___ (lộ trình nghề nghiệp) rõ ràng.",
  "ex-pre-37-3": "Hãy đặt một ___ (mục tiêu nghề nghiệp) thực tế.",
  "ex-pre-37-4": "___ (bộ kỹ năng) của bạn rất mạnh.",
  "ex-pre-37-5": "Tôi cần ___ (nâng cao kỹ năng) về phân tích dữ liệu.",
  "ex-pre-37-6": "Nhiều người lao động ___ (học lại kỹ năng mới) sau khi tự động hóa.",
  "ex-pre-37-7": "___ (xây dựng quan hệ) giúp cô ấy tìm được cơ hội mới.",
  "ex-pre-37-8": "Một ___ (người cố vấn) có thể định hướng quyết định của bạn.",
  "ex-pre-37-9": "Công ty có chương trình ___.",
  "ex-pre-37-10": "___ có thể khiến nhà tuyển dụng lo ngại.",
  "ex-pre-37-11": "Hãy trình bày ___ của bạn khi phỏng vấn.",
  "ex-pre-37-12": "Đào tạo hỗ trợ ___ (phát triển chuyên môn).",
  "ex-pre-37-13": "Cô ấy thăng tiến trên ___ (nấc thang sự nghiệp) nhanh chóng.",
  "ex-pre-37-14": "Thành tựu này giúp bạn ___.",
  "ex-pre-38-1": "Ghép mỗi từ với nghĩa tiếng Việt.",
  "ex-pre-38-2": "Mỗi nhân viên có một ___ (bàn làm việc).",
  "ex-pre-38-3": "___ (đồ dùng văn phòng) được cất trong tủ đó.",
  "ex-pre-38-4": "Tháng này chúng tôi cần thêm ___ (văn phòng phẩm).",
  "ex-pre-38-5": "___ (hàng chờ in) rất dài.",
  "ex-pre-38-6": "___ (máy photocopy) hết giấy rồi.",
  "ex-pre-38-7": "Hãy đặt ___ (phòng họp) trước.",
  "ex-pre-38-8": "Chúng tôi có một ___ (cuộc gọi hội nghị) lúc 3 giờ chiều.",
  "ex-pre-38-9": "___ là một phần công việc của tôi.",
  "ex-pre-38-10": "Vui lòng gửi ___ trước.",
  "ex-pre-38-11": "\"To ___\" nghĩa là đặt trước phòng họp.",
  "ex-pre-38-12": "Tôi viết một ___ (email theo dõi) cho khách hàng.",
  "ex-pre-38-13": "___ (hộp thư đến) của tôi hôm nay đầy.",
  "ex-pre-38-14": "Nhóm chúng tôi dùng hệ thống ___.",
  "ex-pre-39-1": "Ghép mỗi từ với nghĩa tiếng Việt.",
  "ex-pre-39-2": "Anh ấy ra mắt một ___ (công ty khởi nghiệp) trong lĩnh vực fintech.",
  "ex-pre-39-3": "___ (người sáng lập) thuyết trình trước các nhà đầu tư.",
  "ex-pre-39-4": "Cô ấy là ___ (đồng sáng lập) của ứng dụng.",
  "ex-pre-39-5": "___ (cổ đông) biểu quyết về đề xuất.",
  "ex-pre-39-6": "___ (hội đồng quản trị) phê duyệt ngân sách.",
  "ex-pre-39-7": "Tôi làm ở ___ (phòng) marketing.",
  "ex-pre-39-8": "___ (bộ phận nhân sự) phụ trách tuyển dụng.",
  "ex-pre-39-9": "Đăng ký thuê bao là ___ chính của chúng tôi.",
  "ex-pre-39-10": "___ của họ có khả năng mở rộng.",
  "ex-pre-39-11": "Người quản lý nên ___ hiệu quả.",
  "ex-pre-39-12": "Tiền thuê là một khoản chi phí ___ (vận hành) lớn.",
  "ex-pre-39-13": "___ (dòng tiền) lành mạnh giữ cho doanh nghiệp ổn định.",
  "ex-pre-39-14": "___ tạo ra một tập đoàn lớn hơn.",
  "ex-pre-40-1": "Ghép mỗi từ với nghĩa tiếng Việt.",
  "ex-pre-40-2": "Công ty tăng gấp đôi ___ (doanh thu).",
  "ex-pre-40-3": "___ (biên lợi nhuận) thấp khiến nhà đầu tư lo lắng.",
  "ex-pre-40-4": "___ (lợi nhuận ròng) tăng trong quý này.",
  "ex-pre-40-5": "Công ty báo cáo một khoản ___ (lỗ) nhỏ.",
  "ex-pre-40-6": "Chúng ta cần một ___ (ngân sách) thực tế.",
  "ex-pre-40-7": "___ (dự báo) doanh số khá lạc quan.",
  "ex-pre-40-8": "Vui lòng gửi ___ (hóa đơn) hôm nay.",
  "ex-pre-40-9": "Hãy giữ ___ để hoàn tiền.",
  "ex-pre-40-10": "Họ vay một ___ để mua thiết bị.",
  "ex-pre-40-11": "___ ngắn hạn quá cao.",
  "ex-pre-40-12": "Chúng tôi hy vọng ___ (hòa vốn) trong năm nay.",
  "ex-pre-40-13": "Cô ấy đã ___ (trả hết) khoản vay sinh viên.",
  "ex-pre-40-14": "Kiểm toán viên xem xét ___.",
  "ex-pre-41-1": "Ghép mỗi từ với nghĩa tiếng Việt.",
  "ex-pre-41-2": "Đọc sách là ___ (hoạt động giải trí) yêu thích của tôi.",
  "ex-pre-41-3": "Tôi tập một ___ (buổi tập luyện) sau giờ làm.",
  "ex-pre-41-4": "Cô ấy tham gia một ___ (lớp thể dục).",
  "ex-pre-41-5": "Chúng tôi đi ___ (đi bộ đường dài) vào cuối tuần.",
  "ex-pre-41-6": "___ (đạp xe) giúp tôi thư giãn.",
  "ex-pre-41-7": "___ (bơi lội) tốt cho lưng của bạn.",
  "ex-pre-41-8": "___ (yoga) cải thiện độ dẻo dai.",
  "ex-pre-41-9": "\"To ___\" nghĩa là bắt đầu theo đuổi sở thích mới.",
  "ex-pre-41-10": "Âm nhạc giúp tôi ___.",
  "ex-pre-41-11": "Nhiếp ảnh là ___ chính của anh ấy.",
  "ex-pre-41-12": "Hãy cố ___ (duy trì vận động) mỗi ngày.",
  "ex-pre-41-13": "Cuối tuần giúp tôi ___ (nạp lại năng lượng).",
  "ex-pre-41-14": "Bóng đá là một ___ hàng đầu.",
  "ex-pre-42-1": "Ghép mỗi từ với nghĩa tiếng Việt.",
  "ex-pre-42-2": "Đội chúng tôi tham gia một ___ (giải đấu).",
  "ex-pre-42-3": "Cô ấy giành ___ (giải vô địch) quốc gia.",
  "ex-pre-42-4": "Họ vào đến ___ (trận chung kết).",
  "ex-pre-42-5": "___ (trận bán kết) diễn ra vào thứ Bảy.",
  "ex-pre-42-6": "Trận này là một ___ (trận vòng loại).",
  "ex-pre-42-7": "Kiểm tra ___ (lịch thi đấu) cho tuần tới.",
  "ex-pre-42-8": "___ (trọng tài) rút thẻ đỏ.",
  "ex-pre-42-9": "___ thay đổi chiến thuật.",
  "ex-pre-42-10": "Trận đấu kết thúc với một ___.",
  "ex-pre-42-11": "Chạy đường dài xây dựng ___.",
  "ex-pre-42-12": "Họ ghi bàn trong ___ (thời gian bù giờ).",
  "ex-pre-42-13": "Cô ấy ___ (gỡ hòa) trong hiệp hai.",
  "ex-pre-42-14": "Anh ấy ___ trong cuộc đua 200m.",
  "ex-pre-43-1": "Ghép mỗi từ với nghĩa tiếng Việt.",
  "ex-pre-43-2": "Tôi đang đọc một ___ (tiểu thuyết) lịch sử.",
  "ex-pre-43-3": "___ (cuốn tiểu sử) này rất truyền cảm hứng.",
  "ex-pre-43-4": "___ (hồi ký) của cô ấy trở thành sách bán chạy.",
  "ex-pre-43-5": "___ (cốt truyện) đầy bất ngờ.",
  "ex-pre-43-6": "Nhân vật chính có một ___ (hành trình phát triển nhân vật) mạnh mẽ.",
  "ex-pre-43-7": "___ (bối cảnh) là một thị trấn nhỏ ven biển.",
  "ex-pre-43-8": "___ (thể loại) yêu thích của tôi là khoa học viễn tưởng.",
  "ex-pre-43-9": "Bộ phim là một ___ từ tiểu thuyết.",
  "ex-pre-43-10": "Vui lòng đừng đăng ___.",
  "ex-pre-43-11": "Cuốn trinh thám đó thực sự là một ___.",
  "ex-pre-43-12": "Câu chuyện ___ (cuốn hút) từ đầu đến cuối.",
  "ex-pre-43-13": "Đó là một bộ phim tài liệu ___ (gợi suy ngẫm).",
  "ex-pre-43-14": "Người hâm mộ đang chờ đợi ___.",
  "ex-pre-44-1": "Ghép mỗi từ với nghĩa tiếng Việt.",
  "ex-pre-44-2": "___ (giai điệu) đọng trong đầu tôi cả ngày.",
  "ex-pre-44-3": "Bài hát này có ___ (nhịp điệu) mạnh.",
  "ex-pre-44-4": "Tôi thích ___ (lời bài hát) của ca khúc này.",
  "ex-pre-44-5": "Mọi người cùng hát ___ (điệp khúc).",
  "ex-pre-44-6": "___ (phiên khúc) thứ hai kể câu chuyện.",
  "ex-pre-44-7": "___ (hòa âm giọng hát) của họ rất tuyệt.",
  "ex-pre-44-8": "___ (nhịp độ) trở nên nhanh hơn về cuối.",
  "ex-pre-44-9": "Tôi tạo một ___ để học.",
  "ex-pre-44-10": "Tối qua chúng tôi đi xem một ___ nhạc jazz.",
  "ex-pre-44-11": "Khán giả yêu cầu một ___.",
  "ex-pre-44-12": "Cô ấy sẽ ___ (biểu diễn trực tiếp) vào cuối tuần này.",
  "ex-pre-44-13": "Anh ấy ___ (sáng tác) nhạc cho phim.",
  "ex-pre-44-14": "Nhạc công jazz thường ___.",
  "ex-pre-45-1": "Ghép mỗi từ với nghĩa tiếng Việt.",
  "ex-pre-45-2": "Hôm nay là ___ (kỷ niệm) ngày cưới của chúng tôi.",
  "ex-pre-45-3": "Tốt nghiệp là một ___ (sự kiện cột mốc).",
  "ex-pre-45-4": "___ (lễ) khai mạc bắt đầu lúc 8 giờ.",
  "ex-pre-45-5": "Cả thị trấn tham gia ___ (lễ ăn mừng).",
  "ex-pre-45-6": "___ (lễ hội) đèn lồng thu hút nhiều du khách.",
  "ex-pre-45-7": "Một ___ (cuộc diễu hành) đi qua trung tâm thành phố.",
  "ex-pre-45-8": "Chúng tôi xem ___ (pháo hoa) lúc nửa đêm.",
  "ex-pre-45-9": "Vui lòng chốt ___ hôm nay.",
  "ex-pre-45-10": "___ là trang trọng.",
  "ex-pre-45-11": "Mưa có thể ___ sự kiện ngoài trời.",
  "ex-pre-45-12": "Nhiều cựu sinh viên ___ (tham dự) buổi họp mặt.",
  "ex-pre-45-13": "Sự kiện ___ (tưởng niệm) những người hùng địa phương.",
  "ex-pre-45-14": "Đó là một buổi tối ___.",
};
