import type { VocabularyUnit } from "@/lib/vocabulary/vocabulary-unit-types";
import {
  bold,
  ex,
  fillBlank,
  mcq,
  purple,
} from "@/lib/vocabulary/units/eviu-unit-builder";
import { advancedUnit, wordList } from "@/lib/vocabulary/units/eviu-advanced-unit-helpers";

const U91_WORDS = wordList([
  ["polysemy", "một từ có nhiều nghĩa", "Linguists call this aspect of vocabulary polysemy.", "NOUN"],
  ["homograph", "từ cùng chính tả nhưng khác nghĩa hoàn toàn", "Book Fair and fair weather are homographs of fair.", "NOUN"],
  ["fair", "công bằng; hội chợ; thời tiết đẹp; da sáng; điểm khá", "It's only fair that we share the housework.", "ADJECTIVE"],
  ["book fair", "hội chợ sách", "The Frankfurt Book Fair is vital for publishers.", "NOUN"],
  ["fair skin", "da sáng, dễ cháy nắng", "I've got fair skin and burn easily in the sun.", "PHRASE"],
  ["flat", "căn hộ; bằng phẳng; phí cố định; nốt giáng; đúng (thời gian)", "They saved the children from the burning third-floor flat.", "NOUN"],
  ["flat fee", "mức phí cố định", "To join the club, you pay a flat fee of £500.", "PHRASE"],
  ["in five minutes flat", "chỉ đúng năm phút", "She finished the exercise in five minutes flat.", "PHRASE"],
  ["flat countryside", "vùng đất bằng phẳng, đơn điệu", "The countryside round here is terribly flat and boring.", "PHRASE"],
  ["capital letters", "chữ in hoa", "Fill in the form in capital letters.", "PHRASE"],
  ["capital", "thủ đô; vốn; án tử hình", "Wellington is the capital of New Zealand.", "NOUN"],
  ["plenty of capital", "nhiều vốn đầu tư", "You need plenty of capital to open a restaurant.", "PHRASE"],
  ["capital punishment", "hình phạt tử hình", "Capital punishment has been abolished in many countries.", "PHRASE"],
  ["mean", "nghĩa là; có ý định; keo kiệt; trung bình; đối xử tệ", "What does 'coagulate' mean?", "VERB"],
  ["I didn't mean to", "tôi không cố ý", "I didn't mean to hurt you.", "PHRASE"],
  ["mean temperature", "nhiệt độ trung bình", "The mean temperature for July is 25°C.", "PHRASE"],
  ["too mean to", "keo kiệt đến mức không chịu", "He's far too mean to buy her flowers.", "PHRASE"],
  ["range from excellent to fair", "từ xuất sắc đến khá", "His marks ranged from excellent to fair.", "PHRASE"],
  ["context", "ngữ cảnh giúp xác định nghĩa từ", "Context usually makes the intended meaning absolutely clear.", "NOUN"],
  ["parts of speech", "từ loại (danh từ, tính từ...)", "Words can sometimes be used as different parts of speech.", "PHRASE"],
  ["set of flat keys", "chùm chìa khóa phẳng (flat = căn hộ)", "Flat as apartment can become an adjective: a set of flat keys.", "PHRASE"],
  ["related meanings", "các nghĩa có liên hệ với nhau", "Flat countryside and flat apartment both suggest one level.", "PHRASE"],
]);

const U92_WORDS = wordList([
  ["collocation", "cách từ thường đi cùng nhau", "Collocation is concerned with words that regularly occur together.", "NOUN"],
  ["the real thing", "hàng thật, đúng bản chất (không giả)", "I prefer the real thing — real football with 11 players.", "PHRASE"],
  ["the genuine article", "hàng chính hãng, không phải hàng nhái", "These trainers are the genuine article.", "PHRASE"],
  ["broad summary", "tóm tắt tổng quát (collocation đúng)", "You can give a broad summary of the report.", "PHRASE"],
  ["great detail", "mô tả chi tiết sâu (collocation đúng)", "She described the scene in great detail.", "PHRASE"],
  ["formidable opponent", "đối thủ đáng gờm", "She faced a formidable opponent in the final.", "PHRASE"],
  ["formidable reputation", "danh tiếng đáng gờm", "The firm has a formidable reputation in the market.", "PHRASE"],
  ["formidable task", "nhiệm vụ khó khăn", "Rebuilding the network was a formidable task.", "PHRASE"],
  ["formidable challenge", "thử thách lớn", "Climate change poses a formidable challenge.", "PHRASE"],
  ["move swiftly", "chuyển nhanh sang chủ đề tiếp theo", "Let's move swiftly on to the next point.", "PHRASE"],
  ["feel strongly about", "cảm thấy mạnh mẽ về điều gì", "It's something I feel strongly about.", "PHRASE"],
  ["remember rightly", "nhớ không lầm", "If I remember rightly, it happened at about 6.30.", "PHRASE"],
  ["utterly", "hoàn toàn, tuyệt đối (thường với tính từ tiêu cực)", "The plan was utterly ridiculous.", "ADVERB"],
  ["raise your hand", "giơ tay (collocation đúng)", "Raise your hand to ask a question.", "PHRASE"],
  ["raise a family", "nuôi dạy con cái", "They worked hard to raise a family.", "PHRASE"],
  ["check out a website", "xem/duyệt một trang web", "You can visit or check out a website.", "PHRASE"],
  ["click on a website", "nhấp vào trang web", "Click on the website link for more details.", "PHRASE"],
  ["typical collocations", "cụm kết hợp điển hình của từ", "Learn any typical collocations when you learn new words.", "PHRASE"],
  ["unpredictable ways", "cách kết hợp khó đoán trước", "Words often collocate in unpredictable ways.", "PHRASE"],
  ["restricted range", "phạm vi hạn chế (tính từ + danh từ)", "Formidable collocates with a restricted range of nouns.", "PHRASE"],
  ["walk too fast", "đi quá nhanh (collocation tự nhiên)", "She always walks too fast for me.", "PHRASE"],
]);

const U93_WORDS = wordList([
  ["metaphor", "ẩn dụ — so sánh gián tiếp qua đặc điểm tương tự", "Metaphor compares something indirectly with something else.", "NOUN"],
  ["be on the ball", "rất tinh ý, sẵn sàng hành động", "You need someone who is on the ball.", "IDIOM"],
  ["keep on a tight rein", "kiểm soát chặt chẽ", "She keeps spending on a tight rein.", "IDIOM"],
  ["in the heart of", "ở trung tâm", "The building is in the heart of the city.", "PHRASE"],
  ["mouth of a river", "cửa sông (nơi sông ra biển)", "The town sits at the mouth of a river.", "PHRASE"],
  ["head of an organisation", "người đứng đầu tổ chức", "She became head of the organisation.", "PHRASE"],
  ["eye for a bargain", "mắt tinh tìm được hàng giá tốt", "She has an eye for a bargain.", "PHRASE"],
  ["keep an eye on", "theo dõi cẩn thận", "Keep a close eye on the accounts.", "PHRASE"],
  ["in safe hands", "được người giỏi phụ trách", "The project is in safe hands.", "PHRASE"],
  ["go hand in hand with", "song hành, gắn liền với", "Rights go hand in hand with responsibilities.", "PHRASE"],
  ["rule of thumb", "quy tắc ước lượng thực tế", "As a rule of thumb, allow an hour per task.", "PHRASE"],
  ["see the light", "hiểu ra, thấy rõ", "After weeks of study, I finally saw the light.", "IDIOM"],
  ["cast light on", "làm sáng tỏ, giúp hiểu rõ hơn", "The letters cast light on his troubled relationship.", "PHRASE"],
  ["bright", "thông minh (ẩn dụ ánh sáng)", "She's a bright student who learns quickly.", "ADJECTIVE"],
  ["dim", "kém thông minh (ẩn dụ ánh sáng mờ)", "He felt dim compared with his clever sister.", "ADJECTIVE"],
  ["blow hot and cold", "lúc nhiệt tình lúc lạnh nhạt", "He blows hot and cold about the plan.", "IDIOM"],
  ["hotheaded", "nóng tính, phản ứng theo cảm xúc", "A hotheaded driver caused the accident.", "ADJECTIVE"],
  ["cold-hearted", "vô tình, thiếu cảm xúc", "Only a cold-hearted person could ignore that.", "ADJECTIVE"],
  ["stream of traffic", "dòng xe liên tục", "There was a constant stream of traffic past the window.", "PHRASE"],
  ["invest time", "đầu tư thời gian (ẩn dụ tiền bạc)", "Invest time now and it will pay dividends later.", "PHRASE"],
  ["pay dividends", "mang lại lợi ích sau này", "Hard work will pay dividends in the long run.", "PHRASE"],
  ["advertising campaign", "chiến dịch quảng cáo (ẩn dụ quân sự)", "The company launched an advertising campaign.", "PHRASE"],
  ["marketing strategy", "chiến lược marketing", "They reworked their marketing strategy.", "PHRASE"],
]);

const U94_WORDS = wordList([
  ["worked like a dream", "diễn ra hoàn hảo như mơ", "The plan worked like a dream.", "IDIOM"],
  ["went like clockwork", "trơn tru, không trục trặc", "Everything went like clockwork on the day.", "IDIOM"],
  ["up and running", "đã vận hành ổn định", "The new system is up and running.", "PHRASE"],
  ["falling into place", "dần ổn, sắp xếp được", "At last everything is falling into place.", "PHRASE"],
  ["looking up", "triển vọng tích cực", "Things are looking up at work.", "PHRASE"],
  ["That's all we need", "tin xấu thêm vào lúc khó khăn", "Oh no! That's all we need!", "PHRASE"],
  ["the last thing I wanted to hear", "tin tồi tệ nhất có thể nghe", "That's the last thing I wanted to hear!", "PHRASE"],
  ["like a bad dream", "như cơn ác mộng", "This is like a bad dream!", "PHRASE"],
  ["worst nightmare", "cơn ác mộng tồi tệ nhất", "Traffic jams are my worst nightmare.", "PHRASE"],
  ["What a pain!", "phiền phức quá! (informal)", "The printer broke again — what a pain!", "PHRASE"],
  ["threw me completely", "làm tôi bối rối, không biết trả lời", "Her sudden question threw me completely.", "PHRASE"],
  ["complete shambles", "hỗn loạn hoàn toàn", "The meeting was a complete shambles.", "PHRASE"],
  ["a mystery to me", "điều tôi không thể hiểu", "It's a mystery to me how they found out.", "PHRASE"],
  ["got our wires crossed", "hiểu nhầm nhau", "We must have got our wires crossed about the time.", "PHRASE"],
  ["I'm not with you", "tôi không theo kịp ý bạn", "Sorry, I'm not with you — can you explain?", "PHRASE"],
  ["You've lost me there", "bạn làm tôi bối rối rồi", "You've lost me there; what do you mean?", "PHRASE"],
  ["on cloud nine", "cực kỳ hạnh phúc", "She's been on cloud nine since the news.", "IDIOM"],
  ["in your element", "ở đúng môi trường phù hợp", "He's in his element on stage.", "PHRASE"],
  ["made for", "sinh ra để làm việc này", "She was made for teaching.", "PHRASE"],
  ["fed up to the back teeth", "chán ngấy, thất vọng cực độ", "I'm fed up to the back teeth with delays.", "PHRASE"],
  ["down in the dumps", "buồn bã, chán nản", "He's been down in the dumps all week.", "IDIOM"],
  ["down in the mouth", "vẻ mặt buồn, chán nản", "She looked down in the mouth after the result.", "PHRASE"],
]);

const U95_WORDS = wordList([
  ["come across", "tình cờ gặp; tạo ấn tượng", "I came across an old photo in the drawer.", "VERB"],
  ["come over as", "tạo ấn tượng là", "He can come over as unfriendly at first.", "PHRASE"],
  ["come off", "diễn ra thành công", "I hope our plans to visit Russia come off.", "VERB"],
  ["come over from", "đến từ nơi khác", "Sandro's family came over from Italy for the wedding.", "PHRASE"],
  ["what came over me", "điều gì khiến tôi hành xử như vậy", "I don't know what came over me.", "PHRASE"],
  ["come under criticism", "bị chỉ trích", "The proposal has come under a lot of criticism.", "PHRASE"],
  ["come up", "phát sinh bất ngờ", "If the opportunity comes up, you must take it.", "VERB"],
  ["come up against", "gặp trở ngại", "Our plan came up against some obstacles.", "PHRASE"],
  ["stay on", "ở lại (trường, công việc)", "Selina decided to stay on and do a Master's.", "VERB"],
  ["dwell on", "bám víu suy nghĩ (thường tiêu cực)", "Try not to dwell on the past.", "VERB"],
  ["catch on", "trở nên phổ biến", "I didn't expect platform shoes to catch on.", "VERB"],
  ["go on about", "cứ nói mãi về", "I wish she'd stop going on about her new car.", "PHRASE"],
  ["press on regardless", "tiếp tục bất chấp khó khăn", "The climbers pressed on regardless of the weather.", "PHRASE"],
  ["brush up on", "ôn lại kiến thức đã học", "I need to brush up on my computer skills.", "PHRASE"],
  ["laid off", "sa thải (tạm thời/vĩnh viễn)", "The company laid off half its staff.", "VERB"],
  ["called off", "hủy bỏ", "Tomorrow's meeting has been called off.", "VERB"],
  ["thrown himself into", "dốc sức vào việc mới", "Sasha has thrown himself into his new job.", "PHRASE"],
  ["settle in", "làm quen, cảm thấy thoải mái ở nơi mới", "It took me a few weeks to settle in.", "VERB"],
  ["put together", "biên soạn từ nhiều nguồn", "It took ages to put together the report.", "PHRASE"],
  ["rush into a decision", "quyết định vội vàng", "Don't rush into a decision you'll regret.", "PHRASE"],
  ["put forward a plan", "đề xuất kế hoạch", "Instead of put forward a plan, you can propose one.", "PHRASE"],
  ["propose a plan", "đề xuất kế hoạch (một từ thay phrasal verb)", "She proposed a plan to cut costs.", "VERB"],
  ["make a hasty decision", "đưa ra quyết định vội vã", "Instead of rush into a decision, make a hasty decision is clearer.", "PHRASE"],
]);

const U96_WORDS = wordList([
  ["connotation", "hàm nghĩa, liên tưởng đi kèm từ", "Connotation is about associations beyond literal meaning.", "NOUN"],
  ["word associations", "liên tưởng gắn với một từ", "Writers often make use of word associations.", "PHRASE"],
  ["literal meaning", "nghĩa đen, nghĩa trực tiếp", "Think about the literal meaning first.", "PHRASE"],
  ["primary meaning", "nghĩa cơ bản, chính", "Your knowledge of primary meanings will help.", "PHRASE"],
  ["draw on associations", "khai thác liên tưởng văn hóa", "The advert draws on associations of Paris with glamour.", "PHRASE"],
  ["Paris look", "phong cách thời trang Paris", "Would you like to have that Paris look?", "PHRASE"],
  ["cowboy builders", "thợ xây làm ẩu, không đáng tin", "We hired cowboy builders and regretted it.", "PHRASE"],
  ["shark", "kẻ hung hăng, lợi dụng người khác (ẩn dụ)", "They're all sharks in that garage.", "NOUN"],
  ["scar on the landscape", "công trình phá hỏng cảnh quan", "The office block is a scar on the landscape.", "PHRASE"],
  ["real diamond", "người quý giá, tốt bụng (ẩn dụ)", "Emma's a real diamond.", "PHRASE"],
  ["dove", "người theo đường hòa bình (ẩn dụ)", "The journalist called her a dove.", "NOUN"],
  ["hawk", "người cứng rắn, hiếu chiến (ẩn dụ)", "A more aggressive politician might be called a hawk.", "NOUN"],
  ["a dog's life", "cuộc sống khổ cực, bất hạnh", "He leads a dog's life working two jobs.", "IDIOM"],
  ["personal associations", "liên tưởng cá nhân riêng", "Remember your personal associations as you learn words.", "PHRASE"],
  ["shared associations", "liên tưởng chung trong cộng đồng", "Dove and hawk have shared associations for most speakers.", "PHRASE"],
  ["faithfulness", "sự trung thành (liên tưởng với chó)", "The most shared association of dog is faithfulness.", "NOUN"],
  ["aggressive reputation", "danh tiếng hung hăng", "Sharks have an aggressive reputation.", "PHRASE"],
  ["unspoilt", "chưa bị hỏng hại (cảnh quan)", "A scar marks something that was once unspoilt.", "ADJECTIVE"],
  ["glamour and style", "sự lộng lẫy và phong cách", "Paris is associated with glamour and style.", "PHRASE"],
  ["not careful or trustworthy", "không cẩn thận hoặc không đáng tin", "Cowboy builders are not careful or trustworthy.", "PHRASE"],
  ["high opinion", "đánh giá cao", "A diamond connotation shows a high opinion of someone.", "PHRASE"],
  ["vary from area to area", "khác nhau theo vùng", "Some associations vary from one geographical area to another.", "PHRASE"],
]);

const U97_WORDS = wordList([
  ["register", "mức độ trang trọng của ngôn ngữ", "Register is the overall tone of a text or conversation.", "NOUN"],
  ["other half", "nửa kia (vợ/chồng, informal)", "Is your other half not with you today?", "NOUN"],
  ["bloke", "anh chàng (Anh, informal)", "Rick's a really nice bloke.", "NOUN"],
  ["converse", "trò chuyện (formal)", "She is able to converse with everyone.", "VERB"],
  ["the box", "tivi (informal)", "What's on the box tonight?", "NOUN"],
  ["telly", "tivi (Anh, informal)", "I haven't watched the telly all week.", "NOUN"],
  ["spectacles", "kính (formal)", "He wears spectacles for reading.", "NOUN"],
  ["specs", "kính (informal)", "I left my specs on the desk.", "NOUN"],
  ["garments", "quần áo (formal)", "The shop sells outdoor garments.", "NOUN"],
  ["gear", "đồ, quần áo (informal)", "Pack your walking gear for the trip.", "NOUN"],
  ["employ", "sử dụng, thuê (formal)", "The firm employs over 200 people.", "VERB"],
  ["utilise", "sử dụng (formal)", "We utilise every available resource.", "VERB"],
  ["endeavour", "cố gắng (formal)", "We will endeavour to resolve the issue.", "VERB"],
  ["have a stab at", "thử làm (informal)", "I'll have a stab at fixing the printer.", "PHRASE"],
  ["subsequently", "sau đó (văn viết)", "The police found clues. Subsequently, three were arrested.", "ADVERB"],
  ["in sum", "tóm lại (văn viết)", "In sum, most English adverbs end in -ly.", "PHRASE"],
  ["whatsisname", "ông kia, bà kia (quên tên, nói)", "I met whatsisname at the party.", "NOUN"],
  ["thingy", "cái kia (quên tên, nói)", "Give me that thingy — yes, the bottle opener.", "NOUN"],
  ["mind you", "tuy nhiên (marker nói)", "He's a good actor. Mind you, he went to drama college.", "PHRASE"],
  ["now then", "nào, chú ý (marker nói)", "Now then, is everybody's luggage here?", "PHRASE"],
  ["archaic", "cổ, lỗi thời", "Some words may be correct but sound archaic.", "ADJECTIVE"],
  ["old-fashioned", "lỗi thời, kiểu cũ", "Wireless for radio sounds old-fashioned today.", "ADJECTIVE"],
  ["degrees of formality", "các mức độ trang trọng", "Words can be arranged into degrees of formality.", "PHRASE"],
  ["spoken or written", "dùng nhiều khi nói hoặc khi viết", "Note if a word is more associated with speech or writing.", "PHRASE"],
]);

const U98_WORDS = wordList([
  ["kitty-corner", "chéo đối diện (Mỹ, informal)", "The office is kitty-corner to the gas station.", "ADJECTIVE"],
  ["crosswalk", "vạch sang đường (Mỹ)", "Always use the crosswalk to cross the street.", "NOUN"],
  ["trail", "lối mòn (Mỹ)", "There's a trail that leads down to the creek.", "NOUN"],
  ["creek", "suối nhỏ (Mỹ)", "We followed the creek to the lake.", "NOUN"],
  ["Interstate", "xa lộ liên bang (Mỹ)", "Take the Interstate north for about 20 miles.", "NOUN"],
  ["intersection", "ngã tư (Mỹ)", "After the intersection, look for the airport sign.", "NOUN"],
  ["shopping cart", "xe đẩy hàng (Mỹ)", "I hit a shopping cart in the parking lot.", "NOUN"],
  ["parking lot", "bãi đỗ xe (Mỹ)", "The parking lot was full by noon.", "NOUN"],
  ["backing up", "lùi xe (Mỹ)", "I was backing up when I heard a bump.", "PHRASE"],
  ["overpass", "cầu vượt (Mỹ)", "Look for the overpass, then take the next exit.", "NOUN"],
  ["freshman", "sinh viên năm nhất (Mỹ)", "Are you a freshman or a sophomore?", "NOUN"],
  ["sophomore", "sinh viên năm hai (Mỹ)", "No, I'm a sophomore this year.", "NOUN"],
  ["junior", "sinh viên năm ba (Mỹ)", "Most of my friends are juniors.", "NOUN"],
  ["fresher", "sinh viên năm nhất (Anh)", "Are you a fresher or second year?", "NOUN"],
  ["major in", "chuyên ngành (Mỹ)", "She's majoring in French.", "VERB"],
  ["honours degree", "bằng danh dự (Anh)", "She's doing a French honours degree.", "PHRASE"],
  ["elementary school", "trường tiểu học (Mỹ)", "I want to be an elementary school teacher.", "PHRASE"],
  ["primary school", "trường tiểu học (Anh)", "I want to be a primary school teacher.", "PHRASE"],
  ["high school", "trường trung học (Mỹ)", "My years in high school were not happy.", "PHRASE"],
  ["secondary school", "trường trung học (Anh)", "My years in secondary school were hard.", "PHRASE"],
  ["faucet", "vòi nước (Mỹ)", "The faucet in the kitchen never stops dripping.", "NOUN"],
  ["skillet", "chảo rán (Mỹ)", "I fried the fish in a skillet.", "NOUN"],
  ["dumpster", "thùng rác lớn (Mỹ)", "We need a dumpster for all this old stuff.", "NOUN"],
  ["gas station", "trạm xăng (Mỹ)", "The car rental office is near the gas station.", "PHRASE"],
]);

const U99_WORDS = wordList([
  ["gender-neutral language", "ngôn ngữ trung tính giới", "We take care to use gender-neutral language at work.", "PHRASE"],
  ["chairperson", "chủ tịch (trung tính giới)", "Chairman is often replaced by chair or chairperson.", "NOUN"],
  ["spokesperson", "người phát ngôn (trung tính)", "The spokesperson addressed the press.", "NOUN"],
  ["firefighter", "lính cứu hỏa (trung tính)", "Fireman is now usually firefighter.", "NOUN"],
  ["police officer", "cảnh sát (trung tính)", "Policeman has become police officer.", "NOUN"],
  ["flight attendant", "tiếp viên hàng không (trung tính)", "Air hostess is replaced by flight attendant.", "NOUN"],
  ["sales assistant", "nhân viên bán hàng (trung tính)", "Salesman is often sales assistant today.", "NOUN"],
  ["man-made", "do con người tạo ra (cũ)", "Man-made is often replaced by artificial.", "ADJECTIVE"],
  ["artificial", "nhân tạo (trung tính)", "The lake is artificial, not natural.", "ADJECTIVE"],
  ["mankind", "loài người (cũ)", "Mankind is often replaced by the human race.", "NOUN"],
  ["human race", "loài người (trung tính)", "We must protect the human race and the planet.", "PHRASE"],
  ["to staff", "bố trí nhân sự (thay to man)", "Volunteers will staff the information desk.", "VERB"],
  ["man in the street", "người bình thường (đang tranh luận)", "Man in the street could become person in the street.", "PHRASE"],
  ["manhandle", "xử lý thô bạo (man không còn nghĩa nam)", "Do not manhandle the equipment.", "VERB"],
  ["Ms", "cách xưng hô trung tính (thay Miss/Mrs)", "Ms avoids revealing marital status.", "NOUN"],
  ["masculine", "đặc tính truyền thống gán cho nam", "He showed masculine pride after the win.", "ADJECTIVE"],
  ["feminine", "đặc tính truyền thống gán cho nữ", "She has great feminine charm.", "ADJECTIVE"],
  ["you guys", "các bạn (Mỹ, nam và nữ)", "Do any of you guys fancy going out for pizza?", "PHRASE"],
  ["girlfriend", "bạn nữ (không phải người yêu)", "I'm meeting a few girlfriends this evening.", "NOUN"],
  ["girlie evening", "buổi tối chỉ phụ nữ (quần áo, trang điểm)", "They're having a girlie evening at home.", "PHRASE"],
  ["lad", "chàng trai (Anh, informal)", "He's having a night out with the lads.", "NOUN"],
  ["laddish", "kiểu trai trẻ ồn ào, uống nhiều", "I can't stand that kind of laddish behaviour.", "ADJECTIVE"],
  ["macho", "đàn ông cứng rắn, không khóc", "He refuses to cry — it would spoil his macho image.", "ADJECTIVE"],
  ["male and female", "phân loại giới tính (sinh học)", "Male and female bees have different roles.", "PHRASE"],
]);

const U100_WORDS = wordList([
  ["hits the headlines", "trở thành tin nóng trên báo", "The scandal hit the headlines overnight.", "PHRASE"],
  ["tabloid", "báo lá cải, tin ngắn gây sốc", "Tabloids often use short, dramatic reports.", "NOUN"],
  ["headline language", "ngôn ngữ rút gọn trên tiêu đề báo", "Headline language omits articles and auxiliaries.", "PHRASE"],
  ["present simple for immediacy", "thì hiện tại làm tin tức sống động", "Headlines use present simple instead of past.", "PHRASE"],
  ["ambiguous", "mơ hồ, có thể hiểu nhiều cách", "Headline words are often ambiguous.", "ADJECTIVE"],
  ["cloud storage", "lưu trữ đám mây (ẩn dụ trong headline)", "Cloud dangers can mean internet storage, not weather.", "PHRASE"],
  ["dramatic associations", "từ gợi kịch tính", "Words like danger attract readers.", "PHRASE"],
  ["TV star", "ngôi sao truyền hình", "Tabloids often feature celebrities like TV stars.", "PHRASE"],
  ["alliteration", "lặp âm đầu (Tragic Target)", "Alliteration makes headlines memorable.", "NOUN"],
  ["gunman", "kẻ bắn súng (headline)", "TV STAR TRAGIC TARGET FOR CRAZED GUNMAN.", "NOUN"],
  ["crazed", "mất trí, điên cuồng (headline)", "A crazed gunman attacked the actor.", "ADJECTIVE"],
  ["thugs", "kẻ côn đồ (headline)", "EU acts to crush terror of thugs.", "NOUN"],
  ["yobs", "kẻ lưu manh (Anh, headline)", "Crackdown on soccer yobs.", "NOUN"],
  ["louts", "kẻ hooligan (headline)", "Crackdown on soccer louts.", "NOUN"],
  ["besieged", "bị vây hãm (ẩn dụ quân sự)", "Palace besieged by journalists.", "ADJECTIVE"],
  ["crackdown", "đợt trấn áp mạnh", "Crackdown on soccer louts.", "NOUN"],
  ["reign of terror", "thời kỳ khủng bố", "Rain of terror plays on reign of terror.", "PHRASE"],
  ["Rain of terror", "wordplay: mưa + reign of terror", "A landslide story was headlined Rain of terror.", "PHRASE"],
  ["shooting star", "sao băng; wordplay với cầu thủ Moon", "Moon becomes shooting star after scoring.", "PHRASE"],
  ["play on words", "chơi chữ trên headline", "Many headlines attract attention by playing on words.", "PHRASE"],
  ["militaristic words", "từ ngữ mang sắc quân sự", "Violent words make stories seem more dramatic.", "PHRASE"],
  ["rips through", "quét qua phá hoại (headline)", "Typhoon rips through town.", "PHRASE"],
  ["crush terror", "đàn áp khủng bố (headline)", "EU acts to crush terror of thugs.", "PHRASE"],
]);

const U101_WORDS = wordList([
  ["red tape", "thủ tục hành chính rườm rà", "Students struggle with red tape when applying for loans.", "NOUN"],
  ["bureaucratic language", "ngôn ngữ quan liêu, khó hiểu", "Official forms use bureaucratic language.", "PHRASE"],
  ["eligible", "đủ điều kiện", "A student shall not be eligible for a loan if...", "ADJECTIVE"],
  ["attained the age", "đã đạt tuổi (formal)", "He has attained the age of 50 years.", "PHRASE"],
  ["bestowed on", "trao tặng cho (formal)", "An award bestowed on him under the Act.", "PHRASE"],
  ["hereby rejected", "bị từ chối theo văn bản này", "Your request is hereby rejected.", "PHRASE"],
  ["adjoining property", "tài sản liền kề", "The garage adjoining your property.", "PHRASE"],
  ["undersigned", "người ký dưới đây", "Appeals must be submitted to the undersigned.", "NOUN"],
  ["aforementioned", "đã nêu ở trên", "No exceptions to the aforementioned procedure.", "ADJECTIVE"],
  ["commence", "bắt đầu (formal)", "Work will commence in May.", "VERB"],
  ["commencement", "sự bắt đầu (formal)", "Commencement of work is scheduled for May.", "NOUN"],
  ["ceased operations", "ngừng hoạt động (formal)", "The company ceased operations last year.", "PHRASE"],
  ["deceased", "người đã qua đời (formal)", "Property belonging to the deceased.", "ADJECTIVE"],
  ["next of kin", "người thân gần nhất", "Property will be returned to the next of kin.", "PHRASE"],
  ["in the event of", "trong trường hợp (formal)", "In the event of fire, evacuate immediately.", "PHRASE"],
  ["endeavour to", "cố gắng (formal)", "Tenants must endeavour to keep areas tidy.", "PHRASE"],
  ["facilitate", "tạo điều kiện thuận lợi (formal)", "The works will facilitate movement of traffic.", "VERB"],
  ["proceed to the next phase", "chuyển sang giai đoạn tiếp (formal)", "The project will proceed to the next phase.", "PHRASE"],
  ["rectify", "sửa chữa, khắc phục (formal)", "We are attempting to rectify the situation.", "VERB"],
  ["will be resumed", "sẽ được tiếp tục (passive formal)", "Normal service will be resumed as soon as possible.", "PHRASE"],
  ["acknowledge receipt", "xác nhận đã nhận (thư công vụ)", "Please acknowledge receipt of payment.", "PHRASE"],
  ["with the compliments of", "kèm lời chào từ công ty", "With the compliments of Smith and Co.", "PHRASE"],
  ["at your earliest convenience", "sớm nhất có thể (formal)", "I would be grateful for a reply at your earliest convenience.", "PHRASE"],
  ["in respect of", "liên quan đến, về (formal)", "I enclose payment in respect of your invoice.", "PHRASE"],
  ["with regard to", "về vấn đề (formal)", "I am writing with regard to your advertisement.", "PHRASE"],
  ["clarification", "lời giải thích thêm (formal)", "Contact us if further clarification is required.", "NOUN"],
]);

export const EVIU_ADVANCED_UNITS_91_101: readonly VocabularyUnit[] = [
  advancedUnit(91, {
    introVi:
      "Unit 91 giới thiệu đa nghĩa (polysemy): cùng một từ như fair, flat, capital và mean có thể mang nghĩa hoàn toàn khác nhau tùy ngữ cảnh. Bạn sẽ nhận biết homograph và chọn nét nghĩa đúng.",
    structureSections: [
      { label: "Polysemy and homographs", wordCount: 4 },
      { label: "Fair, flat, capital, mean", wordCount: 14 },
      { label: "Using context", wordCount: 4 },
    ],
    collocationHtml: `${purple("in five minutes flat")}, ${purple("capital punishment")}, ${purple("mean temperature")} và ${purple("book fair")} minh họa cách một từ đổi nghĩa theo ngữ cảnh.`,
    mistakeHtml: `Đừng dịch ${bold("fair")}, ${bold("flat")}, ${bold("capital")} hay ${bold("mean")} bằng một từ Việt duy nhất — luôn đọc cả câu. ${bold("Homograph")} là cùng chính tả; ${bold("polysemy")} là nhiều nghĩa liên quan hoặc không.`,
    principles: [
      {
        title: "Đa nghĩa và homograph",
        body: `${purple("polysemy")} là hiện tượng một từ có nhiều nghĩa. ${purple("homograph")} là cùng chính tả nhưng nghĩa không liên quan — ví dụ ${purple("book fair")} và thời tiết ${purple("fair")}.`,
        examples: [
          ex("You probably need a different word to translate fair in each sentence.", "Mỗi câu có thể cần từ dịch fair khác nhau."),
          ex("Sometimes meanings are clearly related; sometimes there is no connection.", "Đôi khi các nghĩa liên quan; đôi khi hoàn toàn tách rời."),
        ],
      },
      {
        title: "Bốn từ mẫu trong sách",
        body: `${purple("fair")}: công bằng, hội chợ, thời tiết đẹp, da sáng, điểm khá. ${purple("flat")}: căn hộ, đất bằng, phí cố định, nốt giáng, ${purple("in five minutes flat")}. ${purple("capital")}: chữ hoa, thủ đô, vốn, ${purple("capital punishment")}. ${purple("mean")}: nghĩa là, cố ý, keo kiện, trung bình.`,
        examples: [
          ex("He's far too mean to buy her flowers.", "Anh ấy keo kiệm quá, không chịu mua hoa cho cô."),
          ex("You need plenty of capital to open a restaurant.", "Mở nhà hàng cần nhiều vốn."),
        ],
      },
      {
        title: "Ngữ cảnh và từ loại",
        body: `${purple("context")} thường làm rõ nghĩa. Từ có thể đổi ${purple("parts of speech")} — ${purple("flat")} (căn hộ) thành tính từ trong ${purple("set of flat keys")}. Học nhiều nghĩa \"một giá nhiều món\".`,
        examples: [
          ex("Context usually makes the intended meaning absolutely clear.", "Ngữ cảnh thường làm nghĩa đúng trở nên rõ ràng."),
          ex("Learning the range of meanings helps you understand jokes.", "Biết dải nghĩa giúp hiểu đùa trong tiếng Anh."),
        ],
      },
    ],
    words: U91_WORDS,
    exercises: [
      fillBlank(
        91,
        1,
        "Linguists use the term ____ for words with more than one meaning.",
        "polysemy",
        [
          { key: "a", label: "polysemy" },
          { key: "b", label: "collocation" },
          { key: "c", label: "register" },
          { key: "d", label: "metaphor" },
        ],
        "a",
      ),
      mcq(
        91,
        2,
        "Words with the same spelling but unrelated meanings are called:",
        [
          { key: "a", label: "homographs" },
          { key: "b", label: "synonyms" },
          { key: "c", label: "collocations" },
          { key: "d", label: "headlines" },
        ],
        "a",
      ),
      fillBlank(
        91,
        3,
        "She finished the exercise in five minutes ____.",
        "flat",
        [
          { key: "a", label: "flat" },
          { key: "b", label: "fair" },
          { key: "c", label: "mean" },
          { key: "d", label: "capital" },
        ],
        "a",
      ),
      fillBlank(
        91,
        4,
        "____ punishment has been abolished in many countries.",
        "Capital",
        [
          { key: "a", label: "Capital" },
          { key: "b", label: "Fair" },
          { key: "c", label: "Flat" },
          { key: "d", label: "Mean" },
        ],
        "a",
      ),
      mcq(
        91,
        5,
        "\"I didn't mean to hurt you\" — mean ở đây nghĩa là gì?",
        [
          { key: "a", label: "Có ý định / cố ý" },
          { key: "b", label: "Keo kiệt" },
          { key: "c", label: "Nghĩa là gì (định nghĩa)" },
          { key: "d", label: "Nhiệt độ trung bình" },
        ],
        "a",
      ),
      fillBlank(
        91,
        6,
        "The ____ of a word with multiple meanings will usually make the sense clear.",
        "context",
        [
          { key: "a", label: "context" },
          { key: "b", label: "headline" },
          { key: "c", label: "register" },
          { key: "d", label: "red tape" },
        ],
        "a",
      ),
    ],
  }),

  advancedUnit(92, {
    introVi:
      "Unit 92 dạy collocation — từ nào thường đi với từ nào một cách tự nhiên. Bạn sẽ tránh lỗi *wide summary* hay *lift your hand* và học các cụm như the genuine article hay move swiftly.",
    structureSections: [
      { label: "Adjective + noun", wordCount: 10 },
      { label: "Verb + adverb and adverb + adjective", wordCount: 6 },
      { label: "Verb + object", wordCount: 6 },
    ],
    collocationHtml: `${purple("the genuine article")}, ${purple("broad summary")}, ${purple("formidable opponent")} và ${purple("feel strongly about")} là collocations cần học nguyên cụm.`,
    mistakeHtml: `Nói ${bold("broad summary")}, không *wide summary*; ${bold("great detail")}, không *big detail*. ${bold("Raise")} your hand, không *lift*. ${bold("Remember rightly")}, không *remember perfectly*.`,
    principles: [
      {
        title: "Tính từ + danh từ",
        body: `Danh từ thường có tính từ điển hình: ${purple("the real thing")} vs ${purple("the genuine article")}; ${purple("broad summary")}; ${purple("great detail")}. ${purple("formidable")} đi với ${purple("opponent")}, reputation, task, challenge.`,
        examples: [
          ex("These trainers are the genuine article.", "Đôi giày này là hàng chính hãng."),
          ex("Climate change poses a formidable challenge.", "Biến đổi khí hậu là thách thức lớn."),
        ],
      },
      {
        title: "Động từ + trạng từ",
        body: `${purple("move swiftly")} on to the next point; ${purple("feel strongly about")} something; ${purple("remember rightly")}. ${purple("utterly")} thường đứng trước tính từ tiêu cực: utterly ridiculous, utterly useless.`,
        examples: [
          ex("Let's move swiftly on to the next point.", "Chúng ta chuyển nhanh sang điểm tiếp theo."),
          ex("It's something I feel strongly about.", "Đó là điều tôi cảm thấy rất mạnh mẽ."),
        ],
      },
      {
        title: "Động từ + tân ngữ",
        body: `${purple("raise your hand")}; ${purple("raise a family")}. Với website: visit, go to, click on, ${purple("check out a website")}. Collocation thường ${purple("unpredictable ways")} — học ${purple("typical collocations")} cùng từ mới.`,
        examples: [
          ex("Raise your hand to ask a question.", "Giơ tay để hỏi."),
          ex("Words often collocate in unpredictable ways.", "Từ thường kết hợp theo cách khó đoán."),
        ],
      },
    ],
    words: U92_WORDS,
    exercises: [
      fillBlank(
        92,
        1,
        "These trainers are the ____ — not cheap copies.",
        "genuine article",
        [
          { key: "a", label: "genuine article" },
          { key: "b", label: "real summary" },
          { key: "c", label: "wide detail" },
          { key: "d", label: "big opponent" },
        ],
        "a",
      ),
      fillBlank(
        92,
        2,
        "You can give a ____ summary of the findings.",
        "broad",
        [
          { key: "a", label: "broad" },
          { key: "b", label: "wide" },
          { key: "c", label: "big" },
          { key: "d", label: "strong" },
        ],
        "a",
      ),
      mcq(
        92,
        3,
        "Collocation tự nhiên để hỏi trong lớp:",
        [
          { key: "a", label: "raise your hand" },
          { key: "b", label: "lift your hand" },
          { key: "c", label: "hold your hand" },
          { key: "d", label: "push your hand" },
        ],
        "a",
      ),
      fillBlank(
        92,
        4,
        "If I remember ____, it happened at about 6.30.",
        "rightly",
        [
          { key: "a", label: "rightly" },
          { key: "b", label: "perfectly" },
          { key: "c", label: "strongly" },
          { key: "d", label: "swiftly" },
        ],
        "a",
      ),
      {
        type: "match",
        id: "ex-92-match-5",
        instruction: "Ghép collocation với nghĩa tiếng Việt",
        pairs: [
          { left: "move swiftly", right: "chuyển nhanh sang chủ đề tiếp" },
          { left: "feel strongly about", right: "cảm thấy mạnh mẽ về điều gì" },
          { left: "formidable task", right: "nhiệm vụ khó khăn" },
          { left: "check out a website", right: "xem/duyệt trang web" },
          { left: "the real thing", right: "hàng thật, đúng bản chất" },
        ],
      },
      mcq(
        92,
        6,
        "Utterly thường đi với loại tính từ nào?",
        [
          { key: "a", label: "Tính từ tiêu cực hoặc cực đoan" },
          { key: "b", label: "Chỉ tính từ tích cực" },
          { key: "c", label: "Chỉ danh từ" },
          { key: "d", label: "Chỉ động từ" },
        ],
        "a",
      ),
    ],
  }),

  advancedUnit(93, {
    introVi:
      "Unit 93 khám phá metaphor — dùng từ theo nghĩa trừu tượng: thành phố như rừng, người như ánh sáng, thời gian như tiền. Bạn sẽ nhận ra ẩn dụ trong idiom và ngôn ngữ hàng ngày.",
    structureSections: [
      { label: "Idiom metaphors", wordCount: 10 },
      { label: "Body and common concepts", wordCount: 8 },
      { label: "Light, heat, time and business", wordCount: 6 },
    ],
    collocationHtml: `${purple("see the light")}, ${purple("cast light on")}, ${purple("go hand in hand with")} và ${purple("keep on a tight rein")} là ẩn dụ thường gặp.`,
    mistakeHtml: `${bold("See the light")} = hiểu ra, không phải \"nhìn thấy đèn\". ${bold("Rule of thumb")} = quy tắc ước lượng, không liên quan ngón tay cái theo nghĩa đen.`,
    principles: [
      {
        title: "Ẩn dụ và thành ngữ",
        body: `${purple("metaphor")} so sánh gián tiếp: thành phố như rừng; người ${purple("lights up")} cuộc đời. Idiom như ${purple("be on the ball")} hay ${purple("keep on a tight rein")} đều mang tính ẩn dụ.`,
        examples: [
          ex("If we call a city a jungle, we suggest it is wild and dangerous.", "Gọi thành phố là rừng gợi sự hoang dã, nguy hiểm."),
          ex("She keeps spending on a tight rein.", "Cô ấy kiểm soát chi tiêu rất chặt."),
        ],
      },
      {
        title: "Ẩn dụ cơ thể và không gian",
        body: `${purple("in the heart of")} the city; ${purple("mouth of a river")}; ${purple("head of an organisation")}. ${purple("eye for a bargain")}; ${purple("keep an eye on")}; ${purple("in safe hands")}; ${purple("go hand in hand with")}.`,
        examples: [
          ex("Rights go hand in hand with responsibilities.", "Quyền lợi song hành với trách nhiệm."),
          ex("The discovery cast light on his troubled relationship.", "Phát hiện làm sáng tỏ mối quan hệ rắc rối."),
        ],
      },
      {
        title: "Khái niệm ẩn dụ phổ biến",
        body: `Trí tuệ = ánh sáng: ${purple("bright")}, ${purple("dim")}, ${purple("see the light")}. Cảm xúc = nhiệt: ${purple("blow hot and cold")}, ${purple("hotheaded")}, ${purple("cold-hearted")}. Thời gian = tiền: ${purple("invest time")}, ${purple("pay dividends")}. Kinh doanh = quân sự: ${purple("advertising campaign")}, ${purple("marketing strategy")}.`,
        examples: [
          ex("Invest time now and it will pay dividends later.", "Đầu tư thời gian bây giờ sẽ có lợi sau."),
          ex("There was a constant stream of traffic past the window.", "Dòng xe chảy liên tục qua cửa sổ."),
        ],
      },
    ],
    words: U93_WORDS,
    exercises: [
      fillBlank(
        93,
        1,
        "After weeks of confusion, I finally ____.",
        "saw the light",
        [
          { key: "a", label: "saw the light" },
          { key: "b", label: "cast light on" },
          { key: "c", label: "blew hot and cold" },
          { key: "d", label: "kept on a tight rein" },
        ],
        "a",
      ),
      mcq(
        93,
        2,
        "\"Go hand in hand with\" nghĩa là gì?",
        [
          { key: "a", label: "Song hành, gắn liền với nhau" },
          { key: "b", label: "Bắt tay thỏa thuận" },
          { key: "c", label: "Đi cạnh nhau trên phố" },
          { key: "d", label: "Giữ im lặng" },
        ],
        "a",
      ),
      fillBlank(
        93,
        3,
        "She has an ____ for a bargain.",
        "eye",
        [
          { key: "a", label: "eye" },
          { key: "b", label: "hand" },
          { key: "c", label: "head" },
          { key: "d", label: "mouth" },
        ],
        "a",
      ),
      fillBlank(
        93,
        4,
        "Hard work will ____ in the long run.",
        "pay dividends",
        [
          { key: "a", label: "pay dividends" },
          { key: "b", label: "cast light on" },
          { key: "c", label: "blow hot and cold" },
          { key: "d", label: "keep an eye on" },
        ],
        "a",
      ),
      mcq(
        93,
        5,
        "Calling someone \"cold-hearted\" uses metaphor of:",
        [
          { key: "a", label: "Nhiệt độ / cảm xúc" },
          { key: "b", label: "Ánh sáng / trí tuệ" },
          { key: "c", label: "Tiền bạc / thời gian" },
          { key: "d", label: "Nước / giao thông" },
        ],
        "a",
      ),
      fillBlank(
        93,
        6,
        "The company launched an advertising ____.",
        "campaign",
        [
          { key: "a", label: "campaign" },
          { key: "b", label: "rein" },
          { key: "c", label: "thumb" },
          { key: "d", label: "stream" },
        ],
        "a",
      ),
    ],
  }),

  advancedUnit(94, {
    introVi:
      "Unit 94 tập trung idiom đời thường: khi mọi việc suôn sẻ hay trục trặc, khi bối rối, vui mừng hay chán nản. Bạn sẽ phản ứng tự nhiên trong hội thoại tiếng Anh.",
    structureSections: [
      { label: "When things go right", wordCount: 5 },
      { label: "When things go wrong", wordCount: 8 },
      { label: "Confusion and feelings", wordCount: 9 },
    ],
    collocationHtml: `${purple("worked like a dream")}, ${purple("got our wires crossed")}, ${purple("fed up to the back teeth")} và ${purple("on cloud nine")} là idiom giao tiếp thực tế.`,
    mistakeHtml: `${bold("That's all we need")} dùng khi tin xấu thêm — không phải nghĩa đen \"đó là tất cả\". ${bold("Shambles")} = hỗn loạn; khác ${bold("nightmare")} (ác mộng).`,
    principles: [
      {
        title: "Khi mọi việc thuận lợi",
        body: `${purple("worked like a dream")}; ${purple("went like clockwork")}; ${purple("up and running")}; ${purple("falling into place")}; ${purple("looking up")} — mô tả kế hoạch thành công và triển vọng tích cực.`,
        examples: [
          ex("The launch went like clockwork.", "Buổi ra mắt diễn ra trơn tru."),
          ex("At last everything is falling into place.", "Cuối cùng mọi thứ cũng ổn."),
        ],
      },
      {
        title: "Khi có vấn đề",
        body: `${purple("That's all we need")}; ${purple("the last thing I wanted to hear")}; ${purple("like a bad dream")}; ${purple("worst nightmare")}; ${purple("What a pain!")} — phản ứng khi tin xấu hoặc phiền phức.`,
        examples: [
          ex("Oh no! That's all we needed!", "Ôi không! Tin xấu thêm vào lúc này!"),
          ex("The printer broke again — what a pain!", "Máy in hỏng lại — phiền quá!"),
        ],
      },
      {
        title: "Bối rối và cảm xúc",
        body: `${purple("threw me completely")}; ${purple("complete shambles")}; ${purple("a mystery to me")}; ${purple("got our wires crossed")}; ${purple("I'm not with you")}. Vui: ${purple("on cloud nine")}, ${purple("in your element")}. Buồn: ${purple("fed up to the back teeth")}, ${purple("down in the dumps")}.`,
        examples: [
          ex("Her sudden question threw me completely.", "Câu hỏi bất ngờ khiến tôi bối rối."),
          ex("I'm fed up to the back teeth with delays.", "Tôi chán ngấy việc bị trì hoãn."),
        ],
      },
    ],
    words: U94_WORDS,
    exercises: [
      fillBlank(
        94,
        1,
        "The whole event ____ — not a single problem.",
        "worked like a dream",
        [
          { key: "a", label: "worked like a dream" },
          { key: "b", label: "got our wires crossed" },
          { key: "c", label: "threw me completely" },
          { key: "d", label: "down in the dumps" },
        ],
        "a",
      ),
      mcq(
        94,
        2,
        "\"That's all we need!\" thường dùng khi:",
        [
          { key: "a", label: "Tin xấu thêm vào lúc đang khó" },
          { key: "b", label: "Mọi việc hoàn hảo" },
          { key: "c", label: "Rất vui sướng" },
          { key: "d", label: "Không hiểu ai nói gì" },
        ],
        "a",
      ),
      fillBlank(
        94,
        3,
        "We must have ____ about the meeting time.",
        "got our wires crossed",
        [
          { key: "a", label: "got our wires crossed" },
          { key: "b", label: "worked like a dream" },
          { key: "c", label: "been on cloud nine" },
          { key: "d", label: "fallen into place" },
        ],
        "a",
      ),
      fillBlank(
        94,
        4,
        "The meeting was a complete ____ — nobody knew the agenda.",
        "shambles",
        [
          { key: "a", label: "shambles" },
          { key: "b", label: "dream" },
          { key: "c", label: "element" },
          { key: "d", label: "clockwork" },
        ],
        "a",
      ),
      mcq(
        94,
        5,
        "Cụm nào diễn tả cực kỳ hạnh phúc?",
        [
          { key: "a", label: "on cloud nine" },
          { key: "b", label: "down in the dumps" },
          { key: "c", label: "fed up to the back teeth" },
          { key: "d", label: "like a bad dream" },
        ],
        "a",
      ),
      fillBlank(
        94,
        6,
        "Sorry, ____ — can you explain that again?",
        "I'm not with you",
        [
          { key: "a", label: "I'm not with you" },
          { key: "b", label: "looking up" },
          { key: "c", label: "up and running" },
          { key: "d", label: "made for" },
        ],
        "a",
      ),
    ],
  }),

  advancedUnit(95, {
    introVi:
      "Unit 95 ôn phrasal verb: come off, brush up on, laid off, put together... Mỗi cụm có thể nhiều nghĩa; sách khuyên hiểu trước, dùng sau, và học theo chủ đề công việc.",
    structureSections: [
      { label: "Come phrasal verbs", wordCount: 8 },
      { label: "On / stay / dwell / catch", wordCount: 6 },
      { label: "Work and study phrasals", wordCount: 8 },
    ],
    collocationHtml: `${purple("come up against")}, ${purple("brush up on")}, ${purple("thrown himself into")} và ${purple("put together")} là phrasal verb theo ngữ cảnh công việc.`,
    mistakeHtml: `${bold("Come across")} = gặp/tạo ấn tượng; khác ${bold("come off")} = thành công. ${bold("Rush into a decision")} — không *rush a decision into*. Học vị trí tân ngữ.`,
    principles: [
      {
        title: "Học phrasal verb có hệ thống",
        body: `Ghi cụm trong câu ví dụ. Một cụm nhiều nghĩa: ${purple("come across")} = gặp hoặc ${purple("come over as")} unfriendly. Thường có cách nói một từ: ${purple("propose a plan")} thay ${purple("put forward a plan")}.`,
        examples: [
          ex("When you come across a phrasal verb, write it in a sentence.", "Gặp phrasal verb, hãy ghi trong câu ví dụ."),
          ex("Concentrate first on understanding rather than using them.", "Tập trung hiểu trước khi dùng."),
        ],
      },
      {
        title: "Nhóm come và on",
        body: `${purple("come off")} thành công; ${purple("come under criticism")}; ${purple("come up")} bất ngờ; ${purple("come up against")} trở ngại. ${purple("stay on")}; ${purple("dwell on")}; ${purple("catch on")}; ${purple("go on about")}; ${purple("press on regardless")}.`,
        examples: [
          ex("I hope our plans to visit Russia come off.", "Hy vọng kế hoạch sang Nga thành công."),
          ex("Our plan came up against some obstacles.", "Kế hoạch gặp vài trở ngại."),
        ],
      },
      {
        title: "Phrasal verb công việc",
        body: `${purple("brush up on")} kỹ năng; bị ${purple("laid off")}; cuộc họp ${purple("called off")}; ${purple("thrown himself into")} việc mới; ${purple("settle in")}; ${purple("put together")} báo cáo. Tránh ${purple("rush into a decision")}.`,
        examples: [
          ex("I need to brush up on my computer skills.", "Tôi cần ôn lại kỹ năng máy tính."),
          ex("It took ages to put together the report.", "Biên soạn báo cáo mất rất lâu."),
        ],
      },
    ],
    words: U95_WORDS,
    exercises: [
      fillBlank(
        95,
        1,
        "I need to ____ my computer skills before the new job.",
        "brush up on",
        [
          { key: "a", label: "brush up on" },
          { key: "b", label: "dwell on" },
          { key: "c", label: "go on about" },
          { key: "d", label: "stay on" },
        ],
        "a",
      ),
      mcq(
        95,
        2,
        "Come off trong \"I hope our plans come off\" nghĩa là:",
        [
          { key: "a", label: "Diễn ra thành công" },
          { key: "b", label: "Tình cờ gặp" },
          { key: "c", label: "Bị chỉ trích" },
          { key: "d", label: "Đến từ nước ngoài" },
        ],
        "a",
      ),
      fillBlank(
        95,
        3,
        "The company ____ half its staff during the recession.",
        "laid off",
        [
          { key: "a", label: "laid off" },
          { key: "b", label: "called off" },
          { key: "c", label: "caught on" },
          { key: "d", label: "came up" },
        ],
        "a",
      ),
      fillBlank(
        95,
        4,
        "Don't ____ a decision you'll regret.",
        "rush into",
        [
          { key: "a", label: "rush into" },
          { key: "b", label: "put forward" },
          { key: "c", label: "come over" },
          { key: "d", label: "press on" },
        ],
        "a",
      ),
      mcq(
        95,
        5,
        "Thay cho put forward a plan, bạn có thể nói:",
        [
          { key: "a", label: "propose a plan" },
          { key: "b", label: "dwell on a plan" },
          { key: "c", label: "catch on a plan" },
          { key: "d", label: "stay on a plan" },
        ],
        "a",
      ),
      fillBlank(
        95,
        6,
        "It took me weeks to ____ at the new office.",
        "settle in",
        [
          { key: "a", label: "settle in" },
          { key: "b", label: "come off" },
          { key: "c", label: "lay off" },
          { key: "d", label: "call off" },
        ],
        "a",
      ),
    ],
  }),

  advancedUnit(96, {
    introVi:
      "Unit 96 về connotation — liên tưởng vượt nghĩa đen: shark trong garage, dove/hawk trong chính trị, diamond nói về con người. Bạn sẽ đọc sắc thái ẩn mà từ mang theo.",
    structureSections: [
      { label: "Associations and connotation", wordCount: 6 },
      { label: "Animal and object metaphors", wordCount: 8 },
      { label: "Personal and cultural variation", wordCount: 8 },
    ],
    collocationHtml: `${purple("cowboy builders")}, ${purple("scar on the landscape")}, ${purple("real diamond")} và ${purple("word associations")} minh họa connotation trong tiếng Anh.`,
    mistakeHtml: `${bold("Shark")} trong garage = kẻ lợi dụng, không phải cá mập đen. ${bold("Dove")}/${bold("hawk")} là ẩn dụ chính trị. ${bold("Girlfriend")} có thể = bạn nữ, không phải người yêu.`,
    principles: [
      {
        title: "Liên tưởng và hàm nghĩa",
        body: `${purple("connotation")} là ${purple("word associations")} vượt ${purple("literal meaning")}. Nhà báo, quảng cáo khai thác liên tưởng — ${purple("Paris look")}, ${purple("glamour and style")}.`,
        examples: [
          ex("Would you like to have that Paris look?", "Bạn có muốn phong cách Paris không?"),
          ex("Cowboy builders are not careful or trustworthy.", "Thợ xây kiểu cowboy không đáng tin."),
        ],
      },
      {
        title: "Ví dụ shark, scar, diamond",
        body: `${purple("shark")} = hung hăng, lợi dụng; ${purple("scar on the landscape")} = công trình phá cảnh; ${purple("real diamond")} = người quý. ${purple("dove")} = hòa bình; ${purple("hawk")} = cứng rắn.`,
        examples: [
          ex("They're all sharks in that garage.", "Bên garage đó toàn kẻ lợi dụng."),
          ex("Emma's a real diamond.", "Emma là người rất quý."),
        ],
      },
      {
        title: "Cá nhân và văn hóa",
        body: `${purple("shared associations")} (dog = ${purple("faithfulness")}) vs ${purple("personal associations")}. Mèo đen: may ở Anh, xui ở Mỹ. ${purple("a dog's life")} = khổ cực. Ghi liên tưởng riêng khi học từ.`,
        examples: [
          ex("Words are better remembered with personal associations.", "Từ được nhớ lâu hơn nếu có liên tưởng cá nhân."),
          ex("Some associations vary from area to area.", "Vài liên tưởng khác nhau theo vùng."),
        ],
      },
    ],
    words: U96_WORDS,
    exercises: [
      fillBlank(
        96,
        1,
        "They're all ____ in that garage — I don't trust them.",
        "sharks",
        [
          { key: "a", label: "sharks" },
          { key: "b", label: "doves" },
          { key: "c", label: "diamonds" },
          { key: "d", label: "hawks" },
        ],
        "a",
      ),
      mcq(
        96,
        2,
        "\"Emma's a real diamond\" nghĩa là:",
        [
          { key: "a", label: "Emma là người rất tốt, quý giá" },
          { key: "b", label: "Emma bán đá quý" },
          { key: "c", label: "Emma rất keo kiệt" },
          { key: "d", label: "Emma là chính trị gia hòa bình" },
        ],
        "a",
      ),
      fillBlank(
        96,
        3,
        "The new office block is a ____ on the landscape.",
        "scar",
        [
          { key: "a", label: "scar" },
          { key: "b", label: "dove" },
          { key: "c", label: "shark" },
          { key: "d", label: "hawk" },
        ],
        "a",
      ),
      fillBlank(
        96,
        4,
        "A journalist might call a peacemaker a ____.",
        "dove",
        [
          { key: "a", label: "dove" },
          { key: "b", label: "hawk" },
          { key: "c", label: "shark" },
          { key: "d", label: "lad" },
        ],
        "a",
      ),
      {
        type: "match",
        id: "ex-96-match-5",
        instruction: "Ghép từ/cụm với hàm nghĩa liên tưởng",
        pairs: [
          { left: "cowboy builders", right: "thợ xây ẩu, không đáng tin" },
          { left: "hawk", right: "chính trị gia cứng rắn, hiếu chiến" },
          { left: "a dog's life", right: "cuộc sống khổ cực" },
          { left: "Paris look", right: "phong cách thời trang lộng lẫy" },
          { left: "faithfulness", right: "liên tưởng phổ biến với chó" },
        ],
      },
      mcq(
        96,
        6,
        "Connotation khác literal meaning ở điểm nào?",
        [
          { key: "a", label: "Mang liên tưởng/cảm xúc thêm ngoài nghĩa đen" },
          { key: "b", label: "Luôn là từ đồng nghĩa" },
          { key: "c", label: "Chỉ dùng trong headline" },
          { key: "d", label: "Chỉ là lỗi ngữ pháp" },
        ],
        "a",
      ),
    ],
  }),

  advancedUnit(97, {
    introVi:
      "Unit 97 về register — mức trang trọng: partner vs other half, converse vs chat, subsequently vs later. Bạn sẽ chọn từ phù hợp với văn nói, văn viết hay văn công vụ.",
    structureSections: [
      { label: "Formal and informal", wordCount: 10 },
      { label: "Speech vs writing", wordCount: 8 },
      { label: "Outdated vocabulary", wordCount: 6 },
    ],
    collocationHtml: `${purple("other half")}, ${purple("mind you")}, ${purple("subsequently")} và ${purple("have a stab at")} thuộc các register khác nhau.`,
    mistakeHtml: `${bold("Converse")} formal; ${bold("bloke")}/${bold("telly")} informal. ${bold("Subsequently")} và ${bold("in sum")} cho văn viết; ${bold("thingy")} và ${bold("now then")} cho nói. Chọn register đúng tình huống.`,
    principles: [
      {
        title: "Formal, informal, neutral",
        body: `${purple("partner")} (neutral) vs ${purple("other half")} (informal). ${purple("bloke")}, ${purple("gear")}, ${purple("the box")}/${purple("telly")} informal; ${purple("spectacles")}, ${purple("garments")}, ${purple("employ")}/${purple("utilise")} formal.`,
        examples: [
          ex("Is your other half not with you today?", "Nửa kia hôm nay không đi cùng bạn à?"),
          ex("She is able to converse with everyone.", "Cô ấy có thể trò chuyện với mọi người."),
        ],
      },
      {
        title: "Nói hay viết",
        body: `${purple("subsequently")}, ${purple("in sum")} (W). ${purple("whatsisname")}, ${purple("thingy")}, ${purple("mind you")}, ${purple("now then")} (S). Register gắn với quan hệ người nói–người nghe.`,
        examples: [
          ex("Subsequently, three people were arrested.", "Sau đó, ba người bị bắt."),
          ex("Mind you, he went to the best drama college.", "Tuy nhiên, anh ấy học trường sân khấu hàng đầu."),
        ],
      },
      {
        title: "Từ lỗi thời",
        body: `Từ đúng nhưng ${purple("archaic")} / ${purple("old-fashioned")}: wireless (radio), frock (dress), consumption (TB). Hiểu khi đọc văn cũ; tránh dùng trong giao tiếp hiện đại trừ khi có chủ đích.`,
        examples: [
          ex("Register is the overall tone of a text or conversation.", "Register là giọng điệu tổng thể của văn bản hoặc hội thoại."),
          ex("It is important to speak in the appropriate register.", "Quan trọng là nói đúng mức trang trọng."),
        ],
      },
    ],
    words: U97_WORDS,
    exercises: [
      fillBlank(
        97,
        1,
        "Rick's a really nice ____.",
        "bloke",
        [
          { key: "a", label: "bloke" },
          { key: "b", label: "chairperson" },
          { key: "c", label: "deceased" },
          { key: "d", label: "undersigned" },
        ],
        "a",
      ),
      mcq(
        97,
        2,
        "Từ nào formal hơn \"use\"?",
        [
          { key: "a", label: "utilise" },
          { key: "b", label: "gear" },
          { key: "c", label: "telly" },
          { key: "d", label: "thingy" },
        ],
        "a",
      ),
      fillBlank(
        97,
        3,
        "The police found clues. ____, three people were arrested.",
        "Subsequently",
        [
          { key: "a", label: "Subsequently" },
          { key: "b", label: "Now then" },
          { key: "c", label: "Mind you" },
          { key: "d", label: "Whatsisname" },
        ],
        "a",
      ),
      fillBlank(
        97,
        4,
        "Give me that ____ — yes, the bottle opener.",
        "thingy",
        [
          { key: "a", label: "thingy" },
          { key: "b", label: "garment" },
          { key: "c", label: "spectacle" },
          { key: "d", label: "endeavour" },
        ],
        "a",
      ),
      mcq(
        97,
        5,
        "\"Other half\" thay cho từ neutral nào?",
        [
          { key: "a", label: "partner (vợ/chồng)" },
          { key: "b", label: "professor" },
          { key: "c", label: "freshman" },
          { key: "d", label: "gunman" },
        ],
        "a",
      ),
      fillBlank(
        97,
        6,
        "I'll have a ____ at fixing the printer.",
        "stab",
        [
          { key: "a", label: "stab" },
          { key: "b", label: "endeavour" },
          { key: "c", label: "commencement" },
          { key: "d", label: "clarification" },
        ],
        "a",
      ),
    ],
  }),

  advancedUnit(98, {
    introVi:
      "Unit 98 so sánh Anh–Mỹ: crosswalk vs zebra crossing, freshman vs fresher, faucet vs tap. Bạn sẽ hiểu biến thể khu vực mà không nhầm lẫn khi đọc hoặc nói chuyện.",
    structureSections: [
      { label: "Streets and transport", wordCount: 10 },
      { label: "Education", wordCount: 8 },
      { label: "Home and daily life", wordCount: 6 },
    ],
    collocationHtml: `${purple("kitty-corner")}, ${purple("shopping cart")}, ${purple("major in")} và ${purple("honours degree")} phân biệt Mỹ vs Anh.`,
    mistakeHtml: `${bold("College")} ở Anh thường = cao đẳng/chuyên ngành; ở Mỹ ≈ university. ${bold("Professor")} ở Anh = học hàm cao; ở Mỹ gọi chung giảng viên. ${bold("Pavement")} (Anh) ≠ pavement (Mỹ).`,
    principles: [
      {
        title: "Đường phố và giao thông",
        body: `Mỹ: ${purple("crosswalk")}, ${purple("Interstate")}, ${purple("intersection")}, ${purple("overpass")}, ${purple("kitty-corner")}, ${purple("backing up")}. Anh: pedestrian/zebra crossing, motorway, junction, flyover, diagonally opposite, reversing.`,
        examples: [
          ex("Always use the crosswalk to cross the street.", "Luôn dùng vạch sang đường."),
          ex("Look for the overpass, then take the next exit.", "Tìm cầu vượt, rồi ra exit tiếp theo."),
        ],
      },
      {
        title: "Giáo dục",
        body: `Mỹ: ${purple("freshman")}, ${purple("sophomore")}, ${purple("junior")}, ${purple("major in")}, ${purple("elementary school")}, ${purple("high school")}. Anh: ${purple("fresher")}, second/third year, ${purple("honours degree")}, ${purple("primary school")}, ${purple("secondary school")}.`,
        examples: [
          ex("She's majoring in French.", "Cô ấy chuyên ngành tiếng Pháp."),
          ex("My years in secondary school were hard.", "Thời trung học của tôi không dễ."),
        ],
      },
      {
        title: "Trong nhà và đời sống",
        body: `Mỹ: ${purple("faucet")}, ${purple("skillet")}, ${purple("dumpster")}, ${purple("gas station")}, ${purple("shopping cart")}, ${purple("parking lot")}. Anh: tap, frying pan, skip, petrol station, trolley, car park. Ground (Mỹ) / earth (Anh) cable.`,
        examples: [
          ex("The faucet in the kitchen never stops dripping.", "Vòi bếp cứ nhỏ giọt."),
          ex("We need a dumpster for all this old stuff.", "Cần thùng rác lớn cho đống đồ cũ."),
        ],
      },
    ],
    words: U98_WORDS,
    exercises: [
      fillBlank(
        98,
        1,
        "Always use the ____ when you cross the street (US).",
        "crosswalk",
        [
          { key: "a", label: "crosswalk" },
          { key: "b", label: "honours degree" },
          { key: "c", label: "fresher" },
          { key: "d", label: "secondary school" },
        ],
        "a",
      ),
      mcq(
        98,
        2,
        "Sinh viên năm nhất ở Anh thường gọi là:",
        [
          { key: "a", label: "fresher" },
          { key: "b", label: "freshman" },
          { key: "c", label: "sophomore" },
          { key: "d", label: "junior" },
        ],
        "a",
      ),
      fillBlank(
        98,
        3,
        "She's ____ French at university (US).",
        "majoring in",
        [
          { key: "a", label: "majoring in" },
          { key: "b", label: "doing honours in" },
          { key: "c", label: "kitty-corner to" },
          { key: "d", label: "backing up" },
        ],
        "a",
      ),
      fillBlank(
        98,
        4,
        "I fried the fish in a ____ (US).",
        "skillet",
        [
          { key: "a", label: "skillet" },
          { key: "b", label: "dumpster" },
          { key: "c", label: "Interstate" },
          { key: "d", label: "overpass" },
        ],
        "a",
      ),
      mcq(
        98,
        5,
        "British English for US \"gas station\":",
        [
          { key: "a", label: "petrol station" },
          { key: "b", label: "crosswalk" },
          { key: "c", label: "elementary school" },
          { key: "d", label: "shopping cart" },
        ],
        "a",
      ),
      fillBlank(
        98,
        6,
        "The rental office is ____ to the gas station (US, diagonal).",
        "kitty-corner",
        [
          { key: "a", label: "kitty-corner" },
          { key: "b", label: "major in" },
          { key: "c", label: "high school" },
          { key: "d", label: "primary school" },
        ],
        "a",
      ),
    ],
  }),

  advancedUnit(99, {
    introVi:
      "Unit 99 về ngôn ngữ và giới: chairperson, firefighter, Ms, guys; masculine/feminine; macho, laddish. Bạn sẽ dùng từ trung tính trong môi trường chuyên nghiệp và hiểu sắc thái informal.",
    structureSections: [
      { label: "Gender-neutral replacements", wordCount: 10 },
      { label: "Debate and legal context", wordCount: 6 },
      { label: "Informal gendered words", wordCount: 8 },
    ],
    collocationHtml: `${purple("gender-neutral language")}, ${purple("police officer")}, ${purple("human race")} và ${purple("you guys")} phản ánh thay đổi cách dùng từ.`,
    mistakeHtml: `${bold("Guys")} ở Mỹ có thể gọi cả nam lẫn nữ. ${bold("Girlfriend")} = bạn nữ. ${bold("Man")} trong manhandle/man in the street đôi khi không còn nghĩa \"nam giới\". ${bold("Ms")} trung tính hôn phu.`,
    principles: [
      {
        title: "Ngôn ngữ trung tính giới",
        body: `Thay chairman → ${purple("chairperson")}; salesman → ${purple("sales assistant")}; fireman → ${purple("firefighter")}; air hostess → ${purple("flight attendant")}; ${purple("man-made")} → ${purple("artificial")}; mankind → ${purple("human race")}; to man → ${purple("to staff")}.`,
        examples: [
          ex("The spokesperson addressed the press.", "Người phát ngôn trả lời báo chí."),
          ex("Volunteers will staff the information desk.", "Tình nguyện viên trực quầy thông tin."),
        ],
      },
      {
        title: "Tranh luận và pháp lý",
        body: `Mô tả công việc đôi khi bắt buộc trung tính. Vẫn tranh luận: ${purple("man in the street")}, Neanderthal Man, ${purple("manhandle")}, woman. ${purple("Ms")} thay Miss/Mrs.`,
        examples: [
          ex("Gender-neutral language has become a legal requirement in job ads.", "Ngôn ngữ trung tính thành yêu cầu pháp lý trong tin tuyển dụng."),
          ex("Ms avoids revealing marital status.", "Ms tránh tiết lộ tình trạng hôn nhân."),
        ],
      },
      {
        title: "Từ informal có sắc giới",
        body: `${purple("masculine")} pride; ${purple("feminine")} charm. ${purple("you guys")} xưng hô nhóm. ${purple("girlfriend")} (bạn nữ); ${purple("girlie evening")}. ${purple("lad")}, ${purple("laddish")} behaviour; ${purple("macho")} image. ${purple("male and female")} trong sinh học.`,
        examples: [
          ex("Do any of you guys fancy going out for pizza?", "Ai muốn đi ăn pizza không?"),
          ex("I can't stand that kind of laddish behaviour.", "Tôi không chịu nổi kiểu trai trẻ ồn ào đó."),
        ],
      },
    ],
    words: U99_WORDS,
    exercises: [
      fillBlank(
        99,
        1,
        "Fireman is now usually replaced by ____.",
        "firefighter",
        [
          { key: "a", label: "firefighter" },
          { key: "b", label: "salesman" },
          { key: "c", label: "chairman" },
          { key: "d", label: "air hostess" },
        ],
        "a",
      ),
      mcq(
        99,
        2,
        "Ms được dùng để:",
        [
          { key: "a", label: "Trung tính, không tiết lộ hôn nhân" },
          { key: "b", label: "Chỉ gọi sinh viên nữ" },
          { key: "c", label: "Thay cho professor" },
          { key: "d", label: "Headline báo chí" },
        ],
        "a",
      ),
      fillBlank(
        99,
        3,
        "Mankind is often replaced by the ____.",
        "human race",
        [
          { key: "a", label: "human race" },
          { key: "b", label: "macho image" },
          { key: "c", label: "laddish behaviour" },
          { key: "d", label: "girlie evening" },
        ],
        "a",
      ),
      fillBlank(
        99,
        4,
        "Man-made materials are often called ____ today.",
        "artificial",
        [
          { key: "a", label: "artificial" },
          { key: "b", label: "masculine" },
          { key: "c", label: "macho" },
          { key: "d", label: "laddish" },
        ],
        "a",
      ),
      mcq(
        99,
        5,
        "\"Macho\" mô tả người:",
        [
          { key: "a", label: "Cố tỏ mạnh, không khoe yếu đuối" },
          { key: "b", label: "Trung tính giới trong công việc" },
          { key: "c", label: "Chỉ nói về phụ nữ" },
          { key: "d", label: "Sinh viên năm nhất" },
        ],
        "a",
      ),
      fillBlank(
        99,
        6,
        "Volunteers will ____ the help desk.",
        "staff",
        [
          { key: "a", label: "staff" },
          { key: "b", label: "man" },
          { key: "c", label: "major" },
          { key: "d", label: "crush" },
        ],
        "a",
      ),
    ],
  }),

  advancedUnit(100, {
    introVi:
      "Unit 100 phân tích ngôn ngữ headline: rút gọn mạo từ, thì hiện tại, chơi chữ Rain of terror, từ mạnh như crazed gunman, thugs, crackdown. Hữu ích khi đọc báo, ít khi dùng khi nói.",
    structureSections: [
      { label: "Headline style", wordCount: 8 },
      { label: "Drama and violence", wordCount: 8 },
      { label: "Wordplay and tabloids", wordCount: 7 },
    ],
    collocationHtml: `${purple("hits the headlines")}, ${purple("play on words")}, ${purple("reign of terror")} và ${purple("militaristic words")} đặc trưng báo lá cải.`,
    mistakeHtml: `Ngôn ngữ headline ${bold("ambiguous")} — cloud có thể là đám mây công nghệ. ${bold("Crazed")}, ${bold("gunman")} dramatize tin. Không nói kiểu headline trong email trang trọng.`,
    principles: [
      {
        title: "Đặc điểm headline",
        body: `Bỏ articles, prepositions, auxiliaries. ${purple("present simple for immediacy")}. ${purple("ambiguous")} — ${purple("cloud storage")} vs thời tiết. ${purple("dramatic associations")}: danger, tragic.`,
        examples: [
          ex("EXPERT REVEALS NEW CLOUD DANGERS", "CHUYÊN GIA TIẾT LỘ NGUY HIỂM MỚI TỪ 'CLOUD'."),
          ex("Readers have to read the story to find out what cloud means.", "Độc giả phải đọc bài mới biết cloud nghĩa gì."),
        ],
      },
      {
        title: "Kịch tính và bạo lực",
        body: `${purple("tabloid")} dùng celebrity, ${purple("alliteration")} (Tragic Target), từ mạnh: ${purple("gunman")}, ${purple("crazed")}. ${purple("militaristic words")}: ${purple("besieged")}, ${purple("crackdown")}, ${purple("crush terror")}, ${purple("rips through")}; ${purple("thugs")}, ${purple("yobs")}, ${purple("louts")}.`,
        examples: [
          ex("TV STAR TRAGIC TARGET FOR CRAZED GUNMAN", "NGÔI SAO TV — MỤC TIÊU TRÁGIC CỦA KẺ SÚNG ĐIÊN."),
          ex("Typhoon rips through town.", "Bão quét qua thị trấn."),
        ],
      },
      {
        title: "Chơi chữ",
        body: `${purple("Rain of terror")} chơi trên ${purple("reign of terror")}. ${purple("shooting star")} + cầu thủ Moon + shoot a goal. ${purple("play on words")} thu hút mắt đọc — ${purple("hits the headlines")}.`,
        examples: [
          ex("Moon becomes shooting star after scoring.", "Moon thành 'sao băng' sau bàn thắng."),
          ex("Headline language sounds strange in other contexts.", "Ngôn ngữ headline nghe lạ ở ngữ cảnh khác."),
        ],
      },
    ],
    words: U100_WORDS,
    exercises: [
      fillBlank(
        100,
        1,
        "The scandal ____ overnight.",
        "hit the headlines",
        [
          { key: "a", label: "hit the headlines" },
          { key: "b", label: "brush up on" },
          { key: "c", label: "settle in" },
          { key: "d", label: "got our wires crossed" },
        ],
        "a",
      ),
      mcq(
        100,
        2,
        "Headline thường dùng thì hiện tại để:",
        [
          { key: "a", label: "Làm tin nghe cấp bách, trực tiếp" },
          { key: "b", label: "Tuân thủ ngữ pháp email formal" },
          { key: "c", label: "Tránh chơi chữ" },
          { key: "d", label: "Mô tả quá khứ xa" },
        ],
        "a",
      ),
      fillBlank(
        100,
        3,
        "Rain of terror is a ____ on reign of terror.",
        "play on words",
        [
          { key: "a", label: "play on words" },
          { key: "b", label: "crosswalk" },
          { key: "c", label: "honours degree" },
          { key: "d", label: "gender-neutral language" },
        ],
        "a",
      ),
      fillBlank(
        100,
        4,
        "EU acts to ____ terror of thugs.",
        "crush",
        [
          { key: "a", label: "crush" },
          { key: "b", label: "facilitate" },
          { key: "c", label: "endeavour" },
          { key: "d", label: "acknowledge" },
        ],
        "a",
      ),
      mcq(
        100,
        5,
        "Alliteration trong headline giúp:",
        [
          { key: "a", label: "Dễ nhớ và thu hút mắt" },
          { key: "b", label: "Làm câu dài hơn" },
          { key: "c", label: "Tránh hiểu nhầm" },
          { key: "d", label: "Viết văn phong học thuật" },
        ],
        "a",
      ),
      fillBlank(
        100,
        6,
        "Palace ____ by journalists.",
        "besieged",
        [
          { key: "a", label: "besieged" },
          { key: "b", label: "eligible" },
          { key: "c", label: "placid" },
          { key: "d", label: "naive" },
        ],
        "a",
      ),
    ],
  }),

  advancedUnit(101, {
    introVi:
      "Unit 101 về red tape — ngôn ngữ quan liêu: eligible, hereby rejected, commence, in the event of, at your earliest convenience. Bạn sẽ đọc hiểu thư công vụ và form hành chính.",
    structureSections: [
      { label: "Bureaucratic style", wordCount: 8 },
      { label: "Formal verbs and phrases", wordCount: 10 },
      { label: "Official correspondence", wordCount: 8 },
    ],
    collocationHtml: `${purple("hereby rejected")}, ${purple("in the event of")}, ${purple("at your earliest convenience")} và ${purple("acknowledge receipt")} là mẫu thư công vụ.`,
    mistakeHtml: `${bold("Commence")} = start (formal); đừng dùng trong chat. ${bold("Deceased")} = người đã mất — cực kỹ trang trọng. ${bold("Undersigned")} = người ký dưới đây. Passive và danh từ hóa làm câu nặng.`,
    principles: [
      {
        title: "Đặc điểm ngôn ngữ quan liêu",
        body: `Từ dài, \"grander\" hơn đời thường. Passive: ${purple("will be resumed")}. Danh từ hóa chủ ngữ. Tránh You — \"Customers will be informed\" thay \"We will tell you\". ${purple("bureaucratic language")} vs ${purple("red tape")}.`,
        examples: [
          ex("Normal service will be resumed as soon as possible.", "Dịch vụ bình thường sẽ được tiếp tục sớm nhất có thể."),
          ex("Achievement of this module is dependent upon candidates meeting outcomes.", "Đạt module phụ thuộc ứng viên đáp ứng chuẩn đầu ra."),
        ],
      },
      {
        title: "Động từ và cụm formal",
        body: `${purple("eligible")}; ${purple("attained the age")}; ${purple("bestowed on")}; ${purple("commence")}/${purple("commencement")}; ${purple("ceased operations")}; ${purple("deceased")}/${purple("next of kin")}; ${purple("in the event of")}; ${purple("endeavour to")}; ${purple("facilitate")}; ${purple("rectify")}.`,
        examples: [
          ex("Work will commence in May.", "Công việc sẽ bắt đầu vào tháng Năm."),
          ex("In the event of fire, evacuate immediately.", "Nếu có hỏa hoạn, sơ tán ngay."),
        ],
      },
      {
        title: "Thư công vụ",
        body: `${purple("hereby rejected")}; ${purple("adjoining property")}; ${purple("undersigned")}; ${purple("aforementioned")}. ${purple("acknowledge receipt")}; ${purple("with the compliments of")}; ${purple("notify")}; ${purple("at your earliest convenience")}; ${purple("clarification")}; ${purple("in respect of")}; ${purple("with regard to")}.`,
        examples: [
          ex("Your request is hereby rejected.", "Yêu cầu của quý vị bị từ chối theo văn bản này."),
          ex("I enclose payment in respect of your invoice.", "Tôi kèm thanh toán cho hóa đơn của quý công ty."),
        ],
      },
    ],
    words: U101_WORDS,
    exercises: [
      fillBlank(
        101,
        1,
        "A student shall not be ____ for a loan if over 50.",
        "eligible",
        [
          { key: "a", label: "eligible" },
          { key: "b", label: "ambiguous" },
          { key: "c", label: "macho" },
          { key: "d", label: "bright" },
        ],
        "a",
      ),
      mcq(
        101,
        2,
        "Commence trong \"Work will commence in May\" nghĩa là:",
        [
          { key: "a", label: "Bắt đầu (formal)" },
          { key: "b", label: "Kết thúc" },
          { key: "c", label: "Hủy bỏ" },
          { key: "d", label: "Trì hoãn" },
        ],
        "a",
      ),
      fillBlank(
        101,
        3,
        "Your request is ____ rejected.",
        "hereby",
        [
          { key: "a", label: "hereby" },
          { key: "b", label: "swiftly" },
          { key: "c", label: "mind you" },
          { key: "d", label: "flat" },
        ],
        "a",
      ),
      fillBlank(
        101,
        4,
        "____ fire, the building must be evacuated.",
        "In the event of",
        [
          { key: "a", label: "In the event of" },
          { key: "b", label: "On cloud nine" },
          { key: "c", label: "Go hand in hand with" },
          { key: "d", label: "Brush up on" },
        ],
        "a",
      ),
      mcq(
        101,
        5,
        "At your earliest convenience nghĩa là:",
        [
          { key: "a", label: "Sớm nhất có thể (formal)" },
          { key: "b", label: "Khi rảnh tuỳ ý" },
          { key: "c", label: "Không bao giờ" },
          { key: "d", label: "Ngay lập tức (informal)" },
        ],
        "a",
      ),
      fillBlank(
        101,
        6,
        "Please ____ receipt of payment.",
        "acknowledge",
        [
          { key: "a", label: "acknowledge" },
          { key: "b", label: "crush" },
          { key: "c", label: "dwell" },
          { key: "d", label: "catch on" },
        ],
        "a",
      ),
    ],
  }),
];
