import type { VocabularyUnit } from "@/lib/vocabulary/vocabulary-unit-types";
import {
  bold,
  ex,
  fillBlank,
  mcq,
  purple,
} from "@/lib/vocabulary/units/eviu-unit-builder";
import { upperUnit, wordList } from "@/lib/vocabulary/units/eviu-upper-unit-helpers";

const U95_WORDS = wordList([
  ["offspring", "con cái (trang trọng; thân mật: kids)", "The couple have three offspring."],
  ["abode", "nơi ở (trang trọng)", "Welcome to my humble abode."],
  ["residence", "nơi cư trú (trang trọng)", "Please state your permanent residence."],
  ["cheerio", "tạm biệt (thân mật, Anh)", "Cheerio — see you tomorrow!", "INTERJECTION"],
  ["go pear-shaped", "hỏng bét, lệch kế hoạch (thân mật)", "The party went pear-shaped when it started raining.", "IDIOM"],
  ["go amiss", "trục trặc, sai lệch (trang trọng hơn go wrong)", "Something went amiss with the booking.", "PHRASE"],
  ["utilise", "sử dụng (trang trọng; = use)", "The lab utilises the newest equipment.", "VERB"],
  ["frequently", "thường xuyên (trang trọng hơn often)", "This error frequently occurs with older software.", "ADVERB"],
  ["establish", "chứng minh / xác lập (trang trọng)", "The study established a link between stress and ill-health.", "VERB"],
  ["provide", "cung cấp (trang trọng hơn give)", "This book provides a picture of ordinary medieval life.", "VERB"],
  ["attempt", "cố gắng, nỗ lực (trang trọng hơn try)", "The government attempted to reduce unemployment.", "VERB"],
  ["seek", "tìm kiếm (trang trọng hơn look for)", "Physicists seek answers to fundamental questions.", "VERB"],
  ["fundamental", "cơ bản, nền tảng (trang trọng hơn basic)", "They study fundamental questions about the universe.", "ADJECTIVE"],
  ["immediately", "ngay lập tức (trung tính; thân mật: right away)", "I'll email Kieran immediately.", "ADVERB"],
  ["in terms of", "về mặt / xét về", "What should we do in terms of helping young people?", "PHRASE"],
  ["in particular", "đặc biệt là", "Students, in particular, need financial support.", "PHRASE"],
  ["on account of", "vì / do (trang trọng hơn because of)", "Fees rose on account of higher living costs.", "PHRASE"],
  ["on the basis of", "dựa trên / căn cứ vào", "Support is given on the basis of family circumstances.", "PHRASE"],
  ["in relation to", "liên quan đến / đối với", "How should policy act in relation to youth unemployment?", "PHRASE"],
  ["alight", "xuống (xe/tàu) — thường trên biển báo trang trọng", "Please do not alight while the bus is in motion.", "VERB"],
  ["stationary", "đứng yên, không chuyển động (trang trọng)", "Wait until the bus is stationary before you get off.", "ADJECTIVE"],
]);

const U96_WORDS = wordList([
  ["cops", "cảnh sát (thân mật)", "The cops have arrived."],
  ["loo", "nhà vệ sinh (thân mật, Anh)", "The house has two loos."],
  ["quid", "bảng Anh (thân mật)", "It cost me ten quid."],
  ["spud", "khoai tây (thân mật)", "I'll help you peel the spuds."],
  ["tube", "tàu điện ngầm London (thân mật)", "I always go by tube."],
  ["nick", "nhà tù (slang)", "His dad spent ten years in the nick."],
  ["cab", "taxi (thân mật)", "I'll get a cab from the station."],
  ["lab", "phòng thí nghiệm (dạng rút gọn)", "I'll meet you in the lab."],
  ["tech", "công nghệ (dạng rút gọn)", "She works for a tech company."],
  ["telly", "tivi (thân mật)", "What's on telly tonight?"],
  ["mag", "tạp chí (dạng rút gọn)", "Have you seen that mag?"],
  ["ad", "quảng cáo (dạng rút gọn của advertisement)", "We should put an ad in the paper."],
  ["celeb", "người nổi tiếng (thân mật)", "Would you like to be a celeb?"],
  ["dosh", "tiền (slang)", "I need some dosh for the weekend."],
  ["nosh", "đồ ăn (slang)", "Let's get some nosh before the film."],
  ["sarnie", "bánh sandwich (slang, Anh)", "I made a cheese sarnie."],
  ["cuppa", "tách trà (slang, Anh)", "Fancy a cuppa?"],
  ["geek", "người mê máy tính/thiết bị (slang)", "He's a total computer geek."],
  ["nerd", "mọt sách / mọt máy (slang)", "Don't call him a nerd — he's just focused."],
  ["anorak", "người cuồng một sở thích/thiết bị (slang, Anh)", "Only a real anorak knows every train timetable."],
  ["shrink", "bác sĩ tâm thần (slang)", "She's been seeing a shrink for months."],
  ["quack", "bác sĩ (slang, có thể miệt thị)", "I need to see the quack about this cough."],
]);

const U97_WORDS = wordList([
  ["as blind as a bat", "mù tịt (thân mật; có thể xúc phạm)", "Without glasses he's as blind as a bat.", "IDIOM"],
  ["as thin as a rake", "gầy đét (thân mật; có thể xúc phạm)", "After the diet she looked as thin as a rake.", "IDIOM"],
  ["as strong as an ox", "khỏe như trâu", "He's as strong as an ox — he carried both bags.", "IDIOM"],
  ["as quiet as a mouse", "im thin thít", "The children were as quiet as a mouse.", "IDIOM"],
  ["as heavy as lead", "nặng như chì", "This suitcase is as heavy as lead.", "IDIOM"],
  ["as light as a feather", "nhẹ như lông", "The scarf was as light as a feather.", "IDIOM"],
  ["as drunk as a lord", "say bí tỉ (thân mật; có thể xúc phạm)", "He came home as drunk as a lord.", "IDIOM"],
  ["as sober as a judge", "tỉnh táo hoàn toàn", "She was as sober as a judge all evening.", "IDIOM"],
  ["as cool as a cucumber", "bình tĩnh lạnh lùng", "Before the exam he looked as cool as a cucumber.", "IDIOM"],
  ["as busy as a bee", "bận rộn suốt", "She's been as busy as a bee this week.", "IDIOM"],
  ["as hard as iron", "cứng như sắt", "The bed was as hard as iron and I couldn't sleep.", "IDIOM"],
  ["dry as a bone", "khô cứng / khô như que", "The soil's dry as a bone — water the plant.", "IDIOM"],
  ["as mad as a hatter", "điên khùng (thân mật; có thể xúc phạm)", "He's as mad as a hatter — he crossed the Atlantic in a bathtub.", "IDIOM"],
  ["as bold as brass", "trơ tráo / táo tợn", "She told him, as bold as brass, that his lessons were boring.", "IDIOM"],
  ["as deaf as a post", "điếc đặc (thân mật; có thể xúc phạm)", "Speak clearly — he's as deaf as a post.", "IDIOM"],
  ["as easy as pie", "dễ như ăn kẹo", "Passing this exam is as easy as pie.", "IDIOM"],
  ["as quick as a flash", "nhanh như chớp", "She knew the answer as quick as a flash.", "IDIOM"],
  ["as white as a sheet", "tái nhợt vì sợ", "When he saw it, his face went as white as a sheet.", "IDIOM"],
  ["as sick as a parrot", "thất vọng / bực bội hết sức (thân mật)", "She ran off with my money — I felt as sick as a parrot.", "IDIOM"],
  ["like a dream", "suôn sẻ tuyệt vời", "My plan worked like a dream.", "IDIOM"],
  ["eyes like a hawk", "tinh mắt, không sót chi tiết", "The boss has eyes like a hawk.", "IDIOM"],
  ["mind like a sieve", "hay quên như sàng thủng", "I've got a mind like a sieve today.", "IDIOM"],
]);

const U98_WORDS = wordList([
  [
    "Don't count your chickens before they hatch",
    "đừng tính chuyện chưa chắc xảy ra",
    "Don't count your chickens before they hatch — wait for the offer letter.",
    "IDIOM",
  ],
  [
    "Don't put all your eggs in one basket",
    "đừng dồn hết nỗ lực/tiền vào một chỗ",
    "Apply to several universities — don't put all your eggs in one basket.",
    "IDIOM",
  ],
  [
    "Never judge a book by its cover",
    "đừng đánh giá qua vẻ ngoài",
    "Never judge a book by its cover — she's brilliant once you talk to her.",
    "IDIOM",
  ],
  [
    "Never look a gift-horse in the mouth",
    "đừng từ chối may mắn đang ở trước mặt",
    "It's free training — never look a gift-horse in the mouth.",
    "IDIOM",
  ],
  [
    "Take care of the pennies and the pounds will take care of themselves",
    "tiết kiệm từng khoản nhỏ rồi khoản lớn sẽ tự lo được",
    "She saves spare change; take care of the pennies and the pounds will take care of themselves.",
    "IDIOM",
  ],
  [
    "We'll cross that bridge when we come to it",
    "đến đâu hay đến đó / xử lý khi vấn đề thực sự xảy ra",
    "Don't worry about next year yet — we'll cross that bridge when we come to it.",
    "IDIOM",
  ],
  [
    "When the cat's away, the mice will play",
    "vắng chủ nhà gà vọc niêu tôm",
    "The manager's on leave — when the cat's away, the mice will play.",
    "IDIOM",
  ],
  [
    "You can lead a horse to water but you can't make it drink",
    "có thể khuyên nhưng không ép được ai",
    "I showed him the course, but you can lead a horse to water but you can't make it drink.",
    "IDIOM",
  ],
  [
    "One swallow doesn't make a summer",
    "một dấu hiệu tốt chưa đủ để kết luận mọi chuyện ổn",
    "One good result is nice, but one swallow doesn't make a summer.",
    "IDIOM",
  ],
  [
    "There's no smoke without fire",
    "không có lửa sao có khói (tin đồn thường có phần thật)",
    "People keep talking about a merger — there's no smoke without fire.",
    "IDIOM",
  ],
  [
    "Where there's smoke, there's fire",
    "có khói là có lửa (biến thể của proverb trên)",
    "Where there's smoke, there's fire — check the rumours carefully.",
    "IDIOM",
  ],
  [
    "People who live in glass houses shouldn't throw stones",
    "mình còn khuyết điểm thì đừng chê người khác",
    "People who live in glass houses shouldn't throw stones — you've made the same mistake.",
    "IDIOM",
  ],
  [
    "Too many cooks spoil the broth",
    "lắm thầy thối ma (quá nhiều người xen vào thì hỏng việc)",
    "Let one person edit the draft — too many cooks spoil the broth.",
    "IDIOM",
  ],
  [
    "Many hands make light work",
    "đông người thì việc nhẹ hơn",
    "If we all help, many hands make light work.",
    "IDIOM",
  ],
  ["count your chickens", "tính trước chuyện chưa chắc (dạng rút gọn)", "Don't count your chickens just yet.", "IDIOM"],
  [
    "all your eggs in one basket",
    "dồn hết vào một chỗ (dạng rút gọn)",
    "Investing everything there is putting all your eggs in one basket.",
    "IDIOM",
  ],
  ["cross that bridge later", "tính sau khi tới chuyện (dạng rút gọn)", "We'll cross that bridge later.", "IDIOM"],
  [
    "judge a book by its cover",
    "đánh giá qua bề ngoài (dạng rút gọn)",
    "Try not to judge a book by its cover.",
    "IDIOM",
  ],
  ["gift-horse", "món quà / may mắn không nên soi xét quá", "It's a gift-horse — just say thank you.", "IDIOM"],
  ["spoil the broth", "làm hỏng việc vì quá nhiều người xen vào", "Extra editors will only spoil the broth.", "IDIOM"],
]);

const U99_WORDS = wordList([
  ["alight here", "xuống xe tại đây (biển báo)", "Alight here for the museum.", "PHRASE"],
  [
    "trespassers will be prosecuted",
    "người xâm nhập đất tư sẽ bị kiện",
    "The sign said trespassers will be prosecuted.",
    "PHRASE",
  ],
  ["no through road", "đường cụt / không thông ra đầu kia", "There's a no through road for cars.", "PHRASE"],
  ["litter", "rác vứt bừa bãi", "There's a heavy fine for dropping litter.", "NOUN"],
  ["penalty", "mức phạt", "The penalty for littering can be £1,000."],
  ["refreshments", "đồ ăn nhẹ / đồ uống (thường trên biển báo)", "Refreshments are available in the café."],
  ["admission", "quyền/điều kiện vào cửa", "Admission for under-18s only with an adult."],
  [
    "accompanied by an adult",
    "đi cùng người lớn",
    "Under-18s may enter only if accompanied by an adult.",
    "PHRASE",
  ],
  ["reduce speed now", "giảm tốc độ ngay", "The road sign says reduce speed now.", "PHRASE"],
  ["refrain from", "xin hãy tránh / không làm", "Please refrain from using mobile phones.", "VERB"],
  ["unauthorized entry", "vào không được phép", "Unauthorized entry is forbidden.", "PHRASE"],
  ["staff only", "chỉ dành cho nhân viên", "That door is marked staff only.", "PHRASE"],
  ["permit holders only", "chỉ người có giấy phép", "Fishing is for permit holders only.", "PHRASE"],
  ["do not feed the animals", "không cho thú ăn", "The zoo notice said do not feed the animals.", "PHRASE"],
  ["display your ticket", "để vé ở chỗ dễ thấy", "Please display your ticket clearly.", "PHRASE"],
  ["cyclists dismount", "người đi xe đạp phải xuống xe", "Cyclists dismount before the bridge.", "PHRASE"],
  ["until further notice", "cho đến khi có thông báo mới", "The stairway is closed until further notice.", "PHRASE"],
  ["lift capacity", "sức chứa tối đa của thang máy", "Lift capacity: six persons or 500 kilos.", "PHRASE"],
  ["we regret", "chúng tôi rất tiếc (văn biển báo/thông báo)", "We regret we no longer accept cheques.", "PHRASE"],
  ["boarding", "lên tàu/xe", "Tickets must be purchased before boarding."],
  ["in motion", "đang chuyển động", "Do not speak to the driver while the bus is in motion.", "PHRASE"],
]);

const U100_WORDS = wordList([
  ["aid", "viện trợ / giúp đỡ (từ headline ngắn)", "Flood victims need urgent aid.", "NOUN"],
  ["axe", "cắt giảm, loại bỏ (headline)", "The firm will axe 200 jobs.", "VERB"],
  ["back", "ủng hộ (headline)", "Unions back the new pay deal.", "VERB"],
  ["bar", "cấm / loại trừ (headline)", "Fans were barred from the stadium.", "VERB"],
  ["bid", "nỗ lực / cố gắng (headline)", "A last-minute bid to save the club failed."],
  ["blast", "vụ nổ (headline)", "Blast rocks city centre."],
  ["blaze", "đám cháy lớn (headline)", "Blaze destroys warehouse."],
  ["boost", "thúc đẩy / cú hích (headline)", "Tax cuts aim to boost spending.", "VERB"],
  ["clash", "xung đột / tranh cãi (headline)", "Police clash with protesters."],
  ["curb", "hạn chế / kiềm chế (headline)", "New laws curb smoking in public.", "VERB"],
  ["drive", "chiến dịch / nỗ lực (headline)", "A new drive to cut waste begins."],
  ["go-ahead", "sự chấp thuận / đèn xanh", "Council gives go-ahead for new bridge."],
  ["oust", "đẩy khỏi vị trí / lật đổ (headline)", "MPs try to oust the leader.", "VERB"],
  ["ordeal", "trải nghiệm đau đớn / gian khổ", "Hostages described their ordeal."],
  ["plea", "lời kêu gọi / cầu xin (headline)", "Parents make plea for missing child."],
  ["pledge", "cam kết / hứa (headline)", "PM pledges more school funding.", "VERB"],
  ["ploy", "mánh khóe / thủ đoạn khéo", "Critics called the promise an election ploy."],
  ["poll", "cuộc thăm dò / bầu cử (headline)", "Latest poll shows a tight race."],
  ["probe", "cuộc điều tra (headline)", "Police launch probe into fraud."],
  ["quit", "từ chức / bỏ việc (headline)", "Minister to quit after scandal.", "VERB"],
  ["vow", "thề / cam kết mạnh (headline)", "Leaders vow to fight corruption.", "VERB"],
  ["wed", "kết hôn (headline)", "Film stars wed in secret ceremony.", "VERB"],
]);

const U101_WORDS = wordList([
  ["gas / petrol", "xăng (AmE gas; BrE petrol)", "Fill the tank: gas / petrol means the same fuel.", "PHRASE"],
  ["truck / lorry", "xe tải (AmE truck; BrE lorry)", "A delivery truck / lorry blocked the street.", "PHRASE"],
  ["sidewalk / pavement", "vỉa hè (AmE sidewalk; BrE pavement)", "Keep bikes off the sidewalk / pavement.", "PHRASE"],
  ["crosswalk / zebra crossing", "vạch sang đường (AmE crosswalk; BrE zebra crossing)", "Stop at the crosswalk / zebra crossing.", "PHRASE"],
  ["line / queue", "hàng người xếp hàng (AmE line; BrE queue)", "Please join the line / queue at the counter.", "PHRASE"],
  ["vacation / holiday", "kỳ nghỉ (AmE vacation; BrE holiday)", "We're planning a summer vacation / holiday.", "PHRASE"],
  ["parking lot / car park", "bãi đỗ xe (AmE parking lot; BrE car park)", "Leave the car in the parking lot / car park.", "PHRASE"],
  ["trunk / boot", "cốp xe (AmE trunk; BrE boot)", "Put the bags in the trunk / boot.", "PHRASE"],
  ["hood / bonnet", "nắp capo (AmE hood; BrE bonnet)", "Open the hood / bonnet to check the oil.", "PHRASE"],
  ["freeway / motorway", "đường cao tốc (AmE freeway; BrE motorway)", "Take the freeway / motorway to the airport.", "PHRASE"],
  ["round trip / return", "vé khứ hồi (AmE round trip; BrE return)", "I bought a round trip / return ticket.", "PHRASE"],
  ["subway / underground", "tàu điện ngầm (AmE subway; BrE underground)", "Take the subway / underground across town.", "PHRASE"],
  ["garbage / rubbish", "rác (AmE garbage/trash; BrE rubbish)", "Take out the garbage / rubbish tonight.", "PHRASE"],
  ["elevator / lift", "thang máy (AmE elevator; BrE lift)", "Take the elevator / lift to floor three.", "PHRASE"],
  ["apartment / flat", "căn hộ (AmE apartment; BrE flat)", "They rent a small apartment / flat.", "PHRASE"],
  ["flashlight / torch", "đèn pin (AmE flashlight; BrE torch)", "Bring a flashlight / torch when camping.", "PHRASE"],
  ["cookie / biscuit", "bánh quy ngọt (AmE cookie; BrE biscuit)", "Have a chocolate cookie / biscuit with tea.", "PHRASE"],
  ["candy / sweets", "kẹo (AmE candy; BrE sweets)", "Kids love candy / sweets after dinner.", "PHRASE"],
  ["diaper / nappy", "tã em bé (AmE diaper; BrE nappy)", "Change the baby's diaper / nappy.", "PHRASE"],
  ["fall / autumn", "mùa thu (AmE fall; BrE autumn)", "Leaves change colour in fall / autumn.", "PHRASE"],
  ["pants / trousers", "quần dài (AmE pants; BrE trousers — BrE pants thường = quần lót)", "AmE pants / trousers means long outer wear.", "PHRASE"],
  ["check / bill", "hóa đơn nhà hàng (AmE check; BrE bill)", "Could we have the check / bill, please?", "PHRASE"],
]);
export const EVIU_UPPER_UNITS_95_101: VocabularyUnit[] = [
  upperUnit(95, {
    introVi:
      "Unit 95 dạy thang độ trang trọng–thân mật: cặp từ Latin/Hy Lạp dài thường trang trọng hơn bản trung tính/ngắn, cùng các cụm academic/official. Bạn sẽ chọn register phù hợp quan hệ và ngữ cảnh.",
    structureSections: [
      { label: "Formality scales", wordCount: 6 },
      { label: "Latin/Greek formal verbs", wordCount: 8 },
      { label: "Formal phrases and notices", wordCount: 7 },
    ],
    collocationHtml: `${purple("in terms of")}, ${purple("on account of")}, ${purple("on the basis of")} và ${purple("in relation to")} là các cụm trang trọng then chốt trong văn học thuật/quan phương.`,
    mistakeHtml: `Đừng dùng ngôn ngữ thân mật chỉ để \"nghe trôi chảy\". Phân biệt ${bold("utilise")} (trang trọng) với ${bold("use")} (trung tính), và ${bold("go pear-shaped")} (thân mật) với ${bold("go wrong")} / ${bold("go amiss")}. Trên biển báo, ${bold("alight")} và ${bold("stationary")} nghe trang trọng hơn get off / not moving.`,
    principles: [
      {
        title: "Thang độ trang trọng",
        body: `Cùng một ý có thể đi từ trang trọng → trung tính → thân mật: ${purple("offspring")} → children → kids; ${purple("abode")} / ${purple("residence")} → house/home → place; goodbye → bye → ${purple("cheerio")}; ${purple("go amiss")} → go wrong → ${purple("go pear-shaped")}.`,
        examples: [
          ex("The couple have three offspring.", "Cặp đôi có ba người con (văn trang trọng)."),
          ex("The party went pear-shaped.", "Bữa tiệc hỏng bét."),
        ],
      },
      {
        title: "Động từ Latin/Hy Lạp trang trọng",
        body: `${purple("utilise")} ≈ use; ${purple("frequently")} ≈ often; ${purple("establish")} ≈ show/prove; ${purple("provide")} ≈ give; ${purple("attempt")} ≈ try; ${purple("seek")} ≈ look for; ${purple("fundamental")} ≈ basic; ${purple("immediately")} ≈ at once / right away.`,
        examples: [
          ex("The researchers utilise modern equipment.", "Các nhà nghiên cứu sử dụng thiết bị hiện đại."),
          ex("I'll email him immediately.", "Tôi sẽ email anh ấy ngay."),
        ],
      },
      {
        title: "Cụm trang trọng và biển báo",
        body: `${purple("in terms of")}, ${purple("in particular")}, ${purple("on account of")}, ${purple("on the basis of")}, ${purple("in relation to")}. Biển báo: ${purple("alight")}, ${purple("stationary")}.`,
        examples: [
          ex("Students, in particular, need support on account of high fees.", "Sinh viên, đặc biệt, cần hỗ trợ vì học phí cao."),
          ex("Do not alight while the bus is in motion.", "Không xuống xe khi xe đang chạy."),
        ],
      },
    ],
    words: U95_WORDS,
    exercises: [
      mcq(
        95,
        1,
        "Trong thang độ formality, \"kids\" thuộc mức nào?",
        [
          { key: "a", label: "Thân mật (informal)" },
          { key: "b", label: "Trang trọng nhất (formal)" },
          { key: "c", label: "Chỉ dùng trong biển báo" },
          { key: "d", label: "Chỉ dùng trong văn học thuật" },
        ],
        "a",
      ),
      fillBlank(
        95,
        2,
        "The study ____ a link between stress and ill-health.",
        "established",
        [
          { key: "a", label: "established" },
          { key: "b", label: "cheerioed" },
          { key: "c", label: "alighted" },
          { key: "d", label: "offspringed" },
        ],
        "a",
      ),
      mcq(
        95,
        3,
        "\"Utilise\" gần nghĩa trung tính nhất với từ nào?",
        [
          { key: "a", label: "use" },
          { key: "b", label: "kids" },
          { key: "c", label: "cheerio" },
          { key: "d", label: "spud" },
        ],
        "a",
      ),
      fillBlank(
        95,
        4,
        "Fees rose on ____ of higher living costs.",
        "account",
        [
          { key: "a", label: "account" },
          { key: "b", label: "amount" },
          { key: "c", label: "access" },
          { key: "d", label: "advice" },
        ],
        "a",
      ),
      mcq(
        95,
        5,
        "\"Go pear-shaped\" mang sắc thái nào?",
        [
          { key: "a", label: "Thân mật: mọi thứ hỏng / lệch kế hoạch" },
          { key: "b", label: "Trang trọng học thuật" },
          { key: "c", label: "Chỉ dùng trên biển báo giao thông" },
          { key: "d", label: "Đồng nghĩa với establish" },
        ],
        "a",
      ),
      fillBlank(
        95,
        6,
        "Wait until the bus is ____ before you get off.",
        "stationary",
        [
          { key: "a", label: "stationary" },
          { key: "b", label: "stationery" },
          { key: "c", label: "statuary" },
          { key: "d", label: "statutory" },
        ],
        "a",
      ),
      mcq(
        95,
        7,
        "\"In particular\" gần nghĩa với từ nào?",
        [
          { key: "a", label: "especially" },
          { key: "b", label: "never" },
          { key: "c", label: "instead" },
          { key: "d", label: "outdoors" },
        ],
        "a",
      ),
      fillBlank(
        95,
        8,
        "Physicists ____ answers to fundamental questions.",
        "seek",
        [
          { key: "a", label: "seek" },
          { key: "b", label: "cheerio" },
          { key: "c", label: "litter" },
          { key: "d", label: "poll" },
        ],
        "a",
      ),
    ],
  }),

  upperUnit(96, {
    introVi:
      "Unit 96 mở rộng từ thân mật một âm tiết, dạng rút gọn (clipping) và slang. Bạn sẽ nhận biết các từ sống động trong nói chuyện/báo lá cải — và nhớ giữ phần lớn slang ở vốn thụ động.",
    structureSections: [
      { label: "Monosyllabic informal words", wordCount: 7 },
      { label: "Clippings", wordCount: 6 },
      { label: "Slang for money, food and people", wordCount: 9 },
    ],
    collocationHtml: `${purple("go by tube")}, ${purple("ten quid")}, ${purple("fancy a cuppa")} và ${purple("put an ad in the paper")} là các cụm thân mật/rút gọn hay gặp.`,
    mistakeHtml: `${bold("Slang")} thay đổi nhanh và dễ dùng sai ngữ cảnh; sách khuyên giữ nhiều từ ở vốn thụ động. Phân biệt clipping chấp nhận rộng (${bold("lab")}, ${bold("fridge")}, ${bold("vet")}) với slang mạnh hơn (${bold("dosh")}, ${bold("nick")}, ${bold("quack")}).`,
    principles: [
      {
        title: "Từ thân mật một âm tiết",
        body: `${purple("cops")} = police; ${purple("loo")} = toilet; ${purple("quid")} = pound; ${purple("spud")} = potato; ${purple("tube")} = London Underground; ${purple("nick")} = prison; ${purple("cab")} = taxi.`,
        examples: [
          ex("The cops have arrived.", "Cảnh sát đã tới."),
          ex("It cost me ten quid.", "Nó tốn tôi mười bảng."),
        ],
      },
      {
        title: "Clippings (rút gọn)",
        body: `${purple("lab")}, ${purple("tech")}, ${purple("telly")}, ${purple("mag")}, ${purple("ad")} / advert, ${purple("celeb")} — rút gọn thường làm từ kém trang trọng hơn, nhưng nhiều dạng vẫn dùng rộng.`,
        examples: [
          ex("I'll meet you in the lab.", "Tôi gặp bạn ở phòng thí nghiệm."),
          ex("What's on telly tonight?", "Tối nay TV có gì?"),
        ],
      },
      {
        title: "Slang: tiền, đồ ăn, người",
        body: `Tiền: ${purple("dosh")}. Đồ ăn/uống: ${purple("nosh")}, ${purple("sarnie")}, ${purple("cuppa")}. Người: ${purple("geek")}, ${purple("nerd")}, ${purple("anorak")}, ${purple("shrink")}, ${purple("quack")}.`,
        examples: [
          ex("Fancy a cuppa?", "Uống tách trà không?"),
          ex("She's been seeing a shrink.", "Cô ấy đang gặp bác sĩ tâm thần."),
        ],
      },
    ],
    words: U96_WORDS,
    exercises: [
      mcq(
        96,
        1,
        "\"Quid\" trong tiếng Anh thân mật nghĩa là gì?",
        [
          { key: "a", label: "Bảng Anh (pound)" },
          { key: "b", label: "Cảnh sát" },
          { key: "c", label: "Nhà tù" },
          { key: "d", label: "Tạp chí" },
        ],
        "a",
      ),
      fillBlank(
        96,
        2,
        "I'll get a ____ from the station.",
        "cab",
        [
          { key: "a", label: "cab" },
          { key: "b", label: "curb" },
          { key: "c", label: "celeb" },
          { key: "d", label: "clash" },
        ],
        "a",
      ),
      mcq(
        96,
        3,
        "\"Telly\" là dạng rút gọn của từ nào?",
        [
          { key: "a", label: "television" },
          { key: "b", label: "telephone" },
          { key: "c", label: "telegram" },
          { key: "d", label: "telescope" },
        ],
        "a",
      ),
      fillBlank(
        96,
        4,
        "Fancy a ____ before we start work?",
        "cuppa",
        [
          { key: "a", label: "cuppa" },
          { key: "b", label: "curb" },
          { key: "c", label: "probe" },
          { key: "d", label: "ploy" },
        ],
        "a",
      ),
      mcq(
        96,
        5,
        "\"Shrink\" (slang) chỉ nghề nào?",
        [
          { key: "a", label: "Bác sĩ tâm thần" },
          { key: "b", label: "Lính cấp thấp" },
          { key: "c", label: "Tài xế taxi" },
          { key: "d", label: "Phóng viên" },
        ],
        "a",
      ),
      fillBlank(
        96,
        6,
        "His dad spent ten years in the ____.",
        "nick",
        [
          { key: "a", label: "nick" },
          { key: "b", label: "nosh" },
          { key: "c", label: "nerd" },
          { key: "d", label: "note" },
        ],
        "a",
      ),
      mcq(
        96,
        7,
        "Sách khuyên gì về slang?",
        [
          { key: "a", label: "Nên giữ phần lớn ở vốn thụ động; dễ dùng sai ngữ cảnh" },
          { key: "b", label: "Luôn dùng slang trong email công việc" },
          { key: "c", label: "Slang không bao giờ thay đổi" },
          { key: "d", label: "Slang chỉ xuất hiện trong từ điển học thuật" },
        ],
        "a",
      ),
      fillBlank(
        96,
        8,
        "We should put an ____ in the paper.",
        "ad",
        [
          { key: "a", label: "ad" },
          { key: "b", label: "aid" },
          { key: "c", label: "axe" },
          { key: "d", label: "ox" },
        ],
        "a",
      ),
    ],
  }),

  upperUnit(97, {
    introVi:
      "Unit 97 dạy simile cố định kiểu as … as và like …: hình ảnh dễ nhớ, thường thân mật/hài hước. Bạn sẽ hiểu nghĩa cả cụm và dùng chúng cẩn thận (một số có thể xúc phạm).",
    structureSections: [
      { label: "As … as picture similes", wordCount: 8 },
      { label: "Sound patterns and useful as … as", wordCount: 7 },
      { label: "Like-similes", wordCount: 7 },
    ],
    collocationHtml: `${purple("as cool as a cucumber")}, ${purple("as quick as a flash")}, ${purple("like a dream")} và ${purple("eyes like a hawk")} là các simile then chốt của unit.`,
    mistakeHtml: `Simile cố định thường ${bold("thân mật")} và mang tính cường điệu — giữ nhiều cụm ở vốn thụ động. Các mục đánh dấu tiêu cực trong sách (ví dụ ${bold("as blind as a bat")}, ${bold("as mad as a hatter")}) có thể xúc phạm. Phân biệt ${bold("as white as snow")} (đẹp) và ${bold("as white as a sheet")} (tái vì sợ).`,
    principles: [
      {
        title: "Simile as … as tạo hình ảnh",
        body: `${purple("as blind as a bat")}, ${purple("as thin as a rake")}, ${purple("as strong as an ox")}, ${purple("as quiet as a mouse")}; cặp đối: ${purple("as heavy as lead")} ≠ ${purple("as light as a feather")}; ${purple("as drunk as a lord")} ≠ ${purple("as sober as a judge")}.`,
        examples: [
          ex("He's as strong as an ox.", "Anh ấy khỏe như trâu."),
          ex("This suitcase is as heavy as lead.", "Chiếc vali này nặng như chì."),
        ],
      },
      {
        title: "Vần điệu và as … as hữu ích",
        body: `${purple("as cool as a cucumber")}, ${purple("as busy as a bee")}, ${purple("as hard as iron")}, ${purple("dry as a bone")}, ${purple("as bold as brass")}, ${purple("as easy as pie")}, ${purple("as quick as a flash")}, ${purple("as white as a sheet")}, ${purple("as sick as a parrot")}.`,
        examples: [
          ex("Passing this exam is as easy as pie.", "Thi cái này dễ như ăn kẹo."),
          ex("His face went as white as a sheet.", "Mặt anh ấy tái nhợt."),
        ],
      },
      {
        title: "Simile với like",
        body: `${purple("like a dream")} (suôn sẻ), ${purple("eyes like a hawk")}, ${purple("mind like a sieve")}; còn có eat like a horse, sleep like a log, like a bull in a china shop, like a red rag to a bull.`,
        examples: [
          ex("My plan worked like a dream.", "Kế hoạch của tôi chạy suôn sẻ tuyệt vời."),
          ex("I've got a mind like a sieve.", "Tôi hay quên như sàng thủng."),
        ],
      },
    ],
    words: U97_WORDS,
    exercises: [
      mcq(
        97,
        1,
        "\"As cool as a cucumber\" mô tả ai?",
        [
          { key: "a", label: "Người rất bình tĩnh" },
          { key: "b", label: "Người rất nóng tính" },
          { key: "c", label: "Người rất gầy" },
          { key: "d", label: "Người rất điếc" },
        ],
        "a",
      ),
      fillBlank(
        97,
        2,
        "She knew the answer as quick as a ____.",
        "flash",
        [
          { key: "a", label: "flash" },
          { key: "b", label: "flame" },
          { key: "c", label: "flood" },
          { key: "d", label: "floor" },
        ],
        "a",
      ),
      mcq(
        97,
        3,
        "\"As white as a sheet\" thường gợi điều gì?",
        [
          { key: "a", label: "Tái mặt vì sợ/hoảng" },
          { key: "b", label: "Da đẹp như cổ tích" },
          { key: "c", label: "Rất khỏe" },
          { key: "d", label: "Rất bận" },
        ],
        "a",
      ),
      fillBlank(
        97,
        4,
        "The soil's dry as a ____ — water the plant.",
        "bone",
        [
          { key: "a", label: "bone" },
          { key: "b", label: "bean" },
          { key: "c", label: "boat" },
          { key: "d", label: "book" },
        ],
        "a",
      ),
      mcq(
        97,
        5,
        "\"Eyes like a hawk\" nghĩa là gì?",
        [
          { key: "a", label: "Tinh mắt, để ý mọi thứ" },
          { key: "b", label: "Hay quên" },
          { key: "c", label: "Say rượu" },
          { key: "d", label: "Điếc đặc" },
        ],
        "a",
      ),
      fillBlank(
        97,
        6,
        "My plan worked like a ____.",
        "dream",
        [
          { key: "a", label: "dream" },
          { key: "b", label: "drama" },
          { key: "c", label: "drive" },
          { key: "d", label: "drill" },
        ],
        "a",
      ),
      mcq(
        97,
        7,
        "\"As sick as a parrot\" (thân mật) thường nói về cảm xúc nào?",
        [
          { key: "a", label: "Thất vọng / bực bội mạnh" },
          { key: "b", label: "Vui tột độ" },
          { key: "c", label: "Bình tĩnh" },
          { key: "d", label: "Tự hào" },
        ],
        "a",
      ),
      fillBlank(
        97,
        8,
        "I've got a mind like a ____ — I forgot again!",
        "sieve",
        [
          { key: "a", label: "sieve" },
          { key: "b", label: "sheet" },
          { key: "c", label: "spud" },
          { key: "d", label: "probe" },
        ],
        "a",
      ),
    ],
  }),

  upperUnit(98, {
    introVi:
      "Unit 98 giới thiệu tục ngữ Anh về lời khuyên, cảnh báo và hình ảnh động vật/khói–lửa–bếp núc. Bạn sẽ hiểu paraphrase và dùng proverb để bình luận tình huống một cách tự nhiên.",
    structureSections: [
      { label: "Advice and warnings", wordCount: 7 },
      { label: "Animal and bird key elements", wordCount: 5 },
      { label: "Visual proverbs and short forms", wordCount: 8 },
    ],
    collocationHtml: `${purple("Don't count your chickens")}, ${purple("cross that bridge when we come to it")}, ${purple("no smoke without fire")} và ${purple("too many cooks spoil the broth")} hay dùng để kết thúc câu chuyện/bình luận.`,
    mistakeHtml: `Proverb thường dùng để ${bold("bình luận")} tình huống, không phải dịch word-by-word. Nhiều tục ngữ có dạng rút gọn khi nói (${bold("count your chickens")}, ${bold("cross that bridge later")}). Phân biệt ${bold("Too many cooks spoil the broth")} (đông người xen vào thì hỏng) với ${bold("Many hands make light work")} (đông người giúp thì nhẹ việc).`,
    principles: [
      {
        title: "Lời khuyên và cảnh báo",
        body: `${purple("Don't count your chickens before they hatch")}; ${purple("Don't put all your eggs in one basket")}; ${purple("Never judge a book by its cover")}; ${purple("Never look a gift-horse in the mouth")}; ${purple("We'll cross that bridge when we come to it")}; tiết kiệm xu lẻ → bảng lớn.`,
        examples: [
          ex("Don't count your chickens before they hatch.", "Đừng tính chuyện chưa chắc xảy ra."),
          ex("We'll cross that bridge when we come to it.", "Đến đâu hay đến đó."),
        ],
      },
      {
        title: "Nhóm động vật/chim",
        body: `${purple("When the cat's away, the mice will play")}; ${purple("You can lead a horse to water but you can't make it drink")}; ${purple("One swallow doesn't make a summer")}.`,
        examples: [
          ex("When the cat's away, the mice will play.", "Vắng chủ thì người khác hành xử tự do hơn."),
          ex("One swallow doesn't make a summer.", "Một dấu hiệu tốt chưa đủ để kết luận mọi chuyện ổn."),
        ],
      },
      {
        title: "Hình ảnh và dạng rút gọn",
        body: `${purple("There's no smoke without fire")} / ${purple("Where there's smoke, there's fire")}; ${purple("People who live in glass houses shouldn't throw stones")}; ${purple("Too many cooks spoil the broth")} ≠ ${purple("Many hands make light work")}.`,
        examples: [
          ex("There's no smoke without fire.", "Không có lửa sao có khói."),
          ex("Many hands make light work.", "Đông người thì việc nhẹ hơn."),
        ],
      },
    ],
    words: U98_WORDS,
    exercises: [
      mcq(
        98,
        1,
        "\"Don't count your chickens before they hatch\" khuyên điều gì?",
        [
          { key: "a", label: "Đừng phụ thuộc vào chuyện chưa chắc xảy ra" },
          { key: "b", label: "Hãy nuôi thật nhiều gà" },
          { key: "c", label: "Luôn đánh giá qua vẻ ngoài" },
          { key: "d", label: "Nên dồn hết tiền vào một chỗ" },
        ],
        "a",
      ),
      fillBlank(
        98,
        2,
        "Don't put all your eggs in one ____.",
        "basket",
        [
          { key: "a", label: "basket" },
          { key: "b", label: "bucket" },
          { key: "c", label: "bottle" },
          { key: "d", label: "basement" },
        ],
        "a",
      ),
      mcq(
        98,
        3,
        "\"Never judge a book by its cover\" nghĩa là gì?",
        [
          { key: "a", label: "Đừng đánh giá người/việc chỉ qua vẻ ngoài" },
          { key: "b", label: "Đừng đọc sách thiếu bìa" },
          { key: "c", label: "Luôn tin tin đồn" },
          { key: "d", label: "Càng đông càng vui" },
        ],
        "a",
      ),
      fillBlank(
        98,
        4,
        "We'll cross that ____ when we come to it.",
        "bridge",
        [
          { key: "a", label: "bridge" },
          { key: "b", label: "broth" },
          { key: "c", label: "blaze" },
          { key: "d", label: "boost" },
        ],
        "a",
      ),
      mcq(
        98,
        5,
        "Phân biệt đúng nhất về \"too many cooks\" và \"many hands\"?",
        [
          {
            key: "a",
            label: "too many cooks = đông xen vào thì hỏng; many hands = đông giúp thì nhẹ việc",
          },
          { key: "b", label: "Hai tục ngữ hoàn toàn đồng nghĩa" },
          { key: "c", label: "many hands luôn mang nghĩa tiêu cực" },
          { key: "d", label: "too many cooks chỉ nói về nấu ăn thật" },
        ],
        "a",
      ),
      fillBlank(
        98,
        6,
        "There's no smoke without ____.",
        "fire",
        [
          { key: "a", label: "fire" },
          { key: "b", label: "fear" },
          { key: "c", label: "fare" },
          { key: "d", label: "file" },
        ],
        "a",
      ),
      mcq(
        98,
        7,
        "\"You can lead a horse to water but you can't make it drink\" nói về điều gì?",
        [
          { key: "a", label: "Có thể khuyên/thuyết phục nhưng không ép được ai" },
          { key: "b", label: "Ngựa luôn từ chối uống nước" },
          { key: "c", label: "Nên dồn hết trứng vào một giỏ" },
          { key: "d", label: "Tin đồn luôn sai hoàn toàn" },
        ],
        "a",
      ),
      fillBlank(
        98,
        8,
        "Too many cooks spoil the ____.",
        "broth",
        [
          { key: "a", label: "broth" },
          { key: "b", label: "bridge" },
          { key: "c", label: "blaze" },
          { key: "d", label: "boost" },
        ],
        "a",
      ),
    ],
  }),

  upperUnit(99, {
    introVi:
      "Unit 99 dạy ngôn ngữ biển báo và thông báo công cộng: từ trang trọng ít gặp trong hội thoại hàng ngày. Bạn sẽ \"dịch\" biển báo sang tiếng Anh đời thường và hiểu lệnh cấm/hướng dẫn.",
    structureSections: [
      { label: "Travel and access notices", wordCount: 7 },
      { label: "Rules and restrictions", wordCount: 7 },
      { label: "Service and safety wording", wordCount: 7 },
    ],
    collocationHtml: `${purple("until further notice")}, ${purple("accompanied by an adult")}, ${purple("permit holders only")} và ${purple("please refrain from")} là các cụm biển báo then chốt.`,
    mistakeHtml: `Ngôn ngữ biển báo thường ${bold("trang trọng và rút gọn")}. ${bold("Alight")} ≈ get off; ${bold("refrain from")} ≈ please don't; ${bold("unauthorized entry")} ≈ you may not enter without permission. Đọc cả cụm, không chỉ từng từ.`,
    principles: [
      {
        title: "Đi lại và lối vào",
        body: `${purple("alight here")}; ${purple("no through road")}; ${purple("boarding")}; ${purple("in motion")}; ${purple("cyclists dismount")}; ${purple("admission")}; ${purple("accompanied by an adult")}.`,
        examples: [
          ex("Alight here for Buckingham Palace.", "Xuống xe tại đây để tới Buckingham Palace."),
          ex("Under-18s only if accompanied by an adult.", "Dưới 18 chỉ vào khi có người lớn đi cùng."),
        ],
      },
      {
        title: "Quy định và hạn chế",
        body: `${purple("trespassers will be prosecuted")}; ${purple("litter")} / ${purple("penalty")}; ${purple("unauthorized entry")}; ${purple("staff only")}; ${purple("permit holders only")}; ${purple("do not feed the animals")}; ${purple("refrain from")}.`,
        examples: [
          ex("Trespassers will be prosecuted.", "Người xâm nhập sẽ bị kiện."),
          ex("Please refrain from using mobile phones.", "Xin hãy không dùng điện thoại."),
        ],
      },
      {
        title: "Dịch vụ và an toàn",
        body: `${purple("refreshments")}; ${purple("display your ticket")}; ${purple("until further notice")}; ${purple("lift capacity")}; ${purple("we regret")}; ${purple("reduce speed now")}.`,
        examples: [
          ex("Closed until further notice.", "Đóng cửa cho đến khi có thông báo mới."),
          ex("We regret we no longer accept cheques.", "Chúng tôi rất tiếc không còn nhận séc."),
        ],
      },
    ],
    words: U99_WORDS,
    exercises: [
      mcq(
        99,
        1,
        "Trên biển báo, \"alight here\" nghĩa đời thường là gì?",
        [
          { key: "a", label: "Get off here" },
          { key: "b", label: "Light a fire here" },
          { key: "c", label: "Buy a ticket here" },
          { key: "d", label: "Park here" },
        ],
        "a",
      ),
      fillBlank(
        99,
        2,
        "The stairway is closed until further ____.",
        "notice",
        [
          { key: "a", label: "notice" },
          { key: "b", label: "nosh" },
          { key: "c", label: "nick" },
          { key: "d", label: "nerd" },
        ],
        "a",
      ),
      mcq(
        99,
        3,
        "\"Trespassers will be prosecuted\" cảnh báo điều gì?",
        [
          { key: "a", label: "Người vào đất tư trái phép có thể bị đưa ra tòa" },
          { key: "b", label: "Được miễn phí vào cửa" },
          { key: "c", label: "Phải cho thú ăn" },
          { key: "d", label: "Được phép đi xe đạp" },
        ],
        "a",
      ),
      fillBlank(
        99,
        4,
        "Please ____ from using mobile phones in the hall.",
        "refrain",
        [
          { key: "a", label: "refrain" },
          { key: "b", label: "refresh" },
          { key: "c", label: "reduce" },
          { key: "d", label: "regret" },
        ],
        "a",
      ),
      mcq(
        99,
        5,
        "\"Cyclists dismount\" yêu cầu gì?",
        [
          { key: "a", label: "Người đi xe đạp phải xuống xe" },
          { key: "b", label: "Phải tăng tốc" },
          { key: "c", label: "Chỉ nhân viên được vào" },
          { key: "d", label: "Được vứt rác" },
        ],
        "a",
      ),
      fillBlank(
        99,
        6,
        "Do not speak to the driver while the bus is in ____.",
        "motion",
        [
          { key: "a", label: "motion" },
          { key: "b", label: "mag" },
          { key: "c", label: "moolah" },
          { key: "d", label: "move-up" },
        ],
        "a",
      ),
      mcq(
        99,
        7,
        "\"Permit holders only\" nghĩa là gì?",
        [
          { key: "a", label: "Chỉ người có giấy phép mới được" },
          { key: "b", label: "Miễn phí cho mọi người" },
          { key: "c", label: "Chỉ trẻ em được vào" },
          { key: "d", label: "Cấm toàn bộ khu vực vĩnh viễn" },
        ],
        "a",
      ),
      fillBlank(
        99,
        8,
        "Please ____ your ticket where it can be seen.",
        "display",
        [
          { key: "a", label: "display" },
          { key: "b", label: "dismount" },
          { key: "c", label: "deposit" },
          { key: "d", label: "delay" },
        ],
        "a",
      ),
    ],
  }),

  upperUnit(100, {
    introVi:
      "Unit 100 dạy \"Headline English\": ngữ pháp rút gọn trên tiêu đề báo và các từ ngắn, kịch tính thay cho từ đời thường. Bạn sẽ đọc headline nhanh hơn và nắm nghĩa aid, axe, probe, vow…",
    structureSections: [
      { label: "Dramatic action words", wordCount: 8 },
      { label: "Conflict, limits and campaigns", wordCount: 7 },
      { label: "Promises, probes and people events", wordCount: 7 },
    ],
    collocationHtml: `${purple("axe jobs")}, ${purple("launch a probe")}, ${purple("give the go-ahead")} và ${purple("make a plea")} là collocation headline thường gặp.`,
    mistakeHtml: `Headline thường ${bold("bỏ mạo từ/trợ động từ")}, dùng hiện tại đơn cho sự kiện gần, và dùng ${bold("to + V")} cho tương lai (PRESIDENT TO VISIT…). Nhiều từ vừa là danh từ vừa động từ (${bold("aid")}, ${bold("cut")}, ${bold("boost")}). Nghĩa headline có thể hẹp/kịch tính hơn tiếng Anh thường ngày.`,
    principles: [
      {
        title: "Từ hành động kịch tính",
        body: `${purple("aid")} = help; ${purple("axe")} = cut/remove; ${purple("back")} = support; ${purple("bar")} = forbid; ${purple("bid")} = attempt; ${purple("blast")} = explosion; ${purple("blaze")} = fire; ${purple("boost")} = encourage/increase.`,
        examples: [
          ex("Firm to axe 200 jobs.", "Công ty sẽ cắt 200 việc làm."),
          ex("Unions back pay deal.", "Công đoàn ủng hộ thỏa thuận lương."),
        ],
      },
      {
        title: "Xung đột, hạn chế và chiến dịch",
        body: `${purple("clash")}, ${purple("curb")}, ${purple("drive")} (campaign), ${purple("go-ahead")}, ${purple("oust")}, ${purple("ordeal")}, ${purple("ploy")}.`,
        examples: [
          ex("Police clash with protesters.", "Cảnh sát đụng độ người biểu tình."),
          ex("Council gives go-ahead for bridge.", "Hội đồng cấp phép xây cầu."),
        ],
      },
      {
        title: "Lời kêu gọi, điều tra và sự kiện",
        body: `${purple("plea")}, ${purple("pledge")}, ${purple("poll")}, ${purple("probe")}, ${purple("quit")}, ${purple("vow")}, ${purple("wed")}.`,
        examples: [
          ex("Police launch probe into fraud.", "Cảnh sát mở cuộc điều tra gian lận."),
          ex("Leaders vow to fight corruption.", "Lãnh đạo thề chống tham nhũng."),
        ],
      },
    ],
    words: U100_WORDS,
    exercises: [
      mcq(
        100,
        1,
        "Trong headline, \"axe\" thường nghĩa là gì?",
        [
          { key: "a", label: "Cắt giảm / loại bỏ" },
          { key: "b", label: "Ủng hộ" },
          { key: "c", label: "Kết hôn" },
          { key: "d", label: "Thăm dò ý kiến" },
        ],
        "a",
      ),
      fillBlank(
        100,
        2,
        "Police launch a ____ into the fraud claims.",
        "probe",
        [
          { key: "a", label: "probe" },
          { key: "b", label: "ploy" },
          { key: "c", label: "plea" },
          { key: "d", label: "poll" },
        ],
        "a",
      ),
      mcq(
        100,
        3,
        "\"Back\" dùng như động từ trên headline nghĩa là gì?",
        [
          { key: "a", label: "Ủng hộ / support" },
          { key: "b", label: "Đi lùi" },
          { key: "c", label: "Đốt cháy" },
          { key: "d", label: "Từ chức" },
        ],
        "a",
      ),
      fillBlank(
        100,
        4,
        "The council gave the ____ for the new stadium.",
        "go-ahead",
        [
          { key: "a", label: "go-ahead" },
          { key: "b", label: "get-off" },
          { key: "c", label: "go-amiss" },
          { key: "d", label: "go-pear" },
        ],
        "a",
      ),
      mcq(
        100,
        5,
        "\"Blaze\" trên headline thường chỉ gì?",
        [
          { key: "a", label: "Đám cháy lớn" },
          { key: "b", label: "Cuộc bầu cử" },
          { key: "c", label: "Lời hứa" },
          { key: "d", label: "Đám cưới" },
        ],
        "a",
      ),
      fillBlank(
        100,
        6,
        "Parents make a ____ for help finding their child.",
        "plea",
        [
          { key: "a", label: "plea" },
          { key: "b", label: "ploy" },
          { key: "c", label: "poll" },
          { key: "d", label: "pants" },
        ],
        "a",
      ),
      mcq(
        100,
        7,
        "\"Wed\" trên headline nghĩa là gì?",
        [
          { key: "a", label: "Kết hôn / marry" },
          { key: "b", label: "Từ chức" },
          { key: "c", label: "Cấm cửa" },
          { key: "d", label: "Điều tra" },
        ],
        "a",
      ),
      fillBlank(
        100,
        8,
        "MPs try to ____ the party leader.",
        "oust",
        [
          { key: "a", label: "oust" },
          { key: "b", label: "aid" },
          { key: "c", label: "wed" },
          { key: "d", label: "vow" },
        ],
        "a",
      ),
    ],
  }),

  upperUnit(101, {
    introVi:
      "Unit 101 so sánh tiếng Anh Mỹ và Anh: cặp từ đi lại/nhà cửa, khác biệt chính tả nhẹ, và vài từ dễ gây hiểu nhầm (pants, check/bill…). Bạn sẽ chọn đúng biến thể theo ngữ cảnh AmE/BrE.",
    structureSections: [
      { label: "Travel and street pairs", wordCount: 8 },
      { label: "Home and everyday pairs", wordCount: 8 },
      { label: "Confusable AmE/BrE meanings", wordCount: 6 },
    ],
    collocationHtml: `${purple("on the weekend")} (AmE) / ${purple("at the weekend")} (BrE), ${purple("round trip")} / ${purple("return")}, và ${purple("parking lot")} / ${purple("car park")} là các cặp then chốt.`,
    mistakeHtml: `${bold("Pants")}: AmE ≈ trousers; BrE thường ≈ underpants. ${bold("Bill")}: BrE = hóa đơn nhà hàng; AmE ${bold("check")} mới là hóa đơn, còn bill AmE có thể là tờ tiền. ${bold("Second floor")}: AmE ≈ BrE first floor. Chính tả: colour/color, centre/center, realise/realize.`,
    principles: [
      {
        title: "Cặp từ đi lại / đường phố",
        body: `${purple("gas / petrol")}, ${purple("truck / lorry")}, ${purple("sidewalk / pavement")}, ${purple("crosswalk / zebra crossing")}, ${purple("line / queue")}, ${purple("freeway / motorway")}, ${purple("trunk / boot")}, ${purple("hood / bonnet")}, ${purple("subway / underground")}, ${purple("round trip / return")}.`,
        examples: [
          ex("Fill the tank: gas / petrol means the same fuel.", "AmE gas = BrE petrol (xăng)."),
          ex("Keep bikes off the sidewalk / pavement.", "Cùng nghĩa vỉa hè."),
        ],
      },
      {
        title: "Cặp từ nhà cửa và đời sống",
        body: `${purple("vacation / holiday")}, ${purple("parking lot / car park")}, ${purple("garbage / rubbish")}, ${purple("elevator / lift")}, ${purple("apartment / flat")}, ${purple("flashlight / torch")}, ${purple("cookie / biscuit")}, ${purple("candy / sweets")}, ${purple("diaper / nappy")}, ${purple("fall / autumn")}.`,
        examples: [
          ex("Take the elevator / lift to floor three.", "Thang máy."),
          ex("Leaves change colour in fall / autumn.", "Mùa thu."),
        ],
      },
      {
        title: "Nghĩa dễ gây nhầm",
        body: `${purple("pants / trousers")} (AmE pants ≈ BrE trousers; BrE pants thường = quần lót); hóa đơn nhà hàng: ${purple("check / bill")}. Nhớ thêm: AmE second floor ≈ BrE first floor; wash up cũng lệch nghĩa giữa hai biến thể.`,
        examples: [
          ex("Could we have the check / bill, please?", "Xin hóa đơn."),
          ex("AmE pants / trousers means long outer wear.", "Quần dài — không phải quần lót (BrE pants)."),
        ],
      },
    ],
    words: U101_WORDS,
    exercises: [
      mcq(
        101,
        1,
        "\"Petrol\" (BrE) tương ứng từ AmE nào?",
        [
          { key: "a", label: "gas / gasoline" },
          { key: "b", label: "garbage" },
          { key: "c", label: "elevator" },
          { key: "d", label: "cookie" },
        ],
        "a",
      ),
      fillBlank(
        101,
        2,
        "Keep bikes off the sidewalk / ____.",
        "pavement",
        [
          { key: "a", label: "pavement" },
          { key: "b", label: "petrol" },
          { key: "c", label: "probe" },
          { key: "d", label: "ploy" },
        ],
        "a",
      ),
      mcq(
        101,
        3,
        "Cặp \"apartment / flat\" chỉ gì?",
        [
          { key: "a", label: "Căn hộ (AmE apartment; BrE flat)" },
          { key: "b", label: "Xe tải" },
          { key: "c", label: "Tã em bé" },
          { key: "d", label: "Nắp capo" },
        ],
        "a",
      ),
      fillBlank(
        101,
        4,
        "Take the elevator / ____ to floor three.",
        "lift",
        [
          { key: "a", label: "lift" },
          { key: "b", label: "line" },
          { key: "c", label: "loo" },
          { key: "d", label: "lab" },
        ],
        "a",
      ),
      mcq(
        101,
        5,
        "Với cặp \"pants / trousers\", lưu ý quan trọng là gì?",
        [
          { key: "a", label: "AmE pants ≈ BrE trousers; BrE pants thường = quần lót" },
          { key: "b", label: "Hai từ luôn đồng nghĩa tuyệt đối ở cả hai biến thể" },
          { key: "c", label: "Chỉ dùng cho xăng xe" },
          { key: "d", label: "Chỉ xuất hiện trên headline báo" },
        ],
        "a",
      ),
      fillBlank(
        101,
        6,
        "Leaves change colour in fall / ____.",
        "autumn",
        [
          { key: "a", label: "autumn" },
          { key: "b", label: "august" },
          { key: "c", label: "airport" },
          { key: "d", label: "apartment" },
        ],
        "a",
      ),
      mcq(
        101,
        7,
        "Cặp \"check / bill\" trong nhà hàng nghĩa là gì?",
        [
          { key: "a", label: "Hóa đơn thanh toán (AmE check; BrE bill)" },
          { key: "b", label: "Vé khứ hồi" },
          { key: "c", label: "Đèn pin" },
          { key: "d", label: "Bãi đỗ xe" },
        ],
        "a",
      ),
      fillBlank(
        101,
        8,
        "A delivery truck / ____ blocked the street.",
        "lorry",
        [
          { key: "a", label: "lorry" },
          { key: "b", label: "loo" },
          { key: "c", label: "lab" },
          { key: "d", label: "line" },
        ],
        "a",
      ),
    ],
  }),
];
