export const CURATED_EXERCISE_PROMPT_VI_16_30: Readonly<Record<string, string>> = {
  "ex-16-2-1": "Bạn bỏ thư qua khe ở ___ trên phố.",
  "ex-16-2-2": "___ là hộp nhỏ trên phố để gọi điện.",
  "ex-16-2-3": "Điện thoại ___ là điện thoại mang theo người.",
  "ex-16-2-4": "Bạn dán ___ lên phong bì trước khi gửi.",
  "ex-16-2-5": "Viết tên và ___ trên phong bì.",
  "ex-16-2-6": "Cho thư vào ___ trước khi gửi.",
  "ex-16-2-7": "___ máy tính hiển thị hình và chữ.",
  "ex-16-2-8": "___ là máy tính nhỏ mang theo được.",
  "ex-16-2-9": "Thẻ ___ lưu trữ file máy tính.",
  "ex-16-2-10": "Bạn dùng ___ để di chuyển con trỏ trên máy tính.",
  "ex-16-2-11": "Cầm ___ lên và quay số.",
  "ex-16-3-1": "MEENA: Xin chào. ___ Meena đây. Tôi có thể nói chuyện với Amal được không?",
  "ex-16-3-2": "MEENA: Tôi có thể ___ với Amal được không?",
  "ex-16-3-3": "AMELIA: ___ , anh ấy đang đi làm lúc này.",
  "ex-16-3-4": "AMELIA: Anh ấy đang đi làm ___ giờ này.",
  "ex-16-3-5": "AMELIA: Tôi có thể ___ lời nhắn không?",
  "ex-16-3-6": "MEENA: Tôi sẽ ___ lại sau.",
  "ex-17-1": "Ghép bộ phận điện thoại bên trái với chức năng bên phải",
  "ex-17-2-1": "Tanya có ___ mới để nhắn tin trên Internet.",
  "ex-17-2-2": "Khi pin điện thoại yếu, bạn cần ___.",
  "ex-17-2-3": "Bạn có thể dùng điện thoại của tôi để ___ Megan.",
  "ex-17-2-4": "Điện thoại mới của Danny có ___ rất tốt. Nó chụp ảnh tuyệt vời.",
  "ex-17-2-5": "Tôi mua ___ mới ở Pháp để gọi điện và dùng Internet rẻ hơn.",
  "ex-17-2-6": "Tôi muốn mua ___ mới. Cái này cũ và bẩn rồi.",
  "ex-17-3-1": "Maria đã ___ cho tôi tối qua, nhưng tôi mới thấy tin nhắn sáng nay.",
  "ex-17-3-2": "Carlos ___ rất nhiều ảnh chú chó mới và đăng lên Facebook.",
  "ex-17-3-3": "Ứng dụng cuối cùng bạn ___ là gì?",
  "ex-17-3-4": "Lucy đã ___ chị gái. Họ nói về kỳ nghỉ ở bãi biển.",
  "ex-17-3-5": "Victor đã ___ cho tôi một voicemail. Anh ấy bảo tôi gọi lại.",
  "ex-17-4-1": "IREENA: Để tôi nhập PIN để ___ nó.",
  "ex-17-4-2": "DEEPA: Tôi có ___ sang phải để xem ảnh tiếp không?",
  "ex-17-4-3": "IREENA: Tôi đã ___ chúng vào thư mục khác.",
  "ex-18-1-1": "A: Thứ Hai bạn có đi làm không? B: Không, tôi đang ___ kỳ nghỉ.",
  "ex-18-1-2": "A: Năm nay bạn có đi nghỉ không? B: Có, tôi sẽ ___ cắm trại.",
  "ex-18-1-3": "A: Bạn có kỳ nghỉ vui ở Hy Lạp không? B: Có, thật tuyệt vời.",
  "ex-18-1-4": "A: Bạn bay đến Ý à? B: Không, tôi đi ___ tàu hỏa.",
  "ex-18-1-5": "A: Tuần sau tôi đến New York. B: Tuyệt! Hãy ___ cho tôi một bưu thiếp.",
  "ex-18-2-1": "Vui nhưng lều rất nhỏ. Đây là kỳ nghỉ ___.",
  "ex-18-2-2": "Mọi thứ đã bao gồm — khách sạn và chuyến bay.",
  "ex-18-2-3": "Chúng tôi ngồi trên xe buýt du lịch bảy ngày. Tôi rất mệt.",
  "ex-18-2-4": "Chúng tôi đi bộ khoảng 20 km mỗi ngày.",
  "ex-18-2-5": "Chúng tôi đến Thụy Sĩ vào tháng 12. Có rất nhiều tuyết.",
  "ex-18-4-1": "Đừng quên ___ khi đến nước khác.",
  "ex-18-4-2": "Mang theo ___ để chụp ảnh khi đi nghỉ.",
  "ex-18-4-3": "Bạn cần ___ cho máy bay hoặc tàu hỏa.",
  "ex-18-5-1": "Bạn có thể cần ___ — một tem đặc biệt trong hộ chiếu.",
  "ex-18-5-2": "Chúng tôi bay đến đó bằng ___.",
  "ex-18-5-3": "___ là túi đeo sau lưng.",
  "ex-18-6-1": "Tôi đang có khoảng thời gian ___ tuyệt vời ở Tây Ban Nha.",
  "ex-18-6-2": "___ ở đây tuyệt — các club mở cả đêm.",
  "ex-18-6-3": "Đồ ăn ___ rất ngon — nhiều cá và salad.",
  "ex-18-6-4": "Hãy gửi cho tôi một ___ từ kỳ nghỉ ở Ý của bạn.",
  "ex-19-1": "Ghép món hàng bên trái với loại cửa hàng bên phải",
  "ex-19-2-1": "Tôi muốn mua báo. Tôi cần đến ___.",
  "ex-19-2-2": "Tôi muốn mua thức ăn cho một tuần. Tôi sẽ đến ___.",
  "ex-19-2-3": "Tôi cần tem. Tôi sẽ đến ___.",
  "ex-19-2-4": "Chúng ta phải mua quà cho Michael. Hãy đến ___.",
  "ex-19-2-5": "Tôi muốn mua sách. Tôi sẽ đến ___.",
  "ex-19-3-1": "Son môi ở tầng ___ (Beauty).",
  "ex-19-3-2": "Ghế bành ở tầng ___ (Furniture).",
  "ex-19-3-3": "Váy ở tầng ___ (Women's Wear).",
  "ex-19-3-4": "TV ở ___ (Electricals).",
  "ex-19-4-1": "Tiền (không phải séc hay thẻ tín dụng/ghi nợ) gọi là ___",
  "ex-19-4-2": "Tờ giấy trị giá £20 là ___",
  "ex-19-4-3": "'Tiền nhựa' nghĩa là ___",
  "ex-19-4-4": "Tiền xu hoặc tiền giấy nhỏ hơn gọi là ___",
  "ex-19-5-1": "Biển báo nào cho biết bạn không thể vào cửa hàng?",
  "ex-19-5-2": "Biển báo nào cho biết cửa sẽ mở về phía bạn?",
  "ex-19-5-3": "Biển báo nào cho biết cửa sẽ mở hướng ra ngoài?",
  "ex-19-6-1": "KHÁCH: Chiếc áo khoác này ___ bao nhiêu?",
  "ex-19-6-2": "KHÁCH: Tôi có thể ___ bằng thẻ tín dụng không?",
  "ex-19-6-3": "NHÂN VIÊN: Bạn có muốn (túi) ___ không?",
  "ex-20-1": "Ghép thuật ngữ mua hàng online bên trái với ví dụ bên phải",
  "ex-20-2-1": "Khi mua hàng online, bạn có thể ___ để tìm giá tốt nhất.",
  "ex-20-2-2": "Bạn có thể đọc ___ từ người đã mua cùng món.",
  "ex-20-2-3": "Nếu muốn mua, hãy ___ vào giỏ hàng.",
  "ex-20-2-4": "Nếu không muốn mua món trong giỏ, bạn có thể ___ nó.",
  "ex-20-2-5": "Đừng quên kiểm tra bạn sẽ trả bao nhiêu cho ___.",
  "ex-20-2-6": "Bạn có thể dùng ___ để thanh toán.",
  "ex-20-3-1": "TOM: Tôi đang chờ ___ một đôi giày.",
  "ex-20-3-2": "CHĂM SÓC KHÁCH: Mã ___ của bạn là gì?",
  "ex-20-3-3": "TOM: 31 Mill Road, WC2 5SN. Địa chỉ và ___ của bạn là gì?",
  "ex-20-3-4": "Tôi trả £5 cho giao hàng ___.",
  "ex-20-4-1": "Bước ĐẦU TIÊN khi mua máy tính online là gì?",
  "ex-20-4-2": "Sau khi tìm được website, bạn làm gì tiếp?",
  "ex-20-4-3": "SAU KHI chọn máy tính, bạn làm gì?",
  "ex-20-4-4": "Bước CUỐI CÙNG là gì?",
  "ex-21-1-1": "LỄ TÂN: Bạn có muốn phòng ___ có phòng tắm không?",
  "ex-21-1-2": "KHÁCH: Vâng. Và nhìn ra ___, làm ơn.",
  "ex-21-1-3": "LỄ TÂN: Tất cả phòng có TV, ___ và vòi sen.",
  "ex-21-1-4": "LỄ TÂN: Đây là ___ của bạn.",
  "ex-21-1-5": "LỄ TÂN: ___ ở ngay đó.",
  "ex-21-2": "Ghép nhu cầu bên trái với thứ bạn cần bên phải",
  "ex-21-3-1": "Ở ___ bạn có thể gọi dịch vụ phòng.",
  "ex-21-3-2": "Chúng tôi muốn phòng ___ nhìn ra vườn.",
  "ex-21-3-3": "___ ở ngay đó. Đi tới tầng hai.",
  "ex-21-3-4": "Vui lòng ___ vào mẫu này.",
  "ex-21-3-5": "Tôi muốn được gọi ___ lúc 7 giờ 30.",
  "ex-21-3-6": "Tôi có ___ phòng đơn có phòng tắm.",
  "ex-21-4-1": "Tôi có thể được gọi ___ không?",
  "ex-21-4-2": "Tôi có thể ăn sáng trong ___ không?",
  "ex-21-4-3": "Cho tôi xem ___, làm ơn.",
  "ex-21-4-4": "Tôi có thể có phòng ___ cho tối nay không?",
  "ex-22-1-1": "Bạn sẽ đến đâu để mua bữa ăn mang về?",
  "ex-22-1-2": "Bạn sẽ đến đâu để có bữa tối lãng mạn cho hai người?",
  "ex-22-1-3": "Bạn sẽ đến đâu để ăn trưa nhanh?",
  "ex-22-1-4": "Bạn sẽ đến đâu để ăn bánh và uống cà phê?",
  "ex-22-1-5": "Bạn sẽ đến đâu để uống rượu vang với bạn bè?",
  "ex-22-3-1": "Bạn có thể dùng súp cà chua / rau / gà ___ làm món khai vị.",
  "ex-22-3-2": "Tôi muốn món bò / gà / rau ___ làm món chính.",
  "ex-22-3-3": "Tôi sẽ lấy ___ trộn / cà chua / trái cây.",
  "ex-22-3-4": "Cho tôi bánh táo / gà ___, làm ơn.",
  "ex-22-3-5": "Bạn thích ___ chín kỹ, vừa hay tái?",
  "ex-22-4-1": "PHỤC VỤ: Bạn sẵn sàng ___ chưa?",
  "ex-22-4-2": "KHÁCH: Vâng, tôi ___ súp rau và bít tết.",
  "ex-22-4-3": "PHỤC VỤ: Bạn muốn bít tết tái, vừa hay chín ___?",
  "ex-22-4-4": "PHỤC VỤ: Bạn muốn ___ uống gì?",
  "ex-22-4-5": "KHÁCH: ___ nước cam, làm ơn.",
  "ex-22-4-6": "KHÁCH: Một ly nước ___, làm ơn.",
  "ex-23-1-1": "Người ta đá bóng vào khung thành trong môn thể thao này.",
  "ex-23-1-2": "Người ta bơi trong nước trong môn thể thao này.",
  "ex-23-1-3": "Người ta đấu bằng judo hoặc karate.",
  "ex-23-1-4": "Người ta đua xe rất nhanh trong môn thể thao này.",
  "ex-23-1-5": "Người ta đánh bóng qua lưới trên bãi biển hoặc sân.",
  "ex-23-1-6": "Người ta dùng thuyền và gió trên mặt nước.",
  "ex-23-2-1": "Bạn cần vợt và cầu lông cho ___.",
  "ex-23-2-2": "Bạn chơi ___ trên bàn với vợt nhỏ.",
  "ex-23-2-3": "Bạn cần ván trượt cho ___.",
  "ex-23-2-4": "Bạn ném và bắt bóng bằng găng trong ___.",
  "ex-23-2-5": "Bạn ném bóng vào rổ trong ___.",
  "ex-23-2-6": "Bạn trượt trên tuyết với một ván trong ___.",
  "ex-23-3-1": "___ bạn chơi bóng đá không?",
  "ex-23-3-2": "___ bạn có chơi môn thể thao nào không?",
  "ex-23-3-3": "___ bạn có đi bơi không?",
  "ex-23-3-4": "___ là môn thể thao yêu thích của bạn?",
  "ex-23-3-5": "Ở đâu ___ người ta chơi rugby?",
  "ex-24-1-2": "Một đĩa bay từ sao Hỏa hạ cánh.",
  "ex-24-1-3": "Người chết sống lại.",
  "ex-24-1-4": "James Bond cứu thế giới.",
  "ex-24-1-5": "Mickey Mouse đi picnic.",
  "ex-24-1-6": "Một người đàn ông yêu cô giáo của mình.",
  "ex-24-1-7": "Một xác chết được tìm thấy trong sông.",
  "ex-24-1-8": "Có rất nhiều bài hát và khiêu vũ.",
  "ex-24-3-1": "Phim khiến bạn sợ gọi là ___.",
  "ex-24-3-2": "Phim khiến bạn cười gọi là ___.",
  "ex-24-3-3": "Phim có nhiều đánh nhau và đuổi xe gọi là phim ___.",
  "ex-24-3-4": "Phim về tương lai và không gian là phim ___ fiction.",
  "ex-24-3-5": "Phim có hát và nhảy gọi là ___.",
  "ex-24-3-6": "Phim hoạt hình cho trẻ em gọi là ___.",
  "ex-24-4-1": "Tối qua chúng tôi ___ một DVD.",
  "ex-24-4-2": "Daniel Radcliffe ___ Harry Potter trong phim Harry Potter.",
  "ex-24-4-3": "Monica Bellucci là ___ phim.",
  "ex-24-4-4": "Steven Spielberg là ___ phim người Mỹ nổi tiếng.",
  "ex-24-4-5": "Rachel Weisz có ___ The Constant Gardener không?",
  "ex-25-1-1": "Cô ấy đang xem TV.",
  "ex-25-1-2": "Anh ấy đang đọc báo.",
  "ex-25-1-3": "Anh ấy đang nấu ăn.",
  "ex-25-1-4": "Cô ấy đang dùng Internet.",
  "ex-25-1-5": "Cô ấy đang nghe nhạc.",
  "ex-25-1-6": "Anh ấy đang làm vườn.",
  "ex-25-2-1": "Tôi thường ___ nhạc trên laptop ở nhà.",
  "ex-25-2-2": "Tôi thích ___ tạp chí hơn báo.",
  "ex-25-2-3": "Tôi ___ với chị gái qua điện thoại mỗi Chủ nhật.",
  "ex-25-2-4": "Nhiều người thích ___ một giấc sau bữa trưa.",
  "ex-25-2-5": "Bạn có bao giờ ___ bạn bè đến ăn tối không?",
  "ex-25-2-6": "Trẻ em ___ video game mỗi tối.",
  "ex-25-2-7": "Tối nay tôi muốn ___ nhạc từ Internet.",
  "ex-25-2-8": "Hôm qua bạn có ___ chương trình về Namibia không?",
  "ex-25-2-9": "Bố tôi ___ rau trong vườn.",
  "ex-25-2-10": "Tối nay chúng ta ___ một DVD nhé?",
  "ex-26-1-1": "Loại ___ yêu thích của bạn là gì?",
  "ex-26-1-2": "Anh trai tôi nghĩ mình là ___ giỏi, nhưng anh ấy rất tệ!",
  "ex-26-1-3": "Bạn có chơi được nhạc cụ ___ không?",
  "ex-26-1-4": "Tôi thích nhiều loại ___, ví dụ jazz, rock và classical.",
  "ex-26-1-5": "Trong gia đình bạn có ___ nào không?",
  "ex-26-1-6": "Ban nhạc chơi ___ tuyệt vời hơn hai giờ.",
  "ex-26-2-1": "Madison chơi ___ trong dàn nhạc giao hưởng.",
  "ex-26-2-2": "Noah thích chơi ___.",
  "ex-26-2-3": "Emily đang học ___.",
  "ex-26-2-4": "Mason là người chơi ___ rất giỏi.",
  "ex-26-2-5": "Ella chơi ___ mỗi tối.",
  "ex-26-2-6": "William chơi ___.",
  "ex-26-2-7": "Emma đang học ___.",
  "ex-26-2-8": "Lucas là một ___ xuất sắc.",
  "ex-26-3-1": "Tôi thích nhạc ___. Beethoven là người tôi yêu thích nhất.",
  "ex-26-3-2": "Anh trai tôi ___ nhạc dân gian nhưng tôi rất thích.",
  "ex-26-3-3": "Tôi có vài vé ___ ở Town Hall. Bạn có muốn một vé không?",
  "ex-26-3-4": "Harper thích nhạc ___.",
  "ex-27-1-1": "Ghép chữ: H I N A C → ___",
  "ex-27-1-2": "Ghép chữ: Z I R A L B → ___",
  "ex-27-1-3": "Ghép chữ: P I N S A → ___",
  "ex-27-1-4": "Ghép chữ: O C R M O O C → ___",
  "ex-27-1-5": "Ghép chữ: A N J A P → ___",
  "ex-27-2-1": "Rome là thủ đô của ___.",
  "ex-27-2-2": "Canberra là thủ đô của ___.",
  "ex-27-2-3": "Bogotá là thủ đô của ___.",
  "ex-27-2-4": "Cairo là thủ đô của ___.",
  "ex-27-2-5": "London là thủ đô của ___.",
  "ex-27-2-6": "Berlin là thủ đô của ___.",
  "ex-27-3-1": "Ở Mexico, Tây Ban Nha và Chile họ nói tiếng Tây Ban Nha nhưng ở Brazil họ nói ___.",
  "ex-27-3-2": "Ở Áo, Đức và Thụy Sĩ họ nói tiếng Đức nhưng ở Ý họ nói ___.",
  "ex-27-3-3": "Ở Morocco, Ai Cập và Saudi Arabia họ nói tiếng Ả Rập nhưng ở Trung Quốc họ nói ___.",
  "ex-27-3-4": "Ở Thụy Sĩ, Canada và Pháp họ nói tiếng Pháp nhưng ở Scotland họ nói ___.",
  "ex-27-4-1": "Người đến từ Thái Lan là ___.",
  "ex-27-4-2": "Người đến từ Đức là ___.",
  "ex-27-4-3": "Người đến từ Ai Cập là ___.",
  "ex-27-4-4": "Người đến từ Argentina là ___.",
  "ex-27-4-5": "Người đến từ Tây Ban Nha là ___.",
  "ex-28-1": "Ghép từ thời tiết bên trái với mô tả bên phải",
  "ex-28-2-1": "Ở La Paz trời ___.",
  "ex-28-2-2": "Ở Paris trời ___.",
  "ex-28-2-3": "Ở Tashkent trời ___.",
  "ex-28-2-4": "Ở Seoul trời ___.",
  "ex-28-2-5": "Ở Washington trời ___.",
  "ex-28-3-1": "Khi trời ___, tôi mang theo ô.",
  "ex-28-3-2": "Tháng Một ở nước bạn ___ như thế nào?",
  "ex-28-3-3": "Khi trời ___, chúng ta có thể đi trượt tuyết.",
  "ex-28-3-4": "Hôm nay ở đây là 24 ___.",
  "ex-28-3-5": "Nguy hiểm khi ở trên thuyền nhỏ ngoài biển trong ___.",
  "ex-28-3-6": "Bạn thấy ___ trước khi nghe sấm.",
  "ex-28-3-7": "Mùa đông ở Siberia rất ___.",
  "ex-29-1-1": "Tôi có thể lấy thông tin về khách sạn ở đâu? Tại văn phòng thông tin ___.",
  "ex-29-1-2": "Tôi có thể đổi tiền ở đâu? Tại ___.",
  "ex-29-1-3": "Tôi có thể đỗ xe ở đâu? Tại bãi ___.",
  "ex-29-1-4": "Tôi có thể xem đồ cổ và thú vị ở đâu? Tại ___.",
  "ex-29-1-5": "Tôi có thể lên tàu ở đâu? Tại ga ___.",
  "ex-29-1-6": "Tôi có thể gửi bưu kiện ở đâu? Tại bưu ___.",
  "ex-29-2-1": "Bạn muốn rời trung tâm mua sắm. Biển báo nào giúp bạn?",
  "ex-29-2-2": "Bạn muốn ngồi ở nơi không có thuốc lá.",
  "ex-29-2-3": "Bạn muốn biết người ta có được đi trên cỏ không.",
  "ex-29-2-4": "Bạn muốn vào bảo tàng.",
  "ex-29-3-1": "Rẽ phải ở ___ con đường.",
  "ex-29-3-2": "Trạm xe buýt ở ngay đó bên ___.",
  "ex-29-3-3": "Để đến Town Hall, đi xe buýt số 14 ___.",
  "ex-29-3-4": "Có bưu điện ở ___ kia của đường.",
  "ex-29-3-5": "Bạn có thể tìm máy rút tiền tại ngân hàng trên High ___.",
  "ex-29-3-6": "Bạn có thể chỉ đường đến ga ___ được không?",
  "ex-29-4-1": "Ghép chữ: sumuem → ___",
  "ex-29-4-2": "Ghép chữ: nowt hlal → ___",
  "ex-29-4-3": "Ghép chữ: brilyra → ___",
  "ex-29-4-4": "Ghép chữ: rac prak → ___",
  "ex-30-1-1": "Vùng đất đá cao nhô lên gọi là ___.",
  "ex-30-1-2": "Vùng rộng lớn phủ đầy cây cối gọi là ___.",
  "ex-30-1-3": "Những vùng đất nhô nhỏ gọi là ___.",
  "ex-30-1-4": "Nhóm nhà nhỏ ở nông thôn gọi là ___.",
  "ex-30-1-5": "Đất dùng để trồng trọt gọi là ___.",
  "ex-30-1-6": "Vùng nước nhỏ được đất bao quanh gọi là ___.",
  "ex-30-1-7": "Lối đi hẹp để đi bộ ở nông thôn gọi là ___.",
  "ex-30-1-8": "Dòng nước chảy ra biển gọi là ___.",
  "ex-30-2-1": "Anh trai tôi là nông dân. Anh ấy sống trên một ___.",
  "ex-30-2-2": "Không phải nhà lớn; chỉ là một ___.",
  "ex-30-2-3": "Nông trại gần một ___ có 800 người.",
  "ex-30-2-4": "Cách làng 20 km có một ___ nhỏ. Có 9.000 người.",
  "ex-30-3": "Ghép hoạt động bên trái với địa điểm / cách làm bên phải",
  "ex-30-4-1": "Chọn câu đúng:",
  "ex-30-4-2": "Chọn câu đúng:",
  "ex-30-4-3": "Chọn câu đúng:",
  "ex-30-4-4": "Chọn câu đúng:",
};
