import type { VocabularyUnit } from "@/lib/vocabulary/vocabulary-unit-types";
import {
  bold,
  ex,
  fillBlank,
  mcq,
  purple,
} from "@/lib/vocabulary/units/eviu-unit-builder";
import { advancedUnit, wordList } from "@/lib/vocabulary/units/eviu-advanced-unit-helpers";

const U9_WORDS = wordList([
  ["slender", "thon thon, mảnh mai (quyến rũ)", "She is a tall, slender woman with sharp features.", "ADJECTIVE"],
  ["scrawny", "gầy tong teo, xương xẩu", "He was too scrawny to play rugby.", "ADJECTIVE"],
  ["lanky", "cao gầy, tay chân dài", "A lanky teenager walked into the room.", "ADJECTIVE"],
  ["gangly", "cao lêu nghêu, cử động vụng về", "The gangly youth tripped over the step.", "ADJECTIVE"],
  ["obese", "béo phì (mức y tế)", "Studies show more children are becoming obese.", "ADJECTIVE"],
  ["stout", "đậm người, chắc nịch", "She is the stout woman wearing glasses.", "ADJECTIVE"],
  ["stocky", "thấp đậm, vai rộng", "My grandfather was a stocky man with broad shoulders.", "ADJECTIVE"],
  ["bulk up", "tăng cơ, lên cân (cơ bắp)", "He bulked up after months at the gym.", "VERB"],
  ["lean", "gầy khỏe", "He used to be lean and wiry.", "ADJECTIVE"],
  ["wiry", "gầy nhưng rắn chắc", "The runner has a wiry frame.", "ADJECTIVE"],
  ["unkempt", "bù xù, không chỉn tề", "He still looks unkempt after the long trip.", "ADJECTIVE"],
  ["immaculate", "gọn gàng hoàn hảo", "Her sister always wears immaculate clothes.", "ADJECTIVE"],
  ["swarthy", "da sẫm màu", "He has a swarthy complexion from years abroad.", "ADJECTIVE"],
  ["sallow", "da vàng xệ, không khỏe", "Her sister's complexion was more sallow.", "ADJECTIVE"],
  ["haggard", "mệt mỏi hiện rõ trên mặt", "He looked haggard after working all night.", "ADJECTIVE"],
  ["grin", "cười toe toét", "What are you grinning at?", "VERB"],
  ["pout", "mím môi (giận hoặc làm dáng)", "She pouts whenever she does not get her way.", "VERB"],
  ["grimace", "nhăn mặt (ghê hoặc đau)", "Do not grimace every time I eat garlic.", "VERB"],
  ["scowl", "cau mày giận dữ", "She scowled at me when I arrived late.", "VERB"],
  ["leer", "nhìn trơ trẻn, gợi cảm khó chịu", "He was leering at us across the bar.", "VERB"],
  ["shrug", "nhún vai", "He just shrugged and said he did not know.", "VERB"],
  ["twitch", "giật giật nhẹ (bất an)", "He sat there twitching nervously before the interview.", "VERB"],
  ["clench", "nắm chặt (nắm đấm)", "She clenched her fist and told him to leave.", "VERB"],
  ["never a hair out of place", "luôn gọn gàng, chỉn chu", "She is never a hair out of place at work.", "PHRASE"],
]);

const U10_WORDS = wordList([
  ["impetuous", "bốc đồng, hành động không suy nghĩ", "She is so impetuous; she acts before thinking.", "ADJECTIVE"],
  ["impulsive", "bốc đồng (có thể tích cực hơn)", "His impulsive generosity helped many people.", "ADJECTIVE"],
  ["effusive", "bộc lộ cảm xúc quá mức", "She gave me an effusive welcome at the door.", "ADJECTIVE"],
  ["excitable", "dễ kích động", "He is an excitable child who needs to calm down.", "ADJECTIVE"],
  ["pushy", "ép buộc, chỉ nghĩ lợi mình", "Do not be so pushy about a pay rise.", "ADJECTIVE"],
  ["self-conscious", "tự ti, lo người khác đánh giá", "Freddie felt self-conscious making the announcement.", "ADJECTIVE"],
  ["well-balanced", "điềm đạm, cân bằng", "The teacher said Maddy was a well-balanced child.", "ADJECTIVE"],
  ["taciturn", "ít nói, trầm lặng", "He was taciturn when I first met him.", "ADJECTIVE"],
  ["introvert", "người hướng nội", "Chloe is an introvert; her brother is outgoing.", "NOUN"],
  ["extrovert", "người hướng ngoại", "Mark is a real extrovert at parties.", "NOUN"],
  ["diffident", "thiếu tự tin", "Mr Rogers is a diffident man with low self-esteem.", "ADJECTIVE"],
  ["reserved", "kín đáo, không dễ gần ngay", "English people are often thought of as reserved.", "ADJECTIVE"],
  ["aloof", "xa cách, lạnh lùng", "Eva tends to be rather aloof at meetings.", "ADJECTIVE"],
  ["haughty", "kiêu ngạo", "My aunt can be haughty and disdainful at times.", "ADJECTIVE"],
  ["disdainful", "khinh miệt, coi thường", "She gave him a disdainful look.", "ADJECTIVE"],
  ["unapproachable", "khó gần", "Professor Mactoft seems very unapproachable.", "ADJECTIVE"],
  ["approachable", "dễ gần, dễ nói chuyện", "Dr O'Daly is friendly and approachable.", "ADJECTIVE"],
  ["conceited", "tự cao, tự đại", "Natasha is very conceited about her looks.", "ADJECTIVE"],
  ["modest", "khiêm tốn", "Rachel is a modest person who never boasts.", "ADJECTIVE"],
  ["naive", "ngây thơ, cả tin", "Arjen is naive enough to think love solves everything.", "ADJECTIVE"],
  ["gullible", "cả tin, dễ bị lừa", "Salespeople often target gullible customers.", "ADJECTIVE"],
  ["conscientious", "tận tâm, làm việc cẩn thận", "My father was a conscientious worker.", "ADJECTIVE"],
  ["restless", "bồn chồn, không yên với hiện tại", "She is a restless individual who changes jobs often.", "ADJECTIVE"],
  ["pig-headed", "cứng đầu (mạnh, informal)", "Stop being so pig-headed and listen to advice.", "ADJECTIVE"],
]);

const U11_WORDS = wordList([
  ["love at first sight", "yêu ngay từ cái nhìn đầu", "It was love at first sight when they met.", "PHRASE"],
  ["head over heels", "say đắm hoàn toàn", "She fell head over heels in love with him.", "IDIOM"],
  ["besotted", "mê mẩn, say đắm mù quáng", "Lauren was completely besotted with Dave.", "ADJECTIVE"],
  ["platonic relationship", "mối quan hệ thuần tình bạn", "Matt and Ellie have a purely platonic relationship.", "PHRASE"],
  ["hit it off", "hợp nhau ngay từ đầu", "Anona and I hit it off immediately.", "VERB"],
  ["soulmate", "tri kỷ, người hiểu mình sâu sắc", "We felt like true soulmates from day one.", "NOUN"],
  ["kindred spirits", "người cùng chí hướng", "Ben and I have always been kindred spirits.", "PHRASE"],
  ["get on like a house on fire", "hợp nhau rất nhanh", "Charlie and I get on like a house on fire.", "IDIOM"],
  ["bosom buddy", "bạn thân ruột thịt", "Rob and Jamie have been bosom buddies for years.", "NOUN"],
  ["inseparable", "không thể tách rời", "Marta and Carmen are inseparable at school.", "ADJECTIVE"],
  ["close bond", "mối gắn bó thân thiết", "There is a close bond between Rushda and her aunt.", "PHRASE"],
  ["well-matched couple", "cặp đôi hợp nhau", "Nathan and Amelia seem a well-matched couple.", "PHRASE"],
  ["family ties", "mối liên kết gia đình", "Family ties in Spain are often very strong.", "PHRASE"],
  ["mutual acquaintances", "người quen chung", "We share a number of mutual acquaintances.", "PHRASE"],
  ["hold in high regard", "rất tôn trọng", "Gareth holds Clare in high regard.", "PHRASE"],
  ["thick as thieves", "thân như keo, thân thiết", "Sarah and Anna are as thick as thieves lately.", "IDIOM"],
  ["adoration", "sự ngưỡng mộ/yêu mến sâu sắc", "The parents gazed at the baby with adoration.", "NOUN"],
  ["amiability", "sự thân thiện, dễ gần", "She always treats us with great amiability.", "NOUN"],
  ["faithfulness", "sự chung thủy", "Faithfulness is the key to a good marriage.", "NOUN"],
  ["fondness", "sự yêu mến nhẹ nhàng", "Over the years she developed a fondness for Mario.", "NOUN"],
  ["loyalty", "lòng trung thành", "He inspired loyalty in every player on the team.", "NOUN"],
  ["man after my own heart", "người cùng chí hướng với mình", "Rob is a man after my own heart.", "IDIOM"],
]);

const U12_WORDS = wordList([
  ["two-faced", "hai mặt, giả tạo", "Kate has been two-faced towards me for months.", "ADJECTIVE"],
  ["allies", "đồng minh", "Russia and America were allies during the war.", "NOUN"],
  ["arch rivals", "đối thủ gay gắt", "We were partners but now we are arch rivals.", "PHRASE"],
  ["sworn enemies", "kẻ thù không đội trời chung", "After the dispute they became sworn enemies.", "PHRASE"],
  ["disloyal", "không trung thành", "Fergus has been disloyal to me on several occasions.", "ADJECTIVE"],
  ["distant", "xa cách, lạnh nhạt", "Sam has been very distant towards me recently.", "ADJECTIVE"],
  ["staunchest ally", "đồng minh trung thành nhất", "Monica has always been my staunchest ally at work.", "PHRASE"],
  ["scrupulously honest", "trung thực tuyệt đối", "Jamie has been scrupulously honest in his dealings.", "PHRASE"],
  ["unswerving loyalty", "lòng trung thành kiên định", "I expect unswerving loyalty from a true friend.", "PHRASE"],
  ["break down", "sụp đổ, tan vỡ (quan hệ)", "Relationships sometimes break down over misunderstandings.", "VERB"],
  ["rift", "vết nứt, bất hòa sâu sắc", "A rift developed between the two departments.", "NOUN"],
  ["discord", "bất hòa, mâu thuẫn", "There has been a lot of discord in the office lately.", "NOUN"],
  ["see eye to eye", "đồng quan điểm", "My father and I do not see eye to eye on politics.", "IDIOM"],
  ["on bad terms", "quan hệ xấu, căng thẳng", "Jack and his sister have been on bad terms for years.", "PHRASE"],
  ["split up", "chia tay", "I think they will split up after the argument.", "VERB"],
  ["ups and downs", "thăng trầm", "Our marriage has had its ups and downs.", "PHRASE"],
  ["bumpy relationship", "mối quan hệ lên xuống thất thường", "They have had a bumpy relationship for years.", "PHRASE"],
  ["broken home", "gia đình tan vỡ (ly hôn)", "Growing up in a broken home was hard for him.", "PHRASE"],
  ["family feud", "mối thù/hấn trong gia đình", "A family feud caused bad feeling for decades.", "PHRASE"],
  ["love affair", "mối tình", "His love affair with Anna has turned sour.", "PHRASE"],
  ["turn sour", "trở nên xấu đi", "Their friendship turned sour after the betrayal.", "VERB"],
  ["speaking ill behind backs", "nói xấu sau lưng", "True friends avoid speaking ill behind backs.", "PHRASE"],
]);

const U13_WORDS = wordList([
  ["crave", "khao khát mãnh liệt", "Pregnant women often crave strange foods.", "VERB"],
  ["yearn", "khao khát điều không có được", "She yearns to be on her own with no responsibilities.", "VERB"],
  ["coveted", "được ai cũng mong muốn", "An Olympic gold medal is the most coveted prize.", "ADJECTIVE"],
  ["defuse", "xoa dịu, làm giảm căng thẳng", "Lottie tried to defuse the tension by changing topic.", "VERB"],
  ["placate", "xoa dịu ai đang giận", "It took her a long time to placate her angry father.", "VERB"],
  ["conciliate", "hòa giải giữa hai bên", "An advisor was brought in to conciliate between unions and management.", "VERB"],
  ["appease", "nhượng bộ để dàn xếp", "Appeasing the enemy postponed war for another year.", "VERB"],
  ["implacable", "không thể lay chuyển (thù hận)", "I cannot understand his implacable hatred for his rival.", "ADJECTIVE"],
  ["exultant", "hân hoan chiến thắng", "Sarah was in an exultant mood after her exam results.", "ADJECTIVE"],
  ["ecstatic", "ngất ngây vui sướng", "She was ecstatic when she heard the news.", "ADJECTIVE"],
  ["rejoice", "vui mừng khôn xiết", "Everyone rejoiced at the news of her recovery.", "VERB"],
  ["jubilant", "hân hoan, ăn mừng chiến thắng", "Jubilant shouts filled the hall after the result.", "ADJECTIVE"],
  ["bliss", "hạnh phúc tuyệt đối", "We enjoyed seven days of utter bliss on the island.", "NOUN"],
  ["blissful", "cực kỳ hạnh phúc", "They are blissfully happy even though they are poor.", "ADJECTIVE"],
  ["full of the joys of spring", "vui tươi như mùa xuân", "You look full of the joys of spring today.", "IDIOM"],
  ["thrilled to bits", "vui sướng tột độ", "We are thrilled to bits at the news of the baby.", "IDIOM"],
  ["on top of the world", "hạnh phúc tột cùng", "I feel on top of the world with my new job.", "IDIOM"],
  ["walking on air", "say sưa hạnh phúc", "I have been walking on air since I got into drama school.", "IDIOM"],
  ["over the moon", "vui sướng khôn tả", "I was over the moon when I scored the winning goal.", "IDIOM"],
  ["have a craving for", "thèm mãnh liệt", "She has a craving for tuna and banana pizza.", "PHRASE"],
  ["have a thirst for", "khao khát (tri thức, v.v.)", "Young children often have a thirst for knowledge.", "PHRASE"],
]);

const U14_WORDS = wordList([
  ["antipathy", "ác cảm mạnh", "Antipathy towards the government increased during the crisis.", "NOUN"],
  ["aversion", "sự ghét mạnh hoặc không muốn", "I felt an instant aversion to the new manager.", "NOUN"],
  ["pet aversion", "thứ ghét nhất", "Arrogance has always been my pet aversion.", "PHRASE"],
  ["averse to", "không thích, phản đối", "I am not averse to a good night out.", "PHRASE"],
  ["loathe", "ghét cay ghét đắng", "I loathe people who tell lies.", "VERB"],
  ["abhor", "kinh tởm, ghét sâu sắc", "We all find her behaviour abhorrent.", "VERB"],
  ["loathing", "sự ghét cay đắng", "She looked at him with pure loathing.", "NOUN"],
  ["abhorrence", "sự kinh tởm", "He spoke of war with abhorrence.", "NOUN"],
  ["scorn", "sự khinh miệt", "There was a scornful note in his voice.", "NOUN"],
  ["offhand", "lạnh nhạt, thiếu quan tâm", "She was very offhand with everyone at the meeting.", "ADJECTIVE"],
  ["officious", "hay ra lệnh, làm lớn chuyện nhỏ", "The assistant can be very officious.", "ADJECTIVE"],
  ["ostentatious", "phô trương phù phiếm", "He makes ostentatious displays of his wealth.", "ADJECTIVE"],
  ["pompous", "trịch thượng, tự cho mình quan trọng", "She has become very pompous since entering Parliament.", "ADJECTIVE"],
  ["pretentious", "làm bộ làm tịch", "She is so pretentious about reading philosophy.", "ADJECTIVE"],
  ["puerile", "trẻ con, ngớ ngẩn", "What puerile behaviour — grow up!", "ADJECTIVE"],
  ["fickle", "thất thường, hay đổi ý", "Jo can be very fickle about her plans.", "ADJECTIVE"],
  ["obnoxious", "đáng ghét, thô lỗ", "The customs officer was an obnoxious man.", "ADJECTIVE"],
  ["dejected", "chán nản, thất vọng", "I felt utterly dejected when I did not get the job.", "ADJECTIVE"],
  ["forlorn", "bơ vơ, tuyệt vọng", "She looked forlorn, gazing into the distance.", "ADJECTIVE"],
  ["devastated", "sụp đổ tinh thần", "I was devastated when I heard of my friend's death.", "ADJECTIVE"],
  ["distraught", "đau khổ tột độ", "The missing child's parents were distraught.", "ADJECTIVE"],
  ["miserable", "khốn khổ, buồn bã", "He always looks miserable and never smiles.", "ADJECTIVE"],
]);

const U15_WORDS = wordList([
  ["pregnancy", "thai kỳ", "Pregnancy usually lasts about nine months.", "NOUN"],
  ["conception", "thụ thai", "Conception occurs when the egg is fertilised.", "NOUN"],
  ["embryo", "phôi", "The embryo implants in the womb.", "NOUN"],
  ["womb", "tử cung", "The foetus grows inside the womb.", "NOUN"],
  ["IVF", "thụ tinh trong ống nghiệm", "Some couples conceive with help from IVF.", "NOUN"],
  ["foetus", "thai nhi (từ tuần thứ 8)", "The foetus is fed through the placenta.", "NOUN"],
  ["placenta", "nhau thai", "Nutrients pass through the placenta to the baby.", "NOUN"],
  ["midwife", "nữ hộ sinh", "A midwife helped her give birth at home.", "NOUN"],
  ["caesarean section", "mổ lấy thai", "The surgeon delivered the baby by caesarean section.", "PHRASE"],
  ["go into labour", "chuyển dạ", "She went into labour at forty weeks.", "PHRASE"],
  ["live to a ripe old age", "sống thọ", "More people now live to a ripe old age.", "PHRASE"],
  ["pensioner", "người nhận lương hưu", "My aunt has been a pensioner for twenty years.", "NOUN"],
  ["sheltered accommodation", "nhà ở có hỗ trợ cho người già", "She lives in sheltered accommodation near the coast.", "PHRASE"],
  ["doddery", "run rẩy, yếu vì già", "He is ninety but not at all doddery.", "ADJECTIVE"],
  ["dementia", "sa sút trí tuệ", "Many elderly people develop dementia.", "NOUN"],
  ["coffin", "quan tài", "There was a coffin painted in team colours.", "NOUN"],
  ["wake", "đám tang tại nhà sau khi mai", "At the wake his sister told a funny story.", "NOUN"],
  ["cremation", "hỏa táng", "I would prefer an ordinary cremation.", "NOUN"],
  ["ashes", "tro cốt", "She wants her ashes scattered at sea.", "NOUN"],
  ["condolences", "lời chia buồn", "Please accept my condolences on your loss.", "NOUN"],
  ["bequeath", "di chúc để lại (tài sản)", "He bequeathed his house to his niece.", "VERB"],
  ["die intestate", "chết không để lại di chúc", "If you die intestate, the law decides who inherits.", "PHRASE"],
  ["pass away", "qua đời (euphemism)", "Her uncle passed away last winter.", "VERB"],
  ["bereaved", "mất người thân", "The bereaved family received many messages of support.", "ADJECTIVE"],
]);

export const EVIU_ADVANCED_UNITS_09_15: readonly VocabularyUnit[] = [
  advancedUnit(9, {
    introVi:
      "Unit 9 mở rộng cách mô tả ngoại hình và cử chỉ: từ vóc dáng (slender, lanky) đến biểu cảm khuôn mặt (scowl, leer) và thói quen (shrug, twitch). Bạn học chọn từ có sắc thái phù hợp khi miêu tả người.",
    structureSections: [
      { label: "Size, build and complexion", wordCount: 16 },
      { label: "Facial expression", wordCount: 5 },
      { label: "Mannerisms and gestures", wordCount: 4 },
    ],
    collocationHtml: `${purple("bulk up")}, ${purple("never a hair out of place")} và ${purple("clench your fist")} là cụm rất hay gặp khi mô tả người ở trình độ Advanced.`,
    mistakeHtml: `${bold("kempt")} không tồn tại — chỉ dùng ${bold("unkempt")}. ${bold("lean")} (gầy khỏe) khác ${bold("scrawny")} (gầy xấu); ${bold("leer")} mang sắc thái tiêu cực, không đồng nghĩa với \"nhìn\" thông thường.`,
    principles: [
      {
        title: "Mô tả vóc dáng có sắc thái",
        body: `${purple("slender")} và ${purple("lanky")} thường trung tính; ${purple("scrawny")} và ${purple("obese")} mang đánh giá rõ hơn. ${purple("stout")}, ${purple("stocky")} mô tả người đậm, chắc.`,
        examples: [
          ex("A lanky teenager walked in awkwardly.", "Một thiếu niên cao lêu nghêu bước vào một cách vụng về."),
          ex("He bulked up after months of training.", "Anh ấy lên cơ sau nhiều tháng tập luyện."),
        ],
      },
      {
        title: "Nước da và vẻ ngoài tổng thể",
        body: `${purple("swarthy")} = da sẫm; ${purple("sallow")} = da vàng xệ, trông không khỏe; ${purple("haggard")} = mệt mỏi hiện rõ trên mặt. ${purple("immaculate")} là đối lập của ${purple("unkempt")}.`,
        examples: [
          ex("He looked haggard after the long flight.", "Anh ấy trông tiều tụy sau chuyến bay dài."),
          ex("She is never a hair out of place.", "Cô ấy lúc nào cũng chỉn chu gọn gàng."),
        ],
      },
      {
        title: "Biểu cảm và cử chỉ",
        body: `${purple("grin")} tích cực hơn ${purple("scowl")}. ${purple("pout")} có thể là làm dáng hoặc cau có. ${purple("shrug")}, ${purple("twitch")} và ${purple("clench")} mô tả thói quen cơ thể.`,
        examples: [
          ex("She scowled when I arrived late.", "Cô ấy cau mày khi tôi đến muộn."),
          ex("He shrugged and said he did not know.", "Anh ấy nhún vai và nói không biết."),
        ],
      },
    ],
    words: U9_WORDS,
    exercises: [
      mcq(
        9,
        1,
        "\"Swarthy\" mô tả làn da như thế nào?",
        [
          { key: "a", label: "Sẫm màu" },
          { key: "b", label: "Vàng xệ, không khỏe" },
          { key: "c", label: "Rám nắng đẹp" },
          { key: "d", label: "Nhợt nhạt" },
        ],
        "a",
      ),
      fillBlank(
        9,
        2,
        "He looked ____ after working through the night.",
        "haggard",
        [
          { key: "a", label: "immaculate" },
          { key: "b", label: "haggard" },
          { key: "c", label: "slender" },
          { key: "d", label: "gangly" },
        ],
        "b",
      ),
      mcq(
        9,
        3,
        "Ai đó \"leers at you\" thường nhìn theo cách nào?",
        [
          { key: "a", label: "Trơ trẻn, gợi cảm khó chịu" },
          { key: "b", label: "Thân thiện, quan tâm" },
          { key: "c", label: "Ngưỡng mộ" },
          { key: "d", label: "Vô tình, không chú ý" },
        ],
        "a",
      ),
      fillBlank(
        9,
        4,
        "She ____ her fist and told him to leave immediately.",
        "clenched",
        [
          { key: "a", label: "shrugged" },
          { key: "b", label: "grinned" },
          { key: "c", label: "clenched" },
          { key: "d", label: "pouted" },
        ],
        "c",
      ),
      mcq(
        9,
        5,
        "\"Unkempt\" nghĩa là gì?",
        [
          { key: "a", label: "Bù xù, không chỉn tề" },
          { key: "b", label: "Gọn gàng hoàn hảo" },
          { key: "c", label: "Gầy khỏe" },
          { key: "d", label: "Cao lêu nghêu" },
        ],
        "a",
      ),
      fillBlank(
        9,
        6,
        "The tall, ____ youth had long arms and awkward movements.",
        "gangly",
        [
          { key: "a", label: "stocky" },
          { key: "b", label: "gangly" },
          { key: "c", label: "obese" },
          { key: "d", label: "swarthy" },
        ],
        "b",
      ),
    ],
  }),

  advancedUnit(10, {
    introVi:
      "Unit 10 đi sâu vào tính cách và đặc điểm hành vi: từ impetuous, taciturn đến aloof, gullible. Bạn học phân biệt từ gần nghĩa và chọn mức độ sắc thái phù hợp khi miêu tả người.",
    structureSections: [
      { label: "Personality adjectives", wordCount: 8 },
      { label: "Sociability and self-image", wordCount: 10 },
      { label: "Character traits", wordCount: 6 },
    ],
    collocationHtml: `${purple("well-balanced")}, ${purple("hold in high regard")} và ${purple("pig-headed")} giúp bạn mô tả tính cách tinh tế hơn ở trình độ Advanced.`,
    mistakeHtml: `${bold("impetuous")} và ${bold("impulsive")} gần nghĩa nhưng impulsive có thể tích cực hơn. ${bold("diffident")} = thiếu tự tin, không phải \"khác biệt\". ${bold("taciturn")} thường mang sắc thái tiêu cực.`,
    principles: [
      {
        title: "Tính cách hành động nhanh hay chậm",
        body: `${purple("impetuous")} và ${purple("impulsive")} đều liên quan hành động không suy nghĩ kỹ; ${purple("excitable")} nhấn mạnh dễ kích động; ${purple("pushy")} mang nghĩa ích kỷ, informal.`,
        examples: [
          ex("She is so impetuous; she acts before thinking.", "Cô ấy quá bốc đồng; hành động trước khi suy nghĩ."),
          ex("His impulsive generosity surprised everyone.", "Lòng hào phóng bốc đồng của anh ấy khiến mọi người bất ngờ."),
        ],
      },
      {
        title: "Mức độ hòa đồng",
        body: `${purple("introvert")} / ${purple("extrovert")} mô tả hướng nội/ngoại. ${purple("reserved")}, ${purple("aloof")}, ${purple("unapproachable")} mô tả khoảng cách xã hội; ${purple("approachable")} là đối lập.`,
        examples: [
          ex("Eva tends to be rather aloof at parties.", "Eva thường khá xa cách ở các buổi tiệc."),
          ex("Dr O'Daly is friendly and approachable.", "Tiến sĩ O'Daly thân thiện và dễ gần."),
        ],
      },
      {
        title: "Đặc điểm tính cách sâu hơn",
        body: `${purple("naive")} và ${purple("gullible")} liên quan cả tin. ${purple("conscientious")} = tận tâm; ${purple("restless")} = không hài lòng với hiện tại; ${purple("pig-headed")} = cứng đầu, informal.`,
        examples: [
          ex("Telephone salespeople target gullible customers.", "Nhân viên telesales hay nhắm vào khách cả tin."),
          ex("Stop being so pig-headed and listen.", "Đừng cứng đầu nữa mà hãy lắng nghe."),
        ],
      },
    ],
    words: U10_WORDS,
    exercises: [
      mcq(
        10,
        1,
        "\"Taciturn\" mô tả người như thế nào?",
        [
          { key: "a", label: "Ít nói, trầm lặng" },
          { key: "b", label: "Rất hướng ngoại" },
          { key: "c", label: "Rất bốc đồng" },
          { key: "d", label: "Rất khiêm tốn" },
        ],
        "a",
      ),
      fillBlank(
        10,
        2,
        "She is so ____; she only thinks about her own promotion.",
        "pushy",
        [
          { key: "a", label: "modest" },
          { key: "b", label: "well-balanced" },
          { key: "c", label: "pushy" },
          { key: "d", label: "conscientious" },
        ],
        "c",
      ),
      mcq(
        10,
        3,
        "Ai \"conceited\" thường thế nào?",
        [
          { key: "a", label: "Tự cao, tự đại" },
          { key: "b", label: "Khiêm tốn" },
          { key: "c", label: "Thiếu tự tin" },
          { key: "d", label: "Dễ bị lừa" },
        ],
        "a",
      ),
      fillBlank(
        10,
        4,
        "My father was a ____ worker who never took time off unless he was ill.",
        "conscientious",
        [
          { key: "a", label: "restless" },
          { key: "b", label: "naive" },
          { key: "c", label: "conscientious" },
          { key: "d", label: "effusive" },
        ],
        "c",
      ),
      mcq(
        10,
        5,
        "\"Diffident\" gần nghĩa với từ nào?",
        [
          { key: "a", label: "Thiếu tự tin" },
          { key: "b", label: "Kiêu ngạo" },
          { key: "c", label: "Bốc đồng" },
          { key: "d", label: "Dễ kích động" },
        ],
        "a",
      ),
      fillBlank(
        10,
        6,
        "Natasha is ____ but Rachel is modest and quiet about her success.",
        "conceited",
        [
          { key: "a", label: "conceited" },
          { key: "b", label: "approachable" },
          { key: "c", label: "gullible" },
          { key: "d", label: "taciturn" },
        ],
        "a",
      ),
    ],
  }),

  advancedUnit(11, {
    introVi:
      "Unit 11 tập trung tình bạn và các mối quan hệ tích cực: từ love at first sight đến thick as thieves. Bạn học idiom, collocation và cặp danh từ–tính từ (loyalty, adoration) mô tả cảm xúc trong quan hệ.",
    structureSections: [
      { label: "Love and romance", wordCount: 4 },
      { label: "Friendship idioms", wordCount: 10 },
      { label: "Positive relationship nouns", wordCount: 8 },
    ],
    collocationHtml: `${purple("hit it off")}, ${purple("thick as thieves")} và ${purple("hold in high regard")} là cụm tần suất cao khi nói về bạn bè và tình cảm.`,
    mistakeHtml: `${bold("platonic relationship")} không có yếu tố tình dục — đừng dùng cho cặp đôi đang hẹn hò. ${bold("besotted")} mạnh hơn ${bold("infatuated")}. ${bold("soulmate")} thường số ít.`,
    principles: [
      {
        title: "Tình yêu và say mê",
        body: `${purple("love at first sight")} và ${purple("head over heels")} mô tả cảm xúc mạnh. ${purple("besotted")} gần nghĩa mù quáng; ${purple("platonic relationship")} là tình bạn thuần túy giữa nam nữ.`,
        examples: [
          ex("It was love at first sight when they met.", "Họ yêu nhau ngay từ cái nhìn đầu tiên."),
          ex("They have a purely platonic relationship.", "Họ chỉ có mối quan hệ bạn bè thuần túy."),
        ],
      },
      {
        title: "Tình bạn thân thiết",
        body: `${purple("hit it off")} = hợp nhau ngay; ${purple("get on like a house on fire")} = quan hệ rất tốt; ${purple("inseparable")} và ${purple("thick as thieves")} nhấn mạnh sự gắn bó.`,
        examples: [
          ex("We hit it off the moment we met.", "Chúng tôi hợp nhau ngay từ lúc gặp."),
          ex("Sarah and Anna are as thick as thieves.", "Sarah và Anna thân như keo dạo này."),
        ],
      },
      {
        title: "Danh từ mô tả cảm xúc tích cực",
        body: `${purple("adoration")}, ${purple("faithfulness")}, ${purple("fondness")} và ${purple("loyalty")} thường đi với tính từ tương ứng (adoring, faithful, fond, loyal).`,
        examples: [
          ex("Faithfulness is the key to a good marriage.", "Chung thủy là chìa khóa của hôn nhân tốt."),
          ex("She treats us with great amiability.", "Cô ấy luôn đối xử với chúng tôi rất thân thiện."),
        ],
      },
    ],
    words: U11_WORDS,
    exercises: [
      mcq(
        11,
        1,
        "\"Thick as thieves\" nghĩa là gì?",
        [
          { key: "a", label: "Rất thân thiết" },
          { key: "b", label: "Hay ăn cắp" },
          { key: "c", label: "Hay cãi nhau" },
          { key: "d", label: "Mới quen" },
        ],
        "a",
      ),
      fillBlank(
        11,
        2,
        "We ____ immediately and have been close ever since.",
        "hit it off",
        [
          { key: "a", label: "split up" },
          { key: "b", label: "hit it off" },
          { key: "c", label: "turn sour" },
          { key: "d", label: "see eye to eye" },
        ],
        "b",
      ),
      mcq(
        11,
        3,
        "Mối quan hệ \"platonic\" là loại nào?",
        [
          { key: "a", label: "Tình bạn, không tình dục" },
          { key: "b", label: "Hôn nhân" },
          { key: "c", label: "Ngoại tình" },
          { key: "d", label: "Đồng nghiệp" },
        ],
        "a",
      ),
      fillBlank(
        11,
        4,
        "Gareth ____ Clare in high regard.",
        "holds",
        [
          { key: "a", label: "holds" },
          { key: "b", label: "craves" },
          { key: "c", label: "loathes" },
          { key: "d", label: "scorns" },
        ],
        "a",
      ),
      mcq(
        11,
        5,
        "\"Besotted with\" gần nghĩa với?",
        [
          { key: "a", label: "Say mê, mù quáng" },
          { key: "b", label: "Ghét cay ghét đắng" },
          { key: "c", label: "Thờ ơ" },
          { key: "d", label: "Chỉ là bạn" },
        ],
        "a",
      ),
      fillBlank(
        11,
        6,
        "Charlie and I get on ____ — we never run out of things to talk about.",
        "like a house on fire",
        [
          { key: "a", label: "on bad terms" },
          { key: "b", label: "like a house on fire" },
          { key: "c", label: "head over heels" },
          { key: "d", label: "at death's door" },
        ],
        "b",
      ),
    ],
  }),

  advancedUnit(12, {
    introVi:
      "Unit 12 xử lý thăng trầm trong quan hệ: từ two-faced, sworn enemies đến ups and downs và family feud. Bạn học collocation mô tả sụp đổ, bất hòa và cách diễn đạt trung thực trong tình bạn.",
    structureSections: [
      { label: "Negative relationship traits", wordCount: 7 },
      { label: "Conflict and breakdown", wordCount: 8 },
      { label: "Relationship collocations", wordCount: 7 },
    ],
    collocationHtml: `${purple("see eye to eye")}, ${purple("on bad terms")} và ${purple("family feud")} là cụm quan trọng khi nói về mối quan hệ xấu hoặc thăng trầm.`,
    mistakeHtml: `${bold("arch rivals")} nhấn mạnh cạnh tranh gay gắt, khác ${bold("sworn enemies")} (thù không đội trời chung). ${bold("break down")} (quan hệ) khác ${bold("split up")} (chia tay). ${bold("rift")} là danh từ.`,
    principles: [
      {
        title: "Phẩm chất tiêu cực trong quan hệ",
        body: `${purple("two-faced")} = nói xấu sau lưng. ${purple("disloyal")} và ${purple("distant")} mô tả sự xa cách. ${purple("staunchest ally")} và ${purple("unswerving loyalty")} là đối lập tích cực.`,
        examples: [
          ex("Kate has been two-faced towards me.", "Kate đã hai mặt với tôi."),
          ex("Monica is my staunchest ally at work.", "Monica là đồng minh trung thành nhất của tôi ở công ty."),
        ],
      },
      {
        title: "Xung đột và tan vỡ",
        body: `${purple("break down")}, ${purple("rift")} và ${purple("discord")} mô tả quan hệ xấu đi. ${purple("see eye to eye")} = đồng quan điểm; ${purple("on bad terms")} = quan hệ căng thẳng.`,
        examples: [
          ex("A rift developed between the two groups.", "Bất hòa sâu sắc nảy sinh giữa hai nhóm."),
          ex("They do not see eye to eye on most things.", "Họ hiếm khi đồng quan điểm về hầu hết mọi việc."),
        ],
      },
      {
        title: "Thăng trầm và hậu quả",
        body: `${purple("ups and downs")} và ${purple("bumpy relationship")} mô tả quan hệ không ổn định. ${purple("broken home")} và ${purple("family feud")} liên quan gia đình.`,
        examples: [
          ex("Our marriage has had its ups and downs.", "Hôn nhân chúng tôi cũng có thăng trầm."),
          ex("Their love affair turned sour and they split up.", "Mối tình họ trở nên xấu đi và họ chia tay."),
        ],
      },
    ],
    words: U12_WORDS,
    exercises: [
      mcq(
        12,
        1,
        "\"Two-faced\" mô tả người như thế nào?",
        [
          { key: "a", label: "Giả tạo, nói xấu sau lưng" },
          { key: "b", label: "Trung thực tuyệt đối" },
          { key: "c", label: "Rất thân thiết" },
          { key: "d", label: "Thiếu tự tin" },
        ],
        "a",
      ),
      fillBlank(
        12,
        2,
        "Jack and his sister have been ____ for a long time.",
        "on bad terms",
        [
          { key: "a", label: "thick as thieves" },
          { key: "b", label: "on bad terms" },
          { key: "c", label: "inseparable" },
          { key: "d", label: "well-matched" },
        ],
        "b",
      ),
      mcq(
        12,
        3,
        "\"Sworn enemies\" nghĩa là gì?",
        [
          { key: "a", label: "Kẻ thù không đội trời chung" },
          { key: "b", label: "Bạn thân ruột thịt" },
          { key: "c", label: "Đồng nghiệp" },
          { key: "d", label: "Người quen sơ sơ" },
        ],
        "a",
      ),
      fillBlank(
        12,
        4,
        "Their friendship ____ after the argument.",
        "turned sour",
        [
          { key: "a", label: "hit it off" },
          { key: "b", label: "turned sour" },
          { key: "c", label: "held in high regard" },
          { key: "d", label: "went into labour" },
        ],
        "b",
      ),
      mcq(
        12,
        5,
        "\"Family feud\" là gì?",
        [
          { key: "a", label: "Mối thù/hấn kéo dài trong gia đình" },
          { key: "b", label: "Đám cưới lớn" },
          { key: "c", label: "Kỳ nghỉ gia đình" },
          { key: "d", label: "Bữa tiệc sinh nhật" },
        ],
        "a",
      ),
      fillBlank(
        12,
        6,
        "Every relationship has its ____ — good times and hard times.",
        "ups and downs",
        [
          { key: "a", label: "mutual acquaintances" },
          { key: "b", label: "ups and downs" },
          { key: "c", label: "close bonds" },
          { key: "d", label: "family ties" },
        ],
        "b",
      ),
    ],
  }),

  advancedUnit(13, {
    introVi:
      "Unit 13 bao quát cảm xúc mạnh và phản ứng: khao khát (crave, yearn), xoa dịu (placate, defuse) và niềm vui cực độ (ecstatic, over the moon). Bạn học động từ formal và idiom informal song song.",
    structureSections: [
      { label: "Strong desires", wordCount: 5 },
      { label: "Managing emotions", wordCount: 5 },
      { label: "Extreme happiness", wordCount: 11 },
    ],
    collocationHtml: `${purple("defuse tension")}, ${purple("over the moon")} và ${purple("walking on air")} là cụm hay dùng khi nói về cảm xúc mạnh.`,
    mistakeHtml: `${bold("implacable")} tồn tại nhưng ${bold("placable")} không có. ${bold("appease")} thường mang sắc thái phê phán (nhượng bộ đối phương). ${bold("coveted")} là tính từ, không phải động từ.`,
    principles: [
      {
        title: "Khao khát mãnh liệt",
        body: `${purple("crave")} và ${purple("have a craving for")} dùng cho ham muốn mạnh. ${purple("yearn")} thường gắn điều khó đạt được. ${purple("coveted")} = ai cũng muốn có.`,
        examples: [
          ex("She yearns to be on her own for a while.", "Cô ấy khao khát được ở một mình một thời gian."),
          ex("An Olympic gold is the most coveted prize.", "Huy chương vàng Olympic là giải thưởng ai cũng mong muốn."),
        ],
      },
      {
        title: "Xoa dịu và hòa giải",
        body: `${purple("defuse")} làm giảm căng thẳng; ${purple("placate")} xoa ai đang giận; ${purple("conciliate")} hòa giải hai bên (formal); ${purple("appease")} nhượng bộ (thường tiêu cực).`,
        examples: [
          ex("Lottie tried to defuse the tension.", "Lottie cố xoa dịu bầu không khí căng thẳng."),
          ex("It took hours to placate her angry father.", "Mất hàng giờ mới xoa dịu được người cha đang giận."),
        ],
      },
      {
        title: "Hạnh phúc cực độ",
        body: `${purple("exultant")}, ${purple("ecstatic")}, ${purple("jubilant")} formal hơn. ${purple("bliss")} = hạnh phúc tuyệt đối. ${purple("over the moon")}, ${purple("thrilled to bits")} informal.`,
        examples: [
          ex("I was over the moon when I got the job.", "Tôi vui sướng khôn tả khi nhận được việc."),
          ex("We had seven days of utter bliss on the island.", "Chúng tôi có bảy ngày hạnh phúc tuyệt đối trên đảo."),
        ],
      },
    ],
    words: U13_WORDS,
    exercises: [
      mcq(
        13,
        1,
        "\"Placate\" nghĩa là gì?",
        [
          { key: "a", label: "Xoa dịu ai đang giận" },
          { key: "b", label: "Khiêu khích thêm" },
          { key: "c", label: "Quên đi" },
          { key: "d", label: "Ghét cay ghét đắng" },
        ],
        "a",
      ),
      fillBlank(
        13,
        2,
        "She tried to ____ the tension by changing the subject.",
        "defuse",
        [
          { key: "a", label: "defuse" },
          { key: "b", label: "appease" },
          { key: "c", label: "loathe" },
          { key: "d", label: "yearn" },
        ],
        "a",
      ),
      mcq(
        13,
        3,
        "\"Implacable hatred\" nghĩa là thù hận như thế nào?",
        [
          { key: "a", label: "Không thể lay chuyển" },
          { key: "b", label: "Nhẹ nhàng, tạm thời" },
          { key: "c", label: "Giả vờ" },
          { key: "d", label: "Đã nguôi" },
        ],
        "a",
      ),
      fillBlank(
        13,
        4,
        "I was ____ when I heard I got into drama school.",
        "over the moon",
        [
          { key: "a", label: "miserable" },
          { key: "b", label: "over the moon" },
          { key: "c", label: "dejected" },
          { key: "d", label: "forlorn" },
        ],
        "b",
      ),
      mcq(
        13,
        5,
        "\"Bliss\" gần nghĩa với?",
        [
          { key: "a", label: "Hạnh phúc tuyệt đối" },
          { key: "b", label: "Nỗi đau sâu sắc" },
          { key: "c", label: "Sự bực bội" },
          { key: "d", label: "Lo lắng" },
        ],
        "a",
      ),
      fillBlank(
        13,
        6,
        "Young children often have a ____ for knowledge.",
        "thirst",
        [
          { key: "a", label: "thirst" },
          { key: "b", label: "rift" },
          { key: "c", label: "feud" },
          { key: "d", label: "aversion" },
        ],
        "a",
      ),
    ],
  }),

  advancedUnit(14, {
    introVi:
      "Unit 14 tập trung cảm xúc tiêu cực: antipathy, loathe, abhor và các tính từ mô tả hành vi khó chịu (offhand, obnoxious). Bạn học cặp noun–verb–adjective và idiom thể hiện sự buồn sâu sắc.",
    structureSections: [
      { label: "Antipathy and aversion", wordCount: 4 },
      { label: "Strong negative feelings", wordCount: 5 },
      { label: "Negative personality traits", wordCount: 8 },
      { label: "Extreme unhappiness", wordCount: 5 },
    ],
    collocationHtml: `${purple("pet aversion")}, ${purple("feel loathing")} và ${purple("utterly dejected")} giúp diễn đạt cảm xúc tiêu cực chính xác hơn.`,
    mistakeHtml: `${bold("averse to")} thường đi với ${bold("not")} (not averse to = không ngại). ${bold("-ing/-ed")}: ${bold("distressing")} news vs ${bold("distressed")} person. ${bold("abhor")} formal hơn ${bold("loathe")}.`,
    principles: [
      {
        title: "Ác cảm và sự ghét",
        body: `${purple("antipathy")} = ác cảm mạnh; ${purple("aversion")} = ghét hoặc không muốn. ${purple("pet aversion")} = thứ ghét nhất. ${purple("averse to")} thường dùng với not (= không ngại).`,
        examples: [
          ex("Arrogance has always been my pet aversion.", "Sự kiêu ngạo luôn là thứ tôi ghét nhất."),
          ex("I am not averse to a good night out.", "Tôi không ngại một buổi đi chơi vui."),
        ],
      },
      {
        title: "Động từ và danh từ cảm xúc mạnh",
        body: `${purple("loathe")} và ${purple("abhor")} = ghét sâu sắc. ${purple("loathing")}, ${purple("abhorrence")}, ${purple("scorn")} là danh từ tương ứng.`,
        examples: [
          ex("I loathe people who tell lies.", "Tôi ghét những người nói dối."),
          ex("We find her behaviour abhorrent.", "Chúng tôi thấy hành vi cô ta đáng kinh tởm."),
        ],
      },
      {
        title: "Buồn bã và thất vọng sâu",
        body: `${purple("dejected")} = thất vọng; ${purple("forlorn")} = bơ vơ; ${purple("devastated")} và ${purple("distraught")} mạnh hơn; ${purple("miserable")} informal.`,
        examples: [
          ex("I felt utterly dejected when I failed the interview.", "Tôi chán nản tột độ khi trượt phỏng vấn."),
          ex("The parents were distraught when their child went missing.", "Bố mẹ đau khổ tột độ khi con mất tích."),
        ],
      },
    ],
    words: U14_WORDS,
    exercises: [
      mcq(
        14,
        1,
        "\"Pet aversion\" là gì?",
        [
          { key: "a", label: "Thứ ghét nhất" },
          { key: "b", label: "Thú cưng yêu thích" },
          { key: "c", label: "Sở thích mới" },
          { key: "d", label: "Nỗi sợ nhẹ" },
        ],
        "a",
      ),
      fillBlank(
        14,
        2,
        "I ____ people who talk through films.",
        "loathe",
        [
          { key: "a", label: "rejoice" },
          { key: "b", label: "loathe" },
          { key: "c", label: "crave" },
          { key: "d", label: "placate" },
        ],
        "b",
      ),
      mcq(
        14,
        3,
        "\"Officious\" mô tả người như thế nào?",
        [
          { key: "a", label: "Hay ra lệnh, làm lớn chuyện nhỏ" },
          { key: "b", label: "Rất khiêm tốn" },
          { key: "c", label: "Rất trung thực" },
          { key: "d", label: "Rất vui vẻ" },
        ],
        "a",
      ),
      fillBlank(
        14,
        4,
        "She looked ____ gazing into the distance.",
        "forlorn",
        [
          { key: "a", label: "jubilant" },
          { key: "b", label: "forlorn" },
          { key: "c", label: "exultant" },
          { key: "d", label: "besotted" },
        ],
        "b",
      ),
      mcq(
        14,
        5,
        "\"Not averse to\" nghĩa là gì?",
        [
          { key: "a", label: "Không ngại, không phản đối" },
          { key: "b", label: "Ghét cay ghét đắng" },
          { key: "c", label: "Hoàn toàn không biết" },
          { key: "d", label: "Rất sợ hãi" },
        ],
        "a",
      ),
      fillBlank(
        14,
        6,
        "The customs officer was an ____ man who shouted at tourists.",
        "obnoxious",
        [
          { key: "a", label: "amiability" },
          { key: "b", label: "obnoxious" },
          { key: "c", label: "modest" },
          { key: "d", label: "conscientious" },
        ],
        "b",
      ),
    ],
  }),

  advancedUnit(15, {
    introVi:
      "Unit 15 bao quát sinh và tử: từ pregnancy, IVF đến cremation, bequeath. Bạn học từ vựng y khoa, euphemism (pass away) và collocation liên quan tang lễ, di chúc ở nhiều register khác nhau.",
    structureSections: [
      { label: "Birth and pregnancy", wordCount: 11 },
      { label: "Ageing and old age", wordCount: 5 },
      { label: "Death and funerals", wordCount: 8 },
    ],
    collocationHtml: `${purple("go into labour")}, ${purple("live to a ripe old age")} và ${purple("die intestate")} là cụm quan trọng khi nói về vòng đời con người.`,
    mistakeHtml: `${bold("expect")} (mang thai) chỉ dùng ở thì tiếp diễn: ${bold("is expecting")}, không dùng ${bold("expects")}. ${bold("late")} + danh từ người = đã mất. ${bold("womb")} và ${bold("uterus")} đồng nghĩa, womb thông dụng hơn.`,
    principles: [
      {
        title: "Thai kỳ và sinh nở",
        body: `${purple("conception")} → ${purple("embryo")} → ${purple("foetus")}. ${purple("IVF")} = thụ tinh trong ống nghiệm. ${purple("midwife")} hỗ trợ sinh; ${purple("caesarean section")} = mổ lấy thai.`,
        examples: [
          ex("She went into labour at forty weeks.", "Cô ấy chuyển dạ ở tuần thứ 40."),
          ex("The baby was delivered by caesarean section.", "Em bé được sinh bằng mổ lấy thai."),
        ],
      },
      {
        title: "Tuổi già",
        body: `${purple("live to a ripe old age")} = sống thọ. ${purple("pensioner")} nhận lương hưu. ${purple("sheltered accommodation")} có hỗ trợ. ${purple("dementia")} = sa sút trí tuệ.`,
        examples: [
          ex("My aunt lives in sheltered accommodation.", "Dì tôi sống ở nhà có hỗ trợ cho người già."),
          ex("More people live to a ripe old age these days.", "Ngày nay nhiều người sống thọ hơn."),
        ],
      },
      {
        title: "Cái chết và tang lễ",
        body: `${purple("pass away")} là euphemism. ${purple("cremation")} = hỏa táng; ${purple("ashes")} = tro cốt. ${purple("bequeath")} = để lại di chúc; ${purple("die intestate")} = chết không có di chúc.`,
        examples: [
          ex("Please accept my condolences on your loss.", "Xin chia buồn cùng gia đình."),
          ex("She wants her ashes scattered at sea.", "Cô ấy muốn tro cốt rải xuống biển."),
        ],
      },
    ],
    words: U15_WORDS,
    exercises: [
      mcq(
        15,
        1,
        "\"IVF\" là gì?",
        [
          { key: "a", label: "Thụ tinh trong ống nghiệm" },
          { key: "b", label: "Phẫu thuật tim" },
          { key: "c", label: "Tiêm vaccine" },
          { key: "d", label: "Chụp X-quang" },
        ],
        "a",
      ),
      fillBlank(
        15,
        2,
        "The developing baby is fed through the ____.",
        "placenta",
        [
          { key: "a", label: "coffin" },
          { key: "b", label: "placenta" },
          { key: "c", label: "will" },
          { key: "d", label: "wake" },
        ],
        "b",
      ),
      mcq(
        15,
        3,
        "\"Die intestate\" nghĩa là gì?",
        [
          { key: "a", label: "Chết không để lại di chúc" },
          { key: "b", label: "Chết vì tai nạn" },
          { key: "c", label: "Chết trong giấc ngủ" },
          { key: "d", label: "Chết ở nước ngoài" },
        ],
        "a",
      ),
      fillBlank(
        15,
        4,
        "He ____ his house to his niece in his will.",
        "bequeathed",
        [
          { key: "a", label: "bequeathed" },
          { key: "b", label: "craved" },
          { key: "c", label: "defused" },
          { key: "d", label: "scowled" },
        ],
        "a",
      ),
      mcq(
        15,
        5,
        "\"Sheltered accommodation\" dành cho ai?",
        [
          { key: "a", label: "Người già cần hỗ trợ" },
          { key: "b", label: "Sinh viên đại học" },
          { key: "c", label: "Vận động viên" },
          { key: "d", label: "Trẻ sơ sinh" },
        ],
        "a",
      ),
      fillBlank(
        15,
        6,
        "At the ____, friends shared stories about his life.",
        "wake",
        [
          { key: "a", label: "conception" },
          { key: "b", label: "wake" },
          { key: "c", label: "placenta" },
          { key: "d", label: "embryo" },
        ],
        "b",
      ),
    ],
  }),
];
