import { assertExerciseCount, cloze, match, mcq } from "./eviu-elementary-curated-helpers";
import type { VocabularyExercise } from "@/lib/vocabulary/vocabulary-unit-types";

const UNIT_1: VocabularyExercise[] = [
  match("ex-pre-1-1", "1 · Ghép từ với nghĩa", [
    { left: "revise", right: "ôn lại kiến thức để nhớ lâu" },
    { left: "retention", right: "khả năng giữ thông tin trong trí nhớ" },
    { left: "collocation", right: "cặp từ thường đi với nhau" },
    { left: "mnemonic", right: "mẹo liên tưởng để ghi nhớ" },
    { left: "antonym", right: "từ trái nghĩa" },
    { left: "register", right: "mức độ trang trọng của từ" },
  ]),
  cloze("ex-pre-1-2", "1 · Điền từ", "Spaced review improves ___.", "retention", ["Retention"]),
  cloze("ex-pre-1-3", "1 · Điền từ", "Learn each phrase in ___.", "context", ["Context"]),
  cloze("ex-pre-1-4", "1 · Điền từ", "Write an ___ beside each adjective.", "antonym", ["Antonym"]),
  cloze("ex-pre-1-5", "1 · Điền từ", "Check the ___ before using slang.", "register", ["Register"]),
  cloze("ex-pre-1-6", "1 · Điền cụm", "Use ___ instead of re-reading.", "active recall", ["Active recall"]),
  mcq("ex-pre-1-7", "1 · Chọn đáp án", "Phương pháp lặp lại ngắt quãng theo chu kỳ là ___", "b", [
    { key: "a", label: "semantic map" },
    { key: "b", label: "spaced repetition" },
    { key: "c", label: "usage note" },
    { key: "d", label: "drill" },
  ]),
  mcq("ex-pre-1-8", "1 · Chọn đáp án", "Từ nào chỉ nhóm từ cùng gốc (noun/verb/adjective)?", "a", [
    { key: "a", label: "word family" },
    { key: "b", label: "synonym set" },
    { key: "c", label: "mnemonic" },
    { key: "d", label: "chunk" },
  ]),
  mcq("ex-pre-1-9", "1 · Chọn đáp án", "\"To ___\" means to learn something so you can remember it.", "c", [
    { key: "a", label: "revise" },
    { key: "b", label: "recall" },
    { key: "c", label: "memorise" },
    { key: "d", label: "browse" },
  ]),
  cloze("ex-pre-1-10", "1 · Điền cụm", "This ___ helps me avoid repetition.", "synonym set", ["Synonym set"]),
  cloze("ex-pre-1-11", "1 · Điền từ", "Quick quizzes help ___.", "recall", ["Recall"]),
  cloze("ex-pre-1-12", "1 · Điền từ", "We did a short pronunciation ___.", "drill", ["Drill"]),
  cloze("ex-pre-1-13", "1 · Điền cụm", "The dictionary gives a clear ___.", "usage note", ["Usage note"]),
  mcq("ex-pre-1-14", "1 · Chọn đáp án", "A ___ links words from the same topic in a diagram.", "a", [
    { key: "a", label: "semantic map" },
    { key: "b", label: "register" },
    { key: "c", label: "antonym" },
    { key: "d", label: "self-test" },
  ]),
];

const UNIT_2: VocabularyExercise[] = [
  match("ex-pre-2-1", "2 · Ghép từ với nghĩa", [
    { left: "entry", right: "mục ghi chép riêng cho một từ" },
    { left: "headword", right: "từ chính đứng đầu mục từ" },
    { left: "error log", right: "danh sách lỗi thường mắc" },
    { left: "template", right: "mẫu khung ghi từ thống nhất" },
    { left: "review cycle", right: "chu kỳ xem lại định kỳ" },
    { left: "abbreviation", right: "cách viết tắt" },
  ]),
  cloze("ex-pre-2-2", "2 · Điền từ", "Write one clear ___ per term.", "entry", ["Entry"]),
  cloze("ex-pre-2-3", "2 · Điền từ", "Highlight the ___ in blue.", "headword", ["Headword"]),
  cloze("ex-pre-2-4", "2 · Điền cụm", "I keep an ___ in the last section.", "error log", ["Error log"]),
  cloze("ex-pre-2-5", "2 · Điền từ", "Use one ___ for all new entries.", "template", ["Template"]),
  cloze("ex-pre-2-6", "2 · Điền cụm", "My ___ is day 1, 3 and 7.", "review cycle", ["Review cycle"]),
  cloze("ex-pre-2-7", "2 · Điền cụm", "Add a ___ from real life.", "sample sentence", ["Sample sentence"]),
  mcq("ex-pre-2-8", "2 · Chọn đáp án", "Mục nào phù hợp nhất để ghi lỗi hay lặp lại?", "b", [
    { key: "a", label: "topic page" },
    { key: "b", label: "error log" },
    { key: "c", label: "index tab" },
    { key: "d", label: "symbol" },
  ]),
  mcq("ex-pre-2-9", "2 · Chọn đáp án", "A ___ tells you if a word is formal or informal.", "a", [
    { key: "a", label: "usage label" },
    { key: "b", label: "headword" },
    { key: "c", label: "index tab" },
    { key: "d", label: "template" },
  ]),
  mcq("ex-pre-2-10", "2 · Chọn đáp án", "To ___ words means to sort them into groups.", "c", [
    { key: "a", label: "annotate" },
    { key: "b", label: "highlight" },
    { key: "c", label: "categorise" },
    { key: "d", label: "tag" },
  ]),
  cloze("ex-pre-2-11", "2 · Điền từ", "___ collocations in purple.", "Highlight", ["highlight"]),
  cloze("ex-pre-2-12", "2 · Điền từ", "___ tricky examples in Vietnamese.", "Annotate", ["annotate"]),
  cloze("ex-pre-2-13", "2 · Điền cụm", "Use ___ to connect similar words.", "cross-reference", ["Cross-reference"]),
  mcq("ex-pre-2-14", "2 · Chọn đáp án", "A star ___ means a difficult word.", "d", [
    { key: "a", label: "template" },
    { key: "b", label: "entry" },
    { key: "c", label: "tag" },
    { key: "d", label: "symbol" },
  ]),
];

const UNIT_3: VocabularyExercise[] = [
  match("ex-pre-3-1", "3 · Ghép từ với nghĩa", [
    { left: "monolingual dictionary", right: "từ điển đơn ngữ" },
    { left: "bilingual dictionary", right: "từ điển song ngữ" },
    { left: "phonemic symbol", right: "ký hiệu phiên âm quốc tế" },
    { left: "idiom", right: "cụm thành ngữ khó đoán nghĩa" },
    { left: "derivative", right: "từ phái sinh từ cùng gốc" },
    { left: "etymology", right: "nguồn gốc lịch sử của từ" },
  ]),
  cloze("ex-pre-3-2", "3 · Điền cụm", "A ___ gives richer examples.", "monolingual dictionary", ["Monolingual dictionary"]),
  cloze("ex-pre-3-3", "3 · Điền cụm", "Beginners often start with a ___.", "bilingual dictionary", ["Bilingual dictionary"]),
  cloze("ex-pre-3-4", "3 · Điền cụm", "The ___ shows vowel length.", "phonemic symbol", ["Phonemic symbol"]),
  cloze("ex-pre-3-5", "3 · Điền từ", "This ___ sounds natural in conversation.", "idiom", ["Idiom"]),
  cloze("ex-pre-3-6", "3 · Điền cụm", "The ___ is on the second syllable.", "stress mark", ["Stress mark"]),
  cloze("ex-pre-3-7", "3 · Điền cụm", "Check the ___ first.", "part-of-speech label", ["Part-of-speech label"]),
  mcq("ex-pre-3-8", "3 · Chọn đáp án", "A ___ shows how common a word is.", "b", [
    { key: "a", label: "stress mark" },
    { key: "b", label: "frequency marker" },
    { key: "c", label: "idiom" },
    { key: "d", label: "derivative" },
  ]),
  mcq("ex-pre-3-9", "3 · Chọn đáp án", "A verb + particle such as \"look up\" is a ___", "c", [
    { key: "a", label: "idiom" },
    { key: "b", label: "derivative" },
    { key: "c", label: "phrasal verb" },
    { key: "d", label: "loanword" },
  ]),
  mcq("ex-pre-3-10", "3 · Chọn đáp án", "To ___ means to check a meaning fits the context.", "a", [
    { key: "a", label: "verify meaning" },
    { key: "b", label: "browse" },
    { key: "c", label: "compare senses" },
    { key: "d", label: "lookup" },
  ]),
  cloze("ex-pre-3-11", "3 · Điền từ", "___ nearby entries for related terms.", "Browse", ["browse"]),
  cloze("ex-pre-3-12", "3 · Điền cụm", "A ___ prevents wrong collocations.", "usage example", ["Usage example"]),
  cloze("ex-pre-3-13", "3 · Điền cụm", "My ___ works offline too.", "dictionary app", ["Dictionary app"]),
  mcq("ex-pre-3-14", "3 · Chọn đáp án", "Before translating, you should ___ of a word.", "d", [
    { key: "a", label: "browse" },
    { key: "b", label: "lookup" },
    { key: "c", label: "annotate" },
    { key: "d", label: "compare senses" },
  ]),
];

const UNIT_4: VocabularyExercise[] = [
  match("ex-pre-4-1", "4 · Ghép từ với nghĩa", [
    { left: "mother tongue", right: "ngôn ngữ mẹ đẻ" },
    { left: "fluency", right: "độ trôi chảy khi nói" },
    { left: "accuracy", right: "độ chính xác về từ và ngữ pháp" },
    { left: "intonation", right: "ngữ điệu lên xuống của câu" },
    { left: "jargon", right: "thuật ngữ chuyên môn khó với người thường" },
    { left: "loanword", right: "từ vay mượn từ ngôn ngữ khác" },
  ]),
  cloze("ex-pre-4-2", "4 · Điền cụm", "Vietnamese is my ___.", "mother tongue", ["Mother tongue"]),
  cloze("ex-pre-4-3", "4 · Điền từ", "Daily speaking practice builds ___.", "fluency", ["Fluency"]),
  cloze("ex-pre-4-4", "4 · Điền từ", "Try to balance fluency and ___.", "accuracy", ["Accuracy"]),
  cloze("ex-pre-4-5", "4 · Điền từ", "Your ___ sounds natural now.", "intonation", ["Intonation"]),
  cloze("ex-pre-4-6", "4 · Điền từ", "This word has three ___.", "syllables", ["Syllables", "syllable", "Syllable"]),
  cloze("ex-pre-4-7", "4 · Điền cụm", "Use ___ in instructions.", "plain English", ["Plain English"]),
  mcq("ex-pre-4-8", "4 · Chọn đáp án", "A ___ is a local form of a language.", "b", [
    { key: "a", label: "accent" },
    { key: "b", label: "dialect" },
    { key: "c", label: "clause" },
    { key: "d", label: "syllable" },
  ]),
  mcq("ex-pre-4-9", "4 · Chọn đáp án", "Avoid ___ when teaching beginners.", "c", [
    { key: "a", label: "fluency" },
    { key: "b", label: "intonation" },
    { key: "c", label: "jargon" },
    { key: "d", label: "accuracy" },
  ]),
  mcq("ex-pre-4-10", "4 · Chọn đáp án", "To ___ means to say something again in other words.", "a", [
    { key: "a", label: "paraphrase" },
    { key: "b", label: "pronounce clearly" },
    { key: "c", label: "emigrate" },
    { key: "d", label: "browse" },
  ]),
  cloze("ex-pre-4-11", "4 · Điền từ", "He has a clear Australian ___.", "accent", ["Accent"]),
  cloze("ex-pre-4-12", "4 · Điền từ", "A relative ___ adds detail.", "clause", ["Clause"]),
  cloze("ex-pre-4-13", "4 · Điền từ", "Correct ___ improves clarity.", "punctuation", ["Punctuation"]),
  cloze("ex-pre-4-14", "4 · Điền từ", "Many tech terms are ___.", "loanwords", ["Loanwords", "loanword", "Loanword"]),
];

const UNIT_5: VocabularyExercise[] = [
  match("ex-pre-5-1", "5 · Ghép từ với nghĩa", [
    { left: "citizenship", right: "quốc tịch theo pháp lý" },
    { left: "resident", right: "người cư trú lâu dài" },
    { left: "expat", right: "người sống và làm việc ở nước ngoài" },
    { left: "immigrant", right: "người nhập cư" },
    { left: "heritage", right: "di sản văn hóa nguồn cội" },
    { left: "native speaker", right: "người bản ngữ" },
  ]),
  cloze("ex-pre-5-2", "5 · Điền từ", "She applied for dual ___.", "citizenship", ["Citizenship"]),
  cloze("ex-pre-5-3", "5 · Điền cụm", "English is an ___ in Singapore.", "official language", ["Official language"]),
  cloze("ex-pre-5-4", "5 · Điền từ", "The city has a large ___ community.", "expat", ["Expat"]),
  cloze("ex-pre-5-5", "5 · Điền từ", "She is proud of her cultural ___.", "heritage", ["Heritage"]),
  cloze("ex-pre-5-6", "5 · Điền cụm", "I practise with a ___ online.", "native speaker", ["Native speaker"]),
  cloze("ex-pre-5-7", "5 · Điền cụm", "Always check your ___ before travel.", "visa status", ["Visa status"]),
  mcq("ex-pre-5-8", "5 · Chọn đáp án", "Someone able to use many languages is ___", "b", [
    { key: "a", label: "foreign-born" },
    { key: "b", label: "multilingual" },
    { key: "c", label: "immigrant" },
    { key: "d", label: "resident" },
  ]),
  mcq("ex-pre-5-9", "5 · Chọn đáp án", "To ___ means to move abroad to live.", "c", [
    { key: "a", label: "settle down" },
    { key: "b", label: "commute" },
    { key: "c", label: "emigrate" },
    { key: "d", label: "browse" },
  ]),
  mcq("ex-pre-5-10", "5 · Chọn đáp án", "The crowd sang the ___ before the match.", "a", [
    { key: "a", label: "national anthem" },
    { key: "b", label: "border control" },
    { key: "c", label: "ethnic group" },
    { key: "d", label: "heritage" },
  ]),
  cloze("ex-pre-5-11", "5 · Điền cụm", "My cousin is a permanent ___.", "resident", ["Resident"]),
  cloze("ex-pre-5-12", "5 · Điền cụm", "They ___ in Canada.", "settled down", ["Settled down", "settle down", "Settle down"]),
  cloze("ex-pre-5-13", "5 · Điền cụm", "___ checked our documents.", "Border control", ["border control"]),
  mcq("ex-pre-5-14", "5 · Chọn đáp án", "She sees herself as a ___.", "d", [
    { key: "a", label: "passport holder" },
    { key: "b", label: "resident" },
    { key: "c", label: "immigrant" },
    { key: "d", label: "global citizen" },
  ]),
];

const UNIT_6: VocabularyExercise[] = [
  match("ex-pre-6-1", "6 · Ghép từ với nghĩa", [
    { left: "landscape", right: "cảnh quan tự nhiên tổng thể" },
    { left: "valley", right: "thung lũng giữa các dãy núi" },
    { left: "cliff", right: "vách đá cao và dốc" },
    { left: "glacier", right: "sông băng lớn di chuyển chậm" },
    { left: "erosion", right: "sự xói mòn do gió, nước" },
    { left: "habitat", right: "môi trường sống tự nhiên" },
  ]),
  cloze("ex-pre-6-2", "6 · Điền từ", "A small river runs through the ___.", "valley", ["Valley"]),
  cloze("ex-pre-6-3", "6 · Điền từ", "Stay away from the edge of the ___.", "cliff", ["Cliff"]),
  cloze("ex-pre-6-4", "6 · Điền từ", "The ___ is shrinking every year.", "glacier", ["Glacier"]),
  cloze("ex-pre-6-5", "6 · Điền từ", "Heavy rain causes soil ___.", "erosion", ["Erosion"]),
  cloze("ex-pre-6-6", "6 · Điền cụm", "Solar energy is a ___.", "renewable resource", ["Renewable resource"]),
  cloze("ex-pre-6-7", "6 · Điền cụm", "Coral reefs are fragile ___.", "ecosystems", ["Ecosystems", "ecosystem", "Ecosystem"]),
  mcq("ex-pre-6-8", "6 · Chọn đáp án", "Coal, oil and gas are types of ___", "b", [
    { key: "a", label: "mineral" },
    { key: "b", label: "fossil fuel" },
    { key: "c", label: "renewable resource" },
    { key: "d", label: "terrain" },
  ]),
  mcq("ex-pre-6-9", "6 · Chọn đáp án", "To ___ means to keep something in its natural state.", "c", [
    { key: "a", label: "pollute" },
    { key: "b", label: "erode" },
    { key: "c", label: "preserve" },
    { key: "d", label: "graze" },
  ]),
  mcq("ex-pre-6-10", "6 · Chọn đáp án", "Factories can ___ rivers.", "a", [
    { key: "a", label: "pollute" },
    { key: "b", label: "preserve" },
    { key: "c", label: "conserve" },
    { key: "d", label: "recycle" },
  ]),
  cloze("ex-pre-6-11", "6 · Điền từ", "This terrain is too rough for ___.", "bikes", ["Bikes", "bike", "Bike"]),
  cloze("ex-pre-6-12", "6 · Điền từ", "This area is rich in ___.", "minerals", ["Minerals", "mineral", "Mineral"]),
  cloze("ex-pre-6-13", "6 · Điền cụm", "Camping is restricted in this ___.", "conservation area", ["Conservation area"]),
  mcq("ex-pre-6-14", "6 · Chọn đáp án", "Tourism has both positive and negative ___.", "d", [
    { key: "a", label: "erosion" },
    { key: "b", label: "biodiversity" },
    { key: "c", label: "terrain" },
    { key: "d", label: "environmental impact" },
  ]),
];

const UNIT_7: VocabularyExercise[] = [
  match("ex-pre-7-1", "7 · Ghép từ với nghĩa", [
    { left: "forecast", right: "dự báo thời tiết" },
    { left: "humidity", right: "độ ẩm trong không khí" },
    { left: "heatwave", right: "đợt nắng nóng kéo dài" },
    { left: "downpour", right: "trận mưa to xối xả" },
    { left: "breeze", right: "gió nhẹ dễ chịu" },
    { left: "frost", right: "lớp băng mỏng do lạnh" },
  ]),
  cloze("ex-pre-7-2", "7 · Điền từ", "The ___ says storms tonight.", "forecast", ["Forecast"]),
  cloze("ex-pre-7-3", "7 · Điền từ", "___ is high in August.", "Humidity", ["humidity"]),
  cloze("ex-pre-7-4", "7 · Điền từ", "A ___ hit the city last week.", "heatwave", ["Heatwave"]),
  cloze("ex-pre-7-5", "7 · Điền từ", "A ___ flooded the streets.", "downpour", ["Downpour"]),
  cloze("ex-pre-7-6", "7 · Điền từ", "A sea ___ cooled us down.", "breeze", ["Breeze"]),
  cloze("ex-pre-7-7", "7 · Điền từ", "Morning ___ covered the grass.", "frost", ["Frost"]),
  mcq("ex-pre-7-8", "7 · Chọn đáp án", "A storm with thunder and lightning is a ___", "b", [
    { key: "a", label: "drizzle" },
    { key: "b", label: "thunderstorm" },
    { key: "c", label: "breeze" },
    { key: "d", label: "sunny spell" },
  ]),
  mcq("ex-pre-7-9", "7 · Chọn đáp án", "A short, strong period of cold weather is a ___", "c", [
    { key: "a", label: "heatwave" },
    { key: "b", label: "downpour" },
    { key: "c", label: "cold snap" },
    { key: "d", label: "gust" },
  ]),
  mcq("ex-pre-7-10", "7 · Chọn đáp án", "The sky stayed ___ all day.", "a", [
    { key: "a", label: "overcast" },
    { key: "b", label: "mild" },
    { key: "c", label: "humid" },
    { key: "d", label: "sunny" },
  ]),
  cloze("ex-pre-7-11", "7 · Điền từ", "Cars were damaged by ___.", "hail", ["Hail"]),
  cloze("ex-pre-7-12", "7 · Điền từ", "A ___ blew my hat away.", "gust", ["Gust"]),
  cloze("ex-pre-7-13", "7 · Điền từ", "Winters are ___ in this region.", "mild", ["Mild"]),
  mcq("ex-pre-7-14", "7 · Chọn đáp án", "A sharp ___ is expected tonight.", "d", [
    { key: "a", label: "sunny spell" },
    { key: "b", label: "breeze" },
    { key: "c", label: "humidity" },
    { key: "d", label: "temperature drop" },
  ]),
];

const UNIT_8: VocabularyExercise[] = [
  match("ex-pre-8-1", "8 · Ghép từ với nghĩa", [
    { left: "mammal", right: "động vật có vú" },
    { left: "predator", right: "động vật săn mồi" },
    { left: "prey", right: "con mồi bị săn" },
    { left: "herd", right: "đàn động vật ăn cỏ" },
    { left: "camouflage", right: "khả năng ngụy trang" },
    { left: "endangered", right: "có nguy cơ tuyệt chủng" },
  ]),
  cloze("ex-pre-8-2", "8 · Điền từ", "Whales are ___, not fish.", "mammals", ["Mammals", "mammal", "Mammal"]),
  cloze("ex-pre-8-3", "8 · Điền từ", "The tiger is a top ___.", "predator", ["Predator"]),
  cloze("ex-pre-8-4", "8 · Điền từ", "Rabbits are common ___ in the wild.", "prey", ["Prey"]),
  cloze("ex-pre-8-5", "8 · Điền từ", "A ___ of deer crossed the road.", "herd", ["Herd"]),
  cloze("ex-pre-8-6", "8 · Điền từ", "___ helps insects survive.", "Camouflage", ["camouflage"]),
  cloze("ex-pre-8-7", "8 · Điền cụm", "Birds follow this ___ every year.", "migration route", ["Migration route"]),
  mcq("ex-pre-8-8", "8 · Chọn đáp án", "A frog is an ___", "b", [
    { key: "a", label: "reptile" },
    { key: "b", label: "amphibian" },
    { key: "c", label: "mammal" },
    { key: "d", label: "predator" },
  ]),
  mcq("ex-pre-8-9", "8 · Chọn đáp án", "Animals active at night are ___", "c", [
    { key: "a", label: "venomous" },
    { key: "b", label: "endangered" },
    { key: "c", label: "nocturnal" },
    { key: "d", label: "graze" },
  ]),
  mcq("ex-pre-8-10", "8 · Chọn đáp án", "To ___ means to sleep through winter.", "a", [
    { key: "a", label: "hibernate" },
    { key: "b", label: "graze" },
    { key: "c", label: "migrate" },
    { key: "d", label: "camouflage" },
  ]),
  cloze("ex-pre-8-11", "8 · Điền từ", "Some snakes are ___.", "venomous", ["Venomous"]),
  cloze("ex-pre-8-12", "8 · Điền từ", "Cows ___ near the river.", "graze", ["Graze"]),
  cloze("ex-pre-8-13", "8 · Điền từ", "Urban growth can reduce ___.", "biodiversity", ["Biodiversity"]),
  mcq("ex-pre-8-14", "8 · Chọn đáp án", "Poaching is banned in the ___.", "d", [
    { key: "a", label: "nesting site" },
    { key: "b", label: "migration route" },
    { key: "c", label: "hive" },
    { key: "d", label: "wildlife reserve" },
  ]),
];

const UNIT_9: VocabularyExercise[] = [
  match("ex-pre-9-1", "9 · Ghép từ với nghĩa", [
    { left: "posture", right: "tư thế cơ thể khi đứng ngồi" },
    { left: "joint", right: "khớp nối giữa các xương" },
    { left: "muscle", right: "cơ bắp giúp vận động" },
    { left: "balance", right: "khả năng giữ thăng bằng" },
    { left: "flexibility", right: "độ dẻo của cơ và khớp" },
    { left: "coordination", right: "sự phối hợp nhịp nhàng cử động" },
  ]),
  cloze("ex-pre-9-2", "9 · Điền từ", "Good ___ prevents back pain.", "posture", ["Posture"]),
  cloze("ex-pre-9-3", "9 · Điền từ", "My knee ___ hurts after running.", "joint", ["Joint"]),
  cloze("ex-pre-9-4", "9 · Điền từ", "Stretching relaxes tight ___.", "muscles", ["Muscles", "muscle", "Muscle"]),
  cloze("ex-pre-9-5", "9 · Điền từ", "Yoga improves ___.", "balance", ["Balance"]),
  cloze("ex-pre-9-6", "9 · Điền từ", "Dancing requires ___.", "coordination", ["Coordination"]),
  cloze("ex-pre-9-7", "9 · Điền từ", "Regular exercise preserves ___.", "mobility", ["Mobility"]),
  mcq("ex-pre-9-8", "9 · Chọn đáp án", "To ___ means to run at full speed for a short time.", "b", [
    { key: "a", label: "jog" },
    { key: "b", label: "sprint" },
    { key: "c", label: "crawl" },
    { key: "d", label: "stumble" },
  ]),
  mcq("ex-pre-9-9", "9 · Chọn đáp án", "To ___ means to trip and lose your balance.", "c", [
    { key: "a", label: "stride" },
    { key: "b", label: "reach" },
    { key: "c", label: "stumble" },
    { key: "d", label: "grip" },
  ]),
  mcq("ex-pre-9-10", "9 · Chọn đáp án", "\"Do not ___ your back suddenly.\"", "a", [
    { key: "a", label: "twist" },
    { key: "b", label: "reach" },
    { key: "c", label: "jog" },
    { key: "d", label: "grip" },
  ]),
  cloze("ex-pre-9-11", "9 · Điền từ", "We ___ in the park before work.", "jog", ["Jog"]),
  cloze("ex-pre-9-12", "9 · Điền từ", "Can you ___ the top shelf?", "reach", ["Reach"]),
  cloze("ex-pre-9-13", "9 · Điền từ", "___ the handle firmly.", "Grip", ["grip"]),
  cloze("ex-pre-9-14", "9 · Điền cụm", "___ your arms slowly.", "Stretch out", ["stretch out"]),
];

const UNIT_10: VocabularyExercise[] = [
  match("ex-pre-10-1", "10 · Ghép từ với nghĩa", [
    { left: "complexion", right: "nước da tổng thể" },
    { left: "freckles", right: "tàn nhang nhỏ trên da" },
    { left: "wrinkle", right: "nếp nhăn trên da" },
    { left: "fringe", right: "mái tóc che trán" },
    { left: "slender", right: "thon dài, mảnh mai" },
    { left: "elegant", right: "thanh lịch và tinh tế" },
  ]),
  cloze("ex-pre-10-2", "10 · Điền từ", "He has a warm ___.", "complexion", ["Complexion"]),
  cloze("ex-pre-10-3", "10 · Điền từ", "___ appear in summer.", "Freckles", ["freckles"]),
  cloze("ex-pre-10-4", "10 · Điền từ", "This cream reduces fine ___.", "wrinkles", ["Wrinkles", "wrinkle", "Wrinkle"]),
  cloze("ex-pre-10-5", "10 · Điền từ", "She cut her ___ shorter.", "fringe", ["Fringe"]),
  cloze("ex-pre-10-6", "10 · Điền từ", "She has a ___ figure.", "slender", ["Slender"]),
  cloze("ex-pre-10-7", "10 · Điền từ", "She looked ___ in black.", "elegant", ["Elegant"]),
  mcq("ex-pre-10-8", "10 · Chọn đáp án", "A man with wide, strong shoulders is ___", "b", [
    { key: "a", label: "slender" },
    { key: "b", label: "broad-shouldered" },
    { key: "c", label: "scruffy" },
    { key: "d", label: "elegant" },
  ]),
  mcq("ex-pre-10-9", "10 · Chọn đáp án", "Someone who looks untidy and messy is ___", "c", [
    { key: "a", label: "elegant" },
    { key: "b", label: "well-built" },
    { key: "c", label: "scruffy" },
    { key: "d", label: "smartly dressed" },
  ]),
  mcq("ex-pre-10-10", "10 · Chọn đáp án", "Everyone at the event was ___.", "a", [
    { key: "a", label: "smartly dressed" },
    { key: "b", label: "scruffy" },
    { key: "c", label: "curly-haired" },
    { key: "d", label: "slender" },
  ]),
  cloze("ex-pre-10-11", "10 · Điền cụm", "The ___ boy is my cousin.", "curly-haired", ["Curly-haired"]),
  cloze("ex-pre-10-12", "10 · Điền cụm", "I prefer a ___ on Fridays.", "casual outfit", ["Casual outfit"]),
  cloze("ex-pre-10-13", "10 · Điền cụm", "A ___ runs across his chin.", "noticeable scar", ["Noticeable scar"]),
  mcq("ex-pre-10-14", "10 · Chọn đáp án", "The goalkeeper is strong and muscular; he is ___", "d", [
    { key: "a", label: "slender" },
    { key: "b", label: "scruffy" },
    { key: "c", label: "elegant" },
    { key: "d", label: "well-built" },
  ]),
];

const UNIT_11: VocabularyExercise[] = [
  match("ex-pre-11-1", "11 · Ghép từ với nghĩa", [
    { left: "outgoing", right: "cởi mở, thích giao tiếp" },
    { left: "reserved", right: "kín đáo, ít bộc lộ" },
    { left: "reliable", right: "đáng tin cậy, làm đúng lời hứa" },
    { left: "stubborn", right: "bướng bỉnh, khó đổi ý" },
    { left: "ambitious", right: "tham vọng tích cực, có mục tiêu lớn" },
    { left: "considerate", right: "biết nghĩ cho người khác" },
  ]),
  cloze("ex-pre-11-2", "11 · Điền từ", "Our new teammate is very ___.", "outgoing", ["Outgoing"]),
  cloze("ex-pre-11-3", "11 · Điền từ", "He is ___ with strangers.", "reserved", ["Reserved"]),
  cloze("ex-pre-11-4", "11 · Điền từ", "She is ___ under pressure.", "reliable", ["Reliable"]),
  cloze("ex-pre-11-5", "11 · Điền từ", "My brother is ___ about money.", "stubborn", ["Stubborn"]),
  cloze("ex-pre-11-6", "11 · Điền từ", "She is ___ but realistic.", "ambitious", ["Ambitious"]),
  cloze("ex-pre-11-7", "11 · Điền cụm", "A good manager is ___.", "open-minded", ["Open-minded"]),
  mcq("ex-pre-11-8", "11 · Chọn đáp án", "Someone who acts on emotion without thinking is ___", "b", [
    { key: "a", label: "thoughtful" },
    { key: "b", label: "impulsive" },
    { key: "c", label: "reliable" },
    { key: "d", label: "reserved" },
  ]),
  mcq("ex-pre-11-9", "11 · Chọn đáp án", "Someone who states opinions firmly but politely is ___", "c", [
    { key: "a", label: "moody" },
    { key: "b", label: "stubborn" },
    { key: "c", label: "assertive" },
    { key: "d", label: "sensitive" },
  ]),
  mcq("ex-pre-11-10", "11 · Chọn đáp án", "Someone who understands others' feelings is ___", "a", [
    { key: "a", label: "empathetic" },
    { key: "b", label: "ambitious" },
    { key: "c", label: "impulsive" },
    { key: "d", label: "moody" },
  ]),
  cloze("ex-pre-11-11", "11 · Điền cụm", "Our coach is ___.", "easy-going", ["Easy-going"]),
  cloze("ex-pre-11-12", "11 · Điền từ", "He is ___ to criticism.", "sensitive", ["Sensitive"]),
  cloze("ex-pre-11-13", "11 · Điền từ", "Choose a ___ partner.", "trustworthy", ["Trustworthy"]),
  mcq("ex-pre-11-14", "11 · Chọn đáp án", "Someone whose mood changes often is ___", "d", [
    { key: "a", label: "easy-going" },
    { key: "b", label: "reliable" },
    { key: "c", label: "considerate" },
    { key: "d", label: "moody" },
  ]),
];

const UNIT_12: VocabularyExercise[] = [
  match("ex-pre-12-1", "12 · Ghép từ với nghĩa", [
    { left: "frustrated", right: "bực bội vì việc không như ý" },
    { left: "relieved", right: "nhẹ nhõm sau khi hết lo" },
    { left: "overwhelmed", right: "quá tải vì quá nhiều việc/cảm xúc" },
    { left: "grateful", right: "biết ơn sâu sắc" },
    { left: "homesick", right: "nhớ nhà khi đi xa" },
    { left: "jealous", right: "ghen tị với thành công của người khác" },
  ]),
  cloze("ex-pre-12-2", "12 · Điền từ", "I felt ___ with the slow internet.", "frustrated", ["Frustrated"]),
  cloze("ex-pre-12-3", "12 · Điền từ", "She was ___ after the exam.", "relieved", ["Relieved"]),
  cloze("ex-pre-12-4", "12 · Điền từ", "He felt ___ on the first day.", "overwhelmed", ["Overwhelmed"]),
  cloze("ex-pre-12-5", "12 · Điền từ", "I am ___ for your guidance.", "grateful", ["Grateful"]),
  cloze("ex-pre-12-6", "12 · Điền từ", "Many students feel ___ abroad.", "homesick", ["Homesick"]),
  cloze("ex-pre-12-7", "12 · Điền từ", "I get ___ before presentations.", "anxious", ["Anxious"]),
  mcq("ex-pre-12-8", "12 · Chọn đáp án", "Feeling bad because you did something wrong is feeling ___", "b", [
    { key: "a", label: "relieved" },
    { key: "b", label: "guilty" },
    { key: "c", label: "thrilled" },
    { key: "d", label: "grateful" },
  ]),
  mcq("ex-pre-12-9", "12 · Chọn đáp án", "Very excited and happy is ___", "c", [
    { key: "a", label: "irritated" },
    { key: "b", label: "anxious" },
    { key: "c", label: "thrilled" },
    { key: "d", label: "ashamed" },
  ]),
  mcq("ex-pre-12-10", "12 · Chọn đáp án", "To ___ means to become more cheerful.", "a", [
    { key: "a", label: "cheer up" },
    { key: "b", label: "bottle up feelings" },
    { key: "c", label: "calm oneself" },
    { key: "d", label: "be in a mood" },
  ]),
  cloze("ex-pre-12-11", "12 · Điền từ", "She felt ___ after the breakup.", "heartbroken", ["Heartbroken"]),
  cloze("ex-pre-12-12", "12 · Điền cụm", "Do not ___ your feelings.", "bottle up", ["Bottle up"]),
  cloze("ex-pre-12-13", "12 · Điền cụm", "Stress can cause ___.", "mood swings", ["Mood swings", "mood swing", "Mood swing"]),
  mcq("ex-pre-12-14", "12 · Chọn đáp án", "Sleep improves ___.", "d", [
    { key: "a", label: "mood swing" },
    { key: "b", label: "peer pressure" },
    { key: "c", label: "jealousy" },
    { key: "d", label: "emotional resilience" },
  ]),
];

const UNIT_13: VocabularyExercise[] = [
  match("ex-pre-13-1", "13 · Ghép từ với nghĩa", [
    { left: "household", right: "những người sống chung một nhà" },
    { left: "stepfather", right: "cha dượng" },
    { left: "in-laws", right: "họ hàng bên vợ/chồng" },
    { left: "flatmate", right: "bạn cùng căn hộ" },
    { left: "close-knit", right: "gắn bó khăng khít" },
    { left: "support network", right: "mạng lưới người thân/bạn bè hỗ trợ" },
  ]),
  cloze("ex-pre-13-2", "13 · Điền từ", "Our ___ has five members.", "household", ["Household"]),
  cloze("ex-pre-13-3", "13 · Điền từ", "Her ___ is very supportive.", "stepfather", ["Stepfather"]),
  cloze("ex-pre-13-4", "13 · Điền từ", "We visit my ___ every New Year.", "in-laws", ["In-laws"]),
  cloze("ex-pre-13-5", "13 · Điền từ", "My ___ cooks dinner on Fridays.", "flatmate", ["Flatmate"]),
  cloze("ex-pre-13-6", "13 · Điền cụm", "A strong ___ reduces stress.", "support network", ["Support network"]),
  cloze("ex-pre-13-7", "13 · Điền cụm", "They are a ___ family.", "close-knit", ["Close-knit"]),
  mcq("ex-pre-13-8", "13 · Chọn đáp án", "To ___ means to gradually become less close.", "b", [
    { key: "a", label: "stay in touch" },
    { key: "b", label: "drift apart" },
    { key: "c", label: "make up" },
    { key: "d", label: "fall out" },
  ]),
  mcq("ex-pre-13-9", "13 · Chọn đáp án", "To ___ means to become friends again after an argument.", "c", [
    { key: "a", label: "fall out" },
    { key: "b", label: "drift apart" },
    { key: "c", label: "make up" },
    { key: "d", label: "stay in touch" },
  ]),
  mcq("ex-pre-13-10", "13 · Chọn đáp án", "The brothers ___ over money.", "a", [
    { key: "a", label: "fell out" },
    { key: "b", label: "made up" },
    { key: "c", label: "stayed in touch" },
    { key: "d", label: "settled in" },
  ]),
  cloze("ex-pre-13-11", "13 · Điền cụm", "We ___ by video call.", "stay in touch", ["Stay in touch"]),
  cloze("ex-pre-13-12", "13 · Điền cụm", "I met a ___ last month.", "childhood friend", ["Childhood friend"]),
  cloze("ex-pre-13-13", "13 · Điền cụm", "Our ___ is next weekend.", "family gathering", ["Family gathering"]),
  mcq("ex-pre-13-14", "13 · Chọn đáp án", "Competition between brothers and sisters is ___", "d", [
    { key: "a", label: "generation gap" },
    { key: "b", label: "peer pressure" },
    { key: "c", label: "support network" },
    { key: "d", label: "sibling rivalry" },
  ]),
];

const UNIT_14: VocabularyExercise[] = [
  match("ex-pre-14-1", "14 · Ghép từ với nghĩa", [
    { left: "toddler", right: "trẻ chập chững biết đi" },
    { left: "adolescence", right: "giai đoạn tuổi dậy thì" },
    { left: "milestone", right: "cột mốc phát triển quan trọng" },
    { left: "peer pressure", right: "áp lực từ bạn cùng lứa" },
    { left: "role model", right: "hình mẫu để noi theo" },
    { left: "turning point", right: "bước ngoặt thay đổi hướng đi" },
  ]),
  cloze("ex-pre-14-2", "14 · Điền từ", "The ___ can already say simple words.", "toddler", ["Toddler"]),
  cloze("ex-pre-14-3", "14 · Điền từ", "Graduation is a major ___.", "milestone", ["Milestone"]),
  cloze("ex-pre-14-4", "14 · Điền cụm", "___ can affect decisions.", "Peer pressure", ["peer pressure"]),
  cloze("ex-pre-14-5", "14 · Điền cụm", "My sister is my ___.", "role model", ["Role model"]),
  cloze("ex-pre-14-6", "14 · Điền từ", "Part-time jobs teach ___.", "independence", ["Independence"]),
  cloze("ex-pre-14-7", "14 · Điền từ", "Teenagers need more ___.", "responsibility", ["Responsibility"]),
  mcq("ex-pre-14-8", "14 · Chọn đáp án", "Someone sensible and grown-up in behaviour is ___", "b", [
    { key: "a", label: "immature" },
    { key: "b", label: "mature" },
    { key: "c", label: "rebellious" },
    { key: "d", label: "grounded" },
  ]),
  mcq("ex-pre-14-9", "14 · Chọn đáp án", "To ___ means to reach adult age.", "c", [
    { key: "a", label: "be grounded" },
    { key: "b", label: "look back on" },
    { key: "c", label: "come of age" },
    { key: "d", label: "settle into" },
  ]),
  mcq("ex-pre-14-10", "14 · Chọn đáp án", "She ___ college life quickly.", "a", [
    { key: "a", label: "settled into" },
    { key: "b", label: "looked back on" },
    { key: "c", label: "came of age" },
    { key: "d", label: "was grounded" },
  ]),
  cloze("ex-pre-14-11", "14 · Điền từ", "He was ___ in high school.", "rebellious", ["Rebellious"]),
  cloze("ex-pre-14-12", "14 · Điền cụm", "I ___ my school years warmly.", "look back on", ["Look back on"]),
  cloze("ex-pre-14-13", "14 · Điền cụm", "Technology widens the ___.", "generation gap", ["Generation gap"]),
  mcq("ex-pre-14-14", "14 · Chọn đáp án", "The biological stage of becoming an adult is ___", "d", [
    { key: "a", label: "adolescence" },
    { key: "b", label: "milestone" },
    { key: "c", label: "life stage" },
    { key: "d", label: "puberty" },
  ]),
];

const UNIT_15: VocabularyExercise[] = [
  match("ex-pre-15-1", "15 · Ghép từ với nghĩa", [
    { left: "crush", right: "cảm nắng, thích thầm ai đó" },
    { left: "commitment", right: "sự cam kết lâu dài trong quan hệ" },
    { left: "newlyweds", right: "cặp vợ chồng mới cưới" },
    { left: "honeymoon", right: "kỳ trăng mật sau cưới" },
    { left: "compatible", right: "hợp nhau về tính cách/lối sống" },
    { left: "mutual respect", right: "sự tôn trọng lẫn nhau" },
  ]),
  cloze("ex-pre-15-2", "15 · Điền từ", "He had a ___ on his classmate.", "crush", ["Crush"]),
  cloze("ex-pre-15-3", "15 · Điền từ", "Trust is the base of ___.", "commitment", ["Commitment"]),
  cloze("ex-pre-15-4", "15 · Điền từ", "The ___ moved to Da Nang.", "newlyweds", ["Newlyweds"]),
  cloze("ex-pre-15-5", "15 · Điền từ", "They spent their ___ in Bali.", "honeymoon", ["Honeymoon"]),
  cloze("ex-pre-15-6", "15 · Điền cụm", "___ keeps a marriage strong.", "Mutual respect", ["mutual respect"]),
  cloze("ex-pre-15-7", "15 · Điền cụm", "They wrote personal ___.", "wedding vows", ["Wedding vows"]),
  mcq("ex-pre-15-8", "15 · Chọn đáp án", "To ___ means to end a romantic relationship.", "b", [
    { key: "a", label: "settle down" },
    { key: "b", label: "break up" },
    { key: "c", label: "remarry" },
    { key: "d", label: "make up" },
  ]),
  mcq("ex-pre-15-9", "15 · Chọn đáp án", "A couple who live far apart are in a ___", "c", [
    { key: "a", label: "separation" },
    { key: "b", label: "honeymoon" },
    { key: "c", label: "long-distance relationship" },
    { key: "d", label: "commitment" },
  ]),
  mcq("ex-pre-15-10", "15 · Chọn đáp án", "To ___ means to marry again.", "a", [
    { key: "a", label: "remarry" },
    { key: "b", label: "break up" },
    { key: "c", label: "split up" },
    { key: "d", label: "date" },
  ]),
  cloze("ex-pre-15-11", "15 · Điền từ", "They are highly ___.", "compatible", ["Compatible"]),
  cloze("ex-pre-15-12", "15 · Điền cụm", "The couple ___ last year.", "split up", ["Split up"]),
  cloze("ex-pre-15-13", "15 · Điền cụm", "She became a ___ at 30.", "single parent", ["Single parent"]),
  mcq("ex-pre-15-14", "15 · Chọn đáp án", "Sharing childcare after divorce is ___", "d", [
    { key: "a", label: "separation" },
    { key: "b", label: "commitment" },
    { key: "c", label: "honeymoon" },
    { key: "d", label: "co-parenting" },
  ]),
];

export const CURATED_PRE_UNITS_01_15: Readonly<Partial<Record<number, readonly VocabularyExercise[]>>> = {
  1: UNIT_1,
  2: UNIT_2,
  3: UNIT_3,
  4: UNIT_4,
  5: UNIT_5,
  6: UNIT_6,
  7: UNIT_7,
  8: UNIT_8,
  9: UNIT_9,
  10: UNIT_10,
  11: UNIT_11,
  12: UNIT_12,
  13: UNIT_13,
  14: UNIT_14,
  15: UNIT_15,
};

for (const [unitNumber, exercises] of Object.entries(CURATED_PRE_UNITS_01_15)) {
  if (exercises) {
    assertExerciseCount(Number(unitNumber), exercises);
  }
}
