import { assertExerciseCount, cloze, match, mcq } from "./eviu-elementary-curated-helpers";
import type { VocabularyExercise } from "@/lib/vocabulary/vocabulary-unit-types";

const UNIT_46: VocabularyExercise[] = [
  mcq("ex-46-1-2", "46.1 · Ghép câu", "Match: We arrived at our station → ?", "d", [
    { key: "a", label: "I'm going to turn it down." },
    { key: "b", label: "Please turn your music down." },
    { key: "c", label: "It's time to get up." },
    { key: "d", label: "We got off the train." },
  ]),
  mcq("ex-46-1-3", "46.1 · Ghép câu", "Match: That funny programme is on soon → ?", "c", [
    { key: "a", label: "I'm going to turn it down." },
    { key: "b", label: "Please turn your music down." },
    { key: "c", label: "Turn on the TV." },
    { key: "d", label: "Turn the radio up." },
  ]),
  mcq("ex-46-1-4", "46.1 · Ghép câu", "Match: The bus arrived → ?", "b", [
    { key: "a", label: "Put on your raincoat." },
    { key: "b", label: "We got on." },
    { key: "c", label: "Turn on the TV." },
    { key: "d", label: "Turn the radio up." },
  ]),
  mcq("ex-46-1-5", "46.1 · Ghép câu", "Match: I'm trying to work → ?", "b", [
    { key: "a", label: "I'm going to turn it down." },
    { key: "b", label: "Please turn your music down." },
    { key: "c", label: "It's time to get up." },
    { key: "d", label: "We got off the train." },
  ]),
  mcq("ex-46-1-6", "46.1 · Ghép câu", "Match: I can't hear the news → ?", "d", [
    { key: "a", label: "Please turn your music down." },
    { key: "b", label: "Put on your raincoat." },
    { key: "c", label: "Turn on the TV." },
    { key: "d", label: "Turn the radio up." },
  ]),
  mcq("ex-46-1-7", "46.1 · Ghép câu", "Match: It's raining today → ?", "a", [
    { key: "a", label: "Put on your raincoat." },
    { key: "b", label: "I'm going to turn it down." },
    { key: "c", label: "We got off the train." },
    { key: "d", label: "We got on." },
  ]),
  mcq("ex-46-1-8", "46.1 · Ghép câu", "Match: I don't want to accept that job → ?", "a", [
    { key: "a", label: "I'm going to turn it down." },
    { key: "b", label: "Please turn your music down." },
    { key: "c", label: "It's time to get up." },
    { key: "d", label: "Turn the radio up." },
  ]),
  cloze("ex-46-2-1", "46.2 · Giới từ phrasal verb", "It's dark in here. Turn ___ the lights.", "on", ["On"]),
  cloze("ex-46-2-2", "46.2 · Giới từ phrasal verb", "Our plane takes ___ at 6.25 and lands at 7.50.", "off", ["Off"]),
  cloze("ex-46-2-3", "46.2 · Giới từ phrasal verb", "When they got to the beach, he put ___ his swimming trunks.", "on", ["On"]),
  cloze("ex-46-2-4", "46.2 · Giới từ phrasal verb", "The children took ___ their school uniforms when they got home.", "off", ["Off"]),
  cloze("ex-46-2-5", "46.2 · Giới từ phrasal verb", "It's time to turn ___ the TV and go to bed now.", "off", ["Off"]),
  cloze("ex-46-2-7", "46.2 · Giới từ phrasal verb", "The students went ___ working until late at night.", "on", ["On"]),
  mcq("ex-46-3-2", "46.3 · Mô tả hình", "What is happening? (shoes)", "a", [
    { key: "a", label: "He is putting on his shoes." },
    { key: "b", label: "A plane is taking off." },
    { key: "c", label: "She is turning on the oven." },
    { key: "d", label: "They are getting on the coach." },
  ]),
  mcq("ex-46-3-3", "46.3 · Mô tả hình", "What is happening? (plane)", "b", [
    { key: "a", label: "He is putting on his shoes." },
    { key: "b", label: "A plane is taking off." },
    { key: "c", label: "She is turning on the oven." },
    { key: "d", label: "They are getting off the train." },
  ]),
  mcq("ex-46-3-4", "46.3 · Mô tả hình", "What is happening? (oven)", "c", [
    { key: "a", label: "He is putting on his shoes." },
    { key: "b", label: "A plane is taking off." },
    { key: "c", label: "She is turning on the oven." },
    { key: "d", label: "They are getting on the coach." },
  ]),
  cloze("ex-46-4-2", "46.4 · Phrasal verb quá khứ", "I removed my hat and coat. → I ___ my hat and coat.", "took off", ["Took off"]),
  cloze("ex-46-4-3", "46.4 · Phrasal verb quá khứ", "She continued writing novels all her life. → She ___ writing novels.", "went on", ["Went on"]),
  cloze("ex-46-4-4", "46.4 · Phrasal verb quá khứ", "Michael left without saying goodbye. → Michael ___ without saying goodbye.", "went off", ["Went off"]),
  cloze("ex-46-4-5", "46.4 · Phrasal verb quá khứ", "I refused the invitation to Maya's wedding. → I ___ the invitation.", "turned down", ["Turned down"]),
];

const UNIT_47: VocabularyExercise[] = [
  cloze("ex-47-1-2", "47.1 · Việc hằng ngày", "She ___ her clothes every Saturday.", "washes", ["Washes"]),
  cloze("ex-47-1-3", "47.1 · Việc hằng ngày", "He ___ the house every weekend.", "cleans", ["Cleans"]),
  cloze("ex-47-1-4", "47.1 · Việc hằng ngày", "He ___ TV every evening.", "watches", ["Watches"]),
  cloze("ex-47-1-5", "47.1 · Việc hằng ngày", "She ___ for a walk every Sunday.", "goes", ["Goes"]),
  mcq("ex-47-2-2", "47.2 · Hỏi tần suất", "How often do you go for a walk?", "a", [
    { key: "a", label: "Every Sunday." },
    { key: "b", label: "At 7 o'clock." },
    { key: "c", label: "By train." },
    { key: "d", label: "On Saturday morning." },
  ]),
  mcq("ex-47-2-3", "47.2 · Hỏi tần suất", "How do you go to work?", "c", [
    { key: "a", label: "Every Saturday." },
    { key: "b", label: "At 7 o'clock." },
    { key: "c", label: "By car." },
    { key: "d", label: "Two or three times a week." },
  ]),
  mcq("ex-47-2-4", "47.2 · Hỏi tần suất", "When do you have dinner?", "b", [
    { key: "a", label: "Every Saturday." },
    { key: "b", label: "At about 7 o'clock usually." },
    { key: "c", label: "By train." },
    { key: "d", label: "I normally walk home." },
  ]),
  cloze("ex-47-3-1", "47.3 · Thói quen", "I usually wake up at ___.", "7 o'clock", ["7 o'clock", "seven o'clock"]),
  cloze("ex-47-3-2", "47.3 · Thói quen", "I go to the bathroom and have a ___.", "shower", ["Shower"]),
  cloze("ex-47-3-3", "47.3 · Thói quen", "I usually have tea and toast for ___.", "breakfast", ["Breakfast"]),
  cloze("ex-47-3-4", "47.3 · Thói quen", "I go to work by ___.", "car", ["Car", "bus", "train"]),
  cloze("ex-47-3-6", "47.3 · Thói quen", "I usually come home at about ___.", "6 pm", ["6 pm", "6 o'clock"]),
  cloze("ex-47-3-7", "47.3 · Thói quen", "I usually make dinner at ___ o'clock.", "7", ["7", "seven"]),
  cloze("ex-47-3-8", "47.3 · Thói quen", "In the evenings I normally watch TV or go for a ___.", "walk", ["Walk"]),
  cloze("ex-47-3-10", "47.3 · Thói quen", "I usually go to ___ at 11 o'clock.", "bed", ["Bed"]),
  cloze("ex-47-w1", "47 · Từ vựng", "He listens to the ___ every morning.", "radio", ["Radio"]),
];

const UNIT_48: VocabularyExercise[] = [
  cloze("ex-48-1-2", "48.1 · Tell / say", "She ___ me she was leaving.", "told", ["Told"]),
  cloze("ex-48-1-3", "48.1 · Tell / say", "He ___ he was leaving.", "said", ["Said"]),
  cloze("ex-48-1-4", "48.1 · Tell / say", "Can you ___ me the time?", "tell", ["Tell"]),
  cloze("ex-48-1-5", "48.1 · Tell / say", "She ___ she was leaving.", "said", ["Said"]),
  cloze("ex-48-1-6", "48.1 · Tell / say", "He ___ me he was leaving.", "told", ["Told"]),
  cloze("ex-48-2-2", "48.2 · Hoàn thành câu", "How do you ___ 'tree' in German?", "say", ["Say"]),
  cloze("ex-48-2-3", "48.2 · Hoàn thành câu", "Excuse me, can you ___ me the time?", "tell", ["Tell"]),
  cloze("ex-48-2-4", "48.2 · Hoàn thành câu", "I just want to ___ goodbye (to you).", "say", ["Say"]),
  cloze("ex-48-2-5", "48.2 · Hoàn thành câu", "Can you ___ me when the exam is?", "tell", ["Tell"]),
  match("ex-48-3", "48.3 · Ghép cụm từ", [
    { left: "answer", right: "the door" },
    { left: "ask for", right: "the bill" },
    { left: "reply to", right: "an email" },
    { left: "tell", right: "someone a joke" },
    { left: "talk to", right: "a friend" },
    { left: "ask", right: "someone to help you" },
    { left: "speak", right: "Japanese" },
  ]),
  cloze("ex-48-4-2", "48.4 · Hội thoại", "Can we have the ___, please?", "bill", ["Bill"]),
  cloze("ex-48-4-3", "48.4 · Hội thoại", "___ New Year!", "Happy", ["Happy"]),
  cloze("ex-48-4-4", "48.4 · Hội thoại", "___ me a story before I go to sleep. Please!", "Tell", ["Tell"]),
];

const UNIT_49: VocabularyExercise[] = [
  cloze("ex-49-1-2", "49.1 · Chuyển động", "They ___ at the party last night.", "danced", ["Danced"]),
  cloze("ex-49-1-3", "49.1 · Chuyển động", "He ___ very fast.", "runs", ["Runs"]),
  cloze("ex-49-1-4", "49.1 · Chuyển động", "She ___ in the sea every day.", "swims", ["Swims"]),
  cloze("ex-49-1-5", "49.1 · Chuyển động", "We went ___ in the mountains.", "climbing", ["Climbing"]),
  cloze("ex-49-1-6", "49.1 · Chuyển động", "The cat ___ onto the wall.", "jumped", ["Jumped"]),
  cloze("ex-49-1-7", "49.1 · Chuyển động", "He ___ and then swam to the shore.", "jumped", ["Jumped"]),
  cloze("ex-49-1-8", "49.1 · Chuyển động", "I ___ to work every day.", "walk", ["Walk"]),
  cloze("ex-49-2-2", "49.2 · Phương tiện", "He ___ to work every day.", "drives", ["Drives"]),
  cloze("ex-49-2-3", "49.2 · Phương tiện", "She ___ the bus to school.", "takes", ["Takes"]),
  cloze("ex-49-2-4", "49.2 · Phương tiện", "I ___ my bike to the park.", "ride", ["Ride", "rode", "Rode"]),
  cloze("ex-49-3-2", "49.3 · Câu chuyện", "Maria ___ her grandmother to the city yesterday.", "drove", ["Drove"]),
  cloze("ex-49-3-3", "49.3 · Câu chuyện", "Charlie ___ to Madrid yesterday.", "flew", ["Flew"]),
  cloze("ex-49-3-4", "49.3 · Câu chuyện", "I ___ a taxi home from the station yesterday.", "took", ["Took"]),
  cloze("ex-49-3-5", "49.3 · Câu chuyện", "Bella ___ when she rode her bike yesterday.", "fell", ["Fell"]),
  cloze("ex-49-3-6", "49.3 · Câu chuyện", "Adrian ___ the 7.30 bus to school yesterday.", "missed", ["Missed"]),
  cloze("ex-49-3-8", "49.3 · Câu chuyện", "Madeline ___ very well yesterday.", "danced", ["Danced"]),
];

const UNIT_50: VocabularyExercise[] = [
  cloze("ex-50-1-2", "50.1 · Liên từ", "Annabelle agreed to marry Aarav ___ they decided to start a business together.", "and", ["And"]),
  cloze("ex-50-1-3", "50.1 · Liên từ", "Annabelle agreed to marry Aarav ___ she loved him.", "because", ["Because"]),
  cloze("ex-50-1-4", "50.1 · Liên từ", "Annabelle agreed to marry Aarav ___ he moved to London.", "so", ["So"]),
  cloze("ex-50-1-5", "50.1 · Liên từ", "Annabelle will marry Aarav ___ he moves to London.", "when", ["When"]),
  cloze("ex-50-1-6", "50.1 · Liên từ", "Annabelle agreed to marry Aarav ___ he moved to London.", "if", ["If"]),
  cloze("ex-50-1-7", "50.1 · Liên từ", "Annabelle will marry Aarav ___ she won't marry anyone.", "or", ["Or"]),
  cloze("ex-50-1-8", "50.1 · Liên từ", "Annabelle agreed to marry Aarav ___ he moved to London.", "before", ["Before"]),
  cloze("ex-50-2-2", "50.2 · Từ nối", "I like listening to music and I like reading ___.", "as well", ["As well", "also", "Also"]),
  cloze("ex-50-2-3", "50.2 · Từ nối", "My sister plays the piano better ___ I do.", "than", ["Than"]),
  cloze("ex-50-2-4", "50.2 · Từ nối", "My brother swims ___ a fish.", "like", ["Like"]),
  cloze("ex-50-2-5", "50.2 · Từ nối", "I ___ play tennis in the summer.", "only", ["Only"]),
  mcq("ex-50-3-1", "50.3 · Chọn liên từ", "I'm learning English ___ I enjoy it.", "b", [
    { key: "a", label: "and" },
    { key: "b", label: "because" },
    { key: "c", label: "if" },
    { key: "d", label: "or" },
  ]),
  mcq("ex-50-3-2", "50.3 · Chọn liên từ", "I'll learn more English ___ I do all the exercises in this book.", "c", [
    { key: "a", label: "and" },
    { key: "b", label: "because" },
    { key: "c", label: "if" },
    { key: "d", label: "so" },
  ]),
  mcq("ex-50-3-3", "50.3 · Chọn liên từ", "I started learning English ___ I was ten.", "d", [
    { key: "a", label: "and" },
    { key: "b", label: "because" },
    { key: "c", label: "if" },
    { key: "d", label: "when" },
  ]),
  mcq("ex-50-3-4", "50.3 · Chọn liên từ", "I can speak some English, ___ it's OK on holiday in the UK.", "a", [
    { key: "a", label: "so" },
    { key: "b", label: "if" },
    { key: "c", label: "or" },
    { key: "d", label: "before" },
  ]),
];

const UNIT_51: VocabularyExercise[] = [
  cloze("ex-51-1-2", "51.1 · Thời gian", "One hundred years is a ___.", "century", ["Century"]),
  cloze("ex-51-1-3", "51.1 · Thời gian", "Two weeks is a ___.", "fortnight", ["Fortnight"]),
  cloze("ex-51-1-4", "51.1 · Thời gian", "Sixty minutes is an ___.", "hour", ["Hour"]),
  cloze("ex-51-1-5", "51.1 · Thời gian", "Seven days is a ___.", "week", ["Week"]),
  cloze("ex-51-2-2", "51.2 · Tháng", "The month after July is ___.", "August", ["August"]),
  cloze("ex-51-2-3", "51.2 · Tháng", "The month before February is ___.", "January", ["January"]),
  cloze("ex-51-2-4", "51.2 · Tháng", "The month after August is ___.", "September", ["September"]),
  cloze("ex-51-2-5", "51.2 · Tháng", "The month before May is ___.", "April", ["April"]),
  cloze("ex-51-2-6", "51.2 · Ngày", "The day after Monday is ___.", "Tuesday", ["Tuesday"]),
  cloze("ex-51-2-7", "51.2 · Ngày", "The day before Sunday is ___.", "Saturday", ["Saturday"]),
  cloze("ex-51-2-8", "51.2 · Ngày", "The day after Wednesday is ___.", "Thursday", ["Thursday"]),
  cloze("ex-51-2-9", "51.2 · Tháng", "The month before March is ___.", "February", ["February"]),
  cloze("ex-51-2-10", "51.2 · Tháng", "The month before December is ___.", "November", ["November"]),
  cloze("ex-51-3-1", "51.3 · Đọc hiểu", "Valentina's birthday is on ___.", "Thursday", ["Thursday"]),
  cloze("ex-51-3-2", "51.3 · Đọc hiểu", "She wanted to have the party at the ___.", "weekend", ["Weekend"]),
  cloze("ex-51-3-3", "51.3 · Đọc hiểu", "___ is a good month to have a birthday because of the weather.", "June", ["June"]),
  cloze("ex-51-4-1", "51.4 · Số", "How many days are there in a fortnight? ___", "14", ["14", "fourteen", "Fourteen"]),
  cloze("ex-51-4-3", "51.4 · Số", "How many minutes are there in five hours? ___", "300", ["300"]),
  cloze("ex-51-4-4", "51.4 · Số", "Which month comes after June? ___", "July", ["July"]),
];

const UNIT_52: VocabularyExercise[] = [
  cloze("ex-52-1-2", "52.1 · Giới từ thời gian", "I've lived here ___ ten years.", "for", ["For"]),
  cloze("ex-52-1-3", "52.1 · Giới từ thời gian", "The shop is open ___ 9 to 5.", "from", ["From"]),
  cloze("ex-52-1-4", "52.1 · Giới từ thời gian", "We're going to Spain ___ two weeks.", "for", ["For"]),
  cloze("ex-52-1-5", "52.1 · Giới từ thời gian", "___ the moment I'm very busy.", "At", ["At"]),
  cloze("ex-52-1-6", "52.1 · Giới từ thời gian", "I haven't seen her ___ ages.", "for", ["For"]),
  mcq("ex-52-2-2", "52.2 · Thế kỷ", "The 22nd century is in the ___.", "a", [
    { key: "a", label: "future" },
    { key: "b", label: "past" },
    { key: "c", label: "present" },
    { key: "d", label: "last year" },
  ]),
  mcq("ex-52-2-3", "52.2 · Thế kỷ", "The 18th century is in the ___.", "b", [
    { key: "a", label: "future" },
    { key: "b", label: "past" },
    { key: "c", label: "present" },
    { key: "d", label: "next week" },
  ]),
  mcq("ex-52-2-4", "52.2 · Thế kỷ", "The 21st century is the ___.", "c", [
    { key: "a", label: "future" },
    { key: "b", label: "past" },
    { key: "c", label: "present" },
    { key: "d", label: "last century only" },
  ]),
  cloze("ex-52-3-2", "52.3 · Tần suất", "I ___ go to school by bus.", "sometimes", ["Sometimes"]),
  cloze("ex-52-3-3", "52.3 · Tần suất", "I ___ watch TV.", "often", ["Often"]),
  cloze("ex-52-3-4", "52.3 · Tần suất", "I ___ drink milk.", "never", ["Never"]),
  cloze("ex-52-3-5", "52.3 · Tần suất", "I ___ wear a hat.", "never", ["Never"]),
  cloze("ex-52-3-7", "52.3 · Tần suất", "I ___ go to bed at 10.", "sometimes", ["Sometimes"]),
  cloze("ex-52-4-2", "52.4 · Bao lâu trước", "When did you last see her? Probably a ___ ago.", "week", ["Week"]),
  cloze("ex-52-4-3", "52.4 · Bao lâu trước", "The bus will arrive in a few ___.", "minutes", ["Minutes"]),
  cloze("ex-52-5-1", "52.5 · Tần suất", "John plays tennis twice a ___.", "week", ["Week"]),
  cloze("ex-52-5-2", "52.5 · Tần suất", "He has a business meeting in Germany once a ___.", "month", ["Month"]),
];

const UNIT_53: VocabularyExercise[] = [
  cloze("ex-53-1-2", "53.1 · Here / there", "Come ___. I want to show you something.", "here", ["Here"]),
  cloze("ex-53-1-3", "53.1 · Here / there", "Look over ___. Can you see the river?", "there", ["There"]),
  cloze("ex-53-1-4", "53.1 · Here / there", "People ___ speak English.", "everywhere", ["Everywhere"]),
  cloze("ex-53-1-5", "53.1 · Here / there", "I lived in Rome for a year but now I'm ___ in London.", "back", ["Back"]),
  cloze("ex-53-2-2", "53.2 · At / on / in", "She works ___ a hospital.", "at", ["At"]),
  cloze("ex-53-2-3", "53.2 · At / on / in", "There's a picture ___ the wall.", "on", ["On"]),
  cloze("ex-53-2-4", "53.2 · At / on / in", "I'll meet you ___ the station.", "at", ["At"]),
  cloze("ex-53-2-5", "53.2 · At / on / in", "She lives ___ the third floor.", "on", ["On"]),
  cloze("ex-53-2-6", "53.2 · At / on / in", "There's a spider ___ the bath and one ___ the bathroom.", "in", ["In"]),
  match("ex-53-3", "53.3 · Ghép vị trí", [
    { left: "the back of", right: "the bus" },
    { left: "the front of", right: "the bus" },
    { left: "the top of", right: "the tree" },
    { left: "the middle of", right: "the tree" },
    { left: "the bottom of", right: "the tree" },
  ]),
  cloze("ex-53-4-2", "53.4 · Out / away", "He went ___ of the room.", "out", ["Out"]),
  cloze("ex-53-4-3", "53.4 · Out / away", "She's gone ___ for a few days.", "away", ["Away"]),
  cloze("ex-53-4-4", "53.4 · Out / away", "They're going ___ on holiday.", "away", ["Away", "abroad", "Abroad"]),
  cloze("ex-53-5-2", "53.5 · Vị trí trong sách", "The Answer key is at the ___ of this book.", "end", ["End"]),
  cloze("ex-53-5-4", "53.5 · Vị trí trong sách", "At the moment I have a pen in my ___ hand.", "right", ["Right"]),
  cloze("ex-53-5-5", "53.5 · Vị trí trong sách", "Unit 3 is at the ___ of this book.", "beginning", ["Beginning"]),
  cloze("ex-53-5-6", "53.5 · Vị trí trong sách", "Unit 36 is in the ___ of this book.", "middle", ["Middle"]),
];

const UNIT_54: VocabularyExercise[] = [
  cloze("ex-54-1-2", "54.1 · Trạng từ", "He sings ___.", "badly", ["Badly"]),
  cloze("ex-54-1-3", "54.1 · Trạng từ", "She speaks ___.", "loudly", ["Loudly"]),
  cloze("ex-54-1-4", "54.1 · Trạng từ", "He drives very ___.", "fast", ["Fast"]),
  cloze("ex-54-1-5", "54.1 · Trạng từ", "Please speak ___.", "quietly", ["Quietly"]),
  cloze("ex-54-1-6", "54.1 · Trạng từ", "She sings very ___.", "well", ["Well"]),
  mcq("ex-54-2-2", "54.2 · Chọn từ", "My dog is old and very ___.", "a", [
    { key: "a", label: "slow" },
    { key: "b", label: "slowly" },
    { key: "c", label: "good" },
    { key: "d", label: "well" },
  ]),
  mcq("ex-54-2-3", "54.2 · Chọn từ", "My brother speaks German ___.", "c", [
    { key: "a", label: "bad" },
    { key: "b", label: "good" },
    { key: "c", label: "badly" },
    { key: "d", label: "well" },
  ]),
  mcq("ex-54-2-4", "54.2 · Chọn từ", "Which word is NOT an adverb?", "c", [
    { key: "a", label: "sadly" },
    { key: "b", label: "strangely" },
    { key: "c", label: "suddenly (when meaning 'quickly')" },
    { key: "d", label: "easily" },
  ]),
  mcq("ex-54-2-5", "54.2 · Chọn từ", "I like to do things the ___ way.", "a", [
    { key: "a", label: "right" },
    { key: "b", label: "wrong" },
    { key: "c", label: "rightly" },
    { key: "d", label: "good" },
  ]),
  cloze("ex-54-3-2", "54.3 · Câu mẫu", "I usually eat too ___.", "fast", ["Fast"]),
  cloze("ex-54-3-3", "54.3 · Câu mẫu", "My mum always behaves in a friendly ___.", "way", ["Way"]),
  cloze("ex-54-3-4", "54.3 · Câu mẫu", "My dog is old and very ___.", "slow", ["Slow"]),
  cloze("ex-54-3-5", "54.3 · Câu mẫu", "My voice is ___.", "quiet", ["Quiet"]),
  cloze("ex-54-3-6", "54.3 · Câu mẫu", "I like to sing ___.", "loudly", ["Loudly"]),
];

const UNIT_55: VocabularyExercise[] = [
  mcq("ex-55-1-2", "55.1 · Không đếm được", "Which are uncountable?", "a", [
    { key: "a", label: "milk and butter" },
    { key: "b", label: "apples and eggs" },
    { key: "c", label: "books and chairs" },
    { key: "d", label: "cars and buses" },
  ]),
  mcq("ex-55-1-3", "55.1 · Không đếm được", "Which word is uncountable?", "c", [
    { key: "a", label: "chair" },
    { key: "b", label: "egg" },
    { key: "c", label: "advice" },
    { key: "d", label: "apple" },
  ]),
  mcq("ex-55-1-4", "55.1 · Không đếm được", "Which word is uncountable?", "d", [
    { key: "a", label: "book" },
    { key: "b", label: "table" },
    { key: "c", label: "pen" },
    { key: "d", label: "air" },
  ]),
  mcq("ex-55-1-5", "55.1 · Không đếm được", "Which word is uncountable?", "d", [
    { key: "a", label: "dog" },
    { key: "b", label: "student" },
    { key: "c", label: "teacher" },
    { key: "d", label: "work" },
  ]),
  mcq("ex-55-1-6", "55.1 · Không đếm được", "Which word is uncountable?", "d", [
    { key: "a", label: "house" },
    { key: "b", label: "car" },
    { key: "c", label: "bus" },
    { key: "d", label: "traffic" },
  ]),
  match("ex-55-2", "55.2 · Ghép từ", [
    { left: "a piece of", right: "advice" },
    { left: "a loaf of", right: "bread" },
    { left: "a bottle of", right: "water" },
    { left: "a bar of", right: "chocolate" },
    { left: "a cup of", right: "coffee" },
    { left: "a glass of", right: "milk" },
  ]),
  cloze("ex-55-3-2", "55.3 · Some + danh từ", "Where can I get some ___ about your country?", "information", ["Information"]),
  cloze("ex-55-3-3", "55.3 · Some + danh từ", "Let me give you some ___.", "advice", ["Advice"]),
  cloze("ex-55-3-5", "55.3 · Some + danh từ", "Can I have some ___, please?", "bread", ["Bread"]),
  cloze("ex-55-3-6", "55.3 · Some + danh từ", "We need to buy some new ___.", "furniture", ["Furniture"]),
  cloze("ex-55-3-8", "55.3 · Some + danh từ", "I must find some new ___ soon.", "accommodation", ["Accommodation"]),
  mcq("ex-55-4-2", "55.4 · Đúng / sai", "The east has a better weather than the west.", "b", [
    { key: "a", label: "Đúng" },
    { key: "b", label: "Sai — không dùng 'a' trước weather" },
    { key: "c", label: "Đúng — weather đếm được" },
    { key: "d", label: "Sai — phải dùng 'the better weathers'" },
  ]),
];

const UNIT_56: VocabularyExercise[] = [
  mcq("ex-56-1-2", "56.1 · Tính từ", "The food was very bad / terrible / ___.", "c", [
    { key: "a", label: "wonderful" },
    { key: "b", label: "lovely" },
    { key: "c", label: "awful" },
    { key: "d", label: "excellent" },
  ]),
  mcq("ex-56-1-4", "56.1 · Tính từ", "The hotel was excellent / great / ___.", "a", [
    { key: "a", label: "wonderful" },
    { key: "b", label: "dreadful" },
    { key: "c", label: "nasty" },
    { key: "d", label: "horrible" },
  ]),
  mcq("ex-56-2-2", "56.2 · Phản ứng", "Oh, how ___!", "a", [
    { key: "a", label: "awful" },
    { key: "b", label: "awfully" },
    { key: "c", label: "awfulness" },
    { key: "d", label: "more awful" },
  ]),
  mcq("ex-56-2-3", "56.2 · Phản ứng", "That's a lovely idea! / Yes, ___!", "b", [
    { key: "a", label: "dreadful" },
    { key: "b", label: "great" },
    { key: "c", label: "badly" },
    { key: "d", label: "terrible" },
  ]),
  mcq("ex-56-2-4", "56.2 · Phản ứng", "Yes, there's the Ritz. It's an ___ restaurant.", "d", [
    { key: "a", label: "awful" },
    { key: "b", label: "dreadful" },
    { key: "c", label: "nasty" },
    { key: "d", label: "excellent" },
  ]),
  match("ex-56-3", "56.3 · Ghép tính từ", [
    { left: "brilliant", right: "idea / scientist" },
    { left: "dreadful", right: "surprise / smell" },
    { left: "marvellous", right: "weather / food" },
    { left: "nasty", right: "surprise / smell" },
    { left: "fine", right: "weather / day" },
  ]),
  cloze("ex-56-4-1", "56.4 · Ô chữ", "Across: very good — b _ _ _ _ _ _ _ t", "brilliant", ["Brilliant"]),
  cloze("ex-56-4-2", "56.4 · Ô chữ", "Down: very bad — d _ _ _ _ _ _ _ l", "dreadful", ["Dreadful"]),
  cloze("ex-56-4-3", "56.4 · Ô chữ", "Across: wonderful — m _ _ _ _ _ _ _ s", "marvellous", ["Marvellous"]),
  cloze("ex-56-4-4", "56.4 · Ô chữ", "Down: unpleasant — n _ _ _ _", "nasty", ["Nasty"]),
  cloze("ex-56-4-5", "56.4 · Ô chữ", "Across: OK / good — f _ _ _", "fine", ["Fine"]),
  cloze("ex-56-5-1", "56.5 · Cặp từ", "a ___ idea / scientist", "brilliant", ["Brilliant"]),
  cloze("ex-56-5-2", "56.5 · Cặp từ", "a ___ surprise / smell", "nasty", ["Nasty"]),
  cloze("ex-56-5-3", "56.5 · Cặp từ", "___ weather / food", "marvellous", ["Marvellous"]),
];

const UNIT_57: VocabularyExercise[] = [
  mcq("ex-57-1-2", "57.1 · Giới từ", "This bicycle belongs ___ the hotel.", "d", [
    { key: "a", label: "for" },
    { key: "b", label: "about" },
    { key: "c", label: "at" },
    { key: "d", label: "to" },
  ]),
  mcq("ex-57-1-3", "57.1 · Giới từ", "The children thanked their aunt ___ the money.", "a", [
    { key: "a", label: "for" },
    { key: "b", label: "to" },
    { key: "c", label: "about" },
    { key: "d", label: "at" },
  ]),
  mcq("ex-57-1-4", "57.1 · Giới từ", "Molly is listening ___ music on her phone.", "b", [
    { key: "a", label: "for" },
    { key: "b", label: "to" },
    { key: "c", label: "about" },
    { key: "d", label: "at" },
  ]),
  mcq("ex-57-1-5", "57.1 · Giới từ", "He apologised ___ his mistake.", "a", [
    { key: "a", label: "for" },
    { key: "b", label: "to" },
    { key: "c", label: "at" },
    { key: "d", label: "about" },
  ]),
  mcq("ex-57-1-6", "57.1 · Giới từ", "Let me pay ___ our tickets.", "a", [
    { key: "a", label: "for" },
    { key: "b", label: "to" },
    { key: "c", label: "about" },
    { key: "d", label: "at" },
  ]),
  mcq("ex-57-1-7", "57.1 · Giới từ", "Javier is thinking ___ the holidays.", "d", [
    { key: "a", label: "for" },
    { key: "b", label: "to" },
    { key: "c", label: "at" },
    { key: "d", label: "about" },
  ]),
  cloze("ex-57-2-2", "57.2 · Hoàn thành cụm", "I look forward ___ my party.", "to", ["To"]),
  cloze("ex-57-2-3", "57.2 · Hoàn thành cụm", "Thank you ___ them.", "for", ["For"]),
  cloze("ex-57-2-5", "57.2 · Hoàn thành cụm", "She shouted ___ me.", "at", ["At"]),
  cloze("ex-57-2-6", "57.2 · Hoàn thành cụm", "I'm looking ___ a new one.", "for", ["For"]),
  cloze("ex-57-3-2", "57.3 · At / to / in / of", "Hiroshi wasn't used to eating British ___.", "food", ["Food"]),
  cloze("ex-57-3-4", "57.3 · At / to / in / of", "He was used to traffic ___.", "jams", ["Jams", "jam", "Jam"]),
  cloze("ex-57-4-1", "57.4 · Cụm thường gặp", "I was good ___ languages and bad at PE.", "at", ["At"]),
  cloze("ex-57-4-3", "57.4 · Cụm thường gặp", "I am proud ___ my family.", "of", ["Of"]),
  cloze("ex-57-4-4", "57.4 · Cụm thường gặp", "I am afraid ___ going to the dentist.", "of", ["Of"]),
  cloze("ex-57-4-6", "57.4 · Cụm thường gặp", "I am looking forward ___ my holiday.", "to", ["To"]),
  cloze("ex-57-4-7", "57.4 · Cụm thường gặp", "I belong ___ a tennis club.", "to", ["To"]),
];

const UNIT_58: VocabularyExercise[] = [
  cloze("ex-58-1-2", "58.1 · Tiền tố", "Please ___ your essay. (write again)", "rewrite", ["Rewrite"]),
  cloze("ex-58-1-3", "58.1 · Tiền tố", "This is an ___ word — not used in formal writing.", "informal", ["Informal"]),
  cloze("ex-58-1-4", "58.1 · Tiền tố", "She was very ___ after the news.", "unhappy", ["Unhappy"]),
  cloze("ex-58-1-5", "58.1 · Tiền tố", "Everything in the shop is ___ today.", "half-price", ["Half-price", "half price", "Half price"]),
  cloze("ex-58-1-6", "58.1 · Tiền tố", "It is ___ to walk alone at night here.", "unsafe", ["Unsafe"]),
  cloze("ex-58-2-2", "58.2 · Tiền tố", "I never see my ___-boyfriend anymore.", "ex", ["Ex"]),
  cloze("ex-58-2-3", "58.2 · Tiền từ", "This work is not very good. Please ___ it.", "redo", ["Redo"]),
  cloze("ex-58-2-4", "58.2 · Tiền tố", "It's ___ to read his handwriting.", "impossible", ["Impossible"]),
  cloze("ex-58-2-5", "58.2 · Tiền tố", "___-school children learn by playing.", "Pre", ["Pre"]),
  cloze("ex-58-3-2", "58.3 · Un-/im-/in-", "This chair is very ___.", "uncomfortable", ["Uncomfortable"]),
  cloze("ex-58-3-3", "58.3 · Un-/im-/in-", "It was ___ of him not to say thank you.", "impolite", ["Impolite"]),
  cloze("ex-58-3-4", "58.3 · Un-/im-/in-", "The smell in the room was ___.", "unpleasant", ["Unpleasant"]),
  cloze("ex-58-3-5", "58.3 · Un-/im-/in-", "He finds the picture ___.", "unattractive", ["Unattractive"]),
  mcq("ex-58-4-1", "58.4 · Chọn tiền tố", "My daughter's room is always very ___.", "a", [
    { key: "a", label: "untidy" },
    { key: "b", label: "retidy" },
    { key: "c", label: "intidy" },
    { key: "d", label: "nontidy" },
  ]),
  mcq("ex-58-4-2", "58.4 · Chọn tiền tố", "We're going to ___paint this room next week.", "b", [
    { key: "a", label: "un" },
    { key: "b", label: "re" },
    { key: "c", label: "pre" },
    { key: "d", label: "non" },
  ]),
];

const UNIT_59: VocabularyExercise[] = [
  cloze("ex-59-1-2", "59.1 · Hậu tố", "A person who teaches skiing is a ski ___.", "instructor", ["Instructor"]),
  cloze("ex-59-1-3", "59.1 · Hậu tố", "Tom is a good ___.", "swimmer", ["Swimmer"]),
  cloze("ex-59-1-4", "59.1 · Hậu tố", "They lived ___ ever after.", "happily", ["Happily"]),
  cloze("ex-59-1-5", "59.1 · Hậu tố", "Use a ___ for difficult sums.", "calculator", ["Calculator"]),
  cloze("ex-59-1-6", "59.1 · Hậu tố", "This dictionary is very ___.", "useful", ["Useful"]),
  cloze("ex-59-2-2", "59.2 · Ghép từ", "a fast ___ / car / swimmer", "worker", ["Worker"]),
  cloze("ex-59-2-3", "59.2 · Ghép từ", "a beautiful ___ / weather / smile", "beach", ["Beach", "book", "Book", "picture", "Picture"]),
  cloze("ex-59-2-4", "59.2 · Ghép từ", "a sandy ___", "beach", ["Beach"]),
  cloze("ex-59-2-5", "59.2 · Ghép từ", "sunny ___ / smile", "weather", ["Weather"]),
  cloze("ex-59-2-6", "59.2 · Ghép từ", "a hard ___", "worker", ["Worker"]),
  cloze("ex-59-3-2", "59.3 · Hậu tố -ly/-ness/-ful", "She sings ___.", "badly", ["Badly"]),
  cloze("ex-59-3-3", "59.3 · Hậu tố -ly/-ness/-ful", "Thank you for being so ___.", "helpful", ["Helpful"]),
  cloze("ex-59-3-4", "59.3 · Hậu tố -ly/-ness/-ful", "Thank you for your ___.", "kindness", ["Kindness"]),
  cloze("ex-59-3-5", "59.3 · Hậu tố -ly/-ness/-ful", "It was ___ of you to leave the door open.", "careless", ["Careless"]),
  cloze("ex-59-3-6", "59.3 · Hậu tố -ly/-ness/-ful", "It was very ___ yesterday.", "windy", ["Windy"]),
  cloze("ex-59-3-7", "59.3 · Hậu tố -ly/-ness/-ful", "She passed the exam ___.", "easily", ["Easily"]),
  cloze("ex-59-3-8", "59.3 · Hậu tố -ly/-ness/-ful", "My father is a ___.", "builder", ["Builder"]),
  match("ex-59-4", "59.4 · Ghép định nghĩa", [
    { left: "traveller", right: "a person who travels" },
    { left: "slowly", right: "the opposite of fast (adverb)" },
    { left: "rainy", right: "weather when it is raining" },
    { left: "tin opener", right: "a thing for opening tins" },
    { left: "footballer", right: "a person who plays football" },
  ]),
];

const UNIT_60: VocabularyExercise[] = [
  cloze("ex-60-1-2", "60.1 · Chọn từ đúng", "Be careful or you'll ___ your keys.", "lose", ["Lose"]),
  cloze("ex-60-1-3", "60.1 · Chọn từ đúng", "I ___ ill yesterday.", "felt", ["Felt"]),
  cloze("ex-60-1-4", "60.1 · Chọn từ đúng", "We bought a new ___ last week. (kitchen appliance)", "cooker", ["Cooker"]),
  cloze("ex-60-1-5", "60.1 · Chọn từ đúng", "She ___ off her bike.", "fell", ["Fell"]),
  cloze("ex-60-1-6", "60.1 · Chọn từ đúng", "It's ___ difficult.", "quite", ["Quite"]),
  cloze("ex-60-1-7", "60.1 · Chọn từ đúng", "These trousers are too ___.", "loose", ["Loose"]),
  cloze("ex-60-1-8", "60.1 · Chọn từ đúng", "I can't ___ very well.", "cook", ["Cook"]),
  mcq("ex-60-2-2", "60.2 · Cặp từ dễ nhầm", "The bottle top is ___. (not tight)", "a", [
    { key: "a", label: "loose" },
    { key: "b", label: "lose" },
    { key: "c", label: "quite" },
    { key: "d", label: "quiet" },
  ]),
  mcq("ex-60-2-3", "60.2 · Cặp từ dễ nhầm", "That's ___ right.", "b", [
    { key: "a", label: "quiet" },
    { key: "b", label: "quite" },
    { key: "c", label: "loose" },
    { key: "d", label: "lose" },
  ]),
  mcq("ex-60-2-4", "60.2 · Cặp từ dễ nhầm", "Please be ___.", "a", [
    { key: "a", label: "quiet" },
    { key: "b", label: "quite" },
    { key: "c", label: "loose" },
    { key: "d", label: "cook" },
  ]),
  cloze("ex-60-3-2", "60.3 · Hội thoại", "Can I ___ your camera?", "borrow", ["Borrow"]),
  cloze("ex-60-3-3", "60.3 · Hội thoại", "Can you ___ me £1?", "lend", ["Lend"]),
  cloze("ex-60-3-4", "60.3 · Hội thoại", "Good ___.", "afternoon", ["Afternoon"]),
  cloze("ex-60-3-5", "60.3 · Hội thoại", "They wait ___ the bus.", "for", ["For"]),
  cloze("ex-60-3-6", "60.3 · Hội thoại", "Please be ___.", "quiet", ["Quiet"]),
  mcq("ex-60-4-1", "60.4 · Hope / expect", "I am ___ my brother at 5.30. (= He said he would come)", "b", [
    { key: "a", label: "hoping" },
    { key: "b", label: "expecting" },
    { key: "c", label: "waiting" },
    { key: "d", label: "borrowing" },
  ]),
  mcq("ex-60-4-2", "60.4 · Hope / expect", "I hope to go on holiday to Spain. (= I really ___ to go)", "a", [
    { key: "a", label: "want" },
    { key: "b", label: "expect" },
    { key: "c", label: "borrow" },
    { key: "d", label: "lend" },
  ]),
  cloze("ex-60-4-3", "60.4 · Borrow / lend", "Sometimes I ___ books and DVDs.", "borrow", ["Borrow"]),
];

export const CURATED_UNITS_46_60: Readonly<Partial<Record<number, readonly VocabularyExercise[]>>> = {
  46: UNIT_46,
  47: UNIT_47,
  48: UNIT_48,
  49: UNIT_49,
  50: UNIT_50,
  51: UNIT_51,
  52: UNIT_52,
  53: UNIT_53,
  54: UNIT_54,
  55: UNIT_55,
  56: UNIT_56,
  57: UNIT_57,
  58: UNIT_58,
  59: UNIT_59,
  60: UNIT_60,
};

for (const [unitNumber, exercises] of Object.entries(CURATED_UNITS_46_60)) {
  if (exercises) {
    assertExerciseCount(Number(unitNumber), exercises);
  }
}
