import type { VocabularyUnit } from "@/lib/vocabulary/vocabulary-unit-types";
import { EVIU_ELEMENTARY_CATALOG } from "../eviu-elementary-catalog";
import { buildEviuUnit, bold, ex, fillBlank, mcq, purple } from "./eviu-unit-builder";

const CATALOG_BY_UNIT = new Map(EVIU_ELEMENTARY_CATALOG.map((entry) => [entry.unitNumber, entry]));

function getCatalog(unitNumber: number) {
  const entry = CATALOG_BY_UNIT.get(unitNumber);
  if (!entry) {
    throw new Error(`Missing EVIU catalog entry for unit ${unitNumber}`);
  }
  return entry;
}

export const EVIU_UNITS_31_45: VocabularyUnit[] = [
  buildEviuUnit(getCatalog(31), {
    introVi: "Từ vựng về thú cưng, động vật hoang dã, côn trùng và môi trường sống của chúng.",
    structureSections: [
      { label: "Pets and farm animals", wordCount: 9 },
      { label: "Wild animals", wordCount: 8 },
      { label: "Birds and insects", wordCount: 5 },
      { label: "Animal actions and habitats", wordCount: 5 },
    ],
    collocationHtml: `Các cụm thường gặp: ${purple("keep a pet")}, ${purple("feed the dog")}, ${purple("walk the dog")}, ${purple("wild animal park")}, ${purple("animal shelter")}.`,
    mistakeHtml: `${bold("a animals")} ${bold("[SAI]")} → dùng ${purple("an animal")} hoặc ${purple("animals")}.`,
    principles: [
      {
        title: "ĐỘNG VẬT NUÔI VÀ HOANG DÃ",
        body: `${purple("Pet")} là động vật nuôi trong nhà; ${purple("wild animal")} sống tự nhiên ngoài hoang dã.`,
        examples: [
          ex("My cat is a friendly pet.", "Mèo của tôi là một thú cưng thân thiện."),
          ex("A tiger is a dangerous wild animal.", "Hổ là loài động vật hoang dã nguy hiểm."),
          ex("Some children want to keep a rabbit as a pet.", "Một số trẻ em muốn nuôi thỏ làm thú cưng."),
        ],
      },
      {
        title: "MÔI TRƯỜNG SỐNG",
        body: `Học động vật theo nơi sống: ${purple("on a farm")}, ${purple("in the forest")}, ${purple("in the sea")}.`,
        examples: [
          ex("Cows live on farms.", "Bò sống ở các trang trại."),
          ex("Monkeys live in forests.", "Khỉ sống trong rừng."),
          ex("Whales live in the sea.", "Cá voi sống ở biển."),
        ],
      },
      {
        title: "ĐỘNG TỪ THƯỜNG DÙNG",
        body: `Dùng các động từ cơ bản như ${purple("feed")}, ${purple("hunt")}, ${purple("bite")}, ${purple("fly")}, ${purple("swim")}.`,
        examples: [
          ex("We feed our dog twice a day.", "Chúng tôi cho chó ăn hai lần mỗi ngày."),
          ex("Mosquitoes bite people at night.", "Muỗi đốt người vào ban đêm."),
          ex("Ducks can swim very well.", "Vịt có thể bơi rất giỏi."),
        ],
      },
    ],
    words: [
      { term: "pet", definition: "thú cưng", partOfSpeech: "NOUN", example: "A dog is a common pet." },
      { term: "puppy", definition: "chó con", partOfSpeech: "NOUN", example: "Their puppy is only three months old." },
      { term: "kitten", definition: "mèo con", partOfSpeech: "NOUN", example: "The kitten is sleeping on the sofa." },
      { term: "rabbit", definition: "thỏ", partOfSpeech: "NOUN", example: "My sister keeps a white rabbit." },
      { term: "hamster", definition: "chuột hamster", partOfSpeech: "NOUN", example: "A hamster is a small pet." },
      { term: "cow", definition: "bò cái", partOfSpeech: "NOUN", example: "There are ten cows on the farm." },
      { term: "sheep", definition: "cừu", partOfSpeech: "NOUN", example: "Sheep eat grass in the field." },
      { term: "goat", definition: "dê", partOfSpeech: "NOUN", example: "The goat climbed onto the rock." },
      { term: "horse", definition: "ngựa", partOfSpeech: "NOUN", example: "He rides a horse every weekend." },
      { term: "lion", definition: "sư tử", partOfSpeech: "NOUN", example: "The lion is sleeping under the tree." },
      { term: "tiger", definition: "hổ", partOfSpeech: "NOUN", example: "A tiger has black stripes." },
      { term: "elephant", definition: "voi", partOfSpeech: "NOUN", example: "Elephants have long trunks." },
      { term: "monkey", definition: "khỉ", partOfSpeech: "NOUN", example: "The monkey is eating a banana." },
      { term: "bear", definition: "gấu", partOfSpeech: "NOUN", example: "Bears can run fast." },
      { term: "fox", definition: "cáo", partOfSpeech: "NOUN", example: "A fox is hunting at night." },
      { term: "deer", definition: "hươu", partOfSpeech: "NOUN", example: "We saw a deer in the forest." },
      { term: "whale", definition: "cá voi", partOfSpeech: "NOUN", example: "A whale is bigger than a shark." },
      { term: "eagle", definition: "đại bàng", partOfSpeech: "NOUN", example: "The eagle flies very high." },
      { term: "owl", definition: "cú", partOfSpeech: "NOUN", example: "An owl hunts at night." },
      { term: "duck", definition: "vịt", partOfSpeech: "NOUN", example: "The duck is swimming in the lake." },
      { term: "butterfly", definition: "bướm", partOfSpeech: "NOUN", example: "A butterfly landed on the flower." },
      { term: "bee", definition: "ong", partOfSpeech: "NOUN", example: "Bees make honey." },
      { term: "mosquito", definition: "muỗi", partOfSpeech: "NOUN", example: "A mosquito bit my arm." },
      { term: "habitat", definition: "môi trường sống", partOfSpeech: "NOUN", example: "Pollution damages animal habitats." },
      { term: "feed", definition: "cho ăn", partOfSpeech: "VERB", example: "Please feed the cat at six." },
      { term: "hunt", definition: "săn", partOfSpeech: "VERB", example: "Wolves hunt in groups." },
      { term: "bite", definition: "cắn", partOfSpeech: "VERB", example: "Be careful: that dog may bite." },
    ],
    exercises: [
      mcq(
        31,
        1,
        "Which animal is usually kept as a pet at home?",
        [
          { key: "a", label: "puppy" },
          { key: "b", label: "lion" },
          { key: "c", label: "whale" },
          { key: "d", label: "eagle" },
        ],
        "a",
      ),
      fillBlank(
        31,
        2,
        "We need to ___ the dog before we go out.",
        "feed",
        [
          { key: "a", label: "feed" },
          { key: "b", label: "hunt" },
          { key: "c", label: "bite" },
          { key: "d", label: "fly" },
        ],
        "a",
        ["Feed"],
      ),
      mcq(
        31,
        3,
        "Which animal is famous for having a trunk?",
        [
          { key: "a", label: "fox" },
          { key: "b", label: "elephant" },
          { key: "c", label: "deer" },
          { key: "d", label: "goat" },
        ],
        "b",
      ),
      fillBlank(
        31,
        4,
        "An owl usually hunts at ___.",
        "night",
        [
          { key: "a", label: "night" },
          { key: "b", label: "noon" },
          { key: "c", label: "breakfast" },
          { key: "d", label: "spring" },
        ],
        "a",
      ),
    ],
  }),
  buildEviuUnit(getCatalog(32), {
    introVi: "Từ vựng về phương tiện đi lại, sân bay, ga tàu và các tình huống di chuyển phổ biến.",
    structureSections: [
      { label: "Transport", wordCount: 10 },
      { label: "Travel documents and planning", wordCount: 7 },
      { label: "At airports and stations", wordCount: 7 },
      { label: "Travel problems and actions", wordCount: 4 },
    ],
    collocationHtml: `Các cụm thường gặp: ${purple("book a ticket")}, ${purple("catch a train")}, ${purple("miss a flight")}, ${purple("check in online")}, ${purple("go through security")}.`,
    mistakeHtml: `${bold("travel by the bus")} ${bold("[SAI]")} → dùng ${purple("travel by bus")} hoặc ${purple("travel by train")}.`,
    principles: [
      {
        title: "CÁCH DI CHUYỂN",
        body: `Dùng ${purple("by car / by bus / by plane")} cho phương tiện; ${purple("on foot")} cho đi bộ.`,
        examples: [
          ex("We travelled by train.", "Chúng tôi đi bằng tàu hỏa."),
          ex("She goes to work on foot.", "Cô ấy đi bộ đến chỗ làm."),
          ex("They flew to Singapore.", "Họ bay đến Singapore."),
        ],
      },
      {
        title: "QUY TRÌNH Ở SÂN BAY",
        body: `Quy trình cơ bản: ${purple("check in")} -> ${purple("drop your bag")} -> ${purple("go through security")} -> ${purple("board")}.`,
        examples: [
          ex("I checked in online last night.", "Tối qua tôi đã làm thủ tục trực tuyến."),
          ex("Please go through security now.", "Vui lòng qua khu kiểm tra an ninh ngay bây giờ."),
          ex("Boarding starts at Gate 12.", "Việc lên máy bay bắt đầu ở cổng 12."),
        ],
      },
      {
        title: "SỰ CỐ KHI ĐI LẠI",
        body: `Mẫu câu thường gặp: ${purple("The flight is delayed.")}, ${purple("I missed the train.")}, ${purple("My luggage is lost.")}.`,
        examples: [
          ex("Our bus was delayed by an hour.", "Xe buýt của chúng tôi bị trễ một giờ."),
          ex("He missed his flight because of traffic.", "Anh ấy lỡ chuyến bay vì kẹt xe."),
          ex("I reported my lost luggage at the desk.", "Tôi đã báo mất hành lý ở quầy."),
        ],
      },
    ],
    words: [
      { term: "travel", definition: "đi lại; du lịch", partOfSpeech: "VERB", example: "I travel a lot for work." },
      { term: "trip", definition: "chuyến đi", partOfSpeech: "NOUN", example: "We had a short trip to Da Nang." },
      { term: "journey", definition: "hành trình", partOfSpeech: "NOUN", example: "The journey took six hours." },
      { term: "tourist", definition: "khách du lịch", partOfSpeech: "NOUN", example: "The city is full of tourists in summer." },
      { term: "guide", definition: "hướng dẫn viên", partOfSpeech: "NOUN", example: "Our guide showed us the old town." },
      { term: "bus", definition: "xe buýt", partOfSpeech: "NOUN", example: "I take the bus to school." },
      { term: "coach", definition: "xe khách", partOfSpeech: "NOUN", example: "We went by coach to the beach." },
      { term: "train", definition: "tàu hỏa", partOfSpeech: "NOUN", example: "The train leaves at 7:30." },
      { term: "underground", definition: "tàu điện ngầm", partOfSpeech: "NOUN", example: "London has a busy underground system." },
      { term: "flight", definition: "chuyến bay", partOfSpeech: "NOUN", example: "Our flight arrives at midnight." },
      { term: "passport", definition: "hộ chiếu", partOfSpeech: "NOUN", example: "Don't forget your passport." },
      { term: "visa", definition: "thị thực", partOfSpeech: "NOUN", example: "She needs a visa for this country." },
      { term: "ticket", definition: "vé", partOfSpeech: "NOUN", example: "I booked my ticket online." },
      { term: "booking", definition: "sự đặt chỗ", partOfSpeech: "NOUN", example: "Your hotel booking is confirmed." },
      { term: "itinerary", definition: "lịch trình", partOfSpeech: "NOUN", example: "Our itinerary includes three cities." },
      { term: "platform", definition: "sân ga", partOfSpeech: "NOUN", example: "The train leaves from platform 2." },
      { term: "gate", definition: "cổng ra máy bay", partOfSpeech: "NOUN", example: "Please wait at gate 21." },
      { term: "luggage", definition: "hành lý", partOfSpeech: "NOUN", example: "My luggage is very heavy." },
      { term: "security", definition: "an ninh", partOfSpeech: "NOUN", example: "You must pass security first." },
      { term: "boarding pass", definition: "thẻ lên máy bay", partOfSpeech: "NOUN", example: "Show your boarding pass at the gate." },
      { term: "check in", definition: "làm thủ tục", partOfSpeech: "VERB", example: "We checked in two hours early." },
      { term: "depart", definition: "khởi hành", partOfSpeech: "VERB", example: "The train departs at 9:00." },
      { term: "arrive", definition: "đến nơi", partOfSpeech: "VERB", example: "We arrived late at night." },
      { term: "delay", definition: "trì hoãn", partOfSpeech: "VERB", example: "Fog delayed our flight." },
      { term: "miss", definition: "lỡ", partOfSpeech: "VERB", example: "I missed my bus this morning." },
      { term: "cancel", definition: "hủy", partOfSpeech: "VERB", example: "They cancelled the flight." },
    ],
    exercises: [
      mcq(
        32,
        1,
        "What do you show before you get on the plane?",
        [
          { key: "a", label: "boarding pass" },
          { key: "b", label: "menu" },
          { key: "c", label: "receipt" },
          { key: "d", label: "newspaper" },
        ],
        "a",
      ),
      fillBlank(
        32,
        2,
        "Please go through ___ before you enter the gate area.",
        "security",
        [
          { key: "a", label: "security" },
          { key: "b", label: "garden" },
          { key: "c", label: "kitchen" },
          { key: "d", label: "library" },
        ],
        "a",
      ),
      mcq(
        32,
        3,
        "Which phrase is correct?",
        [
          { key: "a", label: "travel by bus" },
          { key: "b", label: "travel with bus the" },
          { key: "c", label: "travel in foot" },
          { key: "d", label: "travel at plane" },
        ],
        "a",
      ),
      fillBlank(
        32,
        4,
        "I woke up late and ___ my train.",
        "missed",
        [
          { key: "a", label: "missed" },
          { key: "b", label: "arrived" },
          { key: "c", label: "departed" },
          { key: "d", label: "boarded" },
        ],
        "a",
      ),
    ],
  }),
  buildEviuUnit(getCatalog(33), {
    introVi: "Từ vựng cơ bản về văn hóa, đời sống và biểu tượng quen thuộc của Vương quốc Anh.",
    structureSections: [
      { label: "Places and institutions", wordCount: 8 },
      { label: "Traditions and events", wordCount: 8 },
      { label: "Food and daily life", wordCount: 6 },
      { label: "People and symbols", wordCount: 4 },
    ],
    collocationHtml: `Các cụm thường gặp: ${purple("British weather")}, ${purple("afternoon tea")}, ${purple("public holiday")}, ${purple("the royal family")}, ${purple("queue for the bus")}.`,
    mistakeHtml: `${bold("in UK")} ${bold("[SAI]")} → dùng ${purple("in the UK")}.`,
    principles: [
      {
        title: "TÊN GỌI QUỐC GIA",
        body: `${purple("the UK")} là tên chính thức rút gọn; ${purple("Britain")} thường chỉ Great Britain trong ngữ cảnh đời sống.`,
        examples: [
          ex("She lives in the UK.", "Cô ấy sống ở Vương quốc Anh."),
          ex("Britain has many old castles.", "Anh có nhiều lâu đài cổ."),
          ex("London is the capital of the UK.", "London là thủ đô của Vương quốc Anh."),
        ],
      },
      {
        title: "THÓI QUEN XÃ HỘI",
        body: `Một thói quen nổi bật là ${purple("queueing")} và dùng ${purple("please")}, ${purple("sorry")} thường xuyên.`,
        examples: [
          ex("People queue for buses.", "Mọi người xếp hàng chờ xe buýt."),
          ex("Sorry, is this seat free?", "Xin lỗi, chỗ này còn trống không?"),
          ex("Please stand on the right.", "Vui lòng đứng về phía bên phải."),
        ],
      },
      {
        title: "TỪ KHÓA VĂN HÓA",
        body: `Các cụm quen thuộc: ${purple("afternoon tea")}, ${purple("fish and chips")}, ${purple("public holiday")}, ${purple("the royal family")}.`,
        examples: [
          ex("We had afternoon tea at a small cafe.", "Chúng tôi dùng trà chiều ở một quán cà phê nhỏ."),
          ex("Fish and chips is a famous British dish.", "Fish and chips là món ăn nổi tiếng của Anh."),
          ex("Many people watched the royal event on TV.", "Nhiều người xem sự kiện hoàng gia trên TV."),
        ],
      },
    ],
    words: [
      { term: "the UK", definition: "Vương quốc Anh", partOfSpeech: "NOUN", example: "My aunt moved to the UK last year." },
      { term: "Britain", definition: "nước Anh (Great Britain)", partOfSpeech: "NOUN", example: "Britain has a long history." },
      { term: "England", definition: "nước Anh", partOfSpeech: "NOUN", example: "Manchester is in England." },
      { term: "Scotland", definition: "Scotland", partOfSpeech: "NOUN", example: "Edinburgh is in Scotland." },
      { term: "Wales", definition: "xứ Wales", partOfSpeech: "NOUN", example: "My friend is from Wales." },
      { term: "Northern Ireland", definition: "Bắc Ireland", partOfSpeech: "NOUN", example: "Belfast is in Northern Ireland." },
      { term: "capital city", definition: "thủ đô", partOfSpeech: "NOUN", example: "London is the capital city." },
      { term: "parliament", definition: "quốc hội", partOfSpeech: "NOUN", example: "The law was discussed in parliament." },
      { term: "royal family", definition: "hoàng gia", partOfSpeech: "NOUN", example: "The royal family appeared on the balcony." },
      { term: "king", definition: "vua", partOfSpeech: "NOUN", example: "The king gave a speech." },
      { term: "queen", definition: "nữ hoàng", partOfSpeech: "NOUN", example: "Many people admired the queen." },
      { term: "castle", definition: "lâu đài", partOfSpeech: "NOUN", example: "We visited an old stone castle." },
      { term: "museum", definition: "bảo tàng", partOfSpeech: "NOUN", example: "The museum is free on Sundays." },
      { term: "tradition", definition: "truyền thống", partOfSpeech: "NOUN", example: "This is a local tradition." },
      { term: "festival", definition: "lễ hội", partOfSpeech: "NOUN", example: "The city hosts a music festival." },
      { term: "public holiday", definition: "ngày nghỉ lễ", partOfSpeech: "NOUN", example: "Banks are closed on public holidays." },
      { term: "afternoon tea", definition: "tiệc trà chiều", partOfSpeech: "NOUN", example: "They served cakes at afternoon tea." },
      { term: "fish and chips", definition: "cá và khoai tây chiên", partOfSpeech: "NOUN", example: "We ate fish and chips by the sea." },
      { term: "queue", definition: "xếp hàng", partOfSpeech: "VERB", example: "People queue for tickets." },
      { term: "polite", definition: "lịch sự", partOfSpeech: "ADJECTIVE", example: "He is always polite to strangers." },
      { term: "weather", definition: "thời tiết", partOfSpeech: "NOUN", example: "The British weather changes quickly." },
      { term: "rainy", definition: "mưa nhiều", partOfSpeech: "ADJECTIVE", example: "It was a rainy afternoon." },
      { term: "accent", definition: "giọng vùng miền", partOfSpeech: "NOUN", example: "She has a Scottish accent." },
      { term: "double-decker bus", definition: "xe buýt hai tầng", partOfSpeech: "NOUN", example: "We took a red double-decker bus." },
      { term: "pub", definition: "quán rượu kiểu Anh", partOfSpeech: "NOUN", example: "They met at the local pub." },
    ],
    exercises: [
      mcq(
        33,
        1,
        "What is a typical British social habit?",
        [
          { key: "a", label: "queueing for buses" },
          { key: "b", label: "driving on sidewalks" },
          { key: "c", label: "eating lunch at 6 a.m." },
          { key: "d", label: "calling everyone king" },
        ],
        "a",
      ),
      fillBlank(
        33,
        2,
        "London is the ___ city of the UK.",
        "capital",
        [
          { key: "a", label: "capital" },
          { key: "b", label: "quiet" },
          { key: "c", label: "village" },
          { key: "d", label: "farming" },
        ],
        "a",
      ),
      mcq(
        33,
        3,
        "Which food is strongly linked with UK culture?",
        [
          { key: "a", label: "fish and chips" },
          { key: "b", label: "sushi and ramen" },
          { key: "c", label: "tacos and salsa" },
          { key: "d", label: "kimchi and rice" },
        ],
        "a",
      ),
      fillBlank(
        33,
        4,
        "People often ___ in line before getting on the bus.",
        "queue",
        [
          { key: "a", label: "queue" },
          { key: "b", label: "jump" },
          { key: "c", label: "hide" },
          { key: "d", label: "drive" },
        ],
        "a",
      ),
    ],
  }),
  buildEviuUnit(getCatalog(34), {
    introVi: "Từ vựng về tội phạm, an ninh, cảnh sát và hệ thống pháp luật cơ bản.",
    structureSections: [
      { label: "Types of crime", wordCount: 8 },
      { label: "People in law and crime", wordCount: 7 },
      { label: "Police actions", wordCount: 6 },
      { label: "Court and punishment", wordCount: 4 },
    ],
    collocationHtml: `Các cụm thường gặp: ${purple("commit a crime")}, ${purple("report a theft")}, ${purple("call the police")}, ${purple("go to court")}, ${purple("break the law")}.`,
    mistakeHtml: `${bold("rob money")} ${bold("[SAI]")} → dùng ${purple("steal money")} hoặc ${purple("rob a bank")}.`,
    principles: [
      {
        title: "ĐỘNG TỪ VỀ TỘI PHẠM",
        body: `Phân biệt ${purple("steal something")} và ${purple("rob someone / a bank")}.`,
        examples: [
          ex("Someone stole my phone.", "Có người đã trộm điện thoại của tôi."),
          ex("Two men robbed a bank.", "Hai người đàn ông đã cướp một ngân hàng."),
          ex("The thief stole her bag on the bus.", "Tên trộm đã lấy túi của cô ấy trên xe buýt."),
        ],
      },
      {
        title: "QUY TRÌNH CẢNH SÁT",
        body: `Trình tự thường gặp: ${purple("report")} -> ${purple("investigate")} -> ${purple("arrest")} -> ${purple("charge")}.`,
        examples: [
          ex("She reported the theft immediately.", "Cô ấy đã báo vụ trộm ngay lập tức."),
          ex("Police arrested the suspect.", "Cảnh sát đã bắt nghi phạm."),
          ex("The court charged him with fraud.", "Tòa án buộc tội anh ta vì hành vi lừa đảo."),
        ],
      },
      {
        title: "NGÔN NGỮ PHÁP LUẬT",
        body: `Cụm nền tảng gồm ${purple("break the law")}, ${purple("against the law")}, ${purple("go to court")}, ${purple("be guilty")}.`,
        examples: [
          ex("Drunk driving is against the law.", "Lái xe khi say rượu là trái pháp luật."),
          ex("He went to court last week.", "Anh ấy đã ra tòa tuần trước."),
          ex("The judge said she was not guilty.", "Thẩm phán nói cô ấy vô tội."),
        ],
      },
    ],
    words: [
      { term: "crime", definition: "tội phạm", partOfSpeech: "NOUN", example: "Crime is rising in some areas." },
      { term: "criminal", definition: "tội phạm (người)", partOfSpeech: "NOUN", example: "The criminal escaped by car." },
      { term: "thief", definition: "kẻ trộm", partOfSpeech: "NOUN", example: "A thief took my wallet." },
      { term: "theft", definition: "vụ trộm", partOfSpeech: "NOUN", example: "The police are investigating the theft." },
      { term: "robbery", definition: "vụ cướp", partOfSpeech: "NOUN", example: "The robbery happened at night." },
      { term: "fraud", definition: "lừa đảo", partOfSpeech: "NOUN", example: "Online fraud is common now." },
      { term: "violence", definition: "bạo lực", partOfSpeech: "NOUN", example: "The film contains violence." },
      { term: "murder", definition: "giết người", partOfSpeech: "NOUN", example: "He was accused of murder." },
      { term: "victim", definition: "nạn nhân", partOfSpeech: "NOUN", example: "The victim called the police." },
      { term: "suspect", definition: "nghi phạm", partOfSpeech: "NOUN", example: "The suspect was seen near the bank." },
      { term: "witness", definition: "nhân chứng", partOfSpeech: "NOUN", example: "A witness gave a statement." },
      { term: "detective", definition: "thám tử", partOfSpeech: "NOUN", example: "The detective solved the case." },
      { term: "lawyer", definition: "luật sư", partOfSpeech: "NOUN", example: "She spoke to her lawyer." },
      { term: "judge", definition: "thẩm phán", partOfSpeech: "NOUN", example: "The judge listened carefully." },
      { term: "police officer", definition: "cảnh sát", partOfSpeech: "NOUN", example: "A police officer helped us." },
      { term: "arrest", definition: "bắt giữ", partOfSpeech: "VERB", example: "They arrested two men." },
      { term: "investigate", definition: "điều tra", partOfSpeech: "VERB", example: "The police are investigating the case." },
      { term: "charge", definition: "buộc tội", partOfSpeech: "VERB", example: "He was charged with robbery." },
      { term: "steal", definition: "trộm", partOfSpeech: "VERB", example: "Someone stole my bike." },
      { term: "rob", definition: "cướp", partOfSpeech: "VERB", example: "They robbed a small store." },
      { term: "court", definition: "tòa án", partOfSpeech: "NOUN", example: "The case went to court." },
      { term: "prison", definition: "nhà tù", partOfSpeech: "NOUN", example: "He spent two years in prison." },
      { term: "sentence", definition: "bản án", partOfSpeech: "NOUN", example: "She got a short sentence." },
      { term: "guilty", definition: "có tội", partOfSpeech: "ADJECTIVE", example: "The jury found him guilty." },
      { term: "innocent", definition: "vô tội", partOfSpeech: "ADJECTIVE", example: "She said she was innocent." },
    ],
    exercises: [
      mcq(
        34,
        1,
        "Choose the correct sentence:",
        [
          { key: "a", label: "Someone stole my bike." },
          { key: "b", label: "Someone robbed my bike." },
          { key: "c", label: "Someone stole me bank." },
          { key: "d", label: "Someone rob me money." },
        ],
        "a",
      ),
      fillBlank(
        34,
        2,
        "The police will ___ the case tomorrow.",
        "investigate",
        [
          { key: "a", label: "investigate" },
          { key: "b", label: "queue" },
          { key: "c", label: "publish" },
          { key: "d", label: "borrow" },
        ],
        "a",
      ),
      mcq(
        34,
        3,
        "A person who sees a crime is a ___ .",
        [
          { key: "a", label: "victim" },
          { key: "b", label: "witness" },
          { key: "c", label: "judge" },
          { key: "d", label: "driver" },
        ],
        "b",
      ),
      fillBlank(
        34,
        4,
        "Drink-driving is ___ the law.",
        "against",
        [
          { key: "a", label: "against" },
          { key: "b", label: "across" },
          { key: "c", label: "inside" },
          { key: "d", label: "among" },
        ],
        "a",
      ),
    ],
  }),
  buildEviuUnit(getCatalog(35), {
    introVi: "Từ vựng về báo chí, truyền hình, internet và mạng xã hội trong đời sống hiện đại.",
    structureSections: [
      { label: "Traditional media", wordCount: 8 },
      { label: "Digital media", wordCount: 9 },
      { label: "Content and audience", wordCount: 6 },
      { label: "Media actions", wordCount: 4 },
    ],
    collocationHtml: `Các cụm thường gặp: ${purple("watch the news")}, ${purple("read an article")}, ${purple("post online")}, ${purple("go viral")}, ${purple("fake news")}.`,
    mistakeHtml: `${bold("on radio")} ${bold("[SAI]")} → dùng ${purple("on the radio")} và ${purple("on TV")}.`,
    principles: [
      {
        title: "KÊNH TRUYỀN THÔNG",
        body: `Phân biệt ${purple("TV")}, ${purple("radio")}, ${purple("newspaper")}, ${purple("social media")}.`,
        examples: [
          ex("I heard it on the radio.", "Tôi nghe tin đó trên radio."),
          ex("She saw it on TV.", "Cô ấy thấy điều đó trên TV."),
          ex("He read it in a newspaper.", "Anh ấy đọc điều đó trên báo giấy."),
        ],
      },
      {
        title: "NỘI DUNG TRỰC TUYẾN",
        body: `Các cụm phổ biến: ${purple("post a video")}, ${purple("share a link")}, ${purple("write a comment")}, ${purple("go viral")}.`,
        examples: [
          ex("She posted a short video.", "Cô ấy đã đăng một video ngắn."),
          ex("Please share the link with your class.", "Hãy chia sẻ đường link với lớp của bạn."),
          ex("That clip went viral in one day.", "Đoạn clip đó lan truyền mạnh chỉ trong một ngày."),
        ],
      },
      {
        title: "KIỂM CHỨNG THÔNG TIN",
        body: `Nên ${purple("check the source")} và ${purple("verify the facts")} để tránh ${purple("fake news")}.`,
        examples: [
          ex("Don't trust every headline online.", "Đừng tin mọi tiêu đề trên mạng."),
          ex("Always check the source first.", "Luôn kiểm tra nguồn trước."),
          ex("We verified the facts before publishing.", "Chúng tôi đã kiểm chứng sự thật trước khi xuất bản."),
        ],
      },
    ],
    words: [
      { term: "media", definition: "truyền thông", partOfSpeech: "NOUN", example: "The media reported the story quickly." },
      { term: "newspaper", definition: "báo giấy", partOfSpeech: "NOUN", example: "My grandfather reads a newspaper every morning." },
      { term: "magazine", definition: "tạp chí", partOfSpeech: "NOUN", example: "She bought a fashion magazine." },
      { term: "headline", definition: "tiêu đề lớn", partOfSpeech: "NOUN", example: "The headline was shocking." },
      { term: "article", definition: "bài viết", partOfSpeech: "NOUN", example: "I read an article about climate change." },
      { term: "journalist", definition: "nhà báo", partOfSpeech: "NOUN", example: "A journalist interviewed the singer." },
      { term: "reporter", definition: "phóng viên", partOfSpeech: "NOUN", example: "The reporter is live from Hanoi." },
      { term: "editor", definition: "biên tập viên", partOfSpeech: "NOUN", example: "The editor corrected the text." },
      { term: "television (TV)", definition: "truyền hình", partOfSpeech: "NOUN", example: "There is nothing good on TV tonight." },
      { term: "radio", definition: "đài phát thanh", partOfSpeech: "NOUN", example: "I listen to the radio in the car." },
      { term: "channel", definition: "kênh", partOfSpeech: "NOUN", example: "Switch to channel 5, please." },
      { term: "program", definition: "chương trình", partOfSpeech: "NOUN", example: "This program starts at 8 p.m." },
      { term: "podcast", definition: "podcast", partOfSpeech: "NOUN", example: "I follow a history podcast." },
      { term: "website", definition: "trang web", partOfSpeech: "NOUN", example: "Their website is easy to use." },
      { term: "social media", definition: "mạng xã hội", partOfSpeech: "NOUN", example: "She spends too much time on social media." },
      { term: "post", definition: "bài đăng", partOfSpeech: "NOUN", example: "His post got many likes." },
      { term: "comment", definition: "bình luận", partOfSpeech: "NOUN", example: "I left a comment below the video." },
      { term: "subscribe", definition: "đăng ký theo dõi", partOfSpeech: "VERB", example: "Please subscribe to our channel." },
      { term: "broadcast", definition: "phát sóng", partOfSpeech: "VERB", example: "The match was broadcast live." },
      { term: "publish", definition: "xuất bản", partOfSpeech: "VERB", example: "The paper published the story today." },
      { term: "share", definition: "chia sẻ", partOfSpeech: "VERB", example: "Can you share this link?" },
      { term: "go viral", definition: "lan truyền mạnh", partOfSpeech: "VERB", example: "Her dance video went viral." },
      { term: "source", definition: "nguồn tin", partOfSpeech: "NOUN", example: "This source is reliable." },
      { term: "fake news", definition: "tin giả", partOfSpeech: "NOUN", example: "Many people believe fake news." },
      { term: "fact-check", definition: "kiểm chứng thông tin", partOfSpeech: "VERB", example: "Journalists should fact-check carefully." },
      { term: "audience", definition: "khán giả; người xem", partOfSpeech: "NOUN", example: "The show has a young audience." },
    ],
    exercises: [
      mcq(
        35,
        1,
        "Which collocation is correct?",
        [
          { key: "a", label: "watch the news" },
          { key: "b", label: "hear the newspaper" },
          { key: "c", label: "read the radio" },
          { key: "d", label: "post the television" },
        ],
        "a",
      ),
      fillBlank(
        35,
        2,
        "The video became very popular and ___ online.",
        "went viral",
        [
          { key: "a", label: "went viral" },
          { key: "b", label: "broke law" },
          { key: "c", label: "took bath" },
          { key: "d", label: "did bed" },
        ],
        "a",
      ),
      mcq(
        35,
        3,
        "Before sharing news, we should check the ___ .",
        [
          { key: "a", label: "source" },
          { key: "b", label: "weather" },
          { key: "c", label: "platform shoes" },
          { key: "d", label: "traffic light" },
        ],
        "a",
      ),
      fillBlank(
        35,
        4,
        "This football match was ___ live on TV.",
        "broadcast",
        [
          { key: "a", label: "broadcast" },
          { key: "b", label: "arrested" },
          { key: "c", label: "planted" },
          { key: "d", label: "borrowed" },
        ],
        "a",
      ),
    ],
  }),
  buildEviuUnit(getCatalog(36), {
    introVi: "Từ vựng về các vấn đề thường gặp ở nhà và nơi làm việc cùng cách mô tả, xử lý.",
    structureSections: [
      { label: "Home problems", wordCount: 9 },
      { label: "Workplace problems", wordCount: 9 },
      { label: "Feelings and reactions", wordCount: 4 },
      { label: "Solving problems", wordCount: 3 },
    ],
    collocationHtml: `Các cụm thường gặp: ${purple("have an argument")}, ${purple("be under pressure")}, ${purple("miss a deadline")}, ${purple("fix a problem")}, ${purple("ask for help")}.`,
    mistakeHtml: `${bold("problem to do")} ${bold("[SAI]")} → dùng ${purple("problem with something")} hoặc ${purple("problem doing something")}.`,
    principles: [
      {
        title: "VẤN ĐỀ Ở NHÀ",
        body: `Trong bối cảnh gia đình, thường dùng ${purple("have an argument")}, ${purple("make too much noise")}, ${purple("pay the bills late")}.`,
        examples: [
          ex("They had an argument about money.", "Họ đã cãi nhau về tiền bạc."),
          ex("Our neighbours make too much noise.", "Hàng xóm của chúng tôi gây quá nhiều tiếng ồn."),
          ex("I forgot to pay the electricity bill.", "Tôi quên thanh toán hóa đơn tiền điện."),
        ],
      },
      {
        title: "VẤN ĐỀ Ở CÔNG VIỆC",
        body: `Trong môi trường làm việc, các từ hay gặp là ${purple("deadline")}, ${purple("workload")}, ${purple("stress")}, ${purple("team conflict")}.`,
        examples: [
          ex("We have a tight deadline this week.", "Tuần này chúng tôi có hạn chót rất gấp."),
          ex("Her workload is very heavy.", "Khối lượng công việc của cô ấy rất nặng."),
          ex("The manager solved the team conflict quickly.", "Người quản lý đã giải quyết xung đột trong nhóm rất nhanh."),
        ],
      },
      {
        title: "NÓI VỀ GIẢI PHÁP",
        body: `Khi đề xuất cách xử lý, có thể dùng ${purple("We need to fix this.")}, ${purple("Let's find a solution.")}, ${purple("Can you help me with this?")}.`,
        examples: [
          ex("Let's find a practical solution.", "Hãy tìm một giải pháp thực tế."),
          ex("Can you help me with this report?", "Bạn có thể giúp tôi với báo cáo này không?"),
          ex("We fixed the issue this morning.", "Chúng tôi đã khắc phục vấn đề vào sáng nay."),
        ],
      },
    ],
    words: [
      { term: "problem", definition: "vấn đề", partOfSpeech: "NOUN", example: "We have a problem with the internet." },
      { term: "issue", definition: "vấn đề (trang trọng hơn)", partOfSpeech: "NOUN", example: "There is an issue with the payment system." },
      { term: "argument", definition: "cuộc cãi vã", partOfSpeech: "NOUN", example: "They had an argument last night." },
      { term: "noise", definition: "tiếng ồn", partOfSpeech: "NOUN", example: "The noise from upstairs is terrible." },
      { term: "leak", definition: "rò rỉ", partOfSpeech: "NOUN", example: "There is a leak in the bathroom." },
      { term: "broken", definition: "bị hỏng", partOfSpeech: "ADJECTIVE", example: "Our washing machine is broken." },
      { term: "mess", definition: "bừa bộn", partOfSpeech: "NOUN", example: "The kitchen is a mess." },
      { term: "bill", definition: "hóa đơn", partOfSpeech: "NOUN", example: "I paid the water bill yesterday." },
      { term: "rent", definition: "tiền thuê nhà", partOfSpeech: "NOUN", example: "Rent is expensive in this area." },
      { term: "deadline", definition: "hạn chót", partOfSpeech: "NOUN", example: "The deadline is Friday afternoon." },
      { term: "workload", definition: "khối lượng công việc", partOfSpeech: "NOUN", example: "My workload is too heavy this month." },
      { term: "pressure", definition: "áp lực", partOfSpeech: "NOUN", example: "He works well under pressure." },
      { term: "stress", definition: "căng thẳng", partOfSpeech: "NOUN", example: "Too much stress can make you ill." },
      { term: "conflict", definition: "xung đột", partOfSpeech: "NOUN", example: "There is conflict between two teams." },
      { term: "complaint", definition: "lời phàn nàn", partOfSpeech: "NOUN", example: "The customer made a complaint." },
      { term: "mistake", definition: "lỗi sai", partOfSpeech: "NOUN", example: "I made a mistake in the report." },
      { term: "delay", definition: "sự chậm trễ", partOfSpeech: "NOUN", example: "A technical delay affected the project." },
      { term: "meeting", definition: "cuộc họp", partOfSpeech: "NOUN", example: "We had a long meeting this morning." },
      { term: "task", definition: "nhiệm vụ", partOfSpeech: "NOUN", example: "Please finish this task today." },
      { term: "worried", definition: "lo lắng", partOfSpeech: "ADJECTIVE", example: "I'm worried about my job." },
      { term: "frustrated", definition: "bực bội", partOfSpeech: "ADJECTIVE", example: "She felt frustrated with the delay." },
      { term: "fix", definition: "sửa; khắc phục", partOfSpeech: "VERB", example: "Can you fix the printer?" },
      { term: "solve", definition: "giải quyết", partOfSpeech: "VERB", example: "We solved the problem together." },
      { term: "discuss", definition: "thảo luận", partOfSpeech: "VERB", example: "Let's discuss this issue calmly." },
      { term: "ask for help", definition: "nhờ giúp đỡ", partOfSpeech: "VERB", example: "Don't be afraid to ask for help." },
    ],
    exercises: [
      mcq(
        36,
        1,
        "Which collocation is correct?",
        [
          { key: "a", label: "miss a deadline" },
          { key: "b", label: "eat a deadline" },
          { key: "c", label: "listen a deadline" },
          { key: "d", label: "borrow a deadline" },
        ],
        "a",
      ),
      fillBlank(
        36,
        2,
        "Our washing machine is ___, so we need to call someone.",
        "broken",
        [
          { key: "a", label: "broken" },
          { key: "b", label: "festival" },
          { key: "c", label: "innocent" },
          { key: "d", label: "queue" },
        ],
        "a",
      ),
      mcq(
        36,
        3,
        "What should you do first when a work issue appears?",
        [
          { key: "a", label: "Discuss it and find a solution" },
          { key: "b", label: "Ignore it for two weeks" },
          { key: "c", label: "Shout at everyone" },
          { key: "d", label: "Delete all files" },
        ],
        "a",
      ),
      fillBlank(
        36,
        4,
        "If the noise is too loud, you can make a ___.",
        "complaint",
        [
          { key: "a", label: "complaint" },
          { key: "b", label: "castle" },
          { key: "c", label: "tourist" },
          { key: "d", label: "platform" },
        ],
        "a",
      ),
    ],
  }),
  buildEviuUnit(getCatalog(37), {
    introVi: "Từ vựng nền tảng về các vấn đề toàn cầu: môi trường, xã hội, thiên tai và phát triển.",
    structureSections: [
      { label: "Environment", wordCount: 9 },
      { label: "Natural disasters", wordCount: 7 },
      { label: "Social and economic issues", wordCount: 6 },
      { label: "Action and solutions", wordCount: 3 },
    ],
    collocationHtml: `Các cụm thường gặp: ${purple("climate change")}, ${purple("global warming")}, ${purple("reduce pollution")}, ${purple("save energy")}, ${purple("protect wildlife")}.`,
    mistakeHtml: `${bold("many pollutions")} ${bold("[SAI]")} → dùng ${purple("a lot of pollution")}.`,
    principles: [
      {
        title: "THUẬT NGỮ MÔI TRƯỜNG",
        body: `Các cụm nền tảng gồm ${purple("climate change")}, ${purple("global warming")}, ${purple("air pollution")}, ${purple("water shortage")}.`,
        examples: [
          ex("Climate change affects everyone.", "Biến đổi khí hậu ảnh hưởng đến tất cả mọi người."),
          ex("Air pollution is serious in big cities.", "Ô nhiễm không khí nghiêm trọng ở các thành phố lớn."),
          ex("Some regions face water shortages.", "Một số khu vực đang đối mặt với tình trạng thiếu nước."),
        ],
      },
      {
        title: "THIÊN TAI",
        body: `Mô tả thảm họa bằng cụm: ${purple("an earthquake hit")}, ${purple("a flood destroyed homes")}, ${purple("a drought lasted months")}.`,
        examples: [
          ex("An earthquake hit the town.", "Một trận động đất đã xảy ra ở thị trấn."),
          ex("The flood destroyed many houses.", "Trận lũ đã phá hủy nhiều ngôi nhà."),
          ex("The drought lasted for months.", "Đợt hạn hán kéo dài nhiều tháng."),
        ],
      },
      {
        title: "NÓI VỀ GIẢI PHÁP",
        body: `Ưu tiên động từ hành động: ${purple("reduce")}, ${purple("reuse")}, ${purple("recycle")}, ${purple("protect")}, ${purple("support")}.`,
        examples: [
          ex("We should reduce plastic use.", "Chúng ta nên giảm việc sử dụng nhựa."),
          ex("People can recycle more at home.", "Mọi người có thể tái chế nhiều hơn tại nhà."),
          ex("Governments must protect forests.", "Chính phủ phải bảo vệ rừng."),
        ],
      },
    ],
    words: [
      { term: "climate change", definition: "biến đổi khí hậu", partOfSpeech: "NOUN", example: "Climate change is a global problem." },
      { term: "global warming", definition: "nóng lên toàn cầu", partOfSpeech: "NOUN", example: "Global warming causes extreme weather." },
      { term: "pollution", definition: "ô nhiễm", partOfSpeech: "NOUN", example: "Pollution harms our health." },
      { term: "air pollution", definition: "ô nhiễm không khí", partOfSpeech: "NOUN", example: "Air pollution is worse in winter." },
      { term: "water pollution", definition: "ô nhiễm nước", partOfSpeech: "NOUN", example: "Factories caused water pollution." },
      { term: "deforestation", definition: "nạn phá rừng", partOfSpeech: "NOUN", example: "Deforestation destroys habitats." },
      { term: "waste", definition: "rác thải", partOfSpeech: "NOUN", example: "We produce too much waste." },
      { term: "plastic", definition: "nhựa", partOfSpeech: "NOUN", example: "Single-use plastic is a major issue." },
      { term: "wildlife", definition: "động vật hoang dã", partOfSpeech: "NOUN", example: "Wildlife needs better protection." },
      { term: "earthquake", definition: "động đất", partOfSpeech: "NOUN", example: "The earthquake damaged roads." },
      { term: "flood", definition: "lũ lụt", partOfSpeech: "NOUN", example: "The flood covered the fields." },
      { term: "drought", definition: "hạn hán", partOfSpeech: "NOUN", example: "The drought killed many crops." },
      { term: "storm", definition: "bão", partOfSpeech: "NOUN", example: "A strong storm hit the coast." },
      { term: "wildfire", definition: "cháy rừng", partOfSpeech: "NOUN", example: "Wildfires spread quickly in dry weather." },
      { term: "famine", definition: "nạn đói", partOfSpeech: "NOUN", example: "Famine affects poor regions." },
      { term: "poverty", definition: "nghèo đói", partOfSpeech: "NOUN", example: "Poverty limits educational opportunities." },
      { term: "hunger", definition: "nạn đói; cơn đói", partOfSpeech: "NOUN", example: "Many children still suffer from hunger." },
      { term: "disease", definition: "bệnh tật", partOfSpeech: "NOUN", example: "Clean water prevents disease." },
      { term: "refugee", definition: "người tị nạn", partOfSpeech: "NOUN", example: "The country accepted many refugees." },
      { term: "conflict", definition: "xung đột", partOfSpeech: "NOUN", example: "Conflict forced people to leave home." },
      { term: "shortage", definition: "sự thiếu hụt", partOfSpeech: "NOUN", example: "There is a shortage of clean water." },
      { term: "reduce", definition: "giảm", partOfSpeech: "VERB", example: "We should reduce energy use." },
      { term: "recycle", definition: "tái chế", partOfSpeech: "VERB", example: "Our school recycles paper and plastic." },
      { term: "protect", definition: "bảo vệ", partOfSpeech: "VERB", example: "We must protect endangered animals." },
      { term: "support", definition: "hỗ trợ", partOfSpeech: "VERB", example: "They support local communities." },
    ],
    exercises: [
      mcq(
        37,
        1,
        "Which phrase is an environmental problem?",
        [
          { key: "a", label: "climate change" },
          { key: "b", label: "afternoon tea" },
          { key: "c", label: "double-decker bus" },
          { key: "d", label: "boarding pass" },
        ],
        "a",
      ),
      fillBlank(
        37,
        2,
        "We can help the planet by trying to ___ more waste.",
        "recycle",
        [
          { key: "a", label: "recycle" },
          { key: "b", label: "arrest" },
          { key: "c", label: "rob" },
          { key: "d", label: "queue" },
        ],
        "a",
      ),
      mcq(
        37,
        3,
        "A long period without rain is called a ___ .",
        [
          { key: "a", label: "flood" },
          { key: "b", label: "drought" },
          { key: "c", label: "storm" },
          { key: "d", label: "festival" },
        ],
        "b",
      ),
      fillBlank(
        37,
        4,
        "Our city needs to reduce air ___.",
        "pollution",
        [
          { key: "a", label: "pollution" },
          { key: "b", label: "podcast" },
          { key: "c", label: "meeting" },
          { key: "d", label: "ticket" },
        ],
        "a",
      ),
    ],
  }),
  buildEviuUnit(getCatalog(38), {
    introVi: "Động từ have trong các collocation hằng ngày: sinh hoạt, sức khỏe, giao tiếp và trải nghiệm.",
    structureSections: [
      { label: "Daily routines with have", wordCount: 8 },
      { label: "Events and experiences", wordCount: 8 },
      { label: "Health and feelings", wordCount: 6 },
      { label: "Useful chunks", wordCount: 4 },
    ],
    collocationHtml: `Các cụm thường gặp: ${purple("have breakfast")}, ${purple("have a shower")}, ${purple("have a break")}, ${purple("have a problem")}, ${purple("have a good time")}.`,
    mistakeHtml: `${bold("make a shower")} ${bold("[SAI]")} → dùng ${purple("have a shower")}.`,
    principles: [
      {
        title: "SINH HOẠT HẰNG NGÀY",
        body: `Các cụm sinh hoạt cơ bản: ${purple("have breakfast/lunch/dinner")}, ${purple("have a shower")}, ${purple("have a rest")}.`,
        examples: [
          ex("I have breakfast at seven.", "Tôi ăn sáng lúc bảy giờ."),
          ex("She had a shower before work.", "Cô ấy đã tắm trước khi đi làm."),
          ex("Let's have a short rest.", "Hãy nghỉ ngơi một chút."),
        ],
      },
      {
        title: "SỰ KIỆN THƯỜNG GẶP",
        body: `${purple("have a meeting")}, ${purple("have a lesson")}, ${purple("have a party")}, ${purple("have a conversation")}.`,
        examples: [
          ex("We had a team meeting this morning.", "Sáng nay chúng tôi đã có một cuộc họp nhóm."),
          ex("They had a birthday party last night.", "Tối qua họ đã tổ chức tiệc sinh nhật."),
          ex("Can we have a quick conversation?", "Chúng ta có thể trao đổi nhanh không?"),
        ],
      },
      {
        title: "VẤN ĐỀ VÀ CẢM GIÁC",
        body: `Mẫu rất phổ biến: ${purple("have a headache")}, ${purple("have a cold")}, ${purple("have trouble")} + V-ing.`,
        examples: [
          ex("I have a headache today.", "Hôm nay tôi bị đau đầu."),
          ex("He had a cold last week.", "Tuần trước anh ấy bị cảm."),
          ex("She is having trouble sleeping.", "Cô ấy đang gặp khó khăn khi ngủ."),
        ],
      },
    ],
    words: [
      { term: "have breakfast", definition: "ăn sáng", partOfSpeech: "VERB", example: "I usually have breakfast at home." },
      { term: "have lunch", definition: "ăn trưa", partOfSpeech: "VERB", example: "We have lunch at noon." },
      { term: "have dinner", definition: "ăn tối", partOfSpeech: "VERB", example: "They had dinner together." },
      { term: "have a shower", definition: "tắm vòi sen", partOfSpeech: "VERB", example: "I had a shower after the gym." },
      { term: "have a bath", definition: "tắm bồn", partOfSpeech: "VERB", example: "She likes to have a bath at night." },
      { term: "have a rest", definition: "nghỉ ngơi", partOfSpeech: "VERB", example: "Sit down and have a rest." },
      { term: "have a break", definition: "nghỉ giải lao", partOfSpeech: "VERB", example: "Let's have a short break." },
      { term: "have a nap", definition: "chợp mắt", partOfSpeech: "VERB", example: "He had a nap after lunch." },
      { term: "have a meeting", definition: "họp", partOfSpeech: "VERB", example: "We have a meeting every Monday." },
      { term: "have a lesson", definition: "học một buổi", partOfSpeech: "VERB", example: "I have an English lesson tonight." },
      { term: "have a class", definition: "có lớp học", partOfSpeech: "VERB", example: "They had a class in the lab." },
      { term: "have a party", definition: "mở tiệc", partOfSpeech: "VERB", example: "We had a small party at home." },
      { term: "have a conversation", definition: "trò chuyện", partOfSpeech: "VERB", example: "Can we have a conversation now?" },
      { term: "have a look", definition: "xem qua", partOfSpeech: "VERB", example: "Have a look at this email." },
      { term: "have a try", definition: "thử", partOfSpeech: "VERB", example: "Have a try and tell me." },
      { term: "have fun", definition: "vui vẻ", partOfSpeech: "VERB", example: "The kids had fun in the park." },
      { term: "have a good time", definition: "có khoảng thời gian vui", partOfSpeech: "VERB", example: "We had a good time at the beach." },
      { term: "have a headache", definition: "bị đau đầu", partOfSpeech: "VERB", example: "I have a headache this morning." },
      { term: "have a cold", definition: "bị cảm", partOfSpeech: "VERB", example: "She has a cold, so she stayed home." },
      { term: "have a fever", definition: "bị sốt", partOfSpeech: "VERB", example: "He had a fever last night." },
      { term: "have trouble", definition: "gặp khó khăn", partOfSpeech: "VERB", example: "I have trouble remembering names." },
      { term: "have a problem", definition: "gặp vấn đề", partOfSpeech: "VERB", example: "We have a problem with this file." },
      { term: "have an idea", definition: "có ý tưởng", partOfSpeech: "VERB", example: "I have an idea for the project." },
      { term: "have time", definition: "có thời gian", partOfSpeech: "VERB", example: "Do you have time this afternoon?" },
      { term: "have to", definition: "phải (bắt buộc)", partOfSpeech: "VERB", example: "I have to finish this task today." },
    ],
    exercises: [
      mcq(
        38,
        1,
        "Choose the correct collocation:",
        [
          { key: "a", label: "have a shower" },
          { key: "b", label: "make a shower" },
          { key: "c", label: "do a shower" },
          { key: "d", label: "go a shower" },
        ],
        "a",
      ),
      fillBlank(
        38,
        2,
        "Let's ___ a break after this exercise.",
        "have",
        [
          { key: "a", label: "have" },
          { key: "b", label: "go" },
          { key: "c", label: "take" },
          { key: "d", label: "make" },
        ],
        "a",
      ),
      mcq(
        38,
        3,
        "I can't come. I ___ a meeting at 3 p.m.",
        [
          { key: "a", label: "have" },
          { key: "b", label: "do" },
          { key: "c", label: "make" },
          { key: "d", label: "bring" },
        ],
        "a",
      ),
      fillBlank(
        38,
        4,
        "She is tired because she had ___ fever last night.",
        "a",
        [
          { key: "a", label: "a" },
          { key: "b", label: "an" },
          { key: "c", label: "the" },
          { key: "d", label: "no article" },
        ],
        "a",
      ),
    ],
  }),
  buildEviuUnit(getCatalog(39), {
    introVi: "Động từ go trong các cụm chỉ di chuyển, hoạt động và thay đổi trạng thái thường gặp.",
    structureSections: [
      { label: "Movement and transport", wordCount: 9 },
      { label: "Go + activity", wordCount: 7 },
      { label: "Go + adjective", wordCount: 5 },
      { label: "Phrasal chunks", wordCount: 4 },
    ],
    collocationHtml: `Các cụm thường gặp: ${purple("go to work")}, ${purple("go home")}, ${purple("go shopping")}, ${purple("go out")}, ${purple("go wrong")}.`,
    mistakeHtml: `${bold("go to home")} ${bold("[SAI]")} → dùng ${purple("go home")}.`,
    principles: [
      {
        title: "DI CHUYỂN HẰNG NGÀY",
        body: `Cụm nền: ${purple("go to work/school/bed")}, ${purple("go home")}, ${purple("go abroad")}.`,
        examples: [
          ex("I go to work by bus.", "Tôi đi làm bằng xe buýt."),
          ex("She went home early.", "Cô ấy đã về nhà sớm."),
          ex("They want to go abroad next year.", "Họ muốn ra nước ngoài vào năm tới."),
        ],
      },
      {
        title: "HOẠT ĐỘNG GIẢI TRÍ",
        body: `Nói ${purple("go shopping/swimming/running/camping")} cho hoạt động giải trí.`,
        examples: [
          ex("We went shopping after lunch.", "Chúng tôi đi mua sắm sau bữa trưa."),
          ex("He goes swimming every Sunday.", "Anh ấy đi bơi mỗi Chủ nhật."),
          ex("Let's go camping this weekend.", "Cuối tuần này hãy đi cắm trại."),
        ],
      },
      {
        title: "THAY ĐỔI TRẠNG THÁI",
        body: `Dùng ${purple("go bad")}, ${purple("go quiet")}, ${purple("go crazy")}, ${purple("go wrong")} để tả trạng thái thay đổi.`,
        examples: [
          ex("The milk went bad.", "Sữa đã bị hỏng."),
          ex("The room went quiet.", "Căn phòng trở nên yên lặng."),
          ex("Everything went wrong today.", "Mọi thứ hôm nay đều trục trặc."),
        ],
      },
    ],
    words: [
      { term: "go to work", definition: "đi làm", partOfSpeech: "VERB", example: "I go to work at 8 a.m." },
      { term: "go to school", definition: "đi học", partOfSpeech: "VERB", example: "Children go to school by bike." },
      { term: "go to bed", definition: "đi ngủ", partOfSpeech: "VERB", example: "I usually go to bed at 11." },
      { term: "go home", definition: "về nhà", partOfSpeech: "VERB", example: "Let's go home now." },
      { term: "go abroad", definition: "ra nước ngoài", partOfSpeech: "VERB", example: "She wants to go abroad to study." },
      { term: "go upstairs", definition: "đi lên lầu", partOfSpeech: "VERB", example: "He went upstairs to get his phone." },
      { term: "go downstairs", definition: "đi xuống lầu", partOfSpeech: "VERB", example: "Please go downstairs and wait." },
      { term: "go by bus", definition: "đi bằng xe buýt", partOfSpeech: "VERB", example: "We go by bus every day." },
      { term: "go on foot", definition: "đi bộ", partOfSpeech: "VERB", example: "The shop is close, so let's go on foot." },
      { term: "go shopping", definition: "đi mua sắm", partOfSpeech: "VERB", example: "They go shopping on Saturdays." },
      { term: "go swimming", definition: "đi bơi", partOfSpeech: "VERB", example: "I go swimming after work." },
      { term: "go running", definition: "đi chạy bộ", partOfSpeech: "VERB", example: "He goes running every morning." },
      { term: "go camping", definition: "đi cắm trại", partOfSpeech: "VERB", example: "We went camping near the lake." },
      { term: "go fishing", definition: "đi câu cá", partOfSpeech: "VERB", example: "My dad goes fishing at weekends." },
      { term: "go sightseeing", definition: "đi tham quan", partOfSpeech: "VERB", example: "Tourists go sightseeing in the old town." },
      { term: "go dancing", definition: "đi nhảy", partOfSpeech: "VERB", example: "They went dancing last night." },
      { term: "go crazy", definition: "phát điên", partOfSpeech: "VERB", example: "I go crazy in hot weather." },
      { term: "go quiet", definition: "trở nên yên lặng", partOfSpeech: "VERB", example: "The class went quiet suddenly." },
      { term: "go bad", definition: "bị hỏng; ôi", partOfSpeech: "VERB", example: "Milk can go bad in hot weather." },
      { term: "go wrong", definition: "trục trặc", partOfSpeech: "VERB", example: "Something went wrong with my laptop." },
      { term: "go missing", definition: "mất tích", partOfSpeech: "VERB", example: "My keys have gone missing again." },
      { term: "go out", definition: "ra ngoài", partOfSpeech: "VERB", example: "We don't go out on weekdays." },
      { term: "go back", definition: "quay lại", partOfSpeech: "VERB", example: "I need to go back to the office." },
      { term: "go ahead", definition: "tiến hành", partOfSpeech: "VERB", example: "Go ahead and ask your question." },
      { term: "go through", definition: "trải qua", partOfSpeech: "VERB", example: "She went through a hard time." },
    ],
    exercises: [
      mcq(
        39,
        1,
        "Which phrase is correct?",
        [
          { key: "a", label: "go home" },
          { key: "b", label: "go to home" },
          { key: "c", label: "go at home" },
          { key: "d", label: "go in home" },
        ],
        "a",
      ),
      fillBlank(
        39,
        2,
        "We usually ___ shopping on Sunday afternoon.",
        "go",
        [
          { key: "a", label: "go" },
          { key: "b", label: "have" },
          { key: "c", label: "bring" },
          { key: "d", label: "get" },
        ],
        "a",
      ),
      mcq(
        39,
        3,
        "My milk smells bad. I think it has ___ bad.",
        [
          { key: "a", label: "gone" },
          { key: "b", label: "done" },
          { key: "c", label: "brought" },
          { key: "d", label: "taken" },
        ],
        "a",
      ),
      fillBlank(
        39,
        4,
        "Don't worry. You can ___ ahead with your plan.",
        "go",
        [
          { key: "a", label: "go" },
          { key: "b", label: "do" },
          { key: "c", label: "have" },
          { key: "d", label: "make" },
        ],
        "a",
      ),
    ],
  }),
  buildEviuUnit(getCatalog(40), {
    introVi: "Động từ do trong công việc, việc nhà, học tập và các cấu trúc giao tiếp cơ bản.",
    structureSections: [
      { label: "Daily tasks", wordCount: 8 },
      { label: "Work and study", wordCount: 8 },
      { label: "Health and social use", wordCount: 5 },
      { label: "Fixed chunks", wordCount: 4 },
    ],
    collocationHtml: `Các cụm thường gặp: ${purple("do homework")}, ${purple("do housework")}, ${purple("do your best")}, ${purple("do business")}, ${purple("do someone a favor")}.`,
    mistakeHtml: `${bold("do a mistake")} ${bold("[SAI]")} → dùng ${purple("make a mistake")}.`,
    principles: [
      {
        title: "CÔNG VIỆC VÀ NHIỆM VỤ",
        body: `${purple("do homework")}, ${purple("do housework")}, ${purple("do the washing-up")}, ${purple("do a task")}.`,
        examples: [
          ex("I need to do my homework tonight.", "Tối nay tôi cần làm bài tập."),
          ex("He does the washing-up after dinner.", "Anh ấy rửa chén sau bữa tối."),
          ex("Can you do this task now?", "Bạn có thể làm nhiệm vụ này ngay bây giờ không?"),
        ],
      },
      {
        title: "NGỮ CẢNH CÔNG VIỆC",
        body: `Dùng ${purple("do business")}, ${purple("do a job")}, ${purple("do a presentation")}.`,
        examples: [
          ex("Our company does business abroad.", "Công ty chúng tôi kinh doanh ở nước ngoài."),
          ex("She did a great presentation.", "Cô ấy đã có một bài thuyết trình rất tốt."),
          ex("He does a part-time job on weekends.", "Anh ấy làm công việc bán thời gian vào cuối tuần."),
        ],
      },
      {
        title: "CỤM TỪ CỐ ĐỊNH",
        body: `Cụm cần nhớ: ${purple("do your best")}, ${purple("do well/badly")}, ${purple("do me a favor")}.`,
        examples: [
          ex("Please do your best in the exam.", "Hãy cố hết sức trong kỳ thi."),
          ex("She did well in the interview.", "Cô ấy đã làm tốt trong buổi phỏng vấn."),
          ex("Can you do me a favor?", "Bạn có thể giúp tôi một việc không?"),
        ],
      },
    ],
    words: [
      { term: "do homework", definition: "làm bài tập", partOfSpeech: "VERB", example: "I do homework after dinner." },
      { term: "do housework", definition: "làm việc nhà", partOfSpeech: "VERB", example: "We do housework together on Sundays." },
      { term: "do the dishes", definition: "rửa chén", partOfSpeech: "VERB", example: "He does the dishes every night." },
      { term: "do the washing", definition: "giặt quần áo", partOfSpeech: "VERB", example: "I do the washing on Saturday." },
      { term: "do the shopping", definition: "đi mua đồ", partOfSpeech: "VERB", example: "My dad does the shopping." },
      { term: "do exercise", definition: "tập thể dục", partOfSpeech: "VERB", example: "You should do exercise daily." },
      { term: "do yoga", definition: "tập yoga", partOfSpeech: "VERB", example: "She does yoga every morning." },
      { term: "do nothing", definition: "không làm gì", partOfSpeech: "VERB", example: "I did nothing last Sunday." },
      { term: "do a task", definition: "làm nhiệm vụ", partOfSpeech: "VERB", example: "Please do this task first." },
      { term: "do a job", definition: "làm công việc", partOfSpeech: "VERB", example: "He does a difficult job." },
      { term: "do business", definition: "làm ăn", partOfSpeech: "VERB", example: "They do business with Japan." },
      { term: "do research", definition: "nghiên cứu", partOfSpeech: "VERB", example: "Students do research in the lab." },
      { term: "do an exam", definition: "làm bài thi", partOfSpeech: "VERB", example: "We did an exam this morning." },
      { term: "do a course", definition: "học một khóa", partOfSpeech: "VERB", example: "She is doing an online course." },
      { term: "do a presentation", definition: "thuyết trình", partOfSpeech: "VERB", example: "I have to do a presentation tomorrow." },
      { term: "do your best", definition: "cố hết sức", partOfSpeech: "VERB", example: "Just do your best." },
      { term: "do well", definition: "làm tốt", partOfSpeech: "VERB", example: "He did well in the test." },
      { term: "do badly", definition: "làm tệ", partOfSpeech: "VERB", example: "I did badly in maths last term." },
      { term: "do someone a favor", definition: "giúp ai một việc", partOfSpeech: "VERB", example: "Could you do me a favor?" },
      { term: "do harm", definition: "gây hại", partOfSpeech: "VERB", example: "Smoking does harm to your health." },
      { term: "do good", definition: "làm điều tốt", partOfSpeech: "VERB", example: "Volunteers do good in the community." },
      { term: "do up", definition: "trang trí, sửa sang", partOfSpeech: "VERB", example: "They did up the kitchen." },
      { term: "do without", definition: "xoay xở không có", partOfSpeech: "VERB", example: "I can do without sugar in coffee." },
      { term: "do over", definition: "làm lại", partOfSpeech: "VERB", example: "You need to do the exercise over." },
      { term: "do away with", definition: "loại bỏ", partOfSpeech: "VERB", example: "The school did away with uniforms." },
    ],
    exercises: [
      mcq(
        40,
        1,
        "Which is correct?",
        [
          { key: "a", label: "do homework" },
          { key: "b", label: "make homework" },
          { key: "c", label: "have homeworking" },
          { key: "d", label: "get homeworks" },
        ],
        "a",
      ),
      fillBlank(
        40,
        2,
        "Could you ___ me a favor and open the door?",
        "do",
        [
          { key: "a", label: "do" },
          { key: "b", label: "go" },
          { key: "c", label: "bring" },
          { key: "d", label: "make" },
        ],
        "a",
      ),
      mcq(
        40,
        3,
        "In business English, which phrase is natural?",
        [
          { key: "a", label: "do business with clients" },
          { key: "b", label: "take business with clients" },
          { key: "c", label: "have businessing clients" },
          { key: "d", label: "bring business to table always" },
        ],
        "a",
      ),
      fillBlank(
        40,
        4,
        "She studied hard and did ___ in the exam.",
        "well",
        [
          { key: "a", label: "well" },
          { key: "b", label: "goodly" },
          { key: "c", label: "crime" },
          { key: "d", label: "ticket" },
        ],
        "a",
      ),
    ],
  }),
  buildEviuUnit(getCatalog(41), {
    introVi: "Động từ make trong các collocation tạo ra kết quả, quyết định, giao tiếp và thay đổi.",
    structureSections: [
      { label: "Create and produce", wordCount: 8 },
      { label: "Decisions and plans", wordCount: 7 },
      { label: "Communication and social use", wordCount: 6 },
      { label: "Result expressions", wordCount: 4 },
    ],
    collocationHtml: `Các cụm thường gặp: ${purple("make a decision")}, ${purple("make a plan")}, ${purple("make a mistake")}, ${purple("make noise")}, ${purple("make progress")}.`,
    mistakeHtml: `${bold("do a mistake")} ${bold("[SAI]")} → dùng ${purple("make a mistake")}.`,
    principles: [
      {
        title: "TẠO RA KẾT QUẢ",
        body: `${purple("make food")}, ${purple("make coffee")}, ${purple("make a list")}, ${purple("make a model")} nhấn mạnh tạo ra thứ gì đó.`,
        examples: [
          ex("I'll make coffee for you.", "Tôi sẽ pha cà phê cho bạn."),
          ex("She made a list of tasks.", "Cô ấy đã lập một danh sách công việc."),
          ex("They made dinner together.", "Họ cùng nhau nấu bữa tối."),
        ],
      },
      {
        title: "DANH TỪ TRỪU TƯỢNG",
        body: `Rất thường gặp với danh từ trừu tượng: ${purple("make a decision")}, ${purple("make progress")}, ${purple("make an effort")}.`,
        examples: [
          ex("We made an important decision.", "Chúng tôi đã đưa ra một quyết định quan trọng."),
          ex("He is making good progress.", "Anh ấy đang tiến bộ tốt."),
          ex("You should make more effort.", "Bạn nên nỗ lực hơn."),
        ],
      },
      {
        title: "CỤM GIAO TIẾP",
        body: `Cụm giao tiếp phổ biến: ${purple("make friends")}, ${purple("make a phone call")}, ${purple("make an appointment")}.`,
        examples: [
          ex("She made friends quickly.", "Cô ấy kết bạn rất nhanh."),
          ex("I need to make a phone call.", "Tôi cần thực hiện một cuộc gọi điện thoại."),
          ex("Let's make an appointment with the doctor.", "Hãy đặt lịch hẹn với bác sĩ."),
        ],
      },
    ],
    words: [
      { term: "make breakfast", definition: "làm bữa sáng", partOfSpeech: "VERB", example: "I make breakfast every day." },
      { term: "make coffee", definition: "pha cà phê", partOfSpeech: "VERB", example: "Can you make coffee for us?" },
      { term: "make dinner", definition: "nấu bữa tối", partOfSpeech: "VERB", example: "My mother made dinner late." },
      { term: "make a cake", definition: "làm bánh", partOfSpeech: "VERB", example: "We made a cake for her birthday." },
      { term: "make a list", definition: "lập danh sách", partOfSpeech: "VERB", example: "Make a list before shopping." },
      { term: "make a model", definition: "làm mô hình", partOfSpeech: "VERB", example: "The students made a model plane." },
      { term: "make a video", definition: "làm video", partOfSpeech: "VERB", example: "They made a short video for class." },
      { term: "make money", definition: "kiếm tiền", partOfSpeech: "VERB", example: "She makes money from teaching online." },
      { term: "make a decision", definition: "đưa ra quyết định", partOfSpeech: "VERB", example: "We need to make a decision today." },
      { term: "make a plan", definition: "lập kế hoạch", partOfSpeech: "VERB", example: "Let's make a plan for the trip." },
      { term: "make a choice", definition: "đưa ra lựa chọn", partOfSpeech: "VERB", example: "You must make a choice now." },
      { term: "make an effort", definition: "nỗ lực", partOfSpeech: "VERB", example: "He made a big effort to improve." },
      { term: "make progress", definition: "tiến bộ", partOfSpeech: "VERB", example: "She is making progress in English." },
      { term: "make a promise", definition: "hứa", partOfSpeech: "VERB", example: "I made a promise to my parents." },
      { term: "make a mistake", definition: "mắc lỗi", partOfSpeech: "VERB", example: "Everyone makes mistakes sometimes." },
      { term: "make friends", definition: "kết bạn", partOfSpeech: "VERB", example: "He made friends quickly at school." },
      { term: "make a phone call", definition: "gọi điện", partOfSpeech: "VERB", example: "I need to make a phone call." },
      { term: "make an appointment", definition: "đặt lịch hẹn", partOfSpeech: "VERB", example: "She made an appointment with the dentist." },
      { term: "make a complaint", definition: "khiếu nại", partOfSpeech: "VERB", example: "The customer made a complaint." },
      { term: "make a suggestion", definition: "đưa ra đề xuất", partOfSpeech: "VERB", example: "Can I make a suggestion?" },
      { term: "make noise", definition: "gây ồn", partOfSpeech: "VERB", example: "The children are making too much noise." },
      { term: "make someone happy", definition: "làm ai vui", partOfSpeech: "VERB", example: "Your message made me happy." },
      { term: "make sense", definition: "có lý", partOfSpeech: "VERB", example: "This explanation makes sense." },
      { term: "make sure", definition: "đảm bảo", partOfSpeech: "VERB", example: "Please make sure the door is locked." },
      { term: "make up your mind", definition: "quyết định dứt khoát", partOfSpeech: "VERB", example: "Make up your mind before Friday." },
    ],
    exercises: [
      mcq(
        41,
        1,
        "Which collocation is correct?",
        [
          { key: "a", label: "make a decision" },
          { key: "b", label: "do a decision" },
          { key: "c", label: "have a deciding" },
          { key: "d", label: "bring a decision" },
        ],
        "a",
      ),
      fillBlank(
        41,
        2,
        "I need to ___ sure I saved the file.",
        "make",
        [
          { key: "a", label: "make" },
          { key: "b", label: "go" },
          { key: "c", label: "take" },
          { key: "d", label: "get" },
        ],
        "a",
      ),
      mcq(
        41,
        3,
        "He said sorry because he ___ a mistake.",
        [
          { key: "a", label: "made" },
          { key: "b", label: "did" },
          { key: "c", label: "went" },
          { key: "d", label: "brought" },
        ],
        "a",
      ),
      fillBlank(
        41,
        4,
        "Can we ___ a plan for next week?",
        "make",
        [
          { key: "a", label: "make" },
          { key: "b", label: "do" },
          { key: "c", label: "come" },
          { key: "d", label: "have" },
        ],
        "a",
      ),
    ],
  }),
  buildEviuUnit(getCatalog(42), {
    introVi: "Động từ come trong collocation về di chuyển, trạng thái, thời điểm và hội thoại thường ngày.",
    structureSections: [
      { label: "Movement with come", wordCount: 8 },
      { label: "Time and events", wordCount: 6 },
      { label: "Come + adjective / phrase", wordCount: 6 },
      { label: "Useful phrasal uses", wordCount: 5 },
    ],
    collocationHtml: `Các cụm thường gặp: ${purple("come home")}, ${purple("come back")}, ${purple("come in")}, ${purple("come on time")}, ${purple("come true")}.`,
    mistakeHtml: `${bold("go here")} ${bold("[SAI]")} → dùng ${purple("come here")} khi nói về hướng về phía người nói.`,
    principles: [
      {
        title: "Ý NGHĨA HƯỚNG DI CHUYỂN",
        body: `${purple("come")} thường hướng về người nói hoặc điểm tham chiếu; ${purple("go")} hướng rời khỏi điểm đó.`,
        examples: [
          ex("Come here, please.", "Làm ơn đến đây."),
          ex("I'm coming to your office.", "Tôi đang đến văn phòng của bạn."),
          ex("I'll go there tomorrow.", "Ngày mai tôi sẽ đến đó."),
        ],
      },
      {
        title: "CỤM CHỈ THỜI GIAN",
        body: `Các cụm thời gian phổ biến: ${purple("come early")}, ${purple("come late")}, ${purple("come on time")}, ${purple("come first")}.`,
        examples: [
          ex("Please come on time.", "Vui lòng đến đúng giờ."),
          ex("She came early for the interview.", "Cô ấy đến sớm cho buổi phỏng vấn."),
          ex("He came first in the race.", "Anh ấy về nhất trong cuộc đua."),
        ],
      },
      {
        title: "CỤM ĐỘNG TỪ PHỔ BIẾN",
        body: `Học theo cụm: ${purple("come back")}, ${purple("come in")}, ${purple("come out")}, ${purple("come up with")} (ý tưởng).`,
        examples: [
          ex("When will you come back?", "Khi nào bạn quay lại?"),
          ex("Come in and sit down.", "Mời vào và ngồi xuống."),
          ex("She came up with a good idea.", "Cô ấy đã nghĩ ra một ý tưởng hay."),
        ],
      },
    ],
    words: [
      { term: "come home", definition: "về nhà", partOfSpeech: "VERB", example: "I came home late yesterday." },
      { term: "come here", definition: "đến đây", partOfSpeech: "VERB", example: "Come here and look at this." },
      { term: "come to work", definition: "đến chỗ làm", partOfSpeech: "VERB", example: "She came to work early." },
      { term: "come to school", definition: "đến trường", partOfSpeech: "VERB", example: "He didn't come to school today." },
      { term: "come by bus", definition: "đến bằng xe buýt", partOfSpeech: "VERB", example: "They came by bus." },
      { term: "come on foot", definition: "đến bằng đi bộ", partOfSpeech: "VERB", example: "We came on foot from the station." },
      { term: "come from", definition: "đến từ", partOfSpeech: "VERB", example: "She comes from a small town." },
      { term: "come with", definition: "đi cùng", partOfSpeech: "VERB", example: "Do you want to come with us?" },
      { term: "come early", definition: "đến sớm", partOfSpeech: "VERB", example: "Please come early tomorrow." },
      { term: "come late", definition: "đến muộn", partOfSpeech: "VERB", example: "He came late again." },
      { term: "come on time", definition: "đến đúng giờ", partOfSpeech: "VERB", example: "Try to come on time." },
      { term: "come first", definition: "về nhất", partOfSpeech: "VERB", example: "She came first in the exam." },
      { term: "come second", definition: "về nhì", partOfSpeech: "VERB", example: "Our team came second." },
      { term: "come true", definition: "thành hiện thực", partOfSpeech: "VERB", example: "His dream came true." },
      { term: "come alive", definition: "trở nên sống động", partOfSpeech: "VERB", example: "The city comes alive at night." },
      { term: "come easy", definition: "đến dễ dàng", partOfSpeech: "VERB", example: "Success doesn't come easy." },
      { term: "come back", definition: "quay lại", partOfSpeech: "VERB", example: "I'll come back in ten minutes." },
      { term: "come in", definition: "đi vào", partOfSpeech: "VERB", example: "Come in, please." },
      { term: "come out", definition: "đi ra; được phát hành", partOfSpeech: "VERB", example: "Her new song came out last week." },
      { term: "come up", definition: "xuất hiện", partOfSpeech: "VERB", example: "A new problem came up." },
      { term: "come up with", definition: "nghĩ ra", partOfSpeech: "VERB", example: "We came up with a better plan." },
      { term: "come across", definition: "tình cờ gặp", partOfSpeech: "VERB", example: "I came across an old photo." },
      { term: "come over", definition: "ghé qua", partOfSpeech: "VERB", example: "Can you come over tonight?" },
      { term: "come along", definition: "đi cùng; tiến triển", partOfSpeech: "VERB", example: "Come along with us." },
      { term: "come off", definition: "bị rơi ra", partOfSpeech: "VERB", example: "One button came off my shirt." },
    ],
    exercises: [
      mcq(
        42,
        1,
        "If you are inviting someone to your place, which verb is natural?",
        [
          { key: "a", label: "come" },
          { key: "b", label: "go" },
          { key: "c", label: "make" },
          { key: "d", label: "do" },
        ],
        "a",
      ),
      fillBlank(
        42,
        2,
        "Please ___ in and sit down.",
        "come",
        [
          { key: "a", label: "come" },
          { key: "b", label: "take" },
          { key: "c", label: "bring" },
          { key: "d", label: "get" },
        ],
        "a",
      ),
      mcq(
        42,
        3,
        "My dream finally ___ true last year.",
        [
          { key: "a", label: "came" },
          { key: "b", label: "did" },
          { key: "c", label: "had" },
          { key: "d", label: "took" },
        ],
        "a",
      ),
      fillBlank(
        42,
        4,
        "He couldn't ___ up with a good answer.",
        "come",
        [
          { key: "a", label: "come" },
          { key: "b", label: "go" },
          { key: "c", label: "have" },
          { key: "d", label: "make" },
        ],
        "a",
      ),
    ],
  }),
  buildEviuUnit(getCatalog(43), {
    introVi: "Động từ take trong collocation về mang theo, thời gian, học tập, chăm sóc và quyết định.",
    structureSections: [
      { label: "Carry and movement", wordCount: 8 },
      { label: "Time and process", wordCount: 7 },
      { label: "Health and learning", wordCount: 6 },
      { label: "Fixed expressions", wordCount: 4 },
    ],
    collocationHtml: `Các cụm thường gặp: ${purple("take a photo")}, ${purple("take a bus")}, ${purple("take time")}, ${purple("take medicine")}, ${purple("take care of")}.`,
    mistakeHtml: `${bold("bring a bus")} ${bold("[SAI]")} → dùng ${purple("take a bus")}.`,
    principles: [
      {
        title: "PHƯƠNG TIỆN VÀ DI CHUYỂN",
        body: `${purple("take a bus/train/taxi")} nói về chọn phương tiện để đi.`,
        examples: [
          ex("I take a bus to work.", "Tôi đi làm bằng xe buýt."),
          ex("Let's take a taxi.", "Chúng ta hãy đi taxi."),
          ex("She took the train yesterday.", "Hôm qua cô ấy đã đi tàu."),
        ],
      },
      {
        title: "THỜI GIAN VÀ HÀNH ĐỘNG",
        body: `Cụm rất thông dụng: ${purple("take time")}, ${purple("take a break")}, ${purple("take a look")}, ${purple("take notes")}.`,
        examples: [
          ex("Learning a language takes time.", "Học một ngôn ngữ cần thời gian."),
          ex("Take a break if you are tired.", "Hãy nghỉ giải lao nếu bạn mệt."),
          ex("Please take notes in class.", "Hãy ghi chú trong lớp."),
        ],
      },
      {
        title: "TRÁCH NHIỆM VÀ THAM GIA",
        body: `Dùng ${purple("take care of")}, ${purple("take responsibility for")}, ${purple("take part in")}.`,
        examples: [
          ex("She takes care of her grandmother.", "Cô ấy chăm sóc bà của mình."),
          ex("He took responsibility for the mistake.", "Anh ấy đã chịu trách nhiệm cho lỗi đó."),
          ex("Many students took part in the contest.", "Nhiều học sinh đã tham gia cuộc thi."),
        ],
      },
    ],
    words: [
      { term: "take a bag", definition: "cầm/mang một túi", partOfSpeech: "VERB", example: "Take a bag with you." },
      { term: "take an umbrella", definition: "mang ô", partOfSpeech: "VERB", example: "Take an umbrella. It may rain." },
      { term: "take your phone", definition: "mang điện thoại", partOfSpeech: "VERB", example: "Don't forget to take your phone." },
      { term: "take someone home", definition: "đưa ai về nhà", partOfSpeech: "VERB", example: "I can take you home." },
      { term: "take a bus", definition: "đi xe buýt", partOfSpeech: "VERB", example: "We take a bus to the city center." },
      { term: "take a train", definition: "đi tàu", partOfSpeech: "VERB", example: "They took a train to Hue." },
      { term: "take a taxi", definition: "đi taxi", partOfSpeech: "VERB", example: "Let's take a taxi to save time." },
      { term: "take a flight", definition: "đi máy bay", partOfSpeech: "VERB", example: "She took a flight at dawn." },
      { term: "take time", definition: "tốn thời gian", partOfSpeech: "VERB", example: "Good writing takes time." },
      { term: "take a minute", definition: "mất một phút", partOfSpeech: "VERB", example: "This will only take a minute." },
      { term: "take a break", definition: "nghỉ giải lao", partOfSpeech: "VERB", example: "Let's take a break now." },
      { term: "take turns", definition: "lần lượt", partOfSpeech: "VERB", example: "We take turns cleaning the room." },
      { term: "take notes", definition: "ghi chú", partOfSpeech: "VERB", example: "Students should take notes in lectures." },
      { term: "take a look", definition: "xem qua", partOfSpeech: "VERB", example: "Can you take a look at this?" },
      { term: "take medicine", definition: "uống thuốc", partOfSpeech: "VERB", example: "You should take medicine after meals." },
      { term: "take care of", definition: "chăm sóc", partOfSpeech: "VERB", example: "He takes care of his little brother." },
      { term: "take a rest", definition: "nghỉ ngơi", partOfSpeech: "VERB", example: "Take a rest if you feel tired." },
      { term: "take an exam", definition: "thi", partOfSpeech: "VERB", example: "I will take an exam next week." },
      { term: "take a course", definition: "học một khóa", partOfSpeech: "VERB", example: "She is taking a cooking course." },
      { term: "take part in", definition: "tham gia", partOfSpeech: "VERB", example: "He took part in the game." },
      { term: "take responsibility", definition: "chịu trách nhiệm", partOfSpeech: "VERB", example: "Please take responsibility for this task." },
      { term: "take action", definition: "hành động", partOfSpeech: "VERB", example: "We need to take action now." },
      { term: "take it easy", definition: "thư giãn; bình tĩnh", partOfSpeech: "VERB", example: "Take it easy. Everything is fine." },
      { term: "take off", definition: "cởi ra; cất cánh", partOfSpeech: "VERB", example: "The plane took off on time." },
      { term: "take over", definition: "tiếp quản", partOfSpeech: "VERB", example: "A new manager will take over soon." },
    ],
    exercises: [
      mcq(
        43,
        1,
        "Which collocation is correct?",
        [
          { key: "a", label: "take notes" },
          { key: "b", label: "do notes" },
          { key: "c", label: "make noteses" },
          { key: "d", label: "go notes" },
        ],
        "a",
      ),
      fillBlank(
        43,
        2,
        "Learning to drive can ___ time.",
        "take",
        [
          { key: "a", label: "take" },
          { key: "b", label: "bring" },
          { key: "c", label: "come" },
          { key: "d", label: "do" },
        ],
        "a",
      ),
      mcq(
        43,
        3,
        "If you feel sick, you should ___ medicine.",
        [
          { key: "a", label: "take" },
          { key: "b", label: "go" },
          { key: "c", label: "make" },
          { key: "d", label: "get with" },
        ],
        "a",
      ),
      fillBlank(
        43,
        4,
        "Can you ___ a look at my report?",
        "take",
        [
          { key: "a", label: "take" },
          { key: "b", label: "have" },
          { key: "c", label: "come" },
          { key: "d", label: "bring" },
        ],
        "a",
      ),
    ],
  }),
  buildEviuUnit(getCatalog(44), {
    introVi: "Động từ bring trong collocation về mang đến, gây ra kết quả, gợi nhớ và đưa người/vật đi cùng.",
    structureSections: [
      { label: "Bring objects and people", wordCount: 9 },
      { label: "Bring results and changes", wordCount: 7 },
      { label: "Bring in conversation", wordCount: 6 },
      { label: "Useful phrasal forms", wordCount: 4 },
    ],
    collocationHtml: `Các cụm thường gặp: ${purple("bring your ID")}, ${purple("bring a friend")}, ${purple("bring good news")}, ${purple("bring back memories")}, ${purple("bring up a topic")}.`,
    mistakeHtml: `${bold("take me some water")} ${bold("[SAI]")} → dùng ${purple("bring me some water")}.`,
    principles: [
      {
        title: "HƯỚNG DI CHUYỂN MANG ĐẾN",
        body: `${purple("bring")} nhấn mạnh chuyển động về phía người nói hoặc điểm đích đã xác định.`,
        examples: [
          ex("Please bring your notebook tomorrow.", "Làm ơn mang theo vở của bạn vào ngày mai."),
          ex("Can you bring me some water?", "Bạn có thể mang cho tôi một ít nước không?"),
          ex("She brought her son to work.", "Cô ấy đã đưa con trai đến chỗ làm."),
        ],
      },
      {
        title: "MANG LẠI KẾT QUẢ",
        body: `Các cụm thường gặp: ${purple("bring good/bad news")}, ${purple("bring change")}, ${purple("bring benefits")}.`,
        examples: [
          ex("The project brought many benefits.", "Dự án mang lại nhiều lợi ích."),
          ex("He brought bad news this morning.", "Sáng nay anh ấy mang đến tin xấu."),
          ex("Technology can bring big changes.", "Công nghệ có thể mang lại những thay đổi lớn."),
        ],
      },
      {
        title: "CỤM ĐỘNG TỪ PHỔ BIẾN",
        body: `${purple("bring up")} (nêu ra/chăm nuôi), ${purple("bring back")} (mang về/gợi lại), ${purple("bring out")} (làm nổi bật).`,
        examples: [
          ex("She brought up an important question.", "Cô ấy đã nêu ra một câu hỏi quan trọng."),
          ex("This song brings back memories.", "Bài hát này gợi lại nhiều kỷ niệm."),
          ex("This color brings out your eyes.", "Màu này làm nổi bật đôi mắt của bạn."),
        ],
      },
    ],
    words: [
      { term: "bring your bag", definition: "mang túi của bạn", partOfSpeech: "VERB", example: "Bring your bag to class." },
      { term: "bring your ID", definition: "mang giấy tờ tùy thân", partOfSpeech: "VERB", example: "Please bring your ID to the office." },
      { term: "bring your phone", definition: "mang điện thoại", partOfSpeech: "VERB", example: "Bring your phone charger too." },
      { term: "bring a friend", definition: "dẫn theo bạn", partOfSpeech: "VERB", example: "You can bring a friend to the party." },
      { term: "bring the children", definition: "đưa bọn trẻ đến", partOfSpeech: "VERB", example: "She brought the children to the park." },
      { term: "bring food", definition: "mang đồ ăn", partOfSpeech: "VERB", example: "I'll bring food for everyone." },
      { term: "bring drinks", definition: "mang đồ uống", partOfSpeech: "VERB", example: "Can you bring drinks tonight?" },
      { term: "bring a gift", definition: "mang quà", partOfSpeech: "VERB", example: "He brought a gift for her birthday." },
      { term: "bring me", definition: "mang cho tôi", partOfSpeech: "VERB", example: "Please bring me the menu." },
      { term: "bring good news", definition: "mang tin tốt", partOfSpeech: "VERB", example: "She brought good news from home." },
      { term: "bring bad news", definition: "mang tin xấu", partOfSpeech: "VERB", example: "He brought bad news about the project." },
      { term: "bring change", definition: "mang lại thay đổi", partOfSpeech: "VERB", example: "The new law brought change." },
      { term: "bring benefits", definition: "mang lại lợi ích", partOfSpeech: "VERB", example: "Exercise brings many benefits." },
      { term: "bring trouble", definition: "gây rắc rối", partOfSpeech: "VERB", example: "Lying can bring trouble." },
      { term: "bring peace", definition: "mang lại hòa bình", partOfSpeech: "VERB", example: "Dialogue can bring peace." },
      { term: "bring luck", definition: "mang lại may mắn", partOfSpeech: "VERB", example: "Some people think this coin brings luck." },
      { term: "bring back memories", definition: "gợi lại kỷ niệm", partOfSpeech: "VERB", example: "This photo brings back memories." },
      { term: "bring up a topic", definition: "nêu ra chủ đề", partOfSpeech: "VERB", example: "He brought up a useful topic." },
      { term: "bring up children", definition: "nuôi dạy con cái", partOfSpeech: "VERB", example: "They brought up three children." },
      { term: "bring someone together", definition: "kết nối mọi người", partOfSpeech: "VERB", example: "Sports bring people together." },
      { term: "bring out", definition: "làm nổi bật; phát hành", partOfSpeech: "VERB", example: "This sauce brings out the flavor." },
      { term: "bring in", definition: "đưa vào; mang về (thu nhập)", partOfSpeech: "VERB", example: "The ad campaign brought in new customers." },
      { term: "bring on", definition: "gây ra", partOfSpeech: "VERB", example: "Too much stress can bring on headaches." },
      { term: "bring around", definition: "thuyết phục; đưa đi vòng quanh", partOfSpeech: "VERB", example: "She brought him around to her idea." },
      { term: "bring forward", definition: "đưa lên sớm hơn", partOfSpeech: "VERB", example: "They brought forward the meeting time." },
    ],
    exercises: [
      mcq(
        44,
        1,
        "You are coming to my house. Which verb is best?",
        [
          { key: "a", label: "bring your notebook" },
          { key: "b", label: "take your notebook to me away" },
          { key: "c", label: "go your notebook" },
          { key: "d", label: "do your notebook" },
        ],
        "a",
      ),
      fillBlank(
        44,
        2,
        "This old song ___ back memories of my school days.",
        "brings",
        [
          { key: "a", label: "brings" },
          { key: "b", label: "takes" },
          { key: "c", label: "does" },
          { key: "d", label: "gets" },
        ],
        "a",
      ),
      mcq(
        44,
        3,
        "Which collocation means 'mention a subject'?",
        [
          { key: "a", label: "bring up a topic" },
          { key: "b", label: "bring down a topic" },
          { key: "c", label: "bring over a topic always" },
          { key: "d", label: "bring topic for to" },
        ],
        "a",
      ),
      fillBlank(
        44,
        4,
        "Exercise can ___ many health benefits.",
        "bring",
        [
          { key: "a", label: "bring" },
          { key: "b", label: "come" },
          { key: "c", label: "have" },
          { key: "d", label: "do" },
        ],
        "a",
      ),
    ],
  }),
  buildEviuUnit(getCatalog(45), {
    introVi: "Động từ get đa nghĩa trong giao tiếp đời thường: nhận được, trở nên, di chuyển, hiểu và xử lý.",
    structureSections: [
      { label: "Get = receive/obtain", wordCount: 8 },
      { label: "Get = become", wordCount: 7 },
      { label: "Get around movement/time", wordCount: 6 },
      { label: "Phrasal and fixed chunks", wordCount: 4 },
    ],
    collocationHtml: `Các cụm thường gặp: ${purple("get a message")}, ${purple("get home")}, ${purple("get ready")}, ${purple("get better")}, ${purple("get in touch")}.`,
    mistakeHtml: `${bold("marry with")} ${bold("[SAI]")} → dùng ${purple("get married")}.`,
    principles: [
      {
        title: "NHẬN ĐƯỢC VÀ ĐẠT ĐƯỢC",
        body: `${purple("get an email")}, ${purple("get a job")}, ${purple("get help")}, ${purple("get information")}.`,
        examples: [
          ex("I got your email.", "Tôi đã nhận được email của bạn."),
          ex("She got a new job.", "Cô ấy đã có một công việc mới."),
          ex("We got help from our teacher.", "Chúng tôi nhận được sự giúp đỡ từ giáo viên."),
        ],
      },
      {
        title: "THAY ĐỔI TRẠNG THÁI",
        body: `${purple("get tired")}, ${purple("get angry")}, ${purple("get better")}, ${purple("get worse")} mô tả trạng thái thay đổi.`,
        examples: [
          ex("I get tired after long meetings.", "Tôi thấy mệt sau những cuộc họp dài."),
          ex("The weather got better.", "Thời tiết đã tốt hơn."),
          ex("Don't get angry.", "Đừng nổi giận."),
        ],
      },
      {
        title: "CỤM TỪ QUAN TRỌNG",
        body: `Cụm quan trọng: ${purple("get home")}, ${purple("get ready")}, ${purple("get to work")}, ${purple("get in touch")}.`,
        examples: [
          ex("What time did you get home?", "Bạn về đến nhà lúc mấy giờ?"),
          ex("Please get ready now.", "Hãy chuẩn bị ngay bây giờ."),
          ex("I'll get in touch tomorrow.", "Tôi sẽ liên lạc vào ngày mai."),
        ],
      },
    ],
    words: [
      { term: "get a message", definition: "nhận tin nhắn", partOfSpeech: "VERB", example: "I got a message from Lan." },
      { term: "get an email", definition: "nhận email", partOfSpeech: "VERB", example: "Did you get my email?" },
      { term: "get a call", definition: "nhận cuộc gọi", partOfSpeech: "VERB", example: "I got a call from my boss." },
      { term: "get a ticket", definition: "mua/nhận vé", partOfSpeech: "VERB", example: "We got two tickets online." },
      { term: "get a job", definition: "có việc", partOfSpeech: "VERB", example: "She got a job in marketing." },
      { term: "get help", definition: "nhận giúp đỡ", partOfSpeech: "VERB", example: "You can get help from support." },
      { term: "get information", definition: "lấy thông tin", partOfSpeech: "VERB", example: "Where can I get more information?" },
      { term: "get permission", definition: "xin/nhận sự cho phép", partOfSpeech: "VERB", example: "We got permission to enter." },
      { term: "get tired", definition: "mệt", partOfSpeech: "VERB", example: "I get tired in hot weather." },
      { term: "get angry", definition: "giận", partOfSpeech: "VERB", example: "He got angry with the delay." },
      { term: "get nervous", definition: "hồi hộp", partOfSpeech: "VERB", example: "She gets nervous before exams." },
      { term: "get cold", definition: "lạnh", partOfSpeech: "VERB", example: "I get cold in this room." },
      { term: "get better", definition: "khá hơn", partOfSpeech: "VERB", example: "My English is getting better." },
      { term: "get worse", definition: "tệ hơn", partOfSpeech: "VERB", example: "Traffic gets worse at 6 p.m." },
      { term: "get married", definition: "kết hôn", partOfSpeech: "VERB", example: "They got married last year." },
      { term: "get home", definition: "về tới nhà", partOfSpeech: "VERB", example: "I got home at 9 p.m." },
      { term: "get to work", definition: "đến chỗ làm", partOfSpeech: "VERB", example: "What time do you get to work?" },
      { term: "get to school", definition: "đến trường", partOfSpeech: "VERB", example: "He gets to school by bus." },
      { term: "get on a bus", definition: "lên xe buýt", partOfSpeech: "VERB", example: "We got on the bus quickly." },
      { term: "get off the train", definition: "xuống tàu", partOfSpeech: "VERB", example: "Get off at the next station." },
      { term: "get up", definition: "thức dậy", partOfSpeech: "VERB", example: "I get up at six." },
      { term: "get ready", definition: "chuẩn bị sẵn sàng", partOfSpeech: "VERB", example: "Get ready for class." },
      { term: "get dressed", definition: "mặc quần áo", partOfSpeech: "VERB", example: "The kids got dressed quickly." },
      { term: "get along with", definition: "hòa hợp với", partOfSpeech: "VERB", example: "I get along with my colleagues." },
      { term: "get in touch", definition: "liên lạc", partOfSpeech: "VERB", example: "Please get in touch next week." },
    ],
    exercises: [
      mcq(
        45,
        1,
        "Which phrase means 'become less ill'?",
        [
          { key: "a", label: "get better" },
          { key: "b", label: "get bus" },
          { key: "c", label: "get homeing" },
          { key: "d", label: "geting married with" },
        ],
        "a",
      ),
      fillBlank(
        45,
        2,
        "I usually ___ up at 6:30 on weekdays.",
        "get",
        [
          { key: "a", label: "get" },
          { key: "b", label: "bring" },
          { key: "c", label: "take" },
          { key: "d", label: "come" },
        ],
        "a",
      ),
      mcq(
        45,
        3,
        "Choose the correct collocation:",
        [
          { key: "a", label: "get in touch" },
          { key: "b", label: "get on touch" },
          { key: "c", label: "get to touching with" },
          { key: "d", label: "get touchly" },
        ],
        "a",
      ),
      fillBlank(
        45,
        4,
        "We need to ___ permission before filming here.",
        "get",
        [
          { key: "a", label: "get" },
          { key: "b", label: "do" },
          { key: "c", label: "go" },
          { key: "d", label: "have" },
        ],
        "a",
      ),
    ],
  }),
];
