export const CURATED_PRE_PROMPT_VI_01_15: Readonly<Record<string, string>> = {
  "ex-pre-1-1": "Ghép mỗi từ với nghĩa tiếng Việt.",
  "ex-pre-1-2": "Ôn tập ngắt quãng cải thiện ___ (khả năng ghi nhớ).",
  "ex-pre-1-3": "Hãy học mỗi cụm trong ___ (ngữ cảnh).",
  "ex-pre-1-4": "Viết một ___ (từ trái nghĩa) bên cạnh mỗi tính từ.",
  "ex-pre-1-5": "Kiểm tra ___ (mức trang trọng) trước khi dùng tiếng lóng.",
  "ex-pre-1-6": "Dùng ___ (tự kiểm tra chủ động) thay vì đọc lại.",
  "ex-pre-1-7": "Phương pháp lặp lại ngắt quãng theo chu kỳ là gì?",
  "ex-pre-1-8": "Từ nào chỉ nhóm từ cùng gốc (danh/động/tính từ)?",
  "ex-pre-1-9": "\"To ___\" nghĩa là học để có thể nhớ.",
  "ex-pre-1-10": "___ (nhóm từ đồng nghĩa) này giúp tôi tránh lặp từ.",
  "ex-pre-1-11": "Các bài kiểm tra nhanh giúp ___ (gợi nhớ).",
  "ex-pre-1-12": "Chúng tôi làm một bài ___ (luyện tập) phát âm ngắn.",
  "ex-pre-1-13": "Từ điển cho một ___ (ghi chú cách dùng) rõ ràng.",
  "ex-pre-1-14": "___ liên kết các từ cùng chủ đề trong sơ đồ.",
  "ex-pre-2-1": "Ghép mỗi từ với nghĩa tiếng Việt.",
  "ex-pre-2-2": "Viết một ___ (mục từ) rõ ràng cho mỗi từ.",
  "ex-pre-2-3": "Tô nổi ___ (từ chính) màu xanh.",
  "ex-pre-2-4": "Tôi giữ một ___ (sổ lỗi) ở phần cuối.",
  "ex-pre-2-5": "Dùng một ___ (mẫu khung) cho mọi mục từ mới.",
  "ex-pre-2-6": "___ (chu kỳ ôn) của tôi là ngày 1, 3 và 7.",
  "ex-pre-2-7": "Thêm một ___ (câu ví dụ) từ đời thực.",
  "ex-pre-2-8": "Mục nào phù hợp nhất để ghi lỗi hay lặp lại?",
  "ex-pre-2-9": "___ cho biết từ trang trọng hay thân mật.",
  "ex-pre-2-10": "\"To ___\" nghĩa là phân loại từ thành nhóm.",
  "ex-pre-2-11": "___ (tô nổi) các collocation màu tím.",
  "ex-pre-2-12": "___ (ghi chú) các ví dụ khó bằng tiếng Việt.",
  "ex-pre-2-13": "Dùng ___ (liên kết chéo) để nối các từ tương tự.",
  "ex-pre-2-14": "Một ___ hình sao nghĩa là từ khó.",
  "ex-pre-3-1": "Ghép mỗi từ với nghĩa tiếng Việt.",
  "ex-pre-3-2": "Một ___ (từ điển đơn ngữ) cho ví dụ phong phú hơn.",
  "ex-pre-3-3": "Người mới thường bắt đầu với ___ (từ điển song ngữ).",
  "ex-pre-3-4": "___ (ký hiệu phiên âm) cho biết độ dài nguyên âm.",
  "ex-pre-3-5": "___ (thành ngữ) này nghe tự nhiên khi trò chuyện.",
  "ex-pre-3-6": "___ (dấu trọng âm) nằm ở âm tiết thứ hai.",
  "ex-pre-3-7": "Kiểm tra ___ (nhãn từ loại) trước tiên.",
  "ex-pre-3-8": "___ cho biết một từ phổ biến đến mức nào.",
  "ex-pre-3-9": "Động từ + tiểu từ như \"look up\" là gì?",
  "ex-pre-3-10": "\"To ___\" nghĩa là kiểm tra nghĩa hợp ngữ cảnh.",
  "ex-pre-3-11": "___ (xem lướt) các mục gần đó để tìm từ liên quan.",
  "ex-pre-3-12": "Một ___ (ví dụ dùng từ) tránh sai collocation.",
  "ex-pre-3-13": "___ (ứng dụng từ điển) của tôi chạy cả khi offline.",
  "ex-pre-3-14": "Trước khi dịch, bạn nên ___ (so sánh nét nghĩa).",
  "ex-pre-4-1": "Ghép mỗi từ với nghĩa tiếng Việt.",
  "ex-pre-4-2": "Tiếng Việt là ___ (tiếng mẹ đẻ) của tôi.",
  "ex-pre-4-3": "Luyện nói hằng ngày xây dựng ___ (độ trôi chảy).",
  "ex-pre-4-4": "Cố cân bằng giữa fluency và ___ (độ chính xác).",
  "ex-pre-4-5": "___ (ngữ điệu) của bạn giờ nghe tự nhiên.",
  "ex-pre-4-6": "Từ này có ba ___ (âm tiết).",
  "ex-pre-4-7": "Dùng ___ (tiếng Anh đơn giản) trong hướng dẫn.",
  "ex-pre-4-8": "___ là dạng địa phương của một ngôn ngữ.",
  "ex-pre-4-9": "Tránh ___ (thuật ngữ chuyên môn) khi dạy người mới.",
  "ex-pre-4-10": "\"To ___\" nghĩa là diễn đạt lại bằng từ khác.",
  "ex-pre-4-11": "Anh ấy có ___ (giọng) Úc rõ.",
  "ex-pre-4-12": "Một ___ (mệnh đề) quan hệ bổ sung chi tiết.",
  "ex-pre-4-13": "___ (dấu câu) đúng cải thiện sự rõ ràng.",
  "ex-pre-4-14": "Nhiều thuật ngữ công nghệ là ___ (từ vay mượn).",
  "ex-pre-5-1": "Ghép mỗi từ với nghĩa tiếng Việt.",
  "ex-pre-5-2": "Cô ấy xin ___ (quốc tịch) kép.",
  "ex-pre-5-3": "Tiếng Anh là ___ (ngôn ngữ chính thức) ở Singapore.",
  "ex-pre-5-4": "Thành phố có cộng đồng ___ (người nước ngoài) lớn.",
  "ex-pre-5-5": "Cô ấy tự hào về ___ (di sản) văn hóa của mình.",
  "ex-pre-5-6": "Tôi luyện với ___ (người bản ngữ) trực tuyến.",
  "ex-pre-5-7": "Luôn kiểm tra ___ (tình trạng thị thực) trước khi đi.",
  "ex-pre-5-8": "Người dùng được nhiều ngôn ngữ là gì?",
  "ex-pre-5-9": "\"To ___\" nghĩa là di cư ra nước ngoài để sống.",
  "ex-pre-5-10": "Đám đông hát ___ (quốc ca) trước trận đấu.",
  "ex-pre-5-11": "Anh họ tôi là ___ (người cư trú) thường trú.",
  "ex-pre-5-12": "Họ đã ___ (ổn định cuộc sống) ở Canada.",
  "ex-pre-5-13": "___ (kiểm soát biên giới) kiểm tra giấy tờ của chúng tôi.",
  "ex-pre-5-14": "Cô ấy xem mình là một ___.",
  "ex-pre-6-1": "Ghép mỗi từ với nghĩa tiếng Việt.",
  "ex-pre-6-2": "Một dòng sông nhỏ chảy qua ___ (thung lũng).",
  "ex-pre-6-3": "Tránh xa mép ___ (vách đá).",
  "ex-pre-6-4": "___ (sông băng) đang thu nhỏ mỗi năm.",
  "ex-pre-6-5": "Mưa lớn gây ___ (xói mòn) đất.",
  "ex-pre-6-6": "Năng lượng mặt trời là ___ (tài nguyên tái tạo).",
  "ex-pre-6-7": "Rạn san hô là ___ (hệ sinh thái) mong manh.",
  "ex-pre-6-8": "Than, dầu và khí là loại nào?",
  "ex-pre-6-9": "\"To ___\" nghĩa là giữ nguyên trạng.",
  "ex-pre-6-10": "Nhà máy có thể ___ (làm ô nhiễm) sông.",
  "ex-pre-6-11": "Địa hình này quá gồ ghề cho ___ (xe đạp).",
  "ex-pre-6-12": "Khu vực này giàu ___ (khoáng chất).",
  "ex-pre-6-13": "Cắm trại bị hạn chế trong ___ (khu bảo tồn) này.",
  "ex-pre-6-14": "Du lịch có cả ___ (tác động môi trường) tích cực và tiêu cực.",
  "ex-pre-7-1": "Ghép mỗi từ với nghĩa tiếng Việt.",
  "ex-pre-7-2": "___ (dự báo) nói tối nay có bão.",
  "ex-pre-7-3": "___ (độ ẩm) cao vào tháng Tám.",
  "ex-pre-7-4": "Một ___ (đợt nóng) ập đến thành phố tuần trước.",
  "ex-pre-7-5": "Một ___ (trận mưa lớn) làm ngập phố.",
  "ex-pre-7-6": "Một ___ (làn gió) biển làm chúng tôi mát.",
  "ex-pre-7-7": "___ (sương giá) buổi sáng phủ trên cỏ.",
  "ex-pre-7-8": "Cơn bão có sấm chớp gọi là gì?",
  "ex-pre-7-9": "Đợt lạnh ngắn nhưng mạnh gọi là gì?",
  "ex-pre-7-10": "Bầu trời ___ (u ám) cả ngày.",
  "ex-pre-7-11": "Xe bị hư hại vì ___ (mưa đá).",
  "ex-pre-7-12": "Một ___ (cơn gió giật) thổi bay mũ tôi.",
  "ex-pre-7-13": "Mùa đông ___ (ôn hòa) ở vùng này.",
  "ex-pre-7-14": "Dự kiến tối nay ___ (giảm nhiệt độ) mạnh.",
  "ex-pre-8-1": "Ghép mỗi từ với nghĩa tiếng Việt.",
  "ex-pre-8-2": "Cá voi là ___ (động vật có vú), không phải cá.",
  "ex-pre-8-3": "Hổ là ___ (kẻ săn mồi) đầu bảng.",
  "ex-pre-8-4": "Thỏ là ___ (con mồi) phổ biến trong tự nhiên.",
  "ex-pre-8-5": "Một ___ (đàn) hươu băng qua đường.",
  "ex-pre-8-6": "___ (ngụy trang) giúp côn trùng sống sót.",
  "ex-pre-8-7": "Chim theo ___ (đường di cư) này mỗi năm.",
  "ex-pre-8-8": "Ếch là loài gì?",
  "ex-pre-8-9": "Động vật hoạt động ban đêm là gì?",
  "ex-pre-8-10": "\"To ___\" nghĩa là ngủ suốt mùa đông.",
  "ex-pre-8-11": "Một số loài rắn có ___ (nọc độc).",
  "ex-pre-8-12": "Bò ___ (gặm cỏ) gần sông.",
  "ex-pre-8-13": "Đô thị hóa có thể giảm ___ (đa dạng sinh học).",
  "ex-pre-8-14": "Săn trộm bị cấm trong ___ (khu bảo tồn động vật).",
  "ex-pre-9-1": "Ghép mỗi từ với nghĩa tiếng Việt.",
  "ex-pre-9-2": "___ (tư thế) tốt phòng đau lưng.",
  "ex-pre-9-3": "___ (khớp) gối tôi đau sau khi chạy.",
  "ex-pre-9-4": "Giãn cơ giúp thư giãn ___ (cơ bắp) căng.",
  "ex-pre-9-5": "Yoga cải thiện ___ (thăng bằng).",
  "ex-pre-9-6": "Khiêu vũ đòi hỏi ___ (sự phối hợp).",
  "ex-pre-9-7": "Tập đều đặn giữ ___ (khả năng vận động).",
  "ex-pre-9-8": "\"To ___\" nghĩa là chạy hết tốc lực trong thời gian ngắn.",
  "ex-pre-9-9": "\"To ___\" nghĩa là vấp và mất thăng bằng.",
  "ex-pre-9-10": "\"Đừng ___ lưng đột ngột.\"",
  "ex-pre-9-11": "Chúng tôi ___ (chạy bộ) trong công viên trước giờ làm.",
  "ex-pre-9-12": "Bạn ___ (với tới) kệ trên cùng được không?",
  "ex-pre-9-13": "___ (nắm chắc) tay cầm.",
  "ex-pre-9-14": "___ (duỗi thẳng) tay từ từ.",
  "ex-pre-10-1": "Ghép mỗi từ với nghĩa tiếng Việt.",
  "ex-pre-10-2": "Anh ấy có ___ (nước da) ấm.",
  "ex-pre-10-3": "___ (tàn nhang) xuất hiện vào mùa hè.",
  "ex-pre-10-4": "Kem này giảm ___ (nếp nhăn) mảnh.",
  "ex-pre-10-5": "Cô ấy cắt ___ (mái tóc) ngắn hơn.",
  "ex-pre-10-6": "Cô ấy có dáng ___ (mảnh mai).",
  "ex-pre-10-7": "Cô ấy trông ___ (thanh lịch) trong bộ đồ đen.",
  "ex-pre-10-8": "Người đàn ông vai rộng, chắc là gì?",
  "ex-pre-10-9": "Người trông lôi thôi, luộm thuộm là gì?",
  "ex-pre-10-10": "Mọi người ở sự kiện đều ___ (ăn mặc chỉnh tề).",
  "ex-pre-10-11": "Cậu bé ___ (tóc xoăn) là anh họ tôi.",
  "ex-pre-10-12": "Tôi thích một ___ (trang phục thường ngày) vào thứ Sáu.",
  "ex-pre-10-13": "Một ___ (vết sẹo dễ thấy) chạy ngang cằm anh ấy.",
  "ex-pre-10-14": "Thủ môn khỏe và cơ bắp; anh ấy ___ (vạm vỡ).",
  "ex-pre-11-1": "Ghép mỗi từ với nghĩa tiếng Việt.",
  "ex-pre-11-2": "Đồng đội mới của chúng tôi rất ___ (cởi mở).",
  "ex-pre-11-3": "Anh ấy ___ (kín đáo) với người lạ.",
  "ex-pre-11-4": "Cô ấy ___ (đáng tin) khi chịu áp lực.",
  "ex-pre-11-5": "Anh trai tôi ___ (bướng bỉnh) về tiền bạc.",
  "ex-pre-11-6": "Cô ấy ___ (tham vọng) nhưng thực tế.",
  "ex-pre-11-7": "Một quản lý giỏi thì ___ (cởi mở với ý tưởng).",
  "ex-pre-11-8": "Người hành động theo cảm xúc, thiếu suy nghĩ là gì?",
  "ex-pre-11-9": "Người nêu ý kiến chắc chắn nhưng lịch sự là gì?",
  "ex-pre-11-10": "Người hiểu cảm xúc của người khác là gì?",
  "ex-pre-11-11": "Huấn luyện viên của chúng tôi ___ (dễ tính).",
  "ex-pre-11-12": "Anh ấy ___ (nhạy cảm) với lời chê.",
  "ex-pre-11-13": "Hãy chọn một đối tác ___ (đáng tin cậy).",
  "ex-pre-11-14": "Người có tâm trạng thay đổi thất thường là gì?",
  "ex-pre-12-1": "Ghép mỗi từ với nghĩa tiếng Việt.",
  "ex-pre-12-2": "Tôi cảm thấy ___ (bực bội) với internet chậm.",
  "ex-pre-12-3": "Cô ấy ___ (nhẹ nhõm) sau kỳ thi.",
  "ex-pre-12-4": "Anh ấy cảm thấy ___ (quá tải) trong ngày đầu.",
  "ex-pre-12-5": "Tôi ___ (biết ơn) sự hướng dẫn của bạn.",
  "ex-pre-12-6": "Nhiều sinh viên ___ (nhớ nhà) khi ở nước ngoài.",
  "ex-pre-12-7": "Tôi ___ (lo lắng) trước khi thuyết trình.",
  "ex-pre-12-8": "Cảm thấy tệ vì làm sai là cảm thấy gì?",
  "ex-pre-12-9": "Rất phấn khích và vui là gì?",
  "ex-pre-12-10": "\"To ___\" nghĩa là trở nên vui vẻ hơn.",
  "ex-pre-12-11": "Cô ấy ___ (đau lòng) sau khi chia tay.",
  "ex-pre-12-12": "Đừng ___ (kìm nén) cảm xúc của bạn.",
  "ex-pre-12-13": "Căng thẳng có thể gây ___ (thay đổi tâm trạng).",
  "ex-pre-12-14": "Ngủ đủ cải thiện ___ (khả năng phục hồi cảm xúc).",
  "ex-pre-13-1": "Ghép mỗi từ với nghĩa tiếng Việt.",
  "ex-pre-13-2": "___ (hộ gia đình) của chúng tôi có năm thành viên.",
  "ex-pre-13-3": "___ (cha dượng) của cô ấy rất ủng hộ.",
  "ex-pre-13-4": "Chúng tôi thăm ___ (họ hàng bên chồng/vợ) mỗi dịp Tết.",
  "ex-pre-13-5": "___ (bạn cùng nhà) của tôi nấu tối vào thứ Sáu.",
  "ex-pre-13-6": "Một ___ (mạng lưới hỗ trợ) mạnh giảm căng thẳng.",
  "ex-pre-13-7": "Họ là một gia đình ___ (gắn bó khăng khít).",
  "ex-pre-13-8": "\"To ___\" nghĩa là dần dần xa cách.",
  "ex-pre-13-9": "\"To ___\" nghĩa là làm hòa sau khi cãi nhau.",
  "ex-pre-13-10": "Hai anh em ___ (cãi nhau, mất hòa khí) vì tiền.",
  "ex-pre-13-11": "Chúng tôi ___ (giữ liên lạc) qua gọi video.",
  "ex-pre-13-12": "Tháng trước tôi gặp một ___ (bạn thời thơ ấu).",
  "ex-pre-13-13": "___ (buổi họp mặt gia đình) của chúng tôi vào cuối tuần tới.",
  "ex-pre-13-14": "Sự ganh đua giữa anh chị em gọi là gì?",
  "ex-pre-14-1": "Ghép mỗi từ với nghĩa tiếng Việt.",
  "ex-pre-14-2": "___ (trẻ tập đi) đã nói được vài từ đơn giản.",
  "ex-pre-14-3": "Tốt nghiệp là một ___ (cột mốc) quan trọng.",
  "ex-pre-14-4": "___ (áp lực bạn bè) có thể ảnh hưởng quyết định.",
  "ex-pre-14-5": "Chị tôi là ___ (hình mẫu) của tôi.",
  "ex-pre-14-6": "Việc làm bán thời gian dạy ___ (tính tự lập).",
  "ex-pre-14-7": "Thanh thiếu niên cần nhiều ___ (trách nhiệm) hơn.",
  "ex-pre-14-8": "Người chín chắn, cư xử trưởng thành là gì?",
  "ex-pre-14-9": "\"To ___\" nghĩa là đến tuổi trưởng thành.",
  "ex-pre-14-10": "Cô ấy ___ (thích nghi với) cuộc sống đại học nhanh.",
  "ex-pre-14-11": "Anh ấy ___ (nổi loạn) hồi cấp ba.",
  "ex-pre-14-12": "Tôi ___ (nhìn lại) những năm học phổ thông một cách ấm áp.",
  "ex-pre-14-13": "Công nghệ nới rộng ___ (khoảng cách thế hệ).",
  "ex-pre-14-14": "Giai đoạn sinh học trở thành người lớn là gì?",
  "ex-pre-15-1": "Ghép mỗi từ với nghĩa tiếng Việt.",
  "ex-pre-15-2": "Anh ấy ___ (cảm nắng) một bạn cùng lớp.",
  "ex-pre-15-3": "Niềm tin là nền tảng của ___ (sự cam kết).",
  "ex-pre-15-4": "___ (cặp mới cưới) chuyển đến Đà Nẵng.",
  "ex-pre-15-5": "Họ trải qua ___ (tuần trăng mật) ở Bali.",
  "ex-pre-15-6": "___ (tôn trọng lẫn nhau) giữ hôn nhân bền chặt.",
  "ex-pre-15-7": "Họ viết ___ (lời thề cưới) riêng.",
  "ex-pre-15-8": "\"To ___\" nghĩa là kết thúc quan hệ tình cảm.",
  "ex-pre-15-9": "Cặp đôi sống xa nhau đang trong quan hệ gì?",
  "ex-pre-15-10": "\"To ___\" nghĩa là kết hôn lần nữa.",
  "ex-pre-15-11": "Họ rất ___ (hợp nhau).",
  "ex-pre-15-12": "Cặp đôi ___ (chia tay) năm ngoái.",
  "ex-pre-15-13": "Cô ấy trở thành ___ (cha/mẹ đơn thân) ở tuổi 30.",
  "ex-pre-15-14": "Cùng nuôi con sau ly hôn gọi là gì?",
};
