import { EVIU_ELEMENTARY_CATALOG } from "@/lib/vocabulary/eviu-elementary-catalog";
import type { VocabularyExercise, VocabularyUnit } from "@/lib/vocabulary/vocabulary-unit-types";
import { bold, buildEviuUnit, ex, fillBlank, mcq, purple } from "./eviu-unit-builder";

type WordItem = {
  term: string;
  definition: string;
  partOfSpeech?: string;
  example?: string;
};

type ExerciseInput = {
  question: string;
  answer: string;
  distractors: [string, string, string];
};

function byUnit(unitNumber: number) {
  const entry = EVIU_ELEMENTARY_CATALOG.find((item) => item.unitNumber === unitNumber);
  if (!entry) {
    throw new Error(`Missing catalog entry for unit ${unitNumber}.`);
  }
  return entry;
}

function w(term: string, definition: string, partOfSpeech = "WORD", example?: string): WordItem {
  return { term, definition, partOfSpeech, example };
}

function options(correct: string, d1: string, d2: string, d3: string) {
  return [
    { key: "a", label: correct },
    { key: "b", label: d1 },
    { key: "c", label: d2 },
    { key: "d", label: d3 },
  ];
}

function buildExercises(unitNumber: number, items: ExerciseInput[]): VocabularyExercise[] {
  return items.map((item, index) => {
    const n = index + 1;
    const opts = options(item.answer, item.distractors[0], item.distractors[1], item.distractors[2]);
    if (item.question.includes("___")) {
      return fillBlank(
        unitNumber,
        n,
        item.question,
        item.answer,
        opts,
        "a",
        [item.answer.toLowerCase()],
        "Điền từ vào chỗ trống",
      );
    }
    return mcq(unitNumber, n, item.question, opts, "a", "Chọn đáp án đúng");
  });
}

const UNIT_46 = buildEviuUnit(byUnit(46), {
  introVi: "Cụm động từ phổ biến trong hội thoại hằng ngày, tập trung vào thói quen, công việc và kế hoạch.",
  structureSections: [
    { label: "Daily actions", wordCount: 9 },
    { label: "Home and errands", wordCount: 8 },
    { label: "Plans and communication", wordCount: 8 },
  ],
  collocationHtml: `Các cụm ${purple("wake up early")}, ${purple("turn off the light")}, ${purple("run out of milk")} xuất hiện rất thường xuyên ở trình độ A1-A2.`,
  mistakeHtml: `${purple("look after")} = "chăm sóc", không dịch từng từ. ${bold("[SAI] look = nhìn, after = sau => look after = nhìn sau.")}`,
  principles: [
    {
      title: "HỌC CỤM NHƯ MỘT ĐƠN VỊ NGHĨA",
      body: `Hãy học ${purple("phrasal verbs")} theo cụm và ngữ cảnh, thay vì tách rời động từ + giới từ.`,
      examples: [ex("Please turn off your phone.", "Làm ơn tắt điện thoại của bạn."), ex("I look after my little brother.", "Tôi chăm em trai nhỏ của tôi.")],
    },
    {
      title: "ƯU TIÊN CỤM TẦN SUẤT CAO",
      body: `Ở trình độ elementary, tập trung các cụm dùng mỗi ngày như ${purple("get up")}, ${purple("go out")}, ${purple("pick up")}.`,
      examples: [ex("I get up at six.", "Tôi dậy lúc sáu giờ."), ex("Can you pick me up at school?", "Bạn có thể đón tôi ở trường không?")],
    },
    {
      title: "LUYỆN THEO CẶP ĐỐI LẬP",
      body: `Bạn sẽ nhớ nhanh hơn khi học theo cặp: ${purple("turn on / turn off")}, ${purple("put on / take off")}.`,
      examples: [ex("Turn on the fan.", "Bật quạt lên."), ex("Take off your shoes.", "Cởi giày ra.")],
    },
  ],
  words: [
    w("wake up", "thức dậy", "PHRASAL VERB"),
    w("get up", "ra khỏi giường", "PHRASAL VERB"),
    w("go out", "đi ra ngoài", "PHRASAL VERB"),
    w("come in", "đi vào", "PHRASAL VERB"),
    w("sit down", "ngồi xuống", "PHRASAL VERB"),
    w("stand up", "đứng lên", "PHRASAL VERB"),
    w("put on", "mặc vào; đeo vào", "PHRASAL VERB"),
    w("take off", "cởi ra", "PHRASAL VERB"),
    w("turn on", "bật thiết bị", "PHRASAL VERB"),
    w("turn off", "tắt thiết bị", "PHRASAL VERB"),
    w("pick up", "đón ai; nhặt lên", "PHRASAL VERB"),
    w("drop off", "thả ai xuống", "PHRASAL VERB"),
    w("look for", "tìm kiếm", "PHRASAL VERB"),
    w("look after", "chăm sóc", "PHRASAL VERB"),
    w("find out", "tìm ra; phát hiện", "PHRASAL VERB"),
    w("give up", "từ bỏ", "PHRASAL VERB"),
    w("carry on", "tiếp tục", "PHRASAL VERB"),
    w("hurry up", "nhanh lên", "PHRASAL VERB"),
    w("slow down", "chậm lại", "PHRASAL VERB"),
    w("run out of", "hết thứ gì", "PHRASAL VERB"),
    w("clean up", "dọn dẹp", "PHRASAL VERB"),
    w("throw away", "vứt đi", "PHRASAL VERB"),
    w("try on", "thử đồ", "PHRASAL VERB"),
    w("call back", "gọi lại", "PHRASAL VERB"),
    w("show up", "xuất hiện", "PHRASAL VERB"),
  ],
  exercises: buildExercises(46, [
    { question: "I usually ___ at 6 a.m.", answer: "wake up", distractors: ["give up", "show up", "throw away"] },
    { question: "Which phrasal verb means 'chăm sóc'?", answer: "look after", distractors: ["look for", "carry on", "try on"] },
    { question: "Please ___ your shoes before entering.", answer: "take off", distractors: ["turn on", "look for", "call back"] },
    { question: "What is the opposite of turn on?", answer: "turn off", distractors: ["come in", "sit down", "show up"] },
    { question: "We ___ milk, so I need to buy some.", answer: "run out of", distractors: ["find out", "stand up", "hurry up"] },
    { question: "Choose the correct pair.", answer: "put on / take off", distractors: ["sit down / look for", "go out / look after", "pick up / hurry up"] },
    { question: "Can you ___ me at the station?", answer: "pick up", distractors: ["throw away", "carry on", "drop in"] },
    { question: "Which phrasal verb means 'từ bỏ'?", answer: "give up", distractors: ["clean up", "call back", "turn on"] },
    { question: "___ the lights before you leave.", answer: "turn off", distractors: ["show up", "find out", "come in"] },
    { question: "What does 'hurry up' mean?", answer: "nhanh lên", distractors: ["chậm lại", "chăm sóc", "tiếp tục"] },
  ]),
});

const UNIT_47 = buildEviuUnit(byUnit(47), {
  introVi: "Từ vựng về đồ vật, vật dụng cá nhân và hoạt động sinh hoạt thường ngày.",
  structureSections: [
    { label: "Home objects", wordCount: 9 },
    { label: "Personal items", wordCount: 8 },
    { label: "Daily chores", wordCount: 8 },
  ],
  collocationHtml: `Các cụm ${purple("make the bed")}, ${purple("wash the dishes")}, ${purple("do the laundry")} là nền tảng cho chủ đề việc nhà.`,
  mistakeHtml: `${purple("borrow")} là "mượn", ${purple("lend")} là "cho mượn". ${bold("[SAI] borrow = cho mượn, lend = mượn.")}`,
  principles: [
    {
      title: "NHÓM TỪ THEO KHÔNG GIAN",
      body: `Sắp từ theo khu vực như ${purple("kitchen")}, ${purple("bedroom")}, đồ cá nhân sẽ giúp ghi nhớ nhanh hơn học rời rạc.`,
      examples: [ex("The kettle is in the kitchen.", "Ấm đun nước ở trong bếp."), ex("My wallet is in my bag.", "Ví của tôi ở trong túi.")],
    },
    {
      title: "HỌC DANH TỪ CÙNG ĐỘNG TỪ ĐI KÈM",
      body: `Nên học theo cụm: ${purple("set the table")}, ${purple("take out the rubbish")}, ${purple("charge the phone")}.`,
      examples: [ex("Please set the table.", "Làm ơn bày bàn ăn."), ex("I need to charge my phone.", "Tôi cần sạc điện thoại.")],
    },
    {
      title: "DÙNG ĐÚNG NGỮ CẢNH",
      body: `Một số đồ vật tương tự nhau nhưng khác sắc thái dùng, ví dụ ${purple("wallet")} và ${purple("purse")}.`,
      examples: [ex("He keeps cash in his wallet.", "Anh ấy để tiền mặt trong ví."), ex("She carries a small purse.", "Cô ấy mang một chiếc ví nhỏ.")],
    },
  ],
  words: [
    w("kettle", "ấm đun nước", "NOUN"),
    w("toothbrush", "bàn chải đánh răng", "NOUN"),
    w("toothpaste", "kem đánh răng", "NOUN"),
    w("towel", "khăn tắm", "NOUN"),
    w("soap", "xà phòng", "NOUN"),
    w("pillow", "gối", "NOUN"),
    w("blanket", "chăn", "NOUN"),
    w("remote control", "điều khiển từ xa", "NOUN"),
    w("charger", "bộ sạc", "NOUN"),
    w("wallet", "ví", "NOUN"),
    w("purse", "ví nhỏ", "NOUN"),
    w("backpack", "ba lô", "NOUN"),
    w("notebook", "sổ tay", "NOUN"),
    w("umbrella", "ô; dù", "NOUN"),
    w("keys", "chìa khóa", "NOUN"),
    w("coins", "tiền xu", "NOUN"),
    w("make the bed", "dọn giường", "PHRASE"),
    w("wash the dishes", "rửa bát", "PHRASE"),
    w("do the laundry", "giặt đồ", "PHRASE"),
    w("take out the rubbish", "đổ rác", "PHRASE"),
    w("set the table", "bày bàn ăn", "PHRASE"),
    w("charge the phone", "sạc điện thoại", "PHRASE"),
    w("borrow", "mượn", "VERB"),
    w("lend", "cho mượn", "VERB"),
    w("tidy up", "dọn gọn", "PHRASAL VERB"),
  ],
  exercises: buildExercises(47, [
    { question: "You use this after a shower: ___.", answer: "towel", distractors: ["soap", "pillow", "charger"] },
    { question: "Which phrase means 'rửa bát'?", answer: "wash the dishes", distractors: ["set the table", "make the bed", "do the laundry"] },
    { question: "Can I ___ your pen for a minute?", answer: "borrow", distractors: ["lend", "charge", "tidy up"] },
    { question: "Which one means 'cho mượn'?", answer: "lend", distractors: ["borrow", "set", "wash"] },
    { question: "I forgot my phone ___ at home.", answer: "charger", distractors: ["umbrella", "wallet", "coins"] },
    { question: "Choose the correct collocation.", answer: "do the laundry", distractors: ["make the laundry", "wash the laundry up", "set the laundry"] },
    { question: "Please ___ your room before dinner.", answer: "tidy up", distractors: ["throw up", "look up", "set up"] },
    { question: "Where do people keep money and cards?", answer: "wallet", distractors: ["kettle", "blanket", "remote control"] },
    { question: "It's raining. Take your ___.", answer: "umbrella", distractors: ["notebook", "soap", "keys"] },
    { question: "What does 'set the table' mean?", answer: "bày bàn ăn", distractors: ["đổ rác", "dọn giường", "sạc điện thoại"] },
  ]),
});

const UNIT_48 = buildEviuUnit(byUnit(48), {
  introVi: "Nhóm từ trọng tâm để mở đầu hội thoại, trao đổi thông tin và phản hồi lịch sự.",
  structureSections: [
    { label: "Conversation starters", wordCount: 8 },
    { label: "Information sharing", wordCount: 9 },
    { label: "Responses and opinions", wordCount: 8 },
  ],
  collocationHtml: `Các cụm ${purple("ask a question")}, ${purple("tell a story")}, ${purple("give an opinion")} giúp bạn nói mạch lạc hơn.`,
  mistakeHtml: `${purple("say")} thường đi với nội dung, ${purple("tell")} thường đi với người nghe. ${bold("[SAI] tell a word / say me something.")}`,
  principles: [
    {
      title: "CHỌN ĐỘNG TỪ ĐÚNG MỤC ĐÍCH GIAO TIẾP",
      body: `Muốn lấy thông tin dùng ${purple("ask")}; muốn giải thích dùng ${purple("explain")}; muốn nêu quan điểm dùng ${purple("give an opinion")}.`,
      examples: [ex("Can I ask a question?", "Tôi có thể đặt một câu hỏi không?"), ex("Please explain this idea.", "Làm ơn giải thích ý này.")],
    },
    {
      title: "GIỮ HỘI THOẠI HAI CHIỀU",
      body: `Dùng ${purple("answer")}, ${purple("reply")}, ${purple("agree/disagree")} để cuộc nói chuyện có tương tác thay vì độc thoại.`,
      examples: [ex("He replied quickly.", "Anh ấy trả lời rất nhanh."), ex("I agree with your point.", "Tôi đồng ý với ý kiến của bạn.")],
    },
    {
      title: "SỬ DỤNG CỤM ĐỆM LỊCH SỰ",
      body: `Cụm như ${purple("in my opinion")} hay ${purple("to be honest")} giúp điều chỉnh sắc thái.`,
      examples: [ex("In my opinion, this is better.", "Theo tôi, cái này tốt hơn."), ex("To be honest, I forgot.", "Thành thật mà nói, tôi đã quên.")],
    },
  ],
  words: [
    w("ask", "hỏi", "VERB"),
    w("answer", "trả lời", "VERB"),
    w("reply", "hồi đáp", "VERB"),
    w("say", "nói", "VERB"),
    w("tell", "nói; kể cho ai", "VERB"),
    w("explain", "giải thích", "VERB"),
    w("describe", "miêu tả", "VERB"),
    w("mention", "đề cập", "VERB"),
    w("discuss", "thảo luận", "VERB"),
    w("chat", "trò chuyện", "VERB"),
    w("whisper", "thì thầm", "VERB"),
    w("shout", "la hét", "VERB"),
    w("argue", "tranh cãi", "VERB"),
    w("agree", "đồng ý", "VERB"),
    w("disagree", "không đồng ý", "VERB"),
    w("suggest", "gợi ý", "VERB"),
    w("invite", "mời", "VERB"),
    w("refuse", "từ chối", "VERB"),
    w("promise", "hứa", "VERB"),
    w("warn", "cảnh báo", "VERB"),
    w("ask a question", "đặt câu hỏi", "PHRASE"),
    w("tell a story", "kể chuyện", "PHRASE"),
    w("give an opinion", "đưa ý kiến", "PHRASE"),
    w("in my opinion", "theo ý kiến của tôi", "PHRASE"),
    w("to be honest", "thành thật mà nói", "PHRASE"),
  ],
  exercises: buildExercises(48, [
    { question: "Can I ___ a question?", answer: "ask", distractors: ["argue", "warn", "refuse"] },
    { question: "Which verb means 'giải thích'?", answer: "explain", distractors: ["reply", "invite", "shout"] },
    { question: "Tell me your name. (Choose the missing word) ___ me your name.", answer: "Tell", distractors: ["Say", "Explain", "Mention"] },
    { question: "Which phrase introduces your view?", answer: "in my opinion", distractors: ["ask a question", "tell a story", "to be late"] },
    { question: "I ___ with you. That's a good idea.", answer: "agree", distractors: ["argue", "shout", "refuse"] },
    { question: "Opposite of agree is ___.", answer: "disagree", distractors: ["discuss", "mention", "promise"] },
    { question: "Please ___ your hometown in two sentences.", answer: "describe", distractors: ["whisper", "warn", "invite"] },
    { question: "Which one means 'thành thật mà nói'?", answer: "to be honest", distractors: ["in my opinion", "ask a question", "give an opinion"] },
    { question: "She ___ me to her birthday party.", answer: "invited", distractors: ["argued", "whispered", "refused"] },
    { question: "What does 'reply' mean?", answer: "hồi đáp", distractors: ["tranh cãi", "thì thầm", "kể chuyện"] },
  ]),
});

const UNIT_49 = buildEviuUnit(byUnit(49), {
  introVi: "Từ vựng mô tả chuyển động, hướng đi và thay đổi vị trí trong bối cảnh đời sống.",
  structureSections: [
    { label: "Movement verbs", wordCount: 9 },
    { label: "Transport phrases", wordCount: 8 },
    { label: "Relocation language", wordCount: 8 },
  ],
  collocationHtml: `Các cụm ${purple("get on the bus")}, ${purple("get off the train")}, ${purple("move house")} là trọng tâm của unit này.`,
  mistakeHtml: `${purple("bring")} là mang đến gần người nói, ${purple("take")} là mang đi khỏi người nói. ${bold("[SAI] bring đi chợ, take lại đây.")}`,
  principles: [
    {
      title: "NẮM ĐỘNG TỪ DI CHUYỂN CƠ BẢN",
      body: `Các động từ ${purple("go")}, ${purple("come")}, ${purple("walk")}, ${purple("run")}, ${purple("drive")} là nền tảng trước khi học cụm nâng cao.`,
      examples: [ex("I walk to school.", "Tôi đi bộ đến trường."), ex("She drives to work.", "Cô ấy lái xe đi làm.")],
    },
    {
      title: "DÙNG ĐÚNG CỤM PHƯƠNG TIỆN",
      body: `Dùng ${purple("get on")} khi lên xe/tàu/máy bay và ${purple("get off")} khi rời phương tiện.`,
      examples: [ex("Get on quickly.", "Lên xe nhanh đi."), ex("We get off at the next stop.", "Chúng tôi xuống ở trạm kế tiếp.")],
    },
    {
      title: "MÔ TẢ THAY ĐỔI NƠI Ở",
      body: `Khi nói chuyển chỗ ở hay nơi làm việc, dùng ${purple("move house")}, ${purple("relocate")}, ${purple("move to + place")}.`,
      examples: [ex("We moved house last month.", "Tháng trước chúng tôi đã chuyển nhà."), ex("He relocated to Da Nang.", "Anh ấy đã chuyển vào Đà Nẵng.")],
    },
  ],
  words: [
    w("go", "đi", "VERB"),
    w("come", "đến", "VERB"),
    w("walk", "đi bộ", "VERB"),
    w("run", "chạy", "VERB"),
    w("drive", "lái xe", "VERB"),
    w("ride", "đi xe (đạp/máy)", "VERB"),
    w("fly", "bay", "VERB"),
    w("sail", "đi thuyền", "VERB"),
    w("climb", "leo", "VERB"),
    w("cross", "băng qua", "VERB"),
    w("pass", "đi ngang qua", "VERB"),
    w("turn", "rẽ", "VERB"),
    w("head for", "hướng tới", "PHRASAL VERB"),
    w("move", "di chuyển", "VERB"),
    w("move house", "chuyển nhà", "PHRASE"),
    w("relocate", "chuyển nơi ở/làm việc", "VERB"),
    w("carry", "mang vác", "VERB"),
    w("push", "đẩy", "VERB"),
    w("pull", "kéo", "VERB"),
    w("lift", "nâng lên", "VERB"),
    w("drop", "thả; làm rơi", "VERB"),
    w("get on", "lên phương tiện", "PHRASAL VERB"),
    w("get off", "xuống phương tiện", "PHRASAL VERB"),
    w("set off", "khởi hành", "PHRASAL VERB"),
    w("slow down", "chậm lại", "PHRASAL VERB"),
  ],
  exercises: buildExercises(49, [
    { question: "I ___ to school every day.", answer: "walk", distractors: ["fly", "sail", "pull"] },
    { question: "Which phrase means 'lên phương tiện'?", answer: "get on", distractors: ["get off", "set off", "slow down"] },
    { question: "Turn right and ___ the street.", answer: "cross", distractors: ["relocate", "carry", "ride"] },
    { question: "Opposite of get on is ___.", answer: "get off", distractors: ["set off", "head for", "move house"] },
    { question: "We will ___ at 5 a.m. tomorrow.", answer: "set off", distractors: ["drop off", "put off", "hold off"] },
    { question: "Which one means 'chuyển nhà'?", answer: "move house", distractors: ["move on", "move up", "move out"] },
    { question: "Please ___ this heavy box.", answer: "lift", distractors: ["fly", "sail", "turn"] },
    { question: "Choose the correct pair.", answer: "push / pull", distractors: ["go / come", "walk / run", "get on / get off"] },
    { question: "Drivers should ___ near schools.", answer: "slow down", distractors: ["set off", "get off", "head for"] },
    { question: "What does 'relocate' mean?", answer: "chuyển nơi ở/làm việc", distractors: ["leo núi", "đi thuyền", "kéo vật"] },
  ]),
});

const UNIT_50 = buildEviuUnit(byUnit(50), {
  introVi: "Liên từ và từ nối giúp nối ý logic trong nói và viết, đặc biệt với nguyên nhân-kết quả và tương phản.",
  structureSections: [
    { label: "Basic connectors", wordCount: 9 },
    { label: "Reason and result", wordCount: 8 },
    { label: "Contrast and condition", wordCount: 8 },
  ],
  collocationHtml: `Ba mẫu cần nhớ là ${purple("because of + noun")}, ${purple("so that + clause")}, ${purple("even though + clause")}.`,
  mistakeHtml: `${purple("Because")} it rained, we stayed home. ${bold("[SAI] Because it rained, so we stayed home.")}`,
  principles: [
    {
      title: "NỐI Ý CÙNG CHIỀU VÀ ĐỐI LẬP",
      body: `Dùng ${purple("and/also/moreover")} để thêm ý, dùng ${purple("but/however")} để thể hiện đối lập.`,
      examples: [ex("The room is small but clean.", "Căn phòng nhỏ nhưng sạch."), ex("It is cheap and useful.", "Nó rẻ và hữu ích.")],
    },
    {
      title: "PHÂN BIỆT BECAUSE VÀ BECAUSE OF",
      body: `Dùng ${purple("because + clause")}, còn ${purple("because of + noun phrase")}.`,
      examples: [ex("I stayed home because it rained.", "Tôi ở nhà vì trời mưa."), ex("I stayed home because of the rain.", "Tôi ở nhà vì cơn mưa.")],
    },
    {
      title: "DÙNG IF VÀ UNLESS ĐÚNG NGHĨA",
      body: `${purple("if")} diễn tả điều kiện xảy ra, ${purple("unless")} mang nghĩa "trừ khi".`,
      examples: [ex("If you study, you improve.", "Nếu bạn học, bạn sẽ tiến bộ."), ex("Don't go out unless you need to.", "Đừng ra ngoài trừ khi bạn cần.")],
    },
  ],
  words: [
    w("and", "và", "CONJUNCTION"),
    w("but", "nhưng", "CONJUNCTION"),
    w("or", "hoặc", "CONJUNCTION"),
    w("so", "vì vậy", "CONJUNCTION"),
    w("because", "bởi vì", "CONJUNCTION"),
    w("because of", "bởi vì (đi với danh từ)", "PHRASE"),
    w("although", "mặc dù", "CONJUNCTION"),
    w("even though", "mặc dù", "CONJUNCTION"),
    w("if", "nếu", "CONJUNCTION"),
    w("unless", "trừ khi", "CONJUNCTION"),
    w("when", "khi", "CONJUNCTION"),
    w("while", "trong khi", "CONJUNCTION"),
    w("before", "trước khi", "CONJUNCTION"),
    w("after", "sau khi", "CONJUNCTION"),
    w("as soon as", "ngay khi", "CONJUNCTION"),
    w("since", "vì; kể từ khi", "CONJUNCTION"),
    w("therefore", "do đó", "LINKER"),
    w("however", "tuy nhiên", "LINKER"),
    w("moreover", "hơn nữa", "LINKER"),
    w("instead", "thay vào đó", "LINKER"),
    w("so that", "để mà", "CONJUNCTION"),
    w("in order to", "để", "PHRASE"),
    w("as well as", "cũng như", "PHRASE"),
    w("either ... or", "hoặc ... hoặc", "PHRASE"),
    w("neither ... nor", "không ... cũng không", "PHRASE"),
  ],
  exercises: buildExercises(50, [
    { question: "We stayed home ___ it was raining.", answer: "because", distractors: ["however", "unless", "instead"] },
    { question: "Choose the connector for contrast.", answer: "however", distractors: ["therefore", "because", "so that"] },
    { question: "___ the rain, the match stopped.", answer: "Because of", distractors: ["Because", "Although", "If"] },
    { question: "Which one means 'trừ khi'?", answer: "unless", distractors: ["if", "when", "after"] },
    { question: "I left early ___ I could catch the bus.", answer: "so that", distractors: ["however", "because of", "either ... or"] },
    { question: "Choose the correct structure.", answer: "because + clause", distractors: ["because + noun", "because of + clause", "because of + verb"] },
    { question: "___ you call me, I will help.", answer: "If", distractors: ["While", "After", "Instead"] },
    { question: "Which pair means 'hoặc ... hoặc'?", answer: "either ... or", distractors: ["as well as", "in order to", "neither ... nor"] },
    { question: "It is expensive, ___ it is durable.", answer: "but", distractors: ["so", "because", "unless"] },
    { question: "What does 'therefore' mean?", answer: "do đó", distractors: ["tuy nhiên", "mặc dù", "trừ khi"] },
  ]),
});

const UNIT_51 = buildEviuUnit(byUnit(51), {
  introVi: "Bộ từ nền tảng về ngày, tháng, mùa và các cụm chỉ lịch trình quen thuộc.",
  structureSections: [
    { label: "Days and weekdays", wordCount: 8 },
    { label: "Months and seasons", wordCount: 9 },
    { label: "Calendar expressions", wordCount: 8 },
  ],
  collocationHtml: `Ba mẫu giới từ thời gian quan trọng là ${purple("on Monday")}, ${purple("in July")}, ${purple("at the weekend")}.`,
  mistakeHtml: `Dùng đúng giới từ thời gian. ${bold("[SAI] in Monday, on July, in 7 o'clock.")}`,
  principles: [
    {
      title: "NHỚ THEO HỆ THỐNG THỜI GIAN",
      body: `Học theo lớp ${purple("thứ - ngày - tháng - mùa")} giúp liên kết và ghi nhớ nhanh hơn.`,
      examples: [ex("My class is on Tuesday.", "Lớp học của tôi vào thứ Ba."), ex("We travel in August.", "Chúng tôi đi du lịch vào tháng Tám.")],
    },
    {
      title: "TỰ ĐỘNG HÓA GIỚI TỪ THỜI GIAN",
      body: `Lỗi giới từ thời gian rất phổ biến ở A1, nên luyện phản xạ với ${purple("on + day")}, ${purple("in + month/season/year")}, ${purple("at + time")}.`,
      examples: [ex("on Friday", "vào thứ Sáu"), ex("in winter", "vào mùa đông"), ex("at night", "vào ban đêm")],
    },
    {
      title: "DÙNG CỤM LỊCH TRONG GIAO TIẾP",
      body: `Các cụm như ${purple("this week")}, ${purple("next week")}, ${purple("at the end of")} rất hữu ích khi hẹn lịch.`,
      examples: [ex("Let's meet next week.", "Hẹn gặp vào tuần sau nhé."), ex("The course ends at the end of June.", "Khóa học kết thúc vào cuối tháng Sáu.")],
    },
  ],
  words: [
    w("Monday", "thứ Hai", "NOUN"),
    w("Tuesday", "thứ Ba", "NOUN"),
    w("Wednesday", "thứ Tư", "NOUN"),
    w("Thursday", "thứ Năm", "NOUN"),
    w("Friday", "thứ Sáu", "NOUN"),
    w("Saturday", "thứ Bảy", "NOUN"),
    w("Sunday", "Chủ nhật", "NOUN"),
    w("weekday", "ngày trong tuần", "NOUN"),
    w("weekend", "cuối tuần", "NOUN"),
    w("January", "tháng Một", "NOUN"),
    w("April", "tháng Tư", "NOUN"),
    w("July", "tháng Bảy", "NOUN"),
    w("October", "tháng Mười", "NOUN"),
    w("December", "tháng Mười Hai", "NOUN"),
    w("spring", "mùa xuân", "NOUN"),
    w("summer", "mùa hè", "NOUN"),
    w("autumn", "mùa thu", "NOUN"),
    w("winter", "mùa đông", "NOUN"),
    w("date", "ngày tháng", "NOUN"),
    w("calendar", "lịch", "NOUN"),
    w("this week", "tuần này", "PHRASE"),
    w("next week", "tuần sau", "PHRASE"),
    w("last month", "tháng trước", "PHRASE"),
    w("at the weekend", "vào cuối tuần", "PHRASE"),
    w("at the end of", "vào cuối (khoảng thời gian)", "PHRASE"),
  ],
  exercises: buildExercises(51, [
    { question: "My class is ___ Monday morning.", answer: "on", distractors: ["in", "at", "for"] },
    { question: "Choose a weekday.", answer: "Friday", distractors: ["summer", "December", "weekend"] },
    { question: "My birthday is ___ July.", answer: "in", distractors: ["on", "at", "for"] },
    { question: "Which phrase means 'tuần sau'?", answer: "next week", distractors: ["last week", "this week", "at the weekend"] },
    { question: "It's usually hot in ___.", answer: "summer", distractors: ["Monday", "October", "weekday"] },
    { question: "Which month is at year-end?", answer: "December", distractors: ["April", "January", "July"] },
    { question: "We usually relax ___ the weekend.", answer: "at", distractors: ["in", "on", "to"] },
    { question: "Choose the correct sentence.", answer: "I have class on Tuesday.", distractors: ["I have class in Tuesday.", "I have class at Tuesday.", "I class Tuesday on."] },
    { question: "Please write today's ___ on the form.", answer: "date", distractors: ["season", "weekday", "monthly"] },
    { question: "What does 'at the end of' mean?", answer: "vào cuối (khoảng thời gian)", distractors: ["vào đầu", "ở giữa", "trong suốt"] },
  ]),
});

const UNIT_52 = buildEviuUnit(byUnit(52), {
  introVi: "Từ chỉ thời gian để diễn tả tần suất, trình tự và điểm thời gian chính xác hơn.",
  structureSections: [
    { label: "Frequency adverbs", wordCount: 9 },
    { label: "Sequence words", wordCount: 8 },
    { label: "Useful time phrases", wordCount: 8 },
  ],
  collocationHtml: `Các cụm ${purple("once a week")}, ${purple("from time to time")}, ${purple("in the meantime")} xuất hiện thường xuyên trong tiếng Anh đời thường.`,
  mistakeHtml: `${purple("still")} thường ở câu khẳng định, ${purple("yet")} thường ở phủ định/câu hỏi. ${bold("[SAI] I still haven't finished yet.")}`,
  principles: [
    {
      title: "DÙNG THANG TẦN SUẤT RÕ RÀNG",
      body: `Thang ${purple("always > usually > often > sometimes > rarely > never")} giúp mô tả thói quen tự nhiên.`,
      examples: [ex("I usually cook at home.", "Tôi thường nấu ăn ở nhà."), ex("He rarely drinks coffee.", "Anh ấy hiếm khi uống cà phê.")],
    },
    {
      title: "LIÊN KẾT TRÌNH TỰ HÀNH ĐỘNG",
      body: `${purple("First, then, next, afterwards, finally")} giúp bài nói có mạch logic.`,
      examples: [ex("First, open the file. Then edit it.", "Đầu tiên, mở tệp ra. Sau đó chỉnh sửa nó.")],
    },
    {
      title: "ĐẶT TRẠNG TỪ ĐÚNG VỊ TRÍ",
      body: `Các trạng từ ${purple("already")}, ${purple("still")}, ${purple("yet")} cần đặt đúng vị trí để tránh sai ngữ pháp và sai nghĩa.`,
      examples: [ex("I have already eaten.", "Tôi đã ăn rồi."), ex("I haven't finished yet.", "Tôi vẫn chưa xong.")],
    },
  ],
  words: [
    w("always", "luôn luôn", "ADVERB"),
    w("usually", "thường xuyên", "ADVERB"),
    w("often", "thường", "ADVERB"),
    w("sometimes", "thỉnh thoảng", "ADVERB"),
    w("occasionally", "đôi khi", "ADVERB"),
    w("rarely", "hiếm khi", "ADVERB"),
    w("never", "không bao giờ", "ADVERB"),
    w("daily", "hằng ngày", "ADVERB"),
    w("weekly", "hằng tuần", "ADVERB"),
    w("monthly", "hằng tháng", "ADVERB"),
    w("yearly", "hằng năm", "ADVERB"),
    w("first", "đầu tiên", "ADVERB"),
    w("then", "sau đó", "ADVERB"),
    w("next", "tiếp theo", "ADVERB"),
    w("afterwards", "sau đó", "ADVERB"),
    w("finally", "cuối cùng", "ADVERB"),
    w("already", "đã (rồi)", "ADVERB"),
    w("still", "vẫn", "ADVERB"),
    w("yet", "chưa; chưa?", "ADVERB"),
    w("soon", "sớm", "ADVERB"),
    w("recently", "gần đây", "ADVERB"),
    w("from time to time", "thỉnh thoảng", "PHRASE"),
    w("once a week", "một lần mỗi tuần", "PHRASE"),
    w("twice a month", "hai lần mỗi tháng", "PHRASE"),
    w("in the meantime", "trong lúc đó", "PHRASE"),
  ],
  exercises: buildExercises(52, [
    { question: "I ___ drink coffee after lunch.", answer: "usually", distractors: ["never", "finally", "yet"] },
    { question: "Which word means 'không bao giờ'?", answer: "never", distractors: ["rarely", "often", "soon"] },
    { question: "___, open the app and sign in.", answer: "First", distractors: ["Yet", "Recently", "Monthly"] },
    { question: "Choose the best sequence word after first.", answer: "then", distractors: ["never", "yearly", "still"] },
    { question: "I have ___ finished my homework.", answer: "already", distractors: ["yet", "rarely", "next"] },
    { question: "Which form is correct?", answer: "I haven't eaten yet.", distractors: ["I haven't yet eaten still.", "I still haven't eaten yet.", "I haven't eaten already."] },
    { question: "She goes jogging ___, every morning.", answer: "daily", distractors: ["monthly", "yearly", "finally"] },
    { question: "What means 'thỉnh thoảng'?", answer: "from time to time", distractors: ["in the meantime", "once a week", "already"] },
    { question: "We meet ___, every Friday evening.", answer: "weekly", distractors: ["soon", "recently", "yet"] },
    { question: "What does 'in the meantime' mean?", answer: "trong lúc đó", distractors: ["ngay lập tức", "không bao giờ", "vào tuần sau"] },
  ]),
});

const UNIT_53 = buildEviuUnit(byUnit(53), {
  introVi: "Từ vựng về địa điểm và vị trí để mô tả đường đi, vị trí sự vật trong đời sống.",
  structureSections: [
    { label: "Public places", wordCount: 9 },
    { label: "Building locations", wordCount: 8 },
    { label: "Position phrases", wordCount: 8 },
  ],
  collocationHtml: `Các cụm ${purple("next to the bank")}, ${purple("in front of the station")}, ${purple("at the corner")} rất phổ biến khi mô tả nơi chốn.`,
  mistakeHtml: `Dùng đúng giới từ nơi chốn. ${bold("[SAI] in the station (khi muốn nói địa điểm chung), at the wall.")}`,
  principles: [
    {
      title: "NẮM ĐỊA ĐIỂM TẦN SUẤT CAO",
      body: `Các danh từ như ${purple("station")}, ${purple("hospital")}, ${purple("market")}, ${purple("library")} xuất hiện liên tục khi hỏi đường.`,
      examples: [ex("The station is near my home.", "Nhà ga ở gần nhà tôi."), ex("Let's meet at the library.", "Mình gặp nhau ở thư viện nhé.")],
    },
    {
      title: "MÔ TẢ VỊ TRÍ TƯƠNG ĐỐI",
      body: `Dùng ${purple("next to")}, ${purple("between")}, ${purple("opposite")}, ${purple("behind")} để mô tả quan hệ giữa hai vị trí.`,
      examples: [ex("The cafe is next to the bank.", "Quán cà phê nằm cạnh ngân hàng."), ex("The school is opposite the park.", "Trường học đối diện công viên.")],
    },
    {
      title: "LUYỆN CỤM HOÀN CHỈNH",
      body: `Nên học cụm đầy đủ như ${purple("at the corner")}, ${purple("on the left")} thay vì học từ lẻ để nói đường đi rõ ràng hơn.`,
      examples: [ex("Turn left at the corner.", "Rẽ trái ở góc đường."), ex("The exit is on the right.", "Lối ra ở bên phải.")],
    },
  ],
  words: [
    w("station", "nhà ga", "NOUN"),
    w("airport", "sân bay", "NOUN"),
    w("hospital", "bệnh viện", "NOUN"),
    w("pharmacy", "nhà thuốc", "NOUN"),
    w("supermarket", "siêu thị", "NOUN"),
    w("market", "chợ", "NOUN"),
    w("library", "thư viện", "NOUN"),
    w("museum", "bảo tàng", "NOUN"),
    w("post office", "bưu điện", "NOUN"),
    w("bank", "ngân hàng", "NOUN"),
    w("corner", "góc đường; góc phòng", "NOUN"),
    w("entrance", "lối vào", "NOUN"),
    w("exit", "lối ra", "NOUN"),
    w("ground floor", "tầng trệt", "NOUN"),
    w("upstairs", "trên lầu", "ADVERB"),
    w("downstairs", "tầng dưới", "ADVERB"),
    w("next to", "bên cạnh", "PREPOSITION"),
    w("between", "ở giữa", "PREPOSITION"),
    w("opposite", "đối diện", "PREPOSITION"),
    w("in front of", "phía trước", "PREPOSITION"),
    w("behind", "phía sau", "PREPOSITION"),
    w("near", "gần", "PREPOSITION"),
    w("far from", "xa", "PREPOSITION"),
    w("at the corner", "ở góc đường", "PHRASE"),
    w("on the left", "bên trái", "PHRASE"),
  ],
  exercises: buildExercises(53, [
    { question: "You can buy medicine at a ___.", answer: "pharmacy", distractors: ["museum", "corner", "station"] },
    { question: "Which phrase means 'đối diện'?", answer: "opposite", distractors: ["between", "near", "behind"] },
    { question: "The cafe is ___ the bank.", answer: "next to", distractors: ["between of", "in front", "far to"] },
    { question: "Choose the correct sentence.", answer: "The hospital is near my house.", distractors: ["The hospital near is my house.", "The hospital is house near my.", "Hospital is near at my house."] },
    { question: "Turn right ___ the corner.", answer: "at", distractors: ["in", "on", "for"] },
    { question: "Which one is a public place?", answer: "post office", distractors: ["upstairs", "behind", "left"] },
    { question: "The meeting room is ___. Go up the stairs.", answer: "upstairs", distractors: ["downstairs", "near", "behind"] },
    { question: "What means 'ở giữa'?", answer: "between", distractors: ["opposite", "near", "in front of"] },
    { question: "My office is ___ home, so I commute by bus.", answer: "far from", distractors: ["next to", "between", "on"] },
    { question: "What does 'entrance' mean?", answer: "lối vào", distractors: ["lối ra", "góc đường", "tầng trệt"] },
  ]),
});

const UNIT_54 = buildEviuUnit(byUnit(54), {
  introVi: "Trạng từ chỉ cách thức giúp mô tả hành động rõ hơn và điều chỉnh sắc thái giao tiếp.",
  structureSections: [
    { label: "Core manner adverbs", wordCount: 9 },
    { label: "Attitude and intensity", wordCount: 8 },
    { label: "Useful chunks", wordCount: 8 },
  ],
  collocationHtml: `Ba collocation nên luyện phản xạ là ${purple("speak clearly")}, ${purple("drive carefully")}, ${purple("work hard")}.`,
  mistakeHtml: `Phân biệt tính từ và trạng từ. ${bold("[SAI] He drives careful.")}`,
  principles: [
    {
      title: "TRẠNG TỪ BỔ NGHĨA CHO ĐỘNG TỪ",
      body: `Nhiều trạng từ có đuôi ${purple("-ly")}, giúp diễn tả cách hành động được thực hiện.`,
      examples: [ex("She speaks clearly.", "Cô ấy nói rõ ràng."), ex("Please close the door quietly.", "Làm ơn đóng cửa nhẹ nhàng.")],
    },
    {
      title: "MỘT SỐ TRẠNG TỪ KHÔNG CÓ -LY",
      body: `Các từ ${purple("fast")}, ${purple("hard")}, ${purple("late")}, ${purple("early")} là dạng đặc biệt thường gặp và dễ nhầm.`,
      examples: [ex("He runs fast.", "Anh ấy chạy nhanh."), ex("They work hard.", "Họ làm việc chăm chỉ.")],
    },
    {
      title: "DÙNG TRẠNG TỪ ĐỂ ĐIỀU CHỈNH MỨC ĐỘ",
      body: `Các từ ${purple("quite")}, ${purple("really")}, ${purple("almost")}, ${purple("absolutely")} giúp tăng/giảm độ nhấn khi giao tiếp.`,
      examples: [ex("I'm quite tired.", "Tôi khá mệt."), ex("That's absolutely correct.", "Điều đó hoàn toàn chính xác.")],
    },
  ],
  words: [
    w("slowly", "một cách chậm rãi", "ADVERB"),
    w("quickly", "nhanh chóng", "ADVERB"),
    w("carefully", "cẩn thận", "ADVERB"),
    w("easily", "dễ dàng", "ADVERB"),
    w("clearly", "rõ ràng", "ADVERB"),
    w("quietly", "nhẹ nhàng; yên lặng", "ADVERB"),
    w("loudly", "to tiếng", "ADVERB"),
    w("politely", "lịch sự", "ADVERB"),
    w("rudely", "thô lỗ", "ADVERB"),
    w("happily", "vui vẻ", "ADVERB"),
    w("sadly", "buồn bã", "ADVERB"),
    w("angrily", "giận dữ", "ADVERB"),
    w("badly", "tệ", "ADVERB"),
    w("well", "tốt", "ADVERB"),
    w("fast", "nhanh", "ADVERB"),
    w("hard", "chăm chỉ; mạnh", "ADVERB"),
    w("late", "muộn", "ADVERB"),
    w("early", "sớm", "ADVERB"),
    w("quite", "khá", "ADVERB"),
    w("really", "thực sự", "ADVERB"),
    w("almost", "hầu như", "ADVERB"),
    w("completely", "hoàn toàn", "ADVERB"),
    w("absolutely", "chắc chắn; tuyệt đối", "ADVERB"),
    w("in a hurry", "vội vàng", "PHRASE"),
    w("step by step", "từng bước một", "PHRASE"),
  ],
  exercises: buildExercises(54, [
    { question: "Please speak ___ so everyone can hear.", answer: "clearly", distractors: ["clear", "clarity", "clearness"] },
    { question: "Which sentence is correct?", answer: "He drives carefully.", distractors: ["He drives careful.", "He careful drives.", "He is drives careful."] },
    { question: "She works very ___ and always meets deadlines.", answer: "hard", distractors: ["hardly", "hardness", "harder"] },
    { question: "Choose opposite pair.", answer: "quietly / loudly", distractors: ["well / badly", "early / late", "quickly / slowly"] },
    { question: "I arrived ___, so the shop was still closed.", answer: "early", distractors: ["rudely", "quietly", "hard"] },
    { question: "Which one means 'vội vàng'?", answer: "in a hurry", distractors: ["step by step", "completely", "absolutely"] },
    { question: "He answered ___ and hurt people.", answer: "rudely", distractors: ["politely", "happily", "clearly"] },
    { question: "What means 'hoàn toàn'?", answer: "completely", distractors: ["almost", "quite", "quickly"] },
    { question: "We should learn this ___ to avoid mistakes.", answer: "step by step", distractors: ["in a hurry", "all at once", "for free"] },
    { question: "What does 'well' mean here?", answer: "tốt", distractors: ["muộn", "chậm", "ồn ào"] },
  ]),
});

const UNIT_55 = buildEviuUnit(byUnit(55), {
  introVi: "Danh từ không đếm được thường gây nhầm lẫn cho người học; unit này tập trung dùng đúng số lượng và mạo từ.",
  structureSections: [
    { label: "Food and drink nouns", wordCount: 9 },
    { label: "Abstract nouns", wordCount: 8 },
    { label: "Quantity expressions", wordCount: 8 },
  ],
  collocationHtml: `Các cấu trúc ${purple("a piece of advice")}, ${purple("a bottle of water")}, ${purple("a bit of information")} rất quan trọng với danh từ không đếm được.`,
  mistakeHtml: `Không thêm "s" bừa bãi với danh từ không đếm được. ${bold("[SAI] informations, advices, furnitures.")}`,
  principles: [
    {
      title: "NHẬN DIỆN DANH TỪ KHÔNG ĐẾM ĐƯỢC",
      body: `Nhiều từ quen thuộc như ${purple("rice")}, ${purple("money")}, ${purple("music")}, ${purple("traffic")} không dùng số nhiều thông thường.`,
      examples: [ex("I need some information.", "Tôi cần một ít thông tin."), ex("Music helps me relax.", "Âm nhạc giúp tôi thư giãn.")],
    },
    {
      title: "DÙNG LƯỢNG TỪ THAY VÌ SỐ ĐẾM",
      body: `Khi cần định lượng, dùng ${purple("a piece of")}, ${purple("a cup of")}, ${purple("a bottle of")}, ${purple("some")}, ${purple("a little")}.`,
      examples: [ex("a piece of advice", "một lời khuyên"), ex("a cup of tea", "một tách trà")],
    },
    {
      title: "PHÂN BIỆT VỚI DANH TỪ ĐẾM ĐƯỢC",
      body: `Ví dụ ${purple("hair")} thường không đếm được khi nói chung, nhưng ${purple("a hair")} có thể chỉ một sợi tóc.`,
      examples: [ex("Her hair is long.", "Tóc cô ấy dài."), ex("I found a hair in my soup.", "Tôi tìm thấy một sợi tóc trong bát súp.")],
    },
  ],
  words: [
    w("water", "nước", "UNCOUNTABLE NOUN"),
    w("milk", "sữa", "UNCOUNTABLE NOUN"),
    w("rice", "gạo; cơm", "UNCOUNTABLE NOUN"),
    w("bread", "bánh mì", "UNCOUNTABLE NOUN"),
    w("sugar", "đường", "UNCOUNTABLE NOUN"),
    w("salt", "muối", "UNCOUNTABLE NOUN"),
    w("coffee", "cà phê", "UNCOUNTABLE NOUN"),
    w("tea", "trà", "UNCOUNTABLE NOUN"),
    w("cheese", "phô mai", "UNCOUNTABLE NOUN"),
    w("money", "tiền", "UNCOUNTABLE NOUN"),
    w("information", "thông tin", "UNCOUNTABLE NOUN"),
    w("advice", "lời khuyên", "UNCOUNTABLE NOUN"),
    w("news", "tin tức", "UNCOUNTABLE NOUN"),
    w("furniture", "đồ nội thất", "UNCOUNTABLE NOUN"),
    w("equipment", "thiết bị", "UNCOUNTABLE NOUN"),
    w("luggage", "hành lý", "UNCOUNTABLE NOUN"),
    w("traffic", "giao thông", "UNCOUNTABLE NOUN"),
    w("homework", "bài tập về nhà", "UNCOUNTABLE NOUN"),
    w("work", "công việc", "UNCOUNTABLE NOUN"),
    w("music", "âm nhạc", "UNCOUNTABLE NOUN"),
    w("a piece of", "một mẩu; một phần", "QUANTITY PHRASE"),
    w("a bit of", "một ít", "QUANTITY PHRASE"),
    w("a bottle of", "một chai", "QUANTITY PHRASE"),
    w("a cup of", "một tách", "QUANTITY PHRASE"),
    w("a loaf of", "một ổ (bánh mì)", "QUANTITY PHRASE"),
  ],
  exercises: buildExercises(55, [
    { question: "I need some ___ about this course.", answer: "information", distractors: ["informations", "advices", "furnitures"] },
    { question: "Which is uncountable?", answer: "advice", distractors: ["apple", "chair", "book"] },
    { question: "Can I have a ___ of water?", answer: "bottle", distractors: ["piece", "loaf", "news"] },
    { question: "Choose the correct form.", answer: "some furniture", distractors: ["a furniture", "many furnitures", "an equipment"] },
    { question: "I listened to relaxing ___ last night.", answer: "music", distractors: ["musics", "song", "instrument"] },
    { question: "Which phrase is correct?", answer: "a piece of advice", distractors: ["an advice", "a advice", "advice piece"] },
    { question: "We have too much ___ in the city center.", answer: "traffic", distractors: ["traffics", "carses", "roads"] },
    { question: "Choose the right sentence.", answer: "She gave me good advice.", distractors: ["She gave me good advices.", "She gave me an advice.", "She gave advice me."] },
    { question: "I bought a ___ of bread.", answer: "loaf", distractors: ["bottle", "piece", "cup"] },
    { question: "What does 'luggage' mean?", answer: "hành lý", distractors: ["lối đi", "nội thất", "giao thông"] },
  ]),
});

const UNIT_56 = buildEviuUnit(byUnit(56), {
  introVi: "Nhóm tính từ thông dụng để mô tả người, sự vật và trải nghiệm theo hướng tích cực/tiêu cực.",
  structureSections: [
    { label: "Positive adjectives", wordCount: 9 },
    { label: "Negative adjectives", wordCount: 8 },
    { label: "Intensity and opinion", wordCount: 8 },
  ],
  collocationHtml: `Các cụm ${purple("really useful")}, ${purple("quite difficult")}, ${purple("absolutely wonderful")} giúp diễn đạt linh hoạt hơn.`,
  mistakeHtml: `Chọn tính từ đúng ngữ cảnh và sắc thái. ${bold("[SAI] This food is amazingly bad good nice all together.")}`,
  principles: [
    {
      title: "HỌC THEO CẶP ĐỐI NGHĨA",
      body: `Luyện theo cặp như ${purple("good/bad")}, ${purple("easy/difficult")}, ${purple("cheap/expensive")} để phản xạ nhanh.`,
      examples: [ex("This task is easy.", "Nhiệm vụ này dễ."), ex("That one is difficult.", "Cái kia thì khó.")],
    },
    {
      title: "PHÂN BIỆT TÍNH TỪ KHÁCH QUAN VÀ CHỦ QUAN",
      body: `Một số từ mô tả thực tế như ${purple("large, small")}, số khác mang ý kiến cá nhân như ${purple("amazing, boring")}.`,
      examples: [ex("The room is small.", "Căn phòng nhỏ."), ex("The film was boring.", "Bộ phim thật chán.")],
    },
    {
      title: "TĂNG GIẢM MỨC ĐỘ BẰNG TỪ BỔ NGHĨA",
      body: `Dùng ${purple("very")}, ${purple("quite")}, ${purple("really")}, ${purple("absolutely")} để điều chỉnh mức độ của tính từ.`,
      examples: [ex("It's very useful.", "Nó rất hữu ích."), ex("The concert was absolutely amazing.", "Buổi hòa nhạc tuyệt vời ngoài mong đợi.")],
    },
  ],
  words: [
    w("good", "tốt", "ADJECTIVE"),
    w("nice", "dễ chịu; đẹp", "ADJECTIVE"),
    w("useful", "hữu ích", "ADJECTIVE"),
    w("helpful", "hay giúp đỡ", "ADJECTIVE"),
    w("friendly", "thân thiện", "ADJECTIVE"),
    w("polite", "lịch sự", "ADJECTIVE"),
    w("honest", "trung thực", "ADJECTIVE"),
    w("clean", "sạch", "ADJECTIVE"),
    w("comfortable", "thoải mái", "ADJECTIVE"),
    w("bad", "tệ", "ADJECTIVE"),
    w("awful", "tồi tệ", "ADJECTIVE"),
    w("useless", "vô dụng", "ADJECTIVE"),
    w("rude", "thô lỗ", "ADJECTIVE"),
    w("dirty", "bẩn", "ADJECTIVE"),
    w("noisy", "ồn ào", "ADJECTIVE"),
    w("boring", "chán", "ADJECTIVE"),
    w("difficult", "khó", "ADJECTIVE"),
    w("expensive", "đắt", "ADJECTIVE"),
    w("cheap", "rẻ", "ADJECTIVE"),
    w("amazing", "tuyệt vời", "ADJECTIVE"),
    w("terrible", "kinh khủng", "ADJECTIVE"),
    w("quite", "khá", "INTENSIFIER"),
    w("very", "rất", "INTENSIFIER"),
    w("really", "thực sự", "INTENSIFIER"),
    w("absolutely", "hoàn toàn", "INTENSIFIER"),
  ],
  exercises: buildExercises(56, [
    { question: "This app is very ___ for students.", answer: "useful", distractors: ["useless", "dirty", "noisy"] },
    { question: "Choose the opposite of friendly.", answer: "rude", distractors: ["polite", "helpful", "honest"] },
    { question: "The hotel was clean and ___.", answer: "comfortable", distractors: ["awful", "dirty", "terrible"] },
    { question: "Which adjective means 'đắt'?", answer: "expensive", distractors: ["cheap", "difficult", "boring"] },
    { question: "The movie was so ___ that I almost slept.", answer: "boring", distractors: ["amazing", "helpful", "honest"] },
    { question: "Choose a positive adjective.", answer: "friendly", distractors: ["awful", "dirty", "terrible"] },
    { question: "This lesson is ___ difficult, but I can do it.", answer: "quite", distractors: ["absolutely", "awful", "cheap"] },
    { question: "Which one is strongest for emphasis?", answer: "absolutely", distractors: ["quite", "very", "clean"] },
    { question: "The ticket is too ___. I can't buy it.", answer: "expensive", distractors: ["cheap", "nice", "useful"] },
    { question: "What does 'helpful' mean?", answer: "hay giúp đỡ", distractors: ["khó chịu", "ồn ào", "đắt đỏ"] },
  ]),
});

const UNIT_57 = buildEviuUnit(byUnit(57), {
  introVi: "Học từ đi với giới từ theo cụm cố định để tránh lỗi dịch từng từ.",
  structureSections: [
    { label: "Adjective + preposition", wordCount: 9 },
    { label: "Verb + preposition", wordCount: 8 },
    { label: "Useful fixed phrases", wordCount: 8 },
  ],
  collocationHtml: `Các cụm ${purple("afraid of")}, ${purple("interested in")}, ${purple("good at")} là nhóm cơ bản nhưng rất dễ sai.`,
  mistakeHtml: `Không đổi giới từ theo cảm giác. ${bold("[SAI] depend of, interested on, good in math.")}`,
  principles: [
    {
      title: "HỌC THEO CẶP CỐ ĐỊNH",
      body: `Nhiều từ bắt buộc đi với một giới từ cụ thể, nên ghi nhớ nguyên cụm như ${purple("afraid of")}, ${purple("good at")}.`,
      examples: [ex("I'm interested in music.", "Tôi hứng thú với âm nhạc."), ex("She is good at math.", "Cô ấy giỏi toán.")],
    },
    {
      title: "ƯU TIÊN CỤM TẦN SUẤT CAO",
      body: `Bắt đầu với nhóm dùng thường xuyên trong nói và viết hàng ngày như ${purple("depend on")}, ${purple("wait for")}.`,
      examples: [ex("I'm afraid of dogs.", "Tôi sợ chó."), ex("It depends on the weather.", "Việc đó phụ thuộc vào thời tiết.")],
    },
    {
      title: "TẠO CÂU MẪU NGẮN ĐỂ NHỚ",
      body: `Mỗi cụm nên có một câu mẫu cá nhân hóa, ví dụ với ${purple("proud of")} hoặc ${purple("apologize for")}, để nhớ lâu hơn.`,
      examples: [ex("I'm proud of my team.", "Tôi tự hào về đội của mình."), ex("He apologized for being late.", "Anh ấy xin lỗi vì đến muộn.")],
    },
  ],
  words: [
    w("afraid of", "sợ", "COLLOCATION"),
    w("interested in", "hứng thú với", "COLLOCATION"),
    w("good at", "giỏi về", "COLLOCATION"),
    w("bad at", "kém về", "COLLOCATION"),
    w("famous for", "nổi tiếng vì", "COLLOCATION"),
    w("different from", "khác với", "COLLOCATION"),
    w("similar to", "tương tự", "COLLOCATION"),
    w("full of", "đầy", "COLLOCATION"),
    w("proud of", "tự hào về", "COLLOCATION"),
    w("depend on", "phụ thuộc vào", "COLLOCATION"),
    w("belong to", "thuộc về", "COLLOCATION"),
    w("wait for", "chờ", "COLLOCATION"),
    w("pay for", "trả tiền cho", "COLLOCATION"),
    w("ask for", "xin; yêu cầu", "COLLOCATION"),
    w("listen to", "lắng nghe", "COLLOCATION"),
    w("look at", "nhìn vào", "COLLOCATION"),
    w("think about", "nghĩ về", "COLLOCATION"),
    w("worry about", "lo lắng về", "COLLOCATION"),
    w("talk to", "nói chuyện với", "COLLOCATION"),
    w("speak to", "nói với", "COLLOCATION"),
    w("apologize for", "xin lỗi vì", "COLLOCATION"),
    w("thanks for", "cảm ơn vì", "COLLOCATION"),
    w("in love with", "đang yêu", "COLLOCATION"),
    w("on time", "đúng giờ", "PHRASE"),
    w("at risk of", "có nguy cơ", "PHRASE"),
  ],
  exercises: buildExercises(57, [
    { question: "I'm really interested ___ music.", answer: "in", distractors: ["on", "at", "for"] },
    { question: "Which collocation means 'giỏi về'?", answer: "good at", distractors: ["good in", "good on", "good for"] },
    { question: "This result depends ___ your effort.", answer: "on", distractors: ["of", "at", "to"] },
    { question: "Choose the correct phrase.", answer: "afraid of", distractors: ["afraid from", "afraid to", "afraid on"] },
    { question: "Please listen ___ the instructions.", answer: "to", distractors: ["at", "for", "in"] },
    { question: "Which one means 'thuộc về'?", answer: "belong to", distractors: ["belong with", "belong on", "belong for"] },
    { question: "I'm proud ___ my brother.", answer: "of", distractors: ["in", "to", "with"] },
    { question: "Choose the natural sentence.", answer: "Thank you for your help.", distractors: ["Thank you to your help.", "Thank you in your help.", "Thank you at your help."] },
    { question: "She apologized ___ being late.", answer: "for", distractors: ["to", "at", "about"] },
    { question: "What does 'on time' mean?", answer: "đúng giờ", distractors: ["trễ giờ", "đúng chỗ", "vội vàng"] },
  ]),
});

const UNIT_58 = buildEviuUnit(byUnit(58), {
  introVi: "Tiền tố giúp đoán nghĩa từ mới nhanh hơn và mở rộng vốn từ theo họ từ.",
  structureSections: [
    { label: "Negative prefixes", wordCount: 9 },
    { label: "Repetition and degree", wordCount: 8 },
    { label: "Common prefix families", wordCount: 8 },
  ],
  collocationHtml: `Ba tiền tố năng suất cao ở trình độ sơ cấp là ${purple("un-")}, ${purple("re-")}, ${purple("dis-")}.`,
  mistakeHtml: `Không phải từ nào cũng ghép tiền tố tùy ý. ${bold("[SAI] unagree, dispossible, reright.")}`,
  principles: [
    {
      title: "TIỀN TỐ ĐỔI NGHĨA GỐC",
      body: `Nhiều tiền tố thêm vào đầu từ để đảo nghĩa hoặc thêm sắc thái mới, ví dụ ${purple("un-")}, ${purple("im-")}, ${purple("dis-")}.`,
      examples: [ex("happy → unhappy", "vui → không vui"), ex("possible → impossible", "có thể → không thể")],
    },
    {
      title: "TIỀN TỐ MANG Ý LẶP LẠI",
      body: `${purple("re-")} thường mang nghĩa làm lại hoặc quay lại.`,
      examples: [ex("rewrite", "viết lại"), ex("reopen", "mở lại")],
    },
    {
      title: "HỌC THEO HỌ TỪ PHỔ BIẾN",
      body: `Nên học một gốc từ với nhiều biến thể có tiền tố để nhớ có hệ thống, như ${purple("agree / disagree")} hoặc ${purple("active / inactive")}.`,
      examples: [ex("agree / disagree", "đồng ý / không đồng ý"), ex("active / inactive", "hoạt động / không hoạt động")],
    },
  ],
  words: [
    w("prefix", "tiền tố", "NOUN"),
    w("unhappy", "không vui", "ADJECTIVE"),
    w("unfair", "không công bằng", "ADJECTIVE"),
    w("unclear", "không rõ ràng", "ADJECTIVE"),
    w("unknown", "không biết", "ADJECTIVE"),
    w("impossible", "không thể", "ADJECTIVE"),
    w("impatient", "thiếu kiên nhẫn", "ADJECTIVE"),
    w("illegal", "bất hợp pháp", "ADJECTIVE"),
    w("irregular", "không đều; bất thường", "ADJECTIVE"),
    w("disagree", "không đồng ý", "VERB"),
    w("dislike", "không thích", "VERB"),
    w("disconnect", "ngắt kết nối", "VERB"),
    w("misunderstand", "hiểu nhầm", "VERB"),
    w("mispronounce", "phát âm sai", "VERB"),
    w("misbehave", "cư xử sai", "VERB"),
    w("rewrite", "viết lại", "VERB"),
    w("recheck", "kiểm tra lại", "VERB"),
    w("rebuild", "xây lại", "VERB"),
    w("reopen", "mở lại", "VERB"),
    w("overwork", "làm việc quá sức", "VERB"),
    w("overcook", "nấu quá chín", "VERB"),
    w("underpaid", "bị trả lương thấp", "ADJECTIVE"),
    w("underestimate", "đánh giá thấp", "VERB"),
    w("prepaid", "trả trước", "ADJECTIVE"),
    w("preview", "xem trước", "NOUN"),
  ],
  exercises: buildExercises(58, [
    { question: "The opposite of happy is ___.", answer: "unhappy", distractors: ["rehappy", "dishappy", "inhappy"] },
    { question: "Which prefix often means 'again'?", answer: "re-", distractors: ["un-", "mis-", "dis-"] },
    { question: "Please ___ your answer before submitting.", answer: "recheck", distractors: ["mischeck", "uncheck", "overcheck"] },
    { question: "Which word means 'hiểu nhầm'?", answer: "misunderstand", distractors: ["disunderstand", "reunderstand", "ununderstand"] },
    { question: "He tends to ___ and gets very tired.", answer: "overwork", distractors: ["underwork", "rework", "miswork"] },
    { question: "Choose the opposite of agree.", answer: "disagree", distractors: ["reagree", "unagree", "misagree"] },
    { question: "This rule is ___. You must stop.", answer: "illegal", distractors: ["legal", "regular", "clear"] },
    { question: "Which word means 'trả trước'?", answer: "prepaid", distractors: ["repaid", "underpaid", "mispaid"] },
    { question: "If you speak too fast, you may ___ words.", answer: "mispronounce", distractors: ["repronounce", "unpronounce", "overpronounce"] },
    { question: "What does 'underestimate' mean?", answer: "đánh giá thấp", distractors: ["đánh giá cao", "kiểm tra lại", "xem trước"] },
  ]),
});

const UNIT_59 = buildEviuUnit(byUnit(59), {
  introVi: "Hậu tố giúp biến đổi từ loại và mở rộng diễn đạt từ một gốc từ quen thuộc.",
  structureSections: [
    { label: "Noun suffixes", wordCount: 9 },
    { label: "Adjective suffixes", wordCount: 8 },
    { label: "Adverb and verb forms", wordCount: 8 },
  ],
  collocationHtml: `Các hậu tố năng suất cao ở trình độ elementary là ${purple("-er")}, ${purple("-ful")}, ${purple("-ly")}.`,
  mistakeHtml: `Không phải mọi từ đều thêm cùng một hậu tố. ${bold("[SAI] beautyful, quickful, teachly.")}`,
  principles: [
    {
      title: "HẬU TỐ ĐỔI TỪ LOẠI",
      body: `Từ gốc có thể chuyển thành danh từ, tính từ hoặc trạng từ bằng hậu tố phù hợp như ${purple("-er")}, ${purple("-ful")}, ${purple("-ly")}.`,
      examples: [ex("teach → teacher", "dạy → giáo viên"), ex("care → careful", "quan tâm → cẩn thận")],
    },
    {
      title: "NHÓM HẬU TỐ DANH TỪ THÔNG DỤNG",
      body: `${purple("-er/-or")} chỉ người làm việc; ${purple("-tion/-ment")} chỉ quá trình hoặc kết quả.`,
      examples: [ex("act → actor", "diễn xuất → diễn viên"), ex("develop → development", "phát triển → sự phát triển")],
    },
    {
      title: "HẬU TỐ TRẠNG TỪ -LY",
      body: `Nhiều tính từ đổi thành trạng từ bằng ${purple("-ly")}, nhưng vẫn cần chú ý ngoại lệ.`,
      examples: [ex("quick → quickly", "nhanh → một cách nhanh chóng"), ex("happy → happily", "vui vẻ → một cách vui vẻ")],
    },
  ],
  words: [
    w("suffix", "hậu tố", "NOUN"),
    w("teacher", "giáo viên", "NOUN"),
    w("writer", "nhà văn; người viết", "NOUN"),
    w("worker", "công nhân; người làm việc", "NOUN"),
    w("actor", "diễn viên nam", "NOUN"),
    w("singer", "ca sĩ", "NOUN"),
    w("driver", "tài xế", "NOUN"),
    w("development", "sự phát triển", "NOUN"),
    w("agreement", "sự đồng thuận", "NOUN"),
    w("discussion", "cuộc thảo luận", "NOUN"),
    w("decision", "quyết định", "NOUN"),
    w("careful", "cẩn thận", "ADJECTIVE"),
    w("careless", "bất cẩn", "ADJECTIVE"),
    w("helpful", "hữu ích", "ADJECTIVE"),
    w("hopeless", "vô vọng", "ADJECTIVE"),
    w("friendly", "thân thiện", "ADJECTIVE"),
    w("rainy", "mưa nhiều", "ADJECTIVE"),
    w("sunny", "nhiều nắng", "ADJECTIVE"),
    w("daily", "hằng ngày", "ADJECTIVE"),
    w("quickly", "nhanh chóng", "ADVERB"),
    w("slowly", "chậm rãi", "ADVERB"),
    w("happily", "vui vẻ", "ADVERB"),
    w("beautifully", "một cách đẹp", "ADVERB"),
    w("modernize", "hiện đại hóa", "VERB"),
    w("simplify", "đơn giản hóa", "VERB"),
  ],
  exercises: buildExercises(59, [
    { question: "A person who teaches is a ___.", answer: "teacher", distractors: ["teaching", "teachful", "teachly"] },
    { question: "Which suffix often makes adverbs?", answer: "-ly", distractors: ["-er", "-ful", "-tion"] },
    { question: "He drives ___.", answer: "carefully", distractors: ["careful", "careless", "care"] },
    { question: "Opposite of careful is ___.", answer: "careless", distractors: ["careful", "hopeless", "friendly"] },
    { question: "We reached a good ___.", answer: "agreement", distractors: ["agreeful", "agreeer", "agreeing"] },
    { question: "Which word is a noun ending in -tion?", answer: "discussion", distractors: ["discuss", "discussive", "discussly"] },
    { question: "The weather is ___ today.", answer: "sunny", distractors: ["sun", "sunly", "sunnily"] },
    { question: "Which word means 'đơn giản hóa'?", answer: "simplify", distractors: ["simplity", "simpled", "simpler"] },
    { question: "She sang ___.", answer: "beautifully", distractors: ["beautiful", "beauty", "beautify"] },
    { question: "What does 'development' mean?", answer: "sự phát triển", distractors: ["sự chậm lại", "sự quyết định", "sự tranh luận"] },
  ]),
});

const UNIT_60 = buildEviuUnit(byUnit(60), {
  introVi: "Unit tổng hợp các cặp từ dễ nhầm ở trình độ cơ bản và cách phân biệt thực tế.",
  structureSections: [
    { label: "Everyday confusing pairs", wordCount: 9 },
    { label: "Grammar-sensitive pairs", wordCount: 8 },
    { label: "Meaning contrasts", wordCount: 8 },
  ],
  collocationHtml: `Các cặp ${purple("borrow vs lend")}, ${purple("say vs tell")}, ${purple("job vs work")} là lỗi rất thường gặp ở trình độ cơ bản.`,
  mistakeHtml: `Nên học theo cặp + ví dụ thật để tránh dịch từng từ. ${bold("[SAI] borrow me, tell hello, I have many works.")}`,
  principles: [
    {
      title: "PHÂN BIỆT BẰNG VAI TRÒ TRONG CÂU",
      body: `Nhiều cặp khác nhau ở chủ thể hành động, ví dụ ${purple("borrow/lend")}.`,
      examples: [ex("Can I borrow your pen?", "Mình mượn bút của bạn được không?"), ex("Can you lend me your pen?", "Bạn cho mình mượn bút được không?")],
    },
    {
      title: "PHÂN BIỆT BẰNG MẪU NGỮ PHÁP",
      body: `Một số cặp đi với cấu trúc khác nhau như ${purple("say something")} và ${purple("tell someone something")}.`,
      examples: [ex("She said hello.", "Cô ấy nói \"xin chào\"."), ex("She told me a story.", "Cô ấy kể cho tôi một câu chuyện.")],
    },
    {
      title: "ÔN BẰNG CÂU ĐỐI CHIẾU NGẮN",
      body: `Viết câu đôi cho mỗi cặp từ như ${purple("miss/lose")} hoặc ${purple("bring/take")} sẽ giúp tránh lỗi tái diễn trong nói và viết.`,
      examples: [
        ex("I missed the bus. / I lost my phone.", "Tôi lỡ chuyến xe buýt. / Tôi làm mất điện thoại."),
        ex("Bring it here. / Take it there.", "Mang nó lại đây. / Mang nó qua đó."),
      ],
    },
  ],
  words: [
    w("borrow", "mượn", "VERB"),
    w("lend", "cho mượn", "VERB"),
    w("say", "nói (nội dung)", "VERB"),
    w("tell", "nói/kể với ai", "VERB"),
    w("speak", "nói (ngôn ngữ/chung)", "VERB"),
    w("talk", "trò chuyện", "VERB"),
    w("job", "việc làm; nghề", "NOUN"),
    w("work", "công việc", "NOUN/VERB"),
    w("fun", "vui", "NOUN/ADJECTIVE"),
    w("funny", "hài hước; buồn cười", "ADJECTIVE"),
    w("remember", "nhớ", "VERB"),
    w("remind", "nhắc ai nhớ", "VERB"),
    w("look", "nhìn", "VERB"),
    w("see", "thấy", "VERB"),
    w("listen", "lắng nghe", "VERB"),
    w("hear", "nghe thấy", "VERB"),
    w("bring", "mang đến đây", "VERB"),
    w("take", "mang đi nơi khác", "VERB"),
    w("lose", "làm mất", "VERB"),
    w("miss", "nhỡ; bỏ lỡ", "VERB"),
    w("few", "ít (đếm được)", "DETERMINER"),
    w("little", "ít (không đếm được)", "DETERMINER"),
    w("some", "một vài; một ít", "DETERMINER"),
    w("any", "bất kỳ; chút nào", "DETERMINER"),
    w("other", "khác", "ADJECTIVE"),
  ],
  exercises: buildExercises(60, [
    { question: "Can I ___ your bike for one day?", answer: "borrow", distractors: ["lend", "remind", "miss"] },
    { question: "Which verb means 'cho mượn'?", answer: "lend", distractors: ["borrow", "lose", "take"] },
    { question: "She ___ me that the meeting was canceled.", answer: "told", distractors: ["said", "spoke", "talked"] },
    { question: "Choose correct pair.", answer: "say something / tell someone", distractors: ["say someone / tell something", "speak someone / talk something", "tell language / say person"] },
    { question: "I ___ my keys yesterday.", answer: "lost", distractors: ["missed", "heard", "borrowed"] },
    { question: "Which sentence is correct?", answer: "I missed the bus.", distractors: ["I lost the bus.", "I borrow the bus.", "I remind the bus."] },
    { question: "Please ___ this box to the kitchen.", answer: "take", distractors: ["bring", "hear", "listen"] },
    { question: "What means 'hài hước'?", answer: "funny", distractors: ["fun", "other", "some"] },
    { question: "I have ___ friends in this city.", answer: "few", distractors: ["little", "any", "much"] },
    { question: "What does 'remind' mean?", answer: "nhắc ai nhớ", distractors: ["nhớ", "nhìn thấy", "nghe thấy"] },
  ]),
});

export const EVIU_UNITS_46_60: VocabularyUnit[] = [
  UNIT_46,
  UNIT_47,
  UNIT_48,
  UNIT_49,
  UNIT_50,
  UNIT_51,
  UNIT_52,
  UNIT_53,
  UNIT_54,
  UNIT_55,
  UNIT_56,
  UNIT_57,
  UNIT_58,
  UNIT_59,
  UNIT_60,
];

