import type { VocabularyUnit } from "../vocabulary-unit-types";
import { ex, fillBlank, mcq, purple } from "./eviu-unit-builder";
import { preUnit, wordList } from "./eviu-pre-unit-helpers";

const U61_WORDS = wordList([
  ["zero", "số không", "Please add one zero to the amount."],
  ["dozen", "một tá, gồm mười hai đơn vị", "I bought a dozen eggs this morning."],
  ["hundred", "một trăm", "The hall can hold a hundred people."],
  ["thousand", "một nghìn", "The village has around two thousand residents."],
  ["million", "một triệu", "The video reached one million views.", "NOUN"],
  ["billion", "một tỷ", "The company is worth over one billion dollars."],
  ["percentage", "tỷ lệ phần trăm", "A high percentage of students passed."],
  ["fraction", "phân số, phần nhỏ của tổng thể", "One half is a common fraction."],
  ["decimal", "số thập phân", "Write the answer as a decimal."],
  ["approximate", "xấp xỉ, gần đúng", "The approximate cost is fifty dollars.", "ADJECTIVE"],
  ["exact", "chính xác, tuyệt đối đúng", "I need the exact number, not a guess.", "ADJECTIVE"],
  ["odd number", "số lẻ", "Seven is an odd number."],
  ["even number", "số chẵn", "Eight is an even number."],
  ["round up", "làm tròn lên", "You should round up 4.6 to 5.", "VERB"],
  ["round down", "làm tròn xuống", "We round down 7.2 to 7.", "VERB"],
  ["calculate", "tính toán", "Can you calculate the total quickly?", "VERB"],
  ["estimate", "ước lượng", "Try to estimate the time needed.", "VERB"],
  ["figure", "con số, số liệu", "The final figure surprised everyone."],
]);

const U62_WORDS = wordList([
  ["distance", "khoảng cách giữa hai điểm", "The distance from home to school is short."],
  ["length", "chiều dài", "We measured the table length."],
  ["width", "chiều rộng", "The width of this door is one meter."],
  ["height", "chiều cao", "What is your height in centimeters?"],
  ["depth", "độ sâu", "The depth of the pool is two meters."],
  ["diameter", "đường kính của hình tròn", "The pizza has a diameter of 30 cm."],
  ["radius", "bán kính", "The radius is half the diameter."],
  ["area", "diện tích", "We calculated the area of the room."],
  ["volume", "thể tích", "This bottle has a volume of one liter."],
  ["weigh", "nặng, có trọng lượng", "The package weighs three kilos.", "VERB"],
  ["weight", "trọng lượng", "Please check the luggage weight."],
  ["lightweight", "nhẹ cân, trọng lượng nhẹ", "This suitcase is lightweight.", "ADJECTIVE"],
  ["heavy", "nặng", "That box is too heavy to lift.", "ADJECTIVE"],
  ["huge", "rất to, khổng lồ", "They live in a huge apartment.", "ADJECTIVE"],
  ["tiny", "rất nhỏ", "A tiny crack appeared on the screen.", "ADJECTIVE"],
  ["expand", "mở rộng, nở ra", "Metal can expand in hot weather.", "VERB"],
  ["shrink", "co lại, thu nhỏ", "Wool clothes may shrink in hot water.", "VERB"],
  ["measurement", "phép đo, số đo", "Double-check each measurement before cutting."],
]);

const U63_WORDS = wordList([
  ["object", "vật thể, đồ vật", "Please move that heavy object carefully."],
  ["device", "thiết bị", "This device tracks your daily steps."],
  ["equipment", "trang thiết bị, dụng cụ", "Safety equipment is required in the lab."],
  ["material", "chất liệu", "What material is this jacket made of?"],
  ["fabric", "vải, chất liệu dệt", "The fabric feels soft and breathable."],
  ["wooden", "làm bằng gỗ", "We bought a wooden chair.", "ADJECTIVE"],
  ["metallic", "thuộc kim loại, ánh kim", "The phone has a metallic finish.", "ADJECTIVE"],
  ["plastic", "nhựa", "Plastic containers are easy to clean."],
  ["glass", "thủy tinh", "Glass can break if dropped."],
  ["smooth", "mịn, trơn láng", "The surface is smooth to the touch.", "ADJECTIVE"],
  ["rough", "thô ráp, gồ ghề", "This wall feels rough.", "ADJECTIVE"],
  ["circle", "hình tròn", "Draw a circle in the center."],
  ["square", "hình vuông", "Cut the paper into a square."],
  ["triangle", "hình tam giác", "A triangle has three sides."],
  ["rectangular", "hình chữ nhật", "The mirror is rectangular.", "ADJECTIVE"],
  ["curved", "cong, uốn cong", "The road is curved near the lake.", "ADJECTIVE"],
  ["shade", "sắc độ màu", "I like this darker shade of blue."],
  ["colourful", "nhiều màu sắc, rực rỡ", "The market is full of colourful clothes.", "ADJECTIVE"],
]);

const U64_WORDS = wordList([
  ["container", "đồ chứa, vật đựng", "Use a clean container for leftovers."],
  ["bottle", "chai", "She filled a bottle with water."],
  ["jar", "lọ, hũ", "There is honey in that jar."],
  ["can", "lon", "Open the can carefully.", "NOUN"],
  ["packet", "gói nhỏ đóng sẵn", "I bought a packet of biscuits."],
  ["box", "hộp", "The gift came in a red box."],
  ["carton", "hộp giấy cứng, hộp đựng sữa", "A carton of milk is in the fridge."],
  ["tube", "tuýp, ống", "She squeezed toothpaste from the tube."],
  ["slice", "lát cắt mỏng", "Can I have a slice of bread?"],
  ["piece", "miếng, mảnh", "Give me one piece of chocolate."],
  ["drop", "giọt nhỏ", "Add a drop of lemon juice."],
  ["spoonful", "một thìa đầy", "Take a spoonful of sugar."],
  ["handful", "một nắm tay", "Add a handful of nuts."],
  ["bunch", "một chùm, bó", "He bought a bunch of bananas."],
  ["load", "một lượng lớn chất lên", "The truck carried a full load."],
  ["bulk", "khối lượng lớn", "Buying in bulk saves money."],
  ["empty", "làm rỗng, trống", "Please empty the bin before leaving.", "VERB"],
  ["fill", "đổ đầy", "Could you fill this bottle for me?", "VERB"],
]);

const U65_WORDS = wordList([
  ["apologize", "xin lỗi", "I apologize for arriving late.", "VERB"],
  ["apology", "lời xin lỗi", "He offered a sincere apology."],
  ["regret", "hối tiếc", "We regret the inconvenience caused.", "VERB"],
  ["forgive", "tha thứ", "Please forgive my mistake.", "VERB"],
  ["fault", "lỗi, trách nhiệm sai sót", "It was my fault, not yours."],
  ["blame", "đổ lỗi", "Don't blame him for everything.", "VERB"],
  ["excuse", "lý do biện hộ", "That sounds like an excuse."],
  ["reasonable", "hợp lý", "Your explanation is reasonable.", "ADJECTIVE"],
  ["acceptable", "có thể chấp nhận", "A ten-minute delay is acceptable.", "ADJECTIVE"],
  ["thankful", "biết ơn", "I'm thankful for your support.", "ADJECTIVE"],
  ["grateful", "cảm kích", "She was grateful for the help.", "ADJECTIVE"],
  ["appreciate", "đánh giá cao, trân trọng", "I really appreciate your advice.", "VERB"],
  ["owe", "mắc nợ, mang ơn", "I owe you an apology.", "VERB"],
  ["make it up to", "bù đắp cho ai vì lỗi lầm", "I will make it up to you.", "VERB"],
  ["excuse me", "xin phép / xin lỗi khi làm phiền", "Excuse me, is this seat free?"],
  ["I'm sorry", "tôi xin lỗi", "I'm sorry for the confusion."],
  ["no problem", "không sao đâu", "No problem, we can try again."],
  ["thanks a lot", "cảm ơn rất nhiều", "Thanks a lot for your time."],
]);

const U66_WORDS = wordList([
  ["request", "đề nghị, yêu cầu lịch sự", "I sent a request for more details."],
  ["ask for", "yêu cầu, xin", "You can ask for a refund at the desk.", "VERB"],
  ["would you mind", "bạn có phiền nếu...", "Would you mind opening the window?"],
  ["could you", "bạn có thể... không", "Could you speak more slowly?"],
  ["permission", "sự cho phép", "You need permission to enter the lab."],
  ["allow", "cho phép", "They don't allow phones in class.", "VERB"],
  ["let", "cho phép ai làm gì", "Please let me explain.", "VERB"],
  ["be allowed to", "được phép làm gì", "Are we allowed to park here?", "VERB"],
  ["suggest", "đề xuất", "I suggest taking the earlier train.", "VERB"],
  ["recommend", "khuyên dùng, đề nghị", "I recommend this dictionary.", "VERB"],
  ["advice", "lời khuyên", "Thanks for the useful advice."],
  ["offer", "đề nghị giúp đỡ/cung cấp", "He offered to carry my bag.", "VERB"],
  ["refuse", "từ chối", "She refused to sign the form.", "VERB"],
  ["accept", "chấp nhận", "I gladly accept your invitation.", "VERB"],
  ["deal", "xử lý, giải quyết", "Can you deal with this request today?", "VERB"],
  ["it's a good idea", "đó là một ý hay", "It's a good idea to book early."],
  ["how about", "thế còn... thì sao", "How about meeting at seven?"],
  ["why don't we", "sao chúng ta không...", "Why don't we take a short break?"],
]);

const U67_WORDS = wordList([
  ["opinion", "ý kiến cá nhân", "Everyone has a different opinion."],
  ["point of view", "quan điểm, góc nhìn", "Try to see it from her point of view."],
  ["in my view", "theo quan điểm của tôi", "In my view, this plan is practical."],
  ["personally", "cá nhân tôi thì", "Personally, I prefer a smaller team."],
  ["agree", "đồng ý", "I agree with your suggestion.", "VERB"],
  ["disagree", "không đồng ý", "I disagree with that conclusion.", "VERB"],
  ["completely", "hoàn toàn", "I completely agree with you.", "ADVERB"],
  ["partly", "một phần", "I partly agree, but we need more data.", "ADVERB"],
  ["exactly", "chính xác, đúng vậy", "Exactly, that's what I meant.", "ADVERB"],
  ["not really", "không hẳn vậy", "Not really, I had a different idea."],
  ["convince", "thuyết phục", "Can you convince them to join?", "VERB"],
  ["argument", "lập luận; cuộc tranh luận căng thẳng", "She presented a strong argument."],
  ["evidence", "bằng chứng", "We need evidence to support this claim."],
  ["valid", "hợp lệ, có cơ sở", "That's a valid concern.", "ADJECTIVE"],
  ["fair point", "ý kiến hợp lý", "That's a fair point, thanks."],
  ["on the other hand", "mặt khác", "On the other hand, the cost is high."],
  ["to be honest", "thành thật mà nói", "To be honest, I'm not sure yet."],
  ["from my experience", "theo kinh nghiệm của tôi", "From my experience, clear rules help."],
]);

const U68_WORDS = wordList([
  ["like", "thích", "I like this new design.", "VERB"],
  ["dislike", "không thích", "Many users dislike long forms.", "VERB"],
  ["love", "rất thích", "She loves reading history books.", "VERB"],
  ["hate", "ghét", "I hate waiting in traffic.", "VERB"],
  ["prefer", "thích hơn, ưu tiên hơn", "I prefer tea to coffee.", "VERB"],
  ["favorite", "yêu thích nhất", "Blue is my favorite color.", "ADJECTIVE"],
  ["enjoy", "thích, tận hưởng", "We enjoy walking after dinner.", "VERB"],
  ["interested in", "quan tâm tới", "I'm interested in graphic design.", "ADJECTIVE"],
  ["keen on", "rất thích, hứng thú với", "He's keen on photography.", "ADJECTIVE"],
  ["fond of", "có thiện cảm, thích", "My grandmother is fond of classical music.", "ADJECTIVE"],
  ["can't stand", "không thể chịu nổi", "I can't stand loud noise."],
  ["don't mind", "không ngại", "I don't mind working late today."],
  ["taste", "gu, thị hiếu", "We have similar taste in films."],
  ["preference", "sở thích ưu tiên", "Customer preference is changing fast."],
  ["choice", "sự lựa chọn", "You have a choice between two options."],
  ["rather than", "thay vì", "I'd walk rather than drive."],
  ["would rather", "muốn ... hơn", "I would rather stay home tonight."],
  ["be crazy about", "rất mê, cực kỳ thích", "They're crazy about Korean food.", "VERB"],
]);

const U69_WORDS = wordList([
  ["greet", "chào ai đó", "Please greet the guests at the door.", "VERB"],
  ["greeting", "lời chào", "A warm greeting makes people comfortable."],
  ["hello", "xin chào", "Hello, nice to meet you."],
  ["hi", "chào (thân mật)", "Hi, how's your day going?"],
  ["good morning", "chào buổi sáng", "Good morning, everyone."],
  ["good evening", "chào buổi tối", "Good evening, Mr. Long."],
  ["nice to meet you", "rất vui được gặp bạn", "Nice to meet you at last."],
  ["how are you", "bạn khỏe không", "How are you today?"],
  ["welcome", "chào mừng", "Welcome to our office.", "VERB"],
  ["introduce", "giới thiệu", "Let me introduce my colleague.", "VERB"],
  ["see you", "hẹn gặp lại", "See you tomorrow at class."],
  ["see you later", "gặp lại sau nhé", "See you later, take care."],
  ["goodbye", "tạm biệt", "Goodbye, and thank you."],
  ["bye", "bye, tạm biệt (thân mật)", "Bye, text me when you arrive."],
  ["take care", "giữ gìn nhé", "Take care on your way home."],
  ["have a nice day", "chúc bạn một ngày tốt lành", "Have a nice day at work."],
  ["safe trip", "chúc chuyến đi an toàn", "Safe trip, and call us when you land."],
  ["farewell", "lời chia tay trang trọng", "They organized a farewell party."],
]);

const U70_WORDS = wordList([
  ["unhappy", "không vui", "He looked unhappy after the meeting.", "ADJECTIVE"],
  ["unknown", "không được biết đến", "The cause is still unknown.", "ADJECTIVE"],
  ["disagree", "không đồng ý", "I disagree with that proposal.", "VERB"],
  ["dislike", "không thích", "Some people dislike spicy food.", "VERB"],
  ["misunderstand", "hiểu nhầm", "I misunderstood your message.", "VERB"],
  ["misprint", "in sai, lỗi in", "This textbook has a misprint."],
  ["rewrite", "viết lại", "Please rewrite this paragraph.", "VERB"],
  ["recheck", "kiểm tra lại", "Let's recheck the final numbers.", "VERB"],
  ["overcook", "nấu quá chín", "Don't overcook the vegetables.", "VERB"],
  ["oversleep", "ngủ quên quá giờ", "I overslept and missed the bus.", "VERB"],
  ["underpaid", "bị trả lương thấp", "Many workers feel underpaid.", "ADJECTIVE"],
  ["underestimate", "đánh giá thấp", "Don't underestimate this task.", "VERB"],
  ["prepaid", "trả trước", "I bought a prepaid SIM card.", "ADJECTIVE"],
  ["preview", "xem trước", "We watched a preview of the film."],
  ["co-worker", "đồng nghiệp", "My co-worker helped me fix the bug."],
  ["coexist", "cùng tồn tại", "Different styles can coexist.", "VERB"],
  ["anti-social", "khó hòa đồng, ngại giao tiếp xã hội", "He becomes anti-social in large groups.", "ADJECTIVE"],
  ["subway", "tàu điện ngầm", "We took the subway to downtown."],
]);

const U71_WORDS = wordList([
  ["happiness", "sự hạnh phúc", "Money alone doesn't guarantee happiness."],
  ["kindness", "lòng tốt", "Her kindness touched everyone."],
  ["darkness", "bóng tối", "The room was in complete darkness."],
  ["friendship", "tình bạn", "Their friendship started in college."],
  ["leadership", "khả năng lãnh đạo", "Good leadership builds trust."],
  ["membership", "tư cách thành viên", "Gym membership is paid monthly."],
  ["teacher", "giáo viên", "Our teacher explains clearly."],
  ["driver", "tài xế", "The bus driver was very patient."],
  ["employee", "nhân viên", "Every employee must wear an ID card."],
  ["trainee", "thực tập sinh, người đang được đào tạo", "The trainee asked many smart questions."],
  ["actor", "diễn viên nam/nói chung", "The actor won an international award."],
  ["visitor", "khách tham quan", "Each visitor receives a map."],
  ["decision", "quyết định", "That was a difficult decision."],
  ["discussion", "cuộc thảo luận", "We had a long discussion about budget."],
  ["translation", "bản dịch", "I checked the translation twice."],
  ["activity", "hoạt động", "Outdoor activity improves mood."],
  ["ability", "khả năng", "She has the ability to lead teams."],
  ["certainty", "sự chắc chắn", "There is no certainty about the result."],
]);

const U72_WORDS = wordList([
  ["useful", "hữu ích", "This app is very useful for students.", "ADJECTIVE"],
  ["careful", "cẩn thận", "Be careful with that knife.", "ADJECTIVE"],
  ["helpful", "hay giúp đỡ, có ích", "The guide was helpful.", "ADJECTIVE"],
  ["famous", "nổi tiếng", "Da Nang is famous for its beaches.", "ADJECTIVE"],
  ["dangerous", "nguy hiểm", "Swimming here is dangerous in winter.", "ADJECTIVE"],
  ["nervous", "lo lắng", "I felt nervous before the interview.", "ADJECTIVE"],
  ["natural", "tự nhiên", "This juice has a natural flavor.", "ADJECTIVE"],
  ["personal", "cá nhân", "Please keep this information personal.", "ADJECTIVE"],
  ["national", "thuộc quốc gia", "Today is a national holiday.", "ADJECTIVE"],
  ["rainy", "mưa nhiều, có mưa", "It gets rainy in July.", "ADJECTIVE"],
  ["sunny", "nắng đẹp", "Tomorrow will be sunny.", "ADJECTIVE"],
  ["windy", "nhiều gió", "It's too windy for a boat trip.", "ADJECTIVE"],
  ["cloudy", "nhiều mây", "The sky is cloudy this morning.", "ADJECTIVE"],
  ["friendly", "thân thiện", "The staff are friendly and polite.", "ADJECTIVE"],
  ["noisy", "ồn ào", "This street is noisy at night.", "ADJECTIVE"],
  ["tasty", "ngon miệng", "That soup is really tasty.", "ADJECTIVE"],
  ["comfortable", "thoải mái", "These shoes are comfortable.", "ADJECTIVE"],
  ["affordable", "có giá phải chăng", "We found an affordable apartment.", "ADJECTIVE"],
]);

const U73_WORDS = wordList([
  ["toothbrush", "bàn chải đánh răng", "I packed my toothbrush in a small bag."],
  ["toothpaste", "kem đánh răng", "Buy a new tube of toothpaste."],
  ["hairdryer", "máy sấy tóc", "The hotel room includes a hairdryer."],
  ["bedroom", "phòng ngủ", "Our bedroom faces the garden."],
  ["bathroom", "phòng tắm", "The bathroom needs cleaning."],
  ["notebook", "sổ tay", "I wrote the idea in my notebook."],
  ["bookshop", "hiệu sách", "There's a good bookshop near campus."],
  ["raincoat", "áo mưa", "Take a raincoat in case it rains."],
  ["sunglasses", "kính râm", "She wore sunglasses at the beach."],
  ["headphones", "tai nghe chụp đầu", "These headphones block outside noise."],
  ["keyboard", "bàn phím", "My keyboard is wireless."],
  ["smartphone", "điện thoại thông minh", "Almost everyone has a smartphone now."],
  ["weekend", "cuối tuần", "We're visiting my parents this weekend."],
  ["sunrise", "bình minh", "We watched the sunrise from the hill."],
  ["sunset", "hoàng hôn", "Sunset over the river was beautiful."],
  ["bus stop", "trạm xe buýt", "Meet me at the bus stop."],
  ["coffee shop", "quán cà phê", "Let's work in a coffee shop today."],
  ["credit card", "thẻ tín dụng", "Do you accept credit card payments?"],
]);

const U74_WORDS = wordList([
  ["make a decision", "đưa ra quyết định", "We need to make a decision today.", "VERB"],
  ["take a break", "nghỉ giải lao", "Let's take a break after this section.", "VERB"],
  ["have a look", "xem thử", "Could you have a look at this file?", "VERB"],
  ["give advice", "đưa lời khuyên", "My mentor gave useful advice.", "VERB"],
  ["do homework", "làm bài tập về nhà", "I usually do homework after dinner.", "VERB"],
  ["catch a bus", "bắt xe buýt", "We must catch a bus at 6:30.", "VERB"],
  ["miss a chance", "bỏ lỡ cơ hội", "Don't miss a chance to practice.", "VERB"],
  ["pay attention", "chú ý", "Please pay attention to the instructions.", "VERB"],
  ["keep calm", "giữ bình tĩnh", "Try to keep calm during the exam.", "VERB"],
  ["save time", "tiết kiệm thời gian", "Templates help us save time.", "VERB"],
  ["waste money", "lãng phí tiền bạc", "Buying unused items wastes money.", "VERB"],
  ["tell the truth", "nói sự thật", "You should tell the truth.", "VERB"],
  ["break a promise", "thất hứa", "He never breaks a promise.", "VERB"],
  ["keep in touch", "giữ liên lạc", "Let's keep in touch after graduation.", "VERB"],
  ["set an alarm", "đặt báo thức", "Set an alarm for 5 a.m.", "VERB"],
  ["reach a goal", "đạt mục tiêu", "Daily habits help you reach a goal.", "VERB"],
  ["run out of", "hết, cạn kiệt", "We've run out of milk.", "VERB"],
  ["take responsibility", "chịu trách nhiệm", "Leaders should take responsibility.", "VERB"],
]);

const U75_WORDS = wordList([
  ["as soon as possible", "càng sớm càng tốt", "Please reply as soon as possible."],
  ["by the way", "nhân tiện, tiện thể", "By the way, your package arrived."],
  ["in fact", "thực ra", "In fact, we finished earlier than planned."],
  ["at least", "ít nhất", "Bring at least two copies."],
  ["at first", "lúc đầu", "At first, I didn't understand the task."],
  ["for example", "ví dụ như", "For example, we can start with unit one."],
  ["for now", "tạm thời lúc này", "For now, let's focus on basics."],
  ["on time", "đúng giờ", "The train arrived on time."],
  ["in time", "kịp lúc", "We reached the station in time."],
  ["from time to time", "thỉnh thoảng", "I visit my hometown from time to time."],
  ["in the end", "cuối cùng (kết quả sau cùng)", "In the end, we chose option B."],
  ["at the moment", "vào lúc này", "At the moment, sales are stable."],
  ["all of a sudden", "đột nhiên", "All of a sudden, the lights went out."],
  ["as usual", "như thường lệ", "He arrived early as usual."],
  ["once in a while", "thỉnh thoảng, không thường xuyên", "We eat out once in a while."],
  ["to be honest", "thành thật mà nói", "To be honest, I need more time."],
  ["in other words", "nói cách khác", "In other words, we must restart."],
  ["on purpose", "cố ý", "She didn't delete the file on purpose."],
]);

export const EVIU_PRE_UNITS_61_75: VocabularyUnit[] = [
  preUnit(61, {
    introVi: "Unit 61 tập trung từ vựng về số và cách diễn đạt số liệu thường gặp trong học tập, công việc. Bạn sẽ tự tin hơn khi mô tả con số chính xác hoặc ước lượng.",
    structureSections: [
      { label: "Basic large numbers", wordCount: 6 },
      { label: "Math and formats", wordCount: 6 },
      { label: "Estimating results", wordCount: 6 },
    ],
    collocationHtml: `${purple("round up")}, ${purple("calculate")} và ${purple("approximate figure")} là cụm dùng nhiều khi xử lý dữ liệu.`,
    mistakeHtml: "Không nhầm exact với approximate: exact là chính xác tuyệt đối, còn approximate chỉ giá trị gần đúng.",
    principles: [
      {
        title: "Nói số lớn theo cụm quen thuộc",
        body: `Với số lớn, dùng ${purple("thousand")}, ${purple("million")} và ${purple("billion")} để diễn đạt tự nhiên.`,
        examples: [ex("The app reached one million downloads.", "Ứng dụng đạt một triệu lượt tải.")],
      },
      {
        title: "Phân biệt số học cơ bản",
        body: `${purple("fraction")}, ${purple("decimal")} và ${purple("percentage")} thường dùng trong báo cáo học tập và kinh doanh.`,
        examples: [ex("Please convert this fraction to a decimal.", "Hãy đổi phân số này sang số thập phân.")],
      },
      {
        title: "Ước lượng khi không cần độ chính xác tuyệt đối",
        body: `Khi trình bày nhanh, bạn có thể ${purple("estimate")} hoặc ${purple("round down")} dữ liệu.`,
        examples: [ex("Can you estimate the total cost?", "Bạn có thể ước lượng tổng chi phí không?")],
      },
    ],
    words: U61_WORDS,
    exercises: [
      mcq(
        61,
        1,
        "Từ nào nghĩa là giá trị gần đúng?",
        [
          { key: "a", label: "exact" },
          { key: "b", label: "approximate" },
          { key: "c", label: "odd number" },
          { key: "d", label: "decimal" },
        ],
        "b",
      ),
      fillBlank(
        61,
        2,
        "Please ____ the final amount before sending the invoice.",
        "calculate",
        [
          { key: "a", label: "estimate" },
          { key: "b", label: "calculate" },
          { key: "c", label: "round down" },
          { key: "d", label: "figure" },
        ],
        "b",
      ),
    ],
  }),
  preUnit(62, {
    introVi: "Unit 62 phát triển vốn từ về khoảng cách, kích thước và số đo vật lý. Nội dung giúp bạn mô tả chính xác hình dáng, độ lớn và thông số kỹ thuật.",
    structureSections: [
      { label: "Core dimensions", wordCount: 6 },
      { label: "Shape measurements", wordCount: 6 },
      { label: "Size and change", wordCount: 6 },
    ],
    collocationHtml: `${purple("long distance")}, ${purple("take measurements")} và ${purple("heavy weight")} là các kết hợp xuất hiện thường xuyên.`,
    mistakeHtml: "Đừng dùng lẫn height với length: height là chiều cao theo trục đứng, length là chiều dài theo trục ngang.",
    principles: [
      {
        title: "Mô tả vật thể bằng ba số đo chính",
        body: `Ưu tiên cặp ${purple("length")}, ${purple("width")} và ${purple("height")} trước khi thêm thông tin khác.`,
        examples: [ex("Please send the length and width first.", "Vui lòng gửi trước chiều dài và chiều rộng.")],
      },
      {
        title: "Dùng từ đo lường chuyên biệt khi cần",
        body: `${purple("diameter")} và ${purple("radius")} phù hợp với vật tròn; ${purple("depth")} hợp với hố, bể, hộp.`,
        examples: [ex("The pool depth is clearly marked.", "Độ sâu hồ bơi được ghi rõ.")],
      },
      {
        title: "Thể hiện sự thay đổi kích thước đúng động từ",
        body: `${purple("expand")} nghĩa là nở ra, còn ${purple("shrink")} là co lại hoặc thu nhỏ.`,
        examples: [ex("The material may shrink after washing.", "Chất liệu này có thể co lại sau khi giặt.")],
      },
    ],
    words: U62_WORDS,
    exercises: [
      mcq(
        62,
        1,
        "Từ nào chỉ số đo theo chiều sâu?",
        [
          { key: "a", label: "width" },
          { key: "b", label: "depth" },
          { key: "c", label: "radius" },
          { key: "d", label: "distance" },
        ],
        "b",
      ),
      fillBlank(
        62,
        2,
        "Please check the ____ of your luggage before check-in.",
        "weight",
        [
          { key: "a", label: "volume" },
          { key: "b", label: "measurement" },
          { key: "c", label: "weight" },
          { key: "d", label: "height" },
        ],
        "c",
      ),
    ],
  }),
  preUnit(63, {
    introVi: "Unit 63 giới thiệu từ vựng về đồ vật, chất liệu, hình dạng và màu sắc. Đây là nhóm từ thiết yếu để mô tả sản phẩm, nội thất và vật dụng hằng ngày.",
    structureSections: [
      { label: "Objects and tools", wordCount: 6 },
      { label: "Materials and texture", wordCount: 6 },
      { label: "Shapes and colours", wordCount: 6 },
    ],
    collocationHtml: `${purple("wooden object")}, ${purple("smooth surface")} và ${purple("bright shade")} giúp mô tả vật thể rõ hơn.`,
    mistakeHtml: "Material là chất liệu chung, còn fabric chủ yếu nói về chất liệu vải dùng cho quần áo hoặc đồ dệt.",
    principles: [
      {
        title: "Mô tả theo thứ tự vật thể -> chất liệu -> đặc điểm",
        body: `Cách này tự nhiên hơn khi nói: ${purple("object")} + ${purple("material")} + texture hoặc màu.`,
        examples: [ex("It's a wooden table with a smooth surface.", "Đó là bàn gỗ có bề mặt nhẵn.")],
      },
      {
        title: "Phân biệt từ chỉ hình dạng cơ bản",
        body: `Nắm chắc ${purple("circle")}, ${purple("square")}, ${purple("triangle")} để đọc hướng dẫn kỹ thuật dễ hơn.`,
        examples: [ex("Draw a triangle under the square.", "Vẽ một tam giác bên dưới hình vuông.")],
      },
      {
        title: "Dùng từ sắc độ màu để tăng độ chính xác",
        body: `${purple("shade")} giúp mô tả khác biệt giữa các tông màu cùng họ.`,
        examples: [ex("I want a lighter shade of green.", "Tôi muốn sắc xanh nhạt hơn.")],
      },
    ],
    words: U63_WORDS,
    exercises: [
      mcq(
        63,
        1,
        "Từ nào chỉ bề mặt nhẵn, không thô?",
        [
          { key: "a", label: "rough" },
          { key: "b", label: "metallic" },
          { key: "c", label: "smooth" },
          { key: "d", label: "curved" },
        ],
        "c",
      ),
      fillBlank(
        63,
        2,
        "This jacket is made from a soft ____.",
        "fabric",
        [
          { key: "a", label: "shade" },
          { key: "b", label: "circle" },
          { key: "c", label: "fabric" },
          { key: "d", label: "equipment" },
        ],
        "c",
      ),
    ],
  }),
  preUnit(64, {
    introVi: "Unit 64 tập trung cách nói đồ chứa và lượng trong đời sống thường ngày. Bạn sẽ diễn đạt chính xác hơn khi mua sắm, nấu ăn và mô tả số lượng.",
    structureSections: [
      { label: "Types of containers", wordCount: 6 },
      { label: "Food quantities", wordCount: 6 },
      { label: "Amount and handling", wordCount: 6 },
    ],
    collocationHtml: `${purple("a bottle of water")}, ${purple("a slice of bread")} và ${purple("buy in bulk")} là cụm cực kỳ thực dụng.`,
    mistakeHtml: "Piece dùng chung cho nhiều vật, còn slice thiên về lát mỏng như bánh mì, phô mai, pizza.",
    principles: [
      {
        title: "Chọn đúng loại đồ chứa theo ngữ cảnh",
        body: `${purple("jar")} thường cho đồ đặc như mứt, ${purple("carton")} cho sữa hoặc nước trái cây.`,
        examples: [ex("We need a carton of milk and a jar of jam.", "Chúng ta cần một hộp sữa và một hũ mứt.")],
      },
      {
        title: "Dùng từ chỉ lượng giúp câu tự nhiên",
        body: `${purple("spoonful")}, ${purple("handful")} và ${purple("drop")} rất hay dùng trong hướng dẫn nấu ăn.`,
        examples: [ex("Add a spoonful of sugar and a drop of vanilla.", "Thêm một thìa đường và một giọt vani.")],
      },
      {
        title: "Kết hợp động từ với đồ chứa phù hợp",
        body: `Thường đi cùng ${purple("fill")} a bottle, ${purple("empty")} a box hoặc a bin.`,
        examples: [ex("Please fill the bottle before we leave.", "Hãy đổ đầy chai trước khi chúng ta đi.")],
      },
    ],
    words: U64_WORDS,
    exercises: [
      mcq(
        64,
        1,
        "Từ nào nghĩa là 'một thìa đầy'?",
        [
          { key: "a", label: "slice" },
          { key: "b", label: "spoonful" },
          { key: "c", label: "packet" },
          { key: "d", label: "bunch" },
        ],
        "b",
      ),
      fillBlank(
        64,
        2,
        "Please ____ this jar with clean water.",
        "fill",
        [
          { key: "a", label: "empty" },
          { key: "b", label: "fill" },
          { key: "c", label: "bulk" },
          { key: "d", label: "drop" },
        ],
        "b",
      ),
    ],
  }),
  preUnit(65, {
    introVi: "Unit 65 rèn ngôn ngữ xin lỗi, giải thích và bày tỏ lòng biết ơn trong giao tiếp hàng ngày. Mục tiêu là nói lịch sự, chân thành và đúng bối cảnh.",
    structureSections: [
      { label: "Apologizing language", wordCount: 6 },
      { label: "Excuses and responsibility", wordCount: 6 },
      { label: "Thanks and response", wordCount: 6 },
    ],
    collocationHtml: `${purple("sincere apology")}, ${purple("take the blame")} và ${purple("really appreciate")} là cụm giúp lời nói tự nhiên hơn.`,
    mistakeHtml: "Excuse và apology không giống nhau: excuse là lý do biện hộ, apology là hành động thừa nhận và xin lỗi.",
    principles: [
      {
        title: "Xin lỗi hiệu quả gồm thừa nhận + trách nhiệm",
        body: `Nói rõ ${purple("fault")} của mình và dùng ${purple("I'm sorry")} hoặc ${purple("apologize")} phù hợp mức độ.`,
        examples: [ex("I'm sorry, it was my fault.", "Tôi xin lỗi, đó là lỗi của tôi.")],
      },
      {
        title: "Giải thích nhưng không đổ lỗi",
        body: `Tránh dùng ${purple("excuse")} theo kiểu né trách nhiệm; ưu tiên thái độ ${purple("reasonable")}.`,
        examples: [ex("I regret the delay and will fix it today.", "Tôi rất tiếc về sự chậm trễ và sẽ xử lý hôm nay.")],
      },
      {
        title: "Đáp lại lời cảm ơn tự nhiên",
        body: `Sau khi nhận lời cảm ơn, có thể đáp ${purple("no problem")} để giữ không khí thân thiện.`,
        examples: [ex("Thanks a lot for your help. - No problem.", "Cảm ơn bạn rất nhiều vì đã giúp. - Không có gì.")],
      },
    ],
    words: U65_WORDS,
    exercises: [
      mcq(
        65,
        1,
        "Cụm nào dùng để bày tỏ xin lỗi trực tiếp?",
        [
          { key: "a", label: "thanks a lot" },
          { key: "b", label: "excuse me" },
          { key: "c", label: "I'm sorry" },
          { key: "d", label: "no problem" },
        ],
        "c",
      ),
      fillBlank(
        65,
        2,
        "I really ____ your support during this project.",
        "appreciate",
        [
          { key: "a", label: "forgive" },
          { key: "b", label: "appreciate" },
          { key: "c", label: "blame" },
          { key: "d", label: "owe" },
        ],
        "b",
      ),
    ],
  }),
  preUnit(66, {
    introVi: "Unit 66 bao quát các mẫu câu yêu cầu, xin phép và đưa gợi ý lịch sự. Bạn sẽ giao tiếp tự tin hơn trong lớp học, văn phòng và tình huống dịch vụ.",
    structureSections: [
      { label: "Making requests", wordCount: 6 },
      { label: "Permission language", wordCount: 6 },
      { label: "Suggestions and responses", wordCount: 6 },
    ],
    collocationHtml: `${purple("make a request")}, ${purple("ask for permission")} và ${purple("offer advice")} là ba hướng dùng chính của unit.`,
    mistakeHtml: "Could you dùng để nhờ người khác làm; Can I / Am I allowed to thường dùng để xin phép bản thân làm gì.",
    principles: [
      {
        title: "Ưu tiên cấu trúc lịch sự khi nhờ vả",
        body: `Câu mở bằng ${purple("could you")} hoặc ${purple("would you mind")} thường tạo cảm giác nhẹ nhàng.`,
        examples: [ex("Could you send me the file tonight?", "Bạn có thể gửi tệp cho tôi tối nay không?")],
      },
      {
        title: "Phân biệt xin phép và cho phép",
        body: `${purple("permission")} là danh từ; động từ hay dùng là ${purple("allow")} hoặc ${purple("let")}.`,
        examples: [ex("Are we allowed to enter now?", "Chúng tôi được phép vào bây giờ không?")],
      },
      {
        title: "Đưa gợi ý bằng mẫu câu mềm",
        body: `Dùng ${purple("how about")} và ${purple("why don't we")} giúp đề xuất tự nhiên hơn mệnh lệnh trực tiếp.`,
        examples: [ex("How about meeting after lunch?", "Hay là chúng ta gặp nhau sau bữa trưa?")],
      },
    ],
    words: U66_WORDS,
    exercises: [
      mcq(
        66,
        1,
        "Mẫu nào phù hợp nhất để đưa gợi ý chung cho nhóm?",
        [
          { key: "a", label: "Why don't we..." },
          { key: "b", label: "No problem." },
          { key: "c", label: "Thanks a lot." },
          { key: "d", label: "In my view..." },
        ],
        "a",
      ),
      fillBlank(
        66,
        2,
        "You need official ____ before using this equipment.",
        "permission",
        [
          { key: "a", label: "request" },
          { key: "b", label: "advice" },
          { key: "c", label: "permission" },
          { key: "d", label: "offer" },
        ],
        "c",
      ),
    ],
  }),
  preUnit(67, {
    introVi: "Unit 67 giúp bạn diễn đạt ý kiến, đồng ý hoặc phản đối một cách rõ ràng và tôn trọng. Đây là nền tảng quan trọng cho thảo luận học thuật và công việc nhóm.",
    structureSections: [
      { label: "Giving opinions", wordCount: 6 },
      { label: "Agreeing and disagreeing", wordCount: 6 },
      { label: "Reasoning and balance", wordCount: 6 },
    ],
    collocationHtml: `${purple("strong opinion")}, ${purple("valid argument")} và ${purple("fair point")} là cụm dùng nhiều trong thảo luận.`,
    mistakeHtml: "Disagree with + người/ý kiến; không nói disagree to trong ngữ cảnh nêu quan điểm.",
    principles: [
      {
        title: "Bắt đầu bằng cụm nêu quan điểm rõ ràng",
        body: `Các cụm như ${purple("in my view")} hoặc ${purple("personally")} giúp người nghe nhận diện lập trường của bạn.`,
        examples: [ex("In my view, the deadline is too tight.", "Theo tôi, hạn chót này quá gấp.")],
      },
      {
        title: "Đồng ý/không đồng ý nên có mức độ",
        body: `Dùng ${purple("completely")} hay ${purple("partly")} để tránh phát biểu cực đoan khi không cần thiết.`,
        examples: [ex("I partly agree with your plan.", "Tôi đồng ý một phần với kế hoạch của bạn.")],
      },
      {
        title: "Cân bằng tranh luận bằng góc nhìn khác",
        body: `Cụm ${purple("on the other hand")} giúp thêm chiều sâu và thể hiện tư duy đa chiều.`,
        examples: [ex("On the other hand, this option is cheaper.", "Mặt khác, phương án này rẻ hơn.")],
      },
    ],
    words: U67_WORDS,
    exercises: [
      mcq(
        67,
        1,
        "Từ nào nghĩa là 'ý kiến có cơ sở, hợp lệ'?",
        [
          { key: "a", label: "exactly" },
          { key: "b", label: "valid" },
          { key: "c", label: "partly" },
          { key: "d", label: "personally" },
        ],
        "b",
      ),
      fillBlank(
        67,
        2,
        "____, we should test this idea with real users first.",
        "In my view",
        [
          { key: "a", label: "In my view" },
          { key: "b", label: "How are you" },
          { key: "c", label: "At least" },
          { key: "d", label: "No problem" },
        ],
        "a",
      ),
    ],
  }),
  preUnit(68, {
    introVi: "Unit 68 tập trung cách nói thích/không thích và diễn đạt sở thích cá nhân ở nhiều mức độ. Bạn sẽ mô tả preference tự nhiên hơn trong hội thoại hàng ngày.",
    structureSections: [
      { label: "Core preference verbs", wordCount: 6 },
      { label: "Degree of liking", wordCount: 6 },
      { label: "Choices and habits", wordCount: 6 },
    ],
    collocationHtml: `${purple("personal preference")}, ${purple("similar taste")} và ${purple("make a choice")} là những kết hợp rất thông dụng.`,
    mistakeHtml: "Prefer A to B là cấu trúc phổ biến; không dùng prefer A than B trong tiếng Anh chuẩn.",
    principles: [
      {
        title: "Chọn động từ theo mức độ cảm xúc",
        body: `${purple("like")} nhẹ hơn ${purple("love")}; ${purple("dislike")} nhẹ hơn ${purple("hate")}.`,
        examples: [ex("I dislike cold coffee, but I don't hate it.", "Tôi không thích cà phê lạnh, nhưng không đến mức ghét.")],
      },
      {
        title: "Dùng cấu trúc so sánh sở thích chuẩn",
        body: `Khi so sánh, dùng ${purple("prefer")} A to B hoặc ${purple("would rather")} + V nguyên mẫu.`,
        examples: [ex("I prefer reading to watching TV.", "Tôi thích đọc sách hơn xem TV.")],
      },
      {
        title: "Dùng cụm cố định để nói tự nhiên hơn",
        body: `${purple("can't stand")} và ${purple("don't mind")} giúp bạn diễn đạt thái độ rõ mà không dài dòng.`,
        examples: [ex("I don't mind waiting for ten minutes.", "Tôi không ngại chờ mười phút.")],
      },
    ],
    words: U68_WORDS,
    exercises: [
      mcq(
        68,
        1,
        "Cụm nào nghĩa là 'không thể chịu nổi'?",
        [
          { key: "a", label: "don't mind" },
          { key: "b", label: "can't stand" },
          { key: "c", label: "be interested in" },
          { key: "d", label: "would rather" },
        ],
        "b",
      ),
      fillBlank(
        68,
        2,
        "I ____ tea to coffee in the morning.",
        "prefer",
        [
          { key: "a", label: "enjoy" },
          { key: "b", label: "prefer" },
          { key: "c", label: "hate" },
          { key: "d", label: "dislike" },
        ],
        "b",
      ),
    ],
  }),
  preUnit(69, {
    introVi: "Unit 69 tổng hợp ngôn ngữ chào hỏi và tạm biệt theo các mức độ trang trọng khác nhau. Bạn sẽ phản xạ tự nhiên hơn trong giao tiếp xã hội và môi trường công việc.",
    structureSections: [
      { label: "Basic greetings", wordCount: 6 },
      { label: "Introductions and welcome", wordCount: 6 },
      { label: "Farewells and wishes", wordCount: 6 },
    ],
    collocationHtml: `${purple("warm greeting")}, ${purple("introduce yourself")} và ${purple("say goodbye")} là các mẫu dùng thường xuyên.`,
    mistakeHtml: "Good evening dùng khi gặp vào buổi tối; khi rời đi thường nói goodbye hoặc good night tùy ngữ cảnh.",
    principles: [
      {
        title: "Chọn lời chào theo độ thân mật",
        body: `${purple("hello")} trung tính, ${purple("hi")} thân mật hơn; trong môi trường trang trọng có thể dùng ${purple("good morning")}.`,
        examples: [ex("Good morning, everyone. Let's begin.", "Chào buổi sáng mọi người. Chúng ta bắt đầu nhé.")],
      },
      {
        title: "Kết hợp chào hỏi với giới thiệu",
        body: `Khi gặp lần đầu, thường đi cặp ${purple("nice to meet you")} và động từ ${purple("introduce")}.`,
        examples: [ex("Nice to meet you. Let me introduce my manager.", "Rất vui được gặp bạn. Để tôi giới thiệu quản lý của tôi.")],
      },
      {
        title: "Khép lại cuộc trò chuyện lịch sự",
        body: `Các cụm như ${purple("take care")}, ${purple("have a nice day")} hoặc ${purple("safe trip")} giúp lời tạm biệt tự nhiên.`,
        examples: [ex("Goodbye, take care and text me later.", "Tạm biệt, giữ gìn nhé và nhắn tôi sau.")],
      },
    ],
    words: U69_WORDS,
    exercises: [
      mcq(
        69,
        1,
        "Cụm nào thường dùng khi chia tay và chúc ai đó giữ gìn?",
        [
          { key: "a", label: "How are you?" },
          { key: "b", label: "Take care." },
          { key: "c", label: "Nice to meet you." },
          { key: "d", label: "Good morning." },
        ],
        "b",
      ),
      fillBlank(
        69,
        2,
        "Welcome! Let me ____ my team to you.",
        "introduce",
        [
          { key: "a", label: "greet" },
          { key: "b", label: "introduce" },
          { key: "c", label: "farewell" },
          { key: "d", label: "see you" },
        ],
        "b",
      ),
    ],
  }),
  preUnit(70, {
    introVi: "Unit 70 giới thiệu tiền tố (prefixes) làm thay đổi nghĩa của từ gốc. Bạn sẽ đoán nghĩa từ mới tốt hơn và tránh hiểu sai trong đọc hiểu.",
    structureSections: [
      { label: "Negative and opposite", wordCount: 6 },
      { label: "Repeat and excess", wordCount: 6 },
      { label: "Position and relation", wordCount: 6 },
    ],
    collocationHtml: `${purple("misunderstand a message")}, ${purple("recheck data")} và ${purple("underestimate risk")} là các cụm thực tế của nhóm prefix.`,
    mistakeHtml: "Re- thường mang nghĩa 'làm lại', còn un- thường tạo nghĩa phủ định tính từ; không thể thay thế tùy ý.",
    principles: [
      {
        title: "Nhận diện prefix phủ định nhanh",
        body: `${purple("un-")}, ${purple("dis-")} và ${purple("anti-")} thường tạo nghĩa trái ngược hoặc phủ định.`,
        examples: [ex("He felt unhappy after the test.", "Anh ấy cảm thấy không vui sau bài kiểm tra.")],
      },
      {
        title: "Prefix chỉ làm lại hoặc sai lệch",
        body: `${purple("re-")} cho hành động lặp lại; ${purple("mis-")} cho hành động sai hoặc hiểu sai.`,
        examples: [ex("Please recheck the address to avoid mistakes.", "Hãy kiểm tra lại địa chỉ để tránh lỗi.")],
      },
      {
        title: "Prefix thể hiện mức độ quá hoặc thiếu",
        body: `${purple("over-")} diễn tả quá mức, còn ${purple("under-")} diễn tả thiếu hoặc thấp hơn thực tế.`,
        examples: [ex("Don't overcook the fish.", "Đừng nấu cá quá chín.")],
      },
    ],
    words: U70_WORDS,
    exercises: [
      mcq(
        70,
        1,
        "Từ nào mang nghĩa 'hiểu nhầm'?",
        [
          { key: "a", label: "rewrite" },
          { key: "b", label: "misunderstand" },
          { key: "c", label: "preview" },
          { key: "d", label: "coexist" },
        ],
        "b",
      ),
      fillBlank(
        70,
        2,
        "We should ____ this report before publishing.",
        "recheck",
        [
          { key: "a", label: "recheck" },
          { key: "b", label: "unknown" },
          { key: "c", label: "subway" },
          { key: "d", label: "anti-social" },
        ],
        "a",
      ),
    ],
  }),
  preUnit(71, {
    introVi: "Unit 71 tập trung hậu tố tạo danh từ từ tính từ, động từ hoặc danh từ gốc. Bạn sẽ mở rộng vốn từ học thuật và tăng độ chính xác khi viết.",
    structureSections: [
      { label: "Abstract nouns", wordCount: 6 },
      { label: "People and roles", wordCount: 6 },
      { label: "Actions and results", wordCount: 6 },
    ],
    collocationHtml: `${purple("show kindness")}, ${purple("good leadership")} và ${purple("make a decision")} là các cụm danh từ thông dụng.`,
    mistakeHtml: "Không phải mọi từ đều thêm -ness hoặc -tion được; cần nhớ dạng từ chuẩn thay vì suy đoán máy móc.",
    principles: [
      {
        title: "Nhóm hậu tố tạo danh từ trừu tượng",
        body: `Các hậu tố như -ness, -ship, -ty tạo danh từ ý niệm: ${purple("happiness")}, ${purple("friendship")}, ${purple("ability")}.`,
        examples: [ex("Kindness can change a classroom atmosphere.", "Lòng tốt có thể thay đổi bầu không khí lớp học.")],
      },
      {
        title: "Nhóm hậu tố chỉ người",
        body: `Các đuôi -er, -ee, -or thường tạo danh từ người như ${purple("teacher")}, ${purple("trainee")}, ${purple("visitor")}.`,
        examples: [ex("Each visitor must register at the desk.", "Mỗi khách đến phải đăng ký ở quầy.")],
      },
      {
        title: "Nhóm hậu tố biến động từ thành danh từ hành động",
        body: `${purple("decision")}, ${purple("discussion")} và ${purple("translation")} xuất hiện nhiều trong viết học thuật.`,
        examples: [ex("Our discussion led to a better decision.", "Cuộc thảo luận của chúng tôi dẫn tới quyết định tốt hơn.")],
      },
    ],
    words: U71_WORDS,
    exercises: [
      mcq(
        71,
        1,
        "Từ nào là danh từ trừu tượng chỉ 'lòng tốt'?",
        [
          { key: "a", label: "kindness" },
          { key: "b", label: "kind" },
          { key: "c", label: "kindly" },
          { key: "d", label: "visitor" },
        ],
        "a",
      ),
      fillBlank(
        71,
        2,
        "After careful ____, we chose the safer option.",
        "discussion",
        [
          { key: "a", label: "activity" },
          { key: "b", label: "discussion" },
          { key: "c", label: "teacher" },
          { key: "d", label: "membership" },
        ],
        "b",
      ),
    ],
  }),
  preUnit(72, {
    introVi: "Unit 72 trình bày hậu tố tạo tính từ, giúp bạn mô tả sự vật hiện tượng rõ hơn và đa dạng hơn. Chủ điểm rất quan trọng trong cả nói lẫn viết.",
    structureSections: [
      { label: "General descriptive adjectives", wordCount: 6 },
      { label: "Nature and weather adjectives", wordCount: 6 },
      { label: "Personal and practical adjectives", wordCount: 6 },
    ],
    collocationHtml: `${purple("useful advice")}, ${purple("friendly service")} và ${purple("affordable price")} là các kết hợp rất phổ biến.`,
    mistakeHtml: "Đuôi -ful và -less thường trái nghĩa ở một số cặp, nhưng không áp dụng cho mọi từ; cần học theo cụm thực tế.",
    principles: [
      {
        title: "Nhận diện hậu tố tính từ thông dụng",
        body: "Các đuôi -ful, -ous, -al, -y, -able giúp mở rộng nhanh kho tính từ.",
        examples: [ex("This guide is useful and practical.", "Hướng dẫn này hữu ích và thực tế.")],
      },
      {
        title: "Dùng tính từ thời tiết trong mô tả hằng ngày",
        body: `${purple("rainy")}, ${purple("sunny")}, ${purple("windy")} và ${purple("cloudy")} là bộ từ cần phản xạ nhanh.`,
        examples: [ex("It's windy today, so wear a jacket.", "Hôm nay nhiều gió nên hãy mặc áo khoác.")],
      },
      {
        title: "Ưu tiên tính từ sát ngữ cảnh dịch vụ",
        body: `Trong đánh giá sản phẩm/dịch vụ, các từ như ${purple("comfortable")}, ${purple("friendly")} và ${purple("affordable")} rất hữu ích.`,
        examples: [ex("The room was comfortable and affordable.", "Phòng vừa thoải mái vừa giá phải chăng.")],
      },
    ],
    words: U72_WORDS,
    exercises: [
      mcq(
        72,
        1,
        "Từ nào mô tả một thứ 'giá phải chăng'?",
        [
          { key: "a", label: "dangerous" },
          { key: "b", label: "affordable" },
          { key: "c", label: "noisy" },
          { key: "d", label: "nervous" },
        ],
        "b",
      ),
      fillBlank(
        72,
        2,
        "The staff were very ____ and helped us quickly.",
        "friendly",
        [
          { key: "a", label: "sunny" },
          { key: "b", label: "friendly" },
          { key: "c", label: "personal" },
          { key: "d", label: "careful" },
        ],
        "b",
      ),
    ],
  }),
  preUnit(73, {
    introVi: "Unit 73 tập trung danh từ ghép (compound nouns) thường gặp trong đời sống, học tập và công nghệ. Nắm vững nhóm này giúp bạn tăng tốc độ đọc và giao tiếp tự nhiên.",
    structureSections: [
      { label: "Daily personal items", wordCount: 6 },
      { label: "Home and place nouns", wordCount: 6 },
      { label: "Modern life compounds", wordCount: 6 },
    ],
    collocationHtml: `${purple("catch a bus at the bus stop")}, ${purple("pay by credit card")} và ${purple("work in a coffee shop")} là các cụm ứng dụng trực tiếp.`,
    mistakeHtml: "Một số compound nouns viết liền (toothbrush), một số viết tách (coffee shop). Cần học theo dạng chuẩn từng từ.",
    principles: [
      {
        title: "Nhận diện logic nghĩa của danh từ ghép",
        body: `Thường là danh từ 1 bổ nghĩa cho danh từ 2, ví dụ ${purple("raincoat")} là áo dùng cho mưa.`,
        examples: [ex("I need a raincoat for the trip.", "Tôi cần áo mưa cho chuyến đi.")],
      },
      {
        title: "Ghi nhớ theo nhóm chủ đề thay vì học rời rạc",
        body: `Học nhóm đồ cá nhân như ${purple("toothbrush")}, ${purple("hairdryer")} và nhóm địa điểm như ${purple("bookshop")}.`,
        examples: [ex("There is a bookshop near my bus stop.", "Có một hiệu sách gần trạm xe buýt của tôi.")],
      },
      {
        title: "Ưu tiên các compound nouns tần suất cao",
        body: `Trong đời sống số, ${purple("smartphone")}, ${purple("headphones")} và ${purple("credit card")} xuất hiện rất thường xuyên.`,
        examples: [ex("Most people pay by credit card now.", "Bây giờ đa số mọi người thanh toán bằng thẻ tín dụng.")],
      },
    ],
    words: U73_WORDS,
    exercises: [
      mcq(
        73,
        1,
        "Từ nào là danh từ ghép chỉ 'kính râm'?",
        [
          { key: "a", label: "sunrise" },
          { key: "b", label: "sunglasses" },
          { key: "c", label: "sunset" },
          { key: "d", label: "smartphone" },
        ],
        "b",
      ),
      fillBlank(
        73,
        2,
        "I forgot my ____ so I can't brush my teeth.",
        "toothbrush",
        [
          { key: "a", label: "toothbrush" },
          { key: "b", label: "notebook" },
          { key: "c", label: "raincoat" },
          { key: "d", label: "keyboard" },
        ],
        "a",
      ),
    ],
  }),
  preUnit(74, {
    introVi: "Unit 74 luyện word partners (collocations) để nói tự nhiên như người bản ngữ. Trọng tâm là các cặp động từ - danh từ có tần suất cao trong giao tiếp thực tế.",
    structureSections: [
      { label: "Action collocations", wordCount: 6 },
      { label: "Communication collocations", wordCount: 6 },
      { label: "Progress and responsibility", wordCount: 6 },
    ],
    collocationHtml: `${purple("make a decision")}, ${purple("pay attention")} và ${purple("take responsibility")} là ba cụm cốt lõi của unit.`,
    mistakeHtml: "Nên nói make a decision (không nói do a decision), take a break (không nói make a break) trong tiếng Anh chuẩn.",
    principles: [
      {
        title: "Học collocation theo cụm cố định",
        body: `Các cặp như ${purple("make a decision")} hoặc ${purple("take a break")} nên học nguyên cụm thay vì tách lẻ từng từ.`,
        examples: [ex("We need to make a decision before noon.", "Chúng ta cần đưa ra quyết định trước buổi trưa.")],
      },
      {
        title: "Ưu tiên cụm dùng trong học tập và công việc",
        body: `${purple("pay attention")}, ${purple("set an alarm")} và ${purple("save time")} rất hữu dụng trong thói quen hằng ngày.`,
        examples: [ex("Set an alarm so you don't miss class.", "Hãy đặt báo thức để không lỡ lớp.")],
      },
      {
        title: "Dùng collocation để câu gọn mà rõ",
        body: `Thay vì giải thích dài, dùng trực tiếp cụm như ${purple("keep in touch")} hoặc ${purple("run out of")}.`,
        examples: [ex("Let's keep in touch after this course.", "Chúng ta hãy giữ liên lạc sau khóa học này.")],
      },
    ],
    words: U74_WORDS,
    exercises: [
      mcq(
        74,
        1,
        "Cụm nào đúng theo collocation tự nhiên?",
        [
          { key: "a", label: "do a decision" },
          { key: "b", label: "make a decision" },
          { key: "c", label: "have a responsibility" },
          { key: "d", label: "save a break" },
        ],
        "b",
      ),
      fillBlank(
        74,
        2,
        "Please ____ to the safety instructions before we start.",
        "pay attention",
        [
          { key: "a", label: "pay attention" },
          { key: "b", label: "waste money" },
          { key: "c", label: "run out of" },
          { key: "d", label: "tell the truth" },
        ],
        "a",
      ),
    ],
  }),
  preUnit(75, {
    introVi: "Unit 75 tổng hợp fixed phrases dùng cực thường xuyên trong nói và viết. Bạn sẽ cải thiện độ trôi chảy bằng các cụm nối ý và cụm thời gian chuẩn tự nhiên.",
    structureSections: [
      { label: "Time and sequence phrases", wordCount: 6 },
      { label: "Linking and clarification", wordCount: 6 },
      { label: "Tone and intention", wordCount: 6 },
    ],
    collocationHtml: `${purple("as soon as possible")}, ${purple("in other words")} và ${purple("all of a sudden")} giúp diễn đạt mạch lạc hơn.`,
    mistakeHtml: "On time là đúng giờ theo kế hoạch; in time là kịp lúc trước khi quá muộn. Hai cụm này không hoàn toàn giống nhau.",
    principles: [
      {
        title: "Dùng cụm cố định để nối mạch ý",
        body: `Các cụm như ${purple("for example")}, ${purple("in fact")} và ${purple("in other words")} làm câu nói rõ và logic hơn.`,
        examples: [ex("In fact, this method is simpler.", "Thực ra, cách này đơn giản hơn.")],
      },
      {
        title: "Phân biệt cụm thời gian gần nghĩa",
        body: `${purple("on time")} nhấn mạnh đúng giờ, còn ${purple("in time")} nhấn mạnh kịp trước hạn.`,
        examples: [ex("We arrived in time for the meeting.", "Chúng tôi đến kịp cuộc họp.")],
      },
      {
        title: "Điều chỉnh sắc thái câu bằng fixed phrases",
        body: `${purple("to be honest")} tạo sắc thái thẳng thắn; ${purple("by the way")} dùng để chuyển nhẹ sang ý mới.`,
        examples: [ex("By the way, did you send the report?", "Nhân tiện, bạn đã gửi báo cáo chưa?")],
      },
    ],
    words: U75_WORDS,
    exercises: [
      mcq(
        75,
        1,
        "Cụm nào có nghĩa là 'càng sớm càng tốt'?",
        [
          { key: "a", label: "at first" },
          { key: "b", label: "for now" },
          { key: "c", label: "as soon as possible" },
          { key: "d", label: "once in a while" },
        ],
        "c",
      ),
      fillBlank(
        75,
        2,
        "We arrived just ____ to catch the last train.",
        "in time",
        [
          { key: "a", label: "on purpose" },
          { key: "b", label: "in time" },
          { key: "c", label: "at the moment" },
          { key: "d", label: "for example" },
        ],
        "b",
      ),
    ],
  }),
];
