import type { VocabularyExercise } from "@/lib/vocabulary/vocabulary-unit-types";
import { CURATED_EXERCISE_PROMPT_VI } from "@/lib/vocabulary/units/eviu-elementary-curated-prompt-vi";
import { CURATED_UNITS_16_30 } from "@/lib/vocabulary/units/eviu-elementary-curated-exercises-16-30";
import { CURATED_UNITS_31_45 } from "@/lib/vocabulary/units/eviu-elementary-curated-exercises-31-45";
import { CURATED_UNITS_46_60 } from "@/lib/vocabulary/units/eviu-elementary-curated-exercises-46-60";
import { CURATED_EXERCISE_PROMPT_VI_16_30 } from "@/lib/vocabulary/units/eviu-elementary-curated-prompt-vi-16-30";
import { CURATED_EXERCISE_PROMPT_VI_31_45 } from "@/lib/vocabulary/units/eviu-elementary-curated-prompt-vi-31-45";
import { CURATED_EXERCISE_PROMPT_VI_46_60 } from "@/lib/vocabulary/units/eviu-elementary-curated-prompt-vi-46-60";
import {
  applyExercisePromptVi,
  assertExerciseCount,
  cloze,
  match,
  mcq,
} from "./eviu-elementary-curated-helpers";

const UNIT_1: VocabularyExercise[] = [
  cloze("ex-1-1-1", "1.1 · Gia đình", "Kavita is Ravi's ___.", "sister", ["Sister"]),
  cloze("ex-1-1-2", "1.1 · Gia đình", "Ravi is Kavita's ___.", "brother"),
  cloze("ex-1-1-3", "1.1 · Gia đình", "Anne is Kavita's ___.", "aunt"),
  cloze("ex-1-1-4", "1.1 · Gia đình", "Ivan is Ravi's ___.", "uncle"),
  cloze("ex-1-1-5", "1.1 · Gia đình", "Diana is Ravi's ___.", "grandmother"),
  cloze("ex-1-1-6", "1.1 · Gia đình", "Henry is Kavita's ___.", "grandfather"),
  cloze("ex-1-1-7", "1.1 · Gia đình", "Ravi is Ivan's ___.", "nephew"),
  cloze("ex-1-1-8", "1.1 · Gia đình", "Kavita is Ivan's ___.", "niece"),
  cloze("ex-1-1-9", "1.1 · Gia đình", "Meena is Kavita's ___.", "mother"),
  cloze("ex-1-1-10", "1.1 · Gia đình", "Meena is George's ___.", "wife"),
  cloze("ex-1-1-11", "1.1 · Gia đình", "Karen is Ravi's ___.", "cousin"),
  cloze("ex-1-2-1", "1.2 · Gia đình mở rộng", "Sanjay is Kavita and Ravi's ___.", "uncle"),
  cloze("ex-1-2-2", "1.2 · Gia đình mở rộng", "Sanjay's wife is their ___.", "aunt"),
  cloze("ex-1-2-3", "1.2 · Gia đình mở rộng", "Prem is an ___.", "only child", ["Only child"]),
  cloze("ex-1-2-4", "1.2 · Gia đình mở rộng", "Alexander is Henry's ___.", "father"),
  cloze("ex-1-2-5", "1.2 · Gia đình mở rộng", "Leila is Henry's ___.", "mother"),
  cloze("ex-1-2-6", "1.2 · Gia đình mở rộng", "Alexander and Leila have three ___ — Amelia, Ivan and George.", "children"),
  cloze("ex-1-2-7", "1.2 · Gia đình mở rộng", "Ivan and George and their ___, Anne and Meena, love their grandparents.", "wives"),
  cloze("ex-1-2-8", "1.2 · Gia đình mở rộng", "They love their ___ and visit them as often as possible.", "grandparents"),
  cloze("ex-1-2-9", "1.2 · Gia đình mở rộng", "They also visit their ___ (parents is also possible).", "grandparents"),
];

const UNIT_2: VocabularyExercise[] = [
  mcq(
    "ex-2-2-2",
    "2.2 · Tìm từ",
    "The name for a man on his wedding day is ___",
    "a",
    [
      { key: "a", label: "groom" },
      { key: "b", label: "bride" },
      { key: "c", label: "widow" },
      { key: "d", label: "funeral" },
    ],
  ),
  mcq(
    "ex-2-2-3",
    "2.2 · Tìm từ",
    "What you are if you haven't got a partner:",
    "b",
    [
      { key: "a", label: "married" },
      { key: "b", label: "single" },
      { key: "c", label: "divorced" },
      { key: "d", label: "widowed" },
    ],
  ),
  mcq(
    "ex-2-2-4",
    "2.2 · Tìm từ",
    "To be 57 kilograms is to ___",
    "c",
    [
      { key: "a", label: "die" },
      { key: "b", label: "marry" },
      { key: "c", label: "weigh" },
      { key: "d", label: "born" },
    ],
  ),
  mcq(
    "ex-2-2-5",
    "2.2 · Tìm từ",
    "What you are if your marriage has legally ended:",
    "d",
    [
      { key: "a", label: "single" },
      { key: "b", label: "engaged" },
      { key: "c", label: "widowed" },
      { key: "d", label: "divorced" },
    ],
  ),
  mcq(
    "ex-2-2-6",
    "2.2 · Tìm từ",
    "A religious service for a dead person:",
    "a",
    [
      { key: "a", label: "funeral" },
      { key: "b", label: "wedding" },
      { key: "c", label: "honeymoon" },
      { key: "d", label: "anniversary" },
    ],
  ),
  mcq(
    "ex-2-2-7",
    "2.2 · Tìm từ",
    "A holiday after a wedding:",
    "b",
    [
      { key: "a", label: "funeral" },
      { key: "b", label: "honeymoon" },
      { key: "c", label: "birth" },
      { key: "d", label: "death" },
    ],
  ),
  mcq(
    "ex-2-2-8",
    "2.2 · Tìm từ",
    "What you are if your husband or wife dies:",
    "c",
    [
      { key: "a", label: "divorced" },
      { key: "b", label: "single" },
      { key: "c", label: "widowed" },
      { key: "d", label: "married" },
    ],
  ),
  cloze("ex-2-3-1", "2.3 · Giới từ", "In 2003 Anne got married ___ Daniel Smith.", "to"),
  cloze("ex-2-3-2", "2.3 · Giới từ", "Lydia Smith died ___ old age soon after their wedding.", "of"),
  cloze("ex-2-3-3", "2.3 · Giới từ", "Daniel and Anne were ___ their honeymoon when she died.", "on"),
  cloze("ex-2-3-4", "2.3 · Giới từ", "Anne's baby daughter was ___ two years later.", "born", ["Born"]),
  cloze("ex-2-3-5", "2.3 · Giới từ", "They called the baby Lydia, ___ Daniel's grandmother.", "after", ["After"]),
  cloze(
    "ex-2-4-2",
    "2.4 · Sinh và mất",
    "Christopher Columbus was born in 1451 and ___ in 1506.",
    "died",
    ["Died"],
  ),
  cloze(
    "ex-2-4-3",
    "2.4 · Sinh và mất",
    "Leonardo da Vinci was born in 1452 and ___ in 1519.",
    "died",
    ["Died"],
  ),
  cloze(
    "ex-2-4-4",
    "2.4 · Sinh và mất",
    "Princess Diana was born in 1961 and ___ in 1997.",
    "died",
    ["Died"],
  ),
  cloze("ex-2-5-1", "2.5 · died / dead / death", "Kelly's grandfather ___ last year.", "died", ["Died"]),
  cloze("ex-2-5-2", "2.5 · died / dead / death", "His ___ made her very sad.", "death", ["Death"]),
  cloze("ex-2-5-3", "2.5 · died / dead / death", "Her grandmother has been ___ for five years now.", "dead", ["Dead"]),
  cloze("ex-2-5-4", "2.5 · died / dead / death", "She ___ of a heart attack.", "died", ["Died"]),
  cloze("ex-2-5-5", "2.5 · died / dead / death", "Now all Kelly's grandparents are ___.", "dead", ["Dead"]),
];

const UNIT_4: VocabularyExercise[] = [
  match("ex-4-2", "4.2 · Ghép quần áo với bộ phận cơ thể", [
    { left: "belt", right: "waist" },
    { left: "hat", right: "head" },
    { left: "glove", right: "hand" },
    { left: "glasses", right: "eyes" },
    { left: "scarf", right: "neck" },
    { left: "shoe", right: "foot" },
    { left: "tights", right: "legs" },
  ]),
  cloze("ex-4-3-1", "4.3 · Động từ", "Tim's jeans ___ blue and his T-shirt ___ red.", "are", ["Are"]),
  cloze("ex-4-3-2", "4.3 · Động từ", "Julia ___ jeans and a T-shirt today.", "is wearing", ["Is wearing"]),
  cloze("ex-4-3-3", "4.3 · Động từ", "Meena ___ got a red coat on and she ___ some flowers.", "has", ["Has"]),
  cloze("ex-4-3-4", "4.3 · Động từ", "Sarah's dress ___ old but her shoes ___ new.", "is", ["Is"]),
  cloze("ex-4-3-5", "4.3 · Động từ", "Last year Harry's trousers ___ white. Now they ___ grey.", "were", ["Were"]),
  cloze("ex-4-3-6", "4.3 · Động từ", "___ this a new pair of jeans?", "Is"),
  cloze("ex-4-3-7", "4.3 · Động từ", "My favourite pyjamas ___ dark green.", "are", ["Are"]),
  cloze("ex-4-3-8", "4.3 · Động từ", "Kim ___ a new pair of shorts.", "has", ["Has"]),
  cloze("ex-4-4-2", "4.4 · Hoàn thành câu", "It's cold — I need my ___.", "jumper", ["Jumper"]),
  cloze("ex-4-4-3", "4.4 · Hoàn thành câu", "Take an ___ — it might rain.", "umbrella", ["Umbrella"]),
  cloze("ex-4-4-4", "4.4 · Hoàn thành câu", "She wore a blue ___ to the party.", "skirt", ["Skirt"]),
  cloze("ex-4-4-5", "4.4 · Hoàn thành câu", "He packed his ___ for the trip.", "suitcase", ["Suitcase"]),
  cloze("ex-4-4-6", "4.4 · Hoàn thành câu", "Check the time on your ___.", "watch", ["Watch"]),
  cloze("ex-4-4-7", "4.4 · Hoàn thành câu", "He wore a white ___ to work.", "shirt", ["Shirt"]),
  cloze("ex-4-4-8", "4.4 · Hoàn thành câu", "Put on your ___ — it's freezing.", "coat", ["Coat"]),
  cloze("ex-4-4-9", "4.4 · Hoàn thành câu", "She bought new winter ___.", "boots", ["Boots"]),
  cloze("ex-4-6-1", "4.6 · Mô tả trang phục", "Joe is wearing a smart ___, a white shirt and a tie.", "suit", ["Suit"]),
];

const UNIT_5: VocabularyExercise[] = [
  cloze("ex-5-1-1", "5.1 · Mô tả người", "He's only 1 metre 52. He's quite ___.", "short", ["Short"]),
  cloze("ex-5-1-2", "5.1 · Mô tả người", "Very ___ people are often good at basketball.", "tall", ["Tall"]),
  cloze("ex-5-1-3", "5.1 · Mô tả người", "Models are usually ___.", "slim", ["Slim", "thin", "Thin"]),
  cloze("ex-5-1-4", "5.1 · Mô tả người", "Does she have dark skin? No, it's ___.", "fair", ["Fair"]),
  cloze("ex-5-1-5", "5.1 · Mô tả người", "She's only seven. She's very ___.", "young", ["Young"]),
  cloze("ex-5-1-6", "5.1 · Mô tả người", "If I eat too much I'll be ___.", "overweight", ["Overweight", "fat", "Fat"]),
  cloze("ex-5-1-7", "5.1 · Mô tả người", "My grandmother is in this hospital for ___ people.", "elderly", ["Elderly"]),
  cloze("ex-5-2-1", "5.2 · Câu hỏi", "___ Elena's hair blonde / fair?", "Is"),
  cloze("ex-5-2-2", "5.2 · Câu hỏi", "___ Mike's hair long?", "Is"),
  cloze("ex-5-2-3", "5.2 · Câu hỏi", "___ your parents elderly?", "Are"),
  cloze("ex-5-2-4", "5.2 · Câu hỏi", "___ his sister pretty / beautiful?", "Is"),
  cloze("ex-5-2-5", "5.2 · Câu hỏi", "Why ___ Sara so thin?", "is", ["Is"]),
  cloze("ex-5-3-1", "5.3 · Mô tả ảnh", "Felicity's got blonde hair and ___ skin.", "fair", ["Fair"]),
  cloze("ex-5-3-2", "5.3 · Mô tả ảnh", "Jeff has short fair hair and a ___.", "beard", ["Beard"]),
  cloze("ex-5-4-1", "5.4 · Câu hỏi", "How ___ is your brother?", "tall", ["Tall"]),
  cloze("ex-5-4-2", "5.4 · Câu hỏi", "What does your teacher ___ like?", "look", ["Look"]),
  cloze("ex-5-4-3", "5.4 · Câu hỏi", "How much do you ___?", "weigh", ["Weigh"]),
  cloze("ex-5-4-4", "5.4 · Câu hỏi", "How ___ is your mother?", "old", ["Old"]),
  cloze("ex-5-4-5", "5.4 · Câu hỏi", "How tall is your ___?", "sister", ["Sister"]),
];

const UNIT_6: VocabularyExercise[] = [
  cloze("ex-6-1-1", "6.1 · Hội thoại", "A: How are you today? B: ___, thanks.", "Very well", ["I'm very well", "I am very well"]),
  cloze("ex-6-1-2", "6.1 · Hội thoại", "A: Are you OK? B: No, I feel ___.", "sick", ["Sick", "ill", "Ill"]),
  cloze("ex-6-1-3", "6.1 · Hội thoại", "A: I feel ___. B: I'll get a doctor.", "ill", ["Ill", "sick", "Sick"]),
  cloze("ex-6-1-4", "6.1 · Hội thoại", "A: I've got ___. B: Here's the dentist's phone number.", "toothache", ["Toothache"]),
  cloze("ex-6-1-5", "6.1 · Hội thoại", "A: Your nose is red. Have you got ___? B: Yes.", "a cold", ["A cold"]),
  match("ex-6-2", "6.2 · Ghép bệnh với cách xử trí", [
    { left: "a headache", right: "take an aspirin" },
    { left: "toothache", right: "go to the dentist" },
    { left: "a heart attack", right: "go to hospital" },
    { left: "a cold", right: "go to bed with a hot drink" },
  ]),
  cloze("ex-6-3-2", "6.3 · Bệnh", "Bad drinking water can cause ___.", "cholera", ["Cholera"]),
  cloze("ex-6-3-3", "6.3 · Bệnh", "Pollution and traffic fumes are linked to ___.", "asthma", ["Asthma"]),
  cloze("ex-6-3-4", "6.3 · Bệnh", "Grass and flowers in summer can cause ___.", "hay fever", ["Hay fever"]),
  cloze("ex-6-3-5", "6.3 · Bệnh", "Smoking and an unhealthy diet are linked to ___.", "cancer", ["Cancer"]),
  cloze("ex-6-w1", "6 · Từ vựng", "I've got a ___. I need to go to the dentist.", "toothache", ["Toothache"]),
  cloze("ex-6-w2", "6 · Từ vựng", "I went to bed with a hot drink. I've got ___.", "a cold", ["A cold"]),
  cloze("ex-6-w3", "6 · Từ vựng", "My father had a ___ and went to hospital.", "heart attack", ["Heart attack"]),
  cloze("ex-6-w4", "6 · Từ vựng", "Every summer I start sneezing — I get ___.", "hay fever", ["Hay fever"]),
  cloze("ex-6-w5", "6 · Từ vựng", "Swimming and cycling are good ___ for you.", "exercise", ["Exercise"]),
  cloze("ex-6-w6", "6 · Từ vựng", "I feel ___ when I have too much work.", "stressed", ["Stressed"]),
  cloze("ex-6-w7", "6 · Từ vựng", "Mosquitoes can give people ___.", "malaria", ["Malaria"]),
  cloze("ex-6-w8", "6 · Từ vựng", "Eat lots of fruit and vegetables for a ___ diet.", "healthy", ["Healthy"]),
];

const UNIT_7: VocabularyExercise[] = [
  mcq(
    "ex-7-4-2",
    "7.4 · Cảm xúc",
    "Nicholas is holding an empty glass. How does he feel?",
    "b",
    [
      { key: "a", label: "hungry" },
      { key: "b", label: "thirsty" },
      { key: "c", label: "tired" },
      { key: "d", label: "surprised" },
    ],
  ),
  mcq(
    "ex-7-4-3",
    "7.4 · Cảm xúc",
    "Max is wearing a coat and shivering. How does he feel?",
    "a",
    [
      { key: "a", label: "cold" },
      { key: "b", label: "hot" },
      { key: "c", label: "angry" },
      { key: "d", label: "well" },
    ],
  ),
  mcq(
    "ex-7-4-4",
    "7.4 · Cảm xúc",
    "Sunita is yawning. How does she feel?",
    "c",
    [
      { key: "a", label: "hungry" },
      { key: "b", label: "surprised" },
      { key: "c", label: "tired" },
      { key: "d", label: "ill" },
    ],
  ),
  mcq(
    "ex-7-4-5",
    "7.4 · Cảm xúc",
    "Fiona's eyes are wide open. How does she feel?",
    "d",
    [
      { key: "a", label: "sad" },
      { key: "b", label: "angry" },
      { key: "c", label: "thirsty" },
      { key: "d", label: "surprised" },
    ],
  ),
  mcq(
    "ex-7-4-6",
    "7.4 · Cảm xúc",
    "The children are sweating in the sun. How do they feel?",
    "b",
    [
      { key: "a", label: "cold" },
      { key: "b", label: "hot" },
      { key: "c", label: "upset" },
      { key: "d", label: "well" },
    ],
  ),
  cloze(
    "ex-7-5-1",
    "7.5 · Sửa lỗi",
    "I very like basketball. → I like basketball ___.",
    "very much",
    ["Very much"],
  ),
  cloze(
    "ex-7-5-2",
    "7.5 · Sửa lỗi",
    "I am happy for my sister's good news. → I am happy ___ my sister's good news.",
    "about",
    ["About"],
  ),
  cloze(
    "ex-7-5-3",
    "7.5 · Sửa lỗi",
    "The teacher wants that we learn these words. → The teacher wants ___ to learn these words.",
    "us",
    ["Us"],
  ),
  cloze(
    "ex-7-5-4",
    "7.5 · Sửa lỗi",
    "I like really spiders. → I ___ like spiders.",
    "really",
    ["Really"],
  ),
  cloze(
    "ex-7-5-5",
    "7.5 · Sửa lỗi",
    "I'm very happy about him. → I'm very happy ___ him.",
    "for",
    ["For"],
  ),
  cloze(
    "ex-7-5-6",
    "7.5 · Sửa lỗi",
    "My parents want that I go to university. → My parents want ___ to go to university.",
    "me",
    ["Me"],
  ),
  cloze(
    "ex-7-5-7",
    "7.5 · Sửa lỗi",
    "How for you? → How ___ you?",
    "about",
    ["About"],
  ),
  cloze(
    "ex-7-5-8",
    "7.5 · Sửa lỗi",
    "Priya is bit tired. → Priya is ___ tired this morning.",
    "a bit",
    ["A bit", "a little", "A little"],
  ),
  mcq(
    "ex-7-p1",
    "7.2 · So sánh",
    "Which do you prefer — tea or coffee? Best answer:",
    "a",
    [
      { key: "a", label: "I prefer coffee to tea." },
      { key: "b", label: "I prefer tea than coffee." },
      { key: "c", label: "I prefer coffee from tea." },
      { key: "d", label: "I more prefer coffee." },
    ],
  ),
  mcq(
    "ex-7-p2",
    "7 · Cảm xúc",
    "I ___ horror films. (không thích)",
    "b",
    [
      { key: "a", label: "love" },
      { key: "b", label: "don't like" },
      { key: "c", label: "prefer" },
      { key: "d", label: "hope" },
    ],
  ),
  mcq(
    "ex-7-p3",
    "7 · Cảm xúc",
    "I ___ my exam goes well.",
    "c",
    [
      { key: "a", label: "want" },
      { key: "b", label: "hate" },
      { key: "c", label: "hope" },
      { key: "d", label: "prefer" },
    ],
  ),
  mcq(
    "ex-7-p4",
    "7 · Cảm xúc",
    "I ___ coffee to tea.",
    "a",
    [
      { key: "a", label: "prefer" },
      { key: "b", label: "hope" },
      { key: "c", label: "want" },
      { key: "d", label: "hate" },
    ],
  ),
  mcq(
    "ex-7-p5",
    "7 · Cảm xúc",
    "Spiders? I ___ them!",
    "d",
    [
      { key: "a", label: "love" },
      { key: "b", label: "like" },
      { key: "c", label: "prefer" },
      { key: "d", label: "hate" },
    ],
  ),
];

const UNIT_8: VocabularyExercise[] = [
  mcq(
    "ex-8-1-1",
    "8.1 · Chào hỏi",
    "A sneezes. B says:",
    "a",
    [
      { key: "a", label: "Bless you!" },
      { key: "b", label: "Happy Birthday!" },
      { key: "c", label: "Good luck!" },
      { key: "d", label: "Cheers!" },
    ],
  ),
  mcq(
    "ex-8-1-2",
    "8.1 · Chào hỏi",
    "A: I'm taking my driving test today. B:",
    "c",
    [
      { key: "a", label: "Congratulations!" },
      { key: "b", label: "Happy Birthday!" },
      { key: "c", label: "Good luck!" },
      { key: "d", label: "Goodnight." },
    ],
  ),
  mcq(
    "ex-8-1-3",
    "8.1 · Chào hỏi",
    "A: I passed my driving test! B:",
    "b",
    [
      { key: "a", label: "Good luck!" },
      { key: "b", label: "Congratulations!" },
      { key: "c", label: "Bless you!" },
      { key: "d", label: "Sleep well." },
    ],
  ),
  mcq(
    "ex-8-1-4",
    "8.1 · Chào hỏi",
    "A: Goodbye. B:",
    "a",
    [
      { key: "a", label: "Goodbye. See you soon!" },
      { key: "b", label: "Good morning!" },
      { key: "c", label: "Happy Christmas!" },
      { key: "d", label: "Well done!" },
    ],
  ),
  mcq(
    "ex-8-1-5",
    "8.1 · Chào hỏi",
    "A: It's my birthday today. B:",
    "d",
    [
      { key: "a", label: "Congratulations!" },
      { key: "b", label: "Good luck!" },
      { key: "c", label: "Good afternoon." },
      { key: "d", label: "Happy Birthday!" },
    ],
  ),
  mcq(
    "ex-8-1-6",
    "8.1 · Chào hỏi",
    "A: How are you? B:",
    "b",
    [
      { key: "a", label: "Goodbye." },
      { key: "b", label: "Fine, thanks. And you?" },
      { key: "c", label: "Happy New Year!" },
      { key: "d", label: "Excuse me!" },
    ],
  ),
  mcq(
    "ex-8-3-1",
    "8.3 · Nói gì?",
    "You want to go through a doorway. People are blocking it. You say:",
    "a",
    [
      { key: "a", label: "Excuse me!" },
      { key: "b", label: "Good luck!" },
      { key: "c", label: "Bless you!" },
      { key: "d", label: "Well done!" },
    ],
  ),
  mcq(
    "ex-8-3-2",
    "8.3 · Nói gì?",
    "A friend buys you a drink. You say:",
    "c",
    [
      { key: "a", label: "Goodnight." },
      { key: "b", label: "Happy Birthday!" },
      { key: "c", label: "Thank you! / Cheers!" },
      { key: "d", label: "Sorry!" },
    ],
  ),
  mcq(
    "ex-8-3-3",
    "8.3 · Nói gì?",
    "A child says 'Goodnight' to you. You reply:",
    "b",
    [
      { key: "a", label: "Good morning!" },
      { key: "b", label: "Goodnight. Sleep well." },
      { key: "c", label: "Hello!" },
      { key: "d", label: "Congratulations!" },
    ],
  ),
  mcq(
    "ex-8-3-4",
    "8.3 · Nói gì?",
    "You answer the phone at work at 10.30 am. You say:",
    "d",
    [
      { key: "a", label: "Good evening." },
      { key: "b", label: "Goodnight." },
      { key: "c", label: "Good afternoon." },
      { key: "d", label: "Good morning." },
    ],
  ),
  mcq(
    "ex-8-3-5",
    "8.3 · Nói gì?",
    "You answer the phone at work at 3 pm. You say:",
    "a",
    [
      { key: "a", label: "Good afternoon." },
      { key: "b", label: "Good morning." },
      { key: "c", label: "Goodnight." },
      { key: "d", label: "Happy Birthday!" },
    ],
  ),
  mcq(
    "ex-8-3-6",
    "8.3 · Nói gì?",
    "It is 2 am on 1st January. You meet a friend. You say:",
    "c",
    [
      { key: "a", label: "Happy Christmas!" },
      { key: "b", label: "Good afternoon." },
      { key: "c", label: "Happy New Year!" },
      { key: "d", label: "Good luck!" },
    ],
  ),
  mcq(
    "ex-8-3-7",
    "8.3 · Nói gì?",
    "On a crowded bus you stand on someone's foot. You say:",
    "b",
    [
      { key: "a", label: "Well done!" },
      { key: "b", label: "Sorry!" },
      { key: "c", label: "Cheers!" },
      { key: "d", label: "Bless you!" },
    ],
  ),
  mcq(
    "ex-8-3-8",
    "8.3 · Nói gì?",
    "It is 24th December. You meet a friend on the bus. You say:",
    "d",
    [
      { key: "a", label: "Happy New Year!" },
      { key: "b", label: "Happy Birthday!" },
      { key: "c", label: "Good luck!" },
      { key: "d", label: "Happy Christmas!" },
    ],
  ),
  mcq(
    "ex-8-2-1",
    "8.2 · Trong ảnh",
    "Someone wants to get your attention quietly. They say:",
    "c",
    [
      { key: "a", label: "Goodbye." },
      { key: "b", label: "Sleep well." },
      { key: "c", label: "Excuse me!" },
      { key: "d", label: "Well done!" },
    ],
  ),
  mcq(
    "ex-8-2-2",
    "8.2 · Trong ảnh",
    "Someone is leaving. They say:",
    "a",
    [
      { key: "a", label: "Goodbye." },
      { key: "b", label: "Bless you!" },
      { key: "c", label: "Good luck!" },
      { key: "d", label: "Happy Birthday!" },
    ],
  ),
  mcq(
    "ex-8-2-3",
    "8.2 · Trong ảnh",
    "Someone achieved something special. You say:",
    "b",
    [
      { key: "a", label: "Sorry!" },
      { key: "b", label: "Congratulations! / Well done!" },
      { key: "c", label: "Goodnight." },
      { key: "d", label: "Excuse me!" },
    ],
  ),
  mcq(
    "ex-8-2-4",
    "8.2 · Trong ảnh",
    "You meet someone in the morning. You say:",
    "d",
    [
      { key: "a", label: "Goodnight." },
      { key: "b", label: "Goodbye." },
      { key: "c", label: "Happy Birthday!" },
      { key: "d", label: "Hello! / Hi!" },
    ],
  ),
  mcq(
    "ex-8-4-1",
    "8.4 · Hội thoại",
    "Ann: Good evening. You reply:",
    "a",
    [
      { key: "a", label: "Hello." },
      { key: "b", label: "Goodbye." },
      { key: "c", label: "Goodnight." },
      { key: "d", label: "Bless you!" },
    ],
  ),
  mcq(
    "ex-8-4-2",
    "8.4 · Hội thoại",
    "Ann: It's my birthday today. You say:",
    "c",
    [
      { key: "a", label: "Congratulations!" },
      { key: "b", label: "Good luck!" },
      { key: "c", label: "Happy Birthday!" },
      { key: "d", label: "Well done!" },
    ],
  ),
];

const UNIT_9: VocabularyExercise[] = [
  cloze("ex-9-1-1", "9.1 · Từ hữu ích", "It's boring here. Let's go somewhere ___.", "else", ["Else"]),
  cloze("ex-9-1-2", "9.1 · Từ hữu ích", "There were ___ 20 people at the lecture.", "around", ["Around"]),
  cloze("ex-9-1-3", "9.1 · Từ hữu ích", "It's a ___ good photo!", "really", ["Really"]),
  cloze("ex-9-1-4", "9.1 · Từ hữu ích", "Would you like anything ___?", "else", ["Else"]),
  cloze("ex-9-1-5", "9.1 · Từ hữu ích", "He said he was a doctor but he's ___ a medical student.", "actually", ["Actually"]),
  cloze("ex-9-1-6", "9.1 · Từ hữu ích", "The journey takes ___ two hours.", "around", ["Around"]),
  mcq(
    "ex-9-2-1",
    "9.2 · Chọn đáp án",
    "I don't like skiing and ___ I'm not free that weekend.",
    "b",
    [
      { key: "a", label: "about" },
      { key: "b", label: "anyway" },
      { key: "c", label: "else" },
      { key: "d", label: "around" },
    ],
  ),
  mcq(
    "ex-9-2-2",
    "9.2 · Chọn đáp án",
    "I don't ___ what we do. It's all the same to me.",
    "a",
    [
      { key: "a", label: "mind" },
      { key: "b", label: "matter" },
      { key: "c", label: "agree" },
      { key: "d", label: "really" },
    ],
  ),
  mcq(
    "ex-9-2-3",
    "9.2 · Chọn đáp án",
    "___ invite Rachel to dinner tonight?",
    "b",
    [
      { key: "a", label: "It's up to you" },
      { key: "b", label: "Let's" },
      { key: "c", label: "I agree" },
      { key: "d", label: "Anyway" },
    ],
  ),
  mcq(
    "ex-9-2-4",
    "9.2 · Chọn đáp án",
    "___ in London. There's lots of traffic there.",
    "a",
    [
      { key: "a", label: "Be careful" },
      { key: "b", label: "What a pity" },
      { key: "c", label: "Oh dear" },
      { key: "d", label: "Well done" },
    ],
  ),
  mcq(
    "ex-9-2-5",
    "9.2 · Chọn đáp án",
    "I don't have time to go to the cinema and ___ I've seen that film already.",
    "c",
    [
      { key: "a", label: "really" },
      { key: "b", label: "absolutely" },
      { key: "c", label: "anyway" },
      { key: "d", label: "else" },
    ],
  ),
  mcq(
    "ex-9-3-1",
    "9.3 · Tình huống",
    "___ I didn't get that job.",
    "a",
    [
      { key: "a", label: "Oh dear!" },
      { key: "b", label: "Hurry up!" },
      { key: "c", label: "Look out!" },
      { key: "d", label: "Absolutely!" },
    ],
  ),
  mcq(
    "ex-9-3-2",
    "9.3 · Tình huống",
    "Do you want to go to the party or not?",
    "c",
    [
      { key: "a", label: "Well done!" },
      { key: "b", label: "What a pity!" },
      { key: "c", label: "It's up to you." },
      { key: "d", label: "Look out!" },
    ],
  ),
  mcq(
    "ex-9-3-3",
    "9.3 · Tình huống",
    "I passed my exam!",
    "b",
    [
      { key: "a", label: "Oh dear!" },
      { key: "b", label: "Well done!" },
      { key: "c", label: "Hurry up!" },
      { key: "d", label: "What a pity!" },
    ],
  ),
  mcq(
    "ex-9-3-4",
    "9.3 · Tình huống",
    "The taxi's here — we need to leave now!",
    "d",
    [
      { key: "a", label: "It's up to you." },
      { key: "b", label: "What a pity!" },
      { key: "c", label: "Oh dear!" },
      { key: "d", label: "Hurry up!" },
    ],
  ),
  cloze(
    "ex-9-4-1",
    "9.4 · Sửa hội thoại",
    "Well made! → Well ___!",
    "done",
    ["Done"],
  ),
  cloze(
    "ex-9-4-2",
    "9.4 · Sửa hội thoại",
    "How about go out → How about ___ out",
    "going",
    ["Going"],
  ),
  cloze(
    "ex-9-4-3",
    "9.4 · Sửa hội thoại",
    "Let go to → Let's ___ to",
    "go",
    ["Go"],
  ),
  cloze(
    "ex-9-4-4",
    "9.4 · Sửa hội thoại",
    "it isn't matter → it doesn't ___",
    "matter",
    ["Matter"],
  ),
  cloze(
    "ex-9-4-5",
    "9.4 · Sửa hội thoại",
    "Why don't we going → Why don't we ___",
    "go",
    ["Go"],
  ),
];

const UNIT_11: VocabularyExercise[] = [
  mcq(
    "ex-11-1-1",
    "11.1 · Đúng hay sai?",
    "You use a frying pan to drink out of.",
    "b",
    [
      { key: "a", label: "Đúng" },
      { key: "b", label: "Sai — dùng cup / mug / glass" },
      { key: "c", label: "Đúng — frying pan là cốc" },
      { key: "d", label: "Sai — dùng saucepan" },
    ],
  ),
  mcq(
    "ex-11-1-2",
    "11.1 · Đúng hay sai?",
    "The fridge is colder than the freezer.",
    "b",
    [
      { key: "a", label: "Đúng" },
      { key: "b", label: "Sai — freezer lạnh hơn fridge" },
      { key: "c", label: "Đúng — cả hai bằng nhau" },
      { key: "d", label: "Sai — fridge lạnh hơn nhiều" },
    ],
  ),
  mcq(
    "ex-11-1-3",
    "11.1 · Đúng hay sai?",
    "A tea towel is for making tea.",
    "b",
    [
      { key: "a", label: "Đúng" },
      { key: "b", label: "Sai — dùng để lau bát đĩa" },
      { key: "c", label: "Đúng — là ấm trà" },
      { key: "d", label: "Sai — dùng để nấu cơm" },
    ],
  ),
  cloze("ex-11-2-1", "11.2 · Câu hỏi", "Where's the coffee? → It's in the ___.", "cupboard", ["Cupboard"]),
  cloze("ex-11-2-2", "11.2 · Câu hỏi", "Where's the saucepan? → It's on the ___.", "cooker", ["Cooker"]),
  cloze("ex-11-3-1", "11.3 · Bạn cần gì?", "To make coffee I need a coffee maker, a cup and a ___.", "spoon", ["Spoon"]),
  cloze("ex-11-3-2", "11.3 · Bạn cần gì?", "To make tea I need a teapot and a ___.", "kettle", ["Kettle", "cup", "Cup"]),
  cloze("ex-11-3-3", "11.3 · Bạn cần gì?", "To fry something I need a ___ and a cooker.", "frying pan", ["Frying pan"]),
  cloze("ex-11-3-4", "11.3 · Bạn cần gì?", "To eat my food I need a plate and a knife and ___.", "fork", ["Fork"]),
  cloze("ex-11-3-5", "11.3 · Bạn cần gì?", "To drink water I need a ___ or a mug.", "glass", ["Glass"]),
  cloze("ex-11-3-6", "11.3 · Bạn cần gì?", "To cook dinner in two minutes I need a ___.", "microwave", ["Microwave"]),
  cloze("ex-11-3-7", "11.3 · Bạn cần gì?", "To wash plates I need washing-up liquid, a sink and a ___.", "cloth", ["Cloth"]),
  cloze("ex-11-3-8", "11.3 · Bạn cần gì?", "To wash my clothes I need a washing ___.", "machine", ["Machine"]),
  cloze("ex-11-w1", "11 · Từ vựng", "Put the milk in the ___ — it's cold inside.", "fridge", ["Fridge"]),
  cloze("ex-11-w2", "11 · Từ vựng", "Turn on the ___ to get water.", "tap", ["Tap"]),
  cloze("ex-11-w3", "11 · Từ vựng", "Wash the plates in the ___.", "sink", ["Sink"]),
  cloze("ex-11-w4", "11 · Từ vựng", "Throw rubbish in the ___.", "bin", ["Bin"]),
  cloze("ex-11-w5", "11 · Từ vựng", "Cook rice in a ___.", "saucepan", ["Saucepan"]),
  cloze("ex-11-w4b", "11 · Từ vựng", "Dry plates with a tea ___.", "towel", ["Towel"]),
];

const UNIT_12: VocabularyExercise[] = [
  cloze("ex-12-1-2", "12.1 · Trong ảnh", "Item 2 in the bedroom picture: ___", "wardrobe", ["Wardrobe"]),
  cloze("ex-12-1-3", "12.1 · Trong ảnh", "Item 3: ___", "mirror", ["Mirror"]),
  cloze("ex-12-1-4", "12.1 · Trong ảnh", "Item 4: ___", "hairbrush", ["Hairbrush"]),
  cloze("ex-12-1-5", "12.1 · Trong ảnh", "Item 5: ___", "comb", ["Comb"]),
  cloze("ex-12-1-6", "12.1 · Trong ảnh", "Item 6: ___", "bed", ["Bed"]),
  cloze("ex-12-1-7", "12.1 · Trong ảnh", "Item 7: bedside ___", "lamp", ["Lamp"]),
  cloze("ex-12-1-8", "12.1 · Trong ảnh", "Item 8: bedside ___", "table", ["Table"]),
  cloze("ex-12-1-9", "12.1 · Trong ảnh", "Item 9: alarm ___", "clock", ["Clock"]),
  cloze("ex-12-1-10", "12.1 · Trong ảnh", "Item 10: chest of ___", "drawers", ["Drawers"]),
  cloze("ex-12-3-1", "12.3 · Mô tả", "Anne is cleaning her ___.", "teeth", ["Teeth"]),
  cloze("ex-12-3-2", "12.3 · Mô tả", "Selim and Umit are washing their ___.", "faces", ["Faces"]),
  cloze("ex-12-3-3", "12.3 · Mô tả", "Mrs Park is going ___.", "downstairs", ["Downstairs"]),
  cloze("ex-12-3-4", "12.3 · Mô tả", "Mr Park is having a ___.", "bath", ["Bath"]),
  cloze("ex-12-3-5", "12.3 · Mô tả", "Jaime is getting ___.", "dressed", ["Dressed"]),
  cloze("ex-12-3-6", "12.3 · Mô tả", "Lee is turning off the ___.", "light", ["Light"]),
  cloze("ex-12-6-1", "12.6 · Thói quen", "I usually ___ to bed at 10.30.", "go", ["Go"]),
  cloze("ex-12-6-2", "12.6 · Thói quen", "I get ___ and get into bed.", "undressed", ["Undressed"]),
  cloze("ex-12-6-3", "12.6 · Thói quen", "I turn ___ the light and fall asleep.", "off", ["Off"]),
  cloze("ex-12-6-4", "12.6 · Thói quen", "I ___ up when my alarm clock rings.", "wake", ["Wake"]),
  cloze("ex-12-6-5", "12.6 · Thói quen", "I ___ my teeth and get dressed.", "clean", ["Clean"]),
];

const UNIT_13: VocabularyExercise[] = [
  cloze("ex-13-1-2", "13.1 · Phòng khách", "Somewhere two or three people can sit: a ___", "sofa", ["Sofa"]),
  cloze("ex-13-1-3", "13.1 · Phòng khách", "Somewhere you can put down your cup: a coffee ___", "table", ["Table"]),
  cloze("ex-13-1-4", "13.1 · Phòng khách", "Something you can look at on the wall: a ___", "picture", ["Picture"]),
  cloze("ex-13-1-5", "13.1 · Phòng khách", "Something for switching the light on or off: a light ___", "switch", ["Switch"]),
  cloze("ex-13-1-6", "13.1 · Phòng khách", "Something for listening to music: a ___", "hi-fi", ["Hi-fi"]),
  cloze("ex-13-1-7", "13.1 · Phòng khách", "Something under your feet: a carpet or ___", "rug", ["Rug"]),
  cloze("ex-13-1-8", "13.1 · Phòng khách", "Something for changing channels on the TV: a remote ___", "control", ["Control"]),
  match("ex-13-2", "13.2 · Ghép cụm", [
    { left: "switch on", right: "the TV" },
    { left: "relax in an", right: "armchair" },
    { left: "close the", right: "curtains" },
    { left: "pass the", right: "remote control" },
    { left: "listen to the", right: "radio" },
    { left: "watch", right: "television" },
  ]),
  cloze(
    "ex-13-3-1",
    "13.3 · Sửa lỗi",
    "Let's just relax us at home. → Let's just relax ___ home.",
    "at",
    ["At"],
  ),
  cloze(
    "ex-13-3-2",
    "13.3 · Sửa lỗi",
    "I don't often listen the radio. → I don't often listen ___ the radio.",
    "to",
    ["To"],
  ),
  cloze(
    "ex-13-3-3",
    "13.3 · Sửa lỗi",
    "We need some more bookshelfs. → We need some more ___.",
    "bookshelves",
    ["Bookshelves"],
  ),
  cloze(
    "ex-13-3-4",
    "13.3 · Sửa lỗi",
    "I watched at television. → I watched ___ yesterday.",
    "television",
    ["Television", "TV"],
  ),
  cloze(
    "ex-13-3-5",
    "13.3 · Sửa lỗi",
    "Please make the curtains. → Please ___ the curtains.",
    "close",
    ["Close"],
  ),
  cloze(
    "ex-13-3-6",
    "13.3 · Sửa lỗi",
    "Nice furnitures in his house. → Nice ___ in his house.",
    "furniture",
    ["Furniture"],
  ),
  cloze("ex-13-w1", "13 · Từ vựng", "Can you close the ___? It's getting dark.", "curtains", ["Curtains"]),
  cloze("ex-13-w2", "13 · Từ vựng", "Pass me the remote ___ — I want to turn on the TV.", "control", ["Control"]),
  cloze("ex-13-w3", "13 · Từ vựng", "Put your books on the ___.", "bookshelf", ["Bookshelf", "bookshelves", "Bookshelves"]),
  cloze("ex-13-w4", "13 · Từ vựng", "I like to ___ in an armchair after work.", "relax", ["Relax"]),
  cloze("ex-13-w5", "13 · Từ vựng", "Switch ___ the light, please.", "on", ["On"]),
];

const UNIT_14: VocabularyExercise[] = [
  cloze("ex-14-1-1", "14.1 · Nơi làm việc", "A teacher works in a school / college / ___.", "university", ["University"]),
  cloze("ex-14-1-2", "14.1 · Nơi làm việc", "A doctor works in a hospital or a ___.", "clinic", ["Clinic", "surgery", "Surgery"]),
  cloze("ex-14-1-3", "14.1 · Nơi làm việc", "A waiter works in a restaurant or a ___.", "café", ["Café", "cafe", "Cafe"]),
  cloze("ex-14-1-4", "14.1 · Nơi làm việc", "A secretary works in an ___.", "office", ["Office"]),
  cloze("ex-14-1-5", "14.1 · Nơi làm việc", "A shop assistant works in a ___.", "shop", ["Shop"]),
  cloze("ex-14-1-6", "14.1 · Nơi làm việc", "A hairdresser works in a beauty ___", "salon", ["Salon"]),
  cloze("ex-14-4-2", "14.4 · Hoàn thành", "She wants to be an ___.", "engineer", ["Engineer"]),
  cloze("ex-14-4-3", "14.4 · Hoàn thành", "He works as a ___ driver.", "taxi", ["Taxi"]),
  cloze("ex-14-4-4", "14.4 · Hoàn thành", "My aunt is a ___ in a hospital.", "nurse", ["Nurse"]),
  cloze("ex-14-4-5", "14.4 · Hoàn thành", "The ___ repaired my car.", "mechanic", ["Mechanic"]),
  cloze("ex-14-4-6", "14.4 · Hoàn thành", "She's a ___ in a big company.", "secretary", ["Secretary"]),
  mcq(
    "ex-14-x-1",
    "14.3 · Nghề nghiệp",
    "Someone who works on a bus is a ___",
    "a",
    [
      { key: "a", label: "bus driver" },
      { key: "b", label: "teacher" },
      { key: "c", label: "writer" },
      { key: "d", label: "waiter" },
    ],
  ),
  mcq(
    "ex-14-x-2",
    "14.3 · Nghề nghiệp",
    "Someone who writes books is a ___",
    "c",
    [
      { key: "a", label: "nurse" },
      { key: "b", label: "doctor" },
      { key: "c", label: "writer" },
      { key: "d", label: "bus driver" },
    ],
  ),
  mcq(
    "ex-14-x-3",
    "14.3 · Nghề nghiệp",
    "Someone who works in a school is a ___",
    "b",
    [
      { key: "a", label: "waiter" },
      { key: "b", label: "teacher" },
      { key: "c", label: "mechanic" },
      { key: "d", label: "farmer" },
    ],
  ),
  mcq(
    "ex-14-x-4",
    "14 · Nghề nghiệp",
    "A ___ works with the doctor in a hospital.",
    "d",
    [
      { key: "a", label: "secretary" },
      { key: "b", label: "engineer" },
      { key: "c", label: "shop assistant" },
      { key: "d", label: "nurse" },
    ],
  ),
  cloze("ex-14-w1", "14 · Từ vựng", "A ___ directs traffic and gives parking tickets.", "traffic warden", ["Traffic warden"]),
  cloze("ex-14-w2", "14 · Từ vựng", "A ___ works in a library.", "librarian", ["Librarian"]),
  cloze("ex-14-w3", "14 · Từ vựng", "A bank ___ works behind the counter.", "clerk", ["Clerk"]),
  cloze("ex-14-w4", "14 · Từ vựng", "A ___ keeps people safe in the town.", "police officer", ["Police officer"]),
];

const UNIT_15: VocabularyExercise[] = [
  match("ex-15-1", "15.1 · Ghép đồ dùng học tập", [
    { left: "rubber", right: "xóa bút chì" },
    { left: "ruler", right: "thước kẻ" },
    { left: "textbook", right: "sách giáo khoa" },
    { left: "notebook", right: "vở ghi" },
    { left: "pen", right: "bút mực" },
    { left: "pencil", right: "bút chì" },
    { left: "board", right: "bảng" },
    { left: "drawing pin", right: "ghim bấm" },
    { left: "pencil sharpener", right: "gọt bút chì" },
  ]),
  cloze("ex-15-4-1", "15.4 · Động từ học tập", "She ___ well in all her exams.", "does", ["Does"]),
  cloze("ex-15-4-2", "15.4 · Động từ học tập", "He ___ the exam last week.", "passed", ["Passed"]),
  cloze("ex-15-4-3", "15.4 · Động từ học tập", "I need to ___ / do my homework.", "take", ["Take", "do", "Do"]),
  cloze("ex-15-4-4", "15.4 · Động từ học tập", "If you ___ all your exams, you can celebrate.", "pass", ["Pass", "passes", "Passes"]),
  cloze("ex-15-4-5", "15.4 · Động từ học tập", "I ___ to university next year.", "go", ["Go", "will go", "Will go"]),
  cloze("ex-15-4-6", "15.4 · Động từ học tập", "He ___ the maths test — he got 30%.", "failed", ["Failed"]),
  cloze("ex-15-4-7", "15.4 · Động từ học tập", "We ___ English every day.", "study", ["Study"]),
  cloze("ex-15-4-8", "15.4 · Động từ học tập", "What subjects do you ___ at school?", "do", ["Do"]),
  cloze("ex-15-4-9", "15.4 · Động từ học tập", "I hope to ___ good grades.", "get", ["Get"]),
  cloze("ex-15-w1", "15 · Từ vựng", "Write your answers in your ___.", "notebook", ["Notebook"]),
  cloze("ex-15-w2", "15 · Từ vựng", "The teacher wrote on the ___.", "board", ["Board"]),
  cloze("ex-15-w3", "15 · Từ vựng", "Pin the notice with a drawing ___.", "pin", ["Pin", "drawing pin", "Drawing pin"]),
  cloze("ex-15-w4", "15 · Từ vựng", "Measure the line with a ___.", "ruler", ["Ruler"]),
  cloze("ex-15-w5", "15 · Từ vựng", "Sharpen your pencil with a pencil ___.", "sharpener", ["Sharpener"]),
  cloze("ex-15-w6", "15 · Từ vựng", "Use a ___ to erase your mistake.", "rubber", ["Rubber"]),
  cloze("ex-15-w7", "15 · Từ vựng", "Read chapter 3 in your ___.", "textbook", ["Textbook"]),
  cloze("ex-15-w8", "15 · Từ vựng", "Write with a ___ or a pen.", "pencil", ["Pencil"]),
  cloze("ex-15-w9", "15 · Từ vựng", "A ___ is for writing in ink.", "pen", ["Pen"]),
  cloze("ex-15-w10", "15 · Từ vựng", "A piece of ___ for writing on.", "paper", ["Paper"]),
];

/** Unit 3 (body-a1) và 10 (food-a1) có file mẫu riêng — không override ở đây. */
const CURATED_BY_UNIT: Readonly<Partial<Record<number, readonly VocabularyExercise[]>>> = {
  1: UNIT_1,
  2: UNIT_2,
  4: UNIT_4,
  5: UNIT_5,
  6: UNIT_6,
  7: UNIT_7,
  8: UNIT_8,
  9: UNIT_9,
  11: UNIT_11,
  12: UNIT_12,
  13: UNIT_13,
  14: UNIT_14,
  15: UNIT_15,
  ...CURATED_UNITS_16_30,
  ...CURATED_UNITS_31_45,
  ...CURATED_UNITS_46_60,
};

for (const [unitNumber, exercises] of Object.entries(CURATED_BY_UNIT)) {
  if (exercises) {
    assertExerciseCount(Number(unitNumber), exercises);
  }
}

export { applyExercisePromptVi } from "./eviu-elementary-curated-helpers";

export function applyPromptVi(exercises: readonly VocabularyExercise[]): VocabularyExercise[] {
  return applyExercisePromptVi(exercises, {
    ...CURATED_EXERCISE_PROMPT_VI,
    ...CURATED_EXERCISE_PROMPT_VI_16_30,
    ...CURATED_EXERCISE_PROMPT_VI_31_45,
    ...CURATED_EXERCISE_PROMPT_VI_46_60,
  });
}

export function getCuratedExercisesForUnit(unitNumber: number): readonly VocabularyExercise[] | null {
  const exercises = CURATED_BY_UNIT[unitNumber];
  return exercises ? applyPromptVi(exercises) : null;
}
