import { assertExerciseCount, cloze, match, mcq } from "./eviu-elementary-curated-helpers";
import type { VocabularyExercise } from "@/lib/vocabulary/vocabulary-unit-types";

const UNIT_46: VocabularyExercise[] = [
  match("ex-pre-46-1", "46 · Ghép từ với nghĩa", [
    { left: "itinerary", right: "lịch trình di chuyển chi tiết theo ngày" },
    { left: "reserve", right: "đặt chỗ trước để giữ suất" },
    { left: "booking reference", right: "mã đặt chỗ dùng để tra cứu" },
    { left: "refundable fare", right: "loại vé có thể hoàn lại tiền" },
    { left: "travel insurance", right: "bảo hiểm cho rủi ro khi đi du lịch" },
    { left: "direct flight", right: "chuyến bay đi thẳng không đổi máy bay" },
  ]),
  cloze("ex-pre-46-2", "46 · Điền từ", "Our ___ includes Hanoi, Hue, and Hoi An.", "itinerary", ["Itinerary"]),
  cloze("ex-pre-46-3", "46 · Điền từ", "I need to ___ two train tickets.", "reserve", ["Reserve", "Reserves", "reserved"]),
  cloze("ex-pre-46-4", "46 · Điền cụm", "Please keep your ___ safe.", "booking reference", ["Booking reference"]),
  cloze("ex-pre-46-5", "46 · Điền cụm", "Read the ___ before paying.", "cancellation policy", ["Cancellation policy"]),
  cloze("ex-pre-46-6", "46 · Điền từ", "This ticket is ___.", "non-refundable", ["Non-refundable"]),
  cloze("ex-pre-46-7", "46 · Điền cụm", "A ___ saves a lot of time.", "direct flight", ["Direct flight"]),
  cloze("ex-pre-46-8", "46 · Điền cụm", "My ___ is 20 kilograms.", "baggage allowance", ["Baggage allowance"]),
  mcq("ex-pre-46-9", "46 · Chọn đáp án", "Từ nào chỉ công ty dịch vụ tư vấn và đặt chuyến đi?", "a", [
    { key: "a", label: "travel agency" },
    { key: "b", label: "stopover" },
    { key: "c", label: "check-in window" },
    { key: "d", label: "departure date" },
  ]),
  mcq("ex-pre-46-10", "46 · Chọn đáp án", "We had a six-hour ___ in Doha.", "b", [
    { key: "a", label: "package tour" },
    { key: "b", label: "stopover" },
    { key: "c", label: "seat selection" },
    { key: "d", label: "return date" },
  ]),
  mcq("ex-pre-46-11", "46 · Chọn đáp án", "Từ nào chỉ email xác nhận sau khi đặt thành công?", "c", [
    { key: "a", label: "booking platform" },
    { key: "b", label: "itinerary" },
    { key: "c", label: "confirmation email" },
    { key: "d", label: "travel insurance" },
  ]),
  mcq("ex-pre-46-12", "46 · Chọn đáp án", "Gói du lịch gồm nhiều dịch vụ trọn bộ gọi là ___", "d", [
    { key: "a", label: "refundable fare" },
    { key: "b", label: "booking reference" },
    { key: "c", label: "direct flight" },
    { key: "d", label: "package tour" },
  ]),
  mcq("ex-pre-46-13", "46 · Chọn đáp án", "Việc chọn chỗ ngồi trước chuyến đi gọi là ___", "a", [
    { key: "a", label: "seat selection" },
    { key: "b", label: "cancellation policy" },
    { key: "c", label: "check-in window" },
    { key: "d", label: "non-refundable" },
  ]),
  mcq("ex-pre-46-14", "46 · Chọn đáp án", "Nền tảng trực tuyến để đặt dịch vụ du lịch là ___", "b", [
    { key: "a", label: "travel agency" },
    { key: "b", label: "booking platform" },
    { key: "c", label: "baggage allowance" },
    { key: "d", label: "departure date" },
  ]),
];

const UNIT_47: VocabularyExercise[] = [
  match("ex-pre-47-1", "47 · Ghép từ với nghĩa", [
    { left: "boarding pass", right: "thẻ lên máy bay" },
    { left: "security check", right: "khu vực kiểm tra an ninh" },
    { left: "takeoff", right: "quá trình cất cánh" },
    { left: "turbulence", right: "hiện tượng rung lắc khi bay" },
    { left: "aisle seat", right: "ghế cạnh lối đi" },
    { left: "jet lag", right: "mệt mỏi do lệch múi giờ sau khi bay xa" },
  ]),
  cloze("ex-pre-47-2", "47 · Điền cụm", "Show your ___ at the gate.", "boarding pass", ["Boarding pass"]),
  cloze("ex-pre-47-3", "47 · Điền cụm", "Liquids are checked at the ___.", "security check", ["Security check"]),
  cloze("ex-pre-47-4", "47 · Điền từ", "I always feel nervous during ___.", "takeoff", ["Takeoff"]),
  cloze("ex-pre-47-5", "47 · Điền từ", "The pilot warned us about ___.", "turbulence", ["Turbulence"]),
  cloze("ex-pre-47-6", "47 · Điền cụm", "Put your bag in the overhead ___.", "locker", ["Locker", "overhead locker", "Overhead locker"]),
  cloze("ex-pre-47-7", "47 · Điền từ", "The plane moved slowly onto the ___.", "runway", ["Runway"]),
  cloze("ex-pre-47-8", "47 · Điền cụm", "I had terrible ___ after the trip.", "jet lag", ["Jet lag"]),
  mcq("ex-pre-47-9", "47 · Chọn đáp án", "Từ nào chỉ số cổng ra máy bay?", "c", [
    { key: "a", label: "landing" },
    { key: "b", label: "runway" },
    { key: "c", label: "gate number" },
    { key: "d", label: "turbulence" },
  ]),
  mcq("ex-pre-47-10", "47 · Chọn đáp án", "Chuyến bay bị hoãn gọi là ___", "a", [
    { key: "a", label: "delayed flight" },
    { key: "b", label: "direct flight" },
    { key: "c", label: "window seat" },
    { key: "d", label: "takeoff" },
  ]),
  mcq("ex-pre-47-11", "47 · Chọn đáp án", "Lỡ chuyến nối tiếp gọi là ___", "b", [
    { key: "a", label: "boarding pass" },
    { key: "b", label: "missed connection" },
    { key: "c", label: "departure lounge" },
    { key: "d", label: "cabin crew" },
  ]),
  mcq("ex-pre-47-12", "47 · Chọn đáp án", "Nhân viên kiểm tra hành lý tại hải quan là ___", "d", [
    { key: "a", label: "anchor" },
    { key: "b", label: "cabin crew" },
    { key: "c", label: "lifeguard" },
    { key: "d", label: "customs officer" },
  ]),
  mcq("ex-pre-47-13", "47 · Chọn đáp án", "Hàng chờ làm thủ tục nhập cảnh gọi là ___", "a", [
    { key: "a", label: "immigration queue" },
    { key: "b", label: "security check" },
    { key: "c", label: "departure lounge" },
    { key: "d", label: "gate number" },
  ]),
  mcq("ex-pre-47-14", "47 · Chọn đáp án", "Hành lý xách tay mang lên cabin gọi là ___", "c", [
    { key: "a", label: "baggage allowance" },
    { key: "b", label: "overhead locker" },
    { key: "c", label: "carry-on luggage" },
    { key: "d", label: "boarding pass" },
  ]),
];

const UNIT_48: VocabularyExercise[] = [
  match("ex-pre-48-1", "48 · Ghép từ với nghĩa", [
    { left: "reception desk", right: "quầy lễ tân tại khách sạn" },
    { left: "vacancy", right: "tình trạng còn phòng trống" },
    { left: "room service", right: "dịch vụ mang đồ ăn/uống lên phòng" },
    { left: "housekeeping", right: "bộ phận dọn phòng và vệ sinh" },
    { left: "main course", right: "món chính trong bữa ăn" },
    { left: "check-out time", right: "giờ trả phòng theo quy định" },
  ]),
  cloze("ex-pre-48-2", "48 · Điền cụm", "Please leave your key at the ___.", "reception desk", ["Reception desk"]),
  cloze("ex-pre-48-3", "48 · Điền từ", "Sorry, we have no ___ tonight.", "vacancy", ["Vacancy"]),
  cloze("ex-pre-48-4", "48 · Điền từ", "The hotel is ___ this weekend.", "fully booked", ["Fully booked"]),
  cloze("ex-pre-48-5", "48 · Điền cụm", "We ordered sandwiches from ___.", "room service", ["Room service"]),
  cloze("ex-pre-48-6", "48 · Điền từ", "___ cleaned the room at noon.", "Housekeeping", ["housekeeping"]),
  cloze("ex-pre-48-7", "48 · Điền từ", "Could we have the ___, please?", "bill", ["Bill"]),
  cloze("ex-pre-48-8", "48 · Điền cụm", "___ is at 11 a.m.", "Check-out time", ["check-out time"]),
  mcq("ex-pre-48-9", "48 · Chọn đáp án", "Phòng dành cho một người gọi là ___", "b", [
    { key: "a", label: "double room" },
    { key: "b", label: "single room" },
    { key: "c", label: "vacancy" },
    { key: "d", label: "set menu" },
  ]),
  mcq("ex-pre-48-10", "48 · Chọn đáp án", "Cuộc gọi báo thức từ khách sạn gọi là ___", "c", [
    { key: "a", label: "housekeeping" },
    { key: "b", label: "room service" },
    { key: "c", label: "wake-up call" },
    { key: "d", label: "buffet breakfast" },
  ]),
  mcq("ex-pre-48-11", "48 · Chọn đáp án", "Thực đơn chọn sẵn theo suất gọi là ___", "a", [
    { key: "a", label: "set menu" },
    { key: "b", label: "side dish" },
    { key: "c", label: "main course" },
    { key: "d", label: "reservation" },
  ]),
  mcq("ex-pre-48-12", "48 · Chọn đáp án", "Món ăn kèm gọi là ___", "d", [
    { key: "a", label: "bill" },
    { key: "b", label: "tip" },
    { key: "c", label: "main course" },
    { key: "d", label: "side dish" },
  ]),
  mcq("ex-pre-48-13", "48 · Chọn đáp án", "Tiền boa cho nhân viên phục vụ gọi là ___", "b", [
    { key: "a", label: "bill" },
    { key: "b", label: "tip" },
    { key: "c", label: "reservation" },
    { key: "d", label: "complimentary" },
  ]),
  mcq("ex-pre-48-14", "48 · Chọn đáp án", "Được tặng miễn phí kèm dịch vụ gọi là ___", "c", [
    { key: "a", label: "fully booked" },
    { key: "b", label: "allergy-friendly" },
    { key: "c", label: "complimentary" },
    { key: "d", label: "vacancy" },
  ]),
];

const UNIT_49: VocabularyExercise[] = [
  match("ex-pre-49-1", "49 · Ghép từ với nghĩa", [
    { left: "espresso", right: "cà phê đậm đặc pha bằng áp suất cao" },
    { left: "latte", right: "cà phê pha sữa nóng và lớp bọt mỏng" },
    { left: "cappuccino", right: "cà phê sữa với lớp bọt dày" },
    { left: "barista", right: "người pha chế đồ uống tại quán cà phê" },
    { left: "takeaway cup", right: "ly mang đi" },
    { left: "loyalty card", right: "thẻ tích điểm khách hàng thân thiết" },
  ]),
  cloze("ex-pre-49-2", "49 · Điền từ", "He drinks a single ___ every morning.", "espresso", ["Espresso"]),
  cloze("ex-pre-49-3", "49 · Điền từ", "I usually order an iced ___.", "latte", ["Latte"]),
  cloze("ex-pre-49-4", "49 · Điền từ", "She likes ___ with cinnamon.", "cappuccino", ["Cappuccino"]),
  cloze("ex-pre-49-5", "49 · Điền từ", "The ___ recommended a new blend.", "barista", ["Barista"]),
  cloze("ex-pre-49-6", "49 · Điền cụm", "Can I have this in a ___?", "takeaway cup", ["Takeaway cup"]),
  cloze("ex-pre-49-7", "49 · Điền cụm", "We decided to ___ today.", "dine in", ["Dine in"]),
  cloze("ex-pre-49-8", "49 · Điền từ", "I drink ___ in the evening.", "decaf", ["Decaf"]),
  mcq("ex-pre-49-9", "49 · Chọn đáp án", "Cà phê espresso pha thêm nước nóng gọi là ___", "a", [
    { key: "a", label: "americano" },
    { key: "b", label: "latte" },
    { key: "c", label: "cappuccino" },
    { key: "d", label: "espresso" },
  ]),
  mcq("ex-pre-49-10", "49 · Chọn đáp án", "Sữa đậu nành thay sữa bò gọi là ___", "b", [
    { key: "a", label: "oat milk" },
    { key: "b", label: "soy milk" },
    { key: "c", label: "grind size" },
    { key: "d", label: "refill" },
  ]),
  mcq("ex-pre-49-11", "49 · Chọn đáp án", "Độ mịn của bột cà phê sau khi xay gọi là ___", "c", [
    { key: "a", label: "coffee beans" },
    { key: "b", label: "pastry counter" },
    { key: "c", label: "grind size" },
    { key: "d", label: "opening hours" },
  ]),
  mcq("ex-pre-49-12", "49 · Chọn đáp án", "Việc rót thêm đồ uống gọi là ___", "d", [
    { key: "a", label: "dine in" },
    { key: "b", label: "takeaway cup" },
    { key: "c", label: "loyalty card" },
    { key: "d", label: "refill" },
  ]),
  mcq("ex-pre-49-13", "49 · Chọn đáp án", "Góc ngồi ấm cúng, dễ chịu trong quán gọi là ___", "a", [
    { key: "a", label: "cozy corner" },
    { key: "b", label: "pastry counter" },
    { key: "c", label: "opening hours" },
    { key: "d", label: "coffee beans" },
  ]),
  mcq("ex-pre-49-14", "49 · Chọn đáp án", "Dịch vụ wifi miễn phí cho khách gọi là ___", "b", [
    { key: "a", label: "loyalty card" },
    { key: "b", label: "free wi-fi" },
    { key: "c", label: "grind size" },
    { key: "d", label: "americano" },
  ]),
];

const UNIT_50: VocabularyExercise[] = [
  match("ex-pre-50-1", "50 · Ghép từ với nghĩa", [
    { left: "landmark", right: "địa danh nổi bật mang tính biểu tượng" },
    { left: "guided tour", right: "chuyến tham quan có hướng dẫn viên" },
    { left: "heritage site", right: "địa điểm di sản văn hóa hoặc thiên nhiên" },
    { left: "admission fee", right: "phí vào cửa điểm tham quan" },
    { left: "hidden gem", right: "địa điểm ít người biết nhưng rất đáng đi" },
    { left: "tourist trap", right: "điểm du lịch bị thổi giá hoặc kém chất lượng" },
  ]),
  cloze("ex-pre-50-2", "50 · Điền từ", "The opera house is the city's ___.", "landmark", ["Landmark"]),
  cloze("ex-pre-50-3", "50 · Điền cụm", "We joined a ___ in the old town.", "guided tour", ["Guided tour"]),
  cloze("ex-pre-50-4", "50 · Điền cụm", "Take a ___ from the hotel lobby.", "city map", ["City map"]),
  cloze("ex-pre-50-5", "50 · Điền cụm", "The museum offers an ___ in English.", "audio guide", ["Audio guide"]),
  cloze("ex-pre-50-6", "50 · Điền cụm", "Sunset is beautiful from this ___.", "viewpoint", ["Viewpoint"]),
  cloze("ex-pre-50-7", "50 · Điền cụm", "We walked around the ___ all morning.", "old quarter", ["Old quarter"]),
  cloze("ex-pre-50-8", "50 · Điền cụm", "Tourists ___ before the gate opens.", "queue up", ["Queue up"]),
  mcq("ex-pre-50-9", "50 · Chọn đáp án", "Vé gộp vào nhiều bảo tàng gọi là ___", "c", [
    { key: "a", label: "admission fee" },
    { key: "b", label: "day trip" },
    { key: "c", label: "museum pass" },
    { key: "d", label: "photo spot" },
  ]),
  mcq("ex-pre-50-10", "50 · Chọn đáp án", "Hướng dẫn viên bản địa am hiểu vùng gọi là ___", "a", [
    { key: "a", label: "local guide" },
    { key: "b", label: "souvenir shop" },
    { key: "c", label: "walking tour" },
    { key: "d", label: "city map" },
  ]),
  mcq("ex-pre-50-11", "50 · Chọn đáp án", "Chuyến khám phá đi bộ theo tuyến gọi là ___", "b", [
    { key: "a", label: "guided tour" },
    { key: "b", label: "walking tour" },
    { key: "c", label: "day trip" },
    { key: "d", label: "landmark" },
  ]),
  mcq("ex-pre-50-12", "50 · Chọn đáp án", "Chuyến đi về trong ngày gọi là ___", "d", [
    { key: "a", label: "heritage site" },
    { key: "b", label: "opening times" },
    { key: "c", label: "viewpoint" },
    { key: "d", label: "day trip" },
  ]),
  mcq("ex-pre-50-13", "50 · Chọn đáp án", "Khung giờ mở cửa tham quan gọi là ___", "c", [
    { key: "a", label: "admission fee" },
    { key: "b", label: "photo spot" },
    { key: "c", label: "opening times" },
    { key: "d", label: "souvenir shop" },
  ]),
  mcq("ex-pre-50-14", "50 · Chọn đáp án", "Điểm chụp hình đẹp phổ biến gọi là ___", "a", [
    { key: "a", label: "photo spot" },
    { key: "b", label: "hidden gem" },
    { key: "c", label: "tourist trap" },
    { key: "d", label: "old quarter" },
  ]),
];

const UNIT_51: VocabularyExercise[] = [
  match("ex-pre-51-1", "51 · Ghép từ với nghĩa", [
    { left: "seaside resort", right: "khu nghỉ dưỡng ven biển" },
    { left: "sandy beach", right: "bãi biển có cát mịn" },
    { left: "sunscreen", right: "kem chống nắng bảo vệ da" },
    { left: "lifeguard", right: "nhân viên cứu hộ ở khu bơi" },
    { left: "snorkeling", right: "lặn nông ngắm san hô bằng ống thở" },
    { left: "sunset cruise", right: "hành trình ngắm hoàng hôn trên tàu" },
  ]),
  cloze("ex-pre-51-2", "51 · Điền cụm", "They stayed at a quiet ___.", "seaside resort", ["Seaside resort"]),
  cloze("ex-pre-51-3", "51 · Điền từ", "The ___ here is very rocky.", "coastline", ["Coastline"]),
  cloze("ex-pre-51-4", "51 · Điền từ", "Children played on the ___.", "sandy beach", ["Sandy beach"]),
  cloze("ex-pre-51-5", "51 · Điền từ", "Apply ___ every two hours.", "sunscreen", ["Sunscreen"]),
  cloze("ex-pre-51-6", "51 · Điền từ", "The ___ blew the whistle.", "lifeguard", ["Lifeguard"]),
  cloze("ex-pre-51-7", "51 · Điền từ", "The ___ is high this afternoon.", "tide", ["Tide"]),
  cloze("ex-pre-51-8", "51 · Điền từ", "We tried ___ near the reef.", "snorkeling", ["Snorkeling"]),
  mcq("ex-pre-51-9", "51 · Chọn đáp án", "Việc nằm tắm nắng trên bãi biển gọi là ___", "b", [
    { key: "a", label: "beach volleyball" },
    { key: "b", label: "sunbathing" },
    { key: "c", label: "boat trip" },
    { key: "d", label: "sea breeze" },
  ]),
  mcq("ex-pre-51-10", "51 · Chọn đáp án", "Khăn lớn dùng tại bãi biển gọi là ___", "a", [
    { key: "a", label: "beach towel" },
    { key: "b", label: "seashell" },
    { key: "c", label: "pier" },
    { key: "d", label: "waves" },
  ]),
  mcq("ex-pre-51-11", "51 · Chọn đáp án", "Cầu tàu nhô ra mặt nước gọi là ___", "c", [
    { key: "a", label: "coastline" },
    { key: "b", label: "seafood stall" },
    { key: "c", label: "pier" },
    { key: "d", label: "tide" },
  ]),
  mcq("ex-pre-51-12", "51 · Chọn đáp án", "Gió biển mát thổi từ mặt nước gọi là ___", "d", [
    { key: "a", label: "waves" },
    { key: "b", label: "sunbathing" },
    { key: "c", label: "seashell" },
    { key: "d", label: "sea breeze" },
  ]),
  mcq("ex-pre-51-13", "51 · Chọn đáp án", "Thuê ô che nắng ở bãi biển gọi là ___", "a", [
    { key: "a", label: "rent an umbrella" },
    { key: "b", label: "beach volleyball" },
    { key: "c", label: "boat trip" },
    { key: "d", label: "seafood stall" },
  ]),
  mcq("ex-pre-51-14", "51 · Chọn đáp án", "Chuyến đi biển bằng thuyền gọi là ___", "b", [
    { key: "a", label: "sunset cruise" },
    { key: "b", label: "boat trip" },
    { key: "c", label: "snorkeling" },
    { key: "d", label: "beach volleyball" },
  ]),
];

const UNIT_52: VocabularyExercise[] = [
  match("ex-pre-52-1", "52 · Ghép từ với nghĩa", [
    { left: "headline", right: "tiêu đề chính nổi bật của bản tin" },
    { left: "breaking news", right: "tin nóng vừa xảy ra" },
    { left: "anchor", right: "người dẫn chương trình thời sự" },
    { left: "documentary", right: "phim tài liệu về chủ đề thực tế" },
    { left: "press conference", right: "họp báo chính thức với truyền thông" },
    { left: "current affairs", right: "các vấn đề thời sự đương đại" },
  ]),
  cloze("ex-pre-52-2", "52 · Điền từ", "The ___ shocked many readers.", "headline", ["Headline"]),
  cloze("ex-pre-52-3", "52 · Điền cụm", "Her interview appeared on the ___.", "front page", ["Front page"]),
  cloze("ex-pre-52-4", "52 · Điền từ", "The channel switched to ___.", "breaking news", ["Breaking news"]),
  cloze("ex-pre-52-5", "52 · Điền từ", "The ___ remained calm during the update.", "anchor", ["Anchor"]),
  cloze("ex-pre-52-6", "52 · Điền từ", "We watched a ___ on marine life.", "documentary", ["Documentary"]),
  cloze("ex-pre-52-7", "52 · Điền cụm", "I check the ___ every morning.", "weather report", ["Weather report"]),
  cloze("ex-pre-52-8", "52 · Điền cụm", "The debate will ___ tonight.", "broadcast live", ["Broadcast live"]),
  mcq("ex-pre-52-9", "52 · Chọn đáp án", "Người viết chuyên mục định kỳ gọi là ___", "a", [
    { key: "a", label: "columnist" },
    { key: "b", label: "anchor" },
    { key: "c", label: "editorial" },
    { key: "d", label: "channel" },
  ]),
  mcq("ex-pre-52-10", "52 · Chọn đáp án", "Bài xã luận thể hiện quan điểm tòa soạn gọi là ___", "b", [
    { key: "a", label: "headline" },
    { key: "b", label: "editorial" },
    { key: "c", label: "news bulletin" },
    { key: "d", label: "ratings" },
  ]),
  mcq("ex-pre-52-11", "52 · Chọn đáp án", "Báo khổ nhỏ thiên về tin giật gân gọi là ___", "c", [
    { key: "a", label: "broadsheet" },
    { key: "b", label: "documentary" },
    { key: "c", label: "tabloid" },
    { key: "d", label: "front page" },
  ]),
  mcq("ex-pre-52-12", "52 · Chọn đáp án", "Báo chính luận khổ lớn, nội dung nghiêm túc gọi là ___", "d", [
    { key: "a", label: "tabloid" },
    { key: "b", label: "channel" },
    { key: "c", label: "subtitles" },
    { key: "d", label: "broadsheet" },
  ]),
  mcq("ex-pre-52-13", "52 · Chọn đáp án", "Bản tin ngắn cập nhật theo khung giờ gọi là ___", "a", [
    { key: "a", label: "news bulletin" },
    { key: "b", label: "press conference" },
    { key: "c", label: "weather report" },
    { key: "d", label: "breaking news" },
  ]),
  mcq("ex-pre-52-14", "52 · Chọn đáp án", "Thiết bị điều khiển tivi từ xa gọi là ___", "b", [
    { key: "a", label: "channel" },
    { key: "b", label: "remote control" },
    { key: "c", label: "subtitles" },
    { key: "d", label: "ratings" },
  ]),
];

const UNIT_53: VocabularyExercise[] = [
  match("ex-pre-53-1", "53 · Ghép từ với nghĩa", [
    { left: "voicemail", right: "hộp thư thoại ghi lời nhắn" },
    { left: "signal", right: "mức sóng điện thoại để liên lạc" },
    { left: "missed call", right: "cuộc gọi nhỡ chưa kịp nghe" },
    { left: "text message", right: "tin nhắn văn bản trên điện thoại" },
    { left: "voice note", right: "tin nhắn âm thanh ghi sẵn" },
    { left: "spam call", right: "cuộc gọi rác quảng cáo không mong muốn" },
  ]),
  cloze("ex-pre-53-2", "53 · Điền từ", "Please ___ the number again.", "dial", ["Dial", "Dials", "dialed"]),
  cloze("ex-pre-53-3", "53 · Điền từ", "I left a message in your ___.", "voicemail", ["Voicemail"]),
  cloze("ex-pre-53-4", "53 · Điền từ", "I have no ___ in this basement.", "signal", ["Signal"]),
  cloze("ex-pre-53-5", "53 · Điền cụm", "I saw your ___ this morning.", "missed call", ["Missed call"]),
  cloze("ex-pre-53-6", "53 · Điền cụm", "I'll ___ in ten minutes.", "call back", ["Call back"]),
  cloze("ex-pre-53-7", "53 · Điền cụm", "Send me a ___ when you arrive.", "text message", ["Text message"]),
  cloze("ex-pre-53-8", "53 · Điền cụm", "He sent a ___ instead of typing.", "voice note", ["Voice note"]),
  mcq("ex-pre-53-9", "53 · Chọn đáp án", "Cuộc gọi nhóm với nhiều người gọi là ___", "c", [
    { key: "a", label: "missed call" },
    { key: "b", label: "spam call" },
    { key: "c", label: "conference call" },
    { key: "d", label: "voice note" },
  ]),
  mcq("ex-pre-53-10", "53 · Chọn đáp án", "Biểu tượng cảm xúc dùng khi nhắn tin gọi là ___", "a", [
    { key: "a", label: "emoji" },
    { key: "b", label: "ringtone" },
    { key: "c", label: "autocorrect" },
    { key: "d", label: "read receipt" },
  ]),
  mcq("ex-pre-53-11", "53 · Chọn đáp án", "Tính năng tự sửa từ khi gõ gọi là ___", "b", [
    { key: "a", label: "emoji" },
    { key: "b", label: "autocorrect" },
    { key: "c", label: "contact list" },
    { key: "d", label: "ringtone" },
  ]),
  mcq("ex-pre-53-12", "53 · Chọn đáp án", "Đoạn trò chuyện có nhiều thành viên gọi là ___", "d", [
    { key: "a", label: "text message" },
    { key: "b", label: "voicemail" },
    { key: "c", label: "missed call" },
    { key: "d", label: "group chat" },
  ]),
  mcq("ex-pre-53-13", "53 · Chọn đáp án", "Dấu hiệu cho biết tin nhắn đã được đọc gọi là ___", "c", [
    { key: "a", label: "ringtone" },
    { key: "b", label: "signal" },
    { key: "c", label: "read receipt" },
    { key: "d", label: "autocorrect" },
  ]),
  mcq("ex-pre-53-14", "53 · Chọn đáp án", "Trạng thái pin yếu gần hết gọi là ___", "a", [
    { key: "a", label: "battery low" },
    { key: "b", label: "phone charger" },
    { key: "c", label: "contact list" },
    { key: "d", label: "spam call" },
  ]),
];

const UNIT_54: VocabularyExercise[] = [
  match("ex-pre-54-1", "54 · Ghép từ với nghĩa", [
    { left: "laptop", right: "máy tính xách tay gọn nhẹ" },
    { left: "keyboard", right: "bàn phím dùng để nhập dữ liệu" },
    { left: "monitor", right: "màn hình hiển thị của máy tính" },
    { left: "hard drive", right: "ổ lưu trữ dữ liệu trong máy" },
    { left: "processor", right: "bộ xử lý trung tâm của máy tính" },
    { left: "memory", right: "bộ nhớ RAM dùng xử lý tác vụ" },
  ]),
  cloze("ex-pre-54-2", "54 · Điền cụm", "The office still uses ___ computers.", "desktop", ["Desktop", "desktop computer", "Desktop computer"]),
  cloze("ex-pre-54-3", "54 · Điền từ", "I carry my ___ to class every day.", "laptop", ["Laptop"]),
  cloze("ex-pre-54-4", "54 · Điền từ", "This ___ is quiet and smooth.", "keyboard", ["Keyboard"]),
  cloze("ex-pre-54-5", "54 · Điền từ", "A second ___ improves productivity.", "monitor", ["Monitor"]),
  cloze("ex-pre-54-6", "54 · Điền cụm", "Back up photos on an external ___.", "hard drive", ["Hard drive"]),
  cloze("ex-pre-54-7", "54 · Điền từ", "Try to ___ the computer first.", "restart", ["Restart", "Restarts", "restarted"]),
  cloze("ex-pre-54-8", "54 · Điền cụm", "Always create a ___ before major edits.", "backup file", ["Backup file"]),
  mcq("ex-pre-54-9", "54 · Chọn đáp án", "Chuột điều khiển con trỏ trên màn hình gọi là ___", "b", [
    { key: "a", label: "keyboard" },
    { key: "b", label: "mouse" },
    { key: "c", label: "usb port" },
    { key: "d", label: "processor" },
  ]),
  mcq("ex-pre-54-10", "54 · Chọn đáp án", "Cổng cắm USB để kết nối thiết bị gọi là ___", "c", [
    { key: "a", label: "monitor" },
    { key: "b", label: "memory" },
    { key: "c", label: "usb port" },
    { key: "d", label: "file folder" },
  ]),
  mcq("ex-pre-54-11", "54 · Chọn đáp án", "Tắt máy hoàn toàn gọi là ___", "a", [
    { key: "a", label: "shut down" },
    { key: "b", label: "restart" },
    { key: "c", label: "copy and paste" },
    { key: "d", label: "install software" },
  ]),
  mcq("ex-pre-54-12", "54 · Chọn đáp án", "Sao chép và dán dữ liệu gọi là ___", "d", [
    { key: "a", label: "update driver" },
    { key: "b", label: "delete permanently" },
    { key: "c", label: "shut down" },
    { key: "d", label: "copy and paste" },
  ]),
  mcq("ex-pre-54-13", "54 · Chọn đáp án", "Độ phân giải hiển thị của màn hình gọi là ___", "b", [
    { key: "a", label: "memory" },
    { key: "b", label: "screen resolution" },
    { key: "c", label: "hard drive" },
    { key: "d", label: "file folder" },
  ]),
  mcq("ex-pre-54-14", "54 · Chọn đáp án", "Thư mục chứa tệp tin gọi là ___", "c", [
    { key: "a", label: "backup file" },
    { key: "b", label: "usb port" },
    { key: "c", label: "file folder" },
    { key: "d", label: "screen resolution" },
  ]),
];

const UNIT_55: VocabularyExercise[] = [
  match("ex-pre-55-1", "55 · Ghép từ với nghĩa", [
    { left: "inbox", right: "hộp thư đến chứa email nhận được" },
    { left: "attachment", right: "tệp đính kèm trong email" },
    { left: "subject line", right: "dòng tiêu đề tóm tắt email" },
    { left: "hyperlink", right: "liên kết có thể nhấn để mở trang" },
    { left: "cloud storage", right: "dịch vụ lưu trữ trực tuyến trên đám mây" },
    { left: "two-factor authentication", right: "xác thực hai lớp để tăng bảo mật" },
  ]),
  cloze("ex-pre-55-2", "55 · Điền từ", "My ___ is full of unread emails.", "inbox", ["Inbox"]),
  cloze("ex-pre-55-3", "55 · Điền cụm", "Check the ___ for missing mail.", "spam folder", ["Spam folder"]),
  cloze("ex-pre-55-4", "55 · Điền từ", "I forgot to add the ___.", "attachment", ["Attachment"]),
  cloze("ex-pre-55-5", "55 · Điền cụm", "Write a clear ___.", "subject line", ["Subject line"]),
  cloze("ex-pre-55-6", "55 · Điền từ", "Please ___ your team leader.", "cc", ["CC", "Cc"]),
  cloze("ex-pre-55-7", "55 · Điền cụm", "The ___ leads to our homepage.", "hyperlink", ["Hyperlink"]),
  cloze("ex-pre-55-8", "55 · Điền cụm", "I have too many ___ open.", "browser tabs", ["Browser tabs", "browser tab", "Browser tab"]),
  mcq("ex-pre-55-9", "55 · Chọn đáp án", "Gửi bản sao ẩn danh sách người nhận gọi là ___", "b", [
    { key: "a", label: "cc" },
    { key: "b", label: "bcc" },
    { key: "c", label: "reply all" },
    { key: "d", label: "forward email" },
  ]),
  mcq("ex-pre-55-10", "55 · Chọn đáp án", "Hủy đăng ký nhận tin gọi là ___", "c", [
    { key: "a", label: "upload" },
    { key: "b", label: "download" },
    { key: "c", label: "unsubscribe" },
    { key: "d", label: "hyperlink" },
  ]),
  mcq("ex-pre-55-11", "55 · Chọn đáp án", "Công cụ tìm kiếm thông tin trực tuyến gọi là ___", "a", [
    { key: "a", label: "search engine" },
    { key: "b", label: "browser tab" },
    { key: "c", label: "cloud storage" },
    { key: "d", label: "spam folder" },
  ]),
  mcq("ex-pre-55-12", "55 · Chọn đáp án", "Tải dữ liệu từ internet về thiết bị gọi là ___", "d", [
    { key: "a", label: "upload" },
    { key: "b", label: "forward email" },
    { key: "c", label: "unsubscribe" },
    { key: "d", label: "download" },
  ]),
  mcq("ex-pre-55-13", "55 · Chọn đáp án", "Thao tác đặt lại mật khẩu gọi là ___", "b", [
    { key: "a", label: "privacy settings" },
    { key: "b", label: "password reset" },
    { key: "c", label: "reply all" },
    { key: "d", label: "bcc" },
  ]),
  mcq("ex-pre-55-14", "55 · Chọn đáp án", "Tùy chọn kiểm soát quyền riêng tư gọi là ___", "c", [
    { key: "a", label: "subject line" },
    { key: "b", label: "two-factor authentication" },
    { key: "c", label: "privacy settings" },
    { key: "d", label: "attachment" },
  ]),
];

const UNIT_56: VocabularyExercise[] = [
  match("ex-pre-56-1", "56 · Ghép từ với nghĩa", [
    { left: "theft", right: "hành vi trộm cắp tài sản" },
    { left: "robbery", right: "cướp tài sản bằng đe dọa hoặc vũ lực" },
    { left: "burglary", right: "đột nhập nhà/cửa hàng để lấy trộm" },
    { left: "witness", right: "nhân chứng đã nhìn thấy sự việc" },
    { left: "evidence", right: "chứng cứ phục vụ điều tra và xét xử" },
    { left: "guilty", right: "có tội theo phán quyết tòa án" },
  ]),
  cloze("ex-pre-56-2", "56 · Điền từ", "___ has increased in this area.", "Theft", ["theft"]),
  cloze("ex-pre-56-3", "56 · Điền từ", "The ___ happened at night.", "robbery", ["Robbery"]),
  cloze("ex-pre-56-4", "56 · Điền từ", "Police investigated a ___ nearby.", "burglary", ["Burglary"]),
  cloze("ex-pre-56-5", "56 · Điền từ", "The ___ was seen on camera.", "suspect", ["Suspect"]),
  cloze("ex-pre-56-6", "56 · Điền từ", "A ___ gave a detailed statement.", "witness", ["Witness"]),
  cloze("ex-pre-56-7", "56 · Điền từ", "DNA ___ changed the case.", "evidence", ["Evidence"]),
  cloze("ex-pre-56-8", "56 · Điền từ", "Police decided to ___ the suspect.", "arrest", ["Arrest", "Arrests", "arrested"]),
  mcq("ex-pre-56-9", "56 · Chọn đáp án", "Dấu vân tay nhận dạng cá nhân gọi là ___", "a", [
    { key: "a", label: "fingerprint" },
    { key: "b", label: "handcuffs" },
    { key: "c", label: "fine" },
    { key: "d", label: "scam" },
  ]),
  mcq("ex-pre-56-10", "56 · Chọn đáp án", "Thám tử hoặc điều tra viên hình sự gọi là ___", "b", [
    { key: "a", label: "witness" },
    { key: "b", label: "detective" },
    { key: "c", label: "suspect" },
    { key: "d", label: "civilian" },
  ]),
  mcq("ex-pre-56-11", "56 · Chọn đáp án", "Án phạt tù do tòa tuyên gọi là ___", "c", [
    { key: "a", label: "fine" },
    { key: "b", label: "court case" },
    { key: "c", label: "prison sentence" },
    { key: "d", label: "handcuffs" },
  ]),
  mcq("ex-pre-56-12", "56 · Chọn đáp án", "Vô tội, không phạm hành vi bị cáo buộc gọi là ___", "d", [
    { key: "a", label: "guilty" },
    { key: "b", label: "suspect" },
    { key: "c", label: "robbery" },
    { key: "d", label: "innocent" },
  ]),
  mcq("ex-pre-56-13", "56 · Chọn đáp án", "Hành vi lừa đảo để chiếm đoạt tài sản gọi là ___", "a", [
    { key: "a", label: "scam" },
    { key: "b", label: "burglary" },
    { key: "c", label: "theft" },
    { key: "d", label: "self-defense" },
  ]),
  mcq("ex-pre-56-14", "56 · Chọn đáp án", "Ăn cắp hàng hóa trong cửa hàng gọi là ___", "b", [
    { key: "a", label: "robbery" },
    { key: "b", label: "shoplifting" },
    { key: "c", label: "arrest" },
    { key: "d", label: "evidence" },
  ]),
];

const UNIT_57: VocabularyExercise[] = [
  match("ex-pre-57-1", "57 · Ghép từ với nghĩa", [
    { left: "election", right: "cuộc bầu cử để chọn lãnh đạo" },
    { left: "candidate", right: "người ra tranh cử một vị trí" },
    { left: "voter", right: "cử tri có quyền bỏ phiếu" },
    { left: "parliament", right: "cơ quan lập pháp của quốc gia" },
    { left: "policy", right: "chính sách định hướng hành động công" },
    { left: "democracy", right: "thể chế người dân tham gia chọn lãnh đạo" },
  ]),
  cloze("ex-pre-57-2", "57 · Điền từ", "The national ___ is next month.", "election", ["Election"]),
  cloze("ex-pre-57-3", "57 · Điền từ", "Her ___ focused on education reform.", "campaign", ["Campaign"]),
  cloze("ex-pre-57-4", "57 · Điền từ", "Each ___ gave a short speech.", "candidate", ["Candidate"]),
  cloze("ex-pre-57-5", "57 · Điền từ", "Young ___ care about climate policy.", "voters", ["Voters", "voter", "Voter"]),
  cloze("ex-pre-57-6", "57 · Điền cụm", "Put your ___ in the box.", "ballot paper", ["Ballot paper"]),
  cloze("ex-pre-57-7", "57 · Điền từ", "The law was debated in ___.", "parliament", ["Parliament"]),
  cloze("ex-pre-57-8", "57 · Điền cụm", "The ___ addressed the nation.", "prime minister", ["Prime minister", "Prime Minister"]),
  mcq("ex-pre-57-9", "57 · Chọn đáp án", "Cuộc tranh luận chính thức về vấn đề công gọi là ___", "a", [
    { key: "a", label: "debate" },
    { key: "b", label: "speech" },
    { key: "c", label: "opinion poll" },
    { key: "d", label: "coalition" },
  ]),
  mcq("ex-pre-57-10", "57 · Chọn đáp án", "Cải cách hệ thống thuế gọi là ___", "b", [
    { key: "a", label: "public services" },
    { key: "b", label: "tax reform" },
    { key: "c", label: "policy" },
    { key: "d", label: "campaign" },
  ]),
  mcq("ex-pre-57-11", "57 · Chọn đáp án", "Đảng đối lập với chính quyền đương nhiệm gọi là ___", "c", [
    { key: "a", label: "coalition" },
    { key: "b", label: "parliament" },
    { key: "c", label: "opposition party" },
    { key: "d", label: "democracy" },
  ]),
  mcq("ex-pre-57-12", "57 · Chọn đáp án", "Liên minh giữa nhiều đảng để cầm quyền gọi là ___", "d", [
    { key: "a", label: "election" },
    { key: "b", label: "voter" },
    { key: "c", label: "protest march" },
    { key: "d", label: "coalition" },
  ]),
  mcq("ex-pre-57-13", "57 · Chọn đáp án", "Cuộc tuần hành biểu tình ôn hòa gọi là ___", "a", [
    { key: "a", label: "protest march" },
    { key: "b", label: "debate" },
    { key: "c", label: "speech" },
    { key: "d", label: "ballot paper" },
  ]),
  mcq("ex-pre-57-14", "57 · Chọn đáp án", "Khảo sát ý kiến dư luận gọi là ___", "b", [
    { key: "a", label: "campaign" },
    { key: "b", label: "opinion poll" },
    { key: "c", label: "tax reform" },
    { key: "d", label: "public services" },
  ]),
];

const UNIT_58: VocabularyExercise[] = [
  match("ex-pre-58-1", "58 · Ghép từ với nghĩa", [
    { left: "global warming", right: "hiện tượng nhiệt độ trái đất tăng dài hạn" },
    { left: "greenhouse gas", right: "khí nhà kính giữ nhiệt trong khí quyển" },
    { left: "carbon footprint", right: "lượng phát thải carbon do cá nhân/tổ chức tạo ra" },
    { left: "renewable energy", right: "nguồn năng lượng tái tạo như gió, mặt trời" },
    { left: "deforestation", right: "nạn chặt phá rừng diện rộng" },
    { left: "sustainability", right: "tính bền vững lâu dài về môi trường và xã hội" },
  ]),
  cloze("ex-pre-58-2", "58 · Điền cụm", "___ affects weather worldwide.", "Global warming", ["global warming"]),
  cloze("ex-pre-58-3", "58 · Điền cụm", "CO2 is a major ___.", "greenhouse gas", ["Greenhouse gas"]),
  cloze("ex-pre-58-4", "58 · Điền cụm", "Taking trains reduces your ___.", "carbon footprint", ["Carbon footprint"]),
  cloze("ex-pre-58-5", "58 · Điền cụm", "___ is growing quickly.", "Renewable energy", ["renewable energy"]),
  cloze("ex-pre-58-6", "58 · Điền cụm", "We installed ___ on the roof.", "solar panels", ["Solar panels", "solar panel", "Solar panel"]),
  cloze("ex-pre-58-7", "58 · Điền từ", "___ threatens biodiversity.", "Deforestation", ["deforestation"]),
  cloze("ex-pre-58-8", "58 · Điền cụm", "___ raises sea levels.", "Melting ice", ["melting ice"]),
  mcq("ex-pre-58-9", "58 · Chọn đáp án", "Mực nước biển dâng cao theo thời gian gọi là ___", "a", [
    { key: "a", label: "sea level rise" },
    { key: "b", label: "drought" },
    { key: "c", label: "wind farm" },
    { key: "d", label: "recycle" },
  ]),
  mcq("ex-pre-58-10", "58 · Chọn đáp án", "Thời tiết cực đoan khó dự đoán gọi là ___", "b", [
    { key: "a", label: "melting ice" },
    { key: "b", label: "extreme weather" },
    { key: "c", label: "carbon tax" },
    { key: "d", label: "net zero" },
  ]),
  mcq("ex-pre-58-11", "58 · Chọn đáp án", "Hạn hán kéo dài thiếu nước nghiêm trọng gọi là ___", "c", [
    { key: "a", label: "flood" },
    { key: "b", label: "deforestation" },
    { key: "c", label: "drought" },
    { key: "d", label: "climate action" },
  ]),
  mcq("ex-pre-58-12", "58 · Chọn đáp án", "Phương tiện chạy điện thay nhiên liệu hóa thạch gọi là ___", "d", [
    { key: "a", label: "solar panel" },
    { key: "b", label: "wind farm" },
    { key: "c", label: "greenhouse gas" },
    { key: "d", label: "electric vehicle" },
  ]),
  mcq("ex-pre-58-13", "58 · Chọn đáp án", "Mục tiêu phát thải ròng bằng không gọi là ___", "a", [
    { key: "a", label: "net zero" },
    { key: "b", label: "carbon footprint" },
    { key: "c", label: "renewable energy" },
    { key: "d", label: "recycle" },
  ]),
  mcq("ex-pre-58-14", "58 · Chọn đáp án", "Thuế áp lên lượng phát thải carbon gọi là ___", "b", [
    { key: "a", label: "climate action" },
    { key: "b", label: "carbon tax" },
    { key: "c", label: "sustainability" },
    { key: "d", label: "sea level rise" },
  ]),
];

const UNIT_59: VocabularyExercise[] = [
  match("ex-pre-59-1", "59 · Ghép từ với nghĩa", [
    { left: "conflict", right: "xung đột giữa các nhóm hoặc quốc gia" },
    { left: "ceasefire", right: "thỏa thuận ngừng bắn tạm thời" },
    { left: "refugee", right: "người tị nạn rời nơi ở vì chiến tranh/bạo lực" },
    { left: "civilian", right: "thường dân không tham chiến" },
    { left: "humanitarian aid", right: "hỗ trợ nhân đạo như lương thực, y tế" },
    { left: "peace talks", right: "đàm phán hòa bình để chấm dứt xung đột" },
  ]),
  cloze("ex-pre-59-2", "59 · Điền từ", "The ___ has lasted for years.", "conflict", ["Conflict"]),
  cloze("ex-pre-59-3", "59 · Điền từ", "Both sides agreed to a ___.", "ceasefire", ["Ceasefire"]),
  cloze("ex-pre-59-4", "59 · Điền từ", "The camp shelters many ___.", "refugees", ["Refugees", "refugee", "Refugee"]),
  cloze("ex-pre-59-5", "59 · Điền từ", "The army ___ villagers overnight.", "evacuated", ["Evacuated", "evacuate", "Evacuate"]),
  cloze("ex-pre-59-6", "59 · Điền từ", "Medical teams worked near the ___.", "frontline", ["Frontline", "front line", "Front line"]),
  cloze("ex-pre-59-7", "59 · Điền cụm", "The ___ damaged several buildings.", "air strike", ["Air strike"]),
  cloze("ex-pre-59-8", "59 · Điền cụm", "___ resumed this week.", "Peace talks", ["peace talks"]),
  mcq("ex-pre-59-9", "59 · Chọn đáp án", "Người thương vong trong xung đột gọi là ___", "c", [
    { key: "a", label: "civilian" },
    { key: "b", label: "hostage" },
    { key: "c", label: "casualty" },
    { key: "d", label: "refugee" },
  ]),
  mcq("ex-pre-59-10", "59 · Chọn đáp án", "Vũ khí dùng để tấn công hoặc phòng vệ gọi là ___", "a", [
    { key: "a", label: "weapon" },
    { key: "b", label: "ceasefire" },
    { key: "c", label: "peace talks" },
    { key: "d", label: "humanitarian aid" },
  ]),
  mcq("ex-pre-59-11", "59 · Chọn đáp án", "Nhóm có trang bị vũ trang gọi là ___", "b", [
    { key: "a", label: "civilian" },
    { key: "b", label: "armed group" },
    { key: "c", label: "refugee" },
    { key: "d", label: "casualty" },
  ]),
  mcq("ex-pre-59-12", "59 · Chọn đáp án", "Con tin bị bắt để gây áp lực gọi là ___", "d", [
    { key: "a", label: "weapon" },
    { key: "b", label: "frontline" },
    { key: "c", label: "air strike" },
    { key: "d", label: "hostage" },
  ]),
  mcq("ex-pre-59-13", "59 · Chọn đáp án", "Tội ác chiến tranh vi phạm luật quốc tế gọi là ___", "a", [
    { key: "a", label: "war crime" },
    { key: "b", label: "bomb blast" },
    { key: "c", label: "violent attack" },
    { key: "d", label: "conflict" },
  ]),
  mcq("ex-pre-59-14", "59 · Chọn đáp án", "Sang chấn tâm lý sau biến cố nghiêm trọng gọi là ___", "b", [
    { key: "a", label: "casualty" },
    { key: "b", label: "trauma" },
    { key: "c", label: "ceasefire" },
    { key: "d", label: "rebuild" },
  ]),
];

const UNIT_60: VocabularyExercise[] = [
  match("ex-pre-60-1", "60 · Ghép từ với nghĩa", [
    { left: "punctual", right: "đúng giờ, không trễ hẹn" },
    { left: "deadline", right: "hạn chót phải hoàn thành công việc" },
    { left: "on time", right: "đúng giờ theo kế hoạch ban đầu" },
    { left: "in advance", right: "trước một khoảng thời gian nhất định" },
    { left: "temporary", right: "tạm thời, không kéo dài mãi" },
    { left: "permanent", right: "lâu dài, ổn định" },
  ]),
  cloze("ex-pre-60-2", "60 · Điền từ", "She is always ___ for meetings.", "punctual", ["Punctual"]),
  cloze("ex-pre-60-3", "60 · Điền từ", "We must meet the project ___.", "deadline", ["Deadline"]),
  cloze("ex-pre-60-4", "60 · Điền từ", "My ___ is packed this week.", "schedule", ["Schedule"]),
  cloze("ex-pre-60-5", "60 · Điền từ", "Check the bus ___ before leaving.", "timetable", ["Timetable"]),
  cloze("ex-pre-60-6", "60 · Điền cụm", "The train arrived ___.", "on time", ["On time"]),
  cloze("ex-pre-60-7", "60 · Điền cụm", "Please book ___ for weekends.", "in advance", ["In advance"]),
  cloze("ex-pre-60-8", "60 · Điền từ", "Heavy traffic caused a long ___.", "delay", ["Delay"]),
  mcq("ex-pre-60-9", "60 · Chọn đáp án", "Hoãn lại sang thời điểm khác gọi là ___", "a", [
    { key: "a", label: "postpone" },
    { key: "b", label: "meanwhile" },
    { key: "c", label: "eventually" },
    { key: "d", label: "on time" },
  ]),
  mcq("ex-pre-60-10", "60 · Chọn đáp án", "Trong lúc đó, ở thời điểm song song gọi là ___", "b", [
    { key: "a", label: "recently" },
    { key: "b", label: "meanwhile" },
    { key: "c", label: "lately" },
    { key: "d", label: "in advance" },
  ]),
  mcq("ex-pre-60-11", "60 · Chọn đáp án", "Cuối cùng sau nhiều chờ đợi gọi là ___", "c", [
    { key: "a", label: "currently" },
    { key: "b", label: "meanwhile" },
    { key: "c", label: "eventually" },
    { key: "d", label: "recently" },
  ]),
  mcq("ex-pre-60-12", "60 · Chọn đáp án", "Hiện tại, vào lúc này gọi là ___", "d", [
    { key: "a", label: "lately" },
    { key: "b", label: "eventually" },
    { key: "c", label: "recently" },
    { key: "d", label: "currently" },
  ]),
  mcq("ex-pre-60-13", "60 · Chọn đáp án", "Thời gian rảnh ngoài việc chính gọi là ___", "a", [
    { key: "a", label: "spare time" },
    { key: "b", label: "time zone" },
    { key: "c", label: "timetable" },
    { key: "d", label: "deadline" },
  ]),
  mcq("ex-pre-60-14", "60 · Chọn đáp án", "Chế độ chỉnh đồng hồ theo mùa để tận dụng ánh sáng gọi là ___", "b", [
    { key: "a", label: "time zone" },
    { key: "b", label: "daylight saving" },
    { key: "c", label: "schedule" },
    { key: "d", label: "temporary" },
  ]),
];

export const CURATED_PRE_UNITS_46_60: Readonly<Partial<Record<number, readonly VocabularyExercise[]>>> = {
  46: UNIT_46,
  47: UNIT_47,
  48: UNIT_48,
  49: UNIT_49,
  50: UNIT_50,
  51: UNIT_51,
  52: UNIT_52,
  53: UNIT_53,
  54: UNIT_54,
  55: UNIT_55,
  56: UNIT_56,
  57: UNIT_57,
  58: UNIT_58,
  59: UNIT_59,
  60: UNIT_60,
};

for (const [unitNumber, exercises] of Object.entries(CURATED_PRE_UNITS_46_60)) {
  if (exercises) {
    assertExerciseCount(Number(unitNumber), exercises);
  }
}
