import type { VocabularyUnit } from "../vocabulary-unit-types";
import { ex, fillBlank, mcq, purple } from "./eviu-unit-builder";
import { preUnit, wordList } from "./eviu-pre-unit-helpers";

const U31_WORDS = wordList([
  ["handout", "tài liệu phát tay trong giờ học", "Please keep the handout for next lesson."],
  ["whiteboard", "bảng trắng dùng trong lớp học", "Write your answers on the whiteboard."],
  ["attendance", "sĩ số hoặc điểm danh", "Attendance is taken at the start of class."],
  ["timetable", "thời khóa biểu theo tiết học", "Check your timetable before Monday."],
  ["pair work", "hoạt động làm việc theo cặp", "We will do pair work for ten minutes."],
  ["group discussion", "thảo luận nhóm trong lớp", "The group discussion helped me speak more."],
  ["raise your hand", "giơ tay xin phát biểu", "Raise your hand if you know the answer.", "VERB"],
  ["take notes", "ghi chép ý chính khi học", "Take notes while watching the video.", "VERB"],
  ["submit", "nộp bài cho giáo viên", "Please submit your homework by Friday.", "VERB"],
  ["revise", "ôn lại kiến thức đã học", "I revise vocabulary every evening.", "VERB"],
  ["pronunciation drill", "bài luyện phát âm lặp lại", "We did a pronunciation drill in class."],
  ["worksheet", "phiếu bài tập trên lớp", "Finish the worksheet in pairs."],
  ["instruction", "hướng dẫn cho nhiệm vụ học tập", "Read the instruction carefully before starting."],
  ["deadline", "hạn chót phải hoàn thành", "The project deadline is next Tuesday."],
  ["absent", "vắng mặt trong buổi học", "Minh was absent yesterday.", "ADJECTIVE"],
  ["participate", "tham gia chủ động vào hoạt động", "Everyone should participate in the activity.", "VERB"],
  ["clarify", "làm rõ điều chưa hiểu", "Can you clarify question three?", "VERB"],
  ["assignment", "bài tập được giao về nhà", "Our assignment is to write a short paragraph."],
]);

const U32_WORDS = wordList([
  ["curriculum", "chương trình học chính thức", "The curriculum includes science and arts."],
  ["semester", "học kỳ trong năm học", "This semester ends in December."],
  ["term", "kỳ học ngắn trong niên khóa", "We have three terms this year."],
  ["compulsory subject", "môn học bắt buộc", "Maths is a compulsory subject."],
  ["optional subject", "môn học tự chọn", "Music is an optional subject."],
  ["headteacher", "hiệu trưởng trường phổ thông", "The headteacher spoke at assembly."],
  ["school uniform", "đồng phục học sinh", "Our school uniform is blue and white."],
  ["assembly", "buổi tập trung toàn trường", "There is an assembly every Monday morning."],
  ["report card", "phiếu kết quả học tập", "I showed my report card to my parents."],
  ["grade", "điểm số hoặc mức đánh giá", "She got a high grade in physics."],
  ["detention", "hình thức phạt ở lại trường", "He had detention for being late."],
  ["playground", "sân chơi trong khuôn viên trường", "Students meet in the playground at break."],
  ["canteen", "nhà ăn của trường", "We usually have lunch in the canteen."],
  ["school trip", "chuyến đi ngoại khóa của trường", "The school trip was very educational."],
  ["principal", "người quản lý cao nhất của trường", "The principal welcomed new students."],
  ["drop out", "bỏ học giữa chừng", "He did not drop out; he changed schools.", "VERB"],
  ["discipline", "kỷ luật trong môi trường học đường", "Good discipline creates a better learning space."],
  ["tuition fee", "học phí phải đóng cho trường", "The tuition fee increased this year."],
]);

const U33_WORDS = wordList([
  ["mock exam", "kỳ thi thử trước kỳ thi chính", "We take a mock exam every month."],
  ["exam paper", "đề thi được phát trong phòng thi", "Do not write on the exam paper first."],
  ["invigilator", "giám thị coi thi", "The invigilator checked our IDs."],
  ["candidate", "thí sinh tham gia kỳ thi", "Each candidate has a number."],
  ["marking scheme", "thang điểm và tiêu chí chấm", "Read the marking scheme after practice."],
  ["time management", "kỹ năng phân bổ thời gian làm bài", "Time management is crucial in reading tests."],
  ["word stress", "trọng âm từ trong phát âm", "Word stress can change meaning."],
  ["listen for gist", "nghe lấy ý chính", "Try to listen for gist before details.", "VERB"],
  ["scan for details", "quét nhanh để tìm chi tiết", "In reading, scan for details first.", "VERB"],
  ["proofread", "đọc soát lỗi trước khi nộp", "Always proofread your writing task.", "VERB"],
  ["grammar accuracy", "độ chính xác ngữ pháp", "Grammar accuracy affects your final score."],
  ["band score", "mức điểm theo thang bậc", "My target band score is 6.5."],
  ["retake", "thi lại để cải thiện điểm", "She plans to retake the exam.", "VERB"],
  ["revision plan", "kế hoạch ôn thi có cấu trúc", "Make a weekly revision plan."],
  ["sample answer", "bài mẫu tham khảo", "Compare your essay with a sample answer."],
  ["test strategy", "chiến lược làm bài thi", "A clear test strategy reduces stress."],
  ["distractor", "đáp án nhiễu trong bài trắc nghiệm", "Ignore distractors in multiple-choice questions."],
  ["pass mark", "điểm tối thiểu để đạt", "The pass mark is 50 percent."],
]);

const U34_WORDS = wordList([
  ["undergraduate", "sinh viên bậc cử nhân", "She is an undergraduate in economics."],
  ["postgraduate", "học viên sau đại học", "He is a postgraduate student."],
  ["campus", "khuôn viên trường đại học", "The campus is near the city center."],
  ["lecture hall", "giảng đường lớn của đại học", "Our class is in lecture hall B."],
  ["seminar", "buổi học thảo luận chuyên sâu", "We had a seminar on media ethics."],
  ["tutorial", "buổi hướng dẫn nhóm nhỏ", "The tutorial is every Thursday afternoon."],
  ["credit", "đơn vị tín chỉ học phần", "This module is worth three credits."],
  ["major", "chuyên ngành chính của sinh viên", "My major is computer science."],
  ["minor", "chuyên ngành phụ", "She takes psychology as a minor."],
  ["module", "học phần trong chương trình", "I am taking a statistics module."],
  ["thesis", "luận văn tốt nghiệp", "He is writing his thesis now."],
  ["scholarship", "học bổng hỗ trợ tài chính", "She received a full scholarship."],
  ["dormitory", "ký túc xá sinh viên", "I live in a dormitory on campus."],
  ["academic advisor", "cố vấn học tập", "Talk to your academic advisor first."],
  ["enrol", "đăng ký theo học", "You must enrol before the deadline.", "VERB"],
  ["defer", "hoãn việc học sang kỳ sau", "She decided to defer one semester.", "VERB"],
  ["graduate", "tốt nghiệp hoàn thành chương trình", "He will graduate next summer.", "VERB"],
  ["tuition waiver", "miễn giảm học phí", "The university offered a tuition waiver."],
]);

const U35_WORDS = wordList([
  ["occupation", "nghề nghiệp của một người", "What is your occupation?"],
  ["profession", "nghề chuyên môn cần đào tạo", "Teaching is a respected profession."],
  ["trade", "nghề thủ công hoặc kỹ thuật", "He learned the trade from his father."],
  ["full-time", "làm việc toàn thời gian", "I have a full-time position.", "ADJECTIVE"],
  ["part-time", "làm việc bán thời gian", "Many students have part-time jobs.", "ADJECTIVE"],
  ["self-employed", "tự kinh doanh không làm thuê", "She is self-employed as a designer.", "ADJECTIVE"],
  ["freelancer", "người làm nghề tự do", "He works as a freelance translator."],
  ["job vacancy", "vị trí tuyển dụng còn trống", "I saw a job vacancy online."],
  ["job description", "mô tả nhiệm vụ công việc", "Read the job description carefully."],
  ["qualification", "bằng cấp hoặc chứng chỉ", "You need the right qualification."],
  ["experience", "kinh nghiệm làm việc thực tế", "She has five years of experience."],
  ["internship", "kỳ thực tập nghề nghiệp", "I completed an internship last summer."],
  ["shift", "ca làm việc theo giờ", "My shift starts at 7 a.m."],
  ["salary", "lương cố định hàng tháng", "The salary is paid on the last day."],
  ["wage", "tiền công tính theo giờ/ngày", "Factory workers earn hourly wages."],
  ["resign", "xin nghỉ việc tự nguyện", "He plans to resign next month.", "VERB"],
  ["recruit", "tuyển dụng nhân sự mới", "The company will recruit more staff.", "VERB"],
  ["promotion", "sự thăng chức lên vị trí cao hơn", "She got a promotion after two years."],
]);

const U36_WORDS = wordList([
  ["workload", "khối lượng công việc phải xử lý", "My workload is heavy this week."],
  ["deadline pressure", "áp lực vì hạn chót công việc", "Deadline pressure affects sleep."],
  ["responsibility", "trách nhiệm trong vai trò làm việc", "My main responsibility is client support."],
  ["task list", "danh sách việc cần làm", "I update my task list every morning."],
  ["prioritise", "ưu tiên việc quan trọng trước", "You should prioritise urgent tasks.", "VERB"],
  ["multitask", "xử lý nhiều việc cùng lúc", "I can multitask in a busy office.", "VERB"],
  ["coordinate", "phối hợp công việc với người khác", "I coordinate with the sales team.", "VERB"],
  ["colleague", "đồng nghiệp cùng cơ quan", "My colleagues are very supportive."],
  ["supervisor", "người giám sát trực tiếp", "Ask your supervisor for approval."],
  ["team lead", "trưởng nhóm phụ trách nhóm nhỏ", "Our team lead runs weekly check-ins."],
  ["remote work", "làm việc từ xa không đến văn phòng", "Remote work saves commuting time."],
  ["hybrid schedule", "lịch làm việc kết hợp online/offline", "We follow a hybrid schedule."],
  ["overtime", "làm thêm giờ ngoài ca chính", "I had to do overtime yesterday."],
  ["performance review", "buổi đánh giá hiệu suất làm việc", "My performance review is next week."],
  ["work-life balance", "cân bằng giữa việc và cuộc sống", "Good work-life balance prevents burnout."],
  ["commute", "di chuyển hằng ngày đến nơi làm việc", "I commute by train.", "VERB"],
  ["report to", "báo cáo trực tiếp cho ai", "I report to the operations manager.", "VERB"],
  ["on leave", "đang nghỉ phép theo chế độ", "She is on leave this Friday.", "ADJECTIVE"],
]);

const U37_WORDS = wordList([
  ["career path", "lộ trình phát triển nghề nghiệp", "He has a clear career path."],
  ["career goal", "mục tiêu nghề nghiệp dài hạn", "Set a realistic career goal."],
  ["skill set", "bộ kỹ năng phục vụ công việc", "Your skill set is strong."],
  ["upskill", "nâng cấp kỹ năng hiện có", "I need to upskill in data analysis.", "VERB"],
  ["reskill", "học kỹ năng mới để chuyển nghề", "Many workers reskill after automation.", "VERB"],
  ["networking", "xây dựng quan hệ nghề nghiệp", "Networking helped her find new opportunities."],
  ["mentor", "người cố vấn nghề nghiệp", "A mentor can guide your decisions."],
  ["mentorship", "quá trình được cố vấn dài hạn", "The company offers a mentorship program."],
  ["career break", "khoảng nghỉ tạm khỏi sự nghiệp", "She took a career break to study."],
  ["job hopping", "thay đổi công việc quá thường xuyên", "Job hopping can worry employers."],
  ["professional development", "phát triển năng lực chuyên môn", "Training supports professional development."],
  ["leadership", "năng lực dẫn dắt đội nhóm", "Leadership is more than giving orders."],
  ["portfolio", "hồ sơ sản phẩm hoặc thành tựu", "Show your portfolio at interviews."],
  ["certification", "chứng nhận năng lực chuyên môn", "He earned a cloud certification."],
  ["side project", "dự án làm thêm ngoài công việc chính", "A side project improved my coding skills."],
  ["career ladder", "nấc thang thăng tiến trong nghề", "She moved up the career ladder quickly."],
  ["long-term vision", "tầm nhìn dài hạn cho sự nghiệp", "Have a long-term vision before switching jobs."],
  ["stand out", "nổi bật so với ứng viên khác", "This achievement helps you stand out.", "VERB"],
]);

const U38_WORDS = wordList([
  ["workstation", "bàn làm việc kèm thiết bị", "Each employee has a workstation."],
  ["office supplies", "vật dụng văn phòng thường dùng", "Office supplies are kept in that cabinet."],
  ["stationery", "văn phòng phẩm như bút giấy", "We need more stationery this month."],
  ["printer queue", "hàng đợi lệnh in tài liệu", "The printer queue is very long."],
  ["photocopier", "máy photocopy tài liệu", "The photocopier is out of paper."],
  ["meeting room", "phòng họp cho nhóm làm việc", "Book the meeting room in advance."],
  ["conference call", "cuộc họp từ xa qua điện thoại", "We have a conference call at 3 p.m."],
  ["minute-taking", "ghi biên bản nội dung cuộc họp", "Minute-taking is part of my role."],
  ["agenda", "chương trình nội dung cuộc họp", "Please send the agenda beforehand."],
  ["follow-up email", "email gửi sau họp để chốt việc", "I wrote a follow-up email to clients."],
  ["inbox", "hộp thư nhận email", "My inbox is full today."],
  ["outbox", "hộp thư đã gửi đi", "Check the outbox for confirmation."],
  ["attachment", "tệp đính kèm trong email", "Do not forget the attachment."],
  ["file a document", "lưu hồ sơ đúng thư mục", "Please file the document by date.", "VERB"],
  ["book a room", "đặt trước phòng họp", "Can you book a room for tomorrow?", "VERB"],
  ["schedule a meeting", "xếp lịch một cuộc họp", "Let's schedule a meeting for Friday.", "VERB"],
  ["office etiquette", "quy tắc ứng xử nơi công sở", "Office etiquette matters in open spaces."],
  ["hot desk", "chỗ ngồi linh hoạt không cố định", "Our team uses a hot desk system."],
]);

const U39_WORDS = wordList([
  ["startup", "công ty khởi nghiệp giai đoạn đầu", "He launched a startup in fintech."],
  ["founder", "người sáng lập công ty", "The founder pitched to investors."],
  ["co-founder", "đồng sáng lập cùng xây công ty", "She is the co-founder of the app."],
  ["shareholder", "cổ đông sở hữu cổ phần doanh nghiệp", "Shareholders voted on the proposal."],
  ["board of directors", "hội đồng quản trị công ty", "The board of directors approved the budget."],
  ["department", "phòng ban chức năng trong công ty", "I work in the marketing department."],
  ["human resources", "bộ phận nhân sự quản lý con người", "Human resources handles recruitment."],
  ["operations", "hoạt động vận hành hằng ngày", "Operations must run smoothly."],
  ["revenue stream", "nguồn doanh thu của doanh nghiệp", "Subscription is our main revenue stream."],
  ["business model", "mô hình tạo giá trị và lợi nhuận", "Their business model is scalable."],
  ["overhead cost", "chi phí vận hành gián tiếp", "Rent is a major overhead cost."],
  ["cash flow", "dòng tiền vào ra của công ty", "Healthy cash flow keeps business stable."],
  ["expand", "mở rộng quy mô kinh doanh", "They plan to expand into Asia.", "VERB"],
  ["outsource", "thuê ngoài một phần công việc", "We outsource payroll processing.", "VERB"],
  ["delegate", "phân quyền và giao việc cho cấp dưới", "Managers should delegate effectively.", "VERB"],
  ["set up", "thành lập và bắt đầu vận hành", "She set up an online store.", "VERB"],
  ["stakeholder", "bên liên quan đến hoạt động công ty", "Employees are key stakeholders."],
  ["merger", "thương vụ sáp nhập hai công ty", "The merger created a larger group."],
]);

const U40_WORDS = wordList([
  ["turnover", "doanh thu trong một giai đoạn", "The company doubled its turnover."],
  ["profit margin", "biên lợi nhuận sau chi phí", "Low profit margin worries investors."],
  ["net profit", "lợi nhuận ròng sau tất cả chi phí", "Net profit increased this quarter."],
  ["loss", "thua lỗ tài chính", "The firm reported a small loss."],
  ["budget", "ngân sách phân bổ cho hoạt động", "We need a realistic budget."],
  ["forecast", "dự báo tài chính tương lai", "The sales forecast is optimistic."],
  ["invoice", "hóa đơn yêu cầu thanh toán", "Please send the invoice today."],
  ["receipt", "biên nhận đã thanh toán", "Keep the receipt for reimbursement."],
  ["debt", "khoản nợ phải trả", "The company reduced its debt."],
  ["interest rate", "lãi suất áp dụng cho khoản vay", "Interest rates rose again."],
  ["loan", "khoản vay từ ngân hàng", "They took a loan to buy equipment."],
  ["investment", "khoản đầu tư để sinh lợi", "Foreign investment is growing."],
  ["asset", "tài sản có giá trị kinh tế", "Property is a long-term asset."],
  ["liability", "nghĩa vụ nợ phải thanh toán", "Short-term liabilities are too high."],
  ["break even", "hòa vốn không lãi không lỗ", "We hope to break even this year.", "VERB"],
  ["pay off", "trả hết khoản nợ", "She paid off her student loan.", "VERB"],
  ["allocate", "phân bổ nguồn lực hoặc tiền", "Allocate more funds to training.", "VERB"],
  ["financial statement", "báo cáo tài chính chính thức", "The auditor reviewed the financial statement."],
]);

const U41_WORDS = wordList([
  ["leisure activity", "hoạt động giải trí lúc rảnh", "Reading is my favourite leisure activity."],
  ["workout", "buổi tập luyện thể chất", "I do a workout after work."],
  ["fitness class", "lớp tập thể dục theo nhóm", "She joined a fitness class."],
  ["hiking", "hoạt động đi bộ đường dài", "We go hiking at weekends."],
  ["cycling", "đạp xe để rèn sức khỏe hoặc giải trí", "Cycling helps me relax."],
  ["swimming", "môn bơi lội", "Swimming is good for your back."],
  ["yoga", "bộ môn luyện thân tâm bằng tư thế thở", "Yoga improves flexibility."],
  ["pilates", "bộ môn tăng sức mạnh cơ lõi", "Pilates classes are full this month."],
  ["board game", "trò chơi bàn cờ tại nhà", "We played a board game after dinner."],
  ["craft", "hoạt động thủ công sáng tạo", "Paper craft is popular with kids."],
  ["pastime", "thú tiêu khiển thường ngày", "Photography is his main pastime."],
  ["take up", "bắt đầu theo đuổi sở thích mới", "I want to take up tennis.", "VERB"],
  ["wind down", "thư giãn sau ngày bận rộn", "Music helps me wind down.", "VERB"],
  ["stay active", "duy trì vận động đều đặn", "Try to stay active every day.", "VERB"],
  ["recharge", "nạp lại năng lượng tinh thần", "Weekends help me recharge.", "VERB"],
  ["social club", "câu lạc bộ sinh hoạt cộng đồng", "He joined a local social club."],
  ["outdoor pursuit", "hoạt động ngoài trời mang tính thư giãn", "Kayaking is an outdoor pursuit."],
  ["spectator sport", "môn thể thao hấp dẫn người xem", "Football is a top spectator sport."],
]);

const U42_WORDS = wordList([
  ["tournament", "giải đấu gồm nhiều vòng tranh tài", "Our team entered a tournament."],
  ["championship", "giải vô địch cấp cao", "She won the national championship."],
  ["final", "trận đấu cuối cùng quyết định", "They reached the final."],
  ["semi-final", "trận bán kết trước chung kết", "The semi-final is on Saturday."],
  ["qualifier", "vòng loại để giành suất đi tiếp", "This match is a qualifier."],
  ["fixture", "lịch thi đấu chính thức", "Check the fixture for next week."],
  ["referee", "trọng tài điều hành trận đấu", "The referee gave a red card."],
  ["coach", "huấn luyện viên của đội", "The coach changed the tactics."],
  ["captain", "đội trưởng đại diện đội bóng", "Our captain motivated everyone."],
  ["substitute", "cầu thủ dự bị vào sân thay người", "A substitute scored in minute 90."],
  ["penalty", "quả phạt đền hoặc hình phạt", "They won by a penalty."],
  ["draw", "kết quả hòa không phân thắng bại", "The game ended in a draw."],
  ["defeat", "kết quả thất bại trước đối thủ", "It was their first defeat this season."],
  ["stamina", "sức bền trong thi đấu", "Long runs build stamina."],
  ["injury time", "thời gian bù giờ cuối trận", "They scored in injury time."],
  ["knock out", "loại đối thủ khỏi giải đấu", "They knocked out the champions.", "VERB"],
  ["equalise", "gỡ hòa đưa tỷ số cân bằng", "She equalised in the second half.", "VERB"],
  ["set a record", "lập kỷ lục mới", "He set a record in the 200m race.", "VERB"],
]);

const U43_WORDS = wordList([
  ["novel", "tiểu thuyết có cốt truyện dài", "I am reading a historical novel."],
  ["biography", "sách tiểu sử về một người thật", "This biography is very inspiring."],
  ["memoir", "hồi ký kể trải nghiệm cá nhân", "Her memoir became a bestseller."],
  ["plot", "mạch truyện và diễn biến chính", "The plot is full of surprises."],
  ["character arc", "quá trình thay đổi của nhân vật", "The hero has a strong character arc."],
  ["setting", "bối cảnh thời gian và không gian", "The setting is a small seaside town."],
  ["genre", "thể loại tác phẩm", "My favourite genre is sci-fi."],
  ["soundtrack", "nhạc nền của phim", "The soundtrack was unforgettable."],
  ["subtitle", "phụ đề hiển thị dưới màn hình", "I watched it with English subtitles."],
  ["adaptation", "phiên bản chuyển thể từ tác phẩm khác", "The film is an adaptation of a novel."],
  ["sequel", "phần tiếp theo của phim hoặc sách", "Fans are waiting for the sequel."],
  ["review", "bài nhận xét đánh giá tác phẩm", "I read a review before buying it."],
  ["spoiler", "chi tiết tiết lộ làm mất bất ngờ", "Please do not post spoilers."],
  ["bestseller", "sách bán chạy số lượng lớn", "Her latest book is a bestseller."],
  ["blockbuster", "phim ăn khách doanh thu cao", "The summer blockbuster broke records."],
  ["page-turner", "sách cuốn hút muốn đọc liên tục", "That thriller is a real page-turner."],
  ["captivating", "rất cuốn hút người xem/đọc", "The story was captivating from start to end.", "ADJECTIVE"],
  ["thought-provoking", "gợi suy nghĩ sâu về vấn đề", "It is a thought-provoking documentary.", "ADJECTIVE"],
]);

const U44_WORDS = wordList([
  ["melody", "giai điệu chính dễ nhận ra", "The melody stayed in my head all day."],
  ["rhythm", "nhịp điệu lặp lại của âm nhạc", "This song has a strong rhythm."],
  ["lyrics", "lời bài hát", "I love the lyrics of this track."],
  ["chorus", "điệp khúc lặp lại trong bài hát", "Everyone sang the chorus together."],
  ["verse", "đoạn lời chính giữa các điệp khúc", "The second verse tells the story."],
  ["harmony", "hòa âm giữa nhiều nốt hoặc giọng", "Their vocal harmony is excellent."],
  ["tempo", "tốc độ nhanh chậm của bản nhạc", "The tempo becomes faster near the end."],
  ["genre", "dòng nhạc hoặc thể loại âm nhạc", "Jazz is my favourite genre."],
  ["playlist", "danh sách bài hát phát liên tục", "I made a study playlist."],
  ["single", "bài hát phát hành riêng lẻ", "The band released a new single."],
  ["album", "tuyển tập nhiều bài hát phát hành cùng", "Their debut album won an award."],
  ["gig", "buổi diễn nhạc nhỏ trực tiếp", "We went to a jazz gig last night."],
  ["concert hall", "nhà hát tổ chức biểu diễn âm nhạc", "The concert hall was full."],
  ["encore", "phần diễn thêm theo yêu cầu khán giả", "The crowd asked for an encore."],
  ["perform live", "biểu diễn trực tiếp trước khán giả", "She will perform live this weekend.", "VERB"],
  ["tune", "chỉnh âm nhạc cụ cho chuẩn", "Please tune your guitar first.", "VERB"],
  ["compose", "sáng tác tác phẩm âm nhạc", "He composes music for films.", "VERB"],
  ["improvise", "ngẫu hứng tạo giai điệu tại chỗ", "Jazz musicians often improvise.", "VERB"],
]);

const U45_WORDS = wordList([
  ["anniversary", "ngày kỷ niệm theo mốc thời gian", "Today is our wedding anniversary."],
  ["milestone event", "sự kiện cột mốc quan trọng", "Graduation is a milestone event."],
  ["ceremony", "buổi lễ trang trọng theo nghi thức", "The opening ceremony starts at 8."],
  ["celebration", "hoạt động ăn mừng một dịp đặc biệt", "The whole town joined the celebration."],
  ["festival", "lễ hội văn hóa theo mùa hoặc truyền thống", "The lantern festival attracts many visitors."],
  ["parade", "đoàn diễu hành trên đường phố", "A parade moved through downtown."],
  ["fireworks", "pháo hoa biểu diễn trên bầu trời", "We watched fireworks at midnight."],
  ["banquet", "tiệc lớn mang tính nghi thức", "The hotel hosted a charity banquet."],
  ["guest list", "danh sách khách mời tham dự", "Please finalise the guest list today."],
  ["invitation", "thiệp hoặc lời mời tham dự", "I sent the invitation by email."],
  ["venue", "địa điểm tổ chức sự kiện", "The venue can hold 500 people."],
  ["dress code", "quy định trang phục cho sự kiện", "The dress code is formal."],
  ["host", "người chủ trì hoặc tổ chức sự kiện", "Who will host the award night?", "VERB"],
  ["attend", "tham dự sự kiện với tư cách khách", "Many alumni attended the reunion.", "VERB"],
  ["postpone", "hoãn sự kiện sang thời điểm khác", "Rain may postpone the outdoor event.", "VERB"],
  ["commemorate", "tưởng niệm hoặc kỷ niệm chính thức", "The event commemorates local heroes.", "VERB"],
  ["once-in-a-lifetime", "hiếm có, chỉ xảy ra một lần", "It was a once-in-a-lifetime experience.", "ADJECTIVE"],
  ["memorable", "đáng nhớ và để lại ấn tượng", "It was a memorable evening.", "ADJECTIVE"],
]);

export const EVIU_PRE_UNITS_31_45: VocabularyUnit[] = [
  preUnit(31, {
    introVi: "Unit 31 tập trung vào ngôn ngữ sử dụng trong lớp học: nghe hướng dẫn, đặt câu hỏi, nộp bài và tương tác với giáo viên.",
    structureSections: [
      { label: "Classroom objects and routine", wordCount: 6 },
      { label: "Learning actions", wordCount: 6 },
      { label: "Participation and progress", wordCount: 6 },
    ],
    collocationHtml: `${purple("raise your hand")}, ${purple("take notes")} và ${purple("submit assignment")} là bộ cụm cốt lõi trong giờ học.`,
    mistakeHtml: `Đừng lẫn ${purple("assignment")} với ${purple("exercise")}: assignment thường là nhiệm vụ có hạn nộp.`,
    principles: [
      {
        title: "Hiểu đúng chỉ dẫn lớp học",
        body: `Nắm các từ như ${purple("instruction")}, ${purple("deadline")} để tránh làm sai yêu cầu.`,
        examples: [ex("Read the instruction before you start.", "Hãy đọc hướng dẫn trước khi bắt đầu.")],
      },
      {
        title: "Tương tác chủ động",
        body: `Trong lớp, hãy ${purple("raise your hand")} và ${purple("clarify")} khi chưa hiểu.`,
        examples: [ex("Please clarify this grammar point.", "Cô/Thầy vui lòng làm rõ điểm ngữ pháp này.")],
      },
      {
        title: "Giữ nhịp học đều",
        body: `Kết hợp ${purple("take notes")} và ${purple("revise")} để nhớ lâu hơn sau buổi học.`,
        examples: [ex("I revise my notes after class.", "Tôi ôn lại ghi chép sau giờ học.")],
      },
    ],
    words: U31_WORDS,
    exercises: [
      mcq(
        31,
        1,
        "Trong lớp học, cụm nào nghĩa là giơ tay xin phát biểu?",
        [
          { key: "a", label: "take notes" },
          { key: "b", label: "raise your hand" },
          { key: "c", label: "submit" },
          { key: "d", label: "pair work" },
        ],
        "b",
      ),
      fillBlank(
        31,
        2,
        "Please ____ your assignment before the deadline.",
        "submit",
        [
          { key: "a", label: "clarify" },
          { key: "b", label: "revise" },
          { key: "c", label: "submit" },
          { key: "d", label: "participate" },
        ],
        "c",
      ),
      mcq(
        31,
        3,
        "Từ nào chỉ thời khóa biểu của các tiết học?",
        [
          { key: "a", label: "attendance" },
          { key: "b", label: "worksheet" },
          { key: "c", label: "timetable" },
          { key: "d", label: "deadline" },
        ],
        "c",
      ),
    ],
  }),
  preUnit(32, {
    introVi: "Unit 32 mở rộng từ vựng về giáo dục phổ thông: môn học, tổ chức trường học và hệ thống đánh giá.",
    structureSections: [
      { label: "School system", wordCount: 6 },
      { label: "Subjects and assessment", wordCount: 6 },
      { label: "School life", wordCount: 6 },
    ],
    collocationHtml: `${purple("compulsory subject")}, ${purple("report card")} và ${purple("school trip")} thường xuất hiện trong giao tiếp về trường học.`,
    mistakeHtml: `Phân biệt ${purple("grade")} (điểm) và ${purple("year")} (khối/lớp học theo niên khóa).`,
    principles: [
      {
        title: "Nói về môn học rõ ràng",
        body: `Dùng ${purple("compulsory subject")} và ${purple("optional subject")} để phân loại chính xác.`,
        examples: [ex("Art is an optional subject in my school.", "Mỹ thuật là môn tự chọn ở trường tôi.")],
      },
      {
        title: "Mô tả môi trường trường học",
        body: `Các từ như ${purple("assembly")}, ${purple("canteen")} và ${purple("playground")} giúp kể đời sống học đường tự nhiên hơn.`,
        examples: [ex("We meet at assembly every Monday.", "Chúng tôi tập trung toàn trường mỗi thứ Hai.")],
      },
      {
        title: "Hiểu hệ thống đánh giá",
        body: `${purple("report card")} tổng hợp ${purple("grade")} theo từng môn và kỳ học.`,
        examples: [ex("Her report card shows strong progress.", "Phiếu điểm của bạn ấy cho thấy tiến bộ tốt.")],
      },
    ],
    words: U32_WORDS,
    exercises: [
      mcq(
        32,
        1,
        "Môn học bắt buộc được gọi là gì?",
        [
          { key: "a", label: "optional subject" },
          { key: "b", label: "compulsory subject" },
          { key: "c", label: "school trip" },
          { key: "d", label: "detention" },
        ],
        "b",
      ),
      fillBlank(
        32,
        2,
        "I showed my ____ to my parents after the semester.",
        "report card",
        [
          { key: "a", label: "report card" },
          { key: "b", label: "playground" },
          { key: "c", label: "assembly" },
          { key: "d", label: "uniform" },
        ],
        "a",
      ),
      mcq(
        32,
        3,
        "Từ nào chỉ người đứng đầu trường học?",
        [
          { key: "a", label: "principal" },
          { key: "b", label: "candidate" },
          { key: "c", label: "invigilator" },
          { key: "d", label: "mentor" },
        ],
        "a",
      ),
    ],
  }),
  preUnit(33, {
    introVi: "Unit 33 xoay quanh việc học tiếng Anh và thi cử: từ kỹ thuật làm bài đến từ vựng phòng thi.",
    structureSections: [
      { label: "Exam setting", wordCount: 6 },
      { label: "Test techniques", wordCount: 6 },
      { label: "Results and improvement", wordCount: 6 },
    ],
    collocationHtml: `${purple("mock exam")}, ${purple("time management")} và ${purple("band score")} là các cụm quan trọng khi luyện thi.`,
    mistakeHtml: `Không phụ thuộc hoàn toàn vào ${purple("sample answer")}; hãy dùng nó để học cách tổ chức ý, không phải chép lại.`,
    principles: [
      {
        title: "Luyện thi theo mô phỏng thật",
        body: `Làm ${purple("mock exam")} định kỳ giúp quen áp lực thời gian và định dạng đề.`,
        examples: [ex("I do one mock exam every Sunday.", "Tôi làm một đề thi thử mỗi Chủ nhật.")],
      },
      {
        title: "Kết hợp kỹ thuật đọc-nghe",
        body: `Khi làm bài, cần ${purple("listen for gist")} rồi mới ${purple("scan for details")}.`,
        examples: [ex("First get the main idea, then find key details.", "Đầu tiên nắm ý chính, rồi tìm chi tiết quan trọng.")],
      },
      {
        title: "Tự đánh giá để cải thiện",
        body: `Đối chiếu bài với ${purple("marking scheme")} và kiểm tra ${purple("grammar accuracy")}.`,
        examples: [ex("Proofread before you hand in the test.", "Hãy đọc soát trước khi nộp bài.")],
      },
    ],
    words: U33_WORDS,
    exercises: [
      mcq(
        33,
        1,
        "Người coi thi trong phòng thi được gọi là gì?",
        [
          { key: "a", label: "candidate" },
          { key: "b", label: "invigilator" },
          { key: "c", label: "mentor" },
          { key: "d", label: "coach" },
        ],
        "b",
      ),
      fillBlank(
        33,
        2,
        "Good ____ helps you finish all sections on time.",
        "time management",
        [
          { key: "a", label: "word stress" },
          { key: "b", label: "time management" },
          { key: "c", label: "retake" },
          { key: "d", label: "pass mark" },
        ],
        "b",
      ),
      mcq(
        33,
        3,
        "Cụm nào nghĩa là kỳ thi thử?",
        [
          { key: "a", label: "pass mark" },
          { key: "b", label: "sample answer" },
          { key: "c", label: "mock exam" },
          { key: "d", label: "exam paper" },
        ],
        "c",
      ),
    ],
  }),
  preUnit(34, {
    introVi: "Unit 34 giới thiệu ngôn ngữ về bậc đại học: chương trình học, môi trường campus và tiến trình tốt nghiệp.",
    structureSections: [
      { label: "University structure", wordCount: 6 },
      { label: "Academic pathway", wordCount: 6 },
      { label: "Student life", wordCount: 6 },
    ],
    collocationHtml: `${purple("academic advisor")}, ${purple("lecture hall")} và ${purple("tuition waiver")} là cụm thường gặp ở đại học.`,
    mistakeHtml: `Đừng nhầm ${purple("major")} với ${purple("module")}: major là chuyên ngành, module là học phần cụ thể.`,
    principles: [
      {
        title: "Nắm khung chương trình học",
        body: `Kết hợp từ ${purple("credit")}, ${purple("module")} và ${purple("semester")} để hiểu tiến độ học tập.`,
        examples: [ex("This module gives three credits.", "Học phần này có ba tín chỉ.")],
      },
      {
        title: "Diễn đạt bậc học chính xác",
        body: `Dùng ${purple("undergraduate")} và ${purple("postgraduate")} đúng ngữ cảnh.`,
        examples: [ex("She is a postgraduate in law.", "Cô ấy là học viên sau đại học ngành luật.")],
      },
      {
        title: "Nói về hỗ trợ học tập và tài chính",
        body: `Trao đổi với ${purple("academic advisor")} và tìm ${purple("scholarship")} hoặc ${purple("tuition waiver")} khi cần.`,
        examples: [ex("I applied for a scholarship this year.", "Tôi đã nộp hồ sơ xin học bổng năm nay.")],
      },
    ],
    words: U34_WORDS,
    exercises: [
      mcq(
        34,
        1,
        "Sinh viên bậc cử nhân gọi là gì?",
        [
          { key: "a", label: "postgraduate" },
          { key: "b", label: "undergraduate" },
          { key: "c", label: "advisor" },
          { key: "d", label: "lecturer" },
        ],
        "b",
      ),
      fillBlank(
        34,
        2,
        "You should talk to your ____ before changing your major.",
        "academic advisor",
        [
          { key: "a", label: "dormitory" },
          { key: "b", label: "academic advisor" },
          { key: "c", label: "module" },
          { key: "d", label: "seminar" },
        ],
        "b",
      ),
      mcq(
        34,
        3,
        "Từ nào chỉ luận văn tốt nghiệp?",
        [
          { key: "a", label: "thesis" },
          { key: "b", label: "tutorial" },
          { key: "c", label: "credit" },
          { key: "d", label: "campus" },
        ],
        "a",
      ),
    ],
  }),
  preUnit(35, {
    introVi: "Unit 35 bao quát từ vựng nghề nghiệp: loại hình công việc, tuyển dụng, thu nhập và điều kiện làm việc.",
    structureSections: [
      { label: "Types of jobs", wordCount: 6 },
      { label: "Hiring and qualifications", wordCount: 6 },
      { label: "Pay and work terms", wordCount: 6 },
    ],
    collocationHtml: `${purple("job vacancy")}, ${purple("job description")} và ${purple("work shift")} giúp bạn nói về tìm việc chính xác.`,
    mistakeHtml: `Phân biệt ${purple("salary")} (lương tháng) với ${purple("wage")} (tiền công theo giờ/ngày).`,
    principles: [
      {
        title: "Mô tả loại công việc rõ ràng",
        body: `Dùng tính từ ${purple("full-time")}, ${purple("part-time")} hoặc ${purple("self-employed")} để xác định hình thức làm việc.`,
        examples: [ex("I work part-time while studying.", "Tôi làm bán thời gian khi đi học.")],
      },
      {
        title: "Chuẩn bị hồ sơ đúng yêu cầu",
        body: `Đọc kỹ ${purple("job description")} và đối chiếu ${purple("qualification")} trước khi ứng tuyển.`,
        examples: [ex("The role needs two years of experience.", "Vị trí này cần hai năm kinh nghiệm.")],
      },
      {
        title: "Hiểu từ vựng về thu nhập",
        body: `${purple("salary")}, ${purple("wage")} và ${purple("promotion")} thường đi cùng bối cảnh đàm phán nghề nghiệp.`,
        examples: [ex("She got a promotion with better salary.", "Cô ấy được thăng chức với mức lương tốt hơn.")],
      },
    ],
    words: U35_WORDS,
    exercises: [
      mcq(
        35,
        1,
        "Vị trí tuyển dụng còn trống gọi là gì?",
        [
          { key: "a", label: "job vacancy" },
          { key: "b", label: "job shift" },
          { key: "c", label: "profession" },
          { key: "d", label: "trade" },
        ],
        "a",
      ),
      fillBlank(
        35,
        2,
        "Factory workers are often paid an hourly ____.",
        "wage",
        [
          { key: "a", label: "salary" },
          { key: "b", label: "promotion" },
          { key: "c", label: "wage" },
          { key: "d", label: "internship" },
        ],
        "c",
      ),
      mcq(
        35,
        3,
        "Động từ nào nghĩa là xin nghỉ việc?",
        [
          { key: "a", label: "recruit" },
          { key: "b", label: "resign" },
          { key: "c", label: "promote" },
          { key: "d", label: "apply" },
        ],
        "b",
      ),
    ],
  }),
  preUnit(36, {
    introVi: "Unit 36 giúp bạn mô tả công việc hằng ngày: nhiệm vụ, cộng tác nhóm và cách quản lý áp lực.",
    structureSections: [
      { label: "Work responsibilities", wordCount: 6 },
      { label: "Team communication", wordCount: 6 },
      { label: "Work conditions", wordCount: 6 },
    ],
    collocationHtml: `${purple("workload")}, ${purple("performance review")} và ${purple("work-life balance")} là bộ cụm phổ biến trong môi trường công sở.`,
    mistakeHtml: `Đừng dùng ${purple("manager")} cho mọi trường hợp; phân biệt ${purple("supervisor")} và ${purple("team lead")} theo vai trò cụ thể.`,
    principles: [
      {
        title: "Trình bày vai trò công việc mạch lạc",
        body: `Nêu ${purple("responsibility")} chính, sau đó thêm cách bạn ${purple("prioritise")} và ${purple("coordinate")} với nhóm.`,
        examples: [ex("My responsibility is handling customer issues.", "Trách nhiệm của tôi là xử lý vấn đề khách hàng.")],
      },
      {
        title: "Nói về hình thức làm việc hiện đại",
        body: `Các cụm ${purple("remote work")} và ${purple("hybrid schedule")} rất cần khi mô tả công việc hiện nay.`,
        examples: [ex("We follow a hybrid schedule, three days onsite.", "Chúng tôi làm theo lịch kết hợp, ba ngày tại văn phòng.")],
      },
      {
        title: "Giữ cân bằng để duy trì hiệu suất",
        body: `Kiểm soát ${purple("deadline pressure")} và bảo vệ ${purple("work-life balance")} để tránh kiệt sức.`,
        examples: [ex("Too much overtime harms work-life balance.", "Làm thêm quá nhiều gây hại cân bằng cuộc sống-công việc.")],
      },
    ],
    words: U36_WORDS,
    exercises: [
      mcq(
        36,
        1,
        "Khối lượng công việc phải xử lý gọi là gì?",
        [
          { key: "a", label: "workload" },
          { key: "b", label: "task list" },
          { key: "c", label: "overtime" },
          { key: "d", label: "commute" },
        ],
        "a",
      ),
      fillBlank(
        36,
        2,
        "I ____ to the operations manager.",
        "report to",
        [
          { key: "a", label: "multitask" },
          { key: "b", label: "report to" },
          { key: "c", label: "prioritise" },
          { key: "d", label: "coordinate" },
        ],
        "b",
      ),
      mcq(
        36,
        3,
        "Cụm nào chỉ cân bằng giữa việc và đời sống cá nhân?",
        [
          { key: "a", label: "deadline pressure" },
          { key: "b", label: "work-life balance" },
          { key: "c", label: "remote work" },
          { key: "d", label: "performance review" },
        ],
        "b",
      ),
    ],
  }),
  preUnit(37, {
    introVi: "Unit 37 tập trung vào phát triển sự nghiệp dài hạn: kỹ năng, cố vấn, định hướng và thăng tiến.",
    structureSections: [
      { label: "Career planning", wordCount: 6 },
      { label: "Growth tools", wordCount: 6 },
      { label: "Professional positioning", wordCount: 6 },
    ],
    collocationHtml: `${purple("career path")}, ${purple("professional development")} và ${purple("long-term vision")} giúp bạn nói về sự nghiệp có chiến lược.`,
    mistakeHtml: `Không đánh đồng ${purple("upskill")} và ${purple("reskill")}: upskill là nâng kỹ năng cũ, reskill là học để đổi hướng.`,
    principles: [
      {
        title: "Xác định hướng đi cụ thể",
        body: `Đặt ${purple("career goal")} rõ ràng và xây ${purple("career path")} theo từng giai đoạn.`,
        examples: [ex("My career goal is to become a product manager.", "Mục tiêu nghề nghiệp của tôi là trở thành quản lý sản phẩm.")],
      },
      {
        title: "Đầu tư vào năng lực dài hạn",
        body: `Kết hợp ${purple("certification")}, ${purple("mentorship")} và ${purple("side project")} để tăng lợi thế.`,
        examples: [ex("A side project helped me build a stronger portfolio.", "Dự án phụ giúp tôi xây hồ sơ năng lực tốt hơn.")],
      },
      {
        title: "Tạo khác biệt trên thị trường lao động",
        body: `Muốn ${purple("stand out")}, bạn cần chứng minh ${purple("leadership")} và kết quả thực tế.`,
        examples: [ex("He stands out because of strong leadership skills.", "Anh ấy nổi bật nhờ kỹ năng lãnh đạo tốt.")],
      },
    ],
    words: U37_WORDS,
    exercises: [
      mcq(
        37,
        1,
        "Từ nào chỉ lộ trình phát triển nghề nghiệp?",
        [
          { key: "a", label: "skill set" },
          { key: "b", label: "career path" },
          { key: "c", label: "networking" },
          { key: "d", label: "portfolio" },
        ],
        "b",
      ),
      fillBlank(
        37,
        2,
        "Many professionals ____ by taking online courses.",
        "upskill",
        [
          { key: "a", label: "upskill" },
          { key: "b", label: "defer" },
          { key: "c", label: "drop out" },
          { key: "d", label: "graduate" },
        ],
        "a",
      ),
      mcq(
        37,
        3,
        "Từ nào chỉ người cố vấn nghề nghiệp?",
        [
          { key: "a", label: "captain" },
          { key: "b", label: "mentor" },
          { key: "c", label: "candidate" },
          { key: "d", label: "invigilator" },
        ],
        "b",
      ),
    ],
  }),
  preUnit(38, {
    introVi: "Unit 38 nói về công việc văn phòng thực tế: họp hành, email, lưu trữ tài liệu và quy tắc nơi làm việc.",
    structureSections: [
      { label: "Office tools", wordCount: 6 },
      { label: "Meetings and email", wordCount: 6 },
      { label: "Office workflow", wordCount: 6 },
    ],
    collocationHtml: `${purple("meeting room")}, ${purple("follow-up email")} và ${purple("office etiquette")} là cụm cần dùng thường xuyên ở văn phòng.`,
    mistakeHtml: `Nhớ phân biệt ${purple("agenda")} (nội dung dự kiến) và ${purple("minutes")} (biên bản sau cuộc họp).`,
    principles: [
      {
        title: "Quản lý cuộc họp hiệu quả",
        body: `Trước cuộc họp cần ${purple("book a room")} và gửi ${purple("agenda")} rõ ràng.`,
        examples: [ex("Please share the agenda one day earlier.", "Hãy gửi chương trình họp trước một ngày.")],
      },
      {
        title: "Duy trì giao tiếp qua email chuẩn",
        body: `Sau họp nên gửi ${purple("follow-up email")} và đính kèm ${purple("attachment")} nếu cần.`,
        examples: [ex("I sent a follow-up email with action points.", "Tôi đã gửi email theo dõi kèm các việc cần làm.")],
      },
      {
        title: "Giữ kỷ luật tài liệu văn phòng",
        body: `Biết cách ${purple("file a document")} giúp truy xuất hồ sơ nhanh và giảm sai sót.`,
        examples: [ex("File documents by date and project.", "Hãy lưu tài liệu theo ngày và dự án.")],
      },
    ],
    words: U38_WORDS,
    exercises: [
      mcq(
        38,
        1,
        "Từ nào chỉ phòng họp trong văn phòng?",
        [
          { key: "a", label: "workstation" },
          { key: "b", label: "meeting room" },
          { key: "c", label: "inbox" },
          { key: "d", label: "outbox" },
        ],
        "b",
      ),
      fillBlank(
        38,
        2,
        "Do not forget to include the file as an ____.",
        "attachment",
        [
          { key: "a", label: "agenda" },
          { key: "b", label: "attachment" },
          { key: "c", label: "stationery" },
          { key: "d", label: "photocopier" },
        ],
        "b",
      ),
      mcq(
        38,
        3,
        "Cụm nào nghĩa là lên lịch một cuộc họp?",
        [
          { key: "a", label: "book a room" },
          { key: "b", label: "file a document" },
          { key: "c", label: "schedule a meeting" },
          { key: "d", label: "take minutes" },
        ],
        "c",
      ),
    ],
  }),
  preUnit(39, {
    introVi: "Unit 39 cung cấp từ vựng điều hành doanh nghiệp: cấu trúc công ty, vận hành và quyết định chiến lược.",
    structureSections: [
      { label: "Company structure", wordCount: 6 },
      { label: "Operations and finance", wordCount: 6 },
      { label: "Management actions", wordCount: 6 },
    ],
    collocationHtml: `${purple("business model")}, ${purple("cash flow")} và ${purple("board of directors")} là cụm nền tảng của chủ đề doanh nghiệp.`,
    mistakeHtml: `Không nhầm ${purple("revenue")} với ${purple("profit")}: revenue là tổng thu, profit là phần còn lại sau chi phí.`,
    principles: [
      {
        title: "Hiểu cấu trúc quyền lực trong công ty",
        body: `Phân biệt vai trò của ${purple("founder")}, ${purple("shareholder")} và ${purple("board of directors")}.`,
        examples: [ex("Shareholders approved the annual plan.", "Các cổ đông đã phê duyệt kế hoạch năm.")],
      },
      {
        title: "Nắm các chỉ số vận hành cốt lõi",
        body: `${purple("cash flow")} và ${purple("overhead cost")} quyết định độ bền tài chính của doanh nghiệp.`,
        examples: [ex("We monitor cash flow every week.", "Chúng tôi theo dõi dòng tiền mỗi tuần.")],
      },
      {
        title: "Dùng đúng động từ quản trị",
        body: `Khi điều hành, cần biết ${purple("delegate")}, ${purple("outsource")} và ${purple("expand")} theo mục tiêu.`,
        examples: [ex("Good leaders delegate important tasks clearly.", "Lãnh đạo tốt biết giao việc quan trọng rõ ràng.")],
      },
    ],
    words: U39_WORDS,
    exercises: [
      mcq(
        39,
        1,
        "Từ nào chỉ mô hình tạo giá trị và kiếm lợi nhuận của công ty?",
        [
          { key: "a", label: "business model" },
          { key: "b", label: "startup" },
          { key: "c", label: "department" },
          { key: "d", label: "stakeholder" },
        ],
        "a",
      ),
      fillBlank(
        39,
        2,
        "Managers should ____ tasks instead of doing everything themselves.",
        "delegate",
        [
          { key: "a", label: "set up" },
          { key: "b", label: "expand" },
          { key: "c", label: "delegate" },
          { key: "d", label: "merge" },
        ],
        "c",
      ),
      mcq(
        39,
        3,
        "Cụm nào chỉ hội đồng quản trị công ty?",
        [
          { key: "a", label: "human resources" },
          { key: "b", label: "board of directors" },
          { key: "c", label: "operations team" },
          { key: "d", label: "revenue stream" },
        ],
        "b",
      ),
    ],
  }),
  preUnit(40, {
    introVi: "Unit 40 đi sâu vào từ vựng kinh doanh và tài chính: doanh thu, chi phí, đầu tư, nợ và báo cáo.",
    structureSections: [
      { label: "Business results", wordCount: 6 },
      { label: "Money management", wordCount: 6 },
      { label: "Accounting terms", wordCount: 6 },
    ],
    collocationHtml: `${purple("profit margin")}, ${purple("interest rate")} và ${purple("financial statement")} là cụm then chốt của ngôn ngữ tài chính.`,
    mistakeHtml: `Phân biệt ${purple("asset")} (tài sản) và ${purple("liability")} (nghĩa vụ nợ) để tránh diễn đạt sai trong báo cáo.`,
    principles: [
      {
        title: "Đọc kết quả kinh doanh đúng bản chất",
        body: `${purple("turnover")}, ${purple("net profit")} và ${purple("loss")} phản ánh các góc nhìn khác nhau về hiệu quả.`,
        examples: [ex("Turnover rose, but net profit stayed flat.", "Doanh thu tăng nhưng lợi nhuận ròng vẫn đi ngang.")],
      },
      {
        title: "Hiểu luồng tiền và nghĩa vụ tài chính",
        body: `Theo dõi ${purple("cash flow")}, ${purple("debt")} và ${purple("loan")} giúp kiểm soát rủi ro.`,
        examples: [ex("They paid off the loan early.", "Họ đã trả hết khoản vay sớm.")],
      },
      {
        title: "Dùng thuật ngữ báo cáo chính xác",
        body: `Trong kế toán cơ bản, cần nắm ${purple("invoice")}, ${purple("receipt")} và ${purple("financial statement")}.`,
        examples: [ex("Please keep every receipt for accounting.", "Hãy giữ mọi biên nhận cho kế toán.")],
      },
    ],
    words: U40_WORDS,
    exercises: [
      mcq(
        40,
        1,
        "Từ nào nghĩa là biên lợi nhuận?",
        [
          { key: "a", label: "net profit" },
          { key: "b", label: "profit margin" },
          { key: "c", label: "invoice" },
          { key: "d", label: "debt" },
        ],
        "b",
      ),
      fillBlank(
        40,
        2,
        "The company hopes to ____ next quarter.",
        "break even",
        [
          { key: "a", label: "break even" },
          { key: "b", label: "allocate" },
          { key: "c", label: "pay off" },
          { key: "d", label: "forecast" },
        ],
        "a",
      ),
      mcq(
        40,
        3,
        "Tài sản có giá trị kinh tế được gọi là gì?",
        [
          { key: "a", label: "liability" },
          { key: "b", label: "asset" },
          { key: "c", label: "budget" },
          { key: "d", label: "interest rate" },
        ],
        "b",
      ),
    ],
  }),
  preUnit(41, {
    introVi: "Unit 41 mở rộng từ vựng về thể thao và giải trí thường ngày: vận động, thư giãn và duy trì lối sống lành mạnh.",
    structureSections: [
      { label: "Active hobbies", wordCount: 6 },
      { label: "Relaxing pastimes", wordCount: 6 },
      { label: "Lifestyle language", wordCount: 6 },
    ],
    collocationHtml: `${purple("leisure activity")}, ${purple("stay active")} và ${purple("wind down")} giúp nói về thói quen sống cân bằng.`,
    mistakeHtml: `Đừng dùng một từ ${purple("sport")} cho mọi thứ; nhiều trường hợp tự nhiên hơn với ${purple("leisure activity")} hoặc ${purple("pastime")}.`,
    principles: [
      {
        title: "Phân loại hoạt động theo mục tiêu",
        body: `Các môn như ${purple("cycling")}, ${purple("swimming")} thiên về sức khỏe, còn ${purple("board game")} thiên về giải trí xã hội.`,
        examples: [ex("Swimming helps me stay active.", "Bơi giúp tôi duy trì vận động.")],
      },
      {
        title: "Dùng cụm động từ diễn tả thói quen",
        body: `Bạn có thể ${purple("take up")} môn mới hoặc ${purple("wind down")} bằng âm nhạc vào buổi tối.`,
        examples: [ex("I took up hiking last year.", "Tôi bắt đầu đi bộ đường dài từ năm ngoái.")],
      },
      {
        title: "Nhấn lợi ích phục hồi năng lượng",
        body: `Các hoạt động giải trí đúng cách giúp ${purple("recharge")} tinh thần sau tuần bận rộn.`,
        examples: [ex("Weekend walks help me recharge.", "Đi bộ cuối tuần giúp tôi nạp lại năng lượng.")],
      },
    ],
    words: U41_WORDS,
    exercises: [
      mcq(
        41,
        1,
        "Cụm nào nghĩa là hoạt động giải trí lúc rảnh?",
        [
          { key: "a", label: "workout plan" },
          { key: "b", label: "leisure activity" },
          { key: "c", label: "tournament" },
          { key: "d", label: "fitness test" },
        ],
        "b",
      ),
      fillBlank(
        41,
        2,
        "I want to ____ yoga this summer.",
        "take up",
        [
          { key: "a", label: "recharge" },
          { key: "b", label: "take up" },
          { key: "c", label: "wind down" },
          { key: "d", label: "stay active" },
        ],
        "b",
      ),
      mcq(
        41,
        3,
        "Từ nào chỉ thú tiêu khiển thường xuyên?",
        [
          { key: "a", label: "pastime" },
          { key: "b", label: "stamina" },
          { key: "c", label: "fixture" },
          { key: "d", label: "captain" },
        ],
        "a",
      ),
    ],
  }),
  preUnit(42, {
    introVi: "Unit 42 đi vào ngôn ngữ thể thao thi đấu: giải đấu, vai trò đội bóng và kết quả trận đấu.",
    structureSections: [
      { label: "Competition structure", wordCount: 6 },
      { label: "People and roles", wordCount: 6 },
      { label: "Match outcomes", wordCount: 6 },
    ],
    collocationHtml: `${purple("semi-final")}, ${purple("set a record")} và ${purple("injury time")} là cụm thường thấy trong tin thể thao.`,
    mistakeHtml: `Phân biệt ${purple("draw")} (hòa) với ${purple("defeat")} (thua), tránh dùng chung một từ cho mọi kết quả.`,
    principles: [
      {
        title: "Hiểu cấu trúc một giải đấu",
        body: `Từ ${purple("qualifier")} đến ${purple("semi-final")} rồi ${purple("final")} tạo thành chuỗi thi đấu chuẩn.`,
        examples: [ex("They reached the final after winning the semi-final.", "Họ vào chung kết sau khi thắng bán kết.")],
      },
      {
        title: "Nắm vai trò trên sân",
        body: `${purple("coach")}, ${purple("captain")} và ${purple("referee")} là ba vai trò nền tảng trong thi đấu.`,
        examples: [ex("The referee stopped play for an injury.", "Trọng tài dừng trận vì chấn thương.")],
      },
      {
        title: "Mô tả diễn biến trận đấu tự nhiên",
        body: `Các động từ như ${purple("equalise")} hoặc ${purple("knock out")} giúp tường thuật chính xác hơn.`,
        examples: [ex("They equalised in the final minute.", "Họ gỡ hòa ở phút cuối cùng.")],
      },
    ],
    words: U42_WORDS,
    exercises: [
      mcq(
        42,
        1,
        "Trận đấu quyết định cuối cùng gọi là gì?",
        [
          { key: "a", label: "fixture" },
          { key: "b", label: "qualifier" },
          { key: "c", label: "final" },
          { key: "d", label: "draw" },
        ],
        "c",
      ),
      fillBlank(
        42,
        2,
        "The team managed to ____ in the second half.",
        "equalise",
        [
          { key: "a", label: "defeat" },
          { key: "b", label: "equalise" },
          { key: "c", label: "captain" },
          { key: "d", label: "tournament" },
        ],
        "b",
      ),
      mcq(
        42,
        3,
        "Từ nào chỉ sức bền khi thi đấu?",
        [
          { key: "a", label: "stamina" },
          { key: "b", label: "penalty" },
          { key: "c", label: "substitute" },
          { key: "d", label: "referee" },
        ],
        "a",
      ),
    ],
  }),
  preUnit(43, {
    introVi: "Unit 43 phát triển từ vựng về sách và phim: thể loại, yếu tố nội dung và cách nhận xét tác phẩm.",
    structureSections: [
      { label: "Book and film types", wordCount: 6 },
      { label: "Story elements", wordCount: 6 },
      { label: "Audience response", wordCount: 6 },
    ],
    collocationHtml: `${purple("character arc")}, ${purple("film adaptation")} và ${purple("thought-provoking")} giúp bài review sâu hơn.`,
    mistakeHtml: `Tránh lẫn ${purple("plot")} (diễn biến câu chuyện) với ${purple("setting")} (bối cảnh thời gian-không gian).`,
    principles: [
      {
        title: "Nói rõ yếu tố của tác phẩm",
        body: `Khi nhận xét, tách riêng ${purple("plot")}, ${purple("character arc")} và ${purple("setting")}.`,
        examples: [ex("The plot is simple but the character arc is strong.", "Cốt truyện đơn giản nhưng tuyến phát triển nhân vật rất tốt.")],
      },
      {
        title: "Mô tả loại hình và định dạng",
        body: `Phân biệt ${purple("novel")}, ${purple("memoir")}, ${purple("biography")} hoặc phim ${purple("sequel")}.`,
        examples: [ex("This film is a sequel to a popular thriller.", "Bộ phim này là phần tiếp theo của một phim giật gân nổi tiếng.")],
      },
      {
        title: "Đánh giá trải nghiệm người xem/người đọc",
        body: `Dùng tính từ như ${purple("captivating")} hoặc ${purple("thought-provoking")} thay cho nhận xét chung chung.`,
        examples: [ex("It is captivating and emotionally rich.", "Tác phẩm rất cuốn hút và giàu cảm xúc.")],
      },
    ],
    words: U43_WORDS,
    exercises: [
      mcq(
        43,
        1,
        "Phiên bản chuyển thể từ sách sang phim gọi là gì?",
        [
          { key: "a", label: "subtitle" },
          { key: "b", label: "adaptation" },
          { key: "c", label: "sequel" },
          { key: "d", label: "review" },
        ],
        "b",
      ),
      fillBlank(
        43,
        2,
        "Please do not share any ____ online.",
        "spoiler",
        [
          { key: "a", label: "spoiler" },
          { key: "b", label: "setting" },
          { key: "c", label: "soundtrack" },
          { key: "d", label: "genre" },
        ],
        "a",
      ),
      mcq(
        43,
        3,
        "Từ nào chỉ sách đọc cuốn hút, khó dừng lại?",
        [
          { key: "a", label: "memoir" },
          { key: "b", label: "page-turner" },
          { key: "c", label: "biography" },
          { key: "d", label: "review" },
        ],
        "b",
      ),
    ],
  }),
  preUnit(44, {
    introVi: "Unit 44 cung cấp từ vựng âm nhạc từ cấu trúc bài hát đến biểu diễn trực tiếp và sáng tác.",
    structureSections: [
      { label: "Song components", wordCount: 6 },
      { label: "Performance context", wordCount: 6 },
      { label: "Music creation", wordCount: 6 },
    ],
    collocationHtml: `${purple("write lyrics")}, ${purple("perform live")} và ${purple("debut album")} là cụm phổ biến trong chủ đề âm nhạc.`,
    mistakeHtml: `Đừng nhầm ${purple("rhythm")} với ${purple("melody")}: rhythm là nhịp, melody là tuyến giai điệu.`,
    principles: [
      {
        title: "Nhận diện cấu trúc bài hát",
        body: `Các thành phần ${purple("verse")}, ${purple("chorus")} và ${purple("lyrics")} giúp bạn mô tả một ca khúc rõ ràng.`,
        examples: [ex("The chorus is easier to remember than the verse.", "Điệp khúc dễ nhớ hơn đoạn lời chính.")],
      },
      {
        title: "Nói về biểu diễn tự nhiên",
        body: `Dùng ${purple("gig")}, ${purple("concert hall")} và ${purple("encore")} để kể trải nghiệm đi nghe nhạc.`,
        examples: [ex("The band played an encore after the main set.", "Ban nhạc diễn thêm sau phần chính.")],
      },
      {
        title: "Mô tả quá trình sáng tác",
        body: `Nhạc sĩ có thể ${purple("compose")} trước, sau đó ${purple("improvise")} phần biểu diễn.`,
        examples: [ex("He composed the melody on piano.", "Anh ấy sáng tác giai điệu bằng đàn piano.")],
      },
    ],
    words: U44_WORDS,
    exercises: [
      mcq(
        44,
        1,
        "Phần lặp lại nổi bật trong bài hát gọi là gì?",
        [
          { key: "a", label: "verse" },
          { key: "b", label: "chorus" },
          { key: "c", label: "tempo" },
          { key: "d", label: "harmony" },
        ],
        "b",
      ),
      fillBlank(
        44,
        2,
        "The singer will ____ at the city theater tonight.",
        "perform live",
        [
          { key: "a", label: "compose" },
          { key: "b", label: "perform live" },
          { key: "c", label: "tune" },
          { key: "d", label: "improvise" },
        ],
        "b",
      ),
      mcq(
        44,
        3,
        "Từ nào chỉ danh sách các bài hát phát liên tục?",
        [
          { key: "a", label: "single" },
          { key: "b", label: "playlist" },
          { key: "c", label: "album" },
          { key: "d", label: "gig" },
        ],
        "b",
      ),
    ],
  }),
  preUnit(45, {
    introVi: "Unit 45 kết thúc cụm này với từ vựng về sự kiện đặc biệt: lễ kỷ niệm, tiệc, lễ hội và tổ chức khách mời.",
    structureSections: [
      { label: "Event types", wordCount: 6 },
      { label: "Planning and logistics", wordCount: 6 },
      { label: "Experience and meaning", wordCount: 6 },
    ],
    collocationHtml: `${purple("guest list")}, ${purple("dress code")} và ${purple("once-in-a-lifetime event")} là cụm hay dùng khi mô tả sự kiện.`,
    mistakeHtml: `Phân biệt ${purple("ceremony")} (nghi lễ trang trọng) với ${purple("celebration")} (không khí ăn mừng rộng hơn).`,
    principles: [
      {
        title: "Mô tả loại sự kiện chính xác",
        body: `Dùng ${purple("festival")}, ${purple("anniversary")}, ${purple("ceremony")} theo đúng ngữ cảnh văn hóa.`,
        examples: [ex("The festival celebrates local culture.", "Lễ hội tôn vinh văn hóa địa phương.")],
      },
      {
        title: "Nắm từ vựng tổ chức sự kiện",
        body: `Các mục như ${purple("venue")}, ${purple("invitation")} và ${purple("guest list")} quyết định phần hậu cần.`,
        examples: [ex("Please confirm the venue and guest list.", "Vui lòng xác nhận địa điểm và danh sách khách mời.")],
      },
      {
        title: "Thêm sắc thái cảm xúc cho mô tả",
        body: `Dùng ${purple("memorable")} hoặc ${purple("once-in-a-lifetime")} để diễn tả tầm quan trọng của trải nghiệm.`,
        examples: [ex("It was a memorable celebration for the whole family.", "Đó là buổi kỷ niệm đáng nhớ cho cả gia đình.")],
      },
    ],
    words: U45_WORDS,
    exercises: [
      mcq(
        45,
        1,
        "Danh sách khách mời tham dự gọi là gì?",
        [
          { key: "a", label: "guest list" },
          { key: "b", label: "dress code" },
          { key: "c", label: "venue" },
          { key: "d", label: "banquet" },
        ],
        "a",
      ),
      fillBlank(
        45,
        2,
        "Bad weather may ____ the outdoor ceremony.",
        "postpone",
        [
          { key: "a", label: "attend" },
          { key: "b", label: "commemorate" },
          { key: "c", label: "postpone" },
          { key: "d", label: "host" },
        ],
        "c",
      ),
      mcq(
        45,
        3,
        "Từ nào mô tả trải nghiệm rất đáng nhớ?",
        [
          { key: "a", label: "formal" },
          { key: "b", label: "memorable" },
          { key: "c", label: "ordinary" },
          { key: "d", label: "annual" },
        ],
        "b",
      ),
    ],
  }),
];
