import type { VocabularyUnit } from "../vocabulary-unit-types";
import { ex, fillBlank, mcq, purple } from "./eviu-unit-builder";
import { preUnit, wordList } from "./eviu-pre-unit-helpers";

const U46_WORDS = wordList([
  ["itinerary", "lịch trình di chuyển chi tiết theo ngày", "Our itinerary includes Hanoi, Hue, and Hoi An."],
  ["reserve", "đặt chỗ trước để giữ suất", "I need to reserve two train tickets.", "VERB"],
  ["booking reference", "mã đặt chỗ dùng để tra cứu", "Please keep your booking reference safe."],
  ["cancellation policy", "quy định hủy đặt chỗ và hoàn tiền", "Read the cancellation policy before paying."],
  ["refundable fare", "loại vé có thể hoàn lại tiền", "A refundable fare is safer but more expensive."],
  ["non-refundable", "không được hoàn tiền khi hủy", "This ticket is non-refundable.", "ADJECTIVE"],
  ["travel agency", "công ty dịch vụ tư vấn và đặt chuyến đi", "The travel agency planned our honeymoon."],
  ["package tour", "gói du lịch gồm nhiều dịch vụ trọn bộ", "We chose a package tour for convenience."],
  ["seat selection", "việc chọn chỗ ngồi trước chuyến đi", "Seat selection opens 24 hours before departure."],
  ["travel insurance", "bảo hiểm cho rủi ro khi đi du lịch", "Travel insurance covers lost baggage."],
  ["check-in window", "khoảng thời gian được làm thủ tục", "The check-in window closes one hour early."],
  ["baggage allowance", "mức hành lý được phép mang theo", "My baggage allowance is 20 kilograms."],
  ["direct flight", "chuyến bay đi thẳng không đổi máy bay", "A direct flight saves a lot of time."],
  ["stopover", "điểm dừng trung chuyển giữa hành trình", "We had a six-hour stopover in Doha."],
  ["departure date", "ngày khởi hành", "Please confirm your departure date."],
  ["return date", "ngày quay về", "The return date is still flexible."],
  ["confirmation email", "email xác nhận sau khi đặt thành công", "I got a confirmation email right away."],
  ["booking platform", "nền tảng trực tuyến để đặt dịch vụ", "This booking platform compares many airlines."],
]);

const U47_WORDS = wordList([
  ["boarding pass", "thẻ lên máy bay", "Show your boarding pass at the gate."],
  ["gate number", "số cổng ra máy bay", "Check the gate number on the screen."],
  ["security check", "khu vực kiểm tra an ninh", "Liquids are checked at the security check."],
  ["departure lounge", "khu vực chờ trước khi lên máy bay", "We waited in the departure lounge."],
  ["overhead locker", "ngăn để hành lý phía trên ghế", "Put your bag in the overhead locker."],
  ["runway", "đường băng máy bay cất và hạ cánh", "The plane moved slowly onto the runway."],
  ["takeoff", "quá trình cất cánh", "I always feel nervous during takeoff."],
  ["landing", "quá trình hạ cánh", "The landing was smooth despite the rain."],
  ["turbulence", "hiện tượng rung lắc khi bay", "The pilot warned us about turbulence."],
  ["cabin crew", "đội tiếp viên phục vụ trên chuyến bay", "The cabin crew were very helpful."],
  ["aisle seat", "ghế cạnh lối đi", "I prefer an aisle seat on long flights."],
  ["window seat", "ghế cạnh cửa sổ", "My daughter asked for a window seat."],
  ["delayed flight", "chuyến bay bị hoãn", "A delayed flight made us miss dinner."],
  ["missed connection", "lỡ chuyến nối tiếp", "A storm caused our missed connection."],
  ["customs officer", "nhân viên hải quan", "A customs officer checked my suitcase."],
  ["immigration queue", "hàng chờ làm thủ tục nhập cảnh", "The immigration queue was very long."],
  ["carry-on luggage", "hành lý xách tay mang lên cabin", "Only one carry-on luggage item is allowed."],
  ["jet lag", "mệt mỏi do lệch múi giờ sau khi bay xa", "I had terrible jet lag after the trip."],
]);

const U48_WORDS = wordList([
  ["reception desk", "quầy lễ tân tại khách sạn", "Please leave your key at the reception desk."],
  ["vacancy", "tình trạng còn phòng trống", "Sorry, we have no vacancy tonight."],
  ["fully booked", "đã kín chỗ, không nhận thêm khách", "The hotel is fully booked this weekend.", "ADJECTIVE"],
  ["single room", "phòng dành cho một người", "I booked a single room for two nights."],
  ["double room", "phòng có giường đôi hoặc cho hai người", "A double room costs a bit more."],
  ["room service", "dịch vụ mang đồ ăn/uống lên phòng", "We ordered sandwiches from room service."],
  ["housekeeping", "bộ phận dọn phòng và vệ sinh", "Housekeeping cleaned the room at noon."],
  ["wake-up call", "cuộc gọi báo thức từ khách sạn", "Can I request a wake-up call at 5 a.m.?"], 
  ["buffet breakfast", "bữa sáng tự chọn tại khách sạn", "Buffet breakfast starts at six."],
  ["reservation", "việc đặt bàn hoặc đặt phòng trước", "Do you have a reservation for dinner?"],
  ["set menu", "thực đơn chọn sẵn theo suất", "The set menu includes dessert."],
  ["main course", "món chính trong bữa ăn", "I ordered fish as my main course."],
  ["side dish", "món ăn kèm", "Would you like a side dish of salad?"],
  ["bill", "hóa đơn thanh toán", "Could we have the bill, please?"],
  ["tip", "tiền boa cho nhân viên phục vụ", "He left a small tip for the waiter."],
  ["allergy-friendly", "phù hợp cho người có dị ứng thực phẩm", "This restaurant has allergy-friendly options.", "ADJECTIVE"],
  ["check-out time", "giờ trả phòng theo quy định", "Check-out time is at 11 a.m."],
  ["complimentary", "được tặng miễn phí kèm dịch vụ", "Guests receive complimentary bottled water.", "ADJECTIVE"],
]);

const U49_WORDS = wordList([
  ["espresso", "cà phê đậm đặc pha bằng áp suất cao", "He drinks a single espresso every morning."],
  ["latte", "cà phê pha sữa nóng và lớp bọt mỏng", "I usually order an iced latte."],
  ["cappuccino", "cà phê sữa với lớp bọt dày", "She likes cappuccino with cinnamon."],
  ["americano", "cà phê espresso pha thêm nước nóng", "An americano is less milky than a latte."],
  ["barista", "người pha chế đồ uống tại quán cà phê", "The barista recommended a new blend."],
  ["takeaway cup", "ly mang đi", "Can I have this in a takeaway cup?"],
  ["dine in", "ngồi lại quán để dùng tại chỗ", "We decided to dine in today.", "VERB"],
  ["pastry counter", "quầy bánh ngọt trong quán", "The pastry counter looks amazing."],
  ["loyalty card", "thẻ tích điểm khách hàng thân thiết", "My loyalty card gives me free drinks."],
  ["coffee beans", "hạt cà phê rang để xay pha", "These coffee beans are from Ethiopia."],
  ["grind size", "độ mịn của bột cà phê sau khi xay", "Grind size affects flavor a lot."],
  ["decaf", "cà phê đã giảm hoặc bỏ caffeine", "I drink decaf in the evening."],
  ["soy milk", "sữa đậu nành thay sữa bò", "Can I switch to soy milk?"],
  ["oat milk", "sữa yến mạch có vị béo nhẹ", "Oat milk is popular with vegan customers."],
  ["refill", "việc rót thêm đồ uống", "This place offers free refill for tea."],
  ["opening hours", "khung giờ mở cửa hoạt động", "Please check the opening hours online."],
  ["cozy corner", "góc ngồi ấm cúng, dễ chịu", "We found a cozy corner near the window."],
  ["free wi-fi", "dịch vụ wifi miễn phí cho khách", "Many students come here for free wi-fi."],
]);

const U50_WORDS = wordList([
  ["landmark", "địa danh nổi bật mang tính biểu tượng", "The opera house is the city's landmark."],
  ["guided tour", "chuyến tham quan có hướng dẫn viên", "We joined a guided tour in the old town."],
  ["city map", "bản đồ thành phố để định hướng", "Take a city map from the hotel lobby."],
  ["audio guide", "thiết bị thuyết minh tự động", "The museum offers an audio guide in English."],
  ["museum pass", "vé gộp vào nhiều bảo tàng", "A museum pass saves money for visitors."],
  ["souvenir shop", "cửa hàng quà lưu niệm", "We bought postcards at a souvenir shop."],
  ["admission fee", "phí vào cửa điểm tham quan", "The admission fee is cheaper for students."],
  ["viewpoint", "điểm cao để ngắm cảnh toàn khu", "Sunset is beautiful from this viewpoint."],
  ["old quarter", "khu phố cổ có giá trị lịch sử", "We walked around the old quarter all morning."],
  ["local guide", "hướng dẫn viên bản địa am hiểu vùng", "A local guide shared great stories."],
  ["heritage site", "địa điểm di sản văn hóa hoặc thiên nhiên", "This heritage site attracts many tourists."],
  ["walking tour", "chuyến khám phá đi bộ theo tuyến", "Our walking tour lasted two hours."],
  ["photo spot", "điểm chụp hình đẹp phổ biến", "That bridge is a famous photo spot."],
  ["day trip", "chuyến đi về trong ngày", "We took a day trip to the nearby island."],
  ["queue up", "xếp hàng chờ lượt", "Tourists queue up before the gate opens.", "VERB"],
  ["opening times", "khung giờ mở cửa tham quan", "Always check opening times on holidays."],
  ["tourist trap", "điểm du lịch bị thổi giá hoặc kém chất lượng", "That market felt like a tourist trap."],
  ["hidden gem", "địa điểm ít người biết nhưng rất đáng đi", "The small temple is a hidden gem."],
]);

const U51_WORDS = wordList([
  ["seaside resort", "khu nghỉ dưỡng ven biển", "They stayed at a quiet seaside resort."],
  ["coastline", "dải bờ biển của một vùng", "The coastline here is very rocky."],
  ["sandy beach", "bãi biển có cát mịn", "Children played on the sandy beach."],
  ["sunbathing", "việc nằm tắm nắng trên bãi biển", "She enjoys sunbathing in the morning."],
  ["beach towel", "khăn lớn dùng tại bãi biển", "Don't forget your beach towel."],
  ["sunscreen", "kem chống nắng bảo vệ da", "Apply sunscreen every two hours."],
  ["lifeguard", "nhân viên cứu hộ ở khu bơi", "The lifeguard blew the whistle."],
  ["tide", "mực nước thủy triều lên xuống", "The tide is high this afternoon."],
  ["waves", "những đợt sóng biển", "The waves were too strong for kids."],
  ["snorkeling", "lặn nông ngắm san hô bằng ống thở", "We tried snorkeling near the reef."],
  ["seashell", "vỏ sò nhặt trên bờ biển", "My son collected colorful seashells."],
  ["pier", "cầu tàu nhô ra mặt nước", "We watched fishermen from the pier."],
  ["seafood stall", "quầy bán đồ hải sản", "Let's eat at that seafood stall."],
  ["beach volleyball", "môn bóng chuyền chơi trên cát", "They played beach volleyball at sunset."],
  ["rent an umbrella", "thuê ô che nắng ở bãi biển", "We decided to rent an umbrella.", "VERB"],
  ["sea breeze", "gió biển mát thổi từ mặt nước", "A sea breeze made the weather pleasant."],
  ["boat trip", "chuyến đi biển bằng thuyền", "The boat trip took us to three islands."],
  ["sunset cruise", "hành trình ngắm hoàng hôn trên tàu", "A sunset cruise was the trip highlight."],
]);

const U52_WORDS = wordList([
  ["headline", "tiêu đề chính nổi bật của bản tin", "The headline shocked many readers."],
  ["front page", "trang đầu của tờ báo", "Her interview appeared on the front page."],
  ["columnist", "người viết chuyên mục định kỳ", "That columnist writes about education."],
  ["editorial", "bài xã luận thể hiện quan điểm tòa soạn", "The editorial criticized the new policy."],
  ["breaking news", "tin nóng vừa xảy ra", "The channel switched to breaking news."],
  ["anchor", "người dẫn chương trình thời sự", "The anchor remained calm during the update."],
  ["documentary", "phim tài liệu về chủ đề thực tế", "We watched a documentary on marine life."],
  ["weather report", "bản tin dự báo thời tiết", "I check the weather report every morning."],
  ["broadcast live", "phát sóng trực tiếp theo thời gian thực", "The debate will broadcast live tonight.", "VERB"],
  ["channel", "kênh truyền hình hoặc phát sóng", "This channel focuses on world news."],
  ["remote control", "thiết bị điều khiển tivi từ xa", "Where is the remote control?"],
  ["subtitles", "phụ đề hiển thị lời nói", "Turn on subtitles for this interview."],
  ["ratings", "chỉ số người xem của chương trình", "The show gets high ratings every week."],
  ["tabloid", "báo khổ nhỏ thiên về tin giật gân", "He avoids reading tabloids."],
  ["broadsheet", "báo chính luận khổ lớn, nội dung nghiêm túc", "My father prefers a broadsheet."],
  ["press conference", "họp báo chính thức với truyền thông", "The minister held a press conference."],
  ["news bulletin", "bản tin ngắn cập nhật theo khung giờ", "A news bulletin interrupted the movie."],
  ["current affairs", "các vấn đề thời sự đương đại", "The class discussed current affairs today."],
]);

const U53_WORDS = wordList([
  ["dial", "bấm số để thực hiện cuộc gọi", "Please dial the number again.", "VERB"],
  ["voicemail", "hộp thư thoại ghi lời nhắn", "I left a message in your voicemail."],
  ["signal", "mức sóng điện thoại để liên lạc", "I have no signal in this basement."],
  ["ringtone", "âm chuông báo cuộc gọi đến", "Her ringtone is very loud."],
  ["contact list", "danh bạ lưu thông tin liên lạc", "His contact list is well organized."],
  ["missed call", "cuộc gọi nhỡ chưa kịp nghe", "I saw your missed call this morning."],
  ["call back", "gọi lại sau khi lỡ cuộc gọi", "I'll call back in ten minutes.", "VERB"],
  ["conference call", "cuộc gọi nhóm với nhiều người", "We scheduled a conference call at 3 p.m."],
  ["text message", "tin nhắn văn bản trên điện thoại", "Send me a text message when you arrive."],
  ["emoji", "biểu tượng cảm xúc dùng khi nhắn tin", "She replied with a laughing emoji."],
  ["voice note", "tin nhắn âm thanh ghi sẵn", "He sent a voice note instead of typing."],
  ["autocorrect", "tính năng tự sửa từ khi gõ", "Autocorrect changed my sentence."],
  ["group chat", "đoạn trò chuyện có nhiều thành viên", "Let's post the plan in the group chat."],
  ["mute notifications", "tắt thông báo tạm thời", "I mute notifications during meetings.", "VERB"],
  ["read receipt", "dấu hiệu cho biết tin nhắn đã được đọc", "I turned off read receipts."],
  ["spam call", "cuộc gọi rác quảng cáo không mong muốn", "I blocked three spam calls today."],
  ["battery low", "trạng thái pin yếu gần hết", "My phone says battery low."],
  ["phone charger", "bộ sạc pin cho điện thoại", "Did you bring your phone charger?"],
]);

const U54_WORDS = wordList([
  ["desktop computer", "máy tính để bàn dùng cố định", "The office still uses desktop computers."],
  ["laptop", "máy tính xách tay gọn nhẹ", "I carry my laptop to class every day."],
  ["keyboard", "bàn phím dùng để nhập dữ liệu", "This keyboard is quiet and smooth."],
  ["mouse", "chuột điều khiển con trỏ trên màn hình", "My wireless mouse needs a new battery."],
  ["monitor", "màn hình hiển thị của máy tính", "A second monitor improves productivity."],
  ["hard drive", "ổ lưu trữ dữ liệu trong máy", "Back up photos on an external hard drive."],
  ["usb port", "cổng cắm USB để kết nối thiết bị", "This laptop has only two USB ports."],
  ["restart", "khởi động lại hệ thống", "Try to restart the computer first.", "VERB"],
  ["shut down", "tắt máy hoàn toàn", "Please shut down before leaving.", "VERB"],
  ["install software", "cài đặt phần mềm vào máy", "I need admin rights to install software.", "VERB"],
  ["update driver", "cập nhật trình điều khiển phần cứng", "Updating the driver fixed the sound issue.", "VERB"],
  ["file folder", "thư mục chứa tệp tin", "Create a new file folder for this project."],
  ["copy and paste", "sao chép và dán dữ liệu", "Use copy and paste to save time.", "VERB"],
  ["delete permanently", "xóa vĩnh viễn không vào thùng rác", "Be careful when you delete permanently.", "VERB"],
  ["backup file", "tệp sao lưu để phòng mất dữ liệu", "Always keep a backup file on the cloud."],
  ["screen resolution", "độ phân giải hiển thị của màn hình", "High screen resolution gives sharper text."],
  ["processor", "bộ xử lý trung tâm của máy tính", "This processor handles heavy tasks well."],
  ["memory", "bộ nhớ RAM dùng xử lý tác vụ", "More memory helps when running many apps."],
]);

const U55_WORDS = wordList([
  ["inbox", "hộp thư đến chứa email nhận được", "My inbox is full of unread emails."],
  ["spam folder", "thư mục chứa email rác nghi ngờ", "Check the spam folder for missing mail."],
  ["attachment", "tệp đính kèm trong email", "I forgot to add the attachment."],
  ["subject line", "dòng tiêu đề tóm tắt email", "Write a clear subject line."],
  ["cc", "gửi bản sao hiển thị cho người liên quan", "Please cc your team leader."],
  ["bcc", "gửi bản sao ẩn danh sách người nhận", "Use bcc for large mailing lists."],
  ["forward email", "chuyển tiếp email cho người khác", "Can you forward the email to me?", "VERB"],
  ["reply all", "trả lời toàn bộ người nhận trong chuỗi", "Don't click reply all by mistake.", "VERB"],
  ["unsubscribe", "hủy đăng ký nhận tin", "I unsubscribed from that newsletter.", "VERB"],
  ["hyperlink", "liên kết có thể nhấn để mở trang", "The hyperlink leads to our homepage."],
  ["browser tab", "thẻ trang web đang mở trong trình duyệt", "I have too many browser tabs open."],
  ["search engine", "công cụ tìm kiếm thông tin trực tuyến", "Use a search engine for quick answers."],
  ["download", "tải dữ liệu từ internet về thiết bị", "Do not download unknown files.", "VERB"],
  ["upload", "đưa dữ liệu từ thiết bị lên internet", "Please upload your assignment here.", "VERB"],
  ["cloud storage", "dịch vụ lưu trữ trực tuyến trên đám mây", "Cloud storage keeps files synced."],
  ["password reset", "thao tác đặt lại mật khẩu", "I requested a password reset email."],
  ["two-factor authentication", "xác thực hai lớp để tăng bảo mật", "Enable two-factor authentication now."],
  ["privacy settings", "tùy chọn kiểm soát quyền riêng tư", "Review your privacy settings monthly."],
]);

const U56_WORDS = wordList([
  ["theft", "hành vi trộm cắp tài sản", "Theft has increased in this area."],
  ["robbery", "cướp tài sản bằng đe dọa hoặc vũ lực", "The robbery happened at night."],
  ["burglary", "đột nhập nhà/cửa hàng để lấy trộm", "Police investigated a burglary nearby."],
  ["suspect", "nghi phạm bị tình nghi gây án", "The suspect was seen on camera."],
  ["witness", "nhân chứng đã nhìn thấy sự việc", "A witness gave a detailed statement."],
  ["evidence", "chứng cứ phục vụ điều tra và xét xử", "DNA evidence changed the case."],
  ["fingerprint", "dấu vân tay nhận dạng cá nhân", "The officer collected fingerprints."],
  ["detective", "thám tử hoặc điều tra viên hình sự", "A detective interviewed the neighbors."],
  ["arrest", "bắt giữ theo thủ tục pháp luật", "Police arrested two suspects.", "VERB"],
  ["handcuffs", "còng tay dùng để khống chế người bị bắt", "The man was led away in handcuffs."],
  ["prison sentence", "án phạt tù do tòa tuyên", "He received a five-year prison sentence."],
  ["fine", "khoản tiền phạt hành chính hoặc pháp lý", "The court issued a heavy fine."],
  ["guilty", "có tội theo phán quyết tòa án", "The jury found him guilty.", "ADJECTIVE"],
  ["innocent", "vô tội, không phạm hành vi bị cáo buộc", "She was proved innocent.", "ADJECTIVE"],
  ["court case", "vụ việc được xét xử tại tòa", "The court case lasted three months."],
  ["scam", "hành vi lừa đảo để chiếm đoạt tài sản", "Online shopping scams are common now."],
  ["shoplifting", "ăn cắp hàng hóa trong cửa hàng", "Shoplifting is a serious offense."],
  ["self-defense", "hành động tự vệ để bảo vệ bản thân", "He said he acted in self-defense."],
]);

const U57_WORDS = wordList([
  ["election", "cuộc bầu cử để chọn lãnh đạo", "The national election is next month."],
  ["campaign", "chiến dịch vận động chính trị", "Her campaign focused on education reform."],
  ["candidate", "người ra tranh cử một vị trí", "Each candidate gave a short speech."],
  ["voter", "cử tri có quyền bỏ phiếu", "Young voters care about climate policy."],
  ["ballot paper", "phiếu bầu dùng để chọn ứng viên", "Put your ballot paper in the box."],
  ["parliament", "cơ quan lập pháp của quốc gia", "The law was debated in parliament."],
  ["prime minister", "thủ tướng đứng đầu chính phủ", "The prime minister addressed the nation."],
  ["policy", "chính sách định hướng hành động công", "We need a long-term housing policy."],
  ["debate", "cuộc tranh luận chính thức về vấn đề công", "The debate lasted nearly two hours."],
  ["speech", "bài phát biểu trước công chúng", "Her speech inspired many people."],
  ["tax reform", "cải cách hệ thống thuế", "Tax reform may support small businesses."],
  ["public services", "dịch vụ công như y tế, giáo dục, giao thông", "Public services need stable funding."],
  ["opposition party", "đảng đối lập với chính quyền đương nhiệm", "The opposition party rejected the proposal."],
  ["coalition", "liên minh giữa nhiều đảng để cầm quyền", "A coalition government was formed quickly."],
  ["approve a bill", "thông qua một dự luật thành luật", "Lawmakers voted to approve the bill.", "VERB"],
  ["protest march", "cuộc tuần hành biểu tình ôn hòa", "Thousands joined the protest march."],
  ["opinion poll", "khảo sát ý kiến dư luận", "An opinion poll showed mixed support."],
  ["democracy", "thể chế người dân tham gia chọn lãnh đạo", "Democracy depends on active citizens."],
]);

const U58_WORDS = wordList([
  ["global warming", "hiện tượng nhiệt độ trái đất tăng dài hạn", "Global warming affects weather worldwide."],
  ["greenhouse gas", "khí nhà kính giữ nhiệt trong khí quyển", "CO2 is a major greenhouse gas."],
  ["carbon footprint", "lượng phát thải carbon do cá nhân/tổ chức tạo ra", "Taking trains reduces your carbon footprint."],
  ["renewable energy", "nguồn năng lượng tái tạo như gió, mặt trời", "Renewable energy is growing quickly."],
  ["solar panel", "tấm pin chuyển ánh sáng thành điện", "We installed solar panels on the roof."],
  ["wind farm", "khu đặt nhiều tua-bin tạo điện gió", "A new wind farm opened offshore."],
  ["deforestation", "nạn chặt phá rừng diện rộng", "Deforestation threatens biodiversity."],
  ["melting ice", "quá trình băng tan do nhiệt độ tăng", "Melting ice raises sea levels."],
  ["sea level rise", "mực nước biển dâng cao theo thời gian", "Sea level rise endangers coastal cities."],
  ["extreme weather", "thời tiết cực đoan khó dự đoán", "Extreme weather damages crops."],
  ["drought", "hạn hán kéo dài thiếu nước nghiêm trọng", "Farmers suffered from severe drought."],
  ["flood", "lũ lụt gây ngập diện rộng", "The flood forced families to evacuate."],
  ["climate action", "hành động cụ thể để ứng phó khí hậu", "Young people demand stronger climate action."],
  ["recycle", "tái chế để giảm rác và tiết kiệm tài nguyên", "Please recycle plastic bottles.", "VERB"],
  ["electric vehicle", "phương tiện chạy điện thay nhiên liệu hóa thạch", "Electric vehicles are quieter in cities."],
  ["net zero", "mục tiêu phát thải ròng bằng không", "The company aims for net zero by 2040."],
  ["carbon tax", "thuế áp lên lượng phát thải carbon", "Some economists support a carbon tax."],
  ["sustainability", "tính bền vững lâu dài về môi trường và xã hội", "Sustainability should guide business decisions."],
]);

const U59_WORDS = wordList([
  ["conflict", "xung đột giữa các nhóm hoặc quốc gia", "The conflict has lasted for years."],
  ["ceasefire", "thỏa thuận ngừng bắn tạm thời", "Both sides agreed to a ceasefire."],
  ["refugee", "người tị nạn rời nơi ở vì chiến tranh/bạo lực", "The camp shelters many refugees."],
  ["evacuate", "sơ tán người ra khỏi vùng nguy hiểm", "The army evacuated villagers overnight.", "VERB"],
  ["frontline", "khu vực tuyến đầu giao tranh", "Medical teams worked near the frontline."],
  ["air strike", "cuộc tấn công từ trên không", "The air strike damaged several buildings."],
  ["peace talks", "đàm phán hòa bình để chấm dứt xung đột", "Peace talks resumed this week."],
  ["civilian", "thường dân không tham chiến", "Many civilians fled the city."],
  ["casualty", "người thương vong trong xung đột", "Officials confirmed new casualties."],
  ["weapon", "vũ khí dùng để tấn công hoặc phòng vệ", "The group surrendered their weapons."],
  ["armed group", "nhóm có trang bị vũ trang", "An armed group blocked the road."],
  ["hostage", "con tin bị bắt để gây áp lực", "Negotiators secured the hostages' release."],
  ["bomb blast", "vụ nổ bom gây thiệt hại lớn", "A bomb blast shook the market area."],
  ["humanitarian aid", "hỗ trợ nhân đạo như lương thực, y tế", "Humanitarian aid reached remote villages."],
  ["war crime", "tội ác chiến tranh vi phạm luật quốc tế", "The court is investigating war crimes."],
  ["violent attack", "cuộc tấn công bạo lực gây thương tích", "The violent attack shocked the community."],
  ["rebuild", "xây dựng lại sau tàn phá", "Families hope to rebuild their homes.", "VERB"],
  ["trauma", "sang chấn tâm lý sau biến cố nghiêm trọng", "Children may suffer long-term trauma."],
]);

const U60_WORDS = wordList([
  ["punctual", "đúng giờ, không trễ hẹn", "She is always punctual for meetings.", "ADJECTIVE"],
  ["deadline", "hạn chót phải hoàn thành công việc", "We must meet the project deadline."],
  ["schedule", "lịch sắp xếp hoạt động theo thời gian", "My schedule is packed this week."],
  ["timetable", "bảng thời gian cố định của lớp/tàu xe", "Check the bus timetable before leaving."],
  ["on time", "đúng giờ theo kế hoạch ban đầu", "The train arrived on time."],
  ["in advance", "trước một khoảng thời gian nhất định", "Please book in advance for weekends."],
  ["delay", "sự chậm trễ so với kế hoạch", "Heavy traffic caused a long delay."],
  ["postpone", "hoãn lại sang thời điểm khác", "They postponed the meeting until Friday.", "VERB"],
  ["meanwhile", "trong lúc đó, ở thời điểm song song", "I'll cook dinner; meanwhile, set the table."],
  ["eventually", "cuối cùng sau nhiều chờ đợi", "He eventually found the right answer."],
  ["recently", "gần đây, trong thời gian mới qua", "I recently started a new routine."],
  ["lately", "dạo này, thời gian gần hiện tại", "Have you slept well lately?"],
  ["currently", "hiện tại, vào lúc này", "She is currently working remotely."],
  ["temporary", "tạm thời, không kéo dài mãi", "This office is temporary.", "ADJECTIVE"],
  ["permanent", "lâu dài, ổn định", "He accepted a permanent position.", "ADJECTIVE"],
  ["spare time", "thời gian rảnh ngoài việc chính", "I read novels in my spare time."],
  ["time zone", "múi giờ theo khu vực địa lý", "Tokyo is in a different time zone."],
  ["daylight saving", "chế độ chỉnh đồng hồ theo mùa để tận dụng ánh sáng", "Daylight saving begins in March."],
]);

export const EVIU_PRE_UNITS_46_60: VocabularyUnit[] = [
  preUnit(46, {
    introVi: "Unit 46 tập trung ngôn ngữ đặt vé du lịch: từ đặt chỗ, điều kiện hủy đến xác nhận lịch trình. Mục tiêu là giúp bạn xử lý việc book dịch vụ tự tin hơn.",
    structureSections: [
      { label: "Booking basics", wordCount: 6 },
      { label: "Fare and policy terms", wordCount: 6 },
      { label: "Travel plan details", wordCount: 6 },
    ],
    collocationHtml: `${purple("travel insurance")}, ${purple("cancellation policy")} và ${purple("booking reference")} là ba cụm cần nhớ khi đặt chuyến đi.`,
    mistakeHtml: "Đừng nhầm refundable fare với non-refundable: một loại hoàn tiền được, một loại thường mất phí hoặc không hoàn.",
    principles: [
      {
        title: "Xác nhận rõ điều kiện vé trước khi thanh toán",
        body: `Ưu tiên kiểm tra ${purple("cancellation policy")} và loại ${purple("refundable fare")} để tránh mất tiền khi thay đổi kế hoạch.`,
        examples: [ex("I checked the cancellation policy before paying.", "Tôi kiểm tra chính sách hủy trước khi thanh toán.")],
      },
      {
        title: "Giữ đầy đủ thông tin đặt chỗ",
        body: `Luôn lưu ${purple("booking reference")} và ${purple("confirmation email")} để làm thủ tục nhanh.`,
        examples: [ex("Please show your booking reference at check-in.", "Vui lòng đưa mã đặt chỗ khi làm thủ tục.")],
      },
      {
        title: "Lập lịch đi về rõ ràng",
        body: `Chốt sớm ${purple("departure date")} và ${purple("return date")} giúp đặt giá tốt hơn.`,
        examples: [ex("Our return date is fixed now.", "Ngày quay về của chúng tôi đã chốt.")],
      },
    ],
    words: U46_WORDS,
    exercises: [
      mcq(
        46,
        1,
        "Từ nào chỉ mã dùng để tra cứu đặt chỗ?",
        [
          { key: "a", label: "booking reference" },
          { key: "b", label: "stopover" },
          { key: "c", label: "itinerary" },
          { key: "d", label: "seat selection" },
        ],
        "a",
      ),
      fillBlank(
        46,
        2,
        "A ____ ticket can usually be changed or canceled with money back.",
        "refundable fare",
        [
          { key: "a", label: "booking platform" },
          { key: "b", label: "non-refundable" },
          { key: "c", label: "refundable fare" },
          { key: "d", label: "check-in window" },
        ],
        "c",
      ),
    ],
  }),
  preUnit(47, {
    introVi: "Unit 47 mở rộng từ vựng đi máy bay: khu vực sân bay, thủ tục bay và sự cố phổ biến trong hành trình. Bạn sẽ giao tiếp linh hoạt hơn khi di chuyển quốc tế.",
    structureSections: [
      { label: "Airport procedures", wordCount: 6 },
      { label: "On-board experience", wordCount: 6 },
      { label: "Travel disruptions", wordCount: 6 },
    ],
    collocationHtml: `${purple("boarding pass")}, ${purple("security check")} và ${purple("missed connection")} xuất hiện liên tục ở sân bay.`,
    mistakeHtml: "Đừng dùng lẫn gate number với runway: gate là cổng chờ lên máy bay, runway là đường băng cất hạ cánh.",
    principles: [
      {
        title: "Nắm thứ tự làm thủ tục",
        body: `Thường đi theo trình tự: ${purple("security check")} -> ${purple("departure lounge")} -> gate.`,
        examples: [ex("We cleared security check in ten minutes.", "Chúng tôi qua kiểm tra an ninh trong mười phút.")],
      },
      {
        title: "Chọn chỗ ngồi theo nhu cầu",
        body: `${purple("aisle seat")} tiện di chuyển; ${purple("window seat")} hợp người thích ngắm cảnh.`,
        examples: [ex("I booked an aisle seat for comfort.", "Tôi đặt ghế lối đi để thoải mái hơn.")],
      },
      {
        title: "Chuẩn bị cho các tình huống trễ chuyến",
        body: `Nếu có ${purple("delayed flight")} hoặc ${purple("missed connection")}, hãy liên hệ hãng ngay.`,
        examples: [ex("A delayed flight made us miss our connection.", "Chuyến bay trễ làm chúng tôi lỡ chuyến nối.")],
      },
    ],
    words: U47_WORDS,
    exercises: [
      mcq(
        47,
        1,
        "Bạn cần xuất trình giấy tờ nào khi lên máy bay?",
        [
          { key: "a", label: "weather report" },
          { key: "b", label: "boarding pass" },
          { key: "c", label: "runway map" },
          { key: "d", label: "jet lag" },
        ],
        "b",
      ),
      fillBlank(
        47,
        2,
        "I felt very tired after crossing six time zones. It was ____.",
        "jet lag",
        [
          { key: "a", label: "landing" },
          { key: "b", label: "turbulence" },
          { key: "c", label: "jet lag" },
          { key: "d", label: "gate number" },
        ],
        "c",
      ),
    ],
  }),
  preUnit(48, {
    introVi: "Unit 48 giúp bạn xử lý tình huống ở khách sạn và nhà hàng: đặt phòng, dùng dịch vụ và gọi món. Từ vựng bám sát giao tiếp du lịch thực tế.",
    structureSections: [
      { label: "Hotel services", wordCount: 6 },
      { label: "Room and booking terms", wordCount: 6 },
      { label: "Restaurant dining", wordCount: 6 },
    ],
    collocationHtml: `${purple("reception desk")}, ${purple("room service")} và ${purple("set menu")} là cụm phổ biến khi đi công tác hoặc du lịch.`,
    mistakeHtml: "Reservation có thể dùng cho cả đặt bàn và đặt phòng, cần dựa vào ngữ cảnh để hiểu đúng.",
    principles: [
      {
        title: "Nói rõ loại phòng và thời gian lưu trú",
        body: `Phân biệt ${purple("single room")} và ${purple("double room")} để tránh đặt sai.`,
        examples: [ex("I'd like a double room for two nights.", "Tôi muốn đặt phòng đôi trong hai đêm.")],
      },
      {
        title: "Kiểm tra quyền lợi đi kèm",
        body: `${purple("complimentary")} breakfast hay ${purple("wake-up call")} thường là tiện ích hữu ích.`,
        examples: [ex("Is buffet breakfast complimentary?", "Bữa sáng buffet có miễn phí không?")],
      },
      {
        title: "Gọi món theo cấu trúc bữa ăn",
        body: `Dùng ${purple("main course")} và ${purple("side dish")} để đặt món rõ ràng.`,
        examples: [ex("I'll have chicken as the main course.", "Tôi chọn gà làm món chính.")],
      },
    ],
    words: U48_WORDS,
    exercises: [
      mcq(
        48,
        1,
        "Từ nào chỉ giờ khách phải trả phòng?",
        [
          { key: "a", label: "check-out time" },
          { key: "b", label: "wake-up call" },
          { key: "c", label: "room service" },
          { key: "d", label: "vacancy" },
        ],
        "a",
      ),
      fillBlank(
        48,
        2,
        "Could we have the ____, please?",
        "bill",
        [
          { key: "a", label: "tip" },
          { key: "b", label: "reservation" },
          { key: "c", label: "bill" },
          { key: "d", label: "housekeeping" },
        ],
        "c",
      ),
    ],
  }),
  preUnit(49, {
    introVi: "Unit 49 xoay quanh ngôn ngữ quán cà phê hiện đại: gọi đồ, chọn sữa, dùng dịch vụ tại chỗ hoặc mang đi. Bạn sẽ gọi món tự nhiên hơn trong môi trường quốc tế.",
    structureSections: [
      { label: "Coffee drinks", wordCount: 6 },
      { label: "Cafe service", wordCount: 6 },
      { label: "Shop experience", wordCount: 6 },
    ],
    collocationHtml: `${purple("takeaway cup")}, ${purple("loyalty card")} và ${purple("grind size")} giúp bạn nói chuyện như khách quen.`,
    mistakeHtml: "Dine in là dùng tại quán, không phải mang đi; takeaway mới là mang đi.",
    principles: [
      {
        title: "Phân biệt các loại cà phê cơ bản",
        body: `${purple("latte")}, ${purple("cappuccino")} và ${purple("americano")} khác nhau ở tỷ lệ sữa và nước.`,
        examples: [ex("An americano has no milk by default.", "Americano mặc định không có sữa.")],
      },
      {
        title: "Nói rõ nhu cầu cá nhân khi gọi đồ",
        body: `Bạn có thể đổi ${purple("soy milk")} hoặc ${purple("oat milk")} theo khẩu vị.`,
        examples: [ex("Can I get oat milk instead?", "Tôi đổi sang sữa yến mạch được không?")],
      },
      {
        title: "Tận dụng dịch vụ của quán",
        body: `Nhiều quán có ${purple("free wi-fi")} và chương trình ${purple("loyalty card")}.`,
        examples: [ex("I use the loyalty card every week.", "Tôi dùng thẻ tích điểm mỗi tuần.")],
      },
    ],
    words: U49_WORDS,
    exercises: [
      mcq(
        49,
        1,
        "Người pha chế chuyên nghiệp trong quán cà phê gọi là gì?",
        [
          { key: "a", label: "barista" },
          { key: "b", label: "columnist" },
          { key: "c", label: "lifeguard" },
          { key: "d", label: "guide" },
        ],
        "a",
      ),
      fillBlank(
        49,
        2,
        "I want to drink here, so I will ____.",
        "dine in",
        [
          { key: "a", label: "dine in" },
          { key: "b", label: "refill" },
          { key: "c", label: "takeaway cup" },
          { key: "d", label: "unsubscribe" },
        ],
        "a",
      ),
    ],
  }),
  preUnit(50, {
    introVi: "Unit 50 phát triển từ vựng tham quan khi đi nghỉ: địa danh, vé tham quan và trải nghiệm trong thành phố. Bạn sẽ mô tả chuyến đi chi tiết và tự nhiên hơn.",
    structureSections: [
      { label: "Tour activities", wordCount: 6 },
      { label: "Places and access", wordCount: 6 },
      { label: "Tourist experience", wordCount: 6 },
    ],
    collocationHtml: `${purple("guided tour")}, ${purple("heritage site")} và ${purple("hidden gem")} là cụm xuất hiện nhiều trong review du lịch.`,
    mistakeHtml: "Tourist trap mang nghĩa tiêu cực, còn hidden gem thường mang nghĩa tích cực.",
    principles: [
      {
        title: "Kết hợp từ chỉ nơi chốn và trải nghiệm",
        body: `Ghép ${purple("landmark")} với hoạt động như ${purple("walking tour")} để câu văn sinh động hơn.`,
        examples: [ex("We visited the landmark on a walking tour.", "Chúng tôi thăm địa danh bằng tour đi bộ.")],
      },
      {
        title: "Kiểm tra thông tin trước khi đi",
        body: `${purple("opening times")} và ${purple("admission fee")} giúp bạn tránh lỡ kế hoạch.`,
        examples: [ex("Check opening times before the day trip.", "Hãy xem giờ mở cửa trước chuyến đi trong ngày.")],
      },
      {
        title: "Đánh giá điểm đến bằng từ trung lập",
        body: `Dùng ${purple("tourist trap")} khi nơi đó quá thương mại, dùng ${purple("hidden gem")} khi đáng khám phá.`,
        examples: [ex("That museum cafe is a hidden gem.", "Quán cà phê trong bảo tàng là một điểm rất đáng khám phá.")],
      },
    ],
    words: U50_WORDS,
    exercises: [
      mcq(
        50,
        1,
        "Từ nào nghĩa là địa điểm ít người biết nhưng rất đáng tham quan?",
        [
          { key: "a", label: "tourist trap" },
          { key: "b", label: "front page" },
          { key: "c", label: "hidden gem" },
          { key: "d", label: "queue up" },
        ],
        "c",
      ),
      fillBlank(
        50,
        2,
        "We had to ____ for thirty minutes before entering the museum.",
        "queue up",
        [
          { key: "a", label: "queue up" },
          { key: "b", label: "rebuild" },
          { key: "c", label: "dial" },
          { key: "d", label: "upload" },
        ],
        "a",
      ),
    ],
  }),
  preUnit(51, {
    introVi: "Unit 51 cung cấp vốn từ cho kỳ nghỉ biển: hoạt động bãi biển, an toàn dưới nước và trải nghiệm thư giãn. Nội dung phù hợp cả hội thoại lẫn viết nhật ký du lịch.",
    structureSections: [
      { label: "Beach environment", wordCount: 6 },
      { label: "Sea activities", wordCount: 6 },
      { label: "Safety and services", wordCount: 6 },
    ],
    collocationHtml: `${purple("sandy beach")}, ${purple("sea breeze")} và ${purple("sunset cruise")} giúp mô tả kỳ nghỉ biển giàu hình ảnh.`,
    mistakeHtml: "Tide là mực nước lên xuống theo chu kỳ, không phải waves là sóng chuyển động trên bề mặt.",
    principles: [
      {
        title: "Dùng từ theo bối cảnh ven biển",
        body: `${purple("coastline")}, ${purple("pier")} và ${purple("seaside resort")} tạo khung mô tả địa điểm rõ ràng.`,
        examples: [ex("The pier was busy at sunset.", "Cầu tàu nhộn nhịp lúc hoàng hôn.")],
      },
      {
        title: "Mô tả hoạt động biển cụ thể",
        body: `Bạn có thể nói ${purple("snorkeling")}, ${purple("boat trip")} hoặc ${purple("beach volleyball")} thay vì chỉ nói go to the beach.`,
        examples: [ex("We tried snorkeling in clear water.", "Chúng tôi lặn nông ở vùng nước trong.")],
      },
      {
        title: "Ưu tiên từ vựng an toàn khi đi biển",
        body: `${purple("lifeguard")} và ${purple("sunscreen")} là hai từ rất thực tế khi du lịch gia đình.`,
        examples: [ex("The lifeguard warned us about strong waves.", "Nhân viên cứu hộ cảnh báo sóng mạnh.")],
      },
    ],
    words: U51_WORDS,
    exercises: [
      mcq(
        51,
        1,
        "Ai là người đảm bảo an toàn ở khu bơi biển?",
        [
          { key: "a", label: "barista" },
          { key: "b", label: "lifeguard" },
          { key: "c", label: "anchor" },
          { key: "d", label: "columnist" },
        ],
        "b",
      ),
      fillBlank(
        51,
        2,
        "We watched the sunset while taking a ____.",
        "sunset cruise",
        [
          { key: "a", label: "sunset cruise" },
          { key: "b", label: "weather report" },
          { key: "c", label: "court case" },
          { key: "d", label: "schedule" },
        ],
        "a",
      ),
    ],
  }),
  preUnit(52, {
    introVi: "Unit 52 tập trung ngôn ngữ báo chí và truyền hình: loại bài, chương trình và cách đưa tin. Bạn sẽ đọc tin và thảo luận thời sự chính xác hơn.",
    structureSections: [
      { label: "Newspaper terms", wordCount: 6 },
      { label: "TV and broadcast", wordCount: 6 },
      { label: "News content", wordCount: 6 },
    ],
    collocationHtml: `${purple("breaking news")}, ${purple("press conference")} và ${purple("current affairs")} là cụm quan trọng trong truyền thông.`,
    mistakeHtml: "Tabloid thiên về tin giật gân, còn broadsheet thường nghiêm túc và phân tích sâu hơn.",
    principles: [
      {
        title: "Phân biệt định dạng báo in và truyền hình",
        body: `${purple("front page")} và ${purple("headline")} thường dùng cho báo; ${purple("anchor")} dùng cho TV.`,
        examples: [ex("The headline was on the front page.", "Tiêu đề lớn nằm ở trang nhất.")],
      },
      {
        title: "Nhận biết mức độ cập nhật của bản tin",
        body: `${purple("news bulletin")} là bản tin ngắn, còn ${purple("documentary")} đi sâu một chủ đề.`,
        examples: [ex("A short news bulletin came at noon.", "Một bản tin ngắn phát lúc trưa.")],
      },
      {
        title: "Theo dõi tin có kiểm chứng",
        body: `Khi xem ${purple("breaking news")}, nên chờ thêm nguồn chính thức và ${purple("press conference")}.`,
        examples: [ex("They confirmed details at a press conference.", "Họ xác nhận thông tin trong buổi họp báo.")],
      },
    ],
    words: U52_WORDS,
    exercises: [
      mcq(
        52,
        1,
        "Từ nào chỉ người dẫn bản tin trên truyền hình?",
        [
          { key: "a", label: "anchor" },
          { key: "b", label: "candidate" },
          { key: "c", label: "voter" },
          { key: "d", label: "witness" },
        ],
        "a",
      ),
      fillBlank(
        52,
        2,
        "The minister answered journalists in a ____.",
        "press conference",
        [
          { key: "a", label: "press conference" },
          { key: "b", label: "walking tour" },
          { key: "c", label: "side dish" },
          { key: "d", label: "vacancy" },
        ],
        "a",
      ),
    ],
  }),
  preUnit(53, {
    introVi: "Unit 53 mở rộng từ vựng nghe gọi và nhắn tin trên điện thoại thông minh. Bạn sẽ xử lý giao tiếp số hằng ngày rõ ràng và chuyên nghiệp hơn.",
    structureSections: [
      { label: "Calling actions", wordCount: 6 },
      { label: "Messaging features", wordCount: 6 },
      { label: "Phone issues", wordCount: 6 },
    ],
    collocationHtml: `${purple("missed call")}, ${purple("voice note")} và ${purple("group chat")} là các cụm cực kỳ thông dụng.`,
    mistakeHtml: "Signal là sóng mạng; voicemail là hộp thư thoại. Hai từ này không thay thế nhau.",
    principles: [
      {
        title: "Chọn kênh liên lạc theo tình huống",
        body: `Nếu cần nhanh hãy ${purple("call back")}; nếu cần lưu chi tiết hãy gửi ${purple("text message")}.`,
        examples: [ex("I will call back after the meeting.", "Tôi sẽ gọi lại sau cuộc họp.")],
      },
      {
        title: "Dùng tính năng nhắn tin hiệu quả",
        body: `${purple("read receipt")} và ${purple("mute notifications")} giúp kiểm soát nhịp trao đổi.`,
        examples: [ex("I mute notifications at night.", "Tôi tắt thông báo vào ban đêm.")],
      },
      {
        title: "Xử lý sự cố cơ bản trên điện thoại",
        body: `Khi ${purple("battery low")}, cần ưu tiên cắm ${purple("phone charger")} và giảm ứng dụng nền.`,
        examples: [ex("My phone is battery low; I need a charger.", "Điện thoại tôi sắp hết pin; tôi cần bộ sạc.")],
      },
    ],
    words: U53_WORDS,
    exercises: [
      mcq(
        53,
        1,
        "Từ nào chỉ cuộc gọi bạn chưa kịp nghe?",
        [
          { key: "a", label: "conference call" },
          { key: "b", label: "missed call" },
          { key: "c", label: "read receipt" },
          { key: "d", label: "signal" },
        ],
        "b",
      ),
      fillBlank(
        53,
        2,
        "Please leave a message in my ____ if I can't answer.",
        "voicemail",
        [
          { key: "a", label: "voicemail" },
          { key: "b", label: "contact list" },
          { key: "c", label: "autocorrect" },
          { key: "d", label: "phone charger" },
        ],
        "a",
      ),
    ],
  }),
  preUnit(54, {
    introVi: "Unit 54 cung cấp vốn từ nền tảng về máy tính và thao tác kỹ thuật cơ bản. Bạn sẽ đọc hướng dẫn công nghệ và trao đổi hỗ trợ IT dễ hơn.",
    structureSections: [
      { label: "Computer hardware", wordCount: 6 },
      { label: "System operations", wordCount: 6 },
      { label: "Files and performance", wordCount: 6 },
    ],
    collocationHtml: `${purple("install software")}, ${purple("backup file")} và ${purple("screen resolution")} là các cụm gặp thường xuyên trong công việc số.`,
    mistakeHtml: "Restart là khởi động lại, còn shut down là tắt hẳn máy; cần dùng đúng khi hướng dẫn người khác.",
    principles: [
      {
        title: "Nhớ tên phần cứng cơ bản trước",
        body: `Nắm chắc ${purple("keyboard")}, ${purple("monitor")} và ${purple("processor")} giúp hiểu tài liệu kỹ thuật nhanh hơn.`,
        examples: [ex("This processor is faster than my old one.", "Bộ xử lý này nhanh hơn máy cũ của tôi.")],
      },
      {
        title: "Dùng đúng động từ thao tác hệ thống",
        body: `${purple("restart")} khi máy treo nhẹ; ${purple("shut down")} khi kết thúc làm việc.`,
        examples: [ex("Try to restart before calling IT.", "Hãy thử khởi động lại trước khi gọi IT.")],
      },
      {
        title: "Ưu tiên an toàn dữ liệu",
        body: `Thói quen tạo ${purple("backup file")} và không ${purple("delete permanently")} nhầm là rất quan trọng.`,
        examples: [ex("I keep a weekly backup file.", "Tôi giữ bản sao lưu mỗi tuần.")],
      },
    ],
    words: U54_WORDS,
    exercises: [
      mcq(
        54,
        1,
        "Từ nào chỉ bộ xử lý trung tâm của máy tính?",
        [
          { key: "a", label: "monitor" },
          { key: "b", label: "processor" },
          { key: "c", label: "mouse" },
          { key: "d", label: "usb port" },
        ],
        "b",
      ),
      fillBlank(
        54,
        2,
        "Always create a ____ before making major edits.",
        "backup file",
        [
          { key: "a", label: "backup file" },
          { key: "b", label: "front page" },
          { key: "c", label: "side dish" },
          { key: "d", label: "ballot paper" },
        ],
        "a",
      ),
    ],
  }),
  preUnit(55, {
    introVi: "Unit 55 tập trung email và internet: cách gửi thư chuyên nghiệp, quản lý thông tin và bảo mật tài khoản. Đây là nhóm từ bắt buộc cho học tập và công việc hiện đại.",
    structureSections: [
      { label: "Email basics", wordCount: 6 },
      { label: "Mail actions", wordCount: 6 },
      { label: "Web and security", wordCount: 6 },
    ],
    collocationHtml: `${purple("subject line")}, ${purple("two-factor authentication")} và ${purple("cloud storage")} là cụm quan trọng cho môi trường số.`,
    mistakeHtml: "CC là hiện người nhận công khai, BCC là ẩn danh sách người nhận; dùng sai có thể lộ thông tin.",
    principles: [
      {
        title: "Viết email rõ mục đích",
        body: `${purple("subject line")} ngắn gọn và đúng chủ đề giúp người nhận xử lý nhanh.`,
        examples: [ex("Use a clear subject line for urgent requests.", "Dùng tiêu đề rõ ràng cho yêu cầu khẩn.")],
      },
      {
        title: "Quản lý người nhận cẩn thận",
        body: `Hiểu rõ khi nào dùng ${purple("cc")} hoặc ${purple("bcc")} để giữ tính chuyên nghiệp.`,
        examples: [ex("Please cc finance on this update.", "Vui lòng đưa bộ phận tài chính vào bản sao email này.")],
      },
      {
        title: "Ưu tiên bảo mật tài khoản",
        body: `Bật ${purple("two-factor authentication")} và kiểm tra ${purple("privacy settings")} định kỳ.`,
        examples: [ex("I enabled two-factor authentication today.", "Hôm nay tôi đã bật xác thực hai lớp.")],
      },
    ],
    words: U55_WORDS,
    exercises: [
      mcq(
        55,
        1,
        "Từ nào chỉ tệp được gửi kèm email?",
        [
          { key: "a", label: "attachment" },
          { key: "b", label: "browser tab" },
          { key: "c", label: "inbox" },
          { key: "d", label: "subject line" },
        ],
        "a",
      ),
      fillBlank(
        55,
        2,
        "For better security, turn on ____.",
        "two-factor authentication",
        [
          { key: "a", label: "unsubscribe" },
          { key: "b", label: "cc" },
          { key: "c", label: "two-factor authentication" },
          { key: "d", label: "reply all" },
        ],
        "c",
      ),
    ],
  }),
  preUnit(56, {
    introVi: "Unit 56 giới thiệu bộ từ nền về tội phạm và pháp luật: hành vi phạm tội, điều tra và xét xử. Mục tiêu là hiểu tin tức pháp lý ở mức tiền trung cấp.",
    structureSections: [
      { label: "Types of crime", wordCount: 6 },
      { label: "Investigation terms", wordCount: 6 },
      { label: "Court outcomes", wordCount: 6 },
    ],
    collocationHtml: `${purple("court case")}, ${purple("prison sentence")} và ${purple("DNA evidence")} là các kết hợp thường thấy trong bản tin pháp luật.`,
    mistakeHtml: "Robbery có dùng đe dọa/vũ lực, còn theft là lấy trộm nói chung; burglary là đột nhập trộm.",
    principles: [
      {
        title: "Phân biệt chính xác các loại tội danh",
        body: `Không dùng chung bừa bãi ${purple("theft")}, ${purple("robbery")} và ${purple("burglary")}.`,
        examples: [ex("Burglary often happens when the owner is away.", "Đột nhập trộm thường xảy ra khi chủ nhà vắng mặt.")],
      },
      {
        title: "Nắm từ vựng điều tra cơ bản",
        body: `${purple("suspect")}, ${purple("witness")} và ${purple("evidence")} là ba từ cốt lõi khi đọc bản tin.`,
        examples: [ex("A witness gave evidence in court.", "Một nhân chứng đã cung cấp chứng cứ tại tòa.")],
      },
      {
        title: "Hiểu kết quả pháp lý sau xét xử",
        body: `${purple("guilty")} hoặc ${purple("innocent")} ảnh hưởng trực tiếp đến ${purple("prison sentence")} hay ${purple("fine")}.`,
        examples: [ex("The judge gave him a heavy fine.", "Thẩm phán phạt anh ấy một khoản lớn.")],
      },
    ],
    words: U56_WORDS,
    exercises: [
      mcq(
        56,
        1,
        "Từ nào chỉ người làm chứng đã thấy sự việc?",
        [
          { key: "a", label: "suspect" },
          { key: "b", label: "detective" },
          { key: "c", label: "witness" },
          { key: "d", label: "scam" },
        ],
        "c",
      ),
      fillBlank(
        56,
        2,
        "The police decided to ____ the suspect after collecting evidence.",
        "arrest",
        [
          { key: "a", label: "arrest" },
          { key: "b", label: "recycle" },
          { key: "c", label: "upload" },
          { key: "d", label: "broadcast live" },
        ],
        "a",
      ),
    ],
  }),
  preUnit(57, {
    introVi: "Unit 57 mở rộng từ vựng chính trị công dân: bầu cử, nghị viện, chính sách và tranh luận công. Nội dung giúp bạn theo dõi tin chính trị bằng tiếng Anh dễ hơn.",
    structureSections: [
      { label: "Election process", wordCount: 6 },
      { label: "Government and policy", wordCount: 6 },
      { label: "Public participation", wordCount: 6 },
    ],
    collocationHtml: `${purple("opinion poll")}, ${purple("public services")} và ${purple("approve a bill")} là các cụm nền tảng của chủ đề.`,
    mistakeHtml: "Policy là định hướng cụ thể, còn politics là lĩnh vực chung; không nên dùng thay thế tùy tiện.",
    principles: [
      {
        title: "Hiểu vai trò trong bầu cử",
        body: `${purple("candidate")} tranh cử, ${purple("voter")} bỏ phiếu trên ${purple("ballot paper")}.`,
        examples: [ex("Each voter receives one ballot paper.", "Mỗi cử tri nhận một phiếu bầu.")],
      },
      {
        title: "Nắm cấu trúc thảo luận chính sách",
        body: `Chủ đề thường đi qua ${purple("debate")}, ${purple("speech")} rồi đến biểu quyết.`,
        examples: [ex("The policy was discussed in a long debate.", "Chính sách được thảo luận trong cuộc tranh luận dài.")],
      },
      {
        title: "Theo dõi phản ứng xã hội với quyết định công",
        body: `${purple("protest march")} và ${purple("opinion poll")} cho thấy mức độ ủng hộ của công chúng.`,
        examples: [ex("An opinion poll showed rising support.", "Khảo sát dư luận cho thấy mức ủng hộ tăng.")],
      },
    ],
    words: U57_WORDS,
    exercises: [
      mcq(
        57,
        1,
        "Từ nào chỉ cuộc khảo sát ý kiến công chúng?",
        [
          { key: "a", label: "speech" },
          { key: "b", label: "opinion poll" },
          { key: "c", label: "coalition" },
          { key: "d", label: "policy" },
        ],
        "b",
      ),
      fillBlank(
        57,
        2,
        "Lawmakers voted to ____ before it became law.",
        "approve a bill",
        [
          { key: "a", label: "approve a bill" },
          { key: "b", label: "queue up" },
          { key: "c", label: "shut down" },
          { key: "d", label: "fall out" },
        ],
        "a",
      ),
    ],
  }),
  preUnit(58, {
    introVi: "Unit 58 tập trung biến đổi khí hậu và giải pháp phát triển bền vững. Bạn sẽ dùng được từ vựng môi trường phổ biến trong tin tức và thảo luận học thuật cơ bản.",
    structureSections: [
      { label: "Climate science basics", wordCount: 6 },
      { label: "Impacts and risks", wordCount: 6 },
      { label: "Solutions and policy", wordCount: 6 },
    ],
    collocationHtml: `${purple("carbon footprint")}, ${purple("renewable energy")} và ${purple("climate action")} là ba cụm trọng tâm.`,
    mistakeHtml: "Global warming là một phần của climate change; không phải mọi hiện tượng thời tiết bất thường đều giải thích bằng một ngày nóng.",
    principles: [
      {
        title: "Nắm mối liên hệ nguyên nhân - hậu quả",
        body: `${purple("greenhouse gas")} tăng dẫn tới ${purple("global warming")} và kéo theo nhiều rủi ro khí hậu.`,
        examples: [ex("Greenhouse gas emissions drive global warming.", "Phát thải khí nhà kính làm tăng nóng lên toàn cầu.")],
      },
      {
        title: "Mô tả tác động cụ thể bằng dữ liệu",
        body: `Các từ như ${purple("sea level rise")}, ${purple("drought")} và ${purple("flood")} nên đi kèm bối cảnh rõ.`,
        examples: [ex("Sea level rise threatens low coastal areas.", "Mực nước biển dâng đe dọa vùng ven biển thấp.")],
      },
      {
        title: "Nói về giải pháp dài hạn",
        body: `${purple("renewable energy")}, ${purple("electric vehicle")} và mục tiêu ${purple("net zero")} thường đi cùng nhau.`,
        examples: [ex("The city plans net zero transport by 2045.", "Thành phố đặt mục tiêu giao thông phát thải ròng bằng không vào năm 2045.")],
      },
    ],
    words: U58_WORDS,
    exercises: [
      mcq(
        58,
        1,
        "Từ nào chỉ lượng phát thải do cá nhân hoặc tổ chức tạo ra?",
        [
          { key: "a", label: "wind farm" },
          { key: "b", label: "carbon footprint" },
          { key: "c", label: "solar panel" },
          { key: "d", label: "sustainability" },
        ],
        "b",
      ),
      fillBlank(
        58,
        2,
        "Many countries invest in ____ like wind and solar.",
        "renewable energy",
        [
          { key: "a", label: "renewable energy" },
          { key: "b", label: "war crime" },
          { key: "c", label: "room service" },
          { key: "d", label: "editorial" },
        ],
        "a",
      ),
    ],
  }),
  preUnit(59, {
    introVi: "Unit 59 giới thiệu từ vựng về chiến tranh và bạo lực với cách diễn đạt trung tính, tôn trọng nạn nhân. Bạn sẽ đọc bản tin quốc tế chính xác và có trách nhiệm hơn.",
    structureSections: [
      { label: "War situation terms", wordCount: 6 },
      { label: "Human impact", wordCount: 6 },
      { label: "Peace and recovery", wordCount: 6 },
    ],
    collocationHtml: `${purple("ceasefire")}, ${purple("humanitarian aid")} và ${purple("peace talks")} là nhóm từ quan trọng khi nói về chấm dứt xung đột.`,
    mistakeHtml: "Casualty là thương vong nói chung, không đồng nghĩa hoàn toàn với death.",
    principles: [
      {
        title: "Ưu tiên ngôn ngữ trung tính, không kích động",
        body: `Dùng từ mô tả sự kiện như ${purple("conflict")} hoặc ${purple("violent attack")} thay vì ngôn ngữ cảm tính quá mức.`,
        examples: [ex("The report described the conflict carefully.", "Bản tin mô tả cuộc xung đột một cách thận trọng.")],
      },
      {
        title: "Nhấn mạnh tác động lên thường dân",
        body: `${purple("civilian")}, ${purple("refugee")} và ${purple("trauma")} giúp phản ánh hậu quả nhân đạo.`,
        examples: [ex("Many civilians were forced to evacuate.", "Nhiều thường dân buộc phải sơ tán.")],
      },
      {
        title: "Kết thúc xung đột cần cả đàm phán và tái thiết",
        body: `${purple("peace talks")} mở đường cho ${purple("ceasefire")} và quá trình ${purple("rebuild")}.`,
        examples: [ex("After the ceasefire, towns started to rebuild.", "Sau lệnh ngừng bắn, các thị trấn bắt đầu tái thiết.")],
      },
    ],
    words: U59_WORDS,
    exercises: [
      mcq(
        59,
        1,
        "Từ nào chỉ thỏa thuận ngừng bắn tạm thời?",
        [
          { key: "a", label: "frontline" },
          { key: "b", label: "ceasefire" },
          { key: "c", label: "weapon" },
          { key: "d", label: "hostage" },
        ],
        "b",
      ),
      fillBlank(
        59,
        2,
        "Relief teams delivered ____ to families in need.",
        "humanitarian aid",
        [
          { key: "a", label: "humanitarian aid" },
          { key: "b", label: "admission fee" },
          { key: "c", label: "tax reform" },
          { key: "d", label: "grind size" },
        ],
        "a",
      ),
    ],
  }),
  preUnit(60, {
    introVi: "Unit 60 tổng hợp từ vựng về thời gian: đúng giờ, hạn chót, trì hoãn và các mốc thời gian trong giao tiếp công việc. Đây là nền tảng để quản lý lịch trình hiệu quả bằng tiếng Anh.",
    structureSections: [
      { label: "Planning and deadlines", wordCount: 6 },
      { label: "Time expressions", wordCount: 6 },
      { label: "Long-term vs short-term", wordCount: 6 },
    ],
    collocationHtml: `${purple("meet a deadline")}, ${purple("in advance")} và ${purple("spare time")} là các cụm cực kỳ thực dụng trong đời sống.`,
    mistakeHtml: "Eventually không có nghĩa là cuối cùng trong một danh sách, mà là sau một quá trình/chờ đợi.",
    principles: [
      {
        title: "Lập lịch rõ ràng để giảm căng thẳng",
        body: `${purple("schedule")} và ${purple("timetable")} giúp bạn theo dõi việc theo khung giờ cụ thể.`,
        examples: [ex("I put all classes in my timetable.", "Tôi đưa toàn bộ lịch học vào thời khóa biểu.")],
      },
      {
        title: "Phân biệt từ chỉ tình trạng thời gian",
        body: `${purple("temporary")} và ${purple("permanent")} diễn tả độ dài khác nhau của một quyết định.`,
        examples: [ex("This delay is temporary, not permanent.", "Sự chậm trễ này là tạm thời, không phải lâu dài.")],
      },
      {
        title: "Dùng cụm chỉ thời điểm linh hoạt",
        body: `${purple("recently")}, ${purple("currently")} và ${purple("meanwhile")} giúp câu văn tự nhiên hơn khi kể tiến trình.`,
        examples: [ex("I recently changed jobs and currently work from home.", "Gần đây tôi đổi việc và hiện đang làm ở nhà.")],
      },
    ],
    words: U60_WORDS,
    exercises: [
      mcq(
        60,
        1,
        "Từ nào chỉ hạn chót phải hoàn thành công việc?",
        [
          { key: "a", label: "delay" },
          { key: "b", label: "deadline" },
          { key: "c", label: "time zone" },
          { key: "d", label: "meanwhile" },
        ],
        "b",
      ),
      fillBlank(
        60,
        2,
        "Please send the documents ____ so we can review them early.",
        "in advance",
        [
          { key: "a", label: "on time" },
          { key: "b", label: "eventually" },
          { key: "c", label: "in advance" },
          { key: "d", label: "lately" },
        ],
        "c",
      ),
    ],
  }),
];
